// Copyright 2013-2021 the openage authors. See copying.md for legal info.

// Warning: this file is a dummy file and was auto-generated by the v0.4.1 converter;
// its purpose is to keep the deprecated gamestate compilable and intact;
// these files keep only the minimum functionality and should not be changed;
// For details, see buildsystem/codegen.cmake and openage/codegen.


#include <cstdio>
#include <vector>
#include "blending_mode_dummy.h"
#include "error/error.h"
#include "util/strings.h"


namespace openage {
namespace gamedata {

constexpr size_t blending_mode::member_count;
int blending_mode::fill(const std::string &line) {
    std::vector<std::string> buf = openage::util::split_escape(
        line, ',', blending_mode::member_count
    );

    if (buf.size() != blending_mode::member_count) {
        throw openage::error::Error(
            ERR
            << "Tokenizing blending_mode led to "
            << buf.size()
            << " columns (expected "
            << blending_mode::member_count
            << ")!"
        );
    }

    if (sscanf(buf[0].c_str(), "%d", &this->blend_mode) != 1) { return 0; }

    return -1;
}

bool blending_mode::recurse(const openage::util::CSVCollection & /*storage*/, const std::string & /*basedir*/) {
    return true;
}

} // gamedata
} // openage
