// Copyright 2013-2021 the openage authors. See copying.md for legal info.

// Warning: this file is a dummy file and was auto-generated by the v0.4.1 converter;
// its purpose is to keep the deprecated gamestate compilable and intact;
// these files keep only the minimum functionality and should not be changed;
// For details, see buildsystem/codegen.cmake and openage/codegen.


#include <cstdio>
#include <vector>
#include "error/error.h"
#include "string_resource_dummy.h"
#include "util/strings.h"


namespace openage {
namespace gamedata {

constexpr size_t string_resource::member_count;
int string_resource::fill(const std::string &line) {
    std::vector<std::string> buf = openage::util::split_escape(
        line, ',', string_resource::member_count
    );

    if (buf.size() != string_resource::member_count) {
        throw openage::error::Error(
            ERR
            << "Tokenizing string_resource led to "
            << buf.size()
            << " columns (expected "
            << string_resource::member_count
            << ")!"
        );
    }

    if (sscanf(buf[0].c_str(), "%d", &this->id) != 1) { return 0; }
    this->lang = buf[1];
    this->text = buf[2];

    return -1;
}

bool string_resource::recurse(const openage::util::CSVCollection & /*storage*/, const std::string & /*basedir*/) {
    return true;
}

} // gamedata
} // openage
