# Copyright 2025-2025 the openage authors. See copying.md for legal info.

"""
Mappings of AoC upgrade IDs to their respective subprocessor functions.
"""

from ..upgrade_attribute_subprocessor import AoCUpgradeAttributeSubprocessor
from ..upgrade_resource_subprocessor import AoCUpgradeResourceSubprocessor

UPGRADE_ATTRIBUTE_FUNCS = {
    0: AoCUpgradeAttributeSubprocessor.hp_upgrade,
    1: AoCUpgradeAttributeSubprocessor.los_upgrade,
    2: AoCUpgradeAttributeSubprocessor.garrison_capacity_upgrade,
    3: AoCUpgradeAttributeSubprocessor.unit_size_x_upgrade,
    4: AoCUpgradeAttributeSubprocessor.unit_size_y_upgrade,
    5: AoCUpgradeAttributeSubprocessor.move_speed_upgrade,
    6: AoCUpgradeAttributeSubprocessor.rotation_speed_upgrade,
    8: AoCUpgradeAttributeSubprocessor.armor_upgrade,
    9: AoCUpgradeAttributeSubprocessor.attack_upgrade,
    10: AoCUpgradeAttributeSubprocessor.reload_time_upgrade,
    11: AoCUpgradeAttributeSubprocessor.accuracy_upgrade,
    12: AoCUpgradeAttributeSubprocessor.max_range_upgrade,
    13: AoCUpgradeAttributeSubprocessor.work_rate_upgrade,
    14: AoCUpgradeAttributeSubprocessor.carry_capacity_upgrade,
    16: AoCUpgradeAttributeSubprocessor.projectile_unit_upgrade,
    17: AoCUpgradeAttributeSubprocessor.graphics_angle_upgrade,
    18: AoCUpgradeAttributeSubprocessor.terrain_defense_upgrade,
    19: AoCUpgradeAttributeSubprocessor.ballistics_upgrade,
    20: AoCUpgradeAttributeSubprocessor.min_range_upgrade,
    21: AoCUpgradeAttributeSubprocessor.resource_storage_1_upgrade,
    22: AoCUpgradeAttributeSubprocessor.blast_radius_upgrade,
    23: AoCUpgradeAttributeSubprocessor.search_radius_upgrade,
    42: AoCUpgradeAttributeSubprocessor.standing_wonders_upgrade,
    46: AoCUpgradeAttributeSubprocessor.tribute_inefficiency_upgrade,
    48: AoCUpgradeAttributeSubprocessor.tc_available_upgrade,
    49: AoCUpgradeAttributeSubprocessor.gold_counter_upgrade,
    57: AoCUpgradeAttributeSubprocessor.kidnap_storage_upgrade,
    100: AoCUpgradeAttributeSubprocessor.resource_cost_upgrade,
    101: AoCUpgradeAttributeSubprocessor.creation_time_upgrade,
    102: AoCUpgradeAttributeSubprocessor.min_projectiles_upgrade,
    103: AoCUpgradeAttributeSubprocessor.cost_food_upgrade,
    104: AoCUpgradeAttributeSubprocessor.cost_wood_upgrade,
    105: AoCUpgradeAttributeSubprocessor.cost_gold_upgrade,
    106: AoCUpgradeAttributeSubprocessor.cost_stone_upgrade,
    107: AoCUpgradeAttributeSubprocessor.max_projectiles_upgrade,
    108: AoCUpgradeAttributeSubprocessor.garrison_heal_upgrade,
}

UPGRADE_RESOURCE_FUNCS = {
    4: AoCUpgradeResourceSubprocessor.starting_population_space_upgrade,
    27: AoCUpgradeResourceSubprocessor.monk_conversion_upgrade,
    28: AoCUpgradeResourceSubprocessor.building_conversion_upgrade,
    32: AoCUpgradeResourceSubprocessor.bonus_population_upgrade,
    35: AoCUpgradeResourceSubprocessor.faith_recharge_rate_upgrade,
    36: AoCUpgradeResourceSubprocessor.farm_food_upgrade,
    46: AoCUpgradeResourceSubprocessor.tribute_inefficiency_upgrade,
    47: AoCUpgradeResourceSubprocessor.gather_gold_efficiency_upgrade,
    50: AoCUpgradeResourceSubprocessor.reveal_ally_upgrade,
    77: AoCUpgradeResourceSubprocessor.conversion_resistance_upgrade,
    78: AoCUpgradeResourceSubprocessor.trade_penalty_upgrade,
    79: AoCUpgradeResourceSubprocessor.gather_stone_efficiency_upgrade,
    84: AoCUpgradeResourceSubprocessor.starting_villagers_upgrade,
    85: AoCUpgradeResourceSubprocessor.chinese_tech_discount_upgrade,
    86: AoCUpgradeResourceSubprocessor.research_time_upgrade,
    89: AoCUpgradeResourceSubprocessor.heal_rate_upgrade,
    90: AoCUpgradeResourceSubprocessor.heal_range_upgrade,
    91: AoCUpgradeResourceSubprocessor.starting_food_upgrade,
    92: AoCUpgradeResourceSubprocessor.starting_wood_upgrade,
    94: AoCUpgradeResourceSubprocessor.starting_gold_upgrade,
    96: AoCUpgradeResourceSubprocessor.berserk_heal_rate_upgrade,
    97: AoCUpgradeResourceSubprocessor.herding_dominance_upgrade,
    178: AoCUpgradeResourceSubprocessor.conversion_resistance_min_rounds_upgrade,
    179: AoCUpgradeResourceSubprocessor.conversion_resistance_max_rounds_upgrade,
    183: AoCUpgradeResourceSubprocessor.reveal_enemy_upgrade,
    189: AoCUpgradeResourceSubprocessor.gather_wood_efficiency_upgrade,
    190: AoCUpgradeResourceSubprocessor.gather_food_efficiency_upgrade,
    191: AoCUpgradeResourceSubprocessor.relic_gold_bonus_upgrade,
    192: AoCUpgradeResourceSubprocessor.heresy_upgrade,
    193: AoCUpgradeResourceSubprocessor.theocracy_upgrade,
    194: AoCUpgradeResourceSubprocessor.crenellations_upgrade,
    196: AoCUpgradeResourceSubprocessor.wonder_time_increase_upgrade,
    197: AoCUpgradeResourceSubprocessor.spies_discount_upgrade,
}
