#!/bin/bash
#source this script for helpers that simplify compiler invocations

PROJ_ROOT=$( cd "$( dirname "$0" )" && pwd )

function run_in_root() {
	(cd "$PROJ_ROOT/$1"; shift; $@)
}

function make() {
	run_in_root bin /usr/bin/make $@
}

function run() {
	run_in_root data ../bin/openage $@
}

function gdb() {
	run_in_root data /usr/bin/gdb ../bin/openage $@
}

function valgrind() {
	run_in_root data /usr/bin/valgrind --leak-check=full --track-origins=yes -v ../bin/openage $@
}

function rls() {
	run_in_root . mkdir -p bin
	run_in_root bin cmake -DCMAKE_BUILD_TYPE=Release .. $@
}

function dbg() {
	run_in_root . mkdir -p bin
	run_in_root bin cmake -DCMAKE_BUILD_TYPE=Debug .. $@
}
