# Copyright 2019-2019 the openage authors. See copying.md for legal info.

"""
Age of Empires games do not necessarily come with an english
translation. Therefore, we use the strings in this file to
figure out the names for a nyan object.
"""

# key: line_id; value: (nyan object name, filename prefix)
unit_line_lookups = {
    4: ("Archer", "archer"),
    5: ("HandCannoneer", "hand_cannoneer"),
    7: ("Skirmisher", "skirmisher"),
    8: ("Longbowman", "longbowman"),
    11: ("Mangudai", "mangudai"),
    13: ("FishingShip", "fishing_ship"),
    17: ("TradeCog", "trade_cog"),
    25: ("TeutonicKnight", "teutonic_knight"),
    35: ("Ram", "ram"),
    36: ("BombardCannon", "bombard_cannon"),
    38: ("Knight", "knight"),
    39: ("HorseArcher", "horse_archer"),
    40: ("Cataphract", "cataphract"),
    41: ("Huscarl", "huscarl"),
    46: ("Janissary", "janissary"),
    73: ("ChuKoNu", "chu_ko_nu"),
    74: ("Swordsman", "swordsman"),
    93: ("Spearman", "spearman"),
    118: ("Villager", "villager"),
    125: ("Monk", "monk"),
    128: ("TradeCart", "trade_cart"),
    232: ("WoadRaider", "woad_raider"),
    239: ("WarElephant", "war_elephant"),
    250: ("Longboat", "longboat"),
    279: ("Scorpion", "scorpion"),
    280: ("Mangonel", "mangonel"),
    281: ("ThrowingAxeman", "throwing_axeman"),
    282: ("Mameluke", "mameluke"),
    291: ("Samurai", "samurai"),
    329: ("CamelRider", "camel_rider"),
    331: ("Trebuchet", "trebuchet"),
    420: ("CannonGalleon", "cannon_galleon"),
    440: ("Petard", "petard"),
    448: ("LightCavalry", "light_cavalry"),
    528: ("DemolitionShip", "demo_ship"),
    529: ("FireTrireme", "fire_trireme"),
    539: ("Galley", "galley"),
    545: ("TransportShip", "transport_ship"),
    692: ("Berserk", "berserk"),
    725: ("JaguarWarrior", "haguar_warrior"),
    751: ("EagleWarrior", "eagle_warrior"),
    755: ("Tarkan", "tarkan"),
    763: ("PlumedArcher", "plumed_archer"),
    771: ("Conquistador", "conquistador"),
    775: ("Missionary", "missionary"),
    827: ("WarWaggon", "war_waggon"),
    831: ("TurtleShip", "turtle_ship"),
}

building_line_lookups = {
    12: ("Barracks", "barracks"),
    45: ("Harbor", "harbor"),
    49: ("SiegeWorkshop", "siege_workshop"),
    50: ("Farm", "farm"),
    68: ("Mill", "mill"),
    70: ("House", "house"),
    72: ("PalisadeWall", "palisade"),
    79: ("Tower", "tower"),
    82: ("Castle", "castle"),
    84: ("Market", "market"),
    87: ("ArcheryRange", "archery_range"),
    101: ("Stable", "stable"),
    103: ("Blacksmith", "blacksmith"),
    104: ("Monastery", "monastery"),
    117: ("StoneWall", "stone_wall"),
    199: ("FishingTrap", "fishing_trap"),
    209: ("University", "university"),
    236: ("BombardTower", "bombard_tower"),
    276: ("Wonder", "wonder"),
    487: ("StoneGate", "stone_gate"),
    562: ("LumberCamp", "lumber_camp"),
    584: ("MiningCamp", "mining_camp"),
    598: ("Outpost", "outpost"),
}

civ_group_lookups = {
    0: "Gaia",
    1: "Britons",
    2: "Franks",
    3: "Goths",
    4: "Teutons",
    5: "Japanese",
    6: "Chinese",
    7: "Byzantines",
    8: "Persians",
    9: "Saracens",
    10: "Turks",
    11: "Vikings",
    12: "Mongols",
    13: "Celts",
    14: "Spanish",
    15: "Aztecs",
    16: "Mayans",
    17: "Huns",
    18: "Koreans",
}

class_id_lookups = {
    0: "Archer",
    1: "Artifact",
    2: "TradeBoat",
    3: "BuildingMisc",
    4: "Villager",
    5: "OceanFish",
    6: "Infantry",
    7: "BerryBush",
    8: "StoneMine",
    9: "AnimalPrey",
    10: "AnimalPredator",
    11: "DeadOrProjectileOrBird",     # do not use this as GameEntityType
    12: "Cavalry",
    13: "SiegeWeapon",
    14: "Ambient",
    15: "Tree",
    18: "Monk",
    19: "TradecCart",
    20: "TransportShip",
    21: "FishingShip",
    22: "Warship",
    23: "Conquistador",
    27: "Wall",
    28: "Phalanx",
    29: "DomesticAnimal",
    30: "AmbientFlag",
    31: "DeepSeaFish",
    32: "GoldMine",
    33: "ShoreFish",
    34: "Cliff",
    35: "Petard",
    36: "CavalryArcher",
    37: "Doppelgaenger",
    38: "Bird",
    39: "Gate",
    40: "AmbientPile",
    41: "AmbientResourcePile",
    42: "Relic",
    43: "MonkWithRelic",            # should not be present in final modpack
    44: "HandConnoneer",
    45: "TwoHandedSwordsman",       # should not be present in final modpack (unused anyway)
    46: "Pikeman",                  # should not be present in final modpack (unused anyway)
    47: "CavalryScout",
    48: "OreMine",
    49: "Restockable",
    50: "Spearman",
    51: "Trebuchet",                # packed
    52: "Tower",
    53: "BoardingShip",
    54: "Trebuchet",                # unpacked
    55: "Scorpion",
    56: "Raider",
    57: "CavalryRaider",
    58: "Herdable",
    59: "King",
    61: "Horse",
}
