openage: openage::Unit Class Reference
openage::Unit Class Reference
A game object with current state represented by a stack of actions since this class represents both unit and building objects it may be better to name as GameObject.
#include <unit.h>
Public Member Functions
Unit (UnitContainer *c, id_t id)
virtual ~Unit ()
unit cleanup will delete terrain object
template<class T , typename ... Arg>
void make_location (Arg ... args)
constructs a new location for this unit replacing any existing locatio
void reset ()
removes all actions and abilities current attributes are kept
bool has_action () const
checks the entity has an action, if it has no action it should be removed from the game
bool accept_commands () const
true when the unit is alive and able to add new actions
bool is_own_unit (const Player &player)
checks whether the current player is the owner of this unit
UnitAction * top () const
returns the current action on top of the stack
UnitAction * before (const UnitAction *action) const
returns action under the passed action in the stack returns null if stack size is less than 2
bool update (time_nsec_t lastframe_duration)
update this object using the action currently on top of the stack
void draw (const Engine &engine)
draws this action by taking the graphic type of the top action the graphic is found from the current graphic set
void draw (TerrainObject *loc, const graphic_set &graphics, const Engine &engine)
an generalized draw function which is useful for drawing annexes
void draw (coord::phys3 draw_pos, std::shared_ptr< UnitTexture > graphic, unsigned int frame, const Engine &engine)
draws with a specific graphic and frame
void give_ability (std::shared_ptr< UnitAbility >)
adds an available ability to this unit this turns targeted objects into actions which are pushed onto the stack, eg.
UnitAbility * get_ability (ability_type type)
get ability with specified type, null if not available
void push_action (std::unique_ptr< UnitAction > action, bool force=false)
adds a new action on top of the action stack will be performed immediately
void secondary_action (std::unique_ptr< UnitAction > action)
adds a secondary action which is always updated
void add_attribute (std::shared_ptr< AttributeContainer > attr)
give a new attribute this this unit this is used to set things like color, hitpoints and speed
void add_attributes (const Attributes &attr)
Give new attributes to this unit.
void add_attributes (const Attributes &attr, bool shared, bool unshared)
Give new attributes to this unit.
bool has_attribute (attr_type type) const
returns whether attribute is available
template<attr_type T>
Attribute< T > & get_attribute ()
returns attribute based on templated value
std::shared_ptr< UnitAbility > queue_cmd (const Command &cmd)
queues a command to be applied to this unit on the next update
void stop_gather ()
removes all gather actions without calling their on_complete actions this cancels the gathering action completely
void stop_actions ()
removes all actions above and including the first interuptable action this will stop any of the units current moving or attacking actions a direct command from the user will invoke this function
void delete_unit ()
begins unit removal by popping some actions
UnitReference get_ref ()
get a reference which can check against the container to ensure this object still exists
UnitContainer * get_container () const
the container used when constructing this unit
std::string logsource_name () override
Returns the unit's name as the LogSource name.
Public Member Functions inherited from openage::log::LogSource
LogSource ()
virtual ~LogSource ()=default
void log (const message &msg)
Logs a message (get one via MSG(level)).
Public Attributes
const id_t id
this units unique id value
const UnitType * unit_type
type of this object, this is set by the the UnitType which was most recently applied to this unit
bool selected
should selection features be drawn
std::unique_ptr< TerrainObject > location
space on the map used by this unit null if the object is not yet placed or garrisoned
Attributes attributes
Unit attributes include color, hitpoints, speed, objects garrisoned etc contains 0 or 1 values for each type.
Public Attributes inherited from openage::log::LogSource
const size_t logger_id
Initialized during the LogSource constructor, guaranteed to be unique.
Private Member Functions
void apply_all_cmds ()
applies new commands as part of the units update process
void apply_cmd (std::shared_ptr< UnitAbility > ability, const Command &cmd)
applies one command using a chosen ability locks the command queue mutex while operating
void update_secondary (int64_t time_elapsed)
update all secondary actions
void erase_after (std::function< bool(std::unique_ptr< UnitAction > &)> func, bool run_completed=true)
erase from action specified by func to the end of the stack all actions erased will have the on_complete function called
Private Attributes
std::unordered_map< ability_type, std::shared_ptr< UnitAbility > > ability_available
ability available – actions that this entity can perform when controlled
std::vector< std::unique_ptr< UnitAction > > action_stack
action stack – top action determines graphic to be drawn
std::vector< std::unique_ptr< UnitAction > > action_secondary
secondary actions are always updated
std::queue< std::pair< std::shared_ptr< UnitAbility >, const Command > > command_queue
queue commands to be applied on the next update
std::mutex command_queue_lock
mutex controlling updates to the command queue
bool pop_destructables
pop any destructable actions on the next update cycle and prevent additional actions being added
UnitContainer * container
the container that updates this unit
Detailed Description
A game object with current state represented by a stack of actions since this class represents both unit and building objects it may be better to name as GameObject.
it is possible that abilities are not required here and they could be moved to selection controller – units only need the attributes
Definition at line 36 of file unit.h.
Constructor & Destructor Documentation
Unit()
openage::Unit::Unit (UnitContainer * c, id_t id)
Definition at line 19 of file unit.cpp.
     :
     id{id},
     unit_type{nullptr},
     selected{false},
     pop_destructables{false},
     container(c) {}
~Unit()
openage::Unit::~Unit () virtual
unit cleanup will delete terrain object
Definition at line 27 of file unit.cpp.
             {
     // remove any used location from the map
     if (this->location) {
         this->location->remove();
     }
 }
References location.
Member Function Documentation
accept_commands()
bool openage::Unit::accept_commands () const
true when the unit is alive and able to add new actions
Definition at line 45 of file unit.cpp.
{
     return (this->has_action() && this->top()->allow_control());
 }
References has_action(), and top().
Referenced by push_action().
add_attribute()
void openage::Unit::add_attribute (std::shared_ptr< AttributeContainer > attr)
give a new attribute this this unit this is used to set things like color, hitpoints and speed
Definition at line 246 of file unit.cpp.
{
     this->attributes.add(attr);
 }
References openage::Attributes::add(), and attributes.
Referenced by openage::ObjectProducer::initialise(), openage::MovableProducer::initialise(), openage::LivingProducer::initialise(), openage::BuildingProducer::initialise(), and openage::ProjectileProducer::initialise().
add_attributes() [1/2]
void openage::Unit::add_attributes (const Attributes & attr)
Give new attributes to this unit.
This is used to add the default attributes
Definition at line 250 of file unit.cpp.
{
     this->attributes.add_copies(attr);
 }
References openage::Attributes::add_copies(), and attributes.
Referenced by openage::UnitType::copy_attributes().
add_attributes() [2/2]
void openage::Unit::add_attributes (const Attributes & attr, bool shared, bool unshared)
Give new attributes to this unit.
If shared is false, shared attributes are ignored. If unshared is false, unshared attributes are ignored.
Definition at line 254 of file unit.cpp.
{
     this->attributes.add_copies(attr, shared, unshared);
 }
References openage::Attributes::add_copies(), and attributes.
apply_all_cmds()
void openage::Unit::apply_all_cmds () private
applies new commands as part of the units update process
Definition at line 134 of file unit.cpp.
{
     std::lock_guard<std::mutex> lock(this->command_queue_lock);
     while (!this->command_queue.empty()) {
         auto &action = this->command_queue.front();
         this->apply_cmd(action.first, action.second);
         this->command_queue.pop();
     }
 }
References apply_cmd(), command_queue, command_queue_lock, and lock.
Referenced by update().
apply_cmd()
void openage::Unit::apply_cmd (std::shared_ptr< UnitAbility > ability, const Command & cmd) private
applies one command using a chosen ability locks the command queue mutex while operating
Definition at line 144 of file unit.cpp.
{
     // if the interrupt flag is set, discard ongoing actions
     bool is_direct = cmd.has_flag(command_flag::interrupt);
     if (is_direct) {
         this->stop_actions();
     }
     if (ability->can_invoke(*this, cmd)) {
         ability->invoke(*this, cmd, is_direct);
     }
 }
References openage::Command::has_flag(), openage::interrupt, and stop_actions().
Referenced by apply_all_cmds().
before()
UnitAction * openage::Unit::before (const UnitAction * action) const
returns action under the passed action in the stack returns null if stack size is less than 2
Definition at line 60 of file unit.cpp.
{
     auto start = std::find_if(
         std::begin(this->action_stack),
         std::end(this->action_stack),
         [action](const std::unique_ptr<UnitAction> &a) {
             return action == a.get();
         });
     if (start != std::begin(this->action_stack) &&
         start != std::end(this->action_stack)) {
         return (*(start - 1)).get();
     }
     return nullptr;
 }
References action_stack.
delete_unit()
void openage::Unit::delete_unit ()
begins unit removal by popping some actions
this is the action that occurs when pressing the delete key which plays death sequence and does not remove instantly
Definition at line 278 of file unit.cpp.
{
     this->pop_destructables = true;
 }
References pop_destructables.
Referenced by openage::UnitSelection::kill_unit().
draw() [1/3]
void openage::Unit::draw (const Engine & engine)
draws this action by taking the graphic type of the top action the graphic is found from the current graphic set
this function should be used for most draw purposes
Definition at line 156 of file unit.cpp.
{
     // the top action decides the graphic type and action
     this->draw(this->location.get(), this->top()->current_graphics(), engine);
 }
References openage::UnitAction::current_graphics(), location, and top().
Referenced by draw(), openage::ObjectProducer::place(), and openage::BuildingProducer::place().
draw() [2/3]
void openage::Unit::draw (TerrainObject * loc, const graphic_set & graphics, const Engine & engine)
an generalized draw function which is useful for drawing annexes
Definition at line 163 of file unit.cpp.
{
     ENSURE(loc != nullptr, "there should always be a location for a placed unit");
     auto top_action = this->top();
     auto draw_graphic = top_action->type();
     if (grpc.count(draw_graphic) == 0) {
         this->log(MSG(warn) << "Graphic not available");
         return;
     }
     // the texture to draw with
     auto draw_texture = grpc.at(draw_graphic);
     if (!draw_texture) {
         this->log(MSG(warn) << "Graphic null");
         return;
     }
     // frame specified by the current action
     auto draw_frame = top_action->current_frame();
     this->draw(loc->pos.draw, draw_texture, draw_frame, engine);
     // draw a shadow if the graphic is available
     if (grpc.count(graphic_type::shadow) > 0) {
         auto draw_shadow = grpc.at(graphic_type::shadow);
         if (draw_shadow) {
             // position without height component
             // \todo terrain elevation
             coord::phys3 shadow_pos = loc->pos.draw;
             shadow_pos.up = 0;
             this->draw(shadow_pos, draw_shadow, draw_frame, engine);
         }
     }
     // draw debug details
     top_action->draw_debug(engine);
 }
References openage::tile_range::draw, draw(), ENSURE, openage::log::LogSource::log(), MSG, openage::TerrainObject::pos, openage::shadow, top(), and openage::log::warn().
draw() [3/3]
void openage::Unit::draw (coord::phys3 draw_pos, std::shared_ptr< UnitTexture > graphic, unsigned int frame, const Engine & engine)
draws with a specific graphic and frame
Definition at line 202 of file unit.cpp.
{
     // players color if available
     unsigned color = 0;
     if (this->has_attribute(attr_type::owner)) {
         auto &own_attr = this->get_attribute<attr_type::owner>();
         color = own_attr.player.color;
     }
     // check if object has a direction
     if (this->has_attribute(attr_type::direction)) {
         // directional textures
         auto &d_attr = this->get_attribute<attr_type::direction>();
         coord::phys3_delta draw_dir = d_attr.unit_dir;
         graphic->draw(engine.coord, draw_pos.to_camgame(engine.coord), draw_dir, frame, color);
     }
     else {
         graphic->draw(engine.coord, draw_pos.to_camgame(engine.coord), frame, color);
     }
 }
References openage::texturefont_shader::color, openage::Engine::coord, openage::direction, has_attribute(), openage::owner, and openage::coord::phys3::to_camgame().
erase_after()
void openage::Unit::erase_after (std::function< bool(std::unique_ptr< UnitAction > &)> func, bool run_completed = true) private
erase from action specified by func to the end of the stack all actions erased will have the on_complete function called
Parameters
run_completed usually each action has an on_complete() function called when it is removed but when run_completed is false this on_complete() function is not called for all popped actions
Definition at line 315 of file unit.cpp.
{
     auto position_it = std::find_if(
         std::begin(this->action_stack),
         std::end(this->action_stack),
         func);
     if (position_it != std::end(this->action_stack)) {
         auto completed_action = std::move(*position_it);
         // erase from the stack
         this->action_stack.erase(position_it, std::end(this->action_stack));
         // perform any completion actions
         if (run_completed) {
             completed_action->on_completion();
         }
     }
 }
References action_stack, and openage::move.
Referenced by stop_actions(), stop_gather(), and update().
get_ability()
UnitAbility * openage::Unit::get_ability (ability_type type)
get ability with specified type, null if not available
To invoke commands use the invoke function instead
Definition at line 228 of file unit.cpp.
{
     if (this->ability_available.count(type) > 0) {
         return this->ability_available[type].get();
     }
     return nullptr;
 }
References ability_available.
get_attribute()
template<attr_type T> Attribute<T>& openage::Unit::get_attribute () inline
returns attribute based on templated value
Definition at line 199 of file unit.h.
{
         return *reinterpret_cast<Attribute<T> *>(attributes.get(T).get());
         // \todo change to (templates errors)
         //return attributes.get<T>();
     }
References attributes, and openage::Attributes::get().
Referenced by openage::Player::active_unit_added(), openage::Player::active_unit_removed(), openage::UnitSelection::add_unit(), openage::AttackAction::attack(), openage::GarrisonAbility::can_invoke(), openage::UngarrisonAbility::can_invoke(), openage::TrainAbility::can_invoke(), openage::ResearchAbility::can_invoke(), openage::BuildAbility::can_invoke(), openage::complete_building(), openage::DeadAction::completed(), openage::FoundationAction::completed(), openage::IdleAction::completed(), openage::AttackAction::completed_in_range(), openage::HealAction::completed_in_range(), openage::UnitAction::damage_unit(), openage::UnitAction::face_towards(), openage::AttackAction::fire_projectile(), openage::UnitAction::get_attack_range(), openage::UnitAction::get_heal_range(), openage::UnitAbility::has_hitpoints(), openage::UnitAbility::has_resource(), openage::HealAction::heal(), openage::LivingProducer::initialise(), openage::MoveAction::initialise(), openage::MoveAbility::invoke(), openage::SetPointAbility::invoke(), openage::UnitAbility::is_ally(), openage::UnitAbility::is_damaged(), openage::UnitAbility::is_enemy(), openage::UnitAbility::is_same_player(), openage::Player::is_unit_pending(), openage::UnitAction::move_to(), openage::DeadAction::on_completion(), openage::FoundationAction::on_completion(), openage::BuildAction::on_completion(), openage::GatherAction::on_completion_in_range(), openage::UnitSelection::on_drawhud(), openage::Player::owns(), openage::ProjectileProducer::place(), openage::gameio::save_unit(), openage::UnitSelection::show_attributes(), openage::Attribute< attr_type::multitype >::switchType(), openage::DeadAction::update(), openage::IdleAction::update(), openage::MoveAction::update(), openage::UngarrisonAction::update(), openage::TrainAction::update(), openage::ProjectileAction::update(), openage::GarrisonAction::update_in_range(), openage::BuildAction::update_in_range(), openage::RepairAction::update_in_range(), and openage::GatherAction::update_in_range().
get_container()
UnitContainer * openage::Unit::get_container () const
the container used when constructing this unit
Definition at line 307 of file unit.cpp.
{
     return this->container;
 }
References container.
Referenced by openage::AttackAction::fire_projectile(), and openage::TrainAction::update().
get_ref()
UnitReference openage::Unit::get_ref ()
get a reference which can check against the container to ensure this object still exists
Definition at line 303 of file unit.cpp.
{
     return UnitReference(this->container, id, this);
 }
References container.
Referenced by openage::UnitSelection::add_unit(), openage::AttackAction::fire_projectile(), openage::MoveAbility::invoke(), openage::GarrisonAbility::invoke(), openage::BuildAbility::invoke(), openage::GatherAbility::invoke(), openage::AttackAbility::invoke(), openage::RepairAbility::invoke(), openage::HealAbility::invoke(), openage::ConvertAbility::invoke(), openage::GatherAction::nearest_dropsite(), and openage::GarrisonAction::update_in_range().
give_ability()
void openage::Unit::give_ability (std::shared_ptr< UnitAbility > ability)
adds an available ability to this unit this turns targeted objects into actions which are pushed onto the stack, eg.
targeting a relic may push a collect relic action
Definition at line 224 of file unit.cpp.
{
     this->ability_available.emplace(std::make_pair(ability->type(), ability));
 }
References ability_available.
Referenced by openage::ObjectProducer::initialise(), openage::LivingProducer::initialise(), openage::BuildingProducer::initialise(), and openage::NyanType::initialise().
has_action()
bool openage::Unit::has_action () const
checks the entity has an action, if it has no action it should be removed from the game
Returns
true if the entity currently has an action
Definition at line 41 of file unit.cpp.
{
     return !this->action_stack.empty();
 }
References action_stack.
Referenced by accept_commands(), and update().
has_attribute()
bool openage::Unit::has_attribute (attr_type type) const
returns whether attribute is available
Definition at line 258 of file unit.cpp.
{
     return this->attributes.has(type);
 }
References attributes, and openage::Attributes::has().
Referenced by openage::Player::active_unit_added(), openage::Player::active_unit_removed(), openage::UnitSelection::add_unit(), openage::SetPointAbility::can_invoke(), openage::GarrisonAbility::can_invoke(), openage::UngarrisonAbility::can_invoke(), openage::TrainAbility::can_invoke(), openage::ResearchAbility::can_invoke(), openage::BuildAbility::can_invoke(), openage::GatherAbility::can_invoke(), openage::AttackAbility::can_invoke(), openage::complete_building(), openage::DeadAction::completed(), openage::FoundationAction::completed(), openage::IdleAction::completed(), openage::UnitAction::damage_unit(), draw(), openage::UnitAction::face_towards(), openage::UnitAction::get_attack_range(), openage::UnitAction::get_heal_range(), openage::UnitSelection::get_unit_selection_type(), openage::UnitAbility::has_hitpoints(), openage::UnitAbility::has_resource(), openage::HealAction::heal(), openage::MovableProducer::initialise(), openage::MoveAction::initialise(), openage::MoveAbility::invoke(), openage::UnitAbility::is_ally(), openage::UnitAbility::is_damaged(), openage::UnitAbility::is_enemy(), openage::UnitAbility::is_same_player(), openage::Player::is_unit_pending(), openage::DeadAction::on_completion(), openage::FoundationAction::on_completion(), openage::UnitSelection::on_drawhud(), openage::Player::owns(), openage::gameio::save_unit(), openage::UnitSelection::show_attributes(), stop_actions(), openage::DeadAction::update(), openage::IdleAction::update(), openage::TrainAction::update(), openage::BuildAction::update_in_range(), and openage::GatherAction::update_in_range().
is_own_unit()
bool openage::Unit::is_own_unit (const Player & player)
checks whether the current player is the owner of this unit
Definition at line 49 of file unit.cpp.
{
     return player.owns(*this);
 }
References openage::Player::owns().
Referenced by openage::UnitSelection::get_unit_selection_type(), and openage::UnitSelection::kill_unit().
logsource_name()
std::string openage::Unit::logsource_name () override virtual
Returns the unit's name as the LogSource name.
Implements openage::log::LogSource.
Definition at line 311 of file unit.cpp.
{
     return "Unit " + std::to_string(this->id);
 }
References std::to_string().
make_location()
template<class T , typename ... Arg> void openage::Unit::make_location (Arg ... args) inline
constructs a new location for this unit replacing any existing locatio
uses same args as the location constructor except the first which will filled automatically
Definition at line 78 of file unit.h.
{
         // remove any existing location first
         if (this->location) {
             this->location->remove();
         }
         // since Unit is a friend of the location
         // make_shared will not work
         this->location = std::unique_ptr<T>(new T(*this, args ...));
     }
Referenced by openage::ObjectProducer::place(), openage::BuildingProducer::place(), openage::ProjectileProducer::place(), and openage::NyanType::place().
push_action()
void openage::Unit::push_action (std::unique_ptr< UnitAction > action, bool force = false)
adds a new action on top of the action stack will be performed immediately
Definition at line 235 of file unit.cpp.
{
     // unit not being deleted -- can control unit
     if (force || this->accept_commands()) {
         this->action_stack.push_back(std::move(action));
     }
 }
References accept_commands(), action_stack, and openage::move.
Referenced by openage::ObjectProducer::initialise(), openage::BuildingProducer::initialise(), openage::ProjectileProducer::initialise(), openage::NyanType::initialise(), openage::MoveAbility::invoke(), openage::GarrisonAbility::invoke(), openage::TrainAbility::invoke(), openage::ResearchAbility::invoke(), openage::BuildAbility::invoke(), openage::GatherAbility::invoke(), openage::AttackAbility::invoke(), openage::RepairAbility::invoke(), openage::HealAbility::invoke(), openage::ConvertAbility::invoke(), and openage::FoundationAction::on_completion().
queue_cmd()
std::shared_ptr< UnitAbility > openage::Unit::queue_cmd (const Command & cmd)
queues a command to be applied to this unit on the next update
Returns
the ability which will apply the command if an action was created otherwise nullptr is returned when no ability can handle the command
Definition at line 262 of file unit.cpp.
{
     std::lock_guard<std::mutex> lock(this->command_queue_lock);
     // following the specified ability priority
     // find suitable ability for this target if available
     for (auto &ability : ability_priority) {
         auto pair = this->ability_available.find(ability);
         if (pair != this->ability_available.end() &&
             cmd.ability()[static_cast<int>(pair->first)] && pair->second->can_invoke(*this, cmd)) {
             command_queue.push(std::make_pair(pair->second, cmd));
             return pair->second;
         }
     }
     return nullptr;
 }
References openage::Command::ability(), ability_available, openage::ability_priority, command_queue, command_queue_lock, and lock.
Referenced by openage::UnitAction::move_to(), openage::BuildAction::on_completion(), openage::GatherAction::on_completion_in_range(), openage::IdleAction::update(), and openage::GatherAction::update_in_range().
reset()
void openage::Unit::reset ()
removes all actions and abilities current attributes are kept
Definition at line 35 of file unit.cpp.
                  {
     this->ability_available.clear();
     this->action_stack.clear();
     this->pop_destructables = false;
 }
References ability_available, action_stack, and pop_destructables.
Referenced by openage::ObjectProducer::initialise(), and openage::NyanType::initialise().
secondary_action()
void openage::Unit::secondary_action (std::unique_ptr< UnitAction > action)
adds a secondary action which is always updated
Definition at line 242 of file unit.cpp.
{
     this->action_secondary.push_back(std::move(action));
 }
References action_secondary, and openage::move.
Referenced by openage::UngarrisonAbility::invoke().
stop_actions()
void openage::Unit::stop_actions ()
removes all actions above and including the first interuptable action this will stop any of the units current moving or attacking actions a direct command from the user will invoke this function
Definition at line 289 of file unit.cpp.
{
     // work around for workers continuing to work after retasking
     if (this->has_attribute(attr_type::worker)) {
         this->stop_gather();
     }
     // discard all interruptible tasks
     this->erase_after(
         [](std::unique_ptr<UnitAction> &e) {
             return e->allow_interupt();
         });
 }
References erase_after(), has_attribute(), stop_gather(), and openage::worker.
Referenced by apply_cmd().
stop_gather()
void openage::Unit::stop_gather ()
removes all gather actions without calling their on_complete actions this cancels the gathering action completely
Definition at line 282 of file unit.cpp.
{
     this->erase_after(
         [](std::unique_ptr<UnitAction> &e) {
             return e->name() == "gather";
         }, false);
 }
References erase_after().
Referenced by stop_actions().
top()
UnitAction * openage::Unit::top () const
returns the current action on top of the stack
Definition at line 53 of file unit.cpp.
{
     if (this->action_stack.empty()) {
         throw Error{MSG(err) << "Unit stack empty - no top action exists"};
     }
     return this->action_stack.back().get();
 }
References action_stack, openage::log::err(), and MSG.
Referenced by accept_commands(), draw(), openage::UnitSelection::show_attributes(), and update().
update()
bool openage::Unit::update (time_nsec_t lastframe_duration)
update this object using the action currently on top of the stack
Definition at line 75 of file unit.cpp.
{
     // if unit is not on the map then do nothing
     if (!this->location) {
         return true;
     }
     // unit is dead (not player controlled)
     if (this->pop_destructables) {
         this->erase_after(
             [](std::unique_ptr<UnitAction> &e) {
                 return e->allow_interupt() || e->allow_control();
             }, false);
     }
     /*
      * the active action is on top
      */
     if (this->has_action()) {
         // \todo change the entire unit action timing
         //       to a higher resolution like nsecs or usecs.
         // time as float, in milliseconds.
         auto time_elapsed = lastframe_duration / 1e6;
         this->top()->update(time_elapsed);
         // the top primary action specifies whether
         // secondary actions are updated
         if (this->top()->allow_control()) {
             this->update_secondary(time_elapsed);
         }
         // check completion of all primary actions,
         // pop completed actions and anything above
         this->erase_after(
             [](std::unique_ptr<UnitAction> &e) {
                 return e->completed();
             });
     }
     // apply new queued commands
     this->apply_all_cmds();
     return true;
 }
References apply_all_cmds(), erase_after(), has_action(), location, pop_destructables, top(), openage::UnitAction::update(), and update_secondary().
update_secondary()
void openage::Unit::update_secondary (int64_t time_elapsed) private
update all secondary actions
Definition at line 122 of file unit.cpp.
{
     // update secondary actions and remove when completed
     auto position_it = std::remove_if(
         std::begin(this->action_secondary),
         std::end(this->action_secondary),
         [time_elapsed](std::unique_ptr<UnitAction> &action) {
             action->update(time_elapsed);
             return action->completed();
         });
     this->action_secondary.erase(position_it, std::end(this->action_secondary));
 }
References action_secondary.
Referenced by update().
Member Data Documentation
ability_available
std::unordered_map<ability_type, std::shared_ptr<UnitAbility> > openage::Unit::ability_available private
ability available – actions that this entity can perform when controlled
Definition at line 261 of file unit.h.
Referenced by get_ability(), give_ability(), queue_cmd(), and reset().
action_secondary
std::vector<std::unique_ptr<UnitAction> > openage::Unit::action_secondary private
secondary actions are always updated
Definition at line 273 of file unit.h.
Referenced by secondary_action(), and update_secondary().
action_stack
std::vector<std::unique_ptr<UnitAction> > openage::Unit::action_stack private
action stack – top action determines graphic to be drawn
Definition at line 267 of file unit.h.
Referenced by before(), erase_after(), has_action(), push_action(), reset(), and top().
attributes
Attributes openage::Unit::attributes
Unit attributes include color, hitpoints, speed, objects garrisoned etc contains 0 or 1 values for each type.
Definition at line 254 of file unit.h.
Referenced by add_attribute(), add_attributes(), get_attribute(), has_attribute(), and openage::UnitType::reinitialise().
command_queue
std::queue<std::pair<std::shared_ptr<UnitAbility>, const Command> > openage::Unit::command_queue private
queue commands to be applied on the next update
Definition at line 279 of file unit.h.
Referenced by apply_all_cmds(), and queue_cmd().
command_queue_lock
std::mutex openage::Unit::command_queue_lock private
mutex controlling updates to the command queue
Definition at line 284 of file unit.h.
Referenced by apply_all_cmds(), and queue_cmd().
container
UnitContainer* openage::Unit::container private
the container that updates this unit
Definition at line 296 of file unit.h.
Referenced by get_container(), and get_ref().
id
const id_t openage::Unit::id
this units unique id value
Definition at line 48 of file unit.h.
Referenced by openage::UnitSelection::add_unit(), openage::UnitSelection::remove_unit(), and openage::UnitSelection::toggle_unit().
location
std::unique_ptr<TerrainObject> openage::Unit::location
space on the map used by this unit null if the object is not yet placed or garrisoned
Todo:
make private field
Definition at line 68 of file unit.h.
Referenced by openage::UnitAction::adjacent_range(), openage::AttackAction::attack(), openage::MoveAbility::can_invoke(), openage::GarrisonAbility::can_invoke(), openage::BuildAbility::can_invoke(), openage::GatherAbility::can_invoke(), openage::AttackAbility::can_invoke(), openage::RepairAbility::can_invoke(), openage::HealAbility::can_invoke(), openage::ConvertAbility::can_invoke(), openage::complete_building(), openage::TargetAction::completed(), openage::ProjectileAction::completed(), draw(), openage::UnitAction::face_towards(), openage::AttackAction::fire_projectile(), openage::IdleAction::IdleAction(), openage::BuildingProducer::initialise(), openage::MoveAbility::invoke(), openage::BuildingProducer::make_annex(), openage::TargetAction::on_completion(), openage::BuildAction::on_completion(), openage::GatherAction::on_completion_in_range(), openage::UnitSelection::on_drawhud(), openage::ObjectProducer::place(), openage::BuildingProducer::place(), openage::ProjectileProducer::place(), openage::NyanType::place(), openage::gameio::save_unit(), openage::MoveAction::set_distance(), openage::MoveAction::set_path(), update(), openage::FoundationAction::update(), openage::IdleAction::update(), openage::MoveAction::update(), openage::TrainAction::update(), openage::ProjectileAction::update(), openage::TargetAction::update_distance(), openage::GarrisonAction::update_in_range(), openage::BuildAction::update_in_range(), and ~Unit().
pop_destructables
bool openage::Unit::pop_destructables private
pop any destructable actions on the next update cycle and prevent additional actions being added
Definition at line 291 of file unit.h.
Referenced by delete_unit(), reset(), and update().
selected
bool openage::Unit::selected
should selection features be drawn
Todo:
should be a pointer to selection to be updated when unit is removed, or null if not selected
Definition at line 61 of file unit.h.
Referenced by openage::UnitSelection::add_unit(), openage::ObjectProducer::place(), openage::BuildingProducer::place(), and openage::UnitSelection::remove_unit().
unit_type
const UnitType* openage::Unit::unit_type
type of this object, this is set by the the UnitType which was most recently applied to this unit
Definition at line 54 of file unit.h.
Referenced by openage::Player::active_unit_added(), openage::Player::active_unit_removed(), openage::UnitAction::current_graphics(), openage::ObjectProducer::initialise(), openage::BuildingProducer::initialise(), openage::ProjectileProducer::initialise(), openage::NyanType::initialise(), openage::Player::killed_unit(), openage::gameio::save_unit(), and openage::UnitSelection::show_attributes().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/unit.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/unit.cpp