openage: openage::ResourceCost Class Reference
openage::ResourceCost Class Reference
#include <cost.h>
Public Member Functions
ResourceCost ()
ResourceCost (const ResourceBundle &resources)
ResourceCost (cost_type type, const ResourceBundle &multiplier)
virtual ~ResourceCost ()
void set (cost_type type, const ResourceBundle &multiplier)
const ResourceBundle get (const Player &player) const
Private Attributes
cost_type type
ResourceBundle resources
Detailed Description
A container for a constant or dynamic ResourceBundle representing the cost.
Definition at line 28 of file cost.h.
Constructor & Destructor Documentation
ResourceCost() [1/3]
openage::ResourceCost::ResourceCost ()
Constant zero cost
Definition at line 9 of file cost.cpp.
     :
     type{cost_type::constant},
     resources{} {}
References openage::constant.
ResourceCost() [2/3]
openage::ResourceCost::ResourceCost (const ResourceBundle & resources)
Constant cost
Definition at line 14 of file cost.cpp.
     :
     type{cost_type::constant},
     resources{} {
     this->resources.set(resources);
 }
References openage::constant.
ResourceCost() [3/3]
openage::ResourceCost::ResourceCost (cost_type type, const ResourceBundle & multiplier)
Dynamic cost
Definition at line 21 of file cost.cpp.
     :
     type{type},
     resources{} {
     this->resources.set(multiplier);
 }
References type.
~ResourceCost()
openage::ResourceCost::~ResourceCost () virtual
Definition at line 28 of file cost.cpp.
{
 }
Member Function Documentation
get()
const ResourceBundle openage::ResourceCost::get (const Player & player) const
Returns the cost.
Definition at line 36 of file cost.cpp.
{
     if (type == cost_type::constant) {
         return resources;
     }
     // calculate dynamic cost
     ResourceBundle resources = this->resources.clone();
     if (type == cost_type::workforce) {
         resources *= player.get_workforce_count();
     }
     return resources;
 }
References openage::ResourceBundle::clone(), openage::constant, openage::Player::get_workforce_count(), resources, type, and openage::workforce.
Referenced by openage::Player::active_unit_added(), openage::Player::active_unit_removed(), openage::Player::can_make(), openage::Player::killed_unit(), and openage::ActionMode::place_selection().
set()
void openage::ResourceCost::set (cost_type type, const ResourceBundle & multiplier)
Definition at line 31 of file cost.cpp.
{
     this->type = type;
     this->resources.set(resources);
 }
References resources, openage::ResourceBundle::set(), and type.
Member Data Documentation
resources
ResourceBundle openage::ResourceCost::resources private
Definition at line 59 of file cost.h.
Referenced by get(), and set().
type
cost_type openage::ResourceCost::type private
Definition at line 57 of file cost.h.
Referenced by get(), ResourceCost(), and set().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gamestate/cost.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gamestate/cost.cpp