openage: openage::GameSpec Class Reference
openage::GameSpec Class Reference
#include <game_spec.h>
Public Member Functions
GameSpec (AssetManager *am)
virtual ~GameSpec ()
bool initialize ()
bool load_complete () const
terrain_meta * get_terrain_meta ()
index_t get_slp_graphic (index_t slp)
Texture * get_texture (index_t graphic_id) const
Texture * get_texture (const std::string &file_name, bool use_metafile=true) const
std::shared_ptr< UnitTexture > get_unit_texture (index_t graphic_id) const
const Sound * get_sound (index_t sound_id) const
const gamedata::graphic * get_graphic_data (index_t grp_id) const
std::vector< const gamedata::unit_command * > get_command_data (index_t unit_id) const
std::string get_civ_name (int civ_id) const
void create_unit_types (unit_meta_list &objects, int civ_id) const
AssetManager * get_asset_manager () const
Private Member Functions
bool valid_graphic_id (index_t) const
void create_abilities (const gamedata::empiresdat &gamedata)
void load_building (const gamedata::building_unit &, unit_meta_list &) const
void load_living (const gamedata::living_unit &, unit_meta_list &) const
void load_object (const gamedata::unit_object &, unit_meta_list &) const
void load_missile (const gamedata::missile_unit &, unit_meta_list &) const
void load_terrain (const gamedata::empiresdat &gamedata)
void on_gamedata_loaded (const gamedata::empiresdat &gamedata)
Private Attributes
AssetManager * assetmanager
std::vector< gamedata::empiresdat > gamedata
terrain_meta terrain_data
std::unordered_map< index_t, index_t > slp_to_graphic
std::unordered_map< index_t, const gamedata::graphic * > graphics
std::unordered_map< index_t, std::vector< const gamedata::unit_command * > > commands
std::unordered_map< index_t, std::shared_ptr< UnitTexture > > unit_textures
std::unordered_map< index_t, Sound > available_sounds
bool gamedata_loaded
Detailed Description
GameSpec gives a collection of all game elements this currently includes unit types and terrain types This provides a system which can easily allow game modding
uses the AssetManager to gather graphic data, composite textures and sounds.
all types are sorted and stored by id values, each data object is referenced by a type and id pair
dealing directly with files done by asset manager
Todo:
should the audio loading should be moved there?
Definition at line 72 of file game_spec.h.
Constructor & Destructor Documentation
GameSpec()
openage::GameSpec::GameSpec (AssetManager * am)
Definition at line 25 of file game_spec.cpp.
     :
     assetmanager{am},
     gamedata_loaded{false} {
 }
~GameSpec()
openage::GameSpec::~GameSpec () virtual
Definition at line 31 of file game_spec.cpp.
 {}
Member Function Documentation
create_abilities()
void openage::GameSpec::create_abilities (const gamedata::empiresdat & gamedata) private
create unit abilities from game data
Definition at line 404 of file game_spec.cpp.
{
     // use game data unit commands
     int headers =  gamedata.unit_headers.data.size();
     int total = 0;
     // it seems the index of the header indicates the unit
     for (int i = 0; i < headers; ++i) {
         // init unit command vector
         std::vector<const gamedata::unit_command *> list;
         // add each element
         auto &head = gamedata.unit_headers.data[i];
         for (auto &cmd : head.unit_commands.data) {
             total++;
             // commands either have a class id or a unit id
             // log::dbg("unit command %d %d -> class %d, unit %d, resource %d", i, cmd.id, cmd.class_id, cmd.unit_id, cmd.resource_in);
             list.push_back(&cmd);
         }
         // insert to command map
         this->commands[i] = list;
     }
 }
References commands, gamedata, and openage::py::list().
Referenced by on_gamedata_loaded().
create_unit_types()
void openage::GameSpec::create_unit_types (unit_meta_list & objects, int civ_id) const
makes initial unit types for a particular civ id
Definition at line 155 of file game_spec.cpp.
{
     if (!this->load_complete()) {
         return;
     }
     // create projectile types first
     for (auto &obj : this->gamedata[0].civs.data[civ_id].units.missile.data) {
         this->load_missile(obj, objects);
     }
     // create object unit types
     for (auto &obj : this->gamedata[0].civs.data[civ_id].units.object.data) {
         this->load_object(obj, objects);
     }
     // create dead unit types
     for (auto &unit : this->gamedata[0].civs.data[civ_id].units.moving.data) {
         this->load_object(unit, objects);
     }
     // create living unit types
     for (auto &unit : this->gamedata[0].civs.data[civ_id].units.living.data) {
         this->load_living(unit, objects);
     }
     // create building unit types
     for (auto &building : this->gamedata[0].civs.data[civ_id].units.building.data) {
         this->load_building(building, objects);
     }
 }
References openage::building, gamedata, load_building(), load_complete(), load_living(), load_missile(), and load_object().
Referenced by openage::Civilisation::initialise_unit_types().
get_asset_manager()
AssetManager * openage::GameSpec::get_asset_manager () const
Return the asset manager used for loading resources of this game specification.
Definition at line 187 of file game_spec.cpp.
{
     return this->assetmanager;
 }
References assetmanager.
Referenced by openage::Sound::play().
get_civ_name()
std::string openage::GameSpec::get_civ_name (int civ_id) const
returns the name of a civ by index
Definition at line 151 of file game_spec.cpp.
{
     return this->gamedata[0].civs.data[civ_id].name;
 }
References gamedata.
get_command_data()
std::vector< const gamedata::unit_command * > openage::GameSpec::get_command_data (index_t unit_id) const
get available commands for a unit id nyan will have to replace this somehow
Definition at line 144 of file game_spec.cpp.
{
     if (this->commands.count(unit_id) == 0) {
         return std::vector<const gamedata::unit_command *>(); // empty vector
     }
     return this->commands.at(unit_id);
 }
References commands.
get_graphic_data()
const gamedata::graphic * openage::GameSpec::get_graphic_data (index_t grp_id) const
gamedata for a graphic nyan will have to replace this somehow
Definition at line 136 of file game_spec.cpp.
{
     if (this->graphics.count(grp_id) == 0) {
         log::log(MSG(dbg) << "  -> ignoring grp_id: " << grp_id);
         return nullptr;
     }
     return this->graphics.at(grp_id);
 }
References openage::log::dbg(), graphics, openage::log::log(), and MSG.
Referenced by openage::UnitTexture::initialise(), and openage::UnitTexture::UnitTexture().
get_slp_graphic()
index_t openage::GameSpec::get_slp_graphic (index_t slp)
reverse lookup of slp
Definition at line 87 of file game_spec.cpp.
{
     return this->slp_to_graphic[slp];
 }
References slp_to_graphic.
get_sound()
const Sound * openage::GameSpec::get_sound (index_t sound_id) const
get sound by sound id
Definition at line 125 of file game_spec.cpp.
{
     if (this->available_sounds.count(sound_id) == 0) {
         if (sound_id > 0) {
             log::log(MSG(dbg) << "  -> ignoring sound_id: " << sound_id);
         }
         return nullptr;
     }
     return &this->available_sounds.at(sound_id);
 }
References available_sounds, openage::log::dbg(), openage::log::log(), and MSG.
Referenced by openage::UnitTexture::initialise(), and openage::MovableProducer::MovableProducer().
get_terrain_meta()
terrain_meta * openage::GameSpec::get_terrain_meta ()
return data used for constructing terrain objects
Definition at line 83 of file game_spec.cpp.
{
     return &this->terrain_data;
 }
References terrain_data.
get_texture() [1/2]
Texture * openage::GameSpec::get_texture (index_t graphic_id) const
lookup using a texture id, this specifically avoids returning the missing placeholder texture
Definition at line 91 of file game_spec.cpp.
{
     if (graphic_id <= 0 || this->graphics.count(graphic_id) == 0) {
         log::log(MSG(dbg) << "  -> ignoring graphics_id: " << graphic_id);
         return nullptr;
     }
     auto g = this->graphics.at(graphic_id);
     int slp_id = g->slp_id;
     if (slp_id <= 0) {
         log::log(MSG(dbg) << "  -> ignoring negative slp_id: " << slp_id);
         return nullptr;
     }
     log::log(MSG(dbg) << "   slp id/name: " << slp_id << " " << g->name);
     std::string tex_fname = util::sformat("converted/graphics/%d.slp.png", slp_id);
     return this->get_texture(tex_fname, true);
 }
References openage::log::dbg(), graphics, openage::log::log(), MSG, and openage::util::sformat().
Referenced by openage::UnitTexture::initialise().
get_texture() [2/2]
Texture * openage::GameSpec::get_texture (const std::string & file_name, bool use_metafile = true) const
lookup using a texture file name
Definition at line 110 of file game_spec.cpp.
{
     // return nullptr if the texture wasn't found (3rd param)
     return this->assetmanager->get_texture(file_name, use_metafile, true);
 }
References assetmanager, and openage::AssetManager::get_texture().
get_unit_texture()
std::shared_ptr< UnitTexture > openage::GameSpec::get_unit_texture (index_t graphic_id) const
get unit texture by graphic id – this is an directional texture which also includes graphic deltas
Definition at line 115 of file game_spec.cpp.
{
     if (this->unit_textures.count(unit_id) == 0) {
         if (unit_id > 0) {
             log::log(MSG(dbg) << "  -> ignoring unit_id: " << unit_id);
         }
         return nullptr;
     }
     return this->unit_textures.at(unit_id);
 }
References openage::log::dbg(), openage::log::log(), MSG, and unit_textures.
initialize()
bool openage::GameSpec::initialize ()
perform the main loading job. this loads all the data into the storage.
Definition at line 34 of file game_spec.cpp.
{
     util::Timer load_timer;
     load_timer.start();
     const util::Path &asset_dir = this->assetmanager->get_asset_dir();
     log::log(MSG(info) << "Loading game specification files...");
     std::vector<gamedata::string_resource> string_resources = util::read_csv_file<gamedata::string_resource>(
         asset_dir["converted/string_resources.docx"]
     );
     try {
         // read the packed csv file
         util::CSVCollection raw_gamedata{
             asset_dir["converted/gamedata/gamedata.docx"]
         };
         // parse the original game description files
         this->gamedata = raw_gamedata.read<gamedata::empiresdat>(
             "gamedata-empiresdat.docx"
         );
         this->load_terrain(this->gamedata[0]);
         // process and load the game description files
         this->on_gamedata_loaded(this->gamedata[0]);
         this->gamedata_loaded = true;
     }
     catch (Error &exc) {
         // rethrow allmighty openage exceptions
         throw;
     }
     catch (std::exception &exc) {
         // unfortunately we have no idea of the std::exception backtrace
         throw Error{ERR << "gamedata could not be loaded: "
                         << util::demangle(typeid(exc).name())
                         << ": "<< exc.what()};
     }
     log::log(MSG(info).fmt("Loading time  [data]: %5.3f s",
                            load_timer.getval() / 1e9));
     return true;
 }
References assetmanager, openage::util::demangle(), ERR, gamedata, gamedata_loaded, openage::AssetManager::get_asset_dir(), openage::util::Timer::getval(), openage::log::info(), load_terrain(), openage::log::log(), MSG, on_gamedata_loaded(), and openage::util::Timer::start().
load_building()
void openage::GameSpec::load_building (const gamedata::building_unit & building, unit_meta_list & list) const private
loads required assets to construct a buildings. adds to the type list if the object can be created safely.
Definition at line 282 of file game_spec.cpp.
{
     // check graphics
     if (this->valid_graphic_id(building.graphic_standing0)) {
         auto meta_type = std::make_shared<UnitTypeMeta>("Building", building.id0, [this, &building](const Player &owner) {
             return std::make_shared<BuildingProducer>(owner, *this, &building);
         });
         list.emplace_back(meta_type);
     }
 }
References openage::building, openage::py::list(), openage::owner, and valid_graphic_id().
Referenced by create_unit_types().
load_complete()
bool openage::GameSpec::load_complete () const
Check if loading has been completed, a load percent would be nice
Definition at line 79 of file game_spec.cpp.
{
     return this->gamedata_loaded;
 }
References gamedata_loaded.
Referenced by create_unit_types().
load_living()
void openage::GameSpec::load_living (const gamedata::living_unit & unit, unit_meta_list & list) const private
loads assets for living things.
Definition at line 293 of file game_spec.cpp.
{
     // check graphics
     if (this->valid_graphic_id(unit.dying_graphic) &&
         this->valid_graphic_id(unit.graphic_standing0) &&
         this->valid_graphic_id(unit.walking_graphics0)) {
         auto meta_type = std::make_shared<UnitTypeMeta>("Living", unit.id0, [this, &unit](const Player &owner) {
             return std::make_shared<LivingProducer>(owner, *this, &unit);
         });
         list.emplace_back(meta_type);
     }
 }
References openage::py::list(), openage::owner, and valid_graphic_id().
Referenced by create_unit_types().
load_missile()
void openage::GameSpec::load_missile (const gamedata::missile_unit & proj, unit_meta_list & list) const private
load missile assets.
Definition at line 317 of file game_spec.cpp.
{
     // check graphics
     if (this->valid_graphic_id(proj.graphic_standing0)) {
         auto meta_type = std::make_shared<UnitTypeMeta>("Projectile", proj.id0, [this, &proj](const Player &owner) {
             return std::make_shared<ProjectileProducer>(owner, *this, &proj);
         });
         list.emplace_back(meta_type);
     }
 }
References openage::py::list(), openage::owner, and valid_graphic_id().
Referenced by create_unit_types().
load_object()
void openage::GameSpec::load_object (const gamedata::unit_object & object, unit_meta_list & list) const private
load assets for other game objects (not building and living).
Definition at line 306 of file game_spec.cpp.
{
     // check graphics
     if (this->valid_graphic_id(object.graphic_standing0)) {
         auto meta_type = std::make_shared<UnitTypeMeta>("Object", object.id0, [this, &object](const Player &owner) {
             return std::make_shared<ObjectProducer>(owner, *this, &object);
         });
         list.emplace_back(meta_type);
     }
 }
References openage::py::list(), openage::owner, and valid_graphic_id().
Referenced by create_unit_types().
load_terrain()
void openage::GameSpec::load_terrain (const gamedata::empiresdat & gamedata) private
fill in the terrain_data attribute of this
Definition at line 329 of file game_spec.cpp.
{
     // fetch blending modes
     util::Path convert_dir = this->assetmanager->get_asset_dir()["converted"];
     std::vector<gamedata::blending_mode> blending_meta = util::read_csv_file<gamedata::blending_mode>(
         convert_dir["blending_modes.docx"]
     );
     // copy the terrain metainformation
     std::vector<gamedata::terrain_type> terrain_meta = gamedata.terrains.data;
     // remove any disabled textures
     terrain_meta.erase(
         std::remove_if(
             terrain_meta.begin(),
             terrain_meta.end(),
             [] (const gamedata::terrain_type &t) {
                 return not t.enabled;
             }
         ),
         terrain_meta.end()
     );
     // result attributes
     this->terrain_data.terrain_id_count         = terrain_meta.size();
     this->terrain_data.blendmode_count          = blending_meta.size();
     this->terrain_data.textures.resize(terrain_data.terrain_id_count);
     this->terrain_data.blending_masks.reserve(terrain_data.blendmode_count);
     this->terrain_data.terrain_id_priority_map  = std::make_unique<int[]>(
         this->terrain_data.terrain_id_count
     );
     this->terrain_data.terrain_id_blendmode_map = std::make_unique<int[]>(
         this->terrain_data.terrain_id_count
     );
     this->terrain_data.influences_buf           = std::make_unique<struct influence[]>(
         this->terrain_data.terrain_id_count
     );
     log::log(MSG(dbg) << "Terrain prefs: " <<
         "tiletypes=" << terrain_data.terrain_id_count << ", "
         "blendmodes=" << terrain_data.blendmode_count);
     // create tile textures (snow, ice, grass, whatever)
     for (size_t terrain_id = 0;
          terrain_id < terrain_data.terrain_id_count;
          terrain_id++) {
         auto line = &terrain_meta[terrain_id];
         // \todo terrain double-define check?
         terrain_data.terrain_id_priority_map[terrain_id]  = line->blend_priority;
         terrain_data.terrain_id_blendmode_map[terrain_id] = line->blend_mode;
         // \todo remove hardcoding and rely on nyan data
         auto terraintex_filename = util::sformat("converted/terrain/%d.slp.png",
                                                  line->slp_id);
         auto new_texture = this->assetmanager->get_texture(terraintex_filename, true);
         terrain_data.textures[terrain_id] = new_texture;
     }
     // create blending masks (see doc/media/blendomatic)
     for (size_t i = 0; i < terrain_data.blendmode_count; i++) {
         auto line = &blending_meta[i];
         // \todo remove hardcodingn and use nyan data
         std::string mask_filename = util::sformat("converted/blendomatic/mode%02d.png",
                                                   line->blend_mode);
         terrain_data.blending_masks[i] = this->assetmanager->get_texture(mask_filename);
     }
 }
References assetmanager, openage::terrain_meta::blending_masks, openage::terrain_meta::blendmode_count, openage::log::dbg(), gamedata, openage::AssetManager::get_asset_dir(), openage::AssetManager::get_texture(), openage::terrain_meta::influences_buf, openage::line, openage::log::log(), MSG, openage::util::sformat(), terrain_data, openage::terrain_meta::terrain_id_blendmode_map, openage::terrain_meta::terrain_id_count, openage::terrain_meta::terrain_id_priority_map, and openage::terrain_meta::textures.
Referenced by initialize().
on_gamedata_loaded()
void openage::GameSpec::on_gamedata_loaded (const gamedata::empiresdat & gamedata) private
Invoked when the gamedata has been loaded.
Definition at line 192 of file game_spec.cpp.
{
     const util::Path &asset_dir = this->assetmanager->get_asset_dir();
     util::Path sound_dir = asset_dir["converted/sounds"];
     // create graphic id => graphic map
     for (auto &graphic : gamedata.graphics.data) {
         this->graphics[graphic.id] = &graphic;
         this->slp_to_graphic[graphic.slp_id] = graphic.id;
     }
     log::log(INFO << "Loading textures...");
     // create complete set of unit textures
     for (auto &g : this->graphics) {
         this->unit_textures.insert({g.first, std::make_shared<UnitTexture>(*this, g.second)});
     }
     log::log(INFO << "Loading sounds...");
     // playable sound files for the audio manager
     std::vector<audio::resource_def> load_sound_files;
     // all sounds defined in the game specification
     for (const gamedata::sound &sound : gamedata.sounds.data) {
         std::vector<int> sound_items;
         // each sound may have multiple variation,
         // processed in this loop
         // these are the single sound files.
         for (const gamedata::sound_item &item : sound.sound_items.data) {
             if (item.resource_id < 0) {
                 log::log(SPAM << "   Invalid sound resource id < 0");
                 continue;
             }
             std::string snd_filename = util::sformat("%d.opus", item.resource_id);
             util::Path snd_path = sound_dir[snd_filename];
             if (not snd_path.is_file()) {
                 continue;
             }
             // single items for a sound (so that we can ramdomize it)
             sound_items.push_back(item.resource_id);
             // the single sound will be loaded in the audio system.
             audio::resource_def resource {
                 audio::category_t::GAME,
                 item.resource_id,
                 snd_path,
                 audio::format_t::OPUS,
                 audio::loader_policy_t::DYNAMIC
             };
             load_sound_files.push_back(resource);
         }
         // create test sound objects that can be played later
         this->available_sounds.insert({
             sound.id,
             Sound{
                 this,
                 std::move(sound_items)
             }
         });
     }
     // \todo move out the loading of the sound.
     //       this class only provides the names and locations
     // load the requested sounds.
     audio::AudioManager &am = this->assetmanager->get_engine()->get_audio_manager();
     am.load_resources(load_sound_files);
     // this final step occurs after loading media
     // as producers require both the graphics and sounds
     this->create_abilities(gamedata);
 }
References assetmanager, available_sounds, create_abilities(), openage::audio::DYNAMIC, openage::audio::GAME, gamedata, openage::AssetManager::get_asset_dir(), openage::Engine::get_audio_manager(), openage::AssetManager::get_engine(), graphics, INFO, openage::util::Path::is_file(), openage::audio::AudioManager::load_resources(), openage::log::log(), openage::move, openage::audio::OPUS, openage::resource, openage::util::sformat(), slp_to_graphic, SPAM, and unit_textures.
Referenced by initialize().
valid_graphic_id()
bool openage::GameSpec::valid_graphic_id (index_t graphic_id) const private
check graphic id is valid
Definition at line 272 of file game_spec.cpp.
{
     if (graphic_id <= 0 || this->graphics.count(graphic_id) == 0) {
         return false;
     }
     if (this->graphics.at(graphic_id)->slp_id <= 0) {
         return false;
     }
     return true;
 }
References graphics.
Referenced by load_building(), load_living(), load_missile(), and load_object().
Member Data Documentation
assetmanager
AssetManager* openage::GameSpec::assetmanager private
Asset management entity that is responsible for textures, sounds, etc.
Definition at line 193 of file game_spec.h.
Referenced by get_asset_manager(), get_texture(), initialize(), load_terrain(), and on_gamedata_loaded().
available_sounds
std::unordered_map<index_t, Sound> openage::GameSpec::available_sounds private
sound ids mapped to playable sounds for all available sounds.
Definition at line 228 of file game_spec.h.
Referenced by get_sound(), and on_gamedata_loaded().
commands
std::unordered_map<index_t, std::vector<const gamedata::unit_command *> > openage::GameSpec::commands private
commands available for each unit id
Definition at line 218 of file game_spec.h.
Referenced by create_abilities(), and get_command_data().
gamedata
std::vector<gamedata::empiresdat> openage::GameSpec::gamedata private
The full original gamedata tree.
Definition at line 198 of file game_spec.h.
Referenced by create_abilities(), create_unit_types(), get_civ_name(), initialize(), load_terrain(), and on_gamedata_loaded().
gamedata_loaded
bool openage::GameSpec::gamedata_loaded private
has game data been load yet
Definition at line 233 of file game_spec.h.
Referenced by initialize(), and load_complete().
graphics
std::unordered_map<index_t, const gamedata::graphic *> openage::GameSpec::graphics private
map graphic id to gamedata graphic.
Definition at line 213 of file game_spec.h.
Referenced by get_graphic_data(), get_texture(), on_gamedata_loaded(), and valid_graphic_id().
slp_to_graphic
std::unordered_map<index_t, index_t> openage::GameSpec::slp_to_graphic private
slp to graphic id reverse lookup
Definition at line 208 of file game_spec.h.
Referenced by get_slp_graphic(), and on_gamedata_loaded().
terrain_data
terrain_meta openage::GameSpec::terrain_data private
data used for constructing terrain objects
Definition at line 203 of file game_spec.h.
Referenced by get_terrain_meta(), and load_terrain().
unit_textures
std::unordered_map<index_t, std::shared_ptr<UnitTexture> > openage::GameSpec::unit_textures private
graphic ids -> unit texture for that id
Definition at line 223 of file game_spec.h.
Referenced by get_unit_texture(), and on_gamedata_loaded().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gamestate/game_spec.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gamestate/game_spec.cpp