openage: openage::CreateMode Class Reference
openage::CreateMode Class Reference
#include <game_control.h>
Public Member Functions
CreateMode (qtsdl::GuiItemLink *gui_link)
bool available () const override
void on_enter () override
void on_exit () override
void render () override
std::string name () const override
void on_game_control_set () override
Public Member Functions inherited from openage::OutputMode
OutputMode (qtsdl::GuiItemLink *gui_link)
virtual ~OutputMode ()
virtual void announce ()
virtual void set_game_control (GameControl *game_control)
Public Member Functions inherited from openage::input::InputContext
InputContext ()
InputContext (InputManager *manager)
virtual ~InputContext ()=default
std::vector< std::string > active_binds () const
void bind (action_t type, const action_func_t act)
void bind (const Event &ev, const action_func_t act)
void bind (event_class ec, const action_check_t act)
bool execute_if_bound (const action_arg_t &e)
void register_to (InputManager *manager)
void unregister ()
Additional Inherited Members
Public Attributes inherited from openage::OutputMode
OutputModeSignals gui_signals
qtsdl::GuiItemLink * gui_link
Public Attributes inherited from openage::input::InputContext
bool utf8_mode
Protected Attributes inherited from openage::OutputMode
GameControl * game_control
Detailed Description
This is mainly the game editor. Shows menus to choose units to build.
Definition at line 118 of file game_control.h.
Constructor & Destructor Documentation
CreateMode()
openage::CreateMode::CreateMode (qtsdl::GuiItemLink * gui_link)
Definition at line 43 of file game_control.cpp.
     :
     OutputMode{gui_link} {}
References openage::OutputMode::gui_link.
Member Function Documentation
available()
bool openage::CreateMode::available () const override virtual
Is this mode able to be used?
Implements openage::OutputMode.
Definition at line 47 of file game_control.cpp.
{
     return true;
 }
name()
std::string openage::CreateMode::name () const override virtual
Used for displaying the current mode.
Implements openage::OutputMode.
Definition at line 51 of file game_control.cpp.
{
     return "Creation Mode";
 }
Referenced by openage.util.fslike.path.Path::stem(), openage.util.fslike.path.Path::suffix(), and openage.util.fslike.path.Path::suffixes().
on_enter()
void openage::CreateMode::on_enter () override virtual
Called when switching to this mode.
Implements openage::OutputMode.
Definition at line 57 of file game_control.cpp.
 {}
on_exit()
void openage::CreateMode::on_exit () override virtual
Called when the mode is left.
Implements openage::OutputMode.
Definition at line 59 of file game_control.cpp.
 {}
on_game_control_set()
void openage::CreateMode::on_game_control_set () override virtual
Called after GameControl has been set by QML from set_game_control.
Implements openage::OutputMode.
Definition at line 55 of file game_control.cpp.
 {}
render()
void openage::CreateMode::render () override virtual
Display this mode.
Implements openage::OutputMode.
Definition at line 61 of file game_control.cpp.
 {}
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/game_control.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/game_control.cpp