openage: openage::gui::GameSpecLink Class Reference
openage::gui::GameSpecLink Class Reference
#include <game_spec_link.h>
Public Types
enum State { State::Null, State::Loading, State::Ready }
Signals
void game_spec_loaded (GameSpecLink *game_spec, std::shared_ptr< GameSpec > loaded_game_spec)
void state_changed ()
void terrain_id_count_changed ()
Public Member Functions
GameSpecLink (QObject *parent=nullptr)
virtual ~GameSpecLink ()
State get_state () const
bool get_active () const
void set_active (bool active)
AssetManagerLink * get_asset_manager () const
void set_asset_manager (AssetManagerLink *asset_manager)
int get_terrain_id_count () const
Q_INVOKABLE void invalidate ()
std::shared_ptr< GameSpec > get_loaded_spec ()
Public Member Functions inherited from qtsdl::GuiItemQObject
GuiItemQObject (QObject *parent=nullptr)
Public Member Functions inherited from qtsdl::GuiItemBase
virtual ~GuiItemBase ()
Public Member Functions inherited from qtsdl::DeferredInitialConstantPropertyValues
DeferredInitialConstantPropertyValues ()
virtual ~DeferredInitialConstantPropertyValues ()
void apply_static_properties ()
void clear_static_properties ()
bool is_init_over () const
Public Member Functions inherited from qtsdl::GuiItemLink
virtual ~GuiItemLink ()
Public Member Functions inherited from qtsdl::GuiItem< GameSpecLink >
GuiItem (GuiItemBase *item_base)
Public Member Functions inherited from qtsdl::GuiItemCoreInstantiator< GameSpecLink >
GuiItemCoreInstantiator (GuiItemBase *item_base)
Public Member Functions inherited from qtsdl::GuiItemMethods< GameSpecLink >
virtual ~GuiItemMethods ()
U * get () const
U * get ()
void i (F f, Args &&... args)
Properties
State state
bool active
openage::gui::AssetManagerLink assetManager
int terrainIdCount
Private Slots
void on_load_job_finished ()
void on_game_spec_loaded (std::shared_ptr< GameSpec > loaded_game_spec)
Private Member Functions
virtual void classBegin () override
virtual void on_core_adopted () override
virtual void componentComplete () override
void set_state (State state)
Private Attributes
AssetManagerLink * asset_manager
int terrain_id_count
std::shared_ptr< GameSpec > loaded_game_spec
Additional Inherited Members
Protected Member Functions inherited from qtsdl::GuiItemMethods< GameSpecLink >
void s (F f, P &p, A &&arg)
void sf (F f, P &p, A &&arg)
Protected Attributes inherited from qtsdl::GuiItemBase
GameLogicCaller game_logic_caller
std::function< std::unique_ptr< PersistentCoreHolderBase >)> instantiate_core_func
std::function< void(PersistentCoreHolderBase *, const QString &)> do_adopt_core_func
std::function< void()> on_core_adopted_func
Protected Attributes inherited from qtsdl::DeferredInitialConstantPropertyValues
bool init_over
std::vector< std::function< void()> > static_properties_assignments
Detailed Description
Definition at line 41 of file game_spec_link.h.
Member Enumeration Documentation
State
enum openage::gui::GameSpecLink::State strong
Enumerator
Null
Loading
Ready
Definition at line 55 of file game_spec_link.h.
                      {
         Null, Loading, Ready
     };
Constructor & Destructor Documentation
GameSpecLink()
openage::gui::GameSpecLink::GameSpecLink (QObject * parent = nullptr) explicit
Definition at line 17 of file game_spec_link.cpp.
     :
     GuiItemQObject{parent},
     QQmlParserStatus{},
     GuiItem{this},
     state{},
     active{},
     asset_manager{},
     terrain_id_count{} {
     Q_UNUSED(registration);
     Q_UNUSED(registration_of_ptr);
 }
~GameSpecLink()
openage::gui::GameSpecLink::~GameSpecLink () virtual
Definition at line 30 of file game_spec_link.cpp.
{
 }
Member Function Documentation
classBegin()
void openage::gui::GameSpecLink::classBegin () override private virtual
Definition at line 33 of file game_spec_link.cpp.
{
 }
componentComplete()
void openage::gui::GameSpecLink::componentComplete () override private virtual
Definition at line 42 of file game_spec_link.cpp.
{
     this->on_load_job_finished();
 }
References on_load_job_finished().
game_spec_loaded
void openage::gui::GameSpecLink::game_spec_loaded (GameSpecLink * game_spec, std::shared_ptr< GameSpec > loaded_game_spec) signal
Pass loaded assets to the image provider.
Provider will check if it's still attached to that spec. Also it may be invalidated in the meantime, so share the ownership.
Referenced by on_game_spec_loaded(), and openage::gui::GuiImageProviderLink::set_game_spec().
get_active()
bool openage::gui::GameSpecLink::get_active () const
Definition at line 82 of file game_spec_link.cpp.
{
     return this->active;
 }
References active.
get_asset_manager()
AssetManagerLink * openage::gui::GameSpecLink::get_asset_manager () const
Definition at line 95 of file game_spec_link.cpp.
{
     return this->asset_manager;
 }
References asset_manager.
get_loaded_spec()
std::shared_ptr< GameSpec > openage::gui::GameSpecLink::get_loaded_spec ()
Definition at line 65 of file game_spec_link.cpp.
{
     return this->loaded_game_spec;
 }
References loaded_game_spec.
Referenced by openage::gui::GuiImageProviderLink::set_game_spec().
get_state()
GameSpecLink::State openage::gui::GameSpecLink::get_state () const
Definition at line 69 of file game_spec_link.cpp.
{
     return this->state;
 }
References state.
get_terrain_id_count()
int openage::gui::GameSpecLink::get_terrain_id_count () const
Definition at line 106 of file game_spec_link.cpp.
{
     return this->terrain_id_count;
 }
References terrain_id_count.
invalidate()
void openage::gui::GameSpecLink::invalidate ()
Definition at line 73 of file game_spec_link.cpp.
{
     static auto f = [] (GameSpecHandle *_this) {
         _this->invalidate();
     };
     this->i(f);
     this->set_state(this->active ? State::Loading : State::Null);
 }
References active, qtsdl::GuiItemMethods< GameSpecLink >::i(), Loading, Null, and set_state().
on_core_adopted()
void openage::gui::GameSpecLink::on_core_adopted () override private virtual
Reimplemented from qtsdl::GuiItemBase.
Definition at line 36 of file game_spec_link.cpp.
{
     auto core = unwrap(this);
     QObject::connect(core->gui_signals.get(), &GameSpecSignals::load_job_finished, this, &GameSpecLink::on_load_job_finished);
     QObject::connect(core->gui_signals.get(), &GameSpecSignals::game_spec_loaded, this, &GameSpecLink::on_game_spec_loaded);
 }
References openage::GameSpecSignals::game_spec_loaded(), openage::GameSpecSignals::load_job_finished(), on_game_spec_loaded(), on_load_job_finished(), and qtsdl::unwrap().
on_game_spec_loaded
void openage::gui::GameSpecLink::on_game_spec_loaded (std::shared_ptr< GameSpec > loaded_game_spec) private slot
Definition at line 53 of file game_spec_link.cpp.
{
     this->loaded_game_spec = loaded_game_spec;
     this->terrain_id_count = this->loaded_game_spec->get_terrain_meta()->terrain_id_count;
     this->state = State::Ready;
     emit this->state_changed();
     emit this->terrain_id_count_changed();
     emit this->game_spec_loaded(this, this->loaded_game_spec);
 }
References game_spec_loaded(), loaded_game_spec, Ready, state, state_changed(), terrain_id_count, and terrain_id_count_changed().
Referenced by on_core_adopted().
on_load_job_finished
void openage::gui::GameSpecLink::on_load_job_finished () private slot
Definition at line 46 of file game_spec_link.cpp.
{
     static auto f = [] (GameSpecHandle *_this) {
         _this->announce_spec();
     };
     this->i(f);
 }
References qtsdl::GuiItemMethods< GameSpecLink >::i().
Referenced by componentComplete(), and on_core_adopted().
set_active()
void openage::gui::GameSpecLink::set_active (bool active)
Definition at line 86 of file game_spec_link.cpp.
{
     static auto f = [] (GameSpecHandle *_this, bool active) {
         _this->set_active(active);
     };
     this->s(f, this->active, active);
     this->set_state(this->active && this->state == State::Null ? State::Loading : this->state);
 }
References active, Loading, Null, qtsdl::GuiItemMethods< GameSpecLink >::s(), openage::GameSpecHandle::set_active(), set_state(), and state.
set_asset_manager()
void openage::gui::GameSpecLink::set_asset_manager (AssetManagerLink * asset_manager)
Definition at line 99 of file game_spec_link.cpp.
{
     static auto f = [] (GameSpecHandle *_this, AssetManager *asset_manager) {
         _this->set_asset_manager(asset_manager);
     };
     this->s(f, this->asset_manager, asset_manager);
 }
References asset_manager, qtsdl::GuiItemMethods< GameSpecLink >::s(), and openage::GameSpecHandle::set_asset_manager().
set_state()
void openage::gui::GameSpecLink::set_state (GameSpecLink::State state) private
Definition at line 110 of file game_spec_link.cpp.
{
     if (state != this->state) {
         this->state = state;
         emit this->state_changed();
     }
 }
References state, and state_changed().
Referenced by invalidate(), and set_active().
state_changed
void openage::gui::GameSpecLink::state_changed () signal
Referenced by on_game_spec_loaded(), and set_state().
terrain_id_count_changed
void openage::gui::GameSpecLink::terrain_id_count_changed () signal
Referenced by on_game_spec_loaded().
Member Data Documentation
asset_manager
AssetManagerLink* openage::gui::GameSpecLink::asset_manager private
Definition at line 98 of file game_spec_link.h.
Referenced by get_asset_manager(), and set_asset_manager().
loaded_game_spec
std::shared_ptr<GameSpec> openage::gui::GameSpecLink::loaded_game_spec private
Definition at line 101 of file game_spec_link.h.
Referenced by get_loaded_spec(), and on_game_spec_loaded().
terrain_id_count
int openage::gui::GameSpecLink::terrain_id_count private
Definition at line 99 of file game_spec_link.h.
Referenced by get_terrain_id_count(), and on_game_spec_loaded().
Property Documentation
active
bool openage::gui::GameSpecLink::active read write
Definition at line 47 of file game_spec_link.h.
Referenced by get_active(), invalidate(), and set_active().
assetManager
openage::gui::AssetManagerLink openage::gui::GameSpecLink::assetManager read write
Definition at line 48 of file game_spec_link.h.
state
State openage::gui::GameSpecLink::state read
Definition at line 46 of file game_spec_link.h.
Referenced by get_state(), on_game_spec_loaded(), set_active(), and set_state().
terrainIdCount
int openage::gui::GameSpecLink::terrainIdCount read
Definition at line 49 of file game_spec_link.h.
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/game_spec_link.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/game_spec_link.cpp