openage: openage::TrainAction Class Reference
openage::TrainAction Class Reference
#include <action.h>
Public Member Functions
TrainAction (Unit *e, UnitType *pp)
virtual ~TrainAction ()
void update (unsigned int time) override
void on_completion () override
bool completed () const override
bool allow_interupt () const override
bool allow_control () const override
std::string name () const override
float get_progress () const
Public Member Functions inherited from openage::UnitAction
UnitAction (Unit *u, graphic_type initial_gt)
virtual ~UnitAction ()
graphic_type type () const
float current_frame () const
virtual const graphic_set & current_graphics () const
void draw_debug (const Engine &engine)
void face_towards (const coord::phys3 pos)
bool damage_unit (Unit &target)
void move_to (Unit &target, bool use_range=true)
Private Attributes
UnitType * trained
IntervalTimer timer
bool started
bool complete
Additional Inherited Members
Static Public Member Functions inherited from openage::UnitAction
static coord::phys_t adjacent_range (Unit *u)
static coord::phys_t get_attack_range (Unit *u)
static coord::phys_t get_heal_range (Unit *u)
Static Public Attributes inherited from openage::UnitAction
static bool show_debug = false
Protected Attributes inherited from openage::UnitAction
Unit * entity
graphic_type graphic
float frame
float frame_rate
std::function< void(const Engine &)> debug_draw_action
Detailed Description
trains a new unit
Definition at line 445 of file action.h.
Constructor & Destructor Documentation
TrainAction()
openage::TrainAction::TrainAction (Unit * e, UnitType * pp)
Definition at line 798 of file action.cpp.
     :
     UnitAction{e, graphic_type::standing},
     trained{pp},
     timer{10000, 1}, // TODO get the training time from unit type
     started{false},
     complete{false} {
     // TODO deduct resources
 }
References openage::standing.
~TrainAction()
virtual openage::TrainAction::~TrainAction () inline virtual
Definition at line 448 of file action.h.
 {}
Member Function Documentation
allow_control()
bool openage::TrainAction::allow_control () const inline override virtual
control whether stack can discard the action automatically and should the stack be modifiable when this action is on top
if true this action must complete and will not allow new actions to be pushed while it is active and also does not update the secondary actions
Implements openage::UnitAction.
Definition at line 454 of file action.h.
 { return true; }
allow_interupt()
bool openage::TrainAction::allow_interupt () const inline override virtual
checks if the action can be interrupted, allowing it to be popped if the user specifies a new action, if false the action must reach a completed state before removal eg dead action must be completed and cannot be discarded
Implements openage::UnitAction.
Definition at line 453 of file action.h.
 { return false; }
completed()
bool openage::TrainAction::completed () const inline override virtual
gets called for all actions on stack each update cycle
Returns
true when action is completed so it and everything above it can be popped
Implements openage::UnitAction.
Definition at line 452 of file action.h.
 { return this->complete; }
References complete.
get_progress()
float openage::TrainAction::get_progress () const inline
Definition at line 457 of file action.h.
 { return this->timer.get_progress(); }
References openage::IntervalTimer::get_progress(), and timer.
name()
std::string openage::TrainAction::name () const inline override virtual
debug string to identify action types
Implements openage::UnitAction.
Definition at line 455 of file action.h.
 { return "train"; }
Referenced by openage.util.fslike.path.Path::stem(), openage.util.fslike.path.Path::suffix(), and openage.util.fslike.path.Path::suffixes().
on_completion()
void openage::TrainAction::on_completion () override virtual
action to perform when popped from a units action stack
Implements openage::UnitAction.
Definition at line 850 of file action.cpp.
{
     if (!this->complete) {
         // TODO give back the resources
     }
 }
References complete.
update()
void openage::TrainAction::update (unsigned int time) override virtual
each action has its own update functionality which gets called when this is the active action
Implements openage::UnitAction.
Definition at line 808 of file action.cpp.
{
     if (!this->started) {
         // check if there is enough population capacity
         if (!this->trained->default_attributes.has(attr_type::population)) {
             this->started = true;
         }
         else {
             auto &player = this->entity->get_attribute<attr_type::owner>().player;
             auto &population_demand = this->trained->default_attributes.get<attr_type::population>().demand;
             bool can_start = population_demand == 0 || population_demand <= player.population.get_space();
             // TODO trigger not enough population capacity message
             this->started = can_start;
         }
     }
     if (this->started) {
         // place unit when ready
         if (this->timer.finished() || this->timer.update(time)) {
             // create using the producer
             UnitContainer *container = this->entity->get_container();
             auto &player = this->entity->get_attribute<attr_type::owner>().player;
             auto uref = container->new_unit(*this->trained, player, this->entity->location.get());
             // make sure unit got placed
             // try again next update if cannot place
             if (uref.is_valid()) {
                 if (this->entity->has_attribute(attr_type::building)) {
                     // use a move command to the gather point
                     auto &build_attr = this->entity->get_attribute<attr_type::building>();
                     Command cmd(player, build_attr.gather_point);
                     cmd.set_ability(ability_type::move);
                     uref.get()->queue_cmd(cmd);
                 }
                 this->complete = true;
             }
         }
     }
 }
References openage::building, complete, openage::curve::tests::container(), openage::UnitType::default_attributes, openage::UnitAction::entity, openage::IntervalTimer::finished(), openage::Attributes::get(), openage::Unit::get_attribute(), openage::Unit::get_container(), openage::Attributes::has(), openage::Unit::has_attribute(), openage::Unit::location, openage::move, openage::owner, openage::population, started, timer, trained, and openage::IntervalTimer::update().
Member Data Documentation
complete
bool openage::TrainAction::complete private
Definition at line 464 of file action.h.
Referenced by completed(), on_completion(), and update().
started
bool openage::TrainAction::started private
Definition at line 463 of file action.h.
Referenced by update().
timer
IntervalTimer openage::TrainAction::timer private
Definition at line 462 of file action.h.
Referenced by get_progress(), and update().
trained
UnitType* openage::TrainAction::trained private
Definition at line 460 of file action.h.
Referenced by update().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/action.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/action.cpp