openage: openage::OutputMode Class Reference
openage::OutputMode Class Reference abstract
A target for input handling and gui rendering.
#include <game_control.h>
Public Member Functions
OutputMode (qtsdl::GuiItemLink *gui_link)
virtual ~OutputMode ()
virtual bool available () const =0
Is this mode able to be used?
virtual void on_enter ()=0
Called when switching to this mode.
virtual void on_exit ()=0
Called when the mode is left.
virtual void render ()=0
Display this mode.
virtual std::string name () const =0
Used for displaying the current mode.
virtual void announce ()
Emit the "announced" signal with (name, InputContext::active_binds).
virtual void set_game_control (GameControl *game_control)
Called when the GameControl is set in QML.
virtual void on_game_control_set ()=0
Called after GameControl has been set by QML from set_game_control.
Public Member Functions inherited from openage::input::InputContext
InputContext ()
Create an unbound input context.
InputContext (InputManager *manager)
Create a bound context, assigned to its manager.
virtual ~InputContext ()=default
std::vector< std::string > active_binds () const
a list of all keys of this context which are bound currently in the active context.
void bind (action_t type, const action_func_t act)
bind a specific action idetifier this is the highest matching priority
void bind (const Event &ev, const action_func_t act)
bind a specific event this is the second matching priority
void bind (event_class ec, const action_check_t act)
bind all events of a specific class this is the lowest matching priority
bool execute_if_bound (const action_arg_t &e)
lookup an action.
void register_to (InputManager *manager)
Called by the InputManager where this context shall be registered to.
void unregister ()
Remove the registration to an input manager.
Public Attributes
OutputModeSignals gui_signals
Signals to be triggered when the mode canges.
qtsdl::GuiItemLink * gui_link
Public Attributes inherited from openage::input::InputContext
bool utf8_mode
Affects which keyboard events are received: true to accpet utf8 text events, false to receive regular char events.
Protected Attributes
GameControl * game_control
Detailed Description
A target for input handling and gui rendering.
This allows to switch to different display UIs.
Definition at line 56 of file game_control.h.
Constructor & Destructor Documentation
OutputMode()
openage::OutputMode::OutputMode (qtsdl::GuiItemLink * gui_link) explicit
Definition at line 15 of file game_control.cpp.
     :
     game_control{nullptr},
     gui_link{gui_link} {
 }
~OutputMode()
openage::OutputMode::~OutputMode () virtual
Definition at line 21 of file game_control.cpp.
{
     // An empty deconstructor prevents our clients from needing
     // to implement one.
     //
     // The deconstructor is needed in the first place to stop
     // the compiler from generating ud2 (undefined) instructors
     // for the body of this method.
 }
Member Function Documentation
announce()
void openage::OutputMode::announce () virtual
Emit the "announced" signal with (name, InputContext::active_binds).
Reimplemented in openage::EditorMode, and openage::ActionMode.
Definition at line 30 of file game_control.cpp.
{
     emit this->gui_signals.announced(this->name());
     emit this->gui_signals.binds_changed(this->active_binds());
 }
References openage::input::InputContext::active_binds(), openage::OutputModeSignals::announced(), openage::OutputModeSignals::binds_changed(), gui_signals, and name().
Referenced by openage::ActionMode::announce(), openage::EditorMode::announce(), openage::GameControl::announce_mode(), and set_game_control().
available()
virtual bool openage::OutputMode::available () const pure virtual
Is this mode able to be used?
Implemented in openage::EditorMode, openage::ActionMode, and openage::CreateMode.
name()
virtual std::string openage::OutputMode::name () const pure virtual
Used for displaying the current mode.
Implemented in openage::EditorMode, openage::ActionMode, and openage::CreateMode.
Referenced by announce(), openage.util.fslike.path.Path::stem(), openage.util.fslike.path.Path::suffix(), and openage.util.fslike.path.Path::suffixes().
on_enter()
virtual void openage::OutputMode::on_enter () pure virtual
Called when switching to this mode.
Implemented in openage::EditorMode, openage::ActionMode, and openage::CreateMode.
Referenced by openage::GameControl::set_mode().
on_exit()
virtual void openage::OutputMode::on_exit () pure virtual
Called when the mode is left.
Implemented in openage::EditorMode, openage::ActionMode, and openage::CreateMode.
Referenced by openage::GameControl::set_mode().
on_game_control_set()
virtual void openage::OutputMode::on_game_control_set () pure virtual
Called after GameControl has been set by QML from set_game_control.
Implemented in openage::EditorMode, openage::ActionMode, and openage::CreateMode.
Referenced by set_game_control().
render()
virtual void openage::OutputMode::render () pure virtual
Display this mode.
Implemented in openage::EditorMode, openage::ActionMode, and openage::CreateMode.
Referenced by openage::GameControl::on_drawhud().
set_game_control()
void openage::OutputMode::set_game_control (GameControl * game_control) virtual
Called when the GameControl is set in QML.
Reimplemented in openage::EditorMode.
Definition at line 36 of file game_control.cpp.
{
     this->game_control = game_control;
     this->on_game_control_set();
     this->announce();
 }
References announce(), game_control, and on_game_control_set().
Referenced by openage::EditorMode::set_game_control().
Member Data Documentation
game_control
GameControl* openage::OutputMode::game_control protected
Definition at line 102 of file game_control.h.
Referenced by openage::ActionMode::announce_buttons_type(), openage::EditorMode::announce_categories(), openage::EditorMode::announce_category_content(), openage::ActionMode::announce_resources(), openage::ActionMode::available(), openage::EditorMode::available(), openage::ActionMode::get_action(), openage::ActionModeSignals::on_action(), openage::ActionMode::on_exit(), openage::ActionMode::on_game_control_set(), openage::EditorMode::on_game_control_set(), openage::EditorMode::paint_entity_at(), openage::EditorMode::paint_terrain_at(), openage::ActionMode::place_selection(), openage::ActionMode::render(), set_game_control(), and openage::EditorMode::set_game_control().
gui_link
qtsdl::GuiItemLink* openage::OutputMode::gui_link
Definition at line 110 of file game_control.h.
Referenced by openage::ActionMode::ActionMode(), openage::CreateMode::CreateMode(), and openage::EditorMode::EditorMode().
gui_signals
OutputModeSignals openage::OutputMode::gui_signals
Signals to be triggered when the mode canges.
Definition at line 108 of file game_control.h.
Referenced by announce().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/game_control.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/game_control.cpp