openage: openage::curve::ValueContainer< T > Class Template Reference
openage::curve::ValueContainer< T > Class Template Reference abstract
#include <value_container.h>
Public Member Functions
ValueContainer (const std::shared_ptr< event::Loop > &mgr, size_t id, const EventTarget::single_change_notifier &notifier=nullptr)
virtual ~ValueContainer ()=default
virtual T get (const time_t &t) const =0
virtual T operator() (const time_t &now)
virtual std::pair< time_t, const T & > frame (const time_t &) const
virtual std::pair< time_t, const T & > next_frame (const time_t &) const
virtual void set_last (const time_t &at, const T &value)
virtual void set_insert (const time_t &at, const T &value)
virtual size_t id () const override
Public Member Functions inherited from openage::event::EventTarget
virtual ~EventTarget ()=default
void add_dependent (const std::weak_ptr< Event > &event)
void show_dependents () const
Protected Attributes
KeyframeContainer< T > container
const size_t _id
KeyframeContainer< T >::KeyframeIterator last_element
Additional Inherited Members
Public Types inherited from openage::event::EventTarget
using single_change_notifier = std::function< void(const curve::time_t &)>
Protected Member Functions inherited from openage::event::EventTarget
EventTarget (const std::shared_ptr< Loop > &loop, single_change_notifier parent_notifier=nullptr)
void changes (const curve::time_t &change_time)
void trigger (const curve::time_t &last_valid_time)
Detailed Description
template<typename T>
class openage::curve::ValueContainer< T >
Definition at line 14 of file value_container.h.
Constructor & Destructor Documentation
ValueContainer()
template<typename T > openage::curve::ValueContainer< T >::ValueContainer (const std::shared_ptr< event::Loop > & mgr, size_t id, const EventTarget::single_change_notifier & notifier = nullptr) inline
Definition at line 16 of file value_container.h.
         :
         EventTarget(mgr, notifier),
         container{mgr},
         _id{id},
         last_element{this->container.begin()} {}
~ValueContainer()
template<typename T > virtual openage::curve::ValueContainer< T >::~ValueContainer () virtual default
Member Function Documentation
frame()
template<typename T > std::pair< time_t, const T & > openage::curve::ValueContainer< T >::frame (const time_t & time) const virtual
Definition at line 91 of file value_container.h.
{
     auto e = this->container.last(time, this->container.end());
     return std::make_pair(e->time, e->value);
 }
References openage::curve::tests::container().
get()
template<typename T > virtual T openage::curve::ValueContainer< T >::get (const time_t & t) const pure virtual
Implemented in openage::curve::Discrete< T >, and openage::curve::Continuous< T >.
Referenced by openage::curve::ValueContainer< T >::operator()().
id()
template<typename T > virtual size_t openage::curve::ValueContainer< T >::id () const inline override virtual
Give a unique event system identifier for the entity
Implements openage::event::EventTarget.
Definition at line 40 of file value_container.h.
{
         return _id;
     }
References openage::curve::ValueContainer< T >::_id.
next_frame()
template<typename T > std::pair< time_t, const T & > openage::curve::ValueContainer< T >::next_frame (const time_t & time) const virtual
Definition at line 98 of file value_container.h.
{
     auto e = this->container.last(time, this->container.end());
     e++;
     return std::make_pair(e->time, e->value);
 }
References openage::curve::tests::container().
operator()()
template<typename T > virtual T openage::curve::ValueContainer< T >::operator() (const time_t & now) inline virtual
Definition at line 29 of file value_container.h.
{
         return get(now);
     }
References openage::curve::ValueContainer< T >::get().
set_insert()
template<typename T > void openage::curve::ValueContainer< T >::set_insert (const time_t & at, const T & value) virtual
Definition at line 84 of file value_container.h.
{
     this->container.insert(at, value, this->last_element);
     this->changes(at);
 }
References openage.convert.changelog::changes(), and openage::curve::tests::container().
Referenced by openage::curve::tests::curve_types().
set_last()
template<typename T > void openage::curve::ValueContainer< T >::set_last (const time_t & at, const T & value) virtual
Definition at line 63 of file value_container.h.
{
     auto hint = this->container.last(at, this->last_element);
     // We want to remove a possible equal timed element from the container
     // to do fabs(x-y) < min is only necessary when time_t is floating point!
     //if (std::abs(hint->time - at) < std::numeric_limits<time_t>::min()) {
     if (hint->time == at) {
         hint--;
     }
     hint = this->container.erase_after(hint);
     container.insert(at, value, hint);
     this->last_element = hint;
     this->changes(at);
 }
References openage.convert.changelog::changes(), and openage::curve::tests::container().
Referenced by openage::curve::tests::curve_types().
Member Data Documentation
_id
template<typename T > const size_t openage::curve::ValueContainer< T >::_id protected
Identifier for the container
Definition at line 53 of file value_container.h.
Referenced by openage::curve::ValueContainer< T >::id().
container
template<typename T > KeyframeContainer<T> openage::curve::ValueContainer< T >::container protected
Stores all the keyframes
Definition at line 48 of file value_container.h.
last_element
template<typename T > KeyframeContainer<T>::KeyframeIterator openage::curve::ValueContainer< T >::last_element mutable protected
Cache the iterator for quickly finding the end
Definition at line 58 of file value_container.h.
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/curve/value_container.h