openage: qtsdl::GuiEventQueueImpl Class Reference
qtsdl::GuiEventQueueImpl Class Reference
#include <gui_event_queue_impl.h>
Public Member Functions
GuiEventQueueImpl ()
~GuiEventQueueImpl ()
void process_callbacks ()
QThread * get_thread ()
Static Public Member Functions
static GuiEventQueueImpl * impl (GuiEventQueue *event_queue)
Private Attributes
QThread *const thread
QEventLoop callback_processor
Detailed Description
Provides synchronization with some game thread.
Definition at line 17 of file gui_event_queue_impl.h.
Constructor & Destructor Documentation
GuiEventQueueImpl()
qtsdl::GuiEventQueueImpl::GuiEventQueueImpl () explicit
Definition at line 16 of file gui_event_queue_impl.cpp.
     :
     thread{QThread::currentThread()} {
 }
~GuiEventQueueImpl()
qtsdl::GuiEventQueueImpl::~GuiEventQueueImpl ()
Definition at line 21 of file gui_event_queue_impl.cpp.
{
 }
Member Function Documentation
get_thread()
QThread * qtsdl::GuiEventQueueImpl::get_thread ()
Definition at line 37 of file gui_event_queue_impl.cpp.
{
     return this->thread;
 }
References thread.
Referenced by qtsdl::GuiSubtreeImpl::attach_to(), and qtsdl::GuiInputImpl::relay_input_event().
impl()
GuiEventQueueImpl * qtsdl::GuiEventQueueImpl::impl (GuiEventQueue * event_queue) static
Definition at line 24 of file gui_event_queue_impl.cpp.
{
     return event_queue->impl.get();
 }
References qtsdl::GuiEventQueue::impl.
process_callbacks()
void qtsdl::GuiEventQueueImpl::process_callbacks ()
Definition at line 28 of file gui_event_queue_impl.cpp.
{
     assert(QThread::currentThread() == this->thread);
 #ifdef __APPLE__
     if (QThread::currentThread() != QCoreApplication::instance()->thread()) this->callback_processor.processEvents();
 #else
     this->callback_processor.processEvents();
 #endif
 }
References callback_processor, and thread.
Referenced by qtsdl::GuiInputImpl::relay_input_event().
Member Data Documentation
callback_processor
QEventLoop qtsdl::GuiEventQueueImpl::callback_processor private
Definition at line 30 of file gui_event_queue_impl.h.
Referenced by process_callbacks().
thread
QThread* const qtsdl::GuiEventQueueImpl::thread private
Definition at line 29 of file gui_event_queue_impl.h.
Referenced by get_thread(), and process_callbacks().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/guisys/private/gui_event_queue_impl.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/guisys/private/gui_event_queue_impl.cpp