openage: openage::input::InputManager Class Reference
openage::input::InputManager Class Reference
#include <input_manager.h>
Public Types
enum Edge { Edge::LEFT, Edge::RIGHT, Edge::UP, Edge::DOWN }
Public Member Functions
InputManager (ActionManager *action_manager)
std::string get_bind (const std::string &action)
bool set_bind (const std::string &bind_str, const std::string action)
std::string key_bind_to_string (const Event &ev)
std::string mouse_bind_to_string (const Event &ev)
std::string wheel_bind_to_string (const Event &ev)
InputContext & get_global_context ()
InputContext & get_top_context ()
void push_context (InputContext *context)
void remove_context (InputContext *context)
bool ignored (const Event &e)
bool trigger (const Event &e)
void set_state (const Event &ev, bool is_down)
void set_mouse (int x, int y)
void set_motion (int x, int y)
void set_relative (bool mode)
bool is_mouse_at_edge (Edge edge, int window_size)
bool is_down (const ClassCode &cc) const
bool is_down (event_class ec, code_t code) const
bool is_down (SDL_Keycode k) const
bool is_mod_down (modifier mod) const
bool on_input (SDL_Event *e) override
std::vector< std::string > active_binds (const std::unordered_map< action_t, action_func_t > &ctx_actions) const
ActionManager * get_action_manager () const
Public Member Functions inherited from openage::InputHandler
virtual ~InputHandler ()=default
Private Member Functions
modset_t get_mod () const
Private Attributes
ActionManager * action_manager
InputContext global_context
binding_map_t keys
std::vector< InputContext * > contexts
std::unordered_map< ClassCode, bool, class_code_hash > states
modset_t keymod
bool relative_mode
coord::input mouse_position {0, 0}
coord::input_delta mouse_motion {0, 0}
friend InputContext
Detailed Description
The input manager manages all input layers (hud, game, ...) and triggers the registered actions depending on the active layer.
pxd:
cppclass InputManager: bool set_bind(char* bind_char, string action) except + string get_bind(string action) except +
Definition at line 42 of file input_manager.h.
Member Enumeration Documentation
Edge
enum openage::input::InputManager::Edge strong
Screen edges used for edge scrolling.
Enumerator
LEFT
RIGHT
UP
DOWN
Definition at line 47 of file input_manager.h.
                     {
         LEFT,
         RIGHT,
         UP,
         DOWN
     };
Constructor & Destructor Documentation
InputManager()
openage::input::InputManager::InputManager (ActionManager * action_manager)
Definition at line 15 of file input_manager.cpp.
     :
     action_manager{action_manager},
     global_context{this},
     relative_mode{false} {
     this->global_context.register_to(this);
 }
References action_manager.
Member Function Documentation
active_binds()
std::vector< std::string > openage::input::InputManager::active_binds (const std::unordered_map< action_t, action_func_t > & ctx_actions) const
Return a string representation of active key bindings from the given context.
Definition at line 384 of file input_manager.cpp.
{
     std::vector<std::string> result;
     // \todo this only checks the by_type mappings, the others are missing!
     for (auto &action : ctx_actions) {
         std::string keyboard_key;
         for (auto &key : this->keys) {
             if (key.first == action.first) {
                 keyboard_key = event_as_string(key.second);
                 break;
             }
         }
         // this is only possible if the action is registered,
         // then this->input_manager != nullptr.
         // \todo try to purge the action manager access here.
         // \todo get_name takes O(n) time
         std::string action_type_str = this->get_action_manager()->get_name(action.first);
         result.push_back(keyboard_key + " : " + action_type_str);
     }
     return result;
 }
References get_action_manager(), openage::input::ActionManager::get_name(), keys, and openage.testing.testing::result().
Referenced by openage::input::InputContext::active_binds().
get_action_manager()
ActionManager * openage::input::InputManager::get_action_manager () const
Get the action manager attached to this input manager.
Definition at line 412 of file input_manager.cpp.
{
     return this->action_manager;
 }
References action_manager.
Referenced by active_binds().
get_bind()
std::string openage::input::InputManager::get_bind (const std::string & action)
Return the string representation of the bind assignated to an action.
Definition at line 66 of file input_manager.cpp.
{
     action_t action = this->action_manager->get(action_str);
     if (this->action_manager->is("UNDEFINED", action)) {
         return "";
     }
     auto it = this->keys.find(action);
     if (it == this->keys.end()) {
         return " ";
     }
     switch (it->second.cc.eclass) {
         case event_class::MOUSE_BUTTON :
             return this->mouse_bind_to_string(it->second);
         case event_class::MOUSE_WHEEL :
             return this->wheel_bind_to_string(it->second);
         default:
             return this->key_bind_to_string(it->second);
     }
     return "";
 }
References action_manager, openage::input::ActionManager::get(), openage::input::ActionManager::is(), key_bind_to_string(), keys, mouse_bind_to_string(), openage::input::MOUSE_BUTTON, openage::input::MOUSE_WHEEL, and wheel_bind_to_string().
Referenced by openage::input::ActionManager::create().
get_global_context()
InputContext & openage::input::InputManager::get_global_context ()
returns the global keybind context. actions bound here will be retained even when override_context is called.
Definition at line 142 of file input_manager.cpp.
{
     return this->global_context;
 }
References global_context.
Referenced by openage::ActionMode::on_exit(), openage::console::Console::register_to_engine(), and openage::GameControl::set_engine().
get_mod()
modset_t openage::input::InputManager::get_mod () const private
Definition at line 309 of file input_manager.cpp.
{
     SDL_Keymod mod = SDL_GetModState();
     return sdl_mod(mod);
 }
References openage::util::mod(), and openage::input::sdl_mod().
Referenced by on_input().
get_top_context()
InputContext & openage::input::InputManager::get_top_context ()
Returns the context on top. Note there is always a top context since the global context will be considered on top when none are registered
Definition at line 146 of file input_manager.cpp.
{
     // return the global input context
     // if no override is pushed
     if (this->contexts.empty()) {
         return this->global_context;
     }
     return *this->contexts.back();
 }
References contexts, and global_context.
Referenced by openage::ActionMode::announce_buttons_type(), ignored(), openage::ActionModeSignals::on_action(), and openage::ActionMode::on_exit().
ignored()
bool openage::input::InputManager::ignored (const Event & e)
true if the given event type is being ignored
Definition at line 178 of file input_manager.cpp.
{
     // filter duplicate utf8 events
     // these are ignored unless the top mode enables
     // utf8 mode, in which case regular char codes are ignored
     return ((e.cc.has_class(event_class::CHAR) ||
              e.cc.has_class(event_class::UTF8)) &&
             this->get_top_context().utf8_mode != e.cc.has_class(event_class::UTF8));
 }
References openage::input::Event::cc, openage::input::CHAR, get_top_context(), openage::input::ClassCode::has_class(), openage::input::UTF8, and openage::input::InputContext::utf8_mode.
Referenced by set_state(), and trigger().
is_down() [1/3]
bool openage::input::InputManager::is_down (const ClassCode & cc) const
Query stored pressing stat for a key.
note that the function stores a unknown/new keycode as 'not pressed' if requested
Returns
true when the key is pressed, false else.
Definition at line 285 of file input_manager.cpp.
{
     auto it = this->states.find(cc);
     if (it != this->states.end()) {
         return it->second;
     }
     return false;
 }
References states.
Referenced by is_down(), openage::Engine::loop(), openage::EditorMode::on_game_control_set(), and set_state().
is_down() [2/3]
bool openage::input::InputManager::is_down (event_class ec, code_t code) const
Definition at line 294 of file input_manager.cpp.
{
     return is_down(ClassCode(ec, code));
 }
References is_down().
is_down() [3/3]
bool openage::input::InputManager::is_down (SDL_Keycode k) const
Most cases should use above is_down(class, code) instead to avoid relying on sdl types
Query stored pressing stat for a key.
Returns
true when the key is pressed, false else.
Definition at line 299 of file input_manager.cpp.
{
     return is_down(sdl_key(k).cc);
 }
References is_down(), and openage::input::sdl_key().
is_mod_down()
bool openage::input::InputManager::is_mod_down (modifier mod) const
Checks whether a key modifier is held down.
Definition at line 304 of file input_manager.cpp.
{
     return (this->keymod.count(mod) > 0);
 }
References keymod.
is_mouse_at_edge()
bool openage::input::InputManager::is_mouse_at_edge (Edge edge, int window_size)
Query whether cursor is at edgo of screen
edge variable is enum Edges
Returns
true when the mouse is at the queried screen edge, false else.
Definition at line 260 of file input_manager.cpp.
{
     int x, y;
     SDL_GetMouseState(&x, &y);
     // Border width to consider screen edges for scrolling.
     // AoE II appears to be approx 10px.
     // \todo make configurable through cvar.
     const int edge_offset = 10;
     if (edge == Edge::LEFT && x <= edge_offset) {
         return true;
     }
     if (edge == Edge::RIGHT && x >= window_size - edge_offset - 1) {
         return true;
     }
     if (edge == Edge::UP && y <= edge_offset) {
         return true;
     }
     if (edge == Edge::DOWN && y >= window_size - edge_offset - 1) {
         return true;
     }
     return false;
 }
References DOWN, LEFT, RIGHT, and UP.
Referenced by openage::Engine::loop().
key_bind_to_string()
std::string openage::input::InputManager::key_bind_to_string (const Event & ev)
Return the string representation of the key event.
Definition at line 110 of file input_manager.cpp.
{
     std::string key_str = std::string(SDL_GetKeyName(ev.cc.code));
     auto end = ev.mod.end();
     if (ev.mod.find(modifier::ALT) != end) {
         key_str = "Alt "+key_str;
     }
     if (ev.mod.find(modifier::SHIFT) != end) {
         key_str = "Shift "+key_str;
     }
     if (ev.mod.find(modifier::CTRL) != end) {
         key_str = "Ctrl "+key_str;
     }
     return key_str;
 }
References openage::input::ALT, openage::input::Event::cc, openage::input::ClassCode::code, openage::input::CTRL, openage::input::Event::mod, and openage::input::SHIFT.
Referenced by get_bind().
mouse_bind_to_string()
std::string openage::input::InputManager::mouse_bind_to_string (const Event & ev)
Return the string representation of the mouse event.
Definition at line 126 of file input_manager.cpp.
{
     return "MOUSE " + std::to_string(ev.cc.code);
 }
References openage::input::Event::cc, openage::input::ClassCode::code, and std::to_string().
Referenced by get_bind().
on_input()
bool openage::input::InputManager::on_input (SDL_Event * e) override virtual
When a SDL event happens, this is called.
Implements openage::InputHandler.
Definition at line 315 of file input_manager.cpp.
{
     // top level input handler
     switch (e->type) {
     case SDL_KEYUP: {
         SDL_Keycode code = reinterpret_cast<SDL_KeyboardEvent *>(e)->keysym.sym;
         Event ev = sdl_key(code, SDL_GetModState());
         this->set_state(ev, false);
         break;
     } // case SDL_KEYUP
     case SDL_KEYDOWN: {
         SDL_Keycode code = reinterpret_cast<SDL_KeyboardEvent *>(e)->keysym.sym;
         this->set_state(sdl_key(code, SDL_GetModState()), true);
         break;
     } // case SDL_KEYDOWN
     case SDL_TEXTINPUT: {
         this->trigger(utf8(e->text.text));
         break;
     } // case SDL_TEXTINPUT
     case SDL_MOUSEBUTTONUP: {
         this->set_relative(false);
         this->trigger(sdl_mouse_up_down(e->button.button, true, SDL_GetModState()));
         Event ev = sdl_mouse(e->button.button, SDL_GetModState());
         this->set_state(ev, false);
         break;
     } // case SDL_MOUSEBUTTONUP
     case SDL_MOUSEBUTTONDOWN: {
         // \todo set which buttons
         if (e->button.button == 2) {
             this->set_relative(true);
         }
         this->trigger(sdl_mouse_up_down(e->button.button, false, SDL_GetModState()));
         Event ev = sdl_mouse(e->button.button, SDL_GetModState());
         this->set_state(ev, true);
         break;
     } // case SDL_MOUSEBUTTONDOWN
     case SDL_MOUSEMOTION: {
         if (this->relative_mode) {
             this->set_motion(e->motion.xrel, e->motion.yrel);
         }
         else {
             this->set_mouse(e->button.x, e->button.y);
         }
         // must occur after setting mouse position
         Event ev(event_class::MOUSE_MOTION, 0, this->get_mod());
         this->trigger(ev);
         break;
     } // case SDL_MOUSEMOTION
     case SDL_MOUSEWHEEL: {
         Event ev = sdl_wheel(e->wheel.y, SDL_GetModState());
         this->trigger(ev);
         break;
     } // case SDL_MOUSEWHEEL
     } // switch (e->type)
     return true;
 }
References get_mod(), openage::input::MOUSE_MOTION, relative_mode, openage::input::sdl_key(), openage::input::sdl_mouse(), openage::input::sdl_mouse_up_down(), openage::input::sdl_wheel(), set_motion(), set_mouse(), set_relative(), set_state(), trigger(), and openage::input::utf8().
push_context()
void openage::input::InputManager::push_context (InputContext * context)
register a hotkey context by pushing it onto the stack.
this adds the given pointer to the contexts list. that way the context lays on "top".
if other contexts are registered afterwards, it wanders down the stack, i.e. looses priority.
Definition at line 155 of file input_manager.cpp.
{
     // push the context to the top
     this->contexts.push_back(context);
     context->register_to(this);
 }
References contexts, and openage::input::InputContext::register_to().
Referenced by openage::GameControl::set_mode(), and openage::console::Console::set_visible().
remove_context()
void openage::input::InputManager::remove_context (InputContext * context)
removes any matching registered context from the stack.
the removal is done by finding the given pointer in the contexts lists, then deleting it in there.
Definition at line 163 of file input_manager.cpp.
{
     if (this->contexts.empty()) {
         return;
     }
     for (auto it = this->contexts.begin(); it != this->contexts.end(); ++it) {
         if ((*it) == context) {
             this->contexts.erase(it);
             context->unregister();
             return;
         }
     }
 }
References contexts, and openage::input::InputContext::unregister().
Referenced by openage::ActionMode::on_exit(), openage::GameControl::set_mode(), and openage::console::Console::set_visible().
set_bind()
bool openage::input::InputManager::set_bind (const std::string & bind_str, const std::string action)
Set the given action to be triggered by the given bind (key/mouse /wheel). Remove previous assignation. Do nothing if either they given bind or action is invalid/unknow.
Definition at line 88 of file input_manager.cpp.
{
     try {
         action_t action = this->action_manager->get(action_str);
         if (this->action_manager->is("UNDEFINED", action)) {
             return false;
         }
         Event ev = text_to_event(bind_str);
         auto it = this->keys.find(action);
         if (it != this->keys.end()) {
             this->keys.erase(it);
         }
         this->keys.emplace(std::make_pair(action, ev));
         return true;
     }
     catch (int error) {
         return false;
     }
 }
References action_manager, openage::input::ActionManager::get(), openage::input::ActionManager::is(), keys, and openage::input::text_to_event().
Referenced by openage::input::ActionManager::create().
set_motion()
void openage::input::InputManager::set_motion (int x, int y)
updates mouse motion only
Definition at line 239 of file input_manager.cpp.
{
     this->mouse_motion.x = x;
     this->mouse_motion.y = y;
 }
References mouse_motion.
Referenced by on_input().
set_mouse()
void openage::input::InputManager::set_mouse (int x, int y)
updates mouse position state and motion
Definition at line 232 of file input_manager.cpp.
{
     auto last_position = this->mouse_position;
     this->mouse_position = coord::input{coord::pixel_t{x}, coord::pixel_t{y}};
     this->mouse_motion = this->mouse_position - last_position;
 }
References mouse_motion, and mouse_position.
Referenced by on_input().
set_relative()
void openage::input::InputManager::set_relative (bool mode)
enable relative mouse mode
Definition at line 245 of file input_manager.cpp.
{
     if (this->relative_mode == mode) {
         return;
     }
     // change mode
     this->relative_mode = mode;
     if (this->relative_mode) {
         SDL_SetRelativeMouseMode(SDL_TRUE);
     }
     else {
         SDL_SetRelativeMouseMode(SDL_FALSE);
     }
 }
References relative_mode.
Referenced by on_input().
set_state()
void openage::input::InputManager::set_state (const Event & ev, bool is_down)
sets the state of a specific key
Definition at line 214 of file input_manager.cpp.
{
     if (this->ignored(ev)) {
         return;
     }
     // update key states
     this->keymod = ev.mod;
     bool was_down = this->states[ev.cc];
     this->states[ev.cc] = is_down;
     // a key going from pressed to unpressed
     // will automatically trigger event handling
     if (was_down && !is_down) {
         this->trigger(ev);
     }
 }
References openage::input::Event::cc, ignored(), is_down(), keymod, openage::input::Event::mod, states, and trigger().
Referenced by on_input().
trigger()
bool openage::input::InputManager::trigger (const Event & e)
manages the pressing of an input event (key, mouse, ...). first checks whether an action is bound to it. if it is, look for an handler to execute that handler. returns true if the event was responded to
Definition at line 188 of file input_manager.cpp.
{
     if (this->ignored(e)) {
         return false;
     }
     // arg passed to receivers
     action_arg_t arg{e, this->mouse_position, this->mouse_motion, {}};
     for (auto &it : this->keys) {
         if (e == it.second) {
             arg.hints.emplace_back(it.first);
         }
     }
     // Check context list on top of the stack (most recent bound first)
     for (auto it = this->contexts.rbegin(); it != this->contexts.rend(); ++it) {
         if ((*it)->execute_if_bound(arg)) {
             return true;
         }
     }
     // If no local keybinds were bound, check the global keybinds
     return this->global_context.execute_if_bound(arg);
 }
References contexts, openage::input::InputContext::execute_if_bound(), global_context, ignored(), keys, mouse_motion, and mouse_position.
Referenced by on_input(), and set_state().
wheel_bind_to_string()
std::string openage::input::InputManager::wheel_bind_to_string (const Event & ev)
Return the key representation of the event.
Definition at line 130 of file input_manager.cpp.
{
     std::string base = "WHEEL ";
     switch (ev.cc.code) {
     case 1:
         return base + "UP";
     case -1:
         return base + "DOWN";
     default:
         return "";
     }
 }
References openage::input::Event::cc, and openage::input::ClassCode::code.
Referenced by get_bind().
Member Data Documentation
action_manager
ActionManager* openage::input::InputManager::action_manager private
The action manager to used for keybind action lookups.
Definition at line 204 of file input_manager.h.
Referenced by get_action_manager(), get_bind(), InputManager(), and set_bind().
contexts
std::vector<InputContext *> openage::input::InputManager::contexts private
Stack of active input contexts. The most recent entry is pushed on top of the stack.
Definition at line 220 of file input_manager.h.
Referenced by get_top_context(), push_context(), remove_context(), and trigger().
global_context
InputContext openage::input::InputManager::global_context private
The global context. Used as fallback.
Definition at line 209 of file input_manager.h.
Referenced by get_global_context(), get_top_context(), and trigger().
InputContext
friend openage::input::InputManager::InputContext private
Definition at line 252 of file input_manager.h.
keymod
modset_t openage::input::InputManager::keymod private
Current key modifiers. Included ALL modifiers including num lock and caps lock.
Definition at line 234 of file input_manager.h.
Referenced by is_mod_down(), and set_state().
keys
binding_map_t openage::input::InputManager::keys private
Maps actions to events.
Definition at line 214 of file input_manager.h.
Referenced by active_binds(), get_bind(), set_bind(), and trigger().
mouse_motion
coord::input_delta openage::input::InputManager::mouse_motion {0, 0} private
mouse position relative to the last frame position.
Definition at line 250 of file input_manager.h.
Referenced by set_motion(), set_mouse(), and trigger().
mouse_position
coord::input openage::input::InputManager::mouse_position {0, 0} private
mouse position in the window
Definition at line 245 of file input_manager.h.
Referenced by set_mouse(), and trigger().
relative_mode
bool openage::input::InputManager::relative_mode private
mode where mouse position is ignored used for map scrolling
Definition at line 240 of file input_manager.h.
Referenced by on_input(), and set_relative().
states
std::unordered_map<ClassCode, bool, class_code_hash> openage::input::InputManager::states private
key to is_down map. stores a mapping between keycodes and its pressing state. a true value means the key is currently pressed, false indicates the key is untouched.
Definition at line 228 of file input_manager.h.
Referenced by is_down(), and set_state().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/input/input_manager.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/input/input_manager.cpp