openage: openage::event::EventClass::param_map Class Reference
openage::event::EventClass::param_map Class Reference
Storage for parameters for an event class.
#include <eventclass.h>
Public Types
using map_t = std::unordered_map< std::string, std::any >
Public Member Functions
param_map ()
param_map (std::initializer_list< map_t::value_type > l)
param_map (const map_t &map)
template<typename T >
T get (const std::string &key, const T &defaultval=T()) const
Returns the value, if it exists and is the right type.
bool contains (const std::string &key) const
Check if the map contains the given key.
template<typename Type >
bool check_type (const std::string &key) const
Check if the type of a map entry is correct.
Private Member Functions
template<typename T >
bool check_type (const map_t::const_iterator &it) const
Private Attributes
const map_t map
Data storage.
Detailed Description
Storage for parameters for an event class.
Definition at line 72 of file eventclass.h.
Member Typedef Documentation
map_t
using openage::event::EventClass::param_map::map_t = std::unordered_map<std::string, std::any>
Definition at line 74 of file eventclass.h.
Constructor & Destructor Documentation
param_map() [1/3]
openage::event::EventClass::param_map::param_map () inline
Definition at line 76 of file eventclass.h.
 {}
param_map() [2/3]
openage::event::EventClass::param_map::param_map (std::initializer_list< map_t::value_type > l) inline
Definition at line 77 of file eventclass.h.
 : map(l) {}
param_map() [3/3]
openage::event::EventClass::param_map::param_map (const map_t & map) inline
Definition at line 78 of file eventclass.h.
 : map{std::move(map)} {}
References map, and openage::move.
Member Function Documentation
check_type() [1/2]
template<typename Type > bool openage::event::EventClass::param_map::check_type (const std::string & key) const inline
Check if the type of a map entry is correct.
Definition at line 105 of file eventclass.h.
{
             auto it = map.find(key);
             if (it != map.end()) {
                 return this->check_type<Type>(it);
             }
             return false;
         }
References map.
Referenced by openage::event::tests::eventtrigger().
check_type() [2/2]
template<typename T > bool openage::event::EventClass::param_map::check_type (const map_t::const_iterator & it) const inline private
Definition at line 115 of file eventclass.h.
{
             return it->second.type() == typeid(T);
         }
contains()
bool openage::event::EventClass::param_map::contains (const std::string & key) const inline
Check if the map contains the given key.
Definition at line 97 of file eventclass.h.
{
             return map.find(key) != map.end();
         }
References map.
Referenced by openage::event::tests::eventtrigger().
get()
template<typename T > T openage::event::EventClass::param_map::get (const std::string & key, const T & defaultval = T()) const inline
Returns the value, if it exists and is the right type.
defaultval if not.
Definition at line 85 of file eventclass.h.
{
             auto it = this->map.find(key);
             if (it != this->map.end() && this->check_type<T>(it)) {
                 return std::any_cast<T>(it->second);
             } else {
                 return defaultval;
             }
         }
References map.
Referenced by openage::event::tests::eventtrigger().
Member Data Documentation
map
const map_t openage::event::EventClass::param_map::map private
Data storage.
Definition at line 122 of file eventclass.h.
Referenced by check_type(), contains(), get(), and param_map().
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/event/eventclass.h