openage: openage::datastructure::ConstMap< K, V, pos > Class Template Reference
openage::datastructure::ConstMap< K, V, pos > Class Template Reference
#include <constexpr_map.h>
Public Member Functions
template<class Head , class... Tail>
constexpr ConstMap (Head head, Tail... tail)
constexpr int size () const
constexpr bool contains (const K &key) const
constexpr const V & get (const K &key) const
constexpr const V & operator [] (const K &key) const
Private Member Functions
constexpr bool has_entry (const K &key) const
constexpr bool is_unique () const
constexpr bool all_are_unique () const
constexpr bool verify_no_duplicates () const
constexpr const V & fetch (const K &key) const
Private Attributes
const ConstMapEntry< K, V > value
const ConstMap< K, V, pos - 1 > tail
Friends
class ConstMap< K, V, pos+1 >
Detailed Description
template<typename K, typename V, size_t pos>
class openage::datastructure::ConstMap< K, V, pos >
Compiletime generic lookup map.
This is a recursive template that decreases pos which each iteration step. Each pos stores one map entry. The lookup recursively descends those entries down to the zero-element.
If you experience compiler errors, make sure you request existing keys. We intentionally trigger compiler failures when a key doesn't exist.
Messages include: "error: ‘*0u’ is not a constant expression" -> nonexistant key
Definition at line 60 of file constexpr_map.h.
Constructor & Destructor Documentation
ConstMap()
template<typename K , typename V , size_t pos> template<class Head , class... Tail> constexpr openage::datastructure::ConstMap< K, V, pos >::ConstMap (Head head, Tail... tail) inline
Definition at line 63 of file constexpr_map.h.
         :
         value{head},
         tail{tail...} {}
Member Function Documentation
all_are_unique()
template<typename K , typename V , size_t pos> constexpr bool openage::datastructure::ConstMap< K, V, pos >::all_are_unique () const inline private
Verifies that this entry's key is not used in following entries, then continues checking with the next entry checking for the same.
Definition at line 115 of file constexpr_map.h.
{
         return this->is_unique() and this->tail.all_are_unique();
     }
References openage::datastructure::ConstMap< K, V, pos >::is_unique(), and openage::datastructure::ConstMap< K, V, pos >::tail.
Referenced by openage::datastructure::ConstMap< K, V, pos >::verify_no_duplicates().
contains()
template<typename K , typename V , size_t pos> constexpr bool openage::datastructure::ConstMap< K, V, pos >::contains (const K & key) const inline
Tests if the given key is in this map.
Definition at line 78 of file constexpr_map.h.
{
         return this->verify_no_duplicates(), this->has_entry(key);
     }
References openage::datastructure::ConstMap< K, V, pos >::has_entry(), and openage::datastructure::ConstMap< K, V, pos >::verify_no_duplicates().
fetch()
template<typename K , typename V , size_t pos> constexpr const V& openage::datastructure::ConstMap< K, V, pos >::fetch (const K & key) const inline private
Returns the value matching key from this or following elements.
Definition at line 133 of file constexpr_map.h.
{
         return
         // if we found the key
         (this->value.key == key) ?
             // return the value
             this->value.value
         :
             // else try the lookup on the remaining elements
             this->tail.fetch(key);
     }
References openage::datastructure::ConstMap< K, V, pos >::value.
Referenced by openage::datastructure::ConstMap< K, V, pos >::get().
get()
template<typename K , typename V , size_t pos> constexpr const V& openage::datastructure::ConstMap< K, V, pos >::get (const K & key) const inline
Return the stored value for the given key.
Definition at line 85 of file constexpr_map.h.
{
         return this->verify_no_duplicates(), this->fetch(key);
     }
References openage::datastructure::ConstMap< K, V, pos >::fetch(), and openage::datastructure::ConstMap< K, V, pos >::verify_no_duplicates().
Referenced by openage::datastructure::ConstMap< K, V, pos >::operator []().
has_entry()
template<typename K , typename V , size_t pos> constexpr bool openage::datastructure::ConstMap< K, V, pos >::has_entry (const K & key) const inline private
Test if if the given key is stored in this element or in following elements.
Definition at line 100 of file constexpr_map.h.
{
         return (this->value.key == key) or this->tail.has_entry(key);
     }
References openage::datastructure::ConstMap< K, V, pos >::tail, and openage::datastructure::ConstMap< K, V, pos >::value.
Referenced by openage::datastructure::ConstMap< K, V, pos >::contains().
is_unique()
template<typename K , typename V , size_t pos> constexpr bool openage::datastructure::ConstMap< K, V, pos >::is_unique () const inline private
Test if the key of this entry is not used in following entries.
Definition at line 107 of file constexpr_map.h.
{
         return not this->tail.has_entry(this->value.key);
     }
References openage::datastructure::ConstMap< K, V, pos >::tail, and openage::datastructure::ConstMap< K, V, pos >::value.
Referenced by openage::datastructure::ConstMap< K, V, pos >::all_are_unique().
operator []()
template<typename K , typename V , size_t pos> constexpr const V& openage::datastructure::ConstMap< K, V, pos >::operator [] (const K & key) const inline
Access entries by map[key].
Definition at line 92 of file constexpr_map.h.
{
         return this->get(key);
     }
References openage::datastructure::ConstMap< K, V, pos >::get().
size()
template<typename K , typename V , size_t pos> constexpr int openage::datastructure::ConstMap< K, V, pos >::size () const inline
Return the number of entries in this map.
Definition at line 71 of file constexpr_map.h.
{
         return this->verify_no_duplicates(), pos;
     }
References openage::datastructure::ConstMap< K, V, pos >::verify_no_duplicates().
verify_no_duplicates()
template<typename K , typename V , size_t pos> constexpr bool openage::datastructure::ConstMap< K, V, pos >::verify_no_duplicates () const inline private
Abort when the map uses the same key more than once.
Definition at line 122 of file constexpr_map.h.
{
         return
         this->all_are_unique() ?
             true
         :
             throw Error(MSG(err) << "There is a duplicate key in the map.");
     }
References openage::datastructure::ConstMap< K, V, pos >::all_are_unique(), openage::log::err(), and MSG.
Referenced by openage::datastructure::ConstMap< K, V, pos >::contains(), openage::datastructure::ConstMap< K, V, pos >::get(), and openage::datastructure::ConstMap< K, V, pos >::size().
Friends And Related Function Documentation
ConstMap< K, V, pos+1 >
template<typename K , typename V , size_t pos> friend class ConstMap< K, V, pos+1 > friend
The previous entry is our friend.
Definition at line 157 of file constexpr_map.h.
Member Data Documentation
tail
template<typename K , typename V , size_t pos> const ConstMap<K, V, pos - 1> openage::datastructure::ConstMap< K, V, pos >::tail private
The remaining map entries.
Definition at line 152 of file constexpr_map.h.
Referenced by openage::datastructure::ConstMap< K, V, pos >::all_are_unique(), openage::datastructure::ConstMap< K, V, pos >::has_entry(), and openage::datastructure::ConstMap< K, V, pos >::is_unique().
value
template<typename K , typename V , size_t pos> const ConstMapEntry<K, V> openage::datastructure::ConstMap< K, V, pos >::value private
The entry associated with this map position.
Definition at line 147 of file constexpr_map.h.
Referenced by openage.convert.dataformat.members.ContinueReadMemberResult::__str__(), openage::datastructure::ConstMap< K, V, pos >::fetch(), openage::datastructure::ConstMap< K, V, pos >::has_entry(), and openage::datastructure::ConstMap< K, V, pos >::is_unique().
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/datastructure/constexpr_map.h