openage: openage::log::LogSinkList Class Reference
openage::log::LogSinkList Class Reference
#include <logsink.h>
Public Member Functions
LogSinkList (LogSinkList const &)=delete
void operator= (LogSinkList const &)=delete
void log (const message &msg, class LogSource *source) const
void add (LogSink *sink)
void remove (LogSink *sink)
bool supports_loglevel (level loglevel) const
void loglevel_changed ()
Static Public Member Functions
static LogSinkList & instance ()
Private Member Functions
LogSinkList ()
void set_lowest_loglevel ()
Private Attributes
std::list< LogSink * > sinks
std::mutex sinks_mutex
level lowest_loglevel
Detailed Description
Holds a list of all registered log sinks; Maintained from the LogSink constructors/destructors.
Definition at line 51 of file logsink.h.
Constructor & Destructor Documentation
LogSinkList() [1/2]
openage::log::LogSinkList::LogSinkList (LogSinkList const &) delete
LogSinkList() [2/2]
openage::log::LogSinkList::LogSinkList () private
Definition at line 31 of file logsink.cpp.
{
     this->set_lowest_loglevel();
 }
References set_lowest_loglevel().
Member Function Documentation
add()
void openage::log::LogSinkList::add (LogSink * sink)
Definition at line 53 of file logsink.cpp.
{
     std::lock_guard<std::mutex> lock(this->sinks_mutex);
     this->sinks.push_back(sink);
     this->set_lowest_loglevel();
 }
References lock, set_lowest_loglevel(), sinks, and sinks_mutex.
Referenced by openage::log::LogSink::LogSink().
instance()
LogSinkList & openage::log::LogSinkList::instance () static
Definition at line 36 of file logsink.cpp.
{
     static LogSinkList instance;
     return instance;
 }
Referenced by openage::log::LogSource::log(), openage::log::LogSink::LogSink(), openage::log::LogSink::set_loglevel(), openage::log::MessageBuilder::should_format(), and openage::log::LogSink::~LogSink().
log()
void openage::log::LogSinkList::log (const message & msg, class LogSource * source) const
Definition at line 42 of file logsink.cpp.
{
     std::lock_guard<std::mutex> lock(this->sinks_mutex);
     for (auto *sink : this->sinks) {
         // TODO: more sophisticated filtering (iptables-chains-like)
         if (msg.lvl >= sink->loglevel) {
             sink->output_log_message(msg, source);
         }
     }
 }
References lock, openage::log::message::lvl, sinks, and sinks_mutex.
Referenced by openage::log::LogSource::log().
loglevel_changed()
void openage::log::LogSinkList::loglevel_changed ()
Definition at line 60 of file logsink.cpp.
{
     std::lock_guard<std::mutex> lock(this->sinks_mutex);
     this->set_lowest_loglevel();
 }
References lock, set_lowest_loglevel(), and sinks_mutex.
Referenced by openage::log::LogSink::set_loglevel().
operator=()
void openage::log::LogSinkList::operator= (LogSinkList const &) delete
remove()
void openage::log::LogSinkList::remove (LogSink * sink)
Definition at line 74 of file logsink.cpp.
{
     std::lock_guard<std::mutex> lock(this->sinks_mutex);
     this->sinks.remove(sink);
     this->set_lowest_loglevel();
 }
References lock, set_lowest_loglevel(), sinks, and sinks_mutex.
Referenced by openage::log::LogSink::~LogSink().
set_lowest_loglevel()
void openage::log::LogSinkList::set_lowest_loglevel () private
Definition at line 66 of file logsink.cpp.
{
     this->lowest_loglevel = level::MAX;
     for (auto *sink : this->sinks) {
         this->lowest_loglevel = std::min(this->lowest_loglevel, sink->loglevel);
     }
 }
References lowest_loglevel, openage::MAX, std::min(), and sinks.
Referenced by add(), loglevel_changed(), LogSinkList(), and remove().
supports_loglevel()
bool openage::log::LogSinkList::supports_loglevel (level loglevel) const
Definition at line 81 of file logsink.cpp.
{
     std::lock_guard<std::mutex> lock(this->sinks_mutex);
     return loglevel >= this->lowest_loglevel;
 }
References lock, lowest_loglevel, and sinks_mutex.
Referenced by openage::log::MessageBuilder::should_format().
Member Data Documentation
lowest_loglevel
level openage::log::LogSinkList::lowest_loglevel private
Definition at line 78 of file logsink.h.
Referenced by set_lowest_loglevel(), and supports_loglevel().
sinks
std::list<LogSink*> openage::log::LogSinkList::sinks private
Definition at line 72 of file logsink.h.
Referenced by add(), log(), remove(), and set_lowest_loglevel().
sinks_mutex
std::mutex openage::log::LogSinkList::sinks_mutex mutable private
Definition at line 74 of file logsink.h.
Referenced by add(), log(), loglevel_changed(), remove(), and supports_loglevel().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/log/logsink.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/log/logsink.cpp