openage: openage::util::fslike::FSLike Class Reference
openage::util::fslike::FSLike Class Reference abstract
#include <fslike.h>
Public Member Functions
FSLike ()
virtual ~FSLike ()=default
virtual Path root ()
virtual bool is_file (const Path::parts_t &parts)=0
virtual bool is_dir (const Path::parts_t &parts)=0
virtual bool writable (const Path::parts_t &parts)=0
virtual Path::parts_t list (const Path::parts_t &parts)=0
virtual bool mkdirs (const Path::parts_t &parts)=0
virtual File open_r (const Path::parts_t &parts)=0
virtual File open_w (const Path::parts_t &parts)=0
virtual File open_rw (const Path::parts_t &parts)=0
virtual File open_a (const Path::parts_t &parts)=0
virtual File open_ar (const Path::parts_t &parts)=0
virtual std::pair< bool, Path > resolve_r (const Path::parts_t &parts)
virtual std::pair< bool, Path > resolve_w (const Path::parts_t &parts)
virtual std::string get_native_path (const Path::parts_t &parts)=0
virtual bool rename (const Path::parts_t &parts, const Path::parts_t &target_parts)=0
virtual bool rmdir (const Path::parts_t &parts)=0
virtual bool touch (const Path::parts_t &parts)=0
virtual bool unlink (const Path::parts_t &parts)=0
virtual int get_mtime (const Path::parts_t &parts)=0
virtual uint64_t get_filesize (const Path::parts_t &parts)=0
virtual bool is_python_native () const noexcept
virtual std::ostream & repr (std::ostream &)=0
Detailed Description
Base class for possible path implementations.
pxd: cppclass FSLike: Path root() except + bool is_file(const parts_t &parts) except + bool is_dir(const parts_t &parts) except + bool writable(const parts_t &parts) except + parts_t list(const parts_t &parts) except + bool mkdirs(const parts_t &parts) except +
File open_r(const parts_t &parts) except + File open_w(const parts_t &parts) except + File open_rw(const parts_t &parts) except + File open_a(const parts_t &parts) except + File open_ar(const parts_t &parts) except + pair[bool, Path] resolve_r(const parts_t &parts) except + pair[bool, Path] resolve_w(const parts_t &parts) except + string get_native_path(const parts_t &parts) except +
bool rename(const parts_t &parts, const parts_t &target_parts) except + bool rmdir(const parts_t &parts) except + bool touch(const parts_t &parts) except + bool unlink(const parts_t &parts) except +
int get_mtime(const parts_t &parts) except + uint64_t get_filesize(const parts_t &parts) except +
bool is_python_native() noexcept shared_ptr[FSLike] shared_from_this() except +
Definition at line 69 of file fslike.h.
Constructor & Destructor Documentation
FSLike()
openage::util::fslike::FSLike::FSLike ()
Definition at line 12 of file fslike.cpp.
 {}
~FSLike()
virtual openage::util::fslike::FSLike::~FSLike () virtual default
Member Function Documentation
get_filesize()
virtual uint64_t openage::util::fslike::FSLike::get_filesize (const Path::parts_t & parts) pure virtual
Implemented in openage::util::fslike::Python, and openage::util::fslike::Directory.
get_mtime()
virtual int openage::util::fslike::FSLike::get_mtime (const Path::parts_t & parts) pure virtual
Implemented in openage::util::fslike::Python, and openage::util::fslike::Directory.
get_native_path()
virtual std::string openage::util::fslike::FSLike::get_native_path (const Path::parts_t & parts) pure virtual
Implemented in openage::util::fslike::Python, and openage::util::fslike::Directory.
is_dir()
virtual bool openage::util::fslike::FSLike::is_dir (const Path::parts_t & parts) pure virtual
Implemented in openage::util::fslike::Python, and openage::util::fslike::Directory.
Referenced by openage.util.fslike.abstract.FSLikeObject::exists(), openage.util.fslike.path.Path::removerecursive(), and resolve_r().
is_file()
virtual bool openage::util::fslike::FSLike::is_file (const Path::parts_t & parts) pure virtual
Implemented in openage::util::fslike::Python, and openage::util::fslike::Directory.
Referenced by openage.util.fslike.abstract.FSLikeObject::exists(), and resolve_r().
is_python_native()
bool openage::util::fslike::FSLike::is_python_native () const virtual noexcept
Reimplemented in openage::util::fslike::Python.
Definition at line 39 of file fslike.cpp.
{
     return false;
 }
list()
virtual Path::parts_t openage::util::fslike::FSLike::list (const Path::parts_t & parts) pure virtual
Implemented in openage::util::fslike::Python, and openage::util::fslike::Directory.
mkdirs()
virtual bool openage::util::fslike::FSLike::mkdirs (const Path::parts_t & parts) pure virtual
Implemented in openage::util::fslike::Python, and openage::util::fslike::Directory.
Referenced by openage.util.fslike.wrapper.DirectoryCreator::open_w().
open_a()
virtual File openage::util::fslike::FSLike::open_a (const Path::parts_t & parts) pure virtual
Implemented in openage::util::fslike::Python, and openage::util::fslike::Directory.
open_ar()
virtual File openage::util::fslike::FSLike::open_ar (const Path::parts_t & parts) pure virtual
Implemented in openage::util::fslike::Python, and openage::util::fslike::Directory.
open_r()
virtual File openage::util::fslike::FSLike::open_r (const Path::parts_t & parts) pure virtual
Implemented in openage::util::fslike::Python, and openage::util::fslike::Directory.
open_rw()
virtual File openage::util::fslike::FSLike::open_rw (const Path::parts_t & parts) pure virtual
Implemented in openage::util::fslike::Python, and openage::util::fslike::Directory.
open_w()
virtual File openage::util::fslike::FSLike::open_w (const Path::parts_t & parts) pure virtual
Implemented in openage::util::fslike::Python, and openage::util::fslike::Directory.
rename()
virtual bool openage::util::fslike::FSLike::rename (const Path::parts_t & parts, const Path::parts_t & target_parts) pure virtual
Implemented in openage::util::fslike::Python, and openage::util::fslike::Directory.
repr()
virtual std::ostream& openage::util::fslike::FSLike::repr (std::ostream &) pure virtual
Implemented in openage::util::fslike::Python, and openage::util::fslike::Directory.
resolve_r()
std::pair< bool, Path > openage::util::fslike::FSLike::resolve_r (const Path::parts_t & parts) virtual
Reimplemented in openage::util::fslike::Python.
Definition at line 19 of file fslike.cpp.
{
     if (this->is_file(parts) or this->is_dir(parts)) {
         return std::make_pair(true, Path{this->shared_from_this(), parts});
     }
     else {
         return std::make_pair(false, Path{});
     }
 }
References is_dir(), and is_file().
resolve_w()
std::pair< bool, Path > openage::util::fslike::FSLike::resolve_w (const Path::parts_t & parts) virtual
Reimplemented in openage::util::fslike::Python.
Definition at line 29 of file fslike.cpp.
{
     if (this->writable(parts)) {
         return std::make_pair(true, Path{this->shared_from_this(), parts});
     }
     else {
         return std::make_pair(false, Path{});
     }
 }
References writable().
rmdir()
virtual bool openage::util::fslike::FSLike::rmdir (const Path::parts_t & parts) pure virtual
Implemented in openage::util::fslike::Python, and openage::util::fslike::Directory.
Referenced by openage.util.fslike.path.Path::removerecursive().
root()
Path openage::util::fslike::FSLike::root () virtual
Definition at line 14 of file fslike.cpp.
                   {
     return Path{this->shared_from_this(), {}};
 }
touch()
virtual bool openage::util::fslike::FSLike::touch (const Path::parts_t & parts) pure virtual
Implemented in openage::util::fslike::Python, and openage::util::fslike::Directory.
unlink()
virtual bool openage::util::fslike::FSLike::unlink (const Path::parts_t & parts) pure virtual
Implemented in openage::util::fslike::Python, and openage::util::fslike::Directory.
Referenced by openage.util.fslike.path.Path::removerecursive().
writable()
virtual bool openage::util::fslike::FSLike::writable (const Path::parts_t & parts) pure virtual
Implemented in openage::util::fslike::Python, and openage::util::fslike::Directory.
Referenced by openage.util.fslike.wrapper.Wrapper::resolve_w(), resolve_w(), and openage.util.fslike.abstract.FSLikeObject::resolve_w().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/fslike/fslike.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/fslike/fslike.cpp