openage: openage::renderer::TextRenderer Class Reference
openage::renderer::TextRenderer Class Reference
#include <text.h>
Classes
struct text_render_batch
The set of text draw requests with the same font and color.
struct text_render_batch_pass
A single text draw request containing the text and position.
Public Member Functions
TextRenderer ()
Requires a working OpenGL context to create buffer objects.
virtual ~TextRenderer ()
void set_font (Font *font)
Set the font to be used for the future text draw calls.
void set_color (const Color &color)
Set the color to be used for the future text draw calls.
void draw (coord::viewport position, const char *format,...)
Draw a formatted string at the specified position.
void draw (coord::viewport position, const std::string &text)
Draw text at the specified position.
void draw (int x, int y, const std::string &text)
Draw text at the specified position.
void render ()
Render all the text draw requests made during the frame.
Private Attributes
Font * current_font
Color current_color
bool is_dirty
std::vector< text_render_batch > render_batches
GlyphAtlas glyph_atlas
GLuint vbo
GLuint ibo
Detailed Description
Definition at line 23 of file text.h.
Constructor & Destructor Documentation
TextRenderer()
openage::renderer::TextRenderer::TextRenderer ()
Requires a working OpenGL context to create buffer objects.
Definition at line 48 of file text.cpp.
     :
     current_font{nullptr},
     current_color{255, 255, 255, 255},
     is_dirty{true},
     vbo{0},
     ibo{0} {
     glGenBuffers(1, &this->vbo);
     glGenBuffers(1, &this->ibo);
 }
~TextRenderer()
openage::renderer::TextRenderer::~TextRenderer () virtual
Definition at line 60 of file text.cpp.
{
     if (this->vbo != 0u) {
         glDeleteBuffers(1, &this->vbo);
     }
     if (this->ibo != 0u) {
         glDeleteBuffers(1, &this->ibo);
     }
 }
References ibo, and vbo.
Member Function Documentation
draw() [1/3]
void openage::renderer::TextRenderer::draw (coord::viewport position, const char * format, ...)
Draw a formatted string at the specified position.
Parameters
position where the text should be displayed.
format the text format
Definition at line 87 of file text.cpp.
{
     std::string text;
     va_list vl;
     va_start(vl, format);
     util::vsformat(format, vl, text);
     va_end(vl);
     this->draw(position.x, position.y, text);
 }
References openage::util::vsformat().
Referenced by draw().
draw() [2/3]
void openage::renderer::TextRenderer::draw (coord::viewport position, const std::string & text)
Draw text at the specified position.
Parameters
position where the text should be displayed.
text the text to be displayed.
Definition at line 97 of file text.cpp.
{
     this->draw(position.x, position.y, text);
 }
References draw().
draw() [3/3]
void openage::renderer::TextRenderer::draw (int x, int y, const std::string & text)
Draw text at the specified position.
Parameters
x the position in x-direction.
y the position in y-direction.
text the text to be displayed.
Definition at line 101 of file text.cpp.
{
     if (this->is_dirty || this->render_batches.empty()) {
         this->render_batches.emplace_back(this->current_font, this->current_color);
         this->is_dirty = false;
     }
     this->render_batches.back().passes.emplace_back(x, y, text);
 }
References current_color, current_font, is_dirty, and render_batches.
render()
void openage::renderer::TextRenderer::render ()
Render all the text draw requests made during the frame.
Definition at line 110 of file text.cpp.
{
     // Sort the batches by font
     std::sort(std::begin(this->render_batches), std::end(this->render_batches),
               [](const text_render_batch &a, const text_render_batch &b) -> bool {
                   return a.font < b.font;
               });
     // Merge consecutive batches if font and color values are same
     for (auto current_batch = std::begin(this->render_batches); current_batch != std::end(this->render_batches); ) {
         auto next_batch = current_batch;
         next_batch++;
         if (next_batch != std::end(this->render_batches) &&
             current_batch->font == next_batch->font &&
             current_batch->color == next_batch->color) {
             // Merge the render passes of current and next batches and remove the next batch
             std::move(std::begin(next_batch->passes),
                       std::end(next_batch->passes),
                       std::back_inserter(current_batch->passes));
             this->render_batches.erase(next_batch);
         } else {
             current_batch++;
         }
     }
     size_t index = 0;
     std::vector<text_render_vertex> vertices;
     std::vector<unsigned int> indices;
     std::vector<text_render_task> render_tasks;
     render_tasks.reserve(this->render_batches.size());
     unsigned int offset = 0;
     // Compute vertices and indices
     for (auto &batch : this->render_batches) {
         Font *font = batch.font;
         unsigned int num_elements = 0;
         for (auto &pass : batch.passes) {
             auto x = static_cast<float>(pass.x);
             auto y = static_cast<float>(pass.y);
             std::vector<codepoint_t> glyphs = font->get_glyphs(pass.text);
             // We will create 4 vertices & 6 indices for each glyph (GL_TRIANGLES)
             vertices.resize(vertices.size() + glyphs.size() * 4);
             indices.resize(indices.size() + glyphs.size() * 6);
             codepoint_t previous_glyph = 0;
             for (codepoint_t glyph : glyphs) {
                 GlyphAtlas::Entry entry = this->glyph_atlas.get(font, glyph);
                 float x0 = x + entry.glyph.x_offset;
                 float y0 = y + entry.glyph.y_offset - entry.glyph.height;
                 float x1 = x0 + entry.glyph.width;
                 float y1 = y0 + entry.glyph.height;
                 vertices[index*4 + 0] = {x0, y0, entry.u0, entry.v0};
                 vertices[index*4 + 1] = {x0, y1, entry.u0, entry.v1};
                 vertices[index*4 + 2] = {x1, y1, entry.u1, entry.v1};
                 vertices[index*4 + 3] = {x1, y0, entry.u1, entry.v0};
                 indices[index*6 + 0] = index*4 + 0;
                 indices[index*6 + 1] = index*4 + 1;
                 indices[index*6 + 2] = index*4 + 2;
                 indices[index*6 + 3] = index*4 + 2;
                 indices[index*6 + 4] = index*4 + 3;
                 indices[index*6 + 5] = index*4 + 0;
                 // Advance the pen position
                 x += entry.glyph.x_advance;
                 y += entry.glyph.y_advance;
                 // Handle font kerning
                 if (previous_glyph != 0) {
                     x += font->get_horizontal_kerning(previous_glyph, glyph);
                 }
                 index++;
                 num_elements += 6;
                 previous_glyph = glyph;
             }
         }
         text_render_task render_task{GL_TRIANGLES, batch.color, num_elements, offset};
         render_tasks.push_back(render_task);
         offset += num_elements;
     }
     // Upload vertices and indices
     glBindBuffer(GL_ARRAY_BUFFER, this->vbo);
     glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, this->ibo);
     glBufferData(GL_ARRAY_BUFFER, vertices.size() * sizeof(text_render_vertex), &vertices[0], GL_STATIC_DRAW);
     glBufferData(GL_ELEMENT_ARRAY_BUFFER, indices.size() * sizeof(unsigned int), &indices[0], GL_STATIC_DRAW);
     texturefont_shader::program->use();
     this->glyph_atlas.bind(0);
     glEnableVertexAttribArray(texturefont_shader::program->pos_id);
     glEnableVertexAttribArray(texturefont_shader::tex_coord);
     glVertexAttribPointer(texturefont_shader::program->pos_id, 2, GL_FLOAT, GL_FALSE,
         sizeof(text_render_vertex), (GLvoid *) offsetof(text_render_vertex, x));
     glVertexAttribPointer(texturefont_shader::tex_coord, 2, GL_FLOAT, GL_FALSE,
         sizeof(text_render_vertex), (GLvoid *) offsetof(text_render_vertex, u));
     for (auto &task : render_tasks) {
         glUniform4f(texturefont_shader::color,
             task.color.r/255.f, task.color.g/255.f, task.color.b/255.f, task.color.a/255.f);
         glDrawElements(task.mode, task.num_elements, GL_UNSIGNED_INT, (GLvoid *) (task.offset * sizeof(unsigned int)));
     }
     glDisableVertexAttribArray(texturefont_shader::program->pos_id);
     glDisableVertexAttribArray(texturefont_shader::tex_coord);
     texturefont_shader::program->stopusing();
     glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0);
     glBindBuffer(GL_ARRAY_BUFFER, 0);
     // Clear the render batches for next frame
     this->render_batches.clear();
 }
References openage::renderer::GlyphAtlas::bind(), openage::texturefont_shader::color, openage::renderer::text_render_task::color, openage::renderer::tests::font(), openage::renderer::TextRenderer::text_render_batch::font, openage::renderer::GlyphAtlas::get(), openage::renderer::GlyphAtlas::Entry::glyph, glyph_atlas, openage::renderer::Glyph::height, ibo, openage::move, openage::texturefont_shader::program, render_batches, openage::shader::Program::stopusing(), openage::texturefont_shader::tex_coord, openage::renderer::GlyphAtlas::Entry::u0, openage::renderer::GlyphAtlas::Entry::u1, openage::shader::Program::use(), openage::renderer::GlyphAtlas::Entry::v0, openage::renderer::GlyphAtlas::Entry::v1, vbo, openage::renderer::Glyph::width, openage::renderer::Glyph::x_advance, openage::renderer::Glyph::x_offset, openage::renderer::Glyph::y_advance, and openage::renderer::Glyph::y_offset.
set_color()
void openage::renderer::TextRenderer::set_color (const Color & color)
Set the color to be used for the future text draw calls.
Parameters
color the color to be used.
Definition at line 78 of file text.cpp.
{
     if (this->current_color == color) {
         return;
     }
     this->current_color = color;
     this->is_dirty = true;
 }
References openage::texturefont_shader::color, current_color, and is_dirty.
set_font()
void openage::renderer::TextRenderer::set_font (Font * font)
Set the font to be used for the future text draw calls.
Parameters
font the font to be used.
Definition at line 69 of file text.cpp.
{
     if (this->current_font == font) {
         return;
     }
     this->current_font = font;
     this->is_dirty = true;
 }
References current_font, openage::renderer::tests::font(), and is_dirty.
Referenced by openage::console::draw::to_opengl().
Member Data Documentation
current_color
Color openage::renderer::TextRenderer::current_color private
Definition at line 110 of file text.h.
Referenced by draw(), and set_color().
current_font
Font* openage::renderer::TextRenderer::current_font private
Definition at line 109 of file text.h.
Referenced by draw(), and set_font().
glyph_atlas
GlyphAtlas openage::renderer::TextRenderer::glyph_atlas private
Definition at line 114 of file text.h.
Referenced by render().
ibo
GLuint openage::renderer::TextRenderer::ibo private
Definition at line 117 of file text.h.
Referenced by render(), and ~TextRenderer().
is_dirty
bool openage::renderer::TextRenderer::is_dirty private
Definition at line 111 of file text.h.
Referenced by draw(), set_color(), and set_font().
render_batches
std::vector<text_render_batch> openage::renderer::TextRenderer::render_batches private
Definition at line 112 of file text.h.
Referenced by draw(), and render().
vbo
GLuint openage::renderer::TextRenderer::vbo private
Definition at line 116 of file text.h.
Referenced by render(), and ~TextRenderer().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/text.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/text.cpp