openage: openage::GameMainHandle Class Reference
openage::GameMainHandle Class Reference
Class linked to the QML object "GameMain" via GameMainLink.
#include <game_main.h>
Public Member Functions
GameMainHandle (qtsdl::GuiItemLink *gui_link)
void set_engine (Engine *engine)
void clear ()
End the game and delete the game handle.
void set_game (std::unique_ptr< GameMain > &&game)
Pass the given game to the engine and start it.
GameMain * get_game () const
Return the game.
bool is_game_running () const
Test if there is a game running.
void announce_running ()
Emit a qt signal to notify for changes in a running game.
Public Attributes
GameMainSignals gui_signals
qtsdl::GuiItemLink * gui_link
Private Attributes
GameMain * game
The game state as currently owned by the engine, just remembered here to access it quickly.
Engine * engine
The engine the main game handle is attached to.
Detailed Description
Class linked to the QML object "GameMain" via GameMainLink.
Gets instanciated from QML.
Definition at line 131 of file game_main.h.
Constructor & Destructor Documentation
GameMainHandle()
openage::GameMainHandle::GameMainHandle (qtsdl::GuiItemLink * gui_link) explicit
Definition at line 73 of file game_main.cpp.
     :
     game{},
     engine{},
     gui_link{gui_link} {
 }
Member Function Documentation
announce_running()
void openage::GameMainHandle::announce_running ()
Emit a qt signal to notify for changes in a running game.
Definition at line 115 of file game_main.cpp.
{
     emit this->gui_signals.game_running(this->game);
 }
References game, openage::GameMainSignals::game_running(), and gui_signals.
Referenced by clear(), and set_game().
clear()
void openage::GameMainHandle::clear ()
End the game and delete the game handle.
Definition at line 85 of file game_main.cpp.
{
     if (this->engine) {
         this->game = nullptr;
         this->engine->end_game();
         announce_running();
     }
 }
References announce_running(), openage::Engine::end_game(), engine, and game.
get_game()
GameMain * openage::GameMainHandle::get_game () const
Return the game.
Definition at line 107 of file game_main.cpp.
{
     return this->game;
 }
References game.
Referenced by openage::GameControl::set_engine().
is_game_running()
bool openage::GameMainHandle::is_game_running () const
Test if there is a game running.
Definition at line 111 of file game_main.cpp.
{
     return this->game != nullptr;
 }
References game.
set_engine()
void openage::GameMainHandle::set_engine (Engine * engine)
Definition at line 80 of file game_main.cpp.
{
     ENSURE(!this->engine || this->engine == engine, "relinking GameMain to another engine is not supported and not caught properly");
     this->engine = engine;
 }
References engine, and ENSURE.
Referenced by openage::gui::GameMainLink::set_engine().
set_game()
void openage::GameMainHandle::set_game (std::unique_ptr< GameMain > && game)
Pass the given game to the engine and start it.
Definition at line 93 of file game_main.cpp.
{
     if (this->engine) {
         ENSURE(game, "linking game to engine problem");
         // remember the pointer
         this->game = game.get();
         // then pass on the game to the engine
         this->engine->start_game(std::move(game));
         announce_running();
     }
 }
References announce_running(), engine, ENSURE, game, openage::move, and openage::Engine::start_game().
Member Data Documentation
engine
Engine* openage::GameMainHandle::engine private
The engine the main game handle is attached to.
Definition at line 172 of file game_main.h.
Referenced by clear(), set_engine(), and set_game().
game
GameMain* openage::GameMainHandle::game private
The game state as currently owned by the engine, just remembered here to access it quickly.
Definition at line 167 of file game_main.h.
Referenced by announce_running(), clear(), get_game(), is_game_running(), and set_game().
gui_link
qtsdl::GuiItemLink* openage::GameMainHandle::gui_link
Definition at line 176 of file game_main.h.
gui_signals
GameMainSignals openage::GameMainHandle::gui_signals
Definition at line 175 of file game_main.h.
Referenced by announce_running(), and openage::GameControl::set_game().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gamestate/game_main.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gamestate/game_main.cpp