openage: qtsdl::DeferredInitialConstantPropertyValues Class Reference
qtsdl::DeferredInitialConstantPropertyValues Class Reference
Stores static properties during initialization to be able to assign them after all 'liveReloadTag' properties are set.
#include <deferred_initial_constant_property_values.h>
Public Member Functions
DeferredInitialConstantPropertyValues ()
virtual ~DeferredInitialConstantPropertyValues ()
Is virtual to be able to catch the error when non-persistent item uses liveReloadTag.
void apply_static_properties ()
Execute saved static properties assignments (for newly created cores).
void clear_static_properties ()
Clear saved static properties assignments (for cores that existed before the GUI reload).
bool is_init_over () const
Protected Attributes
bool init_over
std::vector< std::function< void()> > static_properties_assignments
Detailed Description
Stores static properties during initialization to be able to assign them after all 'liveReloadTag' properties are set.
Definition at line 13 of file deferred_initial_constant_property_values.h.
Constructor & Destructor Documentation
DeferredInitialConstantPropertyValues()
qtsdl::DeferredInitialConstantPropertyValues::DeferredInitialConstantPropertyValues ()
Definition at line 7 of file deferred_initial_constant_property_values.cpp.
     :
     init_over{} {
 }
~DeferredInitialConstantPropertyValues()
qtsdl::DeferredInitialConstantPropertyValues::~DeferredInitialConstantPropertyValues () virtual
Is virtual to be able to catch the error when non-persistent item uses liveReloadTag.
Definition at line 12 of file deferred_initial_constant_property_values.cpp.
{
 }
Member Function Documentation
apply_static_properties()
void qtsdl::DeferredInitialConstantPropertyValues::apply_static_properties ()
Execute saved static properties assignments (for newly created cores).
Definition at line 15 of file deferred_initial_constant_property_values.cpp.
{
     for (const auto &f : this->static_properties_assignments)
         f();
     this->clear_static_properties();
     this->init_over = true;
 }
References clear_static_properties(), init_over, and static_properties_assignments.
clear_static_properties()
void qtsdl::DeferredInitialConstantPropertyValues::clear_static_properties ()
Clear saved static properties assignments (for cores that existed before the GUI reload).
Definition at line 23 of file deferred_initial_constant_property_values.cpp.
{
     this->static_properties_assignments.clear();
 }
References static_properties_assignments.
Referenced by apply_static_properties().
is_init_over()
bool qtsdl::DeferredInitialConstantPropertyValues::is_init_over () const
Definition at line 27 of file deferred_initial_constant_property_values.cpp.
{
     return this->init_over;
 }
References init_over.
Member Data Documentation
init_over
bool qtsdl::DeferredInitialConstantPropertyValues::init_over protected
Definition at line 35 of file deferred_initial_constant_property_values.h.
Referenced by apply_static_properties(), qtsdl::GuiItemMethods< GameSpecLink >::assign_while_catching_constant_properies_inits(), and is_init_over().
static_properties_assignments
std::vector<std::function<void()> > qtsdl::DeferredInitialConstantPropertyValues::static_properties_assignments protected
Definition at line 36 of file deferred_initial_constant_property_values.h.
Referenced by apply_static_properties(), qtsdl::GuiItemMethods< GameSpecLink >::assign_while_catching_constant_properies_inits(), and clear_static_properties().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/guisys/private/livereload/deferred_initial_constant_property_values.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/guisys/private/livereload/deferred_initial_constant_property_values.cpp