openage: openage::renderer::ShaderProgram Class Reference
openage::renderer::ShaderProgram Class Reference abstract
#include <shader_program.h>
Public Member Functions
virtual ~ShaderProgram ()=default
void update_uniform_input (UniformInput *)
void update_uniform_input (UniformInput *input, const char *unif, int32_t val)
void update_uniform_input (UniformInput *input, const char *unif, uint32_t val)
void update_uniform_input (UniformInput *input, const char *unif, float val)
void update_uniform_input (UniformInput *input, const char *unif, double val)
void update_uniform_input (UniformInput *input, const char *unif, Eigen::Vector2f const &val)
void update_uniform_input (UniformInput *input, const char *unif, Eigen::Vector3f const &val)
void update_uniform_input (UniformInput *input, const char *unif, Eigen::Vector4f const &val)
void update_uniform_input (UniformInput *input, const char *unif, Texture2d const *val)
void update_uniform_input (UniformInput *input, const char *unif, Texture2d *val)
void update_uniform_input (UniformInput *input, const char *unif, Eigen::Matrix4f const &val)
template<typename T >
void update_uniform_input (UniformInput *, const char *unif, T)
virtual bool has_uniform (const char *unif)=0
Returns whether the shader program contains a uniform variable with the given name.
template<typename... Ts>
std::unique_ptr< UniformInput > new_uniform_input (Ts... vals)
template<typename T , typename... Ts>
void update_uniform_input (UniformInput *input, const char *unif, T val, Ts... vals)
virtual std::map< size_t, resources::vertex_input_t > vertex_attributes () const =0
Protected Member Functions
virtual std::unique_ptr< UniformInput > new_unif_in ()=0
virtual void set_i32 (UniformInput *, const char *, int32_t)=0
virtual void set_u32 (UniformInput *, const char *, uint32_t)=0
virtual void set_f32 (UniformInput *, const char *, float)=0
virtual void set_f64 (UniformInput *, const char *, double)=0
virtual void set_v2f32 (UniformInput *, const char *, Eigen::Vector2f const &)=0
virtual void set_v3f32 (UniformInput *, const char *, Eigen::Vector3f const &)=0
virtual void set_v4f32 (UniformInput *, const char *, Eigen::Vector4f const &)=0
virtual void set_m4f32 (UniformInput *, const char *, Eigen::Matrix4f const &)=0
virtual void set_tex (UniformInput *, const char *, Texture2d const *)=0
Detailed Description
Definition at line 21 of file shader_program.h.
Constructor & Destructor Documentation
~ShaderProgram()
virtual openage::renderer::ShaderProgram::~ShaderProgram () virtual default
Member Function Documentation
has_uniform()
virtual bool openage::renderer::ShaderProgram::has_uniform (const char * unif) pure virtual
Returns whether the shader program contains a uniform variable with the given name.
Implemented in openage::renderer::opengl::GlShaderProgram.
new_unif_in()
virtual std::unique_ptr<UniformInput> openage::renderer::ShaderProgram::new_unif_in () protected pure virtual
Implemented in openage::renderer::opengl::GlShaderProgram.
Referenced by new_uniform_input().
new_uniform_input()
template<typename... Ts> std::unique_ptr<UniformInput> openage::renderer::ShaderProgram::new_uniform_input (Ts... vals) inline
Creates a new uniform input (a binding of uniform names to values) for this shader and optionally sets some uniform values. To do that, just pass two arguments -
a string literal and the value for that uniform for any uniform you want to set. For example new_uniform_input("color", { 0.5, 0.5, 0.5, 1.0 }, "num", 5) will set "color" to { 0.5, 0.5, 0.5, 0.5 } and "num" to 5. Types are important here and a type mismatch between the uniform variable and the input might result in an error.
Definition at line 83 of file shader_program.h.
{
         auto input = this->new_unif_in();
         this->update_uniform_input(input.get(), vals...);
         return input;
     }
References new_unif_in(), and update_uniform_input().
set_f32()
virtual void openage::renderer::ShaderProgram::set_f32 (UniformInput * , const char * , float) protected pure virtual
Implemented in openage::renderer::opengl::GlShaderProgram.
Referenced by update_uniform_input().
set_f64()
virtual void openage::renderer::ShaderProgram::set_f64 (UniformInput * , const char * , double) protected pure virtual
Implemented in openage::renderer::opengl::GlShaderProgram.
Referenced by update_uniform_input().
set_i32()
virtual void openage::renderer::ShaderProgram::set_i32 (UniformInput * , const char * , int32_t) protected pure virtual
Implemented in openage::renderer::opengl::GlShaderProgram.
Referenced by update_uniform_input().
set_m4f32()
virtual void openage::renderer::ShaderProgram::set_m4f32 (UniformInput * , const char * , Eigen::Matrix4f const &) protected pure virtual
Implemented in openage::renderer::opengl::GlShaderProgram.
Referenced by update_uniform_input().
set_tex()
virtual void openage::renderer::ShaderProgram::set_tex (UniformInput * , const char * , Texture2d const *) protected pure virtual
Implemented in openage::renderer::opengl::GlShaderProgram.
Referenced by update_uniform_input().
set_u32()
virtual void openage::renderer::ShaderProgram::set_u32 (UniformInput * , const char * , uint32_t) protected pure virtual
Implemented in openage::renderer::opengl::GlShaderProgram.
Referenced by update_uniform_input().
set_v2f32()
virtual void openage::renderer::ShaderProgram::set_v2f32 (UniformInput * , const char * , Eigen::Vector2f const &) protected pure virtual
Implemented in openage::renderer::opengl::GlShaderProgram.
Referenced by update_uniform_input().
set_v3f32()
virtual void openage::renderer::ShaderProgram::set_v3f32 (UniformInput * , const char * , Eigen::Vector3f const &) protected pure virtual
Implemented in openage::renderer::opengl::GlShaderProgram.
Referenced by update_uniform_input().
set_v4f32()
virtual void openage::renderer::ShaderProgram::set_v4f32 (UniformInput * , const char * , Eigen::Vector4f const &) protected pure virtual
Implemented in openage::renderer::opengl::GlShaderProgram.
Referenced by update_uniform_input().
update_uniform_input() [1/13]
void openage::renderer::ShaderProgram::update_uniform_input (UniformInput *) inline
Definition at line 26 of file shader_program.h.
 {}
Referenced by new_uniform_input(), and update_uniform_input().
update_uniform_input() [2/13]
void openage::renderer::ShaderProgram::update_uniform_input (UniformInput * input, const char * unif, int32_t val) inline
Definition at line 28 of file shader_program.h.
{
         this->set_i32(input, unif, val);
     }
References set_i32(), and val.
update_uniform_input() [3/13]
void openage::renderer::ShaderProgram::update_uniform_input (UniformInput * input, const char * unif, uint32_t val) inline
Definition at line 32 of file shader_program.h.
{
         this->set_u32(input, unif, val);
     }
References set_u32(), and val.
update_uniform_input() [4/13]
void openage::renderer::ShaderProgram::update_uniform_input (UniformInput * input, const char * unif, float val) inline
Definition at line 36 of file shader_program.h.
{
         this->set_f32(input, unif, val);
     }
References set_f32(), and val.
update_uniform_input() [5/13]
void openage::renderer::ShaderProgram::update_uniform_input (UniformInput * input, const char * unif, double val) inline
Definition at line 40 of file shader_program.h.
{
         this->set_f64(input, unif, val);
     }
References set_f64(), and val.
update_uniform_input() [6/13]
void openage::renderer::ShaderProgram::update_uniform_input (UniformInput * input, const char * unif, Eigen::Vector2f const & val) inline
Definition at line 44 of file shader_program.h.
{
         this->set_v2f32(input, unif, val);
     }
References set_v2f32(), and val.
update_uniform_input() [7/13]
void openage::renderer::ShaderProgram::update_uniform_input (UniformInput * input, const char * unif, Eigen::Vector3f const & val) inline
Definition at line 48 of file shader_program.h.
{
         this->set_v3f32(input, unif, val);
     }
References set_v3f32(), and val.
update_uniform_input() [8/13]
void openage::renderer::ShaderProgram::update_uniform_input (UniformInput * input, const char * unif, Eigen::Vector4f const & val) inline
Definition at line 52 of file shader_program.h.
{
         this->set_v4f32(input, unif, val);
     }
References set_v4f32(), and val.
update_uniform_input() [9/13]
void openage::renderer::ShaderProgram::update_uniform_input (UniformInput * input, const char * unif, Texture2d const * val) inline
Definition at line 56 of file shader_program.h.
{
         this->set_tex(input, unif, val);
     }
References set_tex(), and val.
update_uniform_input() [10/13]
void openage::renderer::ShaderProgram::update_uniform_input (UniformInput * input, const char * unif, Texture2d * val) inline
Definition at line 60 of file shader_program.h.
{
         this->set_tex(input, unif, val);
     }
References set_tex(), and val.
update_uniform_input() [11/13]
void openage::renderer::ShaderProgram::update_uniform_input (UniformInput * input, const char * unif, Eigen::Matrix4f const & val) inline
Definition at line 64 of file shader_program.h.
{
         this->set_m4f32(input, unif, val);
     }
References set_m4f32(), and val.
update_uniform_input() [12/13]
template<typename T > void openage::renderer::ShaderProgram::update_uniform_input (UniformInput * , const char * unif, T) inline
Definition at line 69 of file shader_program.h.
{
         throw Error(MSG(err) << "Tried to set uniform " << unif << " using unknown type.");
     }
References openage::log::err(), and MSG.
update_uniform_input() [13/13]
template<typename T , typename... Ts> void openage::renderer::ShaderProgram::update_uniform_input (UniformInput * input, const char * unif, T val, Ts... vals) inline
Updates the given uniform input with new uniform values similarly to new_uniform_input. For example, update_uniform_input(in, "awesome", true) will set the "awesome" uniform in addition to whatever values were in the uniform input before.
Definition at line 93 of file shader_program.h.
{
         this->update_uniform_input(input, unif, val);
         this->update_uniform_input(input, vals...);
     }
References update_uniform_input(), and val.
vertex_attributes()
virtual std::map<size_t, resources::vertex_input_t> openage::renderer::ShaderProgram::vertex_attributes () const pure virtual
Returns a list of active vertex attributes in the shader program. Active attributes are those which have an effect on the shader output, meaning they are included in the output calculation and are not unused. Inactive attributes may or may not be present in the list - in particular, in the OpenGL implementation they will most likely be missing. The returned value is a map from the attribute location to its type. Locations need not be consecutive.
Implemented in openage::renderer::opengl::GlShaderProgram.
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/shader_program.h