openage: openage::TerrainSearch Class Reference
openage::TerrainSearch Class Reference
searches outward from a point and returns nearby objects The state of the search is kept within the class, which allows a user to look at a limited number of tiles per update cycle
#include <terrain_search.h>
Public Member Functions
TerrainSearch (std::shared_ptr< Terrain > t, coord::tile s)
next_tile will cover all tiles on the map
TerrainSearch (std::shared_ptr< Terrain > t, coord::tile s, float radius)
next_tile will iterate over a range of tiles within a radius
~TerrainSearch ()=default
coord::tile start_tile () const
the tile the search began on
void reset ()
restarts the search from the start tile
coord::tile next_tile ()
returns all objects on the next tile
Private Attributes
const std::shared_ptr< Terrain > terrain
const coord::tile start
std::queue< coord::tile > tiles
std::unordered_set< coord::tile > visited
float previous_radius
float max_radius
Detailed Description
searches outward from a point and returns nearby objects The state of the search is kept within the class, which allows a user to look at a limited number of tiles per update cycle
Definition at line 37 of file terrain_search.h.
Constructor & Destructor Documentation
TerrainSearch() [1/2]
openage::TerrainSearch::TerrainSearch (std::shared_ptr< Terrain > t, coord::tile s)
next_tile will cover all tiles on the map
Definition at line 56 of file terrain_search.cpp.
     :
     TerrainSearch(t, s, .0f) {
 }
TerrainSearch() [2/2]
openage::TerrainSearch::TerrainSearch (std::shared_ptr< Terrain > t, coord::tile s, float radius)
next_tile will iterate over a range of tiles within a radius
Definition at line 61 of file terrain_search.cpp.
     :
     terrain{t},
     start(s),
     previous_radius{.0f},
     max_radius{radius} {
 }
~TerrainSearch()
openage::TerrainSearch::~TerrainSearch () default
Member Function Documentation
next_tile()
coord::tile openage::TerrainSearch::next_tile ()
returns all objects on the next tile
Definition at line 81 of file terrain_search.cpp.
{
     // conditions for returning to the initial tile
     if (this->tiles.empty() ||
         (this->max_radius && this->previous_radius > this->max_radius)) {
         this->reset();
     }
     coord::tile result = this->tiles.front();
     this->tiles.pop();
     for (auto i = 0; i < 4; ++i) {
         auto to_add = result + neigh_tile[i];
         // check not visited and tile is within map
         if (this->visited.count(to_add) == 0 && terrain->get_data(to_add)) {
             this->visited.insert(to_add);
             this->tiles.push(to_add);
         }
     }
     this->previous_radius = std::hypot(result.ne - start.ne, result.se - start.se);
     return result;
 }
References std::hypot(), max_radius, openage::neigh_tile, previous_radius, reset(), openage.testing.testing::result(), start, terrain, tiles, and visited.
Referenced by openage::find_in_radius(), and openage::find_near().
reset()
void openage::TerrainSearch::reset ()
restarts the search from the start tile
Definition at line 73 of file terrain_search.cpp.
{
     std::queue<coord::tile> empty;
     std::swap(this->tiles, empty);
     this->visited.clear();
     this->tiles.push(this->start);
     this->visited.insert(this->start);
 }
References tiles, and visited.
Referenced by next_tile().
start_tile()
coord::tile openage::TerrainSearch::start_tile () const
the tile the search began on
Definition at line 69 of file terrain_search.cpp.
{
     return this->start;
 }
References start.
Member Data Documentation
max_radius
float openage::TerrainSearch::max_radius private
Definition at line 70 of file terrain_search.h.
Referenced by next_tile().
previous_radius
float openage::TerrainSearch::previous_radius private
Definition at line 70 of file terrain_search.h.
Referenced by next_tile().
start
const coord::tile openage::TerrainSearch::start private
Definition at line 67 of file terrain_search.h.
Referenced by next_tile(), openage.util.filelike.stream.StreamFragment::read(), and start_tile().
terrain
const std::shared_ptr<Terrain> openage::TerrainSearch::terrain private
Definition at line 66 of file terrain_search.h.
Referenced by next_tile().
tiles
std::queue<coord::tile> openage::TerrainSearch::tiles private
Definition at line 68 of file terrain_search.h.
Referenced by next_tile(), and reset().
visited
std::unordered_set<coord::tile> openage::TerrainSearch::visited private
Definition at line 69 of file terrain_search.h.
Referenced by next_tile(), and reset().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/terrain/terrain_search.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/terrain/terrain_search.cpp