openage: openage::renderer::vulkan::VlkWindow Class Reference
openage::renderer::vulkan::VlkWindow Class Reference
#include <windowvk.h>
Public Member Functions
VlkWindow (const char *title)
~VlkWindow ()
VkInstance get_instance () const
VkSurfaceKHR get_surface () const
Public Member Functions inherited from openage::renderer::Window
virtual ~Window ()=default
std::pair< size_t, size_t > get_size () const
Returns the dimensions of this window.
bool should_close () const
Returns true if this window should be closed.
void add_key_callback (const key_cb_t &)
void add_mouse_button_callback (const mouse_button_cb_t &)
void add_mouse_wheel_callback (const mouse_wheel_cb_t &)
void add_resize_callback (const resize_cb_t &)
virtual void set_size (size_t width, size_t height)=0
Force the window to the given size.
virtual void update ()=0
Polls for window events, calls callbacks for these events, swaps front and back framebuffers to present graphics onto screen.
virtual std::unique_ptr< Renderer > make_renderer ()=0
Creates a renderer which uses the window's graphics API and targets the window.
Private Attributes
vlk_capabilities capabilities
VkInstance instance
VkSurfaceKHR surface
VkDebugReportCallbackEXT debug_callback
VlkLoader loader
SDL_Window * window
Additional Inherited Members
Public Types inherited from openage::renderer::Window
using key_cb_t = std::function< void(SDL_KeyboardEvent const &)>
using mouse_button_cb_t = std::function< void(SDL_MouseButtonEvent const &)>
using mouse_wheel_cb_t = std::function< void(SDL_MouseWheelEvent const &)>
using resize_cb_t = std::function< void(size_t, size_t)>
Protected Member Functions inherited from openage::renderer::Window
Window (size_t width, size_t height)
Protected Attributes inherited from openage::renderer::Window
bool should_be_closed = false
std::pair< size_t, size_t > size
The current size of the framebuffer.
std::vector< key_cb_t > on_key
std::vector< mouse_button_cb_t > on_mouse_button
std::vector< mouse_wheel_cb_t > on_mouse_wheel
std::vector< resize_cb_t > on_resize
Detailed Description
Definition at line 30 of file windowvk.h.
Constructor & Destructor Documentation
VlkWindow()
openage::renderer::vulkan::VlkWindow::VlkWindow (const char * title)
Definition at line 80 of file windowvk.cpp.
     : Window(800, 600)
     , capabilities(find_capabilities())
 {
     make_sdl_available();
     this->window = SDL_CreateWindow(
         title,
         SDL_WINDOWPOS_CENTERED,
         SDL_WINDOWPOS_CENTERED,
         this->size.first,
         this->size.second,
         SDL_WINDOW_OPENGL | SDL_WINDOW_RESIZABLE | SDL_WINDOW_MAXIMIZED
     );
     if (this->window == nullptr) {
         throw Error{MSG(err) << "Failed to create SDL window: " << SDL_GetError()};
     }
     // Find which extensions the SDL window requires.
     auto extension_names = vk_do_ritual(SDL_Vulkan_GetInstanceExtensions, this->window);
     /*
     if (succ != SDL_TRUE) {
         throw Error(MSG(err) << "Failed to obtain required Vulkan extension names from SDL.");
     }
     */
 #ifndef NDEBUG
     extension_names.push_back(VK_EXT_DEBUG_REPORT_EXTENSION_NAME);
 #endif
     extension_names.push_back(VK_KHR_SURFACE_EXTENSION_NAME);
     // Check if all extensions are available.
     for (auto ext : extension_names) {
         if (this->capabilities.extensions.count(ext) == 0) {
             throw Error(MSG(err) << "Vulkan driver is missing required extension: " << ext);
         }
     }
     // The names of Vulkan layers which we need.
     std::vector<const char*> layer_names;
 #ifndef NDEBUG
     layer_names.push_back("VK_LAYER_LUNARG_standard_validation");
 #endif
     // Check if all layers are available
     for (auto lr : layer_names) {
         if (this->capabilities.layers.count(lr) == 0) {
             throw Error(MSG(err) << "Vulkan driver is missing required layer: " << lr);
         }
     }
     // Setup application description.
     VkApplicationInfo app_info  = {};
     app_info.sType = VK_STRUCTURE_TYPE_APPLICATION_INFO;
     app_info.pApplicationName = title;
     app_info.apiVersion = VK_MAKE_VERSION(1, 0, 57);
     VkInstanceCreateInfo inst_info = {};
     inst_info.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
     inst_info.pApplicationInfo = &app_info;
     inst_info.enabledExtensionCount = extension_names.size();
     inst_info.ppEnabledExtensionNames = extension_names.data();
     inst_info.enabledLayerCount = layer_names.size();
     inst_info.ppEnabledLayerNames = layer_names.data();
     // A Vulkan instance is a proxy for all usage of Vulkan from our application,
     // kind of like a GL context. Initialize it.
     VK_CALL_CHECKED(vkCreateInstance, &inst_info, nullptr, &this->instance);
     this->loader.init(this->instance);
 #ifndef NDEBUG
     VkDebugReportCallbackCreateInfoEXT cb_info = {};
     cb_info.sType = VK_STRUCTURE_TYPE_DEBUG_REPORT_CALLBACK_CREATE_INFO_EXT;
     cb_info.flags =
     VK_DEBUG_REPORT_ERROR_BIT_EXT
     | VK_DEBUG_REPORT_WARNING_BIT_EXT
     | VK_DEBUG_REPORT_PERFORMANCE_WARNING_BIT_EXT
     | VK_DEBUG_REPORT_INFORMATION_BIT_EXT
     | VK_DEBUG_REPORT_DEBUG_BIT_EXT;
     cb_info.pfnCallback = vlk_debug_cb;
     VK_CALL_CHECKED(this->loader.vkCreateDebugReportCallbackEXT, this->instance, &cb_info, nullptr, &this->debug_callback);
 #endif
     // Surface is an object that we draw into, corresponding to the window area.
     auto succ = SDL_Vulkan_CreateSurface(this->window, this->instance, &this->surface);
     if (succ != SDL_TRUE) {
         throw Error(MSG(err) << "Failed to create Vulkan surface on SDL window.");
     }
 }
References capabilities, openage::log::err(), openage::renderer::vulkan::vlk_capabilities::extensions, openage::renderer::vulkan::VlkLoader::init(), instance, openage::renderer::vulkan::vlk_capabilities::layers, loader, openage::renderer::make_sdl_available(), MSG, openage::renderer::Window::size, surface, VK_CALL_CHECKED, vk_do_ritual(), openage::renderer::vulkan::VlkLoader::vkCreateDebugReportCallbackEXT(), openage::renderer::vulkan::vlk_debug_cb(), and window.
~VlkWindow()
openage::renderer::vulkan::VlkWindow::~VlkWindow ()
Definition at line 173 of file windowvk.cpp.
                       {
 #ifndef NDEBUG
     this->loader.vkDestroyDebugReportCallbackEXT(this->instance, this->debug_callback, nullptr);
 #endif
     vkDestroySurfaceKHR(this->instance, this->surface, nullptr);
     vkDestroyInstance(this->instance, nullptr);
 }
References debug_callback, instance, loader, surface, and openage::renderer::vulkan::VlkLoader::vkDestroyDebugReportCallbackEXT().
Member Function Documentation
get_instance()
VkInstance openage::renderer::vulkan::VlkWindow::get_instance () const
Definition at line 181 of file windowvk.cpp.
{
     return this->instance;
 }
References instance.
get_surface()
VkSurfaceKHR openage::renderer::vulkan::VlkWindow::get_surface () const
Definition at line 185 of file windowvk.cpp.
{
     return this->surface;
 }
References surface.
Member Data Documentation
capabilities
vlk_capabilities openage::renderer::vulkan::VlkWindow::capabilities private
Definition at line 31 of file windowvk.h.
Referenced by VlkWindow().
debug_callback
VkDebugReportCallbackEXT openage::renderer::vulkan::VlkWindow::debug_callback private
Definition at line 36 of file windowvk.h.
Referenced by ~VlkWindow().
instance
VkInstance openage::renderer::vulkan::VlkWindow::instance private
Definition at line 33 of file windowvk.h.
Referenced by get_instance(), VlkWindow(), and ~VlkWindow().
loader
VlkLoader openage::renderer::vulkan::VlkWindow::loader private
Definition at line 38 of file windowvk.h.
Referenced by VlkWindow(), and ~VlkWindow().
surface
VkSurfaceKHR openage::renderer::vulkan::VlkWindow::surface private
Definition at line 34 of file windowvk.h.
Referenced by get_surface(), VlkWindow(), and ~VlkWindow().
window
SDL_Window* openage::renderer::vulkan::VlkWindow::window private
Definition at line 40 of file windowvk.h.
Referenced by VlkWindow().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/vulkan/windowvk.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/vulkan/windowvk.cpp