openage: qtsdl::GameLogicCaller Class Reference
qtsdl::GameLogicCaller Class Reference
Attaches to the GuiCallbackImpl.
#include <game_logic_caller.h>
Signals
void in_game_logic_thread (const std::function< void()> &f) const
void in_game_logic_thread_blocking (const std::function< void()> &f) const
Public Member Functions
GameLogicCaller ()
void set_game_logic_callback (GuiCallback *game_logic_callback)
Set up signal to be able to run code in the game logic thread.
Detailed Description
Attaches to the GuiCallbackImpl.
Definition at line 16 of file game_logic_caller.h.
Constructor & Destructor Documentation
GameLogicCaller()
qtsdl::GameLogicCaller::GameLogicCaller () explicit
Definition at line 9 of file game_logic_caller.cpp.
     :
     QObject{} {
 }
Member Function Documentation
in_game_logic_thread
void qtsdl::GameLogicCaller::in_game_logic_thread (const std::function< void()> & f) const signal
Referenced by qtsdl::GuiItemMethods< GameSpecLink >::assign_while_catching_constant_properies_inits(), qtsdl::GuiItemMethods< GameSpecLink >::i(), and set_game_logic_callback().
in_game_logic_thread_blocking
void qtsdl::GameLogicCaller::in_game_logic_thread_blocking (const std::function< void()> & f) const signal
Referenced by set_game_logic_callback().
set_game_logic_callback()
void qtsdl::GameLogicCaller::set_game_logic_callback (GuiCallback * game_logic_callback)
Set up signal to be able to run code in the game logic thread.
Definition at line 14 of file game_logic_caller.cpp.
{
     QObject::disconnect(this, &GameLogicCaller::in_game_logic_thread, 0, 0);
     QObject::disconnect(this, &GameLogicCaller::in_game_logic_thread_blocking, 0, 0);
     QObject::connect(this, &GameLogicCaller::in_game_logic_thread, game_logic_callback, &GuiCallback::process);
     QObject::connect(this, &GameLogicCaller::in_game_logic_thread_blocking, game_logic_callback, &GuiCallback::process_blocking, Qt::DirectConnection);
 }
References in_game_logic_thread(), in_game_logic_thread_blocking(), qtsdl::GuiCallback::process(), and qtsdl::GuiCallback::process_blocking().
Referenced by qtsdl::GuiItemBase::set_game_logic_callback().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/guisys/private/game_logic_caller.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/guisys/private/game_logic_caller.cpp