openage: openage::error::StackAnalyzer Class Reference
openage::error::StackAnalyzer Class Reference
#include <stackanalyzer.h>
Public Member Functions
StackAnalyzer ()=default
void analyze ()
void get_symbols (std::function< void(const backtrace_symbol *)> cb, bool reversed) const override
void trim_to_current_stack_frame () override
Public Member Functions inherited from openage::error::Backtrace
virtual ~Backtrace ()=default
Public Attributes
std::vector< void * > stack_addrs
Detailed Description
Implementation of the Backtrace interface that analyzes the current C++ stack.
The Usage is:
StackAnalyzer sa; sa.analyze();
Integrating analyze() into the constructor would be a bad idea because then, all sorts of allocators and other gory constructor internals might be visible in the Backtrace.
The implementation of analyze() and get_symbols() may use all sorts of analyzers, depending on what's available on the platform. The quality of the resolved symbol names may vary accordingly.
Definition at line 27 of file stackanalyzer.h.
Constructor & Destructor Documentation
StackAnalyzer()
openage::error::StackAnalyzer::StackAnalyzer () default
Creates an empty StackAnalyzer object.
Member Function Documentation
analyze()
void openage::error::StackAnalyzer::analyze ()
Definition at line 222 of file stackanalyzer.cpp.
{
     // unfortunately, backtrace won't tell us how big our buffer
     // needs to be, so we have no choice but to try until it
     // reports success.
     std::vector<void *> buffer{64};
     while (true) {
         int elements = backtrace(buffer.data(), buffer.size());
         // the buffer was large enough, so stop resizing.
         if (elements < (ssize_t) buffer.size()) {
             buffer.resize(elements);
             break;
         }
         else {
             buffer.resize(buffer.size() * 2);
         }
     }
     // now store the result, cut off at the front and back.
     size_t idx = 0;
     for (void *element : buffer) {
         // start storing after skipping skip the first few frames
         // so that e.g. this function does not show up in the trace.
         // (most-recent-call)
         if (idx >= base_skip_frames) {
             this->stack_addrs.push_back(element);
         }
         idx += 1;
     }
     // remove some libc-garbage-frames (least-recent-call)
     for (uint64_t i = 0; i < skip_entry_frames; i++) {
         this->stack_addrs.pop_back();
     }
 }
References openage::error::base_skip_frames, and openage::error::skip_entry_frames.
Referenced by openage::error::terminate_handler(), and trim_to_current_stack_frame().
get_symbols()
void openage::error::StackAnalyzer::get_symbols (std::function< void(const backtrace_symbol *)> cb, bool reversed) const override virtual
Returns (via the callback) symbolic names for all stack frames, to its best knowledge.
The most recent call is returned last (alike Python).
Parameters
cb is called for every symbol in the backtrace, starting with the top-most frame.
reversed if true, the most recent call is given last.
Implements openage::error::Backtrace.
Definition at line 268 of file stackanalyzer.cpp.
{
     backtrace_symbol symbol;
     symbol.filename = "";
     symbol.lineno = 0;
     if (reversed) {
         // `for (auto pc : this->stack_addrs | <ranges-ns>::view::reverse)` after Ranges-TS
         for (size_t idx = this->stack_addrs.size(); idx-- > 0;) {
             void *pc = this->stack_addrs[idx];
             symbol.functionname = util::symbol_name(pc, false, true);
             symbol.pc = pc;
             cb(&symbol);
         }
     }
     else {
         for (void *pc : this->stack_addrs) {
             symbol.functionname = util::symbol_name(pc, false, true);
             symbol.pc = pc;
             cb(&symbol);
         }
     }
 }
References openage::error::backtrace_symbol::filename, openage::error::backtrace_symbol::functionname, openage::error::backtrace_symbol::lineno, openage::error::backtrace_symbol::pc, and openage::util::symbol_name().
trim_to_current_stack_frame()
void openage::error::StackAnalyzer::trim_to_current_stack_frame () override virtual
Removes all the lower frames that are also present in the current stack.
Designed to be used in catch clauses, to simulate stack trace collection from throw to catch, instead of from throw to the process entry point.
Defaults to no-op.
Reimplemented from openage::error::Backtrace.
Definition at line 305 of file stackanalyzer.cpp.
{
     StackAnalyzer current;
     current.analyze();
     while (not current.stack_addrs.empty() and not this->stack_addrs.empty()) {
         if (this->stack_addrs.back() != current.stack_addrs.back()) {
             break;
         }
         this->stack_addrs.pop_back();
         current.stack_addrs.pop_back();
     }
 }
References analyze(), and stack_addrs.
Member Data Documentation
stack_addrs
std::vector<void *> openage::error::StackAnalyzer::stack_addrs
All program counters of this backtrace.
Definition at line 43 of file stackanalyzer.h.
Referenced by trim_to_current_stack_frame().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/error/stackanalyzer.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/error/stackanalyzer.cpp