openage: openage::util::ExternalProfiler Class Reference
openage::util::ExternalProfiler Class Reference
#include <externalprofiler.h>
Public Member Functions
ExternalProfiler ()
void start ()
void stop ()
void show_results ()
Public Attributes
bool currently_profiling
const bool can_profile
Static Public Attributes
static const char *const profiling_filename = "/tmp/openage-gperftools-cpuprofile"
static const char *const profiling_pdf_filename = "/tmp/openage-gperftools-cpuprofile.pdf"
Detailed Description
Definition at line 8 of file externalprofiler.h.
Constructor & Destructor Documentation
ExternalProfiler()
openage::util::ExternalProfiler::ExternalProfiler ()
Definition at line 22 of file externalprofiler.cpp.
     :
     currently_profiling{false},
     can_profile{WITH_GPERFTOOLS_PROFILER} {}
Member Function Documentation
show_results()
void openage::util::ExternalProfiler::show_results ()
Definition at line 72 of file externalprofiler.cpp.
{
     if (not this->can_profile) {
         log::log(MSG(err) << "Can not profile: gperftools is missing");
         return;
     }
     if (this->currently_profiling) {
         log::log(MSG(warn) << "Profiler is currently running; trying to show results anyway");
     }
 #if WITH_GPERFTOOLS_PROFILER
     std::string pprof_path = subprocess::which("google-pprof");
     // fallback to pprof
     if (pprof_path.size() == 0) {
         pprof_path = subprocess::which("pprof");
     }
     if (pprof_path.size() == 0) {
         log::log(ERR << "Can not process profiling results: google-pprof or pprof not found in PATH");
         return;
     }
     int retval = subprocess::call(
         {
             pprof_path.c_str(),
             "--pdf",
             "--",
             os::self_exec_filename().c_str(),
             this->profiling_filename,
             nullptr
         },
         true,
         this->profiling_pdf_filename);
     if (retval != 0) {
         log::log(MSG(err) << "Profile analysis failed: " << retval);
         return;
     }
     retval = os::execute_file(this->profiling_pdf_filename);
     if (retval != 0) {
         log::log(MSG(err) <<
             "Could not view profiling visualization " <<
             this->profiling_pdf_filename << ": " << retval);
         return;
     }
 #endif
 }
References openage::subprocess::call(), can_profile, currently_profiling, openage::log::err(), ERR, openage::os::execute_file(), openage::log::log(), MSG, profiling_filename, profiling_pdf_filename, openage::os::self_exec_filename(), openage::log::warn(), and openage::subprocess::which().
start()
void openage::util::ExternalProfiler::start ()
Definition at line 32 of file externalprofiler.cpp.
{
     if (not this->can_profile) {
         log::log(MSG(err) << "Can not profile: gperftools is missing");
         return;
     }
     if (this->currently_profiling) {
         log::log(MSG(info) << "Profiler is already running");
         return;
     }
     log::log(MSG(info) << "Starting profiler; writing data to " << this->profiling_filename);
     this->currently_profiling = true;
 #if WITH_GPERFTOOLS_PROFILER
     ProfilerStart(this->profiling_filename);
 #endif
 }
References can_profile, currently_profiling, openage::log::err(), openage::log::info(), openage::log::log(), MSG, and profiling_filename.
stop()
void openage::util::ExternalProfiler::stop ()
Definition at line 52 of file externalprofiler.cpp.
{
     if (not this->can_profile) {
         log::log(MSG(err) << "Can not profile: gperftools is missing");
         return;
     }
     if (not this->currently_profiling) {
         log::log(MSG(err) << "Profiler is not currently running");
         return;
     }
     this->currently_profiling = false;
 #if WITH_GPERFTOOLS_PROFILER
     ProfilerStop();
 #endif
     log::log(MSG(info) << "Profiler stopped; data written to " << this->profiling_filename);
 }
References can_profile, currently_profiling, openage::log::err(), openage::log::info(), openage::log::log(), MSG, and profiling_filename.
Member Data Documentation
can_profile
const bool openage::util::ExternalProfiler::can_profile
Definition at line 16 of file externalprofiler.h.
Referenced by show_results(), start(), and stop().
currently_profiling
bool openage::util::ExternalProfiler::currently_profiling
Definition at line 15 of file externalprofiler.h.
Referenced by show_results(), start(), and stop().
profiling_filename
const char *const openage::util::ExternalProfiler::profiling_filename = "/tmp/openage-gperftools-cpuprofile" static
Definition at line 12 of file externalprofiler.h.
Referenced by show_results(), start(), and stop().
profiling_pdf_filename
const char *const openage::util::ExternalProfiler::profiling_pdf_filename = "/tmp/openage-gperftools-cpuprofile.pdf" static
Definition at line 13 of file externalprofiler.h.
Referenced by show_results().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/externalprofiler.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/externalprofiler.cpp