openage: openage::Score Class Reference
openage::Score Class Reference
Keeps track of a score and all the sub-scores.
#include <score.h>
Public Member Functions
Score ()
void add_score (const score_category cat, double value)
void add_score (const score_category cat, int value)
void remove_score (const score_category cat, double value)
void remove_score (const score_category cat, int value)
void update_map_explored (double progress)
Updates map exploration precentance based sub-scores.
void update_resources (const ResourceBundle &resources)
Updates resource based sub-scores.
virtual void update_score ()
Calculates the total score from the sub-scores.
int get_score (const score_category cat) const
int get_score (const int index) const
int get_score_total () const
Protected Attributes
int score [static_cast< int >(score_category::SCORE_CATEGORY_COUNT)]
int score_total
Private Attributes
int score_exploration
Used by update_map_explored.
int score_resources
Used by update_resources.
Detailed Description
Keeps track of a score and all the sub-scores.
Definition at line 33 of file score.h.
Constructor & Destructor Documentation
Score()
openage::Score::Score ()
Definition at line 12 of file score.cpp.
     :
     score{0},
     score_total{0},
     score_exploration{0},
     score_resources{0} {
 }
Member Function Documentation
add_score() [1/2]
void openage::Score::add_score (const score_category cat, double value)
Definition at line 20 of file score.cpp.
{
     this->add_score(cat, (int) std::lround(value));
 }
Referenced by openage::Player::active_unit_added(), openage::Player::killed_unit(), update_map_explored(), and update_resources().
add_score() [2/2]
void openage::Score::add_score (const score_category cat, int value)
Definition at line 24 of file score.cpp.
{
     this->score[static_cast<int>(cat)] += value;
     this->update_score();
 }
References score, and update_score().
get_score() [1/2]
int openage::Score::get_score (const score_category cat) const inline
Definition at line 62 of file score.h.
 { return score[static_cast<int>(cat)]; }
References score.
Referenced by update_score().
get_score() [2/2]
int openage::Score::get_score (const int index) const inline
Definition at line 63 of file score.h.
 { return score[index]; }
References score.
get_score_total()
int openage::Score::get_score_total () const inline
Definition at line 65 of file score.h.
 { return score_total; }
References score_total.
remove_score() [1/2]
void openage::Score::remove_score (const score_category cat, double value)
Definition at line 29 of file score.cpp.
{
     this->remove_score(cat, (int) std::lround(value));
 }
Referenced by openage::Player::active_unit_removed(), update_map_explored(), and update_resources().
remove_score() [2/2]
void openage::Score::remove_score (const score_category cat, int value)
Definition at line 33 of file score.cpp.
{
     this->score[static_cast<int>(cat)] -= value;
     this->update_score();
 }
References score, and update_score().
update_map_explored()
void openage::Score::update_map_explored (double progress)
Updates map exploration precentance based sub-scores.
Definition at line 38 of file score.cpp.
{
     this->remove_score(score_category::technology, this->score_exploration);
     this->score_exploration = progress * 1000;
     this->add_score(score_category::technology, this->score_exploration);
 }
References add_score(), remove_score(), score_exploration, and openage::technology.
update_resources()
void openage::Score::update_resources (const ResourceBundle & resources)
Updates resource based sub-scores.
Definition at line 44 of file score.cpp.
{
     this->remove_score(score_category::economy, this->score_resources);
     this->score_resources = resources.sum() * 0.1;
     this->add_score(score_category::economy, this->score_resources);
 }
References add_score(), openage::economy, remove_score(), score_resources, and openage::ResourceBundle::sum().
Referenced by openage::Player::on_resources_change().
update_score()
void openage::Score::update_score () virtual
Calculates the total score from the sub-scores.
Todo:
update gui here
Reimplemented in openage::TeamScore, and openage::PlayerScore.
Definition at line 50 of file score.cpp.
{
     this->score_total = 0;
     for (int i = 0; i < static_cast<int>(score_category::SCORE_CATEGORY_COUNT); i++) {
         this->score_total += this->get_score(i);
     }
 }
References get_score(), openage::SCORE_CATEGORY_COUNT, and score_total.
Referenced by add_score(), remove_score(), openage::PlayerScore::update_score(), and openage::TeamScore::update_score().
Member Data Documentation
score
int openage::Score::score[static_cast< int >(score_category::SCORE_CATEGORY_COUNT)] protected
Definition at line 69 of file score.h.
Referenced by add_score(), get_score(), remove_score(), and openage::TeamScore::update_score().
score_exploration
int openage::Score::score_exploration private
Used by update_map_explored.
Definition at line 78 of file score.h.
Referenced by update_map_explored().
score_resources
int openage::Score::score_resources private
Used by update_resources.
Definition at line 81 of file score.h.
Referenced by update_resources().
score_total
int openage::Score::score_total protected
Definition at line 73 of file score.h.
Referenced by get_score_total(), and update_score().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gamestate/score.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gamestate/score.cpp