openage: openage::renderer::FontManager Class Reference
openage::renderer::FontManager Class Reference
#include <font_manager.h>
Public Member Functions
FontManager ()
~FontManager ()
FT_Library get_ft_library ()
Font * get_font (const char *family, const char *style, unsigned int size)
Font * get_font (const char *font_file, unsigned int size)
Static Public Member Functions
static std::string get_font_filename (const char *family, const char *style)
Private Attributes
FreeTypeLibrary library
std::unordered_map< size_t, std::unique_ptr< Font > > fonts
Detailed Description
Definition at line 44 of file font_manager.h.
Constructor & Destructor Documentation
FontManager()
openage::renderer::FontManager::FontManager ()
Definition at line 49 of file font_manager.cpp.
{
     // Empty
 }
~FontManager()
openage::renderer::FontManager::~FontManager ()
Definition at line 53 of file font_manager.cpp.
{
     // Empty
 }
Member Function Documentation
get_font() [1/2]
Font * openage::renderer::FontManager::get_font (const char * family, const char * style, unsigned int size)
Retrieves a font.
Parameters
family The font family.
style The font style.
size The size of the font in points.
Returns
The pointer to font instance.
Definition at line 61 of file font_manager.cpp.
{
     std::string font_filename = FontManager::get_font_filename(family, style);
     return this->get_font(font_filename.c_str(), size);
 }
References get_font_filename().
get_font() [2/2]
Font * openage::renderer::FontManager::get_font (const char * font_file, unsigned int size)
Retrieves a font.
Parameters
font_file The path to font's file.
size The size of the font in points.
Returns
The pointer to font instance.
Definition at line 66 of file font_manager.cpp.
{
     // Check if the font was already created
     font_description fd{font_file, size};
     size_t key = std::hash<font_description>()(fd);
     auto it = this->fonts.find(key);
     if (it != this->fonts.end()) {
         return it->second.get();
     }
     // Create a new font
     std::unique_ptr<Font> font = std::make_unique<Font>(this, fd);
     auto inserted = this->fonts.emplace(key, std::move(font));
     return inserted.first->second.get();
 }
References openage::renderer::tests::font(), fonts, and openage::move.
get_font_filename()
std::string openage::renderer::FontManager::get_font_filename (const char * family, const char * style) static
Gets the filepath of a particular font family and style.
Parameters
family The font family.
style The font style.
Returns
The path to font's file.
Definition at line 14 of file font_manager.cpp.
{
     // Initialize fontconfig
     if (!FcInit()) {
         throw Error{ERR << "Failed to initialize fontconfig."};
     }
     FcPattern *font_pattern = FcPatternBuild(nullptr, FC_FAMILY, FcTypeString, family, nullptr);
     FcPatternBuild(font_pattern, FC_STYLE, FcTypeString, style, nullptr);
     FcChar8 *query_string = FcNameUnparse(font_pattern);
     log::log(DBG << "Font queried: " << query_string);
     free(query_string);
     // tell fontconfig to find the best match
     FcResult font_match_result;
     FcPattern *font_match = FcFontMatch(nullptr, font_pattern, &font_match_result);
     // get attibute FC_FILE (= filename) of best-matched font
     FcChar8 *font_filename_tmp;
     if (FcPatternGetString(font_match, FC_FILE, 0, &font_filename_tmp) != FcResultMatch) {
         throw Error(ERR << "Fontconfig could not provide font " << family << " " << style);
     }
     std::string font_filename{reinterpret_cast<char *>(font_filename_tmp)};
     log::log(DBG << "Font file: " << font_filename);
     // deinitialize fontconfig.
     FcPatternDestroy(font_match);
     FcPatternDestroy(font_pattern);
     FcFini();
     return font_filename;
 }
References DBG, ERR, and openage::log::log().
Referenced by openage::renderer::font_description::font_description(), and get_font().
get_ft_library()
FT_Library openage::renderer::FontManager::get_ft_library ()
Get the freetype library instance.
Definition at line 57 of file font_manager.cpp.
{
     return this->library.ft_library;
 }
References openage::renderer::FreeTypeLibrary::ft_library, and library.
Member Data Documentation
fonts
std::unordered_map<size_t, std::unique_ptr<Font> > openage::renderer::FontManager::fonts private
Definition at line 90 of file font_manager.h.
Referenced by get_font().
library
FreeTypeLibrary openage::renderer::FontManager::library private
Definition at line 87 of file font_manager.h.
Referenced by get_ft_library().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/font/font_manager.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/font/font_manager.cpp