openage: openage::util::CSVCollection Class Reference
openage::util::CSVCollection Class Reference
#include <csv.h>
Public Types
using csv_file_map_t = std::unordered_map< std::string, std::vector< std::string > >
Public Member Functions
CSVCollection (const Path &entryfile)
virtual ~CSVCollection ()=default
template<class lineformat >
std::vector< lineformat > read (const std::string &filename) const
template<typename lineformat >
std::vector< lineformat > get_data (const std::string &filename) const
Protected Attributes
csv_file_map_t data
Detailed Description
Collection of multiple csv files. Read from a packed csv that contains all the data.
Then, data can be read recursively.
Definition at line 28 of file csv.h.
Member Typedef Documentation
csv_file_map_t
using openage::util::CSVCollection::csv_file_map_t = std::unordered_map<std::string, std::vector<std::string> >
Type for storing csv data: {filename: [line, ...]}.
Definition at line 35 of file csv.h.
Constructor & Destructor Documentation
CSVCollection()
openage::util::CSVCollection::CSVCollection (const Path & entryfile) explicit
Initialize the collection by reading the given file. This file must contain the data that this collection is made up of.
Definition at line 16 of file csv.cpp.
{
     auto file = entryfile_path.open();
     log::log(DBG << "Loading csv collection: " << file);
     // The file format is defined in:
     // openage/convert/dataformat/data_definition.py
     // example:
     //
     // ### some/folder/and/filename.docx
     // # irrelevant
     // # comments
     // data,stuff,moar,bla
     // store the currently read file name
     std::string current_file;
     for (auto &line : file.get_lines()) {
         // a new file starts:
         if (line[0] == '#' and
             line[1] == '#' and
             line[2] == '#' and
             line[3] == ' ') {
             // remove the "### "
             current_file = (line.erase(0, 4));
             // create a vector to put lines in
             this->data.emplace(current_file, std::vector<std::string>{});
         }
         else {
             if (line.empty() or line[0] == '#') {
                 continue;
             }
             if (likely(current_file.size() > 0)) {
                 // add line to the current file linelist
                 this->data.at(current_file).push_back(line);
             }
             else {
                 throw Error{
                     ERR << "csv collection content encountered "
                         << "without known target in " << entryfile_path
                         << ", linedata: " << line
                 };
             }
         }
     }
     log::log(INFO << "Loaded multi-csv file: "
              << this->data.size() << " sub-files");
 }
References data, DBG, ERR, INFO, likely, openage::line, openage::log::log(), and openage::util::Path::open().
~CSVCollection()
virtual openage::util::CSVCollection::~CSVCollection () virtual default
Member Function Documentation
get_data()
template<typename lineformat > std::vector<lineformat> openage::util::CSVCollection::get_data (const std::string & filename) const inline
Parse the data from one file in the map.
Definition at line 89 of file csv.h.
{
         size_t line_count = 0;
         std::vector<lineformat> ret;
         // locate the data in the collection
         auto it = this->data.find(filename);
         if (it != std::end(this->data)) {
             const std::vector<std::string> &lines = it->second;
             for (auto &line : lines) {
                 line_count += 1;
                 lineformat current_line_data;
                 // use the line copy to fill the current line struct.
                 int error_column = current_line_data.fill(line);
                 if (error_column != -1) {
                     throw Error{
                         ERR
                         << "Failed to read CSV file: "
                         << filename << ":" << line_count << ":" << error_column
                         << ": error parsing " << line
                     };
                 }
                 ret.push_back(current_line_data);
             }
         }
         else {
             throw Error{
                 ERR << "File was not found in csv cache: '"
                     << filename << "'"
             };
         }
         return ret;
     }
References data, ERR, openage::util::filename(), and openage::line.
read()
template<class lineformat > std::vector<lineformat> openage::util::CSVCollection::read (const std::string & filename) const inline
This function is the entry point to load the whole file tree recursively.
Should be called again from the .recurse() method of the struct.
The internal flow is as follows:
read entries of the given files (call to the generated field parsers (the fill function))
then, recurse into referenced subdata entries (this implementation is generated)
from there, reach this function again to read each subdata entry.
Definition at line 59 of file csv.h.
{
         // first read the content from the data
         auto result = this->get_data<lineformat>(filename);
         std::string dir = dirname(filename);
         size_t line_count = 0;
         // then recurse into each subdata entry.
         for (auto &entry : result) {
             line_count += 1;
             if (not entry.recurse(*this, dir)) {
                 throw Error{
                     MSG(err)
                     << "Failed to read follow-up files for "
                     << filename << ":" << line_count
                 };
             }
         }
         return result;
     }
References openage::util::dirname(), openage::log::err(), openage::util::filename(), MSG, and openage.testing.testing::result().
Referenced by openage::util::csv_subdata< lineformat >::read(), openage.convert.dataformat.exportable.Exportable::read(), and openage.convert.peresource.StringLiteral::readall().
Member Data Documentation
data
csv_file_map_t openage::util::CSVCollection::data protected
Definition at line 130 of file csv.h.
Referenced by openage.convert.dataformat.content_snippet.ContentSnippet::__eq__(), openage.convert.dataformat.struct_snippet.StructSnippet::__hash__(), openage.convert.dataformat.content_snippet.ContentSnippet::__hash__(), openage.convert.dataformat.content_snippet.ContentSnippet::__repr__(), openage.convert.dataformat.data_definition.DataDefinition::__str__(), openage.convert.dataformat.content_snippet.ContentSnippet::__str__(), openage.convert.dataformat.data_formatter.DataFormatter::add_data(), CSVCollection(), openage.convert.dataformat.data_formatter.DataFormatter::export(), openage.convert.dataformat.data_definition.DataDefinition::generate_csv(), openage.convert.dataformat.content_snippet.ContentSnippet::get_data(), openage.convert.texture.TextureImage::get_data(), get_data(), openage.convert.texture.TextureImage::get_pil_image(), and openage.convert.peresource.PEResources::read_directory().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/csv.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/csv.cpp