openage: openage::UngarrisonAction Class Reference
openage::UngarrisonAction Class Reference
#include <action.h>
Public Member Functions
UngarrisonAction (Unit *e, const coord::phys3 &pos)
virtual ~UngarrisonAction ()
void update (unsigned int time) override
void on_completion () override
bool completed () const override
bool allow_interupt () const override
bool allow_control () const override
std::string name () const override
Public Member Functions inherited from openage::UnitAction
UnitAction (Unit *u, graphic_type initial_gt)
virtual ~UnitAction ()
graphic_type type () const
float current_frame () const
virtual const graphic_set & current_graphics () const
void draw_debug (const Engine &engine)
void face_towards (const coord::phys3 pos)
bool damage_unit (Unit &target)
void move_to (Unit &target, bool use_range=true)
Private Attributes
coord::phys3 position
bool complete
Additional Inherited Members
Static Public Member Functions inherited from openage::UnitAction
static coord::phys_t adjacent_range (Unit *u)
static coord::phys_t get_attack_range (Unit *u)
static coord::phys_t get_heal_range (Unit *u)
Static Public Attributes inherited from openage::UnitAction
static bool show_debug = false
Protected Attributes inherited from openage::UnitAction
Unit * entity
graphic_type graphic
float frame
float frame_rate
std::function< void(const Engine &)> debug_draw_action
Detailed Description
garrison inside a building
Definition at line 425 of file action.h.
Constructor & Destructor Documentation
UngarrisonAction()
openage::UngarrisonAction::UngarrisonAction (Unit * e, const coord::phys3 & pos)
Definition at line 755 of file action.cpp.
     :
     UnitAction{e, graphic_type::standing},
     position(pos),
     complete{false} {
 }
References openage::standing.
~UngarrisonAction()
virtual openage::UngarrisonAction::~UngarrisonAction () inline virtual
Definition at line 428 of file action.h.
 {}
Member Function Documentation
allow_control()
bool openage::UngarrisonAction::allow_control () const inline override virtual
control whether stack can discard the action automatically and should the stack be modifiable when this action is on top
if true this action must complete and will not allow new actions to be pushed while it is active and also does not update the secondary actions
Implements openage::UnitAction.
Definition at line 434 of file action.h.
 { return true; }
allow_interupt()
bool openage::UngarrisonAction::allow_interupt () const inline override virtual
checks if the action can be interrupted, allowing it to be popped if the user specifies a new action, if false the action must reach a completed state before removal eg dead action must be completed and cannot be discarded
Implements openage::UnitAction.
Definition at line 433 of file action.h.
 { return true; }
completed()
bool openage::UngarrisonAction::completed () const inline override virtual
gets called for all actions on stack each update cycle
Returns
true when action is completed so it and everything above it can be popped
Implements openage::UnitAction.
Definition at line 432 of file action.h.
 { return this->complete; }
References complete.
name()
std::string openage::UngarrisonAction::name () const inline override virtual
debug string to identify action types
Implements openage::UnitAction.
Definition at line 435 of file action.h.
 { return "ungarrison"; }
Referenced by openage.util.fslike.path.Path::stem(), openage.util.fslike.path.Path::suffix(), and openage.util.fslike.path.Path::suffixes().
on_completion()
void openage::UngarrisonAction::on_completion () override virtual
action to perform when popped from a units action stack
Implements openage::UnitAction.
Definition at line 796 of file action.cpp.
 {}
update()
void openage::UngarrisonAction::update (unsigned int time) override virtual
each action has its own update functionality which gets called when this is the active action
Implements openage::UnitAction.
Definition at line 762 of file action.cpp.
{
     auto &garrison_attr = this->entity->get_attribute<attr_type::garrison>();
     // try unload all objects currently garrisoned
     auto position_it = std::remove_if(
         std::begin(garrison_attr.content),
         std::end(garrison_attr.content),
         [this](UnitReference &u) {
             if (u.is_valid()) {
                 // ptr to unit being ungarrisoned
                 Unit *unit_ptr = u.get();
                 // make sure it was placed outside
                 if (unit_ptr->unit_type->place_beside(unit_ptr, this->entity->location.get())) {
                     // task unit to move to position
                     auto &player = this->entity->get_attribute<attr_type::owner>().player;
                     Command cmd(player, this->position);
                     cmd.set_ability(ability_type::move);
                     unit_ptr->queue_cmd(cmd);
                     return true;
                 }
             }
             return false;
         });
     // remove elements which were ungarrisoned
     garrison_attr.content.erase(position_it, std::end(garrison_attr.content));
     // completed when no units are remaining
     this->complete = garrison_attr.content.empty();
 }
References openage::UnitAction::entity, openage::garrison, and openage::Unit::get_attribute().
Member Data Documentation
complete
bool openage::UngarrisonAction::complete private
Definition at line 439 of file action.h.
Referenced by completed().
position
coord::phys3 openage::UngarrisonAction::position private
Definition at line 438 of file action.h.
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/action.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/action.cpp