openage: openage::MoveAction Class Reference
openage::MoveAction Class Reference
#include <action.h>
Public Member Functions
MoveAction (Unit *e, coord::phys3 tar, bool repath=true)
MoveAction (Unit *e, UnitReference tar, coord::phys_t within_range)
virtual ~MoveAction ()
void update (unsigned int time) override
void on_completion () override
bool completed () const override
bool allow_interupt () const override
bool allow_control () const override
std::string name () const override
coord::phys3 next_waypoint () const
Public Member Functions inherited from openage::UnitAction
UnitAction (Unit *u, graphic_type initial_gt)
virtual ~UnitAction ()
graphic_type type () const
float current_frame () const
virtual const graphic_set & current_graphics () const
void draw_debug (const Engine &engine)
void face_towards (const coord::phys3 pos)
bool damage_unit (Unit &target)
void move_to (Unit &target, bool use_range=true)
Private Member Functions
void initialise ()
void set_path ()
void set_distance ()
Private Attributes
UnitReference unit_target
coord::phys3 target
coord::phys_t distance_to_target
coord::phys_t radius
path::Path path
bool allow_repath
bool end_action
Additional Inherited Members
Static Public Member Functions inherited from openage::UnitAction
static coord::phys_t adjacent_range (Unit *u)
static coord::phys_t get_attack_range (Unit *u)
static coord::phys_t get_heal_range (Unit *u)
Static Public Attributes inherited from openage::UnitAction
static bool show_debug = false
Protected Attributes inherited from openage::UnitAction
Unit * entity
graphic_type graphic
float frame
float frame_rate
std::function< void(const Engine &)> debug_draw_action
Detailed Description
moves an entity to another location
Definition at line 358 of file action.h.
Constructor & Destructor Documentation
MoveAction() [1/2]
openage::MoveAction::MoveAction (Unit * e, coord::phys3 tar, bool repath = true)
moves unit to a given fixed location
Definition at line 548 of file action.cpp.
     :
     UnitAction{e, graphic_type::walking},
     unit_target{},
     target(tar),
     radius{path::path_grid_size},
     allow_repath{repath},
     end_action{false} {
     this->initialise();
 }
References openage::walking.
MoveAction() [2/2]
openage::MoveAction::MoveAction (Unit * e, UnitReference tar, coord::phys_t within_range)
moves a unit to within a distance to another unit
Definition at line 559 of file action.cpp.
     :
     UnitAction{e, graphic_type::walking},
     unit_target{tar},
     target(tar.get()->location->pos.draw),
     radius{within_range},
     allow_repath{false},
     end_action{false} {
     this->initialise();
 }
References openage::walking.
~MoveAction()
openage::MoveAction::~MoveAction () virtual
Definition at line 589 of file action.cpp.
 {}
Member Function Documentation
allow_control()
bool openage::MoveAction::allow_control () const inline override virtual
control whether stack can discard the action automatically and should the stack be modifiable when this action is on top
if true this action must complete and will not allow new actions to be pushed while it is active and also does not update the secondary actions
Implements openage::UnitAction.
Definition at line 375 of file action.h.
 { return true; }
allow_interupt()
bool openage::MoveAction::allow_interupt () const inline override virtual
checks if the action can be interrupted, allowing it to be popped if the user specifies a new action, if false the action must reach a completed state before removal eg dead action must be completed and cannot be discarded
Implements openage::UnitAction.
Definition at line 374 of file action.h.
 { return true; }
completed()
bool openage::MoveAction::completed () const override virtual
gets called for all actions on stack each update cycle
Returns
true when action is completed so it and everything above it can be popped
Implements openage::UnitAction.
Definition at line 689 of file action.cpp.
{
     // no more waypoints to a static location
     if (this->end_action ||
         (!this->unit_target.is_valid() &&
         this->path.waypoints.empty())) {
         return true;
     }
     //close enough to end action
     if (this->distance_to_target < this->radius) {
         return true;
     }
     return false;
 }
References end_action, openage::UnitReference::is_valid(), path, radius, unit_target, and openage::path::Path::waypoints.
initialise()
void openage::MoveAction::initialise () private
Definition at line 570 of file action.cpp.
{
     // switch workers to the carrying graphic
     if (this->entity->has_attribute(attr_type::worker)) {
         auto &worker_resource = this->entity->get_attribute<attr_type::resource>();
         if (worker_resource.amount > 0) {
             this->graphic = graphic_type::carrying;
         }
     }
     // set initial distance
     this->set_distance();
     // set an initial path
     this->set_path();
     this->debug_draw_action = [&](const Engine &engine) {
         this->path.draw_path(engine.coord);
     };
 }
References openage::carrying, openage::UnitAction::debug_draw_action, openage::path::Path::draw_path(), openage::UnitAction::entity, openage::Unit::get_attribute(), openage::UnitAction::graphic, openage::Unit::has_attribute(), path, openage::resource, set_distance(), set_path(), and openage::worker.
name()
std::string openage::MoveAction::name () const inline override virtual
debug string to identify action types
Implements openage::UnitAction.
Definition at line 376 of file action.h.
 { return "move"; }
Referenced by openage.util.fslike.path.Path::stem(), openage.util.fslike.path.Path::suffix(), and openage.util.fslike.path.Path::suffixes().
next_waypoint()
coord::phys3 openage::MoveAction::next_waypoint () const
Definition at line 706 of file action.cpp.
{
     if (this->path.waypoints.size() > 0) {
         return this->path.waypoints.back().position;
     } else {
         throw Error{MSG(err) << "No next waypoint available!"};
     }
 }
References openage::log::err(), MSG, path, and openage::path::Path::waypoints.
Referenced by update().
on_completion()
void openage::MoveAction::on_completion () override virtual
action to perform when popped from a units action stack
Implements openage::UnitAction.
Definition at line 687 of file action.cpp.
 {}
set_distance()
void openage::MoveAction::set_distance () private
updates the distance_to_target value
Definition at line 726 of file action.cpp.
{
     if (this->unit_target.is_valid()) {
         auto &target_object = this->unit_target.get()->location;
         coord::phys3 &unit_pos = this->entity->location->pos.draw;
         this->distance_to_target = target_object->from_edge(unit_pos);
     }
     else {
         coord::phys3_delta move_dir = this->target - this->entity->location->pos.draw;
         this->distance_to_target = static_cast<coord::phys_t>(std::hypot(move_dir.ne, move_dir.se));
     }
 }
References distance_to_target, openage::UnitAction::entity, openage::UnitReference::get(), std::hypot(), openage::UnitReference::is_valid(), openage::Unit::location, target, and unit_target.
Referenced by initialise(), and update().
set_path()
void openage::MoveAction::set_path () private
use a star to find a path to target
Definition at line 715 of file action.cpp.
{
     if (this->unit_target.is_valid()) {
         this->path = path::to_object(this->entity->location.get(), this->unit_target.get()->location.get(), this->radius);
     }
     else {
         coord::phys3 start = this->entity->location->pos.draw;
         coord::phys3 end = this->target;
         this->path = path::to_point(start, end, this->entity->location->passable);
     }
 }
References openage::UnitAction::entity, openage::UnitReference::get(), openage::UnitReference::is_valid(), openage::Unit::location, path, radius, target, openage::path::to_object(), openage::path::to_point(), and unit_target.
Referenced by initialise(), and update().
update()
void openage::MoveAction::update (unsigned int time) override virtual
each action has its own update functionality which gets called when this is the active action
Implements openage::UnitAction.
Definition at line 591 of file action.cpp.
{
     if (this->unit_target.is_valid()) {
         // a unit is targeted, which may move
         auto &target_object = this->unit_target.get()->location;
         // check for garrisoning objects
         if (!target_object) {
             this->end_action = true;
             return;
         }
         coord::phys3 &target_pos = target_object->pos.draw;
         coord::phys3 &unit_pos = this->entity->location->pos.draw;
         // repath if target changes tiles by a threshold
         // this repathing is more frequent when the unit is
         // close to its target
         coord::phys_t tdx = target_pos.ne - this->target.ne;
         coord::phys_t tdy = target_pos.se - this->target.se;
         coord::phys_t udx = unit_pos.ne - this->target.ne;
         coord::phys_t udy = unit_pos.se - this->target.se;
         if (this->path.waypoints.empty() || std::hypot(tdx, tdy) > std::hypot(udx, udy)) {
             this->target = target_pos;
             this->set_path();
         }
     }
     // path not found
     if (this->path.waypoints.empty()) {
         if (!this->allow_repath) {
             this->entity->log(MSG(dbg) << "Path not found -- drop action");
             this->end_action = true;
         }
         return;
     }
     // find distance to move in this update
     auto &sp_attr = this->entity->get_attribute<attr_type::speed>();
     double distance_to_move = sp_attr.unit_speed.to_double() * time;
     // current position and direction
     coord::phys3 new_position = this->entity->location->pos.draw;
     auto &d_attr = this->entity->get_attribute<attr_type::direction>();
     coord::phys3_delta new_direction = d_attr.unit_dir;
     while (distance_to_move > 0) {
         if (this->path.waypoints.empty()) {
             break;
         }
         // find a point to move directly towards
         coord::phys3 waypoint = this->next_waypoint();
         coord::phys3_delta move_dir = waypoint - new_position;
         // normalise dir
         double distance_to_waypoint = std::hypot(move_dir.ne, move_dir.se);
         if (distance_to_waypoint <= distance_to_move) {
             distance_to_move -= distance_to_waypoint;
             // change entity position and direction
             new_position = waypoint;
             new_direction = move_dir;
             // remove the waypoint
             this->path.waypoints.pop_back();
         }
         else {
             // change entity position and direction
             new_position += move_dir * (distance_to_move / distance_to_waypoint);
             new_direction = move_dir;
             break;
         }
     }
     // check move collisions
     bool move_completed = this->entity->location->move(new_position);
     if (move_completed) {
         d_attr.unit_dir = new_direction;
         this->set_distance();
     }
     else {
         // cases for modifying path when blocked
         if (this->allow_repath) {
             this->entity->log(MSG(dbg) << "Path blocked -- finding new path");
             this->set_path();
         }
         else {
             this->entity->log(MSG(dbg) << "Path blocked -- drop action");
             this->end_action = true;
         }
     }
     // inc frame
     this->frame += time * this->frame_rate / 5.0f;
 }
References allow_repath, openage::log::dbg(), openage::direction, end_action, openage::UnitAction::entity, openage::UnitAction::frame, openage::UnitAction::frame_rate, openage::UnitReference::get(), openage::Unit::get_attribute(), std::hypot(), openage::UnitReference::is_valid(), openage::Unit::location, openage::log::LogSource::log(), MSG, next_waypoint(), path, set_distance(), set_path(), openage::speed, target, unit_target, and openage::path::Path::waypoints.
Member Data Documentation
allow_repath
bool openage::MoveAction::allow_repath private
Definition at line 390 of file action.h.
Referenced by update().
distance_to_target
coord::phys_t openage::MoveAction::distance_to_target private
Definition at line 385 of file action.h.
Referenced by set_distance().
end_action
bool openage::MoveAction::end_action private
Definition at line 390 of file action.h.
Referenced by completed(), and update().
path
path::Path openage::MoveAction::path private
Definition at line 387 of file action.h.
Referenced by openage.util.fslike.directory.Directory::__repr__(), openage.util.fslike.directory.CaseIgnoringDirectory::__repr__(), openage.util.fslike.directory.CaseIgnoringDirectory::actual_name(), completed(), initialise(), next_waypoint(), openage.util.fslike.directory.Directory::resolve(), openage.util.fslike.directory.CaseIgnoringDirectory::resolve(), set_path(), update(), and openage.util.fslike.directory.Directory::writable().
radius
coord::phys_t openage::MoveAction::radius private
Definition at line 385 of file action.h.
Referenced by completed(), and set_path().
target
coord::phys3 openage::MoveAction::target private
Definition at line 382 of file action.h.
Referenced by set_distance(), set_path(), and update().
unit_target
UnitReference openage::MoveAction::unit_target private
Definition at line 381 of file action.h.
Referenced by completed(), set_distance(), set_path(), and update().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/action.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/action.cpp