openage: openage::util::FD Class Reference
openage::util::FD Class Reference
wraps a POSIX file descriptor
#include <fds.h>
Public Member Functions
FD (int fd)
wraps an existing FD
FD (int fd, bool set_nonblocking)
duplicates an existing FD, and optionally sets it to non-blocking mode
FD (FD *fd, bool set_nonblocking)
~FD ()
int write (const char *buf, size_t bytes)
writes 'bytes' bytes from buf
int puts (const char *str)
writes the string (excluding the null terminator)
int putbyte (char c)
writes the char
int putcp (int cp)
writes the unicode codepoint, as utf-8
int printf (const char *format,...)
guess what this does.
void setinputmodecanon ()
sets input to canonical mode.
void restoreinputmode ()
restores the input mode to the mode that was backed up during the last setinputmodecanon() mode.
Public Attributes
int fd
bool close_on_destroy = false
if this is set to true, the destructor will close the fd.
bool restore_input_mode_on_destroy = false
if this is set to true, the destructor will restore the input mode.
struct termios old_tio
Detailed Description
wraps a POSIX file descriptor
Definition at line 17 of file fds.h.
Constructor & Destructor Documentation
FD() [1/3]
openage::util::FD::FD (int fd)
wraps an existing FD
Definition at line 23 of file fds.cpp.
              {
     this->fd = fd;
 }
References fd.
FD() [2/3]
openage::util::FD::FD (int fd, bool set_nonblocking)
duplicates an existing FD, and optionally sets it to non-blocking mode
Definition at line 27 of file fds.cpp.
{
     this->fd = ::dup(fd);
     this->close_on_destroy = true;
     if (set_nonblocking) {
         #ifndef _WIN32
         int flags = ::fcntl(this->fd, F_GETFL, 0);
         ::fcntl(this->fd, F_SETFL, flags | O_NONBLOCK);
         #endif
     }
 }
References close_on_destroy, and fd.
FD() [3/3]
openage::util::FD::FD (FD * fd, bool set_nonblocking)
Definition at line 39 of file fds.cpp.
                                    :
     FD{fd->fd, set_nonblocking} {
 }
References fd.
~FD()
openage::util::FD::~FD ()
Definition at line 43 of file fds.cpp.
         {
     if (this->restore_input_mode_on_destroy) {
         this->restoreinputmode();
     }
     if (this->close_on_destroy) {
         ::close(this->fd);
     }
 }
References close_on_destroy, fd, restore_input_mode_on_destroy, and restoreinputmode().
Member Function Documentation
printf()
int openage::util::FD::printf (const char * format, ...)
guess what this does.
because I won't tell you.
Definition at line 75 of file fds.cpp.
{
     const unsigned buf_size = 16;
     char *buf = (char*) malloc(sizeof(char) * buf_size);
     if (!buf) {
         return -1;
     }
     va_list vl;
     //first, try to vsnprintf to a buffer of length 16
     va_start(vl, format);
     unsigned len = vsnprintf(buf, buf_size, format, vl);
     va_end(vl);
     //if that wasn't enough, allocate more memory and try again
     if (len >= buf_size) {
         char *oldbuf = buf;
         buf = (char*) realloc(oldbuf, sizeof(char) * (len + 1));
         if (!buf) {
             free(oldbuf);
             return -1;
         }
         va_start(vl, format);
         vsnprintf(buf, len + 1, format, vl);
         va_end(vl);
     }
     //output buf to the socket
     int result = this->puts(buf);
     //free the buffer
     free(buf);
     return result;
 }
References puts(), and openage.testing.testing::result().
Referenced by openage::console::draw::to_terminal().
putbyte()
int openage::util::FD::putbyte (char c)
writes the char
Definition at line 61 of file fds.cpp.
                       {
     return this->write(&c, 1);
 }
References write().
Referenced by openage::console::draw::to_terminal().
putcp()
int openage::util::FD::putcp (int cp)
writes the unicode codepoint, as utf-8
Definition at line 65 of file fds.cpp.
                     {
     char utf8buf[5];
     if (util::utf8_encode(cp, utf8buf) == 0) {
         //unrepresentable character (question mark in black rhombus)
         return this->puts("\uFFFD");
     } else {
         return this->puts(utf8buf);
     }
 }
References puts(), and openage::util::utf8_encode().
Referenced by openage::console::draw::to_terminal().
puts()
int openage::util::FD::puts (const char * str)
writes the string (excluding the null terminator)
Definition at line 57 of file fds.cpp.
{
     return this->write(str, strlen(str));
 }
References openage::py::str(), openage::util::constexpr_::strlen(), and write().
Referenced by openage::console::tests::interactive(), printf(), putcp(), and openage::console::draw::to_terminal().
restoreinputmode()
void openage::util::FD::restoreinputmode ()
restores the input mode to the mode that was backed up during the last setinputmodecanon() mode.
Definition at line 130 of file fds.cpp.
{
     #ifndef _WIN32
     if (::isatty(this->fd)) {
         ::tcsetattr(this->fd, TCSANOW, &this->old_tio);
         this->restore_input_mode_on_destroy = false;
     }
     #endif /* _WIN32 */
 }
References fd, old_tio, and restore_input_mode_on_destroy.
Referenced by ~FD().
setinputmodecanon()
void openage::util::FD::setinputmodecanon ()
sets input to canonical mode.
this includes:
disabling ECHO
non-buffered input
no generation of signals on ^C, ^Z, ...
Definition at line 112 of file fds.cpp.
{
     #ifndef _WIN32
     if (::isatty(this->fd)) {
         //get the terminal settings for stdin
         ::tcgetattr(this->fd, &this->old_tio);
         //backup old settings
         struct termios new_tio = this->old_tio;
         //disable buffered i/o (canonical mode) and local echo
         new_tio.c_lflag &= (~ICANON & ~ECHO & ~ISIG);
         //set the settings
         ::tcsetattr(this->fd, TCSANOW, &new_tio);
         this->restore_input_mode_on_destroy = true;
     }
     #endif /* _WIN32 */
 }
References fd, old_tio, and restore_input_mode_on_destroy.
write()
int openage::util::FD::write (const char * buf, size_t bytes)
writes 'bytes' bytes from buf
Definition at line 53 of file fds.cpp.
{
     return ::write(this->fd, buf, bytes);
 }
References openage::py::bytes(), and fd.
Referenced by putbyte(), and puts().
Member Data Documentation
close_on_destroy
bool openage::util::FD::close_on_destroy = false
if this is set to true, the destructor will close the fd.
will be set to true by the constructor iff the fd was duped.
Definition at line 39 of file fds.h.
Referenced by FD(), and ~FD().
fd
int openage::util::FD::fd
Definition at line 33 of file fds.h.
Referenced by FD(), restoreinputmode(), setinputmodecanon(), write(), and ~FD().
old_tio
struct termios openage::util::FD::old_tio
Definition at line 88 of file fds.h.
Referenced by restoreinputmode(), and setinputmodecanon().
restore_input_mode_on_destroy
bool openage::util::FD::restore_input_mode_on_destroy = false
if this is set to true, the destructor will restore the input mode.
will be set on setinputmodecanon().
Definition at line 45 of file fds.h.
Referenced by restoreinputmode(), setinputmodecanon(), and ~FD().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/fds.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/fds.cpp