openage: openage::GatherAction Class Reference
openage::GatherAction Class Reference
gathers resource from another object
#include <action.h>
Public Member Functions
GatherAction (Unit *e, UnitReference tar)
virtual ~GatherAction ()
void update_in_range (unsigned int time, Unit *target_unit) override
Control units action when in range of the target.
void on_completion_in_range (int target_type) override
bool completed_in_range (Unit *) const override
std::string name () const override
debug string to identify action types
Public Member Functions inherited from openage::TargetAction
TargetAction (Unit *e, graphic_type gt, UnitReference r, coord::phys_t action_rad)
action_rad is how close a unit must come to another unit to be considered to touch the other, for example in gathering resource and melee attack
TargetAction (Unit *e, graphic_type gt, UnitReference r)
this constructor uses the default action radius formula which will bring the object as near to the target as the pathing grid will allow.
virtual ~TargetAction ()
void update (unsigned int time) override
each action has its own update functionality which gets called when this is the active action
void on_completion () override
action to perform when popped from a units action stack
bool completed () const override
gets called for all actions on stack each update cycle
bool allow_interupt () const override
checks if the action can be interrupted, allowing it to be popped if the user specifies a new action, if false the action must reach a completed state before removal eg dead action must be completed and cannot be discarded
bool allow_control () const override
control whether stack can discard the action automatically and should the stack be modifiable when this action is on top
coord::phys_t distance_to_target ()
Unit * update_distance ()
UnitReference get_target () const
int get_target_type_id () const
void set_target (UnitReference new_target)
changes target, ending action when new target is invalid
Public Member Functions inherited from openage::UnitAction
UnitAction (Unit *u, graphic_type initial_gt)
Require unit to be updated and an initial graphic type.
virtual ~UnitAction ()
graphic_type type () const
type of graphic this action should use
float current_frame () const
frame number to use on the current graphic
virtual const graphic_set & current_graphics () const
determines which graphic should be used for drawing this unit finds the default graphic using the units type, used by most actions
void draw_debug (const Engine &engine)
void face_towards (const coord::phys3 pos)
common functions for actions
bool damage_unit (Unit &target)
Damage a unit, returns true if the unit was killed in the process.
void move_to (Unit &target, bool use_range=true)
Private Member Functions
UnitReference nearest_dropsite (game_resource res_type)
Private Attributes
bool complete
bool target_resource
UnitReference target
gamedata::unit_classes resource_class
Additional Inherited Members
Static Public Member Functions inherited from openage::UnitAction
static coord::phys_t adjacent_range (Unit *u)
a small distance to which units are considered touching when within this distance
static coord::phys_t get_attack_range (Unit *u)
looks at an ranged attributes on the unit otherwise returns same as adjacent_range()
static coord::phys_t get_heal_range (Unit *u)
looks at heal attribute on the unit otherwise returns same as adjacent_range()
Static Public Attributes inherited from openage::UnitAction
static bool show_debug = false
produce debug info such as visualising paths
Protected Attributes inherited from openage::UnitAction
Unit * entity
the entity being updated
graphic_type graphic
common graphic controls
float frame
float frame_rate
std::function< void(const Engine &)> debug_draw_action
additional drawing for debug purposes
Detailed Description
gathers resource from another object
Definition at line 542 of file action.h.
Constructor & Destructor Documentation
GatherAction()
openage::GatherAction::GatherAction (Unit * e, UnitReference tar)
Definition at line 1020 of file action.cpp.
     :
     TargetAction{e, graphic_type::work, tar},
     complete{false},
     target_resource{true},
     target{tar} {
     Unit *target = this->target.get();
     this->resource_class = target->unit_type->unit_class;
     // handle unit type changes based on resource class
     if (this->entity->has_attribute(attr_type::multitype)) {
         this->entity->get_attribute<attr_type::multitype>().switchType(this->resource_class, this->entity);
     }
     // set the type of gatherer
     auto &worker_resource = this->entity->get_attribute<attr_type::resource>();
     if (target->has_attribute(attr_type::resource)) {
         auto &resource_attr = target->get_attribute<attr_type::resource>();
         if (worker_resource.resource_type != resource_attr.resource_type) {
             worker_resource.amount = 0;
         }
         worker_resource.resource_type = resource_attr.resource_type;
     } else {
         throw std::invalid_argument("Unit reference has no resource attribute");
     }
 }
References openage::work.
~GatherAction()
openage::GatherAction::~GatherAction () virtual
Definition at line 1048 of file action.cpp.
 {}
Member Function Documentation
completed_in_range()
bool openage::GatherAction::completed_in_range (Unit *) const inline override virtual
Implements openage::TargetAction.
Definition at line 549 of file action.h.
 { return this->complete; }
References complete.
name()
std::string openage::GatherAction::name () const inline override virtual
debug string to identify action types
Implements openage::TargetAction.
Definition at line 550 of file action.h.
 { return "gather"; }
Referenced by openage.util.fslike.path.Path::stem(), openage.util.fslike.path.Path::suffix(), and openage.util.fslike.path.Path::suffixes().
nearest_dropsite()
UnitReference openage::GatherAction::nearest_dropsite (game_resource res_type) private
Definition at line 1155 of file action.cpp.
{
     // find nearest dropsite from the targeted resource
     auto ds = find_near(*this->target.get()->location,
         [=](const TerrainObject &obj) {
             if (not obj.unit.has_attribute(attr_type::building) or &obj.unit == this->entity or &obj.unit == this->target.get()) {
                 return false;
             }
             return obj.unit.get_attribute<attr_type::building>().completed >= 1.0f &&
                    obj.unit.has_attribute(attr_type::owner) &&
                    obj.unit.get_attribute<attr_type::owner>().player.owns(*this->entity) &&
                    obj.unit.has_attribute(attr_type::dropsite) &&
                    obj.unit.get_attribute<attr_type::dropsite>().accepting_resource(res_type);
     });
     if (ds) {
         return ds->unit.get_ref();
     }
     else {
         this->entity->log(MSG(dbg) << "no dropsite found");
         return UnitReference();
     }
 }
References openage::building, openage::TargetAction::completed(), openage::log::dbg(), openage::dropsite, openage::UnitAction::entity, openage::find_near(), openage::Unit::get_ref(), openage::log::LogSource::log(), MSG, openage::owner, and openage::TerrainObject::unit.
Referenced by update_in_range().
on_completion_in_range()
void openage::GatherAction::on_completion_in_range (int target_type) override virtual
Implements openage::TargetAction.
Definition at line 1135 of file action.cpp.
{
     // find a different target with same type
     TerrainObject *new_target = nullptr;
     new_target = find_near(*this->entity->location,
         [target_type](const TerrainObject &obj) {
             return obj.unit.unit_type->id() == target_type &&
                    !obj.unit.has_attribute(attr_type::worker) &&
                    obj.unit.has_attribute(attr_type::resource) &&
                    obj.unit.get_attribute<attr_type::resource>().amount > 0.0;
         });
     if (new_target) {
         this->entity->log(MSG(dbg) << "auto retasking");
         auto &pl_attr = this->entity->get_attribute<attr_type::owner>();
         Command cmd(pl_attr.player, &new_target->unit);
         this->entity->queue_cmd(cmd);
     }
 }
References openage::log::dbg(), openage::UnitAction::entity, openage::find_near(), openage::Unit::get_attribute(), openage::Unit::location, openage::log::LogSource::log(), MSG, openage::owner, openage::Unit::queue_cmd(), and openage::TerrainObject::unit.
update_in_range()
void openage::GatherAction::update_in_range (unsigned int , Unit *) override virtual
Control units action when in range of the target.
Implements openage::TargetAction.
Definition at line 1050 of file action.cpp.
{
     auto &worker = this->entity->get_attribute<attr_type::worker>();
     auto &worker_resource = this->entity->get_attribute<attr_type::resource>();
     if (this->target_resource) {
         // the targets attributes
         if (!targeted_resource->has_attribute(attr_type::resource)) {
             complete = true;
             return;
         }
         // attack objects which have hitpoints (trees, hunt, sheep)
         if (this->entity->has_attribute(attr_type::owner) &&
             targeted_resource->has_attribute(attr_type::damaged)) {
             auto &pl = this->entity->get_attribute<attr_type::owner>();
             auto &dm = targeted_resource->get_attribute<attr_type::damaged>();
             // only attack if hitpoints remain
             if (dm.hp > 0) {
                 Command cmd(pl.player, targeted_resource);
                 cmd.set_ability(ability_type::attack);
                 cmd.add_flag(command_flag::attack_res);
                 this->entity->queue_cmd(cmd);
                 return;
             }
         }
         // need to return to dropsite
         if (worker_resource.amount > worker.capacity) {
             // move to dropsite location
             this->target_resource = false;
             this->set_target(this->nearest_dropsite(worker_resource.resource_type));
         }
         else {
             auto &resource_attr = targeted_resource->get_attribute<attr_type::resource>();
             if (resource_attr.amount <= 0.0) {
                 // when the resource runs out
                 if (worker_resource.amount > 0.0) {
                     this->target_resource = false;
                     this->set_target(this->nearest_dropsite(worker_resource.resource_type));
                 }
                 else {
                     this->complete = true;
                 }
             }
             else {
                 // transfer using gather rate
                 double amount = worker.gather_rate[worker_resource.resource_type]
                                 * resource_attr.gather_rate * time;
                 worker_resource.amount += amount;
                 resource_attr.amount -= amount;
             }
         }
     }
     else {
         // dropsite has been reached
         // add value to player stockpile
         auto &player = this->entity->get_attribute<attr_type::owner>().player;
         player.receive(worker_resource.resource_type, worker_resource.amount);
         worker_resource.amount = 0.0;
         // make sure the resource stil exists
         if (this->target.is_valid() &&
             this->target.get()->get_attribute<attr_type::resource>().amount > 0.0) {
             // return to resouce collection
             this->target_resource = true;
             this->set_target(this->target);
         }
         else {
             // resource depleted
             this->complete = true;
         }
     }
     // inc frame
     this->frame += time * this->frame_rate / 3.0f;
 }
References openage::Command::add_flag(), openage::attack, openage::attack_res, complete, openage::damaged, openage::UnitAction::entity, openage::UnitAction::frame, openage::UnitAction::frame_rate, openage::Unit::get_attribute(), openage::Unit::has_attribute(), nearest_dropsite(), openage::owner, openage::Unit::queue_cmd(), openage::resource, openage::Command::set_ability(), openage::TargetAction::set_target(), target_resource, and openage::worker.
Member Data Documentation
complete
bool openage::GatherAction::complete private
Definition at line 553 of file action.h.
Referenced by completed_in_range(), and update_in_range().
resource_class
gamedata::unit_classes openage::GatherAction::resource_class private
Definition at line 555 of file action.h.
target
UnitReference openage::GatherAction::target private
Definition at line 554 of file action.h.
target_resource
bool openage::GatherAction::target_resource private
Definition at line 553 of file action.h.
Referenced by update_in_range().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/action.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/action.cpp