openage: qtsdl::GuiEngineImpl Class Reference
qtsdl::GuiEngineImpl Class Reference
#include <gui_engine_impl.h>
Public Slots
void attach_to (GuiRendererImpl *renderer)
void onReload ()
Signals
void reload ()
void rootDirsPathsChanged (const QStringList &)
Public Member Functions
GuiEngineImpl (GuiRenderer *renderer, const std::vector< GuiImageProvider * > &image_providers=std::vector< GuiImageProvider * >(), GuiSingletonItemsInfo *singleton_items_info=nullptr)
virtual ~GuiEngineImpl ()
QQmlEngine * get_qml_engine ()
void add_root_dir_path (const QString &root_dir_path)
void remove_root_dir_path (const QString &root_dir_path)
Static Public Member Functions
static GuiEngineImpl * impl (GuiEngine *engine)
Private Attributes
GuiRendererImpl * renderer
QmlEngineWithSingletonItemsInfo engine
RecursiveDirectoryWatcher watcher
QStringList root_dirs_paths
Detailed Description
Definition at line 21 of file gui_engine_impl.h.
Constructor & Destructor Documentation
GuiEngineImpl()
qtsdl::GuiEngineImpl::GuiEngineImpl (GuiRenderer * renderer, const std::vector< GuiImageProvider * > & image_providers = std::vector<GuiImageProvider*>(), GuiSingletonItemsInfo * singleton_items_info = nullptr) explicit
Definition at line 17 of file gui_engine_impl.cpp.
     :
     QObject{},
     renderer{},
     engine{GuiImageProviderImpl::take_ownership(image_providers), singleton_items_info} {
     QThread *gui_thread = QCoreApplication::instance()->thread();
     this->moveToThread(gui_thread);
     this->engine.moveToThread(gui_thread);
     this->watcher.moveToThread(gui_thread);
     assert(!this->engine.incubationController());
     this->attach_to(GuiRendererImpl::impl(renderer));
     QObject::connect(this,
                      &GuiEngineImpl::rootDirsPathsChanged,
                      &this->watcher,
                      &RecursiveDirectoryWatcher::rootDirsPathsChanged);
     QObject::connect(&this->watcher,
                      &RecursiveDirectoryWatcher::changeDetected,
                      this,
                      &GuiEngineImpl::onReload);
 }
~GuiEngineImpl()
qtsdl::GuiEngineImpl::~GuiEngineImpl () virtual
Definition at line 44 of file gui_engine_impl.cpp.
{
 }
Member Function Documentation
add_root_dir_path()
void qtsdl::GuiEngineImpl::add_root_dir_path (const QString & root_dir_path)
Definition at line 66 of file gui_engine_impl.cpp.
{
     this->root_dirs_paths.push_back(root_dir_path);
     emit this->rootDirsPathsChanged(this->root_dirs_paths);
 }
References root_dirs_paths, and rootDirsPathsChanged().
attach_to
void qtsdl::GuiEngineImpl::attach_to (GuiRendererImpl * renderer) slot
Definition at line 51 of file gui_engine_impl.cpp.
{
     this->renderer = renderer;
     this->engine.setIncubationController(this->renderer->get_window()->incubationController());
 }
References engine, qtsdl::GuiRendererImpl::get_window(), and renderer.
get_qml_engine()
QQmlEngine * qtsdl::GuiEngineImpl::get_qml_engine ()
Definition at line 56 of file gui_engine_impl.cpp.
{
     return &this->engine;
 }
References engine.
Referenced by qtsdl::GuiSubtreeImpl::attach_to(), qtsdl::GuiEngineImplConnection::get_qml_engine(), and qtsdl::GuiEngineImplConnection::rootContext().
impl()
GuiEngineImpl * qtsdl::GuiEngineImpl::impl (GuiEngine * engine) static
Definition at line 47 of file gui_engine_impl.cpp.
{
     return engine->impl.get();
 }
References engine.
onReload
void qtsdl::GuiEngineImpl::onReload () slot
Definition at line 60 of file gui_engine_impl.cpp.
{
     qDebug("reloading GUI");
     this->engine.clearComponentCache();
     emit this->reload();
 }
References engine, and reload().
reload
void qtsdl::GuiEngineImpl::reload () signal
Referenced by qtsdl::GuiEngineImplConnection::disconnect(), and onReload().
remove_root_dir_path()
void qtsdl::GuiEngineImpl::remove_root_dir_path (const QString & root_dir_path)
Definition at line 71 of file gui_engine_impl.cpp.
{
     if (this->root_dirs_paths.removeOne(root_dir_path))
         emit this->rootDirsPathsChanged(this->root_dirs_paths);
     else
         qWarning() << "Failed to remove path watched by ReloadableQmlEngine.";
 }
References root_dirs_paths, and rootDirsPathsChanged().
Referenced by qtsdl::GuiEngineImplConnection::disconnect().
rootDirsPathsChanged
void qtsdl::GuiEngineImpl::rootDirsPathsChanged (const QStringList &) signal
Referenced by add_root_dir_path(), and remove_root_dir_path().
Member Data Documentation
engine
QmlEngineWithSingletonItemsInfo qtsdl::GuiEngineImpl::engine private
Definition at line 48 of file gui_engine_impl.h.
Referenced by attach_to(), get_qml_engine(), impl(), and onReload().
renderer
GuiRendererImpl* qtsdl::GuiEngineImpl::renderer private
Definition at line 46 of file gui_engine_impl.h.
Referenced by attach_to().
root_dirs_paths
QStringList qtsdl::GuiEngineImpl::root_dirs_paths private
Definition at line 51 of file gui_engine_impl.h.
Referenced by add_root_dir_path(), and remove_root_dir_path().
watcher
RecursiveDirectoryWatcher qtsdl::GuiEngineImpl::watcher private
Definition at line 49 of file gui_engine_impl.h.
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/guisys/private/gui_engine_impl.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/guisys/private/gui_engine_impl.cpp