openage: openage::gui::GameControlLink Class Reference
openage::gui::GameControlLink Class Reference
#include <game_control_link.h>
Signals
void mode_changed ()
void modes_changed ()
void current_player_name_changed ()
void current_civ_index_changed ()
Public Member Functions
GameControlLink (QObject *parent=nullptr)
virtual ~GameControlLink ()
OutputModeLink * get_mode () const
int get_effective_mode_index () const
int get_mode_index () const
void set_mode_index (int mode)
QVariantList get_modes () const
void set_modes (const QVariantList &modes)
EngineLink * get_engine () const
void set_engine (EngineLink *engine)
GameMainLink * get_game () const
void set_game (GameMainLink *game)
QString get_current_player_name () const
int get_current_civ_index () const
Public Member Functions inherited from qtsdl::GuiItemQObject
GuiItemQObject (QObject *parent=nullptr)
Public Member Functions inherited from qtsdl::GuiItemBase
virtual ~GuiItemBase ()
Public Member Functions inherited from qtsdl::DeferredInitialConstantPropertyValues
DeferredInitialConstantPropertyValues ()
virtual ~DeferredInitialConstantPropertyValues ()
Is virtual to be able to catch the error when non-persistent item uses liveReloadTag.
void apply_static_properties ()
Execute saved static properties assignments (for newly created cores).
void clear_static_properties ()
Clear saved static properties assignments (for cores that existed before the GUI reload).
bool is_init_over () const
Public Member Functions inherited from qtsdl::GuiItemLink
virtual ~GuiItemLink ()
Public Member Functions inherited from qtsdl::GuiItem< GameControlLink >
GuiItem (GuiItemBase *item_base)
Creates an empty QObject shell for a core that is wrappable into a type *T.
Public Member Functions inherited from qtsdl::GuiItemCoreInstantiator< GameControlLink >
GuiItemCoreInstantiator (GuiItemBase *item_base)
Sets up a factory for the type T.
Public Member Functions inherited from qtsdl::GuiItemMethods< GameControlLink >
virtual ~GuiItemMethods ()
U * get () const
Get core.
U * get ()
Get core.
void i (F f, Args &&... args)
Invoke a function in the logic thread (the thread of the core of this object).
Properties
openage::gui::OutputModeLink mode
int effectiveModeIndex
int modeIndex
QVariantList modes
openage::gui::EngineLink engine
openage::gui::GameMainLink game
QString currentPlayerName
int currentCivIndex
Private Slots
void on_mode_changed (OutputMode *mode, int mode_index)
void on_modes_changed (OutputMode *mode, int mode_index)
void on_current_player_name_changed (const std::string &current_player_name)
void on_current_civ_index_changed (int current_civ_index)
Private Member Functions
virtual void classBegin () override
virtual void on_core_adopted () override
virtual void componentComplete () override
Private Attributes
OutputModeLink * mode
int effective_mode_index
int mode_index
EngineLink * engine
GameMainLink * game
QString current_player_name
int current_civ_index
Additional Inherited Members
Protected Member Functions inherited from qtsdl::GuiItemMethods< GameControlLink >
void s (F f, P &p, A &&arg)
Set property.
void sf (F f, P &p, A &&arg)
Set property even if it's the same.
Protected Attributes inherited from qtsdl::GuiItemBase
GameLogicCaller game_logic_caller
std::function< std::unique_ptr< PersistentCoreHolderBase >)> instantiate_core_func
std::function< void(PersistentCoreHolderBase *, const QString &)> do_adopt_core_func
std::function< void()> on_core_adopted_func
Protected Attributes inherited from qtsdl::DeferredInitialConstantPropertyValues
bool init_over
std::vector< std::function< void()> > static_properties_assignments
Detailed Description
Definition at line 236 of file game_control_link.h.
Constructor & Destructor Documentation
GameControlLink()
openage::gui::GameControlLink::GameControlLink (QObject * parent = nullptr) explicit
Definition at line 231 of file game_control_link.cpp.
     :
     GuiItemQObject{parent},
     QQmlParserStatus{},
     GuiItem{this},
     mode{},
     effective_mode_index{-1},
     mode_index{-1},
     engine{},
     game{},
     current_civ_index{} {
     Q_UNUSED(registration_mode);
     Q_UNUSED(registration);
 }
~GameControlLink()
openage::gui::GameControlLink::~GameControlLink () virtual
Definition at line 246 of file game_control_link.cpp.
{
 }
Member Function Documentation
classBegin()
void openage::gui::GameControlLink::classBegin () override private virtual
Definition at line 249 of file game_control_link.cpp.
{
 }
componentComplete()
void openage::gui::GameControlLink::componentComplete () override private virtual
Definition at line 259 of file game_control_link.cpp.
{
     static auto f = [] (GameControl *_this) {
         _this->announce_mode();
         _this->announce_current_player_name();
     };
     this->i(f);
 }
References qtsdl::GuiItemMethods< GameControlLink >::i().
current_civ_index_changed
void openage::gui::GameControlLink::current_civ_index_changed () signal
Referenced by on_current_civ_index_changed().
current_player_name_changed
void openage::gui::GameControlLink::current_player_name_changed () signal
Referenced by on_current_player_name_changed().
get_current_civ_index()
int openage::gui::GameControlLink::get_current_civ_index () const
Definition at line 331 of file game_control_link.cpp.
{
     return this->current_civ_index;
 }
References current_civ_index.
get_current_player_name()
QString openage::gui::GameControlLink::get_current_player_name () const
Definition at line 327 of file game_control_link.cpp.
{
     return this->current_player_name;
 }
References current_player_name.
get_effective_mode_index()
int openage::gui::GameControlLink::get_effective_mode_index () const
Definition at line 271 of file game_control_link.cpp.
{
     return this->effective_mode_index;
 }
References effective_mode_index.
get_engine()
EngineLink * openage::gui::GameControlLink::get_engine () const
Definition at line 305 of file game_control_link.cpp.
{
     return this->engine;
 }
References engine.
get_game()
GameMainLink * openage::gui::GameControlLink::get_game () const
Definition at line 316 of file game_control_link.cpp.
{
     return this->game;
 }
References game.
get_mode()
OutputModeLink * openage::gui::GameControlLink::get_mode () const
Definition at line 267 of file game_control_link.cpp.
{
     return this->mode;
 }
References mode.
get_mode_index()
int openage::gui::GameControlLink::get_mode_index () const
Definition at line 275 of file game_control_link.cpp.
{
     return this->mode_index;
 }
References mode_index.
get_modes()
QVariantList openage::gui::GameControlLink::get_modes () const
Definition at line 287 of file game_control_link.cpp.
{
     return this->modes;
 }
References modes.
mode_changed
void openage::gui::GameControlLink::mode_changed () signal
Referenced by on_mode_changed().
modes_changed
void openage::gui::GameControlLink::modes_changed () signal
Referenced by on_modes_changed().
on_core_adopted()
void openage::gui::GameControlLink::on_core_adopted () override private virtual
Reimplemented from qtsdl::GuiItemBase.
Definition at line 252 of file game_control_link.cpp.
{
     QObject::connect(&unwrap(this)->gui_signals, &GameControlSignals::mode_changed, this, &GameControlLink::on_mode_changed);
     QObject::connect(&unwrap(this)->gui_signals, &GameControlSignals::modes_changed, this, &GameControlLink::on_modes_changed);
     QObject::connect(&unwrap(this)->gui_signals, &GameControlSignals::current_player_name_changed, this, &GameControlLink::on_current_player_name_changed);
     QObject::connect(&unwrap(this)->gui_signals, &GameControlSignals::current_civ_index_changed, this, &GameControlLink::on_current_civ_index_changed);
 }
References openage::GameControlSignals::current_civ_index_changed(), openage::GameControlSignals::current_player_name_changed(), openage::GameControlSignals::mode_changed(), openage::GameControlSignals::modes_changed(), on_current_civ_index_changed(), on_current_player_name_changed(), on_mode_changed(), on_modes_changed(), and qtsdl::unwrap().
on_current_civ_index_changed
void openage::gui::GameControlLink::on_current_civ_index_changed (int current_civ_index) private slot
Definition at line 360 of file game_control_link.cpp.
{
     this->current_civ_index = current_civ_index;
     emit this->current_civ_index_changed();
 }
References current_civ_index, and current_civ_index_changed().
Referenced by on_core_adopted().
on_current_player_name_changed
void openage::gui::GameControlLink::on_current_player_name_changed (const std::string & current_player_name) private slot
Definition at line 355 of file game_control_link.cpp.
{
     this->current_player_name = QString::fromStdString(current_player_name);
     emit this->current_player_name_changed();
 }
References current_player_name, and current_player_name_changed().
Referenced by on_core_adopted().
on_mode_changed
void openage::gui::GameControlLink::on_mode_changed (OutputMode * mode, int mode_index) private slot
Definition at line 335 of file game_control_link.cpp.
{
     auto new_mode = qtsdl::wrap(mode);
     if (this->mode != new_mode || this->effective_mode_index != mode_index) {
         this->effective_mode_index = mode_index;
         this->mode = new_mode;
         emit this->mode_changed();
     }
 }
References effective_mode_index, mode, mode_changed(), mode_index, and qtsdl::wrap().
Referenced by on_core_adopted(), and on_modes_changed().
on_modes_changed
void openage::gui::GameControlLink::on_modes_changed (OutputMode * mode, int mode_index) private slot
Definition at line 345 of file game_control_link.cpp.
{
     static auto f = [] (GameControl *_this, int mode) {
         _this->set_mode(mode);
     };
     this->i(f, this->mode_index);
     this->on_mode_changed(mode, mode_index);
     emit this->modes_changed();
 }
References qtsdl::GuiItemMethods< GameControlLink >::i(), mode, mode_index, modes_changed(), on_mode_changed(), and openage::GameControl::set_mode().
Referenced by on_core_adopted().
set_engine()
void openage::gui::GameControlLink::set_engine (EngineLink * engine)
Definition at line 309 of file game_control_link.cpp.
{
     static auto f = [] (GameControl *_this, Engine *engine) {
         _this->set_engine(engine);
     };
     this->s(f, this->engine, engine);
 }
References engine, qtsdl::GuiItemMethods< GameControlLink >::s(), and openage::GameControl::set_engine().
set_game()
void openage::gui::GameControlLink::set_game (GameMainLink * game)
Definition at line 320 of file game_control_link.cpp.
{
     static auto f = [] (GameControl *_this, GameMainHandle *game) {
         _this->set_game(game);
     };
     this->s(f, this->game, game);
 }
References game, qtsdl::GuiItemMethods< GameControlLink >::s(), and openage::GameControl::set_game().
set_mode_index()
void openage::gui::GameControlLink::set_mode_index (int mode)
Definition at line 279 of file game_control_link.cpp.
{
     static auto f = [] (GameControl *_this, int mode) {
         _this->set_mode(mode, true);
     };
     this->sf(f, this->mode_index, mode);
 }
References mode, mode_index, openage::GameControl::set_mode(), and qtsdl::GuiItemMethods< GameControlLink >::sf().
set_modes()
void openage::gui::GameControlLink::set_modes (const QVariantList & modes)
Definition at line 291 of file game_control_link.cpp.
{
     static auto f = [] (GameControl *_this, const QVariantList &modes) {
         std::vector<OutputMode*> new_modes;
         for (auto m : modes)
             if (m.canConvert<OutputModeLink*>())
                 new_modes.push_back(unwrap(m.value<OutputModeLink*>()));
         _this->set_modes(new_modes);
     };
     this->s(f, this->modes, modes);
 }
References modes, qtsdl::GuiItemMethods< GameControlLink >::s(), openage::GameControl::set_modes(), and qtsdl::unwrap().
Member Data Documentation
current_civ_index
int openage::gui::GameControlLink::current_civ_index private
Definition at line 296 of file game_control_link.h.
Referenced by get_current_civ_index(), and on_current_civ_index_changed().
current_player_name
QString openage::gui::GameControlLink::current_player_name private
Definition at line 295 of file game_control_link.h.
Referenced by get_current_player_name(), and on_current_player_name_changed().
effective_mode_index
int openage::gui::GameControlLink::effective_mode_index private
Definition at line 289 of file game_control_link.h.
Referenced by get_effective_mode_index(), and on_mode_changed().
engine
EngineLink* openage::gui::GameControlLink::engine private
Definition at line 293 of file game_control_link.h.
game
GameMainLink* openage::gui::GameControlLink::game private
Definition at line 294 of file game_control_link.h.
mode
OutputModeLink* openage::gui::GameControlLink::mode private
Definition at line 288 of file game_control_link.h.
mode_index
int openage::gui::GameControlLink::mode_index private
Definition at line 290 of file game_control_link.h.
Referenced by get_mode_index(), on_mode_changed(), on_modes_changed(), and set_mode_index().
Property Documentation
currentCivIndex
int openage::gui::GameControlLink::currentCivIndex read
Definition at line 247 of file game_control_link.h.
currentPlayerName
QString openage::gui::GameControlLink::currentPlayerName read
Definition at line 246 of file game_control_link.h.
effectiveModeIndex
int openage::gui::GameControlLink::effectiveModeIndex read
Definition at line 241 of file game_control_link.h.
engine
openage::gui::EngineLink openage::gui::GameControlLink::engine read write
Definition at line 244 of file game_control_link.h.
Referenced by get_engine(), and set_engine().
game
openage::gui::GameMainLink openage::gui::GameControlLink::game read write
Definition at line 245 of file game_control_link.h.
Referenced by get_game(), and set_game().
mode
openage::gui::OutputModeLink openage::gui::GameControlLink::mode read
Definition at line 240 of file game_control_link.h.
Referenced by get_mode(), on_mode_changed(), on_modes_changed(), and set_mode_index().
modeIndex
int openage::gui::GameControlLink::modeIndex read write
Definition at line 242 of file game_control_link.h.
modes
QVariantList openage::gui::GameControlLink::modes read write
Definition at line 243 of file game_control_link.h.
Referenced by get_modes(), and set_modes().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/game_control_link.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/game_control_link.cpp