openage: openage::job::JobManager Class Reference
openage::job::JobManager Class Reference
#include <job_manager.h>
Public Member Functions
JobManager (int number_of_workers)
~JobManager ()
JobManager (const JobManager &)=delete
JobManager (JobManager &&)=delete
JobManager & operator= (const JobManager &)=delete
JobManager & operator= (JobManager &&)=delete
void start ()
void stop ()
template<class T >
Job< T > enqueue (job_function_t< T > function, callback_function_t< T > callback={})
template<class T >
Job< T > enqueue (abortable_function_t< T > function, callback_function_t< T > callback={})
JobGroup create_job_group ()
void execute_callbacks ()
Private Member Functions
void enqueue_state (std::shared_ptr< JobStateBase > state)
std::shared_ptr< JobStateBase > fetch_job ()
bool has_job ()
void finish_job (std::shared_ptr< JobStateBase > job)
Private Attributes
int number_of_workers
int group_index
std::vector< std::unique_ptr< Worker > > workers
std::mutex pending_jobs_mutex
std::queue< std::shared_ptr< JobStateBase > > pending_jobs
std::mutex finished_jobs_mutex
std::unordered_map< size_t, std::vector< std::shared_ptr< JobStateBase > > > finished_jobs
std::atomic_bool is_running
Friends
class Worker
Detailed Description
A job manager can be used to execute functions within separate worker threads.
Definition at line 29 of file job_manager.h.
Constructor & Destructor Documentation
JobManager() [1/3]
openage::job::JobManager::JobManager (int number_of_workers)
Create a new job manager with a specified number of worker threads.
Definition at line 14 of file job_manager.cpp.
     :
     number_of_workers{number_of_workers},
     group_index{0},
     is_running{false} {
     for (int i = 0; i < number_of_workers; i++) {
         this->workers.emplace_back(new Worker{this});
     }
 }
References number_of_workers.
~JobManager()
openage::job::JobManager::~JobManager ()
Destructor that stops the job manager if it is still running.
Definition at line 26 of file job_manager.cpp.
{
     this->stop();
 }
References stop().
JobManager() [2/3]
openage::job::JobManager::JobManager (const JobManager &) delete
JobManager() [3/3]
openage::job::JobManager::JobManager (JobManager &&) delete
Member Function Documentation
create_job_group()
JobGroup openage::job::JobManager::create_job_group ()
Creates a job group, in order to be able to execute multiple jobs on the same worker thread.
Definition at line 83 of file job_manager.cpp.
{
     auto index = this->group_index;
     this->group_index = (this->group_index + 1) % this->number_of_workers;
     return JobGroup{this->workers[index].get()};
 }
References group_index, and workers.
Referenced by openage::audio::DynamicResource::use().
enqueue() [1/2]
template<class T > Job<T> openage::job::JobManager::enqueue (job_function_t< T > function, callback_function_t< T > callback = {}) inline
Enqueues the given function into the job manager's queue, so that it will be dispatched by one of the worker threads. A lightweight Job object is returned, that allows to keep track of the job's state.
Parameters
function the function that is executed as background job
callback the callback function that is executed, when the background job has finished
Definition at line 93 of file job_manager.h.
                                                    {}) {
         auto state = std::make_shared<JobState<T>>(function, callback);
         this->enqueue_state(state);
         return Job<T>{state};
     }
Referenced by openage::ScreenshotManager::save_screenshot(), and openage::GameSpecHandle::start_load_job().
enqueue() [2/2]
template<class T > Job<T> openage::job::JobManager::enqueue (abortable_function_t< T > function, callback_function_t< T > callback = {}) inline
Enqueues the given function into the job manager's queue, so that it will be dispatched by one of the worker threads. A lightweight job object is returned, that allows to keep track of the job's state. The passed function must accept a function object that returns, whether the job should be aborted at any time. Further it must accept a function that can be used to abort the execution of the function.
Parameters
function the function that is executed as background job
callback the callback function that is executed, when the background job has finished
Definition at line 113 of file job_manager.h.
                                                    {}) {
         auto state = std::make_shared<AbortableJobState<T>>(function, callback);
         this->enqueue_state(state);
         return Job<T>{state};
     }
enqueue_state()
void openage::job::JobManager::enqueue_state (std::shared_ptr< JobStateBase > state) private
Enqueues the given job into the internal job queue.
Definition at line 90 of file job_manager.cpp.
{
     std::lock_guard<std::mutex> lock{this->pending_jobs_mutex};
     this->pending_jobs.push(state);
     for (auto &worker : this->workers) {
         worker->notify();
     }
 }
References lock, pending_jobs, pending_jobs_mutex, openage::worker, and workers.
execute_callbacks()
void openage::job::JobManager::execute_callbacks ()
Executes callbacks for all job's, that were created by the current thread and have finished.
Definition at line 59 of file job_manager.cpp.
{
     // run callbacks for finished jobs on this thread id.
     size_t id = util::get_current_thread_id();
     std::unique_lock<std::mutex> lock{this->finished_jobs_mutex};
     auto it = this->finished_jobs.find(id);
     if (it != std::end(this->finished_jobs)) {
         // move the  the finished job list here so we can disable the lock
         std::vector<std::shared_ptr<JobStateBase>> jobs;
         std::swap(jobs, it->second);
         // clear the worker's old finished job list
         it->second.clear();
         lock.unlock();
         for (auto &job : jobs) {
             // the job may throw an exception here
             job->execute_callback();
         }
     }
 }
References finished_jobs, finished_jobs_mutex, openage::util::get_current_thread_id(), and lock.
Referenced by openage::Engine::loop().
fetch_job()
std::shared_ptr< JobStateBase > openage::job::JobManager::fetch_job () private
Returns a job from the internal job queue. If the queue is empty, a nullptr is returned.
Definition at line 99 of file job_manager.cpp.
{
     std::lock_guard<std::mutex> lock{this->pending_jobs_mutex};
     if (this->pending_jobs.empty()) {
         return std::shared_ptr<JobStateBase>{};
     }
     auto job = this->pending_jobs.front();
     this->pending_jobs.pop();
     return job;
 }
References lock, pending_jobs, and pending_jobs_mutex.
Referenced by openage::job::Worker::process().
finish_job()
void openage::job::JobManager::finish_job (std::shared_ptr< JobStateBase > job) private
Adds a finished job to the internal finished job map.
Definition at line 117 of file job_manager.cpp.
{
     std::lock_guard<std::mutex> lock{this->finished_jobs_mutex};
     auto it = this->finished_jobs.find(job->get_thread_id());
     // if there hasn't been a finished job for the thread_id, create a new
     // entry
     if (it == std::end(this->finished_jobs)) {
         this->finished_jobs.insert({job->get_thread_id(), {job}});
     // otherwise, we append the job to the existing entry
     } else {
         it->second.push_back(job);
     }
 }
References finished_jobs, finished_jobs_mutex, and lock.
Referenced by openage::job::Worker::execute_job().
has_job()
bool openage::job::JobManager::has_job () private
Returns whether there are jobs to be executed.
Definition at line 111 of file job_manager.cpp.
{
     std::lock_guard<std::mutex> lock(this->pending_jobs_mutex);
     return not this->pending_jobs.empty();
 }
References lock, pending_jobs, and pending_jobs_mutex.
Referenced by openage::job::Worker::process().
operator=() [1/2]
JobManager& openage::job::JobManager::operator= (const JobManager &) delete
operator=() [2/2]
JobManager& openage::job::JobManager::operator= (JobManager &&) delete
start()
void openage::job::JobManager::start ()
Start the job manager's worker threads.
Definition at line 31 of file job_manager.cpp.
{
     // if the workers have not been started, start them now
     if (not this->is_running.load()) {
         this->is_running.store(true);
         for (auto &worker : this->workers) {
             worker->start();
         }
         log::log(DBG << "Started JobManager with " << this->number_of_workers << " worker threads");
     }
 }
References DBG, is_running, openage::log::log(), openage::worker, and workers.
Referenced by openage::Engine::run(), openage::job::tests::test_simple_job(), and openage::job::tests::test_simple_job_with_exception().
stop()
void openage::job::JobManager::stop ()
Stop the job manager's worker threads. This method blocks until all currently working threads have finished.
Definition at line 43 of file job_manager.cpp.
                       {
     // set is_running to false, notify and join all workers
     if (this->is_running.load()) {
         this->is_running.store(false);
         for (auto &worker : this->workers) {
             worker->stop();
         }
         for (auto &worker : this->workers) {
             worker->join();
         }
         log::log(DBG << "Stopped JobManager with " << this->number_of_workers << " worker threads");
     }
 }
References DBG, is_running, openage::log::log(), openage::worker, and workers.
Referenced by openage::Engine::run(), openage::Engine::stop(), and ~JobManager().
Friends And Related Function Documentation
Worker
friend class Worker friend
A worker has to be a friend of the job manager in order to call the private finish_job method.
Definition at line 152 of file job_manager.h.
Member Data Documentation
finished_jobs
std::unordered_map<size_t, std::vector<std::shared_ptr<JobStateBase> > > openage::job::JobManager::finished_jobs private
Mapping from thread id's to a list of jobs, that have been created by the corresponding thread and have finished.
Definition at line 56 of file job_manager.h.
Referenced by execute_callbacks(), and finish_job().
finished_jobs_mutex
std::mutex openage::job::JobManager::finished_jobs_mutex private
A mutex to synchronize the finished job map.
Definition at line 50 of file job_manager.h.
Referenced by execute_callbacks(), and finish_job().
group_index
int openage::job::JobManager::group_index private
The index of the worker thread, that is used for the next returned job group.
Definition at line 38 of file job_manager.h.
Referenced by create_job_group().
is_running
std::atomic_bool openage::job::JobManager::is_running private
Whether the job manager is currently running.
Definition at line 59 of file job_manager.h.
Referenced by start(), and stop().
number_of_workers
int openage::job::JobManager::number_of_workers private
The number of internal worker threads.
Definition at line 32 of file job_manager.h.
Referenced by JobManager().
pending_jobs
std::queue<std::shared_ptr<JobStateBase> > openage::job::JobManager::pending_jobs private
A queue of jobs that are to be executed.
Definition at line 47 of file job_manager.h.
Referenced by enqueue_state(), fetch_job(), and has_job().
pending_jobs_mutex
std::mutex openage::job::JobManager::pending_jobs_mutex private
A mutex to synchronize accesses to the internal job queue.
Definition at line 44 of file job_manager.h.
Referenced by enqueue_state(), fetch_job(), and has_job().
workers
std::vector<std::unique_ptr<Worker> > openage::job::JobManager::workers private
A vector of all worker threads.
Definition at line 41 of file job_manager.h.
Referenced by create_job_group(), enqueue_state(), start(), and stop().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/job/job_manager.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/job/job_manager.cpp