openage: openage::util::VariableBase Class Reference
openage::util::VariableBase Class Reference
A typed value holder.
#include <variable.h>
Public Member Functions
virtual ~VariableBase ()
template<class T , class V >
void set (const V &value)
sets the type and value
template<class T >
const T & get () const
returns the stored value throws an exception if the template does not match the set type
Detailed Description
A typed value holder.
Definition at line 11 of file variable.h.
Constructor & Destructor Documentation
~VariableBase()
virtual openage::util::VariableBase::~VariableBase () inline virtual
Definition at line 13 of file variable.h.
 {}
Member Function Documentation
get()
template<class T > const T & openage::util::VariableBase::get () const
returns the stored value throws an exception if the template does not match the set type
Definition at line 54 of file variable.h.
{
     return dynamic_cast<const Variable<T> &>(*this).get();
 }
References openage::util::Variable< T >::get().
Referenced by openage::options::OptionValue::value().
set()
template<class T , class V > void openage::util::VariableBase::set (const V & value)
sets the type and value
Definition at line 59 of file variable.h.
{
     return dynamic_cast<Variable<T> &>(*this).set(value);
 }
References openage::util::Variable< T >::set().
Referenced by openage::options::OptionValue::set_value().
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/variable.h