openage: openage::event::demo::Physics Class Reference
openage::event::demo::Physics Class Reference
#include <physics.h>
Public Member Functions
void process_input (const std::shared_ptr< PongState > &, const std::shared_ptr< PongPlayer > &, const std::vector< PongEvent > &input, const std::shared_ptr< Loop > &mgr, const curve::time_t &now)
Static Public Member Functions
static void init (const std::shared_ptr< PongState > &, const std::shared_ptr< Loop > &mgr, const curve::time_t &)
static void reset (const std::shared_ptr< State > &, Loop &mgr, const curve::time_t &)
Detailed Description
Definition at line 17 of file physics.h.
Member Function Documentation
init()
void openage::event::demo::Physics::init (const std::shared_ptr< PongState > & gstate, const std::shared_ptr< Loop > & mgr, const curve::time_t & now) static
Definition at line 362 of file physics.cpp.
{
     auto state = std::dynamic_pointer_cast<PongState>(gstate);
     if (not state->enable_gui) {
         log::log(INFO << "Physics initialization");
     }
     loop->add_event_class(std::make_shared<BallReflectPanel>());
     loop->add_event_class(std::make_shared<BallReflectWall>());
     loop->add_event_class(std::make_shared<ResetGame>());
     loop->create_event("demo.ball.reflect_wall", state->ball->position, state, now);
     loop->create_event("demo.ball.reflect_panel", state->ball->position, state, now);
     // FIXME once "reset": deregister
     //reset(state, mgr, now);
 }
References INFO, and openage::log::log().
process_input()
void openage::event::demo::Physics::process_input (const std::shared_ptr< PongState > & state, const std::shared_ptr< PongPlayer > & player, const std::vector< PongEvent > & input, const std::shared_ptr< Loop > & mgr, const curve::time_t & now)
Definition at line 383 of file physics.cpp.
{
     // seconds into the future
     constexpr static auto predicted_movement_time = curve::time_t::from_double(5.0);
     // lines per second
     constexpr static double movement_speed = 8.0;
     for (auto& evnt : events) {
         // Process only if the future has changed
         if (player->state->get(now).state != evnt.state) {
             // log the new input in the state curve
             player->state->set_last(now, evnt);
             // if the state is active longer than predicted,
             // we have to extend the prediction!
             bool extend_previous_prediction = false;
             auto prev_state = player->state->get_previous(now);
             if (prev_state and prev_state->second.state == evnt.state) {
                 extend_previous_prediction = true;
             }
             switch(evnt.state) {
             case PongEvent::UP:
             case PongEvent::DOWN: {
                 float current_pos = player->position->get(now);
                 if (not extend_previous_prediction) {
                     // create a keyframe for the new movement
                     player->position->set_last(now, current_pos);
                     // TODO: drop the intermediate keyframes
                     //       for position and speed.
                 }
                 switch (evnt.state) {
                 case PongEvent::UP:
                     player->speed->set_last(now, -movement_speed);
                     break;
                 case PongEvent::DOWN:
                     player->speed->set_last(now, movement_speed);
                     break;
                 default:
                     // never reached.
                     break;
                 }
                 curve::time_t move_stop_guess = now + predicted_movement_time;
                 // change the position by integrating the speed curve.
                 // TODO: add native integral to curves.
                 float new_pos = current_pos +
                                 (((player->speed->get(move_stop_guess) +
                                    player->speed->get(now)) / 2.0) *
                                  predicted_movement_time.to_double());
                 // if paddle will get out-of-bounds, calculate the bound hit time
                 // TODO: add native key/value finding in range to curves
                 if (new_pos < 0) {
                     move_stop_guess = now + (current_pos / movement_speed);
                     new_pos = 0;
                 }
                 if (new_pos > state->display_boundary[1]) {
                     move_stop_guess = now + ((state->display_boundary[1] - current_pos) / movement_speed);
                     new_pos = state->display_boundary[1];
                 }
                 PongEvent set_idle{evnt.player, PongEvent::IDLE};
                 player->state->set_last(move_stop_guess, set_idle);
                 player->speed->set_last(move_stop_guess, 0);
                 player->position->set_last(move_stop_guess, new_pos);
                 // TODO: predict_reflect_panel(state, queue, now);
                 break;
             }
             case PongEvent::IDLE:
                 player->position->set_last(now, player->position->get(now));
                 player->speed->set_last(now, 0);
                 break;
             case PongEvent::START:
                 Physics::reset(state, *mgr, now);
                 break;
                 //if (player->state->get(now).state == PongEvent::LOST) {
                 //  state->ball.position->set_last(now, state.display_boundary * 0.5);
                 //}
                 //update_ball(state, now, init_recursion_limit);
                 //break;
             default:
                 break;
             }
         }
     }
 }
References openage::event::demo::PongEvent::DOWN, openage::util::FixedPoint< int64_t, 16 >::from_double(), openage::event::demo::PongEvent::IDLE, openage::event::demo::PongEvent::player, reset(), openage::event::demo::PongEvent::START, and openage::event::demo::PongEvent::UP.
Referenced by openage::event::demo::curvepong().
reset()
void openage::event::demo::Physics::reset (const std::shared_ptr< State > & gstate, Loop & mgr, const curve::time_t & now) static
Definition at line 489 of file physics.cpp.
{
     auto state = std::dynamic_pointer_cast<PongState>(gstate);
     mgr.create_event("demo.reset", state->ball->position, state, now);
 }
References openage::event::Loop::create_event().
Referenced by openage::event::demo::BallReflectPanel::invoke(), and process_input().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/event/demo/physics.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/event/demo/physics.cpp