openage: openage::SetPointAbility Class Reference
openage::SetPointAbility Class Reference
#include <ability.h>
Public Member Functions
SetPointAbility ()
ability_type type () override
bool can_invoke (Unit &to_modify, const Command &cmd) override
void invoke (Unit &to_modify, const Command &cmd, bool play_sound=false) override
Public Member Functions inherited from openage::UnitAbility
virtual ~UnitAbility ()
bool has_hitpoints (Unit &target)
bool is_damaged (Unit &target)
bool has_resource (Unit &target)
bool is_same_player (Unit &to_modify, Unit &target)
bool is_ally (Unit &to_modify, Unit &target)
bool is_enemy (Unit &to_modify, Unit &target)
Additional Inherited Members
Static Public Member Functions inherited from openage::UnitAbility
static ability_set set_from_list (const std::vector< ability_type > &items)
Detailed Description
sets the gather point on buildings
Definition at line 140 of file ability.h.
Constructor & Destructor Documentation
SetPointAbility()
openage::SetPointAbility::SetPointAbility ()
Definition at line 104 of file ability.cpp.
 {}
Member Function Documentation
can_invoke()
bool openage::SetPointAbility::can_invoke (Unit & to_modify, const Command & cmd) override virtual
true if the paramaters allow an action to be performed
Implements openage::UnitAbility.
Definition at line 106 of file ability.cpp.
{
     return cmd.has_position() &&
            to_modify.has_attribute(attr_type::building);
 }
References openage::building, openage::Unit::has_attribute(), and openage::Command::has_position().
invoke()
void openage::SetPointAbility::invoke (Unit & to_modify, const Command & cmd, bool play_sound = false) override virtual
applies command to a given unit
Implements openage::UnitAbility.
Definition at line 111 of file ability.cpp.
{
     auto &build_attr = to_modify.get_attribute<attr_type::building>();
     build_attr.gather_point = cmd.position();
 }
References openage::building, openage::Unit::get_attribute(), and openage::Command::position().
type()
ability_type openage::SetPointAbility::type () inline override virtual
Implements openage::UnitAbility.
Definition at line 144 of file ability.h.
{
         return ability_type::set_point;
     }
References openage::set_point.
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/ability.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/ability.cpp