openage: openage::ResourceProducer Class Reference
openage::ResourceProducer Class Reference
#include <resource.h>
Public Member Functions
ResourceProducer (int id, std::string name)
int id () const override
std::string name () const override
Public Member Functions inherited from openage::Resource
Resource ()
Private Attributes
int _id
std::string _name
Detailed Description
Definition at line 28 of file resource.h.
Constructor & Destructor Documentation
ResourceProducer()
openage::ResourceProducer::ResourceProducer (int id, std::string name) inline
Definition at line 31 of file resource.h.
         :
         _id{id},
         _name{name} { }
Member Function Documentation
id()
int openage::ResourceProducer::id () const inline override virtual
Implements openage::Resource.
Definition at line 36 of file resource.h.
 { return _id; }
References _id.
name()
std::string openage::ResourceProducer::name () const inline override virtual
Implements openage::Resource.
Definition at line 38 of file resource.h.
 { return _name; }
References _name.
Referenced by openage.util.fslike.path.Path::stem(), openage.util.fslike.path.Path::suffix(), and openage.util.fslike.path.Path::suffixes().
Member Data Documentation
_id
int openage::ResourceProducer::_id private
Definition at line 42 of file resource.h.
Referenced by id().
_name
std::string openage::ResourceProducer::_name private
Definition at line 43 of file resource.h.
Referenced by name().
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gamestate/resource.h