openage: openage::GameSpecHandle Class Reference
openage::GameSpecHandle Class Reference
Game specification instanciated in QML.
#include <game_spec.h>
Public Member Functions
GameSpecHandle (qtsdl::GuiItemLink *gui_link)
void set_active (bool active)
Control whether this specification can be loaded (=true) or will not be loaded (=false).
void set_asset_manager (AssetManager *asset_manager)
invoked from qml when the asset_manager member is set.
bool is_ready () const
Return if the specification was fully loaded.
void invalidate ()
forget everything about the specification and reload it with start_loading_if_needed.
void announce_spec ()
signal about a loaded spec if any
std::shared_ptr< GameSpec > get_spec ()
Return the contained game specification.
Public Attributes
std::shared_ptr< GameSpecSignals > gui_signals
qtsdl::GuiItemLink * gui_link
Private Member Functions
void start_loading_if_needed ()
load the game specification if not already present.
void start_load_job ()
Actually dispatch the loading job to the job manager.
void on_loaded (job::result_function_t< bool > result)
called from the job manager when the loading job finished.
Private Attributes
std::shared_ptr< GameSpec > spec
The real game specification.
bool active
enables the loading of the game specification.
AssetManager * asset_manager
Detailed Description
Game specification instanciated in QML.
Linked to the "GameSpec" QML type.
Wraps the "GameSpec" C++ class from above.
Definition at line 252 of file game_spec.h.
Constructor & Destructor Documentation
GameSpecHandle()
openage::GameSpecHandle::GameSpecHandle (qtsdl::GuiItemLink * gui_link) explicit
Definition at line 455 of file game_spec.cpp.
     :
     active{},
     asset_manager{},
     gui_signals{std::make_shared<GameSpecSignals>()},
     gui_link{gui_link} {
 }
Member Function Documentation
announce_spec()
void openage::GameSpecHandle::announce_spec ()
signal about a loaded spec if any
Definition at line 490 of file game_spec.cpp.
{
     if (this->spec && this->spec->load_complete())
         emit this->gui_signals->game_spec_loaded(this->spec);
 }
References gui_signals, and spec.
get_spec()
std::shared_ptr< GameSpec > openage::GameSpecHandle::get_spec ()
Return the contained game specification.
Definition at line 495 of file game_spec.cpp.
{
     return this->spec;
 }
References spec.
invalidate()
void openage::GameSpecHandle::invalidate ()
forget everything about the specification and reload it with start_loading_if_needed.
Definition at line 481 of file game_spec.cpp.
{
     this->spec = nullptr;
     if (this->asset_manager)
         this->asset_manager->check_updates();
     this->start_loading_if_needed();
 }
References asset_manager, openage::AssetManager::check_updates(), spec, and start_loading_if_needed().
is_ready()
bool openage::GameSpecHandle::is_ready () const
Return if the specification was fully loaded.
Definition at line 477 of file game_spec.cpp.
{
     return this->spec && this->spec->load_complete();
 }
References spec.
on_loaded()
void openage::GameSpecHandle::on_loaded (job::result_function_t< bool > result) private
called from the job manager when the loading job finished.
set_active()
void openage::GameSpecHandle::set_active (bool active)
Control whether this specification can be loaded (=true) or will not be loaded (=false).
Definition at line 463 of file game_spec.cpp.
{
     this->active = active;
     this->start_loading_if_needed();
 }
References active, and start_loading_if_needed().
Referenced by openage::gui::GameSpecLink::set_active().
set_asset_manager()
void openage::GameSpecHandle::set_asset_manager (AssetManager * asset_manager)
invoked from qml when the asset_manager member is set.
Definition at line 469 of file game_spec.cpp.
{
     if (this->asset_manager != asset_manager) {
         this->asset_manager = asset_manager;
         this->start_loading_if_needed();
     }
 }
References asset_manager, and start_loading_if_needed().
Referenced by openage::gui::GameSpecLink::set_asset_manager().
start_load_job()
void openage::GameSpecHandle::start_load_job () private
Actually dispatch the loading job to the job manager.
Definition at line 510 of file game_spec.cpp.
{
     // store the shared pointers in another sharedptr
     // so we can pass them to the other thread
     auto spec_and_job = std::make_tuple(this->spec, this->gui_signals, job::Job<bool>{});
     auto spec_and_job_ptr = std::make_shared<decltype(spec_and_job)>(spec_and_job);
     // lambda to be executed to actually load the data files.
     auto perform_load = [spec_and_job_ptr] {
         return std::get<std::shared_ptr<GameSpec>>(*spec_and_job_ptr)->initialize();
     };
     auto load_finished = [gui_signals_ptr = this->gui_signals.get()] (job::result_function_t<bool> result) {
         bool load_ok;
         try {
             load_ok = result();
         }
         catch (Error &) {
             // \todo display that error in the ui.
             throw;
         }
         catch (std::exception &) {
             // \todo same here.
             throw Error{ERR << "gamespec loading failed!"};
         }
         if (load_ok) {
             // send the signal that the load job was finished
             emit gui_signals_ptr->load_job_finished();
         }
     };
     job::JobManager *job_mgr = this->asset_manager->get_engine()->get_job_manager();
     std::get<job::Job<bool>>(*spec_and_job_ptr) = job_mgr->enqueue<bool>(
         perform_load, load_finished
     );
 }
References asset_manager, openage::job::JobManager::enqueue(), ERR, openage::AssetManager::get_engine(), openage::Engine::get_job_manager(), gui_signals, openage.testing.testing::result(), and spec.
Referenced by start_loading_if_needed().
start_loading_if_needed()
void openage::GameSpecHandle::start_loading_if_needed () private
load the game specification if not already present.
Definition at line 499 of file game_spec.cpp.
{
     if (this->active && this->asset_manager && !this->spec) {
         // create the game specification
         this->spec = std::make_shared<GameSpec>(this->asset_manager);
         // the load the data
         this->start_load_job();
     }
 }
References active, asset_manager, spec, and start_load_job().
Referenced by invalidate(), set_active(), and set_asset_manager().
Member Data Documentation
active
bool openage::GameSpecHandle::active private
enables the loading of the game specification.
Definition at line 312 of file game_spec.h.
Referenced by set_active(), and start_loading_if_needed().
asset_manager
AssetManager* openage::GameSpecHandle::asset_manager private
Definition at line 314 of file game_spec.h.
Referenced by invalidate(), set_asset_manager(), start_load_job(), and start_loading_if_needed().
gui_link
qtsdl::GuiItemLink* openage::GameSpecHandle::gui_link
Definition at line 318 of file game_spec.h.
gui_signals
std::shared_ptr<GameSpecSignals> openage::GameSpecHandle::gui_signals
Definition at line 317 of file game_spec.h.
Referenced by announce_spec(), and start_load_job().
spec
std::shared_ptr<GameSpec> openage::GameSpecHandle::spec private
The real game specification.
Definition at line 307 of file game_spec.h.
Referenced by announce_spec(), get_spec(), invalidate(), is_ready(), start_load_job(), and start_loading_if_needed().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gamestate/game_spec.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gamestate/game_spec.cpp