openage: openage::job::TypedJobStateBase< T > Class Template Reference
openage::job::TypedJobStateBase< T > Class Template Reference abstract
A templated job state base class, that implements basic functionality of job states.
#include <typed_job_state_base.h>
Public Member Functions
TypedJobStateBase (callback_function_t< T > callback)
Creates a new typed job with the given callback.
virtual ~TypedJobStateBase ()=default
Default destructor.
bool execute (should_abort_t should_abort) override
Executes the internal function object and stores its result.
void execute_callback () override
Called when the job was finished.
size_t get_thread_id () override
Returns the id of the thread that has created this job.
Public Member Functions inherited from openage::job::JobStateBase
virtual ~JobStateBase ()=default
Default constructor.
Public Attributes
size_t thread_id
Id of the thread, that created this job state.
callback_function_t< T > callback
A callback function that is called when the job has finished.
std::atomic_bool finished
Whether the Job's execution has already been finished.
T result
The result of the Job's executed function.
std::exception_ptr exception
If executing the Job throws an exception, it is stored here.
Protected Member Functions
virtual T execute_and_get (should_abort_t should_abort)=0
Executes the job and returns the result.
Detailed Description
template<class T>
class openage::job::TypedJobStateBase< T >
A templated job state base class, that implements basic functionality of job states.
Parameters
T the result type of this job state. This type must have a default constructor and support move semantics.
Definition at line 26 of file typed_job_state_base.h.
Constructor & Destructor Documentation
TypedJobStateBase()
template<class T > openage::job::TypedJobStateBase< T >::TypedJobStateBase (callback_function_t< T > callback) inline
Creates a new typed job with the given callback.
Definition at line 51 of file typed_job_state_base.h.
         :
         thread_id{openage::util::get_current_thread_id()},
         callback{callback},
         finished{false} {
     }
References openage::util::get_current_thread_id().
~TypedJobStateBase()
template<class T > virtual openage::job::TypedJobStateBase< T >::~TypedJobStateBase () virtual default
Default destructor.
Member Function Documentation
execute()
template<class T > bool openage::job::TypedJobStateBase< T >::execute (should_abort_t should_abort) inline override virtual
Executes the internal function object and stores its result.
Occuring exceptions are stored, as well. Returns whether this job has been aborted.
Implements openage::job::JobStateBase.
Definition at line 66 of file typed_job_state_base.h.
{
         try {
             this->result = this->execute_and_get(should_abort);
         } catch (JobAbortedException &e) {
             return true;
         } catch (...) {
             this->exception = std::current_exception();
         }
         this->finished.store(true);
         return false;
     }
References openage::job::TypedJobStateBase< T >::execute_and_get().
execute_and_get()
template<class T > virtual T openage::job::TypedJobStateBase< T >::execute_and_get (should_abort_t should_abort) protected pure virtual
Executes the job and returns the result.
If an exception is thrown it must be passed to the calling function.
Implemented in openage::job::AbortableJobState< T >, and openage::job::JobState< T >.
Referenced by openage::job::TypedJobStateBase< T >::execute().
execute_callback()
template<class T > void openage::job::TypedJobStateBase< T >::execute_callback () inline override virtual
Called when the job was finished.
This is the result notification for the place where the job was constructed.
Implements openage::job::JobStateBase.
Definition at line 82 of file typed_job_state_base.h.
{
         ENSURE(this->finished.load(), "trying to report a result of an unfinished job");
         if (this->callback) {
             auto get_result = [this]() {
                 if (this->exception != nullptr) {
                     std::rethrow_exception(this->exception);
                 } else {
                     return std::move(this->result);
                 }
             };
             this->callback(get_result);
         }
     }
References openage::job::TypedJobStateBase< T >::callback, ENSURE, and openage::move.
get_thread_id()
template<class T > size_t openage::job::TypedJobStateBase< T >::get_thread_id () inline override virtual
Returns the id of the thread that has created this job.
Implements openage::job::JobStateBase.
Definition at line 96 of file typed_job_state_base.h.
{
         return this->thread_id;
     }
References openage::job::TypedJobStateBase< T >::thread_id.
Member Data Documentation
callback
template<class T > callback_function_t<T> openage::job::TypedJobStateBase< T >::callback
A callback function that is called when the job has finished.
Can be empty.
Definition at line 35 of file typed_job_state_base.h.
Referenced by openage::job::AbortableJobState< T >::AbortableJobState(), openage::job::TypedJobStateBase< T >::execute_callback(), and openage::job::JobState< T >::JobState().
exception
template<class T > std::exception_ptr openage::job::TypedJobStateBase< T >::exception
If executing the Job throws an exception, it is stored here.
Definition at line 48 of file typed_job_state_base.h.
finished
template<class T > std::atomic_bool openage::job::TypedJobStateBase< T >::finished
Whether the Job's execution has already been finished.
An atomic_bool is used, as this field can be used by multiple threads. Thus explicit synchronization is avoided.
Definition at line 42 of file typed_job_state_base.h.
result
template<class T > T openage::job::TypedJobStateBase< T >::result
The result of the Job's executed function.
Definition at line 45 of file typed_job_state_base.h.
thread_id
template<class T > size_t openage::job::TypedJobStateBase< T >::thread_id
Id of the thread, that created this job state.
Definition at line 29 of file typed_job_state_base.h.
Referenced by openage::job::TypedJobStateBase< T >::get_thread_id().
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/job/typed_job_state_base.h