openage: openage::UnitTexture Class Reference
openage::UnitTexture Class Reference
Handling animated and directional textures based on the game graphics data.
#include <unit_texture.h>
Public Member Functions
UnitTexture (GameSpec &spec, uint16_t graphic_id, bool delta=true)
Delta option specifies whether the delta graphics are included.
UnitTexture (GameSpec &spec, const gamedata::graphic *graphic, bool delta=true)
bool is_valid () const
invalid unit textures will cause errors if drawn
coord::viewport size () const
pixel size of this texture
void sample (const coord::CoordManager &coord, const coord::camhud &draw_pos, unsigned color=1) const
a sample drawing for hud
void draw (const coord::CoordManager &coord, const coord::camgame &draw_pos, unsigned int frame, unsigned color) const
draw object with no direction
void draw (const coord::CoordManager &coord, const coord::camgame &draw_pos, coord::phys3_delta &dir, unsigned int frame, unsigned color) const
draw object with direction
void initialise (GameSpec &spec)
initialise graphic data
Public Attributes
const int16_t id
const attributes of the graphic
const int16_t sound_id
const unsigned int frame_count
const unsigned int angle_count
const int16_t mirroring_mode
const float frame_rate
const bool use_up_angles
draw object with vertical orientation (arrows) adding an addtion degree of orientation
const bool use_deltas
use delta information
Private Member Functions
unsigned int subtexture (const Texture *t, unsigned int angle, unsigned int frame) const
find which subtexture should be used for drawing this texture
Private Attributes
const Texture * texture
use a regular texture for drawing
unsigned int safe_frame_count
the above frame count covers the entire graphic (with deltas) the actual number in the base texture may be different
unsigned int angles_included
unsigned int angles_mirrored
unsigned int top_frame
bool draw_this
const Sound * sound
std::vector< gamedata::graphic_delta > delta_id
std::vector< std::pair< std::unique_ptr< UnitTexture >, coord::camgame_delta > > deltas
Detailed Description
Handling animated and directional textures based on the game graphics data.
These objects handle the drawing of regular textures to use a unit's direction and include delta graphics.
This type can also deal with playing position based game sounds.
Definition at line 26 of file unit_texture.h.
Constructor & Destructor Documentation
UnitTexture() [1/2]
openage::UnitTexture::UnitTexture (GameSpec & spec, uint16_t graphic_id, bool delta = true)
Delta option specifies whether the delta graphics are included.
Note that the game data contains loops in delta links which mean recursive loading should be avoided
Definition at line 19 of file unit_texture.cpp.
     :
     UnitTexture{spec, spec.get_graphic_data(graphic_id), delta} {}
References openage::GameSpec::get_graphic_data().
UnitTexture() [2/2]
openage::UnitTexture::UnitTexture (GameSpec & spec, const gamedata::graphic * graphic, bool delta = true)
Definition at line 23 of file unit_texture.cpp.
     :
     id{graphic->id},
     sound_id{graphic->sound_id},
     frame_count{graphic->frame_count},
     angle_count{graphic->angle_count},
     mirroring_mode{graphic->mirroring_mode},
     frame_rate{graphic->frame_rate},
     use_up_angles{graphic->mirroring_mode == 24},
     use_deltas{delta},
     texture{nullptr},
     draw_this{true},
     sound{nullptr},
     delta_id{graphic->graphic_deltas.data} {
     this->initialise(spec);
 }
Member Function Documentation
draw() [1/2]
void openage::UnitTexture::draw (const coord::CoordManager & coord, const coord::camgame & draw_pos, unsigned int frame, unsigned color) const
draw object with no direction
Definition at line 62 of file unit_texture.cpp.
{
     // draw delta list first
     for (auto &d : this->deltas) {
         d.first->draw(coord, draw_pos + d.second, frame, color);
     }
     // draw texture
     if (this->draw_this) {
         unsigned int to_draw = frame % this->texture->get_subtexture_count();
         this->texture->draw(coord, draw_pos, PLAYERCOLORED, false, to_draw, color);
     }
 }
References openage::texturefont_shader::color, openage::coord::tests::coord(), deltas, openage::Texture::draw(), draw_this, openage::Texture::get_subtexture_count(), openage::PLAYERCOLORED, and texture.
draw() [2/2]
void openage::UnitTexture::draw (const coord::CoordManager & coord, const coord::camgame & draw_pos, coord::phys3_delta & dir, unsigned int frame, unsigned color) const
draw object with direction
Definition at line 76 of file unit_texture.cpp.
{
     unsigned int frame_to_use = frame;
     if (this->use_up_angles) {
         // up  1 => tilt 0
         // up -1 => tilt 1
         // up has a scale 5 times smaller
         double len = math::hypot3(dir.ne.to_double(), dir.se.to_double(), dir.up.to_double()/5);
         double up = dir.up.to_double()/(5.0 * len);
         frame_to_use = (0.5 - (0.5 * up)) * this->frame_count;
     }
     else if (this->sound && frame == 0.0) {
         this->sound->play();
     }
     // the index for the current direction
     unsigned int angle = dir_group(dir, this->angle_count);
     // mirroring is used to make additional image sets
     bool mirror = false;
     if (this->angles_included <= angle) {
         // this->angles_included <= angle < this->angle_count
         angle = this->top_frame - angle;
         mirror = true;
     }
     // draw delta list first
     for (auto &d : this->deltas) {
         d.first->draw(coord, draw_pos + d.second, dir, frame, color);
     }
     if (this->draw_this) {
         unsigned int to_draw = this->subtexture(this->texture, angle, frame_to_use);
         this->texture->draw(coord, draw_pos, PLAYERCOLORED, mirror, to_draw, color);
     }
 }
References angle_count, angles_included, openage::texturefont_shader::color, openage::coord::tests::coord(), deltas, openage::dir_group(), openage::Texture::draw(), draw_this, frame_count, openage::math::hypot3(), openage::Sound::play(), openage::PLAYERCOLORED, sound, subtexture(), texture, top_frame, and use_up_angles.
initialise()
void openage::UnitTexture::initialise (GameSpec & spec)
initialise graphic data
Definition at line 112 of file unit_texture.cpp.
{
     this->texture = spec.get_texture(this->id);
     this->sound = spec.get_sound(this->sound_id);
     if (not is_valid()) {
         this->draw_this = false;
     }
     // find deltas
     if (this->use_deltas) for (auto d : this->delta_id) {
         if (spec.get_graphic_data(d.graphic_id)) {
             auto ut = std::make_unique<UnitTexture>(spec, d.graphic_id, false);
             if (ut->is_valid()) {
                 this->deltas.push_back({std::move(ut), coord::camgame_delta{d.offset_x, d.offset_y}});
             }
         }
     }
     if (this->draw_this) {
         // the graphic frame count includes deltas
         unsigned int subtextures = this->texture->get_subtexture_count();
         if (subtextures >= this->frame_count) {
             // angles with graphic data
             this->angles_included = subtextures / this->frame_count;
             this->angles_mirrored = this->angle_count - this->angles_included;
             this->safe_frame_count = this->frame_count;
         }
         else {
             this->angles_included = 1;
             this->angles_mirrored = 0;
             this->safe_frame_count = subtextures;
         }
         // find the top direction for mirroring over
         this->top_frame = this->angle_count - (1 - (this->angles_included - this->angles_mirrored) / 2);
     }
 }
References angle_count, angles_included, angles_mirrored, delta_id, deltas, draw_this, frame_count, openage::GameSpec::get_graphic_data(), openage::GameSpec::get_sound(), openage::Texture::get_subtexture_count(), openage::GameSpec::get_texture(), is_valid(), openage::move, safe_frame_count, sound, sound_id, texture, top_frame, and use_deltas.
is_valid()
bool openage::UnitTexture::is_valid () const
invalid unit textures will cause errors if drawn
Definition at line 40 of file unit_texture.cpp.
{
     return texture;
 }
References texture.
Referenced by initialise().
sample()
void openage::UnitTexture::sample (const coord::CoordManager & coord, const coord::camhud & draw_pos, unsigned color = 1) const
a sample drawing for hud
Definition at line 48 of file unit_texture.cpp.
{
     // draw delta list first
     for (auto &d : this->deltas) {
         coord::camhud_delta dlt = coord::camhud_delta{d.second.x, d.second.y};
         d.first->sample(coord, draw_pos + dlt, color);
     }
     // draw texture
     if (this->draw_this) {
         this->texture->draw(coord, draw_pos, PLAYERCOLORED, false, 0, color);
     }
 }
References openage::texturefont_shader::color, openage::coord::tests::coord(), deltas, openage::Texture::draw(), draw_this, openage::PLAYERCOLORED, and texture.
size()
coord::viewport openage::UnitTexture::size () const
pixel size of this texture
Definition at line 44 of file unit_texture.cpp.
{
     return coord::viewport{this->texture->w, this->texture->h};
 }
References openage::Texture::h, texture, and openage::Texture::w.
subtexture()
unsigned int openage::UnitTexture::subtexture (const Texture * t, unsigned int angle, unsigned int frame) const private
find which subtexture should be used for drawing this texture
Definition at line 151 of file unit_texture.cpp.
{
     unsigned int tex_frames = t->get_subtexture_count();
     unsigned int count = tex_frames / this->angles_included;
     unsigned int to_draw = angle * count + (frame % count);
     if (tex_frames <= to_draw) {
         log::log(MSG(err) << "Subtexture out of range (" << angle << ", " << frame << ")");
         return 0;
     }
     return to_draw;
 }
References angles_included, openage::log::err(), openage::Texture::get_subtexture_count(), openage::log::log(), and MSG.
Referenced by draw().
Member Data Documentation
angle_count
const unsigned int openage::UnitTexture::angle_count
Definition at line 43 of file unit_texture.h.
Referenced by draw(), and initialise().
angles_included
unsigned int openage::UnitTexture::angles_included private
Definition at line 99 of file unit_texture.h.
Referenced by draw(), initialise(), and subtexture().
angles_mirrored
unsigned int openage::UnitTexture::angles_mirrored private
Definition at line 100 of file unit_texture.h.
Referenced by initialise().
delta_id
std::vector<gamedata::graphic_delta> openage::UnitTexture::delta_id private
Definition at line 108 of file unit_texture.h.
Referenced by initialise().
deltas
std::vector<std::pair<std::unique_ptr<UnitTexture>, coord::camgame_delta> > openage::UnitTexture::deltas private
Definition at line 111 of file unit_texture.h.
Referenced by draw(), initialise(), and sample().
draw_this
bool openage::UnitTexture::draw_this private
Definition at line 104 of file unit_texture.h.
Referenced by draw(), initialise(), and sample().
frame_count
const unsigned int openage::UnitTexture::frame_count
Definition at line 42 of file unit_texture.h.
Referenced by draw(), and initialise().
frame_rate
const float openage::UnitTexture::frame_rate
Definition at line 45 of file unit_texture.h.
id
const int16_t openage::UnitTexture::id
const attributes of the graphic
Definition at line 40 of file unit_texture.h.
mirroring_mode
const int16_t openage::UnitTexture::mirroring_mode
Definition at line 44 of file unit_texture.h.
safe_frame_count
unsigned int openage::UnitTexture::safe_frame_count private
the above frame count covers the entire graphic (with deltas) the actual number in the base texture may be different
Definition at line 98 of file unit_texture.h.
Referenced by initialise().
sound
const Sound* openage::UnitTexture::sound private
Definition at line 105 of file unit_texture.h.
Referenced by draw(), and initialise().
sound_id
const int16_t openage::UnitTexture::sound_id
Definition at line 41 of file unit_texture.h.
Referenced by initialise().
texture
const Texture* openage::UnitTexture::texture private
use a regular texture for drawing
Definition at line 92 of file unit_texture.h.
Referenced by draw(), initialise(), is_valid(), sample(), and size().
top_frame
unsigned int openage::UnitTexture::top_frame private
Definition at line 101 of file unit_texture.h.
Referenced by draw(), and initialise().
use_deltas
const bool openage::UnitTexture::use_deltas
use delta information
Definition at line 56 of file unit_texture.h.
Referenced by initialise().
use_up_angles
const bool openage::UnitTexture::use_up_angles
draw object with vertical orientation (arrows) adding an addtion degree of orientation
Definition at line 51 of file unit_texture.h.
Referenced by draw().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/unit_texture.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/unit_texture.cpp