openage: openage::ResourceBundle Class Reference
openage::ResourceBundle Class Reference
#include <resource.h>
Public Member Functions
ResourceBundle ()
ResourceBundle (const Resources &resources)
virtual ~ResourceBundle ()
ResourceBundle (const ResourceBundle &other)
ResourceBundle clone () const
bool operator> (const ResourceBundle &other) const
bool operator>= (const ResourceBundle &other) const
ResourceBundle & operator+= (const ResourceBundle &other)
ResourceBundle & operator-= (const ResourceBundle &other)
ResourceBundle & operator *= (const double a)
ResourceBundle & round ()
bool has (const ResourceBundle &amount) const
bool has (const ResourceBundle &amount1, const ResourceBundle &amount2) const
bool deduct (const ResourceBundle &amount)
void set (const ResourceBundle &amount)
void set_all (const double amount)
void limit (const ResourceBundle &limits)
double & operator[] (const game_resource res)
double & operator[] (const int id)
double get (const game_resource res) const
double get (const int id) const
double sum () const
int get_count () const
Private Member Functions
ResourceBundle (const int count)
void expand (const ResourceBundle &other)
void expand (const int count)
int min_count (const ResourceBundle &other)
Private Attributes
int count
double * value
Detailed Description
A set of amounts of game resources.
Can be also used to store other information about the resources.
Todo:
change amounts from doubles to integers
Definition at line 110 of file resource.h.
Constructor & Destructor Documentation
ResourceBundle() [1/4]
openage::ResourceBundle::ResourceBundle ()
Definition at line 15 of file resource.cpp.
     :
     ResourceBundle{4} {
 }
Referenced by clone().
ResourceBundle() [2/4]
openage::ResourceBundle::ResourceBundle (const Resources & resources)
Definition at line 20 of file resource.cpp.
     :
     ResourceBundle{static_cast<int>(resources.get_count())} {
 }
References openage::Resources::get_count().
~ResourceBundle()
openage::ResourceBundle::~ResourceBundle () virtual
Definition at line 41 of file resource.cpp.
{
     delete[] value;
 }
References value.
ResourceBundle() [3/4]
openage::ResourceBundle::ResourceBundle (const ResourceBundle & other)
Definition at line 31 of file resource.cpp.
     :
     ResourceBundle{resources.count} {
     this->set(resources);
 }
References count.
ResourceBundle() [4/4]
openage::ResourceBundle::ResourceBundle (const int count) private
Definition at line 25 of file resource.cpp.
     :
     count{count},
     value{new double[count] {0}} {
 }
References count.
Member Function Documentation
clone()
ResourceBundle openage::ResourceBundle::clone () const
Definition at line 37 of file resource.cpp.
{
     return ResourceBundle(*this);
 }
References ResourceBundle().
Referenced by openage::ResourceCost::get().
deduct()
bool openage::ResourceBundle::deduct (const ResourceBundle & amount)
If amount can't be deducted return false, else deduct the given amount and return true.
Definition at line 148 of file resource.cpp.
{
     if (this->has(amount)) {
         *this -= amount;
         return true;
     }
     return false;
 }
References has().
Referenced by openage::Player::deduct().
expand() [1/2]
void openage::ResourceBundle::expand (const ResourceBundle & other) private
Definition at line 45 of file resource.cpp.
{
     this->expand(other.count);
 }
References count.
Referenced by operator+=(), operator-=(), and set().
expand() [2/2]
void openage::ResourceBundle::expand (const int count) private
Definition at line 49 of file resource.cpp.
{
     if (this->count == count) {
         return;
     }
     // create new array with old values
     double *new_value = new double[count];
     for (int i = 0; i < this->count; i++) {
         new_value[i] = this->value[i];
     }
     // replace the private variables
     this->count = count;
     delete[] value;
     this->value = new_value;
 }
References count, and value.
get() [1/2]
double openage::ResourceBundle::get (const game_resource res) const inline
Definition at line 159 of file resource.h.
 { return value[static_cast<int>(res)]; }
References value.
Referenced by openage::Player::amount(), openage::Market::buy(), openage::Player::can_deduct(), openage::Player::can_receive(), has(), limit(), operator+=(), operator-=(), operator>(), operator>=(), round(), openage::Market::sell(), set(), and sum().
get() [2/2]
double openage::ResourceBundle::get (const int id) const inline
Definition at line 160 of file resource.h.
 { return value[id]; }
References value.
get_count()
int openage::ResourceBundle::get_count () const inline
The number of resources
Definition at line 170 of file resource.h.
 { return count; };
References count.
has() [1/2]
bool openage::ResourceBundle::has (const ResourceBundle & amount) const
Definition at line 124 of file resource.cpp.
{
     return *this >= amount;
 }
Referenced by openage::Player::can_deduct(), openage::Player::can_receive(), and deduct().
has() [2/2]
bool openage::ResourceBundle::has (const ResourceBundle & amount1, const ResourceBundle & amount2) const
Definition at line 128 of file resource.cpp.
{
     for (int i = 0; i < this->count; i++) {
         if (!(this->get(i) >= amount1.get(i) + amount2.get(i))) {
             return false;
         }
     }
     // check also resources that are not in both bundles
     for (int i = this->count; i < amount1.count; i++) {
         if (amount1.get(i) > 0) {
             return false;
         }
     }
     for (int i = this->count; i < amount2.count; i++) {
         if (amount2.get(i) > 0) {
             return false;
         }
     }
     return true;
 }
References count, and get().
limit()
void openage::ResourceBundle::limit (const ResourceBundle & limits)
Definition at line 169 of file resource.cpp.
{
     for (int i = 0; i < this->min_count(limits); i++) {
         if (this->get(i) > limits.get(i)) {
             (*this)[i] = limits.get(i);
         }
     }
 }
References get(), and min_count().
Referenced by openage::Player::on_resources_change().
min_count()
int openage::ResourceBundle::min_count (const ResourceBundle & other) private
Definition at line 185 of file resource.cpp.
{
     return this->count <= other.count ? this->count : other.count;
 }
References count.
Referenced by limit().
operator *=()
ResourceBundle & openage::ResourceBundle::operator *= (const double a)
Definition at line 110 of file resource.cpp.
{
     for (int i = 0; i < this->count; i++) {
         (*this)[i] *= a;
     }
     return *this;
 }
References count.
operator+=()
ResourceBundle & openage::ResourceBundle::operator+= (const ResourceBundle & other)
Definition at line 94 of file resource.cpp.
{
     this->expand(other);
     for (int i = 0; i < this->count; i++) {
         (*this)[i] += other.get(i);
     }
     return *this;
 }
References count, expand(), and get().
operator-=()
ResourceBundle & openage::ResourceBundle::operator-= (const ResourceBundle & other)
Definition at line 102 of file resource.cpp.
{
     this->expand(other);
     for (int i = 0; i < this->count; i++) {
         (*this)[i] -= other.get(i);
     }
     return *this;
 }
References count, expand(), and get().
operator>()
bool openage::ResourceBundle::operator> (const ResourceBundle & other) const
Definition at line 64 of file resource.cpp.
{
     for (int i = 0; i < this->count; i++) {
         if (!(this->get(i) > other.get(i))) {
             return false;
         }
     }
     // check also resources that are not in both bundles
     for (int i = this->count; i < other.count; i++) {
         if (other.get(i) > 0) {
             return false;
         }
     }
     return true;
 }
References count, and get().
operator>=()
bool openage::ResourceBundle::operator>= (const ResourceBundle & other) const
Definition at line 79 of file resource.cpp.
{
     for (int i = 0; i < this->count; i++) {
         if (!(this->get(i) >= other.get(i))) {
             return false;
         }
     }
     // check also resources that are not in both bundles
     for (int i = this->count; i < other.count; i++) {
         if (other.get(i) > 0) {
             return false;
         }
     }
     return true;
 }
References count, and get().
operator[]() [1/2]
double& openage::ResourceBundle::operator[] (const game_resource res) inline
Definition at line 154 of file resource.h.
 { return value[static_cast<int>(res)]; }
References value.
operator[]() [2/2]
double& openage::ResourceBundle::operator[] (const int id) inline
Definition at line 155 of file resource.h.
 { return value[id]; }
References value.
round()
ResourceBundle & openage::ResourceBundle::round ()
Round each value to the nearest integer. Returns itself.
Definition at line 117 of file resource.cpp.
{
     for (int i = 0; i < this->count; i++) {
         (*this)[i] = std::round(this->get(i));
     }
     return *this;
 }
References count, and get().
set()
void openage::ResourceBundle::set (const ResourceBundle & amount)
Definition at line 156 of file resource.cpp.
{
     this->expand(amount);
     for (int i = 0; i < this->count; i++) {
         (*this)[i] = amount.get(i);
     }
 }
References count, expand(), and get().
Referenced by openage::ResourceCost::set().
set_all()
void openage::ResourceBundle::set_all (const double amount)
Definition at line 163 of file resource.cpp.
{
     for (int i = 0; i < this->count; i++) {
         (*this)[i] = amount;
     }
 }
References count.
sum()
double openage::ResourceBundle::sum () const
Returns the sum of all the resources.
Definition at line 177 of file resource.cpp.
{
     double sum = 0;
     for (int i = 0; i < this->count; i++) {
         sum += this->get(i);
     }
     return sum;
 }
References count, and get().
Referenced by openage::Player::active_unit_added(), openage::Player::active_unit_removed(), openage::Player::killed_unit(), and openage::Score::update_resources().
Member Data Documentation
count
int openage::ResourceBundle::count private
The number of resources
Definition at line 183 of file resource.h.
Referenced by expand(), get_count(), has(), min_count(), operator *=(), operator+=(), operator-=(), operator>(), operator>=(), ResourceBundle(), round(), set(), set_all(), and sum().
value
double* openage::ResourceBundle::value private
Definition at line 185 of file resource.h.
Referenced by openage.convert.dataformat.members.ContinueReadMemberResult::__str__(), expand(), get(), operator[](), and ~ResourceBundle().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gamestate/resource.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gamestate/resource.cpp