openage: openage::event::EventStore Class Reference
openage::event::EventStore Class Reference
#include <eventstore.h>
Public Types
using heap_t = datastructure::PairingHeap< std::shared_ptr< Event >, util::SharedPtrLess< Event > >
using elemmap_t = std::unordered_map< std::shared_ptr< Event >, heap_t::element_t >
Public Member Functions
void push (const std::shared_ptr< Event > &event)
std::shared_ptr< Event > pop ()
const std::shared_ptr< Event > & top ()
bool erase (const std::shared_ptr< Event > &event)
void update (const std::shared_ptr< Event > &event)
bool contains (const std::shared_ptr< Event > &event) const
void clear ()
size_t size () const
bool empty () const
std::vector< std::shared_ptr< Event > > get_sorted_events () const
Public Attributes
heap_t heap
elemmap_t events
Detailed Description
Sorted storage for events. Implemented through a heap that automatically provides the newest event.
Definition at line 20 of file eventstore.h.
Member Typedef Documentation
elemmap_t
using openage::event::EventStore::elemmap_t = std::unordered_map<std::shared_ptr<Event>, heap_t::element_t>
Definition at line 27 of file eventstore.h.
heap_t
using openage::event::EventStore::heap_t = datastructure::PairingHeap<std::shared_ptr<Event>, util::SharedPtrLess<Event> >
Definition at line 26 of file eventstore.h.
Member Function Documentation
clear()
void openage::event::EventStore::clear ()
Definition at line 83 of file eventstore.cpp.
{
     this->heap.clear();
     this->events.clear();
 }
References openage::datastructure::PairingHeap< T, compare, heapnode_t >::clear(), events, and heap.
contains()
bool openage::event::EventStore::contains (const std::shared_ptr< Event > & event) const
Definition at line 78 of file eventstore.cpp.
{
     return (this->events.find(event) != std::end(this->events));
 }
References events.
Referenced by openage::event::EventQueue::enqueue_change().
empty()
bool openage::event::EventStore::empty () const
Definition at line 94 of file eventstore.cpp.
{
     return this->events.empty();
 }
References events.
erase()
bool openage::event::EventStore::erase (const std::shared_ptr< Event > & event)
Definition at line 54 of file eventstore.cpp.
{
     bool erased = false;
     auto it = this->events.find(event);
     if (it != std::end(this->events)) {
         this->heap.unlink_node(it->second);
         this->events.erase(it);
         erased = true;
     }
     return erased;
 }
References events, heap, and openage::datastructure::PairingHeap< T, compare, heapnode_t >::unlink_node().
Referenced by openage::event::EventQueue::remove().
get_sorted_events()
std::vector< std::shared_ptr< Event > > openage::event::EventStore::get_sorted_events () const
Helper function that should not be called 'in production'. It returns the events in the store sorted by time. Use the pop() method instead (but with that you can't iterate).
Definition at line 99 of file eventstore.cpp.
{
     std::vector<std::shared_ptr<Event>> ret;
     ret.reserve(this->events.size());
     std::transform(
         std::begin(this->events),
         std::end(this->events),
         std::back_inserter(ret),
         [](const auto &elem) {
             return elem.first;
         }
     );
     std::sort(
         std::begin(ret),
         std::end(ret),
         [](const auto &a, const auto &b) {
             return *a < *b;
         }
     );
     return ret;
 }
References events.
Referenced by openage::event::Loop::execute_events().
pop()
std::shared_ptr< Event > openage::event::EventStore::pop ()
Definition at line 28 of file eventstore.cpp.
{
     ENSURE(this->heap.size() == this->events.size(),
            "heap and event set are inconsistent 0");
     size_t heap_s = this->heap.size();
     size_t evnt_s = this->events.size();
     std::shared_ptr<Event> event = this->heap.pop();
     this->events.erase(event);
     if (this->heap.size() != this->events.size()) {
         throw Error{ERR << "inconsistent: prev_heap=" << heap_s
                         << " prev_map=" << evnt_s};
     }
         //ENSURE(this->heap.size() == this->events.size(),
         //   "heap and event set are inconsistent 1");
     return event;
 }
References ENSURE, ERR, events, heap, openage::datastructure::PairingHeap< T, compare, heapnode_t >::pop(), and openage::datastructure::PairingHeap< T, compare, heapnode_t >::size().
Referenced by openage::event::EventQueue::take_event().
push()
void openage::event::EventStore::push (const std::shared_ptr< Event > & event)
Definition at line 15 of file eventstore.cpp.
{
     if (unlikely(event == nullptr)) {
         throw Error{ERR << "inserting nullptr event to queue"};
     }
     heap_t::element_t order = this->heap.push(event);
     this->events.emplace(event, order);
     ENSURE(this->heap.size() == this->events.size(),
            "heap and event set are inconsistent");
 }
References ENSURE, ERR, events, heap, openage::datastructure::PairingHeap< T, compare, heapnode_t >::push(), openage::datastructure::PairingHeap< T, compare, heapnode_t >::size(), and unlikely.
Referenced by openage::event::EventQueue::create_event(), openage::event::EventQueue::enqueue_change(), and openage::event::EventQueue::reenqueue().
size()
size_t openage::event::EventStore::size () const
Definition at line 89 of file eventstore.cpp.
{
     return this->events.size();
 }
References events.
Referenced by openage::event::Loop::execute_events(), and openage::event::EventQueue::take_event().
top()
const std::shared_ptr< Event > & openage::event::EventStore::top ()
Definition at line 49 of file eventstore.cpp.
{
     return this->heap.top();
 }
References heap, and openage::datastructure::PairingHeap< T, compare, heapnode_t >::top().
Referenced by openage::event::EventQueue::take_event().
update()
void openage::event::EventStore::update (const std::shared_ptr< Event > & event)
Definition at line 67 of file eventstore.cpp.
{
     auto it = this->events.find(event);
     if (unlikely(it != std::end(this->events))) {
         this->heap.update(it->second);
     }
     else {
         throw Error{ERR << "event to update not found in store"};
     }
 }
References ERR, events, heap, unlikely, and openage::datastructure::PairingHeap< T, compare, heapnode_t >::update().
Referenced by openage::event::EventQueue::enqueue_change().
Member Data Documentation
events
elemmap_t openage::event::EventStore::events
Definition at line 47 of file eventstore.h.
Referenced by clear(), contains(), empty(), erase(), get_sorted_events(), pop(), push(), size(), and update().
heap
heap_t openage::event::EventStore::heap
Definition at line 46 of file eventstore.h.
Referenced by clear(), erase(), pop(), push(), top(), and update().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/event/eventstore.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/event/eventstore.cpp