openage: openage::renderer::Font Class Reference
openage::renderer::Font Class Reference
#include <font.h>
Public Member Functions
Font (const font_description &description)
Create a font instance from the description.
Font (FontManager *font_manager, const font_description &description)
This constructor is used by the font manager to create a new font instance from the description.
virtual ~Font ()
float get_ascender () const
Get the typographic ascender of font.
float get_descender () const
Get the typographic descender of font.
float get_line_height () const
Get the line spacing of font.
float get_horizontal_kerning (codepoint_t left_glyph, codepoint_t right_glyph) const
Get the kerning adjustment between two glyphs.
float get_advance_width (const std::string &text) const
Get the advance width of a particular string.
std::vector< codepoint_t > get_glyphs (const std::string &text) const
Get the list of glyphs for a particular string.
std::unique_ptr< unsigned char[]> load_glyph (codepoint_t codepoint, Glyph &glyph) const
Load a particular glyph's info and retrieves the glyph's bitmap data.
Public Attributes
font_description description
The description of the font.
Private Member Functions
void initialize (FT_Library ft_library)
Initializes the font's face and creates a harfbuzz font instance.
Private Attributes
std::unique_ptr< FreeTypeLibrary > freetype_library
hb_font_t * hb_font
Detailed Description
Definition at line 95 of file font.h.
Constructor & Destructor Documentation
Font() [1/2]
openage::renderer::Font::Font (const font_description & description)
Create a font instance from the description.
Parameters
description the font description.
Definition at line 92 of file font.cpp.
     :
     description{description},
     freetype_library{nullptr},
     hb_font{nullptr} {
     this->freetype_library = std::make_unique<FreeTypeLibrary>();
     this->initialize(this->freetype_library->ft_library);
 }
References description.
Font() [2/2]
openage::renderer::Font::Font (FontManager * font_manager, const font_description & description)
This constructor is used by the font manager to create a new font instance from the description.
Parameters
font_manager The font manager.
description the font description.
Definition at line 102 of file font.cpp.
     :
     description{description},
     freetype_library{nullptr},
     hb_font{nullptr} {
     this->initialize(font_manager->get_ft_library());
 }
References description.
~Font()
openage::renderer::Font::~Font () virtual
Definition at line 127 of file font.cpp.
             {
     // Destroy HarfBuzz font
     // HarfBuzz will take care of destroying the FT_Face instance
     if (this->hb_font) {
         hb_font_destroy(this->hb_font);
         this->hb_font = nullptr;
     }
 }
References hb_font.
Member Function Documentation
get_advance_width()
float openage::renderer::Font::get_advance_width (const std::string & text) const
Get the advance width of a particular string.
Parameters
text The string for which the width is to be determined.
Returns
The advance width of the specified string.
Definition at line 162 of file font.cpp.
{
     hb_buffer_t *buffer = hb_buffer_create();
     hb_buffer_set_direction(buffer, get_hb_font_direction(this->description));
     hb_buffer_set_script(buffer, get_hb_font_script(this->description));
     hb_buffer_set_language(buffer, get_hb_font_language(this->description));
     hb_buffer_add_utf8(buffer, text.c_str(), text.length(), 0, text.length());
     hb_shape(this->hb_font, buffer, nullptr, 0);
     float advance_width = 0.0f;
     unsigned int glyph_count = 0;
     hb_glyph_info_t *glyph_info = hb_buffer_get_glyph_infos(buffer, &glyph_count);
     hb_glyph_position_t *glyph_pos = hb_buffer_get_glyph_positions(buffer, nullptr);
     for (unsigned int i = 0; i < glyph_count; i++) {
         advance_width += static_cast<float>(glyph_pos[i].x_advance)/FREETYPE_UNIT;
         if (i > 0) {
             codepoint_t glyph = glyph_info[i].codepoint;
             codepoint_t previous_glyph = glyph_info[i - 1].codepoint;
             advance_width += this->get_horizontal_kerning(previous_glyph, glyph);
         }
     }
     hb_buffer_destroy(buffer);
     return advance_width;
 }
References description, openage::renderer::FREETYPE_UNIT, openage::renderer::get_hb_font_direction(), openage::renderer::get_hb_font_language(), openage::renderer::get_hb_font_script(), get_horizontal_kerning(), and hb_font.
get_ascender()
float openage::renderer::Font::get_ascender () const
Get the typographic ascender of font.
Returns
The ascender of font.
Definition at line 136 of file font.cpp.
{
     FT_Face ft_face = hb_ft_font_get_face(this->hb_font);
     return static_cast<float>(ft_face->size->metrics.ascender)/FREETYPE_UNIT;
 }
References openage::renderer::FREETYPE_UNIT, and hb_font.
Referenced by openage::console::draw::to_opengl().
get_descender()
float openage::renderer::Font::get_descender () const
Get the typographic descender of font.
Returns
The descender of font.
Definition at line 141 of file font.cpp.
{
     FT_Face ft_face = hb_ft_font_get_face(this->hb_font);
     return static_cast<float>(ft_face->size->metrics.descender)/FREETYPE_UNIT;
 }
References openage::renderer::FREETYPE_UNIT, and hb_font.
get_glyphs()
std::vector< codepoint_t > openage::renderer::Font::get_glyphs (const std::string & text) const
Get the list of glyphs for a particular string.
Parameters
text the string for which the glyphs are to be retrieved.
Returns
The list of the glyphs.
Definition at line 190 of file font.cpp.
{
     hb_buffer_t *buffer = hb_buffer_create();
     hb_buffer_set_direction(buffer, get_hb_font_direction(this->description));
     hb_buffer_set_script(buffer, get_hb_font_script(this->description));
     hb_buffer_set_language(buffer, get_hb_font_language(this->description));
     hb_buffer_add_utf8(buffer, text.c_str(), text.length(), 0, text.length());
     hb_shape(this->hb_font, buffer, nullptr, 0);
     unsigned int glyph_count = 0;
     hb_glyph_info_t *glyph_info = hb_buffer_get_glyph_infos(buffer, &glyph_count);
     std::vector<codepoint_t> glyphs;
     glyphs.resize(glyph_count);
     for (unsigned int i = 0; i < glyph_count; i++) {
         glyphs[i] = glyph_info[i].codepoint;
     }
     hb_buffer_destroy(buffer);
     return glyphs;
 }
References description, openage::renderer::get_hb_font_direction(), openage::renderer::get_hb_font_language(), openage::renderer::get_hb_font_script(), and hb_font.
get_horizontal_kerning()
float openage::renderer::Font::get_horizontal_kerning (codepoint_t left_glyph, codepoint_t right_glyph) const
Get the kerning adjustment between two glyphs.
Parameters
left_glyph The first glyph.
right_glyph The next glyph.
Returns
The kerning adjustment.
Definition at line 157 of file font.cpp.
{
     int kerning = hb_font_get_glyph_h_kerning(this->hb_font, left_glyph, right_glyph);
     return static_cast<float>(kerning)/FREETYPE_UNIT;
 }
References openage::renderer::FREETYPE_UNIT, and hb_font.
Referenced by get_advance_width().
get_line_height()
float openage::renderer::Font::get_line_height () const
Get the line spacing of font.
Returns
The font's line height.
Definition at line 146 of file font.cpp.
{
     FT_Face ft_face = hb_ft_font_get_face(this->hb_font);
     if (FT_IS_SCALABLE(ft_face)) {
         float units_to_pixels_conversion = static_cast<float>(ft_face->size->metrics.y_ppem)/ft_face->units_per_EM;
         return (ft_face->bbox.yMax - ft_face->bbox.yMin) * units_to_pixels_conversion;
     }
     return static_cast<float>(ft_face->size->metrics.height)/FREETYPE_UNIT;
 }
References openage::renderer::FREETYPE_UNIT, and hb_font.
initialize()
void openage::renderer::Font::initialize (FT_Library ft_library) private
Initializes the font's face and creates a harfbuzz font instance.
Parameters
ft_library The freetype library that should be used to load the font's face.
Definition at line 111 of file font.cpp.
{
     FT_Face ft_face;
     if (unlikely(FT_New_Face(ft_library, this->description.font_file.c_str(), 0, &ft_face))) {
         throw Error(MSG(err) << "Failed to create font from " << this->description.font_file);
     }
     if (unlikely(FT_Set_Char_Size(ft_face, 0, this->description.size * FREETYPE_UNIT, 72, 72))) {
         throw Error(MSG(err) << "Failed to set font face size to " << this->description.size);
     }
     hb_ft_font_create_referenced(ft_face);
     // lambda with static_cast to help gcc understand this is ok
     this->hb_font = hb_ft_font_create(ft_face, [] (void *user_data) -> void {
         FT_Done_Face(static_cast<FT_FaceRec_ *>(user_data));
     });
 }
References description, openage::log::err(), openage::renderer::font_description::font_file, openage::renderer::FREETYPE_UNIT, hb_font, MSG, openage::renderer::font_description::size, and unlikely.
load_glyph()
std::unique_ptr< unsigned char[]> openage::renderer::Font::load_glyph (codepoint_t codepoint, Glyph & glyph) const
Load a particular glyph's info and retrieves the glyph's bitmap data.
Parameters
codepoint The glyph.
glyph The glyph's info is loaded in to this object.
Returns
The glyph's bitmap data.
Definition at line 212 of file font.cpp.
{
     FT_Face ft_face = hb_ft_font_get_face(this->hb_font);
     if (unlikely(FT_Load_Glyph(ft_face, codepoint, FT_LOAD_DEFAULT | FT_LOAD_NO_HINTING | FT_LOAD_RENDER))) {
         return nullptr;
     }
     glyph.codepoint = codepoint;
     glyph.x_offset = ft_face->glyph->bitmap_left;
     glyph.y_offset = ft_face->glyph->bitmap_top;
     glyph.width = ft_face->glyph->bitmap.width;
     glyph.height = ft_face->glyph->bitmap.rows;
     glyph.x_advance = static_cast<float>(ft_face->glyph->advance.x)/FREETYPE_UNIT;
     glyph.y_advance = static_cast<float>(ft_face->glyph->advance.y)/FREETYPE_UNIT;
     auto glyph_data = std::make_unique<unsigned char[]>(glyph.width * glyph.height);
     for (size_t i = 0; i < glyph.height; i++) {
         memcpy(
             &glyph_data[i * glyph.width],
             ft_face->glyph->bitmap.buffer + (glyph.height - i - 1) * glyph.width,
             glyph.width * sizeof(unsigned char)
         );
     }
     return glyph_data;
 }
References openage::renderer::Glyph::codepoint, openage::renderer::FREETYPE_UNIT, hb_font, openage::renderer::Glyph::height, unlikely, openage::renderer::Glyph::width, openage::renderer::Glyph::x_advance, openage::renderer::Glyph::x_offset, openage::renderer::Glyph::y_advance, and openage::renderer::Glyph::y_offset.
Member Data Documentation
description
font_description openage::renderer::Font::description
The description of the font.
See also
font_description
Definition at line 184 of file font.h.
Referenced by openage.convert.game_versions.GameVersion::__str__(), Font(), get_advance_width(), get_glyphs(), and initialize().
freetype_library
std::unique_ptr<FreeTypeLibrary> openage::renderer::Font::freetype_library private
Definition at line 188 of file font.h.
hb_font
hb_font_t* openage::renderer::Font::hb_font private
Definition at line 191 of file font.h.
Referenced by get_advance_width(), get_ascender(), get_descender(), get_glyphs(), get_horizontal_kerning(), get_line_height(), initialize(), load_glyph(), and ~Font().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/font/font.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/font/font.cpp