openage: openage::TerrainObject Class Reference
openage::TerrainObject Class Reference abstract
Base class for map location types which include square tile aligned positions and radial positions This enables two inheriting classes SquareObject and RadialObject to specify different areas of the map.
#include <terrain_object.h>
Public Member Functions
TerrainObject (Unit &u)
TerrainObject (const TerrainObject &)=delete
TerrainObject (TerrainObject &&)=delete
virtual ~TerrainObject ()
bool is_floating () const
is the object a floating outline – it is only an indicator of where a building will be built, but not yet started building and does not affect any collisions
bool is_placed () const
returns true if this object has been placed.
bool check_collisions () const
should this object be tested for collisions, which decides whether another object is allowed to overlap the location of this object.
void draw_outline (const coord::CoordManager &coord) const
draws outline of this terrain space in current position
bool place (object_state init_state)
changes the placement state of this object keeping the existing position.
bool place (const std::shared_ptr< Terrain > &t, coord::phys3 &pos, object_state init_state)
binds the TerrainObject to a certain TerrainChunk.
bool move (coord::phys3 &pos)
moves the object – returns false if object cannot be moved here
void remove ()
remove this TerrainObject from the terrain chunks.
void set_ground (int id, int additional=0)
sets all the ground below the object to a terrain id.
template<class T , typename ... Arg>
TerrainObject * make_annex (Arg ... args)
appends new annex location for this object
const TerrainObject * get_parent () const
Returns the parent terrain object, if null the object has no parent which is the case for most objects.
std::vector< TerrainObject * > get_children () const
Returns a list of child objects, this is the inverse of the get_parent() function.
std::shared_ptr< Terrain > get_terrain () const
bool operator< (const TerrainObject &other)
comparison for TerrainObjects.
virtual tile_range get_range (const coord::phys3 &pos, const Terrain &terrain) const =0
returns the range of tiles covered if the object was in the given pos
virtual coord::phys_t from_edge (const coord::phys3 &point) const =0
how far is a point from the edge of this object
virtual coord::phys3 on_edge (const coord::phys3 &angle, coord::phys_t extra=0) const =0
get a position on the edge of this object
virtual bool contains (const coord::phys3 &other) const =0
does this space contain a given point
virtual bool intersects (const TerrainObject &other, const coord::phys3 &position) const =0
would this intersect with another object if it were positioned at the given point
virtual coord::phys_t min_axis () const =0
the shortest line that can be placed across the objects center
Public Attributes
tile_range pos
the range of tiles which are covered by this object
Unit & unit
std::function< bool(const coord::phys3 &)> passable
decide which terrains this object can be on this function should be true if given a valid position for the object
std::function< void(const Engine &e)> draw
specifies content to be drawn
Protected Member Functions
void place_unchecked (const std::shared_ptr< Terrain > &t, coord::phys3 &position)
placement function which does not check passibility used only when passibilty is already checked otherwise the place function should be used this does not modify the units placement state
Protected Attributes
object_state state
std::weak_ptr< Terrain > terrain
int occupied_chunk_count
TerrainChunk * occupied_chunk [4]
TerrainObject * parent
annexes and grouped units
std::vector< std::unique_ptr< TerrainObject > > children
std::shared_ptr< Texture > outline_texture
texture for drawing outline
Detailed Description
Base class for map location types which include square tile aligned positions and radial positions This enables two inheriting classes SquareObject and RadialObject to specify different areas of the map.
All TerrainObjects are owned by a Unit, to construct TerrainObjects, use the make_location function on any Unit
This class allows intersection testing between two TerrainObjects to cover all cases of intersection (water, land or flying objects) the units lambda function is used which takes a tile and returns a bool value of whether that tile can be passed by this
The name of this class is likely to change to TerrainBase or TerrainSpace
Definition at line 75 of file terrain_object.h.
Constructor & Destructor Documentation
TerrainObject() [1/3]
openage::TerrainObject::TerrainObject (Unit & u)
Definition at line 22 of file terrain_object.cpp.
     :
     unit(u),
     passable{[](const coord::phys3 &) -> bool {return true;}},
     draw{[](const Engine &/*e*/) {}},
     state{object_state::removed},
     occupied_chunk_count{0},
     parent{nullptr} {
 }
TerrainObject() [2/3]
openage::TerrainObject::TerrainObject (const TerrainObject &) delete
TerrainObject() [3/3]
openage::TerrainObject::TerrainObject (TerrainObject &&) delete
~TerrainObject()
openage::TerrainObject::~TerrainObject () virtual
Definition at line 32 of file terrain_object.cpp.
{
     // remove all connections from terrain
     this->unit.log(MSG(dbg) << "Cleanup terrain object");
     this->remove();
 }
References openage::log::dbg(), openage::log::LogSource::log(), MSG, remove(), and unit.
Member Function Documentation
check_collisions()
bool openage::TerrainObject::check_collisions () const
should this object be tested for collisions, which decides whether another object is allowed to overlap the location of this object.
arrows and decaying objects will return false
Definition at line 58 of file terrain_object.cpp.
{
     // if object has a parent it must be placed
     if (this->parent && !this->parent->is_placed()) {
         return false;
     }
     return this->state == object_state::placed;
 }
References is_placed(), parent, openage::placed, and state.
Referenced by openage::ObjectProducer::place().
contains()
virtual bool openage::TerrainObject::contains (const coord::phys3 & other) const pure virtual
does this space contain a given point
Implemented in openage::RadialObject, and openage::SquareObject.
draw_outline()
void openage::TerrainObject::draw_outline (const coord::CoordManager & coord) const
draws outline of this terrain space in current position
Definition at line 67 of file terrain_object.cpp.
{
     this->outline_texture->draw(coord, this->pos.draw);
 }
References openage::tile_range::draw, outline_texture, and pos.
Referenced by openage::BuildingProducer::make_annex(), and openage::ObjectProducer::place().
from_edge()
virtual coord::phys_t openage::TerrainObject::from_edge (const coord::phys3 & point) const pure virtual
how far is a point from the edge of this object
Implemented in openage::RadialObject, and openage::SquareObject.
Referenced by openage::path::to_object().
get_children()
std::vector< TerrainObject * > openage::TerrainObject::get_children () const
Returns a list of child objects, this is the inverse of the get_parent() function.
Todo:
this does not perform optimally and is likely to change
Todo:
a better performing way of doing this for example accept a lambda to use for each element or maintain a duplicate class field for raw pointers
Definition at line 216 of file terrain_object.cpp.
{
     std::vector<TerrainObject *> result;
     for (auto &obj: this->children) {
         result.push_back(obj.get());
     }
     return result;
 }
References children, and openage.testing.testing::result().
get_parent()
const TerrainObject * openage::TerrainObject::get_parent () const
Returns the parent terrain object, if null the object has no parent which is the case for most objects.
objects with a parent are owned by that object and to be placed on the map the parent must also be placed
Definition at line 212 of file terrain_object.cpp.
{
     return this->parent;
 }
References parent.
Referenced by openage::BuildingProducer::make_annex().
get_range()
virtual tile_range openage::TerrainObject::get_range (const coord::phys3 & pos, const Terrain & terrain) const pure virtual
returns the range of tiles covered if the object was in the given pos
Parameters
pos the position to find a range for
Implemented in openage::RadialObject, and openage::SquareObject.
Referenced by openage::ObjectProducer::place(), and place_unchecked().
get_terrain()
std::shared_ptr<Terrain> openage::TerrainObject::get_terrain () const inline
Definition at line 201 of file terrain_object.h.
{
         return terrain.lock();
     }
References terrain.
Referenced by openage::find_in_radius(), openage::find_near(), move(), place(), openage::UnitType::place_beside(), place_unchecked(), remove(), and set_ground().
intersects()
virtual bool openage::TerrainObject::intersects (const TerrainObject & other, const coord::phys3 & position) const pure virtual
would this intersect with another object if it were positioned at the given point
Implemented in openage::RadialObject, and openage::SquareObject.
Referenced by openage::ObjectProducer::place().
is_floating()
bool openage::TerrainObject::is_floating () const
is the object a floating outline – it is only an indicator of where a building will be built, but not yet started building and does not affect any collisions
Definition at line 38 of file terrain_object.cpp.
{
     // if parent is floating then all children also are
     if (this->parent && this->parent->is_floating()) {
         return true;
     }
     return this->state == object_state::floating;
 }
References openage::floating, is_floating(), parent, and state.
Referenced by is_floating().
is_placed()
bool openage::TerrainObject::is_placed () const
returns true if this object has been placed.
this indicates that the object has a position and exists on the map, floating buildings are not considered placed as they are only an indicator for where something can begin construction
Definition at line 47 of file terrain_object.cpp.
{
     // if object has a parent it must be placed
     if (this->parent && !this->parent->is_placed()) {
         return false;
     }
     return this->state == object_state::placed ||
            this->state == object_state::placed_no_collision;
 }
References is_placed(), parent, openage::placed, openage::placed_no_collision, and state.
Referenced by check_collisions(), is_placed(), and set_ground().
make_annex()
template<class T , typename ... Arg> TerrainObject* openage::TerrainObject::make_annex (Arg ... args) inline
appends new annex location for this object
this does not replace any existing annex
Definition at line 172 of file terrain_object.h.
{
         this->children.emplace_back(std::unique_ptr<T>(new T(this->unit, args ...)));
         auto &annex_ptr = this->children.back();
         annex_ptr->parent = this;
         return annex_ptr.get();
     }
References children.
min_axis()
virtual coord::phys_t openage::TerrainObject::min_axis () const pure virtual
the shortest line that can be placed across the objects center
Implemented in openage::RadialObject, and openage::SquareObject.
Referenced by openage::Terrain::obj_at_point(), and openage::path::to_object().
move()
bool openage::TerrainObject::move (coord::phys3 & pos)
moves the object – returns false if object cannot be moved here
Definition at line 139 of file terrain_object.cpp.
{
     if (this->state == object_state::removed) {
         return false;
     }
     auto old_state = this->state;
     // \todo should do outside of this function
     bool can_move = this->passable(position);
     if (can_move) {
         this->remove();
         this->place_unchecked(this->get_terrain(), position);
         this->state = old_state;
     }
     return can_move;
 }
References get_terrain(), passable, place_unchecked(), remove(), openage::removed, and state.
on_edge()
virtual coord::phys3 openage::TerrainObject::on_edge (const coord::phys3 & angle, coord::phys_t extra = 0) const pure virtual
get a position on the edge of this object
Implemented in openage::RadialObject, and openage::SquareObject.
operator<()
bool openage::TerrainObject::operator< (const TerrainObject & other)
comparison for TerrainObjects.
sorting for vertical placement. by using this order algorithm, the overlapping order is optimal so the objects can be drawn in correct order.
Definition at line 230 of file terrain_object.cpp.
{
     if (this == &other) {
         return false;
     }
     auto this_ne    = this->pos.draw.ne;
     auto this_se    = this->pos.draw.se;
     auto other_ne   = other.pos.draw.ne;
     auto other_se   = other.pos.draw.se;
     auto this_ypos  = this_ne  - this_se;
     auto other_ypos = other_ne - other_se;
     if (this_ypos < other_ypos) {
         return false;
     }
     else if (this_ypos == other_ypos) {
         if (this_ne > other_ne) {
             return false;
         }
         else if (this_ne == other_ne) {
             return this_se > other_se;
         }
     }
     return true;
 }
References openage::tile_range::draw, and pos.
place() [1/2]
bool openage::TerrainObject::place (object_state init_state)
changes the placement state of this object keeping the existing position.
this is useful for upgrading a floating building to a placed state
Definition at line 71 of file terrain_object.cpp.
{
     if (this->state == object_state::removed) {
         throw Error(MSG(err) << "Building cannot change state with no position");
     }
     // remove any other floating objects
     // which intersect with the new placement
     // if non-floating objects are on the foundation
     // then this placement will fail
     for (coord::tile temp_pos : tile_list(this->pos)) {
         std::vector<TerrainObject *> to_remove;
         TerrainChunk *chunk = this->get_terrain()->get_chunk(temp_pos);
         if (chunk == nullptr) {
             continue;
         }
         for (auto obj : chunk->get_data(temp_pos)->obj) {
             // ignore self and annexes of self
             if (obj != this &&
                 obj->get_parent() != this) {
                 if (obj->is_floating()) {
                     // floating objects get removed
                     to_remove.push_back(obj);
                 }
                 else if (obj->check_collisions()) {
                     // solid objects obstruct placement
                     return false;
                 }
             }
         }
         // all obstructing objects get deleted
         for (auto remove_obj : to_remove) {
             remove_obj->unit.location = nullptr;
         }
     }
     // set new state
     this->state = init_state;
     return true;
 }
References openage::log::err(), openage::TerrainChunk::get_data(), get_terrain(), MSG, openage::TileContent::obj, pos, openage::removed, state, and openage::tile_list().
Referenced by openage::BuildingProducer::make_annex().
place() [2/2]
bool openage::TerrainObject::place (const std::shared_ptr< Terrain > & t, coord::phys3 & pos, object_state init_state)
binds the TerrainObject to a certain TerrainChunk.
Parameters
terrain the terrain where the object will be placed onto.
pos (tile) position of the (nw,sw) corner
init_state should be floating, placed or placed_no_collision
Returns
true when the object was placed, false when it did not fit at pos.
Definition at line 118 of file terrain_object.cpp.
{
     if (this->state != object_state::removed) {
         throw Error(MSG(err) << "This object has already been placed.");
     }
     else if (init_state == object_state::removed) {
         throw Error(MSG(err) << "Cannot place an object with removed state.");
     }
     // use passiblity test
     if (not this->passable(position)) {
         return false;
     }
     // place on terrain
     this->place_unchecked(t, position);
     // set state
     this->state = init_state;
     return true;
 }
References openage::log::err(), MSG, passable, place_unchecked(), openage::removed, and state.
place_unchecked()
void openage::TerrainObject::place_unchecked (const std::shared_ptr< Terrain > & t, coord::phys3 & position) protected
placement function which does not check passibility used only when passibilty is already checked otherwise the place function should be used this does not modify the units placement state
Definition at line 258 of file terrain_object.cpp.
{
     // storing the position:
     this->pos = this->get_range(position, *t);
     this->terrain = t;
     this->occupied_chunk_count = 0;
     bool chunk_known = false;
     // set pointers to this object on each terrain tile
     // where the building will stand and block the ground
     for (coord::tile temp_pos : tile_list(this->pos)) {
         TerrainChunk *chunk = this->get_terrain()->get_chunk(temp_pos);
         if (chunk == nullptr) {
             continue;
         }
         for (int c = 0; c < this->occupied_chunk_count; c++) {
             if (this->occupied_chunk[c] == chunk) {
                 chunk_known = true;
             }
         }
         if (not chunk_known) {
             this->occupied_chunk[this->occupied_chunk_count] = chunk;
             this->occupied_chunk_count += 1;
         } else {
             chunk_known = false;
         }
         chunk->get_data(temp_pos.get_pos_on_chunk())->obj.push_back(this);
     }
 }
References openage::TerrainChunk::get_data(), get_range(), get_terrain(), occupied_chunk, occupied_chunk_count, pos, terrain, and openage::tile_list().
Referenced by move(), and place().
remove()
void openage::TerrainObject::remove ()
remove this TerrainObject from the terrain chunks.
Definition at line 155 of file terrain_object.cpp.
{
     // remove all children first
     for (auto &c : this->children) {
         c->remove();
     }
     this->children.clear();
     if (this->occupied_chunk_count == 0 ||
         this->state == object_state::removed) {
         return;
     }
     for (coord::tile temp_pos : tile_list(this->pos)) {
         TerrainChunk *chunk = this->get_terrain()->get_chunk(temp_pos);
         if (chunk == nullptr) {
             continue;
         }
         auto &v = chunk->get_data(temp_pos.get_pos_on_chunk())->obj;
         auto position_it = std::remove_if(
             std::begin(v),
             std::end(v),
             [this](TerrainObject *obj) {
                 return this == obj;
             });
         v.erase(position_it, std::end(v));
     }
     this->occupied_chunk_count = 0;
     this->state = object_state::removed;
 }
References children, openage::TerrainChunk::get_data(), get_terrain(), occupied_chunk_count, pos, openage::removed, state, and openage::tile_list().
Referenced by move(), openage::EditorMode::paint_entity_at(), and ~TerrainObject().
set_ground()
void openage::TerrainObject::set_ground (int id, int additional = 0)
sets all the ground below the object to a terrain id.
Parameters
id the terrain id to which the ground is set
additional amount of additional space arround the building
Definition at line 188 of file terrain_object.cpp.
{
     if (not this->is_placed()) {
         throw Error(MSG(err) << "Setting ground for object that is not placed yet.");
     }
     coord::tile temp_pos = this->pos.start;
     temp_pos.ne -= additional;
     temp_pos.se -= additional;
     while (temp_pos.ne < this->pos.end.ne + additional) {
         while (temp_pos.se < this->pos.end.se + additional) {
             TerrainChunk *chunk = this->get_terrain()->get_chunk(temp_pos);
             if (chunk == nullptr) {
                 continue;
             }
             chunk->get_data(temp_pos.get_pos_on_chunk())->terrain_id = id;
             temp_pos.se++;
         }
         temp_pos.se = this->pos.start.se - additional;
         temp_pos.ne++;
     }
 }
References openage::log::err(), openage::TerrainChunk::get_data(), openage::coord::tile::get_pos_on_chunk(), get_terrain(), is_placed(), MSG, pos, and openage::tile_range::start.
Member Data Documentation
children
std::vector<std::unique_ptr<TerrainObject> > openage::TerrainObject::children protected
Definition at line 256 of file terrain_object.h.
Referenced by get_children(), make_annex(), and remove().
draw
std::function<void(const Engine &e)> openage::TerrainObject::draw
specifies content to be drawn
Definition at line 124 of file terrain_object.h.
Referenced by openage::BuildingProducer::make_annex().
occupied_chunk
TerrainChunk* openage::TerrainObject::occupied_chunk[4] protected
Definition at line 250 of file terrain_object.h.
Referenced by place_unchecked().
occupied_chunk_count
int openage::TerrainObject::occupied_chunk_count protected
Definition at line 249 of file terrain_object.h.
Referenced by place_unchecked(), and remove().
outline_texture
std::shared_ptr<Texture> openage::TerrainObject::outline_texture protected
texture for drawing outline
Definition at line 261 of file terrain_object.h.
Referenced by draw_outline(), openage::RadialObject::RadialObject(), and openage::SquareObject::SquareObject().
parent
TerrainObject* openage::TerrainObject::parent protected
annexes and grouped units
Definition at line 255 of file terrain_object.h.
Referenced by check_collisions(), get_parent(), is_floating(), is_placed(), openage.util.fslike.path.Path::with_name(), and openage.util.fslike.path.Path::with_suffix().
passable
std::function<bool(const coord::phys3 &)> openage::TerrainObject::passable
decide which terrains this object can be on this function should be true if given a valid position for the object
Definition at line 119 of file terrain_object.h.
Referenced by move(), place(), and openage::path::to_object().
pos
tile_range openage::TerrainObject::pos
the range of tiles which are covered by this object
Definition at line 85 of file terrain_object.h.
Referenced by openage::SquareObject::contains(), openage::RadialObject::contains(), openage::Unit::draw(), draw_outline(), openage::find_in_radius(), openage::find_near(), openage::SquareObject::from_edge(), openage::RadialObject::from_edge(), openage::SquareObject::get_range(), openage::RadialObject::get_range(), openage.convert.binpack.Packer::height(), openage::SquareObject::intersects(), openage::SquareObject::on_edge(), openage::RadialObject::on_edge(), operator<(), place(), openage::UnitType::place_beside(), place_unchecked(), openage.util.filelike.stream.StreamSeekBuffer::read(), openage.util.filelike.fifo.FIFO::read(), openage.util.filelike.stream.StreamFragment::read(), openage.cabextract.cab.CABFolderStream::read_blocks(), remove(), openage.util.filelike.readonly.PosSavingReadOnlyFileLikeObject::seek(), set_ground(), openage.util.filelike.fifo.FIFO::tell(), openage.util.filelike.readonly.PosSavingReadOnlyFileLikeObject::tell(), openage.cabextract.lzxdstream.LZXDStream::tell(), openage.util.filelike.fifo.FIFO::tellw(), openage::path::to_object(), and openage.convert.binpack.Packer::width().
state
object_state openage::TerrainObject::state protected
Definition at line 246 of file terrain_object.h.
Referenced by check_collisions(), is_floating(), is_placed(), move(), place(), and remove().
terrain
std::weak_ptr<Terrain> openage::TerrainObject::terrain protected
Definition at line 248 of file terrain_object.h.
Referenced by get_terrain(), openage::SquareObject::intersects(), and place_unchecked().
unit
Unit& openage::TerrainObject::unit
Definition at line 93 of file terrain_object.h.
Referenced by openage::GatherAction::nearest_dropsite(), openage::BuildAction::on_completion(), openage::GatherAction::on_completion_in_range(), and ~TerrainObject().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/terrain/terrain_object.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/terrain/terrain_object.cpp