openage: openage::UnitReference Class Reference
openage::UnitReference Class Reference
#include <unit_container.h>
Public Member Functions
UnitReference ()
UnitReference (const UnitContainer *c, id_t id, Unit *)
bool is_valid () const
Unit * get () const
Private Attributes
std::shared_ptr< reference_data > data
Detailed Description
Reference to a single unit, which may have been removed from the game, check is_valid() before calling get()
Definition at line 46 of file unit_container.h.
Constructor & Destructor Documentation
UnitReference() [1/2]
openage::UnitReference::UnitReference ()
create an invalid reference
Definition at line 26 of file unit_container.cpp.
     :
     data{nullptr} {}
UnitReference() [2/2]
openage::UnitReference::UnitReference (const UnitContainer * c, id_t id, Unit * u)
create referece by unit id
Definition at line 31 of file unit_container.cpp.
     :
     data{std::make_shared<reference_data>(c, id, u)} {}
Member Function Documentation
get()
Unit * openage::UnitReference::get () const
Definition at line 42 of file unit_container.cpp.
{
     if (!this->is_valid()) {
         throw Error{MSG(err) << "Unit reference is no longer valid"};
     }
     return this->data->unit_ptr;
 }
References data, openage::log::err(), is_valid(), and MSG.
Referenced by openage::TargetAction::completed(), openage::ActionMode::place_selection(), openage::MoveAction::set_distance(), openage::MoveAction::set_path(), openage::MoveAction::update(), and openage::TargetAction::update_distance().
is_valid()
bool openage::UnitReference::is_valid () const
Definition at line 36 of file unit_container.cpp.
{
     return this->data &&
            this->data->container->valid_id(this->data->unit_id);
 }
References data.
Referenced by openage::TargetAction::completed(), openage::MoveAction::completed(), get(), openage::UnitSelection::kill_unit(), openage::ActionMode::place_selection(), openage::MoveAction::set_distance(), openage::MoveAction::set_path(), openage::TargetAction::set_target(), openage::MoveAction::update(), and openage::TargetAction::update_distance().
Member Data Documentation
data
std::shared_ptr<reference_data> openage::UnitReference::data private
The default copy constructor and assignment will just copy the shared pointer
Definition at line 68 of file unit_container.h.
Referenced by openage.convert.dataformat.content_snippet.ContentSnippet::__eq__(), openage.convert.dataformat.struct_snippet.StructSnippet::__hash__(), openage.convert.dataformat.content_snippet.ContentSnippet::__hash__(), openage.convert.dataformat.content_snippet.ContentSnippet::__repr__(), openage.convert.dataformat.data_definition.DataDefinition::__str__(), openage.convert.dataformat.content_snippet.ContentSnippet::__str__(), openage.convert.dataformat.data_formatter.DataFormatter::add_data(), openage.convert.dataformat.data_formatter.DataFormatter::export(), openage.convert.dataformat.data_definition.DataDefinition::generate_csv(), get(), openage.convert.dataformat.content_snippet.ContentSnippet::get_data(), openage.convert.texture.TextureImage::get_data(), openage.convert.texture.TextureImage::get_pil_image(), is_valid(), and openage.convert.peresource.PEResources::read_directory().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/unit_container.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/unit_container.cpp