openage: openage::PatrolAbility Class Reference
openage::PatrolAbility Class Reference
initiates a patrol action when given a valid target
#include <ability.h>
Public Member Functions
PatrolAbility (const Sound *s=nullptr)
ability_type type () override
bool can_invoke (Unit &to_modify, const Command &cmd) override
true if the paramaters allow an action to be performed
void invoke (Unit &to_modify, const Command &cmd, bool play_sound=false) override
applies command to a given unit
Public Member Functions inherited from openage::UnitAbility
virtual ~UnitAbility ()
bool has_hitpoints (Unit &target)
some common functions
bool is_damaged (Unit &target)
bool has_resource (Unit &target)
bool is_same_player (Unit &to_modify, Unit &target)
bool is_ally (Unit &to_modify, Unit &target)
bool is_enemy (Unit &to_modify, Unit &target)
Private Attributes
const Sound * sound
Additional Inherited Members
Static Public Member Functions inherited from openage::UnitAbility
static ability_set set_from_list (const std::vector< ability_type > &items)
set bits corresponding to abilities, useful for initialising an ability_set using a brace enclosed list
Detailed Description
initiates a patrol action when given a valid target
Todo:
implement
Definition at line 329 of file ability.h.
Constructor & Destructor Documentation
PatrolAbility()
openage::PatrolAbility::PatrolAbility (const Sound * s = nullptr)
Definition at line 358 of file ability.cpp.
     :
     sound{s} {
 }
Member Function Documentation
can_invoke()
bool openage::PatrolAbility::can_invoke (Unit & to_modify, const Command & cmd) override virtual
true if the paramaters allow an action to be performed
Implements openage::UnitAbility.
Definition at line 363 of file ability.cpp.
{
     // \todo implement
     return false;
 }
invoke()
void openage::PatrolAbility::invoke (Unit & to_modify, const Command & cmd, bool play_sound = false) override virtual
applies command to a given unit
Implements openage::UnitAbility.
Definition at line 368 of file ability.cpp.
{
     to_modify.log(MSG(dbg) << "not implemented");
     if (play_sound && this->sound) {
         this->sound->play();
     }
     // \todo implement
 }
References openage::log::dbg(), openage::log::LogSource::log(), MSG, openage::Sound::play(), and sound.
type()
ability_type openage::PatrolAbility::type () inline override virtual
Implements openage::UnitAbility.
Definition at line 333 of file ability.h.
{
         return ability_type::patrol;
     }
References openage::patrol.
Member Data Documentation
sound
const Sound* openage::PatrolAbility::sound private
Definition at line 342 of file ability.h.
Referenced by invoke().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/ability.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/ability.cpp