openage: openage::Generator Class Reference
openage::Generator Class Reference
Manages creation and setup of new games.
#include <generator.h>
Public Member Functions
Generator (qtsdl::GuiItemLink *gui_link)
std::shared_ptr< GameSpec > get_spec () const
game spec used by this generator
std::vector< std::string > player_names () const
return the list of player names
std::shared_ptr< Terrain > terrain () const
returns the generated terrain
void add_units (GameMain &m) const
places all initial objects
std::unique_ptr< GameMain > create (std::shared_ptr< GameSpec > spec)
Create a game from a specification.
Public Member Functions inherited from qtsdl::GuiPropertyMap
GuiPropertyMap ()
~GuiPropertyMap ()
template<typename T >
T getv (const char *name) const
template<typename T >
T getv (const std::string &name) const
std::vector< std::string > get_csv (const char *name) const
std::vector< std::string > get_csv (const std::string &name) const
template<typename T >
void setv (const char *name, T v)
template<typename T >
void setv (const std::string &name, T v)
void set_csv (const char *name, const std::vector< std::string > &v)
void set_csv (const std::string &name, const std::vector< std::string > &v)
void setv (const char *name, const std::string &v)
void setv (const std::string &name, const std::string &v)
void setv (const char *name, const std::vector< std::string > &v)
void setv (const std::string &name, const std::vector< std::string > &v)
template<>
bool getv (const char *name) const
template<>
void setv (const char *name, bool v)
template<>
int getv (const char *name) const
template<>
void setv (const char *name, int v)
template<>
double getv (const char *name) const
template<>
void setv (const char *name, double v)
template<>
void setv (const char *name, const char *v)
template<>
QString getv (const char *name) const
template<>
void setv (const char *name, const QString &v)
template<>
QStringList getv (const char *name) const
template<>
void setv (const char *name, const QStringList &v)
template<>
bool getv (const char *name) const
template<>
void setv (const char *name, bool v)
template<>
int getv (const char *name) const
template<>
void setv (const char *name, int v)
template<>
double getv (const char *name) const
template<>
void setv (const char *name, double v)
template<>
std::string getv (const char *name) const
template<>
void setv (const char *name, const std::string &v)
template<>
void setv (const char *name, const char *v)
template<>
std::vector< std::string > getv (const char *name) const
template<>
void setv (const char *name, const std::vector< std::string > &v)
Public Attributes
qtsdl::GuiItemLink * gui_link
Public Attributes inherited from qtsdl::GuiPropertyMap
std::unique_ptr< GuiPropertyMapImpl > impl
Private Member Functions
void create_regions ()
Private Attributes
std::shared_ptr< GameSpec > spec
data version used to create a game
std::vector< Region > regions
the generated data
Detailed Description
Manages creation and setup of new games.
required values used to construct a game this includes game spec and players
this will be identical for each networked player in a game
Definition at line 133 of file generator.h.
Constructor & Destructor Documentation
Generator()
openage::Generator::Generator (qtsdl::GuiItemLink * gui_link) explicit
Definition at line 126 of file generator.cpp.
     :
     gui_link{gui_link}
 {
     this->setv("generation_seed", 4321);
     this->setv("terrain_size", 2);
     this->setv("terrain_base_id", 0);
     this->setv("player_area", 850);
     this->setv("player_radius", 10);
     this->setv("load_filename", "/tmp/default_save.oas");
     this->setv("from_file", false);
     this->set_csv("player_names", std::vector<std::string>{"name1", "name2"});
 }
References gui_link.
Member Function Documentation
add_units()
void openage::Generator::add_units (GameMain & m) const
places all initial objects
Definition at line 252 of file generator.cpp.
{
     for (auto &r : this->regions) {
         // Regions filled with resource objects
         // trees / mines
         if (r.object_id) {
             Player* p = m.get_player(r.owner);
             auto otype = p->get_type(r.object_id);
             if (!otype) {
                 break;
             }
             for (auto &tile : r.get_tiles()) {
                 m.placed_units.new_unit(*otype, *p, tile.to_phys3(*m.terrain));
             }
         }
         // A space for starting town center and villagers
         else if (r.owner) {
             Player* p = m.get_player(r.owner);
             auto tctype = p->get_type(109); // town center
             auto mvtype = p->get_type(83);  // male villager
             auto fvtype = p->get_type(293); // female villager
             auto sctype = p->get_type(448); // scout cavarly
             if (!tctype || !mvtype || !fvtype || !sctype) {
                 break;
             }
             coord::tile tile = r.get_center();
             tile.ne -= 1;
             tile.se -= 1;
             // Place a completed town center
             auto ref = m.placed_units.new_unit(*tctype, *p, tile.to_phys3(*m.terrain));
             if (ref.is_valid()) {
                 complete_building(*ref.get());
             }
             // Place three villagers
             tile.ne -= 1;
             m.placed_units.new_unit(*fvtype, *p, tile.to_phys3(*m.terrain));
             tile.se += 1;
             m.placed_units.new_unit(*mvtype, *p, tile.to_phys3(*m.terrain));
             tile.se += 1;
             m.placed_units.new_unit(*fvtype, *p, tile.to_phys3(*m.terrain));
             // \todo uncomment when the scout looks better
             //tile.se += 2;
             //m.placed_units.new_unit(*sctype, *p, tile.to_tile3().to_phys3());
         }
     }
 }
References openage::complete_building(), openage::GameMain::get_player(), openage::Player::get_type(), openage::UnitContainer::new_unit(), openage::GameMain::placed_units, ref, regions, openage::GameMain::terrain, and openage::coord::tile::to_phys3().
create()
std::unique_ptr< GameMain > openage::Generator::create (std::shared_ptr< GameSpec > spec)
Create a game from a specification.
Definition at line 303 of file generator.cpp.
{
     ENSURE(spec->load_complete(), "spec hasn't been checked or was invalidated");
     this->spec = spec;
     if (this->getv<bool>("from_file")) {
         // create an empty game
         this->regions.clear();
         auto game = std::make_unique<GameMain>(*this);
         gameio::load(game.get(), this->getv<std::string>("load_filename"));
         return game;
     } else {
         // generation
         this->create_regions();
         return std::make_unique<GameMain>(*this);
     }
 }
References create_regions(), ENSURE, openage::gameio::load(), regions, and spec.
create_regions()
void openage::Generator::create_regions () private
Definition at line 153 of file generator.cpp.
{
     // get option settings
     int seed = this->getv<int>("generation_seed");
     int size = this->getv<int>("terrain_size");
     int base_id = this->getv<int>("terrain_base_id");
     int p_area = this->getv<int>("player_area");
     int p_radius = this->getv<int>("player_radius");
     // enforce some lower limits
     size = std::max(1, size);
     base_id = std::max(0, base_id);
     p_area = std::max(50, p_area);
     p_radius = std::max(2, p_radius);
     rng::RNG rng(seed);
     Region base(size * 16);
     base.terrain_id = base_id;
     std::vector<Region> player_regions;
     int player_count = this->player_names().size() - 1;
     for (int i = 0; i < player_count; ++i) {
         log::log(MSG(dbg) << "generate player " << i);
         // space players in a circular pattern
         double angle = static_cast<double>(i) / static_cast<double>(player_count);
         int ne = size * p_radius * sin(math::TAU * angle);
         int se = size * p_radius * cos(math::TAU * angle);
         coord::tile player_tile{ne, se};
         Region player = base.take_tiles(rng, player_tile, p_area, 0.5);
         player.terrain_id = 10;
         Region obj_space = player.take_tiles(rng, player.get_center(), p_area / 5, 0.5);
         obj_space.owner = i + 1;
         obj_space.terrain_id = 8;
         Region trees1 = player.take_random(rng, p_area / 10, 0.3);
         trees1.terrain_id = 9;
         trees1.object_id = 349;
         Region trees2 = player.take_random(rng, p_area / 10, 0.3);
         trees2.terrain_id = 9;
         trees2.object_id = 351;
         Region stone = player.take_random(rng, 5, 0.3);
         stone.object_id = 102;
         Region gold = player.take_random(rng, 7, 0.3);
         gold.object_id = 66;
         Region forage = player.take_random(rng, 6, 0.3);
         forage.object_id = 59;
         Region sheep = player.take_random(rng, 4, 0.3);
         sheep.owner = obj_space.owner;
         sheep.object_id = 594;
         player_regions.push_back(player);
         player_regions.push_back(obj_space);
         player_regions.push_back(trees1);
         player_regions.push_back(trees2);
         player_regions.push_back(stone);
         player_regions.push_back(gold);
         player_regions.push_back(forage);
         player_regions.push_back(sheep);
     }
     for (int i = 0; i < 6; ++i) {
         Region extra_trees = base.take_random(rng, 160, 0.3);
         extra_trees.terrain_id = 9;
         extra_trees.object_id = 349;
         player_regions.push_back(extra_trees);
     }
     // set regions
     this->regions.clear();
     this->regions.push_back(base);
     for (auto &r : player_regions) {
         this->regions.push_back(r);
     }
 }
References openage::log::dbg(), openage::Region::get_center(), openage::gold, openage::log::log(), std::max(), MSG, openage::Region::object_id, openage::Region::owner, player_names(), regions, openage::stone, openage::Region::take_random(), openage::Region::take_tiles(), openage::math::TAU, and openage::Region::terrain_id.
Referenced by create().
get_spec()
std::shared_ptr< GameSpec > openage::Generator::get_spec () const
game spec used by this generator
Definition at line 140 of file generator.cpp.
{
     return this->spec;
 }
References spec.
player_names()
std::vector< std::string > openage::Generator::player_names () const
return the list of player names
Definition at line 144 of file generator.cpp.
{
     auto result = this->get_csv("player_names");
     // gaia is player 0
     result.insert(result.begin(), "gaia");
     return result;
 }
References qtsdl::GuiPropertyMap::get_csv(), and openage.testing.testing::result().
Referenced by create_regions().
terrain()
std::shared_ptr< Terrain > openage::Generator::terrain () const
returns the generated terrain
Definition at line 237 of file generator.cpp.
{
     auto terrain = std::make_shared<Terrain>(this->spec->get_terrain_meta(), true);
     for (auto &r : this->regions) {
         for (auto &tile : r.get_tiles()) {
             TerrainChunk *chunk = terrain->get_create_chunk(tile);
             chunk->get_data(tile.get_pos_on_chunk())->terrain_id = r.terrain_id;
         }
     }
     // mark the 0, 0 tile.
     coord::tile debug_tile_pos{0, 0};
     terrain->get_data(debug_tile_pos)->terrain_id = 6;
     return terrain;
 }
References openage::TerrainChunk::get_data(), regions, spec, and openage::TileContent::terrain_id.
Member Data Documentation
gui_link
qtsdl::GuiItemLink* openage::Generator::gui_link
Definition at line 176 of file generator.h.
Referenced by Generator().
regions
std::vector<Region> openage::Generator::regions private
the generated data
Definition at line 173 of file generator.h.
Referenced by add_units(), create(), create_regions(), and terrain().
spec
std::shared_ptr<GameSpec> openage::Generator::spec private
data version used to create a game
Definition at line 168 of file generator.h.
Referenced by create(), get_spec(), and terrain().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gamestate/generator.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gamestate/generator.cpp