openage: qtsdl::GuiSeparateRenderingContext Class Reference
qtsdl::GuiSeparateRenderingContext Class Reference
Create a separate context to render the GUI, make it shared with the main context.
#include <gui_ctx_setup.h>
Public Member Functions
GuiSeparateRenderingContext (SDL_Window *window)
virtual ~GuiSeparateRenderingContext ()
virtual void pre_render () override
Function that must be called before rendering the GUI.
virtual void post_render () override
Function that must be called after rendering the GUI.
Public Member Functions inherited from qtsdl::CtxExtractionMode
virtual ~CtxExtractionMode ()
QOpenGLContext * get_ctx ()
Private Attributes
QOpenGLContext main_ctx
GL context of the game.
std::unique_ptr< QOpenGLDebugLogger > ctx_logger
GL debug logger of the GL context of the GUI.
std::function< void()> make_current_back
Function to make the game context current.
QOffscreenSurface offscreen_surface
Surface that is needed to make the GUI context current.
Additional Inherited Members
Protected Attributes inherited from qtsdl::CtxExtractionMode
QOpenGLContext ctx
Detailed Description
Create a separate context to render the GUI, make it shared with the main context.
Definition at line 64 of file gui_ctx_setup.h.
Constructor & Destructor Documentation
GuiSeparateRenderingContext()
qtsdl::GuiSeparateRenderingContext::GuiSeparateRenderingContext (SDL_Window * window) explicit
Definition at line 56 of file gui_ctx_setup.cpp.
     :
     CtxExtractionMode{} {
     QVariant handle;
     std::tie(handle, this->make_current_back) = extract_native_context_and_switchback_func(window);
     if (handle.isValid()) {
         this->main_ctx.setNativeHandle(handle);
         this->main_ctx.create();
         assert(this->main_ctx.isValid());
         auto context_debug_parameters = get_current_opengl_debug_parameters(this->main_ctx);
         this->ctx.setFormat(this->main_ctx.format());
         this->ctx.setShareContext(&this->main_ctx);
         this->ctx.create();
         assert(this->ctx.isValid());
         assert(!(this->main_ctx.format().options() ^ this->ctx.format().options()).testFlag(QSurfaceFormat::DebugContext));
         this->offscreen_surface.setFormat(this->ctx.format());
         this->offscreen_surface.create();
         this->pre_render();
         apply_opengl_debug_parameters(context_debug_parameters, this->ctx);
         this->post_render();
     } else {
         throw CtxExtractionException("creating separate context for GUI failed");
     }
 }
~GuiSeparateRenderingContext()
qtsdl::GuiSeparateRenderingContext::~GuiSeparateRenderingContext () virtual
Definition at line 88 of file gui_ctx_setup.cpp.
{
     this->pre_render();
     this->ctx_logger.reset();
     this->post_render();
 }
References ctx_logger, post_render(), and pre_render().
Member Function Documentation
post_render()
void qtsdl::GuiSeparateRenderingContext::post_render () override virtual
Function that must be called after rendering the GUI.
Implements qtsdl::CtxExtractionMode.
Definition at line 101 of file gui_ctx_setup.cpp.
{
     this->make_current_back();
 }
References make_current_back.
Referenced by ~GuiSeparateRenderingContext().
pre_render()
void qtsdl::GuiSeparateRenderingContext::pre_render () override virtual
Function that must be called before rendering the GUI.
Implements qtsdl::CtxExtractionMode.
Definition at line 94 of file gui_ctx_setup.cpp.
{
     if (!this->ctx.makeCurrent(&this->offscreen_surface)) {
         assert(false);
         return;
     }
 }
References qtsdl::CtxExtractionMode::ctx.
Referenced by ~GuiSeparateRenderingContext().
Member Data Documentation
ctx_logger
std::unique_ptr<QOpenGLDebugLogger> qtsdl::GuiSeparateRenderingContext::ctx_logger private
GL debug logger of the GL context of the GUI.
Definition at line 81 of file gui_ctx_setup.h.
Referenced by ~GuiSeparateRenderingContext().
main_ctx
QOpenGLContext qtsdl::GuiSeparateRenderingContext::main_ctx private
GL context of the game.
Definition at line 76 of file gui_ctx_setup.h.
make_current_back
std::function<void()> qtsdl::GuiSeparateRenderingContext::make_current_back private
Function to make the game context current.
Definition at line 86 of file gui_ctx_setup.h.
Referenced by post_render().
offscreen_surface
QOffscreenSurface qtsdl::GuiSeparateRenderingContext::offscreen_surface private
Surface that is needed to make the GUI context current.
Definition at line 91 of file gui_ctx_setup.h.
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/guisys/private/gui_ctx_setup.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/guisys/private/gui_ctx_setup.cpp