openage: openage::curve::MapFilterIterator< key_t, val_t, container_t > Class Template Reference
openage::curve::MapFilterIterator< key_t, val_t, container_t > Class Template Reference
#include <map_filter_iterator.h>
Public Types
using iterator_t = typename container_t::const_iterator
Public Member Functions
MapFilterIterator (const iterator_t &base, const container_t *container, const time_t &from, const time_t &to)
MapFilterIterator (const MapFilterIterator &)=default
virtual bool valid () const override
val_t const & value () const override
const key_t & key () const
Public Member Functions inherited from openage::curve::CurveIterator< val_t, container_t >
CurveIterator (const container_t *c)
CurveIterator (const CurveIterator &)=default
virtual ~CurveIterator ()=default
CurveIterator< val_t, container_t, typename container_t::const_iterator > & operator= (const CurveIterator< val_t, container_t, typename container_t::const_iterator > &)=default
virtual const val_t & operator * () const
virtual const val_t * operator -> () const
virtual bool operator== (const CurveIterator< val_t, container_t > &rhs) const
virtual bool operator != (const CurveIterator< val_t, container_t > &rhs) const
virtual CurveIterator< val_t, container_t > & operator++ ()
const typename container_t::const_iterator & get_base () const
const time_t & get_from () const
const time_t & get_to () const
Additional Inherited Members
Protected Member Functions inherited from openage::curve::CurveIterator< val_t, container_t >
CurveIterator (const typename container_t::const_iterator &base, const container_t *container, const time_t &from, const time_t &to)
Protected Attributes inherited from openage::curve::CurveIterator< val_t, container_t >
typename container_t::const_iterator base
The iterator this is currently referring to.
const container_t * container
The base container.
time_t from
The time, from where this iterator started to iterate.
time_t to
The time, to where this iterator will iterate.
Detailed Description
template<typename key_t, typename val_t, typename container_t>
class openage::curve::MapFilterIterator< key_t, val_t, container_t >
A filtering operator to iterate over all elements of a map whose elements exist for a certain livespan. The range where to iterate is given at construction.
It depends on key_t and val_t as map-parameters, container_t is the container to operate on and the function valid_f, that checks if an element is alive.
Definition at line 24 of file map_filter_iterator.h.
Member Typedef Documentation
iterator_t
template<typename key_t, typename val_t, typename container_t> using openage::curve::MapFilterIterator< key_t, val_t, container_t >::iterator_t = typename container_t::const_iterator
Definition at line 26 of file map_filter_iterator.h.
Constructor & Destructor Documentation
MapFilterIterator() [1/2]
template<typename key_t, typename val_t, typename container_t> openage::curve::MapFilterIterator< key_t, val_t, container_t >::MapFilterIterator (const iterator_t & base, const container_t * container, const time_t & from, const time_t & to) inline
Construct the iterator from its boundary conditions: time and container
Definition at line 31 of file map_filter_iterator.h.
         :
         CurveIterator<val_t, container_t>(base, container, from, to) {}
MapFilterIterator() [2/2]
template<typename key_t, typename val_t, typename container_t> openage::curve::MapFilterIterator< key_t, val_t, container_t >::MapFilterIterator (const MapFilterIterator< key_t, val_t, container_t > &) default
Member Function Documentation
key()
template<typename key_t, typename val_t, typename container_t> const key_t& openage::curve::MapFilterIterator< key_t, val_t, container_t >::key () const inline
Get the key pointed to by this iterator.
Definition at line 58 of file map_filter_iterator.h.
{
         return this->get_base()->first;
     }
References openage::curve::CurveIterator< val_t, container_t >::get_base().
valid()
template<typename key_t, typename val_t, typename container_t> virtual bool openage::curve::MapFilterIterator< key_t, val_t, container_t >::valid () const inline override virtual
Check if the iterator is still valid (this breaks from the stl - in the best way)
Implements openage::curve::CurveIterator< val_t, container_t >.
Definition at line 42 of file map_filter_iterator.h.
{
         return (this->get_base()->second.alive >= this->from
                 and this->get_base()->second.dead < this->to);
     }
References openage::curve::CurveIterator< val_t, container_t >::get_base(), and openage::curve::CurveIterator< val_t, container_t >::to.
value()
template<typename key_t, typename val_t, typename container_t> val_t const& openage::curve::MapFilterIterator< key_t, val_t, container_t >::value () const inline override virtual
Get the value behind the iterator. Nicer way of accessing it beside operator *.
Implements openage::curve::CurveIterator< val_t, container_t >.
Definition at line 51 of file map_filter_iterator.h.
{
         return this->get_base()->second.value;
     }
References openage::curve::CurveIterator< val_t, container_t >::get_base().
Referenced by openage.convert.dataformat.members.ContinueReadMemberResult::__str__().
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/curve/map_filter_iterator.h