openage: openage::pyinterface::Func< ReturnType, ArgTypes > Class Template Reference
openage::pyinterface::Func< ReturnType, ArgTypes > Class Template Reference
#include <functional.h>
Public Member Functions
Func ()
template<typename F >
Func (F &&f)
template<typename F >
Func (std::reference_wrapper< F > f)
Func (const std::function< ReturnType(ArgTypes ...)> &f)
Func (std::function< ReturnType(ArgTypes ...)> &&f)
template<typename F >
Func< ReturnType, ArgTypes ... > & operator= (F &&f)
template<typename F >
Func< ReturnType, ArgTypes ... > & operator= (std::reference_wrapper< F > f)
Func< ReturnType, ArgTypes ... > & operator= (const std::function< ReturnType(ArgTypes ...)> &f)
Func< ReturnType, ArgTypes ... > & operator= (std::function< ReturnType(ArgTypes ...)> &&f)
void check_fptr () const
ReturnType call (ArgTypes ...args) const
operator const std::function< ReturnType (ArgTypes ...)> &() const
const std::function< ReturnType(ArgTypes ...)> & get () const
template<typename ... BoundArgTypes>
void bind (util::FunctionPtr< ReturnType, BoundArgTypes ..., ArgTypes ... > f, BoundArgTypes ...bound_args)
template<typename ... BoundArgTypes>
void bind_noexcept (util::FunctionPtr< ReturnType, BoundArgTypes ..., ArgTypes ... > f, BoundArgTypes ...bound_args)
void bind0 (ReturnType(*f)(ArgTypes ...))
void bind_noexcept0 (ReturnType(*f)(ArgTypes ...))
template<typename BoundArgType0 >
void bind1 (ReturnType(*f)(BoundArgType0, ArgTypes ...), BoundArgType0 bound_arg0)
template<typename BoundArgType0 >
void bind_noexcept1 (ReturnType(*f)(BoundArgType0, ArgTypes ...), BoundArgType0 bound_arg0)
template<typename BoundArgType0 , typename BoundArgType1 >
void bind2 (ReturnType(*f)(BoundArgType0, BoundArgType1, ArgTypes ...), BoundArgType0 bound_arg0, BoundArgType1 bound_arg1)
template<typename BoundArgType0 , typename BoundArgType1 >
void bind_noexcept2 (ReturnType(*f)(BoundArgType0, BoundArgType1, ArgTypes ...), BoundArgType0 bound_arg0, BoundArgType1 bound_arg1)
template<typename BoundArgType0 , typename BoundArgType1 , typename BoundArgType2 >
void bind3 (ReturnType(*f)(BoundArgType0, BoundArgType1, BoundArgType2, ArgTypes ...), BoundArgType0 bound_arg0, BoundArgType1 bound_arg1, BoundArgType2 bound_arg2)
template<typename BoundArgType0 , typename BoundArgType1 , typename BoundArgType2 >
void bind_noexcept3 (ReturnType(*f)(BoundArgType0, BoundArgType1, BoundArgType2, ArgTypes ...), BoundArgType0 bound_arg0, BoundArgType1 bound_arg1, BoundArgType2 bound_arg2)
Private Member Functions
template<bool return_type_is_void, typename ... BoundArgTypes>
std::enable_if< return_type_is_void >::type bind_catchexcept_impl (util::FunctionPtr< ReturnType, BoundArgTypes ..., ArgTypes ... > f, BoundArgTypes ...bound_args)
template<bool return_type_is_void, typename ... BoundArgTypes>
std::enable_if< not return_type_is_void >::type bind_catchexcept_impl (util::FunctionPtr< ReturnType, BoundArgTypes ..., ArgTypes ... > f, BoundArgTypes ...bound_args)
Private Attributes
std::function< ReturnType(ArgTypes ...)> fptr
Detailed Description
template<typename ReturnType, typename ... ArgTypes>
class openage::pyinterface::Func< ReturnType, ArgTypes >
Holds a function pointer, with bound arguments.
Can be filled via its implicit copy constructor, operator = or bind().
operator = is designed for usage from C++, and accepts set() sets it to an existing std::function object one of its bind() members.
It's auto-converted to std::function, and can be called via call().
Designed to allow Cython to call C++ functions that accept std::function callbacks, and to provide a callback function type for Cython to offer to C++.
As of right now, Cython doesn't support variadic templates [https://mail.python.org/pipermail/cython-devel/2015-June/004429.html].
Thus, Func has aliases to allow usage like regular templated types, one for each number of arguments:
from libopenage.pyinterface.functional import Func2 void myfunc(float a0, int a1, int a2): pass Func2[void, int, int] fobj Func2.bind1float
There are definitions up to Func5 and bind3; if you encounter a situation where you'd need more, maybe you should re-think some of your life choices.
Note that you shouldn't use this type purely internally in Cython, since if you bind a Cython function and call it from Cython, every Exception would be needlessly converted from Py to C++ to Py...
For global function pointers that should be initialized at pyinterface initialization time, use PyIfFunc instead of Func; that class has some additional code to verify successful initialization.
Definition at line 58 of file functional.h.
Constructor & Destructor Documentation
Func() [1/5]
template<typename ReturnType, typename ... ArgTypes> openage::pyinterface::Func< ReturnType, ArgTypes >::Func () inline
Definition at line 60 of file functional.h.
         :
         fptr{nullptr} {}
Func() [2/5]
template<typename ReturnType, typename ... ArgTypes> template<typename F > openage::pyinterface::Func< ReturnType, ArgTypes >::Func (F && f) inline
Definition at line 66 of file functional.h.
                 {
         this->fptr = f;
     }
Func() [3/5]
template<typename ReturnType, typename ... ArgTypes> template<typename F > openage::pyinterface::Func< ReturnType, ArgTypes >::Func (std::reference_wrapper< F > f) inline
Definition at line 71 of file functional.h.
{
         this->fptr = f;
     }
Func() [4/5]
template<typename ReturnType, typename ... ArgTypes> openage::pyinterface::Func< ReturnType, ArgTypes >::Func (const std::function< ReturnType(ArgTypes ...)> & f) inline
Definition at line 76 of file functional.h.
{
         this->fptr = f;
     }
Func() [5/5]
template<typename ReturnType, typename ... ArgTypes> openage::pyinterface::Func< ReturnType, ArgTypes >::Func (std::function< ReturnType(ArgTypes ...)> && f) inline
Definition at line 80 of file functional.h.
{
         this->fptr = f;
     }
Member Function Documentation
bind()
template<typename ReturnType, typename ... ArgTypes> template<typename ... BoundArgTypes> void openage::pyinterface::Func< ReturnType, ArgTypes >::bind (util::FunctionPtr< ReturnType, BoundArgTypes ..., ArgTypes ... > f, BoundArgTypes ... bound_args) inline
For manual binding of function pointers and arguments (from Cython; in C++, assign lambdas).
Adds additional code that catches and converts Python exceptions to C++ exceptions.
The 'util::FunctionPtr' argument is due to http://stackoverflow.com/questions/31040075. Note that with clang, it's possible to directly pass function pointers, while with gcc they need to be explicitly converted. Meh.
Definition at line 158 of file functional.h.
{
         this->bind_catchexcept_impl<std::is_void<ReturnType>::value, BoundArgTypes ...>(f, bound_args...);
     }
bind0()
template<typename ReturnType, typename ... ArgTypes> void openage::pyinterface::Func< ReturnType, ArgTypes >::bind0 (ReturnType(*)(ArgTypes ...) f) inline
Definition at line 201 of file functional.h.
{
         this->bind<>(
             util::FunctionPtr<ReturnType, ArgTypes ...>(f));
     }
bind1()
template<typename ReturnType, typename ... ArgTypes> template<typename BoundArgType0 > void openage::pyinterface::Func< ReturnType, ArgTypes >::bind1 (ReturnType(*)(BoundArgType0, ArgTypes ...) f, BoundArgType0 bound_arg0) inline
Definition at line 212 of file functional.h.
{
         this->bind<BoundArgType0>(
             util::FunctionPtr<ReturnType, BoundArgType0, ArgTypes ...>(f), bound_arg0);
     }
bind2()
template<typename ReturnType, typename ... ArgTypes> template<typename BoundArgType0 , typename BoundArgType1 > void openage::pyinterface::Func< ReturnType, ArgTypes >::bind2 (ReturnType(*)(BoundArgType0, BoundArgType1, ArgTypes ...) f, BoundArgType0 bound_arg0, BoundArgType1 bound_arg1) inline
Definition at line 224 of file functional.h.
{
         this->bind<BoundArgType0, BoundArgType1>(
             util::FunctionPtr<ReturnType, BoundArgType0, BoundArgType1, ArgTypes ...>(f), bound_arg0, bound_arg1);
     }
bind3()
template<typename ReturnType, typename ... ArgTypes> template<typename BoundArgType0 , typename BoundArgType1 , typename BoundArgType2 > void openage::pyinterface::Func< ReturnType, ArgTypes >::bind3 (ReturnType(*)(BoundArgType0, BoundArgType1, BoundArgType2, ArgTypes ...) f, BoundArgType0 bound_arg0, BoundArgType1 bound_arg1, BoundArgType2 bound_arg2) inline
Definition at line 236 of file functional.h.
{
         this->bind<BoundArgType0, BoundArgType1, BoundArgType2>(
             util::FunctionPtr<ReturnType, BoundArgType0, BoundArgType1, BoundArgType2, ArgTypes ...>(f), bound_arg0, bound_arg1, bound_arg2);
     }
bind_catchexcept_impl() [1/2]
template<typename ReturnType, typename ... ArgTypes> template<bool return_type_is_void, typename ... BoundArgTypes> std::enable_if<return_type_is_void>::type openage::pyinterface::Func< ReturnType, ArgTypes >::bind_catchexcept_impl (util::FunctionPtr< ReturnType, BoundArgTypes ..., ArgTypes ... > f, BoundArgTypes ... bound_args) inline private
Specialization for bind() with void return types.
Definition at line 168 of file functional.h.
{
         this->fptr = [=](ArgTypes ...args) -> ReturnType {
             f.ptr(bound_args..., args...);
             translate_exc_py_to_cpp();
         };
     }
bind_catchexcept_impl() [2/2]
template<typename ReturnType, typename ... ArgTypes> template<bool return_type_is_void, typename ... BoundArgTypes> std::enable_if<not return_type_is_void>::type openage::pyinterface::Func< ReturnType, ArgTypes >::bind_catchexcept_impl (util::FunctionPtr< ReturnType, BoundArgTypes ..., ArgTypes ... > f, BoundArgTypes ... bound_args) inline private
Specialization for bind() with non-void return types.
Definition at line 180 of file functional.h.
{
         this->fptr = [=](ArgTypes ...args) -> ReturnType {
             ReturnType &&result = f.ptr(bound_args..., args...);
             translate_exc_py_to_cpp();
             return result;
         };
     }
bind_noexcept()
template<typename ReturnType, typename ... ArgTypes> template<typename ... BoundArgTypes> void openage::pyinterface::Func< ReturnType, ArgTypes >::bind_noexcept (util::FunctionPtr< ReturnType, BoundArgTypes ..., ArgTypes ... > f, BoundArgTypes ... bound_args) inline
Like bind, but does not add an exception checker.
Definition at line 194 of file functional.h.
{
         this->fptr = [=](ArgTypes ...args) -> ReturnType {
             return f.ptr(bound_args..., args...);
         };
     }
bind_noexcept0()
template<typename ReturnType, typename ... ArgTypes> void openage::pyinterface::Func< ReturnType, ArgTypes >::bind_noexcept0 (ReturnType(*)(ArgTypes ...) f) inline
Definition at line 206 of file functional.h.
{
         this->bind_noexcept<>(
             util::FunctionPtr<ReturnType, ArgTypes ...>(f));
     }
bind_noexcept1()
template<typename ReturnType, typename ... ArgTypes> template<typename BoundArgType0 > void openage::pyinterface::Func< ReturnType, ArgTypes >::bind_noexcept1 (ReturnType(*)(BoundArgType0, ArgTypes ...) f, BoundArgType0 bound_arg0) inline
Definition at line 218 of file functional.h.
{
         this->bind_noexcept<BoundArgType0>(
             util::FunctionPtr<ReturnType, BoundArgType0, ArgTypes ...>(f), bound_arg0);
     }
bind_noexcept2()
template<typename ReturnType, typename ... ArgTypes> template<typename BoundArgType0 , typename BoundArgType1 > void openage::pyinterface::Func< ReturnType, ArgTypes >::bind_noexcept2 (ReturnType(*)(BoundArgType0, BoundArgType1, ArgTypes ...) f, BoundArgType0 bound_arg0, BoundArgType1 bound_arg1) inline
Definition at line 230 of file functional.h.
{
         this->bind_noexcept<BoundArgType0, BoundArgType1>(
             util::FunctionPtr<ReturnType, BoundArgType0, BoundArgType1, ArgTypes ...>(f), bound_arg0, bound_arg1);
     }
bind_noexcept3()
template<typename ReturnType, typename ... ArgTypes> template<typename BoundArgType0 , typename BoundArgType1 , typename BoundArgType2 > void openage::pyinterface::Func< ReturnType, ArgTypes >::bind_noexcept3 (ReturnType(*)(BoundArgType0, BoundArgType1, BoundArgType2, ArgTypes ...) f, BoundArgType0 bound_arg0, BoundArgType1 bound_arg1, BoundArgType2 bound_arg2) inline
Definition at line 242 of file functional.h.
{
         this->bind_noexcept<BoundArgType0, BoundArgType1, BoundArgType2>(
             util::FunctionPtr<ReturnType, BoundArgType0, BoundArgType1, BoundArgType2, ArgTypes ...>(f), bound_arg0, bound_arg1, bound_arg2);
     }
call()
template<typename ReturnType, typename ... ArgTypes> ReturnType openage::pyinterface::Func< ReturnType, ArgTypes >::call (ArgTypes ... args) const inline
for direct usage (mostly from Cython)
Definition at line 126 of file functional.h.
{
         this->check_fptr();
         return this->fptr(args...);
     }
check_fptr()
template<typename ReturnType, typename ... ArgTypes> void openage::pyinterface::Func< ReturnType, ArgTypes >::check_fptr () const inline
raises an Error if this->fptr is still uninitialized.
Definition at line 111 of file functional.h.
{
         if (unlikely(not this->fptr)) {
             throw Error(
                 MSG(err) << "Uninitialized Func object at " <<
                 util::symbol_name(static_cast<const void *>(this)) << ": "
                 "Can not call or convert to std::function.",
                 true // collect backtrace info
             );
         }
     }
Referenced by openage::pyinterface::Func< ReturnType, ArgTypes ... >::call(), openage::pyinterface::Func< ReturnType, ArgTypes ... >::get(), and openage::pyinterface::Func< ReturnType, ArgTypes ... >::operator const std::function< ReturnType().
get()
template<typename ReturnType, typename ... ArgTypes> const std::function<ReturnType (ArgTypes ...)>& openage::pyinterface::Func< ReturnType, ArgTypes >::get () const inline
for explicit conversion to std::function.
Definition at line 143 of file functional.h.
{
         this->check_fptr();
         return this->fptr;
     }
operator const std::function< ReturnType()
template<typename ReturnType, typename ... ArgTypes> openage::pyinterface::Func< ReturnType, ArgTypes >::operator const std::function< ReturnType (ArgTypes ...) const & inline
for implicit conversion to std::function, for usage in a context where std::function would be expected.
Definition at line 135 of file functional.h.
{
         this->check_fptr();
         return this->fptr;
     }
operator=() [1/4]
template<typename ReturnType, typename ... ArgTypes> template<typename F > Func<ReturnType, ArgTypes ...>& openage::pyinterface::Func< ReturnType, ArgTypes >::operator= (F && f) inline
Definition at line 86 of file functional.h.
{
         this->fptr = f;
         return *this;
     }
operator=() [2/4]
template<typename ReturnType, typename ... ArgTypes> template<typename F > Func<ReturnType, ArgTypes ...>& openage::pyinterface::Func< ReturnType, ArgTypes >::operator= (std::reference_wrapper< F > f) inline
Definition at line 92 of file functional.h.
{
         this->fptr = f;
         return *this;
     }
operator=() [3/4]
template<typename ReturnType, typename ... ArgTypes> Func<ReturnType, ArgTypes ...>& openage::pyinterface::Func< ReturnType, ArgTypes >::operator= (const std::function< ReturnType(ArgTypes ...)> & f) inline
Definition at line 98 of file functional.h.
{
         this->fptr = f;
         return *this;
     }
operator=() [4/4]
template<typename ReturnType, typename ... ArgTypes> Func<ReturnType, ArgTypes ...>& openage::pyinterface::Func< ReturnType, ArgTypes >::operator= (std::function< ReturnType(ArgTypes ...)> && f) inline
Definition at line 103 of file functional.h.
{
         this->fptr = f;
         return *this;
     }
Member Data Documentation
fptr
template<typename ReturnType, typename ... ArgTypes> std::function<ReturnType (ArgTypes ...)> openage::pyinterface::Func< ReturnType, ArgTypes >::fptr private
Definition at line 248 of file functional.h.
Referenced by openage::pyinterface::Func< ReturnType, ArgTypes ... >::bind_catchexcept_impl(), openage::pyinterface::Func< ReturnType, ArgTypes ... >::bind_noexcept(), openage::pyinterface::Func< ReturnType, ArgTypes ... >::call(), openage::pyinterface::Func< ReturnType, ArgTypes ... >::check_fptr(), openage::pyinterface::Func< ReturnType, ArgTypes ... >::Func(), openage::pyinterface::Func< ReturnType, ArgTypes ... >::get(), openage::pyinterface::Func< ReturnType, ArgTypes ... >::operator const std::function< ReturnType(), and openage::pyinterface::Func< ReturnType, ArgTypes ... >::operator=().
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/pyinterface/functional.h