openage: openage::gui::ActionsListModel Class Reference
openage::gui::ActionsListModel Class Reference
#include <actions_list_model.h>
Public Types
enum ActionsRoles { ActionsRoles::IconRole = Qt::UserRole + 1, ActionsRoles::IconCheckedRole, ActionsRoles::GroupIDRole, ActionsRoles::NameRole }
enum GroupIDs { GroupIDs::NoGroup, GroupIDs::StanceGroup }
Signals
void icons_source_changed (const QUrl icons_source)
Public Member Functions
ActionsListModel (QObject *parent=nullptr)
virtual ~ActionsListModel ()
ActionButtonsType get_active_buttons () const
void set_active_buttons (const ActionButtonsType &active_buttons)
ActionModeLink * get_action_mode () const
void set_action_mode (ActionModeLink *action_mode)
QUrl get_icons_source () const
void set_icons_source (const QUrl icons_source)
Q_INVOKABLE void set_initial_buttons ()
Properties
ActionButtonsType active_buttons
ActionModeLink action_mode
QUrl iconsSource
Private Slots
void on_buttons_type_changed (const ActionButtonsType buttons_type)
Private Member Functions
virtual QHash< int, QByteArray > roleNames () const override
virtual int rowCount (const QModelIndex &) const override
virtual QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
virtual QMap< int, QVariant > itemData (const QModelIndex &index) const override
void set_icons_source (const std::string icons_source)
void clear_buttons ()
void add_button (int ico, int ico_chk, int grp_id, const char *name)
Private Attributes
ActionModeLink * action_mode
QUrl icons_source
std::vector< QMap< int, QVariant > > buttons
Detailed Description
Model used for the Action Buttons to render (e.g. for civilian units, military units, buildings etc.)
Definition at line 20 of file actions_list_model.h.
Member Enumeration Documentation
ActionsRoles
enum openage::gui::ActionsListModel::ActionsRoles strong
Enumerator
IconRole
IconCheckedRole
GroupIDRole
NameRole
Definition at line 42 of file actions_list_model.h.
{
         IconRole = Qt::UserRole + 1,
         IconCheckedRole,
         GroupIDRole,
         NameRole
     };
GroupIDs
enum openage::gui::ActionsListModel::GroupIDs strong
Enumerator
NoGroup
StanceGroup
Definition at line 49 of file actions_list_model.h.
{
         NoGroup,
         StanceGroup
     };
Constructor & Destructor Documentation
ActionsListModel()
openage::gui::ActionsListModel::ActionsListModel (QObject * parent = nullptr)
Definition at line 17 of file actions_list_model.cpp.
     :
     QAbstractListModel{parent},
     action_mode{} {
     Q_UNUSED(registration);
 }
~ActionsListModel()
openage::gui::ActionsListModel::~ActionsListModel () virtual
Definition at line 24 of file actions_list_model.cpp.
{
 }
Member Function Documentation
add_button()
void openage::gui::ActionsListModel::add_button (int ico, int ico_chk, int grp_id, const char * name) private
Shortcut to creating a QMap for a button
Definition at line 190 of file actions_list_model.cpp.
{
     QMap<int, QVariant> map;
     map[static_cast<int>(ActionsRoles::IconRole)] = QVariant(ico);
     map[static_cast<int>(ActionsRoles::IconCheckedRole)] = QVariant(ico_chk);
     map[static_cast<int>(ActionsRoles::GroupIDRole)] = QVariant(grp_id);
     map[static_cast<int>(ActionsRoles::NameRole)] = QVariant(name);
     this->buttons.push_back(map);
 }
References buttons, GroupIDRole, IconCheckedRole, IconRole, map, and NameRole.
Referenced by set_active_buttons().
clear_buttons()
void openage::gui::ActionsListModel::clear_buttons () private
Clears all buttons
Definition at line 184 of file actions_list_model.cpp.
{
     this->beginResetModel();
     this->buttons.clear();
     this->endResetModel();
 }
References buttons.
Referenced by set_active_buttons().
data()
QVariant openage::gui::ActionsListModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override private virtual
Definition at line 176 of file actions_list_model.cpp.
{
     return this->buttons.at(index.row()).value(role);
 }
References buttons.
Referenced by openage.convert.peresource.PEResources::read_directory().
get_action_mode()
ActionModeLink * openage::gui::ActionsListModel::get_action_mode () const
Definition at line 120 of file actions_list_model.cpp.
{
     return this->action_mode;
 }
References action_mode.
get_active_buttons()
ActionButtonsType openage::gui::ActionsListModel::get_active_buttons () const
Definition at line 27 of file actions_list_model.cpp.
{
     return this->active_buttons;
 }
References active_buttons.
get_icons_source()
QUrl openage::gui::ActionsListModel::get_icons_source () const
Definition at line 142 of file actions_list_model.cpp.
{
     return QUrl(this->icons_source);
 }
References icons_source.
icons_source_changed
void openage::gui::ActionsListModel::icons_source_changed (const QUrl icons_source) signal
Referenced by set_icons_source().
itemData()
QMap< int, QVariant > openage::gui::ActionsListModel::itemData (const QModelIndex & index) const override private virtual
Definition at line 180 of file actions_list_model.cpp.
{
     return this->buttons.at(index.row());
 }
References buttons.
on_buttons_type_changed
void openage::gui::ActionsListModel::on_buttons_type_changed (const ActionButtonsType buttons_type) private slot
Definition at line 159 of file actions_list_model.cpp.
{
     this->set_active_buttons(buttons_type);
 }
References set_active_buttons().
Referenced by set_action_mode().
roleNames()
QHash< int, QByteArray > openage::gui::ActionsListModel::roleNames () const override private virtual
Definition at line 163 of file actions_list_model.cpp.
{
     QHash<int, QByteArray> roles;
     roles[static_cast<int>(ActionsRoles::IconRole)] = "ico";
     roles[static_cast<int>(ActionsRoles::IconCheckedRole)] = "icoChk";
     roles[static_cast<int>(ActionsRoles::GroupIDRole)] = "grpID";
     roles[static_cast<int>(ActionsRoles::NameRole)] = "name";
     return roles;
 }
References GroupIDRole, IconCheckedRole, IconRole, and NameRole.
rowCount()
int openage::gui::ActionsListModel::rowCount (const QModelIndex &) const override private virtual
Definition at line 172 of file actions_list_model.cpp.
{
     return this->buttons.size();
 }
References buttons.
set_action_mode()
void openage::gui::ActionsListModel::set_action_mode (ActionModeLink * action_mode)
Definition at line 124 of file actions_list_model.cpp.
{
     if (this->action_mode != action_mode) {
         if (this->action_mode != nullptr) {
             QObject::disconnect(this->action_mode,
                                 &ActionModeLink::buttons_type_changed,
                                 this,
                                 &ActionsListModel::on_buttons_type_changed);
         }
         this->action_mode = action_mode;
         QObject::connect(this->action_mode,
                          &ActionModeLink::buttons_type_changed,
                          this,
                          &ActionsListModel::on_buttons_type_changed);
     }
 }
References action_mode, openage::gui::ActionModeLink::buttons_type_changed(), and on_buttons_type_changed().
set_active_buttons()
void openage::gui::ActionsListModel::set_active_buttons (const ActionButtonsType & active_buttons)
Definition at line 31 of file actions_list_model.cpp.
{
     if (this->active_buttons == active_buttons) {
         return;
     }
     this->active_buttons = active_buttons;
     switch (active_buttons) {
     case ActionButtonsType::None:
         this->clear_buttons();
         break;
     case ActionButtonsType::MilitaryUnits:
         this->clear_buttons();
         this->set_icons_source("image://by-filename/converted/interface/hudactions.slp.png");
         this->beginResetModel();
         this->add_button(6,  -1, static_cast<int>(GroupIDs::NoGroup),     "SET_ABILITY_PATROL");
         this->add_button(7,  -1, static_cast<int>(GroupIDs::NoGroup),     "SET_ABILITY_GUARD");
         this->add_button(8,  -1, static_cast<int>(GroupIDs::NoGroup),     "SET_ABILITY_FOLLOW");
         this->add_button(59, -1, static_cast<int>(GroupIDs::NoGroup),     "KILL_UNIT");
         this->add_button(2,  -1, static_cast<int>(GroupIDs::NoGroup),     "SET_ABILITY_GARRISON");
         this->add_button(9,  53, static_cast<int>(GroupIDs::StanceGroup), "AGGRESSIVE_STANCE");
         this->add_button(10, 52, static_cast<int>(GroupIDs::StanceGroup), "DEFENSIVE_STANCE");
         this->add_button(11, 51, static_cast<int>(GroupIDs::StanceGroup), "HOLD_STANCE");
         this->add_button(50, 54, static_cast<int>(GroupIDs::StanceGroup), "PASSIVE_STANCE");
         this->add_button(3,  -1, static_cast<int>(GroupIDs::NoGroup),     "STOP");
         this->endResetModel();
         break;
     case ActionButtonsType::CivilianUnits:
         this->clear_buttons();
         this->set_icons_source("image://by-filename/converted/interface/hudactions.slp.png");
         this->beginResetModel();
         this->add_button(30, -1, static_cast<int>(GroupIDs::NoGroup), "BUILD_MENU");
         this->add_button(31, -1, static_cast<int>(GroupIDs::NoGroup), "BUILD_MENU_MIL");
         this->add_button(28, -1, static_cast<int>(GroupIDs::NoGroup), "SET_ABILITY_REPAIR");
         this->add_button(59, -1, static_cast<int>(GroupIDs::NoGroup), "KILL_UNIT");
         this->add_button(2,  -1, static_cast<int>(GroupIDs::NoGroup), "SET_ABILITY_GARRISON");
         this->add_button(-1, -1, static_cast<int>(GroupIDs::NoGroup), "");
         this->add_button(-1, -1, static_cast<int>(GroupIDs::NoGroup), "");
         this->add_button(-1, -1, static_cast<int>(GroupIDs::NoGroup), "");
         this->add_button(-1, -1, static_cast<int>(GroupIDs::NoGroup), "");
         this->add_button(3,  -1, static_cast<int>(GroupIDs::NoGroup), "STOP");
         this->endResetModel();
         break;
     case ActionButtonsType::BuildMenu:
         this->clear_buttons();
         this->set_icons_source("image://by-filename/converted/interface/50705.slp.png");
         this->beginResetModel();
         this->add_button(34, -1, static_cast<int>(GroupIDs::NoGroup), "BUILDING_HOUS");
         this->add_button(20, -1, static_cast<int>(GroupIDs::NoGroup), "BUILDING_MILL");
         this->add_button(39, -1, static_cast<int>(GroupIDs::NoGroup), "BUILDING_MINE");
         this->add_button(40, -1, static_cast<int>(GroupIDs::NoGroup), "BUILDING_SMIL");
         this->add_button(13, -1, static_cast<int>(GroupIDs::NoGroup), "BUILDING_DOCK");
         this->add_button(35, -1, static_cast<int>(GroupIDs::NoGroup), "BUILDING_FARM");
         this->add_button(4,  -1, static_cast<int>(GroupIDs::NoGroup), "BUILDING_BLAC");
         this->add_button(16, -1, static_cast<int>(GroupIDs::NoGroup), "BUILDING_MRKT");
         this->add_button(10, -1, static_cast<int>(GroupIDs::NoGroup), "BUILDING_CRCH");
         this->add_button(32, -1, static_cast<int>(GroupIDs::NoGroup), "BUILDING_UNIV");
         this->add_button(28, -1, static_cast<int>(GroupIDs::NoGroup), "BUILDING_RTWC");
         this->add_button(37, -1, static_cast<int>(GroupIDs::NoGroup), "BUILDING_WNDR");
         this->endResetModel();
         break;
     case ActionButtonsType::MilBuildMenu:
         this->clear_buttons();
         this->set_icons_source("image://by-filename/converted/interface/50705.slp.png");
         this->beginResetModel();
         this->add_button(2,  -1, static_cast<int>(GroupIDs::NoGroup), "BUILDING_BRKS");
         this->add_button(0,  -1, static_cast<int>(GroupIDs::NoGroup), "BUILDING_ARRG");
         this->add_button(23, -1, static_cast<int>(GroupIDs::NoGroup), "BUILDING_STBL");
         this->add_button(22, -1, static_cast<int>(GroupIDs::NoGroup), "BUILDING_SIWS");
         this->add_button(38, -1, static_cast<int>(GroupIDs::NoGroup), "BUILDING_WCTWX");
         this->add_button(30, -1, static_cast<int>(GroupIDs::NoGroup), "BUILDING_WALL");
         this->add_button(29, -1, static_cast<int>(GroupIDs::NoGroup), "BUILDING_WALL2");
         this->add_button(25, -1, static_cast<int>(GroupIDs::NoGroup), "BUILDING_WCTW");
         this->add_button(42, -1, static_cast<int>(GroupIDs::NoGroup), "BUILDING_WCTW4");
         this->add_button(36, -1, static_cast<int>(GroupIDs::NoGroup), "BUILDING_GTCA2");
         this->add_button(7,  -1, static_cast<int>(GroupIDs::NoGroup), "BUILDING_CSTL");
         this->endResetModel();
         break;
     default:
         log::log(MSG(warn) << "Unknown action mode selection");
     }
 }
References active_buttons, add_button(), openage::BuildMenu, openage::CivilianUnits, clear_buttons(), openage::log::log(), openage::MilBuildMenu, openage::MilitaryUnits, MSG, NoGroup, openage::None, set_icons_source(), StanceGroup, and openage::log::warn().
Referenced by on_buttons_type_changed(), and set_initial_buttons().
set_icons_source() [1/2]
void openage::gui::ActionsListModel::set_icons_source (const QUrl icons_source)
Definition at line 146 of file actions_list_model.cpp.
{
     this->icons_source = icons_source;
 }
References icons_source.
Referenced by set_active_buttons().
set_icons_source() [2/2]
void openage::gui::ActionsListModel::set_icons_source (const std::string icons_source) private
Utility function to create a QUrl from a string and set it as iconsSource
Definition at line 150 of file actions_list_model.cpp.
{
     this->icons_source = QUrl(icons_source.c_str());
     emit this->icons_source_changed(this->icons_source);
 }
References icons_source, and icons_source_changed().
set_initial_buttons()
Q_INVOKABLE void openage::gui::ActionsListModel::set_initial_buttons ()
Definition at line 155 of file actions_list_model.cpp.
{
     this->set_active_buttons(ActionButtonsType::None);
 }
References openage::None, and set_active_buttons().
Member Data Documentation
action_mode
ActionModeLink* openage::gui::ActionsListModel::action_mode private
Definition at line 82 of file actions_list_model.h.
buttons
std::vector<QMap<int, QVariant> > openage::gui::ActionsListModel::buttons private
Definition at line 84 of file actions_list_model.h.
Referenced by add_button(), clear_buttons(), data(), itemData(), and rowCount().
icons_source
QUrl openage::gui::ActionsListModel::icons_source private
Definition at line 83 of file actions_list_model.h.
Referenced by get_icons_source(), and set_icons_source().
Property Documentation
action_mode
ActionModeLink openage::gui::ActionsListModel::action_mode read write
Definition at line 24 of file actions_list_model.h.
Referenced by get_action_mode(), and set_action_mode().
active_buttons
ActionButtonsType openage::gui::ActionsListModel::active_buttons read write
Definition at line 23 of file actions_list_model.h.
Referenced by get_active_buttons(), and set_active_buttons().
iconsSource
QUrl openage::gui::ActionsListModel::iconsSource read write
Definition at line 25 of file actions_list_model.h.
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/actions_list_model.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/actions_list_model.cpp