openage: openage::UnitAction Class Reference
openage::UnitAction Class Reference abstract
#include <action.h>
Public Member Functions
UnitAction (Unit *u, graphic_type initial_gt)
virtual ~UnitAction ()
graphic_type type () const
float current_frame () const
virtual void update (unsigned int time)=0
virtual void on_completion ()=0
virtual bool completed () const =0
virtual bool allow_interupt () const =0
virtual bool allow_control () const =0
virtual std::string name () const =0
virtual const graphic_set & current_graphics () const
void draw_debug (const Engine &engine)
void face_towards (const coord::phys3 pos)
bool damage_unit (Unit &target)
void move_to (Unit &target, bool use_range=true)
Static Public Member Functions
static coord::phys_t adjacent_range (Unit *u)
static coord::phys_t get_attack_range (Unit *u)
static coord::phys_t get_heal_range (Unit *u)
Static Public Attributes
static bool show_debug = false
Protected Attributes
Unit * entity
graphic_type graphic
float frame
float frame_rate
std::function< void(const Engine &)> debug_draw_action
Detailed Description
Actions can be pushed onto any units action stack
Each update cycle will perform the update function of the action on top of this stack
Definition at line 88 of file action.h.
Constructor & Destructor Documentation
UnitAction()
openage::UnitAction::UnitAction (Unit * u, graphic_type initial_gt)
Require unit to be updated and an initial graphic type
Definition at line 89 of file action.cpp.
     :
     entity{u},
     graphic{initial_gt},
     frame{.0f},
     frame_rate{.0f} {
     auto &g_set = this->current_graphics();
     if (g_set.count(initial_gt) > 0) {
         auto utex = g_set.at(initial_gt);
         if (utex) {
             this->frame_rate = utex->frame_rate;
         }
         else {
             this->entity->log(MSG(dbg) << "Broken graphic (null)");
         }
     }
     else {
         this->entity->log(MSG(dbg) << "Broken graphic (not available)");
     }
     if (this->frame_rate == 0) {
         // a random starting point for static graphics
         // this creates variations in trees / houses etc
         // this value is also deterministic to match across clients
         this->frame = (u->id * u->id * 19249) & 0xff;
     }
 }
~UnitAction()
virtual openage::UnitAction::~UnitAction () inline virtual
Definition at line 96 of file action.h.
 {}
Member Function Documentation
adjacent_range()
coord::phys_t openage::UnitAction::adjacent_range (Unit * u) static
a small distance to which units are considered touching when within this distance
Definition at line 67 of file action.cpp.
{
     return path::path_grid_size * 3 + (u->location->min_axis() / 2L);
 }
References openage::Unit::location, and openage::path::path_grid_size.
Referenced by get_attack_range(), and get_heal_range().
allow_control()
virtual bool openage::UnitAction::allow_control () const pure virtual
control whether stack can discard the action automatically and should the stack be modifiable when this action is on top
if true this action must complete and will not allow new actions to be pushed while it is active and also does not update the secondary actions
Implemented in openage::ProjectileAction, openage::ResearchAction, openage::TrainAction, openage::UngarrisonAction, openage::MoveAction, openage::IdleAction, openage::FoundationAction, openage::DeadAction, openage::DecayAction, and openage::TargetAction.
allow_interupt()
virtual bool openage::UnitAction::allow_interupt () const pure virtual
checks if the action can be interrupted, allowing it to be popped if the user specifies a new action, if false the action must reach a completed state before removal eg dead action must be completed and cannot be discarded
Implemented in openage::ProjectileAction, openage::ResearchAction, openage::TrainAction, openage::UngarrisonAction, openage::MoveAction, openage::IdleAction, openage::FoundationAction, openage::DeadAction, openage::DecayAction, and openage::TargetAction.
completed()
virtual bool openage::UnitAction::completed () const pure virtual
gets called for all actions on stack each update cycle
Returns
true when action is completed so it and everything above it can be popped
Implemented in openage::ProjectileAction, openage::ResearchAction, openage::TrainAction, openage::UngarrisonAction, openage::MoveAction, openage::IdleAction, openage::FoundationAction, openage::DeadAction, openage::DecayAction, and openage::TargetAction.
current_frame()
float openage::UnitAction::current_frame () const
frame number to use on the current graphic
Definition at line 123 of file action.cpp.
{
     return this->frame;
 }
References frame.
current_graphics()
const graphic_set & openage::UnitAction::current_graphics () const virtual
determines which graphic should be used for drawing this unit finds the default graphic using the units type, used by most actions
this virtual function is overriden for special cases such as villager task graphics
Definition at line 127 of file action.cpp.
{
     // return the default graphic
     return this->entity->unit_type->graphics;
 }
References entity, openage::UnitType::graphics, and openage::Unit::unit_type.
Referenced by openage::Unit::draw(), openage::AttackAction::update_in_range(), and openage::HealAction::update_in_range().
damage_unit()
bool openage::UnitAction::damage_unit (Unit & target)
Damage a unit, returns true if the unit was killed in the process
Definition at line 147 of file action.cpp.
{
     bool killed = false;
     if (target.has_attribute(attr_type::damaged)) {
         auto &dm = target.get_attribute<attr_type::damaged>();
         // this is the damage calculation system
         if (dm.hp == 0) {
             // already killed, do nothing
         }
         else if (target.has_attribute(attr_type::armor) && this->entity->has_attribute(attr_type::attack)) {
             auto &armor = target.get_attribute<attr_type::armor>().armor;
             auto &damage = this->entity->get_attribute<attr_type::attack>().damage;
             unsigned int actual_damage = 0;
             for (const auto &pair : armor) {
                 auto search = damage.find(pair.first);
                 if (search != damage.end()) {
                     if (pair.second < search->second) {
                         actual_damage += search->second - pair.second;
                     }
                 }
             }
             // \todo add elevation modifier here
             if (actual_damage < 1) {
                 actual_damage = 1;
             }
             if (dm.hp > actual_damage) {
                 dm.hp -= actual_damage;
             }
             else {
                 dm.hp = 0;
                 killed = true;
             }
         }
         else {
             // \todo remove (keep for testing)
             unsigned int dmg = 1;
             if (dm.hp > dmg) {
                 dm.hp -= dmg;
             }
             else {
                 dm.hp = 0;
                 killed = true;
             }
         }
     }
     if (killed) {
         // if killed, give credit to a player
         if (this->entity->has_attribute(attr_type::owner)) {
             auto &owner = this->entity->get_attribute<attr_type::owner>().player;
             owner.killed_unit(target);
         }
     }
     return killed;
 }
References openage::armor, openage::attack, openage::damaged, entity, openage::Unit::get_attribute(), openage::Unit::has_attribute(), and openage::owner.
Referenced by openage::AttackAction::attack(), and openage::ProjectileAction::update().
draw_debug()
void openage::UnitAction::draw_debug (const Engine & engine)
Definition at line 133 of file action.cpp.
{
     // draw debug content if available
     if (show_debug && this->debug_draw_action) {
         this->debug_draw_action(engine);
     }
 }
References debug_draw_action, and show_debug.
face_towards()
void openage::UnitAction::face_towards (const coord::phys3 pos)
common functions for actions
Definition at line 140 of file action.cpp.
{
     if (this->entity->has_attribute(attr_type::direction)) {
         auto &d_attr = this->entity->get_attribute<attr_type::direction>();
         d_attr.unit_dir = pos - this->entity->location->pos.draw;
     }
 }
References openage::direction, entity, openage::Unit::get_attribute(), openage::Unit::has_attribute(), and openage::Unit::location.
Referenced by openage::TargetAction::update().
get_attack_range()
coord::phys_t openage::UnitAction::get_attack_range (Unit * u) static
looks at an ranged attributes on the unit otherwise returns same as adjacent_range()
Definition at line 71 of file action.cpp.
{
     coord::phys_t range = adjacent_range(u);
     if (u->has_attribute(attr_type::attack)) {
         auto &attack = u->get_attribute<attr_type::attack>();
         range += attack.max_range;
     }
     return range;
 }
References adjacent_range(), openage::attack, openage::Unit::get_attribute(), and openage::Unit::has_attribute().
Referenced by openage::AttackAction::AttackAction(), and openage::HealAction::HealAction().
get_heal_range()
coord::phys_t openage::UnitAction::get_heal_range (Unit * u) static
looks at heal attribute on the unit otherwise returns same as adjacent_range()
Definition at line 80 of file action.cpp.
{
     coord::phys_t range = adjacent_range(u);
     if (u->has_attribute(attr_type::heal)) {
         auto &heal = u->get_attribute<attr_type::heal>();
         range += heal.range;
     }
     return range;
 }
References adjacent_range(), openage::Unit::get_attribute(), openage::Unit::has_attribute(), and openage::heal.
move_to()
void openage::UnitAction::move_to (Unit & target, bool use_range = true)
Definition at line 208 of file action.cpp.
{
     auto &player = this->entity->get_attribute<attr_type::owner>().player;
     Command cmd(player, &target);
     cmd.set_ability(ability_type::move);
     if (use_range) {
         cmd.add_flag(command_flag::use_range);
     }
     this->entity->queue_cmd(cmd);
 }
References entity, openage::Unit::get_attribute(), openage::move, openage::owner, openage::Unit::queue_cmd(), and openage::use_range.
Referenced by openage::TargetAction::update().
name()
virtual std::string openage::UnitAction::name () const pure virtual
debug string to identify action types
Implemented in openage::ProjectileAction, openage::ConvertAction, openage::HealAction, openage::AttackAction, openage::GatherAction, openage::RepairAction, openage::BuildAction, openage::ResearchAction, openage::TrainAction, openage::UngarrisonAction, openage::GarrisonAction, openage::MoveAction, openage::IdleAction, openage::FoundationAction, openage::DeadAction, openage::DecayAction, and openage::TargetAction.
Referenced by openage::UnitSelection::show_attributes(), openage.util.fslike.path.Path::stem(), openage.util.fslike.path.Path::suffix(), and openage.util.fslike.path.Path::suffixes().
on_completion()
virtual void openage::UnitAction::on_completion () pure virtual
action to perform when popped from a units action stack
Implemented in openage::ProjectileAction, openage::BuildAction, openage::ResearchAction, openage::TrainAction, openage::UngarrisonAction, openage::MoveAction, openage::IdleAction, openage::FoundationAction, openage::DeadAction, openage::DecayAction, and openage::TargetAction.
type()
graphic_type openage::UnitAction::type () const
type of graphic this action should use
Definition at line 119 of file action.cpp.
{
     return this->graphic;
 }
References graphic.
update()
virtual void openage::UnitAction::update (unsigned int time) pure virtual
each action has its own update functionality which gets called when this is the active action
Implemented in openage::ProjectileAction, openage::ResearchAction, openage::TrainAction, openage::UngarrisonAction, openage::MoveAction, openage::IdleAction, openage::FoundationAction, openage::DeadAction, openage::DecayAction, and openage::TargetAction.
Referenced by openage::Unit::update().
Member Data Documentation
debug_draw_action
std::function<void(const Engine &)> openage::UnitAction::debug_draw_action protected
additional drawing for debug purposes
Definition at line 209 of file action.h.
Referenced by draw_debug(), and openage::MoveAction::initialise().
entity
Unit* openage::UnitAction::entity protected
the entity being updated
Definition at line 197 of file action.h.
Referenced by openage::AttackAction::attack(), openage::DeadAction::completed(), openage::FoundationAction::completed(), openage::IdleAction::completed(), openage::ProjectileAction::completed(), current_graphics(), damage_unit(), face_towards(), openage::AttackAction::fire_projectile(), openage::HealAction::heal(), openage::IdleAction::IdleAction(), openage::MoveAction::initialise(), move_to(), openage::GatherAction::nearest_dropsite(), openage::TargetAction::on_completion(), openage::DeadAction::on_completion(), openage::FoundationAction::on_completion(), openage::BuildAction::on_completion(), openage::GatherAction::on_completion_in_range(), openage::MoveAction::set_distance(), openage::MoveAction::set_path(), openage::DeadAction::update(), openage::FoundationAction::update(), openage::IdleAction::update(), openage::MoveAction::update(), openage::UngarrisonAction::update(), openage::TrainAction::update(), openage::ProjectileAction::update(), openage::TargetAction::update_distance(), openage::GarrisonAction::update_in_range(), openage::RepairAction::update_in_range(), and openage::GatherAction::update_in_range().
frame
float openage::UnitAction::frame protected
Definition at line 203 of file action.h.
Referenced by openage::DecayAction::completed(), openage::DeadAction::completed(), current_frame(), openage::DecayAction::update(), openage::DeadAction::update(), openage::IdleAction::update(), openage::MoveAction::update(), openage::ProjectileAction::update(), openage::BuildAction::update_in_range(), openage::RepairAction::update_in_range(), openage::GatherAction::update_in_range(), openage::AttackAction::update_in_range(), and openage::HealAction::update_in_range().
frame_rate
float openage::UnitAction::frame_rate protected
Definition at line 204 of file action.h.
Referenced by openage::DecayAction::update(), openage::DeadAction::update(), openage::IdleAction::update(), openage::MoveAction::update(), openage::ProjectileAction::update(), openage::BuildAction::update_in_range(), openage::RepairAction::update_in_range(), and openage::GatherAction::update_in_range().
graphic
graphic_type openage::UnitAction::graphic protected
common graphic controls
Definition at line 202 of file action.h.
Referenced by openage::MoveAction::initialise(), type(), openage::IdleAction::update(), openage::AttackAction::update_in_range(), and openage::HealAction::update_in_range().
show_debug
bool openage::UnitAction::show_debug = false static
produce debug info such as visualising paths
Definition at line 173 of file action.h.
Referenced by draw_debug().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/action.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/action.cpp