openage: openage::AssetManager Class Reference
openage::AssetManager Class Reference final
Container class for all available assets.
#include <assetmanager.h>
Public Member Functions
AssetManager (qtsdl::GuiItemLink *gui_link)
const util::Path & get_asset_dir ()
Return the path where assets are found in.
void set_asset_dir (const util::Path &asset_dir)
Set the asset search path.
void set_engine (Engine *engine)
Set the game engine of this asset manager.
Engine * get_engine () const
Return the engine responsible for this asset manager.
Texture * get_texture (const std::string &name, bool use_metafile=true, bool null_if_missing=false)
Query the Texture for a given filename.
void check_updates ()
Ask the kernel whether there were updates to watched files.
Public Attributes
qtsdl::GuiItemLink * gui_link
Protected Member Functions
std::shared_ptr< Texture > load_texture (const std::string &name, bool use_metafile=true, bool null_if_missing=false)
Create an internal texture handle.
std::shared_ptr< Texture > get_missing_tex ()
Retrieves the texture for missing textures.
Private Member Functions
void clear ()
Private Attributes
Engine * engine
The engine this asset manager is attached to.
util::Path asset_path
The root directory for the available assets.
std::shared_ptr< Texture > missing_tex
The replacement texture for missing textures.
std::unordered_map< std::string, std::shared_ptr< Texture > > textures
Map from texture filename to texture instance ptr.
Detailed Description
Container class for all available assets.
Responsible for loading, providing and updating requested files.
Definition at line 27 of file assetmanager.h.
Constructor & Destructor Documentation
AssetManager()
openage::AssetManager::AssetManager (qtsdl::GuiItemLink * gui_link) explicit
Definition at line 20 of file assetmanager.cpp.
     :
     missing_tex{nullptr},
     gui_link{gui_link} {
 #if WITH_INOTIFY
     // initialize the inotify instance
     this->inotify_fd = inotify_init1(IN_NONBLOCK);
     if (this->inotify_fd < 0) {
         throw Error{MSG(err) << "Failed to initialize inotify!"};
     }
 #endif
 }
Member Function Documentation
check_updates()
void openage::AssetManager::check_updates ()
Ask the kernel whether there were updates to watched files.
Definition at line 133 of file assetmanager.cpp.
{
 #if WITH_INOTIFY
     // buffer for at least 4 inotify events
     char buf[4 * (sizeof(struct inotify_event) + NAME_MAX + 1)];
     ssize_t len;
     while (true) {
         // fetch all events, the kernel won't write "half" structs.
         len = read(this->inotify_fd, buf, sizeof(buf));
         if (len == -1) {
             if (errno == EAGAIN) {
                 // no events, nothing to do.
                 break;
             } else {
                 // something went wrong
                 log::log(WARN << "Failed to read inotify events!");
                 break;
             }
         }
         // process fetched events,
         // the kernel guarantees complete events in the buffer.
         char *ptr = buf;
         while (ptr < buf + len) {
             struct inotify_event *event = (struct inotify_event *)ptr;
             if (event->mask & IN_CLOSE_WRITE) {
                 // \todo this should invoke callback functions
                 this->watch_fds[event->wd]->reload();
             }
             // move the buffer ptr to the next event.
             ptr += sizeof(struct inotify_event) + event->len;
         }
     }
 #endif
 }
References openage::log::log(), and WARN.
Referenced by openage::GameSpecHandle::invalidate().
clear()
void openage::AssetManager::clear () private
Definition at line 185 of file assetmanager.cpp.
{
 #if WITH_INOTIFY
     for (auto& watch_fd : this->watch_fds) {
         int result = inotify_rm_watch(this->inotify_fd, watch_fd.first);
         if (result < 0) {
             log::log(WARN << "Failed to remove inotify watches");
         }
     }
     this->watch_fds.clear();
 #endif
     this->textures.clear();
 }
References openage::log::log(), openage.testing.testing::result(), textures, and WARN.
Referenced by set_asset_dir().
get_asset_dir()
const util::Path & openage::AssetManager::get_asset_dir ()
Return the path where assets are found in.
Definition at line 35 of file assetmanager.cpp.
{
     return this->asset_path;
 }
References asset_path.
Referenced by openage::GameSpec::initialize(), openage::GameSpec::load_terrain(), and openage::GameSpec::on_gamedata_loaded().
get_engine()
Engine * openage::AssetManager::get_engine () const
Return the engine responsible for this asset manager.
Definition at line 53 of file assetmanager.cpp.
{
     return this->engine;
 }
References engine.
Referenced by openage::GameSpec::on_gamedata_loaded(), openage::Sound::play(), and openage::GameSpecHandle::start_load_job().
get_missing_tex()
std::shared_ptr< Texture > openage::AssetManager::get_missing_tex () protected
Retrieves the texture for missing textures.
Definition at line 172 of file assetmanager.cpp.
{
     // if not loaded, fetch the "missing" texture (big red X).
     if (unlikely(this->missing_tex.get() == nullptr)) {
         this->missing_tex = std::make_shared<Texture>(
             this->asset_path["missing.png"],
             false
         );
     }
     return this->missing_tex;
 }
References asset_path, missing_tex, and unlikely.
Referenced by load_texture().
get_texture()
Texture * openage::AssetManager::get_texture (const std::string & name, bool use_metafile = true, bool null_if_missing = false)
Query the Texture for a given filename.
Parameters
name the asset file name relative to the asset root.
use_metafile load subtexture information from meta file
null_if_missing instead of providing the "missing texture", return nullptr.
Returns
the queried texture handle.
Definition at line 111 of file assetmanager.cpp.
{
     // check whether the requested texture was loaded already
     auto tex_it = this->textures.find(name);
     // the texture was not loaded yet:
     if (tex_it == this->textures.end()) {
         auto tex = this->load_texture(name, use_metafile, null_if_missing);
         if (tex.get() != nullptr) {
             // insert the texture into the map
             this->textures.insert(std::make_pair(name, tex));
         }
         //  and return the texture pointer.
         return tex.get();
     }
     return tex_it->second.get();
 }
References load_texture(), and textures.
Referenced by openage::GameSpec::get_texture(), and openage::GameSpec::load_terrain().
load_texture()
std::shared_ptr< Texture > openage::AssetManager::load_texture (const std::string & name, bool use_metafile = true, bool null_if_missing = false) protected
Create an internal texture handle.
Definition at line 58 of file assetmanager.cpp.
{
     // the texture to be associated with the given filename
     std::shared_ptr<Texture> tex;
     util::Path tex_path = this->asset_path[name];
     // try to open the texture filename.
     if (not tex_path.is_file()) {
         // \todo add/fetch inotify watch on the containing folder
         // to display the tex as soon at it exists.
         if (null_if_missing) {
             return nullptr;
         }
         else {
             // return the big X texture instead
             tex = this->get_missing_tex();
         }
     }
     else {
         // create the texture!
         tex = std::make_shared<Texture>(tex_path, use_metafile);
 #if WITH_INOTIFY
         std::string native_path = tex_path.resolve_native_path();
         if (native_path.size() > 0) {
             // create inotify update trigger for the requested file
             // \todo let util::Path do the file watching
             int wd = inotify_add_watch(
                 this->inotify_fd,
                 native_path.c_str(),
                 IN_CLOSE_WRITE
             );
             if (wd < 0) {
                 log::log(WARN << "Failed to add inotify watch for " << native_path);
             } else {
                 this->watch_fds[wd] = tex;
             }
         }
 #endif
     }
     // pass back the shared_ptr<Texture>
     return tex;
 }
References asset_path, get_missing_tex(), openage::util::Path::is_file(), openage::log::log(), openage::util::Path::resolve_native_path(), and WARN.
Referenced by get_texture().
set_asset_dir()
void openage::AssetManager::set_asset_dir (const util::Path & asset_dir)
Set the asset search path.
Definition at line 40 of file assetmanager.cpp.
{
     if (this->asset_path != new_path) {
         this->asset_path = new_path;
         this->clear();
     }
 }
References asset_path, and clear().
Referenced by openage::gui::AssetManagerLink::set_asset_dir().
set_engine()
void openage::AssetManager::set_engine (Engine * engine)
Set the game engine of this asset manager.
Called from QML.
Definition at line 48 of file assetmanager.cpp.
{
     this->engine = engine;
 }
References engine.
Referenced by openage::gui::AssetManagerLink::set_engine().
Member Data Documentation
asset_path
util::Path openage::AssetManager::asset_path private
The root directory for the available assets.
Definition at line 93 of file assetmanager.h.
Referenced by get_asset_dir(), get_missing_tex(), load_texture(), and set_asset_dir().
engine
Engine* openage::AssetManager::engine private
The engine this asset manager is attached to.
Definition at line 88 of file assetmanager.h.
Referenced by get_engine(), and set_engine().
gui_link
qtsdl::GuiItemLink* openage::AssetManager::gui_link
Definition at line 119 of file assetmanager.h.
missing_tex
std::shared_ptr<Texture> openage::AssetManager::missing_tex private
The replacement texture for missing textures.
Definition at line 98 of file assetmanager.h.
Referenced by get_missing_tex().
textures
std::unordered_map<std::string, std::shared_ptr<Texture> > openage::AssetManager::textures private
Map from texture filename to texture instance ptr.
Definition at line 103 of file assetmanager.h.
Referenced by clear(), and get_texture().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/assetmanager.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/assetmanager.cpp