openage: qtsdl::GuiItemBase Class Reference
qtsdl::GuiItemBase Class Reference
#include <gui_item.h>
Public Member Functions
virtual ~GuiItemBase ()
Public Member Functions inherited from qtsdl::DeferredInitialConstantPropertyValues
DeferredInitialConstantPropertyValues ()
virtual ~DeferredInitialConstantPropertyValues ()
Is virtual to be able to catch the error when non-persistent item uses liveReloadTag.
void apply_static_properties ()
Execute saved static properties assignments (for newly created cores).
void clear_static_properties ()
Clear saved static properties assignments (for cores that existed before the GUI reload).
bool is_init_over () const
Protected Attributes
GameLogicCaller game_logic_caller
std::function< std::unique_ptr< PersistentCoreHolderBase >)> instantiate_core_func
std::function< void(PersistentCoreHolderBase *, const QString &)> do_adopt_core_func
std::function< void()> on_core_adopted_func
Protected Attributes inherited from qtsdl::DeferredInitialConstantPropertyValues
bool init_over
std::vector< std::function< void()> > static_properties_assignments
Private Member Functions
std::unique_ptr< PersistentCoreHolderBase > instantiate_core ()
Creates and returns a core object inside a holder.
void adopt_core (PersistentCoreHolderBase *holder, const QString &tag)
Attaches to a core object.
void do_adopt_core (PersistentCoreHolderBase *holder, const QString &tag)
virtual void on_core_adopted ()
void set_game_logic_callback (GuiCallback *game_logic_callback)
Set up signal to be able to run code in the game logic thread.
Friends
class GuiLiveReloader
class GuiSubtreeImpl
template<typename >
class GuiItemMethods
template<typename >
class GuiItemCoreInstantiator
template<typename >
class GuiItemListModel
Detailed Description
Definition at line 68 of file gui_item.h.
Constructor & Destructor Documentation
~GuiItemBase()
virtual qtsdl::GuiItemBase::~GuiItemBase () inline virtual
Definition at line 70 of file gui_item.h.
{
     }
Member Function Documentation
adopt_core()
void qtsdl::GuiItemBase::adopt_core (PersistentCoreHolderBase * holder, const QString & tag) inline private
Attaches to a core object.
Definition at line 96 of file gui_item.h.
{
         this->do_adopt_core(holder, tag);
         if (this->on_core_adopted_func)
             this->on_core_adopted_func();
         this->on_core_adopted();
     }
References do_adopt_core(), on_core_adopted(), and on_core_adopted_func.
do_adopt_core()
void qtsdl::GuiItemBase::do_adopt_core (PersistentCoreHolderBase * holder, const QString & tag) inline private
Definition at line 105 of file gui_item.h.
{
         this->do_adopt_core_func(holder, tag);
     }
References do_adopt_core_func.
Referenced by adopt_core().
instantiate_core()
std::unique_ptr<PersistentCoreHolderBase> qtsdl::GuiItemBase::instantiate_core () inline private
Creates and returns a core object inside a holder.
Definition at line 89 of file gui_item.h.
{
         return this->instantiate_core_func();
     }
References instantiate_core_func.
on_core_adopted()
virtual void qtsdl::GuiItemBase::on_core_adopted () inline private virtual
Reimplemented in openage::gui::GameControlLink, openage::gui::GameSpecLink, openage::gui::GameMainLink, and openage::gui::OutputModeLink.
Definition at line 109 of file gui_item.h.
{
     }
Referenced by adopt_core().
set_game_logic_callback()
void qtsdl::GuiItemBase::set_game_logic_callback (GuiCallback * game_logic_callback) inline private
Set up signal to be able to run code in the game logic thread.
Definition at line 115 of file gui_item.h.
{
         this->game_logic_caller.set_game_logic_callback(game_logic_callback);
     }
References game_logic_caller, and qtsdl::GameLogicCaller::set_game_logic_callback().
Referenced by qtsdl::GuiSubtreeImpl::init_persistent_items().
Friends And Related Function Documentation
GuiItemCoreInstantiator
template<typename > friend class GuiItemCoreInstantiator friend
Definition at line 81 of file gui_item.h.
GuiItemListModel
template<typename > friend class GuiItemListModel friend
Definition at line 84 of file gui_item.h.
GuiItemMethods
template<typename > friend class GuiItemMethods friend
Definition at line 78 of file gui_item.h.
GuiLiveReloader
friend class GuiLiveReloader friend
Definition at line 74 of file gui_item.h.
GuiSubtreeImpl
friend class GuiSubtreeImpl friend
Definition at line 75 of file gui_item.h.
Member Data Documentation
do_adopt_core_func
std::function<void(PersistentCoreHolderBase*, const QString&)> qtsdl::GuiItemBase::do_adopt_core_func protected
Definition at line 122 of file gui_item.h.
Referenced by do_adopt_core().
game_logic_caller
GameLogicCaller qtsdl::GuiItemBase::game_logic_caller protected
Definition at line 120 of file gui_item.h.
Referenced by qtsdl::GuiItemMethods< GameSpecLink >::assign_while_catching_constant_properies_inits(), qtsdl::GuiItemMethods< GameSpecLink >::i(), and set_game_logic_callback().
instantiate_core_func
std::function<std::unique_ptr<PersistentCoreHolderBase>)> qtsdl::GuiItemBase::instantiate_core_func protected
Definition at line 121 of file gui_item.h.
Referenced by instantiate_core().
on_core_adopted_func
std::function<void()> qtsdl::GuiItemBase::on_core_adopted_func protected
Definition at line 123 of file gui_item.h.
Referenced by adopt_core().
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/guisys/link/gui_item.h