openage: openage::LivingProducer Class Reference
openage::LivingProducer Class Reference
temporary class – will be replaced with nyan system in future Stores graphics and attributes for a single unit type in aoe living units are derived from objects
#include <producer.h>
Public Member Functions
LivingProducer (const Player &owner, const GameSpec &spec, const gamedata::living_unit *)
virtual ~LivingProducer ()
void initialise (Unit *, Player &) override
Initialize units attributes to this type spec.
TerrainObject * place (Unit *, std::shared_ptr< Terrain >, coord::phys3) const override
set unit in place – return if placement was successful
Public Member Functions inherited from openage::MovableProducer
MovableProducer (const Player &owner, const GameSpec &spec, const gamedata::projectile_unit *)
virtual ~MovableProducer ()
Public Member Functions inherited from openage::ObjectProducer
ObjectProducer (const Player &owner, const GameSpec &spec, const gamedata::unit_object *ud)
virtual ~ObjectProducer ()
int id () const override
gets the unique id of this unit type
int parent_id () const override
gets the parent id of this unit type which is used for village base and gather types
std::string name () const override
gets the name of the unit type being produced
Public Member Functions inherited from openage::UnitType
UnitType ()
bool match (class Unit *)
the unit must have either same class or id as this
UnitType (const Player &owner)
virtual ~UnitType ()
virtual void reinitialise (Unit *, Player &)
Initialize units shared attributes only to this type spec.
bool operator== (const UnitType &other) const
compare if two types are the same
bool operator!= (const UnitType &other) const
UnitTexture * default_texture ()
Get a default texture for HUD drawing.
TerrainObject * place_beside (Unit *, TerrainObject const *) const
similar to place but places adjacent to an existing object
void copy_attributes (Unit *unit) const
copy attributes of this unit type to a new unit instance
void upgrade (const std::shared_ptr< AttributeContainer > &attr)
upgrades one attribute of this unit type
UnitType * parent_type () const
returns type matching parent_id()
Private Attributes
const gamedata::living_unit unit_data
Additional Inherited Members
Public Attributes inherited from openage::UnitType
const Player & owner
the player who owns this unit type
std::vector< UnitReference > instances
all instances of units made from this unit type this could allow all units of a type to be upgraded
std::vector< std::shared_ptr< UnitAbility > > type_abilities
abilities given to all instances
Attributes default_attributes
default attributes which get copied to new units
ResourceCost cost
The cost of the unit.
int have_limit
The max number of units of this type that a player can have at an instance.
int had_limit
The max number of units of this type that a player can create.
graphic_set graphics
The set of graphics used for this type.
coord::tile_delta foundation_size
the square dimensions of the placement
gamedata::unit_classes unit_class
raw game data class of this unit instance
Protected Attributes inherited from openage::MovableProducer
const gamedata::projectile_unit unit_data
UnitTexture * moving
UnitTexture * attacking
const Sound * on_move
const Sound * on_attack
int projectile
Protected Attributes inherited from openage::ObjectProducer
const GameSpec & dataspec
const gamedata::unit_object unit_data
bool decay
decaying objects have a timed lifespan
const Sound * on_create
Sound id played when object is created or destroyed.
const Sound * on_destroy
std::shared_ptr< Texture > terrain_outline
std::shared_ptr< UnitTexture > default_tex
int dead_unit_id
Detailed Description
temporary class – will be replaced with nyan system in future Stores graphics and attributes for a single unit type in aoe living units are derived from objects
Definition at line 91 of file producer.h.
Constructor & Destructor Documentation
LivingProducer()
openage::LivingProducer::LivingProducer (const Player & owner, const GameSpec & spec, const gamedata::living_unit * ud)
Definition at line 438 of file producer.cpp.
     :
     MovableProducer(owner, spec, ud),
     unit_data(*ud) {
     // extra abilities
     this->type_abilities.emplace_back(std::make_shared<GarrisonAbility>(this->on_move));
 }
References openage::MovableProducer::on_move, openage::owner, and openage::UnitType::type_abilities.
~LivingProducer()
openage::LivingProducer::~LivingProducer () virtual
Definition at line 447 of file producer.cpp.
 {}
Member Function Documentation
initialise()
void openage::LivingProducer::initialise (Unit * , Player &) override virtual
Initialize units attributes to this type spec.
This can be called using existing units to modify type Ensure that the unit has been placed before seting the units type
Todo:
make const
Reimplemented from openage::MovableProducer.
Definition at line 449 of file producer.cpp.
{
     /*
      * call base function
      */
     MovableProducer::initialise(unit, player);
     // population of 1 for all movable units
     if (this->unit_data.unit_class != gamedata::unit_classes::SHEEP) {
         unit->add_attribute(std::make_shared<Attribute<attr_type::population>>(1, 0));
     }
     // add worker attributes
     if (this->unit_data.unit_class == gamedata::unit_classes::CIVILIAN) {
         unit->add_attribute(std::make_shared<Attribute<attr_type::worker>>());
         unit->add_attribute(std::make_shared<Attribute<attr_type::resource>>());
         unit->add_attribute(std::make_shared<Attribute<attr_type::multitype>>());
         // add graphic ids for resource actions
         auto &worker_attr = unit->get_attribute<attr_type::worker>();
         worker_attr.capacity = 10.0;
         worker_attr.gather_rate[game_resource::wood] = 0.002;
         worker_attr.gather_rate[game_resource::food] = 0.002;
         worker_attr.gather_rate[game_resource::gold] = 0.002;
         worker_attr.gather_rate[game_resource::stone] = 0.002;
         auto &multitype_attr = unit->get_attribute<attr_type::multitype>();
         // currently not sure where the game data keeps these values
         // \todo PREY_ANIMAL SEA_FISH
         if (this->parent_id() == 83) {
             // male graphics
             multitype_attr.types[gamedata::unit_classes::CIVILIAN] = this->parent_type(); // get default villager
             multitype_attr.types[gamedata::unit_classes::BUILDING] = this->owner.get_type(156); // builder 118
             multitype_attr.types[gamedata::unit_classes::BERRY_BUSH] = this->owner.get_type(120); // forager
             multitype_attr.types[gamedata::unit_classes::SHEEP] = this->owner.get_type(592); // sheperd
             multitype_attr.types[gamedata::unit_classes::TREES] = this->owner.get_type(123); // woodcutter
             multitype_attr.types[gamedata::unit_classes::GOLD_MINE] = this->owner.get_type(579); // gold miner
             multitype_attr.types[gamedata::unit_classes::STONE_MINE] = this->owner.get_type(124); // stone miner
         }
         else {
             // female graphics
             multitype_attr.types[gamedata::unit_classes::CIVILIAN] = this->parent_type(); // get default villager
             multitype_attr.types[gamedata::unit_classes::BUILDING] = this->owner.get_type(222); // builder 212
             multitype_attr.types[gamedata::unit_classes::BERRY_BUSH] = this->owner.get_type(354); // forager
             multitype_attr.types[gamedata::unit_classes::SHEEP] = this->owner.get_type(590); // sheperd
             multitype_attr.types[gamedata::unit_classes::TREES] = this->owner.get_type(218); // woodcutter
             multitype_attr.types[gamedata::unit_classes::GOLD_MINE] = this->owner.get_type(581); // gold miner
             multitype_attr.types[gamedata::unit_classes::STONE_MINE] = this->owner.get_type(220); // stone miner
         }
         unit->give_ability(std::make_shared<GatherAbility>(this->on_attack));
         unit->give_ability(std::make_shared<BuildAbility>(this->on_attack));
         unit->give_ability(std::make_shared<RepairAbility>(this->on_attack));
     }
     else if (this->unit_data.unit_class == gamedata::unit_classes::FISHING_BOAT) {
         unit->add_attribute(std::make_shared<Attribute<attr_type::worker>>());
         unit->add_attribute(std::make_shared<Attribute<attr_type::resource>>());
         // add fishing abilites
         auto &worker_attr = unit->get_attribute<attr_type::worker>();
         worker_attr.capacity = 15.0;
         worker_attr.gather_rate[game_resource::food] = 0.002;
         unit->give_ability(std::make_shared<GatherAbility>(this->on_attack));
     }
 }
References openage::Unit::add_attribute(), openage::food, openage::Unit::get_attribute(), openage::Player::get_type(), openage::Unit::give_ability(), openage::gold, openage::MovableProducer::initialise(), openage::multitype, openage::MovableProducer::on_attack, openage::UnitType::owner, openage::ObjectProducer::parent_id(), openage::UnitType::parent_type(), openage::stone, unit_data, openage::wood, and openage::worker.
place()
TerrainObject * openage::LivingProducer::place (Unit * , std::shared_ptr< Terrain > , coord::phys3) const override virtual
set unit in place – return if placement was successful
This should be used when initially creating a unit or when a unit is ungarrsioned from a building or object
Todo:
make const
Reimplemented from openage::MovableProducer.
Definition at line 518 of file producer.cpp.
{
     return MovableProducer::place(unit, terrain, init_pos);
 }
References openage::MovableProducer::place().
Member Data Documentation
unit_data
const gamedata::living_unit openage::LivingProducer::unit_data private
Definition at line 100 of file producer.h.
Referenced by initialise().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/producer.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/producer.cpp