openage: openage::log::LogSink Class Reference
openage::log::LogSink Class Reference abstract
Abstract base for classes that - in one way or an other - print log messages.
#include <logsink.h>
Public Member Functions
LogSink ()
virtual ~LogSink ()
void set_loglevel (level loglevel)
Private Member Functions
virtual void output_log_message (const struct message &msg, class LogSource *source)=0
Called internally by put_log_message if a message is accepted.
Private Attributes
level loglevel
Friends
class LogSinkList
Detailed Description
Abstract base for classes that - in one way or an other - print log messages.
Instances of this class are automatically added to LogSource::global_sink_list vector by their constructors (and removed by their destructors).
Definition at line 20 of file logsink.h.
Constructor & Destructor Documentation
LogSink()
openage::log::LogSink::LogSink ()
Definition at line 13 of file logsink.cpp.
                  {
     LogSinkList::instance().add(this);
     this->set_loglevel(level::dbg);
 }
References openage::log::LogSinkList::add(), openage::log::dbg(), openage::log::LogSinkList::instance(), and set_loglevel().
~LogSink()
openage::log::LogSink::~LogSink () virtual
Definition at line 20 of file logsink.cpp.
                   {
     LogSinkList::instance().remove(this);
 }
References openage::log::LogSinkList::instance(), and openage::log::LogSinkList::remove().
Member Function Documentation
output_log_message()
virtual void openage::log::LogSink::output_log_message (const struct message & msg, class LogSource * source) private pure virtual
Called internally by put_log_message if a message is accepted.
set_loglevel()
void openage::log::LogSink::set_loglevel (level loglevel)
Todo:
Add iptables-like chains that decide whether a message will be logged, depending on msg.info, logger id, thread id, etc.
This member variable is only a make-shift solution with obvious limitations.
Definition at line 25 of file logsink.cpp.
{
     this->loglevel = loglevel;
     LogSinkList::instance().loglevel_changed();
 }
References openage::log::LogSinkList::instance(), loglevel, and openage::log::LogSinkList::loglevel_changed().
Referenced by LogSink(), and openage::log::set_level().
Friends And Related Function Documentation
LogSinkList
friend class LogSinkList friend
Definition at line 43 of file logsink.h.
Member Data Documentation
loglevel
level openage::log::LogSink::loglevel private
Definition at line 35 of file logsink.h.
Referenced by set_loglevel().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/log/logsink.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/log/logsink.cpp