openage: openage.util.fslike.filecollection.FileCollection Class Reference
openage.util.fslike.filecollection.FileCollection Class Reference
FSLikeObject that holds several individual files.
Public Member Functions
def __init__ (self)
def root (self)
Returns a path-like object for the root of this file system.
def get_direntries (self, parts=None, create=False)
Fetches the fileentries, subdirentries tuple for the given dir.
def add_fileentry (self, parts, fileentry)
Adds a file entry (and parent directory entries, if needed).
def get_fileentry (self, parts)
Gets a file entry.
def open_r (self, parts)
Shall return a BufferedReader for the given file ("mode 'rb'").
def open_w (self, parts)
Shall return a BufferedWriter for the given file ("mode 'wb'").
def list (self, parts)
Shall yield the entry names of the given directory.
def filesize (self, parts)
def mtime (self, parts)
def mkdirs (self, parts)
Shall ensure that the directory exists.
def rmdir (self, parts)
Shall remove an empty directory.
def unlink (self, parts)
Shall remove a single file.
def touch (self, parts)
Shall create the file or update its timestamp.
def rename (self, srcparts, tgtparts)
Shall rename a file or directory to the target name.
def is_file (self, parts)
def is_dir (self, parts)
def writable (self, parts)
def watch (self, parts, callback)
def poll_watches (self)
Public Member Functions inherited from openage.util.fslike.abstract.FSLikeObject
def pretty (self, parts)
pretty-format a path in this filesystem like object.
def open_rw (self, parts)
Shall return a BufferedWriter for the given file ("mode 'r+'").
def open_a (self, parts)
Shall return a BufferedWriter for the given file ("mode 'a'").
def open_ar (self, parts)
Shall return a BufferedWriter for the given file ("mode 'a+'").
def exists (self, parts)
Test if the parts are a file or a directory.
def resolve_r (self, parts)
def resolve_w (self, parts)
Returns a new flattened path.
def get_native_path (self, parts)
Public Attributes
rootentries
Detailed Description
FSLikeObject that holds several individual files.
Uses lambdas to access files somewhere else on the fly.
Definition at line 22 of file filecollection.py.
Constructor & Destructor Documentation
__init__()
def openage.util.fslike.filecollection.FileCollection.__init__ (self)
Definition at line 23 of file filecollection.py.
         # stores lambdas to access the files
         # {name: open_r, open_w, size, mtime}, {name: subdir}
         self.rootentries = OrderedDict(), OrderedDict()
     @property
     def root(self):
Member Function Documentation
add_fileentry()
def openage.util.fslike.filecollection.FileCollection.add_fileentry (self, parts, fileentry)
Adds a file entry (and parent directory entries, if needed).
   This method should not be called directly; instead, use the
   add_file method of Path objects that were obtained from this.
   fileentry must be open_r, open_w, size, mtime.
Definition at line 70 of file filecollection.py.
             raise IsADirectoryError("FileCollection.root is a directory")
         entries = self.get_direntries(parts[:-1], create=True)
         name = parts[-1]
         if name in entries[1]:
             raise IsADirectoryError(b"/".join(parts))
         entries[0][name] = fileentry
     def get_fileentry(self, parts):
         """
References openage.util.fslike.filecollection.FileCollection.get_direntries().
filesize()
def openage.util.fslike.filecollection.FileCollection.filesize (self, parts)
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 128 of file filecollection.py.
         if filesize is None:
             return None
         return filesize()
     def mtime(self, parts):
         _, _, _, mtime = self.get_fileentry(parts)
References openage.util.fslike.filecollection.FileCollection.get_fileentry().
get_direntries()
def openage.util.fslike.filecollection.FileCollection.get_direntries (self, parts = None, create = False)
Fetches the fileentries, subdirentries tuple for the given dir.
   If create == False, raises FileNotFoundError if the directory doesn't
   exist.
   Helper method for internal use.
Definition at line 42 of file filecollection.py.
             parts = []
         entries = self.rootentries
         for idx, subdir in enumerate(parts):
             if subdir not in entries[1]:
                 if create:
                     if subdir in entries[0]:
                         raise FileExistsError(b"/".join(parts[:idx + 1]))
                     entries[1][subdir] = OrderedDict(), OrderedDict()
                 else:
                     raise FileNotFoundError(
                         "No such directory: " +
                         b"/".join(parts[:idx + 1]).decode(errors='replace'))
             entries = entries[1][subdir]
         return entries
     def add_fileentry(self, parts, fileentry):
         """
References openage.util.fslike.filecollection.FileCollection.rootentries.
Referenced by openage.util.fslike.filecollection.FileCollection.add_fileentry(), openage.util.fslike.filecollection.FileCollection.get_fileentry(), openage.util.fslike.filecollection.FileCollection.is_dir(), openage.util.fslike.filecollection.FileCollection.list(), openage.util.fslike.filecollection.FileCollection.mkdirs(), openage.util.fslike.filecollection.FileCollection.rmdir(), and openage.util.fslike.filecollection.FileCollection.unlink().
get_fileentry()
def openage.util.fslike.filecollection.FileCollection.get_fileentry (self, parts)
Gets a file entry.
Helper method for internal use.
   Returns open_r, open_w, size, mtime
Definition at line 87 of file filecollection.py.
             raise IsADirectoryError(
                 "FileCollection.root is a directory")
         entries = self.get_direntries(parts[:-1])
         name = parts[-1]
         if name in entries[1]:
             raise IsADirectoryError(b"/".join(parts))
         if name not in entries[0]:
             raise FileNotFoundError(b"/".join(parts))
         return entries[0][name]
     def open_r(self, parts):
         open_r, _, _, _ = self.get_fileentry(parts)
References openage.util.fslike.filecollection.FileCollection.get_direntries().
Referenced by openage.util.fslike.filecollection.FileCollection.filesize(), openage.util.fslike.filecollection.FileCollection.is_file(), openage.util.fslike.filecollection.FileCollection.mtime(), openage.util.fslike.filecollection.FileCollection.open_r(), openage.util.fslike.filecollection.FileCollection.open_w(), and openage.util.fslike.filecollection.FileCollection.writable().
is_dir()
def openage.util.fslike.filecollection.FileCollection.is_dir (self, parts)
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 196 of file filecollection.py.
             self.get_direntries(parts)
             return True
         except IOError:
             return False
     def writable(self, parts):
         try:
References openage.util.fslike.filecollection.FileCollection.get_direntries().
Referenced by openage.util.fslike.path.Path.removerecursive().
is_file()
def openage.util.fslike.filecollection.FileCollection.is_file (self, parts)
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 189 of file filecollection.py.
             self.get_fileentry(parts)
             return True
         except IOError:
             return False
     def is_dir(self, parts):
         try:
References openage.util.fslike.filecollection.FileCollection.get_fileentry().
list()
def openage.util.fslike.filecollection.FileCollection.list (self, parts)
Shall yield the entry names of the given directory.
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 122 of file filecollection.py.
         yield from subdirs
         yield from fileentries
     def filesize(self, parts):
         _, _, filesize, _ = self.get_fileentry(parts)
References openage.util.fslike.filecollection.FileCollection.get_direntries().
mkdirs()
def openage.util.fslike.filecollection.FileCollection.mkdirs (self, parts)
Shall ensure that the directory exists.
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 144 of file filecollection.py.
     def rmdir(self, parts):
         if not parts:
References openage.util.fslike.filecollection.FileCollection.get_direntries().
mtime()
def openage.util.fslike.filecollection.FileCollection.mtime (self, parts)
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 136 of file filecollection.py.
         if mtime is None:
             return None
         return mtime()
     def mkdirs(self, parts):
         self.get_direntries(parts, create=True)
References openage.util.fslike.filecollection.FileCollection.get_fileentry().
open_r()
def openage.util.fslike.filecollection.FileCollection.open_r (self, parts)
Shall return a BufferedReader for the given file ("mode 'rb'").
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 104 of file filecollection.py.
         if open_r is None:
             raise UnsupportedOperation(
                 "not readable: " +
                 b"/".join(parts).decode(errors='replace'))
         return open_r()
     def open_w(self, parts):
         _, open_w, _, _ = self.get_fileentry(parts)
References openage.util.fslike.filecollection.FileCollection.get_fileentry().
open_w()
def openage.util.fslike.filecollection.FileCollection.open_w (self, parts)
Shall return a BufferedWriter for the given file ("mode 'wb'").
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 114 of file filecollection.py.
         if open_w is None:
             raise UnsupportedOperation(
                 "not writable: " +
                 b"/".join(parts).decode(errors='replace'))
     def list(self, parts):
         fileentries, subdirs = self.get_direntries(parts)
References openage.util.fslike.filecollection.FileCollection.get_fileentry().
poll_watches()
def openage.util.fslike.filecollection.FileCollection.poll_watches (self)
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 216 of file filecollection.py.
 class FileCollectionPath(Path):
     """
rename()
def openage.util.fslike.filecollection.FileCollection.rename (self, srcparts, tgtparts)
Shall rename a file or directory to the target name.
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 186 of file filecollection.py.
     def is_file(self, parts):
         try:
rmdir()
def openage.util.fslike.filecollection.FileCollection.rmdir (self, parts)
Shall remove an empty directory.
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 147 of file filecollection.py.
             raise UnsupportedOperation("can't rmdir FileCollection.root")
         parent_files, parent_dirs = self.get_direntries(parts[:-1])
         name = parts[-1]
         if name in parent_files:
             raise NotADirectoryError(b'/'.join(parts))
         try:
             files, subdirs = parent_dirs[name]
         except KeyError:
             raise FileNotFoundError(b'/'.join(parts)) from None
         if files or subdirs:
             raise IOError("Directory not empty: " +
                           b'/'.join(parts).decode(errors='replace'))
         del parent_dirs[name]
     def unlink(self, parts):
         if not parts:
References openage.util.fslike.filecollection.FileCollection.get_direntries().
Referenced by openage.util.fslike.path.Path.removerecursive().
root()
def openage.util.fslike.filecollection.FileCollection.root (self)
Returns a path-like object for the root of this file system.
   This is the main interface that is used normally.
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 31 of file filecollection.py.
     def get_direntries(self, parts=None, create=False):
         """
touch()
def openage.util.fslike.filecollection.FileCollection.touch (self, parts)
Shall create the file or update its timestamp.
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 183 of file filecollection.py.
     def rename(self, srcparts, tgtparts):
         raise UnsupportedOperation("FileCollection.rename")
unlink()
def openage.util.fslike.filecollection.FileCollection.unlink (self, parts)
Shall remove a single file.
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 168 of file filecollection.py.
             raise IsADirectoryError("FileCollection.root")
         parent_files, parent_dirs = self.get_direntries(parts[:-1])
         name = parts[-1]
         if name in parent_dirs:
             raise IsADirectoryError(b'/'.join(parts))
         try:
             del parent_files[name]
         except KeyError:
             raise FileNotFoundError(b'/'.join(parts)) from None
     def touch(self, parts):
         raise UnsupportedOperation("FileCollection.touch")
References openage.util.fslike.filecollection.FileCollection.get_direntries().
Referenced by openage.util.fslike.path.Path.removerecursive().
watch()
def openage.util.fslike.filecollection.FileCollection.watch (self, parts, callback)
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 212 of file filecollection.py.
         return False
     def poll_watches(self):
         del self  # unused
writable()
def openage.util.fslike.filecollection.FileCollection.writable (self, parts)
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 203 of file filecollection.py.
             _, open_w, _, _ = self.get_fileentry(parts)
             return open_w is not None
         except IOError:
             # generally, directories are not writable,
             # though some of the existing files inside might be.
             return False
     def watch(self, parts, callback):
         del self, parts, callback  # unused
References openage.util.fslike.filecollection.FileCollection.get_fileentry().
Member Data Documentation
rootentries
openage.util.fslike.filecollection.FileCollection.rootentries
Definition at line 28 of file filecollection.py.
Referenced by openage.util.fslike.filecollection.FileCollection.get_direntries().
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/openage/util/fslike/filecollection.py