openage: openage::input::ActionManager Class Reference
openage::input::ActionManager Class Reference
The action manager manages all the actions allow creation, access information and equality.
#include <action.h>
Public Member Functions
ActionManager (InputManager *input_manager, cvar::CVarManager *cvar_manager)
action_t get (const std::string &type)
std::string get_name (const action_t action)
bool is (const std::string &type, const action_t action)
Private Member Functions
bool create (const std::string &type)
Private Attributes
std::unordered_map< std::string, action_t > actions
std::unordered_map< action_t, std::string > reverse_map
InputManager *const input_manager
cvar::CVarManager *const cvar_manager
action_t next_action_id = 0
Detailed Description
The action manager manages all the actions allow creation, access information and equality.
Definition at line 36 of file action.h.
Constructor & Destructor Documentation
ActionManager()
openage::input::ActionManager::ActionManager (InputManager * input_manager, cvar::CVarManager * cvar_manager)
Definition at line 104 of file action.cpp.
     :
     input_manager{input_manager},
     cvar_manager{cvar_manager} {
     this->create("UNDEFINED");
     for (auto &type : DEFAULT_ACTIONS) {
         this->create(type);
     }
 } // anonymous namespace
References input_manager.
Member Function Documentation
create()
bool openage::input::ActionManager::create (const std::string & type) private
Definition at line 117 of file action.cpp.
{
     if (this->actions.find(type) != this->actions.end()) {
         // that action is already in the list. fail.
         // \todo throw an exception instead?
         // for now, just print a warning log message
         log::log(WARN << "can not create action "
                   << util::repr(type) << ": already exists");
         return false;
     }
     action_t action_id = this->next_action_id++;
     this->reverse_map[action_id] = type;
     this->actions[type] = action_id;
     // and the corresponding cvar, which modifies the action bindings
     // \todo this has nothing to do with the actionmanager!
     //       remove the cvarmanager-access here!
     this->cvar_manager->create(type, std::make_pair(
         // the cvar's getter
         [type, this]() {
             return this->input_manager->get_bind(type);
         },
         // the cvar's setter
         [type, this](const std::string &value) {
             this->input_manager->set_bind(value.c_str(), type);
         }
     ));
     return true;
 }
References actions, openage::cvar::CVarManager::create(), cvar_manager, openage::input::InputManager::get_bind(), input_manager, openage::log::log(), next_action_id, openage::util::repr(), reverse_map, openage::input::InputManager::set_bind(), and WARN.
get()
action_t openage::input::ActionManager::get (const std::string & type)
Definition at line 150 of file action.cpp.
{
     auto it = this->actions.find(type);
     if (it != this->actions.end()) {
         return it->second;
     } else {
         return this->actions.at("UNDEFINED");
     }
 }
References actions.
Referenced by openage::input::InputManager::get_bind(), is(), openage::ActionModeSignals::on_action(), and openage::input::InputManager::set_bind().
get_name()
std::string openage::input::ActionManager::get_name (const action_t action)
Definition at line 160 of file action.cpp.
{
     auto it = this->reverse_map.find(action);
     if (it != this->reverse_map.end()) {
         return it->second;
     } else {
         return "UNDEFINED";
     }
 }
References reverse_map.
Referenced by openage::input::InputManager::active_binds().
is()
bool openage::input::ActionManager::is (const std::string & type, const action_t action)
Definition at line 170 of file action.cpp.
{
     return this->get(type) == action;
 }
References get().
Referenced by openage::input::InputManager::get_bind(), and openage::input::InputManager::set_bind().
Member Data Documentation
actions
std::unordered_map<std::string, action_t> openage::input::ActionManager::actions private
Definition at line 50 of file action.h.
Referenced by create(), and get().
cvar_manager
cvar::CVarManager* const openage::input::ActionManager::cvar_manager private
Definition at line 55 of file action.h.
Referenced by create().
input_manager
InputManager* const openage::input::ActionManager::input_manager private
Definition at line 54 of file action.h.
Referenced by ActionManager(), and create().
next_action_id
action_t openage::input::ActionManager::next_action_id = 0 private
Definition at line 58 of file action.h.
Referenced by create().
reverse_map
std::unordered_map<action_t, std::string> openage::input::ActionManager::reverse_map private
Definition at line 52 of file action.h.
Referenced by create(), and get_name().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/input/action.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/input/action.cpp