openage: openage::util::Quaternion< T > Class Template Reference
openage::util::Quaternion< T > Class Template Reference
Implements Quaternions to represent 3d rotations.
#include <quaternion.h>
Public Types
using this_type = Quaternion< T >
using type = T
Public Member Functions
Quaternion (T w, T x, T y, T z)
Quaternion ()
Create a identity quaternion.
template<size_t N = 4>
Quaternion (const Matrix< N, N, T > &mat)
Constructs a quaternion from a rotation matrix.
Quaternion (const this_type &other)=default
Quaternion (this_type &&other)=default
Quaternion & operator= (const this_type &other)=default
Quaternion & operator= (this_type &&other)=default
virtual ~Quaternion ()=default
T dot (const this_type &o) const
Perform a dot product with another quaternion.
T norm () const
Calculate the length of the quaternion.
T normalize ()
Ensure that the quaternion's length equals 1.
this_type normalized () const
Return the normalized version of this quaternion.
void inverse ()
Inverted the quaternion: Flip the rotation axes and scale by inverse sum of all components squared.
this_type inversed () const
Return the inverted quaternion.
void conjugate ()
Conjugate the quaternion by additive inverting the x, y and z components.
this_type conjugated () const
Return the conjugated quaternion.
bool equals (const this_type &other, T eps=default_eps) const
Test if the rotation of both quaternions is the same.
bool equals_number (const this_type &other, T eps=default_eps) const
Test if both quaternion store the same numbers.
bool equals_rad (const this_type &other, T rad_eps=default_eps) const
Test rotation equality with another quaternion with given precision in radians.
bool equals_deg (const this_type &other, T deg_eps=default_eps) const
Test rotation equality with another quaternion with given precision in degree.
Matrix3t< T > to_matrix () const
Generate the corresponding rotation matrix.
Vector3t< T > operator * (const Vector3t< T > &vec) const
Transforms a vector by this quaternion.
const this_type & operator+= (const this_type &other)
this_type operator+ (const this_type &other) const
const this_type & operator -= (const this_type &other)
this_type operator - (const this_type &other) const
const this_type & operator *= (const T &fac)
this_type operator * (const T &fac) const
const this_type & operator *= (const this_type &other)
this_type operator * (const this_type &other) const
const this_type & operator/= (const T &fac)
this_type operator/ (const T &fac) const
const this_type operator - () const
bool operator== (const this_type &other) const
bool operator != (const this_type &other) const
Static Public Member Functions
static this_type from_rad (T rad, Vector3t< T > axis)
Create a quaternion from a rotation in radians around a given axis.
static this_type from_deg (T deg, Vector3t< T > axis)
Create a quaternion from a rotation in degree around a given axis.
Static Public Attributes
static constexpr T default_eps = 1e-4
Protected Attributes
T w
Stored quaternion number components.
T x
T y
T z
Friends
std::ostream & operator<< (std::ostream &o, const this_type &q)
Detailed Description
template<typename T>
class openage::util::Quaternion< T >
Implements Quaternions to represent 3d rotations.
The 4 components stores 3 components as rotation axis, and one component as the rotation amount.
This is mainly Ken Shoemake stuff from: http://www.cs.ucr.edu/~vbz/resources/quatut.pdf
Also: From Quaternion to Matrix and Back J.M.P. van Waveren, id Software, 2005
Definition at line 31 of file quaternion.h.
Member Typedef Documentation
this_type
template<typename T > using openage::util::Quaternion< T >::this_type = Quaternion<T>
Definition at line 33 of file quaternion.h.
type
template<typename T > using openage::util::Quaternion< T >::type = T
Definition at line 34 of file quaternion.h.
Constructor & Destructor Documentation
Quaternion() [1/5]
template<typename T > openage::util::Quaternion< T >::Quaternion (T w, T x, T y, T z) inline
Definition at line 38 of file quaternion.h.
         :
         w{w}, x{x}, y{y}, z{z} {}
References openage::util::Quaternion< T >::w.
Quaternion() [2/5]
template<typename T > openage::util::Quaternion< T >::Quaternion () inline
Create a identity quaternion.
Definition at line 45 of file quaternion.h.
         :
         w{1}, x{0}, y{0}, z{0} {}
Quaternion() [3/5]
template<typename T > template<size_t N = 4> openage::util::Quaternion< T >::Quaternion (const Matrix< N, N, T > & mat) inline
Constructs a quaternion from a rotation matrix.
mat is assumed to be a left-matrix: vec_transformed = mat * vec_orig.
mat can be 3x3 or 4x4.
This tries to avoid float-fuckups in near-zero divides by using larger components first: w, then x, y, or z.
trace(mat) >= 0 => |w| > 1/2 => as small as a largest component can be. else: max diagonal entry <=> max (|x|, |y|, |z|) which is larger than |w| and >= 1/2
Definition at line 66 of file quaternion.h.
{
         static_assert(N == 3 or N == 4, "only 3 and 4 dimensional matrices can be converted to a quaternion!");
         T trace = mat.trace();
         T trace_cmp = trace;
         if (N == 4) {
             trace_cmp -= mat[3][3];
         } else {
             trace += 1.0;
         }
         if (trace_cmp > 0) {
             T trace_root = std::sqrt(trace); // = 2w
             this->w = trace_root * 0.5;      // = w
             trace_root = 0.5 / trace_root;   // = 1/4w
             this->x = (mat[2][1] - mat[1][2]) * trace_root;
             this->y = (mat[0][2] - mat[2][0]) * trace_root;
             this->z = (mat[1][0] - mat[0][1]) * trace_root;
         }
         else {
             // determine highest diagonal component:
             int n0 = 0;
             if (mat[1][1] > mat[0][0]) {
                 n0 = 1;
             }
             if (mat[2][2] > mat[n0][n0]) {
                 n0 = 2;
             }
             // following indices to 0, 1, 2
             int next_index[] = {1, 2, 0};
             // indexable pointers
             T *ptrs[] = {&this->x, &this->y, &this->z};
             int n1 = next_index[n0];
             int n2 = next_index[n1];
             // this avoids float fuckups:
             T trace_ordered = (mat[n0][n0] - (mat[n1][n1] + mat[n2][n2]));
             if (N == 4) {
                 trace_ordered += mat[3][3];
             } else {
                 trace_ordered += 1.0;
             }
             T trace_root = std::sqrt(trace_ordered);
             *ptrs[n0] = trace_root * 0.5;   // = w
             trace_root = 0.5 / trace_root;  // = 1/4w
             *ptrs[n1] = (mat[n0][n1] + mat[n1][n0]) * trace_root;
             *ptrs[n2] = (mat[n2][n0] + mat[n0][n2]) * trace_root;
             this->w = (mat[n2][n1] - mat[n1][n2]) * trace_root;
         }
         if (N == 4) {
             // normalize the quaternion by the matrix[3][3] entry
             (*this) *= 1.0 / std::sqrt(mat[3][3]);
         }
     }
References std::sqrt(), openage::util::Matrix< M, N, T >::trace(), openage::util::Quaternion< T >::w, openage::util::Quaternion< T >::x, openage::util::Quaternion< T >::y, and openage::util::Quaternion< T >::z.
Quaternion() [4/5]
template<typename T > openage::util::Quaternion< T >::Quaternion (const this_type & other) default
Quaternion() [5/5]
template<typename T > openage::util::Quaternion< T >::Quaternion (this_type && other) default
~Quaternion()
template<typename T > virtual openage::util::Quaternion< T >::~Quaternion () virtual default
Member Function Documentation
conjugate()
template<typename T > void openage::util::Quaternion< T >::conjugate () inline
Conjugate the quaternion by additive inverting the x, y and z components.
Definition at line 225 of file quaternion.h.
                      {
         this->x = -this->x;
         this->y = -this->y;
         this->z = -this->z;
     }
References openage::util::Quaternion< T >::x, openage::util::Quaternion< T >::y, and openage::util::Quaternion< T >::z.
Referenced by openage::util::Quaternion< T >::conjugated().
conjugated()
template<typename T > this_type openage::util::Quaternion< T >::conjugated () const inline
Return the conjugated quaternion.
Definition at line 234 of file quaternion.h.
{
         this_type q{*this};
         q.conjugate();
         return q;
     }
References openage::util::Quaternion< T >::conjugate().
Referenced by openage::util::Quaternion< T >::inverse().
dot()
template<typename T > T openage::util::Quaternion< T >::dot (const this_type & o) const inline
Perform a dot product with another quaternion.
Definition at line 166 of file quaternion.h.
{
         return this->w * o.w + this->x * o.x + this->y * o.y + this->z * o.z;
     }
References openage::util::Quaternion< T >::w, openage::util::Quaternion< T >::x, openage::util::Quaternion< T >::y, and openage::util::Quaternion< T >::z.
Referenced by openage::util::Quaternion< T >::equals(), openage::util::Quaternion< T >::equals_rad(), openage::util::Quaternion< T >::inverse(), and openage::util::Quaternion< T >::norm().
equals()
template<typename T > bool openage::util::Quaternion< T >::equals (const this_type & other, T eps = default_eps) const inline
Test if the rotation of both quaternions is the same.
Definition at line 243 of file quaternion.h.
{
         T ori = this->dot(other);
         return (1 - (ori*ori)) < eps;
     }
References openage::util::Quaternion< T >::dot().
Referenced by openage::util::tests::quaternion().
equals_deg()
template<typename T > bool openage::util::Quaternion< T >::equals_deg (const this_type & other, T deg_eps = default_eps) const inline
Test rotation equality with another quaternion with given precision in degree.
Definition at line 275 of file quaternion.h.
{
         return this->equals_rad(other, deg_eps * math::RADSPERDEG);
     }
References openage::util::Quaternion< T >::equals_rad(), and openage::math::RADSPERDEG.
Referenced by openage::util::tests::quaternion().
equals_number()
template<typename T > bool openage::util::Quaternion< T >::equals_number (const this_type & other, T eps = default_eps) const inline
Test if both quaternion store the same numbers.
Definition at line 251 of file quaternion.h.
{
         bool result = true;
         (this->w - other.w) < eps or (result = false);
         (this->x - other.x) < eps or (result = false);
         (this->y - other.y) < eps or (result = false);
         (this->z - other.z) < eps or (result = false);
         return result;
     }
References openage.testing.testing::result(), openage::util::Quaternion< T >::w, openage::util::Quaternion< T >::x, openage::util::Quaternion< T >::y, and openage::util::Quaternion< T >::z.
equals_rad()
template<typename T > bool openage::util::Quaternion< T >::equals_rad (const this_type & other, T rad_eps = default_eps) const inline
Test rotation equality with another quaternion with given precision in radians.
Definition at line 264 of file quaternion.h.
{
         T ori = this->dot(other);
         T angle = std::acos((2.0 * (ori * ori)) - 1.0);
         return std::abs(angle) < rad_eps;
     }
References std::abs(), and openage::util::Quaternion< T >::dot().
Referenced by openage::util::Quaternion< T >::equals_deg(), and openage::util::tests::quaternion().
from_deg()
template<typename T > static this_type openage::util::Quaternion< T >::from_deg (T deg, Vector3t< T > axis) inline static
Create a quaternion from a rotation in degree around a given axis.
Definition at line 159 of file quaternion.h.
{
         return this_type::from_rad(deg * math::DEGSPERRAD, axis);
     }
References openage.util.math::DEGSPERRAD, and openage::util::Quaternion< T >::from_rad().
Referenced by openage::util::tests::quaternion().
from_rad()
template<typename T > static this_type openage::util::Quaternion< T >::from_rad (T rad, Vector3t< T > axis) inline static
Create a quaternion from a rotation in radians around a given axis.
Definition at line 145 of file quaternion.h.
{
         T rot = rad / 2.0;
         this_type q{
             std::cos(rot),
             axis[0] * std::sin(rot),
             axis[1] * std::sin(rot),
             axis[2] * std::sin(rot)
         };
         return q;
     }
Referenced by openage::util::Quaternion< T >::from_deg(), and openage::util::tests::quaternion().
inverse()
template<typename T > void openage::util::Quaternion< T >::inverse () inline
Inverted the quaternion: Flip the rotation axes and scale by inverse sum of all components squared.
inv(q)= conj(q)/(w*w + x*x + y*y + z*z)
Definition at line 202 of file quaternion.h.
                    {
         T dot = this->dot(*this);
         if (dot > 0.0) {
             *this = this->conjugated() / dot;
         }
         else {
             throw Error(MSG(err) << "tried inverting " << *this);
         }
     }
References openage::util::Quaternion< T >::conjugated(), openage::util::Quaternion< T >::dot(), openage::log::err(), and MSG.
Referenced by openage::util::Quaternion< T >::inversed().
inversed()
template<typename T > this_type openage::util::Quaternion< T >::inversed () const inline
Return the inverted quaternion.
Definition at line 215 of file quaternion.h.
{
         this_type q{*this};
         q.inverse();
         return q;
     }
References openage::util::Quaternion< T >::inverse().
Referenced by openage::util::tests::quaternion().
norm()
template<typename T > T openage::util::Quaternion< T >::norm () const inline
Calculate the length of the quaternion.
Definition at line 173 of file quaternion.h.
                    {
         return std::sqrt(this->dot(*this));
     }
References openage::util::Quaternion< T >::dot(), and std::sqrt().
Referenced by openage::util::Quaternion< T >::normalize().
normalize()
template<typename T > T openage::util::Quaternion< T >::normalize () inline
Ensure that the quaternion's length equals 1.
Definition at line 180 of file quaternion.h.
                   {
         T len = this->norm();
         *this /= len;
         return len;
     }
References openage::util::Quaternion< T >::norm().
Referenced by openage::util::Quaternion< T >::normalized().
normalized()
template<typename T > this_type openage::util::Quaternion< T >::normalized () const inline
Return the normalized version of this quaternion.
Definition at line 189 of file quaternion.h.
{
         this_type q{*this};
         q.normalize();
         return q;
     }
References openage::util::Quaternion< T >::normalize().
Referenced by openage::util::tests::quaternion().
operator !=()
template<typename T > bool openage::util::Quaternion< T >::operator != (const this_type & other) const inline
Definition at line 418 of file quaternion.h.
{
         return not (*this == other);
     }
operator *() [1/3]
template<typename T > Vector3t<T> openage::util::Quaternion< T >::operator * (const Vector3t< T > & vec) const inline
Transforms a vector by this quaternion.
Definition at line 311 of file quaternion.h.
{
         Vector3t<T> axis{this->x, this->y, this->z};
         Vector3t<T> axis_vec_normal = axis.cross_product(vec);
         Vector3t<T> axis_vec_inplane = axis.cross_product(axis_vec_normal);
         axis_vec_normal *= 2.0f * this->w;
         axis_vec_inplane *= 2.0f;
         return vec + axis_vec_normal + axis_vec_inplane;
     }
References openage::util::Vector< N, T >::cross_product(), openage::util::Quaternion< T >::w, openage::util::Quaternion< T >::x, openage::util::Quaternion< T >::y, and openage::util::Quaternion< T >::z.
operator *() [2/3]
template<typename T > this_type openage::util::Quaternion< T >::operator * (const T & fac) const inline
Definition at line 362 of file quaternion.h.
{
         this_type q{*this};
         q *= fac;
         return q;
     }
operator *() [3/3]
template<typename T > this_type openage::util::Quaternion< T >::operator * (const this_type & other) const inline
Definition at line 386 of file quaternion.h.
{
         this_type q{*this};
         q *= other;
         return q;
     }
operator *=() [1/2]
template<typename T > const this_type& openage::util::Quaternion< T >::operator *= (const T & fac) inline
Definition at line 353 of file quaternion.h.
{
         this->w *= fac;
         this->x *= fac;
         this->y *= fac;
         this->z *= fac;
         return *this;
     }
References openage::util::Quaternion< T >::w, openage::util::Quaternion< T >::x, openage::util::Quaternion< T >::y, and openage::util::Quaternion< T >::z.
operator *=() [2/2]
template<typename T > const this_type& openage::util::Quaternion< T >::operator *= (const this_type & other) inline
Definition at line 368 of file quaternion.h.
{
         T w_new = (this->w * other.w - this->x * other.x -
                    this->y * other.y - this->z * other.z);
         T x_new = (this->w * other.x + this->x * other.w +
                    this->y * other.z - this->z * other.y);
         T y_new = (this->w * other.y - this->x * other.z +
                    this->y * other.w + this->z * other.x);
         T z_new = (this->w * other.z + this->x * other.y -
                    this->y * other.x + this->z * other.w);
         this->w = w_new;
         this->x = x_new;
         this->y = y_new;
         this->z = z_new;
         return *this;
     }
References openage::util::Quaternion< T >::w, openage::util::Quaternion< T >::x, openage::util::Quaternion< T >::y, and openage::util::Quaternion< T >::z.
operator -() [1/2]
template<typename T > this_type openage::util::Quaternion< T >::operator - (const this_type & other) const inline
Definition at line 347 of file quaternion.h.
{
         this_type q{*this};
         q -= other;
         return q;
     }
operator -() [2/2]
template<typename T > const this_type openage::util::Quaternion< T >::operator - () const inline
Definition at line 407 of file quaternion.h.
{
         return this_type{-this->w, -this->x, -this->y, -this->z};
     }
References openage::util::Quaternion< T >::w, openage::util::Quaternion< T >::x, openage::util::Quaternion< T >::y, and openage::util::Quaternion< T >::z.
operator -=()
template<typename T > const this_type& openage::util::Quaternion< T >::operator -= (const this_type & other) inline
Definition at line 338 of file quaternion.h.
{
         this->w -= other.w;
         this->x -= other.x;
         this->y -= other.y;
         this->z -= other.z;
         return *this;
     }
References openage::util::Quaternion< T >::w, openage::util::Quaternion< T >::x, openage::util::Quaternion< T >::y, and openage::util::Quaternion< T >::z.
operator+()
template<typename T > this_type openage::util::Quaternion< T >::operator+ (const this_type & other) const inline
Definition at line 332 of file quaternion.h.
{
         this_type q{*this};
         q += other;
         return q;
     }
operator+=()
template<typename T > const this_type& openage::util::Quaternion< T >::operator+= (const this_type & other) inline
Definition at line 323 of file quaternion.h.
{
         this->w += other.w;
         this->x += other.x;
         this->y += other.y;
         this->z += other.z;
         return *this;
     }
References openage::util::Quaternion< T >::w, openage::util::Quaternion< T >::x, openage::util::Quaternion< T >::y, and openage::util::Quaternion< T >::z.
operator/()
template<typename T > this_type openage::util::Quaternion< T >::operator/ (const T & fac) const inline
Definition at line 401 of file quaternion.h.
{
         this_type q{*this};
         q /= fac;
         return q;
     }
operator/=()
template<typename T > const this_type& openage::util::Quaternion< T >::operator/= (const T & fac) inline
Definition at line 392 of file quaternion.h.
{
         this->w /= fac;
         this->x /= fac;
         this->y /= fac;
         this->z /= fac;
         return *this;
     }
References openage::util::Quaternion< T >::w, openage::util::Quaternion< T >::x, openage::util::Quaternion< T >::y, and openage::util::Quaternion< T >::z.
operator=() [1/2]
template<typename T > Quaternion& openage::util::Quaternion< T >::operator= (const this_type & other) default
operator=() [2/2]
template<typename T > Quaternion& openage::util::Quaternion< T >::operator= (this_type && other) default
operator==()
template<typename T > bool openage::util::Quaternion< T >::operator== (const this_type & other) const inline
Definition at line 411 of file quaternion.h.
{
         return ((this->w == other.w) and
                 (this->x == other.x) and
                 (this->y == other.y) and
                 (this->z == other.z));
     }
References openage::util::Quaternion< T >::w, openage::util::Quaternion< T >::x, openage::util::Quaternion< T >::y, and openage::util::Quaternion< T >::z.
to_matrix()
template<typename T > Matrix3t<T> openage::util::Quaternion< T >::to_matrix () const inline
Generate the corresponding rotation matrix.
Definition at line 282 of file quaternion.h.
{
         T x2  = this->x * 2;
         T y2  = this->y * 2;
         T z2  = this->z * 2;
         T x2w = x2 * this->w;
         T y2w = y2 * this->w;
         T z2w = z2 * this->w;
         T x3  = x2 * this->x;
         T y2x = y2 * this->x;
         T z2x = z2 * this->x;
         T y3  = y2 * this->y;
         T z2y = z2 * this->y;
         T z3  = z2 * this->z;
         Matrix3t<T> m{
             1.0 - (y3 + z3), y2x - z2w, z2x + y2w,
             y2x + z2w, 1.0 - (x3 + z3), z2y - x2w,
             z2x - y2w, z2y + x2w, 1.0 - (x3 + y3)
         };
         return m;
     }
References openage::util::Quaternion< T >::w, openage::util::Quaternion< T >::x, openage::util::Quaternion< T >::y, and openage::util::Quaternion< T >::z.
Friends And Related Function Documentation
operator<<
template<typename T > std::ostream& operator<< (std::ostream & o, const this_type & q) friend
Definition at line 422 of file quaternion.h.
{
         o << "Quaternion(" << q.w << ", " << q.x;
         o << ", " << q.y << ", " << q.z << ")";
         return o;
     }
Member Data Documentation
default_eps
template<typename T > constexpr T openage::util::Quaternion< T >::default_eps = 1e-4 static
Definition at line 36 of file quaternion.h.
w
template<typename T > T openage::util::Quaternion< T >::w protected
Stored quaternion number components.
Definition at line 432 of file quaternion.h.
Referenced by openage::util::Quaternion< T >::dot(), openage::util::Quaternion< T >::equals_number(), openage::util::Quaternion< T >::operator *(), openage::util::Quaternion< T >::operator *=(), openage::util::Quaternion< T >::operator -(), openage::util::Quaternion< T >::operator -=(), openage::util::Quaternion< T >::operator+=(), openage::util::Quaternion< T >::operator/=(), openage::util::Quaternion< T >::operator==(), openage::util::Quaternion< T >::Quaternion(), and openage::util::Quaternion< T >::to_matrix().
x
template<typename T > T openage::util::Quaternion< T >::x protected
Definition at line 432 of file quaternion.h.
Referenced by openage::util::Quaternion< T >::conjugate(), openage::util::Quaternion< T >::dot(), openage::util::Quaternion< T >::equals_number(), openage::util::Quaternion< T >::operator *(), openage::util::Quaternion< T >::operator *=(), openage::util::Quaternion< T >::operator -(), openage::util::Quaternion< T >::operator -=(), openage::util::Quaternion< T >::operator+=(), openage::util::Quaternion< T >::operator/=(), openage::util::Quaternion< T >::operator==(), openage::util::Quaternion< T >::Quaternion(), and openage::util::Quaternion< T >::to_matrix().
y
template<typename T > T openage::util::Quaternion< T >::y protected
Definition at line 432 of file quaternion.h.
Referenced by openage::util::Quaternion< T >::conjugate(), openage::util::Quaternion< T >::dot(), openage::util::Quaternion< T >::equals_number(), openage::util::Quaternion< T >::operator *(), openage::util::Quaternion< T >::operator *=(), openage::util::Quaternion< T >::operator -(), openage::util::Quaternion< T >::operator -=(), openage::util::Quaternion< T >::operator+=(), openage::util::Quaternion< T >::operator/=(), openage::util::Quaternion< T >::operator==(), openage::util::Quaternion< T >::Quaternion(), and openage::util::Quaternion< T >::to_matrix().
z
template<typename T > T openage::util::Quaternion< T >::z protected
Definition at line 432 of file quaternion.h.
Referenced by openage::util::Quaternion< T >::conjugate(), openage::util::Quaternion< T >::dot(), openage::util::Quaternion< T >::equals_number(), openage::util::Quaternion< T >::operator *(), openage::util::Quaternion< T >::operator *=(), openage::util::Quaternion< T >::operator -(), openage::util::Quaternion< T >::operator -=(), openage::util::Quaternion< T >::operator+=(), openage::util::Quaternion< T >::operator/=(), openage::util::Quaternion< T >::operator==(), openage::util::Quaternion< T >::Quaternion(), and openage::util::Quaternion< T >::to_matrix().
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/quaternion.h