openage: openage::Terrain Class Reference
openage::Terrain Class Reference
#include <terrain.h>
Public Member Functions
Terrain (terrain_meta *meta, bool is_infinite)
~Terrain ()
std::vector< coord::chunk > used_chunks () const
bool fill (const int *data, const coord::tile_delta &size)
void attach_chunk (TerrainChunk *new_chunk, const coord::chunk &position, bool manual=true)
TerrainChunk * get_chunk (const coord::chunk &position)
TerrainChunk * get_chunk (const coord::tile &position)
TerrainChunk * get_create_chunk (const coord::chunk &position)
TerrainChunk * get_create_chunk (const coord::tile &position)
TileContent * get_data (const coord::tile &position)
TerrainObject * obj_at_point (const coord::phys3 &point)
struct chunk_neighbors get_chunk_neighbors (const coord::chunk &position)
unsigned get_subtexture_id (const coord::tile &pos, unsigned atlas_size)
tile_state check_tile (const coord::tile &position)
bool check_tile_position (const coord::tile &position)
bool validate_terrain (terrain_t terrain_id)
bool validate_mask (ssize_t mask_id)
int priority (terrain_t terrain_id)
int blendmode (terrain_t terrain_id)
Texture * texture (terrain_t terrain_id)
Texture * blending_mask (ssize_t mask_id)
int get_blending_mode (terrain_t base_id, terrain_t neighbor_id)
void draw (Engine *engine, RenderOptions *settings)
struct terrain_render_data create_draw_advice (const coord::tile &ab, const coord::tile &cd, const coord::tile &ef, const coord::tile &gh, bool blending_enabled)
struct tile_draw_data create_tile_advice (coord::tile position, bool blending_enabled)
void get_neighbors (coord::tile basepos, struct neighbor_tile *neigh_tiles, struct influence *influences_by_terrain_id)
struct influence_group calculate_influences (struct tile_data *base_tile, struct neighbor_tile *neigh_tiles, struct influence *influences_by_terrain_id)
void calculate_masks (coord::tile position, struct tile_draw_data *tile_data, struct influence_group *influences)
Public Attributes
bool infinite
chunks are automagically created as soon as they are referenced
Private Attributes
terrain_meta * meta
std::unordered_map< coord::chunk, TerrainChunk *, coord_chunk_hash > chunks
Detailed Description
the terrain class is the main top-management interface for dealing with cost-benefit analysis to maximize company profits.
actually this is just the entrypoint and container for the terrain chunks.
Definition at line 175 of file terrain.h.
Constructor & Destructor Documentation
Terrain()
openage::Terrain::Terrain (terrain_meta * meta, bool is_infinite)
Definition at line 31 of file terrain.cpp.
     :
     infinite{is_infinite},
     meta{meta} {
     // TODO:
     //this->limit_positive =
     //this->limit_negative =
     // maps chunk position to chunks
     this->chunks = std::unordered_map<coord::chunk, TerrainChunk *, coord_chunk_hash>{};
 }
~Terrain()
openage::Terrain::~Terrain ()
Definition at line 45 of file terrain.cpp.
                   {
     log::log(MSG(dbg) << "Cleanup terrain");
     for (auto &chunk : this->chunks) {
         // this chunk was autogenerated, so clean it up
         if (chunk.second->manually_created == false) {
             delete chunk.second;
         }
     }
 }
References chunks, openage::log::dbg(), openage::log::log(), and MSG.
Member Function Documentation
attach_chunk()
void openage::Terrain::attach_chunk (TerrainChunk * new_chunk, const coord::chunk & position, bool manual = true)
Attach a chunk to the terrain, to a given position.
Parameters
new_chunk The chunk to be attached
position The chunk position where the chunk will be placed
manually_created Was this chunk created manually? If true, it will not be free'd automatically
Definition at line 82 of file terrain.cpp.
{
     new_chunk->set_terrain(this);
     new_chunk->manually_created = manually_created;
     log::log(MSG(dbg) << "Inserting new chunk at (" << position.ne << "," << position.se << ")");
     this->chunks[position] = new_chunk;
     struct chunk_neighbors neigh = this->get_chunk_neighbors(position);
     for (int i = 0; i < 8; i++) {
         TerrainChunk *neighbor = neigh.neighbor[i];
         if (neighbor != nullptr) {
             //set the new chunks neighbor to the neighbor chunk
             new_chunk->neighbors.neighbor[i] = neighbor;
             //set the neighbors neighbor on the opposite direction
             //to the new chunk
             neighbor->neighbors.neighbor[(i+4) % 8] = new_chunk;
             log::log(MSG(dbg) << "Neighbor " << i << " gets notified of new neighbor.");
         }
         else {
             log::log(MSG(dbg) << "Neighbor " << i << " not found.");
         }
     }
 }
References chunks, openage::log::dbg(), get_chunk_neighbors(), openage::log::log(), openage::TerrainChunk::manually_created, MSG, openage::chunk_neighbors::neighbor, openage::TerrainChunk::neighbors, and openage::TerrainChunk::set_terrain().
Referenced by get_create_chunk().
blending_mask()
Texture * openage::Terrain::blending_mask (ssize_t mask_id)
get the blendomatic mask with the given mask id.
Definition at line 197 of file terrain.cpp.
{
     this->validate_mask(mask_id);
     return this->meta->blending_masks[mask_id];
 }
References openage::terrain_meta::blending_masks, meta, and validate_mask().
Referenced by calculate_masks().
blendmode()
int openage::Terrain::blendmode (terrain_t terrain_id)
return the blending mode/blendomatic mask set for a given terrain id.
Definition at line 187 of file terrain.cpp.
{
     this->validate_terrain(terrain_id);
     return this->meta->terrain_id_blendmode_map[terrain_id];
 }
References meta, openage::terrain_meta::terrain_id_blendmode_map, and validate_terrain().
Referenced by get_blending_mode().
calculate_influences()
struct influence_group openage::Terrain::calculate_influences (struct tile_data * base_tile, struct neighbor_tile * neigh_tiles, struct influence * influences_by_terrain_id)
look at neighbor tiles around the base_tile, and store the influence bits.
Parameters
base_tile the base tile for which influences are calculated
neigh_tiles the neigbors of base_tile
influences_by_terrain_id influences will be stored to this buffer, as bitmasks
Returns
an influence group that describes the maximum 8 possible influences on the base_tile
Definition at line 500 of file terrain.cpp.
{
     // influences to actually draw (-> maximum 8)
     struct influence_group influences;
     influences.count = 0;
     // process adjacent neighbors first,
     // then add diagonal influences, if no adjacent influence was found
     constexpr int neigh_id_lookup[] = {1, 3, 5, 7, 0, 2, 4, 6};
     for (int i = 0; i < 8; i++) {
         // diagonal neighbors: (neigh_id % 2) == 0
         // adjacent neighbors: (neigh_id % 2) == 1
         int neigh_id = neigh_id_lookup[i];
         bool is_adjacent_neighbor = neigh_id % 2 == 1;
         bool is_diagonal_neighbor = not is_adjacent_neighbor;
         // the current neighbor_tile.
         auto neighbor = &neigh_data[neigh_id];
         // neighbor is nonexistant
         if (neighbor->state == tile_state::missing) {
             continue;
         }
         // neighbor only interesting if it's a different terrain than the base.
         // if it is the same id, the priorities are equal.
         // neighbor draws over the base if it's priority is greater.
         if (neighbor->priority > base_tile->priority) {
             // get influence storage for the neighbor terrain id
             // to group influences by id
             auto influence = &influences_by_terrain_id[neighbor->terrain_id];
             // check if diagonal influence is valid
             if (is_diagonal_neighbor) {
                 // get the adjacent neighbors to the current diagonal
                 // influence
                 //  (a & 0x07) == (a % 8)
                 uint8_t adj_neigh_0 = (neigh_id - 1) & 0x07;
                 uint8_t adj_neigh_1 = (neigh_id + 1) & 0x07;
                 uint8_t neigh_mask = (1 << adj_neigh_0) | (1 << adj_neigh_1);
                 // the adjacent neigbors are already influencing
                 // the current tile, therefore don't apply the diagonal mask
                 if ((influence->direction & neigh_mask) != 0) {
                     continue;
                 }
             }
             // this terrain id hasn't had influence so far:
             // add it to the list of influences.
             if (influence->direction == 0) {
                 influences.terrain_ids[influences.count] = neighbor->terrain_id;
                 influences.count += 1;
             }
             // as tile i has influence for this priority
             //  => bit i is set to 1 by 2^i
             influence->direction |= 1 << neigh_id;
             influence->priority = neighbor->priority;
             influence->terrain_id = neighbor->terrain_id;
         }
     }
     // influences_by_terrain_id will be merged in the following,
     // unused terrain ids will be dropped now.
     // shrink the big influence buffer that had entries for all terrains
     // by copying the possible (max 8) influences to a separate buffer.
     for (int k = 0; k < influences.count; k++) {
         int relevant_id    = influences.terrain_ids[k];
         influences.data[k] = influences_by_terrain_id[relevant_id];
     }
     // order the influences by their priority
     for (int k = 1; k < influences.count; k++) {
         struct influence tmp_influence = influences.data[k];
         int l = k - 1;
         while (l >= 0 && influences.data[l].priority > tmp_influence.priority) {
             influences.data[l + 1] = influences.data[l];
             l -= 1;
         }
         influences.data[l + 1] = tmp_influence;
     }
     return influences;
 }
References openage::influence_group::count, openage::influence_group::data, openage::influence::direction, openage::missing, openage::influence::priority, openage::influence::terrain_id, and openage::influence_group::terrain_ids.
calculate_masks()
void openage::Terrain::calculate_masks (coord::tile position, struct tile_draw_data * tile_data, struct influence_group * influences)
calculate blending masks for a given tile position.
Parameters
position the base tile position, for which the masks are calculated
tile_data the buffer where the created drawing layers will be stored in
influences the buffer where calculated influences were stored to
See also
calculate_influences
Definition at line 595 of file terrain.cpp.
{
     // influences are grouped by terrain id.
     // the direction member has each bit set to 1 that is an influence from that direction.
     // create a mask for this direction combination.
     // the base tile is stored at position 0 of the draw_mask
     terrain_t base_terrain_id = tile_data->data[0].terrain_id;
     // iterate over all neighbors (with different terrain_ids) that have influence
     for (ssize_t i = 0; i < influences->count; i++) {
         // neighbor id of the current influence
         char direction_bits = influences->data[i].direction;
         // all bits are 0 -> no influence directions stored.
         //  => no influence can be ignored.
         if (direction_bits == 0) {
             continue;
         }
         terrain_t neighbor_terrain_id = influences->data[i].terrain_id;
         int adjacent_mask_id = -1;
         /* neighbor ids:
              0
            7   1      => 8 neighbors that can have influence on
          6   @   2         the mask id selection.
            5   3
              4
         */
         // filter adjacent and diagonal influences    neighbor_id: 76543210
         uint8_t direction_bits_adjacent = direction_bits & 0xAA; //0b10101010
         uint8_t direction_bits_diagonal = direction_bits & 0x55; //0b01010101
         switch (direction_bits_adjacent) {
         case 0x08:  //0b00001000
             adjacent_mask_id = 0;  //0..3
             break;
         case 0x02:  //0b00000010
             adjacent_mask_id = 4;  //4..7
             break;
         case 0x20:  //0b00100000
             adjacent_mask_id = 8;  //8..11
             break;
         case 0x80:  //0b10000000
             adjacent_mask_id = 12; //12..15
             break;
         case 0x22:  //0b00100010
             adjacent_mask_id = 20;
             break;
         case 0x88:  //0b10001000
             adjacent_mask_id = 21;
             break;
         case 0xA0:  //0b10100000
             adjacent_mask_id = 22;
             break;
         case 0x82:  //0b10000010
             adjacent_mask_id = 23;
             break;
         case 0x28:  //0b00101000
             adjacent_mask_id = 24;
             break;
         case 0x0A:  //0b00001010
             adjacent_mask_id = 25;
             break;
         case 0x2A:  //0b00101010
             adjacent_mask_id = 26;
             break;
         case 0xA8:  //0b10101000
             adjacent_mask_id = 27;
             break;
         case 0xA2:  //0b10100010
             adjacent_mask_id = 28;
             break;
         case 0x8A:  //0b10001010
             adjacent_mask_id = 29;
             break;
         case 0xAA:  //0b10101010
             adjacent_mask_id = 30;
             break;
         }
         // if it's the linear adjacent mask, cycle the 4 possible masks.
         // e.g. long shorelines don't look the same then.
         //  maskid == 0x08 0x02 0x80 0x20 for that.
         if (adjacent_mask_id <= 12 && adjacent_mask_id % 4 == 0) {
             //we have 4 = 2^2 anti redundancy masks, so keep the last 2 bits
             uint8_t anti_redundancy_offset = (position.ne + position.se) & 0x03;
             adjacent_mask_id += anti_redundancy_offset;
         }
         // get the blending mode (the mask selection) for this transition
         // the mode is dependent on the two meeting terrain types
         int blend_mode = this->get_blending_mode(base_terrain_id, neighbor_terrain_id);
         // append the mask for the adjacent blending
         if (adjacent_mask_id >= 0) {
             struct tile_data *overlay = &tile_data->data[tile_data->count];
             overlay->pos        = position;
             overlay->mask_id    = adjacent_mask_id;
             overlay->blend_mode = blend_mode;
             overlay->terrain_id = neighbor_terrain_id;
             overlay->tex        = this->texture(neighbor_terrain_id);
             overlay->subtexture_id = this->get_subtexture_id(
                 position,
                 std::sqrt(overlay->tex->get_subtexture_count())
             );
             overlay->mask_tex   = this->blending_mask(blend_mode);
             overlay->state      = tile_state::existing;
             tile_data->count += 1;
         }
         // append the mask for the diagonal blending
         if (direction_bits_diagonal > 0) {
             for (int l = 0; l < 4; l++) {
                 // generate one mask for each influencing diagonal neighbor id.
                 // even if they all have the same terrain_id,
                 // because we don't have combined diagonal influence masks.
                 // l == 0: pos = 0b000000001, mask = 18
                 // l == 1: pos = 0b000000100, mask = 16
                 // l == 2: pos = 0b000010000, mask = 17
                 // l == 3: pos = 0b001000000, mask = 19
                 int current_direction_bit = 1 << (l*2);
                 constexpr int diag_mask_id_map[4] = {18, 16, 17, 19};
                 if (direction_bits_diagonal & current_direction_bit) {
                     struct tile_data *overlay = &tile_data->data[tile_data->count];
                     overlay->pos        = position;
                     overlay->mask_id    = diag_mask_id_map[l];
                     overlay->blend_mode = blend_mode;
                     overlay->terrain_id = neighbor_terrain_id;
                     overlay->tex        = this->texture(neighbor_terrain_id);
                     overlay->subtexture_id = this->get_subtexture_id(
                         position,
                         std::sqrt(overlay->tex->get_subtexture_count())
                     );
                     overlay->mask_tex   = this->blending_mask(blend_mode);
                     overlay->state      = tile_state::existing;
                     tile_data->count += 1;
                 }
             }
         }
     }
 }
References openage::tile_data::blend_mode, blending_mask(), openage::influence_group::count, openage::influence_group::data, openage::influence::direction, openage::existing, get_blending_mode(), openage::Texture::get_subtexture_count(), get_subtexture_id(), openage::tile_data::mask_id, openage::tile_data::mask_tex, openage::tile_data::pos, std::sqrt(), openage::tile_data::state, openage::tile_data::subtexture_id, openage::influence::terrain_id, openage::tile_data::terrain_id, openage::tile_data::tex, and texture().
check_tile()
tile_state openage::Terrain::check_tile (const coord::tile & position)
checks the creation state and premissions of a given tile position.
Definition at line 254 of file terrain.cpp.
{
     if (this->check_tile_position(position) == false) {
         return tile_state::invalid;
     }
     else {
         TerrainChunk *chunk = this->get_chunk(position);
         if (chunk == nullptr) {
             return tile_state::creatable;
         }
         else {
             return tile_state::existing;
         }
     }
 }
References check_tile_position(), openage::creatable, openage::existing, get_chunk(), and openage::invalid.
Referenced by fill().
check_tile_position()
bool openage::Terrain::check_tile_position (const coord::tile & position)
checks whether the given tile position is allowed to exist on this terrain.
Definition at line 269 of file terrain.cpp.
{
     if (this->infinite == true) {
         return true;
     }
     else {
         throw Error(ERR << "non-infinite terrains are not supported yet");
     }
 }
References ERR, and infinite.
Referenced by check_tile().
create_draw_advice()
struct terrain_render_data openage::Terrain::create_draw_advice (const coord::tile & ab, const coord::tile & cd, const coord::tile & ef, const coord::tile & gh, bool blending_enabled)
create the drawing instruction data.
created draw data according to the given tile boundaries.
Parameters
ab upper left tile
cd upper right tile
ef lower right tile
gh lower left tile
Returns
a drawing instruction struct that contains all information for rendering
Definition at line 329 of file terrain.cpp.
{
     /*
      * The passed parameters define the screen corners.
      *
      *    ne, se coordinates
      *    o = screen corner, where the tile coordinates can be queried.
      *    x = corner of the rhombus that will be drawn, calculated by all o.
      *
      *                  cb
      *                   x
      *                 .   .
      *               .       .
      *          ab o===========o cd
      *           . =  visible  = .
      *      gb x   =  screen   =   x cf
      *           . =           = .
      *          gh o===========o ef
      *               .       .
      *                 .   .
      *                   x
      *                  gf
      *
      * The rendering area may be optimized further in the future,
      * to exactly fit the visible screen.
      * For now, we are drawing the big rhombus.
      */
     // procedure: find all the tiles to be drawn
     // and store them to a tile drawing instruction structure
     struct terrain_render_data data;
     // vector of tiles to be drawn
     std::vector<struct tile_draw_data> *tiles = &data.tiles;
     // ordered set of objects on the terrain (buildings.)
     // it's ordered by the visibility layers.
     auto objects = &data.objects;
     coord::tile gb = {gh.ne, ab.se};
     coord::tile cf = {cd.ne, ef.se};
     // hint the vector about the number of tiles it will contain
     size_t tiles_count = std::abs(cf.ne - gb.ne) * std::abs(cf.se - gb.se);
     tiles->reserve(tiles_count);
     // sweep the whole rhombus area
     for (coord::tile tilepos = gb; tilepos.ne <= cf.ne; tilepos.ne++) {
         for (tilepos.se = gb.se; tilepos.se <= cf.se; tilepos.se++) {
             // get the terrain tile drawing data
             auto tile = this->create_tile_advice(tilepos, blending_enabled);
             tiles->push_back(tile);
             // get the object standing on the tile
             // TODO: make the terrain independent of objects standing on it.
             TileContent *tile_content = this->get_data(tilepos);
             if (tile_content != nullptr) {
                 for (auto obj_item : tile_content->obj) {
                     objects->insert(obj_item);
                 }
             }
         }
     }
     return data;
 }
References std::abs(), openage::TileContent::obj, openage::terrain_render_data::objects, and openage::terrain_render_data::tiles.
Referenced by draw().
create_tile_advice()
struct tile_draw_data openage::Terrain::create_tile_advice (coord::tile position, bool blending_enabled)
create rendering and blending information for a single tile on the terrain.
Definition at line 402 of file terrain.cpp.
{
     // this struct will be filled with all tiles and overlays to draw.
     struct tile_draw_data tile;
     tile.count = 0;
     TileContent *base_tile_content = this->get_data(position);
     // chunk of this tile does not exist
     if (base_tile_content == nullptr) {
         return tile;
     }
     struct tile_data base_tile_data;
     // the base terrain id of the tile
     base_tile_data.terrain_id = base_tile_content->terrain_id;
     // the base terrain is not existant.
     if (base_tile_data.terrain_id < 0) {
         return tile;
     }
     this->validate_terrain(base_tile_data.terrain_id);
     Texture *tex = this->texture(base_tile_data.terrain_id);
     base_tile_data.state         = tile_state::existing;
     base_tile_data.pos           = position;
     base_tile_data.priority      = this->priority(base_tile_data.terrain_id);
     base_tile_data.tex           = tex;
     base_tile_data.subtexture_id = this->get_subtexture_id(
         position,
         std::sqrt(tex->get_subtexture_count())
     );
     base_tile_data.blend_mode    = -1;
     base_tile_data.mask_tex      = nullptr;
     base_tile_data.mask_id       = -1;
     tile.data[tile.count] = base_tile_data;
     tile.count += 1;
     // blendomatic!!111
     //  see doc/media/blendomatic for the idea behind this.
     if (blending_enabled) {
         // the neighbors of the base tile
         struct neighbor_tile neigh_data[8];
         // get all neighbor tiles around position, reset the influence directions.
         this->get_neighbors(position, neigh_data, this->meta->influences_buf.get());
         // create influence list (direction, priority)
         // strip and order influences, get the final influence data structure
         struct influence_group influence_group = this->calculate_influences(
             &base_tile_data, neigh_data,
             this->meta->influences_buf.get()
         );
         // create the draw_masks from the calculated influences
         this->calculate_masks(position, &tile, &influence_group);
     }
     return tile;
 }
References openage::tile_data::blend_mode, openage::tile_draw_data::count, openage::tile_draw_data::data, openage::existing, openage::Texture::get_subtexture_count(), openage::tile_data::mask_id, openage::tile_data::mask_tex, openage::tile_data::pos, openage::tile_data::priority, std::sqrt(), openage::tile_data::state, openage::tile_data::subtexture_id, openage::TileContent::terrain_id, openage::tile_data::terrain_id, openage::tile_data::tex, and openage::texturefont_shader::texture.
draw()
void openage::Terrain::draw (Engine * engine, RenderOptions * settings)
draw the currently visible terrain area on screen.
Parameters
engine the engine where the terrain should be drawn to.
Definition at line 278 of file terrain.cpp.
{
     // TODO: move this draw invokation to a render manager.
     //       it can reorder the draw instructions and minimize texture switching.
     // query the window coordinates from the engine first
     coord::viewport wbl = coord::viewport{0, 0};
     coord::viewport wbr = coord::viewport{engine->coord.viewport_size.x, 0};
     coord::viewport wtl = coord::viewport{0, engine->coord.viewport_size.y};
     coord::viewport wtr = coord::viewport{engine->coord.viewport_size.x, engine->coord.viewport_size.y};
     // top left, bottom right tile coordinates
     // that are currently visible in the window
     // then convert them to tile coordinates.
     coord::tile tl = wtl.to_tile(engine->coord);
     coord::tile tr = wtr.to_tile(engine->coord);
     coord::tile bl = wbl.to_tile(engine->coord);
     coord::tile br = wbr.to_tile(engine->coord);
     // main terrain calculation call: get the `terrain_render_data`
     auto draw_data = this->create_draw_advice(tl, tr, br, bl, settings->terrain_blending.value);
     // TODO: the following loop is totally inefficient and shit.
     //       it reloads the drawing texture to the gpu FOR EACH TILE!
     //       nevertheless, currently it works.
     // draw the terrain ground
     for (auto &tile : draw_data.tiles) {
         // iterate over all layers to be drawn
         for (int i = 0; i < tile.count; i++) {
             struct tile_data *layer = &tile.data[i];
             // position, where the tile is drawn
             coord::tile tile_pos = layer->pos;
             int      mask_id       = layer->mask_id;
             Texture *texture       = layer->tex;
             int      subtexture_id = layer->subtexture_id;
             Texture *mask_texture  = layer->mask_tex;
             texture->draw(engine->coord, *this, tile_pos, ALPHAMASKED, subtexture_id, mask_texture, mask_id);
         }
     }
     // TODO: drawing buildings can't be the job of the terrain..
     // draw the buildings
     for (auto &object : draw_data.objects) {
         object->draw(*engine);
     }
 }
References openage::ALPHAMASKED, openage::Engine::coord, create_draw_advice(), openage::Texture::draw(), openage::tile_data::mask_id, openage::tile_data::mask_tex, openage::alphamask_shader::mask_texture, openage::tile_data::pos, openage::tile_data::subtexture_id, openage::RenderOptions::terrain_blending, openage::tile_data::tex, texture(), openage::coord::viewport::to_tile(), openage::util::Variable< T >::value, and openage::coord::CoordManager::viewport_size.
fill()
bool openage::Terrain::fill (const int * data, const coord::tile_delta & size)
fill the terrain with given terrain_id values.
Returns
whether the data filled on the terrain was cut because of the terrains size limit.
Definition at line 64 of file terrain.cpp.
{
     bool was_cut = false;
     coord::tile pos = {0, 0};
     for (; pos.ne < size.ne; pos.ne++) {
         for (pos.se = 0; pos.se < size.se; pos.se++) {
             if (this->check_tile(pos) == tile_state::invalid) {
                 was_cut = true;
                 continue;
             }
             int terrain_id = data[pos.ne * size.ne + pos.se];
             TerrainChunk *chunk = this->get_create_chunk(pos);
             chunk->get_data(pos)->terrain_id = terrain_id;
         }
     }
     return was_cut;
 }
References check_tile(), get_create_chunk(), openage::TerrainChunk::get_data(), openage::invalid, and openage::TileContent::terrain_id.
Referenced by openage.convert.colortable.ColorTable::__init__().
get_blending_mode()
int openage::Terrain::get_blending_mode (terrain_t base_id, terrain_t neighbor_id)
return the blending mode id for two given neighbor ids.
Definition at line 226 of file terrain.cpp.
{
     /*
      * this function may require much more code, but this simple
      * magnitude comparison seems to do the job.
      * feel free to confirm or fix the behavior.
      *
      * my guess is that the blending mode encodes another information
      * not publicly noticed yet: the overlay priority.
      * the higher the blendmode id, the higher the mode priority.
      * this may also be the reason why there are mask duplicates
      * in blendomatic.dat
      *
      * funny enough, just using the modes in the dat file lead
      * to a totally wrong render. the convert script reassigns the
      * blending modes with a simple key=>val mapping,
      * and after that, it looks perfect.
      */
     int base_mode     = this->blendmode(base_id);
     int neighbor_mode = this->blendmode(neighbor_id);
     if (neighbor_mode > base_mode) {
         return neighbor_mode;
     } else {
         return base_mode;
     }
 }
References blendmode().
Referenced by calculate_masks().
get_chunk() [1/2]
TerrainChunk * openage::Terrain::get_chunk (const coord::chunk & position)
get a terrain chunk by a given chunk position.
Returns
the chunk if exists, nullptr else
Definition at line 109 of file terrain.cpp.
{
     auto iter = this->chunks.find(position);
     if (iter == this->chunks.end()) {
         return nullptr;
     }
     else {
         return iter->second;
     }
 }
References chunks.
Referenced by check_tile(), get_chunk(), get_create_chunk(), and get_data().
get_chunk() [2/2]
TerrainChunk * openage::Terrain::get_chunk (const coord::tile & position)
get a terrain chunk by a given tile position.
Returns
the chunk it exists, nullptr else
Definition at line 120 of file terrain.cpp.
{
     return this->get_chunk(position.to_chunk());
 }
References get_chunk(), and openage::coord::tile::to_chunk().
get_chunk_neighbors()
struct chunk_neighbors openage::Terrain::get_chunk_neighbors (const coord::chunk & position)
get the neighbor chunks of a given chunk.
chunk neighbor ids: 0 / <- ne 7 1 6 @ 2 5 3 4 \ <- se
ne se 0: 1 -1 1: 1 0 2: 1 1 3: 0 1 4: -1 1 5: -1 0 6: -1 -1 7: 0 -1
Parameters
position the position of the center chunk.
Definition at line 212 of file terrain.cpp.
{
     struct chunk_neighbors ret;
     for (int i = 0; i < 8; i++) {
         coord::chunk tmp {
             position.ne + (coord::chunk_t) neigh_offsets[i].ne,
             position.se + (coord::chunk_t) neigh_offsets[i].se
         };
         ret.neighbor[i] = this->get_chunk(tmp);
     }
     return ret;
 }
References openage::neigh_offsets, and openage::chunk_neighbors::neighbor.
Referenced by attach_chunk().
get_create_chunk() [1/2]
TerrainChunk * openage::Terrain::get_create_chunk (const coord::chunk & position)
get or create a terrain chunk for a given chunk position.
Returns
the (maybe newly created) chunk
Definition at line 124 of file terrain.cpp.
{
     TerrainChunk *res = this->get_chunk(position);
     if (res == nullptr) {
         res = new TerrainChunk();
         this->attach_chunk(res, position, false);
     }
     return res;
 }
References attach_chunk(), and get_chunk().
Referenced by fill(), get_create_chunk(), openage::EditorMode::paint_entity_at(), and openage::EditorMode::paint_terrain_at().
get_create_chunk() [2/2]
TerrainChunk * openage::Terrain::get_create_chunk (const coord::tile & position)
get or create a terrain chunk for a given tile position.
Returns
the (maybe newly created) chunk
Definition at line 133 of file terrain.cpp.
{
     return this->get_create_chunk(position.to_chunk());
 }
References get_create_chunk(), and openage::coord::tile::to_chunk().
get_data()
TileContent * openage::Terrain::get_data (const coord::tile & position)
return tile data for the given position.
the only reason the chunks exist, is because of this data.
Definition at line 137 of file terrain.cpp.
{
     TerrainChunk *c = this->get_chunk(position.to_chunk());
     if (c == nullptr) {
         return nullptr;
     } else {
         return c->get_data(position.get_pos_on_chunk());
     }
 }
References get_chunk(), openage::TerrainChunk::get_data(), openage::coord::tile::get_pos_on_chunk(), and openage::coord::tile::to_chunk().
Referenced by get_neighbors(), obj_at_point(), and openage::UnitSelection::select_space().
get_neighbors()
void openage::Terrain::get_neighbors (coord::tile basepos, struct neighbor_tile * neigh_tiles, struct influence * influences_by_terrain_id)
gather neighbors of a given base tile.
Parameters
basepos the base position, around which the neighbors will be fetched
neigh_tiles the destination buffer where the neighbors will be stored
influences_by_terrain_id influence buffer that is reset in the same step
Definition at line 467 of file terrain.cpp.
{
     // walk over all given neighbor tiles and store them to the influence list,
     // group them by terrain id.
     for (int neigh_id = 0; neigh_id < 8; neigh_id++) {
         // the current neighbor
         auto neighbor = &neigh_data[neigh_id];
         // calculate the pos of the neighbor tile
         coord::tile neigh_pos = basepos + neigh_offsets[neigh_id];
         // get the neighbor data
         TileContent *neigh_content = this->get_data(neigh_pos);
         // chunk for neighbor or single tile is not existant
         if (neigh_content == nullptr || neigh_content->terrain_id < 0) {
             neighbor->state = tile_state::missing;
         }
         else {
             neighbor->terrain_id = neigh_content->terrain_id;
             neighbor->state      = tile_state::existing;
             neighbor->priority   = this->priority(neighbor->terrain_id);
             // reset influence directions for this tile
             influences_by_terrain_id[neighbor->terrain_id].direction = 0;
         }
     }
 }
References openage::influence::direction, openage::existing, get_data(), openage::missing, openage::neigh_offsets, priority(), and openage::TileContent::terrain_id.
get_subtexture_id()
unsigned openage::Terrain::get_subtexture_id (const coord::tile & pos, unsigned atlas_size)
return the subtexture offset id for a given tile position. the maximum offset is determined by the atlas size.
this function returns always the right value, so that neighbor tiles of the same terrain (like grass-grass) are matching (without blendomatic). -> e.g. grass only map.
Definition at line 202 of file terrain.cpp.
{
     unsigned result = 0;
     result += util::mod<coord::tile_t>(pos.se, atlas_size);
     result *= atlas_size;
     result += util::mod<coord::tile_t>(pos.ne, atlas_size);
     return result;
 }
References openage.testing.testing::result().
Referenced by calculate_masks().
obj_at_point()
TerrainObject * openage::Terrain::obj_at_point (const coord::phys3 & point)
an object which contains the given point, null otherwise
Definition at line 146 of file terrain.cpp.
{
     coord::tile t = point.to_tile();
     TileContent *tc = this->get_data(t);
     if (!tc) {
         return nullptr;
     }
     // prioritise selecting the smallest object
     TerrainObject *smallest = nullptr;
     for (auto obj_ptr : tc->obj) {
         if (obj_ptr->contains(point) &&
             (!smallest || obj_ptr->min_axis() < smallest->min_axis())) {
             smallest = obj_ptr;
         }
     }
     return smallest;
 }
References get_data(), openage::TerrainObject::min_axis(), openage::TileContent::obj, and openage::coord::phys3::to_tile().
Referenced by openage::UnitSelection::select_point().
priority()
int openage::Terrain::priority (terrain_t terrain_id)
return the blending priority for a given terrain id.
Definition at line 182 of file terrain.cpp.
{
     this->validate_terrain(terrain_id);
     return this->meta->terrain_id_priority_map[terrain_id];
 }
References meta, openage::terrain_meta::terrain_id_priority_map, and validate_terrain().
Referenced by get_neighbors().
texture()
Texture * openage::Terrain::texture (terrain_t terrain_id)
get the terrain texture for a given terrain id.
Definition at line 192 of file terrain.cpp.
{
     this->validate_terrain(terrain_id);
     return this->meta->textures[terrain_id];
 }
References meta, openage::terrain_meta::textures, and validate_terrain().
Referenced by calculate_masks(), and draw().
used_chunks()
std::vector< coord::chunk > openage::Terrain::used_chunks () const
returns a list of all referenced chunks
Definition at line 56 of file terrain.cpp.
{
     std::vector<coord::chunk> result;
     for (auto &c : chunks) {
         result.push_back(c.first);
     }
     return result;
 }
References chunks, and openage.testing.testing::result().
validate_mask()
bool openage::Terrain::validate_mask (ssize_t mask_id)
validate whether the given mask id is available.
Definition at line 173 of file terrain.cpp.
{
     if (mask_id >= (ssize_t)this->meta->blendmode_count) {
         throw Error(MSG(err) << "Requested mask_id is out of range: " << mask_id);
     }
     else {
         return true;
     }
 }
References openage::terrain_meta::blendmode_count, openage::log::err(), meta, and MSG.
Referenced by blending_mask().
validate_terrain()
bool openage::Terrain::validate_terrain (terrain_t terrain_id)
validate whether the given terrain id is available.
Definition at line 164 of file terrain.cpp.
{
     if (terrain_id >= (ssize_t)this->meta->terrain_id_count) {
         throw Error(MSG(err) << "Requested terrain_id is out of range: " << terrain_id);
     }
     else {
         return true;
     }
 }
References openage::log::err(), meta, MSG, and openage::terrain_meta::terrain_id_count.
Referenced by blendmode(), priority(), and texture().
Member Data Documentation
chunks
std::unordered_map<coord::chunk, TerrainChunk *, coord_chunk_hash> openage::Terrain::chunks private
maps chunk coordinates to chunks.
Definition at line 403 of file terrain.h.
Referenced by attach_chunk(), get_chunk(), used_chunks(), and ~Terrain().
infinite
bool openage::Terrain::infinite
chunks are automagically created as soon as they are referenced
Definition at line 180 of file terrain.h.
Referenced by check_tile_position().
meta
terrain_meta* openage::Terrain::meta private
terrain meta data
Definition at line 398 of file terrain.h.
Referenced by blending_mask(), blendmode(), priority(), texture(), validate_mask(), and validate_terrain().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/terrain/terrain.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/terrain/terrain.cpp