openage: openage::Attributes Class Reference
openage::Attributes Class Reference
Contains a group of attributes.
#include <attributes.h>
Public Member Functions
Attributes ()
void add (const std::shared_ptr< AttributeContainer > attr)
Add an attribute or replace any attribute of the same type.
void add_copies (const Attributes &attrs)
Add copies of all the attributes from the given Attributes.
void add_copies (const Attributes &attrs, bool shared, bool unshared)
Add copies of all the attributes from the given Attributes.
bool remove (const attr_type type)
Remove an attribute based on the type.
bool has (const attr_type type) const
Check if the attribute of the given type exists.
std::shared_ptr< AttributeContainer > get (const attr_type type) const
Get the attribute based on the type.
template<attr_type T>
Attribute< T > & get () const
Get the attribute.
Private Attributes
std::map< attr_type, std::shared_ptr< AttributeContainer > > attrs
Detailed Description
Contains a group of attributes.
Can contain only one attribute of each type.
Definition at line 15 of file attributes.h.
Constructor & Destructor Documentation
Attributes()
openage::Attributes::Attributes () inline
Definition at line 17 of file attributes.h.
 {}
Member Function Documentation
add()
void openage::Attributes::add (const std::shared_ptr< AttributeContainer > attr)
Add an attribute or replace any attribute of the same type.
Definition at line 7 of file attributes.cpp.
{
     this->attrs[attr->type] = attr;
 }
References attrs.
Referenced by openage::Unit::add_attribute(), add_copies(), and openage::UnitType::upgrade().
add_copies() [1/2]
void openage::Attributes::add_copies (const Attributes & attrs)
Add copies of all the attributes from the given Attributes.
Definition at line 11 of file attributes.cpp.
{
     this->add_copies(other, true, true);
 }
Referenced by openage::Unit::add_attributes(), and openage::UnitType::reinitialise().
add_copies() [2/2]
void openage::Attributes::add_copies (const Attributes & attrs, bool shared, bool unshared)
Add copies of all the attributes from the given Attributes.
If shared is false, shared attributes are ignored. If unshared is false, unshared attributes are ignored.
Definition at line 15 of file attributes.cpp.
{
     for (auto &i : other.attrs) {
         auto &attr = *i.second.get();
         if (attr.shared()) {
             if (shared) {
                 // pass self
                 this->add(i.second);
             }
         }
         else if (unshared) {
             // create copy
             this->add(attr.copy());
         }
     }
 }
References add(), and attrs.
get() [1/2]
std::shared_ptr< AttributeContainer > openage::Attributes::get (const attr_type type) const
Get the attribute based on the type.
Definition at line 40 of file attributes.cpp.
{
     return this->attrs.at(type);
 }
References attrs.
Referenced by openage::Unit::get_attribute(), and openage::TrainAction::update().
get() [2/2]
template<attr_type T> Attribute<T>& openage::Attributes::get () const inline
Get the attribute.
Definition at line 55 of file attributes.h.
{
         return *reinterpret_cast<Attribute<T> *>(this->attrs.at(T).get());
     }
References attrs.
has()
bool openage::Attributes::has (const attr_type type) const
Check if the attribute of the given type exists.
Definition at line 36 of file attributes.cpp.
{
     return this->attrs.find(type) != this->attrs.end();
 }
References attrs.
Referenced by openage::Unit::has_attribute(), and openage::TrainAction::update().
remove()
bool openage::Attributes::remove (const attr_type type)
Remove an attribute based on the type.
Definition at line 32 of file attributes.cpp.
{
     return this->attrs.erase(type) > 0;
 }
References attrs.
Member Data Documentation
attrs
std::map<attr_type, std::shared_ptr<AttributeContainer> > openage::Attributes::attrs private
Definition at line 61 of file attributes.h.
Referenced by add(), add_copies(), get(), has(), and remove().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/attributes.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/attributes.cpp