openage: openage::gui::GuiGameSpecImageProviderByIdImpl Class Reference
openage::gui::GuiGameSpecImageProviderByIdImpl Class Reference abstract
Base for providers that expose textures to the Qt by their id.
#include <gui_game_spec_image_provider_by_id_impl.h>
Public Member Functions
GuiGameSpecImageProviderByIdImpl (qtsdl::GuiEventQueue *render_updater)
virtual ~GuiGameSpecImageProviderByIdImpl ()
Public Member Functions inherited from openage::gui::GuiGameSpecImageProviderImpl
GuiGameSpecImageProviderImpl (qtsdl::GuiEventQueue *render_updater)
virtual ~GuiGameSpecImageProviderImpl ()
void on_game_spec_loaded (const std::shared_ptr< GameSpec > &loaded_game_spec)
Unblocks the provider.
void on_game_spec_invalidated ()
Set to every sprite the 'missing texture' from current spec.
GuiFilledTextureHandleUser fill_texture_handle (const QString &id, const QSize &requested_size, SizedTextureHandle *filled_handle)
Fills in the provided handle object.
Public Member Functions inherited from qtsdl::GuiImageProviderImpl
GuiImageProviderImpl ()
virtual ~GuiImageProviderImpl ()
virtual const char * get_id () const =0
Private Member Functions
virtual TextureHandle get_texture_handle (const QString &id) override
virtual openage::Texture * get_texture (int texture_id)=0
Additional Inherited Members
Static Public Member Functions inherited from qtsdl::GuiImageProviderImpl
static std::unique_ptr< GuiImageProviderImpl > take_ownership (GuiImageProvider *image_provider)
static std::vector< std::unique_ptr< GuiImageProviderImpl > > take_ownership (const std::vector< GuiImageProvider * > &image_providers)
Protected Member Functions inherited from openage::gui::GuiGameSpecImageProviderImpl
TextureHandle get_missing_texture ()
Protected Attributes inherited from openage::gui::GuiGameSpecImageProviderImpl
std::shared_ptr< GameSpec > loaded_game_spec
bool invalidated
When true, still uses the old source but shows the 'missing texture'.
Detailed Description
Base for providers that expose textures to the Qt by their id.
Numeric id has a form of <texture-id>.<subid>.
Definition at line 15 of file gui_game_spec_image_provider_by_id_impl.h.
Constructor & Destructor Documentation
GuiGameSpecImageProviderByIdImpl()
openage::gui::GuiGameSpecImageProviderByIdImpl::GuiGameSpecImageProviderByIdImpl (qtsdl::GuiEventQueue * render_updater) explicit
Definition at line 13 of file gui_game_spec_image_provider_by_id_impl.cpp.
     :
     GuiGameSpecImageProviderImpl{render_updater} {
 }
~GuiGameSpecImageProviderByIdImpl()
openage::gui::GuiGameSpecImageProviderByIdImpl::~GuiGameSpecImageProviderByIdImpl () virtual
Definition at line 18 of file gui_game_spec_image_provider_by_id_impl.cpp.
{
 }
Member Function Documentation
get_texture()
virtual openage::Texture* openage::gui::GuiGameSpecImageProviderByIdImpl::get_texture (int texture_id) private pure virtual
Implemented in openage::gui::GuiGameSpecImageProviderByGraphicIdImpl, and openage::gui::GuiGameSpecImageProviderByTerrainIdImpl.
Referenced by get_texture_handle().
get_texture_handle()
TextureHandle openage::gui::GuiGameSpecImageProviderByIdImpl::get_texture_handle (const QString & id) override private virtual
Implements openage::gui::GuiGameSpecImageProviderImpl.
Definition at line 21 of file gui_game_spec_image_provider_by_id_impl.cpp.
{
     ENSURE(this->loaded_game_spec, "trying to actually get a texture from a non-loaded spec");
     auto ids = id.splitRef(".");
     if (ids.size() == 2) {
         bool id_ok = false, subid_ok = false;
         const int texture_id = ids[0].toInt(&id_ok);
         const int subid = ids[1].toInt(&subid_ok);
         auto tex = (id_ok and subid_ok)
                    ?
                    this->get_texture(texture_id)
                    :
                    nullptr;
         if (tex != nullptr and
             subid < static_cast<int>(tex->get_subtexture_count())) {
             return TextureHandle{tex, subid};
         }
         else {
             return this->get_missing_texture();
         }
     } else {
         qWarning("Invalid texture id: 'image://%s/%s'. Example formatting: 'image://%s/7366.18'.", this->get_id(), qUtf8Printable(id), this->get_id());
         return this->get_missing_texture();
     }
 }
References ENSURE, qtsdl::GuiImageProviderImpl::get_id(), openage::gui::GuiGameSpecImageProviderImpl::get_missing_texture(), get_texture(), and openage::gui::GuiGameSpecImageProviderImpl::loaded_game_spec.
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/integration/private/gui_game_spec_image_provider_by_id_impl.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/integration/private/gui_game_spec_image_provider_by_id_impl.cpp