openage: openage::EditorMode Class Reference
openage::EditorMode Class Reference
#include <game_control.h>
Public Member Functions
EditorMode (qtsdl::GuiItemLink *gui_link)
bool available () const override
void on_enter () override
void on_exit () override
void render () override
std::string name () const override
void on_game_control_set () override
void set_current_type_id (int current_type_id)
void set_current_terrain_id (openage::terrain_t current_terrain_id)
void set_paint_terrain (bool paint_terrain)
bool on_single_click (int button, coord::viewport point)
void announce_categories ()
void announce_category_content (const std::string &category_name)
Public Member Functions inherited from openage::OutputMode
OutputMode (qtsdl::GuiItemLink *gui_link)
virtual ~OutputMode ()
Public Member Functions inherited from openage::input::InputContext
InputContext ()
InputContext (InputManager *manager)
virtual ~InputContext ()=default
std::vector< std::string > active_binds () const
void bind (action_t type, const action_func_t act)
void bind (const Event &ev, const action_func_t act)
void bind (event_class ec, const action_check_t act)
bool execute_if_bound (const action_arg_t &e)
void register_to (InputManager *manager)
void unregister ()
Public Attributes
EditorModeSignals gui_signals
Public Attributes inherited from openage::OutputMode
OutputModeSignals gui_signals
qtsdl::GuiItemLink * gui_link
Public Attributes inherited from openage::input::InputContext
bool utf8_mode
Private Member Functions
virtual void announce () override
virtual void set_game_control (GameControl *game_control) override
void paint_terrain_at (const coord::viewport &point)
void paint_entity_at (const coord::viewport &point, const bool del)
Private Attributes
terrain_t editor_current_terrain
int current_type_id
std::string category
bool paint_terrain
Additional Inherited Members
Protected Attributes inherited from openage::OutputMode
GameControl * game_control
Detailed Description
UI mode to provide an interface for map editing.
Definition at line 277 of file game_control.h.
Constructor & Destructor Documentation
EditorMode()
openage::EditorMode::EditorMode (qtsdl::GuiItemLink * gui_link) explicit
Definition at line 538 of file game_control.cpp.
     :
     OutputMode{gui_link},
     editor_current_terrain{-1},
     current_type_id{-1},
     paint_terrain{},
     gui_signals{this} {}
References openage::OutputMode::gui_link.
Member Function Documentation
announce()
void openage::EditorMode::announce () override private virtual
Emit the "announced" signal with (name, InputContext::active_binds).
Reimplemented from openage::OutputMode.
Definition at line 675 of file game_control.cpp.
{
     OutputMode::announce();
     this->announce_categories();
 }
References openage::OutputMode::announce(), and announce_categories().
announce_categories()
void openage::EditorMode::announce_categories ()
Definition at line 651 of file game_control.cpp.
{
     if (this->game_control)
         if (auto player = this->game_control->get_current_player())
             emit this->gui_signals.categories_changed(player->civ->get_type_categories());
     emit this->gui_signals.categories_content_changed();
 }
References openage::EditorModeSignals::categories_changed(), openage::EditorModeSignals::categories_content_changed(), openage::OutputMode::game_control, openage::GameControl::get_current_player(), and gui_signals.
Referenced by announce(), openage::EditorModeSignals::on_current_player_name_changed(), and set_game_control().
announce_category_content()
void openage::EditorMode::announce_category_content (const std::string & category_name)
Definition at line 659 of file game_control.cpp.
{
     if (this->game_control)
         if (auto player = this->game_control->get_current_player()) {
             auto inds = player->civ->get_category(category_name);
             std::vector<std::tuple<index_t, uint16_t>> type_and_texture(inds.size());
             auto it = std::begin(type_and_texture);
             std::for_each(std::begin(inds), std::end(inds), [player, &it] (auto index) {
                 *it++ = std::make_tuple(index, player->get_type(index)->default_texture()->id);
             });
             emit this->gui_signals.category_content_changed(category_name, type_and_texture);
         }
 }
References openage::EditorModeSignals::category_content_changed(), openage::util::for_each(), openage::OutputMode::game_control, openage::GameControl::get_current_player(), and gui_signals.
Referenced by openage::gui::EditorModeLink::announce_category_content().
available()
bool openage::EditorMode::available () const override virtual
Is this mode able to be used?
Implements openage::OutputMode.
Definition at line 579 of file game_control.cpp.
{
     if (this->game_control == nullptr) {
         log::log(MSG(warn) << "game_control not yet linked to EditorMode");
         return false;
     }
     else if (this->game_control->get_engine()->get_game() != nullptr) {
         return true;
     }
     else {
         log::log(MSG(warn) << "Cannot enter editor mode without a game");
         return false;
     }
 }
References openage::OutputMode::game_control, openage::GameControl::get_engine(), openage::Engine::get_game(), openage::log::log(), MSG, and openage::log::warn().
name()
std::string openage::EditorMode::name () const override virtual
Used for displaying the current mode.
Implements openage::OutputMode.
Definition at line 599 of file game_control.cpp.
{
     return "Editor mode";
 }
Referenced by openage.util.fslike.path.Path::stem(), openage.util.fslike.path.Path::suffix(), and openage.util.fslike.path.Path::suffixes().
on_enter()
void openage::EditorMode::on_enter () override virtual
Called when switching to this mode.
Implements openage::OutputMode.
Definition at line 593 of file game_control.cpp.
 {}
on_exit()
void openage::EditorMode::on_exit () override virtual
Called when the mode is left.
Implements openage::OutputMode.
Definition at line 595 of file game_control.cpp.
 {}
on_game_control_set()
void openage::EditorMode::on_game_control_set () override virtual
Called after GameControl has been set by QML from set_game_control.
Implements openage::OutputMode.
Definition at line 547 of file game_control.cpp.
{
     Engine *engine = this->game_control->get_engine();
     auto &action = engine->get_action_manager();
     // bind required hotkeys
     this->bind(action.get("ENABLE_BUILDING_PLACEMENT"), [this](const input::action_arg_t &) {
         log::log(MSG(dbg) << "change category");
         emit this->gui_signals.toggle();
     });
     this->bind(input::event_class::MOUSE, [this, engine](const input::action_arg_t &arg) {
         if (arg.e.cc == input::ClassCode(input::event_class::MOUSE_BUTTON, 1) ||
             engine->get_input_manager().is_down(input::event_class::MOUSE_BUTTON, 1)) {
             if (this->paint_terrain) {
                 this->paint_terrain_at(arg.mouse.to_viewport(engine->coord));
             } else {
                 this->paint_entity_at(arg.mouse.to_viewport(engine->coord), false);
             }
             return true;
         }
         else if (arg.e.cc == input::ClassCode(input::event_class::MOUSE_BUTTON, 3) ||
             engine->get_input_manager().is_down(input::event_class::MOUSE_BUTTON, 3)) {
                 if (!this->paint_terrain) {
                     this->paint_entity_at(arg.mouse.to_viewport(engine->coord), true);
                 }
             return true;
         }
         return false;
     });
 }
References openage::input::InputContext::bind(), openage::input::Event::cc, openage::Engine::coord, openage::log::dbg(), openage::input::action_arg_t::e, openage::OutputMode::game_control, openage::Engine::get_action_manager(), openage::GameControl::get_engine(), openage::Engine::get_input_manager(), gui_signals, openage::input::InputManager::is_down(), openage::log::log(), openage::input::MOUSE, openage::input::action_arg_t::mouse, openage::input::MOUSE_BUTTON, MSG, paint_entity_at(), paint_terrain, paint_terrain_at(), openage::coord::input::to_viewport(), and openage::EditorModeSignals::toggle().
on_single_click()
bool openage::EditorMode::on_single_click (int button, coord::viewport point)
paint_entity_at()
void openage::EditorMode::paint_entity_at (const coord::viewport & point, const bool del) private
Definition at line 625 of file game_control.cpp.
{
     Engine *engine = this->game_control->get_engine();
     GameMain *game = engine->get_game();
     Terrain *terrain = game->terrain.get();
     auto mousepos_phys3 = point.to_phys3(engine->coord);
     auto mousepos_tile = mousepos_phys3.to_tile();
     TerrainChunk *chunk = terrain->get_create_chunk(mousepos_tile);
     // TODO : better detection of presence of unit
     if (!chunk->get_data(mousepos_tile.get_pos_on_chunk())->obj.empty()) {
         if (del) {
             // delete first object currently standing at the clicked position
             TerrainObject *obj = chunk->get_data(mousepos_tile.get_pos_on_chunk())->obj[0];
             obj->remove();
         }
     } else if (!del && this->current_type_id != -1) {
         Player *player = this->game_control->get_current_player();
         UnitType *selected_type = player->get_type(this->current_type_id);
         // tile is empty so try creating a unit
         UnitContainer *container = &game->placed_units;
         container->new_unit(*selected_type, *this->game_control->get_current_player(), mousepos_phys3);
     }
 }
References openage::curve::tests::container(), openage::Engine::coord, current_type_id, openage::OutputMode::game_control, openage::Terrain::get_create_chunk(), openage::GameControl::get_current_player(), openage::TerrainChunk::get_data(), openage::GameControl::get_engine(), openage::Engine::get_game(), openage::Player::get_type(), openage::GameMain::placed_units, openage::TerrainObject::remove(), openage::GameMain::terrain, openage::coord::viewport::to_phys3(), and openage::coord::phys3::to_tile().
Referenced by on_game_control_set().
paint_terrain_at()
void openage::EditorMode::paint_terrain_at (const coord::viewport & point) private
Definition at line 615 of file game_control.cpp.
{
     Engine *engine = this->game_control->get_engine();
     Terrain *terrain = engine->get_game()->terrain.get();
     auto mousepos_tile = point.to_tile(engine->coord);
     TerrainChunk *chunk = terrain->get_create_chunk(mousepos_tile);
     chunk->get_data(mousepos_tile.get_pos_on_chunk())->terrain_id = editor_current_terrain;
 }
References openage::Engine::coord, editor_current_terrain, openage::OutputMode::game_control, openage::Terrain::get_create_chunk(), openage::TerrainChunk::get_data(), openage::GameControl::get_engine(), openage::Engine::get_game(), openage::GameMain::terrain, and openage::coord::viewport::to_tile().
Referenced by on_game_control_set().
render()
void openage::EditorMode::render () override virtual
Display this mode.
Implements openage::OutputMode.
Definition at line 597 of file game_control.cpp.
 {}
set_current_terrain_id()
void openage::EditorMode::set_current_terrain_id (openage::terrain_t current_terrain_id)
Definition at line 607 of file game_control.cpp.
{
     this->editor_current_terrain = current_terrain_id;
 }
References editor_current_terrain.
Referenced by openage::gui::EditorModeLink::set_current_terrain_id().
set_current_type_id()
void openage::EditorMode::set_current_type_id (int current_type_id)
Definition at line 603 of file game_control.cpp.
{
     this->current_type_id = current_type_id;
 }
References current_type_id.
Referenced by openage::gui::EditorModeLink::set_current_type_id().
set_game_control()
void openage::EditorMode::set_game_control (GameControl * game_control) override private virtual
Called when the GameControl is set in QML.
Reimplemented from openage::OutputMode.
Definition at line 680 of file game_control.cpp.
{
     if (this->game_control != game_control) {
         if (this->game_control)
             QObject::disconnect(
                 &this->game_control->gui_signals,
                 &GameControlSignals::current_player_name_changed,
                 &this->gui_signals,
                 &EditorModeSignals::on_current_player_name_changed
             );
         // actually set the control
         OutputMode::set_game_control(game_control);
         if (this->game_control)
             QObject::connect(
                 &this->game_control->gui_signals,
                 &GameControlSignals::current_player_name_changed,
                 &this->gui_signals,
                 &EditorModeSignals::on_current_player_name_changed
             );
         this->announce_categories();
     }
     else {
         // just set the control
         OutputMode::set_game_control(game_control);
     }
 }
References announce_categories(), openage::GameControlSignals::current_player_name_changed(), openage::OutputMode::game_control, openage::GameControl::gui_signals, openage::EditorModeSignals::on_current_player_name_changed(), and openage::OutputMode::set_game_control().
set_paint_terrain()
void openage::EditorMode::set_paint_terrain (bool paint_terrain)
Definition at line 611 of file game_control.cpp.
{
     this->paint_terrain = paint_terrain;
 }
References paint_terrain.
Referenced by openage::gui::EditorModeLink::set_paint_terrain().
Member Data Documentation
category
std::string openage::EditorMode::category private
Definition at line 309 of file game_control.h.
current_type_id
int openage::EditorMode::current_type_id private
Definition at line 308 of file game_control.h.
Referenced by paint_entity_at(), and set_current_type_id().
editor_current_terrain
terrain_t openage::EditorMode::editor_current_terrain private
currently selected terrain id
Definition at line 307 of file game_control.h.
Referenced by paint_terrain_at(), and set_current_terrain_id().
gui_signals
EditorModeSignals openage::EditorMode::gui_signals
Definition at line 319 of file game_control.h.
Referenced by announce_categories(), announce_category_content(), and on_game_control_set().
paint_terrain
bool openage::EditorMode::paint_terrain private
mouse click mode: true = terrain painting, false = unit placement
Definition at line 316 of file game_control.h.
Referenced by on_game_control_set(), and set_paint_terrain().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/game_control.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/game_control.cpp