openage: openage::util::compress::BitStream< inbuf_size > Class Template Reference
openage::util::compress::BitStream< inbuf_size > Class Template Reference
#include <bitstream.h>
Public Member Functions
BitStream (read_callback_t read_callback)
unsigned read_bits (unsigned int nbits)
unsigned read_bytes (unsigned char *buf, unsigned count)
unsigned char read_single_byte ()
unsigned int read_4bytes_le ()
void switch_to_bitstream_mode ()
void switch_to_bytestream_mode ()
void align_if_in_bitstream_mode ()
Public Attributes
unsigned char eof
Private Member Functions
unsigned int input_bytes_available ()
void ensure_input_bytes ()
void load_next_16_bits ()
void ensure_bits (unsigned int nbits)
unsigned peek_bits (unsigned int nbits)
void remove_bits (unsigned int nbits)
void align_bitstream (unsigned int min_discard=0)
Private Attributes
read_callback_t read_callback
unsigned char inbuf [inbuf_size]
unsigned char * i_ptr
unsigned char * i_end
unsigned int bit_buffer
unsigned int bits_left
size_t stream_position
bool bitstream_mode
Friends
template<unsigned maxsymbols_p, unsigned tablebits_p, bool allow_empty>
class HuffmanTable
Detailed Description
template<unsigned int inbuf_size>
class openage::util::compress::BitStream< inbuf_size >
Bitstream that is stored in 16-bit little-endian numbers. There are two modes:
Bit stream
This is the default mode. Bits may be retrieved via read_bits().
The input bytes
0babcdefgh 0bijklmnop 0bmnopqrst 0buvwxyzAB
are decoded to the following bitstream:
ijkl mnop abcd efgh uvwx yzAB mnop qrst
Someone should get a medal for this.
Byte stream
In bytestream mode, read_bytes() can be used to read any number of bytes, verbatim, from the data source.
Mode switching
You can switch between modes via
switch_to_bytestream_mode()
switch_to_bitstream_mode()
Every modeswitch aligns the stream to a 16-bit boundary by discarding the appropriate amount of nullbits/nullbytes. Calling the modeswitch methods while already in the respective mode does nothing.
Definition at line 69 of file bitstream.h.
Constructor & Destructor Documentation
BitStream()
template<unsigned int inbuf_size> openage::util::compress::BitStream< inbuf_size >::BitStream (read_callback_t read_callback) inline
Definition at line 295 of file bitstream.h.
         :
         eof{false},
         read_callback{read_callback},
         i_ptr{inbuf},
         i_end{inbuf},
         bit_buffer{0},
         bits_left{0},
         stream_position{0},
         bitstream_mode{true} {
         static_assert(inbuf_size >= 2, "inbuf size must be at least 2");
         static_assert(inbuf_size % 2 == 0, "inbuf size must be even");
     }
Member Function Documentation
align_bitstream()
template<unsigned int inbuf_size> void openage::util::compress::BitStream< inbuf_size >::align_bitstream (unsigned int min_discard = 0) inline private
for use in bitstream mode.
Aligns the bitstream to the next multiple of 2 bytes.
If min_discard is given, at least that amount of bits is discarded.
Definition at line 269 of file bitstream.h.
{
         unsigned int nbits = this->stream_position % 16;
         if (nbits != 0) {
             nbits = 16 - nbits;
         }
         while (unlikely(nbits < min_discard)) {
             nbits += 16;
         }
         if (nbits == 0) {
             return;
         }
         if (this->peek_bits(nbits)) {
             auto errmsg = MSG(err);
             errmsg << "attempted to discard " << nbits << " non-null bits: ";
             for (unsigned ctr = 1; ctr <= nbits; ctr++) {
                 errmsg << (this->peek_bits(ctr) & 1);
             }
             throw Error(errmsg);
         }
         this->remove_bits(nbits);
     }
Referenced by openage::util::compress::BitStream< 4096 >::align_if_in_bitstream_mode(), and openage::util::compress::BitStream< 4096 >::switch_to_bytestream_mode().
align_if_in_bitstream_mode()
template<unsigned int inbuf_size> void openage::util::compress::BitStream< inbuf_size >::align_if_in_bitstream_mode () inline
Aligns the bitstream - that is, if we're currenlty in bitstream mode.
Otherwise, a no-op.
Definition at line 428 of file bitstream.h.
{
         if (this->bitstream_mode == true) {
             this->align_bitstream();
         }
     }
Referenced by openage::util::compress::LZXDStream::decompress_next_frame().
ensure_bits()
template<unsigned int inbuf_size> void openage::util::compress::BitStream< inbuf_size >::ensure_bits (unsigned int nbits) inline private
for use in bitstream mode.
ensures there are at least nbits bits in the bit buffer.
Definition at line 214 of file bitstream.h.
{
         if (unlikely(!this->bitstream_mode)) {
             throw Error(MSG(err) << "instream: attempted to ensure bits while in bytestream mode");
         }
         while (bits_left < nbits) {
             this->load_next_16_bits();
         }
     }
Referenced by openage::util::compress::BitStream< 4096 >::peek_bits(), and openage::util::compress::BitStream< 4096 >::remove_bits().
ensure_input_bytes()
template<unsigned int inbuf_size> void openage::util::compress::BitStream< inbuf_size >::ensure_input_bytes () inline private
ensures that at least one byte is available in the input byte buffer.
returns the amount of available bytes.
Definition at line 140 of file bitstream.h.
{
         // check if we need to actually read some bytes.
         if (this->input_bytes_available() == 0) {
             // fill the entire input buffer.
             size_t read_bytes = this->read_callback(this->inbuf, inbuf_size);
             // we might overrun the input stream by asking for bits we don't use,
             // so fake 2 more bytes at the end of input
             if (unlikely(read_bytes == 0)) {
                 if (this->eof) {
                     throw Error(MSG(err) << "Unexpected EOF in the middle of a block");
                 } else {
                     read_bytes = 2;
                     this->inbuf[0] = 0;
                     this->inbuf[1] = 0;
                     this->eof = true;
                 }
             }
             if (unlikely(read_bytes > (int) inbuf_size)) {
                 throw Error(MSG(err) << "read() returned more data than requested");
             }
             // update i_ptr and i_end
             this->i_ptr = this->inbuf;
             this->i_end = &this->inbuf[read_bytes];
         }
         // check if the reading was successful.
         if (unlikely(this->i_ptr >= this->i_end)) {
             throw Error(MSG(err) << "input byte buffer empty: failed to ensure_input_bytes");
         }
     }
Referenced by openage::util::compress::BitStream< 4096 >::load_next_16_bits(), and openage::util::compress::BitStream< 4096 >::read_bytes().
input_bytes_available()
template<unsigned int inbuf_size> unsigned int openage::util::compress::BitStream< inbuf_size >::input_bytes_available () inline private
returns the number of bytes that are available in the input byte buffer.
Definition at line 127 of file bitstream.h.
{
         if (unlikely(this->i_ptr > this->i_end)) {
             throw Error(MSG(err) << "input byte buffer state invalid: i_ptr > i_end");
         }
         return this->i_end - this->i_ptr;
     }
Referenced by openage::util::compress::BitStream< 4096 >::ensure_input_bytes(), and openage::util::compress::BitStream< 4096 >::read_bytes().
load_next_16_bits()
template<unsigned int inbuf_size> void openage::util::compress::BitStream< inbuf_size >::load_next_16_bits () inline private
for use in bitstream mode.
loads the next 16-bit value into the bitstream.
Definition at line 185 of file bitstream.h.
{
         // example: input stream contains bytes A, B. previous byte was J.
         //
         // 5 bits are left
         // bit buffer is:                     jjjjj000 00000000 00000000 00000000
         //
         // ensure_bits(9) is called.
         // b0 = aaaaaaaa
         // b1 = bbbbbbbb
         // bit_buffer |= bbbbbbbb aaaaaaaa << (32 - 16 - 5) == 11
         //
         // new bit buffer:                    jjjjjbbb bbbbbaaa aaaaa000 00000000
         // read two bytes to b0, b1
         this->ensure_input_bytes();
         unsigned char b0 = *i_ptr++;
         this->ensure_input_bytes();
         unsigned char b1 = *i_ptr++;
         // inject bits into bit_buffer
         bit_buffer |= ((b1 << 8) | b0) << (sizeof(bit_buffer) * 8 - 16 - bits_left);
         bits_left += 16;
     }
Referenced by openage::util::compress::BitStream< 4096 >::ensure_bits().
peek_bits()
template<unsigned int inbuf_size> unsigned openage::util::compress::BitStream< inbuf_size >::peek_bits (unsigned int nbits) inline private
for use in bitstream mode.
returns nbits bits from the bit buffer, without removing them.
Definition at line 229 of file bitstream.h.
{
         // example: bit buffer is:   abcdefgh ijkl0000 00000000 00000000
         //
         // peek_bits(3) is called.
         //
         // return (bit_buffer >> (32 - 3) == 29
         //
         // returned value is:        abc
         this->ensure_bits(nbits);
         return (bit_buffer >> (sizeof(bit_buffer) * 8 - nbits));
     }
Referenced by openage::util::compress::BitStream< 4096 >::align_bitstream(), and openage::util::compress::BitStream< 4096 >::read_bits().
read_4bytes_le()
template<unsigned int inbuf_size> unsigned int openage::util::compress::BitStream< inbuf_size >::read_4bytes_le () inline
for use in bytestream mode.
reads a little-endian-encoded 4-byte number and returns it.
Definition at line 368 of file bitstream.h.
{
         unsigned int result;
         result  = this->read_single_byte() <<  0;
         result |= this->read_single_byte() <<  8;
         result |= this->read_single_byte() << 16;
         result |= this->read_single_byte() << 24;
         return result;
     }
Referenced by openage::util::compress::LZXDStream::init_next_block().
read_bits()
template<unsigned int inbuf_size> unsigned openage::util::compress::BitStream< inbuf_size >::read_bits (unsigned int nbits) inline
for use in bitstream mode.
takes nbits bits from the bit buffer and returns them.
Definition at line 315 of file bitstream.h.
{
         unsigned ret = peek_bits(nbits);
         remove_bits(nbits);
         return ret;
     }
Referenced by openage::util::compress::LZXDStream::decode_symbol_from_aligned_block(), openage::util::compress::LZXDStream::decode_symbol_from_verbatim_block(), openage::util::compress::LZXDStream::decompress_next_frame(), and openage::util::compress::LZXDStream::init_next_block().
read_bytes()
template<unsigned int inbuf_size> unsigned openage::util::compress::BitStream< inbuf_size >::read_bytes (unsigned char * buf, unsigned count) inline
for use in bytestream mode.
reads up to count verbatim bytes from the input byte buffer, and writes them to *buf.
reads at least 1 and at most count bytes.
Definition at line 329 of file bitstream.h.
{
         if (unlikely(this->bitstream_mode == true)) {
             throw Error(MSG(err) << "attempt to read_bytes while in bitstream mode");
         }
         this->ensure_input_bytes();
         unsigned int available = this->input_bytes_available();
         if (available < count) {
             count = available;
         }
         memcpy(buf, this->i_ptr, count);
         this->i_ptr += count;
         this->stream_position += count;
         return count;
     }
Referenced by openage::util::compress::BitStream< 4096 >::ensure_input_bytes(), openage::util::compress::LZXDStream::read_data_from_uncompressed_block(), and openage::util::compress::BitStream< 4096 >::read_single_byte().
read_single_byte()
template<unsigned int inbuf_size> unsigned char openage::util::compress::BitStream< inbuf_size >::read_single_byte () inline
for use in bytestream mode.
reads a single verbatim byte from the input byte buffer, and returns it.
Definition at line 353 of file bitstream.h.
{
         unsigned char buf;
         if (unlikely(this->read_bytes(&buf, 1) != 1)) {
             throw Error(MSG(err) << "failed to read single byte in bytestream mode");
         }
         return buf;
     }
Referenced by openage::util::compress::BitStream< 4096 >::read_4bytes_le(), and openage::util::compress::BitStream< 4096 >::switch_to_bitstream_mode().
remove_bits()
template<unsigned int inbuf_size> void openage::util::compress::BitStream< inbuf_size >::remove_bits (unsigned int nbits) inline private
for use in bitstream mode.
removes nbits bits from the bit buffer.
Definition at line 247 of file bitstream.h.
{
         // example: bit buffer is:  abcdefgh ijkl0000 00000000 00000000
         //
         // remove_bits(3) is called.
         //
         // bit_buffer <<= 3
         //
         // resulting bit buffer is: defghijk l0000000 00000000 00000000
         this->ensure_bits(nbits);
         bit_buffer <<= nbits;
         bits_left -= nbits;
         this->stream_position += nbits;
     }
Referenced by openage::util::compress::BitStream< 4096 >::align_bitstream(), and openage::util::compress::BitStream< 4096 >::read_bits().
switch_to_bitstream_mode()
template<unsigned int inbuf_size> void openage::util::compress::BitStream< inbuf_size >::switch_to_bitstream_mode () inline
Switches to bitstream mode.
If the previous bytestream had an odd size, one byte is discarded first.
Definition at line 384 of file bitstream.h.
{
         if (this->bitstream_mode == true) {
             return;
         }
         if (this->stream_position & 1) {
             // bytestream hat odd length; discard one nullbyte.
             unsigned char data = this->read_single_byte();
             if (data != 0) {
                 throw Error(MSG(err).fmt("attempted to discard a non-zero byte at end of bytestream: %02x", data));
             }
         }
         this->bitstream_mode = true;
         this->stream_position = 0;
     }
Referenced by openage::util::compress::LZXDStream::init_next_block().
switch_to_bytestream_mode()
template<unsigned int inbuf_size> void openage::util::compress::BitStream< inbuf_size >::switch_to_bytestream_mode () inline
Switches to bytestream mode.
Discards 1 to 16 bits to align the bitstream first.
Definition at line 406 of file bitstream.h.
{
         if (this->bitstream_mode == false) {
             return;
         }
         // for some weird reason, the alignment padding here is 1 to 16 bits, not 0 to 15.
         // thus, discard an additional bit.
         this->align_bitstream(1);
         this->bitstream_mode = false;
         this->stream_position = 0;
         if (this->bits_left) {
             throw Error(MSG(err) << "bits left after switching to bytestream mode: " << this->bits_left);
         }
     }
Referenced by openage::util::compress::LZXDStream::init_next_block().
Friends And Related Function Documentation
HuffmanTable
template<unsigned int inbuf_size> template<unsigned maxsymbols_p, unsigned tablebits_p, bool allow_empty> friend class HuffmanTable friend
Definition at line 178 of file bitstream.h.
Member Data Documentation
bit_buffer
template<unsigned int inbuf_size> unsigned int openage::util::compress::BitStream< inbuf_size >::bit_buffer private
Bit buffer; used in bitstream mode. Filled by via get_next_byte() via ensure_bits(), read by peak_bits(), cleared by remove_bits().
Definition at line 104 of file bitstream.h.
Referenced by openage::util::compress::BitStream< 4096 >::load_next_16_bits(), openage::util::compress::BitStream< 4096 >::peek_bits(), and openage::util::compress::BitStream< 4096 >::remove_bits().
bits_left
template<unsigned int inbuf_size> unsigned int openage::util::compress::BitStream< inbuf_size >::bits_left private
The number of valid bits in bit_buffer. If e.g. the value is 2, only the two most significant bits of bit_buffer are set.
Definition at line 111 of file bitstream.h.
Referenced by openage::util::compress::BitStream< 4096 >::ensure_bits(), openage::util::compress::BitStream< 4096 >::load_next_16_bits(), and openage::util::compress::BitStream< 4096 >::remove_bits().
bitstream_mode
template<unsigned int inbuf_size> bool openage::util::compress::BitStream< inbuf_size >::bitstream_mode private
If set, the bitstream is currently in bytestream mode.
Definition at line 122 of file bitstream.h.
eof
template<unsigned int inbuf_size> unsigned char openage::util::compress::BitStream< inbuf_size >::eof
true if the read callback has returned EOF.
Definition at line 74 of file bitstream.h.
Referenced by openage::util::compress::LZXDStream::decompress_next_frame(), openage.codegen.codegen.WriteCatcher::read(), openage.util.filelike.fifo.FIFO::read(), openage.util.filelike.fifo.FIFO::seteof(), and openage.util.filelike.fifo.FIFO::write().
i_end
template<unsigned int inbuf_size> unsigned char* openage::util::compress::BitStream< inbuf_size >::i_end private
Pointer to end of valid data in inbuf.
Definition at line 96 of file bitstream.h.
i_ptr
template<unsigned int inbuf_size> unsigned char* openage::util::compress::BitStream< inbuf_size >::i_ptr private
Pointer to current position in inbuf.
Definition at line 91 of file bitstream.h.
Referenced by openage::util::compress::BitStream< 4096 >::input_bytes_available(), and openage::util::compress::BitStream< 4096 >::load_next_16_bits().
inbuf
template<unsigned int inbuf_size> unsigned char openage::util::compress::BitStream< inbuf_size >::inbuf[inbuf_size] private
Input byte buffer. Used by both modes (via ensure_bits and read_bytes).
Definition at line 86 of file bitstream.h.
Referenced by openage::util::compress::BitStream< 4096 >::ensure_input_bytes().
read_callback
template<unsigned int inbuf_size> read_callback_t openage::util::compress::BitStream< inbuf_size >::read_callback private
read callback function; invoked whenever the input buffer is empty.
Definition at line 80 of file bitstream.h.
Referenced by openage::util::compress::BitStream< 4096 >::ensure_input_bytes().
stream_position
template<unsigned int inbuf_size> size_t openage::util::compress::BitStream< inbuf_size >::stream_position private
counts the number of bits (in bitstream mode) or bytes (in bytestream mode), for determining the correct number of bits/bytes to discard.
Definition at line 117 of file bitstream.h.
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/compress/bitstream.h