openage: openage::log::LogSource Class Reference
openage::log::LogSource Class Reference abstract
#include <logsource.h>
Public Member Functions
LogSource ()
virtual ~LogSource ()=default
void log (const message &msg)
virtual std::string logsource_name ()=0
Public Attributes
const size_t logger_id
Static Private Member Functions
static size_t get_unique_logger_id ()
Detailed Description
Any class that wants to provide .log() shall inherit from this. Examples: Engine, Unit, ...
pxd:
cppclass LogSource: void log(message msg) except + const size_t logger_id string logsource_name() except +
Definition at line 27 of file logsource.h.
Constructor & Destructor Documentation
LogSource()
openage::log::LogSource::LogSource ()
Definition at line 14 of file logsource.cpp.
     :
     logger_id{LogSource::get_unique_logger_id()} {}
References get_unique_logger_id().
~LogSource()
virtual openage::log::LogSource::~LogSource () virtual default
Member Function Documentation
get_unique_logger_id()
size_t openage::log::LogSource::get_unique_logger_id () static private
Provides unique logger ids.
Definition at line 28 of file logsource.cpp.
{
     // Strictly-monotonically increasing counter.
     static std::atomic<size_t> ctr{0};
     return ctr++;
 }
Referenced by LogSource().
log()
void openage::log::LogSource::log (const message & msg)
Logs a message (get one via MSG(level)).
Definition at line 19 of file logsource.cpp.
{
     // ensure that the global stdoutsink has been constructed
     // (and thus at least one sink exists).
     global_stdoutsink();
     LogSinkList::instance().log(msg, this);
 }
References openage::log::global_stdoutsink(), openage::log::LogSinkList::instance(), and openage::log::LogSinkList::log().
Referenced by openage::log::tests::demo(), openage::Unit::draw(), openage::AttackAction::fire_projectile(), openage::ObjectProducer::initialise(), openage::BuildingProducer::initialise(), openage::MoveAbility::invoke(), openage::GarrisonAbility::invoke(), openage::UngarrisonAbility::invoke(), openage::TrainAbility::invoke(), openage::BuildAbility::invoke(), openage::GatherAbility::invoke(), openage::AttackAbility::invoke(), openage::RepairAbility::invoke(), openage::HealAbility::invoke(), openage::PatrolAbility::invoke(), openage::ConvertAbility::invoke(), openage::log::log(), openage::BuildingProducer::make_annex(), openage::GatherAction::nearest_dropsite(), openage::BuildAction::on_completion(), openage::GatherAction::on_completion_in_range(), openage::ObjectProducer::place(), openage::NyanType::place(), openage::MoveAction::update(), and openage::TerrainObject::~TerrainObject().
logsource_name()
virtual std::string openage::log::LogSource::logsource_name () pure virtual
Implemented in openage::Unit, openage::log::NamedLogSource, and openage::log::tests::TestLogSource.
Referenced by openage::log::FileSink::output_log_message(), and openage::log::StdOutSink::output_log_message().
Member Data Documentation
logger_id
const size_t openage::log::LogSource::logger_id
Initialized during the LogSource constructor, guaranteed to be unique.
Definition at line 43 of file logsource.h.
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/log/logsource.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/log/logsource.cpp