openage: qtsdl::GuiInputImpl Class Reference
qtsdl::GuiInputImpl Class Reference
#include <gui_input_impl.h>
Signals
void input_event (std::atomic< bool > *processed, QEvent *ev, bool only_if_grabbed=false)
Public Member Functions
GuiInputImpl (GuiRenderer *renderer, GuiEventQueue *game_logic_updater)
virtual ~GuiInputImpl ()
bool process (SDL_Event *e)
Private Member Functions
bool relay_input_event (QEvent *ev, bool only_if_grabbed=false)
Private Attributes
Qt::MouseButtons mouse_buttons_state
GuiEventQueueImpl * game_logic_updater
Detailed Description
Definition at line 17 of file gui_input_impl.h.
Constructor & Destructor Documentation
GuiInputImpl()
qtsdl::GuiInputImpl::GuiInputImpl (GuiRenderer * renderer, GuiEventQueue * game_logic_updater) explicit
Definition at line 18 of file gui_input_impl.cpp.
     :
     QObject{},
     mouse_buttons_state{},
     game_logic_updater{GuiEventQueueImpl::impl(game_logic_updater)} {
     const bool logic_diff_input = this->game_logic_updater->get_thread() != QThread::currentThread();
     const bool gui_diff_input = QCoreApplication::instance()->thread() != QThread::currentThread();
     const Qt::ConnectionType input_to_gui = gui_diff_input ? logic_diff_input ? Qt::BlockingQueuedConnection : Qt::QueuedConnection : Qt::DirectConnection;
     QObject::connect(this, &GuiInputImpl::input_event, GuiRendererImpl::impl(renderer)->get_window(), &EventHandlingQuickWindow::on_input_event, input_to_gui);
 }
~GuiInputImpl()
qtsdl::GuiInputImpl::~GuiInputImpl () virtual
Definition at line 31 of file gui_input_impl.cpp.
{
 }
Member Function Documentation
input_event
void qtsdl::GuiInputImpl::input_event (std::atomic< bool > * processed, QEvent * ev, bool only_if_grabbed = false) signal
Referenced by relay_input_event().
process()
bool qtsdl::GuiInputImpl::process (SDL_Event * e)
Returns true if the event was accepted.
Definition at line 88 of file gui_input_impl.cpp.
{
     switch (e->type) {
     case SDL_MOUSEMOTION: {
         QMouseEvent ev{QEvent::MouseMove, QPoint{e->motion.x, e->motion.y}, Qt::MouseButton::NoButton, this->mouse_buttons_state = sdl_mouse_state_to_qt(e->motion.state), Qt::KeyboardModifier::NoModifier};
         ev.setAccepted(false);
         // Allow dragging stuff under the gui overlay.
         return relay_input_event(&ev, e->motion.state & (SDL_BUTTON_LMASK | SDL_BUTTON_MMASK | SDL_BUTTON_RMASK));
         break;
     }
     case SDL_MOUSEBUTTONDOWN: {
         auto button = sdl_mouse_btn_to_qt(e->button.button);
         QMouseEvent ev{QEvent::MouseButtonPress, QPoint{e->button.x, e->button.y}, button, this->mouse_buttons_state |= button, Qt::KeyboardModifier::NoModifier};
         ev.setAccepted(false);
         bool accepted = relay_input_event(&ev);
         if (e->button.clicks == 2) {
             QMouseEvent ev_dbl{QEvent::MouseButtonDblClick, QPoint{e->button.x, e->button.y}, button, this->mouse_buttons_state, Qt::KeyboardModifier::NoModifier};
             ev_dbl.setAccepted(false);
             accepted = relay_input_event(&ev_dbl) || accepted;
         }
         return accepted;
         break;
     }
     case SDL_MOUSEBUTTONUP: {
         auto button = sdl_mouse_btn_to_qt(e->button.button);
         QMouseEvent ev{QEvent::MouseButtonRelease, QPoint{e->button.x, e->button.y}, button, this->mouse_buttons_state &= ~button, Qt::KeyboardModifier::NoModifier};
         ev.setAccepted(false);
         // Allow dragging stuff under the gui overlay: when no item is grabbed, it probably means that initial MousButtonPress was outside gui.
         return relay_input_event(&ev, true);
         break;
     }
     case SDL_MOUSEWHEEL: {
         QPoint pos;
         SDL_GetMouseState(&pos.rx(), &pos.ry());
         QWheelEvent ev{pos, pos, QPoint{}, QPoint{e->wheel.x, e->wheel.y}, 0, Qt::Orientation{}, this->mouse_buttons_state, Qt::KeyboardModifier::NoModifier};
         ev.setAccepted(false);
         return relay_input_event(&ev);
         break;
     }
     case SDL_KEYDOWN: {
         QKeyEvent ev{QEvent::KeyPress, sdl_key_to_qt(e->key.keysym.sym), Qt::NoModifier, QChar((short) e->key.keysym.sym)};
         ev.setAccepted(false);
         return relay_input_event(&ev);
         break;
     }
     case SDL_KEYUP: {
         QKeyEvent ev{QEvent::KeyRelease, sdl_key_to_qt(e->key.keysym.sym), Qt::NoModifier, QChar((short) e->key.keysym.sym)};
         ev.setAccepted(false);
         return relay_input_event(&ev);
         break;
     }
     default:
         break;
     }
     return false;
 }
References mouse_buttons_state, and relay_input_event().
relay_input_event()
bool qtsdl::GuiInputImpl::relay_input_event (QEvent * ev, bool only_if_grabbed = false) private
Todo:
if/when the logic thread or input thread of the main game is made separate, give mutex or queue to the gui in order to replace this busy wait.
Definition at line 159 of file gui_input_impl.cpp.
{
     const bool logic_diff_input = this->game_logic_updater->get_thread() != QThread::currentThread();
     std::atomic<bool> processed{false};
     emit this->input_event(&processed, ev, only_if_grabbed);
     // We have sent an event to the gui thread and want a response about collision. But the gui can be
     // executing a getter that blocks the gui thread while doing something in the logic thread.
     // So, if the logic thread is the same as the input thread, it should be running somehow.
     //
     if (!logic_diff_input)
         while (!processed) {
             this->game_logic_updater->process_callbacks();
             QThread::usleep(1);
         }
     return ev->isAccepted();
 }
References game_logic_updater, qtsdl::GuiEventQueueImpl::get_thread(), input_event(), and qtsdl::GuiEventQueueImpl::process_callbacks().
Referenced by process().
Member Data Documentation
game_logic_updater
GuiEventQueueImpl* qtsdl::GuiInputImpl::game_logic_updater private
Definition at line 36 of file gui_input_impl.h.
Referenced by relay_input_event().
mouse_buttons_state
Qt::MouseButtons qtsdl::GuiInputImpl::mouse_buttons_state private
Definition at line 35 of file gui_input_impl.h.
Referenced by process().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/guisys/private/gui_input_impl.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/guisys/private/gui_input_impl.cpp