openage: qtsdl::GuiListModel Class Reference
qtsdl::GuiListModel Class Reference
Adapts core that uses a property map to QAbstractListModel interface.
#include <gui_list_model.h>
Public Slots
void on_property_changed (const QByteArray &name, const QVariant &value)
Signals
void changed_from_gui (const char *name, const QVariant &value)
Public Member Functions
GuiListModel (QObject *parent=nullptr)
virtual ~GuiListModel ()
void set (const std::vector< std::tuple< QByteArray, QVariant >> &values)
Public Member Functions inherited from qtsdl::GuiItemBase
virtual ~GuiItemBase ()
Public Member Functions inherited from qtsdl::DeferredInitialConstantPropertyValues
DeferredInitialConstantPropertyValues ()
virtual ~DeferredInitialConstantPropertyValues ()
Is virtual to be able to catch the error when non-persistent item uses liveReloadTag.
void apply_static_properties ()
Execute saved static properties assignments (for newly created cores).
void clear_static_properties ()
Clear saved static properties assignments (for cores that existed before the GUI reload).
bool is_init_over () const
Public Member Functions inherited from qtsdl::GuiItemLink
virtual ~GuiItemLink ()
Private Member Functions
virtual int rowCount (const QModelIndex &) const override
virtual Qt::ItemFlags flags (const QModelIndex &index) const override
virtual QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
virtual bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole) override
Private Attributes
std::vector< std::tuple< QByteArray, QVariant > > values
Additional Inherited Members
Protected Attributes inherited from qtsdl::GuiItemBase
GameLogicCaller game_logic_caller
std::function< std::unique_ptr< PersistentCoreHolderBase >)> instantiate_core_func
std::function< void(PersistentCoreHolderBase *, const QString &)> do_adopt_core_func
std::function< void()> on_core_adopted_func
Protected Attributes inherited from qtsdl::DeferredInitialConstantPropertyValues
bool init_over
std::vector< std::function< void()> > static_properties_assignments
Detailed Description
Adapts core that uses a property map to QAbstractListModel interface.
Definition at line 17 of file gui_list_model.h.
Constructor & Destructor Documentation
GuiListModel()
qtsdl::GuiListModel::GuiListModel (QObject * parent = nullptr)
Definition at line 9 of file gui_list_model.cpp.
     :
     QAbstractListModel{parent} {
 }
~GuiListModel()
qtsdl::GuiListModel::~GuiListModel () virtual
Definition at line 14 of file gui_list_model.cpp.
{
 }
Member Function Documentation
changed_from_gui
void qtsdl::GuiListModel::changed_from_gui (const char * name, const QVariant & value) signal
Referenced by qtsdl::GuiItemListModel< GeneratorLink >::establish_from_gui_propagation(), and setData().
data()
QVariant qtsdl::GuiListModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override private virtual
Definition at line 52 of file gui_list_model.cpp.
{
     switch (role) {
     case Qt::DisplayRole:
         return std::get<QByteArray>(this->values[index.row()]);
         break;
     case Qt::EditRole: {
         return std::get<QVariant>(this->values[index.row()]);
         break;
     }
     default:
         break;
     }
     return QVariant{};
 }
References values.
Referenced by openage.convert.peresource.PEResources::read_directory().
flags()
Qt::ItemFlags qtsdl::GuiListModel::flags (const QModelIndex & index) const override private virtual
Definition at line 48 of file gui_list_model.cpp.
{
     return Qt::ItemIsEditable | this->QAbstractListModel::flags(index);
 }
on_property_changed
void qtsdl::GuiListModel::on_property_changed (const QByteArray & name, const QVariant & value) slot
Definition at line 23 of file gui_list_model.cpp.
{
     auto foundIt = std::find_if(std::begin(this->values), std::end(this->values), [&name] (std::tuple<QByteArray, QVariant>& p) {
         return std::get<QByteArray>(p) == name;
     });
     if (foundIt != std::end(this->values)) {
         auto &current_value = std::get<QVariant>(*foundIt);
         if (current_value != value) {
             current_value = value;
             auto i = this->index(std::distance(std::begin(this->values), foundIt));
             emit this->dataChanged(i, i, {Qt::EditRole});
         }
     } else {
         this->beginInsertRows(QModelIndex(), this->values.size(), this->values.size());
         this->values.emplace(std::end(this->values), name, value);
         this->endInsertRows();
     }
 }
References values.
Referenced by qtsdl::GuiItemListModel< GeneratorLink >::establish_to_gui_propagation().
rowCount()
int qtsdl::GuiListModel::rowCount (const QModelIndex &) const override private virtual
Definition at line 44 of file gui_list_model.cpp.
{
     return values.size();
 }
References values.
set()
void qtsdl::GuiListModel::set (const std::vector< std::tuple< QByteArray, QVariant >> & values)
Definition at line 17 of file gui_list_model.cpp.
{
     this->beginResetModel();
     this->values = values;
     this->endResetModel();
 }
References values.
setData()
bool qtsdl::GuiListModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) override private virtual
Definition at line 70 of file gui_list_model.cpp.
{
     if (role == Qt::EditRole) {
         auto &property = this->values[index.row()];
         emit this->changed_from_gui(std::get<QByteArray>(property), std::get<QVariant>(property) = value);
         return true;
     }
     return false;
 }
References changed_from_gui(), and values.
Member Data Documentation
values
std::vector<std::tuple<QByteArray, QVariant> > qtsdl::GuiListModel::values private
Definition at line 38 of file gui_list_model.h.
Referenced by data(), openage.convert.dataformat.members.EnumMember::format_hash(), openage.convert.dataformat.members.EnumMember::get_parsers(), openage.convert.dataformat.members.EnumMember::get_snippets(), on_property_changed(), rowCount(), set(), setData(), and openage.convert.dataformat.members.EnumMember::validate_value().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/guisys/link/gui_list_model.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/guisys/link/gui_list_model.cpp