openage: openage::gui::GuiTextureFactory Class Reference
openage::gui::GuiTextureFactory Class Reference
#include <gui_texture_factory.h>
Public Member Functions
GuiTextureFactory (GuiGameSpecImageProviderImpl *provider, const QString &id, const QSize &requested_size)
virtual ~GuiTextureFactory ()
virtual QSGTexture * createTexture (QQuickWindow *window) const override
virtual int textureByteCount () const override
virtual QSize textureSize () const override
Private Attributes
SizedTextureHandle texture_handle
GuiFilledTextureHandleUser texture_handle_user
Detailed Description
Definition at line 17 of file gui_texture_factory.h.
Constructor & Destructor Documentation
GuiTextureFactory()
openage::gui::GuiTextureFactory::GuiTextureFactory (GuiGameSpecImageProviderImpl * provider, const QString & id, const QSize & requested_size) explicit
Definition at line 13 of file gui_texture_factory.cpp.
     :
     texture_handle(),
     texture_handle_user{provider->fill_texture_handle(id, requested_size, &this->texture_handle)} {
 }
References openage::gui::GuiGameSpecImageProviderImpl::fill_texture_handle(), and texture_handle.
~GuiTextureFactory()
openage::gui::GuiTextureFactory::~GuiTextureFactory () virtual
Definition at line 19 of file gui_texture_factory.cpp.
{
 }
Member Function Documentation
createTexture()
QSGTexture * openage::gui::GuiTextureFactory::createTexture (QQuickWindow * window) const override virtual
Definition at line 22 of file gui_texture_factory.cpp.
{
     Q_UNUSED(window);
     return new GuiTexture{this->texture_handle};
 }
References texture_handle.
textureByteCount()
int openage::gui::GuiTextureFactory::textureByteCount () const override virtual
Definition at line 27 of file gui_texture_factory.cpp.
{
     // assume 32bit textures
     return this->texture_handle.texture->w * this->texture_handle.texture->h * 4;
 }
References openage::Texture::h, openage::gui::TextureHandle::texture, texture_handle, and openage::Texture::w.
textureSize()
QSize openage::gui::GuiTextureFactory::textureSize () const override virtual
Definition at line 32 of file gui_texture_factory.cpp.
{
     return openage::gui::textureSize(this->texture_handle);
 }
References texture_handle, and openage::gui::textureSize().
Referenced by openage::gui::GuiGameSpecImageProviderImpl::requestTexture().
Member Data Documentation
texture_handle
SizedTextureHandle openage::gui::GuiTextureFactory::texture_handle private
Definition at line 29 of file gui_texture_factory.h.
Referenced by createTexture(), GuiTextureFactory(), textureByteCount(), and textureSize().
texture_handle_user
GuiFilledTextureHandleUser openage::gui::GuiTextureFactory::texture_handle_user private
Definition at line 30 of file gui_texture_factory.h.
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/integration/private/gui_texture_factory.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/integration/private/gui_texture_factory.cpp