openage: openage::util::CachableOSStream Class Reference
openage::util::CachableOSStream Class Reference
#include <stringformatter.h>
Public Member Functions
CachableOSStream ()
CachableOSStream (std::string &output)
Static Public Member Functions
static CachableOSStream * acquire (std::string &output)
static OAAPI void release (CachableOSStream *cs)
Public Attributes
ExternalOStringStream stream
Private Attributes
std::atomic_flag flag = ATOMIC_FLAG_INIT
Detailed Description
Designed for usage by StringFormatter.
The problem with iostreams, including ExternalOStringStream, is that they use lots of memory, and are quite slow to construct, due to some pesky implementation details.
This class fixes this by keeping a reservoir of such objects, and providing access to them via acquire(), in a thread-safe manner. If the cache is exhausted, new objects are constructed on the heap as needed.
release() makes a cached object available for acquiring again (cache) or destroys it (heap).
Definition at line 32 of file stringformatter.h.
Constructor & Destructor Documentation
CachableOSStream() [1/2]
openage::util::CachableOSStream::CachableOSStream ()
Definition at line 11 of file stringformatter.cpp.
 {}
CachableOSStream() [2/2]
openage::util::CachableOSStream::CachableOSStream (std::string & output)
Calls stream.use_with(output); for use by heap objects.
Definition at line 14 of file stringformatter.cpp.
     :
     CachableOSStream{} {
     this->stream.use_with(output);
 }
Member Function Documentation
acquire()
CachableOSStream * openage::util::CachableOSStream::acquire (std::string & output) static
Returns a brand-new(*) CachableOSStream object. Origin may vary (static internal cache, heap allocation).
After you're done, pass the pointer to release().
(*) Disclaimer: Object might not actually be brand-new.
Parameters
output The string object that the stream should output its data to.
Definition at line 22 of file stringformatter.cpp.
{
     static std::array<CachableOSStream, 128> cache;
     // Find an available cache element.
     for (CachableOSStream &elem : cache) {
         if (elem.flag.test_and_set() == false) {
             elem.stream.use_with(output);
             return &elem;
         }
     }
     // All cached objects are currently in use... that probably means that
     // your code is broken.
     // Anyways, have fun with your dynamically-allocated object.
     // \todo Print a warning debug message about this?
     // then again, printing a log message about the logging system being
     // overloaded might not be the most clever idea.
     return new CachableOSStream{output};
 }
References stream, and openage::util::ExternalOStringStream::use_with().
Referenced by openage::util::StringFormatter< Formatter >::ensure_stream_obj().
release()
void openage::util::CachableOSStream::release (CachableOSStream * cs) static
Resets the stream to a brand-new state, and clears the flag.
no-op if cs is nullptr.
Definition at line 44 of file stringformatter.cpp.
{
     if (cs == nullptr) {
         return;
     }
     // std::atomic_flag doesn't have a simple way of getting the truth
     // value, so we have to do a "full" test_and_set() instead,
     // even though thread-safety is not a concern here.
     if (cs->flag.test_and_set()) {
         cs->stream.clear();
         cs->flag.clear();
     } else {
         // test_and_set returned false -> the flag was not set.
         // This is because the element was not acquired from the cache,
         // but instead dynamically allocated. de-alloc it.
         delete cs;
     }
 }
References flag, and stream.
Referenced by openage::util::StringFormatter< Formatter >::~StringFormatter().
Member Data Documentation
flag
std::atomic_flag openage::util::CachableOSStream::flag = ATOMIC_FLAG_INIT private
true if all of the following are true:
object is part of a larger cache
object is currently in use (-> unavailable) http://en.cppreference.com/w/cpp/atomic/ATOMIC_FLAG_INIT https://stackoverflow.com/questions/24437396/stdatomic-flag-as-member-variable
Definition at line 74 of file stringformatter.h.
Referenced by release().
stream
ExternalOStringStream openage::util::CachableOSStream::stream
Definition at line 34 of file stringformatter.h.
Referenced by acquire(), openage::util::StringFormatter< Formatter >::operator<<(), openage.util.filelike.stream.StreamFragment::read(), release(), and openage::util::StringFormatter< Formatter >::reset_flags().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/stringformatter.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/stringformatter.cpp