openage: openage::event::tests::TestState::TestObject Class Reference
openage::event::tests::TestState::TestObject Class Reference
Public Member Functions
TestObject (const std::shared_ptr< Loop > &loop, int id)
void set_number (int number, const curve::time_t &time)
size_t id () const override
Give a unique event system identifier for the entity.
void test_trigger (const curve::time_t &time)
Public Member Functions inherited from openage::event::EventTarget
virtual ~EventTarget ()=default
void add_dependent (const std::weak_ptr< Event > &event)
Add a dependent class, that should be notified when dependency is called.
void show_dependents () const
For debugging: print the dependent eventclass ids as log messages.
Public Attributes
int number
Private Attributes
const int _id
Additional Inherited Members
Public Types inherited from openage::event::EventTarget
using single_change_notifier = std::function< void(const curve::time_t &)>
Protected Member Functions inherited from openage::event::EventTarget
EventTarget (const std::shared_ptr< Loop > &loop, single_change_notifier parent_notifier=nullptr)
For children to be able to initialize us.
void changes (const curve::time_t &change_time)
Call this whenever some data in the target changes.
void trigger (const curve::time_t &last_valid_time)
Call this when a keyframe in the underlying container was passed by in time.
Detailed Description
Definition at line 20 of file tests.cpp.
Constructor & Destructor Documentation
TestObject()
openage::event::tests::TestState::TestObject::TestObject (const std::shared_ptr< Loop > & loop, int id) inline
Definition at line 23 of file tests.cpp.
             :
             EventTarget(loop),
             _id{id},
             number(0) {}
Member Function Documentation
id()
size_t openage::event::tests::TestState::TestObject::id () const inline override virtual
Give a unique event system identifier for the entity.
Implements openage::event::EventTarget.
Definition at line 34 of file tests.cpp.
{
             return _id;
         }
References _id.
set_number()
void openage::event::tests::TestState::TestObject::set_number (int number, const curve::time_t & time) inline
Definition at line 29 of file tests.cpp.
{
             this->number = number;
             this->changes(time + curve::time_t::from_double(1));
         }
References openage::event::EventTarget::changes(), openage::util::FixedPoint< int64_t, 16 >::from_double(), and number.
test_trigger()
void openage::event::tests::TestState::TestObject::test_trigger (const curve::time_t & time) inline
Definition at line 38 of file tests.cpp.
{
             this->trigger(time);
         }
References openage::event::EventTarget::trigger().
Member Data Documentation
_id
const int openage::event::tests::TestState::TestObject::_id private
Definition at line 21 of file tests.cpp.
Referenced by id().
number
int openage::event::tests::TestState::TestObject::number
Definition at line 42 of file tests.cpp.
Referenced by set_number().
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/event/tests.cpp