openage: qtsdl::GuiSubtreeImpl Class Reference
qtsdl::GuiSubtreeImpl Class Reference
#include <gui_subtree_impl.h>
Public Slots
void onEngineReloaded ()
void attach_to (GuiEventQueueImpl *game_logic_updater)
void attach_to (GuiRendererImpl *renderer)
void attach_to (GuiEngineImpl *engine, const QString &source)
Signals
void process_game_logic_callback_blocking (const std::function< void()> &f)
Public Member Functions
GuiSubtreeImpl (GuiRenderer *renderer, GuiEventQueue *game_logic_updater, GuiEngine *engine, const QString &source, const QString &rootdir)
virtual ~GuiSubtreeImpl ()
Private Slots
void component_status_changed (QQmlComponent::Status status)
void on_resized (const QSize &size)
void on_process_game_logic_callback_blocking (const std::function< void()> &f)
Private Member Functions
void init_persistent_items ()
void reparent_root ()
void destroy_root ()
Private Attributes
GuiRendererImpl * renderer
GuiEngineImplConnection engine
GuiLiveReloader reloader
GuiCallback game_logic_callback
std::unique_ptr< QQmlComponent > root_component
QQuickItem * root
Detailed Description
Definition at line 55 of file gui_subtree_impl.h.
Constructor & Destructor Documentation
GuiSubtreeImpl()
qtsdl::GuiSubtreeImpl::GuiSubtreeImpl (GuiRenderer * renderer, GuiEventQueue * game_logic_updater, GuiEngine * engine, const QString & source, const QString & rootdir) explicit
Definition at line 25 of file gui_subtree_impl.cpp.
     :
     QObject{},
     renderer{},
     engine{},
     root{} {
     QObject::connect(
         &this->game_logic_callback,
         &GuiCallback::process_blocking,
         this,
         &GuiSubtreeImpl::on_process_game_logic_callback_blocking,
         Qt::DirectConnection
     );
     QObject::connect(
         this,
         &GuiSubtreeImpl::process_game_logic_callback_blocking,
         &this->game_logic_callback,
         &GuiCallback::process,
         (QCoreApplication::instance()->thread() != QThread::currentThread()
          ? Qt::BlockingQueuedConnection
          : Qt::DirectConnection)
     );
     this->moveToThread(QCoreApplication::instance()->thread());
     this->attach_to(GuiEventQueueImpl::impl(game_logic_updater));
     this->attach_to(GuiRendererImpl::impl(renderer));
     this->attach_to(GuiEngineImpl::impl(engine), rootdir);
     // Should now be initialized by the engine-attaching
     assert(this->root_component);
     // Need to queue the loading because some underlying game logic elements
     // require the loop to be running (maybe some things that are created after
     // the gui).
     QMetaObject::invokeMethod(this->root_component.get(),
                               "loadUrl", Qt::QueuedConnection,
                               Q_ARG(QUrl, QUrl::fromLocalFile(source)));
 }
~GuiSubtreeImpl()
qtsdl::GuiSubtreeImpl::~GuiSubtreeImpl () virtual
Definition at line 70 of file gui_subtree_impl.cpp.
{
 }
Member Function Documentation
attach_to [1/3]
void qtsdl::GuiSubtreeImpl::attach_to (GuiEventQueueImpl * game_logic_updater) slot
Definition at line 90 of file gui_subtree_impl.cpp.
{
     this->game_logic_callback.moveToThread(game_logic_updater->get_thread());
 }
References game_logic_callback, and qtsdl::GuiEventQueueImpl::get_thread().
attach_to [2/3]
void qtsdl::GuiSubtreeImpl::attach_to (GuiRendererImpl * renderer) slot
Definition at line 94 of file gui_subtree_impl.cpp.
{
     assert(renderer);
     if (this->renderer)
         QObject::disconnect(this->renderer, 0, this, 0);
     this->renderer = renderer;
     QObject::connect(
         this->renderer,
         &GuiRendererImpl::resized,
         this,
         &GuiSubtreeImpl::on_resized
     );
     this->reparent_root();
 }
References on_resized(), renderer, reparent_root(), and qtsdl::GuiRendererImpl::resized().
attach_to [3/3]
void qtsdl::GuiSubtreeImpl::attach_to (GuiEngineImpl * engine, const QString & source) slot
Definition at line 111 of file gui_subtree_impl.cpp.
{
     if (this->engine.has_subtree()) {
         this->destroy_root();
         this->engine = GuiEngineImplConnection{};
     }
     this->root_component = std::make_unique<QQmlComponent>(engine_impl->get_qml_engine());
     QObject::connect(
         this->root_component.get(),
         &QQmlComponent::statusChanged,
         this,
         &GuiSubtreeImpl::component_status_changed
     );
     // operator = &&
     this->engine = GuiEngineImplConnection{this, engine_impl, root_dir};
     this->root_component->moveToThread(QCoreApplication::instance()->thread());
 }
References component_status_changed(), destroy_root(), engine, qtsdl::GuiEngineImpl::get_qml_engine(), qtsdl::GuiEngineImplConnection::has_subtree(), and root_component.
component_status_changed
void qtsdl::GuiSubtreeImpl::component_status_changed (QQmlComponent::Status status) private slot
Definition at line 132 of file gui_subtree_impl.cpp.
{
     if (QQmlComponent::Error == status) {
         qCritical("%s", qUtf8Printable(this->root_component->errorString()));
         return;
     }
     if (QQmlComponent::Ready == status) {
         assert(!this->root);
         this->root = qobject_cast<QQuickItem*>(this->root_component->beginCreate(this->engine.rootContext()));
         assert(this->root);
         this->init_persistent_items();
         this->root_component->completeCreate();
         this->reparent_root();
     }
 }
References init_persistent_items(), reparent_root(), root, and root_component.
Referenced by attach_to(), and onEngineReloaded().
destroy_root()
void qtsdl::GuiSubtreeImpl::destroy_root () private
Definition at line 180 of file gui_subtree_impl.cpp.
{
     if (this->root) {
         this->root->setParent(nullptr);
         this->root->setParentItem(nullptr);
         this->root->deleteLater();
         this->root = nullptr;
     }
 }
References root.
Referenced by attach_to(), and onEngineReloaded().
init_persistent_items()
void qtsdl::GuiSubtreeImpl::init_persistent_items () private
Definition at line 162 of file gui_subtree_impl.cpp.
{
     auto persistent = this->root->findChildren<GuiLiveReloaderAttachedProperty*>();
     for (auto ap : persistent)
         ap->get_attachee()->set_game_logic_callback(&this->game_logic_callback);
     this->reloader.init_persistent_items(persistent);
 }
References game_logic_callback, qtsdl::GuiLiveReloaderAttachedProperty::get_attachee(), qtsdl::GuiLiveReloader::init_persistent_items(), reloader, root, and qtsdl::GuiItemBase::set_game_logic_callback().
Referenced by component_status_changed().
on_process_game_logic_callback_blocking
void qtsdl::GuiSubtreeImpl::on_process_game_logic_callback_blocking (const std::function< void()> & f) private slot
Definition at line 157 of file gui_subtree_impl.cpp.
{
     TemporaryDisableGuiRendererSync {*this->renderer};
     emit this->process_game_logic_callback_blocking(f);
 }
References process_game_logic_callback_blocking(), and renderer.
on_resized
void qtsdl::GuiSubtreeImpl::on_resized (const QSize & size) private slot
Definition at line 152 of file gui_subtree_impl.cpp.
{
     if (this->root)
         this->root->setSize(size);
 }
References root.
Referenced by attach_to().
onEngineReloaded
void qtsdl::GuiSubtreeImpl::onEngineReloaded () slot
Definition at line 73 of file gui_subtree_impl.cpp.
{
     const QUrl source = this->root_component->url();
     this->destroy_root();
     this->root_component = std::make_unique<QQmlComponent>(this->engine.get_qml_engine());
     QObject::connect(
         this->root_component.get(),
         &QQmlComponent::statusChanged,
         this,
         &GuiSubtreeImpl::component_status_changed
     );
     this->root_component->loadUrl(source);
 }
References component_status_changed(), destroy_root(), engine, qtsdl::GuiEngineImplConnection::get_qml_engine(), and root_component.
Referenced by qtsdl::GuiEngineImplConnection::disconnect().
process_game_logic_callback_blocking
void qtsdl::GuiSubtreeImpl::process_game_logic_callback_blocking (const std::function< void()> & f) signal
Referenced by on_process_game_logic_callback_blocking().
reparent_root()
void qtsdl::GuiSubtreeImpl::reparent_root () private
Definition at line 171 of file gui_subtree_impl.cpp.
{
     if (this->root) {
         QQuickWindow *window = this->renderer->get_window();
         this->root->setParentItem(window->contentItem());
         this->root->setSize(QSize{window->width(), window->height()});
     }
 }
References qtsdl::GuiRendererImpl::get_window(), renderer, and root.
Referenced by attach_to(), and component_status_changed().
Member Data Documentation
engine
GuiEngineImplConnection qtsdl::GuiSubtreeImpl::engine private
Definition at line 88 of file gui_subtree_impl.h.
Referenced by attach_to(), and onEngineReloaded().
game_logic_callback
GuiCallback qtsdl::GuiSubtreeImpl::game_logic_callback private
Definition at line 91 of file gui_subtree_impl.h.
Referenced by attach_to(), and init_persistent_items().
reloader
GuiLiveReloader qtsdl::GuiSubtreeImpl::reloader private
Definition at line 89 of file gui_subtree_impl.h.
Referenced by init_persistent_items().
renderer
GuiRendererImpl* qtsdl::GuiSubtreeImpl::renderer private
Definition at line 87 of file gui_subtree_impl.h.
Referenced by attach_to(), on_process_game_logic_callback_blocking(), and reparent_root().
root
QQuickItem* qtsdl::GuiSubtreeImpl::root private
Definition at line 94 of file gui_subtree_impl.h.
Referenced by component_status_changed(), destroy_root(), openage.convert.binpack.BinaryTreePacker::fit(), openage.convert.binpack.BinaryTreePacker::grow_down(), openage.convert.binpack.BinaryTreePacker::grow_node(), openage.convert.binpack.BinaryTreePacker::grow_right(), init_persistent_items(), on_resized(), and reparent_root().
root_component
std::unique_ptr<QQmlComponent> qtsdl::GuiSubtreeImpl::root_component private
Definition at line 93 of file gui_subtree_impl.h.
Referenced by attach_to(), component_status_changed(), and onEngineReloaded().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/guisys/private/gui_subtree_impl.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/guisys/private/gui_subtree_impl.cpp