openage: openage::renderer::opengl::GlWindow Class Reference
openage::renderer::opengl::GlWindow Class Reference final
#include <window.h>
Public Member Functions
GlWindow (const char *title, size_t width, size_t height)
Create a shiny window with the given title.
~GlWindow ()
void set_size (size_t width, size_t height) override
Force the window to the given size.
void update () override
Polls for window events, calls callbacks for these events, swaps front and back framebuffers to present graphics onto screen.
std::unique_ptr< Renderer > make_renderer () override
Creates a renderer which uses the window's graphics API and targets the window.
void make_context_current ()
Make this window's context the current rendering context of the current thread.
opengl::GlContext * get_context ()
Return a pointer to this window's GL context.
Public Member Functions inherited from openage::renderer::Window
virtual ~Window ()=default
std::pair< size_t, size_t > get_size () const
Returns the dimensions of this window.
bool should_close () const
Returns true if this window should be closed.
void add_key_callback (const key_cb_t &)
void add_mouse_button_callback (const mouse_button_cb_t &)
void add_mouse_wheel_callback (const mouse_wheel_cb_t &)
void add_resize_callback (const resize_cb_t &)
Private Attributes
SDL_Window * window
The SDL struct representing this window.
std::optional< opengl::GlContext > context
The window's OpenGL context.
Additional Inherited Members
Public Types inherited from openage::renderer::Window
using key_cb_t = std::function< void(SDL_KeyboardEvent const &)>
using mouse_button_cb_t = std::function< void(SDL_MouseButtonEvent const &)>
using mouse_wheel_cb_t = std::function< void(SDL_MouseWheelEvent const &)>
using resize_cb_t = std::function< void(size_t, size_t)>
Protected Member Functions inherited from openage::renderer::Window
Window (size_t width, size_t height)
Protected Attributes inherited from openage::renderer::Window
bool should_be_closed = false
std::pair< size_t, size_t > size
The current size of the framebuffer.
std::vector< key_cb_t > on_key
std::vector< mouse_button_cb_t > on_mouse_button
std::vector< mouse_wheel_cb_t > on_mouse_wheel
std::vector< resize_cb_t > on_resize
Detailed Description
Definition at line 16 of file window.h.
Constructor & Destructor Documentation
GlWindow()
openage::renderer::opengl::GlWindow::GlWindow (const char * title, size_t width, size_t height)
Create a shiny window with the given title.
Definition at line 16 of file window.cpp.
     : Window(width, height)
 {
     make_sdl_available();
     // We need HIGHDPI for eventual support of GUI scaling.
     // \todo HIGHDPI fails (requires newer SDL2?)
     int32_t window_flags = SDL_WINDOW_OPENGL | SDL_WINDOW_RESIZABLE | SDL_WINDOW_MAXIMIZED;
     this->window = SDL_CreateWindow(
         title,
         SDL_WINDOWPOS_CENTERED,
         SDL_WINDOWPOS_CENTERED,
         this->size.first,
         this->size.second,
         window_flags
     );
     if (this->window == nullptr) {
         throw Error{MSG(err) << "Failed to create SDL window: " << SDL_GetError()};
     }
     this->context = opengl::GlContext(this->window);
     this->add_resize_callback([] (size_t w, size_t h) { glViewport(0, 0, w, h); } );
     log::log(MSG(info) << "Created SDL window with OpenGL context.");
 }
References openage::renderer::Window::add_resize_callback(), context, openage::log::err(), openage::log::info(), openage::log::log(), openage::renderer::make_sdl_available(), MSG, openage::renderer::Window::size, and window.
~GlWindow()
openage::renderer::opengl::GlWindow::~GlWindow ()
Definition at line 43 of file window.cpp.
                     {
     SDL_DestroyWindow(this->window);
 }
References window.
Member Function Documentation
get_context()
opengl::GlContext * openage::renderer::opengl::GlWindow::get_context ()
Return a pointer to this window's GL context.
Definition at line 101 of file window.cpp.
{
     return &this->context.value();
 }
References context.
Referenced by make_renderer().
make_context_current()
void openage::renderer::opengl::GlWindow::make_context_current ()
Make this window's context the current rendering context of the current thread.
Only use this and most other GL functions on a dedicated window thread.
Definition at line 97 of file window.cpp.
{
     SDL_GL_MakeCurrent(this->window, this->context->get_raw_context());
 }
References context, and window.
make_renderer()
std::unique_ptr< Renderer > openage::renderer::opengl::GlWindow::make_renderer () override virtual
Creates a renderer which uses the window's graphics API and targets the window.
Implements openage::renderer::Window.
Definition at line 93 of file window.cpp.
{
     return std::make_unique<GlRenderer>(this->get_context());
 }
References get_context().
Referenced by openage::renderer::tests::renderer_demo_0().
set_size()
void openage::renderer::opengl::GlWindow::set_size (size_t width, size_t height) override virtual
Force the window to the given size.
It's generally not a good idea to use this, as it makes the window jump around wierdly.
Implements openage::renderer::Window.
Definition at line 47 of file window.cpp.
{
     if (this->size.first != width || this->size.second != height) {
         SDL_SetWindowSize(this->window, width, height);
         this->size = std::make_pair(width, height);
     }
     for (auto& cb : this->on_resize) {
         cb(width, height);
     }
 }
References openage::renderer::Window::on_resize, openage::renderer::Window::size, and window.
update()
void openage::renderer::opengl::GlWindow::update () override virtual
Polls for window events, calls callbacks for these events, swaps front and back framebuffers to present graphics onto screen.
This has to be called at the end of every graphics frame.
Implements openage::renderer::Window.
Definition at line 58 of file window.cpp.
                       {
     SDL_Event event;
     while (SDL_PollEvent(&event) != 0) {
         if (event.type == SDL_WINDOWEVENT) {
             if (event.window.event == SDL_WINDOWEVENT_RESIZED) {
                 size_t width = event.window.data1;
                 size_t height = event.window.data2;
                 log::log(MSG(dbg) << "Window resized to: " << width << "x" << height);
                 this->size = std::make_pair(width, height);
                 for (auto& cb : this->on_resize) {
                     cb(width, height);
                 }
             }
         } else if (event.type == SDL_QUIT) {
             this->should_be_closed = true;
             // \todo call on_destroy
         } else if (event.type == SDL_KEYUP) {
             auto const ev = *reinterpret_cast<SDL_KeyboardEvent const*>(&event);
             for (auto& cb : this->on_key) {
                 cb(ev);
             }
             // \todo handle keydown
         } else if (event.type == SDL_MOUSEBUTTONUP) {
             auto const ev = *reinterpret_cast<SDL_MouseButtonEvent const*>(&event);
             for (auto& cb : this->on_mouse_button) {
                 cb(ev);
             }
             // \todo handle mousedown
         }
     }
     SDL_GL_SwapWindow(this->window);
 }
References openage::log::dbg(), openage::log::log(), MSG, openage::renderer::Window::on_key, openage::renderer::Window::on_mouse_button, openage::renderer::Window::on_resize, openage::renderer::Window::should_be_closed, openage::renderer::Window::size, and window.
Referenced by openage::renderer::tests::renderer_demo_0().
Member Data Documentation
context
std::optional<opengl::GlContext> openage::renderer::opengl::GlWindow::context private
The window's OpenGL context.
It's optional because it can't be constructed immediately, but after the constructor runs it's guaranteed to be available.
Definition at line 41 of file window.h.
Referenced by get_context(), GlWindow(), and make_context_current().
window
SDL_Window* openage::renderer::opengl::GlWindow::window private
The SDL struct representing this window.
Definition at line 37 of file window.h.
Referenced by GlWindow(), make_context_current(), set_size(), update(), and ~GlWindow().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/opengl/window.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/opengl/window.cpp