openage: openage::UnitType Class Reference
openage::UnitType Class Reference abstract
units in aoc have a class and a type
#include <type_pair.h>
Public Member Functions
UnitType ()
bool match (class Unit *)
the unit must have either same class or id as this
UnitType (const Player &owner)
virtual ~UnitType ()
virtual int id () const =0
gets the unique id of this unit type
virtual int parent_id () const =0
gets the parent id of this unit type which is used for village base and gather types
virtual std::string name () const =0
gets the name of the unit type being produced
virtual void initialise (Unit *, Player &)=0
Initialize units attributes to this type spec.
virtual void reinitialise (Unit *, Player &)
Initialize units shared attributes only to this type spec.
virtual TerrainObject * place (Unit *, std::shared_ptr< Terrain >, coord::phys3) const =0
set unit in place – return if placement was successful
bool operator== (const UnitType &other) const
compare if two types are the same
bool operator!= (const UnitType &other) const
UnitTexture * default_texture ()
Get a default texture for HUD drawing.
TerrainObject * place_beside (Unit *, TerrainObject const *) const
similar to place but places adjacent to an existing object
void copy_attributes (Unit *unit) const
copy attributes of this unit type to a new unit instance
void upgrade (const std::shared_ptr< AttributeContainer > &attr)
upgrades one attribute of this unit type
UnitType * parent_type () const
returns type matching parent_id()
Public Attributes
const Player & owner
the player who owns this unit type
std::vector< UnitReference > instances
all instances of units made from this unit type this could allow all units of a type to be upgraded
std::vector< std::shared_ptr< UnitAbility > > type_abilities
abilities given to all instances
Attributes default_attributes
default attributes which get copied to new units
ResourceCost cost
The cost of the unit.
int have_limit
The max number of units of this type that a player can have at an instance.
int had_limit
The max number of units of this type that a player can create.
graphic_set graphics
The set of graphics used for this type.
coord::tile_delta foundation_size
the square dimensions of the placement
gamedata::unit_classes unit_class
raw game data class of this unit instance
Private Attributes
unsigned int class_id
unsigned int unit_type_id
Detailed Description
units in aoc have a class and a type
UnitType has to main roles:
initialise(unit, player) should be called on a unit to give it a type and the required attributes, abilities and initial actions of that type
place(unit, terrain, initial position) is called to customise how the unit gets added to the world – used to setup the TerrainObject location
UnitType is connected to a player to allow independent tech levels
Definition at line 10 of file type_pair.h.
Constructor & Destructor Documentation
UnitType() [1/2]
openage::UnitType::UnitType ()
Definition at line 7 of file type_pair.cpp.
 {}
UnitType() [2/2]
openage::UnitType::UnitType (const Player & owner)
Definition at line 28 of file unit_type.cpp.
     :
     owner{owner},
     have_limit{math::INT_INF},
     had_limit{math::INT_INF} {
 }
References openage::owner, and owner.
~UnitType()
virtual openage::UnitType::~UnitType () inline virtual
Definition at line 62 of file unit_type.h.
 {}
Member Function Documentation
copy_attributes()
void openage::UnitType::copy_attributes (Unit * unit) const
copy attributes of this unit type to a new unit instance
Definition at line 86 of file unit_type.cpp.
{
     unit->add_attributes(this->default_attributes);
 }
References openage::Unit::add_attributes(), and default_attributes.
Referenced by openage::NyanType::initialise().
default_texture()
UnitTexture * openage::UnitType::default_texture ()
Get a default texture for HUD drawing.
Definition at line 55 of file unit_type.cpp.
{
     return this->graphics[graphic_type::standing].get();
 }
References graphics, and openage::standing.
Referenced by openage::ActionMode::render().
id()
virtual int openage::UnitType::id () const pure virtual
gets the unique id of this unit type
Implemented in openage::NyanType, openage::ProjectileProducer, openage::BuildingProducer, and openage::ObjectProducer.
Referenced by openage::Player::active_unit_added(), openage::Player::active_unit_removed(), openage::Player::can_make(), openage::gameio::save_unit(), and openage::UnitSelection::show_attributes().
initialise()
virtual void openage::UnitType::initialise (Unit * , Player &) pure virtual
Initialize units attributes to this type spec.
This can be called using existing units to modify type Ensure that the unit has been placed before seting the units type
Todo:
make const
Implemented in openage::NyanType, openage::ProjectileProducer, openage::BuildingProducer, openage::LivingProducer, openage::MovableProducer, and openage::ObjectProducer.
Referenced by openage::ObjectProducer::initialise(), openage::UnitContainer::new_unit(), and reinitialise().
match()
bool openage::UnitType::match (class Unit *)
the unit must have either same class or id as this
Definition at line 9 of file type_pair.cpp.
{
     // \todo add types
     return true;
 }
name()
virtual std::string openage::UnitType::name () const pure virtual
gets the name of the unit type being produced
Implemented in openage::NyanType, openage::ProjectileProducer, openage::BuildingProducer, and openage::ObjectProducer.
Referenced by openage::UnitSelection::show_attributes(), openage.util.fslike.path.Path::stem(), openage.util.fslike.path.Path::suffix(), and openage.util.fslike.path.Path::suffixes().
operator!=()
bool openage::UnitType::operator!= (const UnitType & other) const
Definition at line 51 of file unit_type.cpp.
{
     return !(*this == other);
 }
operator==()
bool openage::UnitType::operator== (const UnitType & other) const
compare if two types are the same
Definition at line 47 of file unit_type.cpp.
{
     return this->type_abilities == other.type_abilities;
 }
References type_abilities.
parent_id()
virtual int openage::UnitType::parent_id () const pure virtual
gets the parent id of this unit type which is used for village base and gather types
Implemented in openage::NyanType, openage::ProjectileProducer, openage::BuildingProducer, and openage::ObjectProducer.
Referenced by parent_type().
parent_type()
UnitType * openage::UnitType::parent_type () const
returns type matching parent_id()
Definition at line 94 of file unit_type.cpp.
{
     return this->owner.get_type(this->parent_id());
 }
References openage::Player::get_type(), owner, and parent_id().
Referenced by openage::LivingProducer::initialise().
place()
virtual TerrainObject* openage::UnitType::place (Unit * , std::shared_ptr< Terrain > , coord::phys3) const pure virtual
set unit in place – return if placement was successful
This should be used when initially creating a unit or when a unit is ungarrsioned from a building or object
Todo:
make const
Implemented in openage::NyanType, openage::ProjectileProducer, openage::BuildingProducer, openage::LivingProducer, openage::MovableProducer, and openage::ObjectProducer.
Referenced by openage::UnitContainer::new_unit(), and place_beside().
place_beside()
TerrainObject * openage::UnitType::place_beside (Unit * u, TerrainObject const * other) const
similar to place but places adjacent to an existing object
Definition at line 59 of file unit_type.cpp.
{
     if (!u || !other) {
         return nullptr;
     }
     // find the range of possible tiles
     tile_range outline{other->pos.start - coord::tile_delta{1, 1},
                        other->pos.end   + coord::tile_delta{1, 1},
                        other->pos.draw};
     // find a free position adjacent to the object
     auto terrain = other->get_terrain();
     for (coord::tile temp_pos : tile_list(outline)) {
         TerrainChunk *chunk = terrain->get_chunk(temp_pos);
         if (chunk == nullptr) {
             continue;
         }
         auto placed = this->place(u, terrain, temp_pos.to_phys3(*terrain));
         if (placed) {
             return placed;
         }
     }
     return nullptr;
 }
References openage::tile_range::draw, openage::tile_range::end, openage::TerrainObject::get_terrain(), place(), openage::placed, openage::TerrainObject::pos, openage::tile_range::start, and openage::tile_list().
Referenced by openage::UnitContainer::new_unit().
reinitialise()
void openage::UnitType::reinitialise (Unit * unit, Player & player) virtual
Initialize units shared attributes only to this type spec.
This can be called using existing units to modify type if the type Ensure that the unit has been placed before seting the units type
Todo:
define if pure vitrual or not / should be in nyan?
Definition at line 35 of file unit_type.cpp.
{
     // In case reinitialise is not implemented separately
     Attributes tmp;
     // copy only unshared
     tmp.add_copies(unit->attributes, false, true);
     // initialise the new unit
     this->initialise(unit, player);
     // replace new unshared attributes with the old
     unit->attributes.add_copies(tmp);
 }
References openage::Attributes::add_copies(), openage::Unit::attributes, and initialise().
upgrade()
void openage::UnitType::upgrade (const std::shared_ptr< AttributeContainer > & attr)
upgrades one attribute of this unit type
Definition at line 90 of file unit_type.cpp.
{
     this->default_attributes.add(attr);
 }
References openage::Attributes::add(), and default_attributes.
Member Data Documentation
class_id
unsigned int openage::UnitType::class_id private
Definition at line 20 of file type_pair.h.
cost
ResourceCost openage::UnitType::cost
The cost of the unit.
Definition at line 164 of file unit_type.h.
Referenced by openage::Player::active_unit_added(), openage::Player::active_unit_removed(), openage::Player::can_make(), openage::Player::killed_unit(), and openage::ActionMode::place_selection().
default_attributes
Attributes openage::UnitType::default_attributes
default attributes which get copied to new units
Definition at line 159 of file unit_type.h.
Referenced by copy_attributes(), openage::TrainAction::update(), and upgrade().
foundation_size
coord::tile_delta openage::UnitType::foundation_size
the square dimensions of the placement
Definition at line 186 of file unit_type.h.
Referenced by openage::ObjectProducer::place(), openage::BuildingProducer::place(), and openage::ActionMode::render().
graphics
graphic_set openage::UnitType::graphics
The set of graphics used for this type.
Definition at line 181 of file unit_type.h.
Referenced by openage::UnitAction::current_graphics(), default_texture(), and openage::ObjectProducer::initialise().
had_limit
int openage::UnitType::had_limit
The max number of units of this type that a player can create.
Use negative values for special cases.
Definition at line 176 of file unit_type.h.
Referenced by openage::Player::can_make().
have_limit
int openage::UnitType::have_limit
The max number of units of this type that a player can have at an instance.
Use negative values for special cases.
Definition at line 170 of file unit_type.h.
Referenced by openage::Player::can_make(), and openage::BuildingProducer::initialise().
instances
std::vector<UnitReference> openage::UnitType::instances
all instances of units made from this unit type this could allow all units of a type to be upgraded
Definition at line 149 of file unit_type.h.
owner
const Player& openage::UnitType::owner
the player who owns this unit type
Definition at line 143 of file unit_type.h.
Referenced by openage::ObjectProducer::initialise(), openage::MovableProducer::initialise(), openage::LivingProducer::initialise(), openage::BuildingProducer::initialise(), openage::ProjectileProducer::initialise(), openage::BuildingProducer::make_annex(), parent_type(), and UnitType().
type_abilities
std::vector<std::shared_ptr<UnitAbility> > openage::UnitType::type_abilities
abilities given to all instances
Definition at line 154 of file unit_type.h.
Referenced by openage::ObjectProducer::initialise(), openage::NyanType::initialise(), openage::LivingProducer::LivingProducer(), and operator==().
unit_class
gamedata::unit_classes openage::UnitType::unit_class
raw game data class of this unit instance
Definition at line 191 of file unit_type.h.
unit_type_id
unsigned int openage::UnitType::unit_type_id private
Definition at line 21 of file type_pair.h.
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/type_pair.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/unit_type.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/type_pair.cpp
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/unit_type.cpp