openage: openage::DeadAction Class Reference
openage::DeadAction Class Reference
#include <action.h>
Public Member Functions
DeadAction (Unit *e, std::function< void()> on_complete=[]() {})
virtual ~DeadAction ()
void update (unsigned int time) override
void on_completion () override
bool completed () const override
bool allow_interupt () const override
bool allow_control () const override
std::string name () const override
Public Member Functions inherited from openage::UnitAction
UnitAction (Unit *u, graphic_type initial_gt)
virtual ~UnitAction ()
graphic_type type () const
float current_frame () const
virtual const graphic_set & current_graphics () const
void draw_debug (const Engine &engine)
void face_towards (const coord::phys3 pos)
bool damage_unit (Unit &target)
void move_to (Unit &target, bool use_range=true)
Private Attributes
float end_frame
std::function< void()> on_complete_func
Additional Inherited Members
Static Public Member Functions inherited from openage::UnitAction
static coord::phys_t adjacent_range (Unit *u)
static coord::phys_t get_attack_range (Unit *u)
static coord::phys_t get_heal_range (Unit *u)
Static Public Attributes inherited from openage::UnitAction
static bool show_debug = false
Protected Attributes inherited from openage::UnitAction
Unit * entity
graphic_type graphic
float frame
float frame_rate
std::function< void(const Engine &)> debug_draw_action
Detailed Description
plays a fixed number of frames for the units dying animation
Definition at line 295 of file action.h.
Constructor & Destructor Documentation
DeadAction()
openage::DeadAction::DeadAction (Unit * e, std::function< void()> on_complete = []() {})
Definition at line 360 of file action.cpp.
     :
     UnitAction(e, graphic_type::dying),
     end_frame{.0f},
     on_complete_func{on_complete} {
     auto &g_set = this->current_graphics();
     if (g_set.count(graphic) > 0) {
         this->end_frame = g_set.at(graphic)->frame_count - 1;
     }
 }
References openage::dying.
~DeadAction()
virtual openage::DeadAction::~DeadAction () inline virtual
Definition at line 298 of file action.h.
 {}
Member Function Documentation
allow_control()
bool openage::DeadAction::allow_control () const inline override virtual
control whether stack can discard the action automatically and should the stack be modifiable when this action is on top
if true this action must complete and will not allow new actions to be pushed while it is active and also does not update the secondary actions
Implements openage::UnitAction.
Definition at line 304 of file action.h.
 { return false; }
allow_interupt()
bool openage::DeadAction::allow_interupt () const inline override virtual
checks if the action can be interrupted, allowing it to be popped if the user specifies a new action, if false the action must reach a completed state before removal eg dead action must be completed and cannot be discarded
Implements openage::UnitAction.
Definition at line 303 of file action.h.
 { return false; }
completed()
bool openage::DeadAction::completed () const override virtual
gets called for all actions on stack each update cycle
Returns
true when action is completed so it and everything above it can be popped
Implements openage::UnitAction.
Definition at line 405 of file action.cpp.
{
     // check resource, trees/huntables with resource are not removed but not workers
     if (this->entity->has_attribute(attr_type::resource) && !this->entity->has_attribute(attr_type::worker)) {
         auto &res_attr = this->entity->get_attribute<attr_type::resource>();
         return res_attr.amount <= 0; // cannot complete when resource remains
     }
     return this->frame > this->end_frame;
 }
References end_frame, openage::UnitAction::entity, openage::UnitAction::frame, openage::Unit::get_attribute(), openage::Unit::has_attribute(), openage::resource, and openage::worker.
name()
std::string openage::DeadAction::name () const inline override virtual
debug string to identify action types
Implements openage::UnitAction.
Definition at line 305 of file action.h.
 { return "dead"; }
Referenced by openage.util.fslike.path.Path::stem(), openage.util.fslike.path.Path::suffix(), and openage.util.fslike.path.Path::suffixes().
on_completion()
void openage::DeadAction::on_completion () override virtual
action to perform when popped from a units action stack
Implements openage::UnitAction.
Definition at line 396 of file action.cpp.
{
     if (this->entity->has_attribute(attr_type::owner)) {
         auto &owner = this->entity->get_attribute<attr_type::owner>().player;
         owner.active_unit_removed(this->entity); // \todo move before the start of dead action?
     }
     this->on_complete_func();
 }
References openage::UnitAction::entity, openage::Unit::get_attribute(), openage::Unit::has_attribute(), on_complete_func, and openage::owner.
update()
void openage::DeadAction::update (unsigned int time) override virtual
each action has its own update functionality which gets called when this is the active action
Implements openage::UnitAction.
Definition at line 372 of file action.cpp.
{
     if (this->entity->has_attribute(attr_type::damaged)) {
         auto &dm = this->entity->get_attribute<attr_type::damaged>();
         dm.hp = 0;
     }
     // decay resources
     if (this->entity->has_attribute(attr_type::resource)) {
         auto &resource = this->entity->get_attribute<attr_type::resource>();
         if (resource.decay > 0) {
             resource.amount -= resource.decay;
         }
     }
     // inc frame but do not pass the end frame
     // the end frame will remain if the object carries resources
     if (this->frame < this->end_frame) {
         this->frame += 0.001 + time * this->frame_rate / 3.0f;
     }
     else {
         this->frame = this->end_frame;
     }
 }
References openage::damaged, end_frame, openage::UnitAction::entity, openage::UnitAction::frame, openage::UnitAction::frame_rate, openage::Unit::get_attribute(), openage::Unit::has_attribute(), and openage::resource.
Member Data Documentation
end_frame
float openage::DeadAction::end_frame private
Definition at line 308 of file action.h.
Referenced by completed(), and update().
on_complete_func
std::function<void()> openage::DeadAction::on_complete_func private
Definition at line 309 of file action.h.
Referenced by on_completion().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/action.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/action.cpp