openage: openage::UnitSelection Class Reference
openage::UnitSelection Class Reference
a user interface component allowing control of a selected group
#include <selection.h>
Public Member Functions
UnitSelection (Engine *engine)
bool on_drawhud () override
execute the drawing action.
void drag_begin (coord::camgame pos)
void drag_update (coord::camgame pos)
void drag_release (const Player &player, Terrain *terrain, bool append=false)
void clear ()
void toggle_unit (const Player &player, Unit *u, bool append=false)
void add_unit (const Player &player, Unit *u, bool append=false)
void remove_unit (Unit *u)
selection_type_t get_selection_type ()
void kill_unit (const Player &player)
kill a single unit in the selection
bool contains_builders (const Player &player)
checks whether there are any builders in the selection
bool contains_military (const Player &player)
checks whether there are any military units (i.e.
void select_point (const Player &player, Terrain *terrain, coord::camgame p, bool append=false)
point unit selection
void select_space (const Player &player, Terrain *terrain, coord::camgame p1, coord::camgame p2, bool append=false)
boxed unit selection
void all_invoke (Command &cmd)
uses command on every selected unit
Public Member Functions inherited from openage::HudHandler
virtual ~HudHandler ()=default
Private Member Functions
void show_attributes (Unit *)
Must be given a valid unit to display text attribute indicators.
selection_type_t get_unit_selection_type (const Player &player, Unit *)
Check whether the currently selected units may be selected at the same time If not, deselect some units This is the order in which the checks occur: Own units > own building(s) > enemy unit > enemy building > any object.
Private Attributes
std::unordered_map< id_t, UnitReference > units
selection_type_t selection_type
bool drag_active
coord::camgame start = {0, 0}
coord::camgame end = {0, 0}
int font_size
Engine * engine
Engine where this selection is attached to.
Detailed Description
a user interface component allowing control of a selected group
Definition at line 38 of file selection.h.
Constructor & Destructor Documentation
UnitSelection()
openage::UnitSelection::UnitSelection (Engine * engine)
Definition at line 20 of file selection.cpp.
     :
     selection_type{selection_type_t::nothing},
     drag_active{false},
     font_size{12},
     engine{engine} {
 }
References openage::nothing.
Member Function Documentation
add_unit()
void openage::UnitSelection::add_unit (const Player & player, Unit * u, bool append = false)
Definition at line 136 of file selection.cpp.
{
     // Only select resources and units with hitpoints > 0
     if (u->has_attribute(attr_type::resource) ||
        (u->has_attribute(attr_type::damaged) && u->get_attribute<attr_type::damaged>().hp > 0)) {
         selection_type_t unit_type = get_unit_selection_type(player, u);
         int unit_type_i = static_cast<int>(unit_type);
         int selection_type_i = static_cast<int>(this->selection_type);
         if (unit_type_i > selection_type_i) {
             // Don't select this unit as it has too low priority
             return;
         }
         if (unit_type_i < selection_type_i) {
             // Upgrade selection to a higher priority selection
             this->clear();
             this->selection_type = unit_type;
         }
         // Can't select multiple enemies at once
         if (not (unit_type == selection_type_t::own_units ||
                 (unit_type == selection_type_t::own_buildings && append))) {
             this->clear();
             this->selection_type = unit_type; // Clear resets selection_type
         }
         // Finally, add the unit to the selection
         u->selected = true;
         this->units[u->id] = u->get_ref();
     }
 }
References clear(), openage::damaged, openage::Unit::get_attribute(), openage::Unit::get_ref(), get_unit_selection_type(), openage::Unit::has_attribute(), openage::Unit::id, openage::own_buildings, openage::own_units, openage::resource, openage::Unit::selected, selection_type, and units.
Referenced by select_space(), and toggle_unit().
all_invoke()
void openage::UnitSelection::all_invoke (Command & cmd)
uses command on every selected unit
Definition at line 272 of file selection.cpp.
{
     for (auto u : this->units) {
         if (u.second.is_valid() && u.second.get()->is_own_unit(cmd.player)) {
             // allow unit to find best use of the command
             // \todo queue_cmd returns ability which allows playing of sound
             u.second.get()->queue_cmd(cmd);
         }
     }
 }
References openage::Command::player, and units.
Referenced by openage::ActionMode::on_game_control_set(), and openage::ActionMode::place_selection().
clear()
void openage::UnitSelection::clear ()
Definition at line 118 of file selection.cpp.
{
     for (auto u : this->units) {
         if (u.second.is_valid()) {
             u.second.get()->selected = false;
         }
     }
     this->units.clear();
     this->selection_type = selection_type_t::nothing;
 }
References openage::nothing, selection_type, and units.
Referenced by add_unit(), select_point(), and select_space().
contains_builders()
bool openage::UnitSelection::contains_builders (const Player & player)
checks whether there are any builders in the selection
Definition at line 206 of file selection.cpp.
{
     for (auto &it : units) {
         if (it.second.is_valid() &&
             it.second.get()->get_ability(ability_type::build) &&
             it.second.get()->is_own_unit(player)) {
             return true;
         }
     }
     return false;
 }
References openage::build, and units.
Referenced by openage::ActionMode::on_game_control_set().
contains_military()
bool openage::UnitSelection::contains_military (const Player & player)
checks whether there are any military units (i.e.
non-builders) in the selection
Definition at line 217 of file selection.cpp.
{
     for (auto &it : units) {
         if (it.second.is_valid() &&
             !it.second.get()->get_ability(ability_type::build) &&
             it.second.get()->is_own_unit(player)) {
             return true;
         }
     }
     return false;
 }
References openage::build, and units.
Referenced by openage::ActionMode::announce_buttons_type(), and openage::ActionMode::on_game_control_set().
drag_begin()
void openage::UnitSelection::drag_begin (coord::camgame pos)
Definition at line 93 of file selection.cpp.
{
     this->start = pos;
     this->end = pos;
     this->drag_active = true;
 }
References drag_active, end, and start.
Referenced by drag_update().
drag_release()
void openage::UnitSelection::drag_release (const Player & player, Terrain * terrain, bool append = false)
Definition at line 108 of file selection.cpp.
{
     if (this->start == this->end) {
         this->select_point(player, terrain, this->start, append);
     }
     else {
         this->select_space(player, terrain, this->start, this->end, append);
     }
     this->drag_active = false;
 }
References drag_active, end, select_point(), select_space(), and start.
Referenced by openage::ActionMode::on_game_control_set().
drag_update()
void openage::UnitSelection::drag_update (coord::camgame pos)
Definition at line 101 of file selection.cpp.
{
     if (!this->drag_active) {
         this->drag_begin(pos);
     }
     this->end = pos;
 }
References drag_active, drag_begin(), and end.
Referenced by openage::ActionMode::on_game_control_set().
get_selection_type()
selection_type_t openage::UnitSelection::get_selection_type ()
Definition at line 179 of file selection.cpp.
{
     return this->selection_type;
 }
References selection_type.
Referenced by openage::ActionMode::announce_buttons_type(), and openage::ActionMode::on_game_control_set().
get_unit_selection_type()
selection_type_t openage::UnitSelection::get_unit_selection_type (const Player & player, Unit * u) private
Check whether the currently selected units may be selected at the same time If not, deselect some units This is the order in which the checks occur: Own units > own building(s) > enemy unit > enemy building > any object.
So you can select a group of units, or a building (or multiple if append is on) Enemy units, enemy buildings and other objects may only be selected one at a time
Definition at line 319 of file selection.cpp.
{
     bool is_building = u->has_attribute(attr_type::building);
     // Check owner
     // \todo implement allied units
     if (u->is_own_unit(player)) {
         return is_building ? selection_type_t::own_buildings : selection_type_t::own_units;
     } else {
         return is_building ? selection_type_t::enemy_building : selection_type_t::enemy_unit;
     }
 }
References openage::building, openage::enemy_building, openage::enemy_unit, openage::Unit::has_attribute(), openage::Unit::is_own_unit(), openage::own_buildings, and openage::own_units.
Referenced by add_unit().
kill_unit()
void openage::UnitSelection::kill_unit (const Player & player)
kill a single unit in the selection
Definition at line 183 of file selection.cpp.
{
     if (this->units.empty()) {
         return;
     }
     UnitReference &ref = this->units.begin()->second;
     if (!ref.is_valid()) {
         this->units.erase(this->units.begin());
         if (this->units.empty()) {
             this->selection_type = selection_type_t::nothing;
         }
     } else {
         Unit *u = ref.get();
         // Check color: you can only kill your own units
         if (u->is_own_unit(player)) {
             this->remove_unit(u);
             u->delete_unit();
         }
     }
 }
References openage::Unit::delete_unit(), openage::Unit::is_own_unit(), openage::UnitReference::is_valid(), openage::nothing, ref, remove_unit(), selection_type, and units.
Referenced by openage::ActionMode::on_game_control_set().
on_drawhud()
bool openage::UnitSelection::on_drawhud () override virtual
execute the drawing action.
Implements openage::HudHandler.
Definition at line 28 of file selection.cpp.
{
     // the drag selection box
     if (drag_active) {
         coord::viewport s = this->start.to_viewport(this->engine->coord);
         coord::viewport e = this->end.to_viewport(this->engine->coord);
         glLineWidth(1);
         glColor3f(1.0, 1.0, 1.0);
         glBegin(GL_LINE_LOOP); {
             glVertex3f(s.x, s.y, 0);
             glVertex3f(e.x, s.y, 0);
             glVertex3f(e.x, e.y, 0);
             glVertex3f(s.x, e.y, 0);
         }
         glEnd();
     }
     // draw hp bars for each selected unit
     glLineWidth(3);
     for (auto u : this->units) {
         if (u.second.is_valid()) {
             Unit *unit_ptr = u.second.get();
             if (unit_ptr->location &&
                 unit_ptr->has_attribute(attr_type::hitpoints) &&
                 unit_ptr->has_attribute(attr_type::damaged)) {
                 auto &hp = unit_ptr->get_attribute<attr_type::hitpoints>();
                 auto &dm = unit_ptr->get_attribute<attr_type::damaged>();
                 float percent = static_cast<float>(dm.hp) / static_cast<float>(hp.hp);
                 int mid = percent * 28.0f - 14.0f;
                 coord::phys3 &pos_phys3 = unit_ptr->location->pos.draw;
                 auto pos = pos_phys3.to_viewport(this->engine->coord);
                 // green part
                 glColor3f(0.0, 1.0, 0.0);
                 glBegin(GL_LINES); {
                     glVertex3f(pos.x - 14, pos.y + 60, 0);
                     glVertex3f(pos.x + mid, pos.y + 60, 0);
                 }
                 glEnd();
                 // red part
                 glColor3f(1.0, 0.0, 0.0);
                 glBegin(GL_LINES); {
                     glVertex3f(pos.x + mid, pos.y + 60, 0);
                     glVertex3f(pos.x + 14, pos.y + 60, 0);
                 }
                 glEnd();
             }
         }
     }
     glColor3f(1.0, 1.0, 1.0); // reset
     // display details of single selected unit
     if (this->units.size() == 1) {
         auto &ref = this->units.begin()->second;
         if (ref.is_valid()) {
             this->show_attributes(ref.get());
         }
     }
     // ui graphics 3404 and 3405
     return true;
 }
References openage::Engine::coord, openage::damaged, drag_active, end, engine, openage::Unit::get_attribute(), openage::Unit::has_attribute(), openage::hitpoints, openage::Unit::location, ref, show_attributes(), start, openage::coord::camgame::to_viewport(), openage::coord::phys3::to_viewport(), and units.
Referenced by openage::ActionMode::render().
remove_unit()
void openage::UnitSelection::remove_unit (Unit * u)
Definition at line 170 of file selection.cpp.
{
     u->selected = false;
     this->units.erase(u->id);
     if (this->units.empty()) {
         this->selection_type = selection_type_t::nothing;
     }
 }
References openage::Unit::id, openage::nothing, openage::Unit::selected, selection_type, and units.
Referenced by kill_unit(), and toggle_unit().
select_point()
void openage::UnitSelection::select_point (const Player & player, Terrain * terrain, coord::camgame p, bool append = false)
point unit selection
Definition at line 228 of file selection.cpp.
{
     if (!append) {
         this->clear();
     }
     if (!terrain) {
         log::log(MSG(warn) << "selection terrain not specified");
         return;
     }
     // find any object at selected point
     auto obj = terrain->obj_at_point(point.to_phys3(this->engine->coord));
     if (obj) {
         this->toggle_unit(player, &obj->unit);
     }
 }
References clear(), openage::log::log(), MSG, openage::Terrain::obj_at_point(), openage::coord::camgame::to_phys3(), toggle_unit(), and openage::log::warn().
Referenced by drag_release().
select_space()
void openage::UnitSelection::select_space (const Player & player, Terrain * terrain, coord::camgame p1, coord::camgame p2, bool append = false)
boxed unit selection
Definition at line 246 of file selection.cpp.
{
     if (!append) {
         this->clear();
     }
     coord::camgame min{std::min(point0.x, point1.x), std::min(point0.y, point1.y)};
     coord::camgame max{std::max(point0.x, point1.x), std::max(point0.y, point1.y)};
     // look at each tile in the range and find all units
     for (coord::tile check_pos : tiles_in_range(point0, point1, this->engine->coord)) {
         TileContent *tc = terrain->get_data(check_pos);
         if (tc) {
             // find objects within selection box
             for (auto unit_location : tc->obj) {
                 coord::camgame pos = unit_location->pos.draw.to_camgame(this->engine->coord);
                 if ((pos.x > min.x and pos.x < max.x) and
                      (pos.y > min.y and pos.y < max.y)) {
                     this->add_unit(player, &unit_location->unit, append);
                 }
             }
         }
     }
 }
References add_unit(), clear(), openage::Engine::coord, engine, openage::Terrain::get_data(), openage::console::tests::max(), std::max(), std::min(), openage::TileContent::obj, and openage::tiles_in_range().
Referenced by drag_release().
show_attributes()
void openage::UnitSelection::show_attributes (Unit * u) private
Must be given a valid unit to display text attribute indicators.
Definition at line 283 of file selection.cpp.
{
     std::vector<std::string> lines;
     lines.push_back(u->top()->name());
     lines.push_back("type: "+std::to_string(u->unit_type->id()));
     if (u->has_attribute(attr_type::owner)) {
         auto &own_attr = u->get_attribute<attr_type::owner>();
         lines.push_back(own_attr.player.name);
     }
     if (u->has_attribute(attr_type::hitpoints) && u->has_attribute(attr_type::damaged)) {
         auto &hp = u->get_attribute<attr_type::hitpoints>();
         auto &dm = u->get_attribute<attr_type::damaged>();
         lines.push_back("hitpoints: "+std::to_string(dm.hp)+"/"+std::to_string(hp.hp));
     }
     if (u->has_attribute(attr_type::resource)) {
         auto &res_attr = u->get_attribute<attr_type::resource>();
         lines.push_back("resource: "+std::to_string(res_attr.amount)+" "+std::to_string(res_attr.resource_type));
     }
     if (u->has_attribute(attr_type::building)) {
         auto &build_attr = u->get_attribute<attr_type::building>();
         lines.push_back("built: "+std::to_string(build_attr.completed));
     }
     if (u->has_attribute(attr_type::garrison)) {
         auto &garrison_attr = u->get_attribute<attr_type::garrison>();
         lines.push_back("garrison: "+std::to_string(garrison_attr.content.size()));
     }
     // render text
     int vpos = 160;
     this->engine->render_text({0, vpos}, 20, "%s", u->unit_type->name().c_str());
     for (auto &s : lines) {
         vpos -= this->font_size;
         engine->render_text({0, vpos}, this->font_size, "%s", s.c_str());
     }
 }
References openage::building, openage::damaged, engine, font_size, openage::garrison, openage::Unit::get_attribute(), openage::Unit::has_attribute(), openage::hitpoints, openage::UnitType::id(), openage::UnitType::name(), openage::UnitAction::name(), openage::owner, openage::Engine::render_text(), openage::resource, std::to_string(), openage::Unit::top(), and openage::Unit::unit_type.
Referenced by on_drawhud().
toggle_unit()
void openage::UnitSelection::toggle_unit (const Player & player, Unit * u, bool append = false)
Definition at line 128 of file selection.cpp.
{
     if (this->units.count(u->id) == 0) {
         this->add_unit(player, u, append);
     } else {
         this->remove_unit(u);
     }
 }
References add_unit(), openage::Unit::id, remove_unit(), and units.
Referenced by select_point().
Member Data Documentation
drag_active
bool openage::UnitSelection::drag_active private
Definition at line 105 of file selection.h.
Referenced by drag_begin(), drag_release(), drag_update(), and on_drawhud().
end
coord::camgame openage::UnitSelection::end = {0, 0} private
Definition at line 107 of file selection.h.
Referenced by drag_begin(), drag_release(), drag_update(), and on_drawhud().
engine
Engine* openage::UnitSelection::engine private
Engine where this selection is attached to.
Definition at line 113 of file selection.h.
Referenced by on_drawhud(), select_space(), and show_attributes().
font_size
int openage::UnitSelection::font_size private
Definition at line 108 of file selection.h.
Referenced by show_attributes().
selection_type
selection_type_t openage::UnitSelection::selection_type private
Definition at line 103 of file selection.h.
Referenced by add_unit(), clear(), get_selection_type(), kill_unit(), and remove_unit().
start
coord::camgame openage::UnitSelection::start = {0, 0} private
Definition at line 107 of file selection.h.
Referenced by drag_begin(), drag_release(), on_drawhud(), and openage.util.filelike.stream.StreamFragment::read().
units
std::unordered_map<id_t, UnitReference> openage::UnitSelection::units private
Definition at line 102 of file selection.h.
Referenced by add_unit(), all_invoke(), clear(), contains_builders(), contains_military(), kill_unit(), on_drawhud(), remove_unit(), and toggle_unit().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/selection.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/selection.cpp