openage: openage::pyinterface::PyObjectRef Class Reference
openage::pyinterface::PyObjectRef Class Reference
#include <pyobject.h>
Public Member Functions
PyObjectRef () noexcept
PyObjectRef (PyObject *ref)
PyObjectRef (const PyObjectRef &other)
PyObjectRef (PyObjectRef &&other) noexcept
PyObjectRef & operator= (const PyObjectRef &other)
PyObjectRef & operator= (PyObjectRef &&other)
~PyObjectRef ()
std::string str () const
std::string repr () const
std::string bytes () const
int len () const
bool callable () const
template<typename ... Args>
PyObjectRef call (Args... args) const
PyObjectRef getattr (const std::string &name) const
bool hasattr (const std::string &name) const
void setattr (const std::string &name, const PyObjectRef &attr) const
bool isinstance (const PyObjectRef &type) const
bool to_bool () const
int64_t to_int () const
void dir (const Func< void, std::string > &callback) const
bool is (const PyObjectRef &other) const
bool equals (const PyObjectRef &other) const
PyObjectRef eval (const std::string &expression) const
void exec (const std::string &statement) const
PyObjectRef get (const PyObjectRef &key) const
PyObjectRef get (const std::string &key) const
PyObjectRef get (int key) const
bool in (const PyObjectRef &container) const
PyObjectRef type () const
std::string modulename () const
std::string classname () const
PyObject * get_ref () const noexcept
PyObject * operator() () const noexcept
void set_ref (PyObject *ref)
void set_ref_without_incrementing (PyObject *ref)
void clear_ref_without_decrementing () noexcept
template<>
PyObjectRef (int number)
template<>
PyObjectRef (const char *data)
template<>
PyObjectRef (const std::string &txt)
Private Member Functions
PyObjectRef call_impl (std::vector< PyObjectRef > &args) const
template<typename T >
PyObjectRef (T arg)
Private Attributes
PyObject * ref
Detailed Description
Holds a Python object, as a PyObject * pointer.
Reference counting (Py_INCREF and Py_DECREF) is correctly performed in the various copy/move constructors/operators.
pxd:
cppclass PyObjectRef: PyObjectRef() noexcept PyObjectRef(PyObject *ref) except +
PyObject *get_ref() noexcept void set_ref(PyObject *ref) except + void set_ref_without_incrementing(PyObject *ref) except + void clear_ref_without_decrementing() noexcept
ctypedef PyObjectRef PyObj
ctypedef PyObjectRef *PyObjectRefPtr ctypedef PyObject *PyObjectPtr
Definition at line 49 of file pyobject.h.
Constructor & Destructor Documentation
PyObjectRef() [1/8]
openage::pyinterface::PyObjectRef::PyObjectRef () noexcept
Initializes reference with nullptr.
Definition at line 13 of file pyobject.cpp.
     :
     ref{nullptr} {}
PyObjectRef() [2/8]
openage::pyinterface::PyObjectRef::PyObjectRef (PyObject * ref)
Wraps a raw PyObject * pointer (calls Py_INCREF).
Definition at line 18 of file pyobject.cpp.
     :
     ref{ref} {
     py_xincref.call(this->ref);
 }
References ref.
PyObjectRef() [3/8]
openage::pyinterface::PyObjectRef::PyObjectRef (const PyObjectRef & other)
Clones a PyObjectRef (calls Py_INCREF).
Definition at line 26 of file pyobject.cpp.
     :
     ref{other.ref} {
     py_xincref.call(this->ref);
 }
References ref.
PyObjectRef() [4/8]
openage::pyinterface::PyObjectRef::PyObjectRef (PyObjectRef && other) noexcept
Move-constructs from an other PyObjectRef.
Definition at line 34 of file pyobject.cpp.
     :
     ref{other.ref} {
     // don't incref, because we simultaneously clear other.ref.
     other.ref = nullptr;
 }
~PyObjectRef()
openage::pyinterface::PyObjectRef::~PyObjectRef ()
Destroys the object, calls Py_XDECREF.
Definition at line 96 of file pyobject.cpp.
{
     if (this->ref != nullptr) {
         py_xdecref.call(this->ref);
     }
 }
References openage::pyinterface::py_xdecref, and ref.
PyObjectRef() [5/8]
template<typename T > openage::pyinterface::PyObjectRef::PyObjectRef (T arg) explicit private
Primary template for PyObjectRef conversions.
PyObjectRef() [6/8]
template<> openage::pyinterface::PyObjectRef::PyObjectRef (int number)
Integer conversion.
Definition at line 73 of file pyobject.cpp.
     :
     PyObjectRef(py::integer(number)) {}
PyObjectRef() [7/8]
template<> openage::pyinterface::PyObjectRef::PyObjectRef (const char * data)
Bytes conversion.
Definition at line 82 of file pyobject.cpp.
     :
     PyObjectRef(py::bytes(data)) {}
PyObjectRef() [8/8]
template<> openage::pyinterface::PyObjectRef::PyObjectRef (const std::string & txt)
String conversion.
Definition at line 91 of file pyobject.cpp.
     :
     PyObjectRef(py::bytes(txt)) {}
Member Function Documentation
bytes()
std::string openage::pyinterface::PyObjectRef::bytes () const
bytes(obj)
Definition at line 132 of file pyobject.cpp.
{
     return py_bytes.call(this->ref);
 }
References openage::pyinterface::py_bytes, and ref.
Referenced by openage::util::fslike::Python::get_native_path(), and openage::pyinterface::tests::pyobject().
call()
template<typename ... Args> PyObjectRef openage::pyinterface::PyObjectRef::call (Args... args) const inline
obj(args...)
Definition at line 120 of file pyobject.h.
{
         // this vector collects the function call arguments
         std::vector<PyObjectRef> arg_objs {
             PyObjectRef(args)...
         };
         return this->call_impl(arg_objs);
     }
Referenced by openage::pyinterface::tests::pyobject(), and openage::pyinterface::tests::pyobject_demo().
call_impl()
PyObjectRef openage::pyinterface::PyObjectRef::call_impl (std::vector< PyObjectRef > & args) const private
obj(args)
Definition at line 147 of file pyobject.cpp.
{
     PyObjectRef result;
     if (args.empty()) {
         py_call0.call(&result, this->ref);
     } else {
         std::vector<PyObject *> py_args{args.size()};
         std::transform(args.begin(), args.end(), py_args.begin(),
                        std::mem_fn(&PyObjectRef::get_ref));
         py_calln.call(&result, this->ref, py_args);
     }
     return result;
 }
References get_ref(), openage::pyinterface::py_call0, openage::pyinterface::py_calln, ref, and openage.testing.testing::result().
callable()
bool openage::pyinterface::PyObjectRef::callable () const
callable(obj)
Definition at line 142 of file pyobject.cpp.
{
     return py_callable.call(this->ref);
 }
References openage::pyinterface::py_callable, and ref.
Referenced by openage::pyinterface::tests::pyobject().
classname()
std::string openage::pyinterface::PyObjectRef::classname () const
type(obj).__name__
Definition at line 256 of file pyobject.cpp.
{
     return py_classname.call(this->ref);
 }
References openage::pyinterface::py_classname, and ref.
Referenced by openage::pyinterface::tests::pyobject(), and openage::pyinterface::PyException::type_name().
clear_ref_without_decrementing()
void openage::pyinterface::PyObjectRef::clear_ref_without_decrementing () inline noexcept
Clears the internal reference, but does NOT call PY_XDECREF. Only use in special cases, if you know exactly what you're doing.
Definition at line 273 of file pyobject.h.
{
         this->ref = nullptr;
     }
dir()
void openage::pyinterface::PyObjectRef::dir (const Func< void, std::string > & callback) const
for elem in dir(obj): callback(elem)
Definition at line 193 of file pyobject.cpp.
{
     py_dir.call(this->ref, callback);
 }
References openage::pyinterface::py_dir, and ref.
equals()
bool openage::pyinterface::PyObjectRef::equals (const PyObjectRef & other) const
obj == other
Definition at line 203 of file pyobject.cpp.
{
     return py_equals.call(this->ref, other.get_ref());
 }
References get_ref(), openage::pyinterface::py_equals, and ref.
Referenced by openage::pyinterface::tests::pyobject().
eval()
PyObjectRef openage::pyinterface::PyObjectRef::eval (const std::string & expression) const
eval(expression, obj)
Definition at line 208 of file pyobject.cpp.
{
     PyObjectRef result;
     py_eval.call(this->ref, &result, expression);
     return result;
 }
References openage::pyinterface::py_eval, ref, and openage.testing.testing::result().
Referenced by openage::pyinterface::tests::pyobject(), and openage::pyinterface::tests::pyobject_demo().
exec()
void openage::pyinterface::PyObjectRef::exec (const std::string & statement) const
exec(statement, obj)
Definition at line 215 of file pyobject.cpp.
{
     py_exec.call(this->ref, statement);
 }
References openage::pyinterface::py_exec, and ref.
Referenced by openage::pyinterface::tests::pyobject(), and openage::pyinterface::tests::pyobject_demo().
get() [1/3]
PyObjectRef openage::pyinterface::PyObjectRef::get (const PyObjectRef & key) const
obj[key]
Definition at line 220 of file pyobject.cpp.
{
     PyObjectRef result;
     py_get.call(this->ref, &result, key.get_ref());
     return result;
 }
References get_ref(), openage::pyinterface::py_get, ref, and openage.testing.testing::result().
Referenced by get(), and openage::pyinterface::tests::pyobject().
get() [2/3]
PyObjectRef openage::pyinterface::PyObjectRef::get (const std::string & key) const
obj[key]
Definition at line 227 of file pyobject.cpp.
{
     PyObjectRef keyobj = py::str(key);
     return this->get(keyobj);
 }
References get(), and openage::py::str().
get() [3/3]
PyObjectRef openage::pyinterface::PyObjectRef::get (int key) const
obj[key]
Definition at line 233 of file pyobject.cpp.
{
     PyObjectRef keyobj = py::integer(key);
     return this->get(keyobj);
 }
References get(), and openage::py::integer().
get_ref()
PyObject* openage::pyinterface::PyObjectRef::get_ref () const inline noexcept
Provide the internal PyObject *.
Definition at line 246 of file pyobject.h.
{
         return this->ref;
     }
References ref.
Referenced by call_impl(), equals(), get(), in(), openage::pyinterface::PyException::init_backtrace(), is(), isinstance(), and setattr().
getattr()
PyObjectRef openage::pyinterface::PyObjectRef::getattr (const std::string & name) const
getattr(obj, name)
Definition at line 166 of file pyobject.cpp.
{
     PyObjectRef result;
     py_getattr.call(&result, this->ref, name);
     return result;
 }
References openage::pyinterface::py_getattr, ref, and openage.testing.testing::result().
Referenced by openage::pyinterface::tests::pyobject().
hasattr()
bool openage::pyinterface::PyObjectRef::hasattr (const std::string & name) const
hasattr(obj, name)
Definition at line 161 of file pyobject.cpp.
{
     return py_hasattr.call(this->ref, name);
 }
References openage::pyinterface::py_hasattr, and ref.
Referenced by openage::pyinterface::tests::pyobject().
in()
bool openage::pyinterface::PyObjectRef::in (const PyObjectRef & container) const
obj in container
Definition at line 239 of file pyobject.cpp.
{
     return py_in.call(this->ref, container.get_ref());
 }
References get_ref(), openage::pyinterface::py_in, and ref.
is()
bool openage::pyinterface::PyObjectRef::is (const PyObjectRef & other) const
obj is other
Definition at line 198 of file pyobject.cpp.
{
     return this->ref == other.get_ref();
 }
References get_ref(), and ref.
Referenced by openage::util::fslike::Python::get_native_path(), and openage::pyinterface::tests::pyobject().
isinstance()
bool openage::pyinterface::PyObjectRef::isinstance (const PyObjectRef & type) const
isinstance(obj, type)
Definition at line 188 of file pyobject.cpp.
{
     return py_isinstance.call(this->ref, type.get_ref());
 }
References get_ref(), openage::pyinterface::py_isinstance, and ref.
Referenced by openage::pyinterface::tests::pyobject().
len()
int openage::pyinterface::PyObjectRef::len () const
len(obj)
Definition at line 137 of file pyobject.cpp.
{
     return py_len.call(this->ref);
 }
References openage::pyinterface::py_len, and ref.
Referenced by openage::pyinterface::tests::pyobject().
modulename()
std::string openage::pyinterface::PyObjectRef::modulename () const
type(obj).__module__
Definition at line 251 of file pyobject.cpp.
{
     return py_modulename.call(this->ref);
 }
References openage::pyinterface::py_modulename, and ref.
Referenced by openage::pyinterface::tests::pyobject(), and openage::pyinterface::PyException::type_name().
operator()()
PyObject* openage::pyinterface::PyObjectRef::operator() () const inline noexcept
Implicit conversion to PyObject *. Mainly for convenience to avoid all the get_ref() calls.
Definition at line 254 of file pyobject.h.
{
         return this->ref;
     }
References ref.
operator=() [1/2]
PyObjectRef & openage::pyinterface::PyObjectRef::operator= (const PyObjectRef & other)
Assigns from an other PyObjectRef (calls Py_XDECREF on the old value, and Py_XINCREF on the new one).
Definition at line 43 of file pyobject.cpp.
{
     if (this->ref != nullptr) {
         py_xdecref.call(this->ref);
     }
     this->ref = other.ref;
     py_xincref.call(this->ref);
     return *this;
 }
References openage::pyinterface::py_xdecref, openage::pyinterface::py_xincref, and ref.
operator=() [2/2]
PyObjectRef & openage::pyinterface::PyObjectRef::operator= (PyObjectRef && other)
Move-assigns from an other PyObject (calls Py_XDECREF on the old value).
Definition at line 55 of file pyobject.cpp.
{
     if (this->ref != nullptr) {
         py_xdecref.call(this->ref);
     }
     this->ref = other.ref;
     // don't incref, because we simultaneously clear other.ref.
     other.ref = nullptr;
     return *this;
 }
References openage::pyinterface::py_xdecref, and ref.
repr()
std::string openage::pyinterface::PyObjectRef::repr () const
repr(obj)
Definition at line 127 of file pyobject.cpp.
{
     return py_repr.call(this->ref);
 }
References openage::pyinterface::py_repr, and ref.
Referenced by openage::pyinterface::tests::pyobject().
set_ref()
void openage::pyinterface::PyObjectRef::set_ref (PyObject * ref)
Like operator =(const PyObjectRef &other).
Definition at line 103 of file pyobject.cpp.
{
     if (unlikely(this->ref != nullptr)) {
         py_xdecref.call(this->ref);
     }
     this->ref = ref;
     py_xincref.call(this->ref);
 }
References openage::pyinterface::py_xdecref, openage::pyinterface::py_xincref, ref, and unlikely.
set_ref_without_incrementing()
void openage::pyinterface::PyObjectRef::set_ref_without_incrementing (PyObject * ref)
Like set_ref, but does NOT call PY_XINCREF. Only use in special cases, if you know exactly what you're doing.
Definition at line 113 of file pyobject.cpp.
{
     if (unlikely(this->ref != nullptr)) {
         py_xdecref.call(this->ref);
     }
     this->ref = ref;
 }
References openage::pyinterface::py_xdecref, ref, and unlikely.
setattr()
void openage::pyinterface::PyObjectRef::setattr (const std::string & name, const PyObjectRef & attr) const
setattr(obj, name)
Definition at line 173 of file pyobject.cpp.
{
     py_setattr.call(this->ref, name, attr.get_ref());
 }
References get_ref(), openage::pyinterface::py_setattr, and ref.
Referenced by openage::pyinterface::tests::pyobject().
str()
std::string openage::pyinterface::PyObjectRef::str () const
str(obj)
Definition at line 122 of file pyobject.cpp.
{
     return py_str.call(this->ref);
 }
References openage::pyinterface::py_str, and ref.
Referenced by openage::pyinterface::tests::pyobject(), and openage::pyinterface::tests::pyobject_demo().
to_bool()
bool openage::pyinterface::PyObjectRef::to_bool () const
bool(obj)
Definition at line 178 of file pyobject.cpp.
{
     return py_to_bool.call(this->ref);
 }
References openage::pyinterface::py_to_bool, and ref.
Referenced by openage::pyinterface::tests::pyobject().
to_int()
int64_t openage::pyinterface::PyObjectRef::to_int () const
int(obj)
Definition at line 183 of file pyobject.cpp.
{
     return py_to_int.call(this->ref);
 }
References openage::pyinterface::py_to_int, and ref.
Referenced by openage::pyinterface::tests::pyobject().
type()
PyObjectRef openage::pyinterface::PyObjectRef::type () const
type(obj)
Definition at line 244 of file pyobject.cpp.
{
     PyObjectRef result;
     py_type.call(this->ref, &result);
     return result;
 }
References openage::pyinterface::py_type, ref, and openage.testing.testing::result().
Referenced by openage::pyinterface::tests::pyobject().
Member Data Documentation
ref
PyObject* openage::pyinterface::PyObjectRef::ref private
Internal PyObject * for obj.
Definition at line 239 of file pyobject.h.
Referenced by bytes(), call_impl(), callable(), classname(), dir(), equals(), eval(), exec(), get(), getattr(), hasattr(), in(), is(), isinstance(), len(), modulename(), operator=(), PyObjectRef(), repr(), set_ref(), set_ref_without_incrementing(), setattr(), str(), to_bool(), to_int(), type(), and ~PyObjectRef().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/pyinterface/pyobject.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/pyinterface/pyobject.cpp