openage: openage::gui::CategoryContentsListModel Class Reference
openage::gui::CategoryContentsListModel Class Reference
#include <category_contents_list_model.h>
Public Member Functions
CategoryContentsListModel (QObject *parent=nullptr)
virtual ~CategoryContentsListModel ()
QString get_name () const
void set_name (const QString &name)
EditorModeLink * get_editor_mode () const
void set_editor_mode (EditorModeLink *editor_mode)
Properties
QString name
openage::gui::EditorModeLink editorMode
Private Slots
void on_category_content_changed (const std::string &category_name, std::vector< std::tuple< index_t, uint16_t >> type_and_texture)
void on_categories_content_changed ()
Private Member Functions
virtual QHash< int, QByteArray > roleNames () const override
virtual int rowCount (const QModelIndex &) const override
virtual QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
Private Attributes
std::vector< std::tuple< index_t, uint16_t > > type_and_texture
EditorModeLink * editor_mode
Detailed Description
Adaptor for the contents of a category of the Civilisation.
Definition at line 22 of file category_contents_list_model.h.
Constructor & Destructor Documentation
CategoryContentsListModel()
openage::gui::CategoryContentsListModel::CategoryContentsListModel (QObject * parent = nullptr)
Definition at line 16 of file category_contents_list_model.cpp.
     :
     QAbstractListModel{parent},
     editor_mode{} {
     Q_UNUSED(registration);
 }
~CategoryContentsListModel()
openage::gui::CategoryContentsListModel::~CategoryContentsListModel () virtual
Definition at line 23 of file category_contents_list_model.cpp.
{
 }
Member Function Documentation
data()
QVariant openage::gui::CategoryContentsListModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override private virtual
Definition at line 83 of file category_contents_list_model.cpp.
{
     switch (role) {
     case Qt::DisplayRole:
         return std::get<1>(this->type_and_texture[index.row()]);
         break;
     case Qt::UserRole + 1:
         return std::get<0>(this->type_and_texture[index.row()]);
         break;
     default:
         break;
     }
     return QVariant{};
 }
References type_and_texture.
Referenced by openage.convert.peresource.PEResources::read_directory().
get_editor_mode()
EditorModeLink * openage::gui::CategoryContentsListModel::get_editor_mode () const
Definition at line 38 of file category_contents_list_model.cpp.
{
     return this->editor_mode;
 }
References editor_mode.
get_name()
QString openage::gui::CategoryContentsListModel::get_name () const
Definition at line 26 of file category_contents_list_model.cpp.
{
     return this->name;
 }
References name.
on_categories_content_changed
void openage::gui::CategoryContentsListModel::on_categories_content_changed () private slot
Definition at line 68 of file category_contents_list_model.cpp.
{
     if (this->editor_mode)
         this->editor_mode->announce_category_content(this->name.toStdString());
 }
References openage::gui::EditorModeLink::announce_category_content(), editor_mode, and name.
Referenced by set_editor_mode(), and set_name().
on_category_content_changed
void openage::gui::CategoryContentsListModel::on_category_content_changed (const std::string & category_name, std::vector< std::tuple< index_t, uint16_t >> type_and_texture) private slot
Definition at line 60 of file category_contents_list_model.cpp.
{
     if (this->name == QString::fromStdString(category_name)) {
         this->beginResetModel();
         this->type_and_texture = type_and_texture;
         this->endResetModel();
     }
 }
References name, and type_and_texture.
Referenced by set_editor_mode().
roleNames()
QHash< int, QByteArray > openage::gui::CategoryContentsListModel::roleNames () const override private virtual
Definition at line 73 of file category_contents_list_model.cpp.
{
     auto names = this->QAbstractListModel::roleNames();
     names.insert(Qt::UserRole + 1, "typeId");
     return names;
 }
rowCount()
int openage::gui::CategoryContentsListModel::rowCount (const QModelIndex &) const override private virtual
Definition at line 79 of file category_contents_list_model.cpp.
{
     return this->type_and_texture.size();
 }
References type_and_texture.
set_editor_mode()
void openage::gui::CategoryContentsListModel::set_editor_mode (EditorModeLink * editor_mode)
Definition at line 42 of file category_contents_list_model.cpp.
{
     if (this->editor_mode != editor_mode) {
         if (this->editor_mode) {
             QObject::disconnect(this->editor_mode, &EditorModeLink::categories_content_changed, this, &CategoryContentsListModel::on_categories_content_changed);
             QObject::disconnect(this->editor_mode, &EditorModeLink::category_content_changed, this, &CategoryContentsListModel::on_category_content_changed);
         }
         this->editor_mode = editor_mode;
         if (this->editor_mode) {
             QObject::connect(this->editor_mode, &EditorModeLink::categories_content_changed, this, &CategoryContentsListModel::on_categories_content_changed);
             QObject::connect(this->editor_mode, &EditorModeLink::category_content_changed, this, &CategoryContentsListModel::on_category_content_changed);
         }
         this->on_categories_content_changed();
     }
 }
References openage::gui::EditorModeLink::categories_content_changed(), openage::gui::EditorModeLink::category_content_changed(), editor_mode, on_categories_content_changed(), and on_category_content_changed().
set_name()
void openage::gui::CategoryContentsListModel::set_name (const QString & name)
Definition at line 30 of file category_contents_list_model.cpp.
{
     if (this->name != name) {
         this->name = name;
         this->on_categories_content_changed();
     }
 }
References name, and on_categories_content_changed().
Member Data Documentation
editor_mode
EditorModeLink* openage::gui::CategoryContentsListModel::editor_mode private
Definition at line 50 of file category_contents_list_model.h.
Referenced by get_editor_mode(), on_categories_content_changed(), and set_editor_mode().
type_and_texture
std::vector<std::tuple<index_t, uint16_t> > openage::gui::CategoryContentsListModel::type_and_texture private
Definition at line 47 of file category_contents_list_model.h.
Referenced by data(), on_category_content_changed(), and rowCount().
Property Documentation
editorMode
openage::gui::EditorModeLink openage::gui::CategoryContentsListModel::editorMode read write
Definition at line 26 of file category_contents_list_model.h.
name
QString openage::gui::CategoryContentsListModel::name read write
Definition at line 25 of file category_contents_list_model.h.
Referenced by openage.convert.dataformat.header_snippet.HeaderSnippet::__eq__(), openage.convert.dataformat.header_snippet.HeaderSnippet::__hash__(), openage.convert.dataformat.header_snippet.HeaderSnippet::__repr__(), openage.convert.dataformat.header_snippet.HeaderSnippet::get_file_name(), get_name(), on_categories_content_changed(), on_category_content_changed(), set_name(), openage.util.fslike.path.Path::stem(), openage.util.fslike.path.Path::suffix(), and openage.util.fslike.path.Path::suffixes().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/category_contents_list_model.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/category_contents_list_model.cpp