openage: openage::gui::GuiTexture Class Reference
openage::gui::GuiTexture Class Reference
#include <gui_texture.h>
Public Member Functions
GuiTexture (const SizedTextureHandle &texture_handle)
virtual ~GuiTexture ()
Private Member Functions
virtual void bind () override
virtual bool hasAlphaChannel () const override
virtual bool hasMipmaps () const override
virtual bool isAtlasTexture () const override
virtual QSGTexture * removedFromAtlas () const override
virtual QRectF normalizedTextureSubRect () const override
virtual int textureId () const override
virtual QSize textureSize () const override
Private Attributes
const SizedTextureHandle texture_handle
std::unique_ptr< QSGTexture > standalone
Detailed Description
Definition at line 14 of file gui_texture.h.
Constructor & Destructor Documentation
GuiTexture()
openage::gui::GuiTexture::GuiTexture (const SizedTextureHandle & texture_handle) explicit
Definition at line 16 of file gui_texture.cpp.
     :
     QSGTexture{},
     texture_handle(texture_handle) {
 }
~GuiTexture()
openage::gui::GuiTexture::~GuiTexture () virtual
Definition at line 22 of file gui_texture.cpp.
{
 }
Member Function Documentation
bind()
void openage::gui::GuiTexture::bind () override private virtual
Definition at line 25 of file gui_texture.cpp.
                       {
     glBindTexture(GL_TEXTURE_2D, this->textureId());
 }
References textureId().
hasAlphaChannel()
bool openage::gui::GuiTexture::hasAlphaChannel () const override private virtual
Definition at line 29 of file gui_texture.cpp.
{
     // assume 32bit textures
     return true;
 }
hasMipmaps()
bool openage::gui::GuiTexture::hasMipmaps () const override private virtual
Definition at line 34 of file gui_texture.cpp.
{
     return false;
 }
isAtlasTexture()
bool openage::gui::GuiTexture::isAtlasTexture () const override private virtual
Definition at line 38 of file gui_texture.cpp.
{
     return openage::gui::isAtlasTexture(this->texture_handle);
 }
References openage::gui::isAtlasTexture(), and texture_handle.
Referenced by normalizedTextureSubRect(), and removedFromAtlas().
normalizedTextureSubRect()
QRectF openage::gui::GuiTexture::normalizedTextureSubRect () const override private virtual
Definition at line 103 of file gui_texture.cpp.
{
     if (this->isAtlasTexture()) {
         auto tex = this->texture_handle.texture;
         auto sub = tex->get_subtexture(this->texture_handle.subid);
         return QTransform::fromScale(tex->w, tex->h).inverted().mapRect(QRectF(sub->x, sub->y, sub->w, sub->h));
     } else {
         return QSGTexture::normalizedTextureSubRect();
     }
 }
References openage::Texture::get_subtexture(), isAtlasTexture(), openage::gui::TextureHandle::subid, openage::gui::TextureHandle::texture, and texture_handle.
removedFromAtlas()
QSGTexture * openage::gui::GuiTexture::removedFromAtlas () const override private virtual
Definition at line 69 of file gui_texture.cpp.
{
     if (this->isAtlasTexture()) {
         if (!this->standalone) {
             auto tex = this->texture_handle.texture;
             auto sub = tex->get_subtexture(this->texture_handle.subid);
             GLuint sub_texture_id = create_compatible_texture(tex->get_texture_id(), sub->w, sub->h);
             std::array<GLuint, 2>  fbo;
             glGenFramebuffers(fbo.size(), &fbo.front());
             glBindFramebuffer(GL_READ_FRAMEBUFFER, fbo[0]);
             glFramebufferTexture2D(GL_READ_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, this->textureId(), 0);
             glReadBuffer(GL_COLOR_ATTACHMENT0);
             glBindFramebuffer(GL_DRAW_FRAMEBUFFER, fbo[1]);
             glFramebufferTexture2D(GL_DRAW_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, sub_texture_id, 0);
             glDrawBuffer(GL_COLOR_ATTACHMENT0);
             glBlitFramebuffer(sub->x, sub->y, sub->x + sub->w, sub->y + sub->h, 0, 0, sub->w, sub->h, GL_COLOR_BUFFER_BIT, GL_NEAREST);
             glBindFramebuffer(GL_FRAMEBUFFER, 0);
             glDeleteFramebuffers(fbo.size(), &fbo.front());
             this->standalone = make_standalone_subtexture(sub_texture_id, QSize(sub->w, sub->h));
         }
         return this->standalone.get();
     }
     return nullptr;
 }
References openage::Texture::get_subtexture(), isAtlasTexture(), openage::gui::make_standalone_subtexture(), standalone, openage::gui::TextureHandle::subid, openage::gui::TextureHandle::texture, texture_handle, and textureId().
textureId()
int openage::gui::GuiTexture::textureId () const override private virtual
Definition at line 113 of file gui_texture.cpp.
{
     return this->texture_handle.texture->get_texture_id();
 }
References openage::Texture::get_texture_id(), openage::gui::TextureHandle::texture, and texture_handle.
Referenced by bind(), and removedFromAtlas().
textureSize()
QSize openage::gui::GuiTexture::textureSize () const override private virtual
Definition at line 117 of file gui_texture.cpp.
{
     return openage::gui::textureSize(this->texture_handle);
 }
References texture_handle, and openage::gui::textureSize().
Member Data Documentation
standalone
std::unique_ptr<QSGTexture> openage::gui::GuiTexture::standalone mutable private
Definition at line 32 of file gui_texture.h.
Referenced by removedFromAtlas().
texture_handle
const SizedTextureHandle openage::gui::GuiTexture::texture_handle private
Definition at line 31 of file gui_texture.h.
Referenced by isAtlasTexture(), normalizedTextureSubRect(), removedFromAtlas(), textureId(), and textureSize().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/integration/private/gui_texture.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/integration/private/gui_texture.cpp