openage: openage::gui::ResourcesListModel Class Reference
openage::gui::ResourcesListModel Class Reference
Resource table for the gui.
#include <resources_list_model.h>
Public Member Functions
ResourcesListModel (QObject *parent=nullptr)
virtual ~ResourcesListModel ()
ActionModeLink * get_action_mode () const
void set_action_mode (ActionModeLink *action_mode)
Properties
openage::gui::ActionModeLink actionMode
Private Slots
void on_resource_changed (game_resource resource, int amount)
Private Member Functions
virtual int rowCount (const QModelIndex &) const override
virtual QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
Private Attributes
std::vector< int > amounts
ActionModeLink * action_mode
Detailed Description
Resource table for the gui.
Definition at line 20 of file resources_list_model.h.
Constructor & Destructor Documentation
ResourcesListModel()
openage::gui::ResourcesListModel::ResourcesListModel (QObject * parent = nullptr)
Definition at line 25 of file resources_list_model.cpp.
     :
     QAbstractListModel(parent),
     amounts(resource_type_count),
     action_mode() {
     Q_UNUSED(registration);
 }
~ResourcesListModel()
openage::gui::ResourcesListModel::~ResourcesListModel () virtual
Definition at line 33 of file resources_list_model.cpp.
{
 }
Member Function Documentation
data()
QVariant openage::gui::ResourcesListModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override private virtual
Definition at line 71 of file resources_list_model.cpp.
{
     const int i = index.row();
     switch (role) {
     case Qt::DisplayRole:
         ENSURE(i >= 0 && i < std::distance(std::begin(this->amounts), std::end(this->amounts)), "Res type index is out of range: '" << i << "'.");
         return this->amounts[index.row()];
         break;
     default:
         break;
     }
     return QVariant{};
 }
References amounts, and ENSURE.
Referenced by openage.convert.peresource.PEResources::read_directory().
get_action_mode()
ActionModeLink * openage::gui::ResourcesListModel::get_action_mode () const
Definition at line 36 of file resources_list_model.cpp.
{
     return this->action_mode;
 }
References action_mode.
on_resource_changed
void openage::gui::ResourcesListModel::on_resource_changed (game_resource resource, int amount) private slot
Definition at line 54 of file resources_list_model.cpp.
{
     int i = static_cast<int>(resource);
     ENSURE(i >= 0 && i < std::distance(std::begin(this->amounts), std::end(this->amounts)), "Res type index is out of range: '" << i << "'.");
     if (this->amounts[i] != amount) {
         auto model_index = this->index(i);
         this->amounts[i] = amount;
         emit this->dataChanged(model_index, model_index, QVector<int>{Qt::DisplayRole});
     }
 }
References amounts, ENSURE, and openage::resource.
Referenced by set_action_mode().
rowCount()
int openage::gui::ResourcesListModel::rowCount (const QModelIndex &) const override private virtual
Definition at line 66 of file resources_list_model.cpp.
{
     ENSURE(resource_type_count == this->amounts.size(), "Res type count is compile-time const '" << resource_type_count << "', but got '" << this->amounts.size() << "'.");
     return this->amounts.size();
 }
References amounts, and ENSURE.
set_action_mode()
void openage::gui::ResourcesListModel::set_action_mode (ActionModeLink * action_mode)
Definition at line 40 of file resources_list_model.cpp.
{
     if (this->action_mode != action_mode) {
         if (this->action_mode) {
             QObject::disconnect(&unwrap(this->action_mode)->gui_signals, &ActionModeSignals::resource_changed, this, &ResourcesListModel::on_resource_changed);
         }
         this->action_mode = action_mode;
         if (this->action_mode) {
             QObject::connect(&unwrap(this->action_mode)->gui_signals, &ActionModeSignals::resource_changed, this, &ResourcesListModel::on_resource_changed);
         }
     }
 }
References action_mode, on_resource_changed(), openage::ActionModeSignals::resource_changed(), and qtsdl::unwrap().
Member Data Documentation
action_mode
ActionModeLink* openage::gui::ResourcesListModel::action_mode private
Definition at line 41 of file resources_list_model.h.
Referenced by get_action_mode(), and set_action_mode().
amounts
std::vector<int> openage::gui::ResourcesListModel::amounts private
Definition at line 39 of file resources_list_model.h.
Referenced by data(), on_resource_changed(), and rowCount().
Property Documentation
actionMode
openage::gui::ActionModeLink openage::gui::ResourcesListModel::actionMode read write
Definition at line 23 of file resources_list_model.h.
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/resources_list_model.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/resources_list_model.cpp