openage: qtsdl::GuiLiveReloaderAttachedProperty Class Reference
qtsdl::GuiLiveReloaderAttachedProperty Class Reference
The 'LR.tag' attached property.
#include <gui_live_reloader.h>
Public Member Functions
GuiLiveReloaderAttachedProperty (QObject *object)
GuiItemBase * get_attachee () const
QString get_tag () const
void set_tag (const QString &tag)
QString get_tag_for_init () const
Properties
QString tag
Tag that allows to connect newly created shells to corresponding cores after GUI reload.
Detailed Description
The 'LR.tag' attached property.
Definition at line 30 of file gui_live_reloader.h.
Constructor & Destructor Documentation
GuiLiveReloaderAttachedProperty()
qtsdl::GuiLiveReloaderAttachedProperty::GuiLiveReloaderAttachedProperty (QObject * object) explicit
Definition at line 18 of file gui_live_reloader.cpp.
     :
     QObject{object} {
     Q_UNUSED(registration);
     Q_UNUSED(registration_property);
     if (!dynamic_cast<GuiItemBase*>(this->parent()))
         qFatal("Error in QML code: tried to set the 'LR.tag' to item with non-persistent type '%s'.", object->metaObject()->className());
 }
Member Function Documentation
get_attachee()
GuiItemBase * qtsdl::GuiLiveReloaderAttachedProperty::get_attachee () const
Definition at line 28 of file gui_live_reloader.cpp.
{
     auto attachee = dynamic_cast<GuiItemBase*>(this->parent());
     assert(attachee);
     return attachee;
 }
Referenced by qtsdl::GuiSubtreeImpl::init_persistent_items(), and set_tag().
get_tag()
QString qtsdl::GuiLiveReloaderAttachedProperty::get_tag () const
Definition at line 35 of file gui_live_reloader.cpp.
{
     qWarning("Some QML code is enquiring about the '%s' 'LR.tag'. You must not rely on the tag value.", qUtf8Printable(this->tag));
     return this->tag;
 }
References tag.
get_tag_for_init()
QString qtsdl::GuiLiveReloaderAttachedProperty::get_tag_for_init () const
Definition at line 47 of file gui_live_reloader.cpp.
{
     return this->tag;
 }
References tag.
set_tag()
void qtsdl::GuiLiveReloaderAttachedProperty::set_tag (const QString & tag)
Definition at line 40 of file gui_live_reloader.cpp.
{
     if (this->get_attachee()->is_init_over())
         qCritical("Error in QML code: tried to change the '%s' 'LR.tag' to '%s'.", qUtf8Printable(this->tag), qUtf8Printable(tag));
     else
         this->tag = tag;
 }
References get_attachee(), and tag.
Property Documentation
tag
QString qtsdl::GuiLiveReloaderAttachedProperty::tag read write
Tag that allows to connect newly created shells to corresponding cores after GUI reload.
Definition at line 33 of file gui_live_reloader.h.
Referenced by get_tag(), get_tag_for_init(), and set_tag().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/guisys/private/livereload/gui_live_reloader.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/guisys/private/livereload/gui_live_reloader.cpp