openage: openage::util::File Class Reference
openage::util::File Class Reference
Generic File implementation, used in our filesystem-like and file-like abtraction system.
#include <file.h>
Public Types
using seek_t = filelike::FileLike::seek_t
using mode_t = filelike::FileLike::mode_t
Public Member Functions
File ()
Empty constructor, pls don't use.
File (const std::string &path, int mode)
Open a filesystem path, int version.
File (const std::string &path, mode_t mode=mode_t::R)
Open a filesystem path.
File (std::shared_ptr< filelike::FileLike > filelike)
Create a file from an already created filelike.
File (py::Obj filelike)
Wraps a python filelike object that is already open.
virtual ~File ()=default
std::string read (ssize_t max=-1)
Read data from the file and return a string.
size_t read_to (void *buf, ssize_t max=-1)
Read data from the file into a buffer, which has to be large enough to fit max bytes.
bool readable ()
void write (const std::string &data)
bool writable ()
void seek (ssize_t offset, seek_t how=seek_t::SET)
bool seekable ()
size_t tell ()
void close ()
void flush ()
ssize_t size ()
std::vector< std::string > get_lines ()
std::shared_ptr< filelike::FileLike > get_fileobj () const
Protected Attributes
std::shared_ptr< filelike::FileLike > filelike
Friends
std::ostream & operator<< (std::ostream &stream, const File &file)
Detailed Description
Generic File implementation, used in our filesystem-like and file-like abtraction system.
Can be created from Python :)
pxd:
cppclass File: File() noexcept File(const string &path, int mode) except + File(PyObj) except +
shared_ptr[FileLike] get_fileobj() except +
Definition at line 41 of file file.h.
Member Typedef Documentation
mode_t
using openage::util::File::mode_t = filelike::FileLike::mode_t
Definition at line 44 of file file.h.
seek_t
using openage::util::File::seek_t = filelike::FileLike::seek_t
Definition at line 43 of file file.h.
Constructor & Destructor Documentation
File() [1/5]
openage::util::File::File ()
Empty constructor, pls don't use.
It only exists because Cython needs it.
Definition at line 22 of file file.cpp.
 {}
File() [2/5]
openage::util::File::File (const std::string & path, int mode)
Open a filesystem path, int version.
this is just the integer value of the mode_t, because Cython...
Definition at line 26 of file file.cpp.
     :
     File{path, static_cast<mode_t>(mode)} {}
File() [3/5]
openage::util::File::File (const std::string & path, mode_t mode = mode_t::R)
Open a filesystem path.
Definition at line 31 of file file.cpp.
{
     this->filelike = std::make_shared<filelike::Native>(path, mode);
 }
References filelike.
File() [4/5]
openage::util::File::File (std::shared_ptr< filelike::FileLike > filelike)
Create a file from an already created filelike.
Definition at line 36 of file file.cpp.
     :
     filelike{filelike} {}
References filelike.
File() [5/5]
openage::util::File::File (py::Obj filelike)
Wraps a python filelike object that is already open.
This is called from Cython.
You will probably never call that manually.
Definition at line 41 of file file.cpp.
{
     this->filelike = std::make_shared<filelike::Python>(filelike);
 }
References filelike.
~File()
virtual openage::util::File::~File () virtual default
Member Function Documentation
close()
void openage::util::File::close ()
Definition at line 86 of file file.cpp.
                  {
     this->filelike->close();
 }
References filelike.
Referenced by openage.util.filelike.abstract.FileLikeObject::__exit__(), and openage.convert.slp_converter_pool.SLPConverterPool::__exit__().
flush()
void openage::util::File::flush ()
Definition at line 91 of file file.cpp.
                  {
     this->filelike->flush();
 }
References filelike.
get_fileobj()
std::shared_ptr< filelike::FileLike > openage::util::File::get_fileobj () const
Definition at line 119 of file file.cpp.
{
     return this->filelike;
 }
References filelike.
get_lines()
std::vector< std::string > openage::util::File::get_lines ()
Todo:
relay the get_lines to the underlaying filelike which may do a better job in getting the lines. instead, we read everything and then split up into lines.
Definition at line 101 of file file.cpp.
{
     std::string line;
     std::vector<std::string> result{};
     std::istringstream content{this->read()};
     while (std::getline(content, line)) {
         result.push_back(line);
     }
     return result;
 }
References openage::line, read(), and openage.testing.testing::result().
Referenced by openage::util::read_csv_file().
read()
std::string openage::util::File::read (ssize_t max = -1)
Read data from the file and return a string.
If max is negative, return the full remaining file.
Definition at line 46 of file file.cpp.
{
     return this->filelike->read(max);
 }
References filelike.
Referenced by get_lines(), openage.convert.dataformat.exportable.Exportable::read(), and openage.convert.peresource.StringLiteral::readall().
read_to()
size_t openage::util::File::read_to (void * buf, ssize_t max = -1)
Read data from the file into a buffer, which has to be large enough to fit max bytes.
If max is negative, read the full remaining file, so buf has to be as big as the remaining file size.
Returns the number of bytes that were read.
Definition at line 51 of file file.cpp.
{
     return this->filelike->read_to(buf, max);
 }
References filelike, and openage::console::tests::max().
readable()
bool openage::util::File::readable ()
Definition at line 56 of file file.cpp.
                     {
     return this->filelike->readable();
 }
References filelike.
seek()
void openage::util::File::seek (ssize_t offset, seek_t how = seek_t::SET)
Definition at line 71 of file file.cpp.
{
     this->filelike->seek(offset, how);
 }
References filelike.
seekable()
bool openage::util::File::seekable ()
Definition at line 76 of file file.cpp.
                     {
     return this->filelike->seekable();
 }
References filelike.
size()
ssize_t openage::util::File::size ()
Definition at line 96 of file file.cpp.
                    {
     return this->filelike->get_size();
 }
References filelike.
tell()
size_t openage::util::File::tell ()
Definition at line 81 of file file.cpp.
                   {
     return this->filelike->tell();
 }
References filelike.
Referenced by openage.util.filelike.abstract.FileLikeObject::seek_helper().
writable()
bool openage::util::File::writable ()
Definition at line 66 of file file.cpp.
                     {
     return this->filelike->writable();
 }
References filelike.
Referenced by openage.util.fslike.wrapper.Wrapper::resolve_w(), and openage.util.fslike.abstract.FSLikeObject::resolve_w().
write()
void openage::util::File::write (const std::string & data)
Definition at line 61 of file file.cpp.
{
     this->filelike->write(data);
 }
References filelike.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & stream, const File & file) friend
Definition at line 124 of file file.cpp.
{
     stream << "File(";
     file.filelike->repr(stream);
     stream << ")";
     return stream;
 }
Member Data Documentation
filelike
std::shared_ptr<filelike::FileLike> openage::util::File::filelike protected
Definition at line 107 of file file.h.
Referenced by close(), File(), flush(), get_fileobj(), openage::util::operator<<(), read(), read_to(), readable(), seek(), seekable(), size(), tell(), writable(), and write().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/file.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/file.cpp