openage: openage::event::EventTarget Class Reference
openage::event::EventTarget Class Reference abstract
Every Object in the gameworld that wants to be targeted by events or as dependency for events, has to implement this class.
#include <eventtarget.h>
Public Types
using single_change_notifier = std::function< void(const curve::time_t &)>
Public Member Functions
virtual size_t id () const =0
Give a unique event system identifier for the entity.
virtual ~EventTarget ()=default
void add_dependent (const std::weak_ptr< Event > &event)
Add a dependent class, that should be notified when dependency is called.
void show_dependents () const
For debugging: print the dependent eventclass ids as log messages.
Protected Member Functions
EventTarget (const std::shared_ptr< Loop > &loop, single_change_notifier parent_notifier=nullptr)
For children to be able to initialize us.
void changes (const curve::time_t &change_time)
Call this whenever some data in the target changes.
void trigger (const curve::time_t &last_valid_time)
Call this when a keyframe in the underlying container was passed by in time.
Private Attributes
std::shared_ptr< Loop > loop
Event loop this target is registered to.
std::list< std::weak_ptr< Event > > dependents
List of events that depend on this target.
single_change_notifier parent_notifier
Detailed Description
Every Object in the gameworld that wants to be targeted by events or as dependency for events, has to implement this class.
Definition at line 21 of file eventtarget.h.
Member Typedef Documentation
single_change_notifier
using openage::event::EventTarget::single_change_notifier = std::function<void(const curve::time_t &)>
Definition at line 26 of file eventtarget.h.
Constructor & Destructor Documentation
EventTarget()
openage::event::EventTarget::EventTarget (const std::shared_ptr< Loop > & loop, single_change_notifier parent_notifier = nullptr) inline protected
For children to be able to initialize us.
The notifier is used by hierarchical structures to be able to traverse a change up in the tree, this is necessary to make containers with event targets inside and listen to any changes on the full.
Definition at line 36 of file eventtarget.h.
         :
         loop{loop},
         parent_notifier{parent_notifier} {}
References loop.
~EventTarget()
virtual openage::event::EventTarget::~EventTarget () virtual default
Member Function Documentation
add_dependent()
void openage::event::EventTarget::add_dependent (const std::weak_ptr< Event > & event)
Add a dependent class, that should be notified when dependency is called.
Definition at line 90 of file eventtarget.cpp.
{
     this->dependents.emplace_back(event);
 }
References dependents.
changes()
void openage::event::EventTarget::changes (const curve::time_t & change_time) protected
Call this whenever some data in the target changes.
This triggers the reevaluation of dependent events.
Definition at line 14 of file eventtarget.cpp.
{
     // This target has some change, so we have to notify all dependents
     // that subscribed on this target.
     log::log(DBG << "Target: change happens on " << this->id() << " at t=" << time);
     if (this->parent_notifier != nullptr) {
         this->parent_notifier(time);
     }
     // This is a maybe-erase construct so obsolete dependents are cleaned up.
     for (auto it = this->dependents.begin(); it != this->dependents.end(); ) {
         auto dependent = it->lock();
         if (dependent) {
             switch (dependent->get_eventclass()->type) {
             case EventClass::trigger_type::DEPENDENCY_IMMEDIATELY:
             case EventClass::trigger_type::DEPENDENCY:
                 // Enqueue a change so that change events will be retriggered
                 // (that depend on this target)
                 // FIXME: Traverse the changed value
                 this->loop->create_change(dependent, time, 0);
                 ++it;
                 break;
             case EventClass::trigger_type::ONCE:
                 // If the dependent is a ONCE-event
                 // Has it been triggered? If so - forget it.
                 if (dependent->last_triggered > 0) {
                     it = this->dependents.erase(it);
                 } else {
                     // FIXME: Traverse the changed value
                     this->loop->create_change(dependent, time, 0);
                     ++it;
                 }
                 break;
             case EventClass::trigger_type::TRIGGER:
             case EventClass::trigger_type::REPEAT:
                 // Ignore announced changes for execute/keyframe events
                 ++it;
                 break;
             }
         }
         else {
             // The dependent is no more, so we can safely forget him
             it = this->dependents.erase(it);
         }
     }
 }
References DBG, openage::event::EventClass::DEPENDENCY, openage::event::EventClass::DEPENDENCY_IMMEDIATELY, dependents, openage::log::log(), loop, openage::event::EventClass::ONCE, parent_notifier, openage::event::EventClass::REPEAT, and openage::event::EventClass::TRIGGER.
Referenced by openage::event::tests::TestState::TestObject::set_number().
id()
virtual size_t openage::event::EventTarget::id () const pure virtual
Give a unique event system identifier for the entity.
Implemented in openage::event::demo::PongBall, openage::event::demo::PongPlayer, openage::curve::ValueContainer< T >, and openage::event::tests::TestState::TestObject.
show_dependents()
void openage::event::EventTarget::show_dependents () const
For debugging: print the dependent eventclass ids as log messages.
Definition at line 94 of file eventtarget.cpp.
{
     log::log(DBG << "Dependent list:");
     for (auto &dep : this->dependents) {
         auto dependent = dep.lock();
         if (dependent) {
             log::log(DBG << " - " << dependent->get_eventclass()->id());
         }
         else {
             log::log(DBG << " - ** outdated old reference **");
         }
     }
 }
References DBG, dependents, and openage::log::log().
trigger()
void openage::event::EventTarget::trigger (const curve::time_t & last_valid_time) protected
Call this when a keyframe in the underlying container was passed by in time.
Definition at line 64 of file eventtarget.cpp.
{
     // notify all dependent events that are triggered `on_keyframe`
     // that the this target changed.
     // the only events that is "notified" by are TRIGGER.
     for (auto it = this->dependents.begin(); it != this->dependents.end(); ) {
         auto dependent = it->lock();
         if (dependent) {
             if (dependent->get_eventclass()->type == EventClass::trigger_type::TRIGGER) {
                 log::log(DBG << "Target: trigger creates a change for "
                          << dependent->get_eventclass()->id()
                          << " at t=" << last_valid_time);
                 // FIXME: Traverse the changed value
                 loop->create_change(dependent, last_valid_time, 0);
             }
             ++it;
         }
         else {
             it = this->dependents.erase(it);
         }
     }
 }
References DBG, dependents, openage::log::log(), loop, and openage::event::EventClass::TRIGGER.
Referenced by openage::event::tests::TestState::TestObject::test_trigger().
Member Data Documentation
dependents
std::list<std::weak_ptr<Event> > openage::event::EventTarget::dependents private
List of events that depend on this target.
Definition at line 71 of file eventtarget.h.
Referenced by add_dependent(), changes(), show_dependents(), and trigger().
loop
std::shared_ptr<Loop> openage::event::EventTarget::loop private
Event loop this target is registered to.
Definition at line 68 of file eventtarget.h.
Referenced by changes(), EventTarget(), and trigger().
parent_notifier
single_change_notifier openage::event::EventTarget::parent_notifier private
Definition at line 73 of file eventtarget.h.
Referenced by changes().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/event/eventtarget.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/event/eventtarget.cpp