openage: openage::IdleAction Class Reference
openage::IdleAction Class Reference
keeps an entity in a fixed position
#include <action.h>
Public Member Functions
IdleAction (Unit *e)
virtual ~IdleAction ()
void update (unsigned int time) override
each action has its own update functionality which gets called when this is the active action
void on_completion () override
action to perform when popped from a units action stack
bool completed () const override
gets called for all actions on stack each update cycle
bool allow_interupt () const override
checks if the action can be interrupted, allowing it to be popped if the user specifies a new action, if false the action must reach a completed state before removal eg dead action must be completed and cannot be discarded
bool allow_control () const override
control whether stack can discard the action automatically and should the stack be modifiable when this action is on top
std::string name () const override
debug string to identify action types
Public Member Functions inherited from openage::UnitAction
UnitAction (Unit *u, graphic_type initial_gt)
Require unit to be updated and an initial graphic type.
virtual ~UnitAction ()
graphic_type type () const
type of graphic this action should use
float current_frame () const
frame number to use on the current graphic
virtual const graphic_set & current_graphics () const
determines which graphic should be used for drawing this unit finds the default graphic using the units type, used by most actions
void draw_debug (const Engine &engine)
void face_towards (const coord::phys3 pos)
common functions for actions
bool damage_unit (Unit &target)
Damage a unit, returns true if the unit was killed in the process.
void move_to (Unit &target, bool use_range=true)
Private Attributes
std::shared_ptr< TerrainSearch > search
ability_set auto_abilities
Additional Inherited Members
Static Public Member Functions inherited from openage::UnitAction
static coord::phys_t adjacent_range (Unit *u)
a small distance to which units are considered touching when within this distance
static coord::phys_t get_attack_range (Unit *u)
looks at an ranged attributes on the unit otherwise returns same as adjacent_range()
static coord::phys_t get_heal_range (Unit *u)
looks at heal attribute on the unit otherwise returns same as adjacent_range()
Static Public Attributes inherited from openage::UnitAction
static bool show_debug = false
produce debug info such as visualising paths
Protected Attributes inherited from openage::UnitAction
Unit * entity
the entity being updated
graphic_type graphic
common graphic controls
float frame
float frame_rate
std::function< void(const Engine &)> debug_draw_action
additional drawing for debug purposes
Detailed Description
keeps an entity in a fixed position
Definition at line 336 of file action.h.
Constructor & Destructor Documentation
IdleAction()
openage::IdleAction::IdleAction (Unit * e)
Definition at line 453 of file action.cpp.
     :
     UnitAction(e, graphic_type::standing) {
     auto terrain = this->entity->location->get_terrain();
     auto current_tile = this->entity->location->pos.draw.to_tile3().to_tile();
     this->search = std::make_shared<TerrainSearch>(terrain, current_tile, 5.0f);
     // currently allow attack and heal automatically
     this->auto_abilities = UnitAbility::set_from_list({ability_type::attack, ability_type::heal});
 }
References openage::attack, auto_abilities, openage::UnitAction::entity, openage::heal, openage::Unit::location, search, openage::UnitAbility::set_from_list(), and openage::standing.
~IdleAction()
virtual openage::IdleAction::~IdleAction () inline virtual
Definition at line 339 of file action.h.
 {}
Member Function Documentation
allow_control()
bool openage::IdleAction::allow_control () const inline override virtual
control whether stack can discard the action automatically and should the stack be modifiable when this action is on top
if true this action must complete and will not allow new actions to be pushed while it is active and also does not update the secondary actions
Implements openage::UnitAction.
Definition at line 345 of file action.h.
 { return true; }
allow_interupt()
bool openage::IdleAction::allow_interupt () const inline override virtual
checks if the action can be interrupted, allowing it to be popped if the user specifies a new action, if false the action must reach a completed state before removal eg dead action must be completed and cannot be discarded
Implements openage::UnitAction.
Definition at line 344 of file action.h.
 { return false; }
completed()
bool openage::IdleAction::completed () const override virtual
gets called for all actions on stack each update cycle
Returns
true when action is completed so it and everything above it can be popped
Implements openage::UnitAction.
Definition at line 536 of file action.cpp.
{
     if (this->entity->has_attribute(attr_type::damaged)) {
         auto &dm = this->entity->get_attribute<attr_type::damaged>();
         return dm.hp == 0;
     }
     else if (this->entity->has_attribute(attr_type::resource)) {
         auto &res_attr = this->entity->get_attribute<attr_type::resource>();
         return res_attr.amount <= 0.0;
     }
     return false;
 }
References openage::damaged, openage::UnitAction::entity, openage::Unit::get_attribute(), openage::Unit::has_attribute(), and openage::resource.
name()
std::string openage::IdleAction::name () const inline override virtual
debug string to identify action types
Implements openage::UnitAction.
Definition at line 346 of file action.h.
 { return "idle"; }
Referenced by openage.util.fslike.path.Path::stem(), openage.util.fslike.path.Path::suffix(), and openage.util.fslike.path.Path::suffixes().
on_completion()
void openage::IdleAction::on_completion () override virtual
action to perform when popped from a units action stack
Implements openage::UnitAction.
Definition at line 534 of file action.cpp.
 {}
update()
void openage::IdleAction::update (unsigned int time) override virtual
each action has its own update functionality which gets called when this is the active action
Implements openage::UnitAction.
Definition at line 464 of file action.cpp.
{
     // auto task searching
     if (this->entity->location &&
         this->entity->has_attribute(attr_type::owner) &&
         this->entity->has_attribute(attr_type::attack) &&
         this->entity->has_attribute(attr_type::formation) &&
         this->entity->get_attribute<attr_type::formation>().stance != attack_stance::do_nothing) {
         // restart search from new tile when moved
         auto terrain = this->entity->location->get_terrain();
         auto current_tile = this->entity->location->pos.draw.to_tile3().to_tile();
         if (!(current_tile == this->search->start_tile())) {
             this->search = std::make_shared<TerrainSearch>(terrain, current_tile, 5.0f);
         }
         // search one tile per update
         // next tile will always be valid
         coord::tile tile = this->search->next_tile();
         auto tile_data = terrain->get_data(tile);
         auto &player = this->entity->get_attribute<attr_type::owner>().player;
         // find and actions which can be invoked
         for (auto object_location : tile_data->obj) {
             Command to_object(player, &object_location->unit);
             // only allow abilities in the set of auto ability types
             to_object.set_ability_set(auto_abilities);
             if (this->entity->queue_cmd(to_object)) {
                 break;
             }
         }
     }
     // generate resources
     // \todo move elsewhere
     if (this->entity->has_attribute(attr_type::resource_generator) &&
         this->entity->has_attribute(attr_type::owner)) {
         auto &player = this->entity->get_attribute<attr_type::owner>().player;
         auto &resource_generator = this->entity->get_attribute<attr_type::resource_generator>();
         ResourceBundle resources = resource_generator.resources.clone();
         if (resource_generator.rate == 0) {
             resources *= time;
         } else {
             // \todo add in intervals and not continuously
             resources *= time * resource_generator.rate;
         }
         player.receive(resources);
     }
     // unit carrying ressources take the carrying sprite when idle
     // we're not updating frames because the carying sprite is walking
     if (entity->has_attribute(attr_type::worker)) {
         auto &worker_resource = this->entity->get_attribute<attr_type::resource>();
         if (worker_resource.amount > 0) {
             this->graphic = graphic_type::carrying;
         } else {
             this->graphic = graphic_type::standing;
             this->frame += time * this->frame_rate / 20.0f;
         }
     }
     else {
         // inc frame
         this->frame += time * this->frame_rate / 20.0f;
     }
 }
References openage::attack, auto_abilities, openage::carrying, openage::do_nothing, openage::UnitAction::entity, openage::formation, openage::UnitAction::frame, openage::UnitAction::frame_rate, openage::Unit::get_attribute(), openage::UnitAction::graphic, openage::Unit::has_attribute(), openage::Unit::location, openage::owner, openage::Unit::queue_cmd(), openage::resource, openage::resource_generator, search, openage::standing, openage::path::to_object(), and openage::worker.
Member Data Documentation
auto_abilities
ability_set openage::IdleAction::auto_abilities private
Definition at line 351 of file action.h.
Referenced by IdleAction(), and update().
search
std::shared_ptr<TerrainSearch> openage::IdleAction::search private
Definition at line 350 of file action.h.
Referenced by IdleAction(), and update().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/action.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/action.cpp