openage: openage::gui::GameSaver Class Reference
openage::gui::GameSaver Class Reference
#include <game_saver.h>
Public Slots
void on_processed (const QString &error_string)
Signals
void error_string_changed ()
void game_changed ()
void generator_parameters_changed ()
Public Member Functions
GameSaver (QObject *parent=nullptr)
virtual ~GameSaver ()
QString get_error_string () const
Q_INVOKABLE void activate ()
Q_INVOKABLE void clearErrors ()
Properties
QString errorString
openage::gui::GameMainLink game
openage::gui::GeneratorLink generatorParameters
Private Attributes
QString error_string
GameMainLink * game
GeneratorLink * generator_parameters
Detailed Description
Definition at line 13 of file game_saver.h.
Constructor & Destructor Documentation
GameSaver()
openage::gui::GameSaver::GameSaver (QObject * parent = nullptr) explicit
Definition at line 21 of file game_saver.cpp.
     :
     QObject{parent},
     game{},
     generator_parameters{} {
     Q_UNUSED(registration);
 }
~GameSaver()
openage::gui::GameSaver::~GameSaver () virtual
Definition at line 29 of file game_saver.cpp.
                       {
 }
Member Function Documentation
activate()
void openage::gui::GameSaver::activate ()
Definition at line 37 of file game_saver.cpp.
{
     static auto f = [] (GameMainHandle *game,
                         Generator *generator,
                         std::shared_ptr<GameSaverSignals> callback) {
         QString error_msg;
         if (!game->is_game_running()) {
             error_msg = "no open game to save";
         } else {
             auto filename = generator->getv<std::string>("load_filename");
             gameio::save(game->get_game(), filename);
         }
         emit callback->error_message(error_msg);
     };
     if (this->game && this->generator_parameters) {
         std::shared_ptr<GameSaverSignals> callback = std::make_shared<GameSaverSignals>();
         QObject::connect(callback.get(),
                          &GameSaverSignals::error_message,
                          this,
                          &GameSaver::on_processed);
         this->game->i(f, this->generator_parameters, callback);
     }
     else {
         QString error_msg = "unknown error";
         if (!this->game) {
             error_msg = "provide 'game' before saving";
         }
         if (!this->generator_parameters) {
             error_msg = "provide 'generatorParameters' before saving";
         }
         else {
             ENSURE(false, "unhandled case for refusal to create a game");
         }
         this->on_processed(error_msg);
     }
 }
References ENSURE, openage::gui::GameSaverSignals::error_message(), openage::util::filename(), game, generator_parameters, on_processed(), and openage::gameio::save().
clearErrors()
void openage::gui::GameSaver::clearErrors ()
Definition at line 81 of file game_saver.cpp.
{
     this->error_string.clear();
     emit this->error_string_changed();
 }
References error_string, and error_string_changed().
error_string_changed
void openage::gui::GameSaver::error_string_changed () signal
Referenced by clearErrors(), and on_processed().
game_changed
void openage::gui::GameSaver::game_changed () signal
generator_parameters_changed
void openage::gui::GameSaver::generator_parameters_changed () signal
get_error_string()
QString openage::gui::GameSaver::get_error_string () const
Definition at line 32 of file game_saver.cpp.
{
     return this->error_string;
 }
References error_string.
on_processed
void openage::gui::GameSaver::on_processed (const QString & error_string) slot
Definition at line 86 of file game_saver.cpp.
{
     this->error_string = error_string;
     emit this->error_string_changed();
 }
References error_string, and error_string_changed().
Referenced by activate().
Member Data Documentation
error_string
QString openage::gui::GameSaver::error_string private
Definition at line 39 of file game_saver.h.
Referenced by clearErrors(), get_error_string(), and on_processed().
game
GameMainLink* openage::gui::GameSaver::game private
Definition at line 40 of file game_saver.h.
generator_parameters
GeneratorLink* openage::gui::GameSaver::generator_parameters private
Definition at line 41 of file game_saver.h.
Referenced by activate().
Property Documentation
errorString
QString openage::gui::GameSaver::errorString read
Definition at line 17 of file game_saver.h.
game
openage::gui::GameMainLink openage::gui::GameSaver::game
Definition at line 18 of file game_saver.h.
Referenced by activate().
generatorParameters
openage::gui::GeneratorLink openage::gui::GameSaver::generatorParameters
Definition at line 19 of file game_saver.h.
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/game_saver.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/game_saver.cpp