openage: openage::curve::CurveIterator< val_t, container_t, iterator_t > Class Template Reference
openage::curve::CurveIterator< val_t, container_t, iterator_t > Class Template Reference abstract
#include <iterator.h>
Public Member Functions
virtual const val_t & value () const =0
virtual bool valid () const =0
CurveIterator (const container_t *c)
CurveIterator (const CurveIterator &)=default
virtual ~CurveIterator ()=default
CurveIterator< val_t, container_t, iterator_t > & operator= (const CurveIterator< val_t, container_t, iterator_t > &)=default
virtual const val_t & operator * () const
virtual const val_t * operator -> () const
virtual bool operator== (const CurveIterator< val_t, container_t > &rhs) const
virtual bool operator != (const CurveIterator< val_t, container_t > &rhs) const
virtual CurveIterator< val_t, container_t > & operator++ ()
const iterator_t & get_base () const
const time_t & get_from () const
const time_t & get_to () const
Protected Member Functions
CurveIterator (const iterator_t &base, const container_t *container, const time_t &from, const time_t &to)
Protected Attributes
iterator_t base
The iterator this is currently referring to.
const container_t * container
The base container.
time_t from
The time, from where this iterator started to iterate.
time_t to
The time, to where this iterator will iterate.
Detailed Description
template<typename val_t, typename container_t, typename iterator_t = typename container_t::const_iterator>
class openage::curve::CurveIterator< val_t, container_t, iterator_t >
Default interface for curve containers
Definition at line 15 of file iterator.h.
Constructor & Destructor Documentation
CurveIterator() [1/3]
template<typename val_t, typename container_t, typename iterator_t = typename container_t::const_iterator> openage::curve::CurveIterator< val_t, container_t, iterator_t >::CurveIterator (const container_t * c) inline explicit
The iterator needs a reference to the container
Definition at line 31 of file iterator.h.
         :
         base{},
         container{c},
         from{-std::numeric_limits<time_t>::max()},
         to{+std::numeric_limits<time_t>::max()} {}
CurveIterator() [2/3]
template<typename val_t, typename container_t, typename iterator_t = typename container_t::const_iterator> openage::curve::CurveIterator< val_t, container_t, iterator_t >::CurveIterator (const iterator_t & base, const container_t * container, const time_t & from, const time_t & to) inline protected
Can only be constructed from the referenced container
Definition at line 42 of file iterator.h.
         :
         base{base},
         container{container},
         from{from},
         to{to} {}
CurveIterator() [3/3]
template<typename val_t, typename container_t, typename iterator_t = typename container_t::const_iterator> openage::curve::CurveIterator< val_t, container_t, iterator_t >::CurveIterator (const CurveIterator< val_t, container_t, iterator_t > &) default
Default copy c'tor
~CurveIterator()
template<typename val_t, typename container_t, typename iterator_t = typename container_t::const_iterator> virtual openage::curve::CurveIterator< val_t, container_t, iterator_t >::~CurveIterator () virtual default
Member Function Documentation
get_base()
template<typename val_t, typename container_t, typename iterator_t = typename container_t::const_iterator> const iterator_t& openage::curve::CurveIterator< val_t, container_t, iterator_t >::get_base () const inline
Access the underlying
Definition at line 102 of file iterator.h.
{
         return base;
     }
get_from()
template<typename val_t, typename container_t, typename iterator_t = typename container_t::const_iterator> const time_t& openage::curve::CurveIterator< val_t, container_t, iterator_t >::get_from () const inline
Access the lower end value of the defined time frame
Definition at line 109 of file iterator.h.
{
         return from;
     }
get_to()
template<typename val_t, typename container_t, typename iterator_t = typename container_t::const_iterator> const time_t& openage::curve::CurveIterator< val_t, container_t, iterator_t >::get_to () const inline
Access the higher end value of the defined time frame
Definition at line 116 of file iterator.h.
{
         return to;
     }
operator !=()
template<typename val_t, typename container_t, typename iterator_t = typename container_t::const_iterator> virtual bool openage::curve::CurveIterator< val_t, container_t, iterator_t >::operator != (const CurveIterator< val_t, container_t > & rhs) const inline virtual
For unequalness only the base iterator will be testet - not the timespans this is defined in.
Definition at line 84 of file iterator.h.
{
         return this->base != rhs.base;
     }
operator *()
template<typename val_t, typename container_t, typename iterator_t = typename container_t::const_iterator> virtual const val_t& openage::curve::CurveIterator< val_t, container_t, iterator_t >::operator * () const inline virtual
Dereference will call the virtual function
Definition at line 63 of file iterator.h.
{
         return this->value();
     }
operator ->()
template<typename val_t, typename container_t, typename iterator_t = typename container_t::const_iterator> virtual const val_t* openage::curve::CurveIterator< val_t, container_t, iterator_t >::operator -> () const inline virtual
Dereference will call the virutal function
Definition at line 68 of file iterator.h.
{
         return &this->value();
     }
operator++()
template<typename val_t, typename container_t, typename iterator_t = typename container_t::const_iterator> virtual CurveIterator<val_t, container_t>& openage::curve::CurveIterator< val_t, container_t, iterator_t >::operator++ () inline virtual
Advance to the next valid element.
Definition at line 91 of file iterator.h.
{
         do {
             ++this->base;
         } while (this->container->end().base != this->base and not this->valid());
         return *this;
     }
operator=()
template<typename val_t, typename container_t, typename iterator_t = typename container_t::const_iterator> CurveIterator<val_t, container_t, iterator_t>& openage::curve::CurveIterator< val_t, container_t, iterator_t >::operator= (const CurveIterator< val_t, container_t, iterator_t > &) default
Default assignment operator
operator==()
template<typename val_t, typename container_t, typename iterator_t = typename container_t::const_iterator> virtual bool openage::curve::CurveIterator< val_t, container_t, iterator_t >::operator== (const CurveIterator< val_t, container_t > & rhs) const inline virtual
For equalness only the base iterator will be testet - not the timespans this is defined in.
Definition at line 76 of file iterator.h.
{
         return this->base == rhs.base;
     }
valid()
template<typename val_t, typename container_t, typename iterator_t = typename container_t::const_iterator> virtual bool openage::curve::CurveIterator< val_t, container_t, iterator_t >::valid () const pure virtual
Check if the iterator is still valid (this breaks from the stl - in the best way)
Implemented in openage::curve::MapFilterIterator< key_t, val_t, container_t >, and openage::curve::QueueFilterIterator< val_t, container_t >.
Referenced by openage::curve::CurveIterator< val_t, container_t >::operator++().
value()
template<typename val_t, typename container_t, typename iterator_t = typename container_t::const_iterator> virtual const val_t& openage::curve::CurveIterator< val_t, container_t, iterator_t >::value () const pure virtual
access the value of the iterator
Implemented in openage::curve::MapFilterIterator< key_t, val_t, container_t >, and openage::curve::QueueFilterIterator< val_t, container_t >.
Referenced by openage.convert.dataformat.members.ContinueReadMemberResult::__str__(), openage::curve::CurveIterator< val_t, container_t >::operator *(), and openage::curve::CurveIterator< val_t, container_t >::operator ->().
Member Data Documentation
base
template<typename val_t, typename container_t, typename iterator_t = typename container_t::const_iterator> iterator_t openage::curve::CurveIterator< val_t, container_t, iterator_t >::base protected
The iterator this is currently referring to.
Definition at line 122 of file iterator.h.
Referenced by openage::curve::CurveIterator< val_t, container_t >::CurveIterator(), openage::curve::CurveIterator< val_t, container_t >::get_base(), openage::curve::CurveIterator< val_t, container_t >::operator !=(), openage::curve::CurveIterator< val_t, container_t >::operator++(), and openage::curve::CurveIterator< val_t, container_t >::operator==().
container
template<typename val_t, typename container_t, typename iterator_t = typename container_t::const_iterator> const container_t* openage::curve::CurveIterator< val_t, container_t, iterator_t >::container protected
The base container.
Definition at line 125 of file iterator.h.
Referenced by openage::curve::CurveIterator< val_t, container_t >::operator++().
from
template<typename val_t, typename container_t, typename iterator_t = typename container_t::const_iterator> time_t openage::curve::CurveIterator< val_t, container_t, iterator_t >::from protected
The time, from where this iterator started to iterate.
Definition at line 128 of file iterator.h.
Referenced by openage::curve::CurveIterator< val_t, container_t >::get_from().
to
template<typename val_t, typename container_t, typename iterator_t = typename container_t::const_iterator> time_t openage::curve::CurveIterator< val_t, container_t, iterator_t >::to protected
The time, to where this iterator will iterate.
Definition at line 131 of file iterator.h.
Referenced by openage::curve::CurveIterator< val_t, container_t >::get_to().
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/curve/iterator.h