openage: openage::input::InputContext Class Reference
openage::input::InputContext Class Reference
#include <input_context.h>
Public Member Functions
InputContext ()
InputContext (InputManager *manager)
virtual ~InputContext ()=default
std::vector< std::string > active_binds () const
void bind (action_t type, const action_func_t act)
void bind (const Event &ev, const action_func_t act)
void bind (event_class ec, const action_check_t act)
bool execute_if_bound (const action_arg_t &e)
void register_to (InputManager *manager)
void unregister ()
Public Attributes
bool utf8_mode
Private Attributes
InputManager * input_manager
std::unordered_map< action_t, action_func_t > by_type
std::unordered_map< Event, action_func_t, event_hash > by_event
std::unordered_map< event_class, action_check_t, event_class_hash > by_class
Detailed Description
An input context contains all keybindings and actions active in e.g. the HUD only. For the console, there's a different input context. That way, each context can have the same keys assigned to different actions, the active context decides, which one to trigger.
Definition at line 27 of file input_context.h.
Constructor & Destructor Documentation
InputContext() [1/2]
openage::input::InputContext::InputContext ()
Create an unbound input context.
Definition at line 12 of file input_context.cpp.
     :
     InputContext{nullptr} {}
Referenced by openage::ActionMode::announce_buttons_type(), openage::ActionMode::on_exit(), and openage::ActionMode::on_game_control_set().
InputContext() [2/2]
openage::input::InputContext::InputContext (InputManager * manager)
Create a bound context, assigned to its manager.
Definition at line 17 of file input_context.cpp.
     :
     utf8_mode{false} {
     this->register_to(manager);
 }
~InputContext()
virtual openage::input::InputContext::~InputContext () virtual default
Member Function Documentation
active_binds()
std::vector< std::string > openage::input::InputContext::active_binds () const
a list of all keys of this context which are bound currently in the active context.
Todo:
move this method to the input manager. as InputManager::active_binds(const InputContext &) const;
Definition at line 25 of file input_context.cpp.
{
     if (this->input_manager == nullptr) {
         return {};
     }
     // \todo try to purge this backpointer to the input manager.
     return this->input_manager->active_binds(this->by_type);
 }
References openage::input::InputManager::active_binds(), by_type, and input_manager.
Referenced by openage::OutputMode::announce().
bind() [1/3]
void openage::input::InputContext::bind (action_t type, const action_func_t act)
bind a specific action idetifier this is the highest matching priority
Definition at line 34 of file input_context.cpp.
{
     this->by_type.emplace(std::make_pair(type, act));
 }
References by_type.
Referenced by openage::ActionMode::on_game_control_set(), openage::EditorMode::on_game_control_set(), openage::console::Console::register_to_engine(), and openage::GameControl::set_engine().
bind() [2/3]
void openage::input::InputContext::bind (const Event & ev, const action_func_t act)
bind a specific event this is the second matching priority
Definition at line 38 of file input_context.cpp.
{
     this->by_event.emplace(std::make_pair(ev, act));
 }
References by_event.
bind() [3/3]
void openage::input::InputContext::bind (event_class ec, const action_check_t act)
bind all events of a specific class this is the lowest matching priority
Definition at line 42 of file input_context.cpp.
{
     this->by_class.emplace(std::make_pair(ec, act));
 }
References by_class.
execute_if_bound()
bool openage::input::InputContext::execute_if_bound (const action_arg_t & e)
lookup an action. If it is bound, execute it.
Returns
true when the action is executed, false else.
Definition at line 46 of file input_context.cpp.
{
     // arg type hints are highest priority
     for (auto &h : arg.hints) {
         auto action = this->by_type.find(h);
         if (action != this->by_type.end()) {
             action->second(arg);
             return true;
         }
     }
     // specific event mappings
     auto action = this->by_event.find(arg.e);
     if (action != this->by_event.end()) {
         action->second(arg);
         return true;
     }
     // check all possible class mappings
     for (auto &c : arg.e.cc.get_classes()) {
         auto action = this->by_class.find(c);
         if (action != this->by_class.end() &&
             action->second(arg)) {
             return true;
         }
     }
     return false;
 }
References by_class, by_event, by_type, openage::input::Event::cc, openage::input::action_arg_t::e, openage::input::ClassCode::get_classes(), and openage::input::action_arg_t::hints.
Referenced by openage::ActionModeSignals::on_action(), and openage::input::InputManager::trigger().
register_to()
void openage::input::InputContext::register_to (InputManager * manager)
Called by the InputManager where this context shall be registered to.
Definition at line 77 of file input_context.cpp.
{
     this->input_manager = manager;
 }
References input_manager.
Referenced by openage::input::InputManager::push_context().
unregister()
void openage::input::InputContext::unregister ()
Remove the registration to an input manager.
Definition at line 82 of file input_context.cpp.
{
     this->input_manager = nullptr;
 }
References input_manager.
Referenced by openage::input::InputManager::remove_context().
Member Data Documentation
by_class
std::unordered_map<event_class, action_check_t, event_class_hash> openage::input::InputContext::by_class private
event to action map event_class as key, to ensure all events can be mapped
Definition at line 115 of file input_context.h.
Referenced by bind(), and execute_if_bound().
by_event
std::unordered_map<Event, action_func_t, event_hash> openage::input::InputContext::by_event private
map specific overriding events
Definition at line 109 of file input_context.h.
Referenced by bind(), and execute_if_bound().
by_type
std::unordered_map<action_t, action_func_t> openage::input::InputContext::by_type private
Maps an action id to a event execution function.
Definition at line 104 of file input_context.h.
Referenced by active_binds(), bind(), and execute_if_bound().
input_manager
InputManager* openage::input::InputContext::input_manager private
Input manager this context is bound to.
Definition at line 99 of file input_context.h.
Referenced by active_binds(), openage::ActionMode::on_exit(), register_to(), and unregister().
utf8_mode
bool openage::input::InputContext::utf8_mode
Affects which keyboard events are received: true to accpet utf8 text events, false to receive regular char events
Definition at line 92 of file input_context.h.
Referenced by openage::input::InputManager::ignored(), and openage::console::Console::register_to_engine().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/input/input_context.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/input/input_context.cpp