openage: openage.cabextract.cab.CABFile Class Reference
openage.cabextract.cab.CABFile Class Reference
The actual file system-like CAB object.
Public Member Functions
def __init__ (self, cab)
def __repr__ (self)
def read_folder_headers (self, cab)
Called during the constructor run.
def read_file_headers (self, cab)
Called during the constructor run.
Public Member Functions inherited from openage.util.fslike.filecollection.FileCollection
def __init__ (self)
def root (self)
Returns a path-like object for the root of this file system.
def get_direntries (self, parts=None, create=False)
Fetches the fileentries, subdirentries tuple for the given dir.
def add_fileentry (self, parts, fileentry)
Adds a file entry (and parent directory entries, if needed).
def get_fileentry (self, parts)
Gets a file entry.
def open_r (self, parts)
Shall return a BufferedReader for the given file ("mode 'rb'").
def open_w (self, parts)
Shall return a BufferedWriter for the given file ("mode 'wb'").
def list (self, parts)
Shall yield the entry names of the given directory.
def filesize (self, parts)
def mtime (self, parts)
def mkdirs (self, parts)
Shall ensure that the directory exists.
def rmdir (self, parts)
Shall remove an empty directory.
def unlink (self, parts)
Shall remove a single file.
def touch (self, parts)
Shall create the file or update its timestamp.
def rename (self, srcparts, tgtparts)
Shall rename a file or directory to the target name.
def is_file (self, parts)
def is_dir (self, parts)
def writable (self, parts)
def watch (self, parts, callback)
def poll_watches (self)
Public Member Functions inherited from openage.util.fslike.abstract.FSLikeObject
def pretty (self, parts)
pretty-format a path in this filesystem like object.
def open_rw (self, parts)
Shall return a BufferedWriter for the given file ("mode 'r+'").
def open_a (self, parts)
Shall return a BufferedWriter for the given file ("mode 'a'").
def open_ar (self, parts)
Shall return a BufferedWriter for the given file ("mode 'a+'").
def exists (self, parts)
Test if the parts are a file or a directory.
def resolve_r (self, parts)
def resolve_w (self, parts)
Returns a new flattened path.
def get_native_path (self, parts)
Public Attributes
header
folders
rootdir
Public Attributes inherited from openage.util.fslike.filecollection.FileCollection
rootentries
Detailed Description
The actual file system-like CAB object.
Constructor arguments:
Parameters
cab A file-like object that must implement read() and seek() with whence=os.SEEK_SET.
The constructor reads the entire header, including the folder and file descriptions. Most CAB file issues should cause the constructor to fail.
Definition at line 228 of file cab.py.
Constructor & Destructor Documentation
__init__()
def openage.cabextract.cab.CABFile.__init__ (self, cab)
Definition at line 229 of file cab.py.
         # read header
         cab.seek(0)
         header = CFHeader.read(cab)
         # verify magic number
         if header.signature != b"MSCF":
             raise Exception("invalid CAB file signature: " +
                             repr(header.signature))
         # read reserve header, if present
         if header.flags.reserve_present:
             header.reserved_data = CFHeaderReservedFields.read(cab)
         else:
             header.reserved_data = CFHeaderReservedFields.from_nullbytes()
         # read reserved
         header.reserved = read_guaranteed(cab, header.reserved_data.cbCFHeader)
         # read previous cabinet info
         if header.flags.prev_cabinet:
             header.prev_cab = try_decode(read_nullterminated_string(cab))
             header.prev_disk = try_decode(read_nullterminated_string(cab))
         # read next cabinet info
         if header.flags.next_cabinet:
             header.next_cab = try_decode(read_nullterminated_string(cab))
             header.next_disk = try_decode(read_nullterminated_string(cab))
         dbg(header)
         self.header = header
         self.folders = tuple(self.read_folder_headers(cab))
         # {filename: fileobj}, {subdirname: subdir}
         self.rootdir = OrderedDict(), OrderedDict()
         for fileobj in self.read_file_headers(cab):
             if self.is_file(fileobj.path) or self.is_dir(fileobj.path):
                 raise ValueError(
                     "CABFile has multiple entries with the same path: " +
                     b'/'.join(fileobj.path).decode())
             def open_r(fileobj=fileobj):
                 """ Returns a opened ('rb') file-like object for fileobj. """
                 return StreamFragment(
                     fileobj.folder.plain_stream,
                     fileobj.pos,
                     fileobj.size
                 )
             self.add_fileentry(fileobj.path, (
                 open_r,
                 None,
                 lambda fileobj=fileobj: fileobj.size,
                 lambda fileobj=fileobj: fileobj.timestamp
             ))
     def __repr__(self):
         return "CABFile"
References openage::log.dbg(), openage.util.files.read_guaranteed(), openage.util.files.read_nullterminated_string(), openage::util.repr(), and openage.util.strings.try_decode().
Member Function Documentation
__repr__()
def openage.cabextract.cab.CABFile.__repr__ (self)
Definition at line 289 of file cab.py.
     def read_folder_headers(self, cab):
         """
read_file_headers()
def openage.cabextract.cab.CABFile.read_file_headers (self, cab)
Called during the constructor run.
   Reads the headers for all files and yields CFFile objects.
Definition at line 356 of file cab.py.
         if cab.tell() != self.header.coffFiles:
             cab.seek(self.header.coffFiles)
             dbg("cabfile has nonstandard format: seek to header.coffFiles was required")
         for _ in range(self.header.cFiles):
             fileobj = CFFile.read(cab)
             # read filename
             rpath = read_nullterminated_string(cab)
             # decode filename according to flags
             if fileobj.attribs.name_is_utf:
                 path = rpath.decode('utf-8')
             else:
                 path = rpath.decode('iso-8859-1')
             fileobj.path = path.replace('\\', '/').lower().encode().split(b'/')
             # interpret the special values of folderid
             if fileobj.folderid == 0xFFFD:
                 fileobj.folderid = 0
                 fileobj.continued = True
             elif fileobj.folderid == 0xFFFE:
                 fileobj.folderid = len(self.folders) - 1
                 fileobj.continues = True
             elif fileobj.folderid == 0xFFFF:
                 fileobj.folderid = 0
                 fileobj.continued = True
                 fileobj.continues = True
             fileobj.folder = self.folders[fileobj.folderid]
             # decode file timestamp
             # beware: reading this may give you internal bleedings.
             year = (fileobj.date >> 9) + 1980
             month = (fileobj.date >> 5) & 0x000f
             day = (fileobj.date >> 0) & 0x001f
             # it's sort of sad that there's no bit for AM/PM.
             hour = (fileobj.time >> 11)
             minute = (fileobj.time >> 5) & 0x003f
             sec = (fileobj.time << 1) & 0x003f
             # CAB files have no timezone info; assume UTC.
             fileobj.timestamp = timegm((year, month, day, hour, minute, sec))
             yield fileobj
 class CABFolderStream(PosSavingReadOnlyFileLikeObject):
     """
     Read-only, seekable, file-like stream object that represents
     a compressed MSCAB folder (MSCAB folders are just compressed streams
     of concatenated file contents, and are not to be confused with file system
     folders).
     Constructor arguments:
     @param fileobj:
         Seekable file-like object that represents the CAB file.
         CABFolderStream explicitly positions the file cursor before every read;
         this is to make sure that multiple CABFolderStreams can work on the
         same file, in parallel.
         The file object must implement read() and seek() with SEEK_SET.
     @param offset:
         Offset of the first of the folder's data blocks in the CAB file.
     @param blockcount:
         Number of data blocks in the folder.
     """
References openage::log.dbg(), openage.cabextract.cab.CABFile.folders, openage.cabextract.cab.CABFile.header, openage.util.files.read_nullterminated_string(), and openage::util.split().
read_folder_headers()
def openage.cabextract.cab.CABFile.read_folder_headers (self, cab)
Called during the constructor run.
   Reads the folder headers and initializes the folder's plain stream
   file-like objects.
   Yields all folders.
Definition at line 300 of file cab.py.
         for _ in range(self.header.cFolders):
             folder = CFFolder.read(cab)
             # read reserved
             folder.reserved = read_guaranteed(
                 cab,
                 self.header.reserved_data.cbCFFolder)
             # create compressed data stream
             compressed_data_stream = CABFolderStream(
                 cab,
                 folder.coffCabStart,
                 folder.cCFData,
                 self.header.reserved_data.cbCFData)
             # determine compression type and create plain data stream
             compression_type = folder.typeCompress & 0x000f
             if compression_type == 0:
                 folder.comp_name = "Plain"
                 folder.plain_stream = compressed_data_stream
             elif compression_type == 1:
                 raise Exception("MSZIP compression is unsupported")
             elif compression_type == 2:
                 raise Exception("Quantum compression is unsupported")
             elif compression_type == 3:
                 window_bits = (folder.typeCompress >> 8) & 0x1f
                 folder.comp_name = "LZX (window_bits = %d)" % window_bits
                 from .lzxdstream import LZXDStream
                 from ..util.filelike.stream import StreamSeekBuffer
                 unseekable_plain_stream = LZXDStream(
                     compressed_data_stream,
                     window_bits=window_bits,
                     reset_interval=0)
                 folder.plain_stream = StreamSeekBuffer(unseekable_plain_stream)
             else:
                 raise Exception("Unknown compression type %d"
                                 % compression_type)
             dbg(folder)
             yield folder
     def read_file_headers(self, cab):
         """
References openage::log.dbg(), openage.cabextract.cab.CABFile.header, and openage.util.files.read_guaranteed().
Member Data Documentation
folders
openage.cabextract.cab.CABFile.folders
Definition at line 263 of file cab.py.
Referenced by openage.cabextract.cab.CABFile.read_file_headers().
header
openage.cabextract.cab.CABFile.header
Definition at line 261 of file cab.py.
Referenced by openage.cabextract.cab.CABFile.read_file_headers(), and openage.cabextract.cab.CABFile.read_folder_headers().
rootdir
openage.cabextract.cab.CABFile.rootdir
Definition at line 266 of file cab.py.
Referenced by openage.convert.peresource.PEResources.__getitem__(), and openage.convert.peresource.PEResources.read_strings().
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/openage/cabextract/cab.py