openage: openage::ActionMode Class Reference
openage::ActionMode Class Reference
#include <game_control.h>
Public Member Functions
ActionMode (qtsdl::GuiItemLink *gui_link)
bool available () const override
void on_enter () override
void on_exit () override
void render () override
std::string name () const override
void on_game_control_set () override
Public Member Functions inherited from openage::OutputMode
OutputMode (qtsdl::GuiItemLink *gui_link)
virtual ~OutputMode ()
virtual void set_game_control (GameControl *game_control)
Public Member Functions inherited from openage::input::InputContext
InputContext ()
InputContext (InputManager *manager)
virtual ~InputContext ()=default
std::vector< std::string > active_binds () const
void bind (action_t type, const action_func_t act)
void bind (const Event &ev, const action_func_t act)
void bind (event_class ec, const action_check_t act)
bool execute_if_bound (const action_arg_t &e)
void register_to (InputManager *manager)
void unregister ()
Public Attributes
ActionModeSignals gui_signals
Public Attributes inherited from openage::OutputMode
OutputModeSignals gui_signals
qtsdl::GuiItemLink * gui_link
Public Attributes inherited from openage::input::InputContext
bool utf8_mode
Private Member Functions
virtual void announce () override
void announce_resources ()
void announce_buttons_type ()
Command get_action (const coord::phys3 &pos) const
void create_binds ()
bool place_selection (coord::phys3 point)
Private Attributes
friend ActionModeSignals
InputContext build_menu_context
InputContext build_menu_mil_context
InputContext building_context
UnitSelection * selection
bool use_set_ability
ability_type ability
UnitType * type_focus
coord::phys3 mousepos_phys3 {0, 0, 0}
coord::tile mousepos_tile {0, 0}
bool selecting
ActionButtonsType buttons_type
rng::RNG rng
Additional Inherited Members
Protected Attributes inherited from openage::OutputMode
GameControl * game_control
Detailed Description
This is the main game UI.
Used to control units, issue commands, basically this is where you sink your time in when playing.
Definition at line 165 of file game_control.h.
Constructor & Destructor Documentation
ActionMode()
openage::ActionMode::ActionMode (qtsdl::GuiItemLink * gui_link)
Definition at line 91 of file game_control.cpp.
     :
     OutputMode{gui_link},
     selection{nullptr},
     use_set_ability{false},
     type_focus{nullptr},
     selecting{false},
     rng{rng::random_seed()},
     gui_signals{this} {}
References openage::OutputMode::gui_link.
Member Function Documentation
announce()
void openage::ActionMode::announce () override private virtual
sends to gui the properties that it needs
Reimplemented from openage::OutputMode.
Definition at line 478 of file game_control.cpp.
{
     this->OutputMode::announce();
     this->announce_resources();
     emit this->gui_signals.ability_changed(
         this->use_set_ability ? std::to_string(this->ability) : "");
 }
References ability, openage::ActionModeSignals::ability_changed(), openage::OutputMode::announce(), announce_resources(), gui_signals, std::to_string(), and use_set_ability.
Referenced by announce_buttons_type().
announce_buttons_type()
void openage::ActionMode::announce_buttons_type () private
sends to gui the buttons it should use for the action buttons (if changed)
Definition at line 503 of file game_control.cpp.
{
     ActionButtonsType buttons_type;
     Engine *engine = this->game_control->get_engine();
     InputContext *top_ctxt = &engine->get_input_manager().get_top_context();
     if (top_ctxt == &this->build_menu_context) {
         buttons_type = ActionButtonsType::BuildMenu;
     } else if (top_ctxt == &this->build_menu_mil_context) {
         buttons_type = ActionButtonsType::MilBuildMenu;
     } else if (top_ctxt == &this->building_context ||
                this->selection->get_selection_type() != selection_type_t::own_units) {
         buttons_type = ActionButtonsType::None;
     } else if (this->selection->contains_military(*this->game_control->get_current_player())) {
         buttons_type = ActionButtonsType::MilitaryUnits;
     } else {
         buttons_type = ActionButtonsType::CivilianUnits;
     }
     if (buttons_type != this->buttons_type) {
         this->buttons_type = buttons_type;
         emit this->gui_signals.buttons_type_changed(buttons_type);
         // announce the changed input context
         this->announce();
     }
 }
References announce(), build_menu_context, build_menu_mil_context, building_context, openage::BuildMenu, buttons_type, openage::ActionModeSignals::buttons_type_changed(), openage::CivilianUnits, openage::UnitSelection::contains_military(), openage::OutputMode::game_control, openage::GameControl::get_engine(), openage::Engine::get_input_manager(), openage::UnitSelection::get_selection_type(), openage::input::InputManager::get_top_context(), gui_signals, openage::input::InputContext::InputContext(), openage::MilBuildMenu, openage::MilitaryUnits, openage::None, openage::own_units, and selection.
Referenced by on_exit(), and on_game_control_set().
announce_resources()
void openage::ActionMode::announce_resources () private
sends to gui the amounts of resources
Definition at line 486 of file game_control.cpp.
{
     if (this->game_control) {
         if (Player *player = this->game_control->get_current_player()) {
             for (auto i = static_cast<std::underlying_type<game_resource>::type>(game_resource::RESOURCE_TYPE_COUNT); i != 0; --i) {
                 auto resource_type = static_cast<game_resource>(i - 1);
                 emit this->gui_signals.resource_changed(
                     resource_type,
                     static_cast<int>(player->amount(resource_type))
                 );
             }
             emit this->gui_signals.population_changed(player->population.get_demand(), player->population.get_capacity(),
                 player->population.get_space() <= 0 && !player->population.is_capacity_maxed());
         }
     }
 }
References openage::OutputMode::game_control, openage::GameControl::get_current_player(), gui_signals, openage::ActionModeSignals::population_changed(), openage::ActionModeSignals::resource_changed(), and openage::RESOURCE_TYPE_COUNT.
Referenced by announce(), and render().
available()
bool openage::ActionMode::available () const override virtual
Is this mode able to be used?
Implements openage::OutputMode.
Definition at line 355 of file game_control.cpp.
{
     if (this->game_control == nullptr) {
         log::log(MSG(warn) << "ActionMode::available() queried without "
                               "game control being attached.");
         return false;
     }
     Engine *engine = this->game_control->get_engine();
     if (engine->get_game() != nullptr) {
         return true;
     }
     else {
         log::log(MSG(warn) << "Cannot enter action mode without a game");
         return false;
     }
 }
References openage::OutputMode::game_control, openage::GameControl::get_engine(), openage::Engine::get_game(), openage::log::log(), MSG, and openage::log::warn().
create_binds()
void openage::ActionMode::create_binds () private
Register the keybindings.
get_action()
Command openage::ActionMode::get_action (const coord::phys3 & pos) const private
decides which type of right mouse click command to issue based on position.
if a unit is at the position the command should target the unit, otherwise target ground position
Definition at line 390 of file game_control.cpp.
{
     Engine *engine = this->game_control->get_engine();
     GameMain *game = engine->get_game();
     auto obj = game->terrain->obj_at_point(pos);
     if (obj) {
         Command c(*this->game_control->get_current_player(), &obj->unit, pos);
         if (this->use_set_ability) {
             c.set_ability(ability);
         }
         return c;
     }
     else {
         Command c(*this->game_control->get_current_player(), pos);
         if (this->use_set_ability) {
             c.set_ability(ability);
         }
         return c;
     }
 }
References ability, openage::OutputMode::game_control, openage::GameControl::get_current_player(), openage::GameControl::get_engine(), openage::Engine::get_game(), openage::Command::set_ability(), openage::GameMain::terrain, and use_set_ability.
Referenced by on_game_control_set().
name()
std::string openage::ActionMode::name () const override virtual
Used for displaying the current mode.
Implements openage::OutputMode.
Definition at line 474 of file game_control.cpp.
{
     return "Action Mode";
 }
Referenced by openage.util.fslike.path.Path::stem(), openage.util.fslike.path.Path::suffix(), and openage.util.fslike.path.Path::suffixes().
on_enter()
void openage::ActionMode::on_enter () override virtual
Called when switching to this mode.
Implements openage::OutputMode.
Definition at line 372 of file game_control.cpp.
 {}
on_exit()
void openage::ActionMode::on_exit () override virtual
Called when the mode is left.
Implements openage::OutputMode.
Definition at line 374 of file game_control.cpp.
{
     // Since on_exit is called after removing the active mode, if the top context isn't the global one then it must
     // be either a build menu or the building context
     Engine *engine = this->game_control->get_engine();
     auto *input_manager = &engine->get_input_manager();
     InputContext *top_ctxt = &input_manager->get_top_context();
     if (top_ctxt != &input_manager->get_global_context()) {
         if (top_ctxt == &this->building_context) {
             this->type_focus = nullptr;
         }
         input_manager->remove_context(top_ctxt);
         this->announce_buttons_type();
     }
     this->selecting = false;
 }
References announce_buttons_type(), building_context, openage::OutputMode::game_control, openage::GameControl::get_engine(), openage::input::InputManager::get_global_context(), openage::Engine::get_input_manager(), openage::input::InputManager::get_top_context(), openage::input::InputContext::input_manager, openage::input::InputContext::InputContext(), openage::input::InputManager::remove_context(), selecting, and type_focus.
on_game_control_set()
void openage::ActionMode::on_game_control_set () override virtual
Called after GameControl has been set by QML from set_game_control.
Implements openage::OutputMode.
Definition at line 102 of file game_control.cpp.
{
     ENSURE(this->game_control != nullptr, "no control was actually set");
     Engine *engine = this->game_control->get_engine();
     ENSURE(engine != nullptr, "engine must be known!");
     auto &action = engine->get_action_manager();
     auto input = &engine->get_input_manager();
     coord::CoordManager &coord = engine->coord;
     // \\todo the selection should not be used in here!
     this->selection = engine->get_unit_selection();
     ENSURE(this->selection != nullptr, "selection must be fetched!");
     this->bind(action.get("TRAIN_OBJECT"),
                [this](const input::action_arg_t &) {
         // attempt to train editor selected object
         // randomly select between male and female villagers
         auto player = this->game_control->get_current_player();
         auto type = player->get_type(this->rng.probability(0.5)? 83 : 293);
         Command cmd(*player, type);
         cmd.add_flag(command_flag::interrupt);
         this->selection->all_invoke(cmd);
     });
     this->bind(action.get("ENABLE_BUILDING_PLACEMENT"),
                [](const input::action_arg_t &) {
         // this->building_placement = true;
     });
     this->bind(action.get("DISABLE_SET_ABILITY"),
                [this](const input::action_arg_t &) {
         this->use_set_ability = false;
     });
     this->bind(action.get("SET_ABILITY_MOVE"),
                [this](const input::action_arg_t &) {
         this->use_set_ability = true;
         this->ability = ability_type::move;
         emit this->gui_signals.ability_changed(std::to_string(this->ability));
     });
     this->bind(action.get("SET_ABILITY_GATHER"),
                [this](const input::action_arg_t &) {
         this->use_set_ability = true;
         this->ability = ability_type::gather;
         emit this->gui_signals.ability_changed(std::to_string(this->ability));
     });
     this->bind(action.get("SET_ABILITY_GARRISON"),
                [this](const input::action_arg_t &) {
         this->use_set_ability = true;
         this->ability = ability_type::garrison;
         emit this->gui_signals.ability_changed(std::to_string(this->ability));
     });
     this->bind(action.get("SET_ABILITY_REPAIR"), [this](const input::action_arg_t &) {
         this->use_set_ability = true;
         this->ability = ability_type::repair;
         emit this->gui_signals.ability_changed(std::to_string(this->ability));
     });
     this->bind(action.get("SPAWN_VILLAGER"),
                [this, engine](const input::action_arg_t &) {
         auto player = this->game_control->get_current_player();
         if (player->type_count() > 0) {
             UnitType &type = *player->get_type(590);
             // \\todo tile position
             engine->get_game()->placed_units.new_unit(type, *player, this->mousepos_phys3);
         }
     });
     this->bind(action.get("KILL_UNIT"),
                [this](const input::action_arg_t &) {
         this->selection->kill_unit(*this->game_control->get_current_player());
     });
     this->bind(action.get("BUILD_MENU"),
                [this, input](const input::action_arg_t &) {
         log::log(MSG(dbg) << "Opening build menu");
         input->push_context(&this->build_menu_context);
         this->announce_buttons_type();
     });
     this->bind(action.get("BUILD_MENU_MIL"),
                [this, input](const input::action_arg_t &) {
         log::log(MSG(dbg) << "Opening military build menu");
         input->push_context(&this->build_menu_mil_context);
         this->announce_buttons_type();
     });
     this->build_menu_context.bind(action.get("CANCEL"),
                                   [this, input](const input::action_arg_t &) {
         input->remove_context(&this->build_menu_context);
         this->announce_buttons_type();
     });
     this->build_menu_mil_context.bind(action.get("CANCEL"),
                                       [this, input](const input::action_arg_t &) {
         input->remove_context(&this->build_menu_mil_context);
         this->announce_buttons_type();
     });
     // Villager build commands
     auto bind_building_key = [this, input](input::action_t action, int building, input::InputContext *ctxt) {
         ctxt->bind(action, [this, building, ctxt, input](const input::action_arg_t &) {
             auto player = this->game_control->get_current_player();
             if (this->selection->contains_builders(*player)) {
                 auto player = this->game_control->get_current_player();
                 this->type_focus = player->get_type(building);
                 if (player->can_make(*this->type_focus)) {
                     if (&input->get_top_context() != &this->building_context) {
                         input->remove_context(ctxt);
                         input->push_context(&this->building_context);
                         this->announce_buttons_type();
                     }
                 } else {
                     // \\todo show in game error message
                 }
             }
         });
     };
     bind_building_key(action.get("BUILDING_HOUS"),  70,  &this->build_menu_context); // House
     bind_building_key(action.get("BUILDING_MILL"),  68,  &this->build_menu_context); // Mill
     bind_building_key(action.get("BUILDING_MINE"),  584, &this->build_menu_context); // Mining Camp
     bind_building_key(action.get("BUILDING_SMIL"),  562, &this->build_menu_context); // Lumber Camp
     bind_building_key(action.get("BUILDING_DOCK"),  47,  &this->build_menu_context); // Dock
     // \\todo Doesn't show until it is placed
     bind_building_key(action.get("BUILDING_FARM"),  50,  &this->build_menu_context); // Farm
     bind_building_key(action.get("BUILDING_BLAC"),  103, &this->build_menu_context); // Blacksmith
     bind_building_key(action.get("BUILDING_MRKT"),  84,  &this->build_menu_context); // Market
     bind_building_key(action.get("BUILDING_CRCH"),  104, &this->build_menu_context); // Monastery
     bind_building_key(action.get("BUILDING_UNIV"),  209, &this->build_menu_context); // University
     bind_building_key(action.get("BUILDING_RTWC"),  109, &this->build_menu_context); // Town Center
     bind_building_key(action.get("BUILDING_WNDR"),  276, &this->build_menu_context); // Wonder
     bind_building_key(action.get("BUILDING_BRKS"),  12,  &this->build_menu_mil_context); // Barracks
     bind_building_key(action.get("BUILDING_ARRG"),  87,  &this->build_menu_mil_context); // Archery Range
     bind_building_key(action.get("BUILDING_STBL"),  101, &this->build_menu_mil_context); // Stable
     bind_building_key(action.get("BUILDING_SIWS"),  49,  &this->build_menu_mil_context); // Siege Workshop
     bind_building_key(action.get("BUILDING_WCTWX"), 598, &this->build_menu_mil_context); // Outpost
     // \\todo for palisade and stone wall: Drag walls, automatically adjust orientation
     // \\todo This just cycles through all palisade textures
     bind_building_key(action.get("BUILDING_WALL"),  72,  &this->build_menu_mil_context); // Palisade Wall
     // \\todo Fortified wall has a different ID
     bind_building_key(action.get("BUILDING_WALL2"), 117, &this->build_menu_mil_context); // Stone Wall
     // \\todo Upgraded versions have different IDs
     bind_building_key(action.get("BUILDING_WCTW"),  79,  &this->build_menu_mil_context); // Watch Tower
     bind_building_key(action.get("BUILDING_WCTW4"), 236, &this->build_menu_mil_context); // Bombard Tower
     // \\todo Gate placement - 659 is horizontal closed
     bind_building_key(action.get("BUILDING_GTCA2"), 659, &this->build_menu_mil_context); // Gate
     bind_building_key(action.get("BUILDING_CSTL"),  82,  &this->build_menu_mil_context); // Castle
     this->building_context.bind(action.get("CANCEL"),
                                 [this, input](const input::action_arg_t &) {
         input->remove_context(&this->building_context);
         this->announce_buttons_type();
         this->type_focus = nullptr;
     });
     auto bind_build = [this, input, &coord](input::action_t action, const bool increase) {
         this->building_context.bind(action, [this, increase, input, &coord](const input::action_arg_t &arg) {
             this->mousepos_phys3 = arg.mouse.to_phys3(coord, 0);
             this->mousepos_tile = this->mousepos_phys3.to_tile();
             bool placed = this->place_selection(this->mousepos_phys3);
             if (placed && !increase) {
                 this->type_focus = nullptr;
                 input->remove_context(&this->building_context);
                 this->announce_buttons_type();
             }
         });
     };
     bind_build(action.get("BUILD"), false);
     bind_build(action.get("KEEP_BUILDING"), true);
     auto bind_select = [this, input, engine](input::action_t action, const bool increase) {
         this->bind(action, [this, increase, input, engine](const input::action_arg_t &arg) {
             auto mousepos_camgame = arg.mouse.to_camgame(engine->coord);
             Terrain *terrain = engine->get_game()->terrain.get();
             this->selection->drag_update(mousepos_camgame);
             this->selection->drag_release(*this->game_control->get_current_player(), terrain, increase);
             InputContext *top_ctxt = &input->get_top_context();
             if ((this->selection->get_selection_type() != selection_type_t::own_units or
                  this->selection->contains_military(*this->game_control->get_current_player()))
                 and
                 (top_ctxt == &this->build_menu_context ||
                  top_ctxt == &this->build_menu_mil_context)) {
                 input->remove_context(top_ctxt);
             }
             this->announce_buttons_type();
         });
     };
     bind_select(action.get("SELECT"), false);
     bind_select(action.get("INCREASE_SELECTION"), true);
     this->bind(action.get("ORDER_SELECT"), [this, input, &coord](const input::action_arg_t &arg) {
         if (this->type_focus) {
             // right click can cancel building placement
             this->type_focus = nullptr;
             input->remove_context(&this->building_context);
             this->announce_buttons_type();
         }
         auto cmd = this->get_action(arg.mouse.to_phys3(coord));
         cmd.add_flag(command_flag::interrupt);
         this->selection->all_invoke(cmd);
         this->use_set_ability = false;
     });
     this->bind(action.get("BEGIN_SELECTION"), [this](const input::action_arg_t&) {
         this->selecting = true;
     });
     this->bind(action.get("END_SELECTION"), [this](const input::action_arg_t&) {
         this->selecting = false;
     });
     this->bind(input::event_class::MOUSE, [this, &coord](const input::action_arg_t &arg) {
         auto mousepos_camgame = arg.mouse.to_camgame(coord);
         this->mousepos_phys3 = mousepos_camgame.to_phys3(coord);
         this->mousepos_tile = this->mousepos_phys3.to_tile();
         // drag selection box
         if (arg.e.cc == input::ClassCode(input::event_class::MOUSE_MOTION, 0) &&
             this->selecting && !this->type_focus) {
             this->selection->drag_update(mousepos_camgame);
             return true;
         }
         return false;
     });
 }
References ability, openage::ActionModeSignals::ability_changed(), openage::Command::add_flag(), openage::UnitSelection::all_invoke(), announce_buttons_type(), openage::input::InputContext::bind(), build_menu_context, build_menu_mil_context, openage::building, building_context, openage::input::Event::cc, openage::UnitSelection::contains_builders(), openage::UnitSelection::contains_military(), openage::coord::tests::coord(), openage::Engine::coord, openage::log::dbg(), openage::UnitSelection::drag_release(), openage::UnitSelection::drag_update(), openage::input::action_arg_t::e, ENSURE, openage::OutputMode::game_control, openage::garrison, openage::gather, get_action(), openage::Engine::get_action_manager(), openage::GameControl::get_current_player(), openage::GameControl::get_engine(), openage::Engine::get_game(), openage::Engine::get_input_manager(), openage::UnitSelection::get_selection_type(), openage::Player::get_type(), openage::Engine::get_unit_selection(), gui_signals, openage::input::InputContext::InputContext(), openage::interrupt, openage::UnitSelection::kill_unit(), openage::log::log(), openage::input::MOUSE, openage::input::action_arg_t::mouse, openage::input::MOUSE_MOTION, mousepos_phys3, mousepos_tile, openage::move, MSG, openage::UnitContainer::new_unit(), openage::own_units, place_selection(), openage::placed, openage::GameMain::placed_units, openage::rng::RNG::probability(), openage::repair, rng, selecting, selection, openage::GameMain::terrain, openage::coord::input::to_camgame(), openage::coord::input::to_phys3(), std::to_string(), openage::coord::phys3::to_tile(), type_focus, and use_set_ability.
place_selection()
bool openage::ActionMode::place_selection (coord::phys3 point) private
places hovering building
Definition at line 411 of file game_control.cpp.
{
     if (this->type_focus) {
         auto player = this->game_control->get_current_player();
         if (player->can_make(*this->type_focus)) {
             // confirm building placement with left click
             // first create foundation using the producer
             Engine *engine = this->game_control->get_engine();
             UnitContainer *container = &engine->get_game()->placed_units;
             UnitReference new_building = container->new_unit(*this->type_focus, *player, point);
             // task all selected villagers to build
             // \todo editor placed objects are completed already
             if (new_building.is_valid()) {
                 player->deduct(this->type_focus->cost.get(*player)); // \todo change, move elsewheres
                 Command cmd(*player, new_building.get());
                 cmd.set_ability(ability_type::build);
                 cmd.add_flag(command_flag::interrupt);
                 this->selection->all_invoke(cmd);
                 return true;
             }
         } else {
             // \todo show in game error message
             return false;
         }
     }
     return false;
 }
References openage::UnitSelection::all_invoke(), openage::build, openage::curve::tests::container(), openage::UnitType::cost, openage::OutputMode::game_control, openage::ResourceCost::get(), openage::UnitReference::get(), openage::GameControl::get_current_player(), openage::GameControl::get_engine(), openage::Engine::get_game(), openage::interrupt, openage::UnitReference::is_valid(), openage::GameMain::placed_units, selection, openage::Command::set_ability(), and type_focus.
Referenced by on_game_control_set().
render()
void openage::ActionMode::render () override virtual
Display this mode.
Implements openage::OutputMode.
Definition at line 445 of file game_control.cpp.
{
     ENSURE(this->game_control != nullptr, "game_control is unset");
     Engine *engine = this->game_control->get_engine();
     ENSURE(engine != nullptr, "engine is needed to render ActionMode");
     if (GameMain *game = engine->get_game()) {
         Player *player = this->game_control->get_current_player();
         this->announce_resources();
         // when a building is being placed
         if (this->type_focus) {
             auto txt = this->type_focus->default_texture();
             auto size = this->type_focus->foundation_size;
             tile_range center = building_center(this->mousepos_phys3, size, *game->terrain);
             txt->sample(engine->coord, center.draw.to_camhud(engine->coord), player->color);
         }
     }
     else {
         engine->render_text({0, 140}, 12, "Action Mode requires a game");
     }
     ENSURE(this->selection != nullptr, "selection not set");
     this->selection->on_drawhud();
 }
References announce_resources(), openage::building_center(), openage::Player::color, openage::Engine::coord, openage::UnitType::default_texture(), openage::tile_range::draw, ENSURE, openage::UnitType::foundation_size, openage::OutputMode::game_control, openage::GameControl::get_current_player(), openage::GameControl::get_engine(), openage::Engine::get_game(), mousepos_phys3, openage::UnitSelection::on_drawhud(), openage::Engine::render_text(), selection, openage::coord::phys3::to_camhud(), and type_focus.
Member Data Documentation
ability
ability_type openage::ActionMode::ability private
Definition at line 233 of file game_control.h.
Referenced by announce(), get_action(), and on_game_control_set().
ActionModeSignals
friend openage::ActionMode::ActionModeSignals private
Definition at line 177 of file game_control.h.
build_menu_context
InputContext openage::ActionMode::build_menu_context private
used after opening the build menu
Definition at line 211 of file game_control.h.
Referenced by announce_buttons_type(), and on_game_control_set().
build_menu_mil_context
InputContext openage::ActionMode::build_menu_mil_context private
used after opening the military build menu
Definition at line 216 of file game_control.h.
Referenced by announce_buttons_type(), and on_game_control_set().
building_context
InputContext openage::ActionMode::building_context private
used when selecting the building placement
Definition at line 221 of file game_control.h.
Referenced by announce_buttons_type(), openage::ActionModeSignals::on_action(), on_exit(), and on_game_control_set().
buttons_type
ActionButtonsType openage::ActionMode::buttons_type private
Definition at line 247 of file game_control.h.
Referenced by announce_buttons_type().
gui_signals
ActionModeSignals openage::ActionMode::gui_signals
Definition at line 253 of file game_control.h.
Referenced by announce(), announce_buttons_type(), announce_resources(), and on_game_control_set().
mousepos_phys3
coord::phys3 openage::ActionMode::mousepos_phys3 {0, 0, 0} private
Todo:
these shouldn't be here. remove them ASAP. they are used to carry over mouse information into some of the game control lambda functions
Definition at line 243 of file game_control.h.
Referenced by on_game_control_set(), and render().
mousepos_tile
coord::tile openage::ActionMode::mousepos_tile {0, 0} private
Definition at line 244 of file game_control.h.
Referenced by on_game_control_set().
rng
rng::RNG openage::ActionMode::rng private
Definition at line 250 of file game_control.h.
Referenced by on_game_control_set().
selecting
bool openage::ActionMode::selecting private
Definition at line 245 of file game_control.h.
Referenced by on_exit(), and on_game_control_set().
selection
UnitSelection* openage::ActionMode::selection private
Definition at line 229 of file game_control.h.
Referenced by announce_buttons_type(), on_game_control_set(), place_selection(), and render().
type_focus
UnitType* openage::ActionMode::type_focus private
Definition at line 236 of file game_control.h.
Referenced by on_exit(), on_game_control_set(), place_selection(), and render().
use_set_ability
bool openage::ActionMode::use_set_ability private
Definition at line 232 of file game_control.h.
Referenced by announce(), get_action(), and on_game_control_set().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/game_control.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/game_control.cpp