openage: openage::shader::Program Class Reference
openage::shader::Program Class Reference
#include <program.h>
Public Member Functions
Program ()
Program (Shader *s0, Shader *s1)
~Program ()
void attach_shader (Shader *s)
void link ()
void use ()
void stopusing ()
GLint get_uniform_id (const char *name)
GLint get_attribute_id (const char *name)
void set_attribute_id (const char *name, GLuint id)
void dump_active_attributes ()
Public Attributes
GLuint id
GLint pos_id
GLint mvpm_id
Private Member Functions
void check (GLenum what_to_check)
GLint get_info (GLenum pname)
char * get_log ()
void post_link_hook ()
Private Attributes
bool is_linked
Shader * vert
Shader * frag
Shader * geom
Detailed Description
Definition at line 12 of file program.h.
Constructor & Destructor Documentation
Program() [1/2]
openage::shader::Program::Program ()
Definition at line 20 of file program.cpp.
                  : is_linked(false), vert(nullptr), frag(nullptr), geom(nullptr) {
     this->id = glCreateProgram();
 }
Program() [2/2]
openage::shader::Program::Program (Shader * s0, Shader * s1)
Definition at line 24 of file program.cpp.
                                        : Program{} {
     this->attach_shader(s0);
     this->attach_shader(s1);
 }
~Program()
openage::shader::Program::~Program ()
Definition at line 29 of file program.cpp.
                   {
     glDeleteProgram(this->id);
 }
Member Function Documentation
attach_shader()
void openage::shader::Program::attach_shader (Shader * s)
Definition at line 33 of file program.cpp.
{
     switch (s->type) {
     case GL_VERTEX_SHADER:
         this->vert = s;
         break;
     case GL_FRAGMENT_SHADER:
         this->frag = s;
         break;
     case GL_GEOMETRY_SHADER:
         this->geom = s;
         break;
     }
     glAttachShader(this->id, s->id);
 }
References frag, geom, openage::shader::Shader::id, openage::shader::Shader::type, and vert.
check()
void openage::shader::Program::check (GLenum what_to_check) private
checks a given status for this program.
Parameters
what_to_check GL_LINK_STATUS GL_VALIDATE_STATUS GL_COMPILE_STATUS
Definition at line 72 of file program.cpp.
{
     GLint status;
     glGetProgramiv(this->id, what_to_check, &status);
     if (status != GL_TRUE) {
         GLint loglen;
         glGetProgramiv(this->id, GL_INFO_LOG_LENGTH, &loglen);
         char *infolog = new char[loglen];
         glGetProgramInfoLog(this->id, loglen, NULL, infolog);
         const char *what_str;
         switch(what_to_check) {
         case GL_LINK_STATUS:
             what_str = "linking";
             break;
         case GL_VALIDATE_STATUS:
             what_str = "validation";
             break;
         case GL_COMPILE_STATUS:
             what_str = "compiliation";
             break;
         default:
             what_str = "<unknown task>";
             break;
         }
         auto errormsg = MSG(err);
         errormsg << "Program " << what_str << " failed\n" << infolog;
         delete[] infolog;
         throw Error(errormsg);
     }
 }
References openage::log::err(), and MSG.
Referenced by link().
dump_active_attributes()
void openage::shader::Program::dump_active_attributes ()
Definition at line 147 of file program.cpp.
{
     auto msg = MSG(warn);
     msg << "Dumping shader program active attribute list:";
     GLint num_attribs;
     glGetProgramiv(this->id, GL_ACTIVE_ATTRIBUTES, &num_attribs);
     GLint attrib_max_length;
     glGetProgramiv(this->id, GL_ACTIVE_ATTRIBUTE_MAX_LENGTH, &attrib_max_length);
     for (int i = 0; i < num_attribs; i++) {
         GLsizei attrib_length;
         GLint attrib_size;
         GLenum attrib_type;
         char *attrib_name = new char[attrib_max_length];
         glGetActiveAttrib(this->id, i, attrib_max_length, &attrib_length, &attrib_size, &attrib_type, attrib_name);
         msg << "\n" <<
             "-> attribute " << attrib_name << ": "
             " : type=" << attrib_type << ", size=" << attrib_size;
         delete[] attrib_name;
     }
 }
References MSG, and openage::log::warn().
Referenced by get_attribute_id().
get_attribute_id()
GLint openage::shader::Program::get_attribute_id (const char * name)
Definition at line 118 of file program.cpp.
{
     if (unlikely(!this->is_linked)) {
         throw Error(MSG(err) <<
             "Attribute " << name <<
             " was queried before program was linked!");
     }
     GLint aid = glGetAttribLocation(this->id, name);
     if (unlikely(aid == -1)) {
         this->dump_active_attributes();
         throw Error(MSG(err) <<
             "Attribute " << name << " queried but not found or active"
             " (pwnt by the compiler).");
     }
     return aid;
 }
References dump_active_attributes(), openage::log::err(), is_linked, MSG, and unlikely.
Referenced by post_link_hook().
get_info()
GLint openage::shader::Program::get_info (GLenum pname) private
get_log()
char* openage::shader::Program::get_log () private
get_uniform_id()
GLint openage::shader::Program::get_uniform_id (const char * name)
Definition at line 114 of file program.cpp.
{
     return glGetUniformLocation(this->id, name);
 }
Referenced by post_link_hook().
link()
void openage::shader::Program::link ()
Definition at line 48 of file program.cpp.
                    {
     glLinkProgram(this->id);
     this->check(GL_LINK_STATUS);
     glValidateProgram(this->id);
     this->check(GL_VALIDATE_STATUS);
     this->is_linked = true;
     this->post_link_hook();
     if (this->vert != nullptr) {
         glDetachShader(this->id, this->vert->id);
     }
     if (this->frag != nullptr) {
         glDetachShader(this->id, this->frag->id);
     }
     if (this->geom != nullptr) {
         glDetachShader(this->id, this->geom->id);
     }
 }
References check(), frag, geom, openage::shader::Shader::id, is_linked, post_link_hook(), and vert.
post_link_hook()
void openage::shader::Program::post_link_hook () private
Definition at line 172 of file program.cpp.
{
     this->pos_id  = this->get_attribute_id("vertex_position");
     this->mvpm_id = this->get_uniform_id("mvp_matrix");
 }
References get_attribute_id(), get_uniform_id(), mvpm_id, and pos_id.
Referenced by link().
set_attribute_id()
void openage::shader::Program::set_attribute_id (const char * name, GLuint id)
Definition at line 137 of file program.cpp.
{
     if (!this->is_linked) {
         glBindAttribLocation(this->id, id, name);
     }
     else {
         //TODO: maybe enable overwriting, but after that relink the program
         throw Error(MSG(err) << "assigned attribute " << name << " = " << id << " after program was linked!");
     }
 }
References openage::log::err(), is_linked, and MSG.
stopusing()
void openage::shader::Program::stopusing ()
Definition at line 110 of file program.cpp.
{
     glUseProgram(static_cast<GLuint>(0));
 }
Referenced by openage::Texture::draw(), and openage::renderer::TextRenderer::render().
use()
void openage::shader::Program::use ()
Definition at line 106 of file program.cpp.
                   {
     glUseProgram(this->id);
 }
Referenced by openage::Texture::draw(), and openage::renderer::TextRenderer::render().
Member Data Documentation
frag
Shader * openage::shader::Program::frag private
Definition at line 37 of file program.h.
Referenced by attach_shader(), and link().
geom
Shader * openage::shader::Program::geom private
Definition at line 37 of file program.h.
Referenced by attach_shader(), and link().
id
GLuint openage::shader::Program::id
Definition at line 14 of file program.h.
is_linked
bool openage::shader::Program::is_linked private
Definition at line 36 of file program.h.
Referenced by get_attribute_id(), link(), and set_attribute_id().
mvpm_id
GLint openage::shader::Program::mvpm_id
Definition at line 15 of file program.h.
Referenced by post_link_hook().
pos_id
GLint openage::shader::Program::pos_id
Definition at line 15 of file program.h.
Referenced by openage::Texture::draw(), and post_link_hook().
vert
Shader* openage::shader::Program::vert private
Definition at line 37 of file program.h.
Referenced by attach_shader(), and link().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/shader/program.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/shader/program.cpp