openage: openage::error::Error Class Reference
openage::error::Error Class Reference
Openage base exception type; the constructor usage is analogous to log::log().
#include <error.h>
Public Member Functions
Error (const log::message &msg, bool generate_backtrace=true, bool store_cause=true)
void store_cause ()
Stores a pointer to the currently-handled exception in this->cause.
void trim_backtrace ()
Calls this->backtrace->trim_to_current_stack_frame(), if this->backtrace is not nullptr.
void rethrow_cause () const
Re-throws the exception cause, if the exception has one.
virtual std::string type_name () const
The type name of the exception (for pretty-printing in case the exception hierarchy is used).
const char * what () const noexcept override
Returns the message's content.
Static Public Member Functions
static void debug_break_on_create (bool state)
Turn on debug breaks in the constructor.
Public Attributes
log::message msg
The error message.
std::shared_ptr< Backtrace > backtrace
The (optional) backtrace.
Private Member Functions
Error ()
Constructs an empty error.
Private Attributes
std::exception_ptr cause
Re-throw this with rethrow_cause().
Detailed Description
Openage base exception type; the constructor usage is analogous to log::log().
pxd:
cppclass Error: message msg
string type_name() except + const char *what() except + void rethrow_cause() except + void trim_backtrace() except + @staticmethod void debug_break_on_create(bool state) except +
Backtrace *backtrace
Definition at line 51 of file error.h.
Constructor & Destructor Documentation
Error() [1/2]
openage::error::Error::Error (const log::message & msg, bool generate_backtrace = true, bool store_cause = true)
Parameters
msg As with log::log()
generate_backtrace If true, some platform-specific code is run to collect traceback information (e.g.: backtrace (3)) (default true). The performance impacts should be not too bad, as only program counter pointers are collected.
store_cause If true, a pointer to the causing exception is collected and stored (default true).
Definition at line 20 of file error.cpp.
     :
     std::runtime_error{runtime_error_message},
     msg(msg) {
     if (unlikely(enable_break_on_create)) {
         BREAKPOINT;
     }
     if (generate_backtrace) {
         auto backtrace = std::make_shared<StackAnalyzer>();
         backtrace->analyze();
         this->backtrace = backtrace;
     }
     if (store_cause) {
         this->store_cause();
     }
 }
References openage::error::runtime_error_message.
Error() [2/2]
openage::error::Error::Error () private
Constructs an empty error.
For use by our friend, pyinterface::PyException.
Definition at line 67 of file error.cpp.
     :
     std::runtime_error{runtime_error_message} {}
References openage::error::runtime_error_message.
Member Function Documentation
debug_break_on_create()
void openage::error::Error::debug_break_on_create (bool state) static
Turn on debug breaks in the constructor.
Definition at line 16 of file error.cpp.
{
     enable_break_on_create = state;
 }
References openage::error::enable_break_on_create.
rethrow_cause()
void openage::error::Error::rethrow_cause () const
Re-throws the exception cause, if the exception has one.
Otherwise, does nothing.
Use this when handling the exception, to handle the cause.
Definition at line 82 of file error.cpp.
{
     if (this->cause) {
         std::rethrow_exception(this->cause);
     }
 }
References cause.
Referenced by openage::pyinterface::tests::err_py_to_cpp(), and openage::error::operator<<().
store_cause()
void openage::error::Error::store_cause ()
Stores a pointer to the currently-handled exception in this->cause.
Definition at line 41 of file error.cpp.
{
     // we could simply do this->cause = std::current_exception(),
     // but we need to trim the cause Error's backtrace.
     if (likely(!std::current_exception())) {
         return;
     }
     try {
         throw;
     } catch (Error &cause) {
         cause.trim_backtrace();
         this->cause = std::current_exception();
     } catch (...) {
         this->cause = std::current_exception();
     }
 }
References cause, and likely.
Referenced by openage::pyinterface::translate_exc_py_to_cpp().
trim_backtrace()
void openage::error::Error::trim_backtrace ()
Calls this->backtrace->trim_to_current_stack_frame(), if this->backtrace is not nullptr.
Designed to be used in catch clauses, to strip away all those unneeded symbols from program init upwards.
Automatically called for cause exceptions, and when storing cause exceptions, and by the to_py converter.
Definition at line 60 of file error.cpp.
{
     if (this->backtrace) {
         this->backtrace->trim_to_current_stack_frame();
     }
 }
References backtrace.
Referenced by openage::error::demo().
type_name()
std::string openage::error::Error::type_name () const virtual
The type name of the exception (for pretty-printing in case the exception hierarchy is used).
Uses typeid internally.
Reimplemented in openage::pyinterface::PyException.
Definition at line 77 of file error.cpp.
{
     return util::demangle(typeid(*this).name());
 }
References openage::util::demangle().
Referenced by openage::error::operator<<().
what()
const char * openage::error::Error::what () const override noexcept
Returns the message's content.
Definition at line 72 of file error.cpp.
{
     return this->msg.text.c_str();
 }
References msg, and openage::log::message::text.
Referenced by openage::pyinterface::tests::err_py_to_cpp().
Member Data Documentation
backtrace
std::shared_ptr<Backtrace> openage::error::Error::backtrace
The (optional) backtrace.
Definition at line 97 of file error.h.
Referenced by openage::error::demo(), openage::pyinterface::PyException::init_backtrace(), openage::error::operator<<(), and trim_backtrace().
cause
std::exception_ptr openage::error::Error::cause private
Re-throw this with rethrow_cause().
Definition at line 141 of file error.h.
Referenced by rethrow_cause(), and store_cause().
msg
log::message openage::error::Error::msg
The error message.
Definition at line 91 of file error.h.
Referenced by openage::error::operator<<(), and what().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/error/error.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/error/error.cpp