openage: openage::BuildingProducer Class Reference
openage::BuildingProducer Class Reference
Stores graphics and attributes for a building type Will be replaced with nyan system in future in aoe buildings are derived from living units.
#include <producer.h>
Public Member Functions
BuildingProducer (const Player &owner, const GameSpec &spec, const gamedata::building_unit *ud)
virtual ~BuildingProducer ()
int id () const override
gets the unique id of this unit type
int parent_id () const override
gets the parent id of this unit type which is used for village base and gather types
std::string name () const override
gets the name of the unit type being produced
void initialise (Unit *, Player &) override
Initialize units attributes to this type spec.
TerrainObject * place (Unit *, std::shared_ptr< Terrain >, coord::phys3) const override
set unit in place – return if placement was successful
Public Member Functions inherited from openage::UnitType
UnitType ()
bool match (class Unit *)
the unit must have either same class or id as this
UnitType (const Player &owner)
virtual ~UnitType ()
virtual void reinitialise (Unit *, Player &)
Initialize units shared attributes only to this type spec.
bool operator== (const UnitType &other) const
compare if two types are the same
bool operator!= (const UnitType &other) const
UnitTexture * default_texture ()
Get a default texture for HUD drawing.
TerrainObject * place_beside (Unit *, TerrainObject const *) const
similar to place but places adjacent to an existing object
void copy_attributes (Unit *unit) const
copy attributes of this unit type to a new unit instance
void upgrade (const std::shared_ptr< AttributeContainer > &attr)
upgrades one attribute of this unit type
UnitType * parent_type () const
returns type matching parent_id()
Private Member Functions
std::vector< game_resource > get_accepted_resources ()
TerrainObject * make_annex (Unit &u, std::shared_ptr< Terrain > t, int annex_id, coord::phys3 annex_pos, bool c) const
Private Attributes
const gamedata::building_unit unit_data
const Sound * on_create
Sound id played when object is created or destroyed.
const Sound * on_destroy
std::shared_ptr< Texture > terrain_outline
std::shared_ptr< UnitTexture > texture
std::shared_ptr< UnitTexture > destroyed
int projectile
int foundation_terrain
bool enable_collisions
used for objects like town centers or gates where the base does not apply collision checks
Additional Inherited Members
Public Attributes inherited from openage::UnitType
const Player & owner
the player who owns this unit type
std::vector< UnitReference > instances
all instances of units made from this unit type this could allow all units of a type to be upgraded
std::vector< std::shared_ptr< UnitAbility > > type_abilities
abilities given to all instances
Attributes default_attributes
default attributes which get copied to new units
ResourceCost cost
The cost of the unit.
int have_limit
The max number of units of this type that a player can have at an instance.
int had_limit
The max number of units of this type that a player can create.
graphic_set graphics
The set of graphics used for this type.
coord::tile_delta foundation_size
the square dimensions of the placement
gamedata::unit_classes unit_class
raw game data class of this unit instance
Detailed Description
Stores graphics and attributes for a building type Will be replaced with nyan system in future in aoe buildings are derived from living units.
Definition at line 108 of file producer.h.
Constructor & Destructor Documentation
BuildingProducer()
openage::BuildingProducer::BuildingProducer (const Player & owner, const GameSpec & spec, const gamedata::building_unit * ud)
Definition at line 522 of file producer.cpp.
     :
     UnitType(owner),
     unit_data{*ud},
     texture{spec.get_unit_texture(ud->graphic_standing0)},
     destroyed{spec.get_unit_texture(ud->dying_graphic)},
     projectile{this->unit_data.missile_unit_id},
     foundation_terrain{ud->foundation_terrain_id},
     enable_collisions{this->unit_data.id0 != 109} { // 109 = town center
     // copy the class type
     this->unit_class = this->unit_data.unit_class;
     // find suitable sounds
     int creation_sound = this->unit_data.train_sound;
     int dying_sound = this->unit_data.sound_dying;
     if (creation_sound == -1) {
         creation_sound = this->unit_data.damage_sound;
     }
     if (creation_sound == -1) {
         creation_sound = this->unit_data.sound_selection;
     }
     if (dying_sound == -1) {
         dying_sound = 323; //generic explosion sound
     }
     on_create = spec.get_sound(creation_sound);
     on_destroy = spec.get_sound(dying_sound);
     // convert the float to the discrete foundation size...
     this->foundation_size = {
         static_cast<int>(this->unit_data.radius_x * 2),
         static_cast<int>(this->unit_data.radius_y * 2),
     };
     // graphic set
     this->graphics[graphic_type::construct] = spec.get_unit_texture(ud->construction_graphic_id);
     this->graphics[graphic_type::standing] = spec.get_unit_texture(ud->graphic_standing0);
     this->graphics[graphic_type::attack] = spec.get_unit_texture(ud->graphic_standing0);
     auto dying_tex = spec.get_unit_texture(ud->dying_graphic);
     if (dying_tex) {
         this->graphics[graphic_type::dying] = dying_tex;
     }
     this->terrain_outline = square_outline(this->foundation_size);
     // \todo get cost, temp fixed cost of 100 wood
     this->cost.set(cost_type::constant, create_resource_cost(game_resource::wood, 100));
 }
References openage::owner.
~BuildingProducer()
openage::BuildingProducer::~BuildingProducer () virtual
Definition at line 571 of file producer.cpp.
 {}
Member Function Documentation
get_accepted_resources()
std::vector< game_resource > openage::BuildingProducer::get_accepted_resources () private
Definition at line 650 of file producer.cpp.
{
     // \todo use a more general approach instead of hard coded ids
     auto id_in = [=](std::initializer_list<int> ids) {
         return std::any_of(ids.begin(), ids.end(), [=](int n) { return n == this->id(); });
     };
     if (this->id() == 109) { // Town center
         return std::vector<game_resource>{
             game_resource::wood,
             game_resource::food,
             game_resource::gold,
             game_resource::stone
         };
     } else if (id_in({584, 585, 586, 587})) { // Mine
         return std::vector<game_resource>{
             game_resource::gold,
             game_resource::stone
         };
     } else if (id_in({68, 129, 130, 131})) { // Mill
         return std::vector<game_resource>{
             game_resource::food
         };
     } else if (id_in({562, 563, 564, 565})) { // Lumberjack camp
         return std::vector<game_resource>{
             game_resource::wood
         };
     }
     return std::vector<game_resource>();
 }
References openage::food, openage::gold, id(), openage::stone, and openage::wood.
Referenced by initialise().
id()
int openage::BuildingProducer::id () const override virtual
gets the unique id of this unit type
Implements openage::UnitType.
Definition at line 573 of file producer.cpp.
{
     return this->unit_data.id0;
 }
References unit_data.
Referenced by get_accepted_resources().
initialise()
void openage::BuildingProducer::initialise (Unit * , Player &) override virtual
Initialize units attributes to this type spec.
This can be called using existing units to modify type Ensure that the unit has been placed before seting the units type
Todo:
make const
Implements openage::UnitType.
Definition at line 585 of file producer.cpp.
{
     ENSURE(this->owner == player, "unit init from a UnitType of a wrong player which breaks tech levels");
     // log type
     unit->log(MSG(dbg) << "setting unit type " <<
         this->unit_data.id0 << " " <<
         this->unit_data.name);
     // initialize graphic set
     unit->unit_type = this;
     auto player_attr = std::make_shared<Attribute<attr_type::owner>>(player);
     unit->add_attribute(player_attr);
     // building specific attribute
     auto build_attr = std::make_shared<Attribute<attr_type::building>>(
         this->foundation_terrain,
         this->owner.get_type(293), // fem_villager, male is 83
         unit->location->pos.draw
     );
     build_attr->completion_state = this->enable_collisions ? object_state::placed : object_state::placed_no_collision;
     unit->add_attribute(build_attr);
     // garrison and hp for all buildings
     unit->add_attribute(std::make_shared<Attribute<attr_type::garrison>>());
     unit->add_attribute(std::make_shared<Attribute<attr_type::hitpoints>>(this->unit_data.hit_points));
     unit->add_attribute(std::make_shared<Attribute<attr_type::damaged>>(this->unit_data.hit_points));
     // population
     if (this->id() == 109 || this->id() == 70) { // Town center, House
         unit->add_attribute(std::make_shared<Attribute<attr_type::population>>(0, 5));
     }
     else if (this->id() == 82) { // Castle
         unit->add_attribute(std::make_shared<Attribute<attr_type::population>>(0, 20));
     }
     // limits
     if (this->id() == 109 || this->id() == 276) { // Town center, Wonder
         this->have_limit = 2; // \todo change to 1, 2 is for testing
     }
     bool has_destruct_graphic = this->destroyed != nullptr;
     unit->push_action(std::make_unique<FoundationAction>(unit, has_destruct_graphic), true);
     UnitType *proj_type = this->owner.get_type(this->projectile);
     if (this->unit_data.missile_unit_id > 0 && proj_type) {
         coord::phys_t range_phys = this->unit_data.weapon_range_max;
         unit->add_attribute(std::make_shared<Attribute<attr_type::attack>>(proj_type, range_phys, 350000, 1));
         // formation is used only for the attack_stance
         unit->add_attribute(std::make_shared<Attribute<attr_type::formation>>(attack_stance::aggressive));
         unit->give_ability(std::make_shared<AttackAbility>());
     }
     // dropsite attribute
     std::vector<game_resource> accepted_resources = this->get_accepted_resources();
     if (accepted_resources.size() != 0) {
         unit->add_attribute(std::make_shared<Attribute<attr_type::dropsite>>(accepted_resources));
     }
     // building can train new units and ungarrison
     unit->give_ability(std::make_shared<SetPointAbility>());
     unit->give_ability(std::make_shared<TrainAbility>());
     unit->give_ability(std::make_shared<UngarrisonAbility>());
 }
References openage::Unit::add_attribute(), openage::aggressive, openage::log::dbg(), destroyed, enable_collisions, ENSURE, foundation_terrain, get_accepted_resources(), openage::Player::get_type(), openage::Unit::give_ability(), openage::UnitType::have_limit, openage::Unit::location, openage::log::LogSource::log(), MSG, openage::UnitType::owner, openage::placed, openage::placed_no_collision, projectile, openage::Unit::push_action(), unit_data, and openage::Unit::unit_type.
make_annex()
TerrainObject * openage::BuildingProducer::make_annex (Unit & u, std::shared_ptr< Terrain > t, int annex_id, coord::phys3 annex_pos, bool c) const private
Definition at line 749 of file producer.cpp.
{
     // for use in lambda drawing functions
     auto annex_type = this->owner.get_type(annex_id);
     if (!annex_type) {
         u.log(MSG(warn) << "Invalid annex type id " << annex_id);
         return nullptr;
     }
     // foundation size
     coord::tile_delta annex_foundation = annex_type->foundation_size;
     // producers place by the nw tile
     coord::phys3 start_tile = annex_pos;
     start_tile.ne -= annex_foundation.ne / 2.0;
     start_tile.se -= annex_foundation.se / 2.0;
     // create and place on terrain
     TerrainObject *annex_loc = u.location->make_annex<SquareObject>(annex_foundation);
     object_state state = c? object_state::placed : object_state::placed_no_collision;
     annex_loc->place(t, start_tile, state);
     // create special drawing functions for annexes,
     annex_loc->draw = [annex_loc, annex_type, &u, c](const Engine &e) {
         // hack which draws the outline in the right order
         // removable once rendering system is improved
         if (c && u.selected) {
             annex_loc->get_parent()->draw_outline(e.coord);
         }
         // only draw if building is completed
         if (u.has_attribute(attr_type::building) &&
             u.get_attribute<attr_type::building>().completed >= 1.0f) {
             u.draw(annex_loc, annex_type->graphics, e);
         }
     };
     return annex_loc;
 }
References openage::building, openage::TerrainObject::draw, openage::TerrainObject::draw_outline(), openage::TerrainObject::get_parent(), openage::Player::get_type(), openage::Unit::location, openage::log::LogSource::log(), MSG, openage::UnitType::owner, openage::TerrainObject::place(), openage::placed, openage::placed_no_collision, and openage::log::warn().
Referenced by place().
name()
std::string openage::BuildingProducer::name () const override virtual
gets the name of the unit type being produced
Implements openage::UnitType.
Definition at line 581 of file producer.cpp.
{
     return this->unit_data.name;
 }
References unit_data.
Referenced by openage.util.fslike.path.Path::stem(), openage.util.fslike.path.Path::suffix(), and openage.util.fslike.path.Path::suffixes().
parent_id()
int openage::BuildingProducer::parent_id () const override virtual
gets the parent id of this unit type which is used for village base and gather types
Implements openage::UnitType.
Definition at line 577 of file producer.cpp.
{
     return this->unit_data.id0;
 }
References unit_data.
place()
TerrainObject * openage::BuildingProducer::place (Unit * , std::shared_ptr< Terrain > , coord::phys3) const override virtual
set unit in place – return if placement was successful
This should be used when initially creating a unit or when a unit is ungarrsioned from a building or object
Todo:
make const
Implements openage::UnitType.
Definition at line 682 of file producer.cpp.
{
     // buildings have a square base
     u->make_location<SquareObject>(this->foundation_size, this->terrain_outline);
     /*
      * decide what terrain is passable using this lambda
      * currently unit avoids water and tiles with another unit
      * this function should be true if pos is a valid position of the object
      */
     TerrainObject *obj_ptr = u->location.get();
     std::weak_ptr<Terrain> terrain_ptr = terrain;
     // find set of allowed terrains
     std::unordered_set<terrain_t> terrains = allowed_terrains(this->unit_data.terrain_restriction);
     u->location->passable = [obj_ptr, terrain_ptr, terrains](const coord::phys3 &pos) -> bool {
         auto terrain = terrain_ptr.lock();
         // look at all tiles in the bases range
         for (coord::tile check_pos : tile_list(obj_ptr->get_range(pos, *terrain))) {
             TileContent *tc = terrain->get_data(check_pos);
             // check if terrains are suitable and free of content
             if (!tc || !terrains.count(tc->terrain_id) || tc->obj.size()) {
                 return false;
             }
         }
         return true;
     };
     // drawing function
     bool draw_outline = this->enable_collisions;
     u->location->draw = [u, obj_ptr, draw_outline](const Engine &e) {
         if (u->selected && draw_outline) {
             obj_ptr->draw_outline(e.coord);
         }
         u->draw(e);
     };
     // try to place the obj, it knows best whether it will fit.
     auto state = object_state::floating;
     if (!u->location->place(terrain, init_pos, state)) {
         return nullptr;
     }
     // annex objects
     for (unsigned i = 0; i < 4; ++i) {
         const gamedata::building_annex &annex = this->unit_data.building_annex.data[i];
         if (annex.unit_id > 0) {
             // make objects for annex
             coord::phys3 a_pos = u->location->pos.draw;
             a_pos.ne += annex.misplaced0;
             a_pos.se += annex.misplaced1;
             this->make_annex(*u, terrain, annex.unit_id, a_pos, i == 0);
         }
     }
     // \todo play sound once built
     if (this->on_create) {
         this->on_create->play();
     }
     return u->location.get();
 }
References openage::allowed_terrains(), openage::Unit::draw(), enable_collisions, openage::floating, openage::UnitType::foundation_size, openage::Unit::location, make_annex(), openage::Unit::make_location(), openage::TileContent::obj, on_create, openage::Sound::play(), openage::Unit::selected, openage::TileContent::terrain_id, terrain_outline, openage::tile_list(), and unit_data.
Member Data Documentation
destroyed
std::shared_ptr<UnitTexture> openage::BuildingProducer::destroyed private
Definition at line 131 of file producer.h.
Referenced by initialise().
enable_collisions
bool openage::BuildingProducer::enable_collisions private
used for objects like town centers or gates where the base does not apply collision checks
Definition at line 140 of file producer.h.
Referenced by initialise(), and place().
foundation_terrain
int openage::BuildingProducer::foundation_terrain private
Definition at line 133 of file producer.h.
Referenced by initialise().
on_create
const Sound* openage::BuildingProducer::on_create private
Sound id played when object is created or destroyed.
Definition at line 127 of file producer.h.
Referenced by place().
on_destroy
const Sound* openage::BuildingProducer::on_destroy private
Definition at line 128 of file producer.h.
projectile
int openage::BuildingProducer::projectile private
Definition at line 132 of file producer.h.
Referenced by initialise().
terrain_outline
std::shared_ptr<Texture> openage::BuildingProducer::terrain_outline private
Definition at line 129 of file producer.h.
Referenced by place().
texture
std::shared_ptr<UnitTexture> openage::BuildingProducer::texture private
Definition at line 130 of file producer.h.
unit_data
const gamedata::building_unit openage::BuildingProducer::unit_data private
Definition at line 122 of file producer.h.
Referenced by id(), initialise(), name(), parent_id(), and place().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/producer.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/producer.cpp