openage: openage::curve::QueueFilterIterator< val_t, container_t > Class Template Reference
openage::curve::QueueFilterIterator< val_t, container_t > Class Template Reference
#include <queue_filter_iterator.h>
Public Types
using const_iterator = typename container_t::const_iterator
Public Member Functions
QueueFilterIterator (const const_iterator &base, const container_t *base_container, const time_t &from, const time_t &to)
virtual bool valid () const override
const val_t & value () const override
Public Member Functions inherited from openage::curve::CurveIterator< val_t, container_t, container_t::const_iterator >
CurveIterator (const container_t *c)
CurveIterator (const CurveIterator &)=default
virtual ~CurveIterator ()=default
CurveIterator< val_t, container_t, container_t::const_iterator > & operator= (const CurveIterator< val_t, container_t, container_t::const_iterator > &)=default
virtual const val_t & operator * () const
virtual const val_t * operator -> () const
virtual bool operator== (const CurveIterator< val_t, container_t > &rhs) const
virtual bool operator != (const CurveIterator< val_t, container_t > &rhs) const
virtual CurveIterator< val_t, container_t > & operator++ ()
const container_t::const_iterator & get_base () const
const time_t & get_from () const
const time_t & get_to () const
Additional Inherited Members
Protected Member Functions inherited from openage::curve::CurveIterator< val_t, container_t, container_t::const_iterator >
CurveIterator (const container_t::const_iterator &base, const container_t *container, const time_t &from, const time_t &to)
Protected Attributes inherited from openage::curve::CurveIterator< val_t, container_t, container_t::const_iterator >
container_t::const_iterator base
The iterator this is currently referring to.
const container_t * container
The base container.
time_t from
The time, from where this iterator started to iterate.
time_t to
The time, to where this iterator will iterate.
Detailed Description
template<typename val_t, typename container_t>
class openage::curve::QueueFilterIterator< val_t, container_t >
A filtering operator to iterate over all elements of a queue whose elements exist at exactly one point of time, the range where to iterate is given at construction.
It depends on val_t as its value type, container_t is the container to operate on and the function valid_f, that checks if an element is alive.
Definition at line 24 of file queue_filter_iterator.h.
Member Typedef Documentation
const_iterator
template<typename val_t, typename container_t> using openage::curve::QueueFilterIterator< val_t, container_t >::const_iterator = typename container_t::const_iterator
Definition at line 26 of file queue_filter_iterator.h.
Constructor & Destructor Documentation
QueueFilterIterator()
template<typename val_t, typename container_t> openage::curve::QueueFilterIterator< val_t, container_t >::QueueFilterIterator (const const_iterator & base, const container_t * base_container, const time_t & from, const time_t & to) inline
Construct the iterator from its boundary conditions: time and container
Definition at line 31 of file queue_filter_iterator.h.
         :
         CurveIterator<val_t, container_t>(base, base_container, from, to) {}
Member Function Documentation
valid()
template<typename val_t, typename container_t> virtual bool openage::curve::QueueFilterIterator< val_t, container_t >::valid () const inline override virtual
Check if the iterator is still valid (this breaks from the stl - in the best way)
Implements openage::curve::CurveIterator< val_t, container_t, container_t::const_iterator >.
Definition at line 38 of file queue_filter_iterator.h.
{
         if (this->container->end().get_base() != this->get_base()) {
             return (this->get_base()->time() >= this->from and
                     this->get_base()->time() < this->to);
         }
         return false;
     }
References openage::curve::CurveIterator< val_t, container_t, container_t::const_iterator >::container, openage::curve::CurveIterator< val_t, container_t, container_t::const_iterator >::from, openage::curve::CurveIterator< val_t, container_t, container_t::const_iterator >::get_base(), and openage::curve::CurveIterator< val_t, container_t, container_t::const_iterator >::to.
value()
template<typename val_t, typename container_t> const val_t& openage::curve::QueueFilterIterator< val_t, container_t >::value () const inline override virtual
access the value of the iterator
Implements openage::curve::CurveIterator< val_t, container_t, container_t::const_iterator >.
Definition at line 46 of file queue_filter_iterator.h.
{
         const auto &a = *this->get_base();
         return a.value;
     }
References openage::curve::CurveIterator< val_t, container_t, container_t::const_iterator >::get_base().
Referenced by openage.convert.dataformat.members.ContinueReadMemberResult::__str__().
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/curve/queue_filter_iterator.h