openage: openage::Research Class Reference
openage::Research Class Reference
#include <research.h>
Public Member Functions
Research (const ResearchType *type)
void started ()
void stopped ()
void completed ()
bool can_start () const
bool is_active () const
bool is_researched () const
void apply ()
Public Attributes
const ResearchType * type
Protected Attributes
int active_count
int completed_count
Detailed Description
At most one Research must exist for each ResearchType.
A research represents how many times the research type has been completed (completed count) and also how many unit are researching it now (active count).
Definition at line 104 of file research.h.
Constructor & Destructor Documentation
Research()
openage::Research::Research (const ResearchType * type)
Definition at line 18 of file research.cpp.
     :
     type{type},
     active_count{0},
     completed_count{0} {
 }
References type.
Member Function Documentation
apply()
void openage::Research::apply ()
Apply the modifications to the owner player.
Definition at line 50 of file research.cpp.
                      {
     // apply the patch
     this->type->apply();
     // perform category based actions
     if (type->category() == research_category::age_advance) {
         type->owner.advance_age();
     } else if (type->category() == research_category::generic) {
         // \todo implement a way to handle this category
     }
 }
References openage::Player::advance_age(), openage::age_advance, openage::ResearchType::apply(), openage::ResearchType::category(), openage::generic, openage::ResearchType::owner, and type.
Referenced by openage::ResearchAction::update().
can_start()
bool openage::Research::can_start () const
Returns true if a unit can start researching this research.
Definition at line 38 of file research.cpp.
{
     return this->active_count + this->completed_count < this->type->get_max_repeats();
 }
References active_count, completed_count, openage::ResearchType::get_max_repeats(), and type.
completed()
void openage::Research::completed ()
Called when a unit completed researching this research.
Definition at line 33 of file research.cpp.
{
     this->active_count -= 1;
     this->completed_count += 1;
 }
References active_count, and completed_count.
Referenced by openage::ResearchAction::update().
is_active()
bool openage::Research::is_active () const
Returns true if any unit is researching this research.
Definition at line 42 of file research.cpp.
{
     return this->active_count > 0;
 }
References active_count.
is_researched()
bool openage::Research::is_researched () const
Returns true if it has nothing more to offer (reached max repeats).
Definition at line 46 of file research.cpp.
{
     return this->completed_count == this->type->get_max_repeats();
 }
References completed_count, openage::ResearchType::get_max_repeats(), and type.
started()
void openage::Research::started ()
Called when a unit started researching this research.
Definition at line 25 of file research.cpp.
{
     this->active_count += 1;
 }
References active_count.
stopped()
void openage::Research::stopped ()
Called when a unit stopped researching this research before completing it.
Definition at line 29 of file research.cpp.
{
     this->active_count -= 1;
 }
References active_count.
Referenced by openage::ResearchAction::on_completion().
Member Data Documentation
active_count
int openage::Research::active_count protected
The number of units that are researching this research
Definition at line 151 of file research.h.
Referenced by can_start(), completed(), is_active(), started(), and stopped().
completed_count
int openage::Research::completed_count protected
The number of times this research has been completed
Definition at line 156 of file research.h.
Referenced by can_start(), completed(), and is_researched().
type
const ResearchType* openage::Research::type
Definition at line 109 of file research.h.
Referenced by apply(), can_start(), openage::ResearchAction::get_research_type(), is_researched(), and Research().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/research.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/research.cpp