openage: openage::renderer::vulkan::VlkGraphicsDevice Class Reference
openage::renderer::vulkan::VlkGraphicsDevice Class Reference
Owns a device capable of graphics operations and surface presentation using WSI.
#include <graphics_device.h>
Public Member Functions
VlkGraphicsDevice (VkPhysicalDevice dev, std::vector< uint32_t > const &q_fams)
Given a physical device and a list of queue family indices in that device, instantiates a logical device with a queue per each of the families.
VkPhysicalDevice get_physical_device () const
VkDevice get_device () const
VkQueue get_queue (size_t idx) const
~VlkGraphicsDevice ()
Static Public Member Functions
static std::optional< SurfaceSupportDetails > find_device_surface_support (VkPhysicalDevice, VkSurfaceKHR)
Given a physical device and a surface, checks whether the device is capable of presenting to the surface.
Private Attributes
VkPhysicalDevice phys_device
The underlying physical device.
VkDevice device
Logical device, owned by this object.
std::vector< VkQueue > queues
The queues instantiated for this device.
Detailed Description
Owns a device capable of graphics operations and surface presentation using WSI.
Definition at line 42 of file graphics_device.h.
Constructor & Destructor Documentation
VlkGraphicsDevice()
openage::renderer::vulkan::VlkGraphicsDevice::VlkGraphicsDevice (VkPhysicalDevice dev, std::vector< uint32_t > const & q_fams)
Given a physical device and a list of queue family indices in that device, instantiates a logical device with a queue per each of the families.
The device has to support the swapchain extension.
Definition at line 93 of file graphics_device.cpp.
     : phys_device(dev)
 {
     // Prepare queue creation info for each family requested
     std::vector<VkDeviceQueueCreateInfo> q_infos(q_fams.size());
     const float p = 1.0f;
     for (size_t i = 0; i < q_fams.size(); i++) {
         q_infos[i].sType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO;
         q_infos[i].queueFamilyIndex = q_fams[i];
         q_infos[i].queueCount = 1;
         q_infos[i].pQueuePriorities = &p;
     }
     // Request these extensions
     std::vector<const char*> ext_names = { VK_KHR_SWAPCHAIN_EXTENSION_NAME };
     // Check if extensions are available
     auto exts = vk_do_ritual(vkEnumerateDeviceExtensionProperties, dev, nullptr);
     for (auto ext : ext_names) {
         if (std::count_if(exts.begin(), exts.end(), [=] (VkExtensionProperties const& p) {
                                                         return std::strcmp(p.extensionName, ext) == 0;
                                                     } ) == 0
         ) {
             throw Error(MSG(err) << "Tried to instantiate device, but it's missing this extension: " << ext);
         }
     }
 #ifndef NDEBUG
     {
         VkPhysicalDeviceProperties dev_props;
         vkGetPhysicalDeviceProperties(this->phys_device, &dev_props);
         log::log(MSG(dbg) << "Chosen Vulkan graphics device: " << dev_props.deviceName);
         log::log(MSG(dbg) << "Device extensions:");
         for (auto const& ext : exts) {
             log::log(MSG(dbg) << "\t" << ext.extensionName);
         }
     }
 #endif
     // Prepare device creation
     VkDeviceCreateInfo create_dev {};
     create_dev.sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO;
     create_dev.queueCreateInfoCount = q_infos.size();
     create_dev.pQueueCreateInfos = q_infos.data();
     create_dev.enabledExtensionCount = ext_names.size();
     create_dev.ppEnabledExtensionNames = ext_names.data();
     VkPhysicalDeviceFeatures features {};
     // \todo request features
     create_dev.pEnabledFeatures = &features;
     VK_CALL_CHECKED(vkCreateDevice, this->phys_device, &create_dev, nullptr, &this->device);
     // Obtain handles for the created queues
     this->queues.resize(q_fams.size());
     for (size_t i = 0; i < q_fams.size(); i++) {
         vkGetDeviceQueue(this->device, q_fams[i], 0, &this->queues[i]);
     }
 }
References openage::log::dbg(), device, openage::log::err(), openage::log::log(), MSG, phys_device, queues, VK_CALL_CHECKED, and vk_do_ritual().
~VlkGraphicsDevice()
openage::renderer::vulkan::VlkGraphicsDevice::~VlkGraphicsDevice ()
Definition at line 166 of file graphics_device.cpp.
{
     vkDestroyDevice(this->device, nullptr);
 }
References device.
Member Function Documentation
find_device_surface_support()
std::optional< SurfaceSupportDetails > openage::renderer::vulkan::VlkGraphicsDevice::find_device_surface_support (VkPhysicalDevice dev, VkSurfaceKHR surf) static
Given a physical device and a surface, checks whether the device is capable of presenting to the surface.
If it is, returns information about its presentation capabilities, otherwise returns an empty optional.
Definition at line 17 of file graphics_device.cpp.
{
     // Search for queue families in the device
     auto q_fams = vk_do_ritual(vkGetPhysicalDeviceQueueFamilyProperties, dev);
     std::optional<uint32_t> maybe_graphics_fam = {};
     std::optional<uint32_t> maybe_present_fam = {};
     // Figure out if any of the families supports graphics
     for (size_t i = 0; i < q_fams.size(); i++) {
         auto const& q_fam = q_fams[i];
         if (q_fam.queueCount > 0) {
             if ((q_fam.queueFlags & VK_QUEUE_GRAPHICS_BIT) != 0u) {
                 maybe_graphics_fam = i;
                 // See if it also supports present
                 VkBool32 support = VK_FALSE;
                 vkGetPhysicalDeviceSurfaceSupportKHR(dev, i, surf, &support);
                 if (support != VK_FALSE) {
                     // This family support both, we're done
                     maybe_present_fam = i;
                     break;
                 }
             }
         }
     }
     if (!maybe_graphics_fam) {
         // This device has no graphics queue family that works with the surface
         return {};
     }
     SurfaceSupportDetails details = {};
     details.phys_device = dev;
     details.surface = surf;
     // If we have found a family that support both graphics and present
     if (maybe_present_fam) {
         details.graphics_fam = *maybe_graphics_fam;
         details.maybe_present_fam = {};
     } else {
         // Otherwise look for a present-only queue
         for (size_t i = 0; i < q_fams.size(); i++) {
             auto const& q_fam = q_fams[i];
             if (q_fam.queueCount > 0) {
                 VkBool32 support = VK_FALSE;
                 vkGetPhysicalDeviceSurfaceSupportKHR(dev, i, surf, &support);
                 if (support != VK_FALSE) {
                     maybe_present_fam = i;
                     break;
                 }
             }
         }
         if (!maybe_present_fam) {
             // This device has no present queue family that works with the surface
             return {};
         }
         details.graphics_fam = *maybe_graphics_fam;
         details.maybe_present_fam = maybe_present_fam;
     }
     // Obtain other information
     details.surface_formats = vk_do_ritual(vkGetPhysicalDeviceSurfaceFormatsKHR, dev, surf);
     details.present_modes = vk_do_ritual(vkGetPhysicalDeviceSurfacePresentModesKHR, dev, surf);
     vkGetPhysicalDeviceSurfaceCapabilitiesKHR(dev, surf, &details.surface_caps);
     // Finally, check that we have at least one format and present mode
     if (details.surface_formats.empty() || details.present_modes.empty()) {
         return {};
     }
     return details;
 }
References openage::renderer::vulkan::SurfaceSupportDetails::graphics_fam, openage::renderer::vulkan::SurfaceSupportDetails::maybe_present_fam, openage::renderer::vulkan::SurfaceSupportDetails::phys_device, openage::renderer::vulkan::SurfaceSupportDetails::present_modes, openage::renderer::vulkan::SurfaceSupportDetails::surface, openage::renderer::vulkan::SurfaceSupportDetails::surface_caps, openage::renderer::vulkan::SurfaceSupportDetails::surface_formats, and vk_do_ritual().
Referenced by openage::renderer::vulkan::VlkRenderer::do_the_thing().
get_device()
VkDevice openage::renderer::vulkan::VlkGraphicsDevice::get_device () const
Definition at line 158 of file graphics_device.cpp.
{
     return this->device;
 }
References device.
Referenced by openage::renderer::vulkan::VlkRenderer::do_the_thing().
get_physical_device()
VkPhysicalDevice openage::renderer::vulkan::VlkGraphicsDevice::get_physical_device () const
Definition at line 154 of file graphics_device.cpp.
{
     return this->phys_device;
 }
References phys_device.
get_queue()
VkQueue openage::renderer::vulkan::VlkGraphicsDevice::get_queue (size_t idx) const
Definition at line 162 of file graphics_device.cpp.
{
     return this->queues[idx];
 }
References queues.
Referenced by openage::renderer::vulkan::VlkRenderer::do_the_thing().
Member Data Documentation
device
VkDevice openage::renderer::vulkan::VlkGraphicsDevice::device private
Logical device, owned by this object.
Definition at line 47 of file graphics_device.h.
Referenced by get_device(), VlkGraphicsDevice(), and ~VlkGraphicsDevice().
phys_device
VkPhysicalDevice openage::renderer::vulkan::VlkGraphicsDevice::phys_device private
The underlying physical device.
Definition at line 44 of file graphics_device.h.
Referenced by get_physical_device(), and VlkGraphicsDevice().
queues
std::vector<VkQueue> openage::renderer::vulkan::VlkGraphicsDevice::queues private
The queues instantiated for this device.
Definition at line 50 of file graphics_device.h.
Referenced by get_queue(), and VlkGraphicsDevice().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/vulkan/graphics_device.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/vulkan/graphics_device.cpp