openage: openage::util::filelike::Python Class Reference
openage::util::filelike::Python Class Reference
#include <python.h>
Public Member Functions
Python (py::Obj fileobj)
std::string read (ssize_t max) override
size_t read_to (void *buf, ssize_t max) override
bool readable () override
void write (const std::string &data) override
bool writable () override
void seek (ssize_t offset, seek_t how=seek_t::SET) override
bool seekable () override
size_t tell () override
void close () override
void flush () override
ssize_t get_size () override
bool is_python_native () const noexcept override
OAAPI py::Obj & get_py_fileobj () const
std::ostream & repr (std::ostream &) override
Public Member Functions inherited from openage::util::filelike::FileLike
FileLike ()
virtual ~FileLike ()=default
Protected Attributes
std::shared_ptr< py::Obj > fileobj
Additional Inherited Members
Public Types inherited from openage::util::filelike::FileLike
enum seek_t : int { seek_t::SET = 0, seek_t::CUR = 1, seek_t::END = 2 }
enum mode_t : int {
mode_t::R = 0, mode_t::W = 1, mode_t::RW = 2, mode_t::A = 3,
mode_t::AR = 4
}
Detailed Description
File-like class that wraps a python open() file-like object.
pxd: cppclass Python: PyObj &get_py_fileobj() except +
Definition at line 31 of file python.h.
Constructor & Destructor Documentation
Python()
openage::util::filelike::Python::Python (py::Obj fileobj)
Definition at line 12 of file python.cpp.
     :
     fileobj{std::make_shared<py::Obj>(fileobj)} {}
References fileobj.
Member Function Documentation
close()
void openage::util::filelike::Python::close () override virtual
Implements openage::util::filelike::FileLike.
Definition at line 60 of file python.cpp.
                    {
     pyx_file_close.call(this->fileobj->get_ref());
 }
References fileobj, and openage::util::filelike::pyx_file_close.
Referenced by openage.util.filelike.abstract.FileLikeObject::__exit__(), and openage.convert.slp_converter_pool.SLPConverterPool::__exit__().
flush()
void openage::util::filelike::Python::flush () override virtual
Implements openage::util::filelike::FileLike.
Definition at line 65 of file python.cpp.
                    {
     pyx_file_flush.call(this->fileobj->get_ref());
 }
References fileobj, and openage::util::filelike::pyx_file_flush.
get_py_fileobj()
py::Obj & openage::util::filelike::Python::get_py_fileobj () const
Definition at line 80 of file python.cpp.
{
     return *this->fileobj.get();
 }
References fileobj.
get_size()
ssize_t openage::util::filelike::Python::get_size () override virtual
Implements openage::util::filelike::FileLike.
Definition at line 70 of file python.cpp.
{
     return pyx_file_size.call(this->fileobj->get_ref());
 }
References fileobj, and openage::util::filelike::pyx_file_size.
Referenced by openage.util.filelike.abstract.FileLikeObject::seek_helper().
is_python_native()
bool openage::util::filelike::Python::is_python_native () const override virtual noexcept
Reimplemented from openage::util::filelike::FileLike.
Definition at line 75 of file python.cpp.
{
     return true;
 }
read()
std::string openage::util::filelike::Python::read (ssize_t max) override virtual
Implements openage::util::filelike::FileLike.
Definition at line 17 of file python.cpp.
{
     return pyx_file_read.call(this->fileobj->get_ref(), max);
 }
References fileobj, openage::console::tests::max(), and openage::util::filelike::pyx_file_read.
Referenced by openage.convert.dataformat.exportable.Exportable::read(), and openage.convert.peresource.StringLiteral::readall().
read_to()
size_t openage::util::filelike::Python::read_to (void * buf, ssize_t max) override virtual
Implements openage::util::filelike::FileLike.
Definition at line 22 of file python.cpp.
{
     return pyx_file_read_to.call(this->fileobj->get_ref(), buf, max);
 }
References fileobj, openage::console::tests::max(), and openage::util::filelike::pyx_file_read_to.
readable()
bool openage::util::filelike::Python::readable () override virtual
Implements openage::util::filelike::FileLike.
Definition at line 27 of file python.cpp.
                       {
     return pyx_file_readable.call(this->fileobj->get_ref());
 }
References fileobj, and openage::util::filelike::pyx_file_readable.
repr()
std::ostream & openage::util::filelike::Python::repr (std::ostream &) override virtual
string representation of the filelike
Implements openage::util::filelike::FileLike.
Definition at line 85 of file python.cpp.
{
     stream << this->fileobj->repr();
     return stream;
 }
References fileobj.
seek()
void openage::util::filelike::Python::seek (ssize_t offset, seek_t how = seek_t::SET) override virtual
Implements openage::util::filelike::FileLike.
Definition at line 42 of file python.cpp.
{
     // transform the enum class...
     int how_i = static_cast<std::underlying_type<seek_t>::type>(how);
     pyx_file_seek.call(this->fileobj->get_ref(), offset, how_i);
 }
References fileobj, and openage::util::filelike::pyx_file_seek.
seekable()
bool openage::util::filelike::Python::seekable () override virtual
Implements openage::util::filelike::FileLike.
Definition at line 50 of file python.cpp.
                       {
     return pyx_file_seekable.call(this->fileobj->get_ref());
 }
References fileobj, and openage::util::filelike::pyx_file_seekable.
tell()
size_t openage::util::filelike::Python::tell () override virtual
Implements openage::util::filelike::FileLike.
Definition at line 55 of file python.cpp.
                     {
     return pyx_file_tell.call(this->fileobj->get_ref());
 }
References fileobj, and openage::util::filelike::pyx_file_tell.
Referenced by openage.util.filelike.abstract.FileLikeObject::seek_helper().
writable()
bool openage::util::filelike::Python::writable () override virtual
Implements openage::util::filelike::FileLike.
Definition at line 37 of file python.cpp.
                       {
     return pyx_file_writable.call(this->fileobj->get_ref());
 }
References fileobj, and openage::util::filelike::pyx_file_writable.
Referenced by openage.util.fslike.wrapper.Wrapper::resolve_w(), and openage.util.fslike.abstract.FSLikeObject::resolve_w().
write()
void openage::util::filelike::Python::write (const std::string & data) override virtual
Implements openage::util::filelike::FileLike.
Definition at line 32 of file python.cpp.
{
     pyx_file_write.call(this->fileobj->get_ref(), data);
 }
References fileobj, and openage::util::filelike::pyx_file_write.
Member Data Documentation
fileobj
std::shared_ptr<py::Obj> openage::util::filelike::Python::fileobj protected
Definition at line 57 of file python.h.
Referenced by close(), flush(), get_py_fileobj(), get_size(), openage.convert.peresource.ResourceLeaf::open(), openage.convert.pefile.PEFile::open_section(), Python(), read(), openage.cabextract.cab.CABFolderStream::read_block_data(), openage.convert.drs.DRS::read_tables(), read_to(), readable(), repr(), seek(), seekable(), tell(), writable(), and write().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/filelike/python.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/filelike/python.cpp