openage: openage::gui::EngineLink Class Reference
openage::gui::EngineLink Class Reference
#include <engine_link.h>
Signals
void global_binds_changed ()
Public Member Functions
EngineLink (QObject *parent, Engine *engine)
virtual ~EngineLink ()
template<typename U >
U * get () const
QStringList get_global_binds () const
Q_INVOKABLE void stop ()
Public Member Functions inherited from qtsdl::GuiSingletonItem
GuiSingletonItem (QObject *parent=nullptr)
virtual ~GuiSingletonItem ()
Public Member Functions inherited from qtsdl::GuiItemLink
virtual ~GuiItemLink ()
Static Public Member Functions
static QObject * provider (QQmlEngine *, QJSEngine *)
Properties
QStringList globalBinds
The text list of global key bindings.
Private Slots
void on_global_binds_changed (const std::vector< std::string > &global_binds)
Private Attributes
Engine * core
QStringList global_binds
Detailed Description
Definition at line 37 of file engine_link.h.
Constructor & Destructor Documentation
EngineLink()
openage::gui::EngineLink::EngineLink (QObject * parent, Engine * engine) explicit
Definition at line 24 of file engine_link.cpp.
     :
     GuiSingletonItem{parent},
     core{engine} {
     Q_UNUSED(registration);
     ENSURE(!unwrap(this)->gui_link, "Sharing singletons between QML engines is not supported for now.");
     // when the engine announces that the global key bindings
     // changed, update the display.
     QObject::connect(
         &unwrap(this)->gui_signals,
         &EngineSignals::global_binds_changed,
         this,
         &EngineLink::on_global_binds_changed
     );
     // trigger the engine signal,
     // which then triggers this->on_global_binds_changed.
     unwrap(this)->announce_global_binds();
 }
~EngineLink()
openage::gui::EngineLink::~EngineLink () virtual
Definition at line 46 of file engine_link.cpp.
{
     unwrap(this)->gui_link = nullptr;
 }
References qtsdl::unwrap().
Member Function Documentation
get()
template<typename U > U* openage::gui::EngineLink::get () const inline
Definition at line 55 of file engine_link.h.
                    {
         return core;
     }
References core.
get_global_binds()
QStringList openage::gui::EngineLink::get_global_binds () const
Definition at line 71 of file engine_link.cpp.
{
     return this->global_binds;
 }
References global_binds.
global_binds_changed
void openage::gui::EngineLink::global_binds_changed () signal
Referenced by on_global_binds_changed().
on_global_binds_changed
void openage::gui::EngineLink::on_global_binds_changed (const std::vector< std::string > & global_binds) private slot
Definition at line 79 of file engine_link.cpp.
{
     QStringList new_global_binds;
     // create the qstring list from the std string list
     // which is then displayed in the ui
     std::transform(
         std::begin(global_binds),
         std::end(global_binds),
         std::back_inserter(new_global_binds),
         [] (const std::string &s) {
             return QString::fromStdString(s);
         }
     );
     if (this->global_binds != new_global_binds) {
         this->global_binds = new_global_binds;
         emit this->global_binds_changed();
     }
 }
References global_binds, and global_binds_changed().
provider()
QObject * openage::gui::EngineLink::provider (QQmlEngine * engine, QJSEngine *) static
Definition at line 54 of file engine_link.cpp.
{
     // cast the engine to our specialization
     qtsdl::QmlEngineWithSingletonItemsInfo *engine_with_singleton_items_info = qtsdl::checked_static_cast<qtsdl::QmlEngineWithSingletonItemsInfo*>(engine);
     // get the singleton container out of the custom qml engine
     auto info = static_cast<gui::EngineQMLInfo*>(
         engine_with_singleton_items_info->get_singleton_items_info()
     );
     ENSURE(info, "qml-globals were lost or not passed to the gui subsystem");
     // owned by the QML engine
     // this handle contains the pointer to the openage engine,
     // obtained through the qmlengine
     return new EngineLink{nullptr, info->engine};
 }
References ENSURE, qtsdl::QmlEngineWithSingletonItemsInfo::get_singleton_items_info(), and openage::log::info().
stop()
void openage::gui::EngineLink::stop ()
Definition at line 75 of file engine_link.cpp.
                       {
     this->core->stop();
 }
References core, and openage::Engine::stop().
Member Data Documentation
core
Engine* openage::gui::EngineLink::core private
Definition at line 70 of file engine_link.h.
Referenced by get(), and stop().
global_binds
QStringList openage::gui::EngineLink::global_binds private
Definition at line 72 of file engine_link.h.
Referenced by get_global_binds(), and on_global_binds_changed().
Property Documentation
globalBinds
QStringList openage::gui::EngineLink::globalBinds read
The text list of global key bindings.
displayed so one can see what keys are active.
Definition at line 46 of file engine_link.h.
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/engine_link.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/engine_link.cpp