openage: openage::ScreenshotManager Class Reference
openage::ScreenshotManager Class Reference
#include <screenshot.h>
Public Member Functions
ScreenshotManager (job::JobManager *job_mgr)
~ScreenshotManager ()
void save_screenshot (coord::viewport_delta size)
bool encode_png (std::shared_ptr< uint8_t > pxdata, coord::viewport_delta size)
Public Attributes
coord::viewport_delta window_size
Private Member Functions
std::string gen_next_filename ()
Private Attributes
unsigned count
std::time_t last_time
job::JobManager * job_manager
Detailed Description
Definition at line 17 of file screenshot.h.
Constructor & Destructor Documentation
ScreenshotManager()
openage::ScreenshotManager::ScreenshotManager (job::JobManager * job_mgr)
Initializes the screenshot manager with the given job manager.
Definition at line 22 of file screenshot.cpp.
     :
     count{0},
     job_manager{job_mgr} {
 }
~ScreenshotManager()
openage::ScreenshotManager::~ScreenshotManager ()
Definition at line 29 of file screenshot.cpp.
 {}
Member Function Documentation
encode_png()
bool openage::ScreenshotManager::encode_png (std::shared_ptr< uint8_t > pxdata, coord::viewport_delta size)
To be called by the job manager. Returns true on success, false otherwise.
Definition at line 65 of file screenshot.cpp.
{
     std::FILE *fout = NULL;
     coord::pixel_t width = size.x,
                    height = size.y;
     auto warn_fn = [] (png_structp /*png_ptr*/, png_const_charp message) {
         log::log(MSG(err) << "Creating screenshot failed: libpng error: " << message);
     };
     auto err_fn = [] (png_structp png_ptr, png_const_charp message) {
         log::log(MSG(err) << "Creating screenshot failed: libpng error: " << message);
         longjmp(png_jmpbuf(png_ptr), 1);
     };
     png_structp png_ptr = png_create_write_struct(PNG_LIBPNG_VER_STRING,
                                                   (png_voidp) NULL,
                                                   err_fn, warn_fn);
     if (!png_ptr)
         return false;
     png_infop info_ptr = png_create_info_struct(png_ptr);
     if (!info_ptr) {
         png_destroy_write_struct(&png_ptr, (png_infopp) NULL);
         return false;
     }
     if (setjmp(png_jmpbuf(png_ptr))) {
         std::fclose(fout);
         png_destroy_write_struct(&png_ptr, &info_ptr);
         return false;
     }
     std::string filename = this->gen_next_filename();
     fout = std::fopen(filename.c_str(), "wb");
     if (fout == NULL) {
         png_destroy_write_struct(&png_ptr, &info_ptr);
         log::log(MSG(err) << "Could not open '"<< filename << "': "
                  << std::string(strerror(errno)));
         return false;
     }
     png_init_io(png_ptr, fout);
     png_set_IHDR(png_ptr, info_ptr, width, height, 8, PNG_COLOR_TYPE_RGB,
                  PNG_INTERLACE_NONE, PNG_COMPRESSION_TYPE_DEFAULT,
                  PNG_FILTER_TYPE_DEFAULT);
     // Put image row pointer into info_ptr so that we can use the high-level
     // write interface.
     std::vector<png_bytep> row_ptrs;
     // Invert rows.
     row_ptrs.reserve(height);
     for (int i = 1; i <= height; i++) {
         row_ptrs.push_back(pxdata.get() + (height - i) * 4 * width);
     }
     png_set_rows(png_ptr, info_ptr, &row_ptrs[0]);
     //TODO: print ingame message.
     log::log(MSG(info) << "Saving screenshot to '" << filename << "'.");
     png_write_png(png_ptr, info_ptr, PNG_TRANSFORM_STRIP_FILLER_AFTER, NULL);
     std::fclose(fout);
     png_destroy_write_struct(&png_ptr, &info_ptr);
     return true;
 }
References openage::log::err(), openage::util::filename(), gen_next_filename(), openage::log::info(), openage::log::log(), and MSG.
Referenced by save_screenshot().
gen_next_filename()
std::string openage::ScreenshotManager::gen_next_filename () private
to be called to get the next screenshot filename into the array
Definition at line 32 of file screenshot.cpp.
{
     std::time_t t = std::time(NULL);
     if (t == this->last_time) {
         this->count++;
     } else {
         this->count = 0;
         this->last_time = t;
     }
     // these two values (32) *must* be the same for safety reasons
     char timestamp[32];
     std::strftime(timestamp, 32, "%Y-%m-%d_%H-%M-%S", std::localtime(&t));
     return util::sformat("/tmp/openage_%s_%02d.png", timestamp, this->count);
 }
References count, last_time, and openage::util::sformat().
Referenced by encode_png().
save_screenshot()
void openage::ScreenshotManager::save_screenshot (coord::viewport_delta size)
To be called to save a screenshot.
Definition at line 51 of file screenshot.cpp.
{
     coord::pixel_t width = size.x,
                    height = size.y;
     std::shared_ptr<uint8_t> pxdata(new uint8_t[4*width*height], std::default_delete<uint8_t[]>());
     glReadPixels(0, 0, width, height, GL_RGBA, GL_UNSIGNED_BYTE, pxdata.get());
     auto encode_function = [this, pxdata, size] () {
         return this->encode_png(pxdata, size);
     };
     this->job_manager->enqueue<bool>(encode_function);
 }
References encode_png(), openage::job::JobManager::enqueue(), and job_manager.
Member Data Documentation
count
unsigned openage::ScreenshotManager::count private
contains the number to be in the next screenshot filename
Definition at line 42 of file screenshot.h.
Referenced by gen_next_filename().
job_manager
job::JobManager* openage::ScreenshotManager::job_manager private
the job manager this screenshot manager uses
Definition at line 48 of file screenshot.h.
Referenced by save_screenshot().
last_time
std::time_t openage::ScreenshotManager::last_time private
contains the last time when a screenshot was taken
Definition at line 45 of file screenshot.h.
Referenced by gen_next_filename().
window_size
coord::viewport_delta openage::ScreenshotManager::window_size
size of the game window, in coord_sdl
Definition at line 34 of file screenshot.h.
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/screenshot.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/screenshot.cpp