openage: openage::ProjectileProducer Class Reference
openage::ProjectileProducer Class Reference
#include <producer.h>
Public Member Functions
ProjectileProducer (const Player &owner, const GameSpec &spec, const gamedata::missile_unit *)
virtual ~ProjectileProducer ()
int id () const override
int parent_id () const override
std::string name () const override
void initialise (Unit *, Player &) override
TerrainObject * place (Unit *, std::shared_ptr< Terrain >, coord::phys3) const override
Public Member Functions inherited from openage::UnitType
UnitType ()
bool match (class Unit *)
UnitType (const Player &owner)
virtual ~UnitType ()
virtual void reinitialise (Unit *, Player &)
bool operator== (const UnitType &other) const
bool operator!= (const UnitType &other) const
UnitTexture * default_texture ()
TerrainObject * place_beside (Unit *, TerrainObject const *) const
void copy_attributes (Unit *unit) const
void upgrade (const std::shared_ptr< AttributeContainer > &attr)
UnitType * parent_type () const
Private Attributes
const gamedata::missile_unit unit_data
std::shared_ptr< Texture > terrain_outline
std::shared_ptr< UnitTexture > tex
std::shared_ptr< UnitTexture > sh
std::shared_ptr< UnitTexture > destroyed
Additional Inherited Members
Public Attributes inherited from openage::UnitType
const Player & owner
std::vector< UnitReference > instances
std::vector< std::shared_ptr< UnitAbility > > type_abilities
Attributes default_attributes
ResourceCost cost
int have_limit
int had_limit
graphic_set graphics
coord::tile_delta foundation_size
gamedata::unit_classes unit_class
Detailed Description
creates projectiles
Todo:
use MovableProducer as base class
Definition at line 149 of file producer.h.
Constructor & Destructor Documentation
ProjectileProducer()
openage::ProjectileProducer::ProjectileProducer (const Player & owner, const GameSpec & spec, const gamedata::missile_unit * pd)
Definition at line 790 of file producer.cpp.
     :
     UnitType(owner),
     unit_data{*pd},
     tex{spec.get_unit_texture(this->unit_data.graphic_standing0)},
     sh{spec.get_unit_texture(3379)}, // 3379 = general arrow shadow
     destroyed{spec.get_unit_texture(this->unit_data.dying_graphic)} {
     // copy the class type
     this->unit_class = this->unit_data.unit_class;
     // graphic set
     this->graphics[graphic_type::standing] = this->tex;
     this->graphics[graphic_type::shadow] = this->sh;
     if (destroyed) {
         this->graphics[graphic_type::dying] = destroyed;
     }
     // outline
     terrain_outline = radial_outline(pd->radius_y);
 }
References openage::owner.
~ProjectileProducer()
openage::ProjectileProducer::~ProjectileProducer () virtual
Definition at line 812 of file producer.cpp.
 {}
Member Function Documentation
id()
int openage::ProjectileProducer::id () const override virtual
gets the unique id of this unit type
Implements openage::UnitType.
Definition at line 814 of file producer.cpp.
{
     return this->unit_data.id0;
 }
References unit_data.
initialise()
void openage::ProjectileProducer::initialise (Unit * , Player &) override virtual
Initialize units attributes to this type spec
This can be called using existing units to modify type Ensure that the unit has been placed before seting the units type
Todo:
make const
Implements openage::UnitType.
Definition at line 826 of file producer.cpp.
{
     ENSURE(this->owner == player, "unit init from a UnitType of a wrong player which breaks tech levels");
     // initialize graphic set
     unit->unit_type = this;
     auto player_attr = std::make_shared<Attribute<attr_type::owner>>(player);
     unit->add_attribute(player_attr);
     // projectile speed
     coord::phys_t sp = this->unit_data.speed / 666;
     unit->add_attribute(std::make_shared<Attribute<attr_type::speed>>(sp));
     unit->add_attribute(std::make_shared<Attribute<attr_type::projectile>>(this->unit_data.projectile_arc));
     unit->add_attribute(std::make_shared<Attribute<attr_type::direction>>(coord::phys3_delta{ 1, 0, 0 }));
     // if destruction graphic is available
     if (this->destroyed) {
         unit->push_action(std::make_unique<DeadAction>(unit), true);
     }
 }
References openage::Unit::add_attribute(), destroyed, ENSURE, openage::UnitType::owner, openage::Unit::push_action(), unit_data, and openage::Unit::unit_type.
name()
std::string openage::ProjectileProducer::name () const override virtual
gets the name of the unit type being produced
Implements openage::UnitType.
Definition at line 822 of file producer.cpp.
{
     return this->unit_data.name;
 }
References unit_data.
Referenced by openage.util.fslike.path.Path::stem(), openage.util.fslike.path.Path::suffix(), and openage.util.fslike.path.Path::suffixes().
parent_id()
int openage::ProjectileProducer::parent_id () const override virtual
gets the parent id of this unit type which is used for village base and gather types
Implements openage::UnitType.
Definition at line 818 of file producer.cpp.
{
     return this->unit_data.id0;
 }
References unit_data.
place()
TerrainObject * openage::ProjectileProducer::place (Unit * , std::shared_ptr< Terrain > , coord::phys3) const override virtual
set unit in place – return if placement was successful
This should be used when initially creating a unit or when a unit is ungarrsioned from a building or object
Todo:
make const
Implements openage::UnitType.
Definition at line 847 of file producer.cpp.
{
     /*
      * radial base shape without collision checking
      */
     u->make_location<RadialObject>(this->unit_data.radius_y, this->terrain_outline);
     TerrainObject *obj_ptr = u->location.get();
     std::weak_ptr<Terrain> terrain_ptr = terrain;
     u->location->passable = [obj_ptr, u, terrain_ptr](const coord::phys3 &pos) -> bool {
         if (pos.up > 64000) {
             return true;
         }
         // avoid intersections with launcher
         Unit *launcher = nullptr;
         auto terrain = terrain_ptr.lock();
         if (u->has_attribute(attr_type::projectile)) {
             auto &pr_attr = u->get_attribute<attr_type::projectile>();
             if (pr_attr.launched && pr_attr.launcher.is_valid()) {
                 launcher = pr_attr.launcher.get();
             }
             else {
                 return true;
             }
         }
         else {
             return true;
         }
         // look at all tiles in the bases range
         for (coord::tile check_pos : tile_list(obj_ptr->get_range(pos, *terrain))) {
             TileContent *tc = terrain->get_data(check_pos);
             if (!tc) return false;
             // ensure no intersections with other objects
             for (auto obj_cmp : tc->obj) {
                 if (obj_ptr != obj_cmp &&
                     &obj_cmp->unit != launcher &&
                     obj_cmp->check_collisions() &&
                     obj_ptr->intersects(*obj_cmp, pos)) {
                     return false;
                 }
             }
         }
         return true;
     };
     u->location->draw = [u](const Engine &e) {
         u->draw(e);
     };
     // try to place the obj, it knows best whether it will fit.
     if (u->location->place(terrain, init_pos, object_state::placed_no_collision)) {
         return u->location.get();
     }
     return nullptr;
 }
References openage::Unit::get_attribute(), openage::Unit::location, openage::Unit::make_location(), openage::TileContent::obj, openage::placed_no_collision, openage::projectile, terrain_outline, openage::tile_list(), and unit_data.
Member Data Documentation
destroyed
std::shared_ptr<UnitTexture> openage::ProjectileProducer::destroyed private
Definition at line 165 of file producer.h.
Referenced by initialise().
sh
std::shared_ptr<UnitTexture> openage::ProjectileProducer::sh private
Definition at line 164 of file producer.h.
terrain_outline
std::shared_ptr<Texture> openage::ProjectileProducer::terrain_outline private
Definition at line 162 of file producer.h.
Referenced by place().
tex
std::shared_ptr<UnitTexture> openage::ProjectileProducer::tex private
Definition at line 163 of file producer.h.
unit_data
const gamedata::missile_unit openage::ProjectileProducer::unit_data private
Definition at line 161 of file producer.h.
Referenced by id(), initialise(), name(), parent_id(), and place().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/producer.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/producer.cpp