openage: openage::renderer::SDL Class Reference
openage::renderer::SDL Class Reference
A static SDL singleton manager. Used to lazily initialize SDL.
Public Member Functions
~SDL ()
Static Public Member Functions
static void make_available ()
Static Private Attributes
static SDL sdl
static bool inited = false
Detailed Description
A static SDL singleton manager. Used to lazily initialize SDL.
Definition at line 13 of file sdl_global.cpp.
Constructor & Destructor Documentation
~SDL()
openage::renderer::SDL::~SDL () inline
Definition at line 39 of file sdl_global.cpp.
            {
         if (SDL::inited) {
             IMG_Quit();
             SDL_Quit();
             log::log(MSG(info) << "Destroyed SDL global context");
         }
     }
References openage::log::info(), inited, openage::log::log(), and MSG.
Member Function Documentation
make_available()
static void openage::renderer::SDL::make_available () inline static
Definition at line 15 of file sdl_global.cpp.
{
         if (!inited) {
             if (SDL_Init(SDL_INIT_VIDEO) < 0) {
                 throw Error{MSG(err) << "SDL video initialization failed: " << SDL_GetError()};
             }
             // Initialize support for the PNG image formats, jpg bit: IMG_INIT_JPG
             int wanted_image_formats = IMG_INIT_PNG;
             int sdlimg_inited = IMG_Init(wanted_image_formats);
             if ((sdlimg_inited & wanted_image_formats) != wanted_image_formats) {
                 throw Error{MSG(err) << "Failed to initialize PNG support: " << IMG_GetError()};
             }
         }
         SDL::sdl = SDL();
         SDL_version version;
         SDL_GetVersion(&version);
         log::log(MSG(info) << "Initialized SDL " << uint32_t(version.major) << "." << uint32_t(version.minor) << "." << uint32_t(version.patch));
         SDL::inited = true;
     }
References openage::log::err(), openage::log::info(), inited, openage::log::log(), MSG, and sdl.
Referenced by openage::renderer::make_sdl_available().
Member Data Documentation
inited
bool openage::renderer::SDL::inited = false static private
Definition at line 50 of file sdl_global.cpp.
Referenced by make_available(), and ~SDL().
sdl
SDL openage::renderer::SDL::sdl static private
Definition at line 49 of file sdl_global.cpp.
Referenced by make_available().
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/sdl_global.cpp