openage: openage::renderer::Geometry Class Reference
openage::renderer::Geometry Class Reference abstract
A class representing geometry to be passed to a draw call.
#include <geometry.h>
Public Member Functions
virtual ~Geometry ()=default
geometry_t get_type () const
Returns the type of this geometry.
void update_verts (std::vector< uint8_t > const &verts)
virtual void update_verts_offset (std::vector< uint8_t > const &verts, size_t offset)=0
Protected Member Functions
Geometry (geometry_t type)
Initialize the geometry to a given type.
Private Attributes
geometry_t type
Detailed Description
A class representing geometry to be passed to a draw call.
Definition at line 23 of file geometry.h.
Constructor & Destructor Documentation
~Geometry()
virtual openage::renderer::Geometry::~Geometry () virtual default
Geometry()
openage::renderer::Geometry::Geometry (geometry_t type) explicit protected
Initialize the geometry to a given type.
Definition at line 9 of file geometry.cpp.
     : type(type) {}
Member Function Documentation
get_type()
geometry_t openage::renderer::Geometry::get_type () const
Returns the type of this geometry.
Definition at line 12 of file geometry.cpp.
{
     return this->type;
 }
References type.
Referenced by openage::renderer::opengl::GlGeometry::draw(), and openage::renderer::opengl::GlGeometry::update_verts_offset().
update_verts()
void openage::renderer::Geometry::update_verts (std::vector< uint8_t > const & verts)
In a meshed geometry, updates the vertex data. The size and type of the vertex data has to be the same as before. If the mesh is indexed, indices will stay the same.
Exceptions
if there is a size mismatch between the new and old vertex data
Definition at line 16 of file geometry.cpp.
{
     this->update_verts_offset(verts, 0);
 }
References update_verts_offset().
update_verts_offset()
virtual void openage::renderer::Geometry::update_verts_offset (std::vector< uint8_t > const & verts, size_t offset) pure virtual
In a meshed geometry, updates the vertex data starting from the offset-th vertex. The type of the vertex data has to be the same as it was on initializing the geometry. The size plus the offset cannot exceed the previous size of the vertex data. If the mesh is indexed, indices will stay the same.
Exceptions
if there is a size mismatch between the new and old vertex data
Implemented in openage::renderer::opengl::GlGeometry.
Referenced by update_verts().
Member Data Documentation
type
geometry_t openage::renderer::Geometry::type private
Definition at line 46 of file geometry.h.
Referenced by get_type().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/geometry.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/geometry.cpp