openage: openage::ResearchAbility Class Reference
openage::ResearchAbility Class Reference
#include <ability.h>
Public Member Functions
ResearchAbility (const Sound *s=nullptr)
ability_type type () override
bool can_invoke (Unit &to_modify, const Command &cmd) override
void invoke (Unit &to_modify, const Command &cmd, bool play_sound=false) override
Public Member Functions inherited from openage::UnitAbility
virtual ~UnitAbility ()
bool has_hitpoints (Unit &target)
bool is_damaged (Unit &target)
bool has_resource (Unit &target)
bool is_same_player (Unit &to_modify, Unit &target)
bool is_ally (Unit &to_modify, Unit &target)
bool is_enemy (Unit &to_modify, Unit &target)
Private Attributes
const Sound * sound
Additional Inherited Members
Static Public Member Functions inherited from openage::UnitAbility
static ability_set set_from_list (const std::vector< ability_type > &items)
Detailed Description
initiates a research
Definition at line 214 of file ability.h.
Constructor & Destructor Documentation
ResearchAbility()
openage::ResearchAbility::ResearchAbility (const Sound * s = nullptr)
Definition at line 192 of file ability.cpp.
     :
     sound{s} {
 }
Member Function Documentation
can_invoke()
bool openage::ResearchAbility::can_invoke (Unit & to_modify, const Command & cmd) override virtual
true if the paramaters allow an action to be performed
Implements openage::UnitAbility.
Definition at line 197 of file ability.cpp.
{
     if (to_modify.has_attribute(attr_type::owner) && cmd.has_research()) {
         auto &player = to_modify.get_attribute<attr_type::owner>().player;
         auto research = cmd.research();
         return research->can_start() &&
                player.can_deduct(research->type->get_research_cost().get(player));
     }
     return false;
 }
References openage::Unit::get_attribute(), openage::Unit::has_attribute(), openage::Command::has_research(), openage::owner, openage::research, and openage::Command::research().
invoke()
void openage::ResearchAbility::invoke (Unit & to_modify, const Command & cmd, bool play_sound = false) override virtual
applies command to a given unit
Implements openage::UnitAbility.
Definition at line 207 of file ability.cpp.
{
     if (play_sound && this->sound) {
         this->sound->play();
     }
     to_modify.push_action(std::make_unique<ResearchAction>(&to_modify, cmd.research()));
 }
References openage::Sound::play(), openage::Unit::push_action(), openage::Command::research(), and sound.
type()
ability_type openage::ResearchAbility::type () inline override virtual
Implements openage::UnitAbility.
Definition at line 218 of file ability.h.
{
         return ability_type::research;
     }
References openage::research.
Member Data Documentation
sound
const Sound* openage::ResearchAbility::sound private
Definition at line 227 of file ability.h.
Referenced by invoke().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/ability.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/ability.cpp