openage: openage::BuildAbility Class Reference
openage::BuildAbility Class Reference
villagers build new buildings
#include <ability.h>
Public Member Functions
BuildAbility (const Sound *s=nullptr)
ability_type type () override
bool can_invoke (Unit &to_modify, const Command &cmd) override
true if the paramaters allow an action to be performed
void invoke (Unit &to_modify, const Command &cmd, bool play_sound=false) override
applies command to a given unit
Public Member Functions inherited from openage::UnitAbility
virtual ~UnitAbility ()
bool has_hitpoints (Unit &target)
some common functions
bool is_damaged (Unit &target)
bool has_resource (Unit &target)
bool is_same_player (Unit &to_modify, Unit &target)
bool is_ally (Unit &to_modify, Unit &target)
bool is_enemy (Unit &to_modify, Unit &target)
Private Attributes
const Sound * sound
Additional Inherited Members
Static Public Member Functions inherited from openage::UnitAbility
static ability_set set_from_list (const std::vector< ability_type > &items)
set bits corresponding to abilities, useful for initialising an ability_set using a brace enclosed list
Detailed Description
villagers build new buildings
Definition at line 233 of file ability.h.
Constructor & Destructor Documentation
BuildAbility()
openage::BuildAbility::BuildAbility (const Sound * s = nullptr)
Definition at line 214 of file ability.cpp.
     :
     sound{s} {
 }
Member Function Documentation
can_invoke()
bool openage::BuildAbility::can_invoke (Unit & to_modify, const Command & cmd) override virtual
true if the paramaters allow an action to be performed
Implements openage::UnitAbility.
Definition at line 219 of file ability.cpp.
{
     if (cmd.has_unit()) {
         Unit *target = cmd.unit();
         return to_modify.location &&
                is_same_player(to_modify, *target) &&
                target->has_attribute(attr_type::building) &&
                target->get_attribute<attr_type::building>().completed < 1.0f;
     }
     return false;
 }
References openage::building, openage::Unit::get_attribute(), openage::Unit::has_attribute(), openage::Command::has_unit(), openage::UnitAbility::is_same_player(), openage::Unit::location, and openage::Command::unit().
invoke()
void openage::BuildAbility::invoke (Unit & to_modify, const Command & cmd, bool play_sound = false) override virtual
applies command to a given unit
Implements openage::UnitAbility.
Definition at line 230 of file ability.cpp.
{
     to_modify.log(MSG(dbg) << "invoke build action");
     if (play_sound && this->sound) {
         this->sound->play();
     }
     if (cmd.has_unit()) {
         to_modify.push_action(std::make_unique<BuildAction>(&to_modify, cmd.unit()->get_ref()));
     }
 }
References openage::log::dbg(), openage::Unit::get_ref(), openage::Command::has_unit(), openage::log::LogSource::log(), MSG, openage::Sound::play(), openage::Unit::push_action(), sound, and openage::Command::unit().
type()
ability_type openage::BuildAbility::type () inline override virtual
Implements openage::UnitAbility.
Definition at line 237 of file ability.h.
{
         return ability_type::build;
     }
References openage::build.
Member Data Documentation
sound
const Sound* openage::BuildAbility::sound private
Definition at line 246 of file ability.h.
Referenced by invoke().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/ability.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/ability.cpp