openage: openage::ResearchType Class Reference
openage::ResearchType Class Reference abstract
#include <research.h>
Public Member Functions
ResearchType (Player &owner)
virtual int id () const =0
virtual std::string name () const =0
virtual research_category category () const =0
std::shared_ptr< Research > initialise () const
int get_max_repeats () const
virtual unsigned int get_research_time () const =0
virtual ResourceCost get_research_cost () const =0
virtual void apply () const =0
Public Attributes
Player & owner
Detailed Description
Describes a research for a single player
The get_max_repeats (with a default value of 1) can allow for a research to be performed multiple types
Definition at line 39 of file research.h.
Constructor & Destructor Documentation
ResearchType()
openage::ResearchType::ResearchType (Player & owner)
Definition at line 9 of file research.cpp.
     :
     owner{owner} {
 }
References openage::owner, and owner.
Member Function Documentation
apply()
virtual void openage::ResearchType::apply () const pure virtual
Performs the modifications (eg. apply patch to the unit types)
Referenced by openage::Research::apply().
category()
virtual research_category openage::ResearchType::category () const pure virtual
Gets the research category of the research.
Referenced by openage::Research::apply().
get_max_repeats()
int openage::ResearchType::get_max_repeats () const inline
How many times it can be researched. All classic researches have a value of 1.
Definition at line 74 of file research.h.
 { return 1; }
Referenced by openage::Research::can_start(), and openage::Research::is_researched().
get_research_cost()
virtual ResourceCost openage::ResearchType::get_research_cost () const pure virtual
get_research_time()
virtual unsigned int openage::ResearchType::get_research_time () const pure virtual
id()
virtual int openage::ResearchType::id () const pure virtual
Gets the unique id of this research type.
initialise()
std::shared_ptr< Research > openage::ResearchType::initialise () const
Creates a single Research object. Must be called only once.
Definition at line 14 of file research.cpp.
{
     return std::make_shared<Research>(this);
 }
name()
virtual std::string openage::ResearchType::name () const pure virtual
Gets the name of the research.
Referenced by openage.util.fslike.path.Path::stem(), openage.util.fslike.path.Path::suffix(), and openage.util.fslike.path.Path::suffixes().
Member Data Documentation
owner
Player& openage::ResearchType::owner
The player who owns this research type
Definition at line 68 of file research.h.
Referenced by openage::Research::apply(), and ResearchType().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/research.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/research.cpp