openage: openage::curve::UnorderedMap< key_t, val_t > Class Template Reference
openage::curve::UnorderedMap< key_t, val_t > Class Template Reference
#include <map.h>
Classes
struct map_element
Public Types
using const_iterator = typename std::unordered_map< key_t, map_element >::const_iterator
Public Member Functions
std::optional< MapFilterIterator< key_t, val_t, UnorderedMap > > operator() (const time_t &, const key_t &) const
std::optional< MapFilterIterator< key_t, val_t, UnorderedMap > > at (const time_t &, const key_t &) const
MapFilterIterator< key_t, val_t, UnorderedMap > begin (const time_t &e=std::numeric_limits< time_t >::max()) const
MapFilterIterator< key_t, val_t, UnorderedMap > end (const time_t &e=std::numeric_limits< time_t >::max()) const
MapFilterIterator< key_t, val_t, UnorderedMap > insert (const time_t &birth, const key_t &, const val_t &)
MapFilterIterator< key_t, val_t, UnorderedMap > insert (const time_t &birth, const time_t &death, const key_t &key, const val_t &value)
MapFilterIterator< key_t, val_t, UnorderedMap > between (const time_t &start, const time_t &to) const
void birth (const time_t &, const key_t &)
void birth (const time_t &, const MapFilterIterator< val_t, val_t, UnorderedMap > &)
void kill (const time_t &, const key_t &)
void kill (const time_t &, const MapFilterIterator< val_t, val_t, UnorderedMap > &)
void clean (const time_t &)
void dump ()
Private Attributes
std::unordered_map< key_t, map_element > container
Detailed Description
template<typename key_t, typename val_t>
class openage::curve::UnorderedMap< key_t, val_t >
Map that keeps track of the lifetime of the contained elements. Make sure that no key is reused.
Definition at line 20 of file map.h.
Member Typedef Documentation
const_iterator
template<typename key_t, typename val_t> using openage::curve::UnorderedMap< key_t, val_t >::const_iterator = typename std::unordered_map<key_t, map_element>::const_iterator
Definition at line 41 of file map.h.
Member Function Documentation
at()
template<typename key_t , typename val_t > std::optional< MapFilterIterator< key_t, val_t, UnorderedMap< key_t, val_t > > > openage::curve::UnorderedMap< key_t, val_t >::at (const time_t & time, const key_t & key) const
Definition at line 94 of file map.h.
{
     auto e = this->container.find(key);
     if (e != this->container.end() and
         e->second.alive <= time and
         e->second.dead > time) {
         return MapFilterIterator<key_t, val_t, UnorderedMap<key_t, val_t>>(
             e,
             this,
             time,
             std::numeric_limits<time_t>::max()
         );
     } else {
         return {};
     }
 }
References openage::console::tests::max().
begin()
template<typename key_t , typename val_t > MapFilterIterator< key_t, val_t, UnorderedMap< key_t, val_t > > openage::curve::UnorderedMap< key_t, val_t >::begin (const time_t & e = std::numeric_limits<time_t>::max()) const
Definition at line 114 of file map.h.
{
     return MapFilterIterator<key_t, val_t, UnorderedMap<key_t, val_t>>(
         this->container.begin(),
         this,
         time,
         std::numeric_limits<time_t>::max());
 }
References openage::console::tests::max().
between()
template<typename key_t , typename val_t > MapFilterIterator< key_t, val_t, UnorderedMap< key_t, val_t > > openage::curve::UnorderedMap< key_t, val_t >::between (const time_t & start, const time_t & to) const
Definition at line 134 of file map.h.
{
     auto it = MapFilterIterator<key_t, val_t, UnorderedMap<key_t, val_t>>(
         this->container.begin(),
         this,
         from,
         to);
     if (!it.valid()) {
         ++it;
     }
     return it;
 }
birth() [1/2]
template<typename key_t , typename val_t > void openage::curve::UnorderedMap< key_t, val_t >::birth (const time_t & time, const key_t & key)
Definition at line 175 of file map.h.
{
     auto it = this->container.find(key);
     if (it != this->container.end()) {
         it->second.alive = time;
     }
 }
birth() [2/2]
template<typename key_t , typename val_t > void openage::curve::UnorderedMap< key_t, val_t >::birth (const time_t & time, const MapFilterIterator< val_t, val_t, UnorderedMap< key_t, val_t > > & it)
Definition at line 184 of file map.h.
{
     it->second.alive = time;
 }
clean()
template<typename key_t , typename val_t > void openage::curve::UnorderedMap< key_t, val_t >::clean (const time_t &)
Definition at line 206 of file map.h.
{
     // TODO save everything to a file and be happy.
 }
dump()
template<typename key_t, typename val_t> void openage::curve::UnorderedMap< key_t, val_t >::dump () inline
gdb helper method.
Definition at line 78 of file map.h.
                 {
         for (auto i : container) {
             std::cout << "Element: " << i.second.value << std::endl;;
         }
     }
References openage::curve::UnorderedMap< key_t, val_t >::container.
Referenced by openage.convert.texture.Texture::save().
end()
template<typename key_t , typename val_t > MapFilterIterator< key_t, val_t, UnorderedMap< key_t, val_t > > openage::curve::UnorderedMap< key_t, val_t >::end (const time_t & e = std::numeric_limits<time_t>::max()) const
Definition at line 124 of file map.h.
{
     return MapFilterIterator<key_t, val_t, UnorderedMap<key_t, val_t>>(
         this->container.end(),
         this,
         -std::numeric_limits<time_t>::max(),
         time);
 }
References openage::console::tests::max().
insert() [1/2]
template<typename key_t , typename val_t > MapFilterIterator< key_t, val_t, UnorderedMap< key_t, val_t > > openage::curve::UnorderedMap< key_t, val_t >::insert (const time_t & birth, const key_t & key, const val_t & value)
Definition at line 149 of file map.h.
{
     return this->insert(
         alive,
         std::numeric_limits<time_t>::max(),
         key,
         value);
 }
References openage::console::tests::max().
insert() [2/2]
template<typename key_t , typename val_t > MapFilterIterator< key_t, val_t, UnorderedMap< key_t, val_t > > openage::curve::UnorderedMap< key_t, val_t >::insert (const time_t & birth, const time_t & death, const key_t & key, const val_t & value)
Definition at line 161 of file map.h.
{
     map_element e(value, alive, dead);
     auto it = this->container.insert(std::make_pair(key, e));
     return MapFilterIterator<key_t, val_t, UnorderedMap<key_t, val_t>>(
         it.first,
         this,
         alive,
         dead);
 }
kill() [1/2]
template<typename key_t , typename val_t > void openage::curve::UnorderedMap< key_t, val_t >::kill (const time_t & time, const key_t & key)
Definition at line 191 of file map.h.
{
     auto it = this->container.find(key);
     if (it != this->container.end()) {
         it->second.dead = time;
     }
 }
kill() [2/2]
template<typename key_t , typename val_t > void openage::curve::UnorderedMap< key_t, val_t >::kill (const time_t & time, const MapFilterIterator< val_t, val_t, UnorderedMap< key_t, val_t > > & it)
Definition at line 200 of file map.h.
{
     it->second.dead = time;
 }
operator()()
template<typename key_t , typename val_t > std::optional< MapFilterIterator< key_t, val_t, UnorderedMap< key_t, val_t > > > openage::curve::UnorderedMap< key_t, val_t >::operator() (const time_t & time, const key_t & key) const
Definition at line 87 of file map.h.
{
     return this->at(time, key);
 }
Member Data Documentation
container
template<typename key_t, typename val_t> std::unordered_map<key_t, map_element> openage::curve::UnorderedMap< key_t, val_t >::container private
Data holder. Maps keys to map elements. Map elements themselves store when they are valid.
Definition at line 38 of file map.h.
Referenced by openage::curve::UnorderedMap< key_t, val_t >::dump().
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/curve/map.h