openage: openage::util::Timer Class Reference
openage::util::Timer Class Reference
#include <timer.h>
Public Member Functions
Timer (bool stopped=true)
void reset (bool stopped=true)
void stop ()
void start ()
time_nsec_t getval () const
time_nsec_t getandresetval ()
bool isstopped () const
Private Attributes
bool stopped
union {
time_nsec_t stoppedat
time_nsec_t starttime
};
Detailed Description
Time measurement class.
Definition at line 16 of file timer.h.
Constructor & Destructor Documentation
Timer()
openage::util::Timer::Timer (bool stopped = true)
creates the timer, in either stopped or running state.
Definition at line 10 of file timer.cpp.
{
     this->reset(stopped);
 }
References reset().
Member Function Documentation
getandresetval()
time_nsec_t openage::util::Timer::getandresetval ()
reads the current timer value, in nanoseconds, and resets the timer to zero (preserving started/stopped state).
Definition at line 45 of file timer.cpp.
{
     time_nsec_t result;
     if (this->stopped) {
         result = this->stoppedat;
         this->stoppedat = 0;
     }
     else {
         time_nsec_t now = timing::get_monotonic_time();
         result = now - this->starttime;
         this->starttime = now;
     }
     return result;
 }
References openage::timing::get_monotonic_time(), openage.testing.testing::result(), starttime, stopped, and stoppedat.
Referenced by openage::util::FrameCounter::frame().
getval()
time_nsec_t openage::util::Timer::getval () const
reads the current timer value, in nanoseconds.
Definition at line 37 of file timer.cpp.
{
     if (this->stopped) {
         return this->stoppedat;
     } else {
         return timing::get_monotonic_time() - this->starttime;
     }
 }
References openage::timing::get_monotonic_time(), starttime, stopped, and stoppedat.
Referenced by openage::GameSpec::initialize(), openage::Engine::loop(), and openage::run_game().
isstopped()
bool openage::util::Timer::isstopped () const
returns whether the timer is currently running.
Definition at line 61 of file timer.cpp.
{
     return this->stopped;
 }
References stopped.
reset()
void openage::util::Timer::reset (bool stopped = true)
resets the timer, in either stopped or running state.
Definition at line 14 of file timer.cpp.
{
     this->stopped = stopped;
     if (this->stopped) {
         this->stoppedat = 0;
     } else {
         this->starttime = timing::get_monotonic_time();
     }
 }
References openage::timing::get_monotonic_time(), starttime, stopped, and stoppedat.
Referenced by openage::Engine::loop(), and Timer().
start()
void openage::util::Timer::start ()
starts/unpauses the timer.
Definition at line 30 of file timer.cpp.
                   {
     if (this->stopped) {
         this->stopped = false;
         this->starttime = timing::get_monotonic_time() - this->stoppedat;
     }
 }
References openage::timing::get_monotonic_time(), starttime, stopped, and stoppedat.
Referenced by openage::GameSpec::initialize(), and openage::run_game().
stop()
void openage::util::Timer::stop ()
stops/pauses the timer.
Definition at line 23 of file timer.cpp.
                  {
     if (not stopped) {
         this->stopped = true;
         this->stoppedat = timing::get_monotonic_time() - this->starttime;
     }
 }
References openage::timing::get_monotonic_time(), starttime, stopped, and stoppedat.
Member Data Documentation
@1
union { ... }
starttime
time_nsec_t openage::util::Timer::starttime
while running, stores the time the timer is counting from
Definition at line 27 of file timer.h.
Referenced by getandresetval(), getval(), reset(), start(), and stop().
stopped
bool openage::util::Timer::stopped private
Definition at line 17 of file timer.h.
Referenced by getandresetval(), getval(), isstopped(), reset(), start(), and stop().
stoppedat
time_nsec_t openage::util::Timer::stoppedat
while paused, stores the current timer value
Definition at line 22 of file timer.h.
Referenced by getandresetval(), getval(), reset(), start(), and stop().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/timer.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/timer.cpp