openage: openage::audio::AudioManager Class Reference
openage::audio::AudioManager Class Reference
#include <audio_manager.h>
Public Member Functions
AudioManager (job::JobManager *job_manager, const std::string &device_name="")
~AudioManager ()
AudioManager (const AudioManager &)=delete
AudioManager (AudioManager &&)=delete
AudioManager & operator= (const AudioManager &)=delete
AudioManager & operator= (AudioManager &&)=delete
void load_resources (const std::vector< resource_def > &sound_files)
Sound get_sound (category_t category, int id)
void audio_callback (int16_t *stream, int length)
SDL_AudioSpec get_device_spec () const
job::JobManager * get_job_manager () const
bool is_available () const
Static Public Member Functions
static std::vector< std::string > get_devices ()
static std::vector< std::string > get_drivers ()
static std::string get_current_driver ()
Private Member Functions
void add_sound (std::shared_ptr< SoundImpl > sound)
void remove_sound (std::shared_ptr< SoundImpl > sound)
Private Attributes
bool available
job::JobManager * job_manager
std::string device_name
SDL_AudioSpec device_spec
SDL_AudioDeviceID device_id
std::unique_ptr< int32_t[]> mix_buffer
std::unordered_map< std::tuple< category_t, int >, std::shared_ptr< Resource > > resources
std::unordered_map< category_t, std::vector< std::shared_ptr< SoundImpl > > > playing_sounds
Friends
class Sound
Detailed Description
This class provides audio functionality for openage.
Definition at line 32 of file audio_manager.h.
Constructor & Destructor Documentation
AudioManager() [1/3]
openage::audio::AudioManager::AudioManager (job::JobManager * job_manager, const std::string & device_name = "")
Initializes the audio manager with the given device name. If the name is empty, the default device is used.
Definition at line 48 of file audio_manager.cpp.
     :
     available{false},
     job_manager{job_manager},
     device_name{device_name} {
     if (SDL_Init(SDL_INIT_AUDIO) < 0) {
         log::log(MSG(err)
                  << "SDL audio initialization failed: "
                  << SDL_GetError());
         return;
     } else {
         log::log(MSG(info) << "SDL audio subsystems initialized");
     }
     // set desired audio output format
     SDL_AudioSpec desired_spec;
     SDL_zero(desired_spec);
     desired_spec.freq = 48000;
     desired_spec.format = AUDIO_S16LSB;
     desired_spec.channels = 2;
     desired_spec.samples = 4096;
     desired_spec.userdata = this;
     // call back that is invoked once SDL needs the next chunk of data
     desired_spec.callback = [] (void *userdata, uint8_t *stream, int len) {
         AudioManager *audio_manager = static_cast<AudioManager*>(userdata);
         audio_manager->audio_callback(reinterpret_cast<int16_t*>(stream), len / 2);
     };
     // convert device name to valid parameter for sdl call
     // if the device name is empty, use a nullptr in order to indicate that the
     // default device should be used
     const char *c_device_name = device_name.empty() ?
                                 nullptr : device_name.c_str();
     // open audio playback device
     device_id = SDL_OpenAudioDevice(c_device_name, 0, &desired_spec,
                                     &device_spec, 0);
     // no device could be opened
     if (device_id == 0) {
         log::log(MSG(err) << "Error opening audio device: " << SDL_GetError());
         return;
     }
     // initialize playing sounds vectors
     using sound_vector = std::vector<std::shared_ptr<SoundImpl>>;
     playing_sounds.insert({category_t::GAME, sound_vector{}});
     playing_sounds.insert({category_t::INTERFACE, sound_vector{}});
     playing_sounds.insert({category_t::MUSIC, sound_vector{}});
     playing_sounds.insert({category_t::TAUNT, sound_vector{}});
     // create buffer for mixing
     this->mix_buffer = std::make_unique<int32_t[]>(
         4 * device_spec.samples * device_spec.channels
     );
     log::log(MSG(info) <<
              "Using audio device: "
              << (device_name.empty() ? "default" : device_name)
              << " [freq=" << device_spec.freq
              << ", format=" << device_spec.format
              << ", channels=" << static_cast<uint16_t>(device_spec.channels)
              << ", samples=" << device_spec.samples
              << "]");
     SDL_PauseAudioDevice(device_id, 0);
     this->available = true;
 }
~AudioManager()
openage::audio::AudioManager::~AudioManager ()
Definition at line 120 of file audio_manager.cpp.
{
     SDL_CloseAudioDevice(device_id);
 }
References device_id.
AudioManager() [2/3]
openage::audio::AudioManager::AudioManager (const AudioManager &) delete
AudioManager() [3/3]
openage::audio::AudioManager::AudioManager (AudioManager &&) delete
Member Function Documentation
add_sound()
void openage::audio::AudioManager::add_sound (std::shared_ptr< SoundImpl > sound) private
Definition at line 194 of file audio_manager.cpp.
{
     SDLDeviceLock lock{this->device_id};
     auto category = sound->get_category();
     auto &playing_list = this->playing_sounds.find(category)->second;
     // \todo probably check if sound already exists in playing list
     playing_list.push_back(sound);
 }
References device_id, lock, and playing_sounds.
Referenced by openage::audio::Sound::play(), and openage::audio::Sound::resume().
audio_callback()
void openage::audio::AudioManager::audio_callback (int16_t * stream, int length)
Called from the audio system once to request new data.
Definition at line 163 of file audio_manager.cpp.
{
     std::memset(mix_buffer.get(), 0, length*4);
     // iterate over all categories
     for (auto &entry : this->playing_sounds) {
         auto &playing_list = entry.second;
         // iterate over all sounds in one category
         for (size_t i = 0; i < playing_list.size(); i++) {
             auto &sound = playing_list[i];
             auto sound_finished = sound->mix_audio(mix_buffer.get(), length);
             // if the sound is finished,
             // it should be removed from the playing list
             if (sound_finished) {
                 util::vector_remove_swap_end(playing_list, i);
                 i--;
             }
         }
     }
     // write the mix buffer to the output stream and adjust volume
     for (int i = 0; i < length; i++) {
         auto value = mix_buffer[i]/256;
         if (value > 32767) {
             value = 32767;
         } else if (value < -32768) {
             value = -32768;
         }
         stream[i] = static_cast<int16_t>(value);
     }
 }
References mix_buffer, playing_sounds, and openage::util::vector_remove_swap_end().
get_current_driver()
std::string openage::audio::AudioManager::get_current_driver () static
Returns the name of the currently used driver.
Definition at line 248 of file audio_manager.cpp.
{
     const char *c_driver = SDL_GetCurrentAudioDriver();
     if (c_driver == nullptr) {
         return "";
     } else {
         return c_driver;
     }
 }
get_device_spec()
SDL_AudioSpec openage::audio::AudioManager::get_device_spec () const
Returns the currently used audio output format.
Definition at line 217 of file audio_manager.cpp.
{
     return this->device_spec;
 }
References device_spec.
get_devices()
std::vector< std::string > openage::audio::AudioManager::get_devices () static
Returns a vector of all available device names.
Definition at line 230 of file audio_manager.cpp.
{
     std::vector<std::string> device_list;
     auto num_devices = SDL_GetNumAudioDevices(0);
     for (int i = 0; i < num_devices; i++) {
         device_list.push_back(SDL_GetAudioDeviceName(i, 0));
     }
     return device_list;
 }
get_drivers()
std::vector< std::string > openage::audio::AudioManager::get_drivers () static
Returns a vector of all available driver names.
Definition at line 239 of file audio_manager.cpp.
{
     std::vector<std::string> driver_list;
     auto num_drivers = SDL_GetNumAudioDrivers();
     for (int i = 0; i < num_drivers; i++) {
         driver_list.push_back(SDL_GetAudioDriver(i));
     }
     return driver_list;
 }
get_job_manager()
job::JobManager * openage::audio::AudioManager::get_job_manager () const
Return the game engine the audio manager is attached to.
Definition at line 221 of file audio_manager.cpp.
{
     return this->job_manager;
 }
References job_manager.
Referenced by openage::audio::DynamicResource::use().
get_sound()
Sound openage::audio::AudioManager::get_sound (category_t category, int id)
Returns a sound object with the given category and the given id. If no such sound exists an Error will be thrown.
Parameters
category the sound's category
id the sound's id
Definition at line 142 of file audio_manager.cpp.
{
     if (not this->available) {
         throw error::Error{MSG(err) << "audio manager not available, "
                                     << "but sound was requested!"};
     }
     auto resource = resources.find(std::make_tuple(category, id));
     if (resource == std::end(resources)) {
         throw audio::Error{
             MSG(err) <<
             "Sound resource does not exist: "
             "category=" << category << ", " <<
             "id=" << id
         };
     }
     auto sound_impl = std::make_shared<SoundImpl>(resource->second);
     return Sound{this, sound_impl};
 }
References available, openage::log::err(), MSG, openage::resource, and resources.
Referenced by openage::Sound::play().
is_available()
bool openage::audio::AudioManager::is_available () const
If this audio manager is available. It's not available if
Definition at line 225 of file audio_manager.cpp.
{
     return this->available;
 }
References available.
Referenced by openage::audio::Sound::is_playing(), and openage::Sound::play().
load_resources()
void openage::audio::AudioManager::load_resources (const std::vector< resource_def > & sound_files)
Loads all audio resources, that are specified in the sound_files vector.
Parameters
sound_files a list of all sound resources
Definition at line 124 of file audio_manager.cpp.
{
     if (not this->available) {
         return;
     }
     for (auto &sound_file : sound_files) {
         auto key = std::make_tuple(sound_file.category, sound_file.id);
         if (this->resources.find(key) != std::end(this->resources)) {
             // sound is already loaded
             continue;
         }
         auto resource = Resource::create_resource(this, sound_file);
         this->resources.insert({key, resource});
     }
 }
References available, openage::audio::Resource::create_resource(), openage::resource, and resources.
Referenced by openage::GameSpec::on_gamedata_loaded().
operator=() [1/2]
AudioManager& openage::audio::AudioManager::operator= (const AudioManager &) delete
operator=() [2/2]
AudioManager& openage::audio::AudioManager::operator= (AudioManager &&) delete
remove_sound()
void openage::audio::AudioManager::remove_sound (std::shared_ptr< SoundImpl > sound) private
Definition at line 203 of file audio_manager.cpp.
{
     SDLDeviceLock lock{this->device_id};
     auto category = sound->get_category();
     auto &playing_list = this->playing_sounds.find(category)->second;
     for (size_t i = 0; i < playing_list.size(); i++) {
         if (playing_list[i] == sound) {
             util::vector_remove_swap_end(playing_list, i);
             break;
         }
     }
 }
References device_id, lock, playing_sounds, and openage::util::vector_remove_swap_end().
Referenced by openage::audio::Sound::pause(), and openage::audio::Sound::stop().
Friends And Related Function Documentation
Sound
friend class Sound friend
Definition at line 90 of file audio_manager.h.
Member Data Documentation
available
bool openage::audio::AudioManager::available private
If no audio device was found, this audio manager will be unavailable.
Definition at line 96 of file audio_manager.h.
Referenced by get_sound(), is_available(), and load_resources().
device_id
SDL_AudioDeviceID openage::audio::AudioManager::device_id private
the used audio device's id
Definition at line 116 of file audio_manager.h.
Referenced by add_sound(), remove_sound(), and ~AudioManager().
device_name
std::string openage::audio::AudioManager::device_name private
the used audio device's name
Definition at line 106 of file audio_manager.h.
device_spec
SDL_AudioSpec openage::audio::AudioManager::device_spec private
the audio output format
Definition at line 111 of file audio_manager.h.
Referenced by get_device_spec().
job_manager
job::JobManager* openage::audio::AudioManager::job_manager private
The job manager used in this audio manager for job queuing.
Definition at line 101 of file audio_manager.h.
Referenced by get_job_manager().
mix_buffer
std::unique_ptr<int32_t[]> openage::audio::AudioManager::mix_buffer private
Buffer used for mixing audio to one stream.
Definition at line 121 of file audio_manager.h.
Referenced by audio_callback().
playing_sounds
std::unordered_map<category_t,std::vector<std::shared_ptr<SoundImpl> > > openage::audio::AudioManager::playing_sounds private
Definition at line 125 of file audio_manager.h.
Referenced by add_sound(), audio_callback(), and remove_sound().
resources
std::unordered_map<std::tuple<category_t,int>,std::shared_ptr<Resource> > openage::audio::AudioManager::resources private
Definition at line 123 of file audio_manager.h.
Referenced by get_sound(), and load_resources().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/audio/audio_manager.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/audio/audio_manager.cpp