openage: openage::renderer::resources::Texture2dInfo Class Reference
openage::renderer::resources::Texture2dInfo Class Reference
Contains information about a 2D texture surface, without actual texture data.
#include <texture_info.h>
Public Member Functions
Texture2dInfo (size_t width, size_t height, pixel_format, size_t row_alignment=1, std::vector< Texture2dSubInfo > &&=std::vector< Texture2dSubInfo >())
Constructs a Texture2dInfo with the given information.
Texture2dInfo ()=default
Texture2dInfo (Texture2dInfo const &)=default
~Texture2dInfo ()=default
bool operator== (Texture2dInfo const &)
Compares the texture parameters excluding the subtexture information and returns true if they're equal, false otherwise.
bool operator!= (Texture2dInfo const &)
See operator==.
std::pair< int32_t, int32_t > get_size () const
Returns the dimensions of the whole texture bitmap.
pixel_format get_format () const
size_t get_row_alignment () const
Returns the alignment of texture rows to byte boundaries.
size_t get_row_size () const
Returns the size in bytes of a single row, including possible padding at its end.
size_t get_data_size () const
Returns the size in bytes of the raw pixel data.
size_t get_subtexture_count () const
Returns the number of available subtextures.
const Texture2dSubInfo & get_subtexture (size_t subid) const
Returns the coordinates of the subtexture with the given ID.
std::pair< int32_t, int32_t > get_subtexture_size (size_t subid) const
Returns the size of the subtexture with the given ID.
std::tuple< float, float, float, float > get_subtexture_coordinates (size_t subid) const
Returns atlas subtexture coordinates.
Private Attributes
int32_t w
Width and height of this texture.
int32_t h
pixel_format format
The pixel format of this texture.
size_t row_alignment
The alignment of texture rows to byte boundaries.
std::vector< Texture2dSubInfo > subtextures
Some textures are merged together into texture atlases, large images which contain more than one individual texture.
Detailed Description
Contains information about a 2D texture surface, without actual texture data.
The class supports subtextures, so that one big texture ("texture atlas") can contain several smaller images, which can be extracted for rendering one-by-one.
Definition at line 54 of file texture_info.h.
Constructor & Destructor Documentation
Texture2dInfo() [1/3]
openage::renderer::resources::Texture2dInfo::Texture2dInfo (size_t width, size_t height, pixel_format fmt, size_t row_alignment = 1, std::vector< Texture2dSubInfo > && subs = std::vector<Texture2dSubInfo>())
Constructs a Texture2dInfo with the given information.
Definition at line 10 of file texture_info.cpp.
     : w(width)
     , h(height)
     , format(fmt)
     , row_alignment(row_alignment)
     , subtextures(std::move(subs)) {}
References openage::move.
Texture2dInfo() [2/3]
openage::renderer::resources::Texture2dInfo::Texture2dInfo () default
Texture2dInfo() [3/3]
openage::renderer::resources::Texture2dInfo::Texture2dInfo (Texture2dInfo const &) default
~Texture2dInfo()
openage::renderer::resources::Texture2dInfo::~Texture2dInfo () default
Member Function Documentation
get_data_size()
size_t openage::renderer::resources::Texture2dInfo::get_data_size () const
Returns the size in bytes of the raw pixel data.
It is equal to get_row_size() * get_size().second.
Definition at line 53 of file texture_info.cpp.
{
     return this->get_row_size() * this->h;
 }
References get_row_size(), and h.
Referenced by openage::renderer::opengl::GlRenderer::display_into_data(), openage::renderer::opengl::GlTexture2d::into_data(), and openage::renderer::resources::Texture2dData::read_pixel().
get_format()
pixel_format openage::renderer::resources::Texture2dInfo::get_format () const
Returns
the format of pixels in this texture
Definition at line 32 of file texture_info.cpp.
{
     return this->format;
 }
References format.
Referenced by openage::renderer::opengl::GlTexture2dArray::GlTexture2dArray(), openage::renderer::opengl::GlTexture2d::into_data(), openage::renderer::resources::Texture2dData::read_pixel(), openage::renderer::resources::Texture2dData::store(), openage::renderer::opengl::GlTexture2d::upload(), and openage::renderer::opengl::GlTexture2dArray::upload().
get_row_alignment()
size_t openage::renderer::resources::Texture2dInfo::get_row_alignment () const
Returns the alignment of texture rows to byte boundaries.
Definition at line 36 of file texture_info.cpp.
{
     return this->row_alignment;
 }
References row_alignment.
Referenced by openage::renderer::opengl::GlTexture2d::into_data().
get_row_size()
size_t openage::renderer::resources::Texture2dInfo::get_row_size () const
Returns the size in bytes of a single row, including possible padding at its end.
Definition at line 40 of file texture_info.cpp.
{
     size_t px_size = pixel_size(this->format);
     size_t row_size = this->w * px_size;
     if (row_size % this->row_alignment != 0) {
         // Unaligned rows, have to add padding.
         size_t padding = this->row_alignment - (row_size % this->row_alignment);
         row_size += padding;
     }
     return row_size;
 }
References format, openage::renderer::resources::pixel_size(), row_alignment, and w.
Referenced by openage::renderer::resources::Texture2dData::flip_y(), get_data_size(), openage::renderer::resources::Texture2dData::read_pixel(), and openage::renderer::resources::Texture2dData::store().
get_size()
std::pair< int32_t, int32_t > openage::renderer::resources::Texture2dInfo::get_size () const
Returns the dimensions of the whole texture bitmap.
Returns
tuple(width, height)
Definition at line 28 of file texture_info.cpp.
{
     return std::make_pair(this->w, this->h);
 }
References h, and w.
Referenced by openage::renderer::resources::Texture2dData::flip_y(), openage::renderer::opengl::GlTexture2dArray::GlTexture2dArray(), openage::renderer::resources::Texture2dData::read_pixel(), openage.util.filelike.abstract.FileLikeObject::seek_helper(), openage::renderer::resources::Texture2dData::store(), openage::renderer::opengl::GlTexture2d::upload(), and openage::renderer::opengl::GlTexture2dArray::upload().
get_subtexture()
const Texture2dSubInfo & openage::renderer::resources::Texture2dInfo::get_subtexture (size_t subid) const
Returns the coordinates of the subtexture with the given ID.
Definition at line 61 of file texture_info.cpp.
{
     if (subid < this->subtextures.size()) {
         return this->subtextures[subid];
     }
     throw Error(MSG(err) << "Unknown subtexture requested: " << subid);
 }
References openage::log::err(), MSG, and subtextures.
Referenced by get_subtexture_coordinates(), and get_subtexture_size().
get_subtexture_coordinates()
std::tuple< float, float, float, float > openage::renderer::resources::Texture2dInfo::get_subtexture_coordinates (size_t subid) const
Returns atlas subtexture coordinates.
Returns
left, right, top and bottom bounds as coordinates these pick the requested area out of the big texture. returned as floats in range 0.0 to 1.0, relative to the whole surface size.
Definition at line 74 of file texture_info.cpp.
{
     auto tx = this->get_subtexture(subid);
     return std::make_tuple(
         ((float)tx.x)           / this->w,
         ((float)(tx.x + tx.w)) / this->w,
         ((float)tx.y)           / this->h,
         ((float)(tx.y + tx.h)) / this->h
     );
 }
References get_subtexture().
get_subtexture_count()
size_t openage::renderer::resources::Texture2dInfo::get_subtexture_count () const
Returns the number of available subtextures.
Definition at line 57 of file texture_info.cpp.
{
     return this->subtextures.size();
 }
References subtextures.
get_subtexture_size()
std::pair< int, int > openage::renderer::resources::Texture2dInfo::get_subtexture_size (size_t subid) const
Returns the size of the subtexture with the given ID.
Definition at line 69 of file texture_info.cpp.
{
     auto subtex = this->get_subtexture(subid);
     return std::make_pair(subtex.w, subtex.h);
 }
References get_subtexture().
operator!=()
bool openage::renderer::resources::Texture2dInfo::operator!= (Texture2dInfo const & other)
See operator==.
Definition at line 24 of file texture_info.cpp.
{
     return not (*this == other);
 }
operator==()
bool openage::renderer::resources::Texture2dInfo::operator== (Texture2dInfo const & other)
Compares the texture parameters excluding the subtexture information and returns true if they're equal, false otherwise.
Definition at line 17 of file texture_info.cpp.
{
     return other.w == this->w
     and other.h == this->h
     and other.format == this->format
     and other.row_alignment == this->row_alignment;
 }
References format, h, row_alignment, and w.
Member Data Documentation
format
pixel_format openage::renderer::resources::Texture2dInfo::format private
The pixel format of this texture.
Definition at line 109 of file texture_info.h.
Referenced by get_format(), get_row_size(), and operator==().
h
int32_t openage::renderer::resources::Texture2dInfo::h private
Definition at line 106 of file texture_info.h.
Referenced by get_data_size(), get_size(), and operator==().
row_alignment
size_t openage::renderer::resources::Texture2dInfo::row_alignment private
The alignment of texture rows to byte boundaries.
Can be 1, 2, 4 or 8. There is padding at the end of each row to match the alignment if the row size is not a multiple of the alignment.
Definition at line 114 of file texture_info.h.
Referenced by get_row_alignment(), get_row_size(), and operator==().
subtextures
std::vector<Texture2dSubInfo> openage::renderer::resources::Texture2dInfo::subtextures private
Some textures are merged together into texture atlases, large images which contain more than one individual texture.
These are their positions in the atlas.
Definition at line 118 of file texture_info.h.
Referenced by get_subtexture(), and get_subtexture_count().
w
int32_t openage::renderer::resources::Texture2dInfo::w private
Width and height of this texture.
Definition at line 106 of file texture_info.h.
Referenced by get_row_size(), get_size(), and operator==().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/resources/texture_info.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/resources/texture_info.cpp