openage: openage::util::filelike::FileLike Class Reference
openage::util::filelike::FileLike Class Reference abstract
#include <filelike.h>
Public Types
enum seek_t : int { seek_t::SET = 0, seek_t::CUR = 1, seek_t::END = 2 }
enum mode_t : int {
mode_t::R = 0, mode_t::W = 1, mode_t::RW = 2, mode_t::A = 3,
mode_t::AR = 4
}
Public Member Functions
FileLike ()
virtual ~FileLike ()=default
virtual std::string read (ssize_t max=-1)=0
virtual size_t read_to (void *buf, ssize_t max=-1)=0
virtual bool readable ()=0
virtual void write (const std::string &data)=0
virtual bool writable ()=0
virtual void seek (ssize_t offset, seek_t how=seek_t::SET)=0
virtual bool seekable ()=0
virtual size_t tell ()=0
virtual void close ()=0
virtual void flush ()=0
virtual ssize_t get_size ()=0
virtual bool is_python_native () const noexcept
virtual std::ostream & repr (std::ostream &)=0
Detailed Description
File-like class that has the standard operations like read, seek, write etc.
pxd: ctypedef enum seek_t "openage::util::filelike::FileLike::seek_t": seek_t_SET "::openage::util::filelike::FileLike::seek_t::SET" = 0 seek_t_CUR "::openage::util::filelike::FileLike::seek_t::CUR" = 1 seek_t_END "::openage::util::filelike::FileLike::seek_t::END" = 2
cppclass FileLike: string read(ssize_t max) except + bool readable() except + void write(const string &data) except + bool writable() except + void seek(ssize_t offset, seek_t how) except + bool seekable() except + size_t tell() except + void close() except + void flush() except + ssize_t get_size() except +
bool is_python_native() noexcept
Definition at line 41 of file filelike.h.
Member Enumeration Documentation
mode_t
enum openage::util::filelike::FileLike::mode_t : int strong
File access mode.
Sync the numbers with the fslike/cpp.pyx because Cython can't enum class yet.
Enumerator
R
W
RW
A
AR
Definition at line 64 of file filelike.h.
                       : int {
         R = 0,
         W = 1,
         RW = 2,
         A = 3,
         AR = 4,
     };
seek_t
enum openage::util::filelike::FileLike::seek_t : int strong
Seek reference point.
Don't change the numbers, they're used from Cython.
Enumerator
SET
offset from file beginning
CUR
offset from current position
END
offset from file end
Definition at line 48 of file filelike.h.
                       : int {
         SET = 0,
         CUR = 1,
         END = 2
     };
Constructor & Destructor Documentation
FileLike()
openage::util::filelike::FileLike::FileLike ()
Definition at line 10 of file filelike.cpp.
 {}
~FileLike()
virtual openage::util::filelike::FileLike::~FileLike () virtual default
Member Function Documentation
close()
virtual void openage::util::filelike::FileLike::close () pure virtual
Implemented in openage::util::filelike::Python, and openage::util::filelike::Native.
Referenced by openage.util.filelike.abstract.FileLikeObject::__exit__(), and openage.convert.slp_converter_pool.SLPConverterPool::__exit__().
flush()
virtual void openage::util::filelike::FileLike::flush () pure virtual
Implemented in openage::util::filelike::Python, and openage::util::filelike::Native.
get_size()
virtual ssize_t openage::util::filelike::FileLike::get_size () pure virtual
Implemented in openage::util::filelike::Python, and openage::util::filelike::Native.
Referenced by openage.util.filelike.abstract.FileLikeObject::seek_helper().
is_python_native()
bool openage::util::filelike::FileLike::is_python_native () const virtual noexcept
Reimplemented in openage::util::filelike::Python.
Definition at line 12 of file filelike.cpp.
{
     return false;
 }
read()
virtual std::string openage::util::filelike::FileLike::read (ssize_t max = -1) pure virtual
Implemented in openage::util::filelike::Python, and openage::util::filelike::Native.
Referenced by openage.convert.dataformat.exportable.Exportable::read(), and openage.convert.peresource.StringLiteral::readall().
read_to()
virtual size_t openage::util::filelike::FileLike::read_to (void * buf, ssize_t max = -1) pure virtual
Implemented in openage::util::filelike::Python, and openage::util::filelike::Native.
readable()
virtual bool openage::util::filelike::FileLike::readable () pure virtual
Implemented in openage::util::filelike::Python, and openage::util::filelike::Native.
repr()
virtual std::ostream& openage::util::filelike::FileLike::repr (std::ostream &) pure virtual
string representation of the filelike
Implemented in openage::util::filelike::Python, and openage::util::filelike::Native.
seek()
virtual void openage::util::filelike::FileLike::seek (ssize_t offset, seek_t how = seek_t::SET) pure virtual
Implemented in openage::util::filelike::Python, and openage::util::filelike::Native.
seekable()
virtual bool openage::util::filelike::FileLike::seekable () pure virtual
Implemented in openage::util::filelike::Python, and openage::util::filelike::Native.
tell()
virtual size_t openage::util::filelike::FileLike::tell () pure virtual
Implemented in openage::util::filelike::Python, and openage::util::filelike::Native.
Referenced by openage.util.filelike.abstract.FileLikeObject::seek_helper().
writable()
virtual bool openage::util::filelike::FileLike::writable () pure virtual
Implemented in openage::util::filelike::Python, and openage::util::filelike::Native.
Referenced by openage.util.fslike.wrapper.Wrapper::resolve_w(), and openage.util.fslike.abstract.FSLikeObject::resolve_w().
write()
virtual void openage::util::filelike::FileLike::write (const std::string & data) pure virtual
Implemented in openage::util::filelike::Python, and openage::util::filelike::Native.
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/filelike/filelike.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/filelike/filelike.cpp