openage: openage::renderer::GlyphAtlas Class Reference
openage::renderer::GlyphAtlas Class Reference
#include <glyph_atlas.h>
Classes
struct dirty_rect
class Entry
class Shelf
Public Member Functions
GlyphAtlas (int width=1024, int height=1024)
virtual ~GlyphAtlas ()
void bind (int unit=0)
GlyphAtlas::Entry get (Font *font, codepoint_t codepoint)
Private Member Functions
size_t get_cache_key (Font *font, codepoint_t codepoint) const
GlyphAtlas::Entry set (size_t key, const Glyph &glyph, const unsigned char *image)
void update_dirty_area (int x, int y, int width, int height)
Private Attributes
int width
int height
bool is_dirty
dirty_rect dirty_area
std::unique_ptr< unsigned char > buffer
unsigned int texture_id
std::unordered_map< size_t, GlyphAtlas::Entry > glyphs
std::vector< GlyphAtlas::Shelf > shelves
Detailed Description
A glyph atlas is used to pack and manage several font glyphs in to a single OpenGL texture.
A single glyph atlas can be used to stored glyphs from multiple fonts.
Currently, the glyph atlas uses a naive "Shelf First-Fit" algorithm based on the article "A Thousand Ways to Pack the Bin - A Practical Approach to Two-Dimensional Rectangle Bin Packing" by Jukka Jylänki. The article can be found at http://clb.demon.fi/files/RectangleBinPack.pdf
This is a very basic algorithm. If there is a need for a more complex packing requirement, the glyph atlas can be easily modified.
Definition at line 26 of file glyph_atlas.h.
Constructor & Destructor Documentation
GlyphAtlas()
openage::renderer::GlyphAtlas::GlyphAtlas (int width = 1024, int height = 1024)
Creates a glyph atlas with the specified width and height.
Also, creates a OpenGL texture of the same width and height. The contents of this glyph atlas is automatically synchronized to the texture (when you bind the texture).
Parameters
width The width of glyph atlas
height The height of glyph atlas
Definition at line 39 of file glyph_atlas.cpp.
     :
     width{width},
     height{height},
     is_dirty{false},
     dirty_area{width, height, 0, 0},
     texture_id{0} {
     this->buffer = std::unique_ptr<unsigned char>(new unsigned char[this->width * this->height]);
     memset(this->buffer.get(), 0, this->width * this->height);
     glGenTextures(1, &this->texture_id);
     glBindTexture(GL_TEXTURE_2D, this->texture_id);
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP);
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP);
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
     glTexImage2D(GL_TEXTURE_2D, 0, GL_RED, this->width, this->height, 0, GL_RED, GL_UNSIGNED_BYTE, this->buffer.get());
 }
References width.
~GlyphAtlas()
openage::renderer::GlyphAtlas::~GlyphAtlas () virtual
Definition at line 60 of file glyph_atlas.cpp.
{
     if (this->texture_id) {
         glDeleteTextures(1, &this->texture_id);
     }
 }
References texture_id.
Member Function Documentation
bind()
void openage::renderer::GlyphAtlas::bind (int unit = 0)
Binds the OpenGL texture of this glyph atlas at the specified unit.
Parameters
unit the texture unit.
Definition at line 66 of file glyph_atlas.cpp.
{
     glActiveTexture(GL_TEXTURE0 + unit);
     glBindTexture(GL_TEXTURE_2D, this->texture_id);
     if (this->is_dirty) {
         // We update the entire width of the atlas because of our buffer memory alignment
         glTexSubImage2D(GL_TEXTURE_2D, 0,
                         0, this->dirty_area.y1, this->width, this->dirty_area.y2 - this->dirty_area.y1,
                         GL_RED, GL_UNSIGNED_BYTE, this->buffer.get() + this->width * this->dirty_area.y1);
         this->is_dirty = false;
         this->dirty_area = {this->width, this->height, 0, 0};
     }
 }
References dirty_area, height, is_dirty, texture_id, width, and openage::renderer::GlyphAtlas::dirty_rect::y1.
Referenced by openage::renderer::TextRenderer::render().
get()
GlyphAtlas::Entry openage::renderer::GlyphAtlas::get (Font * font, codepoint_t codepoint)
Retrieves the atlas entry for a specified font and glyph.
If the particular entry does not exist in the atlas, the glyph atlas requests the font to provide the glyph info. The provided info along with the glyph's bitmap data is used to create a new cached entry. This entry is then returned.
Parameters
font The font
codepoint The glyph whose atlas entry must be retrieved
Returns
The atlas entry.
Definition at line 81 of file glyph_atlas.cpp.
{
     size_t key = this->get_cache_key(font, codepoint);
     auto it = this->glyphs.find(key);
     if (it != this->glyphs.end()) {
         return it->second;
     }
     Glyph glyph;
     std::unique_ptr<unsigned char[]> image = font->load_glyph(codepoint, glyph);
     return this->set(key, glyph, image.get());
 }
References openage::renderer::tests::font(), get_cache_key(), glyphs, and set().
Referenced by openage::renderer::TextRenderer::render().
get_cache_key()
size_t openage::renderer::GlyphAtlas::get_cache_key (Font * font, codepoint_t codepoint) const private
Definition at line 93 of file glyph_atlas.cpp.
{
     size_t hash = std::hash<std::type_index>()(std::type_index(typeid(openage::renderer::GlyphAtlas)));
     hash = openage::util::hash_combine(hash, std::hash<font_description>()(font->description));
     hash = openage::util::hash_combine(hash, std::hash<codepoint_t>()(codepoint));
     return hash;
 }
References openage::renderer::tests::font(), openage::util::hash(), and openage::util::hash_combine().
Referenced by get().
set()
GlyphAtlas::Entry openage::renderer::GlyphAtlas::set (size_t key, const Glyph & glyph, const unsigned char * image) private
Definition at line 100 of file glyph_atlas.cpp.
{
     // Give the glyphs a 1px padding in the atlas
     int required_width = glyph.width + 1;
     int required_height = glyph.height + 1;
     if (this->shelves.empty()) {
         this->shelves.emplace_back(0, this->width, required_height);
     }
     for (auto &shelf : this->shelves) {
         if (shelf.check_fits(required_width, required_height)) {
             int x_pos = shelf.reserve(required_width, required_height);
             int y_pos = shelf.y_position;
             // Create a new entry and insert it
             GlyphAtlas::Entry entry;
             entry.glyph = glyph;
             entry.u0 = static_cast<float>(x_pos)/this->width;
             entry.v0 = static_cast<float>(y_pos)/this->height;
             entry.u1 = static_cast<float>(x_pos + glyph.width)/this->width;
             entry.v1 = static_cast<float>(y_pos + glyph.height)/this->height;
             for (unsigned int i = 0; i < glyph.height; i++) {
                 memcpy(
                     this->buffer.get() + ((y_pos + i) * this->width + x_pos),
                     image + (i * glyph.width),
                     glyph.width * sizeof(unsigned char)
                 );
             }
             this->update_dirty_area(x_pos, y_pos, glyph.width, glyph.height);
             this->glyphs.emplace(key, entry);
             return entry;
         }
     }
     GlyphAtlas::Shelf last_shelf = this->shelves.back();
     if (this->height > (last_shelf.y_position + last_shelf.height + required_height)) {
         this->shelves.emplace_back(last_shelf.y_position + last_shelf.height, this->width, required_height);
         return this->set(key, glyph, image);
     }
     // TODO: figure out a clean way to resize the atlas
     throw Error(MSG(err) << "Not enough space in the atlas");
 }
References buffer, openage::log::err(), openage::renderer::GlyphAtlas::Entry::glyph, glyphs, openage::renderer::Glyph::height, openage::renderer::GlyphAtlas::Shelf::height, height, MSG, shelves, openage::renderer::GlyphAtlas::Entry::u0, openage::renderer::GlyphAtlas::Entry::u1, update_dirty_area(), openage::renderer::GlyphAtlas::Entry::v0, openage::renderer::GlyphAtlas::Entry::v1, openage::renderer::Glyph::width, width, and openage::renderer::GlyphAtlas::Shelf::y_position.
Referenced by get().
update_dirty_area()
void openage::renderer::GlyphAtlas::update_dirty_area (int x, int y, int width, int height) private
Definition at line 147 of file glyph_atlas.cpp.
{
     this->is_dirty = true;
     this->dirty_area = {
         std::min(this->dirty_area.x1, x),
         std::min(this->dirty_area.y1, y),
         std::max(this->dirty_area.x2, x + width),
         std::max(this->dirty_area.y2, y + height)};
 }
References dirty_area, height, is_dirty, std::max(), std::min(), width, openage::renderer::GlyphAtlas::dirty_rect::x1, openage::renderer::GlyphAtlas::dirty_rect::x2, openage::renderer::GlyphAtlas::dirty_rect::y1, and openage::renderer::GlyphAtlas::dirty_rect::y2.
Referenced by set().
Member Data Documentation
buffer
std::unique_ptr<unsigned char> openage::renderer::GlyphAtlas::buffer private
Definition at line 121 of file glyph_atlas.h.
Referenced by set().
dirty_area
dirty_rect openage::renderer::GlyphAtlas::dirty_area private
Definition at line 118 of file glyph_atlas.h.
Referenced by bind(), and update_dirty_area().
glyphs
std::unordered_map<size_t, GlyphAtlas::Entry> openage::renderer::GlyphAtlas::glyphs private
Definition at line 128 of file glyph_atlas.h.
Referenced by get(), and set().
height
int openage::renderer::GlyphAtlas::height private
Definition at line 111 of file glyph_atlas.h.
Referenced by openage.convert.texture.Texture::__init__(), bind(), openage::renderer::GlyphAtlas::Shelf::check_fits(), set(), and update_dirty_area().
is_dirty
bool openage::renderer::GlyphAtlas::is_dirty private
Definition at line 114 of file glyph_atlas.h.
Referenced by bind(), and update_dirty_area().
shelves
std::vector<GlyphAtlas::Shelf> openage::renderer::GlyphAtlas::shelves private
Definition at line 131 of file glyph_atlas.h.
Referenced by set().
texture_id
unsigned int openage::renderer::GlyphAtlas::texture_id private
Definition at line 124 of file glyph_atlas.h.
Referenced by bind(), and ~GlyphAtlas().
width
int openage::renderer::GlyphAtlas::width private
Definition at line 108 of file glyph_atlas.h.
Referenced by openage.convert.texture.Texture::__init__(), bind(), GlyphAtlas(), openage::renderer::GlyphAtlas::Shelf::reserve(), set(), and update_dirty_area().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/font/glyph_atlas.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/font/glyph_atlas.cpp