openage: openage::util::compress::HuffmanTable< maxsymbols_p, tablebits_p, allow_empty > Class Template Reference
openage::util::compress::HuffmanTable< maxsymbols_p, tablebits_p, allow_empty > Class Template Reference
Public Member Functions
HuffmanTable (class LZXDStream *lzx)
int read_sym ()
void make_decode_table ()
void read_lengths (unsigned int first, unsigned int last)
Public Attributes
unsigned char len [maxsymbols_p+LZX_LENTABLE_SAFETY]
uint16_t table [(1<< tablebits_p)+(maxsymbols_p *2)]
bool is_empty
Static Public Attributes
static constexpr unsigned int HUFF_MAXBITS = 16
static constexpr unsigned int maxsymbols = maxsymbols_p
static constexpr unsigned int tablebits = tablebits_p
Private Member Functions
bool try_make_decode_table ()
Private Attributes
class LZXDStream * lzx
Detailed Description
template<unsigned int maxsymbols_p, unsigned int tablebits_p, bool allow_empty = false>
class openage::util::compress::HuffmanTable< maxsymbols_p, tablebits_p, allow_empty >
Definition at line 94 of file lzxd.cpp.
Constructor & Destructor Documentation
HuffmanTable()
template<unsigned int maxsymbols_p, unsigned int tablebits_p, bool allow_empty = false> openage::util::compress::HuffmanTable< maxsymbols_p, tablebits_p, allow_empty >::HuffmanTable (class LZXDStream * lzx) inline
Definition at line 123 of file lzxd.cpp.
 : lzx{lzx}, is_empty{true} {}
Member Function Documentation
make_decode_table()
template<unsigned int maxsymbols_p, unsigned int tablebits_p, bool allow_empty> void openage::util::compress::HuffmanTable< maxsymbols_p, tablebits_p, allow_empty >::make_decode_table ()
calls try_make_decode_table, and, if allow_empty is false, raises an exception on failure. builds a huffman lookup table from code lengths.
Definition at line 259 of file lzxd.cpp.
{
     if (this->try_make_decode_table()) {
         this->is_empty = false;
     } else {
         if (allow_empty) {
             // allow an empty tree, but don't decode symbols with it
             // if any of the symbols has a greater-than-zero length, fail.
             for (unsigned int i = 0; i < maxsymbols; i++) {
                 if (unlikely(this->len[i] > 0)) {
                     throw Error(MSG(err) << "failed to build HuffmanTable<allow_empty=true>");
                 }
             }
             this->is_empty = true;
         } else {
             throw Error(MSG(err) << "failed to build HuffmanTable<allow_empty=false>");
         }
     }
 }
Referenced by openage::util::compress::LZXDStream::init_next_block().
read_lengths()
template<unsigned int maxsymbols_p, unsigned int tablebits_p, bool allow_empty> void openage::util::compress::HuffmanTable< maxsymbols_p, tablebits_p, allow_empty >::read_lengths (unsigned int first, unsigned int last)
reads in code lengths for symbols first to last in the given table. The code lengths are stored in their own special LZX way.
Definition at line 363 of file lzxd.cpp.
{
     // bit buffer and huffman symbol decode variables
     unsigned int x, y;
     int z;
     // read lengths for pretree (20 symbols, lengths stored in fixed 4 bits)
     for (x = 0; x < 20; x++) {
         lzx->htpre.len[x] = lzx->bits.read_bits(4);
     }
     lzx->htpre.make_decode_table();
     for (x = first; x < last; ) {
         z = lzx->htpre.read_sym();
         if (z == 17) {
             // code = 17, run of ([read 4 bits]+4) zeros
             y = lzx->bits.read_bits(4);
             y += 4;
             while (y--) {
                 len[x++] = 0;
             }
         }
         else if (z == 18) {
             // code = 18, run of ([read 5 bits]+20) zeros
             y = lzx->bits.read_bits(5);
             y += 20;
             while (y--) {
                 len[x++] = 0;
             }
         }
         else if (z == 19) {
             // code = 19, run of ([read 1 bit]+4) [read huffman symbol]
             y = lzx->bits.read_bits(1);
             y += 4;
             z = lzx->htpre.read_sym();
             z = len[x] - z;
             if (z < 0) {
                 z += 17;
             }
             while (y--) {
                 len[x++] = z;
             }
         }
         else {
             // code = 0 to 16, delta current length entry
             z = len[x] - z; if (z < 0) z += 17;
             len[x++] = z;
         }
     }
 }
Referenced by openage::util::compress::LZXDStream::init_next_block().
read_sym()
template<unsigned int maxsymbols_p, unsigned int tablebits_p, bool allow_empty> int openage::util::compress::HuffmanTable< maxsymbols_p, tablebits_p, allow_empty >::read_sym ()
Decodes the next huffman symbol from the input bitstream, and returns it. Do not use this function on a table unless build_decode_table() succeeded.
Definition at line 240 of file lzxd.cpp.
{
     lzx->bits.ensure_bits(HUFF_MAXBITS);
     uint16_t sym = table[lzx->bits.peek_bits(tablebits)];
     unsigned i = 1 << (sizeof(lzx->bits.bit_buffer) * 8 - tablebits);
     while (sym >= maxsymbols) {
         // huff_traverse
         if (unlikely((i >>= 1) == 0)) {
             throw Error(MSG(err) << "huff_error in huff_traverse");
         }
         sym = table[(sym << 1) | ((lzx->bits.bit_buffer & i) ? 1 : 0)];
     }
     lzx->bits.remove_bits(len[sym]);
     return sym;
 }
Referenced by openage::util::compress::LZXDStream::decode_symbol_from_aligned_block(), and openage::util::compress::LZXDStream::decode_symbol_from_verbatim_block().
try_make_decode_table()
template<unsigned int maxsymbols_p, unsigned int tablebits_p, bool allow_empty> bool openage::util::compress::HuffmanTable< maxsymbols_p, tablebits_p, allow_empty >::try_make_decode_table () private
This function was originally coded by David Tritscher. It builds a fast huffman decoding table from a canonical huffman code lengths table.
Definition at line 281 of file lzxd.cpp.
{
     uint16_t sym, next_symbol;
     unsigned int leaf, fill;
     unsigned char bit_num;
     unsigned int pos = 0; // the current position in the decode table
     unsigned int table_mask = 1 << tablebits;
     unsigned int bit_mask = table_mask >> 1; // don't do 0 length codes
     // fill entries for codes short enough for a direct mapping
     for (bit_num = 1; bit_num <= tablebits; bit_num++) {
         for (sym = 0; sym < maxsymbols; sym++) {
             if (len[sym] != bit_num) {
                 continue;
             }
             leaf = pos;
             if ((pos += bit_mask) > table_mask) {
                 return false; // table overrun
             }
             // fill all possible lookups of this symbol with the symbol itself
             for (fill = bit_mask; fill-- > 0;) {
                 table[leaf++] = sym;
             }
         }
         bit_mask >>= 1;
     }
     // exit with success if table is now complete
     if (pos == table_mask) {
         return true;
     }
     // mark all remaining table entries as unused
     for (sym = pos; sym < table_mask; sym++) {
         table[sym] = 0xFFFF;
     }
     // next_symbol = base of allocation for long codes
     next_symbol = ((table_mask >> 1) < maxsymbols) ? maxsymbols : (table_mask >> 1);
     // give ourselves room for codes to grow by up to 16 more bits.
     // codes now start at bit (tablebits + 16) and end at (tablebits + 16 - codelength)
     pos <<= 16;
     table_mask <<= 16;
     bit_mask = 1 << 15;
     for (bit_num = tablebits + 1; bit_num <= HUFF_MAXBITS; bit_num++) {
         for (sym = 0; sym < maxsymbols; sym++) {
             if (len[sym] != bit_num) {
                 continue;
             }
             leaf = pos >> 16;
             for (fill = 0; fill < (bit_num - tablebits); fill++) {
                 // if this path hasn't been taken yet, 'allocate' two entries
                 if (table[leaf] == 0xFFFF) {
                         table[(next_symbol << 1) + 0] = 0xFFFF;
                         table[(next_symbol << 1) + 1] = 0xFFFF;
                         table[leaf] = next_symbol++;
                 }
                 // follow the path and select either left or right for next bit
                 leaf = table[leaf] << 1;
                 if ((pos >> (15-fill)) & 1) leaf++;
             }
             table[leaf] = sym;
             if ((pos += bit_mask) > table_mask) {
                 // table overflow
                 return false;
             }
         }
         bit_mask >>= 1;
     }
     // full table?
     return pos == table_mask;
 }
Member Data Documentation
HUFF_MAXBITS
template<unsigned int maxsymbols_p, unsigned int tablebits_p, bool allow_empty = false> constexpr unsigned int openage::util::compress::HuffmanTable< maxsymbols_p, tablebits_p, allow_empty >::HUFF_MAXBITS = 16 static
Definition at line 99 of file lzxd.cpp.
is_empty
template<unsigned int maxsymbols_p, unsigned int tablebits_p, bool allow_empty = false> bool openage::util::compress::HuffmanTable< maxsymbols_p, tablebits_p, allow_empty >::is_empty
the table could not be constructed and is empty (try_make_decode_table failed). this will lead to errors, should read_sym() be called.
Definition at line 121 of file lzxd.cpp.
Referenced by openage::util::compress::LZXDStream::decode_symbol_from_aligned_block(), openage::util::compress::LZXDStream::decode_symbol_from_verbatim_block(), and openage::util::compress::LZXDStream::init_next_block().
len
template<unsigned int maxsymbols_p, unsigned int tablebits_p, bool allow_empty = false> unsigned char openage::util::compress::HuffmanTable< maxsymbols_p, tablebits_p, allow_empty >::len[maxsymbols_p+LZX_LENTABLE_SAFETY]
table of code lengths (in bits) for each symbol
Definition at line 106 of file lzxd.cpp.
Referenced by openage::util::compress::LZXDStream::init_next_block(), and openage::util::compress::LZXDStream::reset_state().
lzx
template<unsigned int maxsymbols_p, unsigned int tablebits_p, bool allow_empty = false> class LZXDStream* openage::util::compress::HuffmanTable< maxsymbols_p, tablebits_p, allow_empty >::lzx private
Definition at line 96 of file lzxd.cpp.
Referenced by openage::util::compress::HuffmanTable< LZX_PRETREE_MAXSYMBOLS, LZX_PRETREE_TABLEBITS >::HuffmanTable().
maxsymbols
template<unsigned int maxsymbols_p, unsigned int tablebits_p, bool allow_empty = false> constexpr unsigned int openage::util::compress::HuffmanTable< maxsymbols_p, tablebits_p, allow_empty >::maxsymbols = maxsymbols_p static
Definition at line 100 of file lzxd.cpp.
table
template<unsigned int maxsymbols_p, unsigned int tablebits_p, bool allow_empty = false> uint16_t openage::util::compress::HuffmanTable< maxsymbols_p, tablebits_p, allow_empty >::table[(1<< tablebits_p)+(maxsymbols_p *2)]
table to fill up with decoded values for symbols, and pointers. symbols shorter than tablebits_p are decoded by direct lookup (that's the first (1<<tablebits_p) entries). longer symbols are decoded by following pointers to the appropriate leaf in the upper nsyms*2 fields.
Definition at line 115 of file lzxd.cpp.
tablebits
template<unsigned int maxsymbols_p, unsigned int tablebits_p, bool allow_empty = false> constexpr unsigned int openage::util::compress::HuffmanTable< maxsymbols_p, tablebits_p, allow_empty >::tablebits = tablebits_p static
Definition at line 101 of file lzxd.cpp.
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/compress/lzxd.cpp