openage: openage::Engine Class Reference
openage::Engine Class Reference
main engine container.
#include <engine.h>
Public Member Functions
Engine (const util::Path &root_dir, int32_t fps_limit, bool gl_debug, const char *windowtitle)
engine initialization method.
Engine (const Engine &copy)=delete
engine copy constructor.
Engine & operator= (const Engine &copy)=delete
engine assignment operator.
Engine (Engine &&other)=delete
engine move constructor.
Engine & operator= (Engine &&other)=delete
engine move operator.
virtual ~Engine ()
engine destructor, cleans up memory etc.
void run ()
starts the engine loop.
void stop ()
enqueues the stop of the main loop.
bool on_resize (coord::viewport_delta new_size) override
window resize handler function.
void start_game (const Generator &generator)
Start a game with the given game generator.
void start_game (std::unique_ptr< GameMain > &&game)
Start a game with the given initialized game.
void end_game ()
Stop the running game.
void save_screenshot (const char *filename)
draw the current frames per second number on screen.
bool draw_debug_overlay ()
Draw the game version and the current FPS on screen.
void register_input_action (InputHandler *handler)
register a new input event handler, run for each input event.
void register_tick_action (TickHandler *handler)
register a tick action, executed upon engine tick.
void register_drawhud_action (HudHandler *handler)
register a hud drawing handler, drawn in hud coordinates.
void register_draw_action (DrawHandler *handler)
register a draw handler, run in game coordinates.
void register_resize_action (ResizeHandler *handler)
register a resize handler, run when the window size changes.
const util::Path & get_root_dir ()
return the data directory where the engine was started from.
GameMain * get_game ()
return currently running game or null if a game is not currently running
job::JobManager * get_job_manager ()
return this engine's job manager.
audio::AudioManager & get_audio_manager ()
return this engine's audio manager.
ScreenshotManager & get_screenshot_manager ()
return this engine's screenshot manager.
input::ActionManager & get_action_manager ()
return this engine's action manager.
cvar::CVarManager & get_cvar_manager ()
return this engine's cvar manager.
input::InputManager & get_input_manager ()
return this engine's keybind manager.
UnitSelection * get_unit_selection ()
return this engine's unit selection.
void announce_global_binds ()
send keybindings help string to gui.
renderer::TextRenderer * get_text_renderer ()
return this engine's text renderer.
time_nsec_t lastframe_duration_nsec () const
return the number of nanoseconds that have passed for rendering the last frame.
void render_text (coord::viewport position, size_t size, const char *format,...) ATTRIBUTE_FORMAT(4
render text with the at a position with specified font size
void void move_phys_camera (float x, float y, float amount=1.0)
move the phys3 camera incorporated in the engine
Public Member Functions inherited from openage::ResizeHandler
virtual ~ResizeHandler ()=default
Public Member Functions inherited from openage::options::OptionNode
OptionNode (const std::string &panel_name)
virtual ~OptionNode ()
std::vector< std::string > list_options (bool recurse=false, std::string indent="")
lists all available options in a readable format
std::vector< std::string > list_variables () const
shows all available variable names
std::vector< std::string > list_functions () const
shows all the available function names
OptionValue & get_variable_rw (const std::string &name)
const OptionValue & get_variable (const std::string &name) const
template<class T >
const T & getv (const std::string &name)
shortcut for get_variable(name).value<T>()
OptionNode * get_child (const std::string &name) const
return a child by name, or null if not available
void set_parent (OptionNode *parent)
Set a parent panel which implies adding a child to the parent.
OptionValue do_action (const std::string &aname)
performs the named action returning the actions response
Public Attributes
bool running
current engine state variable.
options::Var< bool > drawing_debug_overlay
FPS and game version are drawn when this is true.
options::Var< bool > drawing_huds
this allows to disable drawing of every registered hud.
util::ExternalProfiler external_profiler
profiler used by the engine
coord::CoordManager coord
this engine's coordinate manager.
EngineSignals gui_signals
Signal emitting capability for the engine.
gui::GuiItemLink * gui_link
Link to the Qt GUI.
Public Attributes inherited from openage::options::OptionNode
const std::string name
name of this node
Private Member Functions
void loop ()
main engine loop function.
Private Attributes
util::Path root_dir
The engine root directory.
time_nsec_t ns_per_frame
how many nanoseconds are in a frame (1e9 / fps_limit).
std::vector< InputHandler * > on_input_event
input event processor objects.
std::vector< TickHandler * > on_engine_tick
run on every engine tick, after input handling, before rendering
std::vector< DrawHandler * > on_drawgame
run every time the game is being drawn, with the renderer set to the camgame system
std::vector< HudHandler * > on_drawhud
run every time the hud is being drawn, with the renderer set to the camhud system
std::vector< ResizeHandler * > on_resize_handler
list of handlers that are executed upon a resize event.
std::unique_ptr< GameMain > game
the currently running game
job::JobManager job_manager
the engine's job manager, for asynchronous background task queuing.
gui::EngineQMLInfo qml_info
This stores information to be accessible from the QML engine.
util::FrameCounter fps_counter
the frame counter measuring fps.
ScreenshotManager screenshot_manager
the engine's screenshot manager.
cvar::CVarManager cvar_manager
the engine's cvar manager.
input::ActionManager action_manager
the engine's action manager.
audio::AudioManager audio_manager
the engine's audio manager.
input::InputManager input_manager
the engine's keybind manager.
std::unique_ptr< UnitSelection > unit_selection
the engine's unit selection.
std::unordered_map< int, renderer::Font * > fonts
the text fonts to be used for (can you believe it?) texts.
SDL_Window * window
SDL window where everything is displayed within.
SDL_GLContext glcontext
SDL OpenGL context, we'll only have one, but it would allow having multiple ones.
std::unique_ptr< gui::GUI > gui
the gui binding
util::Profiler profiler
the engines profiler
std::unique_ptr< renderer::FontManager > font_manager
ttf font loading manager
std::unique_ptr< renderer::TextRenderer > text_renderer
2d text renderer
std::unique_ptr< log::FileSink > logsink_file
Logsink to store messages to the filesystem.
Friends
class GameMain
Additional Inherited Members
Protected Member Functions inherited from openage::options::OptionNode
void add (const std::string &vname, const OptionValue &value)
add types to the interface
void add_action (const OptionAction &action)
Detailed Description
main engine container.
central foundation for everything the openage engine is capable of.
pxd:
cppclass Engine:
InputManager &get_input_manager() except +
CVarManager &get_cvar_manager() except +
CoordManager coord
Definition at line 88 of file engine.h.
Constructor & Destructor Documentation
Engine() [1/3]
openage::Engine::Engine (const util::Path & root_dir, int32_t fps_limit, bool gl_debug, const char * windowtitle)
engine initialization method.
opens a window and initializes the OpenGL context.
Definition at line 39 of file engine.cpp.
     :
     OptionNode{"Engine"},
     running{false},
     drawing_debug_overlay{this, "drawing_debug_overlay", true},
     drawing_huds{this, "drawing_huds", true},
     root_dir{root_dir},
     job_manager{SDL_GetCPUCount()},
     qml_info{this, root_dir["assets"]},
     screenshot_manager{&this->job_manager},
     cvar_manager{root_dir["cfg"]},
     action_manager{&this->input_manager, &this->cvar_manager},
     audio_manager{&this->job_manager},
     input_manager{&this->action_manager},
     profiler{this},
     gui_link{} {
     if (fps_limit > 0) {
         this->ns_per_frame = 1e9 / fps_limit;
     } else {
         this->ns_per_frame = 0;
     }
     this->font_manager = std::make_unique<renderer::FontManager>();
     for (uint32_t size : {12, 20}) {
         fonts[size] = this->font_manager->get_font("DejaVu Serif", "Book", size);
     }
     // temporary log to the filesystem.
     // some housekeeping should be implemented as this file is only ever appended to
     this->logsink_file = std::make_unique<log::FileSink>("/tmp/openage-log", true);
     // enqueue the engine's own input handler to the
     // execution list.
     this->register_resize_action(this);
     if (SDL_Init(SDL_INIT_VIDEO) < 0) {
         throw Error(MSG(err) << "SDL video initialization: " << SDL_GetError());
     } else {
         log::log(MSG(info) << "Initialized SDL video subsystems.");
     }
     SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 2);
     SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 1);
     SDL_GL_SetAttribute(SDL_GL_ACCELERATED_VISUAL, 1);
     SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 1);
     SDL_GL_SetAttribute(SDL_GL_STENCIL_SIZE, 8);
     SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE, 24);
     int32_t window_flags = SDL_WINDOW_OPENGL | SDL_WINDOW_RESIZABLE | SDL_WINDOW_MAXIMIZED;
     this->window = SDL_CreateWindow(
         windowtitle,
         SDL_WINDOWPOS_CENTERED,
         SDL_WINDOWPOS_CENTERED,
         this->coord.viewport_size.x,
         this->coord.viewport_size.y,
         window_flags
     );
     if (this->window == nullptr) {
         throw Error(MSG(err) << "Failed to create SDL window: " << SDL_GetError());
     }
     // load support for the PNG image formats, jpg bit: IMG_INIT_JPG
     int wanted_image_formats = IMG_INIT_PNG;
     int sdlimg_inited = IMG_Init(wanted_image_formats);
     if ((sdlimg_inited & wanted_image_formats) != wanted_image_formats) {
         throw Error(MSG(err) << "Failed to init PNG support: " << IMG_GetError());
     }
     if (gl_debug)
         this->glcontext = error::create_debug_context(this->window);
     else
         this->glcontext = SDL_GL_CreateContext(this->window);
     if (this->glcontext == nullptr) {
         throw Error(MSG(err) << "Failed creating OpenGL context: " << SDL_GetError());
     }
     // check the OpenGL version, for shaders n stuff
     if (!epoxy_is_desktop_gl() || epoxy_gl_version() < 21) {
         throw Error(MSG(err) << "OpenGL 2.1 not available");
     }
     // to quote the standard doc:
     // 'The value gives a rough estimate
     // of the largest texture that the GL can handle'
     // -> wat?
     // anyways, we need at least 1024x1024.
     int max_texture_size;
     glGetIntegerv(GL_MAX_TEXTURE_SIZE, &max_texture_size);
     log::log(MSG(dbg) << "Maximum supported texture size: " << max_texture_size);
     if (max_texture_size < 1024) {
         throw Error(MSG(err) << "Maximum supported texture size too small: " << max_texture_size);
     }
     int max_texture_units;
     glGetIntegerv(GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS, &max_texture_units);
     log::log(MSG(dbg) << "Maximum supported texture units: " << max_texture_units);
     if (max_texture_units < 2) {
         throw Error(MSG(err) << "Your GPU has not enough texture units: " << max_texture_units);
     }
     // vsync on
     SDL_GL_SetSwapInterval(1);
     // enable alpha blending
     glEnable(GL_BLEND);
     // order of drawing relevant for depth
     // what gets drawn last is displayed on top.
     glDisable(GL_DEPTH_TEST);
     glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
     util::Path qml_root = this->root_dir / "assets" / "qml";
     if (not qml_root.is_dir()) {
         throw Error{ERR << "could not find qml root folder " << qml_root};
     }
     util::Path qml_root_file = qml_root / "main.qml";
     if (not qml_root_file.is_file()) {
         throw Error{ERR << "could not find main.qml file " << qml_root_file};
     }
     // \todo in order to support qml-mods, the fslike and filelike
     //       library has to be integrated into qt. For now,
     //       figure out the absolute paths here and pass them in.
     std::string qml_root_str = qml_root.resolve_native_path();
     std::string qml_root_file_str = qml_root_file.resolve_native_path();
     this->gui = std::make_unique<gui::GUI>(
         this->window,                // sdl window for the gui
         qml_root_file_str,           // entry qml file, absolute path.
         qml_root_str,                // directory to watch for qml file changes
         &this->qml_info              // qml data: Engine *, the data directory, ...
     );
     // register the engines input manager
     this->register_input_action(&this->input_manager);
     // initialize engine related global keybinds
     auto &global_input_context = this->get_input_manager().get_global_context();
     input::ActionManager &action = this->get_action_manager();
     global_input_context.bind(action.get("STOP_GAME"), [this](const input::action_arg_t &) {
         this->stop();
     });
     global_input_context.bind(action.get("TOGGLE_HUD"), [this](const input::action_arg_t &) {
         this->drawing_huds.value = !this->drawing_huds.value;
     });
     global_input_context.bind(action.get("SCREENSHOT"), [this](const input::action_arg_t &) {
         this->get_screenshot_manager().save_screenshot(this->coord.viewport_size);
     });
     global_input_context.bind(action.get("TOGGLE_DEBUG_OVERLAY"), [this](const input::action_arg_t &) {
         this->drawing_debug_overlay.value = !this->drawing_debug_overlay.value;
     });
     global_input_context.bind(action.get("TOGGLE_PROFILER"), [this](const input::action_arg_t &) {
         if (this->external_profiler.currently_profiling) {
             this->external_profiler.stop();
             this->external_profiler.show_results();
         } else {
             this->external_profiler.start();
         }
     });
     global_input_context.bind(input::event_class::MOUSE, [this](const input::action_arg_t &arg) {
         if (arg.e.cc.has_class(input::event_class::MOUSE_MOTION) &&
             this->get_input_manager().is_down(input::event_class::MOUSE_BUTTON, 2)) {
             this->move_phys_camera(arg.motion.x, arg.motion.y);
             return true;
         }
         return false;
     });
     this->text_renderer = std::make_unique<renderer::TextRenderer>();
     this->unit_selection = std::make_unique<UnitSelection>(this);
 }
Engine() [2/3]
openage::Engine::Engine (const Engine & copy) delete
engine copy constructor.
Engine() [3/3]
openage::Engine::Engine (Engine && other) delete
engine move constructor.
~Engine()
openage::Engine::~Engine () virtual
engine destructor, cleans up memory etc.
deletes opengl context, the SDL window, and engine variables.
Definition at line 227 of file engine.cpp.
                 {
     this->profiler.unregister_all();
     // deallocate the gui system
     // this looses the opengl context in the qtsdl::GuiRenderer
     // deallocation (of the QtOpenGLContext).
     // so no gl* functions will be called after the gl context is gone.
     this->gui.reset(nullptr);
     SDL_GL_DeleteContext(this->glcontext);
     SDL_DestroyWindow(this->window);
     IMG_Quit();
     SDL_Quit();
 }
References glcontext, gui, profiler, openage::util::Profiler::unregister_all(), and window.
Member Function Documentation
announce_global_binds()
void openage::Engine::announce_global_binds ()
send keybindings help string to gui.
Definition at line 519 of file engine.cpp.
{
     emit this->gui_signals.global_binds_changed(
         this->get_input_manager().get_global_context().active_binds()
     );
 }
References get_input_manager(), openage::EngineSignals::global_binds_changed(), and gui_signals.
draw_debug_overlay()
bool openage::Engine::draw_debug_overlay ()
Draw the game version and the current FPS on screen.
Definition at line 274 of file engine.cpp.
{
     util::col {255, 255, 255, 255}.use();
     // Draw FPS counter in the lower right corner
     this->render_text(
         {this->coord.viewport_size.x - 100, 15}, 20,
         "%.1f fps", this->fps_counter.fps
     );
     // Draw version string in the lower left corner
     this->render_text(
         {5, 35}, 20,
         "openage %s", config::version
     );
     this->render_text(
         {5, 15}, 12,
         "%s", config::config_option_string
     );
     this->profiler.show(true);
     return true;
 }
References coord, openage::util::FrameCounter::fps, fps_counter, profiler, render_text(), openage::util::Profiler::show(), openage::util::col::use(), and openage::coord::CoordManager::viewport_size.
Referenced by loop().
end_game()
void openage::Engine::end_game ()
Stop the running game.
Definition at line 575 of file engine.cpp.
                       {
     this->game = nullptr;
     this->unit_selection->clear();
 }
References game, and unit_selection.
Referenced by openage::GameMainHandle::clear().
get_action_manager()
input::ActionManager & openage::Engine::get_action_manager ()
return this engine's action manager.
Definition at line 503 of file engine.cpp.
{
     return this->action_manager;
 }
References action_manager.
Referenced by openage::ActionModeSignals::on_action(), openage::ActionMode::on_game_control_set(), openage::EditorMode::on_game_control_set(), and openage::console::Console::register_to_engine().
get_audio_manager()
audio::AudioManager & openage::Engine::get_audio_manager ()
return this engine's audio manager.
Definition at line 495 of file engine.cpp.
{
     return this->audio_manager;
 }
References audio_manager.
Referenced by openage::GameSpec::on_gamedata_loaded(), and openage::Sound::play().
get_cvar_manager()
cvar::CVarManager & openage::Engine::get_cvar_manager ()
return this engine's cvar manager.
Definition at line 507 of file engine.cpp.
{
     return this->cvar_manager;
 }
References cvar_manager.
Referenced by openage::console::Console::interpret().
get_game()
GameMain * openage::Engine::get_game ()
return currently running game or null if a game is not currently running
Definition at line 487 of file engine.cpp.
{
     return this->game.get();
 }
References game.
Referenced by openage::ActionMode::available(), openage::EditorMode::available(), openage::GameRenderer::game(), openage::ActionMode::get_action(), openage::GameControl::get_current_player(), openage::GameRenderer::on_draw(), openage::ActionMode::on_game_control_set(), openage::EditorMode::paint_entity_at(), openage::EditorMode::paint_terrain_at(), openage::ActionMode::place_selection(), and openage::ActionMode::render().
get_input_manager()
input::InputManager & openage::Engine::get_input_manager ()
return this engine's keybind manager.
Definition at line 511 of file engine.cpp.
{
     return this->input_manager;
 }
References input_manager.
Referenced by openage::ActionMode::announce_buttons_type(), announce_global_binds(), loop(), openage::ActionModeSignals::on_action(), openage::ActionMode::on_exit(), openage::ActionMode::on_game_control_set(), openage::EditorMode::on_game_control_set(), openage::console::Console::register_to_engine(), openage::GameControl::set_engine(), openage::GameControl::set_mode(), and openage::console::Console::set_visible().
get_job_manager()
job::JobManager * openage::Engine::get_job_manager ()
return this engine's job manager.
Definition at line 491 of file engine.cpp.
{
     return &this->job_manager;
 }
References job_manager.
Referenced by openage::GameSpecHandle::start_load_job().
get_root_dir()
const util::Path & openage::Engine::get_root_dir ()
return the data directory where the engine was started from.
Definition at line 483 of file engine.cpp.
{
     return this->root_dir;
 }
References root_dir.
get_screenshot_manager()
ScreenshotManager & openage::Engine::get_screenshot_manager ()
return this engine's screenshot manager.
Definition at line 499 of file engine.cpp.
{
     return this->screenshot_manager;
 }
References screenshot_manager.
get_text_renderer()
renderer::TextRenderer * openage::Engine::get_text_renderer ()
return this engine's text renderer.
Definition at line 525 of file engine.cpp.
{
     return this->text_renderer.get();
 }
References text_renderer.
Referenced by openage::console::draw::to_opengl().
get_unit_selection()
UnitSelection * openage::Engine::get_unit_selection ()
return this engine's unit selection.
Definition at line 515 of file engine.cpp.
{
     return this->unit_selection.get();
 }
References unit_selection.
Referenced by openage::ActionMode::on_game_control_set().
lastframe_duration_nsec()
time_nsec_t openage::Engine::lastframe_duration_nsec () const
return the number of nanoseconds that have passed for rendering the last frame.
use that for fps-independent input actions.
Definition at line 529 of file engine.cpp.
{
     return this->fps_counter.nsec_lastframe;
 }
References fps_counter, and openage::util::FrameCounter::nsec_lastframe.
Referenced by loop().
loop()
void openage::Engine::loop () private
main engine loop function.
this will be looped once per frame when the game is running.
the loop invokes fps counting, SDL event handling, view translation, and calling the main draw_method.
Definition at line 315 of file engine.cpp.
                   {
     SDL_Event event;
     util::Timer cap_timer;
     while (this->running) {
         this->profiler.start_frame_measure();
         this->fps_counter.frame();
         cap_timer.reset(false);
         this->job_manager.execute_callbacks();
         this->profiler.start_measure("events", {1.0, 0.0, 0.0});
         // top level input handling
         while (SDL_PollEvent(&event)) {
             switch (event.type) {
             case SDL_QUIT:
                 this->stop();
                 break;
             case SDL_WINDOWEVENT: {
                 if (event.window.event == SDL_WINDOWEVENT_RESIZED) {
                     coord::viewport_delta new_size{event.window.data1, event.window.data2};
                     // call additional handlers for the resize event
                     for (auto &handler : on_resize_handler) {
                         if (!handler->on_resize(new_size)) {
                             break;
                         }
                     }
                 }
                 break;
             }
             default:
                 for (auto &action : this->on_input_event) {
                     if (false == action->on_input(&event)) {
                         break;
                     }
                 }
             } // switch event
         }
         // here, call to Qt and process all the gui events.
         this->gui->process_events();
         if (this->game) {
             // read camera movement input keys and/or cursor location,
             // and move camera accordingly.
             // camera movement speed, in pixels per millisecond
             // one pixel per millisecond equals 14.3 tiles/second
             float mov_x = 0.0, mov_y = 0.0, cam_movement_speed_keyboard = 0.5;
             Uint32 win_flags = SDL_GetWindowFlags(this->window);
             bool inp_focus = win_flags & SDL_WINDOW_INPUT_FOCUS;
             input::InputManager &input = this->get_input_manager();
             using Edge = input::InputManager::Edge;
             if (inp_focus and (input.is_down(SDLK_LEFT) or
                 input.is_mouse_at_edge(Edge::LEFT, coord.viewport_size.x))) {
                 mov_x = -cam_movement_speed_keyboard;
             }
             if (inp_focus and (input.is_down(SDLK_RIGHT) or
                 input.is_mouse_at_edge(Edge::RIGHT, coord.viewport_size.x))) {
                 mov_x = cam_movement_speed_keyboard;
             }
             if (inp_focus and (input.is_down(SDLK_DOWN) or
                 input.is_mouse_at_edge(Edge::DOWN, coord.viewport_size.y))) {
                 mov_y = cam_movement_speed_keyboard;
             }
             if (inp_focus and (input.is_down(SDLK_UP) or
                 input.is_mouse_at_edge(Edge::UP, coord.viewport_size.y))) {
                 mov_y = -cam_movement_speed_keyboard;
             }
             // perform camera movement
             this->move_phys_camera(
                 mov_x, mov_y,
                 static_cast<float>(this->lastframe_duration_nsec()) / 1e6);
             // update the currently running game
             this->game->update(this->lastframe_duration_nsec());
         }
         this->profiler.end_measure("events");
         // call engine tick callback methods
         for (auto &action : this->on_engine_tick) {
             if (false == action->on_tick()) {
                 break;
             }
         }
         this->profiler.start_measure("rendering", {0.0, 1.0, 0.0});
         // clear the framebuffer to black
         // in the future, we might disable it for lazy drawing
         glClearColor(0.0, 0.0, 0.0, 0.0);
         glClear(GL_COLOR_BUFFER_BIT | GL_STENCIL_BUFFER_BIT);
         // invoke all game drawing handlers
         for (auto &action : this->on_drawgame) {
             if (false == action->on_draw()) {
                 break;
             }
         }
         util::gl_check_error();
         // draw the fps overlay
         if (this->drawing_debug_overlay.value) {
             this->draw_debug_overlay();
         }
         // invoke all hud drawing callback methods
         if (this->drawing_huds.value) {
             for (auto &action : this->on_drawhud) {
                 if (false == action->on_drawhud()) {
                     break;
                 }
             }
         }
         this->text_renderer->render();
         util::gl_check_error();
         this->profiler.end_measure("rendering");
         this->profiler.start_measure("idle", {0.0, 0.0, 1.0});
         // the rendering is done
         // swap the drawing buffers to actually show the frame
         SDL_GL_SwapWindow(window);
         if (this->ns_per_frame != 0) {
             uint64_t ns_for_current_frame = cap_timer.getval();
             if (ns_for_current_frame < this->ns_per_frame) {
                 SDL_Delay((this->ns_per_frame - ns_for_current_frame) / 1e6);
             }
         }
         this->profiler.end_measure("idle");
         this->profiler.end_frame_measure();
     }
 }
References coord, draw_debug_overlay(), drawing_debug_overlay, drawing_huds, openage::util::Profiler::end_frame_measure(), openage::util::Profiler::end_measure(), openage::job::JobManager::execute_callbacks(), fps_counter, openage::util::FrameCounter::frame(), game, get_input_manager(), openage::util::Timer::getval(), openage::util::gl_check_error(), gui, openage::input::InputManager::is_down(), openage::input::InputManager::is_mouse_at_edge(), job_manager, lastframe_duration_nsec(), move_phys_camera(), ns_per_frame, on_drawgame, on_drawhud, on_engine_tick, on_input_event, on_resize_handler, profiler, openage::util::Timer::reset(), running, openage::util::Profiler::start_frame_measure(), openage::util::Profiler::start_measure(), stop(), text_renderer, openage::util::Variable< T >::value, openage::coord::CoordManager::viewport_size, and window.
Referenced by run().
move_phys_camera()
void openage::Engine::move_phys_camera (float x, float y, float amount = 1.0)
move the phys3 camera incorporated in the engine
Definition at line 551 of file engine.cpp.
{
     // calculate camera position delta from velocity and frame duration
     coord::camgame_delta cam_delta{
         static_cast<coord::pixel_t>(+x * amount),
         static_cast<coord::pixel_t>(-y * amount)
     };
     // update camera phys position
     this->coord.camgame_phys += cam_delta.to_phys3(this->coord, 0);
 }
References openage::coord::CoordManager::camgame_phys, and coord.
Referenced by loop().
on_resize()
bool openage::Engine::on_resize (coord::viewport_delta new_size) override virtual
window resize handler function.
recalculates opengl settings like viewport and projection matrices.
Implements openage::ResizeHandler.
Definition at line 242 of file engine.cpp.
{
     // \todo move all this to the renderer!
     log::log(MSG(dbg) << "engine window resize to "
              << new_size.x << "x" << new_size.y);
     // update engine window size
     this->coord.viewport_size = new_size;
     // update camgame window position, set it to center.
     this->coord.camgame_viewport = coord::viewport{0, 0} + (this->coord.viewport_size / 2);
     // update camhud window position, set to lower left corner
     this->coord.camhud_viewport = {0, coord::pixel_t{this->coord.viewport_size.y}};
     // reset previous projection matrix
     glMatrixMode(GL_PROJECTION);
     glLoadIdentity();
     // update OpenGL viewport: the rendering area
     glViewport(0, 0, this->coord.viewport_size.x, this->coord.viewport_size.y);
     // set orthographic projection: left, right, bottom, top, near_val, far_val
     glOrtho(0, this->coord.viewport_size.x, 0, this->coord.viewport_size.y, 9001, -1);
     // reset the modelview matrix
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     return true;
 }
References openage::coord::CoordManager::camgame_viewport, openage::coord::CoordManager::camhud_viewport, coord, openage::log::dbg(), openage::log::log(), MSG, and openage::coord::CoordManager::viewport_size.
operator=() [1/2]
Engine& openage::Engine::operator= (const Engine & copy) delete
engine assignment operator.
operator=() [2/2]
Engine& openage::Engine::operator= (Engine && other) delete
engine move operator.
register_draw_action()
void openage::Engine::register_draw_action (DrawHandler * handler)
register a draw handler, run in game coordinates.
Definition at line 475 of file engine.cpp.
{
     this->on_drawgame.push_back(handler);
 }
References on_drawgame.
register_drawhud_action()
void openage::Engine::register_drawhud_action (HudHandler * handler)
register a hud drawing handler, drawn in hud coordinates.
Definition at line 471 of file engine.cpp.
{
     this->on_drawhud.push_back(handler);
 }
References on_drawhud.
Referenced by openage::console::Console::register_to_engine(), and openage::GameControl::set_engine().
register_input_action()
void openage::Engine::register_input_action (InputHandler * handler)
register a new input event handler, run for each input event.
Definition at line 463 of file engine.cpp.
{
     this->on_input_event.push_back(handler);
 }
References on_input_event.
Referenced by openage::console::Console::register_to_engine().
register_resize_action()
void openage::Engine::register_resize_action (ResizeHandler * handler)
register a resize handler, run when the window size changes.
Definition at line 479 of file engine.cpp.
{
     this->on_resize_handler.push_back(handler);
 }
References on_resize_handler.
Referenced by openage::console::Console::register_to_engine().
register_tick_action()
void openage::Engine::register_tick_action (TickHandler * handler)
register a tick action, executed upon engine tick.
Definition at line 467 of file engine.cpp.
{
     this->on_engine_tick.push_back(handler);
 }
References on_engine_tick.
Referenced by openage::console::Console::register_to_engine().
render_text()
void openage::Engine::render_text (coord::viewport position, size_t size, const char * format, ...)
render text with the at a position with specified font size
Definition at line 533 of file engine.cpp.
{
     auto it = this->fonts.find(size);
     if (it == this->fonts.end()) {
         throw Error(MSG(err) << "Unknown font size requested: " << size);
     }
     renderer::Font *font = it->second;
     std::string buf;
     va_list vl;
     va_start(vl, format);
     util::vsformat(format, vl, buf);
     va_end(vl);
     this->text_renderer->set_font(font);
     this->text_renderer->draw(position.x, position.y, buf);
 }
References openage::log::err(), openage::renderer::tests::font(), fonts, MSG, text_renderer, and openage::util::vsformat().
Referenced by draw_debug_overlay(), openage::util::Profiler::draw_legend(), openage::ActionMode::render(), and openage::UnitSelection::show_attributes().
run()
void openage::Engine::run ()
starts the engine loop.
Definition at line 298 of file engine.cpp.
                  {
     try {
         this->job_manager.start();
         this->running = true;
         this->loop();
         this->running = false;
     } catch (...) {
         this->job_manager.stop();
         throw;
     }
 }
References job_manager, loop(), running, openage::job::JobManager::start(), and openage::job::JobManager::stop().
save_screenshot()
void openage::Engine::save_screenshot (const char * filename)
draw the current frames per second number on screen.
save the current framebuffer to a given png file.
Parameters
filename the file where the picture will be saved to.
start_game() [1/2]
void openage::Engine::start_game (const Generator & generator)
Start a game with the given game generator.
Definition at line 570 of file engine.cpp.
{
     this->game = std::make_unique<GameMain>(generator);
     this->game->set_parent(this);
 }
References game.
Referenced by openage::GameMainHandle::set_game().
start_game() [2/2]
void openage::Engine::start_game (std::unique_ptr< GameMain > && game)
Start a game with the given initialized game.
Definition at line 562 of file engine.cpp.
{
     // \todo maybe implement a proper 1-to-1 connection
     ENSURE(game, "linking game to engine problem");
     this->game = std::move(game);
     this->game->set_parent(this);
 }
References ENSURE, game, and openage::move.
stop()
void openage::Engine::stop ()
enqueues the stop of the main loop.
Definition at line 310 of file engine.cpp.
                   {
     this->job_manager.stop();
     this->running = false;
 }
References job_manager, running, and openage::job::JobManager::stop().
Referenced by loop(), and openage::gui::EngineLink::stop().
Friends And Related Function Documentation
GameMain
friend class GameMain friend
Definition at line 89 of file engine.h.
Member Data Documentation
action_manager
input::ActionManager openage::Engine::action_manager private
the engine's action manager.
Definition at line 385 of file engine.h.
Referenced by get_action_manager().
audio_manager
audio::AudioManager openage::Engine::audio_manager private
the engine's audio manager.
Definition at line 390 of file engine.h.
Referenced by get_audio_manager().
coord
coord::CoordManager openage::Engine::coord
this engine's coordinate manager.
Definition at line 294 of file engine.h.
Referenced by openage::Unit::draw(), openage::Terrain::draw(), draw_debug_overlay(), loop(), move_phys_camera(), openage::GameRenderer::on_draw(), openage::UnitSelection::on_drawhud(), openage::ActionMode::on_game_control_set(), openage::EditorMode::on_game_control_set(), on_resize(), openage::EditorMode::paint_entity_at(), openage::EditorMode::paint_terrain_at(), openage::ActionMode::render(), and openage::UnitSelection::select_space().
cvar_manager
cvar::CVarManager openage::Engine::cvar_manager private
the engine's cvar manager.
Definition at line 380 of file engine.h.
Referenced by get_cvar_manager().
drawing_debug_overlay
options::Var<bool> openage::Engine::drawing_debug_overlay
FPS and game version are drawn when this is true.
Definition at line 279 of file engine.h.
Referenced by openage::util::Profiler::engine_in_debug_mode(), and loop().
drawing_huds
options::Var<bool> openage::Engine::drawing_huds
this allows to disable drawing of every registered hud.
Definition at line 284 of file engine.h.
Referenced by loop().
external_profiler
util::ExternalProfiler openage::Engine::external_profiler
profiler used by the engine
Definition at line 289 of file engine.h.
font_manager
std::unique_ptr<renderer::FontManager> openage::Engine::font_manager private
ttf font loading manager
Definition at line 435 of file engine.h.
fonts
std::unordered_map<int, renderer::Font *> openage::Engine::fonts private
the text fonts to be used for (can you believe it?) texts.
maps fontsize -> font
Definition at line 406 of file engine.h.
Referenced by render_text().
fps_counter
util::FrameCounter openage::Engine::fps_counter private
the frame counter measuring fps.
Definition at line 370 of file engine.h.
Referenced by draw_debug_overlay(), lastframe_duration_nsec(), and loop().
game
std::unique_ptr<GameMain> openage::Engine::game private
the currently running game
Definition at line 352 of file engine.h.
Referenced by end_game(), get_game(), loop(), and start_game().
glcontext
SDL_GLContext openage::Engine::glcontext private
SDL OpenGL context, we'll only have one, but it would allow having multiple ones.
This is actually a void * but sdl2 thought it was a good idea to name it like a differently.
Definition at line 420 of file engine.h.
Referenced by ~Engine().
gui
std::unique_ptr<gui::GUI> openage::Engine::gui private
the gui binding
Definition at line 425 of file engine.h.
Referenced by loop(), and ~Engine().
gui_link
gui::GuiItemLink* openage::Engine::gui_link
Link to the Qt GUI.
Definition at line 456 of file engine.h.
gui_signals
EngineSignals openage::Engine::gui_signals
Signal emitting capability for the engine.
Definition at line 451 of file engine.h.
Referenced by announce_global_binds().
input_manager
input::InputManager openage::Engine::input_manager private
the engine's keybind manager.
Definition at line 395 of file engine.h.
Referenced by get_input_manager().
job_manager
job::JobManager openage::Engine::job_manager private
the engine's job manager, for asynchronous background task queuing.
Definition at line 357 of file engine.h.
Referenced by get_job_manager(), loop(), run(), and stop().
logsink_file
std::unique_ptr<log::FileSink> openage::Engine::logsink_file private
Logsink to store messages to the filesystem.
Definition at line 445 of file engine.h.
ns_per_frame
time_nsec_t openage::Engine::ns_per_frame private
how many nanoseconds are in a frame (1e9 / fps_limit).
0 if there is no fps limit.
Definition at line 319 of file engine.h.
Referenced by loop().
on_drawgame
std::vector<DrawHandler *> openage::Engine::on_drawgame private
run every time the game is being drawn, with the renderer set to the camgame system
Definition at line 336 of file engine.h.
Referenced by loop(), and register_draw_action().
on_drawhud
std::vector<HudHandler *> openage::Engine::on_drawhud private
run every time the hud is being drawn, with the renderer set to the camhud system
Definition at line 342 of file engine.h.
Referenced by loop(), and register_drawhud_action().
on_engine_tick
std::vector<TickHandler *> openage::Engine::on_engine_tick private
run on every engine tick, after input handling, before rendering
Definition at line 330 of file engine.h.
Referenced by loop(), and register_tick_action().
on_input_event
std::vector<InputHandler *> openage::Engine::on_input_event private
input event processor objects.
called for each captured sdl input event.
Definition at line 325 of file engine.h.
Referenced by loop(), and register_input_action().
on_resize_handler
std::vector<ResizeHandler *> openage::Engine::on_resize_handler private
list of handlers that are executed upon a resize event.
Definition at line 347 of file engine.h.
Referenced by loop(), and register_resize_action().
profiler
util::Profiler openage::Engine::profiler private
the engines profiler
Definition at line 430 of file engine.h.
Referenced by draw_debug_overlay(), loop(), and ~Engine().
qml_info
gui::EngineQMLInfo openage::Engine::qml_info private
This stores information to be accessible from the QML engine.
Information in there (such as a pointer to the this engine) is then usable from within qml files, after some additional magic.
Definition at line 365 of file engine.h.
root_dir
util::Path openage::Engine::root_dir private
The engine root directory.
Uses the openage fslike path abstraction that can mount paths into one.
This means that this path does simulataneously lead to global assets, home-folder-assets, settings, and basically the whole filesystem access.
Definition at line 313 of file engine.h.
Referenced by get_root_dir().
running
bool openage::Engine::running
current engine state variable.
to be set to false to stop the engine loop.
Definition at line 274 of file engine.h.
Referenced by loop(), run(), and stop().
screenshot_manager
ScreenshotManager openage::Engine::screenshot_manager private
the engine's screenshot manager.
Definition at line 375 of file engine.h.
Referenced by get_screenshot_manager().
text_renderer
std::unique_ptr<renderer::TextRenderer> openage::Engine::text_renderer private
2d text renderer
Definition at line 440 of file engine.h.
Referenced by get_text_renderer(), loop(), and render_text().
unit_selection
std::unique_ptr<UnitSelection> openage::Engine::unit_selection private
the engine's unit selection.
Definition at line 400 of file engine.h.
Referenced by end_game(), and get_unit_selection().
window
SDL_Window* openage::Engine::window private
SDL window where everything is displayed within.
Definition at line 411 of file engine.h.
Referenced by loop(), and ~Engine().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/engine.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/engine.cpp