openage: openage::Sound Class Reference
openage::Sound Class Reference
simple sound object
#include <game_spec.h>
Public Member Functions
Sound (GameSpec *spec, std::vector< int > &&sound_items)
void play () const
Public Attributes
std::vector< int > sound_items
GameSpec * game_spec
Detailed Description
simple sound object
Todo:
move to assetmanager
Definition at line 43 of file game_spec.h.
Constructor & Destructor Documentation
Sound()
openage::Sound::Sound (GameSpec * spec, std::vector< int > && sound_items) inline
Definition at line 45 of file game_spec.h.
         :
         sound_items{sound_items},
         game_spec{spec} {}
References sound_items.
Member Function Documentation
play()
void openage::Sound::play () const
Definition at line 431 of file game_spec.cpp.
{
     if (this->sound_items.size() <= 0) {
         return;
     }
     int rand = rng::random_range(0, this->sound_items.size());
     int sndid = this->sound_items.at(rand);
     try {
         // \todo buhuuuu gnargghh this has to be moved to the asset loading subsystem hnnnng
         audio::AudioManager &am = this->game_spec->get_asset_manager()->get_engine()->get_audio_manager();
         if (not am.is_available()) {
             return;
         }
         audio::Sound sound = am.get_sound(audio::category_t::GAME, sndid);
         sound.play();
     }
     catch (audio::Error &e) {
         log::log(MSG(warn) << "cannot play: " << e);
     }
 }
References openage::audio::GAME, game_spec, openage::GameSpec::get_asset_manager(), openage::Engine::get_audio_manager(), openage::AssetManager::get_engine(), openage::audio::AudioManager::get_sound(), openage::audio::AudioManager::is_available(), openage::log::log(), MSG, openage::audio::Sound::play(), openage::rng::random_range(), sound_items, and openage::log::warn().
Referenced by openage::UnitTexture::draw(), openage::MoveAbility::invoke(), openage::GarrisonAbility::invoke(), openage::UngarrisonAbility::invoke(), openage::TrainAbility::invoke(), openage::ResearchAbility::invoke(), openage::BuildAbility::invoke(), openage::GatherAbility::invoke(), openage::AttackAbility::invoke(), openage::RepairAbility::invoke(), openage::HealAbility::invoke(), openage::PatrolAbility::invoke(), openage::ConvertAbility::invoke(), openage::ObjectProducer::place(), and openage::BuildingProducer::place().
Member Data Documentation
game_spec
GameSpec* openage::Sound::game_spec
Definition at line 54 of file game_spec.h.
Referenced by play().
sound_items
std::vector<int> openage::Sound::sound_items
Definition at line 52 of file game_spec.h.
Referenced by play(), and Sound().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gamestate/game_spec.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gamestate/game_spec.cpp