openage: openage::RepairAction Class Reference
openage::RepairAction Class Reference
repairs a unit
#include <action.h>
Public Member Functions
RepairAction (Unit *e, UnitReference tar)
virtual ~RepairAction ()
void update_in_range (unsigned int time, Unit *target_unit) override
Control units action when in range of the target.
void on_completion_in_range (int) override
bool completed_in_range (Unit *) const override
std::string name () const override
debug string to identify action types
Public Member Functions inherited from openage::TargetAction
TargetAction (Unit *e, graphic_type gt, UnitReference r, coord::phys_t action_rad)
action_rad is how close a unit must come to another unit to be considered to touch the other, for example in gathering resource and melee attack
TargetAction (Unit *e, graphic_type gt, UnitReference r)
this constructor uses the default action radius formula which will bring the object as near to the target as the pathing grid will allow.
virtual ~TargetAction ()
void update (unsigned int time) override
each action has its own update functionality which gets called when this is the active action
void on_completion () override
action to perform when popped from a units action stack
bool completed () const override
gets called for all actions on stack each update cycle
bool allow_interupt () const override
checks if the action can be interrupted, allowing it to be popped if the user specifies a new action, if false the action must reach a completed state before removal eg dead action must be completed and cannot be discarded
bool allow_control () const override
control whether stack can discard the action automatically and should the stack be modifiable when this action is on top
coord::phys_t distance_to_target ()
Unit * update_distance ()
UnitReference get_target () const
int get_target_type_id () const
void set_target (UnitReference new_target)
changes target, ending action when new target is invalid
Public Member Functions inherited from openage::UnitAction
UnitAction (Unit *u, graphic_type initial_gt)
Require unit to be updated and an initial graphic type.
virtual ~UnitAction ()
graphic_type type () const
type of graphic this action should use
float current_frame () const
frame number to use on the current graphic
virtual const graphic_set & current_graphics () const
determines which graphic should be used for drawing this unit finds the default graphic using the units type, used by most actions
void draw_debug (const Engine &engine)
void face_towards (const coord::phys3 pos)
common functions for actions
bool damage_unit (Unit &target)
Damage a unit, returns true if the unit was killed in the process.
void move_to (Unit &target, bool use_range=true)
Private Attributes
ResourceBundle cost
stores the cost of the repair for 1hp
IntervalTimer timer
bool complete
Additional Inherited Members
Static Public Member Functions inherited from openage::UnitAction
static coord::phys_t adjacent_range (Unit *u)
a small distance to which units are considered touching when within this distance
static coord::phys_t get_attack_range (Unit *u)
looks at an ranged attributes on the unit otherwise returns same as adjacent_range()
static coord::phys_t get_heal_range (Unit *u)
looks at heal attribute on the unit otherwise returns same as adjacent_range()
Static Public Attributes inherited from openage::UnitAction
static bool show_debug = false
produce debug info such as visualising paths
Protected Attributes inherited from openage::UnitAction
Unit * entity
the entity being updated
graphic_type graphic
common graphic controls
float frame
float frame_rate
std::function< void(const Engine &)> debug_draw_action
additional drawing for debug purposes
Detailed Description
repairs a unit
Definition at line 518 of file action.h.
Constructor & Destructor Documentation
RepairAction()
openage::RepairAction::RepairAction (Unit * e, UnitReference tar)
Definition at line 958 of file action.cpp.
     :
     TargetAction{e, graphic_type::work, tar},
     timer{80},
     complete{false} {
     if (!tar.is_valid()) {
         // the target no longer exists
         complete = true;
     }
     else {
         Unit *target = tar.get();
         if (!target->has_attribute(attr_type::building)) {
             this->timer.set_interval(this->timer.get_interval() * 4);
         }
         // cost formula: 0.5 * (target cost) / (target max hp)
         auto &hp = target->get_attribute<attr_type::hitpoints>();
         auto &owner = this->entity->get_attribute<attr_type::owner>();
         // get the target unit's cost
         this->cost += target->unit_type->cost.get(owner.player);
         this->cost *= 0.5 / hp.hp;
         if (!owner.player.deduct(this->cost)) {
             // no resources to start
             this->complete = true;
         }
     }
 }
References openage::work.
~RepairAction()
virtual openage::RepairAction::~RepairAction () inline virtual
Definition at line 521 of file action.h.
 {}
Member Function Documentation
completed_in_range()
bool openage::RepairAction::completed_in_range (Unit *) const inline override virtual
Implements openage::TargetAction.
Definition at line 525 of file action.h.
 { return this->complete; }
References complete.
name()
std::string openage::RepairAction::name () const inline override virtual
debug string to identify action types
Implements openage::TargetAction.
Definition at line 526 of file action.h.
 { return "repair"; }
Referenced by openage.util.fslike.path.Path::stem(), openage.util.fslike.path.Path::suffix(), and openage.util.fslike.path.Path::suffixes().
on_completion_in_range()
void openage::RepairAction::on_completion_in_range (int) inline override virtual
Implements openage::TargetAction.
Definition at line 524 of file action.h.
 {}
update_in_range()
void openage::RepairAction::update_in_range (unsigned int , Unit *) override virtual
Control units action when in range of the target.
Implements openage::TargetAction.
Definition at line 991 of file action.cpp.
{
     auto &hp = target_unit->get_attribute<attr_type::hitpoints>();
     auto &dm = target_unit->get_attribute<attr_type::damaged>();
     if (dm.hp >= hp.hp) {
         // repaired by something else
         this->complete = true;
     }
     else if (this->timer.update(time)) {
         dm.hp += 1;
         if (dm.hp >= hp.hp) {
             this->complete = true;
         }
         if (!this->complete) {
             auto &owner = this->entity->get_attribute<attr_type::owner>();
             if (!owner.player.deduct(this->cost)) {
                 // no resources to continue
                 this->complete = true;
             }
         }
     }
     // inc frame
     this->frame += time * this->frame_rate / 2.5f;
 }
References complete, openage::damaged, openage::UnitAction::entity, openage::UnitAction::frame, openage::UnitAction::frame_rate, openage::Unit::get_attribute(), openage::hitpoints, openage::owner, timer, and openage::IntervalTimer::update().
Member Data Documentation
complete
bool openage::RepairAction::complete private
Definition at line 536 of file action.h.
Referenced by completed_in_range(), and update_in_range().
cost
ResourceBundle openage::RepairAction::cost private
stores the cost of the repair for 1hp
Definition at line 533 of file action.h.
timer
IntervalTimer openage::RepairAction::timer private
Definition at line 535 of file action.h.
Referenced by update_in_range().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/action.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/action.cpp