openage: openage::event::demo::BallReflectWall Class Reference
openage::event::demo::BallReflectWall Class Reference
Public Member Functions
BallReflectWall ()
void setup_event (const std::shared_ptr< Event > &evnt, const std::shared_ptr< State > &gstate) override
Called for each event that is created for this EventClass.
void invoke (Loop &, const std::shared_ptr< EventTarget > &target, const std::shared_ptr< State > &gstate, const curve::time_t &now, const EventClass::param_map &) override
This method implements the effects of the event.
curve::time_t predict_invoke_time (const std::shared_ptr< EventTarget > &target, const std::shared_ptr< State > &gstate, const curve::time_t &now) override
Is called to calculate the execution time for an event of this eventclass.
Public Member Functions inherited from openage::event::DependencyEventClass
DependencyEventClass (const std::string &name)
Public Member Functions inherited from openage::event::EventClass
EventClass (const std::string &name, const trigger_type &type)
Constructor to be constructed with the unique identifier.
virtual ~EventClass ()=default
const std::string & id ()
Return a unique identifier.
Additional Inherited Members
Public Types inherited from openage::event::EventClass
enum trigger_type {
trigger_type::DEPENDENCY, trigger_type::DEPENDENCY_IMMEDIATELY, trigger_type::TRIGGER, trigger_type::REPEAT,
trigger_type::ONCE
}
Available types for the event class: These decide when an event of this event class will be executed.
Public Attributes inherited from openage::event::EventClass
const trigger_type type
The event type this event class represents.
Detailed Description
Definition at line 27 of file physics.cpp.
Constructor & Destructor Documentation
BallReflectWall()
openage::event::demo::BallReflectWall::BallReflectWall () inline
Definition at line 29 of file physics.cpp.
 : DependencyEventClass("demo.ball.reflect_wall") {}
Member Function Documentation
invoke()
void openage::event::demo::BallReflectWall::invoke (Loop & loop, const std::shared_ptr< EventTarget > & target, const std::shared_ptr< State > & state, const curve::time_t & time, const EventClass::param_map & params) inline override virtual
This method implements the effects of the event.
It will be called at the time that was determined by predict_invoke_time.
Called from the Loop.
Implements openage::event::EventClass.
Definition at line 46 of file physics.cpp.
{
         auto positioncurve = std::dynamic_pointer_cast<curve::Continuous<util::Vector2d>>(target);
         auto state = std::dynamic_pointer_cast<PongState>(gstate);
         auto speedcurve = state->ball->speed;
         // get speed and position to insert new movement keyframe
         auto speed = speedcurve->get(now);
         auto pos = positioncurve->get(now);
         speed[1] *= -1.0;
         state->ball->speed->set_last(now, speed);
         state->ball->position->set_last(now, pos);
         if (speed[1] == 0) {
             return;
         }
         curve::time_t ty = 0;
         if (speed[1] > 0) {
             ty = curve::time_t::from_double(
                 (state->display_boundary[1] - pos[1]) / speed[1]
             );
         }
         else if (speed[1] < 0) {
             ty = curve::time_t::from_double(
                 pos[1] / -speed[1]
             );
         }
         state->ball->position->set_last(now + ty, pos + (speed * ty.to_double()));
     }
References openage::util::FixedPoint< int64_t, 16 >::from_double(), openage::speed, and openage::util::FixedPoint< int_type, fractional_bits >::to_double().
predict_invoke_time()
curve::time_t openage::event::demo::BallReflectWall::predict_invoke_time (const std::shared_ptr< EventTarget > & target, const std::shared_ptr< State > & state, const curve::time_t & at) inline override virtual
Is called to calculate the execution time for an event of this eventclass.
This is called whenever one of the set up dependencies was changed, or when a REPEAT event was executed.
Parameters
target the target the event was created for
state the state this shall work on
at the time when the change happened, from there on it shall be calculated onwards
If the event is obsolete, return <time_t>min().
If the time is lower than the previous time, then dependencies may not be resolved perfectly anymore (if other events have already been calculated before that).
Implements openage::event::EventClass.
Definition at line 82 of file physics.cpp.
{
         auto positioncurve = std::dynamic_pointer_cast<curve::Continuous<util::Vector2d>>(target);
         auto state = std::dynamic_pointer_cast<PongState>(gstate);
         auto speed = state->ball->speed->get(now);
         auto pos = positioncurve->get(now);
         if (speed[1] == 0) {
             return std::numeric_limits<curve::time_t>::max();
         }
         curve::time_t ty = 0;
         if (speed[1] > 0) {
             ty = curve::time_t::from_double((state->display_boundary[1] - pos[1]) / speed[1]);
         }
         else if (speed[1] < 0) {
             ty = curve::time_t::from_double(pos[1] / -speed[1]);
         }
 #if WITH_NCURSES
         if (state->enable_gui) {
             util::FString str;
             str.fmt("WALL TY %f NOW %f, NOWTY %f ",
                     ty.to_double(), now.to_double(), (now + ty).to_double());
             state->gui->log(str);
         };
 #endif
         return now + ty;
     }
References openage::util::FixedPoint< int64_t, 16 >::from_double(), openage::console::tests::max(), openage::speed, openage::py::str(), and openage::util::FixedPoint< int_type, fractional_bits >::to_double().
setup_event()
void openage::event::demo::BallReflectWall::setup_event (const std::shared_ptr< Event > & event, const std::shared_ptr< State > & state) inline override virtual
Called for each event that is created for this EventClass.
The job of the setup function is to add all dependencies with other event targets found in state.
Implements openage::event::EventClass.
Definition at line 31 of file physics.cpp.
{
         auto state = std::dynamic_pointer_cast<PongState>(gstate);
         // FIXME dependency to a full ball object so that any curve
         // triggers a change
         evnt->depend_on(state->ball->position);
         evnt->depend_on(state->ball->speed);
         // \todo add dependency to size of game area
         // FIXME: warn if it's not a dependency eventclass
     }
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/event/demo/physics.cpp