openage: openage::util::utf8_decoder Class Reference
openage::util::utf8_decoder Class Reference
#include <unicode.h>
Public Member Functions
utf8_decoder ()
bool feed (char c)
void reset ()
Public Attributes
codepoint_t out
unsigned remaining
Detailed Description
Definition at line 17 of file unicode.h.
Constructor & Destructor Documentation
utf8_decoder()
openage::util::utf8_decoder::utf8_decoder ()
Definition at line 10 of file unicode.cpp.
{
     reset();
 }
References reset().
Member Function Documentation
feed()
bool openage::util::utf8_decoder::feed (char c)
feeds one char to the decoder state machine returns false on decoding error, true else
once a character has been completely decoded, remaining is set to false and out is set to the decoded character. note that even if true is returned, remaining MAY be false (e.g. multi-byte characters), and remaining MAY be true even if false is returned (successful re-synchronization).
thus, after each call to feed(), you'll first want to evaluate the return value and print an error message or add the U+FFFD replacement character. then, you'll want to check for remaining == 0 out >= 0
Definition at line 19 of file unicode.cpp.
{
     bool result = true;
     if ((c & (1 << 7)) == 0) {
         // single-byte character
         if (remaining) {
             // successful re-synchronization
             // (current multi-byte character discarded)
             result = false;
         }
         remaining = 0;
         out = c;
     } else if (c & (1 << 6)) {
         if (remaining) {
             // successful re-synchronization
             // (current multi-byte character discarded)
             result = false;
         }
         // beginning of a multi-byte character
         if ((c & (1 << 5)) == 0) {
             // 2-byte character
             remaining = 1;
             out = c & ((1 << 5) - 1);
         } else if ((c & (1 << 4)) == 0) {
             // 3-byte character
             remaining = 2;
             out = c & ((1 << 4) - 1);
         } else if ((c & (1 << 3)) == 0) {
             // 4-byte character
             remaining = 3;
             out = c & ((1 << 3) - 1);
         } else {
             // no 5- or 6-byte characters exist in utf8
             remaining = 0;
             out = -1;
             result = false;
         }
     } else {
         // inside a multi-byte character
         if (!remaining) {
             // we expected the start of a new character
             result = false;
         }
         remaining -= 1;
         out = (out << 6) | (c & ((1 << 6) - 1));
     }
     return result;
 }
References out, remaining, and openage.testing.testing::result().
Referenced by openage::console::Buf::write().
reset()
void openage::util::utf8_decoder::reset ()
resets the decoder to its initial state
Definition at line 14 of file unicode.cpp.
{
     out = -1;
     remaining = 0;
 }
References out, and remaining.
Referenced by utf8_decoder().
Member Data Documentation
out
codepoint_t openage::util::utf8_decoder::out
current result character code point; overwritten on feed().
if no valid output character currently exists, this is negative or remaining is not 0.
Definition at line 28 of file unicode.h.
Referenced by feed(), reset(), and openage::console::Buf::write().
remaining
unsigned openage::util::utf8_decoder::remaining
number of remaining characters
Definition at line 33 of file unicode.h.
Referenced by feed(), reset(), and openage::console::Buf::write().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/unicode.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/unicode.cpp