openage: openage::curve::Continuous< T > Class Template Reference
openage::curve::Continuous< T > Class Template Reference
#include <continuous.h>
Public Member Functions
T get (const time_t &) const override
Public Member Functions inherited from openage::curve::ValueContainer< T >
ValueContainer (const std::shared_ptr< event::Loop > &mgr, size_t id, const EventTarget::single_change_notifier &notifier=nullptr)
virtual ~ValueContainer ()=default
virtual T operator() (const time_t &now)
virtual std::pair< time_t, const T & > frame (const time_t &) const
virtual std::pair< time_t, const T & > next_frame (const time_t &) const
virtual void set_last (const time_t &at, const T &value)
virtual void set_insert (const time_t &at, const T &value)
virtual size_t id () const override
Public Member Functions inherited from openage::event::EventTarget
virtual ~EventTarget ()=default
void add_dependent (const std::weak_ptr< Event > &event)
void show_dependents () const
Additional Inherited Members
Public Types inherited from openage::event::EventTarget
using single_change_notifier = std::function< void(const curve::time_t &)>
Protected Member Functions inherited from openage::event::EventTarget
EventTarget (const std::shared_ptr< Loop > &loop, single_change_notifier parent_notifier=nullptr)
void changes (const curve::time_t &change_time)
void trigger (const curve::time_t &last_valid_time)
Protected Attributes inherited from openage::curve::ValueContainer< T >
KeyframeContainer< T > container
const size_t _id
KeyframeContainer< T >::KeyframeIterator last_element
Detailed Description
template<typename T>
class openage::curve::Continuous< T >
Continuous Datatype. Stores a value container with continuous access. The bound template type T has to implement operator+(T) and operator*(time_t).
Definition at line 20 of file continuous.h.
Member Function Documentation
get()
template<typename T > T openage::curve::Continuous< T >::get (const time_t & time) const override virtual
will interpolate between the keyframes linearly based on the time.
Implements openage::curve::ValueContainer< T >.
Definition at line 32 of file continuous.h.
{
     const auto &e = this->container.last(time, this->last_element);
     this->last_element = e;
     auto nxt = e;
     ++nxt;
     time_t diff_time = 0;
     auto offset = time - e->time;
     // If we do not have a next (buffer underrun!!) we assign values
     if (nxt == this->container.end()) {
         // log::log(WARN << "Continuous buffer underrun. This might be bad! Assuming constant.");
     } else {
         diff_time = nxt->time - e->time;
     }
     if (nxt == this->container.end() // use the last curve value
         || offset == 0               // values equal -> don't need to interpolate
         || diff_time == 0) {         // values at the same time -> division-by-zero-error
         return e->value;
     } else {
         // Interpolation between time(now) and time(next) that has elapsed
         double elapsed_frac = offset.to_double() / diff_time.to_double();
         return e->value + (nxt->value - e->value) * elapsed_frac;
     }
 }
References openage::curve::tests::container(), and openage::util::FixedPoint< int_type, fractional_bits >::to_double().
Referenced by openage::curve::tests::curve_types().
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/curve/continuous.h