openage: openage.util.struct.NamedStruct Class Reference
openage.util.struct.NamedStruct Class Reference
Designed to be inherited from, similar to Enum.
Public Member Functions
def __init__ (self, data)
def unpack (cls, data)
Unpacks data and returns a NamedStruct object that holds the fields.
def size (cls)
Returns the size of the struct, in bytes.
def read (cls, fileobj)
Reads the appropriate amount of data from fileobj, and unpacks it.
def from_nullbytes (cls)
Decodes nullbytes (sort of a 'default' value).
def __len__ (self)
Returns the number of fields.
def __getitem__ (self, index)
Returns the n-th field, or raises IndexError.
def as_dict (self)
Returns a key-value dict for all attributes.
def __iter__ (self)
def __repr__ (self)
def __str__ (self)
Public Member Functions inherited from openage.util.struct.NamedStructMeta
def __prepare__ (mcs, name, bases, **kwds)
def __new__ (mcs, name, bases, classdict, **kwds)
Static Private Attributes
_postprocessors
_struct
_attributes
Detailed Description
Designed to be inherited from, similar to Enum.
Specify all fields of the struct, as 'membername = specstr', where specstr is a string describing the field, as in struct.Struct. NamedStructMeta translates those individual specstr fragments to a complete specstr.
Alternatively to a specstr, a callable object with a specstr member may be passed; the specstr is used as usual, but afterwards the callable is invoked to post-process the extracted data. One example for such a callable is the Flags class.
Alternatively, attributes may be set to None; those are ignored, and may be set manually at some later point.
The first member must be 'endianess'.
Examples
class MyStruct(NamedStruct):
    endianness = "<"
    mgck = "4s"
    test = "I"
    rofl = "H"
    flag = MyFlagType
The constructor takes a bytes object of the appropriate length, and fills
in all the members with the struct's actual values.
Definition at line 116 of file struct.py.
Constructor & Destructor Documentation
__init__()
def openage.util.struct.NamedStruct.__init__ (self, data)
Definition at line 132 of file struct.py.
             # pylint: disable=unsupported-membership-test
             if name in self._postprocessors:
                 # pylint: disable=unsubscriptable-object
                 value = self._postprocessors[name](value)
             setattr(self, name, value)
     @classmethod
     def unpack(cls, data):
         """
         Unpacks data and returns a NamedStruct object that holds the fields.
         """
         return cls(data)
     @classmethod
     def size(cls):
         """
         Returns the size of the struct, in bytes.
         """
         return cls._struct.size
References openage.util.struct.NamedStruct._attributes, openage.util.struct.NamedStruct._postprocessors, openage.util.struct.NamedStruct._struct, and openage.util.struct.NamedStruct.unpack().
Member Function Documentation
__getitem__()
def openage.util.struct.NamedStruct.__getitem__ (self, index)
Returns the n-th field, or raises IndexError.
Definition at line 194 of file struct.py.
     def __repr__(self):
         return str(type(self)) + ": " + repr(self.as_dict())
References openage.util.struct.NamedStruct._attributes.
__iter__()
def openage.util.struct.NamedStruct.__iter__ (self)
Definition at line 205 of file struct.py.
 class FlagsMeta(type):
     """
     Metaclass for Flags. Compare to NamedStructMeta.
__len__()
def openage.util.struct.NamedStruct.__len__ (self)
Returns the number of fields.
Definition at line 188 of file struct.py.
         """
         # pylint: disable=not-an-iterable
         return {attr: getattr(self, attr) for attr in self._attributes}
References openage.util.struct.NamedStruct._attributes.
__repr__()
def openage.util.struct.NamedStruct.__repr__ (self)
Definition at line 208 of file struct.py.
     """
     def __new__(mcs, name, bases, classdict, **kwds):
         del kwds  # unused variable
References openage.util.struct.NamedStruct.as_dict(), openage::util.repr(), and openage::py.str().
__str__()
def openage.util.struct.NamedStruct.__str__ (self)
Definition at line 211 of file struct.py.
         # we don't need to know the order of the flags, so we don't need
         # to do the whole 'OrderedDict' dance.
         # stores a mapping of flag value <-> flag name
         flags = {}
         specstr_found = False
References openage.util.struct.NamedStruct.as_dict(), and openage::py.str().
as_dict()
def openage.util.struct.NamedStruct.as_dict (self)
Returns a key-value dict for all attributes.
Definition at line 201 of file struct.py.
             for key, value in sorted(self.as_dict().items())
         )
References openage.util.struct.NamedStruct._attributes.
Referenced by openage.util.struct.NamedStruct.__repr__(), openage.util.struct.Flags.__repr__(), openage.util.struct.NamedStruct.__str__(), and openage.util.struct.Flags.unknown().
from_nullbytes()
def openage.util.struct.NamedStruct.from_nullbytes (cls)
Decodes nullbytes (sort of a 'default' value).
Definition at line 178 of file struct.py.
     def __getitem__(self, index):
         """
         Returns the n-th field, or raises IndexError.
         """
References openage.util.struct.NamedStruct._struct, and openage.util.struct.NamedStruct.unpack().
read()
def openage.util.struct.NamedStruct.read (cls, fileobj)
Reads the appropriate amount of data from fileobj, and unpacks it.
Definition at line 170 of file struct.py.
     # them if you need them.
     def __len__(self):
         """
References openage.util.struct.NamedStruct._struct, openage.util.files.read_guaranteed(), and openage.util.struct.NamedStruct.unpack().
Referenced by openage.convert.peresource.StringLiteral.readall().
size()
def openage.util.struct.NamedStruct.size (cls)
Returns the size of the struct, in bytes.
Definition at line 163 of file struct.py.
         """
         Decodes nullbytes (sort of a 'default' value).
         """
References openage.util.struct.NamedStruct._struct.
unpack()
def openage.util.struct.NamedStruct.unpack (cls, data)
Unpacks data and returns a NamedStruct object that holds the fields.
Definition at line 156 of file struct.py.
         Reads the appropriate amount of data from fileobj, and unpacks it.
         """
         data = read_guaranteed(fileobj, cls._struct.size)
Referenced by openage.util.struct.NamedStruct.__init__(), openage.util.struct.NamedStruct.from_nullbytes(), and openage.util.struct.NamedStruct.read().
Member Data Documentation
_attributes
openage.util.struct.NamedStruct._attributes static private
Definition at line 130 of file struct.py.
Referenced by openage.util.struct.NamedStruct.__getitem__(), openage.util.struct.NamedStruct.__init__(), openage.util.struct.NamedStruct.__len__(), and openage.util.struct.NamedStruct.as_dict().
_postprocessors
openage.util.struct.NamedStruct._postprocessors static private
Definition at line 122 of file struct.py.
Referenced by openage.util.struct.NamedStruct.__init__().
_struct
openage.util.struct.NamedStruct._struct static private
Definition at line 126 of file struct.py.
Referenced by openage.util.struct.NamedStruct.__init__(), openage.util.struct.NamedStruct.from_nullbytes(), openage.util.struct.NamedStruct.read(), and openage.util.struct.NamedStruct.size().
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/openage/util/struct.py