openage: openage::MovableProducer Class Reference
openage::MovableProducer Class Reference
movable unit types
#include <producer.h>
Public Member Functions
MovableProducer (const Player &owner, const GameSpec &spec, const gamedata::projectile_unit *)
virtual ~MovableProducer ()
void initialise (Unit *, Player &) override
Initialize units attributes to this type spec.
TerrainObject * place (Unit *, std::shared_ptr< Terrain >, coord::phys3) const override
set unit in place – return if placement was successful
Public Member Functions inherited from openage::ObjectProducer
ObjectProducer (const Player &owner, const GameSpec &spec, const gamedata::unit_object *ud)
virtual ~ObjectProducer ()
int id () const override
gets the unique id of this unit type
int parent_id () const override
gets the parent id of this unit type which is used for village base and gather types
std::string name () const override
gets the name of the unit type being produced
Public Member Functions inherited from openage::UnitType
UnitType ()
bool match (class Unit *)
the unit must have either same class or id as this
UnitType (const Player &owner)
virtual ~UnitType ()
virtual void reinitialise (Unit *, Player &)
Initialize units shared attributes only to this type spec.
bool operator== (const UnitType &other) const
compare if two types are the same
bool operator!= (const UnitType &other) const
UnitTexture * default_texture ()
Get a default texture for HUD drawing.
TerrainObject * place_beside (Unit *, TerrainObject const *) const
similar to place but places adjacent to an existing object
void copy_attributes (Unit *unit) const
copy attributes of this unit type to a new unit instance
void upgrade (const std::shared_ptr< AttributeContainer > &attr)
upgrades one attribute of this unit type
UnitType * parent_type () const
returns type matching parent_id()
Protected Attributes
const gamedata::projectile_unit unit_data
UnitTexture * moving
UnitTexture * attacking
const Sound * on_move
const Sound * on_attack
int projectile
Protected Attributes inherited from openage::ObjectProducer
const GameSpec & dataspec
const gamedata::unit_object unit_data
bool decay
decaying objects have a timed lifespan
const Sound * on_create
Sound id played when object is created or destroyed.
const Sound * on_destroy
std::shared_ptr< Texture > terrain_outline
std::shared_ptr< UnitTexture > default_tex
int dead_unit_id
Additional Inherited Members
Public Attributes inherited from openage::UnitType
const Player & owner
the player who owns this unit type
std::vector< UnitReference > instances
all instances of units made from this unit type this could allow all units of a type to be upgraded
std::vector< std::shared_ptr< UnitAbility > > type_abilities
abilities given to all instances
Attributes default_attributes
default attributes which get copied to new units
ResourceCost cost
The cost of the unit.
int have_limit
The max number of units of this type that a player can have at an instance.
int had_limit
The max number of units of this type that a player can create.
graphic_set graphics
The set of graphics used for this type.
coord::tile_delta foundation_size
the square dimensions of the placement
gamedata::unit_classes unit_class
raw game data class of this unit instance
Detailed Description
movable unit types
Definition at line 68 of file producer.h.
Constructor & Destructor Documentation
MovableProducer()
openage::MovableProducer::MovableProducer (const Player & owner, const GameSpec & spec, const gamedata::projectile_unit * um)
Definition at line 363 of file producer.cpp.
     :
     ObjectProducer(owner, spec, um),
     unit_data(*um),
     on_move{spec.get_sound(this->unit_data.command_sound_id)},
     on_attack{spec.get_sound(this->unit_data.command_sound_id)},
     projectile{this->unit_data.missile_unit_id} {
     // extra graphics if available
     // villagers have invalid attack and walk graphics
     // it seems these come from the command data instead
     auto walk = spec.get_unit_texture(this->unit_data.walking_graphics0);
     if (!walk) {
         // use standing instead
         walk = this->graphics[graphic_type::standing];
     }
     this->graphics[graphic_type::walking] = walk;
     // reuse as carry graphic if not already set
     if (this->graphics.count(graphic_type::carrying) == 0) {
         this->graphics[graphic_type::carrying] = walk;
     }
     auto attack = spec.get_unit_texture(this->unit_data.fight_sprite_id);
     if (attack && attack->is_valid()) {
         this->graphics[graphic_type::attack] = attack;
     }
     // extra abilities
     this->type_abilities.emplace_back(std::make_shared<MoveAbility>(this->on_move));
     this->type_abilities.emplace_back(std::make_shared<AttackAbility>(this->on_attack));
 }
References openage::GameSpec::get_sound(), openage::owner, and unit_data.
~MovableProducer()
openage::MovableProducer::~MovableProducer () virtual
Definition at line 397 of file producer.cpp.
 {}
Member Function Documentation
initialise()
void openage::MovableProducer::initialise (Unit * , Player &) override virtual
Initialize units attributes to this type spec.
This can be called using existing units to modify type Ensure that the unit has been placed before seting the units type
Todo:
make const
Reimplemented from openage::ObjectProducer.
Reimplemented in openage::LivingProducer.
Definition at line 399 of file producer.cpp.
{
     /*
      * call base function
      */
     ObjectProducer::initialise(unit, player);
     /*
      * basic attributes
      */
     if (!unit->has_attribute(attr_type::direction)) {
         unit->add_attribute(std::make_shared<Attribute<attr_type::direction>>(coord::phys3_delta{ 1, 0, 0 }));
     }
     /*
      * distance per millisecond -- consider original game speed
      * where 1.5 in game seconds pass in 1 real second
      */
     coord::phys_t sp = this->unit_data.speed / 666;
     unit->add_attribute(std::make_shared<Attribute<attr_type::speed>>(sp));
     // projectile of melee attacks
     UnitType *proj_type = this->owner.get_type(this->projectile);
     if (this->unit_data.missile_unit_id > 0 && proj_type) {
         // calculate requirements for ranged attacks
         coord::phys_t range_phys = this->unit_data.weapon_range_max;
         unit->add_attribute(std::make_shared<Attribute<attr_type::attack>>(proj_type, range_phys, 48000, 1));
     }
     else {
         unit->add_attribute(std::make_shared<Attribute<attr_type::attack>>(nullptr, 0, 0, 1));
     }
     unit->add_attribute(std::make_shared<Attribute<attr_type::formation>>());
 }
References openage::Unit::add_attribute(), openage::direction, openage::Player::get_type(), openage::Unit::has_attribute(), openage::ObjectProducer::initialise(), openage::UnitType::owner, projectile, and unit_data.
Referenced by openage::LivingProducer::initialise().
place()
TerrainObject * openage::MovableProducer::place (Unit * , std::shared_ptr< Terrain > , coord::phys3) const override virtual
set unit in place – return if placement was successful
This should be used when initially creating a unit or when a unit is ungarrsioned from a building or object
Todo:
make const
Reimplemented from openage::ObjectProducer.
Reimplemented in openage::LivingProducer.
Definition at line 434 of file producer.cpp.
{
     return ObjectProducer::place(unit, terrain, init_pos);
 }
References openage::ObjectProducer::place().
Referenced by openage::LivingProducer::place().
Member Data Documentation
attacking
UnitTexture* openage::MovableProducer::attacking protected
Definition at line 79 of file producer.h.
moving
UnitTexture* openage::MovableProducer::moving protected
Definition at line 78 of file producer.h.
on_attack
const Sound* openage::MovableProducer::on_attack protected
Definition at line 81 of file producer.h.
Referenced by openage::LivingProducer::initialise().
on_move
const Sound* openage::MovableProducer::on_move protected
Definition at line 80 of file producer.h.
Referenced by openage::LivingProducer::LivingProducer().
projectile
int openage::MovableProducer::projectile protected
Definition at line 82 of file producer.h.
Referenced by initialise().
unit_data
const gamedata::projectile_unit openage::MovableProducer::unit_data protected
Definition at line 77 of file producer.h.
Referenced by initialise(), and MovableProducer().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/producer.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/producer.cpp