openage: openage::util::Path Class Reference
openage::util::Path Class Reference
#include <path.h>
Public Types
using part_t = std::string
using parts_t = std::vector< part_t >
Public Member Functions
Path ()
Path (py::Obj fslike, const parts_t &parts={})
Path (const std::shared_ptr< fslike::FSLike > &fslike, const parts_t &parts={})
virtual ~Path ()=default
bool exists () const
bool is_file () const
bool is_dir () const
bool writable () const
std::vector< part_t > list ()
std::vector< Path > iterdir ()
bool mkdirs ()
File open (const std::string &mode="r") const
File open_r () const
File open_w () const
File open_rw () const
File open_a () const
File open_ar () const
std::string resolve_native_path (const std::string &mode="r") const
std::string resolve_native_path_r () const
std::string resolve_native_path_w () const
bool rename (const Path &target_path)
bool rmdir ()
bool touch ()
bool unlink ()
void removerecursive ()
int get_mtime () const
uint64_t get_filesize () const
Path get_parent () const
const std::string & get_name () const
std::string get_suffix () const
std::vector< std::string > get_suffixes () const
std::string get_stem () const
Path joinpath (const parts_t &subpaths) const
Path joinpath (const part_t &subpath) const
Path operator [] (const parts_t &subpaths) const
Path operator [] (const part_t &subpath) const
Path operator/ (const part_t &subpath) const
Path with_name (const part_t &name) const
Path with_suffix (const part_t &suffix) const
bool operator== (const Path &other) const
bool operator != (const Path &other) const
fslike::FSLike * get_fsobj () const
const parts_t & get_parts () const
Protected Attributes
std::shared_ptr< fslike::FSLike > fsobj
parts_t parts
Private Member Functions
std::string get_native_path () const
Friends
std::ostream & operator<< (std::ostream &stream, const Path &path)
Detailed Description
C++ pendant to the python util.fslike.path.Path
Contains a filesystem-like object and path-parts.
pxd: cppclass Path: ctypedef string part_t ctypedef vector[string] parts_t
Path() noexcept Path(PyObj, const vector[string]&) except +
FSLike *get_fsobj() except + const vector[string] &get_parts() except +
Definition at line 46 of file path.h.
Member Typedef Documentation
part_t
using openage::util::Path::part_t = std::string
Storage type for a part of a path access. Basically this is the name of a file or directory.
Definition at line 53 of file path.h.
parts_t
using openage::util::Path::parts_t = std::vector<part_t>
Storage type for the filesystem access parts this is basically a list/of/elements/in/a/path.
Definition at line 59 of file path.h.
Constructor & Destructor Documentation
Path() [1/3]
openage::util::Path::Path ()
Nullary constructor, pls don't use. It only exists because Cython can't RAII. It should be just friend of cython.
Definition at line 41 of file path.cpp.
 {}
Path() [2/3]
openage::util::Path::Path (py::Obj fslike, const parts_t & parts = {})
Construct a path object from a python fslike object. This is called from Cython.
You will probably never call that manually.
Path() [3/3]
openage::util::Path::Path (const std::shared_ptr< fslike::FSLike > & fslike, const parts_t & parts = {})
Construct a path from a fslike pointer.
Definition at line 67 of file path.cpp.
     :
     fsobj{fsobj} {
     path_normalizer(this->parts, parts);
 }
References fsobj.
~Path()
virtual openage::util::Path::~Path () virtual default
Member Function Documentation
exists()
bool openage::util::Path::exists () const
Definition at line 76 of file path.cpp.
{
     return this->is_file() or this->is_dir();
 }
References is_dir(), and is_file().
Referenced by openage.util.fslike.wrapper.Wrapper::resolve_r(), and openage.util.fslike.abstract.FSLikeObject::resolve_r().
get_filesize()
uint64_t openage::util::Path::get_filesize () const
Definition at line 240 of file path.cpp.
{
     return this->fsobj->get_filesize(this->parts);
 }
References fsobj.
get_fsobj()
fslike::FSLike * openage::util::Path::get_fsobj () const
Definition at line 339 of file path.cpp.
{
     return this->fsobj.get();
 }
References fsobj.
get_mtime()
int openage::util::Path::get_mtime () const
Definition at line 236 of file path.cpp.
{
     return this->fsobj->get_mtime(this->parts);
 }
References fsobj.
get_name()
const std::string & openage::util::Path::get_name () const
Definition at line 252 of file path.cpp.
{
     if (this->parts.size() > 0) {
         return this->parts.back();
     }
     else {
         return util::empty_string;
     }
 }
References openage::util::empty_string.
Referenced by get_stem(), get_suffix(), and get_suffixes().
get_native_path()
std::string openage::util::Path::get_native_path () const private
Return the native path (something like /your/folder/with/file) for this path. returns emptystring ("") if there is no native path.
This does not minimize/flatten (= "resolve") the path!
You probably want to use resolve_native_path instead.
Definition at line 158 of file path.cpp.
{
     return this->fsobj->get_native_path(this->parts);
 }
References fsobj.
get_parent()
Path openage::util::Path::get_parent () const
Todo:
watching of path with inotify or similar this should get a Watcher*, which manages the multiple events otherwise, each file would require an inotify fd. => see the AssetManager and move functionality from there.
Definition at line 247 of file path.cpp.
{
     return this->joinpath("..");
 }
References joinpath().
Referenced by openage::renderer::resources::Texture2dData::Texture2dData(), and with_name().
get_parts()
const Path::parts_t & openage::util::Path::get_parts () const
Definition at line 344 of file path.cpp.
{
     return this->parts;
 }
References parts.
get_stem()
std::string openage::util::Path::get_stem () const
Definition at line 282 of file path.cpp.
{
     const std::string &name = this->get_name();
     size_t pos = name.rfind('.');
     if (pos == std::string::npos) {
         return name;
     }
     return name.substr(0, pos);
 }
References get_name().
Referenced by openage::renderer::resources::Texture2dData::Texture2dData(), and with_suffix().
get_suffix()
std::string openage::util::Path::get_suffix () const
Definition at line 261 of file path.cpp.
{
     auto &name = this->get_name();
     size_t pos = name.rfind(".");
     if (pos == std::string::npos) {
         return "";
     }
     return name.substr(pos);
 }
References get_name().
get_suffixes()
std::vector< std::string > openage::util::Path::get_suffixes () const
Definition at line 271 of file path.cpp.
{
     std::string name = this->get_name();
     if (name.size() > 0 and name[0] == '.') {
         name = name.substr(1);
     }
     std::vector<std::string> ret;
     // ret = ['.' + suffix for suffix in name.split('.')[1:]]
     return ret;
 }
References get_name().
is_dir()
bool openage::util::Path::is_dir () const
Definition at line 84 of file path.cpp.
{
     return this->fsobj->is_dir(this->parts);
 }
References fsobj.
Referenced by openage.util.fslike.abstract.FSLikeObject::exists(), exists(), removerecursive(), and openage.util.fslike.path.Path::removerecursive().
is_file()
bool openage::util::Path::is_file () const
Definition at line 80 of file path.cpp.
{
     return this->fsobj->is_file(this->parts);
 }
References fsobj.
Referenced by openage::audio::Resource::create_resource(), openage.util.fslike.abstract.FSLikeObject::exists(), exists(), openage::AssetManager::load_texture(), openage::GameSpec::on_gamedata_loaded(), and openage::audio::open_opus_file().
iterdir()
std::vector< Path > openage::util::Path::iterdir ()
Definition at line 96 of file path.cpp.
{
     std::vector<Path> ret;
     // return a new path object for each element in that directory
     for (auto &entry : this->fsobj->list(this->parts)) {
         ret.push_back(this->joinpath(entry));
     }
     return ret;
 }
References fsobj, and joinpath().
Referenced by removerecursive(), and openage.util.fslike.path.Path::removerecursive().
joinpath() [1/2]
Path openage::util::Path::joinpath (const parts_t & subpaths) const
Definition at line 293 of file path.cpp.
{
     parts_t new_parts = this->parts;
     for (auto &part : subpaths) {
         if (likely(part.size() > 0)) {
             new_parts.push_back(part);
         }
     }
     return Path{this->fsobj, new_parts};
 }
References fsobj, likely, and parts.
Referenced by openage.util.fslike.path.Path::__getitem__(), openage.util.fslike.path.Path::__truediv__(), get_parent(), iterdir(), joinpath(), operator [](), operator/(), and with_name().
joinpath() [2/2]
Path openage::util::Path::joinpath (const part_t & subpath) const
Definition at line 303 of file path.cpp.
{
     return this->joinpath(util::split(subpath, '/'));
 }
References joinpath(), and openage::util::split().
Referenced by openage.util.fslike.path.Path::__getitem__(), and openage.util.fslike.path.Path::__truediv__().
list()
std::vector< Path::part_t > openage::util::Path::list ()
Definition at line 92 of file path.cpp.
{
     return this->fsobj->list(this->parts);
 }
References fsobj.
mkdirs()
bool openage::util::Path::mkdirs ()
Definition at line 107 of file path.cpp.
                   {
     return this->fsobj->mkdirs(this->parts);
 }
References fsobj.
Referenced by openage.util.fslike.wrapper.DirectoryCreator::open_w().
open()
File openage::util::Path::open (const std::string & mode = "r") const
Definition at line 111 of file path.cpp.
{
     if (mode == "r") {
         return this->open_r();
     }
     else if (mode == "w") {
         return this->open_w();
     }
     else if (mode == "rw" or mode == "r+") {
         return this->open_w();
     }
     else if (mode == "a") {
         return this->open_a();
     }
     else if (mode == "a+" or mode == "ar") {
         return this->open_ar();
     }
     else {
         throw Error{ERR << "unsupported open mode: " << mode};
     }
 }
References ERR, open_a(), open_ar(), open_r(), and open_w().
Referenced by openage::util::CSVCollection::CSVCollection(), and openage::util::read_csv_file().
open_a()
File openage::util::Path::open_a () const
Definition at line 148 of file path.cpp.
{
     return this->fsobj->open_a(this->parts);
 }
References fsobj.
Referenced by open().
open_ar()
File openage::util::Path::open_ar () const
Definition at line 153 of file path.cpp.
{
     return this->fsobj->open_ar(this->parts);
 }
References fsobj.
Referenced by open().
open_r()
File openage::util::Path::open_r () const
Definition at line 133 of file path.cpp.
{
     return this->fsobj->open_r(this->parts);
 }
References fsobj.
Referenced by open(), and openage::audio::open_opus_file().
open_rw()
File openage::util::Path::open_rw () const
Definition at line 143 of file path.cpp.
{
     return this->fsobj->open_rw(this->parts);
 }
References fsobj.
open_w()
File openage::util::Path::open_w () const
Definition at line 138 of file path.cpp.
{
     return this->fsobj->open_w(this->parts);
 }
References fsobj.
Referenced by open().
operator !=()
bool openage::util::Path::operator != (const Path & other) const
Definition at line 334 of file path.cpp.
{
     return not (*this == other);
 }
operator []() [1/2]
Path openage::util::Path::operator [] (const parts_t & subpaths) const
Definition at line 307 of file path.cpp.
{
     return this->joinpath(subpaths);
 }
References joinpath().
operator []() [2/2]
Path openage::util::Path::operator [] (const part_t & subpath) const
Definition at line 311 of file path.cpp.
{
     return this->joinpath(subpath);
 }
References joinpath().
operator/()
Path openage::util::Path::operator/ (const part_t & subpath) const
Definition at line 315 of file path.cpp.
{
     return this->joinpath(subpath);
 }
References joinpath().
operator==()
bool openage::util::Path::operator== (const Path & other) const
Definition at line 327 of file path.cpp.
{
     return (
         this->fsobj == other.fsobj and
         this->parts == other.parts
     );
 }
References fsobj, and parts.
removerecursive()
void openage::util::Path::removerecursive ()
Definition at line 223 of file path.cpp.
{
     if (this->is_dir()) {
         for (auto &path : this->iterdir()) {
             path.removerecursive();
         }
         this->rmdir();
     }
     else {
         this->unlink();
     }
 }
References is_dir(), iterdir(), rmdir(), and unlink().
rename()
bool openage::util::Path::rename (const Path & target_path)
Definition at line 200 of file path.cpp.
{
     // check if both fsobj pointers are the same
     // maybe a real equality check is better?
     if (this->fsobj != target_path.fsobj) {
         throw Error{
             ERR << "can't rename across two different filesystem like objects"
         };
     }
     return this->fsobj->rename(this->parts, target_path.parts);
 }
References ERR, fsobj, and parts.
resolve_native_path()
std::string openage::util::Path::resolve_native_path (const std::string & mode = "r") const
Resolve the native path by flattening all underlying filesystem objects (like unions). Returns the /native/path/on/disk. Throws up if there is no native path.
This basically is the same as resolve_*().get_native_path().
Definition at line 163 of file path.cpp.
{
     if (mode == "r") {
         return this->resolve_native_path_r();
     }
     else if (mode == "w") {
         return this->resolve_native_path_w();
     }
     else {
         throw Error{ERR << "unsupported resolve mode: " << mode};
     }
 }
References ERR, resolve_native_path_r(), and resolve_native_path_w().
Referenced by openage::Texture::load(), openage::AssetManager::load_texture(), openage::audio::open_opus_file(), and openage::renderer::resources::Texture2dData::Texture2dData().
resolve_native_path_r()
std::string openage::util::Path::resolve_native_path_r () const
Definition at line 176 of file path.cpp.
{
     auto resolved_path = this->fsobj->resolve_r(this->parts);
     if (resolved_path.first) {
         return resolved_path.second.get_native_path();
     }
     else {
         throw Error{ERR << "failed to locate readable path: " << *this};
     }
 }
References ERR, and fsobj.
Referenced by resolve_native_path(), and openage.util.fslike.path.Path::resolve_native_path().
resolve_native_path_w()
std::string openage::util::Path::resolve_native_path_w () const
Definition at line 188 of file path.cpp.
{
     auto resolved_path = this->fsobj->resolve_w(this->parts);
     if (resolved_path.first) {
         return resolved_path.second.get_native_path();
     }
     else {
         throw Error{ERR << "failed to locate writable path: " << *this};
     }
 }
References ERR, and fsobj.
Referenced by resolve_native_path(), openage.util.fslike.path.Path::resolve_native_path(), and openage::renderer::resources::Texture2dData::store().
rmdir()
bool openage::util::Path::rmdir ()
Definition at line 211 of file path.cpp.
                  {
     return this->fsobj->rmdir(this->parts);
 }
References fsobj.
Referenced by removerecursive(), and openage.util.fslike.path.Path::removerecursive().
touch()
bool openage::util::Path::touch ()
Definition at line 215 of file path.cpp.
                  {
     return this->fsobj->touch(this->parts);
 }
References fsobj.
unlink()
bool openage::util::Path::unlink ()
Definition at line 219 of file path.cpp.
                   {
     return this->fsobj->unlink(this->parts);
 }
References fsobj.
Referenced by removerecursive(), and openage.util.fslike.path.Path::removerecursive().
with_name()
Path openage::util::Path::with_name (const part_t & name) const
Definition at line 319 of file path.cpp.
{
     return this->get_parent().joinpath(name);
 }
References get_parent(), and joinpath().
Referenced by with_suffix().
with_suffix()
Path openage::util::Path::with_suffix (const part_t & suffix) const
Definition at line 323 of file path.cpp.
{
     return this->with_name(this->get_stem() + suffix);
 }
References get_stem(), and with_name().
Referenced by openage::Texture::load().
writable()
bool openage::util::Path::writable () const
Definition at line 88 of file path.cpp.
{
     return this->fsobj->writable(this->parts);
 }
References fsobj.
Referenced by openage.util.fslike.wrapper.Wrapper::resolve_w(), and openage.util.fslike.abstract.FSLikeObject::resolve_w().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & stream, const Path & path) friend
Definition at line 349 of file path.cpp.
{
     stream << "Path(";
     path.fsobj->repr(stream);
     stream << ":";
     for (auto &part : path.parts) {
         stream << "/" << part;
     }
     stream << ")";
     return stream;
 }
Member Data Documentation
fsobj
std::shared_ptr<fslike::FSLike> openage::util::Path::fsobj protected
Definition at line 167 of file path.h.
Referenced by openage.util.fslike.path.Path::__eq__(), openage.util.fslike.path.Path::__repr__(), openage.util.fslike.path.Path::__str__(), openage.util.fslike.path.Path::_get_native_path(), openage.util.fslike.path.Path::_resolve_r(), openage.util.fslike.path.Path::_resolve_w(), openage.util.fslike.filecollection.FileCollectionPath::add_file(), openage.util.fslike.path.Path::exists(), openage.util.fslike.path.Path::filesize(), get_filesize(), get_fsobj(), get_mtime(), get_native_path(), openage.util.fslike.path.Path::is_dir(), is_dir(), is_file(), openage.util.fslike.path.Path::is_file(), iterdir(), openage.util.fslike.path.Path::iterdir(), joinpath(), openage.util.fslike.path.Path::joinpath(), list(), openage.util.fslike.path.Path::list(), mkdirs(), openage.util.fslike.path.Path::mkdirs(), openage.util.fslike.union.UnionPath::mount(), openage.util.fslike.path.Path::mtime(), openage.util.fslike.path.Path::open(), open_a(), open_ar(), open_r(), openage.util.fslike.path.Path::open_r(), open_rw(), open_w(), openage.util.fslike.path.Path::open_w(), openage::util::operator<<(), operator==(), openage.util.fslike.path.Path::parent(), Path(), openage.util.fslike.path.Path::poll_fs_watches(), rename(), openage.util.fslike.path.Path::rename(), resolve_native_path_r(), resolve_native_path_w(), rmdir(), openage.util.fslike.path.Path::rmdir(), touch(), openage.util.fslike.path.Path::touch(), unlink(), openage.util.fslike.path.Path::unlink(), openage.util.fslike.union.UnionPath::unmount(), openage.util.fslike.path.Path::watch(), writable(), and openage.util.fslike.path.Path::writable().
parts
parts_t openage::util::Path::parts protected
Definition at line 169 of file path.h.
Referenced by openage.util.fslike.path.Path::__eq__(), openage.util.fslike.path.Path::__repr__(), openage.util.fslike.path.Path::__str__(), openage.util.fslike.path.Path::_get_native_path(), openage.util.fslike.path.Path::_resolve_r(), openage.util.fslike.path.Path::_resolve_w(), openage.util.fslike.filecollection.FileCollectionPath::add_file(), openage.util.fslike.path.Path::exists(), openage.util.fslike.path.Path::filesize(), get_parts(), openage.util.fslike.path.Path::is_dir(), openage.util.fslike.path.Path::is_file(), openage.util.fslike.path.Path::iterdir(), joinpath(), openage.util.fslike.path.Path::joinpath(), openage.util.fslike.path.Path::list(), openage.util.fslike.path.Path::mkdirs(), openage.util.fslike.union.UnionPath::mount(), openage.util.fslike.path.Path::mtime(), openage.util.fslike.path.Path::name(), openage.util.fslike.path.Path::open(), openage.util.fslike.path.Path::open_r(), openage.util.fslike.path.Path::open_w(), openage::util::operator<<(), operator==(), openage.util.fslike.path.Path::parent(), rename(), openage.util.fslike.path.Path::rename(), openage.util.fslike.path.Path::rmdir(), openage.util.fslike.path.Path::touch(), openage.util.fslike.path.Path::unlink(), openage.util.fslike.union.UnionPath::unmount(), openage.util.fslike.path.Path::watch(), and openage.util.fslike.path.Path::writable().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/path.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/path.cpp