openage: openage::gui::EditorModeLink Class Reference
openage::gui::EditorModeLink Class Reference
#include <game_control_link.h>
Signals
void toggle ()
void categories_changed ()
void categories_content_changed ()
void category_content_changed (const std::string &category_name, std::vector< std::tuple< index_t, uint16_t >> type_and_texture)
Public Member Functions
EditorModeLink (QObject *parent=nullptr)
virtual ~EditorModeLink ()
int get_current_type_id () const
void set_current_type_id (int current_type_id)
int get_current_terrain_id () const
void set_current_terrain_id (int current_terrain_id)
bool get_paint_terrain () const
void set_paint_terrain (bool paint_terrain)
QStringList get_categories () const
void announce_category_content (const std::string &category_name)
Public Member Functions inherited from qtsdl::Inherits< OutputModeLink, EditorModeLink >
Inherits (QObject *parent=nullptr)
virtual ~Inherits ()
Public Member Functions inherited from qtsdl::Shadow< OutputModeLink >
Shadow (QObject *parent=nullptr)
void get (NullClass)
void i (NullClass)
void s (NullClass)
void sf (NullClass)
Public Member Functions inherited from qtsdl::GuiItemCoreInstantiator< EditorModeLink >
GuiItemCoreInstantiator (GuiItemBase *item_base)
Public Member Functions inherited from qtsdl::GuiItemMethods< EditorModeLink >
virtual ~GuiItemMethods ()
U * get () const
U * get ()
void i (F f, Args &&... args)
Properties
int currentTypeId
int currentTerrainId
bool paintTerrain
QStringList categories
Private Slots
void on_categories_changed (const std::vector< std::string > &categories)
Private Member Functions
virtual void on_core_adopted () override
Private Attributes
int current_type_id
int current_terrain_id
bool paint_terrain
Additional Inherited Members
Protected Member Functions inherited from qtsdl::GuiItemMethods< EditorModeLink >
void s (F f, P &p, A &&arg)
void sf (F f, P &p, A &&arg)
Detailed Description
Definition at line 171 of file game_control_link.h.
Constructor & Destructor Documentation
EditorModeLink()
openage::gui::EditorModeLink::EditorModeLink (QObject * parent = nullptr)
Definition at line 161 of file game_control_link.cpp.
     :
     Inherits{parent},
     current_type_id{-1},
     current_terrain_id{-1},
     paint_terrain{} {
     Q_UNUSED(registration_editor);
 }
~EditorModeLink()
openage::gui::EditorModeLink::~EditorModeLink () virtual
Definition at line 170 of file game_control_link.cpp.
{
 }
Member Function Documentation
announce_category_content()
void openage::gui::EditorModeLink::announce_category_content (const std::string & category_name)
Definition at line 210 of file game_control_link.cpp.
{
     static auto f = [] (EditorMode *_this, const std::string &category_name) {
         _this->announce_category_content(category_name);
     };
     this->i(f, category_name);
 }
References openage::EditorMode::announce_category_content(), and qtsdl::Shadow< OutputModeLink >::i().
Referenced by openage::gui::CategoryContentsListModel::on_categories_content_changed().
categories_changed
void openage::gui::EditorModeLink::categories_changed () signal
Referenced by on_categories_changed().
categories_content_changed
void openage::gui::EditorModeLink::categories_content_changed () signal
Referenced by on_core_adopted(), and openage::gui::CategoryContentsListModel::set_editor_mode().
category_content_changed
void openage::gui::EditorModeLink::category_content_changed (const std::string & category_name, std::vector< std::tuple< index_t, uint16_t >> type_and_texture) signal
Referenced by on_core_adopted(), and openage::gui::CategoryContentsListModel::set_editor_mode().
get_categories()
QStringList openage::gui::EditorModeLink::get_categories () const
Definition at line 206 of file game_control_link.cpp.
{
     return this->categories;
 }
References categories.
get_current_terrain_id()
int openage::gui::EditorModeLink::get_current_terrain_id () const
Definition at line 184 of file game_control_link.cpp.
{
     return this->current_terrain_id;
 }
References current_terrain_id.
get_current_type_id()
int openage::gui::EditorModeLink::get_current_type_id () const
Definition at line 173 of file game_control_link.cpp.
{
     return this->current_type_id;
 }
References current_type_id.
get_paint_terrain()
bool openage::gui::EditorModeLink::get_paint_terrain () const
Definition at line 195 of file game_control_link.cpp.
{
     return this->paint_terrain;
 }
References paint_terrain.
on_categories_changed
void openage::gui::EditorModeLink::on_categories_changed (const std::vector< std::string > & categories) private slot
Definition at line 217 of file game_control_link.cpp.
{
     this->categories.clear();
     std::transform(std::begin(categories), std::end(categories), std::back_inserter(this->categories), [] (const std::string &s) {return QString::fromStdString(s);});
     emit this->categories_changed();
 }
References categories, categories_changed(), and qtsdl::Shadow< OutputModeLink >::s().
Referenced by on_core_adopted().
on_core_adopted()
void openage::gui::EditorModeLink::on_core_adopted () override private virtual
Definition at line 223 of file game_control_link.cpp.
{
     this->Inherits::on_core_adopted();
     QObject::connect(&unwrap(this)->gui_signals, &EditorModeSignals::toggle, this, &EditorModeLink::toggle);
     QObject::connect(&unwrap(this)->gui_signals, &EditorModeSignals::categories_changed, this, &EditorModeLink::on_categories_changed);
     QObject::connect(&unwrap(this)->gui_signals, &EditorModeSignals::categories_content_changed, this, &EditorModeLink::categories_content_changed);
     QObject::connect(&unwrap(this)->gui_signals, &EditorModeSignals::category_content_changed, this, &EditorModeLink::category_content_changed);
 }
References openage::EditorModeSignals::categories_changed(), categories_content_changed(), openage::EditorModeSignals::categories_content_changed(), category_content_changed(), openage::EditorModeSignals::category_content_changed(), on_categories_changed(), toggle(), openage::EditorModeSignals::toggle(), and qtsdl::unwrap().
set_current_terrain_id()
void openage::gui::EditorModeLink::set_current_terrain_id (int current_terrain_id)
Definition at line 188 of file game_control_link.cpp.
{
     static auto f = [](EditorMode* _this, int current_terrain_id) {
         _this->set_current_terrain_id(current_terrain_id);
     };
     this->s(f, this->current_terrain_id, current_terrain_id);
 }
References current_terrain_id, qtsdl::Shadow< OutputModeLink >::s(), and openage::EditorMode::set_current_terrain_id().
set_current_type_id()
void openage::gui::EditorModeLink::set_current_type_id (int current_type_id)
Definition at line 177 of file game_control_link.cpp.
{
     static auto f = [](EditorMode* _this, int current_type_id) {
         _this->set_current_type_id(current_type_id);
     };
     this->s(f, this->current_type_id, current_type_id);
 }
References current_type_id, qtsdl::Shadow< OutputModeLink >::s(), and openage::EditorMode::set_current_type_id().
set_paint_terrain()
void openage::gui::EditorModeLink::set_paint_terrain (bool paint_terrain)
Definition at line 199 of file game_control_link.cpp.
{
     static auto f = [](EditorMode* _this, int paint_terrain) {
         _this->set_paint_terrain(paint_terrain);
     };
     this->s(f, this->paint_terrain, paint_terrain);
 }
References paint_terrain, qtsdl::Shadow< OutputModeLink >::s(), and openage::EditorMode::set_paint_terrain().
toggle
void openage::gui::EditorModeLink::toggle () signal
Referenced by on_core_adopted().
Member Data Documentation
current_terrain_id
int openage::gui::EditorModeLink::current_terrain_id private
Definition at line 209 of file game_control_link.h.
Referenced by get_current_terrain_id(), and set_current_terrain_id().
current_type_id
int openage::gui::EditorModeLink::current_type_id private
Definition at line 208 of file game_control_link.h.
Referenced by get_current_type_id(), and set_current_type_id().
paint_terrain
bool openage::gui::EditorModeLink::paint_terrain private
Definition at line 210 of file game_control_link.h.
Referenced by get_paint_terrain(), and set_paint_terrain().
Property Documentation
categories
QStringList openage::gui::EditorModeLink::categories read
Definition at line 177 of file game_control_link.h.
Referenced by get_categories(), and on_categories_changed().
currentTerrainId
int openage::gui::EditorModeLink::currentTerrainId read write
Definition at line 175 of file game_control_link.h.
currentTypeId
int openage::gui::EditorModeLink::currentTypeId read write
Definition at line 174 of file game_control_link.h.
paintTerrain
bool openage::gui::EditorModeLink::paintTerrain read write
Definition at line 176 of file game_control_link.h.
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/game_control_link.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/game_control_link.cpp