openage: openage::gui::GuiGameSpecImageProviderImpl Class Reference
openage::gui::GuiGameSpecImageProviderImpl Class Reference abstract
Exposes game textures to the Qt.
#include <gui_game_spec_image_provider_impl.h>
Public Member Functions
GuiGameSpecImageProviderImpl (qtsdl::GuiEventQueue *render_updater)
virtual ~GuiGameSpecImageProviderImpl ()
void on_game_spec_loaded (const std::shared_ptr< GameSpec > &loaded_game_spec)
Unblocks the provider.
void on_game_spec_invalidated ()
Set to every sprite the 'missing texture' from current spec.
GuiFilledTextureHandleUser fill_texture_handle (const QString &id, const QSize &requested_size, SizedTextureHandle *filled_handle)
Fills in the provided handle object.
Public Member Functions inherited from qtsdl::GuiImageProviderImpl
GuiImageProviderImpl ()
virtual ~GuiImageProviderImpl ()
virtual const char * get_id () const =0
Protected Member Functions
TextureHandle get_missing_texture ()
Protected Attributes
std::shared_ptr< GameSpec > loaded_game_spec
bool invalidated
When true, still uses the old source but shows the 'missing texture'.
Private Member Functions
virtual TextureHandle get_texture_handle (const QString &id)=0
virtual QQuickTextureFactory * requestTexture (const QString &id, QSize *size, const QSize &requestedSize) override
virtual void give_up () override
void migrate_to_new_game_spec (const std::shared_ptr< GameSpec > &loaded_game_spec)
Change the already produced texture handles to use new source.
void overwrite_texture_handle (const QString &id, const QSize &requested_size, SizedTextureHandle *filled_handle)
Private Attributes
std::shared_ptr< GuiFilledTextureHandles > filled_handles
Changing the texture handles underneath the QSGTexture to reflect the reload of the GameSpec.
std::mutex loaded_game_spec_mutex
std::condition_variable loaded_game_spec_cond
bool ended
qtsdl::GuiCallback render_thread_callback
Additional Inherited Members
Static Public Member Functions inherited from qtsdl::GuiImageProviderImpl
static std::unique_ptr< GuiImageProviderImpl > take_ownership (GuiImageProvider *image_provider)
static std::vector< std::unique_ptr< GuiImageProviderImpl > > take_ownership (const std::vector< GuiImageProvider * > &image_providers)
Detailed Description
Exposes game textures to the Qt.
Definition at line 35 of file gui_game_spec_image_provider_impl.h.
Constructor & Destructor Documentation
GuiGameSpecImageProviderImpl()
openage::gui::GuiGameSpecImageProviderImpl::GuiGameSpecImageProviderImpl (qtsdl::GuiEventQueue * render_updater) explicit
Definition at line 20 of file gui_game_spec_image_provider_impl.cpp.
     :
     GuiImageProviderImpl{},
     invalidated{},
     filled_handles{std::make_shared<GuiFilledTextureHandles>()},
     ended{} {
     QThread *render_thread = qtsdl::GuiEventQueueImpl::impl(render_updater)->get_thread();
     this->render_thread_callback.moveToThread(render_thread);
     QObject::connect(&this->render_thread_callback, &qtsdl::GuiCallback::process_blocking, &this->render_thread_callback, &qtsdl::GuiCallback::process, render_thread != QThread::currentThread() ? Qt::BlockingQueuedConnection : Qt::DirectConnection);
 }
~GuiGameSpecImageProviderImpl()
openage::gui::GuiGameSpecImageProviderImpl::~GuiGameSpecImageProviderImpl () virtual
Definition at line 32 of file gui_game_spec_image_provider_impl.cpp.
{
 }
Member Function Documentation
fill_texture_handle()
GuiFilledTextureHandleUser openage::gui::GuiGameSpecImageProviderImpl::fill_texture_handle (const QString & id, const QSize & requested_size, SizedTextureHandle * filled_handle)
Fills in the provided handle object.
Memorizes pointer to it in order to update it if the source changes.
Returns
pointer to all memorized handles, so the client can unsubscribe.
Definition at line 86 of file gui_game_spec_image_provider_impl.cpp.
{
     this->overwrite_texture_handle(id, requested_size, filled_handle);
     return GuiFilledTextureHandleUser(this->filled_handles, id, requested_size, filled_handle);
 }
References filled_handles, and overwrite_texture_handle().
Referenced by openage::gui::GuiTextureFactory::GuiTextureFactory().
get_missing_texture()
TextureHandle openage::gui::GuiGameSpecImageProviderImpl::get_missing_texture () protected
Definition at line 91 of file gui_game_spec_image_provider_impl.cpp.
{
     return TextureHandle{this->loaded_game_spec->get_texture("missing.png", false), -1};
 }
References loaded_game_spec.
Referenced by openage::gui::GuiGameSpecImageProviderByIdImpl::get_texture_handle(), openage::gui::GuiGameSpecImageProviderByFilenameImpl::get_texture_handle(), and on_game_spec_invalidated().
get_texture_handle()
virtual TextureHandle openage::gui::GuiGameSpecImageProviderImpl::get_texture_handle (const QString & id) private pure virtual
Implemented in openage::gui::GuiGameSpecImageProviderByFilenameImpl, and openage::gui::GuiGameSpecImageProviderByIdImpl.
Referenced by overwrite_texture_handle().
give_up()
void openage::gui::GuiGameSpecImageProviderImpl::give_up () override private virtual
Implements qtsdl::GuiImageProviderImpl.
Definition at line 110 of file gui_game_spec_image_provider_impl.cpp.
{
     {
         std::unique_lock<std::mutex> lck{this->loaded_game_spec_mutex};
         this->ended = true;
     }
     this->loaded_game_spec_cond.notify_one();
 }
References ended, loaded_game_spec_cond, and loaded_game_spec_mutex.
migrate_to_new_game_spec()
void openage::gui::GuiGameSpecImageProviderImpl::migrate_to_new_game_spec (const std::shared_ptr< GameSpec > & loaded_game_spec) private
Change the already produced texture handles to use new source.
Definition at line 49 of file gui_game_spec_image_provider_impl.cpp.
{
     ENSURE(loaded_game_spec, "spec hasn't been checked or was invalidated");
     if (this->loaded_game_spec) {
         auto keep_old_game_spec = this->loaded_game_spec;
         // Need to set up this because the load functions use this->loaded_game_spec internally.
         this->loaded_game_spec = loaded_game_spec;
         emit this->render_thread_callback.process_blocking([this] {
             using namespace std::placeholders;
             this->filled_handles->refresh_all_handles_with_texture(std::bind(&GuiGameSpecImageProviderImpl::overwrite_texture_handle, this, _1, _2, _3));
         });
     } else {
         this->loaded_game_spec = loaded_game_spec;
     }
 }
References openage::renderer::bind(), ENSURE, filled_handles, loaded_game_spec, overwrite_texture_handle(), qtsdl::GuiCallback::process_blocking(), and render_thread_callback.
Referenced by on_game_spec_loaded().
on_game_spec_invalidated()
void openage::gui::GuiGameSpecImageProviderImpl::on_game_spec_invalidated ()
Set to every sprite the 'missing texture' from current spec.
Needed as a visible reaction to setting the property to null. We can't unload the textures without recreating the engine, so we keep the old source.
Definition at line 72 of file gui_game_spec_image_provider_impl.cpp.
{
     std::unique_lock<std::mutex> lck{this->loaded_game_spec_mutex};
     if (this->loaded_game_spec) {
         const TextureHandle missing_texture = get_missing_texture();
         emit this->render_thread_callback.process_blocking([this, &missing_texture] {
             this->filled_handles->fill_all_handles_with_texture(missing_texture);
         });
         invalidated = true;
     }
 }
References filled_handles, get_missing_texture(), invalidated, loaded_game_spec, loaded_game_spec_mutex, qtsdl::GuiCallback::process_blocking(), and render_thread_callback.
Referenced by openage::gui::GuiImageProviderLink::set_game_spec().
on_game_spec_loaded()
void openage::gui::GuiGameSpecImageProviderImpl::on_game_spec_loaded (const std::shared_ptr< GameSpec > & loaded_game_spec)
Unblocks the provider.
Refreshes already loaded assets (if this->loaded_game_spec wasn't null before the call).
Parameters
loaded_game_spec new source (can't be null)
Definition at line 35 of file gui_game_spec_image_provider_impl.cpp.
{
     ENSURE(loaded_game_spec, "spec hasn't been checked or was invalidated");
     std::unique_lock<std::mutex> lck{this->loaded_game_spec_mutex};
     if (invalidated || loaded_game_spec != this->loaded_game_spec) {
         migrate_to_new_game_spec(loaded_game_spec);
         invalidated = false;
         lck.unlock();
         this->loaded_game_spec_cond.notify_one();
     }
 }
References ENSURE, invalidated, loaded_game_spec, loaded_game_spec_cond, loaded_game_spec_mutex, and migrate_to_new_game_spec().
Referenced by openage::gui::GuiImageProviderLink::on_game_spec_loaded(), and openage::gui::GuiImageProviderLink::set_game_spec().
overwrite_texture_handle()
void openage::gui::GuiGameSpecImageProviderImpl::overwrite_texture_handle (const QString & id, const QSize & requested_size, SizedTextureHandle * filled_handle) private
Definition at line 67 of file gui_game_spec_image_provider_impl.cpp.
{
     const TextureHandle texture_handle = this->get_texture_handle(id);
     *filled_handle = {texture_handle, aspect_fit_size(texture_handle, requested_size)};
 }
References openage::gui::aspect_fit_size(), and get_texture_handle().
Referenced by fill_texture_handle(), and migrate_to_new_game_spec().
requestTexture()
QQuickTextureFactory * openage::gui::GuiGameSpecImageProviderImpl::requestTexture (const QString & id, QSize * size, const QSize & requestedSize) override private virtual
Definition at line 95 of file gui_game_spec_image_provider_impl.cpp.
{
     std::unique_lock<std::mutex> lck{this->loaded_game_spec_mutex};
     this->loaded_game_spec_cond.wait(lck, [this] {return this->ended || this->loaded_game_spec;});
     if (this->ended) {
         qWarning("ImageProvider was stopped during the load, so it'll appear like the requestTexture() isn't implemented.");
         return this->GuiImageProviderImpl::requestTexture(id, size, requestedSize);
     } else {
         auto tex_factory = new GuiTextureFactory{this, id, requestedSize};
         *size = tex_factory->textureSize();
         return tex_factory;
     }
 }
References ended, loaded_game_spec, loaded_game_spec_cond, loaded_game_spec_mutex, and openage::gui::GuiTextureFactory::textureSize().
Member Data Documentation
ended
bool openage::gui::GuiGameSpecImageProviderImpl::ended private
Definition at line 98 of file gui_game_spec_image_provider_impl.h.
Referenced by give_up(), and requestTexture().
filled_handles
std::shared_ptr<GuiFilledTextureHandles> openage::gui::GuiGameSpecImageProviderImpl::filled_handles private
Changing the texture handles underneath the QSGTexture to reflect the reload of the GameSpec.
It's not a proper Qt usage, so the live reload of the game assets for the gui may break in future Qt releases. When it breaks, this feature should be implemented via the recreation of the qml engine.
Definition at line 94 of file gui_game_spec_image_provider_impl.h.
Referenced by fill_texture_handle(), migrate_to_new_game_spec(), and on_game_spec_invalidated().
invalidated
bool openage::gui::GuiGameSpecImageProviderImpl::invalidated protected
When true, still uses the old source but shows the 'missing texture'.
Definition at line 74 of file gui_game_spec_image_provider_impl.h.
Referenced by on_game_spec_invalidated(), and on_game_spec_loaded().
loaded_game_spec
std::shared_ptr<GameSpec> openage::gui::GuiGameSpecImageProviderImpl::loaded_game_spec protected
Definition at line 69 of file gui_game_spec_image_provider_impl.h.
Referenced by get_missing_texture(), openage::gui::GuiGameSpecImageProviderByGraphicIdImpl::get_texture(), openage::gui::GuiGameSpecImageProviderByTerrainIdImpl::get_texture(), openage::gui::GuiGameSpecImageProviderByIdImpl::get_texture_handle(), openage::gui::GuiGameSpecImageProviderByFilenameImpl::get_texture_handle(), migrate_to_new_game_spec(), on_game_spec_invalidated(), on_game_spec_loaded(), and requestTexture().
loaded_game_spec_cond
std::condition_variable openage::gui::GuiGameSpecImageProviderImpl::loaded_game_spec_cond private
Definition at line 97 of file gui_game_spec_image_provider_impl.h.
Referenced by give_up(), on_game_spec_loaded(), and requestTexture().
loaded_game_spec_mutex
std::mutex openage::gui::GuiGameSpecImageProviderImpl::loaded_game_spec_mutex private
Definition at line 96 of file gui_game_spec_image_provider_impl.h.
Referenced by give_up(), on_game_spec_invalidated(), on_game_spec_loaded(), and requestTexture().
render_thread_callback
qtsdl::GuiCallback openage::gui::GuiGameSpecImageProviderImpl::render_thread_callback private
Definition at line 100 of file gui_game_spec_image_provider_impl.h.
Referenced by migrate_to_new_game_spec(), and on_game_spec_invalidated().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/integration/private/gui_game_spec_image_provider_impl.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/integration/private/gui_game_spec_image_provider_impl.cpp