openage: openage::curve::Queue< T > Class Template Reference
openage::curve::Queue< T > Class Template Reference
#include <queue.h>
Classes
struct queue_wrapper
Public Types
using container_t = typename std::deque< queue_wrapper >
using const_iterator = typename container_t::const_iterator
using iterator = typename container_t::const_iterator
Public Member Functions
const T & front (const time_t &) const
QueueFilterIterator< T, Queue< T > > begin (const time_t &t=-std::numeric_limits< time_t >::max()) const
QueueFilterIterator< T, Queue< T > > end (const time_t &t=std::numeric_limits< time_t >::max()) const
QueueFilterIterator< T, Queue< T > > between (const time_t &begin=std::numeric_limits< time_t >::max(), const time_t &end=std::numeric_limits< time_t >::max()) const
void erase (const CurveIterator< T, Queue< T >> &)
QueueFilterIterator< T, Queue< T > > insert (const time_t &, const T &e)
void clear ()
void clean (const time_t &)
void dump ()
Private Attributes
container_t container
Detailed Description
template<class T>
class openage::curve::Queue< T >
A container that manages events on a timeline. Every event has exactly one time it will happen. This container can be used to store interactions
Definition at line 19 of file queue.h.
Member Typedef Documentation
const_iterator
template<class T> using openage::curve::Queue< T >::const_iterator = typename container_t::const_iterator
Definition at line 36 of file queue.h.
container_t
template<class T> using openage::curve::Queue< T >::container_t = typename std::deque<queue_wrapper>
Definition at line 35 of file queue.h.
iterator
template<class T> using openage::curve::Queue< T >::iterator = typename container_t::const_iterator
Definition at line 37 of file queue.h.
Member Function Documentation
begin()
template<typename T > QueueFilterIterator< T, Queue< T > > openage::curve::Queue< T >::begin (const time_t & t = -std::numeric_limits<time_t>::max()) const
Definition at line 79 of file queue.h.
{
     for (auto it = this->container.begin(); it != this->container.end(); ++it) {
         if (it->time() >= t) {
             return QueueFilterIterator<T, Queue<T>>(
                 it,
                 this,
                 t,
                 std::numeric_limits<time_t>::max());
         }
     }
     return this->end(t);
 }
References openage::curve::tests::container(), and openage::console::tests::max().
Referenced by openage::curve::tests::test_queue().
between()
template<typename T > QueueFilterIterator< T, Queue< T > > openage::curve::Queue< T >::between (const time_t & begin = std::numeric_limits<time_t>::max(), const time_t & end = std::numeric_limits<time_t>::max()) const
Definition at line 105 of file queue.h.
{
     auto it = QueueFilterIterator<T, Queue<T>>(
         container.begin(),
         this,
         begin,
         end);
     if (!container.empty() && !it.valid()) {
         ++it;
     }
     return it;
 }
References openage::curve::tests::container().
Referenced by openage::curve::tests::test_queue().
clean()
template<typename T > void openage::curve::Queue< T >::clean (const time_t & time)
Definition at line 164 of file queue.h.
{
     for (auto it = this->container.begin();
          it != this->container.end() and it->time() < time;
          it = this->container.erase(it))
     {}
 }
References openage::curve::tests::container().
clear()
template<typename T > void openage::curve::Queue< T >::clear ()
Definition at line 158 of file queue.h.
                      {
     this->container.clear();
 }
References openage::curve::tests::container().
dump()
template<class T> void openage::curve::Queue< T >::dump () inline
Definition at line 61 of file queue.h.
                 {
         for (auto i : container) {
             std::cout << i.value << " at " << i.time() << std::endl;
         }
     }
References openage::curve::Queue< T >::container.
Referenced by openage.convert.texture.Texture::save().
end()
template<typename T > QueueFilterIterator< T, Queue< T > > openage::curve::Queue< T >::end (const time_t & t = std::numeric_limits<time_t>::max()) const
Definition at line 95 of file queue.h.
{
     return QueueFilterIterator<T, Queue<T>>(
         container.end(),
         this,
         t,
         std::numeric_limits<time_t>::max());
 }
References openage::curve::tests::container(), and openage::console::tests::max().
Referenced by openage::curve::tests::test_queue().
erase()
template<typename T > void openage::curve::Queue< T >::erase (const CurveIterator< T, Queue< T >> & t)
Definition at line 122 of file queue.h.
{
     auto it = container.erase(t.base());
     return;
 }
References openage::curve::tests::container().
front()
template<typename T > const T & openage::curve::Queue< T >::front (const time_t &) const
Definition at line 73 of file queue.h.
{
     return container.front();
 }
References openage::curve::tests::container().
insert()
template<typename T > QueueFilterIterator< T, Queue< T > > openage::curve::Queue< T >::insert (const time_t & time, const T & e)
Definition at line 129 of file queue.h.
                 {
     const_iterator insertion_point = this->container.end();
     for (auto it = this->container.begin(); it != this->container.end(); ++it) {
         if (time < it->time()) {
             insertion_point = this->container.insert(it, queue_wrapper(time, e));
             break;
         }
     }
     if (insertion_point == this->container.end()) {
         insertion_point = this->container.insert(this->container.end(),
                                                  queue_wrapper(time, e));
     }
     auto ct = QueueFilterIterator<T, Queue<T>>(
         insertion_point,
         this,
         time, std::numeric_limits<time_t>::max());
     if (!ct.valid()) {
         ++ct;
     }
     return ct;
 }
References openage::curve::tests::container(), and openage::console::tests::max().
Referenced by openage::curve::tests::test_queue().
Member Data Documentation
container
template<class T> container_t openage::curve::Queue< T >::container private
Definition at line 68 of file queue.h.
Referenced by openage::curve::Queue< T >::dump().
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/curve/queue.h