openage: openage::event::Loop Class Reference
openage::event::Loop Class Reference
The core class to manage event class and targets.
#include <loop.h>
Public Member Functions
void add_event_class (const std::shared_ptr< EventClass > &cls)
register a new event class
std::weak_ptr< Event > create_event (const std::string &name, const std::shared_ptr< EventTarget > &target, const std::shared_ptr< State > &state, const curve::time_t &reference_time, const EventClass::param_map &params=EventClass::param_map({}))
Add a new Event to the queue.
std::weak_ptr< Event > create_event (const std::shared_ptr< EventClass > &eventclass, const std::shared_ptr< EventTarget > &target, const std::shared_ptr< State > &state, const curve::time_t &reference_time, const EventClass::param_map &params=EventClass::param_map({}))
This will generate a new randomly named eventclass for this specific element.
void onfilter (const std::shared_ptr< EventClass > &eventclass, const EventFilter &)
template<class evntclass_t >
void onfilter (const EventFilter &filter)
void register_object (const std::shared_ptr< EventTarget > &)
void reach_time (const curve::time_t &max_time, const std::shared_ptr< State > &state)
Execute all events that are registered until a certain point in time.
template<class T >
void create_change (const std::shared_ptr< Event > &event, const curve::time_t &changes_at, const T &new_value)
Register that a given event must be reevaluated at a time, this usually happens because this event depended on an eventtarget that got changed at this time.
const EventQueue & get_queue () const
Private Member Functions
int execute_events (const curve::time_t &max_time, const std::shared_ptr< State > &state)
Execute the events.
void update_changes (const std::shared_ptr< State > &state)
Call all the time change functions.
Private Attributes
std::unordered_map< std::string, std::shared_ptr< EventClass > > classstore
Here we do the bookkeeping of registered event classes.
std::list< EventFilter > filters
Here we store all running filters that shall be applied whenever a new obejct is added to our objectstore.
EventQueue queue
All events are enqueued here.
std::shared_ptr< Event > active_event
The currently processed event.
std::unordered_map< uint64_t, std::weak_ptr< EventTarget > > curveindex
Friends
int demo::curvepong ()
Detailed Description
The core class to manage event class and targets.
Definition at line 32 of file loop.h.
Member Function Documentation
add_event_class()
void openage::event::Loop::add_event_class (const std::shared_ptr< EventClass > & cls)
register a new event class
Definition at line 16 of file loop.cpp.
{
     classstore.insert(std::make_pair(cls->id(), cls));
 }
References classstore.
create_change()
template<typename T > void openage::event::Loop::create_change (const std::shared_ptr< Event > & event, const curve::time_t & changes_at, const T & new_value)
Register that a given event must be reevaluated at a time, this usually happens because this event depended on an eventtarget that got changed at this time.
This inserts the event into the changes queue so it will be evaluated in the next loop iteration.
Definition at line 137 of file loop.h.
{
     log::log(DBG << "Loop: registering change of " << evnt->get_eventclass()->id()
              << " at t=" << changes_at << " to " << new_value);
     this->queue.add_change(evnt, changes_at);
 }
References openage::event::EventQueue::add_change(), DBG, openage::log::log(), and queue.
create_event() [1/2]
std::weak_ptr< Event > openage::event::Loop::create_event (const std::string & name, const std::shared_ptr< EventTarget > & target, const std::shared_ptr< State > & state, const curve::time_t & reference_time, const EventClass::param_map & params = EventClass::param_map({}))
Add a new Event to the queue.
The event is from the given class (name) and is invoked for a target in a state.
The reference_time is used to calculate the actual event time.
Definition at line 21 of file loop.cpp.
{
     auto it = classstore.find(name);
     if (it == classstore.end()) {
         throw Error{MSG(err) << "Trying to subscribe to eventclass "
                              << name << ", which does not exist."};
     }
     return this->queue.create_event(target, it->second, state, reference_time, params);
 }
References classstore, openage::event::EventQueue::create_event(), openage::log::err(), MSG, and queue.
Referenced by openage::event::demo::Physics::reset().
create_event() [2/2]
std::weak_ptr< Event > openage::event::Loop::create_event (const std::shared_ptr< EventClass > & eventclass, const std::shared_ptr< EventTarget > & target, const std::shared_ptr< State > & state, const curve::time_t & reference_time, const EventClass::param_map & params = EventClass::param_map({}))
This will generate a new randomly named eventclass for this specific element.
The reference_time is used to determine the actual event trigger time.
Definition at line 36 of file loop.cpp.
{
     auto it = this->classstore.find(eventclass->id());
     if (it == this->classstore.end()) {
         auto res = this->classstore.insert(std::make_pair(eventclass->id(), eventclass));
         if (res.second) {
             it = res.first;
         } else {
             throw Error{ERR << "could not insert eventclass into class store"};
         }
     }
     return this->queue.create_event(target, it->second, state, reference_time, params);
 }
References classstore, openage::event::EventQueue::create_event(), ERR, and queue.
execute_events()
int openage::event::Loop::execute_events (const curve::time_t & max_time, const std::shared_ptr< State > & state) private
Execute the events.
Returns
number of events processed
Definition at line 90 of file loop.cpp.
{
     log::log(DBG << "Loop: Pending events in the queue (# = "
              << this->queue.get_event_queue().size() << "):");
     {
         size_t i = 0;
         for (const auto &e : this->queue.get_event_queue().get_sorted_events()) {
             log::log(DBG << "  event "
                      << i << ": t=" << e->get_time() << ": " << e->get_eventclass()->id());
             i++;
         }
     }
     int cnt = 0;
     while (true) {
         // fetch an event from the queue that happens before <= time_until
         std::shared_ptr<Event> event = this->queue.take_event(time_until);
         if (event == nullptr) {
             break;
         }
         auto target = event->get_target().lock();
         if (target) {
             log::log(DBG << "Loop: invoking event \"" << event->get_eventclass()->id()
                      << "\" on target \"" << target->id()
                      << "\" for time t=" << event->get_time());
             this->active_event = event;
             // apply the event effects
             event->get_eventclass()->invoke(
                 *this, target, state,
                 event->get_time(), event->get_params()
             );
             this->active_event = nullptr;
             cnt += 1;
             // if the event is REPEAT, readd the event.
             if (event->get_eventclass()->type == EventClass::trigger_type::REPEAT) {
                 curve::time_t new_time = event->get_eventclass()->predict_invoke_time(
                     target, state, event->get_time()
                 );
                 if (new_time != std::numeric_limits<curve::time_t>::min()) {
                     event->set_time(new_time);
                     log::log(DBG << "Loop: repeating event \"" << event->get_eventclass()->id()
                              << "\" on target \"" << target->id()
                              << "\" will be reenqueued for time t=" << event->get_time());
                     this->queue.reenqueue(event);
                 }
             }
         }
         else {
             // The element was already removed from the queue, so we can safely
             // kill it by ignoring it.
         }
     }
     return cnt;
 }
References active_event, DBG, openage::event::EventQueue::get_event_queue(), openage::event::EventStore::get_sorted_events(), openage::log::log(), std::min(), queue, openage::event::EventQueue::reenqueue(), openage::event::EventClass::REPEAT, openage::event::EventStore::size(), and openage::event::EventQueue::take_event().
Referenced by reach_time().
get_queue()
const EventQueue& openage::event::Loop::get_queue () const inline
Definition at line 92 of file loop.h.
{
         return this->queue;
     }
References queue.
onfilter() [1/2]
void openage::event::Loop::onfilter (const std::shared_ptr< EventClass > & eventclass, const EventFilter &)
Referenced by onfilter().
onfilter() [2/2]
template<class evntclass_t > void openage::event::Loop::onfilter (const EventFilter & filter) inline
Definition at line 68 of file loop.h.
{
         this->onfilter(std::make_shared<evntclass_t>(), filter);
     }
References onfilter().
reach_time()
void openage::event::Loop::reach_time (const curve::time_t & max_time, const std::shared_ptr< State > & state)
Execute all events that are registered until a certain point in time.
Definition at line 56 of file loop.cpp.
{
     // \todo detect infinite loops (is this a halting problem?)
     // this happens when the events don't settle:
     // at least one processed event adds another event so
     // the queue never stops adding changes
     // simple "solution": abort after over 9000 attempts.
     int cnt = 0;
     int attempts = 0;
     do {
         log::log(DBG << "Loop: Attempt " << attempts << " to reach t=" << max_time);
         this->update_changes(state);
         cnt = this->execute_events(max_time, state);
         log::log(DBG << "Loop: to reach t=" << max_time
                  << ", n=" << cnt << " events were executed");
         if (attempts > 9000) {
             log::log(WARN << "Loop: reached event settling threshold, giving up.");
             break;
         }
         attempts += 1;
     } while (cnt != 0);
     // Swap in the end of the execution, else we might skip changes that happen
     // in the main loop for one frame - which is bad btw.
     this->queue.swap_changesets();
     log::log(DBG << "Loop: t=" << max_time << " was reached! ========");
 }
References DBG, execute_events(), openage::log::log(), queue, openage::event::EventQueue::swap_changesets(), update_changes(), and WARN.
register_object()
void openage::event::Loop::register_object (const std::shared_ptr< EventTarget > &)
update_changes()
void openage::event::Loop::update_changes (const std::shared_ptr< State > & state) private
Call all the time change functions.
This is constant on the state!
Definition at line 158 of file loop.cpp.
{
     log::log(DBG << "Loop: " << this->queue.get_changes().size()
              << " target changes have to be processed");
     size_t i = 0;
     // reevaluate depending events beecause of the change
     for (const auto &change : this->queue.get_changes()) {
         auto evnt = change.evnt.lock();
         if (evnt) {
             log::log(DBG << "  change " << i++ << ": " << evnt->get_eventclass()->id());
             switch(evnt->get_eventclass()->type) {
             case EventClass::trigger_type::ONCE:
             case EventClass::trigger_type::DEPENDENCY: {
                 auto target = evnt->get_target().lock();
                 // \todo what happens when the target is degraded?
                 if (target) {
                     curve::time_t new_time = evnt->get_eventclass()
                                                  ->predict_invoke_time(target, state, change.time);
                     if (new_time != std::numeric_limits<curve::time_t>::min()) {
                         log::log(DBG << "Loop: due to a change, rescheduling event of '"
                                  << evnt->get_eventclass()->id()
                                  << "' on target '" << target->id()
                                  << "' at time t=" << change.time
                                  << " to NEW TIME t=" << new_time);
                         evnt->set_time(new_time);
                         this->queue.enqueue_change(evnt);
                     }
                     else {
                         log::log(DBG << "Loop: due to a change, canceled execution of '"
                                  << evnt->get_eventclass()->id()
                                  << "' on target '" << target->id()
                                  << "' at time t=" << change.time);
                         this->queue.remove(evnt);
                     }
                 }
             } break;
             case EventClass::trigger_type::TRIGGER:
             case EventClass::trigger_type::DEPENDENCY_IMMEDIATELY:
                 evnt->set_time(change.time);
                 this->queue.enqueue_change(evnt);
                 break;
             case EventClass::trigger_type::REPEAT:
                 break;
             }
         }
     }
     this->queue.clear_changes();
 }
References openage::event::EventQueue::clear_changes(), DBG, openage::event::EventClass::DEPENDENCY, openage::event::EventClass::DEPENDENCY_IMMEDIATELY, openage::event::EventQueue::enqueue_change(), openage::event::EventQueue::get_changes(), openage::log::log(), std::min(), openage::event::EventClass::ONCE, queue, openage::event::EventQueue::remove(), openage::event::EventClass::REPEAT, and openage::event::EventClass::TRIGGER.
Referenced by reach_time().
Friends And Related Function Documentation
demo::curvepong
int demo::curvepong () friend
Member Data Documentation
active_event
std::shared_ptr<Event> openage::event::Loop::active_event private
The currently processed event.
This is useful for event cancelations (so one can't cancel itself).
Definition at line 130 of file loop.h.
Referenced by execute_events().
classstore
std::unordered_map<std::string, std::shared_ptr<EventClass> > openage::event::Loop::classstore private
Here we do the bookkeeping of registered event classes.
Definition at line 113 of file loop.h.
Referenced by add_event_class(), and create_event().
curveindex
std::unordered_map<uint64_t, std::weak_ptr<EventTarget> > openage::event::Loop::curveindex private
Definition at line 132 of file loop.h.
filters
std::list<EventFilter> openage::event::Loop::filters private
Here we store all running filters that shall be applied whenever a new obejct is added to our objectstore.
Definition at line 119 of file loop.h.
queue
EventQueue openage::event::Loop::queue private
All events are enqueued here.
Definition at line 124 of file loop.h.
Referenced by openage.util.filelike.fifo.FIFO::__len__(), create_change(), create_event(), execute_events(), get_queue(), openage.util.filelike.fifo.FIFO::get_size(), reach_time(), openage.util.filelike.fifo.FIFO::read(), openage.util.filelike.fifo.FIFO::tellw(), update_changes(), and openage.util.filelike.fifo.FIFO::write().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/event/loop.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/event/loop.cpp