openage: openage::pyinterface::PyIfFunc< ReturnType, ArgTypes > Class Template Reference
openage::pyinterface::PyIfFunc< ReturnType, ArgTypes > Class Template Reference
#include <functional.h>
Public Member Functions
PyIfFunc ()
~PyIfFunc ()
PyIfFunc (const PyIfFunc< ReturnType, ArgTypes ... > &other)=delete
PyIfFunc (PyIfFunc< ReturnType, ArgTypes ... > &&other)=delete
PyIfFunc< ReturnType, ArgTypes ... > & operator= (const PyIfFunc< ReturnType, ArgTypes ... > &other)=delete
PyIfFunc< ReturnType, ArgTypes ... > & operator= (PyIfFunc< ReturnType, ArgTypes ... > &&other)=delete
operator Func< ReturnType, ArgTypes ... > & () const
Public Member Functions inherited from openage::pyinterface::Func< ReturnType, ArgTypes ... >
Func ()
Func (F &&f)
Func (std::reference_wrapper< F > f)
Func (const std::function< ReturnType(ArgTypes ...)> &f)
Func (std::function< ReturnType(ArgTypes ...)> &&f)
Func< ReturnType, ArgTypes ... > & operator= (F &&f)
Func< ReturnType, ArgTypes ... > & operator= (std::reference_wrapper< F > f)
Func< ReturnType, ArgTypes ... > & operator= (const std::function< ReturnType(ArgTypes ...)> &f)
Func< ReturnType, ArgTypes ... > & operator= (std::function< ReturnType(ArgTypes ...)> &&f)
void check_fptr () const
ReturnType call (ArgTypes ...args) const
operator const std::function< ReturnType (ArgTypes ...)> &() const
const std::function< ReturnType(ArgTypes ...)> & get () const
void bind (util::FunctionPtr< ReturnType, BoundArgTypes ..., ArgTypes ... > f, BoundArgTypes ...bound_args)
void bind_noexcept (util::FunctionPtr< ReturnType, BoundArgTypes ..., ArgTypes ... > f, BoundArgTypes ...bound_args)
void bind0 (ReturnType(*f)(ArgTypes ...))
void bind_noexcept0 (ReturnType(*f)(ArgTypes ...))
void bind1 (ReturnType(*f)(BoundArgType0, ArgTypes ...), BoundArgType0 bound_arg0)
void bind_noexcept1 (ReturnType(*f)(BoundArgType0, ArgTypes ...), BoundArgType0 bound_arg0)
void bind2 (ReturnType(*f)(BoundArgType0, BoundArgType1, ArgTypes ...), BoundArgType0 bound_arg0, BoundArgType1 bound_arg1)
void bind_noexcept2 (ReturnType(*f)(BoundArgType0, BoundArgType1, ArgTypes ...), BoundArgType0 bound_arg0, BoundArgType1 bound_arg1)
void bind3 (ReturnType(*f)(BoundArgType0, BoundArgType1, BoundArgType2, ArgTypes ...), BoundArgType0 bound_arg0, BoundArgType1 bound_arg1, BoundArgType2 bound_arg2)
void bind_noexcept3 (ReturnType(*f)(BoundArgType0, BoundArgType1, BoundArgType2, ArgTypes ...), BoundArgType0 bound_arg0, BoundArgType1 bound_arg1, BoundArgType2 bound_arg2)
Detailed Description
template<typename ReturnType, typename ... ArgTypes>
class openage::pyinterface::PyIfFunc< ReturnType, ArgTypes >
For usage by "Py Interface Functions", i.e. empty global function pointers in libopenage that get filled by Cython at initialization time.
Use only for global objects that have associated symbol names (this is enforced).
The interface for PyIfFunc is identical to that of Func, so we'll simply typedef them to avoid the redundant pxd lines from above.
pxd:
ctypedef Func0 PyIfFunc0 ctypedef Func1 PyIfFunc1 ctypedef Func2 PyIfFunc2 ctypedef Func3 PyIfFunc3 ctypedef Func4 PyIfFunc4 ctypedef Func5 PyIfFunc5
Definition at line 407 of file functional.h.
Constructor & Destructor Documentation
PyIfFunc() [1/3]
template<typename ReturnType, typename ... ArgTypes> openage::pyinterface::PyIfFunc< ReturnType, ArgTypes >::PyIfFunc () inline
Definition at line 409 of file functional.h.
                {
         add_py_if_component(this, [=]() -> bool {
             try {
                 this->check_fptr();
                 return true;
             } catch (Error &) {
                 return false;
             }
         });
     }
References openage::pyinterface::add_py_if_component(), and openage::pyinterface::Func< ReturnType, ArgTypes ... >::check_fptr().
~PyIfFunc()
template<typename ReturnType, typename ... ArgTypes> openage::pyinterface::PyIfFunc< ReturnType, ArgTypes >::~PyIfFunc () inline
Definition at line 420 of file functional.h.
                 {
         destroy_py_if_component(this);
     }
References openage::pyinterface::destroy_py_if_component().
PyIfFunc() [2/3]
template<typename ReturnType, typename ... ArgTypes> openage::pyinterface::PyIfFunc< ReturnType, ArgTypes >::PyIfFunc (const PyIfFunc< ReturnType, ArgTypes ... > & other) delete
PyIfFunc() [3/3]
template<typename ReturnType, typename ... ArgTypes> openage::pyinterface::PyIfFunc< ReturnType, ArgTypes >::PyIfFunc (PyIfFunc< ReturnType, ArgTypes ... > && other) delete
Member Function Documentation
operator Func< ReturnType, ArgTypes ... > &()
template<typename ReturnType, typename ... ArgTypes> openage::pyinterface::PyIfFunc< ReturnType, ArgTypes >::operator Func< ReturnType, ArgTypes ... > & () const inline
Definition at line 431 of file functional.h.
{
         return static_cast<Func<ReturnType, ArgTypes ...>>(this->fptr);
     }
References openage::pyinterface::Func< ReturnType, ArgTypes ... >::fptr.
operator=() [1/2]
template<typename ReturnType, typename ... ArgTypes> PyIfFunc<ReturnType, ArgTypes ...>& openage::pyinterface::PyIfFunc< ReturnType, ArgTypes >::operator= (const PyIfFunc< ReturnType, ArgTypes ... > & other) delete
operator=() [2/2]
template<typename ReturnType, typename ... ArgTypes> PyIfFunc<ReturnType, ArgTypes ...>& openage::pyinterface::PyIfFunc< ReturnType, ArgTypes >::operator= (PyIfFunc< ReturnType, ArgTypes ... > && other) delete
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/pyinterface/functional.h