openage: openage::renderer::resources::Texture2dData Class Reference
openage::renderer::resources::Texture2dData Class Reference
Stores 2D texture data in a CPU-accessible byte buffer.
#include <texture_data.h>
Public Member Functions
Texture2dData (const util::Path &path, bool use_metafile=false)
Create a texture from an image file.
Texture2dData (Texture2dInfo const &info, std::vector< uint8_t > &&data)
Construct by moving the information and raw texture data from somewhere else.
Texture2dData flip_y ()
Flips the texture along the Y-axis and returns the flipped data with the same info.
const Texture2dInfo & get_info () const
Returns the information describing this texture data.
const uint8_t * get_data () const
Returns a pointer to the raw texture data, in row-major order.
template<typename T >
T read_pixel (size_t x, size_t y) const
Reads the pixel at the given position and casts it to the given type.
void store (const util::Path &file) const
Stores this texture data in the given file in the PNG format.
Private Attributes
Texture2dInfo info
Information about this texture data.
std::vector< uint8_t > data
The raw texture data.
Detailed Description
Stores 2D texture data in a CPU-accessible byte buffer.
Provides methods for loading from and storing onto disk, as well as sending to and receiving from graphics hardware.
Definition at line 19 of file texture_data.h.
Constructor & Destructor Documentation
Texture2dData() [1/2]
openage::renderer::resources::Texture2dData::Texture2dData (const util::Path & path, bool use_metafile = false)
Create a texture from an image file.
Parameters
[in] use_metafile determines whether the loading should read an accompanying metadata file to split the texture into subtextures
Uses SDL Image internally. For supported image file types, see the SDL_Image initialization in the engine.
Definition at line 56 of file texture_data.cpp.
{
     std::string native_path = path.resolve_native_path();
     std::unique_ptr<SDL_Surface, decltype(&SDL_FreeSurface)> surface(
         IMG_Load(native_path.c_str()),
         &SDL_FreeSurface
     );
     if (!surface) {
         throw Error(MSG(err)
                     << "Could not load texture from " << native_path
                     << ": " << IMG_GetError());
     }
     log::log(MSG(dbg) << "Texture has been loaded from " << native_path);
     auto surf_fmt = *surface->format;
     pixel_format pix_fmt;
     switch (surf_fmt.format) {
     case SDL_PIXELFORMAT_RGB24:
         pix_fmt = pixel_format::rgb8;
         break;
     case SDL_PIXELFORMAT_BGR24:
         pix_fmt = pixel_format::bgr8;
         break;
 #if SDL_BYTEORDER == SDL_BIG_ENDIAN
     case SDL_PIXELFORMAT_RGBA8888:
 #else
     case SDL_PIXELFORMAT_ABGR8888:
 #endif
         pix_fmt = pixel_format::rgba8;
         break;
     default:
         throw Error(MSG(err) << "Texture " << native_path << " uses an unsupported format.");
     }
     auto w = uint32_t(surface->w);
     auto h = uint32_t(surface->h);
     size_t data_size = surf_fmt.BytesPerPixel * surface->w * surface->h;
     // copy pixel data from surface
     this->data = std::vector<uint8_t>(data_size);
     memcpy(this->data.data(), surface->pixels, data_size);
     std::vector<Texture2dSubInfo> subtextures;
     if (use_metafile) {
         util::Path meta = (path.get_parent() / path.get_stem()).with_suffix(".slp.docx");
         log::log(MSG(info) << "Loading meta file: " << meta);
         // get subtexture information by meta file exported by script
         subtextures = util::read_csv_file<Texture2dSubInfo>(meta);
     }
     else {
         // we don't have a texture description file.
         // use the whole image as one texture then.
         Texture2dSubInfo s{0, 0, w, h, w/2, h/2};
         subtextures.push_back(s);
     }
     size_t align = guess_row_alignment(w, pix_fmt, surface->pitch);
     this->info = Texture2dInfo(w, h, pix_fmt, align, std::move(subtextures));
 }
References openage::renderer::resources::bgr8, data, openage::log::dbg(), openage::log::err(), openage::util::Path::get_parent(), openage::util::Path::get_stem(), openage::renderer::resources::guess_row_alignment(), info, openage::log::log(), openage::move, MSG, openage::util::Path::resolve_native_path(), openage::renderer::resources::rgb8, and openage::renderer::resources::rgba8.
Referenced by flip_y().
Texture2dData() [2/2]
openage::renderer::resources::Texture2dData::Texture2dData (Texture2dInfo const & info, std::vector< uint8_t > && data)
Construct by moving the information and raw texture data from somewhere else.
Definition at line 121 of file texture_data.cpp.
     : info(info)
     , data(std::move(data)) {}
References openage::move.
Member Function Documentation
flip_y()
Texture2dData openage::renderer::resources::Texture2dData::flip_y ()
Flips the texture along the Y-axis and returns the flipped data with the same info.
Sometimes necessary when converting between storage modes.
Definition at line 125 of file texture_data.cpp.
{
     size_t row_size = this->info.get_row_size();
     size_t height = this->info.get_size().second;
     std::vector<uint8_t> new_data(this->data.size());
     for (size_t y = 0; y < height; ++y) {
         std::copy(this->data.data() + row_size * y, this->data.data() + row_size * (y+1), new_data.end() - row_size * (y+1));
     }
     this->data = new_data;
     Texture2dInfo new_info(this->info);
     return Texture2dData(std::move(new_info), std::move(new_data));
 }
References data, openage::renderer::resources::Texture2dInfo::get_row_size(), openage::renderer::resources::Texture2dInfo::get_size(), info, openage::move, and Texture2dData().
get_data()
const uint8_t * openage::renderer::resources::Texture2dData::get_data () const
Returns a pointer to the raw texture data, in row-major order.
Definition at line 146 of file texture_data.cpp.
{
     return this->data.data();
 }
References data.
Referenced by openage::renderer::opengl::GlTexture2d::upload(), and openage::renderer::opengl::GlTexture2dArray::upload().
get_info()
const Texture2dInfo & openage::renderer::resources::Texture2dData::get_info () const
Returns the information describing this texture data.
Definition at line 142 of file texture_data.cpp.
{
     return this->info;
 }
References info.
Referenced by openage::renderer::opengl::GlTexture2d::upload().
read_pixel()
template<typename T > T openage::renderer::resources::Texture2dData::read_pixel (size_t x, size_t y) const inline
Reads the pixel at the given position and casts it to the given type.
The texture is not read as if it consisted of pixels of the given type, but rather according to its original pixel format, so the coordinates have to be specified according to that.
Definition at line 47 of file texture_data.h.
{
         const uint8_t *data = this->data.data();
         auto dims = this->info.get_size();
         size_t off = (dims.second - y) * this->info.get_row_size();
         off += x * pixel_size(this->info.get_format());
         if ((off + sizeof(T)) > this->info.get_data_size()) {
             throw Error(MSG(err) << "Pixel position (" << x << ", " << y << ") is outside texture.");
         }
         return *reinterpret_cast<const T*>(data + off);
     }
References data, openage::log::err(), openage::renderer::resources::Texture2dInfo::get_data_size(), openage::renderer::resources::Texture2dInfo::get_format(), openage::renderer::resources::Texture2dInfo::get_row_size(), openage::renderer::resources::Texture2dInfo::get_size(), MSG, and openage::renderer::resources::pixel_size().
Referenced by openage::renderer::tests::renderer_demo_0().
store()
void openage::renderer::resources::Texture2dData::store (const util::Path & file) const
Stores this texture data in the given file in the PNG format.
Definition at line 150 of file texture_data.cpp.
{
     log::log(MSG(info) << "Saving texture data to " << file);
     if (this->info.get_format() != pixel_format::rgba8) {
         throw Error(MSG(err) << "Storing 2D textures into files is unimplemented. PRs welcome :D");
     }
     auto size = this->info.get_size();
 // If an older SDL2 is used, we have to specify the format manually.
 #ifndef SDL_PIXELFORMAT_RGBA32
     uint32_t rmask, gmask, bmask, amask;
 #if SDL_BYTEORDER == SDL_BIG_ENDIAN
     rmask = 0xff000000;
     gmask = 0x00ff0000;
     bmask = 0x0000ff00;
     amask = 0x000000ff;
 #else // little endian, like x86
     rmask = 0x000000ff;
     gmask = 0x0000ff00;
     bmask = 0x00ff0000;
     amask = 0xff000000;
 #endif
     std::unique_ptr<SDL_Surface, decltype(&SDL_FreeSurface)> surf(
         SDL_CreateRGBSurfaceFrom(
             // const_cast is okay, because the surface doesn't modify data
             const_cast<void*>(static_cast<void const*>(this->data.data())),
             size.first,
             size.second,
             32,
             this->info.get_row_size(),
             rmask, gmask, bmask, amask
         ),
         &SDL_FreeSurface
     );
 #else
     std::unique_ptr<SDL_Surface, decltype(&SDL_FreeSurface)> surf(
         SDL_CreateRGBSurfaceWithFormatFrom(
             // const_cast is okay, because the surface doesn't modify data
             const_cast<void*>(static_cast<void const*>(this->data.data())),
             size.first,
             size.second,
             32,
             this->info.get_row_size(),
             SDL_PIXELFORMAT_RGBA32
         ),
         &SDL_FreeSurface
     );
 #endif
     // Call sdl_image for saving the screenshot to PNG
     std::string path = file.resolve_native_path_w();
     IMG_SavePNG(surf.get(), path.c_str());
 }
References data, openage::log::err(), openage::renderer::resources::Texture2dInfo::get_format(), openage::renderer::resources::Texture2dInfo::get_row_size(), openage::renderer::resources::Texture2dInfo::get_size(), info, openage::log::log(), MSG, openage::util::Path::resolve_native_path_w(), and openage::renderer::resources::rgba8.
Member Data Documentation
data
std::vector<uint8_t> openage::renderer::resources::Texture2dData::data private
The raw texture data.
Definition at line 68 of file texture_data.h.
Referenced by openage.convert.dataformat.content_snippet.ContentSnippet::__eq__(), openage.convert.dataformat.struct_snippet.StructSnippet::__hash__(), openage.convert.dataformat.content_snippet.ContentSnippet::__hash__(), openage.convert.dataformat.content_snippet.ContentSnippet::__repr__(), openage.convert.dataformat.data_definition.DataDefinition::__str__(), openage.convert.dataformat.content_snippet.ContentSnippet::__str__(), openage.convert.dataformat.data_formatter.DataFormatter::add_data(), openage.convert.dataformat.data_formatter.DataFormatter::export(), flip_y(), openage.convert.dataformat.data_definition.DataDefinition::generate_csv(), get_data(), openage.convert.dataformat.content_snippet.ContentSnippet::get_data(), openage.convert.texture.TextureImage::get_data(), openage.convert.texture.TextureImage::get_pil_image(), openage.convert.peresource.PEResources::read_directory(), read_pixel(), store(), and Texture2dData().
info
Texture2dInfo openage::renderer::resources::Texture2dData::info private
Information about this texture data.
Definition at line 65 of file texture_data.h.
Referenced by flip_y(), get_info(), store(), and Texture2dData().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/resources/texture_data.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/resources/texture_data.cpp