openage: openage::TerrainChunk Class Reference
openage::TerrainChunk Class Reference
terrain chunk class represents one chunk of the the drawn terrain.
#include <terrain_chunk.h>
Public Member Functions
TerrainChunk ()
~TerrainChunk ()
void draw (coord::chunk chunk_pos)
draws the terrain chunk on screen.
TileContent * get_data (coord::tile abspos)
get tile data by absolute coordinates.
TileContent * get_data (coord::tile_delta pos)
get tile data by coordinates that are releative to this chunk.
TileContent * get_data (size_t pos)
get tile data by memory position.
TileContent * get_data_neigh (coord::tile_delta pos)
get the tile data a given tile position relative to this chunk.
int neighbor_id_by_pos (coord::tile_delta pos)
size_t tile_position (coord::tile_delta pos)
size_t tile_position_neigh (coord::tile_delta pos)
size_t get_tile_count ()
size_t tiles_in_row (unsigned int row)
size_t get_size ()
void set_terrain (Terrain *parent)
Public Attributes
size_t size
stores the length for one chunk side.
size_t tile_count
number of tiles on that chunk (this->size^2)
TileContent * data
stores the chunk data, one tile_content struct for each tile.
Terrain * terrain
the terrain to which this chunk belongs to.
chunk_neighbors neighbors
the 8 neighbors this chunk has.
bool manually_created
Detailed Description
terrain chunk class represents one chunk of the the drawn terrain.
Definition at line 43 of file terrain_chunk.h.
Constructor & Destructor Documentation
TerrainChunk()
openage::TerrainChunk::TerrainChunk ()
Definition at line 22 of file terrain_chunk.cpp.
     :
     manually_created{true} {
     this->tile_count = std::pow(chunk_size, 2);
     // the data array for this chunk.
     // each element describes the tile data.
     this->data = new TileContent[this->tile_count];
     // initialize all neighbors as nonexistant
     for (int i = 0; i < 8; i++) {
         this->neighbors.neighbor[i] = nullptr;
     }
     log::log(MSG(dbg) << "Terrain chunk created: " <<
         "size=" << chunk_size << ", " <<
         "tiles=" << this->tile_count);
 }
~TerrainChunk()
openage::TerrainChunk::~TerrainChunk ()
Definition at line 42 of file terrain_chunk.cpp.
{
     delete[] this->data;
 }
References data.
Member Function Documentation
draw()
void openage::TerrainChunk::draw (coord::chunk chunk_pos)
draws the terrain chunk on screen.
Parameters
chunk_pos the chunk position where it will be drawn
get_data() [1/3]
TileContent * openage::TerrainChunk::get_data (coord::tile abspos)
get tile data by absolute coordinates.
Definition at line 46 of file terrain_chunk.cpp.
{
     return this->get_data(abspos.get_pos_on_chunk());
 }
References openage::coord::tile::get_pos_on_chunk().
Referenced by openage::Terrain::fill(), get_data(), openage::Terrain::get_data(), get_data_neigh(), openage::gameio::load(), openage::EditorMode::paint_entity_at(), openage::EditorMode::paint_terrain_at(), openage::TerrainObject::place(), openage::TerrainObject::place_unchecked(), openage::TerrainObject::remove(), openage::gameio::save(), openage::TerrainObject::set_ground(), and openage::Generator::terrain().
get_data() [2/3]
TileContent * openage::TerrainChunk::get_data (coord::tile_delta pos)
get tile data by coordinates that are releative to this chunk.
Definition at line 50 of file terrain_chunk.cpp.
{
     return this->get_data(this->tile_position(pos));
 }
References get_data(), and tile_position().
get_data() [3/3]
TileContent * openage::TerrainChunk::get_data (size_t pos)
get tile data by memory position.
Definition at line 54 of file terrain_chunk.cpp.
{
     return &this->data[pos];
 }
References data.
get_data_neigh()
TileContent * openage::TerrainChunk::get_data_neigh (coord::tile_delta pos)
get the tile data a given tile position relative to this chunk.
also queries neighbors if the position is not on this chunk.
Definition at line 58 of file terrain_chunk.cpp.
{
     // determine the neighbor id by the given position
     int neighbor_id = this->neighbor_id_by_pos(pos);
     // if the location is not on the current chunk, the neighbor id is != -1
     if (neighbor_id != -1) {
         // get the chunk where the requested neighbor tile lies on.
         TerrainChunk *neigh_chunk = this->neighbors.neighbor[neighbor_id];
         // this neighbor does not exist, so the tile does not exist.
         if (neigh_chunk == nullptr) {
             return nullptr;
         }
         // get position of tile on neighbor
         size_t pos_on_neighbor = this->tile_position_neigh(pos);
         return neigh_chunk->get_data(pos_on_neighbor);
     }
     // the position lies on the current chunk.
     else {
         return this->get_data(pos);
     }
 }
References get_data(), openage::chunk_neighbors::neighbor, neighbor_id_by_pos(), neighbors, and tile_position_neigh().
get_size()
size_t openage::TerrainChunk::get_size ()
Definition at line 182 of file terrain_chunk.cpp.
{
     return chunk_size;
 }
References openage::chunk_size.
Referenced by openage.util.filelike.abstract.FileLikeObject::seek_helper().
get_tile_count()
size_t openage::TerrainChunk::get_tile_count ()
Definition at line 178 of file terrain_chunk.cpp.
{
     return this->tile_count;
 }
References tile_count.
neighbor_id_by_pos()
int openage::TerrainChunk::neighbor_id_by_pos (coord::tile_delta pos)
Definition at line 101 of file terrain_chunk.cpp.
{
     int neigh_id = -1;
     if (pos.ne < 0) {
         if (pos.se < 0) {
             neigh_id = 6;
         }
         else if (pos.se >= (ssize_t)chunk_size) {
             neigh_id = 4;
         }
         else {
             neigh_id = 5;
         }
     }
     else if (pos.ne >= (ssize_t)chunk_size) {
         if (pos.se < 0) {
             neigh_id = 0;
         }
         else if (pos.se >= (ssize_t)chunk_size) {
             neigh_id = 2;
         }
         else {
             neigh_id = 1;
         }
     }
     else {
         if (pos.se < 0) {
             neigh_id = 7;
         }
         else if (pos.se >= (ssize_t)chunk_size) {
             neigh_id = 3;
         }
         else {
             neigh_id = -1;
         }
     }
     return neigh_id;
 }
References openage::chunk_size.
Referenced by get_data_neigh(), and tile_position().
set_terrain()
void openage::TerrainChunk::set_terrain (Terrain * parent)
Definition at line 186 of file terrain_chunk.cpp.
{
     this->terrain = parent;
 }
References terrain.
Referenced by openage::Terrain::attach_chunk().
tile_position()
size_t openage::TerrainChunk::tile_position (coord::tile_delta pos)
Definition at line 160 of file terrain_chunk.cpp.
{
     if (this->neighbor_id_by_pos(pos) != -1) {
         throw Error(MSG(err) << "Tile "
             "(" << pos.ne << ", " << pos.se << ") "
             "has been requested, but is not part of this chunk.");
     }
     return pos.se * chunk_size + pos.ne;
 }
References openage::chunk_size, openage::log::err(), MSG, and neighbor_id_by_pos().
Referenced by get_data().
tile_position_neigh()
size_t openage::TerrainChunk::tile_position_neigh (coord::tile_delta pos)
Definition at line 170 of file terrain_chunk.cpp.
{
     // get position of tile on neighbor
     pos.ne = util::mod<coord::tile_t, chunk_size>(pos.ne);
     pos.se = util::mod<coord::tile_t, chunk_size>(pos.se);
     return pos.se * chunk_size + pos.ne;
 }
References openage::chunk_size.
Referenced by get_data_neigh().
tiles_in_row()
size_t openage::TerrainChunk::tiles_in_row (unsigned int row)
Member Data Documentation
data
TileContent* openage::TerrainChunk::data
stores the chunk data, one tile_content struct for each tile.
Definition at line 61 of file terrain_chunk.h.
Referenced by openage.convert.dataformat.content_snippet.ContentSnippet::__eq__(), openage.convert.dataformat.struct_snippet.StructSnippet::__hash__(), openage.convert.dataformat.content_snippet.ContentSnippet::__hash__(), openage.convert.dataformat.content_snippet.ContentSnippet::__repr__(), openage.convert.dataformat.data_definition.DataDefinition::__str__(), openage.convert.dataformat.content_snippet.ContentSnippet::__str__(), openage.convert.dataformat.data_formatter.DataFormatter::add_data(), openage.convert.dataformat.data_formatter.DataFormatter::export(), openage.convert.dataformat.data_definition.DataDefinition::generate_csv(), openage.convert.dataformat.content_snippet.ContentSnippet::get_data(), openage.convert.texture.TextureImage::get_data(), get_data(), openage.convert.texture.TextureImage::get_pil_image(), openage.convert.peresource.PEResources::read_directory(), and ~TerrainChunk().
manually_created
bool openage::TerrainChunk::manually_created
Definition at line 113 of file terrain_chunk.h.
Referenced by openage::Terrain::attach_chunk().
neighbors
chunk_neighbors openage::TerrainChunk::neighbors
the 8 neighbors this chunk has.
Definition at line 71 of file terrain_chunk.h.
Referenced by openage::Terrain::attach_chunk(), and get_data_neigh().
size
size_t openage::TerrainChunk::size
stores the length for one chunk side.
Definition at line 51 of file terrain_chunk.h.
Referenced by openage.util.bytequeue.ByteQueue::__len__(), openage.util.bytequeue.ByteQueue::append(), openage.util.filelike.stream.StreamFragment::get_size(), openage.util.bytequeue.ByteQueue::popleft(), and openage.util.filelike.stream.StreamFragment::read().
terrain
Terrain* openage::TerrainChunk::terrain
the terrain to which this chunk belongs to.
Definition at line 66 of file terrain_chunk.h.
Referenced by set_terrain().
tile_count
size_t openage::TerrainChunk::tile_count
number of tiles on that chunk (this->size^2)
Definition at line 56 of file terrain_chunk.h.
Referenced by get_tile_count(), and openage::gameio::save().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/terrain/terrain_chunk.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/terrain/terrain_chunk.cpp