openage: openage::renderer::vulkan::VlkShaderProgram Class Reference
openage::renderer::vulkan::VlkShaderProgram Class Reference
#include <shader_program.h>
Public Member Functions
VlkShaderProgram (VkDevice dev, std::vector< resources::ShaderSource > const &srcs)
Public Attributes
std::vector< VkShaderModule > modules
std::vector< VkPipelineShaderStageCreateInfo > pipeline_stage_infos
Detailed Description
Definition at line 27 of file shader_program.h.
Constructor & Destructor Documentation
VlkShaderProgram()
openage::renderer::vulkan::VlkShaderProgram::VlkShaderProgram (VkDevice dev, std::vector< resources::ShaderSource > const & srcs) inline explicit
Definition at line 32 of file shader_program.h.
{
         // TODO reflect with spirv-cross
         // TODO if glsl, compile to spirv with libshaderc
         for (auto const& src : srcs) {
             if (src.get_lang() != resources::shader_lang_t::spirv) {
                 throw Error(MSG(err) << "Unsupported shader language in Vulkan shader.");
             }
             VkShaderModuleCreateInfo cr_shdr = {};
             cr_shdr.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
             cr_shdr.codeSize = src.get_source().size();
             cr_shdr.pCode = reinterpret_cast<uint32_t const*>(src.get_source().data());
             VkShaderModule mod;
             VK_CALL_CHECKED(vkCreateShaderModule, dev, &cr_shdr, nullptr, &mod);
             this->modules.push_back(mod);
             VkPipelineShaderStageCreateInfo cr_stage = {};
             cr_stage.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
             cr_stage.stage = vk_shader_stage(src.get_stage());
             cr_stage.module = mod;
             cr_stage.pName = "main";
             this->pipeline_stage_infos.push_back(cr_stage);
         }
         log::log(MSG(dbg) << "Created modules for Vulkan shader");
     }
References openage::log::dbg(), openage::log::err(), openage::log::log(), openage::util::mod(), MSG, openage::renderer::resources::spirv, src, VK_CALL_CHECKED, and openage::renderer::vulkan::vk_shader_stage().
Member Data Documentation
modules
std::vector<VkShaderModule> openage::renderer::vulkan::VlkShaderProgram::modules
Definition at line 29 of file shader_program.h.
pipeline_stage_infos
std::vector<VkPipelineShaderStageCreateInfo> openage::renderer::vulkan::VlkShaderProgram::pipeline_stage_infos
Definition at line 30 of file shader_program.h.
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/vulkan/shader_program.h