openage: qtsdl::GuiCallback Class Reference
qtsdl::GuiCallback Class Reference
#include <gui_callback.h>
Public Slots
void process (const std::function< void()> &f)
Signals
void process_blocking (const std::function< void()> &f)
Public Member Functions
GuiCallback ()
virtual ~GuiCallback ()
Detailed Description
Definition at line 12 of file gui_callback.h.
Constructor & Destructor Documentation
GuiCallback()
qtsdl::GuiCallback::GuiCallback ()
Definition at line 13 of file gui_callback.cpp.
     :
     QObject{} {
     Q_UNUSED(registration);
 }
~GuiCallback()
qtsdl::GuiCallback::~GuiCallback () virtual
Definition at line 19 of file gui_callback.cpp.
{
 }
Member Function Documentation
process
void qtsdl::GuiCallback::process (const std::function< void()> & f) slot
Definition at line 22 of file gui_callback.cpp.
{
     f();
 }
Referenced by qtsdl::GameLogicCaller::set_game_logic_callback().
process_blocking
void qtsdl::GuiCallback::process_blocking (const std::function< void()> & f) signal
Referenced by openage::gui::GuiGameSpecImageProviderImpl::migrate_to_new_game_spec(), openage::gui::GuiGameSpecImageProviderImpl::on_game_spec_invalidated(), and qtsdl::GameLogicCaller::set_game_logic_callback().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/guisys/private/gui_callback.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/guisys/private/gui_callback.cpp