openage: openage::RadialObject Class Reference
openage::RadialObject Class Reference
Represents circular shaped objects (movable game units) can only be constructed by unit->make_location<RadialObject>(...)
#include <terrain_object.h>
Public Member Functions
virtual ~RadialObject ()
tile_range get_range (const coord::phys3 &pos, const Terrain &terrain) const override
finds the range covered if the object was in a position
coord::phys_t from_edge (const coord::phys3 &point) const override
how far is a point from the edge of this object
coord::phys3 on_edge (const coord::phys3 &angle, coord::phys_t extra=0) const override
get a position on the edge of this object
bool contains (const coord::phys3 &other) const override
does this space contain a given point
bool intersects (const TerrainObject &other, const coord::phys3 &position) const override
would this intersect with another object if it were positioned at the given point
coord::phys_t min_axis () const override
the shortest line that can be placed across the objects center
Public Member Functions inherited from openage::TerrainObject
TerrainObject (Unit &u)
TerrainObject (const TerrainObject &)=delete
TerrainObject (TerrainObject &&)=delete
virtual ~TerrainObject ()
bool is_floating () const
is the object a floating outline – it is only an indicator of where a building will be built, but not yet started building and does not affect any collisions
bool is_placed () const
returns true if this object has been placed.
bool check_collisions () const
should this object be tested for collisions, which decides whether another object is allowed to overlap the location of this object.
void draw_outline (const coord::CoordManager &coord) const
draws outline of this terrain space in current position
bool place (object_state init_state)
changes the placement state of this object keeping the existing position.
bool place (const std::shared_ptr< Terrain > &t, coord::phys3 &pos, object_state init_state)
binds the TerrainObject to a certain TerrainChunk.
bool move (coord::phys3 &pos)
moves the object – returns false if object cannot be moved here
void remove ()
remove this TerrainObject from the terrain chunks.
void set_ground (int id, int additional=0)
sets all the ground below the object to a terrain id.
template<class T , typename ... Arg>
TerrainObject * make_annex (Arg ... args)
appends new annex location for this object
const TerrainObject * get_parent () const
Returns the parent terrain object, if null the object has no parent which is the case for most objects.
std::vector< TerrainObject * > get_children () const
Returns a list of child objects, this is the inverse of the get_parent() function.
std::shared_ptr< Terrain > get_terrain () const
bool operator< (const TerrainObject &other)
comparison for TerrainObjects.
Public Attributes
const coord::phys_t phys_radius
radius of this cirular space
Public Attributes inherited from openage::TerrainObject
tile_range pos
the range of tiles which are covered by this object
Unit & unit
std::function< bool(const coord::phys3 &)> passable
decide which terrains this object can be on this function should be true if given a valid position for the object
std::function< void(const Engine &e)> draw
specifies content to be drawn
Private Member Functions
RadialObject (Unit &u, float rad)
RadialObject (Unit &u, float rad, std::shared_ptr< Texture > out_tex)
Friends
class TerrainObject
class Unit
Additional Inherited Members
Protected Member Functions inherited from openage::TerrainObject
void place_unchecked (const std::shared_ptr< Terrain > &t, coord::phys3 &position)
placement function which does not check passibility used only when passibilty is already checked otherwise the place function should be used this does not modify the units placement state
Protected Attributes inherited from openage::TerrainObject
object_state state
std::weak_ptr< Terrain > terrain
int occupied_chunk_count
TerrainChunk * occupied_chunk [4]
TerrainObject * parent
annexes and grouped units
std::vector< std::unique_ptr< TerrainObject > > children
std::shared_ptr< Texture > outline_texture
texture for drawing outline
Detailed Description
Represents circular shaped objects (movable game units) can only be constructed by unit->make_location<RadialObject>(...)
Definition at line 325 of file terrain_object.h.
Constructor & Destructor Documentation
~RadialObject()
openage::RadialObject::~RadialObject () virtual
Definition at line 397 of file terrain_object.cpp.
 {}
RadialObject() [1/2]
openage::RadialObject::RadialObject (Unit & u, float rad) private
Definition at line 385 of file terrain_object.cpp.
     :
     RadialObject(u, rad, radial_outline(rad)) {
 }
RadialObject() [2/2]
openage::RadialObject::RadialObject (Unit & u, float rad, std::shared_ptr< Texture > out_tex) private
Definition at line 390 of file terrain_object.cpp.
     :
     TerrainObject(u),
     phys_radius(rad) {
     this->outline_texture = out_tex;
 }
References openage::TerrainObject::outline_texture.
Member Function Documentation
contains()
bool openage::RadialObject::contains (const coord::phys3 & other) const override virtual
does this space contain a given point
Implements openage::TerrainObject.
Definition at line 427 of file terrain_object.cpp.
{
     return this->pos.draw.to_phys2().distance(other.to_phys2()) < this->phys_radius.to_double();
 }
References openage::coord::phys2::distance(), openage::tile_range::draw, phys_radius, openage::TerrainObject::pos, openage::util::FixedPoint< int_type, fractional_bits >::to_double(), and openage::coord::phys3::to_phys2().
from_edge()
coord::phys_t openage::RadialObject::from_edge (const coord::phys3 & point) const override virtual
how far is a point from the edge of this object
Implements openage::TerrainObject.
Definition at line 416 of file terrain_object.cpp.
{
     return std::max(
         coord::phys_t(point.to_phys2().distance(this->pos.draw.to_phys2())) - this->phys_radius,
         static_cast<coord::phys_t>(0)
     );
 }
References openage::coord::phys2::distance(), openage::tile_range::draw, std::max(), phys_radius, openage::TerrainObject::pos, and openage::coord::phys3::to_phys2().
get_range()
tile_range openage::RadialObject::get_range (const coord::phys3 & pos, const Terrain & terrain) const override virtual
finds the range covered if the object was in a position
Implements openage::TerrainObject.
Definition at line 399 of file terrain_object.cpp.
{
     tile_range result;
     // create bounds
     coord::phys3 p_start = pos, p_end = pos;
     p_start.ne -= this->phys_radius;
     p_start.se -= this->phys_radius;
     p_end.ne += this->phys_radius;
     p_end.se += this->phys_radius;
     // set result
     result.start   = p_start.to_tile3().to_tile();
     result.end     = p_end.to_tile3().to_tile() + coord::tile_delta{ 1, 1 };
     result.draw = pos;
     return result;
 }
References phys_radius, openage::TerrainObject::pos, openage.testing.testing::result(), openage::tile_range::start, openage::coord::tile3::to_tile(), and openage::coord::phys3::to_tile3().
intersects()
bool openage::RadialObject::intersects (const TerrainObject & other, const coord::phys3 & position) const override virtual
would this intersect with another object if it were positioned at the given point
Implements openage::TerrainObject.
Definition at line 431 of file terrain_object.cpp.
{
     if (const SquareObject *sq = dynamic_cast<const SquareObject *>(&other)) {
         return sq->from_edge(position) < this->phys_radius;
     }
     else if (const RadialObject *rad = dynamic_cast<const RadialObject *>(&other)) {
         return position.to_phys2().distance(rad->pos.draw.to_phys2()) < (this->phys_radius + rad->phys_radius).to_double();
     }
     return false;
 }
References openage::coord::phys2::distance(), phys_radius, and openage::coord::phys3::to_phys2().
min_axis()
coord::phys_t openage::RadialObject::min_axis () const override virtual
the shortest line that can be placed across the objects center
Implements openage::TerrainObject.
Definition at line 441 of file terrain_object.cpp.
{
     return this->phys_radius * 2;
 }
References phys_radius.
on_edge()
coord::phys3 openage::RadialObject::on_edge (const coord::phys3 & angle, coord::phys_t extra = 0) const override virtual
get a position on the edge of this object
Implements openage::TerrainObject.
Definition at line 423 of file terrain_object.cpp.
{
     return this->pos.draw + (angle - this->pos.draw).to_phys2().normalize((this->phys_radius + extra).to_double()).to_phys3();
 }
References openage::tile_range::draw, phys_radius, and openage::TerrainObject::pos.
Friends And Related Function Documentation
TerrainObject
friend class TerrainObject friend
Definition at line 349 of file terrain_object.h.
Unit
friend class Unit friend
Definition at line 350 of file terrain_object.h.
Member Data Documentation
phys_radius
const coord::phys_t openage::RadialObject::phys_radius
radius of this cirular space
Definition at line 332 of file terrain_object.h.
Referenced by contains(), from_edge(), get_range(), intersects(), min_axis(), and on_edge().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/terrain/terrain_object.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/terrain/terrain_object.cpp