openage: qtsdl::GuiImageProviderImpl Class Reference
qtsdl::GuiImageProviderImpl Class Reference abstract
#include <gui_image_provider_impl.h>
Public Member Functions
GuiImageProviderImpl ()
virtual ~GuiImageProviderImpl ()
virtual const char * get_id () const =0
virtual void give_up ()=0
Static Public Member Functions
static std::unique_ptr< GuiImageProviderImpl > take_ownership (GuiImageProvider *image_provider)
static std::vector< std::unique_ptr< GuiImageProviderImpl > > take_ownership (const std::vector< GuiImageProvider * > &image_providers)
Detailed Description
Definition at line 14 of file gui_image_provider_impl.h.
Constructor & Destructor Documentation
GuiImageProviderImpl()
qtsdl::GuiImageProviderImpl::GuiImageProviderImpl () explicit
Definition at line 11 of file gui_image_provider_impl.cpp.
     :
     QQuickImageProvider{QQmlImageProviderBase::Texture, QQuickImageProvider::ForceAsynchronousImageLoading} {
 }
~GuiImageProviderImpl()
qtsdl::GuiImageProviderImpl::~GuiImageProviderImpl () virtual
Definition at line 16 of file gui_image_provider_impl.cpp.
{
 }
Member Function Documentation
get_id()
virtual const char* qtsdl::GuiImageProviderImpl::get_id () const pure virtual
Implemented in openage::gui::GuiGameSpecImageProviderByFilenameImpl, openage::gui::GuiGameSpecImageProviderByGraphicIdImpl, and openage::gui::GuiGameSpecImageProviderByTerrainIdImpl.
Referenced by openage::gui::GuiGameSpecImageProviderByIdImpl::get_texture_handle(), openage::gui::GuiImageProviderLink::provider(), and qtsdl::QmlEngineWithSingletonItemsInfo::~QmlEngineWithSingletonItemsInfo().
give_up()
virtual void qtsdl::GuiImageProviderImpl::give_up () pure virtual
Implemented in openage::gui::GuiGameSpecImageProviderImpl.
Referenced by qtsdl::QmlEngineWithSingletonItemsInfo::~QmlEngineWithSingletonItemsInfo().
take_ownership() [1/2]
std::unique_ptr< GuiImageProviderImpl > qtsdl::GuiImageProviderImpl::take_ownership (GuiImageProvider * image_provider) static
Definition at line 19 of file gui_image_provider_impl.cpp.
{
     std::unique_ptr<GuiImageProviderImpl> ptr{image_provider->impl.release()};
     image_provider->impl = decltype(image_provider->impl) {ptr.get(), [] (GuiImageProviderImpl*) {}};
     return ptr;
 }
References qtsdl::GuiImageProvider::impl.
Referenced by take_ownership().
take_ownership() [2/2]
std::vector< std::unique_ptr< GuiImageProviderImpl > > qtsdl::GuiImageProviderImpl::take_ownership (const std::vector< GuiImageProvider * > & image_providers) static
Definition at line 25 of file gui_image_provider_impl.cpp.
{
     std::vector<std::unique_ptr<GuiImageProviderImpl>> image_provider_owning_ptrs(image_providers.size());
     std::transform(std::begin(image_providers), std::end(image_providers), std::begin(image_provider_owning_ptrs), static_cast<std::unique_ptr<GuiImageProviderImpl>(*)(GuiImageProvider*)>(GuiImageProviderImpl::take_ownership));
     return image_provider_owning_ptrs;
 }
References take_ownership().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/guisys/private/gui_image_provider_impl.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/guisys/private/gui_image_provider_impl.cpp