openage: openage::HealAbility Class Reference
openage::HealAbility Class Reference
#include <ability.h>
Public Member Functions
HealAbility (const Sound *s=nullptr)
ability_type type () override
bool can_invoke (Unit &to_modify, const Command &cmd) override
void invoke (Unit &to_modify, const Command &cmd, bool play_sound=false) override
Public Member Functions inherited from openage::UnitAbility
virtual ~UnitAbility ()
bool has_hitpoints (Unit &target)
bool is_damaged (Unit &target)
bool has_resource (Unit &target)
bool is_same_player (Unit &to_modify, Unit &target)
bool is_ally (Unit &to_modify, Unit &target)
bool is_enemy (Unit &to_modify, Unit &target)
Private Attributes
const Sound * sound
Additional Inherited Members
Static Public Member Functions inherited from openage::UnitAbility
static ability_set set_from_list (const std::vector< ability_type > &items)
Detailed Description
initiates a heal action when given a valid target
Definition at line 309 of file ability.h.
Constructor & Destructor Documentation
HealAbility()
openage::HealAbility::HealAbility (const Sound * s = nullptr)
Definition at line 330 of file ability.cpp.
     :
     sound{s} {
 }
Member Function Documentation
can_invoke()
bool openage::HealAbility::can_invoke (Unit & to_modify, const Command & cmd) override virtual
true if the paramaters allow an action to be performed
Implements openage::UnitAbility.
Definition at line 335 of file ability.cpp.
{
     if (cmd.has_unit()) {
         Unit &target = *cmd.unit();
         return &to_modify != &target &&
                to_modify.location &&
                target.location &&
                target.location->is_placed() &&
                is_damaged(target) &&
                is_ally(to_modify, target);
     }
     return false;
 }
References openage::Command::has_unit(), openage::UnitAbility::is_ally(), openage::UnitAbility::is_damaged(), openage::Unit::location, and openage::Command::unit().
invoke()
void openage::HealAbility::invoke (Unit & to_modify, const Command & cmd, bool play_sound = false) override virtual
applies command to a given unit
Implements openage::UnitAbility.
Definition at line 348 of file ability.cpp.
{
     to_modify.log(MSG(dbg) << "invoke heal action");
     if (play_sound && this->sound) {
         this->sound->play();
     }
     Unit *target = cmd.unit();
     to_modify.push_action(std::make_unique<HealAction>(&to_modify, target->get_ref()));
 }
References openage::log::dbg(), openage::Unit::get_ref(), openage::log::LogSource::log(), MSG, openage::Sound::play(), openage::Unit::push_action(), sound, and openage::Command::unit().
type()
ability_type openage::HealAbility::type () inline override virtual
Implements openage::UnitAbility.
Definition at line 313 of file ability.h.
{
         return ability_type::heal;
     }
References openage::heal.
Member Data Documentation
sound
const Sound* openage::HealAbility::sound private
Definition at line 322 of file ability.h.
Referenced by invoke().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/ability.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/ability.cpp