openage: openage::renderer::opengl::GlGeometry Class Reference
openage::renderer::opengl::GlGeometry Class Reference final
The OpenGL class representing geometry to be passed to a draw call.
#include <geometry.h>
Classes
struct GlMesh
All the pieces of OpenGL state that represent a mesh.
Public Member Functions
GlGeometry ()
The default constructor makes a quad.
GlGeometry (resources::MeshData const &)
Initialize a meshed geometry. Relatively costly, has to initialize GL buffers and copy vertex data.
void draw () const
void update_verts_offset (std::vector< uint8_t > const &, size_t) override
Public Member Functions inherited from openage::renderer::Geometry
virtual ~Geometry ()=default
geometry_t get_type () const
Returns the type of this geometry.
void update_verts (std::vector< uint8_t > const &verts)
Private Attributes
std::optional< GlMesh > mesh
Additional Inherited Members
Protected Member Functions inherited from openage::renderer::Geometry
Geometry (geometry_t type)
Initialize the geometry to a given type.
Detailed Description
The OpenGL class representing geometry to be passed to a draw call.
Definition at line 19 of file geometry.h.
Constructor & Destructor Documentation
GlGeometry() [1/2]
openage::renderer::opengl::GlGeometry::GlGeometry ()
The default constructor makes a quad.
Definition at line 17 of file geometry.cpp.
     : Geometry(geometry_t::bufferless_quad) {}
References openage::renderer::bufferless_quad.
GlGeometry() [2/2]
openage::renderer::opengl::GlGeometry::GlGeometry (resources::MeshData const & mesh) explicit
Initialize a meshed geometry. Relatively costly, has to initialize GL buffers and copy vertex data.
Definition at line 20 of file geometry.cpp.
     : Geometry(geometry_t::mesh) {
     GlBuffer verts_buf(mesh.get_data().data(), mesh.get_data().size());
     GlVertexArray verts_array(verts_buf, mesh.get_info());
     this->mesh = GlMesh {
         std::move(verts_buf),
         std::move(verts_array),
         {},
         {},
         mesh.get_data().size() / mesh.get_info().vert_size(),
         GL_PRIMITIVE.get(mesh.get_info().get_primitive()),
     };
     if (mesh.get_ids()) {
         this->mesh->indices = GlBuffer(mesh.get_ids()->data(), mesh.get_ids()->size());
         this->mesh->index_type = GL_INDEX_TYPE.get(*mesh.get_info().get_index_type());
         this->mesh->vert_count = mesh.get_ids()->size() / sizeof(GLuint);
     }
 }
References openage::renderer::opengl::GL_INDEX_TYPE, openage::renderer::opengl::GL_PRIMITIVE, openage::renderer::mesh, mesh, and openage::move.
Member Function Documentation
draw()
void openage::renderer::opengl::GlGeometry::draw () const
Executes a draw command for the geometry on the currently active context. Assumes bound and valid shader program and all other necessary state.
Definition at line 54 of file geometry.cpp.
{
     switch (this->get_type()) {
     case geometry_t::bufferless_quad:
         glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);
         break;
     case geometry_t::mesh: {
         auto const& mesh = *this->mesh;
         mesh.vao.bind();
         if (mesh.indices) {
             mesh.indices->bind(GL_ELEMENT_ARRAY_BUFFER);
             glDrawElements(mesh.primitive, mesh.vert_count, *mesh.index_type, nullptr);
         } else {
             glDrawArrays(GL_TRIANGLE_STRIP, 0, mesh.vert_count);
         }
         break;
     }
     default:
         throw Error(MSG(err) << "Unknown geometry type in GlGeometry.");
     }
 }
References openage::renderer::bufferless_quad, openage::log::err(), openage::renderer::Geometry::get_type(), openage::renderer::mesh, mesh, and MSG.
Referenced by openage::renderer::opengl::GlShaderProgram::execute_with().
update_verts_offset()
void openage::renderer::opengl::GlGeometry::update_verts_offset (std::vector< uint8_t > const & verts, size_t offset) override virtual
In a meshed geometry, updates the vertex data starting from the offset-th vertex. The type of the vertex data has to be the same as it was on initializing the geometry. The size plus the offset cannot exceed the previous size of the vertex data. If the mesh is indexed, indices will stay the same.
Exceptions
if there is a size mismatch between the new and old vertex data
Implements openage::renderer::Geometry.
Definition at line 41 of file geometry.cpp.
{
     if (this->get_type() != geometry_t::mesh) {
         throw Error(MSG(err) << "Cannot update vertex data for non-mesh GlGeometry.");
     }
     if (verts.size() != this->mesh->vertices.get_size()) {
         throw Error(MSG(err) << "Size mismatch between old and new vertex data for GlGeometry.");
     }
     // \todo support offset updating
     this->mesh->vertices.upload_data(verts.data(), offset, verts.size());
 }
References openage::log::err(), openage::renderer::Geometry::get_type(), openage::renderer::mesh, mesh, and MSG.
Member Data Documentation
mesh
std::optional<GlMesh> openage::renderer::opengl::GlGeometry::mesh private
Data managing GPU memory and interpretation of mesh data. Only present if the type is a mesh.
Definition at line 46 of file geometry.h.
Referenced by draw(), GlGeometry(), and update_verts_offset().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/opengl/geometry.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/opengl/geometry.cpp