openage: openage::renderer::vulkan::VlkDrawableDisplay Class Reference
openage::renderer::vulkan::VlkDrawableDisplay Class Reference
A Vulkan representation of a display target that can be drawn onto directly, that is not by copying data from another object.
#include <render_target.h>
Public Member Functions
VkSurfaceFormatKHR choose_best_surface_format (std::vector< VkSurfaceFormatKHR > const &formats)
VkPresentModeKHR choose_best_present_mode (std::vector< VkPresentModeKHR > const &modes)
VlkDrawableDisplay (VkDevice device, SurfaceSupportDetails details)
~VlkDrawableDisplay ()
Public Attributes
VkDevice device
VkSwapchainKHR swapchain
VkFormat format
VkExtent2D extent
std::vector< VkImage > images
std::vector< VkImageView > image_views
std::vector< VkFramebuffer > framebuffers
Detailed Description
A Vulkan representation of a display target that can be drawn onto directly, that is not by copying data from another object.
Definition at line 18 of file render_target.h.
Constructor & Destructor Documentation
VlkDrawableDisplay()
openage::renderer::vulkan::VlkDrawableDisplay::VlkDrawableDisplay (VkDevice device, SurfaceSupportDetails details) inline
Definition at line 73 of file render_target.h.
         : device(device) {
         VkSurfaceFormatKHR format = choose_best_surface_format(details.surface_formats);
         this->format = format.format;
         VkPresentModeKHR mode = choose_best_present_mode(details.present_modes);
         if (details.surface_caps.currentExtent.width != std::numeric_limits<uint32_t>::max()) {
             this->extent = details.surface_caps.currentExtent;
         } else {
             // \todo choose a size from this->size in this case
             throw Error(MSG(err) << "Window manager does not provide a window size.");
         }
         uint32_t img_count = details.surface_caps.minImageCount + 1;
         if (details.surface_caps.maxImageCount != 0) {
             img_count = std::max(img_count, details.surface_caps.maxImageCount);
         }
         VkSwapchainCreateInfoKHR cr_swap = {};
         cr_swap.sType = VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR;
         cr_swap.surface = details.surface;
         cr_swap.minImageCount = img_count;
         cr_swap.imageFormat = this->format;
         cr_swap.imageColorSpace = format.colorSpace;
         cr_swap.presentMode = mode;
         // \todo why doesn't validation work?
         cr_swap.imageExtent = this->extent;
         cr_swap.imageArrayLayers = 1;
         // or VK_IMAGE_USAGE_TRANSFER_DST_BIT if not drawing directly (postprocess)
         cr_swap.imageUsage = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT;
         if (details.maybe_present_fam) {
             // We have to share the swapchain between different queues in this case
             cr_swap.imageSharingMode = VK_SHARING_MODE_CONCURRENT;
             cr_swap.queueFamilyIndexCount = 2;
             std::array<uint32_t, 2> q_fams = {{ details.graphics_fam, *details.maybe_present_fam }};
             cr_swap.pQueueFamilyIndices = q_fams.data();
         } else {
             // Otherwise only one queue can access it
             cr_swap.imageSharingMode = VK_SHARING_MODE_EXCLUSIVE;
         }
         cr_swap.preTransform = details.surface_caps.currentTransform;
         cr_swap.compositeAlpha = VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR;
         // Discard pixels which are not visible
         cr_swap.clipped = VK_TRUE;
         cr_swap.oldSwapchain = VK_NULL_HANDLE;
         VK_CALL_CHECKED(vkCreateSwapchainKHR, this->device, &cr_swap, nullptr, &this->swapchain);
         this->images = vk_do_ritual(vkGetSwapchainImagesKHR, this->device, this->swapchain);
         // \todo move out?
         for (auto img : this->images) {
             VkImageViewCreateInfo cr_view = {};
             cr_view.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
             cr_view.image = img;
             cr_view.viewType = VK_IMAGE_VIEW_TYPE_2D;
             cr_view.format = this->format;
             cr_view.components.r = VK_COMPONENT_SWIZZLE_IDENTITY;
             cr_view.components.g = VK_COMPONENT_SWIZZLE_IDENTITY;
             cr_view.components.b = VK_COMPONENT_SWIZZLE_IDENTITY;
             cr_view.components.a = VK_COMPONENT_SWIZZLE_IDENTITY;
             cr_view.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
             cr_view.subresourceRange.baseMipLevel = 0;
             cr_view.subresourceRange.levelCount = 1;
             cr_view.subresourceRange.baseArrayLayer = 0;
             cr_view.subresourceRange.layerCount = 1;
             VkImageView view;
             VK_CALL_CHECKED(vkCreateImageView, this->device, &cr_view, nullptr, &view);
             this->image_views.push_back(view);
         }
     }
References choose_best_present_mode(), choose_best_surface_format(), openage::log::err(), extent, format, openage::renderer::vulkan::SurfaceSupportDetails::graphics_fam, openage::console::tests::max(), std::max(), openage::renderer::vulkan::SurfaceSupportDetails::maybe_present_fam, MSG, openage::renderer::vulkan::SurfaceSupportDetails::present_modes, openage::renderer::vulkan::SurfaceSupportDetails::surface, openage::renderer::vulkan::SurfaceSupportDetails::surface_caps, openage::renderer::vulkan::SurfaceSupportDetails::surface_formats, VK_CALL_CHECKED, and vk_do_ritual().
~VlkDrawableDisplay()
openage::renderer::vulkan::VlkDrawableDisplay::~VlkDrawableDisplay () inline
Definition at line 150 of file render_target.h.
{
         vkDestroySwapchainKHR(this->device, this->swapchain, nullptr);
     }
Member Function Documentation
choose_best_present_mode()
VkPresentModeKHR openage::renderer::vulkan::VlkDrawableDisplay::choose_best_present_mode (std::vector< VkPresentModeKHR > const & modes) inline
Definition at line 50 of file render_target.h.
{
         VkPresentModeKHR ret = VK_PRESENT_MODE_MAILBOX_KHR;
         for (const auto& mode : modes) {
             if (mode == VK_PRESENT_MODE_MAILBOX_KHR) {
                 return mode;
             } else if (mode == VK_PRESENT_MODE_FIFO_KHR) {
                 ret = mode;
             } else if (mode == VK_PRESENT_MODE_FIFO_RELAXED_KHR
                        && ret != VK_PRESENT_MODE_FIFO_KHR)
             {
                 ret = mode;
             } else if (mode == VK_PRESENT_MODE_IMMEDIATE_KHR
                        && ret != VK_PRESENT_MODE_FIFO_KHR
                        && ret != VK_PRESENT_MODE_FIFO_RELAXED_KHR)
             {
                 ret = mode;
             }
         }
         return ret;
     }
Referenced by VlkDrawableDisplay().
choose_best_surface_format()
VkSurfaceFormatKHR openage::renderer::vulkan::VlkDrawableDisplay::choose_best_surface_format (std::vector< VkSurfaceFormatKHR > const & formats) inline
Definition at line 29 of file render_target.h.
{
         // If the implementation doesn't have preferred formats, choose our own
         if (formats.size() == 1
             && formats[0].format == VK_FORMAT_UNDEFINED)
         {
             return { VK_FORMAT_B8G8R8A8_UNORM, VK_COLOR_SPACE_SRGB_NONLINEAR_KHR };
         }
         // Otherwise if one of the preferred formats is good, choose that
         for (const auto& fmt : formats) {
             if (fmt.format == VK_FORMAT_B8G8R8_UNORM
                 && fmt.colorSpace == VK_COLOR_SPACE_SRGB_NONLINEAR_KHR)
             {
                 return fmt;
             }
         }
         // Otherwise select any format
         return formats[0];
     }
Referenced by VlkDrawableDisplay().
Member Data Documentation
device
VkDevice openage::renderer::vulkan::VlkDrawableDisplay::device
Definition at line 21 of file render_target.h.
extent
VkExtent2D openage::renderer::vulkan::VlkDrawableDisplay::extent
Definition at line 24 of file render_target.h.
Referenced by VlkDrawableDisplay().
format
VkFormat openage::renderer::vulkan::VlkDrawableDisplay::format
Definition at line 23 of file render_target.h.
Referenced by VlkDrawableDisplay().
framebuffers
std::vector<VkFramebuffer> openage::renderer::vulkan::VlkDrawableDisplay::framebuffers
Definition at line 27 of file render_target.h.
image_views
std::vector<VkImageView> openage::renderer::vulkan::VlkDrawableDisplay::image_views
Definition at line 26 of file render_target.h.
images
std::vector<VkImage> openage::renderer::vulkan::VlkDrawableDisplay::images
Definition at line 25 of file render_target.h.
swapchain
VkSwapchainKHR openage::renderer::vulkan::VlkDrawableDisplay::swapchain
Definition at line 22 of file render_target.h.
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/vulkan/render_target.h