openage: openage::SquareObject Class Reference
openage::SquareObject Class Reference
terrain object class represents one immobile object on the map (building, trees, fish, ...).
#include <terrain_object.h>
Public Member Functions
virtual ~SquareObject ()
tile_range get_range (const coord::phys3 &pos, const Terrain &terrain) const override
calculate object start and end positions.
coord::phys_t from_edge (const coord::phys3 &point) const override
how far is a point from the edge of this object
coord::phys3 on_edge (const coord::phys3 &angle, coord::phys_t extra=0) const override
get a position on the edge of this object
bool contains (const coord::phys3 &other) const override
does this space contain a given point
bool intersects (const TerrainObject &other, const coord::phys3 &position) const override
would this intersect with another object if it were positioned at the given point
coord::phys_t min_axis () const override
the shortest line that can be placed across the objects center
Public Member Functions inherited from openage::TerrainObject
TerrainObject (Unit &u)
TerrainObject (const TerrainObject &)=delete
TerrainObject (TerrainObject &&)=delete
virtual ~TerrainObject ()
bool is_floating () const
is the object a floating outline – it is only an indicator of where a building will be built, but not yet started building and does not affect any collisions
bool is_placed () const
returns true if this object has been placed.
bool check_collisions () const
should this object be tested for collisions, which decides whether another object is allowed to overlap the location of this object.
void draw_outline (const coord::CoordManager &coord) const
draws outline of this terrain space in current position
bool place (object_state init_state)
changes the placement state of this object keeping the existing position.
bool place (const std::shared_ptr< Terrain > &t, coord::phys3 &pos, object_state init_state)
binds the TerrainObject to a certain TerrainChunk.
bool move (coord::phys3 &pos)
moves the object – returns false if object cannot be moved here
void remove ()
remove this TerrainObject from the terrain chunks.
void set_ground (int id, int additional=0)
sets all the ground below the object to a terrain id.
template<class T , typename ... Arg>
TerrainObject * make_annex (Arg ... args)
appends new annex location for this object
const TerrainObject * get_parent () const
Returns the parent terrain object, if null the object has no parent which is the case for most objects.
std::vector< TerrainObject * > get_children () const
Returns a list of child objects, this is the inverse of the get_parent() function.
std::shared_ptr< Terrain > get_terrain () const
bool operator< (const TerrainObject &other)
comparison for TerrainObjects.
Public Attributes
const coord::tile_delta size
tile size of this objects base
Public Attributes inherited from openage::TerrainObject
tile_range pos
the range of tiles which are covered by this object
Unit & unit
std::function< bool(const coord::phys3 &)> passable
decide which terrains this object can be on this function should be true if given a valid position for the object
std::function< void(const Engine &e)> draw
specifies content to be drawn
Private Member Functions
SquareObject (Unit &u, coord::tile_delta foundation_size)
SquareObject (Unit &u, coord::tile_delta foundation_size, std::shared_ptr< Texture > out_tex)
Friends
class TerrainObject
class Unit
Additional Inherited Members
Protected Member Functions inherited from openage::TerrainObject
void place_unchecked (const std::shared_ptr< Terrain > &t, coord::phys3 &position)
placement function which does not check passibility used only when passibilty is already checked otherwise the place function should be used this does not modify the units placement state
Protected Attributes inherited from openage::TerrainObject
object_state state
std::weak_ptr< Terrain > terrain
int occupied_chunk_count
TerrainChunk * occupied_chunk [4]
TerrainObject * parent
annexes and grouped units
std::vector< std::unique_ptr< TerrainObject > > children
std::shared_ptr< Texture > outline_texture
texture for drawing outline
Detailed Description
terrain object class represents one immobile object on the map (building, trees, fish, ...).
can only be constructed by unit->make_location<SquareObject>(...)
Definition at line 276 of file terrain_object.h.
Constructor & Destructor Documentation
~SquareObject()
openage::SquareObject::~SquareObject () virtual
Definition at line 305 of file terrain_object.cpp.
 {}
SquareObject() [1/2]
openage::SquareObject::SquareObject (Unit & u, coord::tile_delta foundation_size) private
Definition at line 293 of file terrain_object.cpp.
     :
     SquareObject(u, foundation_size, square_outline(foundation_size)) {
 }
SquareObject() [2/2]
openage::SquareObject::SquareObject (Unit & u, coord::tile_delta foundation_size, std::shared_ptr< Texture > out_tex) private
Definition at line 298 of file terrain_object.cpp.
     :
     TerrainObject(u),
     size(foundation_size) {
     this->outline_texture = out_tex;
 }
References openage::TerrainObject::outline_texture.
Member Function Documentation
contains()
bool openage::SquareObject::contains (const coord::phys3 & other) const override virtual
does this space contain a given point
Implements openage::TerrainObject.
Definition at line 337 of file terrain_object.cpp.
{
     coord::tile other_tile = other.to_tile3().to_tile();
     for (coord::tile check_pos : tile_list(this->pos)) {
         if (check_pos == other_tile) {
             return true;
         }
     }
     return false;
 }
References openage::TerrainObject::pos, openage::tile_list(), openage::coord::tile3::to_tile(), and openage::coord::phys3::to_tile3().
from_edge()
coord::phys_t openage::SquareObject::from_edge (const coord::phys3 & point) const override virtual
how far is a point from the edge of this object
Implements openage::TerrainObject.
Definition at line 311 of file terrain_object.cpp.
{
     // clamp between start and end
     coord::phys2 start_phys = this->pos.start.to_phys2();
     coord::phys2 end_phys = this->pos.end.to_phys2();
     coord::phys_t cx = std::max(start_phys.ne, std::min(end_phys.ne, point.ne));
     coord::phys_t cy = std::max(start_phys.se, std::min(end_phys.se, point.se));
     // distance to clamped point
     coord::phys_t dx = point.ne - cx;
     coord::phys_t dy = point.se - cy;
     return std::hypot(dx, dy);
 }
References openage::tile_range::end, std::hypot(), std::max(), std::min(), openage::TerrainObject::pos, openage::tile_range::start, and openage::coord::tile::to_phys2().
get_range()
tile_range openage::SquareObject::get_range (const coord::phys3 & pos, const Terrain & terrain) const override virtual
calculate object start and end positions.
Parameters
pos the center position of the building
set the center position to "middle", start_pos is % and end_pos = &
for a building, the # tile will be "the clicked one": @ @ @ @ @ @ @ %# & @ @ @ % # & @ % # @ & @ @ @ @ @ @ @ @ @
Implements openage::TerrainObject.
Definition at line 307 of file terrain_object.cpp.
{
     return building_center(pos, this->size, terrain);
 }
References openage::building_center(), openage::TerrainObject::pos, and size.
Referenced by intersects().
intersects()
bool openage::SquareObject::intersects (const TerrainObject & other, const coord::phys3 & position) const override virtual
would this intersect with another object if it were positioned at the given point
Implements openage::TerrainObject.
Definition at line 348 of file terrain_object.cpp.
{
     if (const SquareObject *sq = dynamic_cast<const SquareObject *>(&other)) {
         auto terrain_ptr = this->terrain.lock();
         if (not terrain_ptr) {
             throw Error{ERR << "object is not associated to a valid terrain"};
         }
         tile_range rng = this->get_range(position, *terrain_ptr);
         return this->pos.end.ne < rng.start.ne
                || rng.end.ne < sq->pos.start.ne
                || rng.end.se < sq->pos.start.se
                || rng.end.se < sq->pos.start.se;
     }
     else if (const RadialObject *rad = dynamic_cast<const RadialObject *>(&other)) {
         auto terrain_ptr = this->terrain.lock();
         if (not terrain_ptr) {
             throw Error{ERR << "object is not associated to a valid terrain"};
         }
         // clamp between start and end
         tile_range rng = this->get_range(position, *terrain_ptr);
         coord::phys2 start_phys = rng.start.to_phys2();
         coord::phys2 end_phys = rng.end.to_phys2();
         coord::phys_t cx = std::max(start_phys.ne, std::min(end_phys.ne, rad->pos.draw.ne));
         coord::phys_t cy = std::max(start_phys.se, std::min(end_phys.se, rad->pos.draw.se));
         // distance to square object base
         coord::phys_t dx = rad->pos.draw.ne - cx;
         coord::phys_t dy = rad->pos.draw.se - cy;
         return std::hypot(dx, dy) < rad->phys_radius.to_double();
     }
     return false;
 }
References openage::tile_range::end, ERR, get_range(), std::hypot(), std::max(), std::min(), openage::TerrainObject::pos, openage::tile_range::start, openage::TerrainObject::terrain, and openage::coord::tile::to_phys2().
min_axis()
coord::phys_t openage::SquareObject::min_axis () const override virtual
the shortest line that can be placed across the objects center
Implements openage::TerrainObject.
Definition at line 381 of file terrain_object.cpp.
{
     return std::min(this->size.ne, this->size.se);
 }
References std::min(), and size.
on_edge()
coord::phys3 openage::SquareObject::on_edge (const coord::phys3 & angle, coord::phys_t extra = 0) const override virtual
get a position on the edge of this object
Implements openage::TerrainObject.
Definition at line 325 of file terrain_object.cpp.
{
     // clamp between start and end
     // \todo extra is unused
     coord::phys2 start_phys = this->pos.start.to_phys2();
     coord::phys2 end_phys = this->pos.end.to_phys2();
     coord::phys_t cx = std::max(start_phys.ne, std::min(end_phys.ne, angle.ne));
     coord::phys_t cy = std::max(start_phys.se, std::min(end_phys.se, angle.se));
     // \todo use extra distance
     return coord::phys3{cx, cy, 0};
 }
References openage::tile_range::end, std::max(), std::min(), openage::TerrainObject::pos, openage::tile_range::start, and openage::coord::tile::to_phys2().
Friends And Related Function Documentation
TerrainObject
friend class TerrainObject friend
Definition at line 317 of file terrain_object.h.
Unit
friend class Unit friend
Definition at line 318 of file terrain_object.h.
Member Data Documentation
size
const coord::tile_delta openage::SquareObject::size
tile size of this objects base
Definition at line 285 of file terrain_object.h.
Referenced by openage.util.bytequeue.ByteQueue::__len__(), openage.util.bytequeue.ByteQueue::append(), get_range(), openage.util.filelike.stream.StreamFragment::get_size(), min_axis(), openage.util.bytequeue.ByteQueue::popleft(), and openage.util.filelike.stream.StreamFragment::read().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/terrain/terrain_object.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/terrain/terrain_object.cpp