openage: openage::ResearchAction Class Reference
openage::ResearchAction Class Reference
#include <action.h>
Public Member Functions
ResearchAction (Unit *e, Research *research)
virtual ~ResearchAction ()
void update (unsigned int time) override
void on_completion () override
bool completed () const override
bool allow_interupt () const override
bool allow_control () const override
std::string name () const override
float get_progress () const
const ResearchType * get_research_type () const
Public Member Functions inherited from openage::UnitAction
UnitAction (Unit *u, graphic_type initial_gt)
virtual ~UnitAction ()
graphic_type type () const
float current_frame () const
virtual const graphic_set & current_graphics () const
void draw_debug (const Engine &engine)
void face_towards (const coord::phys3 pos)
bool damage_unit (Unit &target)
void move_to (Unit &target, bool use_range=true)
Private Attributes
Research * research
IntervalTimer timer
bool complete
Additional Inherited Members
Static Public Member Functions inherited from openage::UnitAction
static coord::phys_t adjacent_range (Unit *u)
static coord::phys_t get_attack_range (Unit *u)
static coord::phys_t get_heal_range (Unit *u)
Static Public Attributes inherited from openage::UnitAction
static bool show_debug = false
Protected Attributes inherited from openage::UnitAction
Unit * entity
graphic_type graphic
float frame
float frame_rate
std::function< void(const Engine &)> debug_draw_action
Detailed Description
trains a new unit
Definition at line 470 of file action.h.
Constructor & Destructor Documentation
ResearchAction()
openage::ResearchAction::ResearchAction (Unit * e, Research * research)
Definition at line 856 of file action.cpp.
     :
     UnitAction{e, graphic_type::standing},
     research{research},
     timer{research->type->get_research_time(), 1},
     complete{false} {
     this->research->started();
 }
References openage::standing.
~ResearchAction()
virtual openage::ResearchAction::~ResearchAction () inline virtual
Definition at line 473 of file action.h.
 {}
Member Function Documentation
allow_control()
bool openage::ResearchAction::allow_control () const inline override virtual
control whether stack can discard the action automatically and should the stack be modifiable when this action is on top
if true this action must complete and will not allow new actions to be pushed while it is active and also does not update the secondary actions
Implements openage::UnitAction.
Definition at line 479 of file action.h.
 { return true; }
allow_interupt()
bool openage::ResearchAction::allow_interupt () const inline override virtual
checks if the action can be interrupted, allowing it to be popped if the user specifies a new action, if false the action must reach a completed state before removal eg dead action must be completed and cannot be discarded
Implements openage::UnitAction.
Definition at line 478 of file action.h.
 { return false; }
completed()
bool openage::ResearchAction::completed () const inline override virtual
gets called for all actions on stack each update cycle
Returns
true when action is completed so it and everything above it can be popped
Implements openage::UnitAction.
Definition at line 477 of file action.h.
 { return this->complete; }
References complete.
get_progress()
float openage::ResearchAction::get_progress () const inline
Definition at line 482 of file action.h.
 { return this->timer.get_progress(); }
References openage::IntervalTimer::get_progress(), and timer.
get_research_type()
const ResearchType* openage::ResearchAction::get_research_type () const inline
Definition at line 483 of file action.h.
 { return this->research->type; }
References openage::Research::type.
name()
std::string openage::ResearchAction::name () const inline override virtual
debug string to identify action types
Implements openage::UnitAction.
Definition at line 480 of file action.h.
 { return "train"; }
Referenced by openage.util.fslike.path.Path::stem(), openage.util.fslike.path.Path::suffix(), and openage.util.fslike.path.Path::suffixes().
on_completion()
void openage::ResearchAction::on_completion () override virtual
action to perform when popped from a units action stack
Implements openage::UnitAction.
Definition at line 873 of file action.cpp.
{
     if (!this->complete) {
         this->research->stopped();
     }
 }
References complete, research, and openage::Research::stopped().
update()
void openage::ResearchAction::update (unsigned int time) override virtual
each action has its own update functionality which gets called when this is the active action
Implements openage::UnitAction.
Definition at line 865 of file action.cpp.
{
     if (timer.update(time)) {
         this->complete = true;
         this->research->apply();
         this->research->completed();
     }
 }
References openage::Research::apply(), complete, openage::Research::completed(), research, timer, and openage::IntervalTimer::update().
Member Data Documentation
complete
bool openage::ResearchAction::complete private
Definition at line 490 of file action.h.
Referenced by completed(), on_completion(), and update().
research
Research* openage::ResearchAction::research private
Definition at line 487 of file action.h.
Referenced by on_completion(), and update().
timer
IntervalTimer openage::ResearchAction::timer private
Definition at line 489 of file action.h.
Referenced by get_progress(), and update().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/action.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/action.cpp