openage: openage::util::Matrix< M, N, T > Class Template Reference
openage::util::Matrix< M, N, T > Class Template Reference
Matrix class with arithmetic.
#include <matrix.h>
Public Types
using this_type = Matrix< M, N, T >
Public Member Functions
Matrix ()
Initialize the matrix to zeroes.
~Matrix ()=default
template<bool cond = is_column_vector, typename = typename std::enable_if<cond>::type>
Matrix (const Vector< M, T > &vec)
Constructor from Vector.
template<typename ... Ts>
Matrix (Ts ... args)
Constructor with N*M values.
bool equals (const this_type &other, float eps=default_eps) const
Test if both matrices contain the same values within epsilon.
template<size_t P>
Matrix< M, P, T > operator * (const Matrix< N, P, T > &other) const
Matrix multiplication.
Matrix< M, 1, T > operator * (const Vector< M, T > &vec) const
Matrix-Vector multiplication.
this_type operator+ (const this_type &other) const
Matrix addition.
this_type operator - (const this_type &other) const
Matrix subtraction.
void operator *= (T other)
Scalar multiplication with assignment.
this_type operator * (T other) const
Scalar multiplication.
void operator/= (T other)
Scalar division with assignment.
this_type operator/ (T other) const
Scalar division.
Matrix< N, M, T > transpose () const
Transposition.
template<bool cond = is_column_vector, typename = typename std::enable_if<cond>::type>
Vector< M, T > to_vector () const
Conversion to Vector.
template<bool cond = is_square, typename = typename std::enable_if<cond>::type>
T trace () const
Matrix trace: the sum of all diagonal entries.
Static Public Member Functions
template<bool cond = is_square, typename = typename std::enable_if<cond>::type>
static this_type identity ()
Constructs the identity matrix for the current size.
Static Public Attributes
static constexpr float default_eps = 1e-5
static constexpr size_t rows = M
static constexpr size_t cols = N
static constexpr bool is_square = (M == N)
static constexpr bool is_row_vector = (M == 1)
static constexpr bool is_column_vector = (N == 1)
Friends
std::ostream & operator<< (std::ostream &o, const this_type &mat)
Print to output stream using '<<'.
Detailed Description
template<size_t M, size_t N, typename T>
class openage::util::Matrix< M, N, T >
Matrix class with arithmetic.
M rows, N columns. T = underlying single value type (float, double, ...)
Definition at line 20 of file matrix.h.
Member Typedef Documentation
this_type
template<size_t M, size_t N, typename T> using openage::util::Matrix< M, N, T >::this_type = Matrix<M, N, T>
Definition at line 24 of file matrix.h.
Constructor & Destructor Documentation
Matrix() [1/3]
template<size_t M, size_t N, typename T> openage::util::Matrix< M, N, T >::Matrix () inline
Initialize the matrix to zeroes.
Definition at line 37 of file matrix.h.
              {
         for (size_t i = 0; i < M; i++) {
             for (size_t j = 0; j < N; j++) {
                 (*this)[i][j] = 0;
             }
         }
     }
~Matrix()
template<size_t M, size_t N, typename T> openage::util::Matrix< M, N, T >::~Matrix () default
Matrix() [2/3]
template<size_t M, size_t N, typename T> template<bool cond = is_column_vector, typename = typename std::enable_if<cond>::type> openage::util::Matrix< M, N, T >::Matrix (const Vector< M, T > & vec) inline
Constructor from Vector.
Definition at line 52 of file matrix.h.
{
         for (size_t i = 0; i < M; i++) {
             (*this)[i][0] = vec[i];
         }
     }
Matrix() [3/3]
template<size_t M, size_t N, typename T> template<typename ... Ts> openage::util::Matrix< M, N, T >::Matrix (Ts ... args) inline
Constructor with N*M values.
Definition at line 62 of file matrix.h.
{
         static_assert(sizeof...(args) == N*M, "not all values supplied");
         std::array<float, N*M> temp{{static_cast<T>(args)...}};
         for (size_t i = 0; i < N*M; i++) {
             (*this)[i / (N*M)][i % (N*M)] = temp[i];
         }
     }
Member Function Documentation
equals()
template<size_t M, size_t N, typename T> bool openage::util::Matrix< M, N, T >::equals (const this_type & other, float eps = default_eps) const inline
Test if both matrices contain the same values within epsilon.
Definition at line 89 of file matrix.h.
{
         for (size_t i = 0; i < N; i++) {
             for (size_t j = 0; j < M; j++) {
                 if (std::abs((*this)[i][j] - other[i][j]) >= eps) {
                     return false;
                 }
             }
         }
         return true;
     }
References std::abs().
Referenced by openage::util::tests::quaternion().
identity()
template<size_t M, size_t N, typename T> template<bool cond = is_square, typename = typename std::enable_if<cond>::type> static this_type openage::util::Matrix< M, N, T >::identity () inline static
Constructs the identity matrix for the current size.
Definition at line 76 of file matrix.h.
{
         this_type res;
         for (size_t i = 0; i < N; i++) {
             res[i][i] = 1;
         }
         return res;
     }
Referenced by openage::util::tests::quaternion().
operator *() [1/3]
template<size_t M, size_t N, typename T> template<size_t P> Matrix<M, P, T> openage::util::Matrix< M, N, T >::operator * (const Matrix< N, P, T > & other) const inline
Matrix multiplication.
Definition at line 104 of file matrix.h.
{
         Matrix<M, P, T> res;
         for (size_t i = 0; i < M; i++) {
             for (size_t j = 0; j < P; j++) {
                 res[i][j] = 0;
                 for (size_t k = 0; k < N; k++) {
                     res[i][j] += (*this)[i][k] * other[k][j];
                 }
             }
         }
         return res;
     }
operator *() [2/3]
template<size_t M, size_t N, typename T> Matrix<M, 1, T> openage::util::Matrix< M, N, T >::operator * (const Vector< M, T > & vec) const inline
Matrix-Vector multiplication.
Definition at line 120 of file matrix.h.
{
         return (*this) * static_cast<Matrix<M, 1, T>>(vec);
     }
operator *() [3/3]
template<size_t M, size_t N, typename T> this_type openage::util::Matrix< M, N, T >::operator * (T other) const inline
Scalar multiplication.
Definition at line 164 of file matrix.h.
{
         this_type res(*this);
         res *= other;
         return res;
     }
operator *=()
template<size_t M, size_t N, typename T> void openage::util::Matrix< M, N, T >::operator *= (T other) inline
Scalar multiplication with assignment.
Definition at line 153 of file matrix.h.
{
         for (size_t i = 0; i < M; i++) {
             for (size_t j = 0; j < N; j++) {
                 (*this)[i][j] *= other;
             }
         }
     }
operator -()
template<size_t M, size_t N, typename T> this_type openage::util::Matrix< M, N, T >::operator - (const this_type & other) const inline
Matrix subtraction.
Definition at line 140 of file matrix.h.
{
         this_type res;
         for (size_t i = 0; i < M; i++) {
             for (size_t j = 0; j < N; j++) {
                 res[i][j] = (*this)[i][j] - other[i][j];
             }
         }
         return res;
     }
operator+()
template<size_t M, size_t N, typename T> this_type openage::util::Matrix< M, N, T >::operator+ (const this_type & other) const inline
Matrix addition.
Definition at line 127 of file matrix.h.
{
         this_type res;
         for (size_t i = 0; i < M; i++) {
             for (size_t j = 0; j < N; j++) {
                 res[i][j] = (*this)[i][j] + other[i][j];
             }
         }
         return res;
     }
operator/()
template<size_t M, size_t N, typename T> this_type openage::util::Matrix< M, N, T >::operator/ (T other) const inline
Scalar division.
Definition at line 184 of file matrix.h.
{
         this_type res(*this);
         res /= other;
         return res;
     }
operator/=()
template<size_t M, size_t N, typename T> void openage::util::Matrix< M, N, T >::operator/= (T other) inline
Scalar division with assignment.
Definition at line 173 of file matrix.h.
{
         for (size_t i = 0; i < M; i++) {
             for (size_t j = 0; j < N; j++) {
                 (*this)[i][j] /= other;
             }
         }
     }
to_vector()
template<size_t M, size_t N, typename T> template<bool cond = is_column_vector, typename = typename std::enable_if<cond>::type> Vector<M, T> openage::util::Matrix< M, N, T >::to_vector () const inline
Conversion to Vector.
Definition at line 208 of file matrix.h.
{
         Vector<M, T> res{};
         for (size_t i = 0; i < M; i++) {
             res[i] = (*this)[i][0];
         }
         return res;
     }
trace()
template<size_t M, size_t N, typename T> template<bool cond = is_square, typename = typename std::enable_if<cond>::type> T openage::util::Matrix< M, N, T >::trace () const inline
Matrix trace: the sum of all diagonal entries.
Definition at line 221 of file matrix.h.
                     {
         T res = 0;
         for (size_t i = 0; i < N; i++) {
             res += (*this)[i][i];
         }
         return res;
     }
Referenced by openage::util::Quaternion< T >::Quaternion().
transpose()
template<size_t M, size_t N, typename T> Matrix<N, M, T> openage::util::Matrix< M, N, T >::transpose () const inline
Transposition.
Definition at line 193 of file matrix.h.
{
         Matrix <N, M, T> res;
         for (size_t i = 0; i < M; i++) {
             for (size_t j = 0; j < N; j++) {
                 res[j][i] = (*this)[i][j];
             }
         }
         return res;
     }
Referenced by openage::util::tests::matrix().
Friends And Related Function Documentation
operator<<
template<size_t M, size_t N, typename T> std::ostream& operator<< (std::ostream & o, const this_type & mat) friend
Print to output stream using '<<'.
Definition at line 234 of file matrix.h.
{
         o << "(";
         for (size_t j = 0; j < M-1; j++) {
             o << "(";
             for (size_t i = 0; i < N-1; i++) {
                 o << mat[j][i] << ",\t";
             }
             o << mat[j][N-1] << ")";
             o << "," << std::endl << " ";
         }
         o << "(";
         for (size_t i = 0; i < N-1; i++) {
             o << mat[M-1][i] << ",\t";
         }
         o << mat[M-1][N-1] << "))";
         return o;
     }
Member Data Documentation
cols
template<size_t M, size_t N, typename T> constexpr size_t openage::util::Matrix< M, N, T >::cols = N static
Definition at line 29 of file matrix.h.
default_eps
template<size_t M, size_t N, typename T> constexpr float openage::util::Matrix< M, N, T >::default_eps = 1e-5 static
Definition at line 26 of file matrix.h.
is_column_vector
template<size_t M, size_t N, typename T> constexpr bool openage::util::Matrix< M, N, T >::is_column_vector = (N == 1) static
Definition at line 32 of file matrix.h.
is_row_vector
template<size_t M, size_t N, typename T> constexpr bool openage::util::Matrix< M, N, T >::is_row_vector = (M == 1) static
Definition at line 31 of file matrix.h.
is_square
template<size_t M, size_t N, typename T> constexpr bool openage::util::Matrix< M, N, T >::is_square = (M == N) static
Definition at line 30 of file matrix.h.
rows
template<size_t M, size_t N, typename T> constexpr size_t openage::util::Matrix< M, N, T >::rows = M static
Definition at line 28 of file matrix.h.
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/matrix.h