openage: openage::UnitAbility Class Reference
openage::UnitAbility Class Reference abstract
Abilities create an action when given a target some abilities target positions such as moving or patroling others target other game objects, such as attacking or collecting relics.
#include <ability.h>
Public Member Functions
virtual ~UnitAbility ()
virtual ability_type type ()=0
virtual bool can_invoke (Unit &to_modify, const Command &cmd)=0
true if the paramaters allow an action to be performed
virtual void invoke (Unit &to_modify, const Command &cmd, bool play_sound=false)=0
applies command to a given unit
bool has_hitpoints (Unit &target)
some common functions
bool is_damaged (Unit &target)
bool has_resource (Unit &target)
bool is_same_player (Unit &to_modify, Unit &target)
bool is_ally (Unit &to_modify, Unit &target)
bool is_enemy (Unit &to_modify, Unit &target)
Static Public Member Functions
static ability_set set_from_list (const std::vector< ability_type > &items)
set bits corresponding to abilities, useful for initialising an ability_set using a brace enclosed list
Detailed Description
Abilities create an action when given a target some abilities target positions such as moving or patroling others target other game objects, such as attacking or collecting relics.
Abilities are constructed with a default unit texture, but allow the texture to be specified with the invoke function
Definition at line 84 of file ability.h.
Constructor & Destructor Documentation
~UnitAbility()
virtual openage::UnitAbility::~UnitAbility () inline virtual
Definition at line 86 of file ability.h.
 {}
Member Function Documentation
can_invoke()
virtual bool openage::UnitAbility::can_invoke (Unit & to_modify, const Command & cmd) pure virtual
true if the paramaters allow an action to be performed
Implemented in openage::ConvertAbility, openage::PatrolAbility, openage::HealAbility, openage::RepairAbility, openage::AttackAbility, openage::GatherAbility, openage::BuildAbility, openage::ResearchAbility, openage::TrainAbility, openage::UngarrisonAbility, openage::GarrisonAbility, openage::SetPointAbility, and openage::MoveAbility.
has_hitpoints()
bool openage::UnitAbility::has_hitpoints (Unit & target)
some common functions
Definition at line 16 of file ability.cpp.
{
     return target.has_attribute(attr_type::damaged) &&
            target.get_attribute<attr_type::damaged>().hp > 0;
 }
References openage::damaged, openage::Unit::get_attribute(), and openage::Unit::has_attribute().
Referenced by openage::AttackAbility::can_invoke().
has_resource()
bool openage::UnitAbility::has_resource (Unit & target)
Definition at line 26 of file ability.cpp.
{
     return target.has_attribute(attr_type::resource) && !target.has_attribute(attr_type::worker) &&
            target.get_attribute<attr_type::resource>().amount > 0;
 }
References openage::Unit::get_attribute(), openage::Unit::has_attribute(), openage::resource, and openage::worker.
Referenced by openage::GatherAbility::can_invoke(), and openage::AttackAbility::can_invoke().
invoke()
virtual void openage::UnitAbility::invoke (Unit & to_modify, const Command & cmd, bool play_sound = false) pure virtual
applies command to a given unit
Implemented in openage::ConvertAbility, openage::PatrolAbility, openage::HealAbility, openage::RepairAbility, openage::AttackAbility, openage::GatherAbility, openage::BuildAbility, openage::ResearchAbility, openage::TrainAbility, openage::UngarrisonAbility, openage::GarrisonAbility, openage::SetPointAbility, and openage::MoveAbility.
is_ally()
bool openage::UnitAbility::is_ally (Unit & to_modify, Unit & target)
Definition at line 42 of file ability.cpp.
{
     if (to_modify.has_attribute(attr_type::owner) &&
         target.has_attribute(attr_type::owner)) {
         auto &mod_player = to_modify.get_attribute<attr_type::owner>().player;
         auto &tar_player = target.get_attribute<attr_type::owner>().player;
         return mod_player.is_ally(tar_player);
     }
     return false;
 }
References openage::Unit::get_attribute(), openage::Unit::has_attribute(), and openage::owner.
Referenced by openage::GarrisonAbility::can_invoke(), openage::RepairAbility::can_invoke(), and openage::HealAbility::can_invoke().
is_damaged()
bool openage::UnitAbility::is_damaged (Unit & target)
Definition at line 21 of file ability.cpp.
{
     return target.has_attribute(attr_type::damaged) && target.has_attribute(attr_type::hitpoints) &&
            target.get_attribute<attr_type::damaged>().hp < target.get_attribute<attr_type::hitpoints>().hp;
 }
References openage::damaged, openage::Unit::get_attribute(), openage::Unit::has_attribute(), and openage::hitpoints.
Referenced by openage::RepairAbility::can_invoke(), and openage::HealAbility::can_invoke().
is_enemy()
bool openage::UnitAbility::is_enemy (Unit & to_modify, Unit & target)
Definition at line 52 of file ability.cpp.
{
     if (to_modify.has_attribute(attr_type::owner) &&
         target.has_attribute(attr_type::owner)) {
         auto &mod_player = to_modify.get_attribute<attr_type::owner>().player;
         auto &tar_player = target.get_attribute<attr_type::owner>().player;
         return mod_player.is_enemy(tar_player);
     }
     return false;
 }
References openage::Unit::get_attribute(), openage::Unit::has_attribute(), and openage::owner.
Referenced by openage::AttackAbility::can_invoke(), and openage::ConvertAbility::can_invoke().
is_same_player()
bool openage::UnitAbility::is_same_player (Unit & to_modify, Unit & target)
Definition at line 31 of file ability.cpp.
{
     if (to_modify.has_attribute(attr_type::owner) &&
         target.has_attribute(attr_type::owner)) {
         auto &mod_player = to_modify.get_attribute<attr_type::owner>().player;
         auto &tar_player = target.get_attribute<attr_type::owner>().player;
         return mod_player.color == tar_player.color;
     }
     return false;
 }
References openage::Unit::get_attribute(), openage::Unit::has_attribute(), and openage::owner.
Referenced by openage::BuildAbility::can_invoke().
set_from_list()
ability_set openage::UnitAbility::set_from_list (const std::vector< ability_type > & items) static
set bits corresponding to abilities, useful for initialising an ability_set using a brace enclosed list
Definition at line 403 of file ability.cpp.
{
     ability_set result;
     for (auto i : items) {
         result[static_cast<int>(i)] = 1;
     }
     return result;
 }
References openage.testing.testing::result().
Referenced by openage::IdleAction::IdleAction().
type()
virtual ability_type openage::UnitAbility::type () pure virtual
Implemented in openage::ConvertAbility, openage::PatrolAbility, openage::HealAbility, openage::RepairAbility, openage::AttackAbility, openage::GatherAbility, openage::BuildAbility, openage::ResearchAbility, openage::TrainAbility, openage::UngarrisonAbility, openage::GarrisonAbility, openage::SetPointAbility, and openage::MoveAbility.
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/ability.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/ability.cpp