openage: qtsdl::GuiItemListModel< T > Class Template Reference
qtsdl::GuiItemListModel< T > Class Template Reference
A shell object fir cores inherited from GuiPropertyMap.
#include <gui_item_list_model.h>
Public Member Functions
GuiItemListModel (GuiItemBase *item_base)
Public Member Functions inherited from qtsdl::GuiItem< T >
GuiItem (GuiItemBase *item_base)
Creates an empty QObject shell for a core that is wrappable into a type *T.
Public Member Functions inherited from qtsdl::GuiItemCoreInstantiator< T >
GuiItemCoreInstantiator (GuiItemBase *item_base)
Sets up a factory for the type T.
Public Member Functions inherited from qtsdl::GuiItemMethods< T >
virtual ~GuiItemMethods ()
template<typename U >
U * get () const
Get core.
template<typename U >
U * get ()
Get core.
template<typename F , typename ... Args>
void i (F f, Args &&... args)
Invoke a function in the logic thread (the thread of the core of this object).
Private Member Functions
void on_core_adopted ()
void establish_from_gui_propagation ()
void establish_to_gui_propagation ()
void do_initial_to_gui_propagation ()
Additional Inherited Members
Protected Member Functions inherited from qtsdl::GuiItemMethods< T >
template<typename F , typename P , typename A >
void s (F f, P &p, A &&arg)
Set property.
template<typename F , typename P , typename A >
void sf (F f, P &p, A &&arg)
Set property even if it's the same.
Detailed Description
template<typename T>
class qtsdl::GuiItemListModel< T >
A shell object fir cores inherited from GuiPropertyMap.
Core can use a key-value interface while in QML it looks like a ListModel.
Definition at line 19 of file gui_item_list_model.h.
Constructor & Destructor Documentation
GuiItemListModel()
template<typename T> qtsdl::GuiItemListModel< T >::GuiItemListModel (GuiItemBase * item_base) inline explicit
Definition at line 21 of file gui_item_list_model.h.
         :
         GuiItem<T>{item_base} {
         item_base->on_core_adopted_func = std::bind(&GuiItemListModel::on_core_adopted, this);
     }
Member Function Documentation
do_initial_to_gui_propagation()
template<typename T> void qtsdl::GuiItemListModel< T >::do_initial_to_gui_propagation () inline private
Definition at line 52 of file gui_item_list_model.h.
{
         auto _this = checked_static_cast<T*>(this);
         auto properties = unwrap(_this)->impl.get();
         auto property_names = properties->dynamicPropertyNames();
         std::vector<std::tuple<QByteArray, QVariant>> values;
         values.reserve(property_names.size());
         std::transform(std::begin(property_names), std::end(property_names), std::back_inserter(values), [properties] (const QByteArray &name) {
             return std::make_tuple(name, properties->property(name));
         });
         _this->set(values);
     }
Referenced by qtsdl::GuiItemListModel< GeneratorLink >::on_core_adopted().
establish_from_gui_propagation()
template<typename T> void qtsdl::GuiItemListModel< T >::establish_from_gui_propagation () inline private
Definition at line 35 of file gui_item_list_model.h.
{
         auto _this = checked_static_cast<T*>(this);
         QObject::connect(_this, &GuiListModel::changed_from_gui, [_this] (const QByteArray &name, const QVariant &value) {
             emit _this->game_logic_caller.in_game_logic_thread_blocking([&] {
                 unwrap(_this)->impl->setProperty(name, value);
             });
         });
     }
Referenced by qtsdl::GuiItemListModel< GeneratorLink >::on_core_adopted().
establish_to_gui_propagation()
template<typename T> void qtsdl::GuiItemListModel< T >::establish_to_gui_propagation () inline private
Definition at line 45 of file gui_item_list_model.h.
{
         auto _this = checked_static_cast<T*>(this);
         auto properties = unwrap(_this)->impl.get();
         QObject::connect(properties, &GuiPropertyMapImpl::property_changed, _this, &GuiListModel::on_property_changed);
     }
Referenced by qtsdl::GuiItemListModel< GeneratorLink >::on_core_adopted().
on_core_adopted()
template<typename T> void qtsdl::GuiItemListModel< T >::on_core_adopted () inline private
Definition at line 29 of file gui_item_list_model.h.
{
         this->establish_from_gui_propagation();
         this->do_initial_to_gui_propagation();
         this->establish_to_gui_propagation();
     }
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/guisys/link/gui_item_list_model.h