openage: qtsdl::GuiPropertyMapImpl Class Reference
qtsdl::GuiPropertyMapImpl Class Reference
#include <gui_property_map_impl.h>
Signals
void property_changed (const QByteArray &name, const QVariant &value)
Public Member Functions
GuiPropertyMapImpl ()
virtual ~GuiPropertyMapImpl ()
Private Member Functions
virtual bool event (QEvent *e) override
Detailed Description
Definition at line 9 of file gui_property_map_impl.h.
Constructor & Destructor Documentation
GuiPropertyMapImpl()
qtsdl::GuiPropertyMapImpl::GuiPropertyMapImpl ()
Definition at line 12 of file gui_property_map_impl.cpp.
     :
     QObject{} {
 }
~GuiPropertyMapImpl()
qtsdl::GuiPropertyMapImpl::~GuiPropertyMapImpl () virtual
Definition at line 17 of file gui_property_map_impl.cpp.
{
 }
Member Function Documentation
event()
bool qtsdl::GuiPropertyMapImpl::event (QEvent * e) override private virtual
Definition at line 20 of file gui_property_map_impl.cpp.
{
     if (e->type() == QEvent::DynamicPropertyChange) {
         auto property_name = checked_static_cast<QDynamicPropertyChangeEvent*>(e)->propertyName();
         emit this->property_changed(property_name, this->property(property_name));
         return true;
     }
     return this->QObject::event(e);
 }
References property_changed().
property_changed
void qtsdl::GuiPropertyMapImpl::property_changed (const QByteArray & name, const QVariant & value) signal
Referenced by qtsdl::GuiItemListModel< GeneratorLink >::establish_to_gui_propagation(), and event().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/guisys/link/gui_property_map_impl.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/guisys/link/gui_property_map_impl.cpp