openage: openage::TrainAbility Class Reference
openage::TrainAbility Class Reference
buildings train new objects
#include <ability.h>
Public Member Functions
TrainAbility (const Sound *s=nullptr)
ability_type type () override
bool can_invoke (Unit &to_modify, const Command &cmd) override
true if the paramaters allow an action to be performed
void invoke (Unit &to_modify, const Command &cmd, bool play_sound=false) override
applies command to a given unit
Public Member Functions inherited from openage::UnitAbility
virtual ~UnitAbility ()
bool has_hitpoints (Unit &target)
some common functions
bool is_damaged (Unit &target)
bool has_resource (Unit &target)
bool is_same_player (Unit &to_modify, Unit &target)
bool is_ally (Unit &to_modify, Unit &target)
bool is_enemy (Unit &to_modify, Unit &target)
Private Attributes
const Sound * sound
Additional Inherited Members
Static Public Member Functions inherited from openage::UnitAbility
static ability_set set_from_list (const std::vector< ability_type > &items)
set bits corresponding to abilities, useful for initialising an ability_set using a brace enclosed list
Detailed Description
buildings train new objects
Definition at line 195 of file ability.h.
Constructor & Destructor Documentation
TrainAbility()
openage::TrainAbility::TrainAbility (const Sound * s = nullptr)
Definition at line 171 of file ability.cpp.
     :
     sound{s} {
 }
Member Function Documentation
can_invoke()
bool openage::TrainAbility::can_invoke (Unit & to_modify, const Command & cmd) override virtual
true if the paramaters allow an action to be performed
Implements openage::UnitAbility.
Definition at line 176 of file ability.cpp.
{
     if (to_modify.has_attribute(attr_type::building)) {
         auto &build_attr = to_modify.get_attribute<attr_type::building>();
         return cmd.has_type() && 1.0f <= build_attr.completed;
     }
     return false;
 }
References openage::building, openage::Unit::get_attribute(), openage::Unit::has_attribute(), and openage::Command::has_type().
invoke()
void openage::TrainAbility::invoke (Unit & to_modify, const Command & cmd, bool play_sound = false) override virtual
applies command to a given unit
Implements openage::UnitAbility.
Definition at line 184 of file ability.cpp.
{
     to_modify.log(MSG(dbg) << "invoke train action");
     if (play_sound && this->sound) {
         this->sound->play();
     }
     to_modify.push_action(std::make_unique<TrainAction>(&to_modify, cmd.type()));
 }
References openage::log::dbg(), openage::log::LogSource::log(), MSG, openage::Sound::play(), openage::Unit::push_action(), sound, and openage::Command::type().
type()
ability_type openage::TrainAbility::type () inline override virtual
Implements openage::UnitAbility.
Definition at line 199 of file ability.h.
{
         return ability_type::train;
     }
References openage::train.
Member Data Documentation
sound
const Sound* openage::TrainAbility::sound private
Definition at line 208 of file ability.h.
Referenced by invoke().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/ability.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/ability.cpp