openage: openage.convert.binpack.BestPacker Class Reference
openage.convert.binpack.BestPacker Class Reference
Chooses the best result from all the given packers.
Public Member Functions
def __init__ (self, packers)
def pack (self, blocks)
def best_packer (self)
def pos (self, block)
def width (self)
def height (self)
Public Attributes
packers
current_best
Detailed Description
Chooses the best result from all the given packers.
Definition at line 104 of file binpack.py.
Constructor & Destructor Documentation
__init__()
def openage.convert.binpack.BestPacker.__init__ (self, packers)
Definition at line 106 of file binpack.py.
         self.current_best = None
     def pack(self, blocks):
         for packer in self.packers:
Member Function Documentation
best_packer()
def openage.convert.binpack.BestPacker.best_packer (self)
Definition at line 116 of file binpack.py.
     def pos(self, block):
         return self.current_best.pos(block)
References std.min(), and openage.convert.binpack.BestPacker.packers.
Referenced by openage.convert.binpack.BestPacker.pack().
height()
def openage.convert.binpack.BestPacker.height (self)
Definition at line 125 of file binpack.py.
 class PackerNode:
     """A node in a binary packing tree."""
References openage.convert.binpack.BestPacker.current_best.
Referenced by openage.convert.texture.Texture.__init__().
pack()
def openage.convert.binpack.BestPacker.pack (self, blocks)
Definition at line 110 of file binpack.py.
             packer.pack(blocks)
         self.current_best = self.best_packer()
     def best_packer(self):
         return min(self.packers, key=lambda p: p.width() * p.height())
References openage.convert.binpack.BestPacker.best_packer(), openage.convert.binpack.BestPacker.current_best, and openage.convert.binpack.BestPacker.packers.
pos()
def openage.convert.binpack.BestPacker.pos (self, block)
Definition at line 119 of file binpack.py.
     def width(self):
         return self.current_best.width()
References openage.convert.binpack.BestPacker.current_best.
width()
def openage.convert.binpack.BestPacker.width (self)
Definition at line 122 of file binpack.py.
     def height(self):
         return self.current_best.height()
References openage.convert.binpack.BestPacker.current_best.
Referenced by openage.convert.texture.Texture.__init__().
Member Data Documentation
current_best
openage.convert.binpack.BestPacker.current_best
Definition at line 108 of file binpack.py.
Referenced by openage.convert.binpack.BestPacker.height(), openage.convert.binpack.BestPacker.pack(), openage.convert.binpack.BestPacker.pos(), and openage.convert.binpack.BestPacker.width().
packers
openage.convert.binpack.BestPacker.packers
Definition at line 107 of file binpack.py.
Referenced by openage.convert.binpack.BestPacker.best_packer(), and openage.convert.binpack.BestPacker.pack().
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/openage/convert/binpack.py