openage: openage::datastructure::PairingHeap< T, compare, heapnode_t > Class Template Reference
openage::datastructure::PairingHeap< T, compare, heapnode_t > Class Template Reference
#include <pairing_heap.h>
Public Types
using node_t = heapnode_t
using element_t = std::shared_ptr< node_t >
using this_type = PairingHeap< T, compare, node_t >
using cmp_t = compare
Public Member Functions
PairingHeap ()
~PairingHeap ()=default
element_t push (const T &item)
element_t push (T &&item)
T pop ()
element_t pop_node ()
void unlink_node (const element_t &node)
const T & top () const
const element_t & top_node () const
void decrease (const element_t &node)
void update (const element_t &node)
void clear ()
size_t size () const
bool empty () const
void iter_all (const std::function< void(const element_t &)> &func) const
Protected Member Functions
void walk_tree (const element_t &root, const std::function< void(const element_t &)> &func) const
void push_node (const element_t &node)
void root_insert (const element_t &node)
Protected Attributes
compare cmp
size_t node_count
element_t root_node
Detailed Description
template<typename T, typename compare = std::less<T>, typename heapnode_t = PairingHeapNode<T, compare>>
class openage::datastructure::PairingHeap< T, compare, heapnode_t >
(Quite) efficient heap implementation.
Definition at line 37 of file pairing_heap.h.
Member Typedef Documentation
cmp_t
template<typename T, typename compare = std::less<T>, typename heapnode_t = PairingHeapNode<T, compare>> using openage::datastructure::PairingHeap< T, compare, heapnode_t >::cmp_t = compare
Definition at line 200 of file pairing_heap.h.
element_t
template<typename T, typename compare = std::less<T>, typename heapnode_t = PairingHeapNode<T, compare>> using openage::datastructure::PairingHeap< T, compare, heapnode_t >::element_t = std::shared_ptr<node_t>
Definition at line 198 of file pairing_heap.h.
node_t
template<typename T, typename compare = std::less<T>, typename heapnode_t = PairingHeapNode<T, compare>> using openage::datastructure::PairingHeap< T, compare, heapnode_t >::node_t = heapnode_t
Definition at line 197 of file pairing_heap.h.
this_type
template<typename T, typename compare = std::less<T>, typename heapnode_t = PairingHeapNode<T, compare>> using openage::datastructure::PairingHeap< T, compare, heapnode_t >::this_type = PairingHeap<T, compare, node_t>
Definition at line 199 of file pairing_heap.h.
Constructor & Destructor Documentation
PairingHeap()
template<typename T, typename compare = std::less<T>, typename heapnode_t = PairingHeapNode<T, compare>> openage::datastructure::PairingHeap< T, compare, heapnode_t >::PairingHeap () inline
create a empty heap.
Definition at line 205 of file pairing_heap.h.
         :
         node_count(0),
         root_node(nullptr) {
     }
~PairingHeap()
template<typename T, typename compare = std::less<T>, typename heapnode_t = PairingHeapNode<T, compare>> openage::datastructure::PairingHeap< T, compare, heapnode_t >::~PairingHeap () default
Member Function Documentation
clear()
template<typename T, typename compare = std::less<T>, typename heapnode_t = PairingHeapNode<T, compare>> void openage::datastructure::PairingHeap< T, compare, heapnode_t >::clear () inline
erase all elements on the heap.
Definition at line 411 of file pairing_heap.h.
                  {
         this->root_node = nullptr;
         this->node_count = 0;
 #if OPENAGE_PAIRINGHEAP_DEBUG
         this->nodes.clear();
 #endif
     }
Referenced by openage::event::EventStore::clear().
decrease()
template<typename T, typename compare = std::less<T>, typename heapnode_t = PairingHeapNode<T, compare>> void openage::datastructure::PairingHeap< T, compare, heapnode_t >::decrease (const element_t & node) inline
You must call this after the node data decreased. This cuts the subtree and links the subtree again. If the node value increased and you call this, the heap is corrupted. Also known as the decrease_key operation.
O(1)
Definition at line 380 of file pairing_heap.h.
{
         if (likely(node != this->root_node)) {
             // cut out the node and its subtree
             node->loosen();
             this->root_node = node->link_with(this->root_node);
         }
         // decreasing the root node won't change it, so we do nothing.
     }
Referenced by openage::path::a_star().
empty()
template<typename T, typename compare = std::less<T>, typename heapnode_t = PairingHeapNode<T, compare>> bool openage::datastructure::PairingHeap< T, compare, heapnode_t >::empty () const inline
Returns
whether there are no nodes stored on the heap.
Definition at line 429 of file pairing_heap.h.
{
         return this->node_count == 0;
     }
Referenced by openage::path::a_star().
iter_all()
template<typename T, typename compare = std::less<T>, typename heapnode_t = PairingHeapNode<T, compare>> void openage::datastructure::PairingHeap< T, compare, heapnode_t >::iter_all (const std::function< void(const element_t &)> & func) const inline
Definition at line 585 of file pairing_heap.h.
{
         this->walk_tree(this->root_node, func);
     }
pop()
template<typename T, typename compare = std::less<T>, typename heapnode_t = PairingHeapNode<T, compare>> T openage::datastructure::PairingHeap< T, compare, heapnode_t >::pop () inline
returns and removes the smallest item on the heap.
Definition at line 236 of file pairing_heap.h.
             {
         return std::move(this->pop_node()->data);
     }
Referenced by openage::path::a_star(), and openage::event::EventStore::pop().
pop_node()
template<typename T, typename compare = std::less<T>, typename heapnode_t = PairingHeapNode<T, compare>> element_t openage::datastructure::PairingHeap< T, compare, heapnode_t >::pop_node () inline
returns the smallest item on the heap and deletes it. also known as delete_min.
Ω(log log n), O(2^(2*√log log n'))
Definition at line 246 of file pairing_heap.h.
{
         if (this->root_node == nullptr) {
             throw Error{MSG(err) << "Can't pop an empty heap!"};
         }
         // 0. remove tree root, it's the minimum.
         element_t ret = this->root_node;
         element_t current_sibling = this->root_node->first_child;
         this->root_node = nullptr;
         // 1. link root children pairwise, last node may be alone
         element_t first_pair = nullptr;
         element_t previous_pair = nullptr;
         while (unlikely(current_sibling != nullptr)) {
             element_t link0 = current_sibling;
             element_t link1 = current_sibling->next_sibling;
             // pair link0 and link1
             if (link1 != nullptr) {
                 // get the first sibling for next pair, just in advance.
                 current_sibling = link1->next_sibling;
                 // do the link: merges two nodes, smaller one = root.
                 element_t link_root = link0->link_with(link1);
                 link_root->parent = nullptr;
                 if (previous_pair == nullptr) {
                     // this was the first pair
                     first_pair = link_root;
                     first_pair->prev_sibling = nullptr;
                 }
                 else {
                     // store node as next sibling in previous pair
                     previous_pair->next_sibling = link_root;
                     link_root->prev_sibling = previous_pair;
                 }
                 previous_pair = link_root;
                 link_root->next_sibling = nullptr;
             }
             else {
                 // link0 is the last and unpaired root child.
                 link0->parent = nullptr;
                 if (previous_pair == nullptr) {
                     // link0 was the only node
                     first_pair = link0;
                     link0->prev_sibling = nullptr;
                 } else {
                     previous_pair->next_sibling = link0;
                     link0->prev_sibling = previous_pair;
                 }
                 link0->next_sibling = nullptr;
                 current_sibling = nullptr;
             }
         }
         // 2. then link remaining trees to the last one, from right to left
         if (first_pair != nullptr) {
             this->root_node = first_pair->link_backwards();
         }
         this->node_count -= 1;
 #if OPENAGE_PAIRINGHEAP_DEBUG
         if (1 != this->nodes.erase(ret)) {
             throw Error{ERR << "didn't remove node"};
         }
 #endif
         // (to find those two lines, 14h of debugging passed)
         ret->loosen();
         ret->first_child = nullptr;
         // and it's done!
         return ret;
     }
Referenced by openage::datastructure::PairingHeap< std::shared_ptr< Event >, util::SharedPtrLess< Event > >::pop(), openage::datastructure::PairingHeap< std::shared_ptr< Event >, util::SharedPtrLess< Event > >::unlink_node(), and openage::datastructure::PairingHeap< std::shared_ptr< Event >, util::SharedPtrLess< Event > >::update().
push() [1/2]
template<typename T, typename compare = std::less<T>, typename heapnode_t = PairingHeapNode<T, compare>> element_t openage::datastructure::PairingHeap< T, compare, heapnode_t >::push (const T & item) inline
adds the given item to the heap. O(1)
Definition at line 217 of file pairing_heap.h.
{
         element_t new_node = std::make_shared<node_t>(item);
         this->push_node(new_node);
         return new_node;
     }
Referenced by openage::path::a_star(), openage::datastructure::tests::pairing_heap_1(), openage::datastructure::tests::pairing_heap_2(), openage::datastructure::tests::pairing_heap_3(), and openage::event::EventStore::push().
push() [2/2]
template<typename T, typename compare = std::less<T>, typename heapnode_t = PairingHeapNode<T, compare>> element_t openage::datastructure::PairingHeap< T, compare, heapnode_t >::push (T && item) inline
moves the given item to the heap. O(1)
Definition at line 227 of file pairing_heap.h.
{
         element_t new_node = std::make_shared<node_t>(std::move(item));
         this->push_node(new_node);
         return new_node;
     }
push_node()
template<typename T, typename compare = std::less<T>, typename heapnode_t = PairingHeapNode<T, compare>> void openage::datastructure::PairingHeap< T, compare, heapnode_t >::push_node (const element_t & node) inline protected
adds the given node to the heap. use this if the node was not in the heap before. O(1)
Definition at line 613 of file pairing_heap.h.
{
         this->root_insert(node);
 #if OPENAGE_PAIRINGHEAP_DEBUG
         auto ins = this->nodes.insert(node);
         if (not ins.second) {
             throw Error{ERR << "node already known"};
         }
 #endif
         this->node_count += 1;
     }
Referenced by openage::datastructure::PairingHeap< std::shared_ptr< Event >, util::SharedPtrLess< Event > >::push(), and openage::datastructure::PairingHeap< std::shared_ptr< Event >, util::SharedPtrLess< Event > >::update().
root_insert()
template<typename T, typename compare = std::less<T>, typename heapnode_t = PairingHeapNode<T, compare>> void openage::datastructure::PairingHeap< T, compare, heapnode_t >::root_insert (const element_t & node) inline protected
insert a node into the heap.
Definition at line 629 of file pairing_heap.h.
{
         if (unlikely(this->root_node == nullptr)) {
             this->root_node = node;
         } else {
             this->root_node = this->root_node->link_with(node);
         }
     }
Referenced by openage::datastructure::PairingHeap< std::shared_ptr< Event >, util::SharedPtrLess< Event > >::push_node(), and openage::datastructure::PairingHeap< std::shared_ptr< Event >, util::SharedPtrLess< Event > >::unlink_node().
size()
template<typename T, typename compare = std::less<T>, typename heapnode_t = PairingHeapNode<T, compare>> size_t openage::datastructure::PairingHeap< T, compare, heapnode_t >::size () const inline
Returns
the number of nodes stored on the heap.
Definition at line 422 of file pairing_heap.h.
{
         return this->node_count;
     }
Referenced by openage::event::EventStore::pop(), and openage::event::EventStore::push().
top()
template<typename T, typename compare = std::less<T>, typename heapnode_t = PairingHeapNode<T, compare>> const T& openage::datastructure::PairingHeap< T, compare, heapnode_t >::top () const inline
Returns the smallest item on the heap. O(1)
Definition at line 358 of file pairing_heap.h.
{
         return this->root_node->get_data();
     }
Referenced by openage::event::EventStore::top().
top_node()
template<typename T, typename compare = std::less<T>, typename heapnode_t = PairingHeapNode<T, compare>> const element_t& openage::datastructure::PairingHeap< T, compare, heapnode_t >::top_node () const inline
Returns the smallest node on the heap.
O(1)
Definition at line 367 of file pairing_heap.h.
{
         return this->root_node;
     }
unlink_node()
template<typename T, typename compare = std::less<T>, typename heapnode_t = PairingHeapNode<T, compare>> void openage::datastructure::PairingHeap< T, compare, heapnode_t >::unlink_node (const element_t & node) inline
Unlink a node from the heap.
If the item is the current root, just pop(). else, cut the node from its parent, pop() that subtree and merge these trees.
O(pop_node)
Definition at line 334 of file pairing_heap.h.
{
         if (node == this->root_node) {
             this->pop_node();
         }
         else {
             node->loosen();
             element_t real_root = this->root_node;
             this->root_node = node;
             this->pop_node();
             element_t new_root = this->root_node;
             this->root_node = real_root;
             if (new_root != nullptr) {
                 this->root_insert(new_root);
             }
         }
     }
Referenced by openage::event::EventStore::erase(), and openage::datastructure::PairingHeap< std::shared_ptr< Event >, util::SharedPtrLess< Event > >::update().
update()
template<typename T, typename compare = std::less<T>, typename heapnode_t = PairingHeapNode<T, compare>> void openage::datastructure::PairingHeap< T, compare, heapnode_t >::update (const element_t & node) inline
After a change, call this to reorganize the given node. Support increase and decrease of values.
Use decrease instead when you know the value decreased.
O(1) (but slower than decrease), and O(pop) when node is the root.
Definition at line 397 of file pairing_heap.h.
{
         if (likely(node != this->root_node)) {
             this->unlink_node(node);
             this->push_node(node);
         }
         else {
             // it's the root node, so we just pop and push it.
             this->push_node(this->pop_node());
         }
     }
Referenced by openage::event::EventStore::update().
walk_tree()
template<typename T, typename compare = std::less<T>, typename heapnode_t = PairingHeapNode<T, compare>> void openage::datastructure::PairingHeap< T, compare, heapnode_t >::walk_tree (const element_t & root, const std::function< void(const element_t &)> & func) const inline protected
Definition at line 590 of file pairing_heap.h.
{
         func(root);
         if (root) {
             auto node = root->first_child;
             while (true) {
                 if (not node) {
                     break;
                 }
                 this->walk_tree(node, func);
                 node = node->next_sibling;
             }
         }
     }
Referenced by openage::datastructure::PairingHeap< std::shared_ptr< Event >, util::SharedPtrLess< Event > >::iter_all(), and openage::datastructure::PairingHeap< std::shared_ptr< Event >, util::SharedPtrLess< Event > >::walk_tree().
Member Data Documentation
cmp
template<typename T, typename compare = std::less<T>, typename heapnode_t = PairingHeapNode<T, compare>> compare openage::datastructure::PairingHeap< T, compare, heapnode_t >::cmp protected
Definition at line 638 of file pairing_heap.h.
node_count
template<typename T, typename compare = std::less<T>, typename heapnode_t = PairingHeapNode<T, compare>> size_t openage::datastructure::PairingHeap< T, compare, heapnode_t >::node_count protected
Definition at line 639 of file pairing_heap.h.
Referenced by openage::datastructure::PairingHeap< std::shared_ptr< Event >, util::SharedPtrLess< Event > >::clear(), openage::datastructure::PairingHeap< std::shared_ptr< Event >, util::SharedPtrLess< Event > >::empty(), openage::datastructure::PairingHeap< std::shared_ptr< Event >, util::SharedPtrLess< Event > >::pop_node(), openage::datastructure::PairingHeap< std::shared_ptr< Event >, util::SharedPtrLess< Event > >::push_node(), and openage::datastructure::PairingHeap< std::shared_ptr< Event >, util::SharedPtrLess< Event > >::size().
root_node
template<typename T, typename compare = std::less<T>, typename heapnode_t = PairingHeapNode<T, compare>> element_t openage::datastructure::PairingHeap< T, compare, heapnode_t >::root_node protected
Definition at line 640 of file pairing_heap.h.
Referenced by openage::datastructure::PairingHeap< std::shared_ptr< Event >, util::SharedPtrLess< Event > >::clear(), openage::datastructure::PairingHeap< std::shared_ptr< Event >, util::SharedPtrLess< Event > >::decrease(), openage::datastructure::PairingHeap< std::shared_ptr< Event >, util::SharedPtrLess< Event > >::iter_all(), openage::datastructure::PairingHeap< std::shared_ptr< Event >, util::SharedPtrLess< Event > >::pop_node(), openage::datastructure::PairingHeap< std::shared_ptr< Event >, util::SharedPtrLess< Event > >::root_insert(), openage::datastructure::PairingHeap< std::shared_ptr< Event >, util::SharedPtrLess< Event > >::top(), openage::datastructure::PairingHeap< std::shared_ptr< Event >, util::SharedPtrLess< Event > >::top_node(), openage::datastructure::PairingHeap< std::shared_ptr< Event >, util::SharedPtrLess< Event > >::unlink_node(), and openage::datastructure::PairingHeap< std::shared_ptr< Event >, util::SharedPtrLess< Event > >::update().
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/datastructure/pairing_heap.h