openage: openage.util.fslike.abstract.ReadOnlyFSLikeObject Class Reference
openage.util.fslike.abstract.ReadOnlyFSLikeObject Class Reference
Public Member Functions
def read_only_error (self, parts)
Helper method to be called from all other methods.
def open_w (self, parts)
Shall return a BufferedWriter for the given file ("mode 'wb'").
def mkdirs (self, parts)
Shall ensure that the directory exists.
def rmdir (self, parts)
Shall remove an empty directory.
def unlink (self, parts)
Shall remove a single file.
def touch (self, parts)
Shall create the file or update its timestamp.
def rename (self, srcparts, tgtparts)
Shall rename a file or directory to the target name.
def writable (self, parts)
Public Member Functions inherited from openage.util.fslike.abstract.FSLikeObject
def root (self)
Returns a path-like object for the root of this file system.
def pretty (self, parts)
pretty-format a path in this filesystem like object.
def open_r (self, parts)
Shall return a BufferedReader for the given file ("mode 'rb'").
def open_rw (self, parts)
Shall return a BufferedWriter for the given file ("mode 'r+'").
def open_a (self, parts)
Shall return a BufferedWriter for the given file ("mode 'a'").
def open_ar (self, parts)
Shall return a BufferedWriter for the given file ("mode 'a+'").
def exists (self, parts)
Test if the parts are a file or a directory.
def resolve_r (self, parts)
def resolve_w (self, parts)
Returns a new flattened path.
def get_native_path (self, parts)
def list (self, parts)
Shall yield the entry names of the given directory.
def filesize (self, parts)
def mtime (self, parts)
def is_file (self, parts)
def is_dir (self, parts)
def watch (self, parts, callback)
def poll_watches (self)
Detailed Description
Definition at line 188 of file abstract.py.
Member Function Documentation
mkdirs()
def openage.util.fslike.abstract.ReadOnlyFSLikeObject.mkdirs (self, parts)
Shall ensure that the directory exists.
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 200 of file abstract.py.
     def rmdir(self, parts):
         self.read_only_error(parts)
References openage.util.fslike.abstract.ReadOnlyFSLikeObject.read_only_error().
open_w()
def openage.util.fslike.abstract.ReadOnlyFSLikeObject.open_w (self, parts)
Shall return a BufferedWriter for the given file ("mode 'wb'").
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 197 of file abstract.py.
     def mkdirs(self, parts):
         self.read_only_error(parts)
References openage.util.fslike.abstract.ReadOnlyFSLikeObject.read_only_error().
read_only_error()
def openage.util.fslike.abstract.ReadOnlyFSLikeObject.read_only_error (self, parts)
Helper method to be called from all other methods.
Definition at line 193 of file abstract.py.
         raise UnsupportedOperation("read-only: " + str(self))
     def open_w(self, parts):
         self.read_only_error(parts)
References openage::py.str().
Referenced by openage.util.fslike.abstract.ReadOnlyFSLikeObject.mkdirs(), openage.util.fslike.abstract.ReadOnlyFSLikeObject.open_w(), openage.util.fslike.abstract.ReadOnlyFSLikeObject.rename(), openage.util.fslike.abstract.ReadOnlyFSLikeObject.rmdir(), openage.util.fslike.abstract.ReadOnlyFSLikeObject.touch(), and openage.util.fslike.abstract.ReadOnlyFSLikeObject.unlink().
rename()
def openage.util.fslike.abstract.ReadOnlyFSLikeObject.rename (self, srcparts, tgtparts)
Shall rename a file or directory to the target name.
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 212 of file abstract.py.
         self.read_only_error(srcparts)
     def writable(self, parts):
         del parts  # unused
References openage.util.fslike.abstract.ReadOnlyFSLikeObject.read_only_error().
rmdir()
def openage.util.fslike.abstract.ReadOnlyFSLikeObject.rmdir (self, parts)
Shall remove an empty directory.
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 203 of file abstract.py.
     def unlink(self, parts):
         self.read_only_error(parts)
References openage.util.fslike.abstract.ReadOnlyFSLikeObject.read_only_error().
Referenced by openage.util.fslike.path.Path.removerecursive().
touch()
def openage.util.fslike.abstract.ReadOnlyFSLikeObject.touch (self, parts)
Shall create the file or update its timestamp.
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 209 of file abstract.py.
     def rename(self, srcparts, tgtparts):
         del tgtparts  # unused
References openage.util.fslike.abstract.ReadOnlyFSLikeObject.read_only_error().
unlink()
def openage.util.fslike.abstract.ReadOnlyFSLikeObject.unlink (self, parts)
Shall remove a single file.
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 206 of file abstract.py.
     def touch(self, parts):
         self.read_only_error(parts)
References openage.util.fslike.abstract.ReadOnlyFSLikeObject.read_only_error().
Referenced by openage.util.fslike.path.Path.removerecursive().
writable()
def openage.util.fslike.abstract.ReadOnlyFSLikeObject.writable (self, parts)
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 216 of file abstract.py.
         return False
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/openage/util/fslike/abstract.py