openage: openage::renderer::opengl::GlRenderer Class Reference
openage::renderer::opengl::GlRenderer Class Reference final
The OpenGL specialization of the rendering interface.
#include <renderer.h>
Public Member Functions
GlRenderer (GlContext *)
std::unique_ptr< Texture2d > add_texture (resources::Texture2dData const &) override
std::unique_ptr< Texture2d > add_texture (resources::Texture2dInfo const &) override
Creates a new empty texture with the given parameters on the graphics hardware.
std::unique_ptr< ShaderProgram > add_shader (std::vector< resources::ShaderSource > const &) override
std::unique_ptr< Geometry > add_mesh_geometry (resources::MeshData const &) override
std::unique_ptr< Geometry > add_bufferless_quad () override
std::unique_ptr< RenderTarget > create_texture_target (std::vector< Texture2d * >) override
RenderTarget const * get_display_target () override
resources::Texture2dData display_into_data () override
Stores the display framebuffer into a CPU-accessible data object. Essentially, this takes a screenshot.
void render (RenderPass const &) override
Executes a render pass.
Public Member Functions inherited from openage::renderer::Renderer
virtual ~Renderer ()=default
Private Attributes
GlContext * gl_context
The GL context.
GlRenderTarget display
Detailed Description
The OpenGL specialization of the rendering interface.
Definition at line 20 of file renderer.h.
Constructor & Destructor Documentation
GlRenderer()
openage::renderer::opengl::GlRenderer::GlRenderer (GlContext * ctx)
Definition at line 17 of file renderer.cpp.
     : gl_context(ctx)
 {
     log::log(MSG(info) << "Created OpenGL renderer");
 }
References openage::log::info(), openage::log::log(), and MSG.
Member Function Documentation
add_bufferless_quad()
std::unique_ptr< Geometry > openage::renderer::opengl::GlRenderer::add_bufferless_quad () override virtual
Adds a Geometry object that passes a simple 4-vertex drawing command with no vertex attributes to the shader. Useful for generating positions in the vertex shader.
Implements openage::renderer::Renderer.
Definition at line 39 of file renderer.cpp.
{
     return std::make_unique<GlGeometry>();
 }
add_mesh_geometry()
std::unique_ptr< Geometry > openage::renderer::opengl::GlRenderer::add_mesh_geometry (resources::MeshData const &) override virtual
Creates a Geometry object from the given mesh data, uploading it to the GPU by creating appropriate buffer. The vertex attributes will be passed to the shader as described in the mesh data.
Implements openage::renderer::Renderer.
Definition at line 35 of file renderer.cpp.
{
     return std::make_unique<GlGeometry>(mesh);
 }
References openage::renderer::mesh.
add_shader()
std::unique_ptr< ShaderProgram > openage::renderer::opengl::GlRenderer::add_shader (std::vector< resources::ShaderSource > const &) override virtual
Compiles the given shader source code into a shader program. A shader program is the main tool used for graphics rendering.
Implements openage::renderer::Renderer.
Definition at line 31 of file renderer.cpp.
{
     return std::make_unique<GlShaderProgram>(srcs, this->gl_context->get_capabilities());
 }
References openage::renderer::opengl::GlContext::get_capabilities(), and gl_context.
add_texture() [1/2]
std::unique_ptr< Texture2d > openage::renderer::opengl::GlRenderer::add_texture (resources::Texture2dData const &) override virtual
Uploads the given texture data (usually loaded from disk) to graphics hardware and makes it available as a Texture object that can be used for various operations.
Implements openage::renderer::Renderer.
Definition at line 23 of file renderer.cpp.
{
     return std::make_unique<GlTexture2d>(data);
 }
add_texture() [2/2]
std::unique_ptr< Texture2d > openage::renderer::opengl::GlRenderer::add_texture (resources::Texture2dInfo const &) override virtual
Creates a new empty texture with the given parameters on the graphics hardware.
Implements openage::renderer::Renderer.
Definition at line 27 of file renderer.cpp.
{
     return std::make_unique<GlTexture2d>(info);
 }
References openage::log::info().
create_texture_target()
std::unique_ptr< RenderTarget > openage::renderer::opengl::GlRenderer::create_texture_target (std::vector< Texture2d * >) override virtual
Constructs a render target from the given textures. All subsequent drawing operations pointed at this target will write to these textures. Textures are attached to the target in the order in which they appear within the vector. Depth textures are attached as depth components. Textures of every other type are attached as color components.
Implements openage::renderer::Renderer.
Definition at line 43 of file renderer.cpp.
{
     std::vector<const GlTexture2d*> gl_textures;
     gl_textures.reserve(textures.size());
     for (auto tex : textures) {
         gl_textures.push_back(static_cast<const GlTexture2d*>(tex));
     }
     return std::make_unique<GlRenderTarget>(gl_textures);
 }
References openage::renderer::opengl::textures.
display_into_data()
resources::Texture2dData openage::renderer::opengl::GlRenderer::display_into_data () override virtual
Stores the display framebuffer into a CPU-accessible data object. Essentially, this takes a screenshot.
Implements openage::renderer::Renderer.
Definition at line 57 of file renderer.cpp.
{
     GLint params[4];
     glGetIntegerv(GL_VIEWPORT, params);
     GLint width = params[2];
     GLint height = params[3];
     resources::Texture2dInfo tex_info(width, height, resources::pixel_format::rgba8, 4);
     std::vector<uint8_t> data(tex_info.get_data_size());
     static_cast<GlRenderTarget const*>(this->get_display_target())->bind_read();
     glPixelStorei(GL_PACK_ALIGNMENT, 4);
     glReadnPixels(0, 0, width, height, GL_RGBA, GL_UNSIGNED_BYTE, tex_info.get_data_size(), data.data());
     resources::Texture2dData img(std::move(tex_info), std::move(data));
     return img.flip_y();
 }
References openage::renderer::resources::Texture2dInfo::get_data_size(), get_display_target(), openage::move, and openage::renderer::resources::rgba8.
get_display_target()
RenderTarget const * openage::renderer::opengl::GlRenderer::get_display_target () override virtual
Returns the built-in display target that represents the window. Passes pointed at this target will have their output visible on the screen.
Implements openage::renderer::Renderer.
Definition at line 53 of file renderer.cpp.
{
     return &this->display;
 }
References display.
Referenced by display_into_data().
render()
void openage::renderer::opengl::GlRenderer::render (RenderPass const &) override virtual
Executes a render pass.
Implements openage::renderer::Renderer.
Definition at line 75 of file renderer.cpp.
{
     auto gl_target = dynamic_cast<const GlRenderTarget*>(pass.target);
     gl_target->bind_write();
     glClearColor(0.0f, 0.0f, 0.0f, 0.0f);
     glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
     for (auto obj : pass.renderables) {
         if (obj.alpha_blending) {
             glEnable(GL_BLEND);
         }
         else {
             glDisable(GL_BLEND);
         }
         if (obj.depth_test) {
             glEnable(GL_DEPTH_TEST);
         }
         else {
             glDisable(GL_DEPTH_TEST);
         }
         auto in = dynamic_cast<GlUniformInput const*>(obj.unif_in);
         auto geom = dynamic_cast<GlGeometry const*>(obj.geometry);
         in->program->execute_with(in, geom);
     }
 }
References openage::renderer::RenderPass::renderables, and openage::renderer::RenderPass::target.
Member Data Documentation
display
GlRenderTarget openage::renderer::opengl::GlRenderer::display private
Definition at line 43 of file renderer.h.
Referenced by get_display_target().
gl_context
GlContext* openage::renderer::opengl::GlRenderer::gl_context private
The GL context.
Definition at line 41 of file renderer.h.
Referenced by add_shader().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/opengl/renderer.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/opengl/renderer.cpp