openage: openage::event::demo::BallReflectPanel Class Reference
openage::event::demo::BallReflectPanel Class Reference
Public Member Functions
BallReflectPanel ()
void setup_event (const std::shared_ptr< Event > &target, const std::shared_ptr< State > &gstate) override
void invoke (Loop &mgr, const std::shared_ptr< EventTarget > &, const std::shared_ptr< State > &gstate, const curve::time_t &now, const EventClass::param_map &) override
curve::time_t predict_invoke_time (const std::shared_ptr< EventTarget > &target, const std::shared_ptr< State > &gstate, const curve::time_t &now) override
Public Member Functions inherited from openage::event::DependencyEventClass
DependencyEventClass (const std::string &name)
Public Member Functions inherited from openage::event::EventClass
EventClass (const std::string &name, const trigger_type &type)
virtual ~EventClass ()=default
const std::string & id ()
Additional Inherited Members
Public Types inherited from openage::event::EventClass
enum trigger_type {
trigger_type::DEPENDENCY, trigger_type::DEPENDENCY_IMMEDIATELY, trigger_type::TRIGGER, trigger_type::REPEAT,
trigger_type::ONCE
}
Public Attributes inherited from openage::event::EventClass
const trigger_type type
Detailed Description
Definition at line 117 of file physics.cpp.
Constructor & Destructor Documentation
BallReflectPanel()
openage::event::demo::BallReflectPanel::BallReflectPanel () inline
Definition at line 119 of file physics.cpp.
         :
         DependencyEventClass("demo.ball.reflect_panel") {}
Member Function Documentation
invoke()
void openage::event::demo::BallReflectPanel::invoke (Loop & loop, const std::shared_ptr< EventTarget > & target, const std::shared_ptr< State > & state, const curve::time_t & time, const EventClass::param_map & params) inline override virtual
This method implements the effects of the event. It will be called at the time that was determined by predict_invoke_time.
Called from the Loop.
Implements openage::event::EventClass.
Definition at line 138 of file physics.cpp.
{
         auto state = std::dynamic_pointer_cast<PongState>(gstate);
         auto pos = state->ball->position->get(now);
         auto speed = state->ball->speed->get(now);
 #if WITH_NCURSES
         if (state->enable_gui) {
             static int cnt = 0;
             util::FString str;
             str.fmt("Panel hit [%i]", ++cnt);
             state->gui->log(str);
         }
         else {
 #endif
             log::log(INFO << "Panel hit at " << now);
 #if WITH_NCURSES
         }
 #endif
         if (pos[0] <= 1 and
             speed[0] < 0 and
             (pos[1] < state->p1->position->get(now) - state->p1->size->get(now) / 2 or
              pos[1] > state->p1->position->get(now) + state->p1->size->get(now) / 2)) {
             // ball missed the paddle of player 1
             auto l = state->p1->lives->get(now);
             l--;
             state->p1->lives->set_last(now, l);
             state->ball->position->set_last(now, pos);
             Physics::reset(state, mgr, now);
         }
         else if (pos[0] >= state->display_boundary[0] - 1 and
                  speed[0] > 0 and
                  (pos[1] < state->p2->position->get(now) - state->p2->size->get(now) / 2 or
                   pos[1] > state->p2->position->get(now) + state->p2->size->get(now) / 2)) {
             // ball missed the paddel of player 2
             auto l = state->p2->lives->get(now);
             l--;
             state->p2->lives->set_last(now, l);
             state->ball->position->set_last(now, pos);
             Physics::reset(state, mgr, now);
         }
         else if (pos[0] >= state->display_boundary[0]- 1 || pos[0] <= 1) {
             speed[0] *= -1;
             state->ball->speed->set_last(now, speed);
             state->ball->position->set_last(now, pos);
         }
         curve::time_t ty = 0;
         if (speed[0] > 0) {
             ty = curve::time_t::from_double((state->display_boundary[0] - pos[0]) / speed[0]);
         }
         else if (speed[0] < 0) {
             ty = curve::time_t::from_double(pos[0] / -speed[0]);
         }
         auto hit_pos = pos + speed * ty.to_double();
         if (speed[0] > 0) {
             hit_pos[0] = state->display_boundary[0];
         }
         else {
             hit_pos[0] = 0;
         }
         state->ball->position->set_last(now + ty, hit_pos);
     }
References openage::util::FixedPoint< int64_t, 16 >::from_double(), INFO, openage::log::log(), openage::event::demo::Physics::reset(), openage::speed, openage::py::str(), and openage::util::FixedPoint< int_type, fractional_bits >::to_double().
predict_invoke_time()
curve::time_t openage::event::demo::BallReflectPanel::predict_invoke_time (const std::shared_ptr< EventTarget > & target, const std::shared_ptr< State > & state, const curve::time_t & at) inline override virtual
Is called to calculate the execution time for an event of this eventclass. This is called whenever one of the set up dependencies was changed, or when a REPEAT event was executed.
Parameters
target the target the event was created for
state the state this shall work on
at the time when the change happened, from there on it shall be calculated onwards
If the event is obsolete, return <time_t>min().
If the time is lower than the previous time, then dependencies may not be resolved perfectly anymore (if other events have already been calculated before that).
Implements openage::event::EventClass.
Definition at line 215 of file physics.cpp.
{
         auto positioncurve = std::dynamic_pointer_cast<curve::Continuous<util::Vector2d>>(target);
         auto state = std::dynamic_pointer_cast<PongState>(gstate);
         auto speed = state->ball->speed->get(now);
         auto pos = positioncurve->get(now);
         if (speed[0] == 0)
             return std::numeric_limits<curve::time_t>::max();
         curve::time_t ty = 0;
         if (speed[0] > 0) {
             ty = curve::time_t::from_double((state->display_boundary[0] - pos[0]) / speed[0]);
         }
         else if (speed[0] < 0) {
             ty = curve::time_t::from_double(pos[0] / -speed[0]);
         }
 #if WITH_NCURSES
         if (state->enable_gui) {
             util::FString str;
             str.fmt("PANEL REFLECT AT %f NEXT %f", now.to_double(), (now + ty).to_double());
             state->gui->log(str);
         }
         else {
 #endif
             log::log(INFO << "predicting panel reflection at t=" << now
                      << ", next reflection at t=" << (now + ty));
 #if WITH_NCURSES
         }
 #endif
         auto hit_pos = pos + speed * ty.to_double();
         if (speed[0] > 0) {
             hit_pos[0] = state->display_boundary[0];
         }
         else {
             hit_pos[0] = 0;
         }
         ENSURE(hit_pos[0] >= 0, "hit position x must be positive");
         return now + ty;
     }
References ENSURE, openage::util::FixedPoint< int64_t, 16 >::from_double(), INFO, openage::log::log(), openage::console::tests::max(), openage::speed, openage::py::str(), and openage::util::FixedPoint< int_type, fractional_bits >::to_double().
setup_event()
void openage::event::demo::BallReflectPanel::setup_event (const std::shared_ptr< Event > & event, const std::shared_ptr< State > & state) inline override virtual
Called for each event that is created for this EventClass. The job of the setup function is to add all dependencies with other event targets found in state.
Implements openage::event::EventClass.
Definition at line 123 of file physics.cpp.
{
         auto state = std::dynamic_pointer_cast<PongState>(gstate);
         // FIXME dependency to a full ball object
         // then a change to any of the curves triggers the update.
         target->depend_on(state->ball->position);
         target->depend_on(state->ball->speed);
         target->depend_on(state->p1->position);
         target->depend_on(state->p2->position);
         // \todo add dependency to size of game area
     }
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/event/demo/physics.cpp