openage: openage::renderer::opengl::GlBuffer Class Reference
openage::renderer::opengl::GlBuffer Class Reference final
#include <buffer.h>
Public Member Functions
GlBuffer (size_t size, GLenum usage=GL_STATIC_DRAW)
GlBuffer (const uint8_t *data, size_t size, GLenum usage=GL_STATIC_DRAW)
size_t get_size () const
The size in bytes of this buffer.
void upload_data (const uint8_t *data, size_t offset, size_t size)
void bind (GLenum target) const
Bind this buffer to the specified GL target.
Public Member Functions inherited from openage::renderer::opengl::GlSimpleObject
GlSimpleObject (GlSimpleObject &&)
GlSimpleObject & operator= (GlSimpleObject &&)
GlSimpleObject (GlSimpleObject const &)=delete
GlSimpleObject & operator= (GlSimpleObject const &)=delete
virtual ~GlSimpleObject ()
GLuint get_handle () const
Returns the handle to the underlying OpenGL Object.
Private Attributes
size_t size
The size in bytes of this buffer.
Additional Inherited Members
Protected Member Functions inherited from openage::renderer::opengl::GlSimpleObject
GlSimpleObject (std::function< void(GLuint)> delete_fun)
Protected Attributes inherited from openage::renderer::opengl::GlSimpleObject
std::optional< GLuint > handle
The handle to the OpenGL Object that this class represents.
std::function< void(GLuint)> delete_fun
The function that deletes the underlying OpenGL Object.
Detailed Description
Represents an OpenGL buffer of memory allocated on the GPU.
Definition at line 14 of file buffer.h.
Constructor & Destructor Documentation
GlBuffer() [1/2]
openage::renderer::opengl::GlBuffer::GlBuffer (size_t size, GLenum usage = GL_STATIC_DRAW)
Creates an empty buffer of the specified size. Binds the GL_COPY_WRITE_BUFFER target.
Definition at line 12 of file buffer.cpp.
     : GlSimpleObject([] (GLuint handle) { glDeleteBuffers(1, &handle); } )
     , size(size) {
     GLuint handle;
     glGenBuffers(1, &handle);
     this->handle = handle;
     this->bind(GL_COPY_WRITE_BUFFER);
     glBufferData(GL_COPY_WRITE_BUFFER, size, nullptr, usage);
 }
References openage::renderer::opengl::GlSimpleObject::handle.
GlBuffer() [2/2]
openage::renderer::opengl::GlBuffer::GlBuffer (const uint8_t * data, size_t size, GLenum usage = GL_STATIC_DRAW)
Creates a buffer of the specified size and fills it with the given data. Binds the GL_COPY_WRITE_BUFFER target.
Definition at line 23 of file buffer.cpp.
     : GlSimpleObject([] (GLuint handle) { glDeleteBuffers(1, &handle); } )
     , size(size) {
     GLuint handle;
     glGenBuffers(1, &handle);
     this->handle = handle;
     this->bind(GL_COPY_WRITE_BUFFER);
     glBufferData(GL_COPY_WRITE_BUFFER, size, data, usage);
 }
References openage::renderer::opengl::GlSimpleObject::handle.
Member Function Documentation
bind()
void openage::renderer::opengl::GlBuffer::bind (GLenum target) const
Bind this buffer to the specified GL target.
Definition at line 47 of file buffer.cpp.
{
     if (unlikely(!bool(this->handle))) {
         throw Error(MSG(err) << "OpenGL buffer has been moved out of.");
     }
     glBindBuffer(target, *this->handle);
 }
References openage::log::err(), openage::renderer::opengl::GlSimpleObject::handle, MSG, and unlikely.
Referenced by upload_data().
get_size()
size_t openage::renderer::opengl::GlBuffer::get_size () const
The size in bytes of this buffer.
Definition at line 34 of file buffer.cpp.
{
     return this->size;
 }
References size.
Referenced by openage.util.filelike.abstract.FileLikeObject::seek_helper().
upload_data()
void openage::renderer::opengl::GlBuffer::upload_data (const uint8_t * data, size_t offset, size_t size)
Uploads size bytes of new data starting at offset. offset + size has to be less than or equal to get_size(). Binds the GL_COPY_WRITE_BUFFER target.
Definition at line 38 of file buffer.cpp.
{
     if (unlikely(offset + size > this->size)) {
         throw Error(MSG(err) << "Tried to upload more data to OpenGL buffer than can fit.");
     }
     this->bind(GL_COPY_WRITE_BUFFER);
     glBufferSubData(GL_COPY_WRITE_BUFFER, offset, size, data);
 }
References bind(), openage::log::err(), MSG, size, and unlikely.
Member Data Documentation
size
size_t openage::renderer::opengl::GlBuffer::size private
The size in bytes of this buffer.
Definition at line 37 of file buffer.h.
Referenced by openage.util.bytequeue.ByteQueue::__len__(), openage.util.bytequeue.ByteQueue::append(), get_size(), openage.util.filelike.stream.StreamFragment::get_size(), openage.util.bytequeue.ByteQueue::popleft(), openage.util.filelike.stream.StreamFragment::read(), and upload_data().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/opengl/buffer.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/opengl/buffer.cpp