openage: openage::gui::GUI Class Reference
openage::gui::GUI Class Reference
Main entry point for the openage Qt-based user interface.
#include <gui.h>
Public Member Functions
GUI (SDL_Window *window, const std::string &source, const std::string &rootdir, EngineQMLInfo *info=nullptr)
virtual ~GUI ()
void process_events ()
Public Member Functions inherited from openage::InputHandler
virtual ~InputHandler ()=default
Public Member Functions inherited from openage::ResizeHandler
virtual ~ResizeHandler ()=default
Public Member Functions inherited from openage::HudHandler
virtual ~HudHandler ()=default
Private Member Functions
virtual bool on_resize (coord::viewport_delta new_size) override
execute the resize handler.
virtual bool on_input (SDL_Event *event) override
execute the input handler.
virtual bool on_drawhud () override
execute the drawing action.
Private Attributes
GLint tex_loc
GLuint screen_quad_vbo
GuiApplicationWithLogger application
qtsdl::GuiEventQueue render_updater
qtsdl::GuiRenderer renderer
qtsdl::GuiEventQueue game_logic_updater
GuiGameSpecImageProvider image_provider_by_filename
GuiGameSpecImageProvider image_provider_by_graphic_id
GuiGameSpecImageProvider image_provider_by_terrain_id
qtsdl::GuiEngine engine
qtsdl::GuiSubtree subtree
qtsdl::GuiInput input
std::unique_ptr< shader::Program > textured_screen_quad_shader
Detailed Description
Main entry point for the openage Qt-based user interface.
Definition at line 35 of file gui.h.
Constructor & Destructor Documentation
GUI()
openage::gui::GUI::GUI (SDL_Window * window, const std::string & source, const std::string & rootdir, EngineQMLInfo * info = nullptr) explicit
Definition at line 18 of file gui.cpp.
     :
     application{},
     render_updater{},
     renderer{window},
     game_logic_updater{},
     image_provider_by_filename{
         &render_updater,
         GuiGameSpecImageProvider::Type::ByFilename
     },
     image_provider_by_graphic_id{
         &render_updater,
         GuiGameSpecImageProvider::Type::ByGraphicId
     },
     image_provider_by_terrain_id{
         &render_updater,
         GuiGameSpecImageProvider::Type::ByTerrainId
     },
     engine{
         &renderer,
         {
             &image_provider_by_filename,
             &image_provider_by_graphic_id,
             &image_provider_by_terrain_id
         },
         info
     },
     subtree{
         &renderer,
         &game_logic_updater,
         &engine,
         source,
         rootdir
     },
     input{&renderer, &game_logic_updater} {
     info->engine->register_resize_action(this);
     info->engine->register_input_action(this);
     info->engine->register_drawhud_action(this);
     util::Path shader_dir = info->asset_dir / "shaders";
     const char *shader_header_code = "#version 120\n";
     auto text_vert_file = (shader_dir / "identity.vert.glsl").open();
     std::string texture_vert_code = text_vert_file.read();
     auto plaintexture_vert = std::make_unique<shader::Shader>(
         GL_VERTEX_SHADER,
         std::initializer_list<const char *>{ shader_header_code, texture_vert_code.c_str() }
     );
     text_vert_file.close();
     auto text_frag_file = (shader_dir / "maptexture.frag.glsl").open();
     std::string texture_frag_code = text_frag_file.read();
     auto plaintexture_frag = std::make_unique<shader::Shader>(
         GL_FRAGMENT_SHADER,
         std::initializer_list<const char *>{ shader_header_code, texture_frag_code.c_str() }
     );
     text_vert_file.close();
     this->textured_screen_quad_shader = std::make_unique<shader::Program>(
         plaintexture_vert.get(),
         plaintexture_frag.get()
     );
     this->textured_screen_quad_shader->link();
     this->tex_loc = this->textured_screen_quad_shader->get_uniform_id("texture");
     this->textured_screen_quad_shader->use();
     glUniform1i(this->tex_loc, 0);
     this->textured_screen_quad_shader->stopusing();
     const float screen_quad[] = {
         -1.f, -1.f,
         1.f, -1.f,
         1.f, 1.f,
         -1.f, 1.f,
     };
     glGenBuffers(1, &this->screen_quad_vbo);
     glBindBuffer(GL_ARRAY_BUFFER, this->screen_quad_vbo);
     glBufferData(GL_ARRAY_BUFFER, sizeof(screen_quad), screen_quad, GL_STATIC_DRAW);
     glBindBuffer(GL_ARRAY_BUFFER, 0);
 }
~GUI()
openage::gui::GUI::~GUI () virtual
Definition at line 106 of file gui.cpp.
           {
     glDeleteBuffers(1, &this->screen_quad_vbo);
 }
References screen_quad_vbo.
Member Function Documentation
on_drawhud()
bool openage::gui::GUI::on_drawhud () override private virtual
execute the drawing action.
Implements openage::HudHandler.
Definition at line 161 of file gui.cpp.
                      {
     this->render_updater.process_callbacks();
     BlendPreserver preserve_blend;
     auto tex = this->renderer.render();
     glEnable(GL_BLEND);
     glBlendFunc(GL_ONE, GL_ONE_MINUS_SRC_ALPHA);
     this->textured_screen_quad_shader->use();
     glActiveTexture(GL_TEXTURE0);
     glBindTexture(GL_TEXTURE_2D, tex);
     glEnableVertexAttribArray(this->textured_screen_quad_shader->pos_id);
     glBindBuffer(GL_ARRAY_BUFFER, this->screen_quad_vbo);
     glVertexAttribPointer(
         this->textured_screen_quad_shader->pos_id,
         2,
         GL_FLOAT,
         GL_FALSE,
         2 * sizeof(float), 0
     );
     glDrawArrays(GL_TRIANGLE_FAN, 0, 4);
     glDisableVertexAttribArray(this->textured_screen_quad_shader->pos_id);
     glBindBuffer(GL_ARRAY_BUFFER, 0);
     glBindTexture(GL_TEXTURE_2D, 0);
     this->textured_screen_quad_shader->stopusing();
     return true;
 }
References qtsdl::GuiEventQueue::process_callbacks(), qtsdl::GuiRenderer::render(), render_updater, renderer, screen_quad_vbo, and textured_screen_quad_shader.
on_input()
bool openage::gui::GUI::on_input (SDL_Event * event) override private virtual
execute the input handler.
Implements openage::InputHandler.
Definition at line 120 of file gui.cpp.
{
     return not this->input.process(event);
 }
References input, and qtsdl::GuiInput::process().
on_resize()
bool openage::gui::GUI::on_resize (coord::viewport_delta new_size) override private virtual
execute the resize handler.
Implements openage::ResizeHandler.
Definition at line 115 of file gui.cpp.
{
     this->renderer.resize(new_size.x, new_size.y);
     return true;
 }
References renderer, and qtsdl::GuiRenderer::resize().
process_events()
void openage::gui::GUI::process_events ()
Definition at line 110 of file gui.cpp.
{
     this->game_logic_updater.process_callbacks();
     this->application.processEvents();
 }
References application, game_logic_updater, qtsdl::GuiEventQueue::process_callbacks(), and qtsdl::GuiApplication::processEvents().
Member Data Documentation
application
GuiApplicationWithLogger openage::gui::GUI::application private
Definition at line 53 of file gui.h.
Referenced by process_events().
engine
qtsdl::GuiEngine openage::gui::GUI::engine private
Definition at line 60 of file gui.h.
game_logic_updater
qtsdl::GuiEventQueue openage::gui::GUI::game_logic_updater private
Definition at line 56 of file gui.h.
Referenced by process_events().
image_provider_by_filename
GuiGameSpecImageProvider openage::gui::GUI::image_provider_by_filename private
Definition at line 57 of file gui.h.
image_provider_by_graphic_id
GuiGameSpecImageProvider openage::gui::GUI::image_provider_by_graphic_id private
Definition at line 58 of file gui.h.
image_provider_by_terrain_id
GuiGameSpecImageProvider openage::gui::GUI::image_provider_by_terrain_id private
Definition at line 59 of file gui.h.
input
qtsdl::GuiInput openage::gui::GUI::input private
Definition at line 62 of file gui.h.
Referenced by on_input().
render_updater
qtsdl::GuiEventQueue openage::gui::GUI::render_updater private
Definition at line 54 of file gui.h.
Referenced by on_drawhud().
renderer
qtsdl::GuiRenderer openage::gui::GUI::renderer private
Definition at line 55 of file gui.h.
Referenced by on_drawhud(), and on_resize().
screen_quad_vbo
GLuint openage::gui::GUI::screen_quad_vbo private
Definition at line 51 of file gui.h.
Referenced by on_drawhud(), and ~GUI().
subtree
qtsdl::GuiSubtree openage::gui::GUI::subtree private
Definition at line 61 of file gui.h.
tex_loc
GLint openage::gui::GUI::tex_loc private
Definition at line 50 of file gui.h.
textured_screen_quad_shader
std::unique_ptr<shader::Program> openage::gui::GUI::textured_screen_quad_shader private
Definition at line 67 of file gui.h.
Referenced by on_drawhud().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/gui.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/gui.cpp