openage: openage::renderer::opengl::GlContext Class Reference
openage::renderer::opengl::GlContext Class Reference
Manages an OpenGL context.
#include <context.h>
Public Member Functions
GlContext (SDL_Window *)
Create a GL context in the given SDL window.
~GlContext ()
GlContext (const GlContext &)=delete
It doesn't make sense to have more than one instance of the same context.
GlContext & operator= (const GlContext &)=delete
GlContext (GlContext &&)
We have to support moving to avoid a mess somewhere else.
GlContext & operator= (GlContext &&)
SDL_GLContext get_raw_context () const
Returns the underlying SDL context pointer.
gl_context_capabilities get_capabilities () const
Returns the capabilities of this context.
void set_vsync (bool on)
Turns VSYNC on or off for this context.
Static Public Member Functions
static void check_error ()
Checks whether the current GL context on this thread reported any errors and throws an exception if it did.
Private Attributes
SDL_GLContext gl_context
Pointer to SDL struct representing the GL context.
gl_context_capabilities capabilities {}
Context capabilities.
Detailed Description
Manages an OpenGL context.
Definition at line 29 of file context.h.
Constructor & Destructor Documentation
GlContext() [1/3]
openage::renderer::opengl::GlContext::GlContext (SDL_Window * window) explicit
Create a GL context in the given SDL window.
Definition at line 86 of file context.cpp.
{
     this->capabilities = find_capabilities();
     auto const &capabilities = this->capabilities;
     SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE);
     SDL_GL_SetAttribute(SDL_GL_ACCELERATED_VISUAL, 1);
     SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 1);
     SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE, 24);
     SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, capabilities.major_version);
     SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, capabilities.minor_version);
     this->gl_context = SDL_GL_CreateContext(window);
     if (this->gl_context == nullptr) {
         throw Error(MSG(err) << "OpenGL context creation failed. SDL error: " << SDL_GetError());
     }
     // We still have to verify that our version of libepoxy supports this version of OpenGL.
     int epoxy_glv = capabilities.major_version * 10 + capabilities.minor_version;
     if (!epoxy_is_desktop_gl() || epoxy_gl_version() < epoxy_glv) {
         throw Error(MSG(err) << "The used version of libepoxy does not support OpenGL version "
                              << capabilities.major_version << "." << capabilities.minor_version);
     }
     log::log(MSG(info) << "Created OpenGL context version " << capabilities.major_version << "." << capabilities.minor_version);
     // To quote the standard doc: 'The value gives a rough estimate of the
     // largest texture that the GL can handle'
     // -> wat?  anyways, we need at least 1024x1024.
     log::log(MSG(dbg) << "Maximum supported texture size: "
                       << capabilities.max_texture_size);
     if (capabilities.max_texture_size < 1024) {
         throw Error(MSG(err) << "Maximum supported texture size is too small: "
                              << capabilities.max_texture_size);
     }
     log::log(MSG(dbg) << "Maximum supported texture units: "
                       << capabilities.max_texture_slots);
     if (capabilities.max_texture_slots < 2) {
         throw Error(MSG(err) << "Your GPU doesn't have enough texture units: "
                              << capabilities.max_texture_slots);
     }
 }
References capabilities, openage::log::dbg(), openage::log::err(), openage::renderer::opengl::find_capabilities(), gl_context, openage::log::info(), openage::log::log(), openage::renderer::opengl::gl_context_capabilities::major_version, openage::renderer::opengl::gl_context_capabilities::max_texture_size, openage::renderer::opengl::gl_context_capabilities::max_texture_slots, openage::renderer::opengl::gl_context_capabilities::minor_version, and MSG.
~GlContext()
openage::renderer::opengl::GlContext::~GlContext ()
Definition at line 130 of file context.cpp.
                       {
     if (this->gl_context != nullptr) {
         SDL_GL_DeleteContext(this->gl_context);
     }
 }
References gl_context.
GlContext() [2/3]
openage::renderer::opengl::GlContext::GlContext (const GlContext &) delete
It doesn't make sense to have more than one instance of the same context.
GlContext() [3/3]
openage::renderer::opengl::GlContext::GlContext (GlContext && other)
We have to support moving to avoid a mess somewhere else.
Definition at line 136 of file context.cpp.
     : gl_context(other.gl_context)
     , capabilities(other.capabilities) {
     other.gl_context = nullptr;
 }
Member Function Documentation
check_error()
void openage::renderer::opengl::GlContext::check_error () static
Checks whether the current GL context on this thread reported any errors and throws an exception if it did.
Note that it's static.
Definition at line 158 of file context.cpp.
{
     GLenum error_state = glGetError();
     if (error_state != GL_NO_ERROR) {
         const char *msg = [=] {
             // generate error message
             switch (error_state) {
             case GL_INVALID_ENUM:
                 // An unacceptable value is specified for an enumerated argument.
                 // The offending command is ignored
                 // and has no other side effect than to set the error flag.
                 return "GL_INVALID_ENUM";
             case GL_INVALID_VALUE:
                 // A numeric argument is out of range.
                 // The offending command is ignored
                 // and has no other side effect than to set the error flag.
                 return "GL_INVALID_VALUE";
             case GL_INVALID_OPERATION:
                 // The specified operation is not allowed in the current state.
                 // The offending command is ignored
                 // and has no other side effect than to set the error flag.
                 return "GL_INVALID_OPERATION";
             case GL_INVALID_FRAMEBUFFER_OPERATION:
                 // The framebuffer object is not complete. The offending command
                 // is ignored and has no other side effect than to set the error flag.
                 return "GL_INVALID_FRAMEBUFFER_OPERATION";
             case GL_OUT_OF_MEMORY:
                 // There is not enough memory left to execute the command.
                 // The state of the GL is undefined,
                 // except for the state of the error flags,
                 // after this error is recorded.
                 return "GL_OUT_OF_MEMORY";
             case GL_STACK_UNDERFLOW:
                 // An attempt has been made to perform an operation that would
                 // cause an internal stack to underflow.
                 return "GL_STACK_UNDERFLOW";
             case GL_STACK_OVERFLOW:
                 // An attempt has been made to perform an operation that would
                 // cause an internal stack to overflow.
                 return "GL_STACK_OVERFLOW";
             default:
                 // unknown error state
                 return "unknown error";
             }
         }();
         throw Error(
             MSG(err) << "An OpenGL error has occured.\n\t"
             << "(" << error_state << "): " << msg
         );
     }
 }
References openage::log::err(), and MSG.
Referenced by openage::renderer::tests::renderer_demo_0().
get_capabilities()
gl_context_capabilities openage::renderer::opengl::GlContext::get_capabilities () const
Returns the capabilities of this context.
Definition at line 154 of file context.cpp.
{
     return this->capabilities;
 }
References capabilities.
Referenced by openage::renderer::opengl::GlRenderer::add_shader().
get_raw_context()
SDL_GLContext openage::renderer::opengl::GlContext::get_raw_context () const
Returns the underlying SDL context pointer.
Definition at line 150 of file context.cpp.
{
     return this->gl_context;
 }
References gl_context.
operator=() [1/2]
GlContext& openage::renderer::opengl::GlContext::operator= (const GlContext &) delete
operator=() [2/2]
GlContext & openage::renderer::opengl::GlContext::operator= (GlContext && other)
Definition at line 142 of file context.cpp.
{
     this->gl_context = other.gl_context;
     this->capabilities = other.capabilities;
     other.gl_context = nullptr;
     return *this;
 }
References capabilities, and gl_context.
set_vsync()
void openage::renderer::opengl::GlContext::set_vsync (bool on)
Turns VSYNC on or off for this context.
Definition at line 210 of file context.cpp.
{
     if (on) {
         // try to use swap control tearing (adaptive vsync)
         if (SDL_GL_SetSwapInterval(-1) == -1) {
             // otherwise fall back to standard vsync
             SDL_GL_SetSwapInterval(1);
         }
     }
     else {
         SDL_GL_SetSwapInterval(0);
     }
 }
Member Data Documentation
capabilities
gl_context_capabilities openage::renderer::opengl::GlContext::capabilities {} private
Context capabilities.
Definition at line 61 of file context.h.
Referenced by get_capabilities(), GlContext(), and operator=().
gl_context
SDL_GLContext openage::renderer::opengl::GlContext::gl_context private
Pointer to SDL struct representing the GL context.
Definition at line 58 of file context.h.
Referenced by get_raw_context(), GlContext(), operator=(), and ~GlContext().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/opengl/context.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/opengl/context.cpp