openage: openage::util::FunctionPtr< ReturnType, ArgTypes > Class Template Reference
openage::util::FunctionPtr< ReturnType, ArgTypes > Class Template Reference
Simple wrapper type that contains a function pointer.
#include <language.h>
Public Member Functions
FunctionPtr (ReturnType(*ptr)(ArgTypes ...))
Implicit conversion from raw type.
Public Attributes
ReturnType(* ptr)(ArgTypes ...)
Detailed Description
template<typename ReturnType, typename ... ArgTypes>
class openage::util::FunctionPtr< ReturnType, ArgTypes >
Simple wrapper type that contains a function pointer.
Needed as workaround for http://stackoverflow.com/questions/31040075
Definition at line 20 of file language.h.
Constructor & Destructor Documentation
FunctionPtr()
template<typename ReturnType, typename ... ArgTypes> openage::util::FunctionPtr< ReturnType, ArgTypes >::FunctionPtr (ReturnType(*)(ArgTypes ...) ptr) inline
Implicit conversion from raw type.
Definition at line 25 of file language.h.
                                                  :
         ptr{ptr} {}
References openage::util::FunctionPtr< ReturnType, ArgTypes >::ptr.
Member Data Documentation
ptr
template<typename ReturnType, typename ... ArgTypes> ReturnType(* openage::util::FunctionPtr< ReturnType, ArgTypes >::ptr) (ArgTypes ...)
Definition at line 28 of file language.h.
Referenced by openage::pyinterface::Func< ReturnType, ArgTypes ... >::bind_catchexcept_impl(), openage::pyinterface::Func< ReturnType, ArgTypes ... >::bind_noexcept(), and openage::util::FunctionPtr< ReturnType, ArgTypes >::FunctionPtr().
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/language.h