openage: openage::options::OptionValue Class Reference
openage::options::OptionValue Class Reference
#include <options.h>
Public Member Functions
OptionValue (bool b)
OptionValue (int i)
OptionValue (double d)
OptionValue (const char *s)
OptionValue (const std::string &s)
OptionValue (const option_list &l)
OptionValue (const OptionValue &v)
OptionValue (util::Variable< bool > *b)
OptionValue (util::Variable< int > *i)
OptionValue (util::Variable< double > *d)
OptionValue (util::Variable< std::string > *s)
OptionValue (util::Variable< option_list > *l)
virtual ~OptionValue ()
bool is_reference () const
bool operator== (const OptionValue &other) const
const OptionValue & operator= (const OptionValue &other)
std::string str_value () const
template<class T >
const T & value () const
Public Attributes
const option_type type
Private Member Functions
void set (const OptionValue &other)
template<class T >
void set_value (const OptionValue &other)
Private Attributes
bool owner
util::VariableBase * var
Detailed Description
stores a type and value
Definition at line 39 of file options.h.
Constructor & Destructor Documentation
OptionValue() [1/12]
openage::options::OptionValue::OptionValue (bool b)
value ownership managed by this
Definition at line 9 of file options.cpp.
     :
     type{option_type::bool_type},
     owner{true},
     var{new util::Variable<bool>(b)} {}
References openage::options::bool_type.
OptionValue() [2/12]
openage::options::OptionValue::OptionValue (int i)
Definition at line 16 of file options.cpp.
     :
     type{option_type::int_type},
     owner{true},
     var{new util::Variable<int>(i)} {}
References openage::options::int_type.
OptionValue() [3/12]
openage::options::OptionValue::OptionValue (double d)
Definition at line 23 of file options.cpp.
     :
     type{option_type::double_type},
     owner{true},
     var{new util::Variable<double>(d)} {}
References openage::options::double_type.
OptionValue() [4/12]
openage::options::OptionValue::OptionValue (const char * s)
Definition at line 30 of file options.cpp.
     :
     type{option_type::string_type},
     owner{true},
     var{new util::Variable<std::string>(std::string(s))} {}
References openage::options::string_type.
OptionValue() [5/12]
openage::options::OptionValue::OptionValue (const std::string & s)
Definition at line 37 of file options.cpp.
     :
     type{option_type::string_type},
     owner{true},
     var{new util::Variable<std::string>(s)} {}
References openage::options::string_type.
OptionValue() [6/12]
openage::options::OptionValue::OptionValue (const option_list & l)
Definition at line 44 of file options.cpp.
     :
     type{option_type::list_type},
     owner{true},
     var{new util::Variable<option_list>(l)} {}
References openage::options::list_type.
OptionValue() [7/12]
openage::options::OptionValue::OptionValue (const OptionValue & v)
Definition at line 51 of file options.cpp.
     :
     type{v.type},
     owner{false},
     var{nullptr} {
     this->set(v);
 }
References type.
OptionValue() [8/12]
openage::options::OptionValue::OptionValue (util::Variable< bool > * b)
value owned by another object
Definition at line 60 of file options.cpp.
     :
     type{option_type::bool_type},
     owner{false},
     var{b} {}
References openage::options::bool_type.
OptionValue() [9/12]
openage::options::OptionValue::OptionValue (util::Variable< int > * i)
Definition at line 67 of file options.cpp.
     :
     type{option_type::int_type},
     owner{false},
     var{i} {}
References openage::options::int_type.
OptionValue() [10/12]
openage::options::OptionValue::OptionValue (util::Variable< double > * d)
Definition at line 74 of file options.cpp.
     :
     type{option_type::double_type},
     owner{false},
     var{d} {}
References openage::options::double_type.
OptionValue() [11/12]
openage::options::OptionValue::OptionValue (util::Variable< std::string > * s)
Definition at line 81 of file options.cpp.
     :
     type{option_type::string_type},
     owner{false},
     var{s} {}
References openage::options::string_type.
OptionValue() [12/12]
openage::options::OptionValue::OptionValue (util::Variable< option_list > * l)
Definition at line 88 of file options.cpp.
     :
     type{option_type::list_type},
     owner{false},
     var{l} {}
References openage::options::list_type.
~OptionValue()
openage::options::OptionValue::~OptionValue () virtual
Definition at line 95 of file options.cpp.
{
     if (this->owner) {
         delete this->var;
     }
 }
References owner, and var.
Member Function Documentation
is_reference()
bool openage::options::OptionValue::is_reference () const
True if this value references an object not owned by itself
Definition at line 102 of file options.cpp.
{
     return !this->owner;
 }
References owner.
operator=()
const OptionValue & openage::options::OptionValue::operator= (const OptionValue & other)
Assignment, reference values share their values non reference values are copied
Definition at line 136 of file options.cpp.
{
     if (this->type == other.type) {
         this->set(other);
     }
     return *this;
 }
References set(), and type.
operator==()
bool openage::options::OptionValue::operator== (const OptionValue & other) const
Checks equality
Definition at line 107 of file options.cpp.
{
     if (this->type != other.type) {
         return false;
     }
     // check each type
     switch (this->type) {
     case option_type::bool_type:
         return this->value<bool>() == other.value<bool>();
     case option_type::int_type:
         return this->value<int>() == other.value<int>();
     case option_type::double_type:
         return this->value<double>() == other.value<double>();
     case option_type::string_type:
         return this->value<std::string>() == other.value<std::string>();
     case option_type::list_type:
         return this->value<option_list>() == other.value<option_list>();
     }
     return false;
 }
References openage::options::bool_type, openage::options::double_type, openage::options::int_type, openage::options::list_type, openage::options::string_type, type, and value().
set()
void openage::options::OptionValue::set (const OptionValue & other) private
set the value
Definition at line 144 of file options.cpp.
{
     switch (this->type) {
     case option_type::bool_type:
         this->set_value<bool>(other);
         break;
     case option_type::int_type:
         this->set_value<int>(other);
         break;
     case option_type::double_type:
         this->set_value<double>(other);
         break;
     case option_type::string_type:
         this->set_value<std::string>(other);
         break;
     case option_type::list_type:
         this->set_value<option_list>(other);
         break;
     }
 }
References openage::options::bool_type, openage::options::double_type, openage::options::int_type, openage::options::list_type, openage::options::string_type, and type.
Referenced by operator=().
set_value()
template<class T > void openage::options::OptionValue::set_value (const OptionValue & other) inline private
Definition at line 104 of file options.h.
{
         const T &other_value = other.value<T>();
         if (this->var) {
             this->var->set<T>(other_value);
         }
         else if (other.owner) {
             this->owner = true;
             this->var = new util::Variable<T>(other_value);
         }
         else {
             this->var = other.var;
         }
     }
References owner, openage::util::VariableBase::set(), value(), and var.
str_value()
std::string openage::options::OptionValue::str_value () const
Value converted to a string
Definition at line 171 of file options.cpp.
{
     switch (this->type) {
     case option_type::bool_type:
         return this->value<bool>()? "true" : "false";
     case option_type::int_type:
         return std::to_string(this->value<int>());
     case option_type::double_type:
         return std::to_string(this->value<double>());
     case option_type::string_type:
         return this->value<std::string>();
     case option_type::list_type: {
         std::string result = "[ ";
         for (auto &i : this->value<option_list>()) {
             result += i.str_value() + " ";
         }
         result += "]";
         return result;
     }
     }
     return "";
 }
References openage::options::bool_type, openage::options::double_type, openage::options::int_type, openage::options::list_type, openage.testing.testing::result(), openage::options::string_type, std::to_string(), and type.
value()
template<class T > const T& openage::options::OptionValue::value () const inline
read inner type - the templated type must match
Definition at line 90 of file options.h.
{
         return var->get<T>();
     }
References openage::util::VariableBase::get(), and var.
Referenced by openage.convert.dataformat.members.ContinueReadMemberResult::__str__(), openage::options::OptionNode::getv(), operator==(), and set_value().
Member Data Documentation
owner
bool openage::options::OptionValue::owner private
Use of shared_ptr and unique_ptr doesnt work here possibly solved by templating ownership type
non-owned variables act as references
Definition at line 125 of file options.h.
Referenced by is_reference(), set_value(), and ~OptionValue().
type
const option_type openage::options::OptionValue::type
Definition at line 94 of file options.h.
Referenced by operator=(), operator==(), OptionValue(), set(), and str_value().
var
util::VariableBase* openage::options::OptionValue::var private
Definition at line 126 of file options.h.
Referenced by set_value(), value(), and ~OptionValue().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/options.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/options.cpp