openage: openage::GameControl Class Reference
openage::GameControl Class Reference
#include <game_control.h>
Public Member Functions
GameControl (qtsdl::GuiItemLink *gui_link)
void set_engine (Engine *engine)
void set_game (GameMainHandle *game)
void set_modes (const std::vector< OutputMode * > &modes)
void set_mode (int mode, bool signal_if_unchanged=false)
void announce_mode ()
void announce_current_player_name ()
bool on_drawhud () override
Player * get_current_player () const
Engine * get_engine () const
Public Member Functions inherited from openage::HudHandler
virtual ~HudHandler ()=default
Public Attributes
GameControlSignals gui_signals
qtsdl::GuiItemLink * gui_link
Private Attributes
Engine * engine
GameMainHandle * game
std::vector< OutputMode * > modes
OutputMode * active_mode
int active_mode_index
size_t current_player
Detailed Description
connects the gui system with the game engine switches between contexts such as editor mode and action mode
hud rendering and input handling is redirected to the active mode
Definition at line 353 of file game_control.h.
Constructor & Destructor Documentation
GameControl()
openage::GameControl::GameControl (qtsdl::GuiItemLink * gui_link) explicit
Definition at line 719 of file game_control.cpp.
     :
     engine{nullptr},
     game{nullptr},
     active_mode{nullptr},
     active_mode_index{-1},
     current_player{1},
     gui_signals{this},
     gui_link{gui_link} {
 }
Member Function Documentation
announce_current_player_name()
void openage::GameControl::announce_current_player_name ()
Definition at line 832 of file game_control.cpp.
{
     if (Player *player = this->get_current_player()) {
         emit this->gui_signals.current_player_name_changed(
             "[" + std::to_string(player->color) + "] " + player->name);
         emit this->gui_signals.current_civ_index_changed(player->civ->civ_id);
     }
 }
References openage::GameControlSignals::current_civ_index_changed(), openage::GameControlSignals::current_player_name_changed(), get_current_player(), gui_signals, and std::to_string().
Referenced by openage::GameControlSignals::on_game_running(), and set_engine().
announce_mode()
void openage::GameControl::announce_mode ()
Definition at line 823 of file game_control.cpp.
{
     emit this->gui_signals.mode_changed(this->active_mode,
                                         this->active_mode_index);
     if (this->active_mode != nullptr) {
         emit this->active_mode->announce();
     }
 }
References active_mode, active_mode_index, openage::OutputMode::announce(), gui_signals, and openage::GameControlSignals::mode_changed().
Referenced by set_mode().
get_current_player()
Player * openage::GameControl::get_current_player () const
Definition at line 848 of file game_control.cpp.
{
     if (auto game = this->engine->get_game()) {
         unsigned int number = game->player_count();
         return game->get_player(this->current_player % number);
     }
     return nullptr;
 }
References current_player, engine, game, and openage::Engine::get_game().
Referenced by openage::EditorMode::announce_categories(), openage::EditorMode::announce_category_content(), announce_current_player_name(), openage::ActionMode::announce_resources(), openage::ActionMode::get_action(), openage::ActionMode::on_game_control_set(), openage::EditorMode::paint_entity_at(), openage::ActionMode::place_selection(), and openage::ActionMode::render().
get_engine()
Engine * openage::GameControl::get_engine () const
Definition at line 919 of file game_control.cpp.
{
     if (this->engine == nullptr) {
         throw Error{MSG(err) << "game control doesn't have a valid engine pointer yet"};
     }
     return this->engine;
 }
References engine, openage::log::err(), and MSG.
Referenced by openage::ActionMode::announce_buttons_type(), openage::ActionMode::available(), openage::EditorMode::available(), openage::ActionMode::get_action(), openage::ActionModeSignals::on_action(), openage::ActionMode::on_exit(), openage::ActionMode::on_game_control_set(), openage::EditorMode::on_game_control_set(), openage::EditorMode::paint_entity_at(), openage::EditorMode::paint_terrain_at(), openage::ActionMode::place_selection(), and openage::ActionMode::render().
on_drawhud()
bool openage::GameControl::on_drawhud () override virtual
execute the drawing action.
Implements openage::HudHandler.
Definition at line 840 of file game_control.cpp.
{
     // render the active mode
     if (this->active_mode)
         this->active_mode->render();
     return true;
 }
References active_mode, and openage::OutputMode::render().
set_engine()
void openage::GameControl::set_engine (Engine * engine)
Definition at line 730 of file game_control.cpp.
{
     // \todo decide to either go for a full Engine QML-singleton or for a regular object
     ENSURE(!this->engine || this->engine == engine, "relinking GameControl to another engine is not supported and not caught properly");
     if (not this->engine) {
         this->engine = engine;
         // add handlers
         this->engine->register_drawhud_action(this);
         auto &action = this->engine->get_action_manager();
         auto &global_input_context = engine->get_input_manager().get_global_context();
         // advance the active mode
         global_input_context.bind(action.get("TOGGLE_CONSTRUCT_MODE"), [this](const input::action_arg_t &) {
             this->set_mode((this->active_mode_index + 1) % this->modes.size());
         });
         // Switching between players with the 1-8 keys
         auto bind_player_switch = [this, &global_input_context](input::action_t action, size_t player_index) {
             global_input_context.bind(action, [this, player_index](const input::action_arg_t &) {
                 if (this->current_player != player_index)
                     if (auto game = this->engine->get_game())
                         if (player_index < game->player_count()) {
                             this->current_player = player_index;
                             this->announce_current_player_name();
                         }
             });
         };
         bind_player_switch(action.get("SWITCH_TO_PLAYER_1"), 0);
         bind_player_switch(action.get("SWITCH_TO_PLAYER_2"), 1);
         bind_player_switch(action.get("SWITCH_TO_PLAYER_3"), 2);
         bind_player_switch(action.get("SWITCH_TO_PLAYER_4"), 3);
         bind_player_switch(action.get("SWITCH_TO_PLAYER_5"), 4);
         bind_player_switch(action.get("SWITCH_TO_PLAYER_6"), 5);
         bind_player_switch(action.get("SWITCH_TO_PLAYER_7"), 6);
         bind_player_switch(action.get("SWITCH_TO_PLAYER_8"), 7);
         this->engine->announce_global_binds();
     }
 }
References active_mode_index, announce_current_player_name(), openage::input::InputContext::bind(), current_player, engine, ENSURE, game, openage::GameMainHandle::get_game(), openage::input::InputManager::get_global_context(), openage::Engine::get_input_manager(), modes, openage::Engine::register_drawhud_action(), and set_mode().
Referenced by openage::gui::GameControlLink::set_engine().
set_game()
void openage::GameControl::set_game (GameMainHandle * game)
Definition at line 775 of file game_control.cpp.
{
     if (this->game != game) {
         if (this->game)
             QObject::disconnect(&this->game->gui_signals,
                                 &GameMainSignals::game_running,
                                 &this->gui_signals,
                                 &GameControlSignals::on_game_running);
         this->game = game;
         if (this->game)
             QObject::connect(&this->game->gui_signals,
                              &GameMainSignals::game_running,
                              &this->gui_signals,
                              &GameControlSignals::on_game_running);
     }
 }
References game, openage::GameMainSignals::game_running(), openage::GameMainHandle::gui_signals, and openage::GameControlSignals::on_game_running().
Referenced by openage::gui::GameControlLink::set_game().
set_mode()
void openage::GameControl::set_mode (int mode, bool signal_if_unchanged = false)
Definition at line 856 of file game_control.cpp.
{
     bool need_to_signal = signal_if_unchanged;
     // do we wanna set a new mode?
     if (mode_index != -1) {
         // if the new mode is valid, available and not active at the moment
         if (mode_index < std::distance(std::begin(this->modes),
                                        std::end(this->modes))
             && this->modes[mode_index]->available()
             && this->active_mode_index != mode_index) {
             ENSURE(!this->active_mode == (this->active_mode_index == -1),
                    "inconsistency between the active mode index and pointer");
             // exit from the old mode
             if (this->active_mode) {
                 this->engine->get_input_manager().remove_context(
                     this->active_mode
                 );
                 // trigger the exit callback of the mode
                 if (this->active_mode) {
                     this->active_mode->on_exit();
                 }
             }
             // set the new active mode
             this->active_mode_index = mode_index;
             this->active_mode = this->modes[mode_index];
             // trigger the entry callback
             this->active_mode->on_enter();
             // add the mode-local input context
             this->engine->get_input_manager().push_context(
                 this->active_mode
             );
             need_to_signal = true;
         }
     }
     else {
         // unassign the active mode
         if (this->active_mode) {
             // remove the input context
             this->engine->get_input_manager().remove_context(
                 this->active_mode
             );
             this->active_mode_index = -1;
             this->active_mode = nullptr;
             need_to_signal = true;
         }
     }
     if (need_to_signal) {
         this->announce_mode();
     }
 }
References active_mode, active_mode_index, announce_mode(), engine, ENSURE, openage::Engine::get_input_manager(), modes, openage::OutputMode::on_enter(), openage::OutputMode::on_exit(), openage::input::InputManager::push_context(), and openage::input::InputManager::remove_context().
Referenced by openage::gui::GameControlLink::on_modes_changed(), set_engine(), openage::gui::GameControlLink::set_mode_index(), and set_modes().
set_modes()
void openage::GameControl::set_modes (const std::vector< OutputMode * > & modes)
Definition at line 793 of file game_control.cpp.
{
     const int old_mode_index = this->active_mode_index;
     this->set_mode(-1);
     this->modes = modes;
     for (auto mode : this->modes) {
         // link the controller to the mode
         mode->set_game_control(this);
     }
     // announce the newly set modes
     emit this->gui_signals.modes_changed(this->active_mode,
                                          this->active_mode_index);
     // try to enter the mode we were in before
     // assuming its index didn't change.
     if (old_mode_index != -1) {
         if (old_mode_index < std::distance(std::begin(this->modes),
                                            std::end(this->modes))) {
             this->set_mode(old_mode_index, true);
         }
         else {
             log::log(MSG(warn) << "couldn't enter previous gui mode #"
                      << old_mode_index << " as it vanished.");
         }
     }
 }
References active_mode, active_mode_index, gui_signals, openage::log::log(), modes, openage::GameControlSignals::modes_changed(), MSG, set_mode(), and openage::log::warn().
Referenced by openage::gui::GameControlLink::set_modes().
Member Data Documentation
active_mode
OutputMode* openage::GameControl::active_mode private
Definition at line 378 of file game_control.h.
Referenced by announce_mode(), on_drawhud(), set_mode(), and set_modes().
active_mode_index
int openage::GameControl::active_mode_index private
Definition at line 379 of file game_control.h.
Referenced by announce_mode(), set_engine(), set_mode(), and set_modes().
current_player
size_t openage::GameControl::current_player private
Definition at line 381 of file game_control.h.
Referenced by get_current_player(), and set_engine().
engine
Engine* openage::GameControl::engine private
Definition at line 372 of file game_control.h.
Referenced by get_current_player(), get_engine(), set_engine(), and set_mode().
game
GameMainHandle* openage::GameControl::game private
Definition at line 373 of file game_control.h.
Referenced by get_current_player(), set_engine(), and set_game().
gui_link
qtsdl::GuiItemLink* openage::GameControl::gui_link
Definition at line 385 of file game_control.h.
gui_signals
GameControlSignals openage::GameControl::gui_signals
Definition at line 384 of file game_control.h.
Referenced by announce_current_player_name(), announce_mode(), openage::EditorMode::set_game_control(), and set_modes().
modes
std::vector<OutputMode*> openage::GameControl::modes private
Definition at line 376 of file game_control.h.
Referenced by set_engine(), set_mode(), and set_modes().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/game_control.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/game_control.cpp