openage: openage::Market Class Reference
openage::Market Class Reference
#include <market.h>
Public Member Functions
Market ()
bool sell (Player &player, const game_resource res)
bool buy (Player &player, const game_resource res)
ResourceBundle get_buy_prices (const Player &player) const
ResourceBundle get_sell_prices (const Player &player) const
Protected Member Functions
ResourceBundle get_prices (const Player &player, const bool is_buy) const
double get_multiplier (const Player &player, const bool is_buy) const
Private Attributes
ResourceBundle base_prices
Detailed Description
The global market prices.
Price calculation is documented at doc/reverse_engineering/market.md#prices
Definition at line 21 of file market.h.
Constructor & Destructor Documentation
Market()
openage::Market::Market ()
Definition at line 8 of file market.cpp.
                {
     // the default prices when a game starts
     this->base_prices[game_resource::wood] = 100;
     this->base_prices[game_resource::food] = 100;
     this->base_prices[game_resource::stone] = 130;
 }
References base_prices, openage::food, openage::stone, and openage::wood.
Member Function Documentation
buy()
bool openage::Market::buy (Player & player, const game_resource res)
The given player buys the given resource with gold. Returns true when the transaction is successful.
Definition at line 35 of file market.cpp.
{
     // calc the gold needed to buy MARKET_TRANSACTION_AMOUNT of res
     double price = this->get_buy_prices(player).get(res);
     if (player.deduct(game_resource::gold, price)) {
         // if deduct was successful
         player.receive(res, MARKET_TRANSACTION_AMOUNT);
         // increase the price
         this->base_prices[res] += MARKET_PRICE_D;
         if (this->base_prices.get(res) > MARKET_PRICE_MAX) {
             this->base_prices[res] = MARKET_PRICE_MAX;
         }
         return true;
     }
     return false;
 }
References base_prices, openage::Player::deduct(), openage::ResourceBundle::get(), get_buy_prices(), openage::gold, openage::MARKET_PRICE_D, openage::MARKET_PRICE_MAX, openage::MARKET_TRANSACTION_AMOUNT, and openage::Player::receive().
get_buy_prices()
ResourceBundle openage::Market::get_buy_prices (const Player & player) const
Get the selling prices for a given player.
Definition at line 52 of file market.cpp.
{
     return this->get_prices(player, true);
 }
References get_prices().
Referenced by buy().
get_multiplier()
double openage::Market::get_multiplier (const Player & player, const bool is_buy) const protected
Get the multiplier for the base prices
Definition at line 69 of file market.cpp.
{
     double base = 0.3;
     // TODO change multiplier based on civ bonuses and player researched techs
     double mult = base;
     if (is_buy) {
         mult = 1 + mult;
     }
     else {
         mult = 1 - mult;
     }
     return mult;
 }
Referenced by get_prices().
get_prices()
ResourceBundle openage::Market::get_prices (const Player & player, const bool is_buy) const protected
The getBuyPrices and getSellPrices are redirected here.
Definition at line 60 of file market.cpp.
{
     double mult = this->get_multiplier(player, is_buy);
     auto rb = ResourceBundle(this->base_prices);
     rb *= mult;
     rb.round(); // round to nearest integer
     return rb;
 }
References base_prices, and get_multiplier().
Referenced by get_buy_prices(), and get_sell_prices().
get_sell_prices()
ResourceBundle openage::Market::get_sell_prices (const Player & player) const
Get the buying prices for a given player.
Definition at line 56 of file market.cpp.
{
     return this->get_prices(player, false);
 }
References get_prices().
Referenced by sell().
sell()
bool openage::Market::sell (Player & player, const game_resource res)
The given player sells the given resource for gold. Returns true when the transaction is successful.
Definition at line 17 of file market.cpp.
{
     // deduct the standard MARKET_TRANSACTION_AMOUNT of the selling res
     if (player.deduct(res, MARKET_TRANSACTION_AMOUNT)) {
         // if deduct was successful
         // calc the gold received from selling MARKET_TRANSACTION_AMOUNT of res
         double amount = this->get_sell_prices(player).get(res);
         player.receive(game_resource::gold, amount);
         // decrease the price
         this->base_prices[res] -= MARKET_PRICE_D;
         if (this->base_prices.get(res) < MARKET_PRICE_MIN) {
             this->base_prices[res] = MARKET_PRICE_MIN;
         }
         return true;
     }
     return false;
 }
References base_prices, openage::Player::deduct(), openage::ResourceBundle::get(), get_sell_prices(), openage::gold, openage::MARKET_PRICE_D, openage::MARKET_PRICE_MIN, openage::MARKET_TRANSACTION_AMOUNT, and openage::Player::receive().
Member Data Documentation
base_prices
ResourceBundle openage::Market::base_prices private
Stores the base price values of each resource.
The ResourceBundle is used to represent the prices instead of the amounts for each resource.
Definition at line 67 of file market.h.
Referenced by buy(), get_prices(), Market(), and sell().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gamestate/market.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gamestate/market.cpp