openage: openage::gui::OutputModeLink Class Reference
openage::gui::OutputModeLink Class Reference
#include <game_control_link.h>
Signals
void name_changed ()
void binds_changed ()
Public Member Functions
OutputModeLink (QObject *parent=nullptr)
virtual ~OutputModeLink ()
QString get_name () const
QStringList get_binds () const
Public Member Functions inherited from qtsdl::GuiItemQObject
GuiItemQObject (QObject *parent=nullptr)
Public Member Functions inherited from qtsdl::GuiItemBase
virtual ~GuiItemBase ()
Public Member Functions inherited from qtsdl::DeferredInitialConstantPropertyValues
DeferredInitialConstantPropertyValues ()
virtual ~DeferredInitialConstantPropertyValues ()
void apply_static_properties ()
void clear_static_properties ()
bool is_init_over () const
Public Member Functions inherited from qtsdl::GuiItemLink
virtual ~GuiItemLink ()
Public Member Functions inherited from qtsdl::GuiItemInterface< OutputModeLink >
GuiItemInterface ()
Public Member Functions inherited from qtsdl::GuiItemMethods< OutputModeLink >
virtual ~GuiItemMethods ()
U * get () const
U * get ()
void i (F f, Args &&... args)
Protected Member Functions
virtual void classBegin () override
virtual void on_core_adopted () override
virtual void componentComplete () override
Protected Member Functions inherited from qtsdl::GuiItemMethods< OutputModeLink >
void s (F f, P &p, A &&arg)
void sf (F f, P &p, A &&arg)
Properties
QString name
QStringList binds
Private Slots
void on_announced (const std::string &name)
void on_binds_changed (const std::vector< std::string > &binds)
Additional Inherited Members
Protected Attributes inherited from qtsdl::GuiItemBase
GameLogicCaller game_logic_caller
std::function< std::unique_ptr< PersistentCoreHolderBase >)> instantiate_core_func
std::function< void(PersistentCoreHolderBase *, const QString &)> do_adopt_core_func
std::function< void()> on_core_adopted_func
Protected Attributes inherited from qtsdl::DeferredInitialConstantPropertyValues
bool init_over
std::vector< std::function< void()> > static_properties_assignments
Detailed Description
Definition at line 35 of file game_control_link.h.
Constructor & Destructor Documentation
OutputModeLink()
OutputModeLink::OutputModeLink (QObject * parent = nullptr)
Definition at line 24 of file game_control_link.cpp.
     :
     GuiItemQObject{parent},
     QQmlParserStatus{},
     GuiItemInterface<OutputModeLink>{} {
 }
~OutputModeLink()
OutputModeLink::~OutputModeLink () virtual
Definition at line 31 of file game_control_link.cpp.
{
 }
Member Function Documentation
binds_changed
void openage::gui::OutputModeLink::binds_changed () signal
Referenced by on_binds_changed().
classBegin()
void OutputModeLink::classBegin () override protected virtual
Definition at line 70 of file game_control_link.cpp.
{
 }
componentComplete()
void OutputModeLink::componentComplete () override protected virtual
Definition at line 85 of file game_control_link.cpp.
{
     static auto f = [] (OutputMode *_this) {
         _this->announce();
     };
     this->i(f);
 }
References qtsdl::GuiItemMethods< OutputModeLink >::i().
get_binds()
QStringList OutputModeLink::get_binds () const
Definition at line 38 of file game_control_link.cpp.
{
     return this->binds;
 }
References binds.
get_name()
QString OutputModeLink::get_name () const
Definition at line 34 of file game_control_link.cpp.
{
     return this->name;
 }
References name.
name_changed
void openage::gui::OutputModeLink::name_changed () signal
Referenced by on_announced().
on_announced
void OutputModeLink::on_announced (const std::string & name) private slot
Definition at line 42 of file game_control_link.cpp.
{
     auto new_name = QString::fromStdString(name);
     if (this->name != new_name) {
         this->name = new_name;
         emit this->name_changed();
     }
 }
References name, and name_changed().
Referenced by on_core_adopted().
on_binds_changed
void OutputModeLink::on_binds_changed (const std::vector< std::string > & binds) private slot
Definition at line 51 of file game_control_link.cpp.
{
     QStringList new_binds;
     std::transform(
         std::begin(binds),
         std::end(binds),
         std::back_inserter(new_binds),
         [] (const std::string &s) {
             return QString::fromStdString(s);
         }
     );
     if (this->binds != new_binds) {
         this->binds = new_binds;
         emit this->binds_changed();
     }
 }
References binds, binds_changed(), and qtsdl::GuiItemMethods< OutputModeLink >::s().
Referenced by on_core_adopted().
on_core_adopted()
void OutputModeLink::on_core_adopted () override protected virtual
Reimplemented from qtsdl::GuiItemBase.
Definition at line 73 of file game_control_link.cpp.
{
     QObject::connect(&unwrap(this)->gui_signals,
                      &OutputModeSignals::announced,
                      this,
                      &OutputModeLink::on_announced);
     QObject::connect(&unwrap(this)->gui_signals,
                      &OutputModeSignals::binds_changed,
                      this,
                      &OutputModeLink::on_binds_changed);
 }
References openage::OutputModeSignals::announced(), openage::OutputModeSignals::binds_changed(), on_announced(), on_binds_changed(), and qtsdl::unwrap().
Property Documentation
binds
QStringList OutputModeLink::binds read
Definition at line 40 of file game_control_link.h.
Referenced by get_binds(), and on_binds_changed().
name
QString OutputModeLink::name read
Definition at line 39 of file game_control_link.h.
Referenced by openage.convert.dataformat.header_snippet.HeaderSnippet::__eq__(), openage.convert.dataformat.header_snippet.HeaderSnippet::__hash__(), openage.convert.dataformat.header_snippet.HeaderSnippet::__repr__(), openage.convert.dataformat.header_snippet.HeaderSnippet::get_file_name(), get_name(), on_announced(), openage.util.fslike.path.Path::stem(), openage.util.fslike.path.Path::suffix(), and openage.util.fslike.path.Path::suffixes().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/game_control_link.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/game_control_link.cpp