openage: openage::gui::GuiGameSpecImageProviderByTerrainIdImpl Class Reference
openage::gui::GuiGameSpecImageProviderByTerrainIdImpl Class Reference
#include <gui_game_spec_image_provider_by_terrain_id_impl.h>
Public Member Functions
GuiGameSpecImageProviderByTerrainIdImpl (qtsdl::GuiEventQueue *render_updater)
virtual ~GuiGameSpecImageProviderByTerrainIdImpl ()
Public Member Functions inherited from openage::gui::GuiGameSpecImageProviderByIdImpl
GuiGameSpecImageProviderByIdImpl (qtsdl::GuiEventQueue *render_updater)
virtual ~GuiGameSpecImageProviderByIdImpl ()
Public Member Functions inherited from openage::gui::GuiGameSpecImageProviderImpl
GuiGameSpecImageProviderImpl (qtsdl::GuiEventQueue *render_updater)
virtual ~GuiGameSpecImageProviderImpl ()
void on_game_spec_loaded (const std::shared_ptr< GameSpec > &loaded_game_spec)
void on_game_spec_invalidated ()
GuiFilledTextureHandleUser fill_texture_handle (const QString &id, const QSize &requested_size, SizedTextureHandle *filled_handle)
Public Member Functions inherited from qtsdl::GuiImageProviderImpl
GuiImageProviderImpl ()
virtual ~GuiImageProviderImpl ()
Static Public Member Functions
static const char * id ()
Static Public Member Functions inherited from qtsdl::GuiImageProviderImpl
static std::unique_ptr< GuiImageProviderImpl > take_ownership (GuiImageProvider *image_provider)
static std::vector< std::unique_ptr< GuiImageProviderImpl > > take_ownership (const std::vector< GuiImageProvider * > &image_providers)
Private Member Functions
virtual const char * get_id () const override
virtual openage::Texture * get_texture (int texture_id) override
Additional Inherited Members
Protected Member Functions inherited from openage::gui::GuiGameSpecImageProviderImpl
TextureHandle get_missing_texture ()
Protected Attributes inherited from openage::gui::GuiGameSpecImageProviderImpl
std::shared_ptr< GameSpec > loaded_game_spec
bool invalidated
Detailed Description
Exposes terrain textures to the Qt by their id.
Numeric id has a form of <texture-id>.<subid> where texture-id is the position in the terrain_meta.
Definition at line 15 of file gui_game_spec_image_provider_by_terrain_id_impl.h.
Constructor & Destructor Documentation
GuiGameSpecImageProviderByTerrainIdImpl()
openage::gui::GuiGameSpecImageProviderByTerrainIdImpl::GuiGameSpecImageProviderByTerrainIdImpl (qtsdl::GuiEventQueue * render_updater) explicit
Definition at line 12 of file gui_game_spec_image_provider_by_terrain_id_impl.cpp.
     :
     GuiGameSpecImageProviderByIdImpl{render_updater} {
 }
~GuiGameSpecImageProviderByTerrainIdImpl()
openage::gui::GuiGameSpecImageProviderByTerrainIdImpl::~GuiGameSpecImageProviderByTerrainIdImpl () virtual
Definition at line 17 of file gui_game_spec_image_provider_by_terrain_id_impl.cpp.
{
 }
Member Function Documentation
get_id()
const char * openage::gui::GuiGameSpecImageProviderByTerrainIdImpl::get_id () const override private virtual
Implements qtsdl::GuiImageProviderImpl.
Definition at line 24 of file gui_game_spec_image_provider_by_terrain_id_impl.cpp.
{
     return GuiGameSpecImageProviderByTerrainIdImpl::id();
 }
References id().
get_texture()
openage::Texture * openage::gui::GuiGameSpecImageProviderByTerrainIdImpl::get_texture (int texture_id) override private virtual
Implements openage::gui::GuiGameSpecImageProviderByIdImpl.
Definition at line 28 of file gui_game_spec_image_provider_by_terrain_id_impl.cpp.
{
     ENSURE(this->loaded_game_spec, "trying to actually get a texture from a non-loaded spec");
     auto meta = this->loaded_game_spec->get_terrain_meta();
     return meta && texture_id >=0 && texture_id < std::distance(std::begin(meta->textures), std::end(meta->textures)) ? meta->textures[texture_id] : nullptr;
 }
References ENSURE, and openage::gui::GuiGameSpecImageProviderImpl::loaded_game_spec.
id()
const char * openage::gui::GuiGameSpecImageProviderByTerrainIdImpl::id () static
Definition at line 20 of file gui_game_spec_image_provider_by_terrain_id_impl.cpp.
{
     return "by-terrain-id";
 }
Referenced by get_id(), and openage::gui::GuiImageProviderLink::provider_by_terrain_id().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/integration/private/gui_game_spec_image_provider_by_terrain_id_impl.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/integration/private/gui_game_spec_image_provider_by_terrain_id_impl.cpp