openage: openage::TeamScore Class Reference
openage::TeamScore Class Reference
The score of a team.
#include <score.h>
Public Member Functions
TeamScore (Team *team)
virtual void update_score () override
Calculates the total score from the sub-scores.
Public Member Functions inherited from openage::Score
Score ()
void add_score (const score_category cat, double value)
void add_score (const score_category cat, int value)
void remove_score (const score_category cat, double value)
void remove_score (const score_category cat, int value)
void update_map_explored (double progress)
Updates map exploration precentance based sub-scores.
void update_resources (const ResourceBundle &resources)
Updates resource based sub-scores.
int get_score (const score_category cat) const
int get_score (const int index) const
int get_score_total () const
Private Attributes
Team * team
Additional Inherited Members
Protected Attributes inherited from openage::Score
int score [static_cast< int >(score_category::SCORE_CATEGORY_COUNT)]
int score_total
Detailed Description
The score of a team.
Definition at line 106 of file score.h.
Constructor & Destructor Documentation
TeamScore()
openage::TeamScore::TeamScore (Team * team)
Definition at line 71 of file score.cpp.
     :
     Score(),
     team{team} {
 }
References team.
Member Function Documentation
update_score()
void openage::TeamScore::update_score () override virtual
Calculates the total score from the sub-scores.
Todo:
update gui here
Reimplemented from openage::Score.
Definition at line 77 of file score.cpp.
{
     // scores are the corresponding sums of players score
     for (int i = 0; i < static_cast<int>(score_category::SCORE_CATEGORY_COUNT); i++) {
         this->score[i] = 0;
     }
     for (auto player : this->team->get_players()) {
         for (int i = 0; i < static_cast<int>(score_category::SCORE_CATEGORY_COUNT); i++) {
             this->score[i] += player->score.get_score(i);
         }
     }
     Score::update_score();
 }
References openage::Team::get_players(), openage::Score::score, openage::SCORE_CATEGORY_COUNT, team, and openage::Score::update_score().
Referenced by openage::PlayerScore::update_score().
Member Data Documentation
team
Team* openage::TeamScore::team private
Definition at line 117 of file score.h.
Referenced by TeamScore(), and update_score().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gamestate/score.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gamestate/score.cpp