openage: openage::MoveAbility Class Reference
openage::MoveAbility Class Reference
initiates a move action when given a valid target
#include <ability.h>
Public Member Functions
MoveAbility (const Sound *s=nullptr)
ability_type type () override
bool can_invoke (Unit &to_modify, const Command &cmd) override
true if the paramaters allow an action to be performed
void invoke (Unit &to_modify, const Command &cmd, bool play_sound=false) override
applies command to a given unit
Public Member Functions inherited from openage::UnitAbility
virtual ~UnitAbility ()
bool has_hitpoints (Unit &target)
some common functions
bool is_damaged (Unit &target)
bool has_resource (Unit &target)
bool is_same_player (Unit &to_modify, Unit &target)
bool is_ally (Unit &to_modify, Unit &target)
bool is_enemy (Unit &to_modify, Unit &target)
Private Attributes
const Sound * sound
Additional Inherited Members
Static Public Member Functions inherited from openage::UnitAbility
static ability_set set_from_list (const std::vector< ability_type > &items)
set bits corresponding to abilities, useful for initialising an ability_set using a brace enclosed list
Detailed Description
initiates a move action when given a valid target
Definition at line 121 of file ability.h.
Constructor & Destructor Documentation
MoveAbility()
openage::MoveAbility::MoveAbility (const Sound * s = nullptr)
Definition at line 62 of file ability.cpp.
     :
     sound{s} {
 }
Member Function Documentation
can_invoke()
bool openage::MoveAbility::can_invoke (Unit & to_modify, const Command & cmd) override virtual
true if the paramaters allow an action to be performed
Implements openage::UnitAbility.
Definition at line 67 of file ability.cpp.
{
     if (cmd.has_position()) {
         return bool(to_modify.location);
     }
     else if (cmd.has_unit()) {
         return to_modify.location &&
                cmd.unit()->location &&
                &to_modify != cmd.unit(); // cannot target self
     }
     return false;
 }
References openage::Command::has_position(), openage::Command::has_unit(), openage::Unit::location, and openage::Command::unit().
invoke()
void openage::MoveAbility::invoke (Unit & to_modify, const Command & cmd, bool play_sound = false) override virtual
applies command to a given unit
Implements openage::UnitAbility.
Definition at line 79 of file ability.cpp.
{
     to_modify.log(MSG(dbg) << "invoke move action");
     if (play_sound && this->sound) {
         this->sound->play();
     }
     if (cmd.has_position()) {
         auto target = cmd.position();
         to_modify.push_action(std::make_unique<MoveAction>(&to_modify, target));
     }
     else if (cmd.has_unit()) {
         auto target = cmd.unit();
         // distance from the targets edge that is required to stop moving
         coord::phys_t radius = path::path_grid_size + (to_modify.location->min_axis() / 2L);
         // add the range of the unit if cmd indicator is set
         if (cmd.has_flag(command_flag::use_range) && to_modify.has_attribute(attr_type::attack)) {
             auto &att = to_modify.get_attribute<attr_type::attack>();
             radius += att.max_range;
         }
         to_modify.push_action(std::make_unique<MoveAction>(&to_modify, target->get_ref(), radius));
     }
 }
References openage::attack, openage::log::dbg(), openage::Unit::get_attribute(), openage::Unit::get_ref(), openage::Unit::has_attribute(), openage::Command::has_flag(), openage::Command::has_position(), openage::Command::has_unit(), openage::Unit::location, openage::log::LogSource::log(), MSG, openage::path::path_grid_size, openage::Sound::play(), openage::Command::position(), openage::Unit::push_action(), sound, openage::Command::unit(), and openage::use_range.
type()
ability_type openage::MoveAbility::type () inline override virtual
Implements openage::UnitAbility.
Definition at line 125 of file ability.h.
{
         return ability_type::move;
     }
References openage::move.
Member Data Documentation
sound
const Sound* openage::MoveAbility::sound private
Definition at line 134 of file ability.h.
Referenced by invoke().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/ability.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/ability.cpp