openage: openage::GatherAbility Class Reference
openage::GatherAbility Class Reference
#include <ability.h>
Public Member Functions
GatherAbility (const Sound *s=nullptr)
ability_type type () override
bool can_invoke (Unit &to_modify, const Command &cmd) override
void invoke (Unit &to_modify, const Command &cmd, bool play_sound=false) override
Public Member Functions inherited from openage::UnitAbility
virtual ~UnitAbility ()
bool has_hitpoints (Unit &target)
bool is_damaged (Unit &target)
bool has_resource (Unit &target)
bool is_same_player (Unit &to_modify, Unit &target)
bool is_ally (Unit &to_modify, Unit &target)
bool is_enemy (Unit &to_modify, Unit &target)
Private Attributes
const Sound * sound
Additional Inherited Members
Static Public Member Functions inherited from openage::UnitAbility
static ability_set set_from_list (const std::vector< ability_type > &items)
Detailed Description
initiates an gather resource action when given a valid target
Definition at line 252 of file ability.h.
Constructor & Destructor Documentation
GatherAbility()
openage::GatherAbility::GatherAbility (const Sound * s = nullptr)
Definition at line 241 of file ability.cpp.
     :
     sound{s} {
 }
Member Function Documentation
can_invoke()
bool openage::GatherAbility::can_invoke (Unit & to_modify, const Command & cmd) override virtual
true if the paramaters allow an action to be performed
Implements openage::UnitAbility.
Definition at line 246 of file ability.cpp.
{
     if (cmd.has_unit()) {
         Unit &target = *cmd.unit();
         return &to_modify != &target &&
                to_modify.location &&
                to_modify.has_attribute(attr_type::worker) &&
                has_resource(target);
     }
     return false;
 }
References openage::Unit::has_attribute(), openage::UnitAbility::has_resource(), openage::Command::has_unit(), openage::Unit::location, openage::Command::unit(), and openage::worker.
invoke()
void openage::GatherAbility::invoke (Unit & to_modify, const Command & cmd, bool play_sound = false) override virtual
applies command to a given unit
Implements openage::UnitAbility.
Definition at line 257 of file ability.cpp.
{
     to_modify.log(MSG(dbg) << "invoke gather action");
     if (play_sound && this->sound) {
         this->sound->play();
     }
     Unit *target = cmd.unit();
     try {
         to_modify.push_action(std::make_unique<GatherAction>(&to_modify, target->get_ref()));
     } catch (const std::invalid_argument &e) {
         to_modify.log(MSG(dbg) << "invoke gather action cancelled due to an exception. Reason: " << e.what());
     }
 }
References openage::log::dbg(), openage::Unit::get_ref(), openage::log::LogSource::log(), MSG, openage::Sound::play(), openage::Unit::push_action(), sound, and openage::Command::unit().
type()
ability_type openage::GatherAbility::type () inline override virtual
Implements openage::UnitAbility.
Definition at line 256 of file ability.h.
{
         return ability_type::gather;
     }
References openage::gather.
Member Data Documentation
sound
const Sound* openage::GatherAbility::sound private
Definition at line 265 of file ability.h.
Referenced by invoke().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/ability.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/ability.cpp