openage: qtsdl::QmlEngineWithSingletonItemsInfo Class Reference
qtsdl::QmlEngineWithSingletonItemsInfo Class Reference
#include <qml_engine_with_singleton_items_info.h>
Public Member Functions
QmlEngineWithSingletonItemsInfo (std::vector< std::unique_ptr< GuiImageProviderImpl >> &&image_providers, GuiSingletonItemsInfo *singleton_items_info=nullptr)
QmlEngineWithSingletonItemsInfo (std::vector< std::unique_ptr< GuiImageProviderImpl >> &image_providers, GuiSingletonItemsInfo *singleton_items_info=nullptr)
virtual ~QmlEngineWithSingletonItemsInfo ()
GuiSingletonItemsInfo * get_singleton_items_info () const
std::vector< GuiImageProviderImpl * > get_image_providers () const
Private Attributes
std::vector< GuiImageProviderImpl * > image_providers
GuiSingletonItemsInfo * singleton_items_info
Detailed Description
The Qml Engine used by openage.
It's extended to contain the "singleton items info" and a list of image providers. The singleton item info is just a struct that allows to carry some variables in the qml-engine, namely the openage-engine.
That way, the openage-engine and the qml-engine have a 1:1 relation and qml can access the main engine directly.
Definition at line 25 of file qml_engine_with_singleton_items_info.h.
Constructor & Destructor Documentation
QmlEngineWithSingletonItemsInfo() [1/2]
qtsdl::QmlEngineWithSingletonItemsInfo::QmlEngineWithSingletonItemsInfo (std::vector< std::unique_ptr< GuiImageProviderImpl >> && image_providers, GuiSingletonItemsInfo * singleton_items_info = nullptr) explicit
Definition at line 9 of file qml_engine_with_singleton_items_info.cpp.
     :
     QmlEngineWithSingletonItemsInfo{image_providers, singleton_items_info} {
 }
References image_providers, and singleton_items_info.
QmlEngineWithSingletonItemsInfo() [2/2]
qtsdl::QmlEngineWithSingletonItemsInfo::QmlEngineWithSingletonItemsInfo (std::vector< std::unique_ptr< GuiImageProviderImpl >> & image_providers, GuiSingletonItemsInfo * singleton_items_info = nullptr) explicit
Definition at line 14 of file qml_engine_with_singleton_items_info.cpp.
     :
     QQmlEngine{},
     image_providers(image_providers.size()),
     singleton_items_info{singleton_items_info} {
     std::transform(std::begin(image_providers), std::end(image_providers), std::begin(this->image_providers), [] (const std::unique_ptr<GuiImageProviderImpl> &image_provider) {
         return image_provider.get();
     });
     std::for_each(std::begin(image_providers), std::end(image_providers), [this] (std::unique_ptr<GuiImageProviderImpl> &image_provider) {
         auto id = image_provider->get_id();
         this->addImageProvider(id, image_provider.release());
     });
 }
~QmlEngineWithSingletonItemsInfo()
qtsdl::QmlEngineWithSingletonItemsInfo::~QmlEngineWithSingletonItemsInfo () virtual
Definition at line 30 of file qml_engine_with_singleton_items_info.cpp.
{
     std::for_each(std::begin(this->image_providers), std::end(this->image_providers), [this] (GuiImageProviderImpl *image_provider) {
         image_provider->give_up();
         this->removeImageProvider(image_provider->get_id());
     });
 }
References openage::util::for_each(), qtsdl::GuiImageProviderImpl::get_id(), qtsdl::GuiImageProviderImpl::give_up(), and image_providers.
Member Function Documentation
get_image_providers()
std::vector< GuiImageProviderImpl * > qtsdl::QmlEngineWithSingletonItemsInfo::get_image_providers () const
Definition at line 41 of file qml_engine_with_singleton_items_info.cpp.
{
     return this->image_providers;
 }
References image_providers.
Referenced by openage::gui::GuiImageProviderLink::provider().
get_singleton_items_info()
GuiSingletonItemsInfo * qtsdl::QmlEngineWithSingletonItemsInfo::get_singleton_items_info () const
Definition at line 37 of file qml_engine_with_singleton_items_info.cpp.
{
     return this->singleton_items_info;
 }
References singleton_items_info.
Referenced by openage::gui::MainArgsLink::provider(), and openage::gui::EngineLink::provider().
Member Data Documentation
image_providers
std::vector<GuiImageProviderImpl*> qtsdl::QmlEngineWithSingletonItemsInfo::image_providers private
Definition at line 37 of file qml_engine_with_singleton_items_info.h.
Referenced by get_image_providers(), QmlEngineWithSingletonItemsInfo(), and ~QmlEngineWithSingletonItemsInfo().
singleton_items_info
GuiSingletonItemsInfo* qtsdl::QmlEngineWithSingletonItemsInfo::singleton_items_info private
Definition at line 38 of file qml_engine_with_singleton_items_info.h.
Referenced by get_singleton_items_info(), and QmlEngineWithSingletonItemsInfo().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/guisys/link/qml_engine_with_singleton_items_info.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/guisys/link/qml_engine_with_singleton_items_info.cpp