openage: qtsdl::GuiEngineImplConnection Class Reference
qtsdl::GuiEngineImplConnection Class Reference
#include <gui_subtree_impl.h>
Public Member Functions
GuiEngineImplConnection ()
GuiEngineImplConnection (GuiSubtreeImpl *subtree, GuiEngineImpl *engine, const QString &root_dir)
~GuiEngineImplConnection ()
GuiEngineImplConnection (GuiEngineImplConnection &&cnx) noexcept
GuiEngineImplConnection & operator= (GuiEngineImplConnection &&cnx) noexcept
bool has_subtree () const
QQmlContext * rootContext () const
QQmlEngine * get_qml_engine () const
Private Member Functions
GuiEngineImplConnection (const GuiEngineImplConnection &cnx)=delete
GuiEngineImplConnection & operator= (const GuiEngineImplConnection &cnx)=delete
void disconnect ()
Private Attributes
GuiSubtreeImpl * subtree
GuiEngineImpl * engine
QString root_dir
Detailed Description
Definition at line 27 of file gui_subtree_impl.h.
Constructor & Destructor Documentation
GuiEngineImplConnection() [1/4]
qtsdl::GuiEngineImplConnection::GuiEngineImplConnection ()
Definition at line 189 of file gui_subtree_impl.cpp.
     :
     subtree{},
     engine{} {
 }
GuiEngineImplConnection() [2/4]
qtsdl::GuiEngineImplConnection::GuiEngineImplConnection (GuiSubtreeImpl * subtree, GuiEngineImpl * engine, const QString & root_dir) explicit
Definition at line 195 of file gui_subtree_impl.cpp.
     :
     subtree{subtree},
     engine{engine},
     root_dir{root_dir} {
     assert(this->subtree);
     assert(this->engine);
     QObject::connect(
         this->engine,
         &GuiEngineImpl::reload,
         this->subtree,
         &GuiSubtreeImpl::onEngineReloaded
     );
     // add the directory so it can be watched for changes.
     this->engine->add_root_dir_path(this->root_dir);
 }
References subtree.
~GuiEngineImplConnection()
qtsdl::GuiEngineImplConnection::~GuiEngineImplConnection ()
Definition at line 217 of file gui_subtree_impl.cpp.
{
     this->disconnect();
 }
References disconnect().
GuiEngineImplConnection() [3/4]
qtsdl::GuiEngineImplConnection::GuiEngineImplConnection (GuiEngineImplConnection && cnx) noexcept
Definition at line 238 of file gui_subtree_impl.cpp.
     :
     subtree{cnx.subtree},
     engine{cnx.engine} {
     cnx.subtree = nullptr;
     cnx.engine = nullptr;
 }
GuiEngineImplConnection() [4/4]
qtsdl::GuiEngineImplConnection::GuiEngineImplConnection (const GuiEngineImplConnection & cnx) private delete
Member Function Documentation
disconnect()
void qtsdl::GuiEngineImplConnection::disconnect () private
Definition at line 221 of file gui_subtree_impl.cpp.
{
     if (this->has_subtree()) {
         assert(this->engine);
         QObject::disconnect(
             this->engine,
             &GuiEngineImpl::reload,
             this->subtree,
             &GuiSubtreeImpl::onEngineReloaded
         );
         if (not this->root_dir.isEmpty()) {
             this->engine->remove_root_dir_path(this->root_dir);
         }
     }
 }
References engine, has_subtree(), qtsdl::GuiSubtreeImpl::onEngineReloaded(), qtsdl::GuiEngineImpl::reload(), qtsdl::GuiEngineImpl::remove_root_dir_path(), root_dir, and subtree.
Referenced by ~GuiEngineImplConnection().
get_qml_engine()
QQmlEngine * qtsdl::GuiEngineImplConnection::get_qml_engine () const
Definition at line 269 of file gui_subtree_impl.cpp.
{
     assert(this->subtree);
     assert(this->engine);
     return this->engine->get_qml_engine();
 }
References engine, qtsdl::GuiEngineImpl::get_qml_engine(), and subtree.
Referenced by qtsdl::GuiSubtreeImpl::onEngineReloaded().
has_subtree()
bool qtsdl::GuiEngineImplConnection::has_subtree () const
Definition at line 259 of file gui_subtree_impl.cpp.
{
     return this->subtree != nullptr;
 }
References subtree.
Referenced by qtsdl::GuiSubtreeImpl::attach_to(), and disconnect().
operator=() [1/2]
GuiEngineImplConnection & qtsdl::GuiEngineImplConnection::operator= (GuiEngineImplConnection && cnx) noexcept
Definition at line 247 of file gui_subtree_impl.cpp.
{
     this->disconnect();
     this->subtree = cnx.subtree;
     this->engine = cnx.engine;
     cnx.subtree = nullptr;
     cnx.engine = nullptr;
     return *this;
 }
operator=() [2/2]
GuiEngineImplConnection& qtsdl::GuiEngineImplConnection::operator= (const GuiEngineImplConnection & cnx) private delete
rootContext()
QQmlContext * qtsdl::GuiEngineImplConnection::rootContext () const
Definition at line 263 of file gui_subtree_impl.cpp.
{
     assert(this->subtree);
     assert(this->engine);
     return this->engine->get_qml_engine()->rootContext();
 }
References engine, qtsdl::GuiEngineImpl::get_qml_engine(), and subtree.
Member Data Documentation
engine
GuiEngineImpl* qtsdl::GuiEngineImplConnection::engine private
Definition at line 50 of file gui_subtree_impl.h.
Referenced by disconnect(), get_qml_engine(), and rootContext().
root_dir
QString qtsdl::GuiEngineImplConnection::root_dir private
Definition at line 51 of file gui_subtree_impl.h.
Referenced by disconnect().
subtree
GuiSubtreeImpl* qtsdl::GuiEngineImplConnection::subtree private
Definition at line 49 of file gui_subtree_impl.h.
Referenced by disconnect(), get_qml_engine(), GuiEngineImplConnection(), has_subtree(), and rootContext().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/guisys/private/gui_subtree_impl.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/guisys/private/gui_subtree_impl.cpp