openage: openage::IntervalTimer Class Reference
openage::IntervalTimer Class Reference
A interval triggering timer used in actions.
#include <action.h>
Public Member Functions
IntervalTimer (unsigned int interval)
Constructs a timer with a given interval.
IntervalTimer (unsigned int interval, int max_triggers)
Constructs a timer with a given interval which will stop after a given number of triggers.
void skip_to_trigger ()
bool update (unsigned int time)
unsigned int get_time_left () const
Returns the time until the next trigger.
float get_progress () const
bool has_triggers () const
Returns true if at least one interval has passed.
bool finished () const
Returns true if the interval passed have reached the max.
int get_triggers () const
Returns the number of intervals passed.
unsigned int get_interval () const
void set_interval (unsigned int interval)
Private Attributes
unsigned int interval
int max_triggers
unsigned int time_left
int triggers
Detailed Description
A interval triggering timer used in actions.
Todo:
find a better name for triggers
Definition at line 25 of file action.h.
Constructor & Destructor Documentation
IntervalTimer() [1/2]
openage::IntervalTimer::IntervalTimer (unsigned int interval)
Constructs a timer with a given interval.
Definition at line 19 of file action.cpp.
     :
     IntervalTimer{interval, -1} {
 }
References interval.
IntervalTimer() [2/2]
openage::IntervalTimer::IntervalTimer (unsigned int interval, int max_triggers)
Constructs a timer with a given interval which will stop after a given number of triggers.
Definition at line 24 of file action.cpp.
     :
     interval{interval},
     max_triggers{max_triggers},
     time_left{interval},
     triggers{0} {
 }
References interval.
Member Function Documentation
finished()
bool openage::IntervalTimer::finished () const
Returns true if the interval passed have reached the max.
Definition at line 61 of file action.cpp.
{
     return this->triggers == this->max_triggers;
 }
References max_triggers, and triggers.
Referenced by openage::TrainAction::update().
get_interval()
unsigned int openage::IntervalTimer::get_interval () const inline
Definition at line 65 of file action.h.
 { return this->interval; }
References interval.
Referenced by openage::AttackAction::update_in_range(), and openage::HealAction::update_in_range().
get_progress()
float openage::IntervalTimer::get_progress () const
Definition at line 53 of file action.cpp.
{
     return 1.0f - (this->time_left * 1.0f / this->interval);
 }
References interval, and time_left.
Referenced by openage::TrainAction::get_progress(), and openage::ResearchAction::get_progress().
get_time_left()
unsigned int openage::IntervalTimer::get_time_left () const
Returns the time until the next trigger.
Definition at line 49 of file action.cpp.
{
     return this->time_left;
 }
References time_left.
get_triggers()
int openage::IntervalTimer::get_triggers () const inline
Returns the number of intervals passed.
Definition at line 63 of file action.h.
 { return this->triggers; }
References triggers.
has_triggers()
bool openage::IntervalTimer::has_triggers () const
Returns true if at least one interval has passed.
Definition at line 57 of file action.cpp.
{
     return this->triggers > 0;
 }
References triggers.
set_interval()
void openage::IntervalTimer::set_interval (unsigned int interval) inline
Definition at line 67 of file action.h.
 { this->interval = interval; }
References interval.
skip_to_trigger()
void openage::IntervalTimer::skip_to_trigger ()
Definition at line 32 of file action.cpp.
{
     this->time_left = 0;
 }
References time_left.
update()
bool openage::IntervalTimer::update (unsigned int time)
Definition at line 36 of file action.cpp.
{
     if (this->triggers == this->max_triggers) {
         return false;
     } else if (this->time_left > time) {
         this->time_left -= time;
         return false;
     } else {
         this->time_left += this->interval - time;
         this->triggers += 1;
         return true;
     }
 }
References interval, max_triggers, time_left, and triggers.
Referenced by openage::TrainAction::update(), openage::ResearchAction::update(), openage::RepairAction::update_in_range(), openage::AttackAction::update_in_range(), and openage::HealAction::update_in_range().
Member Data Documentation
interval
unsigned int openage::IntervalTimer::interval private
Definition at line 71 of file action.h.
Referenced by get_interval(), get_progress(), IntervalTimer(), set_interval(), and update().
max_triggers
int openage::IntervalTimer::max_triggers private
Definition at line 73 of file action.h.
Referenced by finished(), and update().
time_left
unsigned int openage::IntervalTimer::time_left private
Definition at line 75 of file action.h.
Referenced by get_progress(), get_time_left(), skip_to_trigger(), and update().
triggers
int openage::IntervalTimer::triggers private
Definition at line 77 of file action.h.
Referenced by finished(), get_triggers(), has_triggers(), and update().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/action.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/action.cpp