openage: openage::util::compress::LZXDStream Class Reference
openage::util::compress::LZXDStream Class Reference
Public Member Functions
LZXDStream (read_callback_t callback, unsigned int window_bits, unsigned int reset_interval)
~LZXDStream ()
LZXDStream (const LZXDStream &other)=delete
LZXDStream (LZXDStream &&other)=delete
LZXDStream & operator= (const LZXDStream &other)=delete
LZXDStream & operator= (LZXDStream &&other)=delete
unsigned decompress_next_frame (unsigned char *output_buf)
void reset_state ()
Public Attributes
ssize_t output_pos
unsigned char * window
unsigned int window_size
unsigned int window_posn
unsigned int frame_posn
unsigned int frame
unsigned int reset_interval
unsigned int R0
unsigned int R1
unsigned int R2
unsigned int block_length
unsigned int block_remaining
signed int e8_magic
bool header_read
unsigned char block_type
unsigned char posn_slots
BitStream< 4096 > bits
HuffmanTable< LZX_PRETREE_MAXSYMBOLS, LZX_PRETREE_TABLEBITS > htpre
HuffmanTable< LZX_MAINTREE_MAXSYMBOLS, LZX_MAINTREE_TABLEBITS > htmain
HuffmanTable< LZX_LENGTH_MAXSYMBOLS, LZX_LENGTH_TABLEBITS, true > htlength
HuffmanTable< LZX_ALIGNED_MAXSYMBOLS, LZX_ALIGNED_TABLEBITS > htaligned
Private Member Functions
void init_next_block ()
int decode_symbol_from_verbatim_block ()
int decode_symbol_from_aligned_block ()
unsigned int read_data_from_uncompressed_block (unsigned int size)
void postprocess_intel_e8 (unsigned char *output_buf, int frame_size)
Detailed Description
Definition at line 155 of file lzxd.cpp.
Constructor & Destructor Documentation
LZXDStream() [1/3]
openage::util::compress::LZXDStream::LZXDStream (read_callback_t callback, unsigned int window_bits, unsigned int reset_interval)
See the doc for LZXDecompressor::LZXDecompressor in lzxd.h
Definition at line 415 of file lzxd.cpp.
         :
         output_pos{0},
         window_size{(unsigned int) 1 << window_bits},
         window_posn{0},
         frame_posn{0},
         frame{0},
         reset_interval{reset_interval},
         bits{read_callback},
         htpre{this},
         htmain{this},
         htlength{this},
         htaligned{this} {
     // LZX supports window sizes of 2^15 (32 KiB) through 2^21 (2 MiB)
     if (window_bits < 15 || window_bits > 21) {
         throw Error(MSG(err) << "Bad requested window size: 2^" << window_bits << " bytes");
     }
     // allocate decompression window
     this->window = new unsigned char[window_size];
     // window bits:    15  16  17  18  19  20  21
     // position slots: 30  32  34  36  38  42  50
     this->posn_slots = 2 * window_bits;
     if (window_bits == 21) {
         this->posn_slots = 50;
     }
     if (window_bits == 20) {
         this->posn_slots = 42;
     }
     this->reset_state();
 }
~LZXDStream()
openage::util::compress::LZXDStream::~LZXDStream ()
Definition at line 453 of file lzxd.cpp.
{
     delete[] this->window;
 }
References window.
LZXDStream() [2/3]
openage::util::compress::LZXDStream::LZXDStream (const LZXDStream & other) delete
LZXDStream() [3/3]
openage::util::compress::LZXDStream::LZXDStream (LZXDStream && other) delete
Member Function Documentation
decode_symbol_from_aligned_block()
int openage::util::compress::LZXDStream::decode_symbol_from_aligned_block () private
Decodes one symbol from the current aligned block. Returns the number of bytes that were decoded. The bytes are written to the window, and window_posn is advanced.
Definition at line 617 of file lzxd.cpp.
{
     int main_element = this->htmain.read_sym();
     if (main_element < (int) LZX_NUM_CHARS) {
         // literal: 0 to LZX_NUM_CHARS - 1
         window[this->window_posn++] = main_element;
         return 1;
     }
     // match: LZX_NUM_CHARS + ((slot<<3) | length_header (3 bits))
     main_element -= LZX_NUM_CHARS;
     // get match length
     int match_length = main_element & LZX_NUM_PRIMARY_LENGTHS;
     if (match_length == LZX_NUM_PRIMARY_LENGTHS) {
         if (unlikely(this->htlength.is_empty)) {
             throw Error(MSG(err) << "decrunch: length symbol needed byt tree is empty");
         }
         int length_footer = this->htlength.read_sym();
         match_length += length_footer;
     }
     match_length += LZX_MIN_MATCH;
     // get match offset
     unsigned match_offset = (main_element >> 3);
     switch (match_offset) {
     case 0:
         match_offset = this->R0;
         break;
     case 1:
         match_offset = this->R1;
         this->R1 = this->R0;
         this->R0 = match_offset;
         break;
     case 2:
         match_offset = this->R2;
         this->R2 = this->R0;
         this->R0 = match_offset;
         break;
     default:
         int extra = extra_bits[match_offset];
         match_offset = position_base[match_offset] - 2;
         if (extra > 3) {
             // verbatim and aligned bits
             extra -= 3;
             int verbatim_bits = this->bits.read_bits(extra);
             match_offset += (verbatim_bits << 3);
             int aligned_bits = this->htaligned.read_sym();
             match_offset += aligned_bits;
         }
         else if (extra == 3) {
             // aligned bits only
             int aligned_bits = this->htaligned.read_sym();
             match_offset += aligned_bits;
         }
         else if (extra > 0) {
             // extra==1, extra==2
             // verbatim bits only
             int verbatim_bits = this->bits.read_bits(extra);
             match_offset += verbatim_bits;
         }
         else {
             // extra == 0
             // ??? not defined in LZX specification!
             match_offset = 1;
         }
         // update repeated offset LRU queue
         this->R2 = this->R1;
         this->R1 = this->R0;
         this->R0 = match_offset;
     }
     if (unlikely((this->window_posn + match_length) > this->window_size)) {
         throw Error(MSG(err) << "decrunch: match ran over window wrap");
     }
     // copy match
     unsigned char *rundest = &window[this->window_posn];
     int i = match_length;
     // does match offset wrap the window?
     if (match_offset > this->window_posn) {
         // j = length from match offset to end of window
         int j = match_offset - this->window_posn;
         if (unlikely(j > (int) this->window_size)) {
             throw Error(MSG(err) << "decrunch: match offset beyond window boundaries");
         }
         unsigned char *runsrc = &window[this->window_size - j];
         if (j < i) {
             // if match goes over the window edge, do two copy runs
             i -= j;
             while (j-- > 0) {
                 *rundest++ = *runsrc++;
             }
             runsrc = window;
         }
         while (i-- > 0) {
             *rundest++ = *runsrc++;
         }
     } else {
         unsigned char *runsrc = rundest - match_offset;
         while (i-- > 0) {
             *rundest++ = *runsrc++;
         }
     }
     this->window_posn += match_length;
     return               match_length;
 }
References bits, openage::log::err(), openage::util::compress::extra_bits, htaligned, htlength, htmain, openage::util::compress::HuffmanTable< maxsymbols_p, tablebits_p, allow_empty >::is_empty, openage::util::compress::LZX_MIN_MATCH, openage::util::compress::LZX_NUM_CHARS, openage::util::compress::LZX_NUM_PRIMARY_LENGTHS, MSG, openage::util::compress::position_base, R0, R1, R2, openage::util::compress::BitStream< inbuf_size >::read_bits(), openage::util::compress::HuffmanTable< maxsymbols_p, tablebits_p, allow_empty >::read_sym(), unlikely, window, window_posn, and window_size.
Referenced by decompress_next_frame().
decode_symbol_from_verbatim_block()
int openage::util::compress::LZXDStream::decode_symbol_from_verbatim_block () private
Decodes one symbol from the current verbatim block. Returns the number of bytes that were decoded. The bytes are written to the window, and window_posn is advanced.
Definition at line 526 of file lzxd.cpp.
{
     int main_element = this->htmain.read_sym();
     if (main_element < (int) LZX_NUM_CHARS) {
         // literal: 0 to LZX_NUM_CHARS-1
         window[this->window_posn++] = main_element;
         return 1;
     }
     // match: LZX_NUM_CHARS + ((slot<<3) | length_header (3 bits))
     main_element -= LZX_NUM_CHARS;
     // get match length
     int match_length = main_element & LZX_NUM_PRIMARY_LENGTHS;
     if (match_length == LZX_NUM_PRIMARY_LENGTHS) {
         if (unlikely(this->htlength.is_empty)) {
             throw Error(MSG(err) << "decrunch: LENGTH symbol needed byt tree is empty");
         }
         int length_footer = this->htlength.read_sym();
         match_length += length_footer;
     }
     match_length += LZX_MIN_MATCH;
     // get match offset
     unsigned match_offset = (main_element >> 3);
     switch (match_offset) {
     case 0:
         match_offset = this->R0;
         break;
     case 1:
         match_offset = this->R1;
         this->R1 = this->R0;
         this->R0 = match_offset;
         break;
     case 2:
         match_offset = this->R2;
         this->R2 = this->R0;
         this->R0 = match_offset;
         break;
     case 3:
         match_offset = 1;
         this->R2 = this->R1;
         this->R1 = this->R0;
         this->R0 = match_offset;
         break;
     default:
         int extra = extra_bits[match_offset];
         int verbatim_bits = this->bits.read_bits(extra);
         match_offset = position_base[match_offset] - 2 + verbatim_bits;
         this->R2 = this->R1;
         this->R1 = this->R0;
         this->R0 = match_offset;
     }
     if (unlikely((this->window_posn + match_length) > this->window_size)) {
         throw Error(MSG(err) << "decrunch: match ran over window wrap");
     }
     // copy match
     unsigned char *rundest = &window[this->window_posn];
     int i = match_length;
     // does match offset wrap the window?
     if (match_offset > this->window_posn) {
         // j = length from match offset to end of window
         int j = match_offset - this->window_posn;
         if (unlikely(j > (int) this->window_size)) {
             throw Error(MSG(err) << "decrunch: match offset beyond window boundaries");
         }
         unsigned char *runsrc = &window[this->window_size - j];
         if (j < i) {
             // if match goes over the window edge, do two copy runs
             i -= j;
             while (j-- > 0) {
                 *rundest++ = *runsrc++;
             }
             runsrc = window;
         }
         while (i-- > 0) {
             *rundest++ = *runsrc++;
         }
     } else {
         unsigned char *runsrc = rundest - match_offset;
         while (i-- > 0) {
             *rundest++ = *runsrc++;
         }
     }
     this->window_posn += match_length;
     return               match_length;
 }
References bits, openage::log::err(), openage::util::compress::extra_bits, htlength, htmain, openage::util::compress::HuffmanTable< maxsymbols_p, tablebits_p, allow_empty >::is_empty, openage::util::compress::LZX_MIN_MATCH, openage::util::compress::LZX_NUM_CHARS, openage::util::compress::LZX_NUM_PRIMARY_LENGTHS, MSG, openage::util::compress::position_base, R0, R1, R2, openage::util::compress::BitStream< inbuf_size >::read_bits(), openage::util::compress::HuffmanTable< maxsymbols_p, tablebits_p, allow_empty >::read_sym(), unlikely, window, window_posn, and window_size.
Referenced by decompress_next_frame().
decompress_next_frame()
unsigned openage::util::compress::LZXDStream::decompress_next_frame (unsigned char * output_buf)
See the doc for LZXDecompressor::decompress_next_frame in lzxd.h
Definition at line 740 of file lzxd.cpp.
{
     if (unlikely(this->bits.eof)) {
         return 0;
     }
     // have we reached the reset interval? (if there is one?)
     if (unlikely(this->reset_interval && ((this->frame % this->reset_interval) == 0))) {
         if (unlikely(this->block_remaining)) {
             throw Error(MSG(err) << this->block_remaining << " bytes remaining at reset interval");
         }
         // re-read the intel header and reset the huffman lengths
         reset_state();
     }
     // read header if necessary (after initializing or resetting the stream).
     if (unlikely(!this->header_read)) {
         // the first bit of the header indicates whether the e8_magic field is present.
         if (this->bits.read_bits(1)) {
             // read e8_magic (32 bits).
             this->e8_magic = this->bits.read_bits(16) << 16;
             this->e8_magic |= this->bits.read_bits(16);
         } else {
             // e8_magic is zero.
             this->e8_magic = 0;
         }
         this->header_read = true;
     }
     // counter that stores the amount of data that has been accumulated for this frame.
     unsigned int frame_size = 0;
     if (unlikely(this->frame_posn - this->window_posn)) {
         // Warning: untested code.
         // In theory, a symbol may have overshot the last frame's boundary.
         // If it did, the amount of data would be available in frame_size.
         throw Error(MSG(err) <<
             "untested code path: extra frame data available from last frame. " <<
             "frame size = " << this->frame_posn - this->window_posn);
     }
     // decode symbols until we have enough data for the frame.
     while (frame_size < LZX_FRAME_SIZE) {
         // initialise next block, if one is needed
         if (unlikely(this->block_remaining == 0)) {
             if (this->bits.eof) {
                 // EOF of input stream was reached at a block boundary.
                 // there are no more blocks. Return the frame as-is.
                 break;
             }
             this->init_next_block();
         }
         unsigned int symbol_size;
         switch (this->block_type) {
         case LZX_BLOCKTYPE_VERBATIM:
             symbol_size = this->decode_symbol_from_verbatim_block();
             break;
         case LZX_BLOCKTYPE_ALIGNED:
             symbol_size = this->decode_symbol_from_aligned_block();
             break;
         case LZX_BLOCKTYPE_UNCOMPRESSED:
             symbol_size = this->read_data_from_uncompressed_block(std::min(this->block_remaining, LZX_FRAME_SIZE - frame_size));
             break;
         default:
             throw Error(MSG(err) << "this->blocktype neither verbatim nor aligned");
         }
         if (unlikely(symbol_size > this->block_remaining)) {
             // we overshot the block boundary.
             throw Error(MSG(err) << "decrunch: overrun went past end of block by " << symbol_size - this->block_remaining);
         }
         this->block_remaining -= symbol_size;
         frame_size += symbol_size;
     }
     if (unlikely(frame_size > LZX_FRAME_SIZE)) {
         // Warning: untested code.
         // In theory, a symbol may overshoot a frame boundary. If it does, the data
         // will get re-used in the next frame, but we have to limit frame_size to LZX_FRAME_SIZE.
         throw Error(MSG(err) << "untested code path: frame_size > LZX_FRAME_SIZE");
         frame_size = LZX_FRAME_SIZE;
     }
     // streams don't extend over frame boundaries
     if (unlikely(this->window_posn != this->frame_posn + frame_size)) {
         throw Error(MSG(err) << "decrunch: decode beyond output frame limits");
     }
     // copy frame data to the output buffer
     memcpy(output_buf, &this->window[this->frame_posn], frame_size);
     // intel e8-postprocess the frame data
     this->postprocess_intel_e8(output_buf, frame_size);
     // frame boundary; re-align the bitstream, if it's currently in bitstream mode.
     this->bits.align_if_in_bitstream_mode();
     // advance frame start position
     this->frame_posn += frame_size;
     // wrap window / frame position pointers
     if (this->window_posn == this->window_size) {
         window_posn = 0;
     }
     if (this->frame_posn == this->window_size) {
         this->frame_posn = 0;
     }
     this->output_pos += frame_size;
     this->frame++;
     return frame_size;
 }
References openage::util::compress::BitStream< inbuf_size >::align_if_in_bitstream_mode(), bits, block_remaining, block_type, decode_symbol_from_aligned_block(), decode_symbol_from_verbatim_block(), e8_magic, openage::util::compress::BitStream< inbuf_size >::eof, openage::log::err(), frame, frame_posn, header_read, init_next_block(), openage::util::compress::LZX_BLOCKTYPE_ALIGNED, openage::util::compress::LZX_BLOCKTYPE_UNCOMPRESSED, openage::util::compress::LZX_BLOCKTYPE_VERBATIM, openage::util::compress::LZX_FRAME_SIZE, std::min(), MSG, output_pos, postprocess_intel_e8(), openage::util::compress::BitStream< inbuf_size >::read_bits(), read_data_from_uncompressed_block(), reset_interval, reset_state(), unlikely, window, window_posn, and window_size.
Referenced by openage::util::compress::LZXDecompressor::decompress_next_frame().
init_next_block()
void openage::util::compress::LZXDStream::init_next_block () private
Initializes the next block.
Definition at line 477 of file lzxd.cpp.
{
     // we might still be in bytstream mode from the previous block.
     this->bits.switch_to_bitstream_mode();
     // read block type (3 bits) and block length (24 bits)
     this->block_type = this->bits.read_bits(3);
     this->block_length = this->bits.read_bits(16) << 8;
     this->block_length |= this->bits.read_bits(8);
     this->block_remaining = this->block_length;
     // read individual block headers
     switch (this->block_type) {
     case LZX_BLOCKTYPE_ALIGNED:
         // read lengths of and build aligned huffman decoding tree
         for (int i = 0; i < 8; i++) {
             this->htaligned.len[i] = this->bits.read_bits(3);
         }
         this->htaligned.make_decode_table();
         // Falls through.
         // Rest of aligned header is same as verbatim
     case LZX_BLOCKTYPE_VERBATIM:
         // read lengths of and build main huffman decoding tree
         this->htmain.read_lengths(0, 256);
         this->htmain.read_lengths(256, LZX_NUM_CHARS + (this->posn_slots << 3));
         this->htmain.make_decode_table();
         // read lengths of and build lengths huffman decoding tree
         this->htlength.read_lengths(0, LZX_NUM_SECONDARY_LENGTHS);
         this->htlength.is_empty = false;
         this->htlength.make_decode_table();
         break;
     case LZX_BLOCKTYPE_UNCOMPRESSED:
         this->bits.switch_to_bytestream_mode();
         // read 12 bytes of stored R0 / R1 / R2 values
         this->R0 = this->bits.read_4bytes_le();
         this->R1 = this->bits.read_4bytes_le();
         this->R2 = this->bits.read_4bytes_le();
         break;
     default:
         throw Error(MSG(err) << "decrunch: bad block type " << this->block_type);
     }
 }
References bits, block_length, block_remaining, block_type, openage::log::err(), htaligned, htlength, htmain, openage::util::compress::HuffmanTable< maxsymbols_p, tablebits_p, allow_empty >::is_empty, openage::util::compress::HuffmanTable< maxsymbols_p, tablebits_p, allow_empty >::len, openage::util::compress::LZX_BLOCKTYPE_ALIGNED, openage::util::compress::LZX_BLOCKTYPE_UNCOMPRESSED, openage::util::compress::LZX_BLOCKTYPE_VERBATIM, openage::util::compress::HuffmanTable< maxsymbols_p, tablebits_p, allow_empty >::make_decode_table(), MSG, posn_slots, R0, R1, R2, openage::util::compress::BitStream< inbuf_size >::read_4bytes_le(), openage::util::compress::BitStream< inbuf_size >::read_bits(), openage::util::compress::HuffmanTable< maxsymbols_p, tablebits_p, allow_empty >::read_lengths(), openage::util::compress::BitStream< inbuf_size >::switch_to_bitstream_mode(), and openage::util::compress::BitStream< inbuf_size >::switch_to_bytestream_mode().
Referenced by decompress_next_frame().
operator=() [1/2]
LZXDStream& openage::util::compress::LZXDStream::operator= (const LZXDStream & other) delete
operator=() [2/2]
LZXDStream& openage::util::compress::LZXDStream::operator= (LZXDStream && other) delete
postprocess_intel_e8()
void openage::util::compress::LZXDStream::postprocess_intel_e8 (unsigned char * output_buf, int frame_size) private
Postprocesses the a frame's decoded data with E8 decoding.
Before compressing data, LZX pre-processes it by translating the four bytes following 0xE8-bytes; this optimizes intel x86 machine code.
What the hell, Microsoft?
Definition at line 863 of file lzxd.cpp.
{
     if (this->e8_magic == 0) {
         // this lzx stream is e8-processing-free
         return;
     }
     if (this->frame >= 32768) {
         // in frames >= 32768 (>= 1GiB of plain data) there's no e8 processing (WTF WHY?)
         return;
     }
     // search the block for occurances of '0xe8'
     // the last 10 bytes of the frame are not e8-handled, because reasons.
     for (int pos = 0; pos < frame_size - 10; pos++) {
         bool is_e8 = (buf[pos] == 0xe8);
         if (!is_e8) {
             continue;
         }
         // we've found an E8 sequence.
         // the next 4 bytes shall be translated.
         int file_pos = pos + this->output_pos;
         // read the next 4 bytes as little endian
         int32_t abs_offset =
             (buf[pos + 1] <<  0) |
             (buf[pos + 2] <<  8) |
             (buf[pos + 3] << 16) |
             (buf[pos + 4] << 24);
         if (abs_offset >= -file_pos && abs_offset < this->e8_magic) {
             int32_t rel_offset;
             if (abs_offset >= 0) {
                 rel_offset = abs_offset - file_pos;
             } else {
                 rel_offset = abs_offset + this->e8_magic;
             }
             // write the next 4 bytes as little endian
             buf[pos + 1] = (unsigned char) (rel_offset >>  0);
             buf[pos + 2] = (unsigned char) (rel_offset >>  8);
             buf[pos + 3] = (unsigned char) (rel_offset >> 16);
             buf[pos + 4] = (unsigned char) (rel_offset >> 24);
         }
         // skip the next four bytes (they are what we just translated).
         pos += 4;
     }
 }
References e8_magic, frame, and output_pos.
Referenced by decompress_next_frame().
read_data_from_uncompressed_block()
unsigned int openage::util::compress::LZXDStream::read_data_from_uncompressed_block (unsigned int size) private
Reads the given amount of bytes from the current uncompressed block. Returns its argument (the number of bytes that were read). The bytes are written to the window, and window_posn is advanced.
Definition at line 727 of file lzxd.cpp.
{
     unsigned int remaining = size;
     while (remaining) {
         unsigned int amount = this->bits.read_bytes(&this->window[this->window_posn], remaining);
         this->window_posn += amount;
         remaining -= amount;
     }
     return size;
 }
References bits, openage::util::compress::BitStream< inbuf_size >::read_bytes(), window, and window_posn.
Referenced by decompress_next_frame().
reset_state()
void openage::util::compress::LZXDStream::reset_state ()
Definition at line 458 of file lzxd.cpp.
{
     this->R0 = 1;
     this->R1 = 1;
     this->R2 = 1;
     this->header_read = false;
     this->block_remaining = 0;
     this->block_type = LZX_BLOCKTYPE_INVALID;
     // initialise tables to 0 (because deltas will be applied to them)
     for (unsigned int i = 0; i < LZX_MAINTREE_MAXSYMBOLS; i++) {
         this->htmain.len[i] = 0;
     }
     for (unsigned int i = 0; i < LZX_LENGTH_MAXSYMBOLS; i++) {
         this->htlength.len[i] = 0;
     }
 }
References block_remaining, block_type, header_read, htlength, htmain, openage::util::compress::HuffmanTable< maxsymbols_p, tablebits_p, allow_empty >::len, openage::util::compress::LZX_BLOCKTYPE_INVALID, openage::util::compress::LZX_LENGTH_MAXSYMBOLS, openage::util::compress::LZX_MAINTREE_MAXSYMBOLS, R0, R1, and R2.
Referenced by decompress_next_frame().
Member Data Documentation
bits
BitStream<4096> openage::util::compress::LZXDStream::bits
Definition at line 179 of file lzxd.cpp.
Referenced by decode_symbol_from_aligned_block(), decode_symbol_from_verbatim_block(), decompress_next_frame(), init_next_block(), and read_data_from_uncompressed_block().
block_length
unsigned int openage::util::compress::LZXDStream::block_length
Definition at line 167 of file lzxd.cpp.
Referenced by init_next_block().
block_remaining
unsigned int openage::util::compress::LZXDStream::block_remaining
Definition at line 168 of file lzxd.cpp.
Referenced by decompress_next_frame(), init_next_block(), and reset_state().
block_type
unsigned char openage::util::compress::LZXDStream::block_type
Definition at line 175 of file lzxd.cpp.
Referenced by decompress_next_frame(), init_next_block(), and reset_state().
e8_magic
signed int openage::util::compress::LZXDStream::e8_magic
Definition at line 170 of file lzxd.cpp.
Referenced by decompress_next_frame(), and postprocess_intel_e8().
frame
unsigned int openage::util::compress::LZXDStream::frame
Definition at line 163 of file lzxd.cpp.
Referenced by decompress_next_frame(), and postprocess_intel_e8().
frame_posn
unsigned int openage::util::compress::LZXDStream::frame_posn
Definition at line 162 of file lzxd.cpp.
Referenced by decompress_next_frame().
header_read
bool openage::util::compress::LZXDStream::header_read
Definition at line 173 of file lzxd.cpp.
Referenced by decompress_next_frame(), and reset_state().
htaligned
HuffmanTable<LZX_ALIGNED_MAXSYMBOLS, LZX_ALIGNED_TABLEBITS> openage::util::compress::LZXDStream::htaligned
Definition at line 185 of file lzxd.cpp.
Referenced by decode_symbol_from_aligned_block(), and init_next_block().
htlength
HuffmanTable<LZX_LENGTH_MAXSYMBOLS, LZX_LENGTH_TABLEBITS, true> openage::util::compress::LZXDStream::htlength
Definition at line 184 of file lzxd.cpp.
Referenced by decode_symbol_from_aligned_block(), decode_symbol_from_verbatim_block(), init_next_block(), and reset_state().
htmain
HuffmanTable<LZX_MAINTREE_MAXSYMBOLS, LZX_MAINTREE_TABLEBITS> openage::util::compress::LZXDStream::htmain
Definition at line 183 of file lzxd.cpp.
Referenced by decode_symbol_from_aligned_block(), decode_symbol_from_verbatim_block(), init_next_block(), and reset_state().
htpre
HuffmanTable<LZX_PRETREE_MAXSYMBOLS, LZX_PRETREE_TABLEBITS> openage::util::compress::LZXDStream::htpre
Definition at line 182 of file lzxd.cpp.
output_pos
ssize_t openage::util::compress::LZXDStream::output_pos
Definition at line 157 of file lzxd.cpp.
Referenced by decompress_next_frame(), and postprocess_intel_e8().
posn_slots
unsigned char openage::util::compress::LZXDStream::posn_slots
Definition at line 176 of file lzxd.cpp.
Referenced by init_next_block().
R0
unsigned int openage::util::compress::LZXDStream::R0
Definition at line 166 of file lzxd.cpp.
Referenced by decode_symbol_from_aligned_block(), decode_symbol_from_verbatim_block(), init_next_block(), and reset_state().
R1
unsigned int openage::util::compress::LZXDStream::R1
Definition at line 166 of file lzxd.cpp.
Referenced by decode_symbol_from_aligned_block(), decode_symbol_from_verbatim_block(), init_next_block(), and reset_state().
R2
unsigned int openage::util::compress::LZXDStream::R2
Definition at line 166 of file lzxd.cpp.
Referenced by decode_symbol_from_aligned_block(), decode_symbol_from_verbatim_block(), init_next_block(), and reset_state().
reset_interval
unsigned int openage::util::compress::LZXDStream::reset_interval
Definition at line 164 of file lzxd.cpp.
Referenced by decompress_next_frame().
window
unsigned char* openage::util::compress::LZXDStream::window
Definition at line 159 of file lzxd.cpp.
Referenced by decode_symbol_from_aligned_block(), decode_symbol_from_verbatim_block(), decompress_next_frame(), read_data_from_uncompressed_block(), and ~LZXDStream().
window_posn
unsigned int openage::util::compress::LZXDStream::window_posn
Definition at line 161 of file lzxd.cpp.
Referenced by decode_symbol_from_aligned_block(), decode_symbol_from_verbatim_block(), decompress_next_frame(), and read_data_from_uncompressed_block().
window_size
unsigned int openage::util::compress::LZXDStream::window_size
Definition at line 160 of file lzxd.cpp.
Referenced by decode_symbol_from_aligned_block(), decode_symbol_from_verbatim_block(), and decompress_next_frame().
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/compress/lzxd.cpp