openage: openage::renderer::vulkan::VlkLoader Class Reference
openage::renderer::vulkan::VlkLoader Class Reference
A class for dynamically loading Vulkan extension functions.
#include <loader.h>
Public Member Functions
VlkLoader ()
void init (VkInstance)
Initialize this loader for the given Vulkan instance.
VkResult vkCreateDebugReportCallbackEXT (VkInstance instance, const VkDebugReportCallbackCreateInfoEXT *pCreateInfo, const VkAllocationCallbacks *pAllocator, VkDebugReportCallbackEXT *pCallback)
Part of VK_EXT_debug_report, allows setting a callback for debug events.
void vkDestroyDebugReportCallbackEXT (VkInstance instance, VkDebugReportCallbackEXT callback, const VkAllocationCallbacks *pAllocator)
Part of VK_EXT_debug_report, destroys the debug callback object.
Private Attributes
PFN_vkCreateDebugReportCallbackEXT pCreateDebugReportCallbackEXT
PFN_vkDestroyDebugReportCallbackEXT pDestroyDebugReportCallbackEXT
bool inited
Detailed Description
A class for dynamically loading Vulkan extension functions.
Definition at line 13 of file loader.h.
Constructor & Destructor Documentation
VlkLoader()
openage::renderer::vulkan::VlkLoader::VlkLoader ()
Definition at line 12 of file loader.cpp.
     : inited(false) {}
Member Function Documentation
init()
void openage::renderer::vulkan::VlkLoader::init (VkInstance instance)
Initialize this loader for the given Vulkan instance.
Definition at line 15 of file loader.cpp.
{
     #ifndef NDEBUG
     this->pCreateDebugReportCallbackEXT = PFN_vkCreateDebugReportCallbackEXT(vkGetInstanceProcAddr(instance, "vkCreateDebugReportCallbackEXT"));
     this->pDestroyDebugReportCallbackEXT = PFN_vkDestroyDebugReportCallbackEXT(vkGetInstanceProcAddr(instance, "vkDestroyDebugReportCallbackEXT"));
     #endif
     this->inited = true;
 }
References inited, pCreateDebugReportCallbackEXT, and pDestroyDebugReportCallbackEXT.
Referenced by openage::renderer::vulkan::VlkWindow::VlkWindow().
vkCreateDebugReportCallbackEXT()
VkResult openage::renderer::vulkan::VlkLoader::vkCreateDebugReportCallbackEXT (VkInstance instance, const VkDebugReportCallbackCreateInfoEXT * pCreateInfo, const VkAllocationCallbacks * pAllocator, VkDebugReportCallbackEXT * pCallback)
Part of VK_EXT_debug_report, allows setting a callback for debug events.
Definition at line 25 of file loader.cpp.
   {
     if (!this->inited) {
         throw Error(MSG(err) << "Tried to request function from Vulkan extension loader before initializing it.");
     }
     if (this->pCreateDebugReportCallbackEXT != nullptr) {
         return this->pCreateDebugReportCallbackEXT(instance, pCreateInfo, pAllocator, pCallback);
     }
     return VK_ERROR_EXTENSION_NOT_PRESENT;
 }
References openage::log::err(), inited, MSG, and pCreateDebugReportCallbackEXT.
Referenced by openage::renderer::vulkan::VlkWindow::VlkWindow().
vkDestroyDebugReportCallbackEXT()
void openage::renderer::vulkan::VlkLoader::vkDestroyDebugReportCallbackEXT (VkInstance instance, VkDebugReportCallbackEXT callback, const VkAllocationCallbacks * pAllocator)
Part of VK_EXT_debug_report, destroys the debug callback object.
Definition at line 42 of file loader.cpp.
   {
     if (!this->inited) {
         throw Error(MSG(err) << "Tried to request function from Vulkan extension loader before initializing it.");
     }
     if (this->pDestroyDebugReportCallbackEXT != nullptr) {
         this->pDestroyDebugReportCallbackEXT(instance, callback, pAllocator);
     }
 }
References openage::log::err(), inited, MSG, and pDestroyDebugReportCallbackEXT.
Referenced by openage::renderer::vulkan::VlkWindow::~VlkWindow().
Member Data Documentation
inited
bool openage::renderer::vulkan::VlkLoader::inited private
Definition at line 19 of file loader.h.
Referenced by init(), vkCreateDebugReportCallbackEXT(), and vkDestroyDebugReportCallbackEXT().
pCreateDebugReportCallbackEXT
PFN_vkCreateDebugReportCallbackEXT openage::renderer::vulkan::VlkLoader::pCreateDebugReportCallbackEXT private
Definition at line 15 of file loader.h.
Referenced by init(), and vkCreateDebugReportCallbackEXT().
pDestroyDebugReportCallbackEXT
PFN_vkDestroyDebugReportCallbackEXT openage::renderer::vulkan::VlkLoader::pDestroyDebugReportCallbackEXT private
Definition at line 16 of file loader.h.
Referenced by init(), and vkDestroyDebugReportCallbackEXT().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/vulkan/loader.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/vulkan/loader.cpp