openage: openage::rng::RNG Class Reference
openage::rng::RNG Class Reference
#include <rng.h>
Public Member Functions
RNG (uint64_t seed)
RNG (const void *data, size_t count)
RNG (const std::string &instr)
RNG (std::istream &instream)
void seed (uint64_t val)
void seed (const void *data, size_t count)
uint64_t random ()
uint64_t operator() ()
uint64_t random_range (uint64_t lower, uint64_t upper)
bool probability (double prob)
double real ()
double real_range (double lower, double upper)
void fill (uint64_t *data, size_t len)
void fill_real (double *data, size_t len)
void discard (size_t num_discard)
std::ostream & to_stream (std::ostream &out) const
std::istream & from_stream (std::istream &in)
std::string to_string () const
void from_string (const std::string &instr)
Static Public Member Functions
static constexpr uint64_t max ()
static constexpr uint64_t min ()
Private Attributes
uint64_t state [2]
Static Private Attributes
static constexpr size_t discard_on_seed = 50
Detailed Description
This class holds an xorshift128+ rng, as well as utility generator functions
Definition at line 16 of file rng.h.
Constructor & Destructor Documentation
RNG() [1/4]
openage::rng::RNG::RNG (uint64_t seed)
Creates an rng and seeds it with the 64 bit seed
Parameters
seed The inital seed for the following number generation.
Definition at line 33 of file rng.cpp.
                     {
     this->seed(v1);
 }
References seed().
RNG() [2/4]
openage::rng::RNG::RNG (const void * data, size_t count)
Initializes the rng using data from the buffer pointed to by data
Parameters
data The buffer that contains data for seeding the rng
count The number of bytes in the buffer
Exceptions
Error if 0 bytes are passed
Definition at line 38 of file rng.cpp.
{
     this->seed(data, len);
 }
References seed().
RNG() [3/4]
openage::rng::RNG::RNG (const std::string & instr)
Reads the rng in from the passed string. If you want to use the data in the string as a seed, then pass the c_str() to rng(const void*, size_t).
Parameters
instr The string from which the rng is serialized
Exceptions
Error if the rng cannot be read from the string
Definition at line 43 of file rng.cpp.
{
     this->from_string(instr);
 }
References from_string().
RNG() [4/4]
openage::rng::RNG::RNG (std::istream & instream)
Reads the rng in from the passed std::istream. This serializes the rng, and does not use the data as a random seed.
Parameters
instream The input stream for serializing the rng
Exceptions
Error if stream initialization fails
Definition at line 48 of file rng.cpp.
{
     this->from_stream(instream);
 }
References from_stream().
Member Function Documentation
discard()
void openage::rng::RNG::discard (size_t num_discard)
Discards num_discard numbers from the generator.
Definition at line 130 of file rng.cpp.
{
     act_fill<uint64_t>(
         nullptr, this->state, len,
         [](uint64_t, uint64_t *, size_t) {}
     );
 }
References state.
Referenced by seed().
fill()
void openage::rng::RNG::fill (uint64_t * data, size_t len)
Effeciently fills a chunk of 64 bit integers. Gives identical result to calling random() len times
Parameters
data The buffer to be filled with random numbers
len the length of the data
Definition at line 120 of file rng.cpp.
{
     act_fill<>(
         dat, this->state, len,
         [](uint64_t v, uint64_t *d, size_t i) {
             d[i] = v;
         }
     );
 }
References state.
Referenced by openage.convert.colortable.ColorTable::__init__(), and openage::rng::tests::fill().
fill_real()
void openage::rng::RNG::fill_real (double * data, size_t len)
Fills an array of doubles with values in [0, 1) Gives identical results as real() but more effeciently
Parameters
data A pointer t0 the buffer of doubles
len The length of the buffer
Definition at line 138 of file rng.cpp.
{
     act_fill(
         dat, this->state, len,
         [](double v, double *d, size_t i) {
             d[i] = v / RNG::max();
         }
     );
 }
References openage::rng::act_fill(), max(), and state.
Referenced by openage::rng::tests::fill_real().
from_stream()
std::istream & openage::rng::RNG::from_stream (std::istream & in)
Reads the rng state from a stream
Exceptions
Error if reading the stream fails
Definition at line 157 of file rng.cpp.
{
     if ((in >> this->state[0]).good() &&
         !(in >> this->state[1]).fail()) {
         return in;
     }
     throw Error(MSG(err) << "Unable to read rng state serialization from input stream");
 }
References openage::log::err(), openage::testing::fail(), MSG, and state.
Referenced by openage::rng::operator >>(), and RNG().
from_string()
void openage::rng::RNG::from_string (const std::string & instr)
Reads the rng in from a string
Exceptions
Error if reading from the string fails
Definition at line 173 of file rng.cpp.
{
     std::stringstream strstr(instr);
     strstr >> *this;
 }
Referenced by RNG().
max()
static constexpr uint64_t openage::rng::RNG::max () inline static
Definition at line 165 of file rng.h.
{
         return UINT64_MAX;
     }
Referenced by fill_real(), probability(), and real().
min()
static constexpr uint64_t openage::rng::RNG::min () inline static
Definition at line 170 of file rng.h.
{
         return 0;
     }
operator()()
uint64_t openage::rng::RNG::operator() () inline
Retrieves a random value from the generator
Definition at line 77 of file rng.h.
{
         return this->random();
     }
References random().
probability()
bool openage::rng::RNG::probability (double prob) inline
Returns true with the passed probability
Definition at line 93 of file rng.h.
{
         return this->random() < (RNG::max() * prob);
     }
References max(), and random().
Referenced by openage::ActionMode::on_game_control_set(), and openage::Region::subset().
random()
uint64_t openage::rng::RNG::random ()
Retrieves a random value from the generator
Definition at line 89 of file rng.cpp.
                      {
     std::swap(this->state[0], this->state[1]);
     return do_rng(this->state[0], this->state[1]);
 }
References openage::rng::do_rng(), and state.
Referenced by operator()(), probability(), openage::rng::random(), random_range(), openage::random_tile(), and real().
random_range()
uint64_t openage::rng::RNG::random_range (uint64_t lower, uint64_t upper) inline
Returns a random integer in the range [lower, upper]
Definition at line 85 of file rng.h.
{
         return (this->random() % (upper - lower)) + lower;
     }
References random().
Referenced by openage::rng::random_range().
real()
double openage::rng::RNG::real () inline
Retrieves a double in [0, 1)
Definition at line 101 of file rng.h.
{
         return static_cast<double>(this->random()) / RNG::max();
     }
References max(), and random().
Referenced by openage::rng::real(), and real_range().
real_range()
double openage::rng::RNG::real_range (double lower, double upper) inline
Returns a double in the range [min, max)
Definition at line 109 of file rng.h.
{
         return this->real() * (upper - lower) + lower;
     }
References real().
Referenced by openage::rng::real_range().
seed() [1/2]
void openage::rng::RNG::seed (uint64_t val)
Seeds with the 64 bit seed
Definition at line 53 of file rng.cpp.
{
     this->seed(&val, sizeof(val));
 }
References val.
Referenced by RNG().
seed() [2/2]
void openage::rng::RNG::seed (const void * data, size_t count)
Initializes the rng using bits from the buffer pointed to by data
Parameters
data The buffer that contains data for seeding the rng
count The number of bytes in the buffer
Exceptions
Error if 0 bytes are passed
Definition at line 58 of file rng.cpp.
{
     if (count == 0) {
         throw Error(MSG(err) << "0 bytes supplied as seed data");
     }
     const uint8_t *data = static_cast<const uint8_t *>(dat);
     openage::util::Siphash siphash(seed_key);
     state[0] = siphash.digest(data, count);
     // Previously, for state[1] we hashed (data ^ state[0])
     // As `data` now has variable length I can't do that, I think that just
     // hashing `state[0]` is enough
     state[1] = siphash.digest(state[0]);
     // This helps prevent low-zero states caused by a bad seed
     this->discard(discard_on_seed);
 }
References discard(), discard_on_seed, openage::log::err(), MSG, openage::rng::seed_key, openage::util::tests::siphash(), and state.
to_stream()
std::ostream & openage::rng::RNG::to_stream (std::ostream & out) const
Outputs the rng state to a stream
Exceptions
Error if writing data fails
Definition at line 148 of file rng.cpp.
{
     if ((out << this->state[0] << " ").good() &&
         !(out << this->state[1]).fail()) {
         return out;
     }
     throw Error(MSG(err) << "Unable to write rng state serialization to output stream");
 }
References openage::log::err(), openage::testing::fail(), MSG, and state.
Referenced by openage::rng::operator<<().
to_string()
std::string openage::rng::RNG::to_string () const
Writes the rng state to a string
Definition at line 166 of file rng.cpp.
{
     util::FString fs;
     fs << *this;
     return fs;
 }
Referenced by openage::rng::tests::serialize().
Member Data Documentation
discard_on_seed
constexpr size_t openage::rng::RNG::discard_on_seed = 50 static private
elements to discard on seed to escape from high-zero seeds
Definition at line 185 of file rng.h.
Referenced by seed().
state
uint64_t openage::rng::RNG::state[2] private
The internal state array
Definition at line 179 of file rng.h.
Referenced by discard(), fill(), fill_real(), from_stream(), random(), seed(), and to_stream().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/rng/rng.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/rng/rng.cpp