openage: openage::event::demo::ResetGame Class Reference
openage::event::demo::ResetGame Class Reference
Public Member Functions
ResetGame ()
void setup_event (const std::shared_ptr< Event > &, const std::shared_ptr< State > &) override
void invoke (Loop &, const std::shared_ptr< EventTarget > &, const std::shared_ptr< State > &gstate, const curve::time_t &now, const EventClass::param_map &) override
curve::time_t predict_invoke_time (const std::shared_ptr< EventTarget > &, const std::shared_ptr< State > &, const curve::time_t &old_time) override
Public Member Functions inherited from openage::event::OnceEventClass
OnceEventClass (const std::string &name)
Public Member Functions inherited from openage::event::EventClass
EventClass (const std::string &name, const trigger_type &type)
virtual ~EventClass ()=default
const std::string & id ()
Additional Inherited Members
Public Types inherited from openage::event::EventClass
enum trigger_type {
trigger_type::DEPENDENCY, trigger_type::DEPENDENCY_IMMEDIATELY, trigger_type::TRIGGER, trigger_type::REPEAT,
trigger_type::ONCE
}
Public Attributes inherited from openage::event::EventClass
const trigger_type type
Detailed Description
Definition at line 266 of file physics.cpp.
Constructor & Destructor Documentation
ResetGame()
openage::event::demo::ResetGame::ResetGame () inline
Definition at line 268 of file physics.cpp.
         :
         OnceEventClass("demo.reset") {}
Member Function Documentation
invoke()
void openage::event::demo::ResetGame::invoke (Loop & loop, const std::shared_ptr< EventTarget > & target, const std::shared_ptr< State > & state, const curve::time_t & time, const EventClass::param_map & params) inline override virtual
This method implements the effects of the event. It will be called at the time that was determined by predict_invoke_time.
Called from the Loop.
Implements openage::event::EventClass.
Definition at line 275 of file physics.cpp.
{
         auto state = std::dynamic_pointer_cast<PongState>(gstate);
         // Check if the condition still applies
         {
             auto pos = state->ball->position->get(now);
             if (pos[0] > 0 && pos[0] < state->display_boundary[0]) {
                 // the gamestate is still valid - there is no need to reset
                 return;
             }
         }
         // move ball to the center
         state->ball->position->set_last(now - curve::time_t::from_double(0.1),
                                         state->ball->position->get(now));
         state->ball->position->set_last(now, state->display_boundary * 0.5);
         // move paddles to center
         state->p1->position->set_last(now, state->display_boundary[1] / 2);
         state->p2->position->set_last(now, state->display_boundary[1] / 2);
         float dirx = (rng::random() % 2) ? 1 : -1;
         float diry = (rng::random() % 2) ? 1 : -1;
         auto init_speed = util::Vector2d(
             dirx * (10 + (rng::random() % 100) / 4.f),
             diry * (0.3 + (rng::random() % 100) / 18.f)
         );
         state->ball->speed->set_last(now, init_speed);
         auto pos = state->ball->position->get(now);
 #if WITH_NCURSES
         if (state->enable_gui) {
             static int cnt = 0;
             util::FString str;
             str.fmt("Reset. Speed %f | %f POS %f | %f [%i]",
                     init_speed[0],
                     init_speed[1],
                     pos[0],
                     pos[1],
                     ++cnt);
             state->gui->log(str);
         }
         else {
 #endif
             log::log(INFO << "Game was reset.");
 #if WITH_NCURSES
         }
 #endif
         curve::time_t ty = 0;
         // calculate the wall-hit-times
         if (init_speed[1] > 0) {
             ty = curve::time_t::from_double((state->display_boundary[1] - pos[1]) / init_speed[1]);
         }
         else if (init_speed[1] < 0) {
             ty = curve::time_t::from_double(pos[1] / -init_speed[1]);
         }
         else {
             // currently never happens, but this would be a non-vertically-moving ball
             // fallback to calculating panel-hit-times
             if (init_speed[0] > 0) {
                 ty = curve::time_t::from_double((state->display_boundary[0] - pos[0]) / init_speed[0]);
             }
             else {
                 ty = curve::time_t::from_double(pos[0] / -init_speed[0]);
             }
         }
         state->ball->position->set_last(now + ty, pos + init_speed * ty.to_double());
     }
References openage::util::FixedPoint< int64_t, 16 >::from_double(), INFO, openage::log::log(), openage::rng::random(), openage::py::str(), and openage::util::FixedPoint< int_type, fractional_bits >::to_double().
predict_invoke_time()
curve::time_t openage::event::demo::ResetGame::predict_invoke_time (const std::shared_ptr< EventTarget > & target, const std::shared_ptr< State > & state, const curve::time_t & at) inline override virtual
Is called to calculate the execution time for an event of this eventclass. This is called whenever one of the set up dependencies was changed, or when a REPEAT event was executed.
Parameters
target the target the event was created for
state the state this shall work on
at the time when the change happened, from there on it shall be calculated onwards
If the event is obsolete, return <time_t>min().
If the time is lower than the previous time, then dependencies may not be resolved perfectly anymore (if other events have already been calculated before that).
Implements openage::event::EventClass.
Definition at line 354 of file physics.cpp.
{
         return old_time;
     }
setup_event()
void openage::event::demo::ResetGame::setup_event (const std::shared_ptr< Event > & event, const std::shared_ptr< State > & state) inline override virtual
Called for each event that is created for this EventClass. The job of the setup function is to add all dependencies with other event targets found in state.
Implements openage::event::EventClass.
Definition at line 272 of file physics.cpp.
                                                              {}
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/event/demo/physics.cpp