openage: openage::job::Worker Class Reference
openage::job::Worker Class Reference
#include <worker.h>
Public Member Functions
Worker (JobManager *manager)
~Worker ()=default
void start ()
void stop ()
void join ()
void enqueue (std::shared_ptr< JobStateBase > job)
void notify ()
Private Member Functions
void execute_job (std::shared_ptr< JobStateBase > &job)
void process ()
Private Attributes
JobManager * manager
bool is_running
std::unique_ptr< std::thread > executor
std::mutex pending_jobs_mutex
std::queue< std::shared_ptr< JobStateBase > > pending_jobs
std::condition_variable jobs_available
Detailed Description
A worker encapsulates the execution of multiple jobs in a single background thread.
Definition at line 22 of file worker.h.
Constructor & Destructor Documentation
Worker()
openage::job::Worker::Worker (JobManager * manager)
Constructs a new worker with the parent job manager.
Definition at line 12 of file worker.cpp.
     :
     manager{manager},
     is_running{false} {
 }
References manager.
~Worker()
openage::job::Worker::~Worker () default
Default destructor.
Member Function Documentation
enqueue()
void openage::job::Worker::enqueue (std::shared_ptr< JobStateBase > job)
Adds the given job to the internal pending job queue.
Definition at line 33 of file worker.cpp.
{
     std::unique_lock<std::mutex> lock{this->pending_jobs_mutex};
     this->pending_jobs.push(job);
     lock.unlock();
     this->notify();
 }
References lock, notify(), pending_jobs, and pending_jobs_mutex.
execute_job()
void openage::job::Worker::execute_job (std::shared_ptr< JobStateBase > & job) private
Executes the given job and tells the parent job manager, when it has finished.
Definition at line 51 of file worker.cpp.
{
     auto should_abort = [this]() {
         return not this->is_running;
     };
     bool aborted = job->execute(should_abort);
     // if the job was not aborted, tell the job manager, that the job has
     // finished
     if (not aborted) {
         this->manager->finish_job(job);
     }
 }
References openage::job::JobManager::finish_job(), is_running, and manager.
Referenced by process().
join()
void openage::job::Worker::join ()
Joins the internal executing thread.
Definition at line 46 of file worker.cpp.
                   {
     this->executor->join();
 }
References executor.
notify()
void openage::job::Worker::notify ()
Notifies this worker, that new jobs are available. This method is although called from the parent job manager.
Definition at line 41 of file worker.cpp.
                     {
     this->jobs_available.notify_all();
 }
References jobs_available.
Referenced by enqueue(), and stop().
process()
void openage::job::Worker::process () private
Fetches pending jobs from the parent job manager and from the internal pending job queue and executes them. If no jobs are available the internal execution thread is wait using a condition variable.
Definition at line 65 of file worker.cpp.
                      {
     // as long as this worker thread is running repeat all steps
     while (true) {
         // lock the local thread queue
         std::unique_lock<std::mutex> lock{this->pending_jobs_mutex};
         // if this thread shall not run any longer, exit the loop
         if (not this->is_running) {
             return;
         }
         // as long as there are no jobs from the local queue or the job manager
         while (this->pending_jobs.empty() and not this->manager->has_job()) {
             // the thread should wait
             this->jobs_available.wait(lock);
             // when the thread is notified, first check if the thread should be
             // stopped
             if (not this->is_running) {
                 return;
             }
         }
         // check if there are jobs in the local queue
         if (not this->pending_jobs.empty()) {
             // fetch the job
             auto job = this->pending_jobs.front();
             this->pending_jobs.pop();
             // release the local queue lock
             lock.unlock();
             // and execute the job
             this->execute_job(job);
         } else {
             // otherwise just unlock the local queue
             lock.unlock();
         }
         // after possibly executing a job from the local queue, check again if
         // the thread should still continue running
         if (not this->is_running) {
             return;
         }
         // now try to fetch a job from the job manager
         auto manager_job = this->manager->fetch_job();
         if (manager_job.get() != nullptr) {
             // and execute it
             this->execute_job(manager_job);
         }
     }
 }
References execute_job(), openage::job::JobManager::fetch_job(), openage::job::JobManager::has_job(), is_running, jobs_available, lock, manager, pending_jobs, and pending_jobs_mutex.
Referenced by start().
start()
void openage::job::Worker::start ()
Starts this worker.
Definition at line 19 of file worker.cpp.
                    {
     this->is_running = true;
     this->executor.reset(new std::thread{&Worker::process, this});
 }
References executor, is_running, and process().
stop()
void openage::job::Worker::stop ()
Stops this worker.
Definition at line 25 of file worker.cpp.
                   {
     std::unique_lock<std::mutex> lock{this->pending_jobs_mutex};
     this->is_running = false;
     lock.unlock();
     this->notify();
 }
References is_running, lock, notify(), and pending_jobs_mutex.
Member Data Documentation
executor
std::unique_ptr<std::thread> openage::job::Worker::executor private
The executing thread.
Definition at line 31 of file worker.h.
Referenced by join(), and start().
is_running
bool openage::job::Worker::is_running private
Whether this worker thread is still running.
Definition at line 28 of file worker.h.
Referenced by execute_job(), process(), start(), and stop().
jobs_available
std::condition_variable openage::job::Worker::jobs_available private
A condition variable to wait for new jobs.
Definition at line 40 of file worker.h.
Referenced by notify(), and process().
manager
JobManager* openage::job::Worker::manager private
The parent job manager, this worker is fetching jobs from.
Definition at line 25 of file worker.h.
Referenced by execute_job(), process(), and Worker().
pending_jobs
std::queue<std::shared_ptr<JobStateBase> > openage::job::Worker::pending_jobs private
A queue of jobs that are to be executed.
Definition at line 37 of file worker.h.
Referenced by enqueue(), and process().
pending_jobs_mutex
std::mutex openage::job::Worker::pending_jobs_mutex private
A mutex to synchronize the internal pending jobs queue.
Definition at line 34 of file worker.h.
Referenced by enqueue(), process(), and stop().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/job/worker.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/job/worker.cpp