openage: openage::ActionModeSignals Class Reference
openage::ActionModeSignals Class Reference
#include <game_control.h>
Public Slots
void on_action (const std::string &action_name)
Signals
void resource_changed (game_resource resource, int amount)
void population_changed (int demand, int capacity, bool warn)
void ability_changed (const std::string &ability)
void buttons_type_changed (const ActionButtonsType type)
Public Member Functions
ActionModeSignals (ActionMode *action_mode)
Private Attributes
ActionMode * action_mode
Detailed Description
Definition at line 139 of file game_control.h.
Constructor & Destructor Documentation
ActionModeSignals()
openage::ActionModeSignals::ActionModeSignals (ActionMode * action_mode) explicit
Definition at line 64 of file game_control.cpp.
     :
     action_mode(action_mode) {
 }
Member Function Documentation
ability_changed
void openage::ActionModeSignals::ability_changed (const std::string & ability) signal
Referenced by openage::ActionMode::announce(), openage::gui::ActionModeLink::on_core_adopted(), and openage::ActionMode::on_game_control_set().
buttons_type_changed
void openage::ActionModeSignals::buttons_type_changed (const ActionButtonsType type) signal
Referenced by openage::ActionMode::announce_buttons_type(), and openage::gui::ActionModeLink::on_core_adopted().
on_action
void openage::ActionModeSignals::on_action (const std::string & action_name) slot
Definition at line 69 of file game_control.cpp.
{
     Engine *engine = this->action_mode->game_control->get_engine();
     const input::action_t &action = engine->get_action_manager().get(action_name);
     input::InputContext *top_ctxt = &engine->get_input_manager().get_top_context();
     if (top_ctxt == this->action_mode ||
         top_ctxt == &this->action_mode->building_context ||
         top_ctxt == &this->action_mode->build_menu_context ||
         top_ctxt == &this->action_mode->build_menu_mil_context) {
         // create an action that just relays the action.
         input::action_arg_t action_arg{
             input::Event{input::event_class::ANY, 0, input::modset_t{}},
             coord::input{0, 0},
             coord::input_delta{0, 0},
             {action}
         };
         top_ctxt->execute_if_bound(action_arg);
     }
 }
References action_mode, openage::input::ANY, openage::ActionMode::building_context, openage::input::InputContext::execute_if_bound(), openage::OutputMode::game_control, openage::input::ActionManager::get(), openage::Engine::get_action_manager(), openage::GameControl::get_engine(), openage::Engine::get_input_manager(), and openage::input::InputManager::get_top_context().
Referenced by openage::gui::ActionModeLink::on_core_adopted().
population_changed
void openage::ActionModeSignals::population_changed (int demand, int capacity, bool warn) signal
Referenced by openage::ActionMode::announce_resources(), and openage::gui::ActionModeLink::on_core_adopted().
resource_changed
void openage::ActionModeSignals::resource_changed (game_resource resource, int amount) signal
Referenced by openage::ActionMode::announce_resources(), and openage::gui::ResourcesListModel::set_action_mode().
Member Data Documentation
action_mode
ActionMode* openage::ActionModeSignals::action_mode private
Definition at line 155 of file game_control.h.
Referenced by on_action().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/game_control.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/game_control.cpp