openage: openage::curve::KeyframeContainer< T > Class Template Reference
openage::curve::KeyframeContainer< T > Class Template Reference
#include <keyframe_container.h>
Classes
class Keyframe
Public Types
using curvecontainer = std::list< Keyframe >
using KeyframeIterator = typename curvecontainer::const_iterator
Public Member Functions
KeyframeContainer (const std::shared_ptr< event::Loop > &loop)
~KeyframeContainer ()
KeyframeIterator last (const time_t &time, const KeyframeIterator &hint) const
KeyframeIterator last (const time_t &time) const
KeyframeIterator insert (const Keyframe &value)
KeyframeIterator insert (const Keyframe &value, const KeyframeIterator &hint)
KeyframeIterator insert (const time_t &time, const T &value)
KeyframeIterator insert (const time_t &time, const T &value, const KeyframeIterator &hint)
KeyframeIterator erase_after (KeyframeIterator last_valid)
KeyframeIterator erase (KeyframeIterator it)
KeyframeIterator begin () const
KeyframeIterator end () const
void dump ()
Private Attributes
const std::shared_ptr< event::Loop > loop
curvecontainer container
Detailed Description
template<typename T>
class openage::curve::KeyframeContainer< T >
A timely ordered list with several management functions
This class manages different time-based management functions for list approach that lies underneath. It contains list to be accessed via a non-accurate timing functionality, this means, that for getting a value, not the exact timestamp has to be known, it will always return the one closest, less or equal to the requested one.
Definition at line 25 of file keyframe_container.h.
Member Typedef Documentation
curvecontainer
template<typename T> using openage::curve::KeyframeContainer< T >::curvecontainer = std::list<Keyframe>
The underlaying container type.
The most important property of this container is the iterator validity on insert and remove.
Definition at line 61 of file keyframe_container.h.
KeyframeIterator
template<typename T> using openage::curve::KeyframeContainer< T >::KeyframeIterator = typename curvecontainer::const_iterator
The iterator type to access elements in the container
Definition at line 66 of file keyframe_container.h.
Constructor & Destructor Documentation
KeyframeContainer()
template<typename T > openage::curve::KeyframeContainer< T >::KeyframeContainer (const std::shared_ptr< event::Loop > & loop)
need the datamanger for change management
Definition at line 172 of file keyframe_container.h.
     :
     loop(loop) {
     // Create a default element at -Inf, that can always be dereferenced - so
     // there will by definition never be a element that cannot be dereferenced
     this->container.push_back(Keyframe(std::numeric_limits<time_t>::min(), T()));
 }
References openage::curve::KeyframeContainer< T >::container, and std::min().
~KeyframeContainer()
template<typename T > openage::curve::KeyframeContainer< T >::~KeyframeContainer ()
Definition at line 182 of file keyframe_container.h.
{
     // We rely on std::list to destroy all elements.
 }
Member Function Documentation
begin()
template<typename T> KeyframeIterator openage::curve::KeyframeContainer< T >::begin () const inline
Obtain an iterator to the first value with the smallest timestamp.
Definition at line 142 of file keyframe_container.h.
{
         return container.begin();
     }
References openage::curve::KeyframeContainer< T >::container.
dump()
template<typename T> void openage::curve::KeyframeContainer< T >::dump () inline
Debugging method to be used from gdb to understand bugs better.
Definition at line 156 of file keyframe_container.h.
                 {
         for (auto e : container) {
             std::cout << "Element: time: " << e.time << " v: " << e.value << std::endl;
         }
     }
References openage::curve::KeyframeContainer< T >::container.
Referenced by openage.convert.texture.Texture::save().
end()
template<typename T> KeyframeIterator openage::curve::KeyframeContainer< T >::end () const inline
Obtain an iterator to the position after the last value.
Definition at line 149 of file keyframe_container.h.
{
         return container.end();
     }
References openage::curve::KeyframeContainer< T >::container.
erase()
template<typename T> KeyframeContainer< T >::KeyframeIterator openage::curve::KeyframeContainer< T >::erase (KeyframeIterator it)
Erase a single element from the curve.
Delete the element from the list and call delete on it.
Definition at line 267 of file keyframe_container.h.
{
     return this->container.erase(e);
 }
References openage::curve::tests::container().
erase_after()
template<typename T> KeyframeContainer< T >::KeyframeIterator openage::curve::KeyframeContainer< T >::erase_after (KeyframeIterator last_valid)
Erase all elements that come after this last valid element.
Go from the end to the last_valid element, and call erase on all of them
Definition at line 248 of file keyframe_container.h.
{
     // exclude the last_valid element from deletion
     if (last_valid != this->container.end()) {
         ++last_valid;
     }
     // Delete everything to the end.
     while (last_valid != this->container.end()) {
         last_valid = this->container.erase(last_valid);
     }
     return last_valid;
 }
References openage::curve::tests::container().
insert() [1/4]
template<typename T> KeyframeIterator openage::curve::KeyframeContainer< T >::insert (const Keyframe & value) inline
Insert a new element without a hint.
This function is not recommended for use, whenever possible, keep a hint to insert the data.
Definition at line 101 of file keyframe_container.h.
{
         return this->insert(value, this->container.begin());
     }
References openage::curve::KeyframeContainer< T >::container.
Referenced by openage::curve::tests::curve_types(), and openage::curve::KeyframeContainer< T >::insert().
insert() [2/4]
template<typename T> KeyframeIterator openage::curve::KeyframeContainer< T >::insert (const Keyframe & value, const KeyframeIterator & hint)
Insert a new element. The hint shall give an approximate location, where the inserter will start to look for a insertion point. If a good hint is given, the runtime of this function will not be affected by the current history size.
insert() [3/4]
template<typename T> KeyframeIterator openage::curve::KeyframeContainer< T >::insert (const time_t & time, const T & value) inline
Create and insert a new element without submitting a hint. The use of this function is discouraged, use it only, if your really do not have the possibility to get a hint
Definition at line 118 of file keyframe_container.h.
{
         return this->insert(Keyframe(time, value), this->container.begin());
     }
References openage::curve::KeyframeContainer< T >::container, and openage::curve::KeyframeContainer< T >::insert().
insert() [4/4]
template<typename T> KeyframeIterator openage::curve::KeyframeContainer< T >::insert (const time_t & time, const T & value, const KeyframeIterator & hint) inline
Create and insert a new element. The hint gives an approximate location.
Definition at line 125 of file keyframe_container.h.
{
         return this->insert(Keyframe(time, value), hint);
     }
References openage::curve::KeyframeContainer< T >::insert().
last() [1/2]
template<typename T > KeyframeContainer< T >::KeyframeIterator openage::curve::KeyframeContainer< T >::last (const time_t & time, const KeyframeIterator & hint) const
Get the last element with e->time <= time, given a hint where to start the search.
Select the element that directly preceedes the given timestamp.
Without a hint, start to iterate at the beginning of the buffer, and return the element last element before e->time > time. This method returns nullptr, if begin->time > time.
Definition at line 194 of file keyframe_container.h.
{
     KeyframeIterator e = (hint == this->container.end()) ? this->container.begin() : hint;
     if (this->container.front().time > time) {
         // This will never happen due to the container.front->time == -Inf magic!
         throw Error(ERR << "rupture in spacetime detected, curve container is broken");
     }
     // Search in the queue
     if (time > e->time) { // the searched element is supposed to be AFTER the hint
         // perform the search via ->next
         while (e != this->container.end() && time >= e->time) {
             e++;
         }
         e--;
         // e is now one of two options:
         // 1. e == end: The last element of the queue was smaller than `time`
         // 2. e != end: There was a element with `e->time` > `time`
     } else if (time < e->time) {
         // the searched element is supposed to be BEFORE the hint
         // perform the search via ->prev
         while (e != this->container.begin() && time < e->time) {
             e--;
         }
         // e is now one of two options:
         // 1. e == begin: The time was before every element in the queue
         // 2. e != begin: There was an element with `e->time` > `time`
     } else {
         // perform <= search - and return e, whose time is == time.
     }
     return e;
 }
References openage::curve::tests::container(), and ERR.
Referenced by openage::curve::KeyframeContainer< T >::last().
last() [2/2]
template<typename T> KeyframeIterator openage::curve::KeyframeContainer< T >::last (const time_t & time) const inline
Get the last element with e->time <= time, without a hint where to start searching.
The usage of this method is discouraged - except if there is absolutely no chance for you to have a hint (or the container is known to be nearly empty)
Definition at line 87 of file keyframe_container.h.
{
         return this->last(time, this->container.begin());
     }
References openage::curve::KeyframeContainer< T >::container, and openage::curve::KeyframeContainer< T >::last().
Member Data Documentation
container
template<typename T> curvecontainer openage::curve::KeyframeContainer< T >::container private
Definition at line 167 of file keyframe_container.h.
Referenced by openage::curve::KeyframeContainer< T >::begin(), openage::curve::KeyframeContainer< T >::dump(), openage::curve::KeyframeContainer< T >::end(), openage::curve::KeyframeContainer< T >::insert(), openage::curve::KeyframeContainer< T >::KeyframeContainer(), and openage::curve::KeyframeContainer< T >::last().
loop
template<typename T> const std::shared_ptr<event::Loop> openage::curve::KeyframeContainer< T >::loop private
The data store.
Definition at line 165 of file keyframe_container.h.
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/curve/keyframe_container.h