openage: openage::console::Console Class Reference
openage::console::Console Class Reference
#include <console.h>
Public Member Functions
Console (Engine *engine)
~Console ()
void load_colors (std::vector< gamedata::palette_color > &colortable)
void register_to_engine ()
void set_visible (bool make_visible)
void write (const char *text)
void interpret (const std::string &command)
bool on_drawhud () override
bool on_tick () override
bool on_input (SDL_Event *event) override
bool on_resize (coord::viewport_delta new_size) override
Public Attributes
coord::camhud bottomleft
coord::camhud topright
coord::camhud charsize
std::vector< util::col > termcolors
bool visible
Buf buf
renderer::Font font
input::InputContext input_context
std::string command
Protected Attributes
Engine * engine
Additional Inherited Members
Private Member Functions inherited from openage::InputHandler
virtual ~InputHandler ()=default
Private Member Functions inherited from openage::TickHandler
virtual ~TickHandler ()=default
Private Member Functions inherited from openage::HudHandler
virtual ~HudHandler ()=default
Private Member Functions inherited from openage::ResizeHandler
virtual ~ResizeHandler ()=default
Detailed Description
Definition at line 25 of file console.h.
Constructor & Destructor Documentation
Console()
openage::console::Console::Console (Engine * engine)
Todo:
multiple terminals on screen resizable terminals scrollbars console input log console, command console
Definition at line 23 of file console.cpp.
     :
     engine{engine},
     bottomleft{0, 0},
     topright{1, 1},
     charsize{1, 1},
     visible(false),
     buf{{80, 25}, 1337, 80},
     font{{"DejaVu Sans Mono", "Book", 12}} {
     termcolors.reserve(256);
     // this better be representative for the width of all other characters
     charsize.x = ceilf(font.get_advance_width("W"));
     charsize.y = ceilf(font.get_line_height());
     log::log(MSG(dbg) << "Console font character size: " << charsize.x << "x" << charsize.y);
     // Adjust the corners of the console based on the default buffer size and char size
     topright.x = charsize.x * this->buf.get_dims().x;
     topright.y = charsize.y * this->buf.get_dims().y;
 }
References engine.
~Console()
openage::console::Console::~Console ()
Definition at line 46 of file console.cpp.
 {}
Member Function Documentation
interpret()
void openage::console::Console::interpret (const std::string & command)
a temporary console command interpreter
Definition at line 124 of file console.cpp.
{
     if (command == "exit") {
         this->set_visible(false);
     }
     else if (command == "list") {
         for (auto &line : this->engine->list_options()) {
             this->write(line.c_str());
         }
     }
     else if (command.substr(0,3) ==  "set") {
         std::size_t first_space = command.find(" ");
         std::size_t second_space = command.find(" ", first_space+1);
         if (first_space != std::string::npos && second_space != std::string::npos) {
             std::string name = command.substr(first_space+1, second_space-first_space-1);
             std::string value = command.substr(second_space+1, std::string::npos);
             this->engine->get_cvar_manager().set(name,value);
         }
     }
     else if (command.substr(0,3) == "get") {
         std::size_t first_space = command.find(" ");
         if (first_space != std::string::npos) {
             std::string name = command.substr(first_space+1, std::string::npos);
             std::string value = this->engine->get_cvar_manager().get(name);
             this->write(value.c_str());
         }
     }
 }
References command, engine, openage::cvar::CVarManager::get(), openage::Engine::get_cvar_manager(), openage::line, openage::options::OptionNode::list_options(), openage::cvar::CVarManager::set(), set_visible(), and write().
Referenced by register_to_engine().
load_colors()
void openage::console::Console::load_colors (std::vector< gamedata::palette_color > & colortable)
load the consoles color table
Definition at line 48 of file console.cpp.
{
     for (auto &c : colortable) {
         this->termcolors.emplace_back(c);
     }
     if (termcolors.size() != 256) {
         throw Error(MSG(err) << "Exactly 256 terminal colors are required.");
     }
 }
References openage::log::err(), MSG, and termcolors.
Referenced by openage::run_game().
on_drawhud()
bool openage::console::Console::on_drawhud () override virtual
execute the drawing action.
Implements openage::HudHandler.
Definition at line 162 of file console.cpp.
{
     if (!this->visible) {
         return true;
     }
     draw::to_opengl(this->engine, this);
     return true;
 }
References engine, openage::console::draw::to_opengl(), and visible.
on_input()
bool openage::console::Console::on_input (SDL_Event * event) override virtual
execute the input handler.
Implements openage::InputHandler.
Definition at line 172 of file console.cpp.
{
     // only handle inputs if the console is visible
     if (!this->visible) {
         return true;
     }
     switch (e->type) {
     case SDL_KEYDOWN:
         // \todo handle key inputs
         //do not allow anyone else to handle this input
         return false;
         break;
     }
     return true;
 }
References visible.
on_resize()
bool openage::console::Console::on_resize (coord::viewport_delta new_size) override virtual
execute the resize handler.
Implements openage::ResizeHandler.
Definition at line 190 of file console.cpp.
{
     coord::pixel_t w = this->buf.get_dims().x * this->charsize.x;
     coord::pixel_t h = this->buf.get_dims().y * this->charsize.y;
     this->bottomleft = {(new_size.x - w) / 2, (new_size.y - h) / 2};
     this->topright = {this->bottomleft.x + w, this->bottomleft.y - h};
     return true;
 }
References bottomleft, buf, charsize, openage::console::Buf::get_dims(), and topright.
on_tick()
bool openage::console::Console::on_tick () override virtual
execute the tick action.
Implements openage::TickHandler.
Definition at line 152 of file console.cpp.
                       {
     if (!this->visible) {
         return true;
     }
     // \todo handle stuff such as cursor blinking,
     // repeating held-down keys
     return true;
 }
References visible.
register_to_engine()
void openage::console::Console::register_to_engine ()
register this console to the engine. this leads to the drawing calls, and input handling.
Definition at line 58 of file console.cpp.
{
     this->engine->register_input_action(this);
     this->engine->register_tick_action(this);
     this->engine->register_drawhud_action(this);
     this->engine->register_resize_action(this);
     // Bind the console toggle key globally
     auto &action = this->engine->get_action_manager();
     auto &global = this->engine->get_input_manager().get_global_context();
     global.bind(action.get("TOGGLE_CONSOLE"), [this](const input::action_arg_t &) {
         this->set_visible(!this->visible);
     });
     // \todo bind any needed input to InputContext
     // toggle console will take highest priority
     this->input_context.bind(action.get("TOGGLE_CONSOLE"), [this](const input::action_arg_t &) {
         this->set_visible(false);
     });
     this->input_context.bind(input::event_class::UTF8, [this](const input::action_arg_t &arg) {
         // a single char typed into the console
         std::string utf8 = arg.e.as_utf8();
         this->buf.write(utf8.c_str());
         command += utf8;
         return true;
     });
     this->input_context.bind(input::event_class::NONPRINT, [this](const input::action_arg_t &arg) {
         switch (arg.e.as_char()) {
             case 8: // remove a single UTF-8 character
                 if (this->command.size() > 0) {
                     util::utf8_pop_back(this->command);
                     this->buf.pop_last_char();
                 }
                 return true;
             case 13: // interpret command
                 this->buf.write('\n');
                 this->interpret(this->command);
                 this->command = "";
                 return true;
             default:
                 return false;
         }
     });
     this->input_context.utf8_mode = true;
 }
References openage::input::Event::as_char(), openage::input::Event::as_utf8(), openage::input::InputContext::bind(), buf, command, openage::input::action_arg_t::e, engine, openage::Engine::get_action_manager(), openage::input::InputManager::get_global_context(), openage::Engine::get_input_manager(), input_context, interpret(), openage::input::NONPRINT, openage::console::Buf::pop_last_char(), openage::Engine::register_drawhud_action(), openage::Engine::register_input_action(), openage::Engine::register_resize_action(), openage::Engine::register_tick_action(), set_visible(), openage::input::UTF8, openage::input::utf8(), openage::input::InputContext::utf8_mode, openage::util::utf8_pop_back(), visible, and openage::console::Buf::write().
set_visible()
void openage::console::Console::set_visible (bool make_visible)
Definition at line 108 of file console.cpp.
{
     if (make_visible) {
         this->engine->get_input_manager().push_context(&this->input_context);
         this->visible = true;
     }
     else {
         this->engine->get_input_manager().remove_context(&this->input_context);
         this->visible = false;
     }
 }
References engine, openage::Engine::get_input_manager(), input_context, openage::input::InputManager::push_context(), openage::input::InputManager::remove_context(), and visible.
Referenced by interpret(), and register_to_engine().
write()
void openage::console::Console::write (const char * text)
prints the given text on the console.
Definition at line 119 of file console.cpp.
{
     this->buf.write(text);
     this->buf.write('\n');
 }
References buf, and openage::console::Buf::write().
Referenced by interpret().
Member Data Documentation
bottomleft
coord::camhud openage::console::Console::bottomleft
Definition at line 63 of file console.h.
Referenced by on_resize(), and openage::console::draw::to_opengl().
buf
Buf openage::console::Console::buf
Definition at line 71 of file console.h.
Referenced by on_resize(), openage.util.filelike.stream.StreamSeekBuffer::read(), openage.cabextract.lzxdstream.LZXDStream::read(), register_to_engine(), openage.util.filelike.stream.StreamSeekBuffer::resetwrappeed(), openage::console::draw::to_opengl(), and write().
charsize
coord::camhud openage::console::Console::charsize
Definition at line 65 of file console.h.
Referenced by on_resize(), and openage::console::draw::to_opengl().
command
std::string openage::console::Console::command
Definition at line 77 of file console.h.
Referenced by interpret(), and register_to_engine().
engine
Engine* openage::console::Console::engine protected
Definition at line 60 of file console.h.
Referenced by Console(), interpret(), on_drawhud(), register_to_engine(), and set_visible().
font
renderer::Font openage::console::Console::font
Definition at line 72 of file console.h.
Referenced by openage::console::draw::to_opengl().
input_context
input::InputContext openage::console::Console::input_context
Definition at line 74 of file console.h.
Referenced by register_to_engine(), and set_visible().
termcolors
std::vector<util::col> openage::console::Console::termcolors
Definition at line 67 of file console.h.
Referenced by load_colors(), and openage::console::draw::to_opengl().
topright
coord::camhud openage::console::Console::topright
Definition at line 64 of file console.h.
Referenced by on_resize().
visible
bool openage::console::Console::visible
Definition at line 69 of file console.h.
Referenced by on_drawhud(), on_input(), on_tick(), register_to_engine(), and set_visible().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/console/console.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/console/console.cpp