openage: openage::BuildAction Class Reference
openage::BuildAction Class Reference
#include <action.h>
Public Member Functions
BuildAction (Unit *e, UnitReference foundation)
virtual ~BuildAction ()
void update_in_range (unsigned int time, Unit *target_unit) override
void on_completion_in_range (int) override
bool completed_in_range (Unit *) const override
void on_completion () override
std::string name () const override
float get_progress () const
Public Member Functions inherited from openage::TargetAction
TargetAction (Unit *e, graphic_type gt, UnitReference r, coord::phys_t action_rad)
TargetAction (Unit *e, graphic_type gt, UnitReference r)
virtual ~TargetAction ()
void update (unsigned int time) override
bool completed () const override
bool allow_interupt () const override
bool allow_control () const override
coord::phys_t distance_to_target ()
Unit * update_distance ()
UnitReference get_target () const
int get_target_type_id () const
void set_target (UnitReference new_target)
Public Member Functions inherited from openage::UnitAction
UnitAction (Unit *u, graphic_type initial_gt)
virtual ~UnitAction ()
graphic_type type () const
float current_frame () const
virtual const graphic_set & current_graphics () const
void draw_debug (const Engine &engine)
void face_towards (const coord::phys3 pos)
bool damage_unit (Unit &target)
void move_to (Unit &target, bool use_range=true)
Private Attributes
float complete
float build_rate
Static Private Attributes
static constexpr float search_tile_distance = 9.0f
Additional Inherited Members
Static Public Member Functions inherited from openage::UnitAction
static coord::phys_t adjacent_range (Unit *u)
static coord::phys_t get_attack_range (Unit *u)
static coord::phys_t get_heal_range (Unit *u)
Static Public Attributes inherited from openage::UnitAction
static bool show_debug = false
Protected Attributes inherited from openage::UnitAction
Unit * entity
graphic_type graphic
float frame
float frame_rate
std::function< void(const Engine &)> debug_draw_action
Detailed Description
builds a building
Definition at line 496 of file action.h.
Constructor & Destructor Documentation
BuildAction()
openage::BuildAction::BuildAction (Unit * e, UnitReference foundation)
Definition at line 879 of file action.cpp.
     :
     TargetAction{e, graphic_type::work, foundation},
     complete{.0f},
     build_rate{.0001f} {
     // update the units type
     if (this->entity->has_attribute(attr_type::multitype)) {
         this->entity->get_attribute<attr_type::multitype>().switchType(gamedata::unit_classes::BUILDING, this->entity);
     }
 }
References openage::work.
~BuildAction()
virtual openage::BuildAction::~BuildAction () inline virtual
Definition at line 499 of file action.h.
 {}
Member Function Documentation
completed_in_range()
bool openage::BuildAction::completed_in_range (Unit *) const inline override virtual
Implements openage::TargetAction.
Definition at line 503 of file action.h.
 { return this->complete >= 1.0f; }
References complete.
get_progress()
float openage::BuildAction::get_progress () const inline
Definition at line 507 of file action.h.
 { return this->complete; }
References complete.
name()
std::string openage::BuildAction::name () const inline override virtual
debug string to identify action types
Implements openage::TargetAction.
Definition at line 505 of file action.h.
 { return "build"; }
Referenced by openage.util.fslike.path.Path::stem(), openage.util.fslike.path.Path::suffix(), and openage.util.fslike.path.Path::suffixes().
on_completion()
void openage::BuildAction::on_completion () override virtual
action to perform when popped from a units action stack
Reimplemented from openage::TargetAction.
Definition at line 932 of file action.cpp.
{
     if (this->get_target().is_valid() && this->get_target().get()->get_attribute<attr_type::building>().completed < 1.0f) {
         // The BuildAction was just aborted and we shouldn't look for new buildings
         return;
     }
     this->entity->log(MSG(dbg) << "Done building, searching for new building");
     auto valid = [this](const TerrainObject &obj) {
         if (!this->entity->get_attribute<attr_type::owner>().player.owns(obj.unit) ||
             !obj.unit.has_attribute(attr_type::building) ||
             obj.unit.get_attribute<attr_type::building>().completed >= 1.0f) {
             return false;
         }
         this->entity->log(MSG(dbg) << "Found unit " << obj.unit.logsource_name());
         return true;
     };
     TerrainObject *new_target = find_in_radius(*this->entity->location, valid, BuildAction::search_tile_distance);
     if (new_target != nullptr) {
         this->entity->log(MSG(dbg) << "Found new building, queueing command");
         Command cmd(this->entity->get_attribute<attr_type::owner>().player, &new_target->unit);
         this->entity->queue_cmd(cmd);
     } else {
         this->entity->log(MSG(dbg) << "Didn't find new building");
     }
 }
References openage::building, openage::TargetAction::completed(), openage::log::dbg(), openage::UnitAction::entity, openage::find_in_radius(), openage::Unit::get_attribute(), openage::TargetAction::get_target(), openage::Unit::location, openage::log::LogSource::log(), MSG, openage::owner, openage::Unit::queue_cmd(), search_tile_distance, and openage::TerrainObject::unit.
on_completion_in_range()
void openage::BuildAction::on_completion_in_range (int) inline override virtual
Implements openage::TargetAction.
Definition at line 502 of file action.h.
 {}
update_in_range()
void openage::BuildAction::update_in_range (unsigned int , Unit *) override virtual
Control units action when in range of the target
Implements openage::TargetAction.
Definition at line 891 of file action.cpp.
{
     if (target_unit->has_attribute(attr_type::building)) {
         auto &build = target_unit->get_attribute<attr_type::building>();
         // upgrade floating outlines
         auto target_location = target_unit->location.get();
         if (target_location->is_floating()) {
             // try to place the object
             if (target_location->place(object_state::placed)) {
                 // modify ground terrain
                 if (build.foundation_terrain > 0) {
                     target_location->set_ground(build.foundation_terrain, 0);
                 }
             }
             else {
                 // failed to start construction
                 this->complete = 1.0f;
                 return;
             }
         }
         // increment building completion
         build.completed += build_rate * time;
         this->complete = build.completed;
         if (this->complete >= 1.0f) {
             this->complete = build.completed = 1.0f;
             target_location->place(build.completion_state);
         }
     }
     else {
         this->complete = 1.0f;
     }
     // inc frame
     this->frame += time * this->frame_rate / 2.5f;
 }
References openage::build, build_rate, openage::building, complete, openage::UnitAction::frame, openage::UnitAction::frame_rate, openage::Unit::get_attribute(), openage::Unit::has_attribute(), openage::Unit::location, and openage::placed.
Member Data Documentation
build_rate
float openage::BuildAction::build_rate private
Definition at line 510 of file action.h.
Referenced by update_in_range().
complete
float openage::BuildAction::complete private
Definition at line 510 of file action.h.
Referenced by completed_in_range(), get_progress(), and update_in_range().
search_tile_distance
constexpr float openage::BuildAction::search_tile_distance = 9.0f static private
Definition at line 511 of file action.h.
Referenced by on_completion().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/action.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/action.cpp