openage: openage::util::Vector< N, T > Class Template Reference
openage::util::Vector< N, T > Class Template Reference
#include <vector.h>
Public Types
using this_type = Vector< N, T >
Public Member Functions
Vector ()
~Vector ()=default
template<typename ... Ts>
Vector (Ts ... args)
bool equals (const this_type &other, T eps=default_eps)
this_type & operator+= (const this_type &other)
this_type operator+ (const this_type &other) const
this_type & operator -= (const this_type &other)
this_type operator - (const this_type &other) const
this_type & operator *= (T a)
this_type operator * (T a) const
this_type & operator/= (T a)
this_type operator/ (T a) const
T dot (const this_type &other) const
T norm () const
this_type & normalize ()
template<typename U = this_type>
std::enable_if< N==3, U >::type cross_product (const this_type &other) const
Static Public Attributes
static constexpr T default_eps = 1e-4
Friends
this_type operator * (T a, const this_type &v)
std::ostream & operator<< (std::ostream &o, const this_type &v)
Detailed Description
template<size_t N, typename T>
class openage::util::Vector< N, T >
Vector class with arithmetic.
N = dimensions T = underlying single value type (double, float, ...)
Definition at line 24 of file vector.h.
Member Typedef Documentation
this_type
template<size_t N, typename T> using openage::util::Vector< N, T >::this_type = Vector<N, T>
Definition at line 28 of file vector.h.
Constructor & Destructor Documentation
Vector() [1/2]
template<size_t N, typename T> openage::util::Vector< N, T >::Vector () inline
Default, random-value constructor.
Definition at line 38 of file vector.h.
              {
         for (size_t i = 0; i < N; i++) {
             (*this)[i] = 0;
         }
     }
~Vector()
template<size_t N, typename T> openage::util::Vector< N, T >::~Vector () default
Vector() [2/2]
template<size_t N, typename T> template<typename ... Ts> openage::util::Vector< N, T >::Vector (Ts ... args) inline
Constructor for initialisation with N T values
Definition at line 50 of file vector.h.
         :
         std::array<T, N>{static_cast<T>(args)...} {
         static_assert(sizeof...(args) == N, "not all values supplied.");
     }
Member Function Documentation
cross_product()
template<size_t N, typename T> template<typename U = this_type> std::enable_if<N==3, U>::type openage::util::Vector< N, T >::cross_product (const this_type & other) const inline
Cross-product of two 3-dimensional vectors
Definition at line 177 of file vector.h.
{
         return this_type(
             ((*this)[1] * other[2] - (*this)[2] * other[1]),
             ((*this)[2] * other[0] - (*this)[0] * other[2]),
             ((*this)[0] * other[1] - (*this)[1] * other[0])
         );
     }
Referenced by openage::util::Quaternion< T >::operator *(), and openage::util::tests::vector().
dot()
template<size_t N, typename T> T openage::util::Vector< N, T >::dot (const this_type & other) const inline
Dot product of two Vectors
Definition at line 149 of file vector.h.
{
         T res = 0;
         for (size_t i = 0; i < N; i++) {
             res += (*this)[i] * other[i];
         }
         return res;
     }
Referenced by openage::util::Vector< N, T >::norm(), and openage::util::tests::vector().
equals()
template<size_t N, typename T> bool openage::util::Vector< N, T >::equals (const this_type & other, T eps = default_eps) inline
Equality test with given precision.
Definition at line 60 of file vector.h.
{
         for (size_t i = 0; i < N; i++) {
             T diff = std::abs((*this)[i] - other[i]);
             if (diff >= eps) {
                 return false;
             }
         }
         return true;
     }
References std::abs().
Referenced by openage::util::tests::quaternion(), and openage::util::tests::vector().
norm()
template<size_t N, typename T> T openage::util::Vector< N, T >::norm () const inline
Euclidian norm aka length
Definition at line 160 of file vector.h.
                    {
         return std::sqrt(this->dot(*this));
     }
References openage::util::Vector< N, T >::dot(), and std::sqrt().
Referenced by openage::util::Vector< N, T >::normalize().
normalize()
template<size_t N, typename T> this_type& openage::util::Vector< N, T >::normalize () inline
Scales the Vector so that its norm is 1
Definition at line 167 of file vector.h.
{
         *this /= this->norm();
         return *this;
     }
References openage::util::Vector< N, T >::norm().
operator *()
template<size_t N, typename T> this_type openage::util::Vector< N, T >::operator * (T a) const inline
Scalar multiplication
Definition at line 121 of file vector.h.
{
         this_type res(*this);
         res *= a;
         return res;
     }
operator *=()
template<size_t N, typename T> this_type& openage::util::Vector< N, T >::operator *= (T a) inline
Scalar multiplication with assignment
Definition at line 111 of file vector.h.
{
         for (size_t i = 0; i < N; i++) {
             (*this)[i] *= a;
         }
         return *this;
     }
operator -()
template<size_t N, typename T> this_type openage::util::Vector< N, T >::operator - (const this_type & other) const inline
Vector subtraction
Definition at line 102 of file vector.h.
{
         this_type res(*this);
         res -= other;
         return res;
     }
operator -=()
template<size_t N, typename T> this_type& openage::util::Vector< N, T >::operator -= (const this_type & other) inline
Vector subtraction with assignment
Definition at line 92 of file vector.h.
{
         for (size_t i = 0; i < N; i++) {
             (*this)[i] -= other[i];
         }
         return *this;
     }
operator+()
template<size_t N, typename T> this_type openage::util::Vector< N, T >::operator+ (const this_type & other) const inline
Vector addition
Definition at line 83 of file vector.h.
{
         this_type res(*this);
         res += other;
         return res;
     }
operator+=()
template<size_t N, typename T> this_type& openage::util::Vector< N, T >::operator+= (const this_type & other) inline
Vector addition with assignment
Definition at line 73 of file vector.h.
{
         for (size_t i = 0; i < N; i++) {
             (*this)[i] += other[i];
         }
         return *this;
     }
operator/()
template<size_t N, typename T> this_type openage::util::Vector< N, T >::operator/ (T a) const inline
Scalar division
Definition at line 140 of file vector.h.
{
         this_type res(*this);
         res /= a;
         return res;
     }
operator/=()
template<size_t N, typename T> this_type& openage::util::Vector< N, T >::operator/= (T a) inline
Scalar division with assignment
Definition at line 130 of file vector.h.
{
         for (size_t i = 0; i < N; i++) {
             (*this)[i] /= a;
         }
         return *this;
     }
Friends And Related Function Documentation
operator *
template<size_t N, typename T> this_type operator * (T a, const this_type & v) friend
Scalar multiplication with swapped arguments
Definition at line 188 of file vector.h.
{
         return v * a;
     }
operator<<
template<size_t N, typename T> std::ostream& operator<< (std::ostream & o, const this_type & v) friend
Print to output stream using '<<'
Definition at line 195 of file vector.h.
{
         o << "(";
         for (size_t i = 0; i < N-1; i++) {
             o << v[i] << ", ";
         }
         o << v[N-1] << ")";
         return o;
     }
Member Data Documentation
default_eps
template<size_t N, typename T> constexpr T openage::util::Vector< N, T >::default_eps = 1e-4 static
Default comparison epsilon.
Definition at line 33 of file vector.h.
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/vector.h