openage: openage::pyinterface::PyException Class Reference
openage::pyinterface::PyException Class Reference
#include <pyexception.h>
Public Member Functions
std::string type_name () const override
void init_backtrace ()
Public Member Functions inherited from openage::error::Error
Error (const log::message &msg, bool generate_backtrace=true, bool store_cause=true)
void store_cause ()
void trim_backtrace ()
void rethrow_cause () const
const char * what () const noexcept override
Public Attributes
PyObjectRef py_obj
Public Attributes inherited from openage::error::Error
log::message msg
std::shared_ptr< Backtrace > backtrace
Additional Inherited Members
Static Public Member Functions inherited from openage::error::Error
static void debug_break_on_create (bool state)
Detailed Description
Thrown by translate_exc_py_to_cpp() from exctranslate.h.
These objects are constructed entirely empty, and designed to be filled from describe_py_exception().
pxd:
cppclass PyException(Error): PyObjectRef py_obj void init_backtrace() except +
Definition at line 60 of file pyexception.h.
Member Function Documentation
init_backtrace()
void openage::pyinterface::PyException::init_backtrace ()
Initializes this->backtrace with a PyExceptionBacktrace object that points at this->py_obj->get_ref().
Definition at line 30 of file pyexception.cpp.
{
     this->backtrace = std::make_shared<PyExceptionBacktrace>(this->py_obj.get_ref());
 }
References openage::error::Error::backtrace, openage::pyinterface::PyObjectRef::get_ref(), and py_obj.
type_name()
std::string openage::pyinterface::PyException::type_name () const override virtual
Returns the type name of py_obj.
Reimplemented from openage::error::Error.
Definition at line 35 of file pyexception.cpp.
{
     std::string result;
     result.append(this->py_obj.modulename());
     result.push_back('.');
     result.append(this->py_obj.classname());
     return result;
 }
References openage::pyinterface::PyObjectRef::classname(), openage::pyinterface::PyObjectRef::modulename(), py_obj, and openage.testing.testing::result().
Referenced by openage::pyinterface::tests::err_py_to_cpp(), and openage::pyinterface::tests::pyobject_demo().
Member Data Documentation
py_obj
PyObjectRef openage::pyinterface::PyException::py_obj
Reference to the Python exception object.
Definition at line 71 of file pyexception.h.
Referenced by init_backtrace(), and type_name().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/pyinterface/pyexception.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/pyinterface/pyexception.cpp