openage: openage::gui::GuiImageProviderLink Class Reference
openage::gui::GuiImageProviderLink Class Reference
#include <gui_image_provider_link.h>
Public Member Functions
GuiImageProviderLink (QObject *parent, GuiGameSpecImageProviderImpl &image_provider)
virtual ~GuiImageProviderLink ()
GameSpecLink * get_game_spec () const
void set_game_spec (GameSpecLink *game_spec)
Sets the game spec to load textures from.
Static Public Member Functions
static QObject * provider (QQmlEngine *, const char *id)
static QObject * provider_by_filename (QQmlEngine *, QJSEngine *)
static QObject * provider_by_graphic_id (QQmlEngine *, QJSEngine *)
static QObject * provider_by_terrain_id (QQmlEngine *, QJSEngine *)
Properties
openage::gui::GameSpecLink gameSpec
Private Slots
void on_game_spec_loaded (GameSpecLink *game_spec, std::shared_ptr< GameSpec > loaded_game_spec)
Pass loaded assets to the image provider.
Private Attributes
GuiGameSpecImageProviderImpl & image_provider
QPointer< GameSpecLink > game_spec
Detailed Description
Definition at line 22 of file gui_image_provider_link.h.
Constructor & Destructor Documentation
GuiImageProviderLink()
openage::gui::GuiImageProviderLink::GuiImageProviderLink (QObject * parent, GuiGameSpecImageProviderImpl & image_provider) explicit
Definition at line 30 of file gui_image_provider_link.cpp.
     :
     QObject{parent},
     image_provider{image_provider},
     game_spec{} {
     Q_UNUSED(registration_by_filename);
     Q_UNUSED(registration_by_id);
     Q_UNUSED(registration_by_terrain_id);
 }
~GuiImageProviderLink()
openage::gui::GuiImageProviderLink::~GuiImageProviderLink () virtual
Definition at line 40 of file gui_image_provider_link.cpp.
{
 }
Member Function Documentation
get_game_spec()
GameSpecLink * openage::gui::GuiImageProviderLink::get_game_spec () const
Definition at line 43 of file gui_image_provider_link.cpp.
{
     return this->game_spec;
 }
References game_spec.
on_game_spec_loaded
void openage::gui::GuiImageProviderLink::on_game_spec_loaded (GameSpecLink * game_spec, std::shared_ptr< GameSpec > loaded_game_spec) private slot
Pass loaded assets to the image provider.
Need to check if we still attached to that spec. Also it may be invalidated in the meantime, so share the ownership.
Definition at line 92 of file gui_image_provider_link.cpp.
{
     if (this->game_spec == game_spec)
         this->image_provider.on_game_spec_loaded(loaded_game_spec);
 }
References game_spec, image_provider, and openage::gui::GuiGameSpecImageProviderImpl::on_game_spec_loaded().
Referenced by set_game_spec().
provider()
QObject * openage::gui::GuiImageProviderLink::provider (QQmlEngine * engine, const char * id) static
Definition at line 66 of file gui_image_provider_link.cpp.
{
     qtsdl::QmlEngineWithSingletonItemsInfo *engine_with_singleton_items_info = qtsdl::checked_static_cast<qtsdl::QmlEngineWithSingletonItemsInfo*>(engine);
     auto image_providers = engine_with_singleton_items_info->get_image_providers();
     auto found_it = std::find_if(std::begin(image_providers), std::end(image_providers), [id] (qtsdl::GuiImageProviderImpl *image_provider) {
         return image_provider->get_id() == id;
     });
     ENSURE(found_it != std::end(image_providers), "The image provider '" << id << "' wasn't created or wasn't passed to the QML engine creation function.");
     // owned by the QML engine
     return new GuiImageProviderLink{nullptr, *qtsdl::checked_static_cast<GuiGameSpecImageProviderImpl*>(*found_it)};
 }
References ENSURE, qtsdl::GuiImageProviderImpl::get_id(), qtsdl::QmlEngineWithSingletonItemsInfo::get_image_providers(), and image_provider.
Referenced by provider_by_filename(), provider_by_graphic_id(), and provider_by_terrain_id().
provider_by_filename()
QObject * openage::gui::GuiImageProviderLink::provider_by_filename (QQmlEngine * engine, QJSEngine *) static
Definition at line 80 of file gui_image_provider_link.cpp.
{
     return GuiImageProviderLink::provider(engine, GuiGameSpecImageProviderByFilenameImpl::id());
 }
References openage::gui::GuiGameSpecImageProviderByFilenameImpl::id(), and provider().
provider_by_graphic_id()
QObject * openage::gui::GuiImageProviderLink::provider_by_graphic_id (QQmlEngine * engine, QJSEngine *) static
Definition at line 84 of file gui_image_provider_link.cpp.
{
     return GuiImageProviderLink::provider(engine, GuiGameSpecImageProviderByGraphicIdImpl::id());
 }
References openage::gui::GuiGameSpecImageProviderByGraphicIdImpl::id(), and provider().
provider_by_terrain_id()
QObject * openage::gui::GuiImageProviderLink::provider_by_terrain_id (QQmlEngine * engine, QJSEngine *) static
Definition at line 88 of file gui_image_provider_link.cpp.
{
     return GuiImageProviderLink::provider(engine, GuiGameSpecImageProviderByTerrainIdImpl::id());
 }
References openage::gui::GuiGameSpecImageProviderByTerrainIdImpl::id(), and provider().
set_game_spec()
void openage::gui::GuiImageProviderLink::set_game_spec (GameSpecLink * game_spec)
Sets the game spec to load textures from.
Setting to null doesn't detach from the spec, but picks the 'missing texture' from that spec and sets it to every sprite.
Definition at line 47 of file gui_image_provider_link.cpp.
{
     if (this->game_spec != game_spec) {
         if (this->game_spec)
             QObject::disconnect(this->game_spec.data(), &GameSpecLink::game_spec_loaded, this, &GuiImageProviderLink::on_game_spec_loaded);
         if (!game_spec)
             this->image_provider.on_game_spec_invalidated();
         this->game_spec = game_spec;
         if (this->game_spec) {
             QObject::connect(this->game_spec.data(), &GameSpecLink::game_spec_loaded, this, &GuiImageProviderLink::on_game_spec_loaded);
             if (std::shared_ptr<GameSpec> spec = this->game_spec->get_loaded_spec())
                 this->image_provider.on_game_spec_loaded(spec);
         }
     }
 }
References game_spec, openage::gui::GameSpecLink::game_spec_loaded(), openage::gui::GameSpecLink::get_loaded_spec(), image_provider, openage::gui::GuiGameSpecImageProviderImpl::on_game_spec_invalidated(), openage::gui::GuiGameSpecImageProviderImpl::on_game_spec_loaded(), and on_game_spec_loaded().
Member Data Documentation
game_spec
QPointer<GameSpecLink> openage::gui::GuiImageProviderLink::game_spec private
Definition at line 57 of file gui_image_provider_link.h.
Referenced by get_game_spec(), on_game_spec_loaded(), and set_game_spec().
image_provider
GuiGameSpecImageProviderImpl& openage::gui::GuiImageProviderLink::image_provider private
Definition at line 56 of file gui_image_provider_link.h.
Referenced by on_game_spec_loaded(), provider(), and set_game_spec().
Property Documentation
gameSpec
openage::gui::GameSpecLink openage::gui::GuiImageProviderLink::gameSpec read write
Definition at line 25 of file gui_image_provider_link.h.
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/integration/private/gui_image_provider_link.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/integration/private/gui_image_provider_link.cpp