openage: openage::util::Profiler Class Reference
openage::util::Profiler Class Reference
#include <profiler.h>
Public Member Functions
Profiler (Engine *engine)
~Profiler ()
void register_component (std::string com, color component_color)
void unregister_component (std::string com)
void unregister_all ()
std::vector< std::string > registered_components ()
void start_measure (std::string com, color component_color={1.0, 1.0, 1.0})
void end_measure (std::string com)
void show (bool debug_mode)
void show ()
bool registered (std::string com) const
unsigned size () const
void start_frame_measure ()
void end_frame_measure ()
Private Member Functions
void draw_canvas ()
void draw_legend ()
void draw_component_performance (std::string com)
double duration_to_percentage (std::chrono::high_resolution_clock::duration duration)
void append_to_history (std::string com, double percentage)
bool engine_in_debug_mode ()
Private Attributes
std::chrono::high_resolution_clock::time_point frame_start
std::chrono::high_resolution_clock::duration frame_duration
std::unordered_map< std::string, component_time_data > components
int insert_pos = 0
Engine * engine
Detailed Description
Definition at line 39 of file profiler.h.
Constructor & Destructor Documentation
Profiler()
openage::util::Profiler::Profiler (Engine * engine)
Definition at line 14 of file profiler.cpp.
     :
     engine{engine} {}
References engine.
~Profiler()
openage::util::Profiler::~Profiler ()
Definition at line 19 of file profiler.cpp.
                     {
     this->unregister_all();
 }
References unregister_all().
Member Function Documentation
append_to_history()
void openage::util::Profiler::append_to_history (std::string com, double percentage) private
Definition at line 187 of file profiler.cpp.
{
     if (this->insert_pos == MAX_DURATION_HISTORY) {
         this->insert_pos = 0;
     }
     this->components[com].history[this->insert_pos] = percentage;
 }
References components, insert_pos, and MAX_DURATION_HISTORY.
Referenced by end_frame_measure().
draw_canvas()
void openage::util::Profiler::draw_canvas () private
Definition at line 156 of file profiler.cpp.
{
     glColor4f(0.2, 0.2, 0.2, PROFILER_CANVAS_ALPHA);
     glRecti(PROFILER_CANVAS_POSITION_X,
             PROFILER_CANVAS_POSITION_Y,
             PROFILER_CANVAS_POSITION_X + PROFILER_CANVAS_WIDTH,
             PROFILER_CANVAS_POSITION_Y + PROFILER_CANVAS_HEIGHT);
 }
References PROFILER_CANVAS_ALPHA, PROFILER_CANVAS_HEIGHT, PROFILER_CANVAS_POSITION_X, PROFILER_CANVAS_POSITION_Y, and PROFILER_CANVAS_WIDTH.
Referenced by show().
draw_component_performance()
void openage::util::Profiler::draw_component_performance (std::string com) private
Definition at line 87 of file profiler.cpp.
{
     color rgb = this->components[com].drawing_color;
     glColor4f(rgb.r, rgb.g, rgb.b, 1.0);
     glLineWidth(1.0);
     glBegin(GL_LINE_STRIP);
     float x_offset = 0.0;
     float offset_factor = (float)PROFILER_CANVAS_WIDTH / (float)MAX_DURATION_HISTORY;
     float percentage_factor = (float)PROFILER_CANVAS_HEIGHT / 100.0;
     for (auto i = this->insert_pos; mod(i, MAX_DURATION_HISTORY) != mod(this->insert_pos-1, MAX_DURATION_HISTORY); ++i) {
         i = mod(i, MAX_DURATION_HISTORY);
         auto percentage = this->components[com].history.at(i);
         glVertex3f(PROFILER_CANVAS_POSITION_X + x_offset, PROFILER_CANVAS_POSITION_Y + percentage * percentage_factor, 0.0);
         x_offset += offset_factor;
     }
     glEnd();
     // reset color
     glColor4f(1.0, 1.0, 1.0, 1.0);
 }
References openage::util::color::b, components, openage::util::color::g, insert_pos, MAX_DURATION_HISTORY, openage::util::mod(), PROFILER_CANVAS_HEIGHT, PROFILER_CANVAS_POSITION_X, PROFILER_CANVAS_POSITION_Y, PROFILER_CANVAS_WIDTH, and openage::util::color::r.
Referenced by show().
draw_legend()
void openage::util::Profiler::draw_legend () private
Definition at line 164 of file profiler.cpp.
{
     int offset = 0;
     for (auto com : this->components) {
         glColor4f(com.second.drawing_color.r, com.second.drawing_color.g, com.second.drawing_color.b, 1.0);
         int box_x = PROFILER_CANVAS_POSITION_X + 2;
         int box_y = PROFILER_CANVAS_POSITION_Y - PROFILER_COM_BOX_HEIGHT - 2 - offset;
         glRecti(box_x, box_y, box_x + PROFILER_COM_BOX_WIDTH, box_y + PROFILER_COM_BOX_HEIGHT);
         glColor4f(0.2, 0.2, 0.2, 1);
         coord::viewport position = coord::viewport{box_x + PROFILER_COM_BOX_WIDTH + 2, box_y + 2};
         this->engine->render_text(position, 12, "%s", com.second.display_name.c_str());
         offset += PROFILER_COM_BOX_HEIGHT + 2;
     }
 }
References components, engine, PROFILER_CANVAS_POSITION_X, PROFILER_CANVAS_POSITION_Y, PROFILER_COM_BOX_HEIGHT, PROFILER_COM_BOX_WIDTH, and openage::Engine::render_text().
Referenced by show().
duration_to_percentage()
double openage::util::Profiler::duration_to_percentage (std::chrono::high_resolution_clock::duration duration) private
Definition at line 180 of file profiler.cpp.
{
     double dur = std::chrono::duration_cast<std::chrono::microseconds>(duration).count();
     double ref = std::chrono::duration_cast<std::chrono::microseconds>(this->frame_duration).count();
     double percentage = dur / ref * 100;
     return percentage;
 }
References frame_duration, and ref.
Referenced by end_frame_measure().
end_frame_measure()
void openage::util::Profiler::end_frame_measure ()
sets the end point for the reference time used to compute the portions of the components. Each recorded measurement for the registered components get appended to their history complete the measurement.
Definition at line 140 of file profiler.cpp.
{
     if (not this->engine_in_debug_mode()) {
         return;
     }
     auto frame_end = std::chrono::high_resolution_clock::now();
     this->frame_duration = frame_end - this->frame_start;
     for (auto com : this->registered_components()) {
         double percentage = this->duration_to_percentage(this->components[com].duration);
         this->append_to_history(com, percentage);
     }
     this->insert_pos++;
 }
References append_to_history(), components, duration_to_percentage(), engine_in_debug_mode(), frame_duration, frame_start, insert_pos, and registered_components().
Referenced by openage::Engine::loop().
end_measure()
void openage::util::Profiler::end_measure (std::string com)
Definition at line 76 of file profiler.cpp.
{
     if (not this->engine_in_debug_mode()) {
         return;
     }
     if (this->registered(com)) {
         std::chrono::high_resolution_clock::time_point end = std::chrono::high_resolution_clock::now();
         this->components[com].duration = end - this->components[com].start;
     }
 }
References components, engine_in_debug_mode(), and registered().
Referenced by openage::Engine::loop().
engine_in_debug_mode()
bool openage::util::Profiler::engine_in_debug_mode () private
Definition at line 194 of file profiler.cpp.
{
     if (this->engine->drawing_debug_overlay.value) {
         return true;
     } else {
         return false;
     }
 }
References openage::Engine::drawing_debug_overlay, engine, and openage::util::Variable< T >::value.
Referenced by end_frame_measure(), end_measure(), start_frame_measure(), and start_measure().
register_component()
void openage::util::Profiler::register_component (std::string com, color component_color)
registers a component
Parameters
com the identifier to distinguish the components
component_color color of the plotted line
Definition at line 23 of file profiler.cpp.
{
     if (this->registered(com)) {
         return;
     }
     component_time_data cdt;
     cdt.display_name = com;
     cdt.drawing_color = component_color;
     for (auto &val : cdt.history) {
         val = 0;
     }
     this->components[com] = cdt;
 }
References components, openage::util::component_time_data::display_name, openage::util::component_time_data::drawing_color, openage::util::component_time_data::history, registered(), and val.
Referenced by start_measure().
registered()
bool openage::util::Profiler::registered (std::string com) const
Definition at line 126 of file profiler.cpp.
{
     return this->components.find(com) != this->components.end();
 }
References components.
Referenced by end_measure(), register_component(), start_measure(), and unregister_component().
registered_components()
std::vector< std::string > openage::util::Profiler::registered_components ()
returns a vector of registered component names
Definition at line 55 of file profiler.cpp.
{
     std::vector<std::string> registered_components;
     for (auto &pair : this->components) {
         registered_components.push_back(pair.first);
     }
     return registered_components;
 }
References components.
Referenced by end_frame_measure(), and unregister_all().
show() [1/2]
void openage::util::Profiler::show (bool debug_mode)
Definition at line 110 of file profiler.cpp.
{
     if (debug_mode) {
         this->show();
     }
 }
References show().
Referenced by openage::Engine::draw_debug_overlay().
show() [2/2]
void openage::util::Profiler::show ()
Definition at line 116 of file profiler.cpp.
                     {
     this->draw_canvas();
     this->draw_legend();
     for (auto com : this->components) {
         this->draw_component_performance(com.first);
     }
 }
References components, draw_canvas(), draw_component_performance(), and draw_legend().
Referenced by show().
size()
unsigned openage::util::Profiler::size () const
Definition at line 130 of file profiler.cpp.
{
     return this->components.size();
 }
References components.
start_frame_measure()
void openage::util::Profiler::start_frame_measure ()
sets the start point for the actual frame which is used as a reference value for the registered components
Definition at line 134 of file profiler.cpp.
{
     if (this->engine_in_debug_mode()) {
         this->frame_start = std::chrono::high_resolution_clock::now();
     }
 }
References engine_in_debug_mode(), and frame_start.
Referenced by openage::Engine::loop().
start_measure()
void openage::util::Profiler::start_measure (std::string com, color component_color = {1.0, 1.0, 1.0})
Definition at line 64 of file profiler.cpp.
{
     if (not this->engine_in_debug_mode()) {
         return;
     }
     if (not this->registered(com)) {
         this->register_component(com, component_color);
     }
     this->components[com].start = std::chrono::high_resolution_clock::now();
 }
References components, engine_in_debug_mode(), register_component(), and registered().
Referenced by openage::Engine::loop().
unregister_all()
void openage::util::Profiler::unregister_all ()
unregisters all remaining components
Definition at line 47 of file profiler.cpp.
{
     std::vector<std::string> registered_components = this->registered_components();
     for (auto com : registered_components) {
         this->unregister_component(com);
     }
 }
References registered_components(), and unregister_component().
Referenced by openage::Engine::~Engine(), and ~Profiler().
unregister_component()
void openage::util::Profiler::unregister_component (std::string com)
unregisters an individual component
Parameters
com component name which should be unregistered
Definition at line 39 of file profiler.cpp.
{
     if (not this->registered(com)) {
         return;
     }
     this->components.erase(com);
 }
References components, and registered().
Referenced by unregister_all().
Member Data Documentation
components
std::unordered_map<std::string, component_time_data> openage::util::Profiler::components private
Definition at line 123 of file profiler.h.
Referenced by append_to_history(), draw_component_performance(), draw_legend(), end_frame_measure(), end_measure(), register_component(), registered(), registered_components(), show(), size(), start_measure(), and unregister_component().
engine
Engine* openage::util::Profiler::engine private
Definition at line 126 of file profiler.h.
Referenced by draw_legend(), engine_in_debug_mode(), and Profiler().
frame_duration
std::chrono::high_resolution_clock::duration openage::util::Profiler::frame_duration private
Definition at line 122 of file profiler.h.
Referenced by duration_to_percentage(), and end_frame_measure().
frame_start
std::chrono::high_resolution_clock::time_point openage::util::Profiler::frame_start private
Definition at line 121 of file profiler.h.
Referenced by end_frame_measure(), and start_frame_measure().
insert_pos
int openage::util::Profiler::insert_pos = 0 private
Definition at line 124 of file profiler.h.
Referenced by append_to_history(), draw_component_performance(), and end_frame_measure().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/profiler.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/profiler.cpp