openage: openage::NyanType Class Reference
openage::NyanType Class Reference
#include <unit_type.h>
Public Member Functions
NyanType (const Player &owner)
virtual ~NyanType ()
int id () const override
int parent_id () const override
std::string name () const override
void initialise (Unit *, Player &) override
TerrainObject * place (Unit *, std::shared_ptr< Terrain >, coord::phys3) const override
Public Member Functions inherited from openage::UnitType
UnitType ()
bool match (class Unit *)
UnitType (const Player &owner)
virtual ~UnitType ()
virtual void reinitialise (Unit *, Player &)
bool operator== (const UnitType &other) const
bool operator!= (const UnitType &other) const
UnitTexture * default_texture ()
TerrainObject * place_beside (Unit *, TerrainObject const *) const
void copy_attributes (Unit *unit) const
void upgrade (const std::shared_ptr< AttributeContainer > &attr)
UnitType * parent_type () const
Additional Inherited Members
Public Attributes inherited from openage::UnitType
const Player & owner
std::vector< UnitReference > instances
std::vector< std::shared_ptr< UnitAbility > > type_abilities
Attributes default_attributes
ResourceCost cost
int have_limit
int had_limit
graphic_set graphics
coord::tile_delta foundation_size
gamedata::unit_classes unit_class
Detailed Description
An example of how nyan can work with the type system
Definition at line 197 of file unit_type.h.
Constructor & Destructor Documentation
NyanType()
openage::NyanType::NyanType (const Player & owner)
TODO: give the parsed nyan attributes to the constructor
Definition at line 98 of file unit_type.cpp.
     :
     UnitType(owner) {
     // TODO: the type should be given attributes and abilities
 }
References openage::owner.
~NyanType()
openage::NyanType::~NyanType () virtual
Definition at line 104 of file unit_type.cpp.
 {}
Member Function Documentation
id()
int openage::NyanType::id () const override virtual
gets the unique id of this unit type
Implements openage::UnitType.
Definition at line 106 of file unit_type.cpp.
{
     return 1;
 }
initialise()
void openage::NyanType::initialise (Unit * , Player &) override virtual
Initialize units attributes to this type spec
This can be called using existing units to modify type Ensure that the unit has been placed before seting the units type
TODO: make const
Implements openage::UnitType.
Definition at line 118 of file unit_type.cpp.
{
     // removes all actions and abilities
     unit->reset();
     // initialise unit
     unit->unit_type = this;
     // the parsed nyan data gives the list of attributes
     // and abilities which are given to the unit
     for (auto &ability : this->type_abilities) {
         unit->give_ability(ability);
     }
     // copy all attributes
     this->copy_attributes(unit);
     // give idle action
     unit->push_action(std::make_unique<IdleAction>(unit), true);
 }
References openage::UnitType::copy_attributes(), openage::Unit::give_ability(), openage::Unit::push_action(), openage::Unit::reset(), openage::UnitType::type_abilities, and openage::Unit::unit_type.
name()
std::string openage::NyanType::name () const override virtual
gets the name of the unit type being produced
Implements openage::UnitType.
Definition at line 114 of file unit_type.cpp.
{
     return "Nyan";
 }
Referenced by openage.util.fslike.path.Path::stem(), openage.util.fslike.path.Path::suffix(), and openage.util.fslike.path.Path::suffixes().
parent_id()
int openage::NyanType::parent_id () const override virtual
gets the parent id of this unit type which is used for village base and gather types
Implements openage::UnitType.
Definition at line 110 of file unit_type.cpp.
{
     return -1;
 }
place()
TerrainObject * openage::NyanType::place (Unit * , std::shared_ptr< Terrain > , coord::phys3) const override virtual
set unit in place – return if placement was successful
This should be used when initially creating a unit or when a unit is ungarrsioned from a building or object TODO: make const
Implements openage::UnitType.
Definition at line 138 of file unit_type.cpp.
{
     // the parsed nyan data gives the rules for terrain placement
     // which includes valid terrains, base radius and shape
     unit->make_location<SquareObject>(coord::tile_delta{1, 1});
     // allow unit to go anywhere
     unit->location->passable = [](const coord::phys3 &) {
         return true;
     };
     // try to place the obj, it knows best whether it will fit.
     if (unit->location->place(terrain, init_pos, object_state::placed)) {
         return unit->location.get();
     }
     // placing at the given position failed
     unit->log(MSG(dbg) << "failed to place object");
     return nullptr;
 }
References openage::log::dbg(), openage::Unit::location, openage::log::LogSource::log(), openage::Unit::make_location(), MSG, and openage::placed.
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/unit_type.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/unit_type.cpp