openage: openage::util::Siphash Class Reference
openage::util::Siphash Class Reference
Contains a Siphash implementration.
#include <hash.h>
Public Member Functions
Siphash (std::array< uint8_t, 16 > key)
Creates a hash generator.
Siphash & set_key (std::array< uint8_t, 16 > key)
Set the key for subsequent hashes.
uint64_t digest (const uint8_t *data, size_t len_data)
Hashes the input data as uint8_t array and returns the result.
uint64_t digest (const uint64_t)
Hashes a single uint64_t number and returns the result.
Private Attributes
uint64_t key [2]
The key to use for hashing.
Detailed Description
Contains a Siphash implementration.
https://131002.net/siphash/
Definition at line 23 of file hash.h.
Constructor & Destructor Documentation
Siphash()
openage::util::Siphash::Siphash (std::array< uint8_t, 16 > key)
Creates a hash generator.
Parameters
key Key to use with this hasher.
Definition at line 18 of file hash.cpp.
{
     set_key(key);
 }
References key, and set_key().
Member Function Documentation
digest() [1/2]
uint64_t openage::util::Siphash::digest (const uint8_t * data, size_t len_data)
Hashes the input data as uint8_t array and returns the result.
Parameters
data Start of the input data.
len_data Number of bytes to read.
Returns
Hash.
Definition at line 107 of file hash.cpp.
{
     return hash(key, data, count);
 }
References openage::util::hash(), and key.
digest() [2/2]
uint64_t openage::util::Siphash::digest (const uint64_t)
Hashes a single uint64_t number and returns the result.
The 64-bit word is interpreted as big-endian. e.g. 0x0123456789abcdef -> {0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef}
Parameters
value uint64_t to hash.
Returns
Hash.
Definition at line 112 of file hash.cpp.
{
     std::vector<uint8_t> data = uint64_to_array8(value, true);
     return hash(key, data.data(), 8);
 }
References openage::util::hash(), key, and openage::util::uint64_to_array8().
set_key()
Siphash & openage::util::Siphash::set_key (std::array< uint8_t, 16 > key)
Set the key for subsequent hashes.
Parameters
k Key to use with this hasher.
Returns
Reference to itself, for method chaining.
Definition at line 23 of file hash.cpp.
{
     this->key[0] = array8_to_uint64(key.data(), 8, false);
     this->key[1] = array8_to_uint64(key.data() + 8, 8, false);
     return *this;
 }
References openage::util::array8_to_uint64(), and key.
Referenced by Siphash().
Member Data Documentation
key
uint64_t openage::util::Siphash::key[2] private
The key to use for hashing.
As two 64-bit little-endian words.
Definition at line 65 of file hash.h.
Referenced by digest(), set_key(), and Siphash().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/hash.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/hash.cpp