openage: openage::Civilisation Class Reference
openage::Civilisation Class Reference
#include <civilisation.h>
Public Member Functions
Civilisation (const GameSpec &spec, int id)
std::vector< std::shared_ptr< UnitTypeMeta > > object_meta () const
std::vector< index_t > get_category (const std::string &c) const
std::vector< std::string > get_type_categories () const
const gamedata::building_unit * get_building_data (index_t unit_id) const
void initialise_unit_types (const GameSpec &spec)
Public Attributes
const int civ_id
const std::string civ_name
Private Member Functions
void add_to_category (const std::string &c, index_t type)
Private Attributes
std::vector< std::shared_ptr< UnitTypeMeta > > civ_objects
std::vector< std::string > all_categories
std::unordered_map< std::string, std::vector< index_t > > categories
std::unordered_map< index_t, const gamedata::building_unit * > buildings
Detailed Description
contains the initial tech structure for one civilisation
Definition at line 17 of file civilisation.h.
Constructor & Destructor Documentation
Civilisation()
openage::Civilisation::Civilisation (const GameSpec & spec, int id)
Definition at line 11 of file civilisation.cpp.
     :
     civ_id{id},
     civ_name{spec.get_civ_name(id)} {
     this->initialise_unit_types(spec);
 }
Member Function Documentation
add_to_category()
void openage::Civilisation::add_to_category (const std::string & c, index_t type) private
creates and adds items to categories
Definition at line 56 of file civilisation.cpp.
{
     if (this->categories.count(c) == 0) {
         this->all_categories.push_back(c);
         this->categories[c] = std::vector<index_t>();
     }
     this->categories[c].push_back(type);
 }
References all_categories, and categories.
Referenced by initialise_unit_types().
get_building_data()
const gamedata::building_unit * openage::Civilisation::get_building_data (index_t unit_id) const
gamedata for a building
Definition at line 38 of file civilisation.cpp.
{
     if (this->buildings.count(unit_id) == 0) {
         log::log(MSG(info) << "  -> ignoring unit_id: " << unit_id);
         return nullptr;
     }
     return this->buildings.at(unit_id);
 }
References buildings, openage::log::info(), openage::log::log(), and MSG.
get_category()
std::vector< index_t > openage::Civilisation::get_category (const std::string & c) const
return all types in a particular named category
Definition at line 24 of file civilisation.cpp.
{
     auto cat = this->categories.find(c);
     if (cat == this->categories.end()) {
         return std::vector<index_t>();
     }
     return cat->second;
 }
References categories.
get_type_categories()
std::vector< std::string > openage::Civilisation::get_type_categories () const
return all used categories, such as living, building or projectile
Definition at line 33 of file civilisation.cpp.
{
     return this->all_categories;
 }
References all_categories.
initialise_unit_types()
void openage::Civilisation::initialise_unit_types (const GameSpec & spec)
initialise the unit meta data
Definition at line 47 of file civilisation.cpp.
{
     log::log(MSG(dbg) << "Init units of civilisation " << civ_name);
     spec.create_unit_types(this->civ_objects, this->civ_id);
     for (auto &type : this->civ_objects) {
         this->add_to_category(type->name(), type->id());
     }
 }
References add_to_category(), civ_id, civ_name, civ_objects, openage::GameSpec::create_unit_types(), openage::log::dbg(), openage::log::log(), and MSG.
object_meta()
std::vector< std::shared_ptr< UnitTypeMeta > > openage::Civilisation::object_meta () const
return all the objects available to this civ
Definition at line 19 of file civilisation.cpp.
{
     return civ_objects;
 }
References civ_objects.
Referenced by openage::Player::initialise_unit_types().
Member Data Documentation
all_categories
std::vector<std::string> openage::Civilisation::all_categories private
all available categories of units
Definition at line 71 of file civilisation.h.
Referenced by add_to_category(), and get_type_categories().
buildings
std::unordered_map<index_t, const gamedata::building_unit *> openage::Civilisation::buildings private
used for annex creation
Definition at line 81 of file civilisation.h.
Referenced by get_building_data().
categories
std::unordered_map<std::string, std::vector<index_t> > openage::Civilisation::categories private
category lists
Definition at line 76 of file civilisation.h.
Referenced by add_to_category(), and get_category().
civ_id
const int openage::Civilisation::civ_id
civ index
Definition at line 24 of file civilisation.h.
Referenced by initialise_unit_types().
civ_name
const std::string openage::Civilisation::civ_name
civ name
Definition at line 29 of file civilisation.h.
Referenced by initialise_unit_types(), and openage::Player::initialise_unit_types().
civ_objects
std::vector<std::shared_ptr<UnitTypeMeta> > openage::Civilisation::civ_objects private
unit types which can be produced by this civilisation.
Definition at line 66 of file civilisation.h.
Referenced by initialise_unit_types(), and object_meta().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gamestate/civilisation.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gamestate/civilisation.cpp