openage: openage::Texture Class Reference
openage::Texture Class Reference
A texture for rendering graphically.
#include <texture.h>
Public Member Functions
Texture (int width, int height, std::unique_ptr< uint32_t[]> data)
Create a texture from a rgba8 array.
Texture (const util::Path &filename, bool use_metafile=false)
Create a texture from a existing image file.
~Texture ()
void draw (const coord::CoordManager &mgr, coord::camhud pos, unsigned int mode=0, bool mirrored=false, int subid=0, unsigned player=0) const
Draws the texture at hud coordinates.
void draw (const coord::CoordManager &mgr, coord::camgame pos, unsigned int mode=0, bool mirrored=false, int subid=0, unsigned player=0) const
Draws the texture at game coordinates.
void draw (const coord::CoordManager &mgr, coord::phys3 pos, unsigned int mode=0, bool mirrored=false, int subid=0, unsigned player=0) const
Draws the texture at phys coordinates.
void draw (const coord::CoordManager &mgr, const Terrain &terrain, coord::tile pos, unsigned int mode, int subid, Texture *alpha_texture, int alpha_subid) const
Draws the texture at tile coordinates.
void draw (coord::viewport pos, unsigned int mode, bool mirrored, int subid, unsigned player, Texture *alpha_texture, int alpha_subid) const
Draws the texture at window coordinates.
void reload ()
Reload the image file.
const gamedata::subtexture * get_subtexture (uint64_t subid) const
Get the subtexture coordinates by its id.
size_t get_subtexture_count () const
void get_subtexture_size (uint64_t subid, int *w, int *h) const
Fetch the size of the given subtexture.
void get_subtexture_coordinates (uint64_t subid, float *txl, float *txr, float *txt, float *txb) const
get atlas subtexture coordinates.
void get_subtexture_coordinates (const gamedata::subtexture *subtex, float *txl, float *txr, float *txt, float *txb) const
void fix_hotspots (unsigned x, unsigned y)
fixes the hotspots of all subtextures to (x,y).
void activate_alphamask (Texture *mask, uint64_t subid)
activates the influence of a given alpha mask to this texture.
void disable_alphamask ()
disable a previously activated alpha mask.
GLuint get_texture_id () const
returns the opengl texture id of this texture.
Public Attributes
int w
int h
Private Member Functions
void load ()
void load_in_glthread () const
The texture loadin must occur on the thread that manages the gl context.
GLuint make_gl_texture (int iformat, int oformat, int w, int h, void *) const
void unload ()
Private Attributes
std::unique_ptr< gl_texture_buffer > buffer
std::vector< gamedata::subtexture > subtextures
bool use_metafile
util::Path filename
Detailed Description
A texture for rendering graphically.
You may believe it or not, but this class represents a single texture, which can be drawn on the screen.
The class supports subtextures, so that one big texture can contain several small images. These are the ones actually to be rendered.
Definition at line 71 of file texture.h.
Constructor & Destructor Documentation
Texture() [1/2]
openage::Texture::Texture (int width, int height, std::unique_ptr< uint32_t[]> data)
Create a texture from a rgba8 array.
It will have w * h * 32bit storage.
Definition at line 37 of file texture.cpp.
     :
     use_metafile{false} {
     ENSURE(glGenBuffers != nullptr, "gl not initialized properly");
     this->w = width;
     this->h = height;
     this->buffer = std::make_unique<gl_texture_buffer>();
     this->buffer->transferred = false;
     this->buffer->texture_format_in = GL_RGBA8;
     this->buffer->texture_format_out = GL_RGBA;
     this->buffer->data = std::move(data);
     this->subtextures.push_back({0, 0, this->w, this->h, this->w/2, this->h/2});
 }
Texture() [2/2]
openage::Texture::Texture (const util::Path & filename, bool use_metafile = false)
Create a texture from a existing image file.
For supported image file types, see the SDL_Image initialization in the engine.
Definition at line 52 of file texture.cpp.
     :
     use_metafile{use_metafile},
     filename{filename} {
     // load the texture upon creation
     this->load();
 }
References use_metafile.
~Texture()
openage::Texture::~Texture ()
Definition at line 185 of file texture.cpp.
                   {
     this->unload();
 }
References unload().
Member Function Documentation
activate_alphamask()
void openage::Texture::activate_alphamask (Texture * mask, uint64_t subid)
activates the influence of a given alpha mask to this texture.
disable_alphamask()
void openage::Texture::disable_alphamask ()
disable a previously activated alpha mask.
draw() [1/5]
void openage::Texture::draw (const coord::CoordManager & mgr, coord::camhud pos, unsigned int mode = 0, bool mirrored = false, int subid = 0, unsigned player = 0) const
Draws the texture at hud coordinates.
Definition at line 198 of file texture.cpp.
{
     this->draw(pos.to_viewport(mgr), mode, mirrored, subid, player, nullptr, -1);
 }
References openage::coord::camhud::to_viewport().
Referenced by openage::UnitTexture::draw(), draw(), openage::Terrain::draw(), openage::GameRenderer::on_draw(), and openage::UnitTexture::sample().
draw() [2/5]
void openage::Texture::draw (const coord::CoordManager & mgr, coord::camgame pos, unsigned int mode = 0, bool mirrored = false, int subid = 0, unsigned player = 0) const
Draws the texture at game coordinates.
Definition at line 205 of file texture.cpp.
{
     this->draw(pos.to_viewport(mgr), mode, mirrored, subid, player, nullptr, -1);
 }
References draw(), and openage::coord::camgame::to_viewport().
draw() [3/5]
void openage::Texture::draw (const coord::CoordManager & mgr, coord::phys3 pos, unsigned int mode = 0, bool mirrored = false, int subid = 0, unsigned player = 0) const
Draws the texture at phys coordinates.
Definition at line 212 of file texture.cpp.
{
     this->draw(pos.to_viewport(mgr), mode, mirrored, subid, player, nullptr, -1);
 }
References draw(), and openage::coord::phys3::to_viewport().
draw() [4/5]
void openage::Texture::draw (const coord::CoordManager & mgr, const Terrain & terrain, coord::tile pos, unsigned int mode, int subid, Texture * alpha_texture, int alpha_subid) const
Draws the texture at tile coordinates.
Definition at line 219 of file texture.cpp.
{
     // currently used for drawing terrain tiles.
     this->draw(pos.to_viewport(mgr, terrain), mode, false,
                subid, 0, alpha_texture, alpha_subid);
 }
References draw(), and openage::coord::tile::to_viewport().
draw() [5/5]
void openage::Texture::draw (coord::viewport pos, unsigned int mode, bool mirrored, int subid, unsigned player, Texture * alpha_texture, int alpha_subid) const
Draws the texture at window coordinates.
Definition at line 229 of file texture.cpp.
{
     this->load_in_glthread();
     glColor4f(1, 1, 1, 1);
     bool use_playercolors = false;
     bool use_alphashader = false;
     const gamedata::subtexture *mtx;
     int *pos_id, *texcoord_id, *masktexcoord_id;
     // is this texture drawn with an alpha mask?
     if ((mode & ALPHAMASKED) && alpha_subid >= 0 && alpha_texture != nullptr) {
         alphamask_shader::program->use();
         // bind the alpha mask texture to slot 1
         glActiveTexture(GL_TEXTURE1);
         glEnable(GL_TEXTURE_2D);
         glBindTexture(GL_TEXTURE_2D, alpha_texture->get_texture_id());
         // get the alphamask subtexture (the blend mask!)
         mtx = alpha_texture->get_subtexture(alpha_subid);
         pos_id = &alphamask_shader::program->pos_id;
         texcoord_id = &alphamask_shader::base_coord;
         masktexcoord_id = &alphamask_shader::mask_coord;
         use_alphashader = true;
     }
     // is this texure drawn with replaced pixels for team coloring?
     else if (mode & PLAYERCOLORED) {
         teamcolor_shader::program->use();
         //set the desired player id in the shader
         glUniform1i(teamcolor_shader::player_id_var, player);
         pos_id = &teamcolor_shader::program->pos_id;
         texcoord_id = &teamcolor_shader::tex_coord;
         use_playercolors = true;
     }
     // mkay, we just draw the plain texture otherwise.
     else {
         texture_shader::program->use();
         pos_id = &texture_shader::program->pos_id;
         texcoord_id = &texture_shader::tex_coord;
     }
     glActiveTexture(GL_TEXTURE0);
     glEnable(GL_TEXTURE_2D);
     glBindTexture(GL_TEXTURE_2D, this->buffer->id);
     const gamedata::subtexture *tx = this->get_subtexture(subid);
     int left, right, top, bottom;
     // coordinates where the texture will be drawn on screen.
     bottom  = pos.y      - (tx->h - tx->cy);
     top     = bottom + tx->h;
     if (not mirrored) {
         left  = pos.x - tx->cx;
         right = left + tx->w;
     } else {
         left  = pos.x + tx->cx;
         right = left - tx->w;
     }
     // convert the texture boundaries to float
     // these will be the vertex coordinates.
     float leftf, rightf, topf, bottomf;
     leftf   = (float) left;
     rightf  = (float) right;
     topf    = (float) top;
     bottomf = (float) bottom;
     // subtexture coordinates
     // left, right, top and bottom bounds as coordinates
     // these pick the requested area out of the big texture.
     float txl, txr, txt, txb;
     this->get_subtexture_coordinates(tx, &txl, &txr, &txt, &txb);
     float mtxl=0, mtxr=0, mtxt=0, mtxb=0;
     if (use_alphashader) {
         alpha_texture->get_subtexture_coordinates(mtx, &mtxl, &mtxr, &mtxt, &mtxb);
     }
     // this array will be uploaded to the GPU.
     // it contains all dynamic vertex data (position, tex coordinates, mask coordinates)
     float vdata[] {
         leftf,  topf,
         leftf,  bottomf,
         rightf, bottomf,
         rightf, topf,
         txl,    txt,
         txl,    txb,
         txr,    txb,
         txr,    txt,
         mtxl,   mtxt,
         mtxl,   mtxb,
         mtxr,   mtxb,
         mtxr,   mtxt
     };
     // store vertex buffer data, \todo prepare this sometime earlier.
     glBindBuffer(GL_ARRAY_BUFFER, this->buffer->vertbuf);
     glBufferData(GL_ARRAY_BUFFER, sizeof(vdata), vdata, GL_STREAM_DRAW);
     // enable vertex buffer and bind it to the vertex attribute
     glEnableVertexAttribArray(*pos_id);
     glEnableVertexAttribArray(*texcoord_id);
     if (use_alphashader) {
         glEnableVertexAttribArray(*masktexcoord_id);
     }
     // set data types, offsets in the vdata array
     glVertexAttribPointer(*pos_id,      2, GL_FLOAT, GL_FALSE, 0, (void *)(0));
     glVertexAttribPointer(*texcoord_id, 2, GL_FLOAT, GL_FALSE, 0, (void *)(sizeof(float) * 8));
     if (use_alphashader) {
         glVertexAttribPointer(*masktexcoord_id, 2, GL_FLOAT, GL_FALSE, 0, (void *)(sizeof(float) * 8 * 2));
     }
     // draw the vertex array
     glDrawArrays(GL_QUADS, 0, 4);
     // unbind the current buffer
     glBindBuffer(GL_ARRAY_BUFFER, 0);
     glDisableVertexAttribArray(*pos_id);
     glDisableVertexAttribArray(*texcoord_id);
     if (use_alphashader) {
         glDisableVertexAttribArray(*masktexcoord_id);
     }
     // disable the shaders.
     if (use_playercolors) {
         teamcolor_shader::program->stopusing();
     } else if (use_alphashader) {
         alphamask_shader::program->stopusing();
         glActiveTexture(GL_TEXTURE1);
         glDisable(GL_TEXTURE_2D);
     } else {
         texture_shader::program->stopusing();
     }
     glActiveTexture(GL_TEXTURE0);
     glDisable(GL_TEXTURE_2D);
     /*
     int size = 2;
     float r = 1.0f, g = 1.0f, b = 0.0f;
     glPushMatrix();
     glTranslatef(leftf, bottomf, 0);
     glColor3f(r, g, b);
     glBegin(GL_TRIANGLES);
     glVertex3f(-size, -size, 0);
     glVertex3f(-size, size, 0);
     glVertex3f(size, size, 0);
     glVertex3f(size, size, 0);
     glVertex3f(-size, -size, 0);
     glVertex3f(size, -size, 0);
     glEnd();
     glPopMatrix();
     */
 }
References openage::ALPHAMASKED, openage::alphamask_shader::base_coord, buffer, get_subtexture(), get_subtexture_coordinates(), get_texture_id(), load_in_glthread(), openage::alphamask_shader::mask_coord, openage::teamcolor_shader::player_id_var, openage::PLAYERCOLORED, openage::shader::Program::pos_id, openage::texture_shader::program, openage::teamcolor_shader::program, openage::alphamask_shader::program, openage::shader::Program::stopusing(), openage::texture_shader::tex_coord, openage::teamcolor_shader::tex_coord, and openage::shader::Program::use().
fix_hotspots()
void openage::Texture::fix_hotspots (unsigned x, unsigned y)
fixes the hotspots of all subtextures to (x,y).
this is a temporary workaround; such fixes should actually be done in the convert script.
Definition at line 190 of file texture.cpp.
{
     for (auto &subtexture : this->subtextures) {
         subtexture.cx = x;
         subtexture.cy = y;
     }
 }
References subtextures.
get_subtexture()
const gamedata::subtexture * openage::Texture::get_subtexture (uint64_t subid) const
Get the subtexture coordinates by its id.
Definition at line 400 of file texture.cpp.
{
     if (subid < this->subtextures.size()) {
         return &this->subtextures[subid];
     }
     else {
         throw Error{
             ERR << "Unknown subtexture requested for texture "
                 << this->filename << ": " << subid
         };
     }
 }
References ERR, filename, and subtextures.
Referenced by draw(), get_subtexture_coordinates(), get_subtexture_size(), openage::gui::native_size(), openage::gui::GuiTexture::normalizedTextureSubRect(), and openage::gui::GuiTexture::removedFromAtlas().
get_subtexture_coordinates() [1/2]
void openage::Texture::get_subtexture_coordinates (uint64_t subid, float * txl, float * txr, float * txt, float * txb) const
get atlas subtexture coordinates.
left, right, top and bottom bounds as coordinates these pick the requested area out of the big texture. returned as floats in range 0.0 to 1.0
Definition at line 413 of file texture.cpp.
{
     const gamedata::subtexture *tx = this->get_subtexture(subid);
     this->get_subtexture_coordinates(tx, txl, txr, txt, txb);
 }
References get_subtexture().
Referenced by draw().
get_subtexture_coordinates() [2/2]
void openage::Texture::get_subtexture_coordinates (const gamedata::subtexture * subtex, float * txl, float * txr, float * txt, float * txb) const
Definition at line 421 of file texture.cpp.
{
     *txl = ((float)tx->x)           /this->w;
     *txr = ((float)(tx->x + tx->w)) /this->w;
     *txt = ((float)tx->y)           /this->h;
     *txb = ((float)(tx->y + tx->h)) /this->h;
 }
References h, and w.
get_subtexture_count()
size_t openage::Texture::get_subtexture_count () const
Returns
the number of available subtextures
Definition at line 431 of file texture.cpp.
{
     return this->subtextures.size();
 }
References subtextures.
Referenced by openage::Terrain::calculate_masks(), openage::Terrain::create_tile_advice(), openage::UnitTexture::draw(), openage::UnitTexture::initialise(), openage::gui::isAtlasTexture(), and openage::UnitTexture::subtexture().
get_subtexture_size()
void openage::Texture::get_subtexture_size (uint64_t subid, int * w, int * h) const
Fetch the size of the given subtexture.
Parameters
subid index of the requested subtexture
w the subtexture width
h the subtexture height
Definition at line 436 of file texture.cpp.
{
     const gamedata::subtexture *subtex = this->get_subtexture(subid);
     *w = subtex->w;
     *h = subtex->h;
 }
References get_subtexture(), h, and w.
get_texture_id()
GLuint openage::Texture::get_texture_id () const
returns the opengl texture id of this texture.
Definition at line 443 of file texture.cpp.
{
     this->load_in_glthread();
     return this->buffer->id;
 }
References buffer, and load_in_glthread().
Referenced by draw(), and openage::gui::GuiTexture::textureId().
load()
void openage::Texture::load () private
Definition at line 61 of file texture.cpp.
                    {
     // \todo use libpng directly.
     SDL_Surface *surface;
     // \todo this will break if there is no native path.
     //       but then we need to load the image
     //       from the buffer provided by this->filename.open_r().read().
     std::string native_path = this->filename.resolve_native_path();
     surface = IMG_Load(native_path.c_str());
     if (!surface) {
         throw Error(
             MSG(err) <<
             "SDL_Image could not load texture from "
             << this->filename << " (= " << native_path << "): "
             << IMG_GetError()
         );
     } else {
         log::log(MSG(dbg) << "Texture has been loaded from " << native_path);
     }
     this->buffer = std::make_unique<gl_texture_buffer>();
     // glTexImage2D format determination
     switch (surface->format->BytesPerPixel) {
     case 3: // RGB 24 bit
         this->buffer->texture_format_in = GL_RGB8;
         this->buffer->texture_format_out
         = surface->format->Rmask == 0x000000ff
         ? GL_RGB
         : GL_BGR;
         break;
     case 4: // RGBA 32 bit
         this->buffer->texture_format_in = GL_RGBA8;
         this->buffer->texture_format_out
         = surface->format->Rmask == 0x000000ff
         ? GL_RGBA
         : GL_BGRA;
         break;
     default:
         throw Error(MSG(err) <<
             "Unknown texture bit depth for " << this->filename << ": " <<
             surface->format->BytesPerPixel << " bytes per pixel");
         break;
     }
     this->w = surface->w;
     this->h = surface->h;
     // temporary buffer for pixel data
     this->buffer->transferred = false;
     this->buffer->data = std::make_unique<uint32_t[]>(this->w * this->h);
     std::memcpy(
         this->buffer->data.get(),
         surface->pixels,
         this->w * this->h * surface->format->BytesPerPixel
     );
     SDL_FreeSurface(surface);
     if (use_metafile) {
         // get subtexture information from the exported metainfo file
         this->subtextures = util::read_csv_file<gamedata::subtexture>(
             filename.with_suffix(".docx")
         );
     }
     else {
         // we don't have a subtexture description file.
         // use the whole image as one texture then.
         gamedata::subtexture s{0, 0, this->w, this->h, this->w/2, this->h/2};
         this->subtextures.push_back(s);
     }
 }
References buffer, openage::log::dbg(), openage::log::err(), filename, h, openage::log::log(), MSG, openage::util::Path::resolve_native_path(), subtextures, use_metafile, w, and openage::util::Path::with_suffix().
Referenced by reload().
load_in_glthread()
void openage::Texture::load_in_glthread () const private
The texture loadin must occur on the thread that manages the gl context.
Definition at line 157 of file texture.cpp.
{
     if (not this->buffer->transferred) {
         this->buffer->id = this->make_gl_texture(
             this->buffer->texture_format_in,
             this->buffer->texture_format_out,
             this->w,
             this->h,
             this->buffer->data.get()
         );
         this->buffer->data = nullptr;
         glGenBuffers(1, &this->buffer->vertbuf);
         this->buffer->transferred = true;
     }
 }
References buffer, and make_gl_texture().
Referenced by draw(), and get_texture_id().
make_gl_texture()
GLuint openage::Texture::make_gl_texture (int iformat, int oformat, int w, int h, void * data) const private
Definition at line 137 of file texture.cpp.
{
     // generate 1 texture handle
     GLuint textureid;
     glGenTextures(1, &textureid);
     glBindTexture(GL_TEXTURE_2D, textureid);
     // sdl surface -> opengl texture
     glTexImage2D(
         GL_TEXTURE_2D, 0,
         iformat, w, h, 0,
         oformat, GL_UNSIGNED_BYTE, data
     );
     // settings for later drawing
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
     return textureid;
 }
References h, and w.
Referenced by load_in_glthread().
reload()
void openage::Texture::reload ()
Reload the image file.
Used for inotify refreshing.
Definition at line 179 of file texture.cpp.
                      {
     this->unload();
     this->load();
 }
References load(), and unload().
unload()
void openage::Texture::unload () private
Definition at line 173 of file texture.cpp.
                      {
     glDeleteTextures(1, &this->buffer->id);
     glDeleteBuffers(1, &this->buffer->vertbuf);
 }
References buffer.
Referenced by reload(), and ~Texture().
Member Data Documentation
buffer
std::unique_ptr<gl_texture_buffer> openage::Texture::buffer private
Definition at line 170 of file texture.h.
Referenced by draw(), get_texture_id(), load(), load_in_glthread(), and unload().
filename
util::Path openage::Texture::filename private
Definition at line 174 of file texture.h.
Referenced by get_subtexture(), and load().
h
int openage::Texture::h
Definition at line 74 of file texture.h.
Referenced by get_subtexture_coordinates(), get_subtexture_size(), load(), make_gl_texture(), openage::UnitTexture::size(), and openage::gui::GuiTextureFactory::textureByteCount().
subtextures
std::vector<gamedata::subtexture> openage::Texture::subtextures private
Definition at line 171 of file texture.h.
Referenced by fix_hotspots(), get_subtexture(), get_subtexture_count(), and load().
use_metafile
bool openage::Texture::use_metafile private
Definition at line 172 of file texture.h.
Referenced by load(), and Texture().
w
int openage::Texture::w
Definition at line 73 of file texture.h.
Referenced by get_subtexture_coordinates(), get_subtexture_size(), load(), make_gl_texture(), openage::UnitTexture::size(), and openage::gui::GuiTextureFactory::textureByteCount().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/texture.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/texture.cpp