openage: openage::Player Class Reference
openage::Player Class Reference
#include <player.h>
Public Member Functions
Player (Civilisation *civ, unsigned int number, std::string name)
bool operator== (const Player &other) const
checks if two players are the same
bool is_enemy (const Player &) const
the specified player is an enemy of this player
bool is_ally (const Player &) const
the specified player is an ally of this player
bool owns (Unit &) const
this player owns the specified unit
void receive (const ResourceBundle &amount)
add to stockpile
void receive (const game_resource resource, double amount)
bool can_receive (const ResourceBundle &amount) const
Check if can add to stockpile.
bool can_receive (const game_resource resource, double amount) const
bool deduct (const ResourceBundle &amount)
remove from stockpile if available
bool deduct (const game_resource resource, double amount)
bool can_deduct (const ResourceBundle &amount) const
Check if the player has enough resources to deduct the given amount.
bool can_deduct (const game_resource resource, double amount) const
double amount (const game_resource resource) const
current stockpile amount
bool can_make (const UnitType &type) const
Check if the player can make a new unit of the given type.
size_t type_count ()
total number of unit types available
UnitType * get_type (index_t type_id) const
unit types by aoe gamedata unit ids – the unit type which corresponds to an aoe unit id
UnitType * get_type_index (size_t type_index) const
unit types by list index – a continuous array of all types probably not a useful function / can be removed
void initialise_unit_types ()
initialise with the base tech level
void active_unit_added (Unit *unit, bool from_pending=false)
Called when a unit is created and active.
void active_unit_removed (Unit *unit)
Called when a unit is destroyed.
void killed_unit (const Unit &unit)
Called when a unit is killed by this player.
void advance_age ()
Advance to next age;.
int get_units_have (int type_id) const
Get the number of units the player has for each unit type id.
int get_units_had (int type_id) const
Get the number of units the player ever had for each unit type id.
int get_units_pending (int type_id) const
Get the number of units the player has being made for each unit type id.
int get_age () const
Get the current age.
int get_workforce_count () const
The number of units considered part of the workforce.
Public Attributes
const unsigned int player_number
values 0 .
const unsigned int color
values 1 .
const Civilisation * civ
civilisation and techs of this player
const std::string name
visible name of this player
Team * team
the team of this player nullptr if member of no team
PopulationTracker population
Keeps track of the population information.
PlayerScore score
The score of the player.
Private Member Functions
bool is_unit_pending (Unit *unit) const
void on_resources_change ()
Called when the resources amounts change.
Private Attributes
ResourceBundle resources
The resources this player currently has.
ResourceBundle resources_capacity
The resources capacities this player currently has.
unit_type_list available_objects
unit types which can be produced by this player.
std::unordered_map< index_t, UnitType * > available_ids
available objects mapped using type id unit ids -> unit type for that id
std::unordered_map< int, int > units_have
The number of units the player has for each unit type id.
std::unordered_map< int, int > units_had
The number of units the player ever had for each unit type id.
std::unordered_map< int, int > units_pending
int age
The current age.
Detailed Description
Definition at line 19 of file player.h.
Constructor & Destructor Documentation
Player()
openage::Player::Player (Civilisation * civ, unsigned int number, std::string name)
Definition at line 14 of file player.cpp.
     :
     player_number{number},
     color{number},
     civ{civ},
     name{name},
     team{nullptr},
     population{0, 200}, // \todo change, get population cap max from game options
     score{this},
     age{1} { // \todo change, get starting age from game options
     // starting resources
     // \todo change, get starting resources from game options
     this->resources.set_all(1000);
     // \todo change, get starting resources capacity from game options or nyan
     this->resources_capacity.set_all(math::DOUBLE_INF / 2); // half to avoid overflows
     this->on_resources_change();
 }
Member Function Documentation
active_unit_added()
void openage::Player::active_unit_added (Unit * unit, bool from_pending = false)
Called when a unit is created and active.
If the unit was pending when create (constuction site, training) the method must be called again when the unit activates (with the from_penging param set to true)
Definition at line 148 of file player.cpp.
{
     // check if unit is actually active
     if (this->is_unit_pending(unit)) {
         this->units_pending[unit->unit_type->id()] += 1;
         return;
     }
     if (from_pending) {
         this->units_pending[unit->unit_type->id()] -= 1;
     }
     this->units_have[unit->unit_type->id()] += 1;
     this->units_had[unit->unit_type->id()] += 1;
     // \todo handle here building dependencies
     // population
     if (unit->has_attribute(attr_type::population)) {
         auto popul = unit->get_attribute<attr_type::population>();
         if (popul.demand > 0) {
             this->population.demand_population(popul.demand);
         }
         if (popul.capacity > 0) {
             this->population.add_capacity(popul.capacity);
         }
     }
     // resources capacity
     if (unit->has_attribute(attr_type::storage)) {
         auto storage = unit->get_attribute<attr_type::storage>();
         this->resources_capacity += storage.capacity;
         this->on_resources_change();
     }
     // score
     // \todo improve selectors
     if (unit->unit_type->id() == 82 || unit->unit_type->id() == 276) { // Castle, Wonder
         this->score.add_score(score_category::society, unit->unit_type->cost.get(*this).sum() * 0.2);
     } else if (unit->has_attribute(attr_type::building) || unit->has_attribute(attr_type::population)) { // building, living
         this->score.add_score(score_category::economy, unit->unit_type->cost.get(*this).sum() * 0.2);
     }
     // \todo handle here on create unit triggers
     // \todo check for unit based win conditions
 }
References openage::PopulationTracker::add_capacity(), openage::Score::add_score(), openage::building, openage::UnitType::cost, openage::PopulationTracker::demand_population(), openage::economy, openage::ResourceCost::get(), openage::Unit::get_attribute(), openage::Unit::has_attribute(), openage::UnitType::id(), is_unit_pending(), on_resources_change(), openage::population, population, resources_capacity, score, openage::society, openage::storage, openage::ResourceBundle::sum(), openage::Unit::unit_type, units_had, units_have, and units_pending.
active_unit_removed()
void openage::Player::active_unit_removed (Unit * unit)
Called when a unit is destroyed.
Definition at line 193 of file player.cpp.
{
     // check if unit is actually active
     if (this->is_unit_pending(unit)) {
         this->units_pending[unit->unit_type->id()] -= 1;
         return;
     }
     this->units_have[unit->unit_type->id()] -= 1;
     // \todo handle here building dependencies
     // population
     if (unit->has_attribute(attr_type::population)) {
         auto popul = unit->get_attribute<attr_type::population>();
         if (popul.demand > 0) {
             this->population.free_population(popul.demand);
         }
         if (popul.capacity > 0) {
             this->population.remove_capacity(popul.capacity);
         }
     }
     // resources capacity
     if (unit->has_attribute(attr_type::storage)) {
         auto storage = unit->get_attribute<attr_type::storage>();
         this->resources_capacity -= storage.capacity;
         this->on_resources_change();
     }
     // score
     // \todo improve selectors
     if (unit->unit_type->id() == 82 || unit->unit_type->id() == 276) { // Castle, Wonder
         // nothing
     } else if (unit->has_attribute(attr_type::building) || unit->has_attribute(attr_type::population)) { // building, living
         this->score.remove_score(score_category::economy, unit->unit_type->cost.get(*this).sum() * 0.2);
     }
     // \todo handle here on death unit triggers
     // \todo check for unit based win conditions
 }
References openage::building, openage::UnitType::cost, openage::economy, openage::PopulationTracker::free_population(), openage::ResourceCost::get(), openage::Unit::get_attribute(), openage::Unit::has_attribute(), openage::UnitType::id(), is_unit_pending(), on_resources_change(), openage::population, population, openage::PopulationTracker::remove_capacity(), openage::Score::remove_score(), resources_capacity, score, openage::storage, openage::ResourceBundle::sum(), openage::Unit::unit_type, units_have, and units_pending.
advance_age()
void openage::Player::advance_age ()
Advance to next age;.
Definition at line 238 of file player.cpp.
{
     this->age += 1;
 }
References age.
Referenced by openage::Research::apply().
amount()
double openage::Player::amount (const game_resource resource) const
current stockpile amount
Definition at line 105 of file player.cpp.
{
     return this->resources.get(resource);
 }
References openage::ResourceBundle::get(), and resources.
Referenced by can_deduct(), can_receive(), deduct(), and receive().
can_deduct() [1/2]
bool openage::Player::can_deduct (const ResourceBundle & amount) const
Check if the player has enough resources to deduct the given amount.
Definition at line 97 of file player.cpp.
{
     return this->resources.has(amount);
 }
References openage::ResourceBundle::has(), and resources.
Referenced by can_make().
can_deduct() [2/2]
bool openage::Player::can_deduct (const game_resource resource, double amount) const
Definition at line 101 of file player.cpp.
{
     return this->resources.get(resource) >= amount;
 }
References amount(), openage::ResourceBundle::get(), and resources.
can_make()
bool openage::Player::can_make (const UnitType & type) const
Check if the player can make a new unit of the given type.
Definition at line 109 of file player.cpp.
{
     return this->can_deduct(type.cost.get(*this)) &&
            this->get_units_have(type.id()) + this->get_units_pending(type.id()) < type.have_limit &&
            this->get_units_had(type.id()) + this->get_units_pending(type.id()) < type.had_limit;
 }
References can_deduct(), openage::UnitType::cost, openage::ResourceCost::get(), get_units_have(), get_units_pending(), openage::UnitType::had_limit, openage::UnitType::have_limit, and openage::UnitType::id().
can_receive() [1/2]
bool openage::Player::can_receive (const ResourceBundle & amount) const
Check if can add to stockpile.
Definition at line 72 of file player.cpp.
{
     return this->resources_capacity.has(this->resources, amount);
 }
References openage::ResourceBundle::has(), resources, and resources_capacity.
can_receive() [2/2]
bool openage::Player::can_receive (const game_resource resource, double amount) const
Definition at line 76 of file player.cpp.
{
     return this->resources_capacity.get(resource) >= this->resources.get(resource) + amount;
 }
References amount(), openage::ResourceBundle::get(), resources, and resources_capacity.
deduct() [1/2]
bool openage::Player::deduct (const ResourceBundle & amount)
remove from stockpile if available
Definition at line 80 of file player.cpp.
{
     if (this->resources.deduct(amount)) {
         this->on_resources_change();
         return true;
     }
     return false;
 }
References openage::ResourceBundle::deduct(), on_resources_change(), and resources.
Referenced by openage::Market::buy(), and openage::Market::sell().
deduct() [2/2]
bool openage::Player::deduct (const game_resource resource, double amount)
Definition at line 88 of file player.cpp.
{
     if (this->resources[resource] >= amount) {
         this->resources[resource] -= amount;
         this->on_resources_change();
         return true;
     }
     return false;
 }
References amount(), on_resources_change(), openage::resource, and resources.
get_age()
int openage::Player::get_age () const inline
Get the current age.
The first age has the value 1.
Definition at line 179 of file player.h.
 { return age; }
References age.
get_type()
UnitType * openage::Player::get_type (index_t type_id) const
unit types by aoe gamedata unit ids – the unit type which corresponds to an aoe unit id
Definition at line 119 of file player.cpp.
{
     if (this->available_ids.count(type_id) == 0) {
         if (type_id > 0) {
             log::log(MSG(info) << "  -> ignoring type_id: " << type_id);
         }
         return nullptr;
     }
     return this->available_ids.at(type_id);
 }
References available_ids, openage::log::info(), openage::log::log(), and MSG.
Referenced by openage::Generator::add_units(), openage::ObjectProducer::initialise(), openage::MovableProducer::initialise(), openage::LivingProducer::initialise(), openage::BuildingProducer::initialise(), openage::gameio::load_unit(), openage::BuildingProducer::make_annex(), openage::ActionMode::on_game_control_set(), openage::EditorMode::paint_entity_at(), and openage::UnitType::parent_type().
get_type_index()
UnitType * openage::Player::get_type_index (size_t type_index) const
unit types by list index – a continuous array of all types probably not a useful function / can be removed
Definition at line 129 of file player.cpp.
{
     if (type_index < available_objects.size()) {
         return available_objects.at(type_index).get();
     }
     log::log(MSG(info) << "  -> ignoring type_index: " << type_index);
     return nullptr;
 }
References available_objects, openage::log::info(), openage::log::log(), and MSG.
get_units_had()
int openage::Player::get_units_had (int type_id) const
Get the number of units the player ever had for each unit type id.
Definition at line 262 of file player.cpp.
{
     if (this->units_had.count(type_id)) {
         return this->units_had.at(type_id);
     }
     return 0;
 }
References units_had.
get_units_have()
int openage::Player::get_units_have (int type_id) const
Get the number of units the player has for each unit type id.
Definition at line 255 of file player.cpp.
{
     if (this->units_have.count(type_id)) {
         return this->units_have.at(type_id);
     }
     return 0;
 }
References units_have.
Referenced by can_make().
get_units_pending()
int openage::Player::get_units_pending (int type_id) const
Get the number of units the player has being made for each unit type id.
Definition at line 269 of file player.cpp.
{
     if (this->units_pending.count(type_id)) {
         return this->units_pending.at(type_id);
     }
     return 0;
 }
References units_pending.
Referenced by can_make().
get_workforce_count()
int openage::Player::get_workforce_count () const
The number of units considered part of the workforce.
Definition at line 281 of file player.cpp.
{
     // \todo get all units tagged as work force
     return this->units_have.at(83) + this->units_have.at(293) + // villagers
            this->units_have.at(13) + // fishing ship
            this->units_have.at(128) + // trade cart
            this->units_have.at(545); // transport ship
 }
References units_have.
Referenced by openage::ResourceCost::get().
initialise_unit_types()
void openage::Player::initialise_unit_types ()
initialise with the base tech level
Definition at line 138 of file player.cpp.
{
     log::log(MSG(info) << name << " has civilisation " << this->civ->civ_name);
     for (auto &type : this->civ->object_meta()) {
         auto shared_type = type->init(*this);
         index_t id = shared_type->id();
         this->available_objects.emplace_back(shared_type);
         this->available_ids[id] = shared_type.get();
     }
 }
References available_ids, available_objects, civ, openage::Civilisation::civ_name, openage::log::info(), openage::log::log(), MSG, name, and openage::Civilisation::object_meta().
is_ally()
bool openage::Player::is_ally (const Player & other) const
the specified player is an ally of this player
Definition at line 41 of file player.cpp.
{
     if (this->player_number == other.player_number) {
         return true; // same player
     }
     if (this->team && this->team->is_member(other)) {
         return true; // same team
     }
     // everyone else is enemy
     return false;
 }
References openage::Team::is_member(), player_number, and team.
Referenced by is_enemy().
is_enemy()
bool openage::Player::is_enemy (const Player & other) const
the specified player is an enemy of this player
Definition at line 36 of file player.cpp.
{
     return !this->is_ally(other);
 }
References is_ally().
is_unit_pending()
bool openage::Player::is_unit_pending (Unit * unit) const private
Definition at line 276 of file player.cpp.
{
     // \todo check aslo if unit is training
     return unit->has_attribute(attr_type::building) && unit->get_attribute<attr_type::building>().completed < 1.0f;
 }
References openage::building, openage::Unit::get_attribute(), and openage::Unit::has_attribute().
Referenced by active_unit_added(), and active_unit_removed().
killed_unit()
void openage::Player::killed_unit (const Unit & unit)
Called when a unit is killed by this player.
Definition at line 233 of file player.cpp.
{
     // score
     this->score.add_score(score_category::military, unit.unit_type->cost.get(*this).sum() * 0.2);
 }
References openage::Score::add_score(), openage::UnitType::cost, openage::ResourceCost::get(), openage::military, score, openage::ResourceBundle::sum(), and openage::Unit::unit_type.
on_resources_change()
void openage::Player::on_resources_change () private
Called when the resources amounts change.
Definition at line 242 of file player.cpp.
{
     // capacity overflow
     if (! (this->resources_capacity >= this->resources_capacity)) {
         this->resources.limit(this->resources_capacity);
     }
     // score
     this->score.update_resources(this->resources);
     // \todo check for resource based win conditions
 }
References openage::ResourceBundle::limit(), resources, resources_capacity, score, and openage::Score::update_resources().
Referenced by active_unit_added(), active_unit_removed(), deduct(), and receive().
operator==()
bool openage::Player::operator== (const Player & other) const
checks if two players are the same
Definition at line 32 of file player.cpp.
{
     return this->player_number == other.player_number;
 }
References player_number.
owns()
bool openage::Player::owns (Unit & unit) const
this player owns the specified unit
Definition at line 55 of file player.cpp.
{
     if (unit.has_attribute(attr_type::owner)) {
         return this == &unit.get_attribute<attr_type::owner>().player;
     }
     return false;
 }
References openage::Unit::get_attribute(), openage::Unit::has_attribute(), and openage::owner.
Referenced by openage::Unit::is_own_unit().
receive() [1/2]
void openage::Player::receive (const ResourceBundle & amount)
add to stockpile
Definition at line 62 of file player.cpp.
{
     this->resources += amount;
     this->on_resources_change();
 }
References amount(), on_resources_change(), and resources.
Referenced by openage::Market::buy(), and openage::Market::sell().
receive() [2/2]
void openage::Player::receive (const game_resource resource, double amount)
Definition at line 67 of file player.cpp.
{
     this->resources[resource] += amount;
     this->on_resources_change();
 }
References amount(), on_resources_change(), openage::resource, and resources.
type_count()
size_t openage::Player::type_count ()
total number of unit types available
Definition at line 115 of file player.cpp.
{
     return this->available_ids.size();
 }
References available_ids.
Member Data Documentation
age
int openage::Player::age private
The current age.
Definition at line 240 of file player.h.
Referenced by advance_age(), and get_age().
available_ids
std::unordered_map<index_t, UnitType *> openage::Player::available_ids private
available objects mapped using type id unit ids -> unit type for that id
Todo:
revisit, can be simplified?
Definition at line 217 of file player.h.
Referenced by get_type(), initialise_unit_types(), and type_count().
available_objects
unit_type_list openage::Player::available_objects private
unit types which can be produced by this player.
Todo:
revisit, can be simplified?
Definition at line 210 of file player.h.
Referenced by get_type_index(), and initialise_unit_types().
civ
const Civilisation* openage::Player::civ
civilisation and techs of this player
Definition at line 37 of file player.h.
Referenced by initialise_unit_types().
color
const unsigned int openage::Player::color
values 1 .
. player count would be better to have rgb color value
Definition at line 32 of file player.h.
Referenced by openage::ActionMode::render().
name
const std::string openage::Player::name
visible name of this player
Definition at line 42 of file player.h.
Referenced by openage.convert.dataformat.header_snippet.HeaderSnippet::__eq__(), openage.convert.dataformat.header_snippet.HeaderSnippet::__hash__(), openage.convert.dataformat.header_snippet.HeaderSnippet::__repr__(), openage.convert.dataformat.header_snippet.HeaderSnippet::get_file_name(), initialise_unit_types(), openage.util.fslike.path.Path::stem(), openage.util.fslike.path.Path::suffix(), and openage.util.fslike.path.Path::suffixes().
player_number
const unsigned int openage::Player::player_number
values 0 .
. player count - 1
Definition at line 26 of file player.h.
Referenced by is_ally(), and operator==().
population
PopulationTracker openage::Player::population
Keeps track of the population information.
Definition at line 128 of file player.h.
Referenced by active_unit_added(), and active_unit_removed().
resources
ResourceBundle openage::Player::resources private
The resources this player currently has.
Definition at line 194 of file player.h.
Referenced by amount(), can_deduct(), can_receive(), deduct(), on_resources_change(), and receive().
resources_capacity
ResourceBundle openage::Player::resources_capacity private
The resources capacities this player currently has.
Definition at line 199 of file player.h.
Referenced by active_unit_added(), active_unit_removed(), can_receive(), and on_resources_change().
score
PlayerScore openage::Player::score
The score of the player.
Definition at line 133 of file player.h.
Referenced by active_unit_added(), active_unit_removed(), killed_unit(), and on_resources_change().
team
Team* openage::Player::team
the team of this player nullptr if member of no team
Definition at line 48 of file player.h.
Referenced by openage::Team::add_member(), is_ally(), openage::Team::remove_member(), and openage::PlayerScore::update_score().
units_had
std::unordered_map<int, int> openage::Player::units_had private
The number of units the player ever had for each unit type id.
Used for unit dependencies (eg. Farm).
Definition at line 229 of file player.h.
Referenced by active_unit_added(), and get_units_had().
units_have
std::unordered_map<int, int> openage::Player::units_have private
The number of units the player has for each unit type id.
Used for and event triggers.
Definition at line 223 of file player.h.
Referenced by active_unit_added(), active_unit_removed(), get_units_have(), and get_workforce_count().
units_pending
std::unordered_map<int, int> openage::Player::units_pending private
Definition at line 235 of file player.h.
Referenced by active_unit_added(), active_unit_removed(), and get_units_pending().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gamestate/player.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gamestate/player.cpp