openage: openage::ObjectProducer Class Reference
openage::ObjectProducer Class Reference
#include <producer.h>
Public Member Functions
ObjectProducer (const Player &owner, const GameSpec &spec, const gamedata::unit_object *ud)
virtual ~ObjectProducer ()
int id () const override
int parent_id () const override
std::string name () const override
void initialise (Unit *, Player &) override
TerrainObject * place (Unit *, std::shared_ptr< Terrain >, coord::phys3) const override
Public Member Functions inherited from openage::UnitType
UnitType ()
bool match (class Unit *)
UnitType (const Player &owner)
virtual ~UnitType ()
virtual void reinitialise (Unit *, Player &)
bool operator== (const UnitType &other) const
bool operator!= (const UnitType &other) const
UnitTexture * default_texture ()
TerrainObject * place_beside (Unit *, TerrainObject const *) const
void copy_attributes (Unit *unit) const
void upgrade (const std::shared_ptr< AttributeContainer > &attr)
UnitType * parent_type () const
Protected Attributes
const GameSpec & dataspec
const gamedata::unit_object unit_data
bool decay
const Sound * on_create
const Sound * on_destroy
std::shared_ptr< Texture > terrain_outline
std::shared_ptr< UnitTexture > default_tex
int dead_unit_id
Additional Inherited Members
Public Attributes inherited from openage::UnitType
const Player & owner
std::vector< UnitReference > instances
std::vector< std::shared_ptr< UnitAbility > > type_abilities
Attributes default_attributes
ResourceCost cost
int have_limit
int had_limit
graphic_set graphics
coord::tile_delta foundation_size
gamedata::unit_classes unit_class
Detailed Description
base game data unit type
Definition at line 35 of file producer.h.
Constructor & Destructor Documentation
ObjectProducer()
openage::ObjectProducer::ObjectProducer (const Player & owner, const GameSpec & spec, const gamedata::unit_object * ud)
Definition at line 89 of file producer.cpp.
     :
     UnitType(owner),
     dataspec(spec),
     unit_data(*ud),
     terrain_outline{nullptr},
     default_tex{spec.get_unit_texture(ud->graphic_standing0)},
     dead_unit_id{ud->dead_unit_id} {
     // copy the class type
     this->unit_class = this->unit_data.unit_class;
     // for now just look for type names ending with "_D"
     this->decay = unit_data.name.substr(unit_data.name.length() - 2) == "_D";
     // find suitable sounds
     int creation_sound = this->unit_data.train_sound;
     int dying_sound = this->unit_data.sound_dying;
     if (creation_sound == -1) {
         creation_sound = this->unit_data.damage_sound;
     }
     if (creation_sound == -1) {
         creation_sound = this->unit_data.sound_selection;
     }
     if (dying_sound == -1) {
         dying_sound = 323; //generic explosion sound
     }
     on_create = spec.get_sound(creation_sound);
     on_destroy = spec.get_sound(dying_sound);
     // convert the float to the discrete foundation size...
     this->foundation_size = {
         static_cast<int>(this->unit_data.radius_x * 2),
         static_cast<int>(this->unit_data.radius_y * 2),
     };
     // shape of the outline
     if (this->unit_data.selection_shape > 1) {
         this->terrain_outline = radial_outline(this->unit_data.radius_x);
     }
     else {
         this->terrain_outline = square_outline(this->foundation_size);
     }
     // graphic set
     auto standing = spec.get_unit_texture(this->unit_data.graphic_standing0);
     if (!standing) {
         // indicates problems with data converion
         throw Error(MSG(err) << "Unit id " << this->unit_data.id0
             << " has invalid graphic data, try reconverting the data");
     }
     this->graphics[graphic_type::standing] = standing;
     auto dying_tex = spec.get_unit_texture(this->unit_data.dying_graphic);
     if (dying_tex) {
         this->graphics[graphic_type::dying] = dying_tex;
     }
     // default extra graphics
     this->graphics[graphic_type::attack] = this->graphics[graphic_type::standing];
     this->graphics[graphic_type::work] = this->graphics[graphic_type::standing];
     // pull extra graphics from unit commands
     auto cmds = spec.get_command_data(this->unit_data.id0);
     for (auto cmd : cmds) {
         // same attack / work graphic
         if (cmd->work_sprite_id == -1 && cmd->proceed_sprite_id > 0) {
             auto task = spec.get_unit_texture(cmd->proceed_sprite_id);
             if (task) {
                 this->graphics[graphic_type::work] = task;
                 this->graphics[graphic_type::attack] = task;
             }
         }
         // separate work and attack graphics
         if (cmd->work_sprite_id > 0 && cmd->proceed_sprite_id > 0 ) {
             auto attack = spec.get_unit_texture(cmd->proceed_sprite_id);
             auto work = spec.get_unit_texture(cmd->work_sprite_id);
             if (attack) {
                 this->graphics[graphic_type::attack] = attack;
             }
             if (work) {
                 this->graphics[graphic_type::work] = work;
             }
         }
         // villager carrying resources graphics
         if (cmd->carry_sprite_id > 0) {
             auto carry = spec.get_unit_texture(cmd->carry_sprite_id);
             this->graphics[graphic_type::carrying] = carry;
         }
     }
     // TODO get cost, temp fixed cost of 50 food
     this->cost.set(cost_type::constant, create_resource_cost(game_resource::food, 50));
 }
References openage::owner.
~ObjectProducer()
openage::ObjectProducer::~ObjectProducer () virtual
Definition at line 188 of file producer.cpp.
 {}
Member Function Documentation
id()
int openage::ObjectProducer::id () const override virtual
gets the unique id of this unit type
Implements openage::UnitType.
Definition at line 190 of file producer.cpp.
{
     return this->unit_data.id0;
 }
References unit_data.
initialise()
void openage::ObjectProducer::initialise (Unit * , Player &) override virtual
Initialize units attributes to this type spec
This can be called using existing units to modify type Ensure that the unit has been placed before seting the units type
TODO: make const
Implements openage::UnitType.
Reimplemented in openage::LivingProducer, and openage::MovableProducer.
Definition at line 213 of file producer.cpp.
{
     ENSURE(this->owner == player, "unit init from a UnitType of a wrong player which breaks tech levels");
     // log attributes
     unit->log(MSG(dbg) << "setting unit type " <<
         this->unit_data.id0 << " " <<
         this->unit_data.name);
     // reset existing attributes
     unit->reset();
     // initialise unit
     unit->unit_type = this;
     // colour
     unit->add_attribute(std::make_shared<Attribute<attr_type::owner>>(player));
     // hitpoints if available
     if (this->unit_data.hit_points > 0) {
         unit->add_attribute(std::make_shared<Attribute<attr_type::hitpoints>>(this->unit_data.hit_points));
         unit->add_attribute(std::make_shared<Attribute<attr_type::damaged>>(this->unit_data.hit_points));
     }
     // collectable resources
     if (this->unit_data.unit_class == gamedata::unit_classes::TREES) {
         unit->add_attribute(std::make_shared<Attribute<attr_type::resource>>(game_resource::wood, 125));
     }
     else if (this->unit_data.unit_class == gamedata::unit_classes::BERRY_BUSH) {
         unit->add_attribute(std::make_shared<Attribute<attr_type::resource>>(game_resource::food, 100));
     }
     else if (this->unit_data.unit_class == gamedata::unit_classes::SEA_FISH) {
         unit->add_attribute(std::make_shared<Attribute<attr_type::resource>>(game_resource::food, 200));
     }
     else if (this->unit_data.unit_class == gamedata::unit_classes::PREY_ANIMAL) {
         unit->add_attribute(std::make_shared<Attribute<attr_type::resource>>(game_resource::food, 140));
     }
     else if (this->unit_data.unit_class == gamedata::unit_classes::SHEEP) {
         unit->add_attribute(std::make_shared<Attribute<attr_type::resource>>(game_resource::food, 100, 0.1));
     }
     else if (this->unit_data.unit_class == gamedata::unit_classes::GOLD_MINE) {
         unit->add_attribute(std::make_shared<Attribute<attr_type::resource>>(game_resource::gold, 800));
     }
     else if (this->unit_data.unit_class == gamedata::unit_classes::STONE_MINE) {
         unit->add_attribute(std::make_shared<Attribute<attr_type::resource>>(game_resource::stone, 350));
     }
     // decaying units have a timed lifespan
     if (decay) {
         unit->push_action(std::make_unique<DecayAction>(unit), true);
     }
     else {
         // if destruction graphic is available
         if (this->dead_unit_id) {
             unit->push_action(
                 std::make_unique<DeadAction>(
                     unit,
                     [this, unit, &player]() {
                         // modify unit to have  dead type
                         UnitType *t = player.get_type(this->dead_unit_id);
                         if (t) {
                             t->initialise(unit, player);
                         }
                     }
                 ),
                 true);
         }
         else if (this->graphics.count(graphic_type::dying) > 0) {
             unit->push_action(std::make_unique<DeadAction>(unit), true);
         }
         // the default action
         unit->push_action(std::make_unique<IdleAction>(unit), true);
     }
     // give required abilitys
     for (auto &a : this->type_abilities) {
         unit->give_ability(a);
     }
 }
References openage::Unit::add_attribute(), openage::log::dbg(), dead_unit_id, decay, openage::dying, ENSURE, openage::food, openage::Player::get_type(), openage::Unit::give_ability(), openage::gold, openage::UnitType::graphics, openage::UnitType::initialise(), openage::log::LogSource::log(), MSG, openage::UnitType::owner, openage::Unit::push_action(), openage::Unit::reset(), openage::stone, openage::UnitType::type_abilities, unit_data, openage::Unit::unit_type, and openage::wood.
Referenced by openage::MovableProducer::initialise().
name()
std::string openage::ObjectProducer::name () const override virtual
gets the name of the unit type being produced
Implements openage::UnitType.
Definition at line 209 of file producer.cpp.
{
     return this->unit_data.name;
 }
References unit_data.
Referenced by openage.util.fslike.path.Path::stem(), openage.util.fslike.path.Path::suffix(), and openage.util.fslike.path.Path::suffixes().
parent_id()
int openage::ObjectProducer::parent_id () const override virtual
gets the parent id of this unit type which is used for village base and gather types
Implements openage::UnitType.
Definition at line 194 of file producer.cpp.
{
     int uid = this->unit_data.id0;
     // male types
     if (uid == 156 || uid == 120 || uid == 592 || uid == 123 || uid == 579 || uid == 124) {
         return 83;
     }
     // female types
     else if (uid == 222 || uid == 354 || uid == 590 || uid == 218 || uid == 581 || uid == 220) {
         return 293;
     }
     return uid;
 }
References unit_data.
Referenced by openage::LivingProducer::initialise().
place()
TerrainObject * openage::ObjectProducer::place (Unit * , std::shared_ptr< Terrain > , coord::phys3) const override virtual
set unit in place – return if placement was successful
This should be used when initially creating a unit or when a unit is ungarrsioned from a building or object TODO: make const
Implements openage::UnitType.
Reimplemented in openage::LivingProducer, and openage::MovableProducer.
Definition at line 294 of file producer.cpp.
{
     // create new object with correct base shape
     if (this->unit_data.selection_shape > 1) {
         u->make_location<RadialObject>(this->unit_data.radius_x, this->terrain_outline);
     }
     else {
         u->make_location<SquareObject>(this->foundation_size, this->terrain_outline);
     }
     // find set of allowed terrains
     std::unordered_set<terrain_t> terrains = allowed_terrains(this->unit_data.terrain_restriction);
     /*
      * decide what terrain is passable using this lambda
      * currently unit avoids water and tiles with another unit
      * this function should be true if pos is a valid position of the object
      */
     TerrainObject *obj_ptr = u->location.get();
     std::weak_ptr<Terrain> terrain_ptr = terrain;
     u->location->passable = [obj_ptr, terrain_ptr, terrains](const coord::phys3 &pos) -> bool {
         // if location is deleted, then so is this lambda (deleting terrain implies location is deleted)
         // so locking objects here will not return null
         auto terrain = terrain_ptr.lock();
         // look at all tiles in the bases range
         for (coord::tile check_pos : tile_list(obj_ptr->get_range(pos, *terrain))) {
             TileContent *tc = terrain->get_data(check_pos);
             // invalid tile types
             if (!tc || terrains.count(tc->terrain_id) == 0) {
                 return false;
             }
             // compare with objects intersecting the units tile
             // ensure no intersections with other objects
             for (auto obj_cmp : tc->obj) {
                 if (obj_ptr != obj_cmp &&
                     obj_cmp->check_collisions() &&
                     obj_ptr->intersects(*obj_cmp, pos)) {
                     return false;
                 }
             }
         }
         return true;
     };
     u->location->draw = [u, obj_ptr](const Engine &e) {
         if (u->selected) {
             obj_ptr->draw_outline(e.coord);
         }
         u->draw(e);
     };
     // try to place the obj, it knows best whether it will fit.
     auto state = this->decay? object_state::placed_no_collision : object_state::placed;
     if (u->location->place(terrain, init_pos, state)) {
         if (this->on_create) {
             this->on_create->play();
         }
         return u->location.get();
     }
     // placing at the given position failed
     u->log(MSG(dbg) << "failed to place object");
     return nullptr;
 }
References openage::allowed_terrains(), openage::TerrainObject::check_collisions(), openage::log::dbg(), decay, openage::Unit::draw(), openage::TerrainObject::draw_outline(), openage::UnitType::foundation_size, openage::TerrainObject::get_range(), openage::TerrainObject::intersects(), openage::Unit::location, openage::log::LogSource::log(), openage::Unit::make_location(), MSG, openage::TileContent::obj, on_create, openage::placed, openage::placed_no_collision, openage::Sound::play(), openage::Unit::selected, openage::TileContent::terrain_id, terrain_outline, openage::tile_list(), and unit_data.
Referenced by openage::MovableProducer::place().
Member Data Documentation
dataspec
const GameSpec& openage::ObjectProducer::dataspec protected
Definition at line 47 of file producer.h.
dead_unit_id
int openage::ObjectProducer::dead_unit_id protected
Definition at line 62 of file producer.h.
Referenced by initialise().
decay
bool openage::ObjectProducer::decay protected
decaying objects have a timed lifespan
Definition at line 53 of file producer.h.
Referenced by initialise(), and place().
default_tex
std::shared_ptr<UnitTexture> openage::ObjectProducer::default_tex protected
Definition at line 61 of file producer.h.
on_create
const Sound* openage::ObjectProducer::on_create protected
Sound id played when object is created or destroyed.
Definition at line 58 of file producer.h.
Referenced by place().
on_destroy
const Sound* openage::ObjectProducer::on_destroy protected
Definition at line 59 of file producer.h.
terrain_outline
std::shared_ptr<Texture> openage::ObjectProducer::terrain_outline protected
Definition at line 60 of file producer.h.
Referenced by place().
unit_data
const gamedata::unit_object openage::ObjectProducer::unit_data protected
Definition at line 48 of file producer.h.
Referenced by id(), initialise(), name(), parent_id(), and place().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/producer.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/producer.cpp