openage: openage::DecayAction Class Reference
openage::DecayAction Class Reference
#include <action.h>
Public Member Functions
DecayAction (Unit *e)
virtual ~DecayAction ()
void update (unsigned int time) override
void on_completion () override
bool completed () const override
bool allow_interupt () const override
bool allow_control () const override
std::string name () const override
Public Member Functions inherited from openage::UnitAction
UnitAction (Unit *u, graphic_type initial_gt)
virtual ~UnitAction ()
graphic_type type () const
float current_frame () const
virtual const graphic_set & current_graphics () const
void draw_debug (const Engine &engine)
void face_towards (const coord::phys3 pos)
bool damage_unit (Unit &target)
void move_to (Unit &target, bool use_range=true)
Private Attributes
float end_frame
Additional Inherited Members
Static Public Member Functions inherited from openage::UnitAction
static coord::phys_t adjacent_range (Unit *u)
static coord::phys_t get_attack_range (Unit *u)
static coord::phys_t get_heal_range (Unit *u)
Static Public Attributes inherited from openage::UnitAction
static bool show_debug = false
Protected Attributes inherited from openage::UnitAction
Unit * entity
graphic_type graphic
float frame
float frame_rate
std::function< void(const Engine &)> debug_draw_action
Detailed Description
plays a fixed number of frames for the units dying animation
Definition at line 275 of file action.h.
Constructor & Destructor Documentation
DecayAction()
openage::DecayAction::DecayAction (Unit * e)
Definition at line 339 of file action.cpp.
     :
     UnitAction(e, graphic_type::standing),
     end_frame{.0f} {
     auto &g_set = this->current_graphics();
     if (g_set.count(this->graphic) > 0) {
         this->end_frame = g_set.at(this->graphic)->frame_count - 1;
     }
 }
References openage::standing.
~DecayAction()
virtual openage::DecayAction::~DecayAction () inline virtual
Definition at line 278 of file action.h.
 {}
Member Function Documentation
allow_control()
bool openage::DecayAction::allow_control () const inline override virtual
control whether stack can discard the action automatically and should the stack be modifiable when this action is on top
if true this action must complete and will not allow new actions to be pushed while it is active and also does not update the secondary actions
Implements openage::UnitAction.
Definition at line 284 of file action.h.
 { return false; }
allow_interupt()
bool openage::DecayAction::allow_interupt () const inline override virtual
checks if the action can be interrupted, allowing it to be popped if the user specifies a new action, if false the action must reach a completed state before removal eg dead action must be completed and cannot be discarded
Implements openage::UnitAction.
Definition at line 283 of file action.h.
 { return false; }
completed()
bool openage::DecayAction::completed () const override virtual
gets called for all actions on stack each update cycle
Returns
true when action is completed so it and everything above it can be popped
Implements openage::UnitAction.
Definition at line 356 of file action.cpp.
{
     return this->frame > this->end_frame;
 }
References end_frame, and openage::UnitAction::frame.
name()
std::string openage::DecayAction::name () const inline override virtual
debug string to identify action types
Implements openage::UnitAction.
Definition at line 285 of file action.h.
 { return "decay"; }
Referenced by openage.util.fslike.path.Path::stem(), openage.util.fslike.path.Path::suffix(), and openage.util.fslike.path.Path::suffixes().
on_completion()
void openage::DecayAction::on_completion () override virtual
action to perform when popped from a units action stack
Implements openage::UnitAction.
Definition at line 354 of file action.cpp.
 {}
update()
void openage::DecayAction::update (unsigned int time) override virtual
each action has its own update functionality which gets called when this is the active action
Implements openage::UnitAction.
Definition at line 350 of file action.cpp.
{
     this->frame += time * this->frame_rate / 10000.0f;
 }
References openage::UnitAction::frame, and openage::UnitAction::frame_rate.
Member Data Documentation
end_frame
float openage::DecayAction::end_frame private
Definition at line 288 of file action.h.
Referenced by completed().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/action.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/action.cpp