openage: openage::PopulationTracker Class Reference
openage::PopulationTracker Class Reference
#include <population_tracker.h>
Public Member Functions
PopulationTracker (int capacity_static, int capacity_max)
void demand_population (int i)
void free_population (int i)
void add_capacity_static (int i)
void add_capacity (int i)
void remove_capacity (int i)
void add_capacity_max (int i)
int get_demand () const
int get_capacity () const
int get_space () const
int get_capacity_overflow () const
bool is_capacity_maxed () const
Private Member Functions
void update_capacity ()
Private Attributes
int demand
int capacity_static
int capacity_real
int capacity_max
int capacity_total
int capacity
Detailed Description
Keeps track of the population size and capacity.
Definition at line 10 of file population_tracker.h.
Constructor & Destructor Documentation
PopulationTracker()
openage::PopulationTracker::PopulationTracker (int capacity_static, int capacity_max)
Definition at line 7 of file population_tracker.cpp.
{
     this->demand = 0;
     this->capacity_static = capacity_static;
     this->capacity_real = 0;
     this->capacity_max = capacity_max;
     this->update_capacity();
 }
References capacity_max, capacity_real, capacity_static, demand, and update_capacity().
Member Function Documentation
add_capacity()
void openage::PopulationTracker::add_capacity (int i)
Add to the capacity given by units
Definition at line 30 of file population_tracker.cpp.
{
     this->capacity_real += i;
     this->update_capacity();
 }
References capacity_real, and update_capacity().
Referenced by openage::Player::active_unit_added().
add_capacity_max()
void openage::PopulationTracker::add_capacity_max (int i)
Changes the max capacity given by civ bonuses
Definition at line 40 of file population_tracker.cpp.
{
     this->capacity_max += i;
     this->update_capacity();
 }
References capacity_max, and update_capacity().
add_capacity_static()
void openage::PopulationTracker::add_capacity_static (int i)
Changes the capacity given by civ bonuses
Definition at line 25 of file population_tracker.cpp.
{
     this->capacity_static += i;
     this->update_capacity();
 }
References capacity_static, and update_capacity().
demand_population()
void openage::PopulationTracker::demand_population (int i)
Add to the population demand
Definition at line 15 of file population_tracker.cpp.
{
     this->demand += i;
     // TODO triger gui update
 }
References demand.
Referenced by openage::Player::active_unit_added().
free_population()
void openage::PopulationTracker::free_population (int i)
Remove from the population demand
Definition at line 20 of file population_tracker.cpp.
{
     this->demand -= i;
     // TODO triger gui update
 }
References demand.
Referenced by openage::Player::active_unit_removed().
get_capacity()
int openage::PopulationTracker::get_capacity () const
Definition at line 60 of file population_tracker.cpp.
{
     return this->capacity;
 }
References capacity.
get_capacity_overflow()
int openage::PopulationTracker::get_capacity_overflow () const
Returns the population capacity over the max limit.
Definition at line 68 of file population_tracker.cpp.
{
     return this->capacity_total - this->capacity;
 }
References capacity, and capacity_total.
get_demand()
int openage::PopulationTracker::get_demand () const
Definition at line 56 of file population_tracker.cpp.
{
     return this->demand;
 }
References demand.
get_space()
int openage::PopulationTracker::get_space () const
Returns the available population capacity for new units.
Definition at line 64 of file population_tracker.cpp.
{
     return this->capacity - this->demand;
 }
References capacity, and demand.
is_capacity_maxed()
bool openage::PopulationTracker::is_capacity_maxed () const
Check if the population capacity has reached the max limit.
Definition at line 72 of file population_tracker.cpp.
{
     return this->capacity >= this->capacity_max;
 }
References capacity, and capacity_max.
remove_capacity()
void openage::PopulationTracker::remove_capacity (int i)
Remove from the capacity given by units
Definition at line 35 of file population_tracker.cpp.
{
     this->capacity_real -= i;
     this->update_capacity();
 }
References capacity_real, and update_capacity().
Referenced by openage::Player::active_unit_removed().
update_capacity()
void openage::PopulationTracker::update_capacity () private
Calculates the capacity values based on the limits. Must be called when a capacity variable changes.
Definition at line 45 of file population_tracker.cpp.
{
     this->capacity_total = this->capacity_static + this->capacity_real;
     // check the capacity limit
     if (this->capacity_total > this->capacity_max) {
         this->capacity = this->capacity_max;
     } else {
         this->capacity = this->capacity_total;
     }
     // TODO triger gui update
 }
References capacity, capacity_max, capacity_real, capacity_static, and capacity_total.
Referenced by add_capacity(), add_capacity_max(), add_capacity_static(), PopulationTracker(), and remove_capacity().
Member Data Documentation
capacity
int openage::PopulationTracker::capacity private
All the population capacity with the limitation
Definition at line 102 of file population_tracker.h.
Referenced by get_capacity(), get_capacity_overflow(), get_space(), is_capacity_maxed(), and update_capacity().
capacity_max
int openage::PopulationTracker::capacity_max private
The max population capacity
Definition at line 90 of file population_tracker.h.
Referenced by add_capacity_max(), is_capacity_maxed(), PopulationTracker(), and update_capacity().
capacity_real
int openage::PopulationTracker::capacity_real private
The population capacity given by units
Definition at line 85 of file population_tracker.h.
Referenced by add_capacity(), PopulationTracker(), remove_capacity(), and update_capacity().
capacity_static
int openage::PopulationTracker::capacity_static private
The population capacity given by civ bonuses
Definition at line 80 of file population_tracker.h.
Referenced by add_capacity_static(), PopulationTracker(), and update_capacity().
capacity_total
int openage::PopulationTracker::capacity_total private
All the population capacity without the limitation
Definition at line 97 of file population_tracker.h.
Referenced by get_capacity_overflow(), and update_capacity().
demand
int openage::PopulationTracker::demand private
The population demand
Definition at line 75 of file population_tracker.h.
Referenced by demand_population(), free_population(), get_demand(), get_space(), and PopulationTracker().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gamestate/population_tracker.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gamestate/population_tracker.cpp