openage: openage::renderer::opengl::GlTexture2dArray Class Reference
openage::renderer::opengl::GlTexture2dArray Class Reference final
An OpenGL array of 2D textures.
#include <texture_array.h>
Public Member Functions
GlTexture2dArray (const std::vector< resources::Texture2dData > &)
GlTexture2dArray (size_t n_layers, resources::Texture2dInfo const &layer_info)
void upload (size_t layer, resources::Texture2dData const &) override
Public Member Functions inherited from openage::renderer::Texture2dArray
virtual ~Texture2dArray ()
resources::Texture2dInfo const & get_info () const
Returns information about the layer format.
Public Member Functions inherited from openage::renderer::opengl::GlSimpleObject
GlSimpleObject (GlSimpleObject &&)
GlSimpleObject & operator= (GlSimpleObject &&)
GlSimpleObject (GlSimpleObject const &)=delete
GlSimpleObject & operator= (GlSimpleObject const &)=delete
virtual ~GlSimpleObject ()
GLuint get_handle () const
Returns the handle to the underlying OpenGL Object.
Private Attributes
size_t n_layers
The number of layers (elements) in the array, AKA the depth.
Additional Inherited Members
Protected Member Functions inherited from openage::renderer::Texture2dArray
Texture2dArray (const resources::Texture2dInfo &)
Constructs the base class.
Protected Member Functions inherited from openage::renderer::opengl::GlSimpleObject
GlSimpleObject (std::function< void(GLuint)> delete_fun)
Protected Attributes inherited from openage::renderer::Texture2dArray
resources::Texture2dInfo layer_info
Information about the size, format, etc. of every layer in this array.
Protected Attributes inherited from openage::renderer::opengl::GlSimpleObject
std::optional< GLuint > handle
The handle to the OpenGL Object that this class represents.
std::function< void(GLuint)> delete_fun
The function that deletes the underlying OpenGL Object.
Detailed Description
An OpenGL array of 2D textures.
Definition at line 18 of file texture_array.h.
Constructor & Destructor Documentation
GlTexture2dArray() [1/2]
openage::renderer::opengl::GlTexture2dArray::GlTexture2dArray (const std::vector< resources::Texture2dData > & data)
Constructs an array of the same number of layers as the size of the given vector, and fills the layers with the corresponding vector element. The texture formats in all vector elements must be the same as defined by Textur2dInfo::operator==.
Definition at line 22 of file texture_array.cpp.
     : GlTexture2dArray(data.size(), data[0].get_info())
 {
     auto fmt_in_out = GL_PIXEL_FORMAT.get(this->layer_info.get_format());
     auto size = this->layer_info.get_size();
     // Fill the array with given data
     size_t i = 0;
     for (auto const& tex : data) {
         glTexSubImage3D(GL_TEXTURE_2D_ARRAY,
                         0,                          // mipmap number
                         0, 0, i,                    // xoffset, yoffset, zoffset
                         size.first, size.second, 1, // width, height, depth
                         std::get<1>(fmt_in_out),    // format
                         std::get<2>(fmt_in_out),    // type
                         tex.get_data()              // data
         );
         i += 1;
     }
 }
References openage::renderer::resources::Texture2dInfo::get_format(), openage::renderer::resources::Texture2dInfo::get_size(), openage::renderer::opengl::GL_PIXEL_FORMAT, and openage::renderer::Texture2dArray::layer_info.
GlTexture2dArray() [2/2]
openage::renderer::opengl::GlTexture2dArray::GlTexture2dArray (size_t n_layers, resources::Texture2dInfo const & layer_info)
Constructs an array of ln_layers empty layers, with the per-layer texture format specified in layer_info.
Definition at line 45 of file texture_array.cpp.
     : Texture2dArray(layer_info)
     , GlSimpleObject([] (GLuint handle) { glDeleteTextures(1, &handle); } )
     , n_layers(n_layers)
 {
     GLuint handle;
     glGenTextures(1, &handle);
     this->handle = handle;
     glBindTexture(GL_TEXTURE_2D_ARRAY, *this->handle);
     auto fmt_in_out = GL_PIXEL_FORMAT.get(this->layer_info.get_format());
     auto size = this->layer_info.get_size();
     // Create empty image
     glTexImage3D(GL_TEXTURE_2D_ARRAY,
                  0,                       // mipmap level
                  std::get<0>(fmt_in_out), // gpu texel format
                  size.first,              // width
                  size.second,             // height
                  n_layers,                // depth
                  0,                       // border
                  std::get<1>(fmt_in_out), // cpu pixel format
                  std::get<2>(fmt_in_out), // cpu pixel type
                  nullptr                  // data
     );
     // \todo these are outdated, use sampler settings
     glTexParameteri(GL_TEXTURE_2D_ARRAY, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
     glTexParameteri(GL_TEXTURE_2D_ARRAY, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
     log::log(MSG(dbg) << "Created an OpenGL texture array.");
 }
References openage::renderer::opengl::GlSimpleObject::handle.
Member Function Documentation
upload()
void openage::renderer::opengl::GlTexture2dArray::upload (size_t layer, resources::Texture2dData const &) override virtual
Uploads the given texture data into the specified layer. layer must be strictly less than the size of the array and the data format must match the format this array was originally created with.
Implements openage::renderer::Texture2dArray.
Definition at line 79 of file texture_array.cpp.
{
     if (layer >= this->n_layers) {
         throw Error(MSG(err) << "Cannot upload to layer " << layer << " in texture array with "
                              << this->n_layers << " layers.");
     }
     glBindTexture(GL_TEXTURE_2D_ARRAY, *this->handle);
     auto fmt_in_out = GL_PIXEL_FORMAT.get(this->layer_info.get_format());
     auto size = this->layer_info.get_size();
     glTexSubImage3D( GL_TEXTURE_2D_ARRAY,
                      0,                          // mipmap number
                      0,0,layer,                  // xoffset, yoffset, zoffset
                      size.first, size.second, 1, // width, height, depth
                      std::get<1>(fmt_in_out),    // format
                      std::get<2>(fmt_in_out),    // type
                      data.get_data()             // data
     );
 }
References openage::log::err(), openage::renderer::resources::Texture2dData::get_data(), openage::renderer::resources::Texture2dInfo::get_format(), openage::renderer::resources::Texture2dInfo::get_size(), openage::renderer::opengl::GL_PIXEL_FORMAT, openage::renderer::Texture2dArray::layer_info, MSG, and n_layers.
Member Data Documentation
n_layers
size_t openage::renderer::opengl::GlTexture2dArray::n_layers private
The number of layers (elements) in the array, AKA the depth.
Definition at line 34 of file texture_array.h.
Referenced by upload().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/opengl/texture_array.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/opengl/texture_array.cpp