openage: openage::Region Class Reference
openage::Region Class Reference
#include <generator.h>
Public Member Functions
Region (int size)
Region (coord::tile center, tileset_t tiles)
tileset_t get_tiles () const
coord::tile get_center () const
coord::tile get_tile (rng::RNG &rng) const
tileset_t subset (rng::RNG &rng, coord::tile start_tile, unsigned int number, double p) const
Region take_tiles (rng::RNG &rng, coord::tile start_tile, unsigned int number, double p)
Region take_random (rng::RNG &rng, unsigned int number, double p)
Public Attributes
int owner
int object_id
int terrain_id
Private Attributes
coord::tile center
tileset_t tiles
Detailed Description
A region is a set of tiles around a starting point, including functions to create child regions
Definition at line 48 of file generator.h.
Constructor & Destructor Documentation
Region() [1/2]
openage::Region::Region (int size)
a square of tiles ranging from {-size, -size} to {size, size}
Definition at line 29 of file generator.cpp.
     :
     owner{0},
     object_id{0},
     terrain_id{0},
     center{0, 0} {
     for (int ne = -size; ne < size; ++ne) {
         for (int se = -size; se < size; ++se) {
             this->tiles.emplace(coord::tile{ne, se});
         }
     }
 }
References openage::owner.
Region() [2/2]
openage::Region::Region (coord::tile center, tileset_t tiles)
a specified set of tiles
Definition at line 42 of file generator.cpp.
     :
     owner{0},
     object_id{0},
     terrain_id{0},
     center(center),
     tiles{tiles} {
 }
References openage::owner.
Member Function Documentation
get_center()
coord::tile openage::Region::get_center () const
the center point of the region
Definition at line 55 of file generator.cpp.
{
     return this->center;
 }
References center.
Referenced by openage::Generator::create_regions().
get_tile()
coord::tile openage::Region::get_tile (rng::RNG & rng) const
picks a random tile from this subset
Definition at line 59 of file generator.cpp.
{
     return random_tile(rng, this->tiles);
 }
References openage::random_tile(), and tiles.
Referenced by take_random().
get_tiles()
tileset_t openage::Region::get_tiles () const
all tiles in this region
Definition at line 51 of file generator.cpp.
{
     return this->tiles;
 }
References tiles.
subset()
tileset_t openage::Region::subset (rng::RNG & rng, coord::tile start_tile, unsigned int number, double p) const
find a group of tiles inside this region, number is the number of tiles to be contained in the subset, p is a probability between 0.0 and 1.0 which produces various shapes. a value of 1.0 produces circular shapes, where as a low value produces more scattered shapes. a value of 0.0 should not be used, and will always return no tiles
Definition at line 64 of file generator.cpp.
{
     if (p == 0.0) {
         return tileset_t();
     }
     // the set of included tiles
     std::unordered_set<coord::tile> subtiles;
     subtiles.emplace(start_point);
     // outside layer of tiles
     std::unordered_set<coord::tile> edge_set;
     while (subtiles.size() < number) {
         if (edge_set.empty()) {
             // try fill the edge list
             for (auto &t : subtiles) {
                 // check adjacent tiles
                 for (int i = 0; i < 4; ++i) {
                     coord::tile adj = t + neigh_tiles[i];
                     if (this->tiles.count(adj) &&
                         !subtiles.count(adj)) {
                         edge_set.emplace(adj);
                     }
                 }
             }
             if (edge_set.empty()) {
                 // unable to grow further
                 return subtiles;
             }
         }
         // transfer a random tile
         coord::tile next_tile = random_tile(rng, edge_set);
         edge_set.erase(next_tile);
         if (rng.probability(p)) {
             subtiles.emplace(next_tile);
         }
     }
     return subtiles;
 }
References openage::neigh_tiles, openage::rng::RNG::probability(), openage::random_tile(), and tiles.
Referenced by take_tiles().
take_random()
Region openage::Region::take_random (rng::RNG & rng, unsigned int number, double p)
similiar to take_tiles, but takes a random group of tiles
Definition at line 122 of file generator.cpp.
{
     return this->take_tiles(rng, this->get_tile(rng), number, p);
 }
References get_tile(), and take_tiles().
Referenced by openage::Generator::create_regions().
take_tiles()
Region openage::Region::take_tiles (rng::RNG & rng, coord::tile start_tile, unsigned int number, double p)
removes the given set of tiles from this region, which get split of as a new child region
Definition at line 108 of file generator.cpp.
{
     tileset_t new_set = this->subset(rng, start_point, number, p);
     // erase from current set
     for (auto &t: new_set) {
         this->tiles.erase(t);
     }
     Region new_region(start_point, new_set);
     new_region.terrain_id = this->terrain_id;
     return new_region;
 }
References subset(), terrain_id, and tiles.
Referenced by openage::Generator::create_regions(), and take_random().
Member Data Documentation
center
coord::tile openage::Region::center private
the center tile of this region
Definition at line 115 of file generator.h.
Referenced by get_center().
object_id
int openage::Region::object_id
the object to be placed on each tile of this region 0 for placing no object
Definition at line 103 of file generator.h.
Referenced by openage::Generator::create_regions().
owner
int openage::Region::owner
player id of the owner, 0 for none
Definition at line 97 of file generator.h.
Referenced by openage::Generator::create_regions().
terrain_id
int openage::Region::terrain_id
the base terrain for this region
Definition at line 108 of file generator.h.
Referenced by openage::Generator::create_regions(), and take_tiles().
tiles
tileset_t openage::Region::tiles private
tiles in this region
Definition at line 120 of file generator.h.
Referenced by get_tile(), get_tiles(), subset(), and take_tiles().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gamestate/generator.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gamestate/generator.cpp