openage: openage::renderer::opengl::GlTexture2d Class Reference
openage::renderer::opengl::GlTexture2d Class Reference final
A handle to an OpenGL texture.
#include <texture.h>
Public Member Functions
GlTexture2d (const resources::Texture2dData &)
Constructs a texture and fills it with the given data.
GlTexture2d (resources::Texture2dInfo const &)
Constructs an empty texture with the given parameters.
resources::Texture2dData into_data () override
void upload (resources::Texture2dData const &) override
Public Member Functions inherited from openage::renderer::Texture2d
virtual ~Texture2d ()
const resources::Texture2dInfo & get_info () const
Returns the texture information.
Public Member Functions inherited from openage::renderer::opengl::GlSimpleObject
GlSimpleObject (GlSimpleObject &&)
GlSimpleObject & operator= (GlSimpleObject &&)
GlSimpleObject (GlSimpleObject const &)=delete
GlSimpleObject & operator= (GlSimpleObject const &)=delete
virtual ~GlSimpleObject ()
GLuint get_handle () const
Returns the handle to the underlying OpenGL Object.
Additional Inherited Members
Protected Member Functions inherited from openage::renderer::Texture2d
Texture2d (const resources::Texture2dInfo &)
Constructs the base with the given information.
Protected Member Functions inherited from openage::renderer::opengl::GlSimpleObject
GlSimpleObject (std::function< void(GLuint)> delete_fun)
Protected Attributes inherited from openage::renderer::Texture2d
resources::Texture2dInfo info
Information about the size, format, etc. of this texture.
Protected Attributes inherited from openage::renderer::opengl::GlSimpleObject
std::optional< GLuint > handle
The handle to the OpenGL Object that this class represents.
std::function< void(GLuint)> delete_fun
The function that deletes the underlying OpenGL Object.
Detailed Description
A handle to an OpenGL texture.
Definition at line 15 of file texture.h.
Constructor & Destructor Documentation
GlTexture2d() [1/2]
openage::renderer::opengl::GlTexture2d::GlTexture2d (const resources::Texture2dData & data) explicit
Constructs a texture and fills it with the given data.
Definition at line 22 of file texture.cpp.
     : Texture2d(data.get_info())
     , GlSimpleObject([] (GLuint handle) { glDeleteTextures(1, &handle); } )
 {
     GLuint handle;
     glGenTextures(1, &handle);
     this->handle = handle;
     glBindTexture(GL_TEXTURE_2D, *this->handle);
     // select pixel format
     auto fmt_in_out = GL_PIXEL_FORMAT.get(this->info.get_format());
     // store raw pixels to gpu
     auto size = this->info.get_size();
     glPixelStorei(GL_UNPACK_ALIGNMENT, this->info.get_row_alignment());
     glTexImage2D(
         GL_TEXTURE_2D, 0,
         std::get<0>(fmt_in_out), size.first, size.second, 0,
         std::get<1>(fmt_in_out), std::get<2>(fmt_in_out), data.get_data()
     );
     // drawing settings
     // TODO these are outdated, use sampler settings
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
     log::log(MSG(dbg) << "Created OpenGL texture from data");
 }
References openage::renderer::opengl::GlSimpleObject::handle.
GlTexture2d() [2/2]
openage::renderer::opengl::GlTexture2d::GlTexture2d (resources::Texture2dInfo const & info)
Constructs an empty texture with the given parameters.
Definition at line 54 of file texture.cpp.
     : Texture2d(info)
     , GlSimpleObject([] (GLuint handle) { glDeleteTextures(1, &handle); } )
 {
     GLuint handle;
     glGenTextures(1, &handle);
     this->handle = handle;
     glBindTexture(GL_TEXTURE_2D, *this->handle);
     auto fmt_in_out = GL_PIXEL_FORMAT.get(this->info.get_format());
     auto dims = this->info.get_size();
     glPixelStorei(GL_UNPACK_ALIGNMENT, this->info.get_row_alignment());
     glTexImage2D(
         GL_TEXTURE_2D, 0,
         std::get<0>(fmt_in_out), dims.first, dims.second, 0,
         std::get<1>(fmt_in_out), std::get<2>(fmt_in_out), nullptr
     );
     // TODO these are outdated, use sampler settings
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
     log::log(MSG(dbg) << "Created OpenGL texture from parameters");
 }
References openage::renderer::opengl::GlSimpleObject::handle.
Member Function Documentation
into_data()
resources::Texture2dData openage::renderer::opengl::GlTexture2d::into_data () override virtual
Copies this texture's data from graphics hardware into a CPU-accessible Texture2dData buffer.
Implements openage::renderer::Texture2d.
Definition at line 83 of file texture.cpp.
{
     auto fmt_in_out = GL_PIXEL_FORMAT.get(this->info.get_format());
     std::vector<uint8_t> data(this->info.get_data_size());
     glPixelStorei(GL_PACK_ALIGNMENT, this->info.get_row_alignment());
     glBindTexture(GL_TEXTURE_2D, *this->handle);
     // TODO use a Pixel Buffer Object instead
     glGetTexImage(GL_TEXTURE_2D, 0, std::get<1>(fmt_in_out), std::get<2>(fmt_in_out), data.data());
     return resources::Texture2dData(resources::Texture2dInfo(this->info), std::move(data));
 }
References openage::renderer::resources::Texture2dInfo::get_data_size(), openage::renderer::resources::Texture2dInfo::get_format(), openage::renderer::resources::Texture2dInfo::get_row_alignment(), openage::renderer::opengl::GL_PIXEL_FORMAT, openage::renderer::Texture2d::info, and openage::move.
upload()
void openage::renderer::opengl::GlTexture2d::upload (resources::Texture2dData const &) override virtual
Uploads the provided data into the GPU texture storage. The format has to match the format this Texture was originally created with.
Implements openage::renderer::Texture2d.
Definition at line 95 of file texture.cpp.
{
     if (this->info != data.get_info()) {
         throw Error(MSG(err) << "Tried to upload texture data of different format into an existing GPU texture.");
     }
     glBindTexture(GL_TEXTURE_2D, *this->handle);
     auto size = this->info.get_size();
     auto fmt_in_out = GL_PIXEL_FORMAT.get(this->info.get_format());
     glTexSubImage2D(GL_TEXTURE_2D, 0, 0, 0,
                     size.first, size.second,
                     std::get<1>(fmt_in_out), std::get<2>(fmt_in_out),
                     data.get_data()
     );
 }
References openage::log::err(), openage::renderer::resources::Texture2dData::get_data(), openage::renderer::resources::Texture2dInfo::get_format(), openage::renderer::resources::Texture2dData::get_info(), openage::renderer::resources::Texture2dInfo::get_size(), openage::renderer::opengl::GL_PIXEL_FORMAT, openage::renderer::Texture2d::info, and MSG.
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/opengl/texture.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/opengl/texture.cpp