openage: openage::util::FString Class Reference
openage::util::FString Class Reference
#include <stringformatter.h>
Public Member Functions
FString ()
FString (const std::string &other)
FString (std::string &&other) noexcept
FString & operator= (const std::string &other)
FString & operator= (std::string &&other) noexcept
operator std::string & ()
operator const std::string & () const
operator std::string () &&
void reset ()
Public Member Functions inherited from openage::util::StringFormatter< FString >
StringFormatter (std::string &output)
StringFormatter (StringFormatter< FString > &&other) noexcept
StringFormatter (const StringFormatter &)=delete
virtual ~StringFormatter ()
FString & child_type_ref ()
StringFormatter< FString > & operator= (StringFormatter< FString > &&other) noexcept
StringFormatter & operator= (const StringFormatter &)=delete
FString & operator<< (const T &t)
FString & operator<< (std::ios &(*x)(std::ios &))
FString & operator<< (std::ostream &(*x)(std::ostream &))
FString & operator<< (const char *s)
FString & operator<< (const std::string &s)
FString FString & operator<< (const std::unique_ptr< T > &ptr)
FString & operator<< (const std::shared_ptr< T > &ptr)
FString & fmt (const char *fmt,...) ATTRIBUTE_FORMAT(2
void reset_flags ()
virtual bool should_format () const
Public Attributes
std::string buffer
Detailed Description
A self-formatting string! Get yours today!
Use like this:
std::string stuff() { FString s; s << "test: " << 5 << std::cout; return s; }
Use as a faster, care-free replacement for stringstream:
std::string stuff() { std::stringstream sstr; sstr << "test: " << 5 << std::cout; return sstr.str(); }
Definition at line 270 of file stringformatter.h.
Constructor & Destructor Documentation
FString() [1/3]
openage::util::FString::FString () inline
Definition at line 272 of file stringformatter.h.
         :
         StringFormatter<FString>{this->buffer} {}
References buffer.
FString() [2/3]
openage::util::FString::FString (const std::string & other) inline
Definition at line 278 of file stringformatter.h.
         :
         StringFormatter<FString>{this->buffer},
         buffer{other} {}
References buffer.
FString() [3/3]
openage::util::FString::FString (std::string && other) inline noexcept
Definition at line 283 of file stringformatter.h.
         :
         StringFormatter<FString>{this->buffer},
         buffer{std::move(other)} {}
References buffer.
Member Function Documentation
operator const std::string &()
openage::util::FString::operator const std::string & () const inline
Definition at line 304 of file stringformatter.h.
{
         return this->buffer;
     }
References buffer.
operator std::string()
openage::util::FString::operator std::string () && inline
Definition at line 308 of file stringformatter.h.
{
         return std::move(this->buffer);
     }
References buffer, and openage::move.
operator std::string &()
openage::util::FString::operator std::string & () inline
Definition at line 300 of file stringformatter.h.
{
         return this->buffer;
     }
References buffer.
operator=() [1/2]
FString& openage::util::FString::operator= (const std::string & other) inline
Definition at line 288 of file stringformatter.h.
{
         this->buffer = other;
         return *this;
     }
References buffer.
operator=() [2/2]
FString& openage::util::FString::operator= (std::string && other) inline noexcept
Definition at line 293 of file stringformatter.h.
{
         this->buffer = std::move(other);
         return *this;
     }
References buffer, and openage::move.
reset()
void openage::util::FString::reset () inline
Definition at line 312 of file stringformatter.h.
                  {
         buffer.clear();
         this->reset_flags();
     }
References buffer, and openage::util::StringFormatter< FString >::reset_flags().
Referenced by openage::coord::tests::coord(), openage::util::tests::enum_(), and openage::util::tests::fixed_point().
Member Data Documentation
buffer
std::string openage::util::FString::buffer
Definition at line 318 of file stringformatter.h.
Referenced by openage::util::tests::enum_(), FString(), operator const std::string &(), operator std::string(), operator std::string &(), operator=(), and reset().
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/stringformatter.h