openage: openage.util.fslike.union.Union Class Reference
openage.util.fslike.union.Union Class Reference
FSLikeObject that provides a structure for mounting several path objects.
Public Member Functions
def __init__ (self)
def __str__ (self)
def root (self)
Returns a path-like object for the root of this file system.
def add_mount (self, pathobj, mountpoint, priority)
def remove_mount (self, search_mountpoint, source_pathobj=None)
def candidate_paths (self, parts)
Helper method.
def open_r (self, parts)
Shall return a BufferedReader for the given file ("mode 'rb'").
def open_w (self, parts)
Shall return a BufferedWriter for the given file ("mode 'wb'").
def resolve_r (self, parts)
def resolve_w (self, parts)
Returns a new flattened path.
def list (self, parts)
Shall yield the entry names of the given directory.
def filesize (self, parts)
def mtime (self, parts)
def mkdirs (self, parts)
Shall ensure that the directory exists.
def rmdir (self, parts)
Shall remove an empty directory.
def unlink (self, parts)
Shall remove a single file.
def touch (self, parts)
Shall create the file or update its timestamp.
def rename (self, srcparts, tgtparts)
Shall rename a file or directory to the target name.
def is_file (self, parts)
def is_dir (self, parts)
def writable (self, parts)
def watch (self, parts, callback)
def poll_watches (self)
Public Member Functions inherited from openage.util.fslike.abstract.FSLikeObject
def pretty (self, parts)
pretty-format a path in this filesystem like object.
def open_rw (self, parts)
Shall return a BufferedWriter for the given file ("mode 'r+'").
def open_a (self, parts)
Shall return a BufferedWriter for the given file ("mode 'a'").
def open_ar (self, parts)
Shall return a BufferedWriter for the given file ("mode 'a+'").
def exists (self, parts)
Test if the parts are a file or a directory.
def get_native_path (self, parts)
Public Attributes
mounts
dirstructure
Detailed Description
FSLikeObject that provides a structure for mounting several path objects.
Unlike in POSIX, mounts may overlap. If multiple mounts match for a directory, those that have a higher priority are preferred. In case of equal priorities, later mounts are preferred.
Definition at line 24 of file union.py.
Constructor & Destructor Documentation
__init__()
def openage.util.fslike.union.Union.__init__ (self)
Definition at line 29 of file union.py.
         # (mountpoint, pathobj, priority), sorted by priority.
         self.mounts = []
         # mountpoints and their parent directories, {name: {...}}.
         # these are the virtual empty folders where mounts can be done
         self.dirstructure = {}
     def __str__(self):
         return "Union({})".format(
Member Function Documentation
__str__()
def openage.util.fslike.union.Union.__str__ (self)
Definition at line 39 of file union.py.
             ", ".join(["%s @ %s" % (repr(pnt[1]),
                                     repr(pnt[0]))
                        for pnt in self.mounts])
         )
     @property
     def root(self):
References openage.util.fslike.union.Union.mounts, and openage::util.repr().
add_mount()
def openage.util.fslike.union.Union.add_mount (self, pathobj, mountpoint, priority)
Definition at line 56 of file union.py.
         if not isinstance(pathobj, Path):
             raise Exception("only a fslike.Path can be mounted, "
                             "not {}".format(type(pathobj)))
         # search for the right place to insert the mount.
         idx = len(self.mounts) - 1
         while idx >= 0 and priority >= self.mounts[idx][2]:
             idx -= 1
         self.mounts.insert(idx + 1, (tuple(mountpoint), pathobj, priority))
         # 'create' parent directories as needed.
         dirstructure = self.dirstructure
         for subdir in mountpoint:
             dirstructure = dirstructure.setdefault(subdir, {})
     def remove_mount(self, search_mountpoint, source_pathobj=None):
         """
References openage.util.fslike.union.Union.dirstructure, and openage.util.fslike.union.Union.mounts.
candidate_paths()
def openage.util.fslike.union.Union.candidate_paths (self, parts)
Helper method.
   Yields path objects from all mounts that match parts, in the order of
   their priorities.
Definition at line 103 of file union.py.
         for mountpoint, pathobj, _ in self.mounts:
             cut_parts = tuple(parts[:len(mountpoint)])
             if mountpoint == cut_parts:
                 yield pathobj.joinpath(parts[len(mountpoint):])
     def open_r(self, parts):
         for path in self.candidate_paths(parts):
References openage.util.fslike.union.Union.mounts.
Referenced by openage.util.fslike.union.Union.filesize(), openage.util.fslike.union.Union.is_dir(), openage.util.fslike.union.Union.is_file(), openage.util.fslike.union.Union.list(), openage.util.fslike.union.Union.mkdirs(), openage.util.fslike.union.Union.mtime(), openage.util.fslike.union.Union.open_r(), openage.util.fslike.union.Union.open_w(), openage.util.fslike.union.Union.rename(), openage.util.fslike.union.Union.resolve_r(), openage.util.fslike.union.Union.resolve_w(), openage.util.fslike.union.Union.rmdir(), openage.util.fslike.union.Union.touch(), openage.util.fslike.union.Union.unlink(), openage.util.fslike.union.Union.watch(), and openage.util.fslike.union.Union.writable().
filesize()
def openage.util.fslike.union.Union.filesize (self, parts)
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 174 of file union.py.
             if path.is_file():
                 return path.filesize
         raise FileNotFoundError(b'/'.join(parts))
     def mtime(self, parts):
         for path in self.candidate_paths(parts):
References openage.util.fslike.union.Union.candidate_paths().
is_dir()
def openage.util.fslike.union.Union.is_dir (self, parts)
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 250 of file union.py.
             dirstructure = self.dirstructure
             for part in parts:
                 dirstructure = dirstructure[part]
             return True
         except KeyError:
             pass
         for path in self.candidate_paths(parts):
             if path.is_dir():
                 return True
         return False
     def writable(self, parts):
         for path in self.candidate_paths(parts):
References openage.util.fslike.union.Union.candidate_paths(), and openage.util.fslike.union.Union.dirstructure.
is_file()
def openage.util.fslike.union.Union.is_file (self, parts)
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 243 of file union.py.
             if path.is_file():
                 return True
         return False
     def is_dir(self, parts):
         try:
References openage.util.fslike.union.Union.candidate_paths().
list()
def openage.util.fslike.union.Union.list (self, parts)
Shall yield the entry names of the given directory.
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 138 of file union.py.
         dir_exists = False
         dirstructure = self.dirstructure
         try:
             # "cd" into the virtual dirstructure
             for subdir in parts:
                 dirstructure = dirstructure[subdir]
             dir_exists = True
             # yield the virtual folders in this folder
             yield from dirstructure
             duplicates.update(dirstructure)
         except KeyError:
             dir_exists = False
         for path in self.candidate_paths(parts):
             if path.is_file():
                 raise NotADirectoryError(repr(path))
             if not path.is_dir():
                 continue
             dir_exists = True
             for name in path.list():
                 if name not in duplicates:
                     yield name
                     duplicates.add(name)
         if not dir_exists:
             raise FileNotFoundError(b'/'.join(parts))
     def filesize(self, parts):
         for path in self.candidate_paths(parts):
References openage.util.fslike.union.Union.candidate_paths(), openage.util.fslike.union.Union.dirstructure, and openage::util.repr().
mkdirs()
def openage.util.fslike.union.Union.mkdirs (self, parts)
Shall ensure that the directory exists.
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 188 of file union.py.
             if path.writable():
                 return path.mkdirs()
         return None
     def rmdir(self, parts):
         found = False
References openage.util.fslike.union.Union.candidate_paths().
mtime()
def openage.util.fslike.union.Union.mtime (self, parts)
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 181 of file union.py.
             if path.exists():
                 return path.mtime
         raise FileNotFoundError(b'/'.join(parts))
     def mkdirs(self, parts):
         for path in self.candidate_paths(parts):
References openage.util.fslike.union.Union.candidate_paths().
open_r()
def openage.util.fslike.union.Union.open_r (self, parts)
Shall return a BufferedReader for the given file ("mode 'rb'").
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 110 of file union.py.
             if path.is_file():
                 return path.open_r()
         raise FileNotFoundError(b'/'.join(parts))
     def open_w(self, parts):
         for path in self.candidate_paths(parts):
References openage.util.fslike.union.Union.candidate_paths().
open_w()
def openage.util.fslike.union.Union.open_w (self, parts)
Shall return a BufferedWriter for the given file ("mode 'wb'").
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 116 of file union.py.
             if path.writable():
                 return path.open_w()
         raise UnsupportedOperation(
             "not writable: " + b'/'.join(parts).decode(errors='replace'))
     def resolve_r(self, parts):
         for path in self.candidate_paths(parts):
References openage.util.fslike.union.Union.candidate_paths().
poll_watches()
def openage.util.fslike.union.Union.poll_watches (self)
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 280 of file union.py.
             pathobj.poll_fs_watches()
 class UnionPath(Path):
     """
References openage.util.fslike.union.Union.mounts.
remove_mount()
def openage.util.fslike.union.Union.remove_mount (self, search_mountpoint, source_pathobj = None)
Definition at line 79 of file union.py.
         unmount = []
         for idx, (mountpoint, pathobj, _) in enumerate(self.mounts):
             # cut the search so prefixes can be matched.
             if mountpoint == tuple(search_mountpoint[:len(mountpoint)]):
                 if not source_pathobj or source_pathobj == pathobj:
                     unmount.append(idx)
         if unmount:
             # reverse the order so that the indices never shift.
             for idx in reversed(sorted(unmount)):
                 del self.mounts[idx]
         else:
             raise ValueError("could not find mounted source")
     def candidate_paths(self, parts):
         """
References openage.util.fslike.union.Union.mounts.
rename()
def openage.util.fslike.union.Union.rename (self, srcparts, tgtparts)
Shall rename a file or directory to the target name.
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 225 of file union.py.
         for srcpath in self.candidate_paths(srcparts):
             if srcpath.exists():
                 found = True
                 if srcpath.writable():
                     for tgtpath in self.candidate_paths(tgtparts):
                         if tgtpath.writable():
                             return srcpath.rename(tgtpath)
         if found:
             raise UnsupportedOperation(
                 "read-only rename: " +
                 b'/'.join(srcparts).decode(errors='replace') + ' to ' +
                 b'/'.join(tgtparts).decode(errors='replace'))
         raise FileNotFoundError(b'/'.join(srcparts))
     def is_file(self, parts):
         for path in self.candidate_paths(parts):
References openage.util.fslike.union.Union.candidate_paths().
resolve_r()
def openage.util.fslike.union.Union.resolve_r (self, parts)
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 124 of file union.py.
             if path.is_file() or path.is_dir():
                 # pylint: disable=protected-access
                 return path._resolve_r()
         return None
     def resolve_w(self, parts):
         for path in self.candidate_paths(parts):
References openage.util.fslike.union.Union.candidate_paths().
resolve_w()
def openage.util.fslike.union.Union.resolve_w (self, parts)
Returns a new flattened path.
This skips funny mounts in between.
   Returns None if the path does not exist or is not writable.
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 131 of file union.py.
             if path.writable():
                 # pylint: disable=protected-access
                 return path._resolve_w()
         return None
     def list(self, parts):
         duplicates = set()
References openage.util.fslike.union.Union.candidate_paths().
rmdir()
def openage.util.fslike.union.Union.rmdir (self, parts)
Shall remove an empty directory.
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 194 of file union.py.
         # remove the directory in all mounts where it exists
         for path in self.candidate_paths(parts):
             if path.is_dir():
                 path.rmdir()
                 found = True
         if not found:
             raise FileNotFoundError(b'/'.join(parts))
     def unlink(self, parts):
         found = False
References openage.util.fslike.union.Union.candidate_paths().
root()
def openage.util.fslike.union.Union.root (self)
Returns a path-like object for the root of this file system.
   This is the main interface that is used normally.
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 47 of file union.py.
     def add_mount(self, pathobj, mountpoint, priority):
         """
touch()
def openage.util.fslike.union.Union.touch (self, parts)
Shall create the file or update its timestamp.
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 218 of file union.py.
             if path.writable():
                 return path.touch()
         raise FileNotFoundError(b'/'.join(parts))
     def rename(self, srcparts, tgtparts):
         found = False
References openage.util.fslike.union.Union.candidate_paths().
unlink()
def openage.util.fslike.union.Union.unlink (self, parts)
Shall remove a single file.
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 206 of file union.py.
         # remove the file in all mounts where it exists
         for path in self.candidate_paths(parts):
             if path.is_file():
                 path.unlink()
                 found = True
         if not found:
             raise FileNotFoundError(b'/'.join(parts))
     def touch(self, parts):
         for path in self.candidate_paths(parts):
References openage.util.fslike.union.Union.candidate_paths().
watch()
def openage.util.fslike.union.Union.watch (self, parts, callback)
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 272 of file union.py.
         for path in self.candidate_paths(parts):
             if path.exists():
                 watching = watching or path.watch(callback)
         return watching
     def poll_watches(self):
         for _, pathobj, _ in self.mounts:
References openage.util.fslike.union.Union.candidate_paths().
writable()
def openage.util.fslike.union.Union.writable (self, parts)
Reimplemented from openage.util.fslike.abstract.FSLikeObject.
Definition at line 265 of file union.py.
             if path.writable():
                 return True
         return False
     def watch(self, parts, callback):
         watching = False
References openage.util.fslike.union.Union.candidate_paths().
Member Data Documentation
dirstructure
openage.util.fslike.union.Union.dirstructure
Definition at line 37 of file union.py.
Referenced by openage.util.fslike.union.Union.add_mount(), openage.util.fslike.union.Union.is_dir(), and openage.util.fslike.union.Union.list().
mounts
openage.util.fslike.union.Union.mounts
Definition at line 33 of file union.py.
Referenced by openage.util.fslike.union.Union.__str__(), openage.util.fslike.union.Union.add_mount(), openage.util.fslike.union.Union.candidate_paths(), openage.util.fslike.union.Union.poll_watches(), and openage.util.fslike.union.Union.remove_mount().
The documentation for this class was generated from the following file:
C:/Users/Jameson/Documents/git-projects/openage/openage/util/fslike/union.py