openage: openage::gui::GameCreator Class Reference
openage::gui::GameCreator Class Reference
#include <game_creator.h>
Public Slots
void on_processed (const QString &error_string)
Signals
void error_string_changed ()
void game_changed ()
void game_spec_changed ()
void generator_parameters_changed ()
Public Member Functions
GameCreator (QObject *parent=nullptr)
virtual ~GameCreator ()
QString get_error_string () const
Q_INVOKABLE void activate ()
Q_INVOKABLE void clearErrors ()
Properties
QString errorString
openage::gui::GameMainLink game
openage::gui::GameSpecLink gameSpec
openage::gui::GeneratorLink generatorParameters
Private Attributes
QString error_string
GameMainLink * game
GameSpecLink * game_spec
GeneratorLink * generator_parameters
Detailed Description
Definition at line 14 of file game_creator.h.
Constructor & Destructor Documentation
GameCreator()
openage::gui::GameCreator::GameCreator (QObject * parent = nullptr) explicit
Definition at line 22 of file game_creator.cpp.
     :
     QObject{parent},
     game{},
     game_spec{},
     generator_parameters{} {
     Q_UNUSED(registration);
 }
~GameCreator()
openage::gui::GameCreator::~GameCreator () virtual
Definition at line 31 of file game_creator.cpp.
{
 }
Member Function Documentation
activate()
void openage::gui::GameCreator::activate ()
Definition at line 38 of file game_creator.cpp.
{
     static auto f = [] (GameMainHandle *game,
                         GameSpecHandle *game_spec,
                         Generator *generator,
                         std::shared_ptr<GameCreatorSignals> callback) {
         QString error_msg;
         if (game->is_game_running()) {
             error_msg = "close existing game before loading";
         }
         else if (not game_spec->is_ready()) {
             error_msg = "game data has not finished loading";
         }
         else {
             auto game_main = generator->create(game_spec->get_spec());
             if (game_main) {
                 game->set_game(std::move(game_main));
             }
             else {
                 error_msg = "unknown error";
             }
         }
         emit callback->error_message(error_msg);
     };
     if (this->game && this->game_spec && this->generator_parameters) {
         std::shared_ptr<GameCreatorSignals> callback = std::make_shared<GameCreatorSignals>();
         QObject::connect(callback.get(), &GameCreatorSignals::error_message, this, &GameCreator::on_processed);
         this->game->i(f, this->game_spec, this->generator_parameters, callback);
     } else {
         this->on_processed([this] {
             if (!this->game)
                 return "provide 'game' before loading";
             if (!this->game_spec)
                 return "provide 'gameSpec' before loading";
             if (!this->generator_parameters)
                 return "provide 'generatorParameters' before loading";
             else
                 ENSURE(false, "unhandled case for refusal to create a game");
             return "unknown error";
         }());
     }
 }
References ENSURE, openage::gui::GameCreatorSignals::error_message(), game, game_spec, generator_parameters, openage::move, and on_processed().
clearErrors()
void openage::gui::GameCreator::clearErrors ()
Definition at line 88 of file game_creator.cpp.
{
     this->error_string.clear();
     emit this->error_string_changed();
 }
References error_string, and error_string_changed().
error_string_changed
void openage::gui::GameCreator::error_string_changed () signal
Referenced by clearErrors(), and on_processed().
game_changed
void openage::gui::GameCreator::game_changed () signal
game_spec_changed
void openage::gui::GameCreator::game_spec_changed () signal
generator_parameters_changed
void openage::gui::GameCreator::generator_parameters_changed () signal
get_error_string()
QString openage::gui::GameCreator::get_error_string () const
Definition at line 34 of file game_creator.cpp.
{
     return this->error_string;
 }
References error_string.
on_processed
void openage::gui::GameCreator::on_processed (const QString & error_string) slot
Definition at line 93 of file game_creator.cpp.
{
     this->error_string = error_string;
     emit this->error_string_changed();
 }
References error_string, and error_string_changed().
Referenced by activate().
Member Data Documentation
error_string
QString openage::gui::GameCreator::error_string private
Definition at line 42 of file game_creator.h.
Referenced by clearErrors(), get_error_string(), and on_processed().
game
GameMainLink* openage::gui::GameCreator::game private
Definition at line 43 of file game_creator.h.
game_spec
GameSpecLink* openage::gui::GameCreator::game_spec private
Definition at line 44 of file game_creator.h.
Referenced by activate().
generator_parameters
GeneratorLink* openage::gui::GameCreator::generator_parameters private
Definition at line 45 of file game_creator.h.
Referenced by activate().
Property Documentation
errorString
QString openage::gui::GameCreator::errorString read
Definition at line 18 of file game_creator.h.
game
openage::gui::GameMainLink openage::gui::GameCreator::game
Definition at line 19 of file game_creator.h.
Referenced by activate().
gameSpec
openage::gui::GameSpecLink openage::gui::GameCreator::gameSpec
Definition at line 20 of file game_creator.h.
generatorParameters
openage::gui::GeneratorLink openage::gui::GameCreator::generatorParameters
Definition at line 21 of file game_creator.h.
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/game_creator.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/game_creator.cpp