openage: openage::Command Class Reference
openage::Command Class Reference
#include <command.h>
Public Member Functions
Command (const Player &, Unit *unit)
Command (const Player &, coord::phys3 position)
Command (const Player &, Unit *unit, coord::phys3 position)
Command (const Player &, UnitType *t)
Command (const Player &, Research *res)
Command (const Player &, UnitType *, coord::phys3)
bool has_unit () const
bool has_position () const
bool has_type () const
bool has_research () const
Unit * unit () const
coord::phys3 position () const
UnitType * type () const
Research * research () const
void set_ability (ability_type t)
void set_ability_set (ability_set set)
const ability_set & ability () const
void add_flag (command_flag flag)
bool has_flag (command_flag flag) const
Public Attributes
const Player & player
Private Member Functions
Command (const Player &, Unit *unit, bool haspos, UnitType *t, Research *res)
Private Attributes
bool has_pos
Unit * u
coord::phys3 pos = {0, 0, 0}
UnitType * unit_type
Research * res
std::unordered_set< command_flag > flags
ability_set modifiers
Detailed Description
Definition at line 51 of file command.h.
Constructor & Destructor Documentation
Command() [1/7]
openage::Command::Command (const Player & p, Unit * unit)
target another unit
Definition at line 17 of file command.cpp.
     :
     Command{p, unit, false, nullptr, nullptr} {
 }
References unit().
Command() [2/7]
openage::Command::Command (const Player & p, coord::phys3 position)
target a position
Definition at line 22 of file command.cpp.
     :
     Command{p, nullptr, true, nullptr, nullptr} {
     this->pos = position;
 }
Command() [3/7]
openage::Command::Command (const Player & p, Unit * unit, coord::phys3 position)
target another unit or a position
Definition at line 28 of file command.cpp.
     :
     Command{p, unit, true, nullptr, nullptr} {
     this->pos = position;
 }
References unit().
Command() [4/7]
openage::Command::Command (const Player & p, UnitType * t)
select a type
Definition at line 34 of file command.cpp.
     :
     Command{p, nullptr, false, t, nullptr} {
 }
Command() [5/7]
openage::Command::Command (const Player & p, Research * res)
select a research
Definition at line 39 of file command.cpp.
     :
     Command{p, nullptr, false, nullptr, res} {
 }
References res.
Command() [6/7]
openage::Command::Command (const Player & p, UnitType * t, coord::phys3 position)
place building foundation
Definition at line 44 of file command.cpp.
     :
     Command{p, nullptr, true, t, nullptr} {
     this->pos = position;
 }
Command() [7/7]
openage::Command::Command (const Player & p, Unit * unit, bool haspos, UnitType * t, Research * res) private
basic constructor, which shouldnt be used directly
Definition at line 7 of file command.cpp.
     :
     player(p),
     has_pos{haspos},
     u{unit},
     unit_type{t},
     res{res} {
     this->modifiers.set();
 }
Member Function Documentation
ability()
const ability_set & openage::Command::ability () const
the ability types allowed to use this command
Definition at line 91 of file command.cpp.
{
     return this->modifiers;
 }
References modifiers.
Referenced by openage::Unit::queue_cmd().
add_flag()
void openage::Command::add_flag (command_flag flag)
add addition option to this command
Definition at line 95 of file command.cpp.
{
     this->flags.insert(flag);
 }
References flags.
Referenced by openage::ActionMode::on_game_control_set(), and openage::GatherAction::update_in_range().
has_flag()
bool openage::Command::has_flag (command_flag flag) const
read the range setting
Definition at line 99 of file command.cpp.
{
     return 0 < this->flags.count(flag);
 }
References flags.
Referenced by openage::Unit::apply_cmd(), openage::AttackAbility::can_invoke(), and openage::MoveAbility::invoke().
has_position()
bool openage::Command::has_position () const
Definition at line 54 of file command.cpp.
{
     return this->has_pos;
 }
References has_pos.
Referenced by openage::MoveAbility::can_invoke(), openage::SetPointAbility::can_invoke(), openage::UngarrisonAbility::can_invoke(), and openage::MoveAbility::invoke().
has_research()
bool openage::Command::has_research () const
Definition at line 62 of file command.cpp.
{
     return this->res;
 }
References res.
Referenced by openage::ResearchAbility::can_invoke().
has_type()
bool openage::Command::has_type () const
Definition at line 58 of file command.cpp.
{
     return this->unit_type;
 }
References unit_type.
Referenced by openage::TrainAbility::can_invoke().
has_unit()
bool openage::Command::has_unit () const
Definition at line 50 of file command.cpp.
{
     return this->u;
 }
References u.
Referenced by openage::MoveAbility::can_invoke(), openage::GarrisonAbility::can_invoke(), openage::BuildAbility::can_invoke(), openage::GatherAbility::can_invoke(), openage::AttackAbility::can_invoke(), openage::RepairAbility::can_invoke(), openage::HealAbility::can_invoke(), openage::ConvertAbility::can_invoke(), openage::MoveAbility::invoke(), and openage::BuildAbility::invoke().
position()
coord::phys3 openage::Command::position () const
Definition at line 70 of file command.cpp.
{
     return this->pos;
 }
References pos.
Referenced by openage::MoveAbility::invoke(), openage::SetPointAbility::invoke(), and openage::UngarrisonAbility::invoke().
research()
Research * openage::Command::research () const
Definition at line 78 of file command.cpp.
{
     return this->res;
 }
References res.
Referenced by openage::ResearchAbility::can_invoke(), and openage::ResearchAbility::invoke().
set_ability()
void openage::Command::set_ability (ability_type t)
sets invoked ability type, no other type may be used if this gets set
Parameters
type allows a specific ability type to be used for example to set a unit to patrol rather than the default move
Definition at line 82 of file command.cpp.
{
     this->modifiers = 0;
     this->modifiers[static_cast<int>(t)] = true;
 }
References modifiers.
Referenced by openage::ActionMode::get_action(), openage::ActionMode::place_selection(), and openage::GatherAction::update_in_range().
set_ability_set()
void openage::Command::set_ability_set (ability_set set)
restricts action to a set of possible ability types
Definition at line 87 of file command.cpp.
{
     this->modifiers = set;
 }
References modifiers.
type()
UnitType * openage::Command::type () const
Definition at line 74 of file command.cpp.
{
     return this->unit_type;
 }
References unit_type.
Referenced by openage::TrainAbility::invoke().
unit()
Unit * openage::Command::unit () const
Definition at line 66 of file command.cpp.
{
     return this->u;
 }
References u.
Referenced by openage::MoveAbility::can_invoke(), openage::GarrisonAbility::can_invoke(), openage::BuildAbility::can_invoke(), openage::GatherAbility::can_invoke(), openage::AttackAbility::can_invoke(), openage::RepairAbility::can_invoke(), openage::HealAbility::can_invoke(), openage::ConvertAbility::can_invoke(), Command(), openage::MoveAbility::invoke(), openage::GarrisonAbility::invoke(), openage::BuildAbility::invoke(), openage::GatherAbility::invoke(), openage::AttackAbility::invoke(), openage::RepairAbility::invoke(), openage::HealAbility::invoke(), and openage::ConvertAbility::invoke().
Member Data Documentation
flags
std::unordered_set<command_flag> openage::Command::flags private
additional options
Definition at line 144 of file command.h.
Referenced by add_flag(), and has_flag().
has_pos
bool openage::Command::has_pos private
Definition at line 135 of file command.h.
Referenced by has_position().
modifiers
ability_set openage::Command::modifiers private
select actions to use when targeting
Definition at line 149 of file command.h.
Referenced by ability(), set_ability(), and set_ability_set().
player
const Player& openage::Command::player
player who created the command
Definition at line 126 of file command.h.
Referenced by openage::UnitSelection::all_invoke().
pos
coord::phys3 openage::Command::pos = {0, 0, 0} private
Definition at line 137 of file command.h.
Referenced by openage.convert.binpack.Packer::height(), position(), openage.util.filelike.stream.StreamSeekBuffer::read(), openage.util.filelike.fifo.FIFO::read(), openage.util.filelike.stream.StreamFragment::read(), openage.cabextract.cab.CABFolderStream::read_blocks(), openage.util.filelike.readonly.PosSavingReadOnlyFileLikeObject::seek(), openage.util.filelike.fifo.FIFO::tell(), openage.util.filelike.readonly.PosSavingReadOnlyFileLikeObject::tell(), openage.cabextract.lzxdstream.LZXDStream::tell(), openage.util.filelike.fifo.FIFO::tellw(), and openage.convert.binpack.Packer::width().
res
Research* openage::Command::res private
Definition at line 139 of file command.h.
Referenced by Command(), has_research(), and research().
u
Unit* openage::Command::u private
Definition at line 136 of file command.h.
Referenced by has_unit(), and unit().
unit_type
UnitType* openage::Command::unit_type private
Definition at line 138 of file command.h.
Referenced by has_type(), and type().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/command.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/command.cpp