openage: openage::util::fslike::Directory Class Reference
openage::util::fslike::Directory Class Reference
#include <directory.h>
Public Member Functions
Directory (const std::string &basepath, bool create_if_missing=false)
bool is_file (const Path::parts_t &parts) override
bool is_dir (const Path::parts_t &parts) override
bool writable (const Path::parts_t &parts) override
std::vector< Path::part_t > list (const Path::parts_t &parts) override
bool mkdirs (const Path::parts_t &parts) override
File open_r (const Path::parts_t &parts) override
File open_w (const Path::parts_t &parts) override
File open_rw (const Path::parts_t &parts) override
File open_a (const Path::parts_t &parts) override
File open_ar (const Path::parts_t &parts) override
std::string get_native_path (const Path::parts_t &parts) override
bool rename (const Path::parts_t &parts, const Path::parts_t &target_parts) override
bool rmdir (const Path::parts_t &parts) override
bool touch (const Path::parts_t &parts) override
bool unlink (const Path::parts_t &parts) override
int get_mtime (const Path::parts_t &parts) override
uint64_t get_filesize (const Path::parts_t &parts) override
std::ostream & repr (std::ostream &) override
Public Member Functions inherited from openage::util::fslike::FSLike
FSLike ()
virtual ~FSLike ()=default
virtual Path root ()
virtual std::pair< bool, Path > resolve_r (const Path::parts_t &parts)
virtual std::pair< bool, Path > resolve_w (const Path::parts_t &parts)
virtual bool is_python_native () const noexcept
Protected Member Functions
std::string resolve (const Path::parts_t &parts) const
std::tuple< struct stat, int > do_stat (const Path::parts_t &parts) const
Protected Attributes
std::string basepath
Detailed Description
Filesystem-like object which uses native libc calls. It is used to directly access your real filesystem that the kernel mounted for you.
Definition at line 24 of file directory.h.
Constructor & Destructor Documentation
Directory()
openage::util::fslike::Directory::Directory (const std::string & basepath, bool create_if_missing = false)
Definition at line 45 of file directory.cpp.
     :
     basepath{basepath} {
     if (create_if_missing) {
         this->mkdirs({});
     }
 }
References basepath.
Member Function Documentation
do_stat()
std::tuple< struct stat, int > openage::util::fslike::Directory::do_stat (const Path::parts_t & parts) const protected
Definition at line 69 of file directory.cpp.
{
     const std::string path = this->resolve(parts);
     struct stat buf;
     int result = stat(path.c_str(), &buf);
     return std::make_tuple(buf, result);
 }
References resolve(), and openage.testing.testing::result().
Referenced by get_filesize(), get_mtime(), is_dir(), and is_file().
get_filesize()
uint64_t openage::util::fslike::Directory::get_filesize (const Path::parts_t & parts) override virtual
Implements openage::util::fslike::FSLike.
Definition at line 295 of file directory.cpp.
{
     auto stat_result = this->do_stat(parts);
     // return the mtime
     if (std::get<1>(stat_result) == 0) {
         return std::get<0>(stat_result).st_size;
     }
     throw Error{ERR << "can't get filesize"};
 }
References do_stat(), and ERR.
get_mtime()
int openage::util::fslike::Directory::get_mtime (const Path::parts_t & parts) override virtual
Implements openage::util::fslike::FSLike.
Definition at line 277 of file directory.cpp.
{
     auto stat_result = this->do_stat(parts);
     // return the mtime
     if (std::get<1>(stat_result) == 0) {
 #ifdef __APPLE__
         return std::get<0>(stat_result).st_mtimespec.tv_sec;
 #elif defined _WIN32
         return std::get<0>(stat_result).st_mtime;
 #else
         return std::get<0>(stat_result).st_mtim.tv_sec;
 #endif
     }
     throw Error{ERR << "can't get mtime"};
 }
References do_stat(), and ERR.
get_native_path()
std::string openage::util::fslike::Directory::get_native_path (const Path::parts_t & parts) override virtual
Implements openage::util::fslike::FSLike.
Definition at line 225 of file directory.cpp.
{
     return this->resolve(parts);
 }
References resolve().
is_dir()
bool openage::util::fslike::Directory::is_dir (const Path::parts_t & parts) override virtual
Implements openage::util::fslike::FSLike.
Definition at line 91 of file directory.cpp.
{
     auto stat_result = this->do_stat(parts);
     // test for regular file
     if (std::get<1>(stat_result) == 0 and
         S_ISDIR(std::get<0>(stat_result).st_mode)) {
         return true;
     }
     return false;
 }
References do_stat().
Referenced by openage.util.fslike.abstract.FSLikeObject::exists(), openage.util.fslike.path.Path::removerecursive(), and writable().
is_file()
bool openage::util::fslike::Directory::is_file (const Path::parts_t & parts) override virtual
Implements openage::util::fslike::FSLike.
Definition at line 78 of file directory.cpp.
{
     auto stat_result = this->do_stat(parts);
     // test for regular file
     if (std::get<1>(stat_result) == 0 and
         S_ISREG(std::get<0>(stat_result).st_mode)) {
         return true;
     }
     return false;
 }
References do_stat().
Referenced by openage.util.fslike.abstract.FSLikeObject::exists(), and writable().
list()
std::vector< Path::part_t > openage::util::fslike::Directory::list (const Path::parts_t & parts) override virtual
Implements openage::util::fslike::FSLike.
Definition at line 123 of file directory.cpp.
{
     const std::string path = this->resolve(parts);
     std::vector<Path::part_t> ret;
     DIR *dir;
     struct dirent *ent;
     dir = opendir(path.c_str());
     if (dir == nullptr) {
         throw Error(ERR << "could not list contents of '" << path << "'");
     }
     // walk over dir contents
     while ((ent = readdir(dir)) != nullptr) {
         ret.push_back(ent->d_name);
     }
     closedir(dir);
     return ret;
 }
References ERR, and resolve().
mkdirs()
bool openage::util::fslike::Directory::mkdirs (const Path::parts_t & parts) override virtual
Implements openage::util::fslike::FSLike.
Definition at line 148 of file directory.cpp.
{
     Path::parts_t all_parts = util::split(this->basepath, PATHSEP);
     vector_extend(all_parts, parts);
     std::string dirpath;
     for (auto &part : all_parts) {
         dirpath += PATHSEP + part;
         struct stat buf;
         // it it exists already, try creating the next one
         if (stat(dirpath.c_str(), &buf) == 0 and
             S_ISDIR(buf.st_mode)) {
             continue;
         }
         // create the folder, umask will turn it to 755.
 #ifdef _MSC_VER
         bool dir_created = _mkdir(dirpath.c_str()) == 0;
 #elif __MINGW32__
         bool dir_created = mkdir(dirpath.c_str()) == 0;
 #else
         bool dir_created = mkdir(dirpath.c_str(), 0777) == 0;
 #endif
         if (not dir_created) {
             return false;
         }
     }
     return true;
 }
References basepath, openage::util::fslike::PATHSEP, openage::util::split(), and openage::util::vector_extend().
Referenced by openage.util.fslike.wrapper.DirectoryCreator::open_w().
open_a()
File openage::util::fslike::Directory::open_a (const Path::parts_t & parts) override virtual
Implements openage::util::fslike::FSLike.
Definition at line 209 of file directory.cpp.
{
     return File{
         std::make_shared<filelike::Native>(this->resolve(parts),
                                            filelike::Native::mode_t::A)
     };
 }
References openage::util::filelike::FileLike::A, and resolve().
open_ar()
File openage::util::fslike::Directory::open_ar (const Path::parts_t & parts) override virtual
Implements openage::util::fslike::FSLike.
Definition at line 217 of file directory.cpp.
{
     return File{
         std::make_shared<filelike::Native>(this->resolve(parts),
                                            filelike::Native::mode_t::AR)
     };
 }
References openage::util::filelike::FileLike::AR, and resolve().
open_r()
File openage::util::fslike::Directory::open_r (const Path::parts_t & parts) override virtual
Implements openage::util::fslike::FSLike.
Definition at line 185 of file directory.cpp.
{
     return File{
         std::make_shared<filelike::Native>(this->resolve(parts),
                                            filelike::Native::mode_t::R)
     };
 }
References openage::util::filelike::FileLike::R, and resolve().
open_rw()
File openage::util::fslike::Directory::open_rw (const Path::parts_t & parts) override virtual
Implements openage::util::fslike::FSLike.
Definition at line 201 of file directory.cpp.
{
     return File{
         std::make_shared<filelike::Native>(this->resolve(parts),
                                            filelike::Native::mode_t::RW)
     };
 }
References resolve(), and openage::util::filelike::FileLike::RW.
open_w()
File openage::util::fslike::Directory::open_w (const Path::parts_t & parts) override virtual
Implements openage::util::fslike::FSLike.
Definition at line 193 of file directory.cpp.
{
     return File{
         std::make_shared<filelike::Native>(this->resolve(parts),
                                            filelike::Native::mode_t::W)
     };
 }
References resolve(), and openage::util::filelike::FileLike::W.
rename()
bool openage::util::fslike::Directory::rename (const Path::parts_t & parts, const Path::parts_t & target_parts) override virtual
Implements openage::util::fslike::FSLike.
Definition at line 230 of file directory.cpp.
{
     return std::rename(this->resolve(parts).c_str(),
                        this->resolve(target_parts).c_str()) == 0;
 }
References resolve().
repr()
std::ostream & openage::util::fslike::Directory::repr (std::ostream & stream) override virtual
Implements openage::util::fslike::FSLike.
Definition at line 307 of file directory.cpp.
{
     stream << this->basepath;
     return stream;
 }
References basepath.
resolve()
std::string openage::util::fslike::Directory::resolve (const Path::parts_t & parts) const protected
resolve the path to an actually usable one. basically basepath + "/".join(parts)
Definition at line 59 of file directory.cpp.
{
     std::string ret = this->basepath;
     for (auto &part : parts) {
         ret += PATHSEP + part;
     }
     return ret;
 }
References basepath, and openage::util::fslike::PATHSEP.
Referenced by do_stat(), openage.util.fslike.directory.Directory::filesize(), get_native_path(), openage.util.fslike.directory.Directory::get_native_path(), openage.util.fslike.directory.Directory::is_dir(), openage.util.fslike.directory.Directory::is_file(), list(), openage.util.fslike.directory.Directory::list(), openage.util.fslike.directory.Directory::mkdirs(), openage.util.fslike.directory.Directory::mtime(), open_a(), openage.util.fslike.directory.Directory::open_a(), open_ar(), openage.util.fslike.directory.Directory::open_ar(), open_r(), openage.util.fslike.directory.Directory::open_r(), open_rw(), openage.util.fslike.directory.Directory::open_rw(), open_w(), openage.util.fslike.directory.Directory::open_w(), rename(), openage.util.fslike.directory.Directory::rename(), rmdir(), openage.util.fslike.directory.Directory::rmdir(), touch(), openage.util.fslike.directory.Directory::touch(), unlink(), openage.util.fslike.directory.Directory::unlink(), writable(), and openage.util.fslike.directory.Directory::writable().
rmdir()
bool openage::util::fslike::Directory::rmdir (const Path::parts_t & parts) override virtual
Implements openage::util::fslike::FSLike.
Definition at line 238 of file directory.cpp.
{
     return ::rmdir(this->resolve(parts).c_str()) == 0;
 }
References resolve().
Referenced by openage.util.fslike.path.Path::removerecursive().
touch()
bool openage::util::fslike::Directory::touch (const Path::parts_t & parts) override virtual
Implements openage::util::fslike::FSLike.
Definition at line 243 of file directory.cpp.
{
     const std::string path = this->resolve(parts);
     // create the file if missing
     int fd = open(
         path.c_str(),
         O_WRONLY|O_CREAT|O_NOCTTY|O_NONBLOCK,
         0666
     );
     if (fd < 0) {
         return false;
     }
     close(fd);
     // update the timestamp
 #ifdef __APPLE__
     int result = utimes(path.c_str(), nullptr) == 0;
 #elif defined _WIN32
     int result = _utime(path.c_str(), nullptr) == 0;
 #else
     int result = utimensat(AT_FDCWD, path.c_str(), nullptr, 0) == 0;
 #endif
     return result;
 }
References resolve(), and openage.testing.testing::result().
unlink()
bool openage::util::fslike::Directory::unlink (const Path::parts_t & parts) override virtual
Implements openage::util::fslike::FSLike.
Definition at line 272 of file directory.cpp.
{
     return std::remove(this->resolve(parts).c_str()) == 0;
 }
References resolve().
Referenced by openage.util.fslike.path.Path::removerecursive().
writable()
bool openage::util::fslike::Directory::writable (const Path::parts_t & parts) override virtual
Implements openage::util::fslike::FSLike.
Definition at line 104 of file directory.cpp.
{
     Path::parts_t parts_test = parts;
     // try to find the first existing path-part
     while (not (this->is_dir(parts_test) or
                 this->is_file(parts_test))) {
         if (parts_test.size() == 0) {
             throw Error{ERR << "file not found"};
         }
         parts_test.pop_back();
     }
     const std::string path = this->resolve(parts_test);
     return access(path.c_str(), W_OK);
 }
References ERR, is_dir(), is_file(), and resolve().
Referenced by openage.util.fslike.wrapper.Wrapper::resolve_w(), and openage.util.fslike.abstract.FSLikeObject::resolve_w().
Member Data Documentation
basepath
std::string openage::util::fslike::Directory::basepath protected
Definition at line 60 of file directory.h.
Referenced by Directory(), mkdirs(), repr(), and resolve().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/fslike/directory.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/fslike/directory.cpp