openage: openage::GameControlSignals Class Reference
openage::GameControlSignals Class Reference
#include <game_control.h>
Public Slots
void on_game_running (bool running)
Signals
void mode_changed (OutputMode *mode, int mode_index)
void modes_changed (OutputMode *mode, int mode_index)
void current_player_name_changed (const std::string &current_player_name)
void current_civ_index_changed (int current_civ_index)
Public Member Functions
GameControlSignals (GameControl *game_control)
Private Attributes
GameControl * game_control
Detailed Description
Definition at line 325 of file game_control.h.
Constructor & Destructor Documentation
GameControlSignals()
openage::GameControlSignals::GameControlSignals (GameControl * game_control) explicit
Definition at line 709 of file game_control.cpp.
     :
     game_control{game_control} {
 }
References game_control.
Member Function Documentation
current_civ_index_changed
void openage::GameControlSignals::current_civ_index_changed (int current_civ_index) signal
Referenced by openage::GameControl::announce_current_player_name(), and openage::gui::GameControlLink::on_core_adopted().
current_player_name_changed
void openage::GameControlSignals::current_player_name_changed (const std::string & current_player_name) signal
Referenced by openage::GameControl::announce_current_player_name(), openage::gui::GameControlLink::on_core_adopted(), and openage::EditorMode::set_game_control().
mode_changed
void openage::GameControlSignals::mode_changed (OutputMode * mode, int mode_index) signal
Referenced by openage::GameControl::announce_mode(), and openage::gui::GameControlLink::on_core_adopted().
modes_changed
void openage::GameControlSignals::modes_changed (OutputMode * mode, int mode_index) signal
Referenced by openage::gui::GameControlLink::on_core_adopted(), and openage::GameControl::set_modes().
on_game_running
void openage::GameControlSignals::on_game_running (bool running) slot
Definition at line 714 of file game_control.cpp.
{
     if (running)
         this->game_control->announce_current_player_name();
 }
References openage::GameControl::announce_current_player_name(), and game_control.
Referenced by openage::GameControl::set_game().
Member Data Documentation
game_control
GameControl* openage::GameControlSignals::game_control private
Definition at line 342 of file game_control.h.
Referenced by GameControlSignals(), and on_game_running().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/game_control.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/game_control.cpp