openage: openage::renderer::opengl::GlShaderProgram Class Reference
openage::renderer::opengl::GlShaderProgram Class Reference final
A handle to an OpenGL shader program.
#include <shader_program.h>
Classes
struct GlInBlockUniform
Represents a uniform in a named block.
struct GlUniform
Represents a uniform in the default block, i.e. not within a named block.
struct GlUniformBlock
Represents a uniform block in the shader program.
struct GlVertexAttrib
Represents a per-vertex input to the shader program.
Public Member Functions
GlShaderProgram (const std::vector< resources::ShaderSource > &, const gl_context_capabilities &)
void use ()
Bind this program as the currently used one in the OpenGL context.
void execute_with (const GlUniformInput *, const GlGeometry *)
bool has_uniform (const char *) override
Returns whether the shader program contains a uniform variable with the given name.
std::map< size_t, resources::vertex_input_t > vertex_attributes () const override
Public Member Functions inherited from openage::renderer::ShaderProgram
virtual ~ShaderProgram ()=default
void update_uniform_input (UniformInput *)
void update_uniform_input (UniformInput *input, const char *unif, int32_t val)
void update_uniform_input (UniformInput *input, const char *unif, uint32_t val)
void update_uniform_input (UniformInput *input, const char *unif, float val)
void update_uniform_input (UniformInput *input, const char *unif, double val)
void update_uniform_input (UniformInput *input, const char *unif, Eigen::Vector2f const &val)
void update_uniform_input (UniformInput *input, const char *unif, Eigen::Vector3f const &val)
void update_uniform_input (UniformInput *input, const char *unif, Eigen::Vector4f const &val)
void update_uniform_input (UniformInput *input, const char *unif, Texture2d const *val)
void update_uniform_input (UniformInput *input, const char *unif, Texture2d *val)
void update_uniform_input (UniformInput *input, const char *unif, Eigen::Matrix4f const &val)
template<typename T >
void update_uniform_input (UniformInput *, const char *unif, T)
template<typename... Ts>
std::unique_ptr< UniformInput > new_uniform_input (Ts... vals)
template<typename T , typename... Ts>
void update_uniform_input (UniformInput *input, const char *unif, T val, Ts... vals)
Public Member Functions inherited from openage::renderer::opengl::GlSimpleObject
GlSimpleObject (GlSimpleObject &&)
GlSimpleObject & operator= (GlSimpleObject &&)
GlSimpleObject (GlSimpleObject const &)=delete
GlSimpleObject & operator= (GlSimpleObject const &)=delete
virtual ~GlSimpleObject ()
GLuint get_handle () const
Returns the handle to the underlying OpenGL Object.
Protected Member Functions
std::unique_ptr< UniformInput > new_unif_in () override
void set_i32 (UniformInput *, const char *, int32_t) override
void set_u32 (UniformInput *, const char *, uint32_t) override
void set_f32 (UniformInput *, const char *, float) override
void set_f64 (UniformInput *, const char *, double) override
void set_v2f32 (UniformInput *, const char *, Eigen::Vector2f const &) override
void set_v3f32 (UniformInput *, const char *, Eigen::Vector3f const &) override
void set_v4f32 (UniformInput *, const char *, Eigen::Vector4f const &) override
void set_m4f32 (UniformInput *, const char *, Eigen::Matrix4f const &) override
void set_tex (UniformInput *, const char *, Texture2d const *) override
Protected Member Functions inherited from openage::renderer::opengl::GlSimpleObject
GlSimpleObject (std::function< void(GLuint)> delete_fun)
Private Member Functions
void set_unif (UniformInput *, const char *, void const *, GLenum)
Private Attributes
std::unordered_map< std::string, GlUniform > uniforms
std::unordered_map< std::string, GlUniformBlock > uniform_blocks
Maps uniform block names to their descriptions.
std::unordered_map< std::string, GlVertexAttrib > attribs
Maps per-vertex attribute names to their descriptions.
std::unordered_map< std::string, GLuint > texunits_per_unifs
Maps sampler uniform names to their assigned texture units.
std::unordered_map< GLuint, GLuint > textures_per_texunits
Maps texture units to the texture handles that are currently bound to them.
bool validated
Whether this program has been validated.
Additional Inherited Members
Protected Attributes inherited from openage::renderer::opengl::GlSimpleObject
std::optional< GLuint > handle
The handle to the OpenGL Object that this class represents.
std::function< void(GLuint)> delete_fun
The function that deletes the underlying OpenGL Object.
Detailed Description
A handle to an OpenGL shader program.
Definition at line 23 of file shader_program.h.
Constructor & Destructor Documentation
GlShaderProgram()
openage::renderer::opengl::GlShaderProgram::GlShaderProgram (const std::vector< resources::ShaderSource > & srcs, const gl_context_capabilities & caps) explicit
Tries to create a shader program from the given sources. Throws an exception on compile/link errors.
Definition at line 50 of file shader_program.cpp.
     : GlSimpleObject([] (GLuint handle) { glDeleteProgram(handle); } )
     , validated(false) {
     GLuint handle = glCreateProgram();
     this->handle = handle;
     std::vector<GlShader> shaders;
     for (auto const& src : srcs) {
         GlShader shader(src);
         glAttachShader(handle, shader.get_handle());
         shaders.push_back(std::move(shader));
     }
     glLinkProgram(handle);
     check_program_status(handle, GL_LINK_STATUS);
     // after linking we can delete the shaders
     for (auto const& shdr : shaders) {
         glDetachShader(handle, shdr.get_handle());
     }
     // query program information
     GLint val;
     glGetProgramiv(handle, GL_ACTIVE_ATTRIBUTES, &val);
     size_t attrib_count = val;
     glGetProgramiv(handle, GL_ACTIVE_ATTRIBUTE_MAX_LENGTH, &val);
     size_t max_name_len = val;
     glGetProgramiv(handle, GL_ACTIVE_UNIFORMS, &val);
     size_t unif_count = val;
     glGetProgramiv(handle, GL_ACTIVE_UNIFORM_MAX_LENGTH, &val);
     max_name_len = std::max(size_t(val), max_name_len);
     glGetProgramiv(handle, GL_ACTIVE_UNIFORM_BLOCKS, &val);
     size_t unif_block_count = val;
     glGetProgramiv(handle, GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH, &val);
     max_name_len = std::max(size_t(val), max_name_len);
     std::vector<char> name(max_name_len);
     // Indices of uniforms within named blocks.
     std::unordered_set<GLuint> in_block_unifs;
     GLuint block_binding = 0;
     // Extract uniform block descriptions.
     for (GLuint i_unif_block = 0; i_unif_block < unif_block_count; ++i_unif_block) {
         glGetActiveUniformBlockName(
             handle,
             i_unif_block,
             name.size(),
             nullptr,
             name.data()
         );
         std::string block_name(name.data());
         GLint data_size;
         glGetActiveUniformBlockiv(handle, i_unif_block, GL_UNIFORM_BLOCK_DATA_SIZE, &data_size);
         glGetActiveUniformBlockiv(handle, i_unif_block, GL_UNIFORM_BLOCK_ACTIVE_UNIFORMS, &val);
         std::vector<GLint> uniform_indices(val);
         glGetActiveUniformBlockiv(handle, i_unif_block, GL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES, uniform_indices.data());
         std::unordered_map<std::string, GlInBlockUniform> uniforms;
         for (GLuint const i_unif : uniform_indices) {
             in_block_unifs.insert(i_unif);
             GLenum type;
             GLint offset, count, stride;
             glGetActiveUniform(
                 handle,
                 i_unif,
                 name.size(),
                 nullptr,
                 &count,
                 &type,
                 name.data()
             );
             glGetActiveUniformsiv(handle, 1, &i_unif, GL_UNIFORM_OFFSET, &offset);
             glGetActiveUniformsiv(handle, 1, &i_unif, GL_UNIFORM_ARRAY_STRIDE, &stride);
             if (stride == 0) {
                 // The uniform is not an array, but it's declared in a named block and hence might
                 // be a matrix whose stride we need to know.
                 glGetActiveUniformsiv(handle, 1, &i_unif, GL_UNIFORM_MATRIX_STRIDE, &stride);
             }
             // We do not need to handle sampler types here like in the uniform loop below,
             // because named blocks cannot contain samplers.
             uniforms.insert(std::make_pair(
                 name.data(),
                 GlInBlockUniform {
                     type,
                     size_t(offset),
                     size_t(count) * GL_SHADER_TYPE_SIZE.get(type),
                     size_t(stride),
                     size_t(count)
                 }
             ));
         }
         ENSURE(block_binding < caps.max_uniform_buffer_bindings,
             "Tried to create an OpenGL shader that uses more uniform blocks "
             << "than there are binding points (" << caps.max_uniform_buffer_bindings
             << " available)."
         );
         glUniformBlockBinding(handle, i_unif_block, block_binding);
         this->uniform_blocks.insert(std::make_pair(
             block_name,
             GlUniformBlock {
                 i_unif_block,
                 size_t(data_size),
                 std::move(uniforms),
                 block_binding
             }
         ));
         block_binding += 1;
     }
     GLuint tex_unit = 0;
     // Extract information about uniforms in the default block.
     for (GLuint i_unif = 0; i_unif < unif_count; ++i_unif) {
         if (in_block_unifs.count(i_unif) == 1) {
             // Skip uniforms within named blocks.
             continue;
         }
         GLint count;
         GLenum type;
         glGetActiveUniform(
             handle,
             i_unif,
             name.size(),
             nullptr,
             &count,
             &type,
             name.data()
         );
         GLuint loc = glGetUniformLocation(handle, name.data());
         this->uniforms.insert(std::make_pair(
             name.data(),
             GlUniform {
                 type,
                 loc
             }
         ));
         if (type == GL_SAMPLER_2D) {
             ENSURE(tex_unit < caps.max_texture_slots,
                 "Tried to create an OpenGL shader that uses more texture sampler uniforms "
                 << "than there are texture unit slots (" << caps.max_texture_slots << " available)."
             );
             this->texunits_per_unifs.insert(std::make_pair(name.data(), tex_unit));
             tex_unit += 1;
         }
     }
     // Extract vertex attribute descriptions.
     for (GLuint i_attrib = 0; i_attrib < attrib_count; ++i_attrib) {
         GLint size;
         GLenum type;
         glGetActiveAttrib(
             handle,
             i_attrib,
             name.size(),
             nullptr,
             &size,
             &type,
             name.data()
         );
         this->attribs.insert(std::make_pair(
             name.data(),
             GlVertexAttrib {
                 type,
                 GLint(i_attrib),
                 size,
             }
         ));
     }
     log::log(MSG(info) << "Created OpenGL shader program");
     if (!this->uniform_blocks.empty()) {
         log::log(MSG(dbg) << "Uniform blocks: ");
         for (auto const& pair : this->uniform_blocks) {
             log::log(MSG(dbg) << "(" << pair.second.index << ") " << pair.first
                               << " (size: " << pair.second.data_size << ") {");
             for (auto const& unif_pair : pair.second.uniforms) {
                 log::log(MSG(dbg) << "\t+" << unif_pair.second.offset
                                   << " " << unif_pair.first << ": "
                                   << GLSL_TYPE_NAME.get(unif_pair.second.type));
             }
             log::log(MSG(dbg) << "}");
         }
     }
     if (!this->uniforms.empty()) {
         log::log(MSG(dbg) << "Uniforms: ");
         for (auto const& pair : this->uniforms) {
             log::log(MSG(dbg) << "(" << pair.second.location << ") " << pair.first << ": "
                               << GLSL_TYPE_NAME.get(pair.second.type));
         }
     }
     if (!this->attribs.empty()) {
         log::log(MSG(dbg) << "Vertex attributes: ");
         for (auto const& pair : this->attribs) {
             log::log(MSG(dbg) << "(" << pair.second.location << ") " << pair.first << ": "
                               << GLSL_TYPE_NAME.get(pair.second.type));
         }
     }
 }
References openage::renderer::opengl::GlSimpleObject::handle.
Member Function Documentation
execute_with()
void openage::renderer::opengl::GlShaderProgram::execute_with (const GlUniformInput * unif_in, const GlGeometry * geom)
Does what the description of Renderable specifies - updates the uniform values and draws the Geometry if it's not nullptr. If geometry is null, only the uniform values are updated.
Definition at line 301 of file shader_program.cpp.
{
     ENSURE(unif_in->program == this, "Uniform input passed to different shader than it was created with.");
     this->use();
     uint8_t const* data = unif_in->update_data.data();
     for (auto const &pair : unif_in->update_offs) {
         uint8_t const* ptr = data + pair.second;
         auto loc = this->uniforms[pair.first].location;
         switch (this->uniforms[pair.first].type) {
         case GL_INT:
             glUniform1i(loc, *reinterpret_cast<const GLint*>(ptr));
             break;
         case GL_UNSIGNED_INT:
             glUniform1ui(loc, *reinterpret_cast<const GLuint*>(ptr));
             break;
         case GL_FLOAT:
             glUniform1f(loc, *reinterpret_cast<const float*>(ptr));
             break;
         case GL_DOUBLE:
             // \todo requires an extension
             glUniform1d(loc, *reinterpret_cast<const double*>(ptr));
             break;
         case GL_FLOAT_VEC2:
             glUniform2fv(loc, 1, reinterpret_cast<const float*>(ptr));
             break;
         case GL_FLOAT_VEC3:
             glUniform3fv(loc, 1, reinterpret_cast<const float*>(ptr));
             break;
         case GL_FLOAT_VEC4:
             glUniform4fv(loc, 1, reinterpret_cast<const float*>(ptr));
             break;
         case GL_FLOAT_MAT3:
             glUniformMatrix3fv(loc, 1, GLboolean(false), reinterpret_cast<const float*>(ptr));
             break;
         case GL_FLOAT_MAT4:
             glUniformMatrix4fv(loc, 1, GLboolean(false), reinterpret_cast<const float*>(ptr));
             break;
         case GL_INT_VEC2:
             glUniform2iv(loc, 1, reinterpret_cast<const GLint*>(ptr));
             break;
         case GL_INT_VEC3:
             glUniform3iv(loc, 1, reinterpret_cast<const GLint*>(ptr));
             break;
         case GL_SAMPLER_2D: {
             GLuint tex_unit = this->texunits_per_unifs[pair.first];
             GLuint tex = *reinterpret_cast<const GLuint*>(ptr);
             glActiveTexture(GL_TEXTURE0 + tex_unit);
             glBindTexture(GL_TEXTURE_2D, tex);
             // \todo maybe call this at a more appropriate position
             glUniform1i(loc, tex_unit);
             this->textures_per_texunits[tex_unit] = tex;
             break;
         }
         default:
             throw Error(MSG(err) << "Tried to upload unknown uniform type to GL shader.");
         }
     }
     if (geom != nullptr) {
         // \todo read obj.blend + family
         geom->draw();
     }
 }
References openage::renderer::opengl::GlGeometry::draw(), ENSURE, openage::log::err(), MSG, openage::renderer::opengl::GlUniformInput::program, textures_per_texunits, texunits_per_unifs, openage::renderer::opengl::GlUniformInput::update_data, openage::renderer::opengl::GlUniformInput::update_offs, and use().
has_uniform()
bool openage::renderer::opengl::GlShaderProgram::has_uniform (const char * unif) override virtual
Returns whether the shader program contains a uniform variable with the given name.
Implements openage::renderer::ShaderProgram.
Definition at line 383 of file shader_program.cpp.
{
     return this->uniforms.count(name) == 1;
 }
new_unif_in()
std::unique_ptr< UniformInput > openage::renderer::opengl::GlShaderProgram::new_unif_in () override protected virtual
Implements openage::renderer::ShaderProgram.
Definition at line 377 of file shader_program.cpp.
{
     auto in = std::make_unique<GlUniformInput>();
     in->program = this;
     return in;
 }
set_f32()
void openage::renderer::opengl::GlShaderProgram::set_f32 (UniformInput * in, const char * unif, float val) override protected virtual
Implements openage::renderer::ShaderProgram.
Definition at line 424 of file shader_program.cpp.
{
     this->set_unif(in, unif, &val, GL_FLOAT);
 }
References set_unif(), and val.
set_f64()
void openage::renderer::opengl::GlShaderProgram::set_f64 (UniformInput * in, const char * unif, double val) override protected virtual
Implements openage::renderer::ShaderProgram.
Definition at line 428 of file shader_program.cpp.
{
     // \todo requires extension
     this->set_unif(in, unif, &val, GL_DOUBLE);
 }
References set_unif(), and val.
set_i32()
void openage::renderer::opengl::GlShaderProgram::set_i32 (UniformInput * in, const char * unif, int32_t val) override protected virtual
Implements openage::renderer::ShaderProgram.
Definition at line 416 of file shader_program.cpp.
{
     this->set_unif(in, unif, &val, GL_INT);
 }
References set_unif(), and val.
set_m4f32()
void openage::renderer::opengl::GlShaderProgram::set_m4f32 (UniformInput * in, const char * unif, Eigen::Matrix4f const & val) override protected virtual
Implements openage::renderer::ShaderProgram.
Definition at line 445 of file shader_program.cpp.
{
     this->set_unif(in, unif, val.data(), GL_FLOAT_MAT4);
 }
References set_unif(), and val.
set_tex()
void openage::renderer::opengl::GlShaderProgram::set_tex (UniformInput * in, const char * unif, Texture2d const * val) override protected virtual
Implements openage::renderer::ShaderProgram.
Definition at line 449 of file shader_program.cpp.
{
     auto const& tex = *static_cast<const GlTexture2d*>(val);
     GLuint handle = tex.get_handle();
     this->set_unif(in, unif, &handle, GL_SAMPLER_2D);
 }
References openage::renderer::opengl::GlSimpleObject::handle, set_unif(), and val.
set_u32()
void openage::renderer::opengl::GlShaderProgram::set_u32 (UniformInput * in, const char * unif, uint32_t val) override protected virtual
Implements openage::renderer::ShaderProgram.
Definition at line 420 of file shader_program.cpp.
{
     this->set_unif(in, unif, &val, GL_UNSIGNED_INT);
 }
References set_unif(), and val.
set_unif()
void openage::renderer::opengl::GlShaderProgram::set_unif (UniformInput * in, const char * unif, void const * val, GLenum type) private
Definition at line 387 of file shader_program.cpp.
{
     auto *unif_in = static_cast<GlUniformInput*>(in);
     ENSURE(this->uniforms.count(unif) != 0,
         "Tried to set uniform " << unif << " that does not exist in the shader program."
     );
     auto const& unif_data = this->uniforms.at(unif);
     ENSURE(type == unif_data.type,
         "Tried to set uniform " << unif << " to a value of the wrong type."
     );
     size_t size = GL_SHADER_TYPE_SIZE.get(unif_data.type);
     if (unif_in->update_offs.count(unif) == 1) {
         // already wrote to this uniform since last upload
         size_t off = unif_in->update_offs[unif];
         memcpy(unif_in->update_data.data() + off, val, size);
     } else {
         // first time writing to this uniform since last upload, so
         // extend the buffer before storing the uniform value
         size_t prev_size = unif_in->update_data.size();
         unif_in->update_data.resize(prev_size + size);
         memcpy(unif_in->update_data.data() + prev_size, val, size);
         unif_in->update_offs.emplace(unif, prev_size);
     }
 }
References ENSURE, openage::renderer::opengl::GL_SHADER_TYPE_SIZE, and val.
Referenced by set_f32(), set_f64(), set_i32(), set_m4f32(), set_tex(), set_u32(), set_v2f32(), set_v3f32(), and set_v4f32().
set_v2f32()
void openage::renderer::opengl::GlShaderProgram::set_v2f32 (UniformInput * in, const char * unif, Eigen::Vector2f const & val) override protected virtual
Implements openage::renderer::ShaderProgram.
Definition at line 433 of file shader_program.cpp.
{
     this->set_unif(in, unif, &val, GL_FLOAT_VEC2);
 }
References set_unif(), and val.
set_v3f32()
void openage::renderer::opengl::GlShaderProgram::set_v3f32 (UniformInput * in, const char * unif, Eigen::Vector3f const & val) override protected virtual
Implements openage::renderer::ShaderProgram.
Definition at line 437 of file shader_program.cpp.
{
     this->set_unif(in, unif, &val, GL_FLOAT_VEC3);
 }
References set_unif(), and val.
set_v4f32()
void openage::renderer::opengl::GlShaderProgram::set_v4f32 (UniformInput * in, const char * unif, Eigen::Vector4f const & val) override protected virtual
Implements openage::renderer::ShaderProgram.
Definition at line 441 of file shader_program.cpp.
{
     this->set_unif(in, unif, &val, GL_FLOAT_VEC4);
 }
References set_unif(), and val.
use()
void openage::renderer::opengl::GlShaderProgram::use ()
Bind this program as the currently used one in the OpenGL context.
Definition at line 272 of file shader_program.cpp.
{
     if (!this->validated) {
         // \todo (Vtec234): validation depends on the context state, so this might be worth calling
         // more than once. However, once per frame is probably too much.
         glValidateProgram(*this->handle);
         check_program_status(*this->handle, GL_VALIDATE_STATUS);
         this->validated = true;
     }
     glUseProgram(*this->handle);
     for (auto const &pair : this->textures_per_texunits) {
         // We have to bind the texture to their texture units here because
         // the texture unit bindings are global to the context. Each time
         // the shader switches, it is possible that some other shader overwrote
         // these, and since we want the uniform values to persist across execute_with
         // calls, we have to set them more often than just on execute_with.
         glActiveTexture(GL_TEXTURE0 + pair.first);
         glBindTexture(GL_TEXTURE_2D, pair.second);
         // By the time we call bind, the texture may have been deleted, but if it's fixed
         // afterwards using execute_with, the render state will still be fine, so we can ignore
         // this error.
         // \todo this will swallow actual errors elsewhere, and should be avoided. how?
         glGetError();
     }
 }
References openage::renderer::opengl::check_program_status(), textures_per_texunits, and validated.
Referenced by execute_with().
vertex_attributes()
std::map< size_t, resources::vertex_input_t > openage::renderer::opengl::GlShaderProgram::vertex_attributes () const override virtual
Returns a list of active vertex attributes in the shader program. Active attributes are those which have an effect on the shader output, meaning they are included in the output calculation and are not unused. Inactive attributes may or may not be present in the list - in particular, in the OpenGL implementation they will most likely be missing. The returned value is a map from the attribute location to its type. Locations need not be consecutive.
Implements openage::renderer::ShaderProgram.
Definition at line 367 of file shader_program.cpp.
{
     std::map<size_t, resources::vertex_input_t> attrib_map;
     for (auto const& attr : this->attribs) {
         attrib_map[attr.second.location] = GL_VERT_IN_TYPE.get(attr.second.type);
     }
     return attrib_map;
 }
References openage::renderer::opengl::GL_VERT_IN_TYPE.
Member Data Documentation
attribs
std::unordered_map<std::string, GlVertexAttrib> openage::renderer::opengl::GlShaderProgram::attribs private
Maps per-vertex attribute names to their descriptions.
Definition at line 110 of file shader_program.h.
textures_per_texunits
std::unordered_map<GLuint, GLuint> openage::renderer::opengl::GlShaderProgram::textures_per_texunits private
Maps texture units to the texture handles that are currently bound to them.
Definition at line 115 of file shader_program.h.
Referenced by execute_with(), and use().
texunits_per_unifs
std::unordered_map<std::string, GLuint> openage::renderer::opengl::GlShaderProgram::texunits_per_unifs private
Maps sampler uniform names to their assigned texture units.
Definition at line 113 of file shader_program.h.
Referenced by execute_with().
uniform_blocks
std::unordered_map<std::string, GlUniformBlock> openage::renderer::opengl::GlShaderProgram::uniform_blocks private
Maps uniform block names to their descriptions.
Definition at line 107 of file shader_program.h.
uniforms
std::unordered_map<std::string, GlUniform> openage::renderer::opengl::GlShaderProgram::uniforms private
Maps uniform names to their descriptions. Contains only uniforms in the default block, i.e. not within named blocks.
Definition at line 104 of file shader_program.h.
validated
bool openage::renderer::opengl::GlShaderProgram::validated private
Whether this program has been validated.
Definition at line 118 of file shader_program.h.
Referenced by use().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/opengl/shader_program.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/opengl/shader_program.cpp