openage: openage::gui::ActionModeLink Class Reference
openage::gui::ActionModeLink Class Reference
#include <game_control_link.h>
Signals
void ability_changed ()
void action_triggered (const std::string &ability)
void buttons_type_changed (const ActionButtonsType buttons_type)
void population_changed ()
Public Member Functions
ActionModeLink (QObject *parent=nullptr)
virtual ~ActionModeLink ()
QString get_ability () const
QString get_population () const
bool get_population_warn () const
Q_INVOKABLE void act (const QString &action)
Public Member Functions inherited from qtsdl::Inherits< OutputModeLink, ActionModeLink >
Inherits (QObject *parent=nullptr)
virtual ~Inherits ()
Public Member Functions inherited from qtsdl::Shadow< OutputModeLink >
Shadow (QObject *parent=nullptr)
void get (NullClass)
void i (NullClass)
void s (NullClass)
void sf (NullClass)
Public Member Functions inherited from qtsdl::GuiItemCoreInstantiator< ActionModeLink >
GuiItemCoreInstantiator (GuiItemBase *item_base)
Public Member Functions inherited from qtsdl::GuiItemMethods< ActionModeLink >
virtual ~GuiItemMethods ()
U * get () const
U * get ()
void i (F f, Args &&... args)
Properties
QString ability
QString population
bool population_warn
Private Slots
void on_ability_changed (const std::string &ability)
void on_buttons_type_changed (const ActionButtonsType buttons_type)
void on_population_changed (int demand, int capacity, bool warn)
Private Member Functions
virtual void on_core_adopted () override
Additional Inherited Members
Protected Member Functions inherited from qtsdl::GuiItemMethods< ActionModeLink >
void s (F f, P &p, A &&arg)
void sf (F f, P &p, A &&arg)
Detailed Description
Definition at line 115 of file game_control_link.h.
Constructor & Destructor Documentation
ActionModeLink()
openage::gui::ActionModeLink::ActionModeLink (QObject * parent = nullptr)
Definition at line 101 of file game_control_link.cpp.
     :
     Inherits{parent} {
     Q_UNUSED(registration_action);
 }
~ActionModeLink()
openage::gui::ActionModeLink::~ActionModeLink () virtual
Definition at line 107 of file game_control_link.cpp.
{
 }
Member Function Documentation
ability_changed
void openage::gui::ActionModeLink::ability_changed () signal
Referenced by on_ability_changed().
act()
void openage::gui::ActionModeLink::act (const QString & action)
Definition at line 122 of file game_control_link.cpp.
{
     emit this->action_triggered(action.toStdString());
 }
References action_triggered().
action_triggered
void openage::gui::ActionModeLink::action_triggered (const std::string & ability) signal
Referenced by act(), and on_core_adopted().
buttons_type_changed
void openage::gui::ActionModeLink::buttons_type_changed (const ActionButtonsType buttons_type) signal
Referenced by on_buttons_type_changed(), and openage::gui::ActionsListModel::set_action_mode().
get_ability()
QString openage::gui::ActionModeLink::get_ability () const
Definition at line 110 of file game_control_link.cpp.
{
     return this->ability;
 }
References ability.
get_population()
QString openage::gui::ActionModeLink::get_population () const
Definition at line 114 of file game_control_link.cpp.
{
     return this->population;
 }
References population.
get_population_warn()
bool openage::gui::ActionModeLink::get_population_warn () const
Definition at line 118 of file game_control_link.cpp.
{
     return this->population_warn;
 }
References population_warn.
on_ability_changed
void openage::gui::ActionModeLink::on_ability_changed (const std::string & ability) private slot
Definition at line 126 of file game_control_link.cpp.
{
     this->ability = QString::fromStdString(ability);
     emit this->ability_changed();
 }
References ability, and ability_changed().
Referenced by on_core_adopted().
on_buttons_type_changed
void openage::gui::ActionModeLink::on_buttons_type_changed (const ActionButtonsType buttons_type) private slot
Definition at line 131 of file game_control_link.cpp.
{
     emit this->buttons_type_changed(buttons_type);
 }
References buttons_type_changed().
Referenced by on_core_adopted().
on_core_adopted()
void openage::gui::ActionModeLink::on_core_adopted () override private virtual
Definition at line 141 of file game_control_link.cpp.
{
     this->Inherits::on_core_adopted();
     QObject::connect(&unwrap(this)->gui_signals,
                      &ActionModeSignals::ability_changed,
                      this,
                      &ActionModeLink::on_ability_changed);
     QObject::connect(&unwrap(this)->gui_signals,
                      &ActionModeSignals::population_changed,
                      this,
                      &ActionModeLink::on_population_changed);
     QObject::connect(&unwrap(this)->gui_signals,
                      &ActionModeSignals::buttons_type_changed,
                      this,
                      &ActionModeLink::on_buttons_type_changed);
     QObject::connect(this,
                      &ActionModeLink::action_triggered,
                      &unwrap(this)->gui_signals,
                      &ActionModeSignals::on_action);
 }
References openage::ActionModeSignals::ability_changed(), action_triggered(), openage::ActionModeSignals::buttons_type_changed(), on_ability_changed(), openage::ActionModeSignals::on_action(), on_buttons_type_changed(), on_population_changed(), openage::ActionModeSignals::population_changed(), and qtsdl::unwrap().
on_population_changed
void openage::gui::ActionModeLink::on_population_changed (int demand, int capacity, bool warn) private slot
Definition at line 135 of file game_control_link.cpp.
{
     this->population = QString::number(demand) + "/" + QString::number(capacity);
     this->population_warn = warn;
     emit this->population_changed();
 }
References population, population_changed(), population_warn, and openage::log::warn().
Referenced by on_core_adopted().
population_changed
void openage::gui::ActionModeLink::population_changed () signal
Referenced by on_population_changed().
Property Documentation
ability
QString openage::gui::ActionModeLink::ability read
Definition at line 118 of file game_control_link.h.
Referenced by get_ability(), and on_ability_changed().
population
QString openage::gui::ActionModeLink::population read
Definition at line 119 of file game_control_link.h.
Referenced by get_population(), and on_population_changed().
population_warn
bool openage::gui::ActionModeLink::population_warn read
Definition at line 120 of file game_control_link.h.
Referenced by get_population_warn(), and on_population_changed().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/game_control_link.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/game_control_link.cpp