openage: openage::AttackAction Class Reference
openage::AttackAction Class Reference
#include <action.h>
Public Member Functions
AttackAction (Unit *e, UnitReference tar)
virtual ~AttackAction ()
void update_in_range (unsigned int time, Unit *target_unit) override
void on_completion_in_range (int) override
bool completed_in_range (Unit *) const override
std::string name () const override
Public Member Functions inherited from openage::TargetAction
TargetAction (Unit *e, graphic_type gt, UnitReference r, coord::phys_t action_rad)
TargetAction (Unit *e, graphic_type gt, UnitReference r)
virtual ~TargetAction ()
void update (unsigned int time) override
void on_completion () override
bool completed () const override
bool allow_interupt () const override
bool allow_control () const override
coord::phys_t distance_to_target ()
Unit * update_distance ()
UnitReference get_target () const
int get_target_type_id () const
void set_target (UnitReference new_target)
Public Member Functions inherited from openage::UnitAction
UnitAction (Unit *u, graphic_type initial_gt)
virtual ~UnitAction ()
graphic_type type () const
float current_frame () const
virtual const graphic_set & current_graphics () const
void draw_debug (const Engine &engine)
void face_towards (const coord::phys3 pos)
bool damage_unit (Unit &target)
void move_to (Unit &target, bool use_range=true)
Private Member Functions
void attack (Unit &target)
void fire_projectile (const Attribute< attr_type::attack > &att, const coord::phys3 &target)
Private Attributes
IntervalTimer timer
Additional Inherited Members
Static Public Member Functions inherited from openage::UnitAction
static coord::phys_t adjacent_range (Unit *u)
static coord::phys_t get_attack_range (Unit *u)
static coord::phys_t get_heal_range (Unit *u)
Static Public Attributes inherited from openage::UnitAction
static bool show_debug = false
Protected Attributes inherited from openage::UnitAction
Unit * entity
graphic_type graphic
float frame
float frame_rate
std::function< void(const Engine &)> debug_draw_action
Detailed Description
attacks another unit
Definition at line 562 of file action.h.
Constructor & Destructor Documentation
AttackAction()
openage::AttackAction::AttackAction (Unit * e, UnitReference tar)
Definition at line 1181 of file action.cpp.
     :
     TargetAction{e, graphic_type::attack, tar, get_attack_range(e)},
     timer{500} { // \todo get fire rate from unit type
     // check if attacking a non resource unit
     if (this->entity->has_attribute(attr_type::worker) &&
         (!tar.get()->has_attribute(attr_type::resource) || tar.get()->has_attribute(attr_type::worker))) {
         // switch to default villager graphics
         if (this->entity->has_attribute(attr_type::multitype)) {
             this->entity->get_attribute<attr_type::multitype>().switchType(gamedata::unit_classes::CIVILIAN, this->entity);
         }
     }
     // \todo rivit logic, a start inside the animation should be provided
     this->timer.skip_to_trigger();
 }
References openage::attack, and openage::UnitAction::get_attack_range().
~AttackAction()
openage::AttackAction::~AttackAction () virtual
Definition at line 1199 of file action.cpp.
 {}
Member Function Documentation
attack()
void openage::AttackAction::attack (Unit & target) private
use attack action
Definition at line 1215 of file action.cpp.
{
     auto &attack = this->entity->get_attribute<attr_type::attack>();
     if (attack.ptype) {
         // add projectile to the game
         this->fire_projectile(attack, target.location->pos.draw);
     }
     else {
         this->damage_unit(target);
     }
 }
References openage::attack, openage::UnitAction::damage_unit(), openage::UnitAction::entity, fire_projectile(), openage::Unit::get_attribute(), and openage::Unit::location.
Referenced by update_in_range().
completed_in_range()
bool openage::AttackAction::completed_in_range (Unit * target_ptr) const override virtual
Implements openage::TargetAction.
Definition at line 1210 of file action.cpp.
{
     auto &dm = target_ptr->get_attribute<attr_type::damaged>();
     return dm.hp < 1; // is unit still alive?
 }
References openage::damaged, and openage::Unit::get_attribute().
fire_projectile()
void openage::AttackAction::fire_projectile (const Attribute< attr_type::attack > & att, const coord::phys3 & target) private
add a projectile game object which moves towards the target
Definition at line 1227 of file action.cpp.
{
     // container terrain and initial position
     UnitContainer *container = this->entity->get_container();
     coord::phys3 current_pos = this->entity->location->pos.draw;
     current_pos.up = att.init_height;
     // create using the producer
     auto &player = this->entity->get_attribute<attr_type::owner>().player;
     auto projectile_ref = container->new_unit(*att.ptype, player, current_pos);
     // send towards target using a projectile ability (creates projectile motion action)
     if (projectile_ref.is_valid()) {
         auto projectile = projectile_ref.get();
         auto &projectile_attr = projectile->get_attribute<attr_type::projectile>();
         projectile_attr.launcher = this->entity->get_ref();
         projectile_attr.launched = true;
         projectile->push_action(std::make_unique<ProjectileAction>(projectile, target), true);
     }
     else {
         this->entity->log(MSG(dbg) << "projectile launch failed");
     }
 }
References openage::curve::tests::container(), openage::log::dbg(), openage::UnitAction::entity, openage::Unit::get_attribute(), openage::Unit::get_container(), openage::Unit::get_ref(), openage::Attribute< attr_type::attack >::init_height, openage::Unit::location, openage::log::LogSource::log(), MSG, openage::owner, openage::projectile, openage::Attribute< attr_type::attack >::ptype, and openage::TargetAction::target.
Referenced by attack().
name()
std::string openage::AttackAction::name () const inline override virtual
debug string to identify action types
Implements openage::TargetAction.
Definition at line 570 of file action.h.
 { return "attack"; }
Referenced by openage.util.fslike.path.Path::stem(), openage.util.fslike.path.Path::suffix(), and openage.util.fslike.path.Path::suffixes().
on_completion_in_range()
void openage::AttackAction::on_completion_in_range (int) inline override virtual
Implements openage::TargetAction.
Definition at line 568 of file action.h.
 {}
update_in_range()
void openage::AttackAction::update_in_range (unsigned int , Unit *) override virtual
Control units action when in range of the target
Implements openage::TargetAction.
Definition at line 1201 of file action.cpp.
{
     if (this->timer.update(time)) {
         this->attack(*target_ptr);
     }
     // inc frame
     this->frame += time * this->current_graphics().at(graphic)->frame_count * 1.0f / this->timer.get_interval();
 }
References attack(), openage::UnitAction::current_graphics(), openage::UnitAction::frame, openage::IntervalTimer::get_interval(), openage::UnitAction::graphic, timer, and openage::IntervalTimer::update().
Member Data Documentation
timer
IntervalTimer openage::AttackAction::timer private
Definition at line 574 of file action.h.
Referenced by update_in_range().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/action.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/action.cpp