openage: openage::gui::GameMainLink Class Reference
openage::gui::GameMainLink Class Reference
#include <game_main_link.h>
Public Types
enum State { State::Null, State::Running }
Signals
void state_changed ()
Public Member Functions
GameMainLink (QObject *parent=nullptr)
virtual ~GameMainLink ()
State get_state () const
EngineLink * get_engine () const
void set_engine (EngineLink *engine)
Q_INVOKABLE void clear ()
Public Member Functions inherited from qtsdl::GuiItemQObject
GuiItemQObject (QObject *parent=nullptr)
Public Member Functions inherited from qtsdl::GuiItemBase
virtual ~GuiItemBase ()
Public Member Functions inherited from qtsdl::DeferredInitialConstantPropertyValues
DeferredInitialConstantPropertyValues ()
virtual ~DeferredInitialConstantPropertyValues ()
void apply_static_properties ()
void clear_static_properties ()
bool is_init_over () const
Public Member Functions inherited from qtsdl::GuiItemLink
virtual ~GuiItemLink ()
Public Member Functions inherited from qtsdl::GuiItem< GameMainLink >
GuiItem (GuiItemBase *item_base)
Public Member Functions inherited from qtsdl::GuiItemCoreInstantiator< GameMainLink >
GuiItemCoreInstantiator (GuiItemBase *item_base)
Public Member Functions inherited from qtsdl::GuiItemMethods< GameMainLink >
virtual ~GuiItemMethods ()
U * get () const
U * get ()
void i (F f, Args &&... args)
Properties
State state
openage::gui::EngineLink engine
Private Slots
void on_game_running (bool running)
Private Member Functions
virtual void classBegin () override
virtual void on_core_adopted () override
virtual void componentComplete () override
Private Attributes
bool active
EngineLink * engine
Additional Inherited Members
Protected Member Functions inherited from qtsdl::GuiItemMethods< GameMainLink >
void s (F f, P &p, A &&arg)
void sf (F f, P &p, A &&arg)
Protected Attributes inherited from qtsdl::GuiItemBase
GameLogicCaller game_logic_caller
std::function< std::unique_ptr< PersistentCoreHolderBase >)> instantiate_core_func
std::function< void(PersistentCoreHolderBase *, const QString &)> do_adopt_core_func
std::function< void()> on_core_adopted_func
Protected Attributes inherited from qtsdl::DeferredInitialConstantPropertyValues
bool init_over
std::vector< std::function< void()> > static_properties_assignments
Detailed Description
Definition at line 35 of file game_main_link.h.
Member Enumeration Documentation
State
enum openage::gui::GameMainLink::State strong
Enumerator
Null
Running
Definition at line 47 of file game_main_link.h.
                      {
         Null, Running
     };
Constructor & Destructor Documentation
GameMainLink()
openage::gui::GameMainLink::GameMainLink (QObject * parent = nullptr) explicit
Definition at line 17 of file game_main_link.cpp.
     :
     GuiItemQObject{parent},
     QQmlParserStatus{},
     GuiItem{this},
     state{},
     active{},
     engine{} {
     Q_UNUSED(registration);
 }
~GameMainLink()
openage::gui::GameMainLink::~GameMainLink () virtual
Definition at line 28 of file game_main_link.cpp.
{
 }
Member Function Documentation
classBegin()
void openage::gui::GameMainLink::classBegin () override private virtual
Definition at line 31 of file game_main_link.cpp.
{
 }
clear()
void openage::gui::GameMainLink::clear ()
Definition at line 60 of file game_main_link.cpp.
{
     static auto f = [] (GameMainHandle *_this) {
         _this->clear();
     };
     this->i(f);
 }
References qtsdl::GuiItemMethods< GameMainLink >::i().
componentComplete()
void openage::gui::GameMainLink::componentComplete () override private virtual
Definition at line 38 of file game_main_link.cpp.
{
     static auto f = [] (GameMainHandle *_this) {
         _this->announce_running();
     };
     this->i(f);
 }
References qtsdl::GuiItemMethods< GameMainLink >::i().
get_engine()
EngineLink * openage::gui::GameMainLink::get_engine () const
Definition at line 49 of file game_main_link.cpp.
{
     return this->engine;
 }
References engine.
get_state()
GameMainLink::State openage::gui::GameMainLink::get_state () const
Definition at line 45 of file game_main_link.cpp.
{
     return this->state;
 }
References state.
on_core_adopted()
void openage::gui::GameMainLink::on_core_adopted () override private virtual
Reimplemented from qtsdl::GuiItemBase.
Definition at line 34 of file game_main_link.cpp.
{
     QObject::connect(&unwrap(this)->gui_signals, &GameMainSignals::game_running, this, &GameMainLink::on_game_running);
 }
References openage::GameMainSignals::game_running(), on_game_running(), and qtsdl::unwrap().
on_game_running
void openage::gui::GameMainLink::on_game_running (bool running) private slot
Definition at line 67 of file game_main_link.cpp.
{
     auto state = running ? State::Running : State::Null;
     if (this->state != state) {
         this->state = state;
         emit this->state_changed();
     }
 }
References Null, Running, state, and state_changed().
Referenced by on_core_adopted().
set_engine()
void openage::gui::GameMainLink::set_engine (EngineLink * engine)
Definition at line 53 of file game_main_link.cpp.
{
     static auto f = [] (GameMainHandle *_this, Engine *engine) {
         _this->set_engine(engine);
     };
     this->s(f, this->engine, engine);
 }
References engine, qtsdl::GuiItemMethods< GameMainLink >::s(), and openage::GameMainHandle::set_engine().
state_changed
void openage::gui::GameMainLink::state_changed () signal
Referenced by on_game_running().
Member Data Documentation
active
bool openage::gui::GameMainLink::active private
Definition at line 70 of file game_main_link.h.
engine
EngineLink* openage::gui::GameMainLink::engine private
Definition at line 71 of file game_main_link.h.
Property Documentation
engine
openage::gui::EngineLink openage::gui::GameMainLink::engine read write
Definition at line 41 of file game_main_link.h.
Referenced by get_engine(), and set_engine().
state
State openage::gui::GameMainLink::state read
Definition at line 40 of file game_main_link.h.
Referenced by get_state(), and on_game_running().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/game_main_link.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/gui/game_main_link.cpp