openage: openage::console::Buf Class Reference
openage::console::Buf Class Reference
#include <buf.h>
Public Member Functions
Buf (coord::term dims, coord::term_t scrollback_lines, coord::term_t min_width, buf_char default_char_fmt={0x20, 254, 0, 0})
~Buf ()
Buf & operator= (const Buf &)=delete
Buf (const Buf &)=delete
void reset ()
resets the buffer to its constructor defaults
void write (const char *c, ssize_t len=-1)
write a byte string to the buffer
void write (char c)
write a single byte to the buffer.
void pop_last_char ()
Pop the last char of the current line.
void resize (coord::term new_dims)
resizes the screen buffer
void scroll (coord::term_t lines)
scrolls up or down by the given number of lines
void process_codepoint (int cp)
processes one unicode codepoint internally called by write(char) after feeding the char into streamdecoder
void print_codepoint (int cp)
prints one unicode codepoint interally called by process_codepoint(int cp) after sorting out escape sequences, and by some escape sequences such as CSI @
void escape_sequence_aborted ()
aborts the current escape sequence (e.g.
void escape_sequence_processed ()
called when a escape sequence has been successfully processed, clears the sequence.
void process_csi_escape_sequence ()
processes the CSI escape sequence currently stored in escape_sequence.
void process_escaped_cp (int cp)
processes a single-codepoint escape sequence.
void process_text_escape_sequence ()
processes a text escape sequence that is one of OSC, DCS, APC or PM
void process_sgr_code (const std::vector< int > &params)
sets graphics rendition parameters; called by process_escape_sequence
void advance (unsigned linecount=1)
advances the buffer by the specified number of lines.
void clear (coord::term start, coord::term end, bool clear_end=false)
clears the screen character and line buffers.
void chrdata_clear (buf_char *start, buf_char *end)
clears a range of the data buffer.
void linedata_clear (buf_line *start, buf_line *end)
clears a range of the linedata buffer.
buf_char * chrdataptr (coord::term pos)
returns a valid pointer to the character info for the character designated by pos
buf_line * linedataptr (coord::term_t lineno)
returns a valid pointer to the line info for the line designated by lineno
const coord::term & get_dims () const
Return the dimensions of the visible console area.
Public Attributes
util::utf8_decoder streamdecoder
utf-8 state-machine that reads input bytes and outputs unicode codepoints
buf_char * chrdata
the complete (2-dimensional) terminal output buffer content
size_t chrdata_size
stores the (array) size of data, for performance and convenience reasons.
buf_char * chrdata_end
stores the end of the region allocated for data, for performance and convenience reasons.
buf_char * screen_chrdata
points to the first character that belongs to the screen buffer, inside the data buffer.
buf_line * linedata
similar to how data holds information about all characters, linedata holds information about all lines.
size_t linedata_size
see chrdata_size
buf_line * linedata_end
see chrdata_end
buf_line * screen_linedata
as an analog to screen_chrdata, this points to the entry in linedata that holds metadata about the top line of the screen buffer.
coord::term_t min_width
minimum screen buffer width
coord::term dims
screen buffer dimensions (in characters)
coord::term_t scrollback_lines
scrollback buffer height; scrollback buffer width is identical to screen buffer width.
coord::term cursorpos
cursor position
coord::term saved_cursorpos
saved cursor position
bool cursor_visible
true if the cursor is visible
bool cursor_special_lastcol
true if cursor is in the last column while whole line is filled this is very special.
bool escaped
true if we are currently reading an escape sequence
std::vector< int > escape_sequence
current escape sequence
bool bell
true if an bell ('') has been received, but not cleared
std::vector< int > title
window title
buf_char current_char_fmt
surrently selected formatting (colors, flags).
const buf_char default_char_fmt
the default buf char, which will be used for filling new lines, or determining whether a line is empty.
coord::term_t scrollback_possible
how far it's currently possible to scroll back.
coord::term_t scrollback_pos
how many lines the buffer is currently scrolled back.
Friends
class NewBuf
Detailed Description
Definition at line 121 of file buf.h.
Constructor & Destructor Documentation
Buf() [1/2]
openage::console::Buf::Buf (coord::term dims, coord::term_t scrollback_lines, coord::term_t min_width, buf_char default_char_fmt = {0x20, 254, 0, 0})
Definition at line 14 of file buf.cpp.
     :
     dims{dims},
     cursorpos{0, 0},
     saved_cursorpos{0, 0},
     default_char_fmt{default_char_fmt}
 {
     //init all member variables
     this->min_width = min_width;
     if (this->dims.x < this->min_width) {
         this->dims.x = this->min_width;
     }
     if (this->dims.y < 1) {
         this->dims.y = 1;
     }
     this->scrollback_lines = scrollback_lines;
     this->linedata_size = this->dims.y + this->scrollback_lines;
     this->linedata = new buf_line[this->linedata_size];
     this->linedata_end = this->linedata + this->linedata_size;
     this->chrdata_size = this->dims.x * linedata_size;
     this->chrdata = new buf_char[this->chrdata_size];
     this->chrdata_end = this->chrdata + this->chrdata_size;
     this->screen_chrdata = this->chrdata;
     this->screen_linedata = this->linedata;
     this->reset();
 }
References dims.
~Buf()
openage::console::Buf::~Buf ()
Definition at line 46 of file buf.cpp.
           {
     //free dynamically allocated members
     delete[] this->linedata;
     delete[] this->chrdata;
 }
References chrdata, and linedata.
Buf() [2/2]
openage::console::Buf::Buf (const Buf &) delete
Member Function Documentation
advance()
void openage::console::Buf::advance (unsigned linecount = 1)
advances the buffer by the specified number of lines.
the top lines are moved to the scrollback buffer. the top lines of the scrollback buffer are discarded. the bottom lines of the buffer are empty after this. the cursor position is not changed by this.
linecount: the number of lines to advance the buffer; defaults to one. may be > buffer height.
Definition at line 341 of file buf.cpp.
{
     // sanitize linecount
     if (linecount == 0) {
         return;
     }
     if ((term_t) linecount > this->dims.y + this->scrollback_lines) {
         linecount = this->dims.y + this->scrollback_lines;
     }
     // update scrollback_possible
     this->scrollback_possible += linecount;
     if (this->scrollback_possible > (term_t) this->scrollback_lines) {
         this->scrollback_possible = this->scrollback_lines;
     }
     // update scrollback position, to remain at the currently scrolled-to
     // position
     if (this->scrollback_pos > 0) {
         this->scrollback_pos += linecount;
         if (this->scrollback_pos > this->scrollback_possible) {
             //seems like we're already on top of the scrollback buffer
             this->scrollback_pos = this->scrollback_possible;
         }
     }
     // clear the new lines. that's scrollback_buffer[0:linecount]
     this->clear({0, (term_t) -this->scrollback_lines}, {0, (term_t) ((term_t) linecount - (term_t) this->scrollback_lines)});
     // move the screen buffer by updating the screen_chrdata pointer
     this->screen_chrdata += linecount * this->dims.x;
     if (this->screen_chrdata >= this->chrdata_end) {
         this->screen_chrdata -= this->chrdata_size;
     }
     // also update the screen_linedata pointer
     this->screen_linedata += linecount;
     if (this->screen_linedata >= this->linedata_end) {
         this->screen_linedata -= this->linedata_size;
     }
 }
References chrdata_end, chrdata_size, clear(), dims, linedata_end, linedata_size, screen_chrdata, screen_linedata, scrollback_lines, scrollback_pos, and scrollback_possible.
Referenced by print_codepoint().
chrdata_clear()
void openage::console::Buf::chrdata_clear (buf_char * start, buf_char * end)
clears a range of the data buffer.
end is the first character that is not cleared. end and start both must be valid pointers within data.
Definition at line 1111 of file buf.cpp.
{
     if (start < end) {
         for (; start < end; start++) {
             *start = this->current_char_fmt;
         }
     } else {
         for (buf_char *c = start; c < this->chrdata_end; c++) {
             *c = this->current_char_fmt;
         }
         for (buf_char *c = this->chrdata; c < end; c++) {
             *c = this->current_char_fmt;
         }
     }
 }
References chrdata, chrdata_end, and current_char_fmt.
Referenced by clear().
chrdataptr()
buf_char * openage::console::Buf::chrdataptr (coord::term pos)
returns a valid pointer to the character info for the character designated by pos
pos screen buffer coordinates negative values of y indicate scrollback buffer -scrollback_lines <= pos.y <= dims.y 0 <= pos.x < dims.x if y == dims.y, the return ptr is not guaranteed to be valid.
Definition at line 1141 of file buf.cpp.
{
     buf_char *result = this->screen_chrdata + pos.x + pos.y * this->dims.x;
     if (result < this->chrdata) {
         result += this->chrdata_size;
     } else if (result >= this->chrdata_end) {
         result -= this->chrdata_size;
     }
     return result;
 }
References chrdata, chrdata_end, chrdata_size, dims, openage.testing.testing::result(), and screen_chrdata.
Referenced by clear(), pop_last_char(), print_codepoint(), resize(), openage::console::draw::to_opengl(), and openage::console::draw::to_terminal().
clear()
void openage::console::Buf::clear (coord::term start, coord::term end, bool clear_end = false)
clears the screen character and line buffers.
lines are cleared iff all of their characters are cleared.
if start >= end, nothing happens.
inputs are not sanitized.
start screen buffer coordinates of first character to be deleted negative values of y indicate scrollback buffer -scrollback_lines <= y < dims.y 0 <= x < dims.x end screen buffer coordinates of first character not to be deleted negative values of y indicate scrollback buffer -scrollback_lines <= y < dims.y 0 <= x < dims.x {x, y} = {0, dims.y} is allowed. clear_end if true, end is incremented by 1. this affects all constraints.
Definition at line 1078 of file buf.cpp.
{
     // apply clear_end
     if (clear_end) {
         end.x++;
         if (end.x > this->dims.x) {
             end.x = 0;
             end.y++;
         }
     }
     if (start.y > end.y or (start.y == end.y and start.x >= end.x)) {
         return;
     }
     // clear char info
     chrdata_clear(chrdataptr(start), chrdataptr(end));
     // calculate lines to clear
     // a line is cleared iff all of its characters are cleared
     term_t line_start = start.y;
     if (start.x > 0) {
         line_start++;
     }
     term_t line_end = end.y;
     if (line_start >= line_end) {
         return;
     }
     // clear line info
     linedata_clear(linedataptr(line_start), linedataptr(line_end));
 }
References chrdata_clear(), chrdataptr(), linedata_clear(), and linedataptr().
Referenced by advance(), process_csi_escape_sequence(), and reset().
escape_sequence_aborted()
void openage::console::Buf::escape_sequence_aborted ()
aborts the current escape sequence (e.g.
because it contained an illegal character, or is not implemented)
Definition at line 609 of file buf.cpp.
{
     this->escaped = false;
     print_cps(stderr, &this->escape_sequence);
     fprintf(stderr, "\n");
     this->escape_sequence.clear();
 }
References escape_sequence, escaped, and openage::console::print_cps().
Referenced by process_codepoint(), process_csi_escape_sequence(), process_escaped_cp(), and process_text_escape_sequence().
escape_sequence_processed()
void openage::console::Buf::escape_sequence_processed ()
called when a escape sequence has been successfully processed, clears the sequence.
either this or abort_escape_sequence is called for each escape sequence.
Definition at line 616 of file buf.cpp.
{
     this->escaped = false;
     this->escape_sequence.clear();
 }
References escape_sequence, and escaped.
Referenced by process_csi_escape_sequence(), and process_text_escape_sequence().
get_dims()
const coord::term & openage::console::Buf::get_dims () const
Return the dimensions of the visible console area.
Definition at line 1162 of file buf.cpp.
{
     return this->dims;
 }
References dims.
Referenced by openage::console::Console::on_resize().
linedata_clear()
void openage::console::Buf::linedata_clear (buf_line * start, buf_line * end)
clears a range of the linedata buffer.
end is the first line that is not cleared. end and start both must be valid pointers within data.
Definition at line 1126 of file buf.cpp.
{
     if (start < end) {
         for (; start < end; start++) {
             *start = BUF_LINE_DEFAULT;
         }
     } else {
         for (buf_line *l = start; l < this->linedata_end; l++) {
             *l = BUF_LINE_DEFAULT;
         }
         for (buf_line *l = this->linedata; l < end; l++) {
             *l = BUF_LINE_DEFAULT;
         }
     }
 }
References openage::console::BUF_LINE_DEFAULT, linedata, and linedata_end.
Referenced by clear().
linedataptr()
buf_line * openage::console::Buf::linedataptr (coord::term_t lineno)
returns a valid pointer to the line info for the line designated by lineno
lineno number of line in screen buffer negative numbers indicate scrollback buffer -scrollback_lines <= lineno <= dims.y if lineno == dims.y, the return ptr is not guaranteed to be valid.
Definition at line 1151 of file buf.cpp.
{
     buf_line *result = this->screen_linedata + lineno;
     if (result < this->linedata) {
         result += this->linedata_size;
     }
     if (result > this->linedata_end) {
         result -= this->linedata_size;
     }
     return result;
 }
References linedata, linedata_end, linedata_size, openage.testing.testing::result(), and screen_linedata.
Referenced by clear(), pop_last_char(), print_codepoint(), and resize().
operator=()
Buf& openage::console::Buf::operator= (const Buf &) delete
pop_last_char()
void openage::console::Buf::pop_last_char ()
Pop the last char of the current line.
Will correctly handle UTF-8 chars and wrapped lines.
Definition at line 393 of file buf.cpp.
{
     if (this->cursorpos.x > 0) {
         if (this->cursor_special_lastcol) {
             this->cursor_special_lastcol = false;
         }
         else {
             this->cursorpos.x -= 1;
         }
         buf_char *ptr = this->chrdataptr(this->cursorpos);
         *ptr = this->current_char_fmt;
         ptr->cp = ' ';
         if (this->cursorpos.x == 0 && this->linedataptr(this->cursorpos.y - 1)->type == LINE_WRAPPED) {
             this->linedataptr(this->cursorpos.y)->type = LINE_EMPTY;
             this->cursorpos.y--;
             this->linedataptr(this->cursorpos.y)->type = LINE_REGULAR;
             this->cursorpos.x = this->dims.x - 1;
             this->cursor_special_lastcol = true;
         }
     }
 }
References chrdataptr(), openage::console::buf_char::cp, current_char_fmt, cursor_special_lastcol, cursorpos, dims, openage::console::LINE_EMPTY, openage::console::LINE_REGULAR, openage::console::LINE_WRAPPED, linedataptr(), and openage::console::buf_line::type.
Referenced by openage::console::Console::register_to_engine().
print_codepoint()
void openage::console::Buf::print_codepoint (int cp)
prints one unicode codepoint interally called by process_codepoint(int cp) after sorting out escape sequences, and by some escape sequences such as CSI @
Definition at line 479 of file buf.cpp.
{
     switch (cp) {
     // control characters
     case 0x00: // NUL: ignore
     case 0x01: // SOH: ignore
     case 0x02: // STX: ignore
     case 0x03: // ETX: ignore
     case 0x04: // EOT: ignore
     case 0x05: // ENQ: ignore (empty response)
     case 0x06: // ACK: ignore
         break;
     case 0x07: // BEL: set bell flag
         this->bell = true;
         break;
     case 0x08: // BS: backspace
         // move cursor 1 left.
         // if cursor pos is 0, move to end of previous line
         // if already at (0,0), move to (0,0)
         if (this->cursor_special_lastcol && (this->cursorpos.x == this->dims.x - 1)) {
             // if we are in the special last-column state, only unset that flag,
             // but don't move the cursor.
             this->cursor_special_lastcol = false;
         } else {
             this->cursorpos.x -= 1;
             if (this->cursorpos.x < 0) {
                 this->cursorpos.x += this->dims.x;
                 this->cursorpos.y -= 1;
                 if (this->cursorpos.y < 0) {
                     this->cursorpos = {0, 0};
                 }
             }
         }
         break;
     case 0x09: // HT: horizontal tab
         // move cursor to next multiple of 8
         // at least move by 1, at most by 8
         // if next multiple of 8 is greater than terminal width,
         // move to end of this line
         // never move to next line
         this->cursorpos.x = ((this->cursorpos.x + 8) / 8) * 8;
         if (this->cursorpos.x >= this->dims.x) {
             this->cursorpos.x = this->dims.x - 1;
         }
         break;
     case 0x0a: // LF: linefeed
     case 0x0b: // VT: vertical tab
     case 0x0c: // FF: form feed
         //all these do the same: move to beginning of next line
         this->cursor_special_lastcol = false;
         this->cursorpos.x = 0;
         if (this->cursorpos.y == this->dims.y - 1) {
             this->advance(1);
         } else {
             this->cursorpos.y += 1;
         }
         break;
     case 0x0d: // CR: carriage return
         this->cursorpos.x = 0;
         this->cursor_special_lastcol = false;
         break;
     case 0x0e: // SO: ignore
     case 0x0f: // SI: ignore
     case 0x10: // DLE: ignore
     case 0x11: // DC1: ignore
     case 0x12: // DC2: ignore
     case 0x13: // DC3: ignore
     case 0x14: // DC4: ignore
     case 0x15: // NAK: ignore
     case 0x16: // SYN: ignore
     case 0x17: // ETB: ignore
     case 0x18: // CAN: ignore
     case 0x19: // EM: ignore
     case 0x1a: // SUB: ignore
         break;
     case 0x1b: // ESC: escape sequence start
         this->escaped = true;
         break;
     case 0x1c: // FS: ignore
     case 0x1d: // GS: ignore
     case 0x1e: // RS: ignore
     case 0x1f: // US: ignore
     case 0x7f: // DEL: ignore
         break;
     default:   // regular, printable character
         if (this->cursor_special_lastcol && (this->cursorpos.x == this->dims.x - 1)) {
             this->cursor_special_lastcol = false;
             // store the fact that this line was auto-wrapped
             // and will continue in the next line
             this->linedataptr(this->cursorpos.y)->type = LINE_WRAPPED;
             this->cursorpos.x = 0;
             if (this->cursorpos.y == this->dims.y - 1) {
                 this->advance(1);
             } else {
                 this->cursorpos.y += 1;
             }
         }
         // set char at current cursor pos
         buf_char *ptr = this->chrdataptr(this->cursorpos);
         *ptr = this->current_char_fmt;
         ptr->cp = cp;
         buf_line *lineptr = this->linedataptr(this->cursorpos.y);
         // store the fact that this line has been written to
         if (lineptr->type == LINE_EMPTY) {
             lineptr->type = LINE_REGULAR;
         }
         // advance cursor to the right
         this->cursorpos.x++;
         if (this->cursorpos.x == this->dims.x) {
             this->cursorpos.x -= 1;
             this->cursor_special_lastcol = true;
         }
         break;
     }
 }
References advance(), bell, chrdataptr(), openage::console::buf_char::cp, current_char_fmt, cursor_special_lastcol, cursorpos, dims, escaped, openage::console::LINE_EMPTY, openage::console::LINE_REGULAR, openage::console::LINE_WRAPPED, linedataptr(), and openage::console::buf_line::type.
Referenced by process_codepoint(), and process_csi_escape_sequence().
process_codepoint()
void openage::console::Buf::process_codepoint (int cp)
processes one unicode codepoint internally called by write(char) after feeding the char into streamdecoder
Definition at line 416 of file buf.cpp.
{
     // if the terminal is currently in escaped state, tread the codepoint as
     // part of the current escape sequence.
     if (this->escaped) {
         this->escape_sequence.push_back(cp);
         size_t len = this->escape_sequence.size();
         int first = this->escape_sequence[0];
         int previous = -1;
         if (len > 1) {
             previous = this->escape_sequence[len - 2];
         }
         // the first char of the escape sequence determines
         // its length, terminators and allowed characters.
         switch (first) {
         case '[':
             // CSI
             if (len == 1 or (cp >= 0x20 and cp < 0x40)) {
                 // regular, allowed char
             } else if (cp >= 0x40 and cp < 0x7f) {
                 // terminator
                 this->process_csi_escape_sequence();
             } else {
                 // illegal char, abortabortabort
                 this->escape_sequence_aborted();
             }
             break;
         case ']':  // OSC
         case 'P':  // DCS
         case '_':  // APC
         case '^':  // PM
             // terminated by ESC \ or BEL
             if ((previous == 0x1b and cp == '\\') or cp == 0x07) {
                 this->process_text_escape_sequence();
             }
             break;
         case '(':  // non-utf8-related stuff
         case ')':  // character-set selection etc...
         case '*':  // these are all 2-char sequences
         case '+':
         case '-':
         case '/':
         case '.':
         case '%':
         case '#':
         case ' ':
             // not implemented
             if (len == 2) {
                 this->escape_sequence_aborted();
             }
             break;
         default: // no known multi-cp sequence, treat as single escaped cp
             this->process_escaped_cp(first);
             break;
         }
     } else {
         // we're not currently escaped, so the char is printed...
         // at least if it's a printable character.
         this->print_codepoint(cp);
     }
 }
References escape_sequence, escape_sequence_aborted(), escaped, print_codepoint(), process_csi_escape_sequence(), process_escaped_cp(), and process_text_escape_sequence().
Referenced by write().
process_csi_escape_sequence()
void openage::console::Buf::process_csi_escape_sequence ()
processes the CSI escape sequence currently stored in escape_sequence.
invalid sequences are ignored.
Definition at line 661 of file buf.cpp.
{
     size_t len = this->escape_sequence.size();
     int type = this->escape_sequence[len - 1];
     bool starts_with_questionmark = false;
     std::vector<int> params;
     bool in_param = false;
     int currentparam;
     for (size_t pos = 1; pos < len - 1; pos++) {
         int cp = this->escape_sequence[pos];
         if (cp == '?' && pos == 1) {
             starts_with_questionmark = true;
         } else if (cp >= '0' && cp <= '9') {
             if (!in_param) {
                 in_param = true;
                 currentparam = 0;
             }
             currentparam = 10 * currentparam + (cp - '0');
         } else if (cp == ';') {
             if (!in_param) {
                 // this ';' did not have a number before it
                 // (ommited)
                 currentparam = -1;
             }
             params.push_back(currentparam);
             in_param = false;
         } else {
             // unexpected character, we want a nice
             // semicolon-separated list of decimal numbers.
             // abortabortabort
             this->escape_sequence_aborted();
             return;
         }
     }
     if (in_param) {
         // there's no semicolon at the end, finish the param
         params.push_back(currentparam);
     } else {
         // there's a semicolon at the end, or we had no params
         // at all. add param with default value.
         params.push_back(-1);
     }
     // default values
     int defaultval;
     unsigned minparamcount;
     switch (type) {
     case 'H':
     case 'f':
         minparamcount = 2;
         defaultval = 1;
         break;
     case 'J':
     case 'K':
     case 'm':
         minparamcount = 1;
         defaultval = 0;
         break;
     case 's':
     case 'u':
         minparamcount = 0;
         defaultval = 0;
         break;
     default:
         minparamcount = 1;
         defaultval = 1;
         break;
     }
     // apply default value requirements
     while (params.size() < minparamcount) {
         params.push_back(-1);
     }
     for (int &p: params) {
         if (p == -1) {
             p = defaultval;
         }
     }
     // execute the escape sequence
     switch (type) {
     case '@': // ICH: insert n blank characters
         for (int i = 0; i < params[0]; i++) {
             this->print_codepoint(0x20);
         }
         break;
     case 'A': // CUU: move cursor up
         this->cursorpos.y -= params[0];
         if (this->cursorpos.y < 0) {
             this->cursorpos.y = 0;
         }
         break;
     case 'e': // VPR: vertical position relative
         //fall through
     case 'B': // CUD: move cursor down
         this->cursorpos.y += params[0];
         if (this->cursorpos.y >= this->dims.y) {
             this->cursorpos.y = this->dims.y - 1;
         }
         break;
     case 'C': // CUF: move cursor to the right
         this->cursorpos.x += params[0];
         if (this->cursorpos.x >= this->dims.x) {
             this->cursorpos.x = this->dims.x - 1;
         }
         break;
     case 'D': // CUB: move cursor to the left
         this->cursorpos.x -= params[0];
         if (this->cursorpos.x < 0) {
             this->cursorpos.x = 0;
         }
         break;
     case 'E': // CNL: move cursor down and to beginning of line
         this->cursorpos.x = 0;
         this->cursorpos.y += params[0];
         if (this->cursorpos.y >= this->dims.y) {
             this->cursorpos.y = this->dims.y - 1;
         }
         break;
     case 'F': // CPL: move cursor up and to beginning of line
         this->cursorpos.x = 0;
         this->cursorpos.y -= params[0];
         if (this->cursorpos.y < 0) {
             this->cursorpos.y = 0;
         }
         break;
     case 'G': // CHA: set cursorpos.x
         this->cursorpos.x = params[0] - 1;
         if (this->cursorpos.x < 0) {
             this->cursorpos.x = 0;
         }
         if (this->cursorpos.x >= this->dims.x) {
             this->cursorpos.x = this->dims.x - 1;
         }
         break;
     case 'f': // HVP: set cursorpos
         //fall through
     case 'H': // CUP: set cursorpos
         this->cursorpos.y = params[0] - 1;
         this->cursorpos.x = params[1] - 1;
         if (this->cursorpos.x < 0) {
             this->cursorpos.x = 0;
         }
         if (this->cursorpos.x >= this->dims.x) {
             this->cursorpos.x = this->dims.x - 1;
         }
         if (this->cursorpos.y < 0) {
             this->cursorpos.y = 0;
         }
         if (this->cursorpos.y >= this->dims.y) {
             this->cursorpos.y = this->dims.y - 1;
         }
         break;
     case 'd': // VPA: vertical position absolute
         this->cursorpos.y = params[0] - 1;
         if (this->cursorpos.y < 0) {
             this->cursorpos.y = 0;
         }
         if (this->cursorpos.y >= this->dims.y) {
             this->cursorpos.y = this->dims.y - 1;
         }
         break;
     case 'J': // ED: erase display
         switch (params[0]) {
         case 0: // clear screen buffer from cursor to end
             this->clear(this->cursorpos, {0, this->dims.y});
             break;
         case 1: // clear screen buffer from beginning to cursor
             this->clear({0, 0}, this->cursorpos, true);
             break;
         case 2: // clear screen buffer
             this->clear({0, 0}, {0, this->dims.y});
             break;
         default: // unknown/unimplemented parameter
             break;
         }
         break;
     case 'K': // EL: erase line
         switch (params[0]) {
         case 0: // clear current line from cursor to end
             this->clear(this->cursorpos, {0, (term_t) (this->cursorpos.y + 1)});
             break;
         case 1: // clear current line from beginning to cursor
             this->clear({0, this->cursorpos.y}, this->cursorpos, true);
             break;
         case 2: // clear current line
             this->clear({0, this->cursorpos.y}, {0, (term_t) (this->cursorpos.y + 1)});
             break;
         default: // unknown/unimplemented parameter
             break;
         }
         break;
     case 'm': // SGR: set graphics rendition
         this->process_sgr_code(params);
         break;
     case 's': // SCP: save cursor position
         this->saved_cursorpos = this->cursorpos;
         break;
     case 'u': // RCP: restore cursor position
         this->cursorpos = this->saved_cursorpos;
         break;
     case 'l': // set mode
         if (starts_with_questionmark) {
             switch(params[0]) {
             case 25: // cursor invisible
                 this->cursor_visible = false;
                 break;
             case 1049: // switch to alternate screen
                 // TBI
                 // idea: use last dims.y lines of scrollback
                 // buffer to save regular screen data
                 break;
             default: // unknown/unimplemented parameter
                 break;
             }
         } else {
             switch(params[0]) {
             default: // unknown/unimplemented parameter
                 break;
             }
             break;
         }
         break;
     case 'h': // reset mode
         if (starts_with_questionmark) {
             switch(params[0]) {
             case 25: // cursor visible
                 this->cursor_visible = true;
                 break;
             case 1049: // restore regular screen
                 // TBI
                 break;
             default: // unknown/unimplemented parameter
                 break;
             }
         } else {
             switch(params[0]) {
             default: // unknown/unimplemented parameter
                 break;
             }
             break;
         }
         break;
     case 'S': // SU
     case 'T': // SD
     case 'n': // DSR
         // not implemented; fall through.
     default:
         // not implemented (or nonexisting)
         this->escape_sequence_aborted();
         return;
     }
     this->escape_sequence_processed();
 }
References clear(), cursor_visible, cursorpos, dims, escape_sequence, escape_sequence_aborted(), escape_sequence_processed(), print_codepoint(), process_sgr_code(), and saved_cursorpos.
Referenced by process_codepoint().
process_escaped_cp()
void openage::console::Buf::process_escaped_cp (int cp)
processes a single-codepoint escape sequence.
invalid codepoints are ignored.
Definition at line 621 of file buf.cpp.
{
     switch (cp) {
     case 'c': //RIS (full reset)
         this->reset();
         break;
     default:
         //unimplemented or invalid codepoint
         this->escape_sequence_aborted();
         break;
     }
 }
References escape_sequence_aborted(), and reset().
Referenced by process_codepoint().
process_sgr_code()
void openage::console::Buf::process_sgr_code (const std::vector< int > & params)
sets graphics rendition parameters; called by process_escape_sequence
params: numerical params list from escape sequence
Definition at line 919 of file buf.cpp.
{
     for (size_t i = 0; i < params.size(); i++) {
         int p = params[i];
         switch (p) {
         case 0: // reset
             this->current_char_fmt = this->default_char_fmt;
             break;
         case 1: // bold
             this->current_char_fmt.flags |= CHR_BOLD;
             this->current_char_fmt.flags &= ~CHR_FAINT;
             break;
         case 2: // faint
             this->current_char_fmt.flags |= CHR_FAINT;
             this->current_char_fmt.flags &= ~CHR_BOLD;
             break;
         case 3: // italic
             this->current_char_fmt.flags |= CHR_ITALIC;
             this->current_char_fmt.flags &= ~CHR_FRAKTUR;
             break;
         case 4: // underline
             this->current_char_fmt.flags |= CHR_UNDERLINED;
             break;
         case 5: // blink slowly
             this->current_char_fmt.flags |= CHR_BLINKING;
             this->current_char_fmt.flags &= ~CHR_BLINKINGFAST;
             break;
         case 6: // blink fast
             this->current_char_fmt.flags |= CHR_BLINKINGFAST;
             this->current_char_fmt.flags &= ~CHR_BLINKING;
             break;
         case 7: // negative
             this->current_char_fmt.flags |= CHR_NEGATIVE;
             break;
         case 8: // invisible
             this->current_char_fmt.flags |= CHR_INVISIBLE;
             break;
         case 9: // struck out
             this->current_char_fmt.flags |= CHR_STRUCKOUT;
             break;
         // cases 10-19: font selectors. not implemented.
         case 20: // fraktur
             this->current_char_fmt.flags |= CHR_FRAKTUR;
             this->current_char_fmt.flags &= ~CHR_ITALIC;
             break;
         case 21: // bold off
             this->current_char_fmt.flags &= ~CHR_BOLD;
             break;
         case 22: // bold and faint off
             this->current_char_fmt.flags &= ~CHR_BOLD;
             this->current_char_fmt.flags &= ~CHR_FAINT;
             break;
         case 23: // italic and fraktur off
             this->current_char_fmt.flags &= ~CHR_ITALIC;
             this->current_char_fmt.flags &= ~CHR_FRAKTUR;
             break;
         case 24: // underline off
             this->current_char_fmt.flags &= ~CHR_UNDERLINED;
             break;
         case 25: // blinking and blinkingfast off
             this->current_char_fmt.flags &= ~CHR_BLINKING;
             this->current_char_fmt.flags &= ~CHR_BLINKINGFAST;
             break;
         // case 26: not yet standardized
         case 27: // negative off
             this->current_char_fmt.flags &= ~CHR_NEGATIVE;
             break;
         case 28: // invisible off
             this->current_char_fmt.flags &= ~CHR_INVISIBLE;
             break;
         case 29: // struck out off
             this->current_char_fmt.flags &= ~CHR_STRUCKOUT;
             break;
         case 30:
         case 31:
         case 32:
         case 33:
         case 34:
         case 35:
         case 36:
         case 37: // foreground color (8 colors)
             this->current_char_fmt.fgcol = (p - 30);
             break;
         case 38: // foreground color (256 colors)
             i += 2;
             if (i >= params.size() || params[i] < 0 || params[i] >= 256) {
                 // invalid 256-color SGR code.
                 return;
             }
             this->current_char_fmt.fgcol = params[i];
             break;
         case 39: // reset foreground color
             this->current_char_fmt.fgcol = this->default_char_fmt.fgcol;
             break;
         case 40:
         case 41:
         case 42:
         case 43:
         case 44:
         case 45:
         case 46:
         case 47: // background color (8 colors)
             this->current_char_fmt.bgcol = (p - 40);
             break;
         case 48: // background color (256 colors)
             i += 2;
             if (i >= params.size() || params[i] < 0 || params[i] >= 256) {
                 // invalid 256-color SGR code.
                 // abortabortabort
                 return;
             }
             this->current_char_fmt.bgcol = params[i];
             break;
         case 49: // reset background color
             this->current_char_fmt.bgcol = this->default_char_fmt.bgcol;
             break;
         // case 50: not yet standardized
         case 51: // framed
             this->current_char_fmt.flags |= CHR_FRAMED;
             this->current_char_fmt.flags &= ~CHR_ENCIRCLED;
             break;
         case 52: // encircled
             this->current_char_fmt.flags |= CHR_ENCIRCLED;
             this->current_char_fmt.flags &= ~CHR_FRAMED;
             break;
         case 53: // overlined
             this->current_char_fmt.flags |= CHR_OVERLINED;
             break;
         case 54: // framed and encircled off
             this->current_char_fmt.flags &= ~CHR_FRAMED;
             this->current_char_fmt.flags &= ~CHR_ENCIRCLED;
             break;
         case 55: // overlined off
             this->current_char_fmt.flags &= ~CHR_OVERLINED;
             break;
         // cases 56-59: not yet standardized
         case 60: // right side line
             this->current_char_fmt.flags |= CHR_RIGHTLINED;
             break;
         // case 61: double right side line. not implemented.
         case 62: // left side line
             this->current_char_fmt.flags |= CHR_LEFTLINED;
             break;
         // case 63: double left side line. not implemented.
         case 64: // stress ideogram (whatever that is)
             this->current_char_fmt.flags |= CHR_STRESS_IDEOGRAM;
             break;
         case 65: // disables effects 60-64
             this->current_char_fmt.flags &= ~CHR_RIGHTLINED;
             this->current_char_fmt.flags &= ~CHR_LEFTLINED;
             break;
         // cases above 65 are not standardized.
         default:
             // not implemented or not defined.
             // abortabortabort
             return;
         }
     }
 }
References openage::console::buf_char::bgcol, openage::console::CHR_BLINKING, openage::console::CHR_BLINKINGFAST, openage::console::CHR_BOLD, openage::console::CHR_ENCIRCLED, openage::console::CHR_FAINT, openage::console::CHR_FRAKTUR, openage::console::CHR_FRAMED, openage::console::CHR_INVISIBLE, openage::console::CHR_ITALIC, openage::console::CHR_LEFTLINED, openage::console::CHR_NEGATIVE, openage::console::CHR_OVERLINED, openage::console::CHR_RIGHTLINED, openage::console::CHR_STRESS_IDEOGRAM, openage::console::CHR_STRUCKOUT, openage::console::CHR_UNDERLINED, current_char_fmt, default_char_fmt, openage::console::buf_char::fgcol, and openage::console::buf_char::flags.
Referenced by process_csi_escape_sequence().
process_text_escape_sequence()
void openage::console::Buf::process_text_escape_sequence ()
processes a text escape sequence that is one of OSC, DCS, APC or PM
Definition at line 633 of file buf.cpp.
{
     size_t len = this->escape_sequence.size();
     switch (this->escape_sequence[0]) {
     case ']': //OSC
         switch (this->escape_sequence[1]) {
         case '0':
         case '2':
             if (this->escape_sequence[2] == ';') {
                 //set window title
                 int maxidx = len - 1;
                 if (this->escape_sequence[len - 1] == '\\') {
                     maxidx = len - 2;
                 }
                 this->title.clear();
                 for (int i = 3; i < maxidx; i++) {
                     this->title.push_back(this->escape_sequence[i]);
                 }
                 this->escape_sequence_processed();
             }
         }
         break;
     default:
         break;
     }
     //not implemented or invalid
     this->escape_sequence_aborted();
 }
References escape_sequence, escape_sequence_aborted(), escape_sequence_processed(), and title.
Referenced by process_codepoint().
reset()
void openage::console::Buf::reset ()
resets the buffer to its constructor defaults
Definition at line 52 of file buf.cpp.
                 {
     this->cursorpos = {0, 0};
     this->saved_cursorpos = {0, 0};
     this->cursor_visible = true;
     this->cursor_special_lastcol = false;
     this->escaped = false;
     this->bell = false;
     this->current_char_fmt = this->default_char_fmt;
     this->scrollback_possible = 0;
     this->scrollback_pos = 0;
     //fully clear data and linedata
     this->clear({0, (term_t) -this->scrollback_lines}, {0, this->dims.y});
 }
References bell, clear(), current_char_fmt, cursor_special_lastcol, cursor_visible, cursorpos, default_char_fmt, dims, escaped, saved_cursorpos, scrollback_lines, scrollback_pos, and scrollback_possible.
Referenced by process_escaped_cp().
resize()
void openage::console::Buf::resize (coord::term new_dims)
resizes the screen buffer
Todo:
copy line by line, considering the value stored in old_linedata_pos->auto_wrapped. start with the first line of the scrollback buffer, and stop with the last line of the screen buffer. do not copy empty characters, unless they are followed by filled characters in the same line, or a continued wrapped line. store in term_t variables the locations in the new buffer of the first/last line of the old scrollback buffer the first/last line of the old screen buffer these variables need to take into account events where upmost lines of a buffer are overwritten by new lines. commented out for now
Todo:
depending on the variables defined in the previous section, decide which line is the first line of the screen buffer int new_chrbuf, and which parts of new_chrbuf must be cleared.
Definition at line 214 of file buf.cpp.
{
     term old_dims = this->dims;
     if (new_dims.x < this->min_width) {
         new_dims.x = this->min_width;
     }
     if (new_dims.y < 1) {
         new_dims.y = 1;
     }
     // allocate new buffers
     size_t new_linedata_size = new_dims.y + this->scrollback_lines;
     buf_line *new_linedata = new buf_line[new_linedata_size];
     buf_line *new_linedata_end = new_linedata + new_linedata_size;
     size_t new_chrdata_size = new_dims.x * new_linedata_size;
     buf_char *new_chrdata = new buf_char[new_chrdata_size];
     buf_char *new_chrdata_end = new_chrdata + new_chrdata_size;
     // working positions in new buffers: start at beginning of buffer
     buf_line *new_linedata_pos = new_linedata;
     buf_char *new_chrdata_pos = new_chrdata;
     // working positions in old buffers: start with oldest line of
     // scrollback buffer
     buf_line *old_linedata_scrollbackstart = this->linedataptr(-scrollback_lines);
     buf_char *old_chrdata_scrollbackstart = this->chrdataptr({0, (term_t) -scrollback_lines});
     buf_line *old_linedata_pos = old_linedata_scrollbackstart;
     buf_char *old_chrdata_pos = old_chrdata_scrollbackstart;
     // term_t scrollback_buf_start;
     // term_t scrollback_buf_end;
     // term_t screen_buf_start;
     // term_t screen_buf_end;
     // count the number of empty chars that we've found in this line,
     // and we may or may not still have to copy.
     size_t empty_chars = 0;
     while (old_linedata_pos != old_linedata_scrollbackstart) {
         // should never be >, always ==
         // also, both checks should always yield identical results
         // \todo do an ASSERT to assure this?)
         if (old_linedata_pos >= this->linedata_end) {
             old_linedata_pos = this->linedata;
         }
         if (old_chrdata_pos >= this->chrdata_end) {
             old_chrdata_pos = this->chrdata;
         }
         // should never be >, always ==
         // also, both checks should always yield identical results
         // \todo do an ASSERT to assure this?)
         if (new_linedata_pos >= new_linedata_end) {
             new_linedata_pos = new_linedata;
         }
         if (new_chrdata_pos >= new_chrdata_end) {
             new_chrdata_pos = new_chrdata;
         }
         for (term_t x = 0; x < old_dims.x; x++) {
             if (*old_chrdata_pos == this->default_char_fmt) {
                 empty_chars++;
             } else {
                 while (empty_chars > 0) {
                     // \todo write the empty chars
                 }
                 // \todo write the char
             }
             old_chrdata_pos++;
         }
     }
     // \todo copy
     this->dims = new_dims;
 }
References chrdata, chrdata_end, chrdataptr(), default_char_fmt, dims, linedata, linedata_end, linedataptr(), min_width, and scrollback_lines.
scroll()
void openage::console::Buf::scroll (coord::term_t lines)
scrolls up or down by the given number of lines
lines amount of lines to scroll up - may be negative if the upper or lower limit is reached, this is capped.
Definition at line 322 of file buf.cpp.
{
     if (lines < 0) {
         // scroll down
         lines = -lines;
         if ((term_t) this->scrollback_pos < lines) {
             this->scrollback_pos = 0;
         } else {
             this->scrollback_pos -= lines;
         }
     } else {
         // scroll up
         this->scrollback_pos += lines;
         if (this->scrollback_pos > this->scrollback_possible) {
             this->scrollback_pos = this->scrollback_possible;
         }
     }
 }
References scrollback_pos, and scrollback_possible.
write() [1/2]
void openage::console::Buf::write (const char * c, ssize_t len = -1)
write a byte string to the buffer
the string is assumed to be UTF-8 encoded.
if len >= 0, it describes the length of the string. otherwise, the string is assumed to be null-terminated.
Definition at line 309 of file buf.cpp.
{
     if (len >= 0) {
         for (; len > 0; len--) {
             this->write(*c);
             c++;
         }
     } else {
         for (; *c; c++) {
             this->write(*c);
         }
     }
 }
Referenced by openage::console::Console::register_to_engine(), openage::console::tests::render(), and openage::console::Console::write().
write() [2/2]
void openage::console::Buf::write (char c)
write a single byte to the buffer.
assumed to be UTF-8 encoded.
Definition at line 382 of file buf.cpp.
                       {
     if (!this->streamdecoder.feed(c)) {
         // an error has been detected in the input stream
         this->process_codepoint(0xFFFD);
     };
     if (this->streamdecoder.remaining == 0 && this->streamdecoder.out >= 0) {
         this->process_codepoint(streamdecoder.out);
     }
 }
References openage::util::utf8_decoder::feed(), openage::util::utf8_decoder::out, process_codepoint(), openage::util::utf8_decoder::remaining, and streamdecoder.
Friends And Related Function Documentation
NewBuf
friend class NewBuf friend
Definition at line 122 of file buf.h.
Member Data Documentation
bell
bool openage::console::Buf::bell
true if an bell ('') has been received, but not cleared
Definition at line 468 of file buf.h.
Referenced by print_codepoint(), and reset().
chrdata
buf_char* openage::console::Buf::chrdata
the complete (2-dimensional) terminal output buffer content
contains the screen buffer (where the cursor may move), and the scrollback buffer (which is invisible while not scrolled back)
thus, its size is always screen buffer size + scrollback buffer size (dims.x * dims.y + dims.x * scrollback_lines)
on resize, this buffer is completely re-created.
the first entry of data is not neccesarily the first character of the screen or scrollback buffer; see screen_chrdata.
Definition at line 347 of file buf.h.
Referenced by openage::console::NewBuf::apply_to_buf(), chrdata_clear(), chrdataptr(), resize(), and ~Buf().
chrdata_end
buf_char* openage::console::Buf::chrdata_end
stores the end of the region allocated for data, for performance and convenience reasons.
points to the first memory region outside the data buffer.
always has the value data + chrdata_size
Definition at line 366 of file buf.h.
Referenced by advance(), openage::console::NewBuf::apply_to_buf(), chrdata_clear(), chrdataptr(), and resize().
chrdata_size
size_t openage::console::Buf::chrdata_size
stores the (array) size of data, for performance and convenience reasons.
always has the value dims.x * (dims.y + scrollback_lines)
Definition at line 356 of file buf.h.
Referenced by advance(), openage::console::NewBuf::apply_to_buf(), and chrdataptr().
current_char_fmt
buf_char openage::console::Buf::current_char_fmt
surrently selected formatting (colors, flags).
all printed chars, as well as all buffer clearing, will use this until it is changed by an SGR escape sequence.
the codepoint is the codepoint used for filling empty chars (e.g. 0x20 ('space'))
Definition at line 483 of file buf.h.
Referenced by chrdata_clear(), pop_last_char(), print_codepoint(), process_sgr_code(), and reset().
cursor_special_lastcol
bool openage::console::Buf::cursor_special_lastcol
true if cursor is in the last column while whole line is filled this is very special.
this allows CR after fully-filled lines to return to the same line, instead of being in the next line.
Definition at line 451 of file buf.h.
Referenced by pop_last_char(), print_codepoint(), and reset().
cursor_visible
bool openage::console::Buf::cursor_visible
true if the cursor is visible
Definition at line 443 of file buf.h.
Referenced by process_csi_escape_sequence(), reset(), openage::console::draw::to_opengl(), and openage::console::draw::to_terminal().
cursorpos
coord::term openage::console::Buf::cursorpos
cursor position
Definition at line 433 of file buf.h.
Referenced by pop_last_char(), print_codepoint(), process_csi_escape_sequence(), reset(), openage::console::draw::to_opengl(), and openage::console::draw::to_terminal().
default_char_fmt
const buf_char openage::console::Buf::default_char_fmt
the default buf char, which will be used for filling new lines, or determining whether a line is empty.
should have space (0x20) as its char, and the desired default values for fgcol and bgcol.
Definition at line 491 of file buf.h.
Referenced by process_sgr_code(), reset(), and resize().
dims
coord::term openage::console::Buf::dims
screen buffer dimensions (in characters)
Definition at line 420 of file buf.h.
Referenced by advance(), openage::console::NewBuf::apply_to_buf(), Buf(), chrdataptr(), get_dims(), openage::console::tests::interactive(), pop_last_char(), print_codepoint(), process_csi_escape_sequence(), reset(), resize(), openage::console::draw::to_opengl(), and openage::console::draw::to_terminal().
escape_sequence
std::vector<int> openage::console::Buf::escape_sequence
current escape sequence
Definition at line 463 of file buf.h.
Referenced by escape_sequence_aborted(), escape_sequence_processed(), process_codepoint(), process_csi_escape_sequence(), and process_text_escape_sequence().
escaped
bool openage::console::Buf::escaped
true if we are currently reading an escape sequence
Definition at line 458 of file buf.h.
Referenced by escape_sequence_aborted(), escape_sequence_processed(), print_codepoint(), process_codepoint(), and reset().
linedata
buf_line* openage::console::Buf::linedata
similar to how data holds information about all characters, linedata holds information about all lines.
currently, the only held information is whether the line has been started by wrapping an existing line (and thus is not a 'real' new line)
Definition at line 392 of file buf.h.
Referenced by openage::console::NewBuf::apply_to_buf(), linedata_clear(), linedataptr(), resize(), and ~Buf().
linedata_end
buf_line* openage::console::Buf::linedata_end
see chrdata_end
Definition at line 402 of file buf.h.
Referenced by advance(), openage::console::NewBuf::apply_to_buf(), linedata_clear(), linedataptr(), and resize().
linedata_size
size_t openage::console::Buf::linedata_size
see chrdata_size
Definition at line 397 of file buf.h.
Referenced by advance(), openage::console::NewBuf::apply_to_buf(), and linedataptr().
min_width
coord::term_t openage::console::Buf::min_width
minimum screen buffer width
Definition at line 415 of file buf.h.
Referenced by resize().
saved_cursorpos
coord::term openage::console::Buf::saved_cursorpos
saved cursor position
Definition at line 438 of file buf.h.
Referenced by process_csi_escape_sequence(), and reset().
screen_chrdata
buf_char* openage::console::Buf::screen_chrdata
points to the first character that belongs to the screen buffer, inside the data buffer.
this pointer is changed when the terminal buffer advances one line.
note that screen_chrdata may NOT be directly indexed, as *screen_chrdata[k] might be >= chrdata_end. in this case, the correct memory location will be *screen_chrdata[k - chrdata_size].
*screen_chrdata[0] always is the correct memory location of the screen buffer top left corner.
*screen_chrdata[dims.x * dims.y] is the memory location of the scrollback buffer top left corner, but it might be neccesary to subtract chrdata_size to get an actually valid memory location.
Definition at line 384 of file buf.h.
Referenced by advance(), and chrdataptr().
screen_linedata
buf_line* openage::console::Buf::screen_linedata
as an analog to screen_chrdata, this points to the entry in linedata that holds metadata about the top line of the screen buffer.
Definition at line 408 of file buf.h.
Referenced by advance(), and linedataptr().
scrollback_lines
coord::term_t openage::console::Buf::scrollback_lines
scrollback buffer height; scrollback buffer width is identical to screen buffer width.
Definition at line 426 of file buf.h.
Referenced by advance(), reset(), and resize().
scrollback_pos
coord::term_t openage::console::Buf::scrollback_pos
how many lines the buffer is currently scrolled back.
if 0, the screen buffer is wholly rendered. if the terminal is being advanced, this stays 0. this makes the terminal follow newly printed text. if > 0, the bottom lines of the screen buffer are not rendered, and the bottom lines of the scrollback buffer are rendered instead. if screen buffer advances, this is increased accordingly (unless it would become >= scrollback_lines). this causes the currently scrolled-to position to remain scrolled-to even when new text is printed.
must be >= 0 and <= scrollback_possible.
Definition at line 518 of file buf.h.
Referenced by advance(), reset(), scroll(), openage::console::draw::to_opengl(), and openage::console::draw::to_terminal().
scrollback_possible
coord::term_t openage::console::Buf::scrollback_possible
how far it's currently possible to scroll back.
this value steadily increases when the buffer advances.
if this is 0, all lines outside the screen buffer are empty.
must be >= 0 and <= scrollback_lines
Definition at line 501 of file buf.h.
Referenced by advance(), reset(), scroll(), and openage::console::draw::to_terminal().
streamdecoder
util::utf8_decoder openage::console::Buf::streamdecoder
utf-8 state-machine that reads input bytes and outputs unicode codepoints
Definition at line 188 of file buf.h.
Referenced by write().
title
std::vector<int> openage::console::Buf::title
window title
Definition at line 473 of file buf.h.
Referenced by process_text_escape_sequence(), and openage::console::draw::to_terminal().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/console/buf.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/console/buf.cpp