openage: openage::ProjectileAction Class Reference
openage::ProjectileAction Class Reference
moves object to fly in a parabolic shape
#include <action.h>
Public Member Functions
ProjectileAction (Unit *e, coord::phys3 target)
virtual ~ProjectileAction ()
void update (unsigned int time) override
each action has its own update functionality which gets called when this is the active action
void on_completion () override
action to perform when popped from a units action stack
bool completed () const override
gets called for all actions on stack each update cycle
bool allow_interupt () const override
checks if the action can be interrupted, allowing it to be popped if the user specifies a new action, if false the action must reach a completed state before removal eg dead action must be completed and cannot be discarded
bool allow_control () const override
control whether stack can discard the action automatically and should the stack be modifiable when this action is on top
std::string name () const override
debug string to identify action types
Public Member Functions inherited from openage::UnitAction
UnitAction (Unit *u, graphic_type initial_gt)
Require unit to be updated and an initial graphic type.
virtual ~UnitAction ()
graphic_type type () const
type of graphic this action should use
float current_frame () const
frame number to use on the current graphic
virtual const graphic_set & current_graphics () const
determines which graphic should be used for drawing this unit finds the default graphic using the units type, used by most actions
void draw_debug (const Engine &engine)
void face_towards (const coord::phys3 pos)
common functions for actions
bool damage_unit (Unit &target)
Damage a unit, returns true if the unit was killed in the process.
void move_to (Unit &target, bool use_range=true)
Private Attributes
double grav
bool has_hit
Additional Inherited Members
Static Public Member Functions inherited from openage::UnitAction
static coord::phys_t adjacent_range (Unit *u)
a small distance to which units are considered touching when within this distance
static coord::phys_t get_attack_range (Unit *u)
looks at an ranged attributes on the unit otherwise returns same as adjacent_range()
static coord::phys_t get_heal_range (Unit *u)
looks at heal attribute on the unit otherwise returns same as adjacent_range()
Static Public Attributes inherited from openage::UnitAction
static bool show_debug = false
produce debug info such as visualising paths
Protected Attributes inherited from openage::UnitAction
Unit * entity
the entity being updated
graphic_type graphic
common graphic controls
float frame
float frame_rate
std::function< void(const Engine &)> debug_draw_action
additional drawing for debug purposes
Detailed Description
moves object to fly in a parabolic shape
Definition at line 631 of file action.h.
Constructor & Destructor Documentation
ProjectileAction()
openage::ProjectileAction::ProjectileAction (Unit * e, coord::phys3 target)
Definition at line 1303 of file action.cpp.
     :
     UnitAction{e, graphic_type::standing},
     has_hit{false} {
     // find speed to move
     auto &sp_attr = this->entity->get_attribute<attr_type::speed>();
     double projectile_speed = sp_attr.unit_speed.to_double();
     // arc of projectile
     auto &pr_attr = this->entity->get_attribute<attr_type::projectile>();
     float projectile_arc = pr_attr.projectile_arc;
     // distance and time to target
     coord::phys3_delta d = target - this->entity->location->pos.draw;
     double distance_to_target = d.length();
     double flight_time = distance_to_target / projectile_speed;
     if (projectile_arc < 0) {
         // \todo negative values probably indicate something
         projectile_arc += 0.2;
     }
     // now figure gravity from arc parameter
     // \todo projectile arc is the ratio between horizontal and
     // vertical components of the initial direction
     this->grav = 0.01f * (exp(pow(projectile_arc, 0.5f)) - 1) * projectile_speed;
     // inital launch direction
     auto &d_attr = this->entity->get_attribute<attr_type::direction>();
     d_attr.unit_dir = d * (projectile_speed / distance_to_target);
     // account for initial height
     coord::phys_t initial_height = this->entity->location->pos.draw.up;
     d_attr.unit_dir.up = coord::phys_t((grav * flight_time) / 2) - (initial_height * (1 / flight_time));
 }
References openage::standing.
~ProjectileAction()
openage::ProjectileAction::~ProjectileAction () virtual
Definition at line 1341 of file action.cpp.
 {}
Member Function Documentation
allow_control()
bool openage::ProjectileAction::allow_control () const inline override virtual
control whether stack can discard the action automatically and should the stack be modifiable when this action is on top
if true this action must complete and will not allow new actions to be pushed while it is active and also does not update the secondary actions
Implements openage::UnitAction.
Definition at line 640 of file action.h.
 { return false; }
allow_interupt()
bool openage::ProjectileAction::allow_interupt () const inline override virtual
checks if the action can be interrupted, allowing it to be popped if the user specifies a new action, if false the action must reach a completed state before removal eg dead action must be completed and cannot be discarded
Implements openage::UnitAction.
Definition at line 639 of file action.h.
 { return false; }
completed()
bool openage::ProjectileAction::completed () const override virtual
gets called for all actions on stack each update cycle
Returns
true when action is completed so it and everything above it can be popped
Implements openage::UnitAction.
Definition at line 1378 of file action.cpp.
{
     return (has_hit || this->entity->location->pos.draw.up <= 0);
 }
References openage::UnitAction::entity, has_hit, and openage::Unit::location.
name()
std::string openage::ProjectileAction::name () const inline override virtual
debug string to identify action types
Implements openage::UnitAction.
Definition at line 641 of file action.h.
 { return "projectile"; }
Referenced by openage.util.fslike.path.Path::stem(), openage.util.fslike.path.Path::suffix(), and openage.util.fslike.path.Path::suffixes().
on_completion()
void openage::ProjectileAction::on_completion () override virtual
action to perform when popped from a units action stack
Implements openage::UnitAction.
Definition at line 1376 of file action.cpp.
 {}
update()
void openage::ProjectileAction::update (unsigned int time) override virtual
each action has its own update functionality which gets called when this is the active action
Implements openage::UnitAction.
Definition at line 1343 of file action.cpp.
{
     auto &d_attr = this->entity->get_attribute<attr_type::direction>();
     // apply gravity
     d_attr.unit_dir.up -= this->grav * time;
     coord::phys3 new_position = this->entity->location->pos.draw + d_attr.unit_dir * time;
     if (!this->entity->location->move(new_position)) {
         // \todo implement friendly_fire (now friendly_fire is always on), attack_attribute.friendly_fire
         // find object which was hit
         auto terrain = this->entity->location->get_terrain();
         TileContent *tc = terrain->get_data(new_position.to_tile3().to_tile());
         if (tc && !tc->obj.empty()) {
             for (auto obj_location : tc->obj) {
                 if (this->entity->location.get() != obj_location &&
                     obj_location->check_collisions()) {
                     this->damage_unit(obj_location->unit);
                     break;
                 }
             }
         }
         // \todo implement area of effect, attack_attribute.area_of_effect
         has_hit = true;
     }
     // inc frame
     this->frame += time * this->frame_rate;
 }
References openage::UnitAction::damage_unit(), openage::direction, openage::UnitAction::entity, openage::UnitAction::frame, openage::UnitAction::frame_rate, openage::Unit::get_attribute(), grav, has_hit, openage::Unit::location, openage::TileContent::obj, openage::coord::tile3::to_tile(), and openage::coord::phys3::to_tile3().
Member Data Documentation
grav
double openage::ProjectileAction::grav private
Definition at line 644 of file action.h.
Referenced by update().
has_hit
bool openage::ProjectileAction::has_hit private
Definition at line 645 of file action.h.
Referenced by completed(), and update().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/action.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/action.cpp