openage: openage::event::EventQueue Class Reference
openage::event::EventQueue Class Reference final
#include <eventqueue.h>
Classes
class OnChangeElement
Public Types
using change_set = std::unordered_set< OnChangeElement, OnChangeElement::Hasher, OnChangeElement::Equal >
Public Member Functions
EventQueue ()
std::shared_ptr< Event > create_event (const std::shared_ptr< EventTarget > &eventtarget, const std::shared_ptr< EventClass > &eventclass, const std::shared_ptr< State > &state, const curve::time_t &reference_time, const EventClass::param_map &params)
void remove (const std::shared_ptr< Event > &evnt)
void enqueue_change (const std::shared_ptr< Event > &event)
void reenqueue (const std::shared_ptr< Event > &event)
void add_change (const std::shared_ptr< Event > &event, const curve::time_t &changed_at)
const EventStore & get_event_queue () const
std::shared_ptr< Event > take_event (const curve::time_t &max_time)
const change_set & get_changes () const
void clear_changes ()
void swap_changesets ()
Private Attributes
change_set * changes
change_set * future_changes
change_set changeset_A
change_set changeset_B
std::unordered_set< std::shared_ptr< Event > > dependency_events
std::unordered_set< std::shared_ptr< Event > > dependency_immediately_events
std::unordered_set< std::shared_ptr< Event > > trigger_events
EventStore event_queue
Detailed Description
The core event class for execution and execution dependencies.
Definition at line 22 of file eventqueue.h.
Member Typedef Documentation
change_set
using openage::event::EventQueue::change_set = std::unordered_set<OnChangeElement, OnChangeElement::Hasher, OnChangeElement::Equal>
Type for the set to store changes to track.
Definition at line 53 of file eventqueue.h.
Constructor & Destructor Documentation
EventQueue()
openage::event::EventQueue::EventQueue ()
Definition at line 76 of file eventqueue.cpp.
     :
     changes(&changeset_A),
     future_changes(&changeset_B) {}
Member Function Documentation
add_change()
void openage::event::EventQueue::add_change (const std::shared_ptr< Event > & event, const curve::time_t & changed_at)
An event target has changed, and the event shall be retriggered
Definition at line 82 of file eventqueue.cpp.
{
     auto it = this->changes->find(OnChangeElement(event, changed_at));
     // Has the event been triggered in this round?
     if (event->last_triggered < changed_at) {
         // Is the change already in the queue?
         if (it != changes->end()) {
             // Is the new change dated _before_ the old one?
             if (it->time > changed_at) {
                 log::log(DBG << "Queue: adjusting time in change queue");
                 // Save the element
                 OnChangeElement e = *it;
                 e.time = changed_at;
                 // delete it from the container and readd it
                 it = this->changes->erase(it);
                 it = this->changes->insert(it, e);
             }
             else {
                 // this change is to be ignored
                 log::log(DBG << "Queue: skipping change for " << event->get_eventclass()->id()
                          << " at " << changed_at
                          << " because there was already a better one at t=" << it->time);
             }
         }
         else {
             // the change was not in the to be changed list
             this->changes->emplace(event, changed_at);
             log::log(DBG << "Queue: inserting change for " << event->get_eventclass()->id()
                      << " to be applied at t=" << changed_at);
         }
     }
     else {
         // the event has been triggered in this round already, so skip it this time
         this->future_changes->emplace(event, changed_at);
         log::log(DBG << "Queue: putting change for "
                  << event->get_eventclass()->id() << " into the future, "
                  << "applied at t=" << changed_at);
     }
     event->last_triggered = changed_at;
 }
References changes, DBG, future_changes, openage::log::log(), and openage::event::EventQueue::OnChangeElement::time.
Referenced by openage::event::Loop::create_change().
clear_changes()
void openage::event::EventQueue::clear_changes ()
All changes (fetched with get_changes) have been processed, so we can clear the change_set.
Definition at line 184 of file eventqueue.cpp.
{
     this->changes->clear();
 }
References changes.
Referenced by openage::event::Loop::update_changes().
create_event()
std::shared_ptr< Event > openage::event::EventQueue::create_event (const std::shared_ptr< EventTarget > & eventtarget, const std::shared_ptr< EventClass > & eventclass, const std::shared_ptr< State > & state, const curve::time_t & reference_time, const EventClass::param_map & params)
Add an event for a specified target
A target is every single unit in the game world - so best add these events in the constructor of the game objects.
The insertion_time is the time used to calculate when the actual event time will happen!
Definition at line 16 of file eventqueue.cpp.
{
     auto event = std::make_shared<Event>(trgt, cls, params);
     cls->setup_event(event, state);
     switch(cls->type) {
     case EventClass::trigger_type::DEPENDENCY:
     case EventClass::trigger_type::REPEAT:
     case EventClass::trigger_type::ONCE:
         event->set_time(event->get_eventclass()
                              ->predict_invoke_time(trgt, state, reference_time));
         if (event->get_time() == std::numeric_limits<curve::time_t>::min()) {
             log::log(DBG << "Queue: ignoring insertion of event "
                      << event->get_eventclass()->id() <<
                      " because no execution was scheduled.");
             return {};
         }
         break;
     case EventClass::trigger_type::DEPENDENCY_IMMEDIATELY:
     case EventClass::trigger_type::TRIGGER:
         event->set_time(reference_time);
         break;
     }
     log::log(DBG << "Queue: inserting event " << event->get_eventclass()->id() <<
              " into queue to be executed at t=" << event->get_time());
     // store the event
     // or enqueue it for execution
     switch(event->get_eventclass()->type) {
     case EventClass::trigger_type::DEPENDENCY:
         this->dependency_events.insert(event);
         break;
     case EventClass::trigger_type::DEPENDENCY_IMMEDIATELY:
         this->dependency_immediately_events.insert(event);
         break;
     case EventClass::trigger_type::TRIGGER:
         this->trigger_events.insert(event);
         break;
     case EventClass::trigger_type::REPEAT:
     case EventClass::trigger_type::ONCE:
     default:
         this->event_queue.push(event);
     }
     return event;
 }
References DBG, openage::event::EventClass::DEPENDENCY, dependency_events, openage::event::EventClass::DEPENDENCY_IMMEDIATELY, dependency_immediately_events, event_queue, openage::log::log(), std::min(), openage::event::EventClass::ONCE, openage::event::EventStore::push(), openage::event::EventClass::REPEAT, openage::event::EventClass::TRIGGER, and trigger_events.
Referenced by openage::event::Loop::create_event().
enqueue_change()
void openage::event::EventQueue::enqueue_change (const std::shared_ptr< Event > & event)
An update to existing events has to be applied. The execution time of this event may have changed or it is newly created. This updates/inserts the given event in the main queue.
Definition at line 138 of file eventqueue.cpp.
{
     if (this->event_queue.contains(evnt)) {
         this->event_queue.update(evnt);
     }
     else {
         this->event_queue.push(evnt);
     }
 }
References openage::event::EventStore::contains(), event_queue, openage::event::EventStore::push(), and openage::event::EventStore::update().
Referenced by openage::event::Loop::update_changes().
get_changes()
const EventQueue::change_set & openage::event::EventQueue::get_changes () const
Get the change_set to process changes.
Definition at line 179 of file eventqueue.cpp.
{
     return *this->changes;
 }
References changes.
Referenced by openage::event::Loop::update_changes().
get_event_queue()
const EventStore & openage::event::EventQueue::get_event_queue () const
Get an accessor to the running queue for state output purpose.
Definition at line 153 of file eventqueue.cpp.
{
     return this->event_queue;
 }
References event_queue.
Referenced by openage::event::Loop::execute_events().
reenqueue()
void openage::event::EventQueue::reenqueue (const std::shared_ptr< Event > & event)
The event was just removed, add it again. This is used for REPEAT events so that they are repeated.
Definition at line 148 of file eventqueue.cpp.
{
     this->event_queue.push(evnt);
 }
References event_queue, and openage::event::EventStore::push().
Referenced by openage::event::Loop::execute_events().
remove()
void openage::event::EventQueue::remove (const std::shared_ptr< Event > & evnt)
Remove the given event from the queue.
Todo:
remove the event from the other storages. this would require changes to dependent events and triggers. (to stop being a dependent event or allow being triggered)
Definition at line 129 of file eventqueue.cpp.
{
     this->event_queue.erase(evnt);
 }
References openage::event::EventStore::erase(), and event_queue.
Referenced by openage::event::Loop::update_changes().
swap_changesets()
void openage::event::EventQueue::swap_changesets ()
Swap the changes and future_changes.
Definition at line 189 of file eventqueue.cpp.
{
     std::swap(this->changes, this->future_changes);
 }
References changes, and future_changes.
Referenced by openage::event::Loop::reach_time().
take_event()
std::shared_ptr< Event > openage::event::EventQueue::take_event (const curve::time_t & max_time)
Obtain the next event from the event_queue that happens before <= max_time.
Definition at line 158 of file eventqueue.cpp.
{
     if (this->event_queue.size() == 0) {
         return nullptr;
     }
     std::shared_ptr<Event> event = this->event_queue.top();
     // check if this event should be processed
     // we take any event that happens <= max_time
     if (event->get_time() <= max_time) {
         // remove the event from the queue
         this->event_queue.pop();
         return event;
     }
     else {
         return nullptr;
     }
 }
References event_queue, openage::event::EventStore::pop(), openage::event::EventStore::size(), and openage::event::EventStore::top().
Referenced by openage::event::Loop::execute_events().
Member Data Documentation
changes
change_set* openage::event::EventQueue::changes private
Definition at line 128 of file eventqueue.h.
Referenced by add_change(), clear_changes(), get_changes(), and swap_changesets().
changeset_A
change_set openage::event::EventQueue::changeset_A private
Definition at line 132 of file eventqueue.h.
changeset_B
change_set openage::event::EventQueue::changeset_B private
Definition at line 133 of file eventqueue.h.
dependency_events
std::unordered_set<std::shared_ptr<Event> > openage::event::EventQueue::dependency_events private
Stores events that sleep until their dependency changes.
Definition at line 138 of file eventqueue.h.
Referenced by create_event().
dependency_immediately_events
std::unordered_set<std::shared_ptr<Event> > openage::event::EventQueue::dependency_immediately_events private
Stores events that sleep until their dependency changes, but they trigger instantly when their dependency changes.
Definition at line 144 of file eventqueue.h.
Referenced by create_event().
event_queue
EventStore openage::event::EventQueue::event_queue private
The universe timeline processes through this queue. Type::ONCE is only inserted into the queue.
Definition at line 155 of file eventqueue.h.
Referenced by create_event(), enqueue_change(), get_event_queue(), reenqueue(), remove(), and take_event().
future_changes
change_set* openage::event::EventQueue::future_changes private
Definition at line 129 of file eventqueue.h.
Referenced by add_change(), and swap_changesets().
trigger_events
std::unordered_set<std::shared_ptr<Event> > openage::event::EventQueue::trigger_events private
Events that fire only when triggered.
Definition at line 149 of file eventqueue.h.
Referenced by create_event().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/event/eventqueue.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/event/eventqueue.cpp