openage: openage::UnitContainer Class Reference
openage::UnitContainer Class Reference
the list of units that are currently in use will also give a view of the current game state for networking in later milestones
#include <unit_container.h>
Public Member Functions
UnitContainer ()
~UnitContainer ()
void reset ()
void set_terrain (std::shared_ptr< Terrain > &t)
sets terrain to initialise units on
std::shared_ptr< Terrain > get_terrain () const
returns the terrain which units are placed on
bool valid_id (id_t id) const
checks the id is valid
UnitReference get_unit (id_t id)
returns a reference to a unit
UnitReference new_unit ()
creates a new unit without initialising
UnitReference new_unit (UnitType &type, Player &owner, coord::phys3 position)
adds a new unit to the container and initialises using a unit type
UnitReference new_unit (UnitType &type, Player &owner, TerrainObject *other)
adds a new unit to the container and initialises using a unit type places outside an existing object using the player of that object
bool dispatch_command (id_t to_id, const Command &cmd)
give a command to a unit – unit creation and deletion should be done as commands
bool update_all (time_nsec_t lastframe_duration)
update dispatched by the game engine on each physics tick.
std::vector< openage::Unit * > all_units ()
gets a list of all units in the container
Private Attributes
id_t next_new_id
std::unordered_map< id_t, std::unique_ptr< Unit > > live_units
mapping unit ids to unit objects
std::weak_ptr< Terrain > terrain
Terrain for initialising new units.
Detailed Description
the list of units that are currently in use will also give a view of the current game state for networking in later milestones
Definition at line 75 of file unit_container.h.
Constructor & Destructor Documentation
UnitContainer()
openage::UnitContainer::UnitContainer ()
Definition at line 50 of file unit_container.cpp.
     :
     next_new_id{1} {}
~UnitContainer()
openage::UnitContainer::~UnitContainer ()
Definition at line 55 of file unit_container.cpp.
 {}
Member Function Documentation
all_units()
std::vector< Unit * > openage::UnitContainer::all_units ()
gets a list of all units in the container
Definition at line 164 of file unit_container.cpp.
{
     std::vector<Unit *> result;
     for (auto &u : this->live_units) {
         result.push_back(u.second.get());
     }
     return result;
 }
References live_units, and openage.testing.testing::result().
Referenced by openage::gameio::save().
dispatch_command()
bool openage::UnitContainer::dispatch_command (id_t to_id, const Command & cmd)
give a command to a unit – unit creation and deletion should be done as commands
get_terrain()
std::shared_ptr< Terrain > openage::UnitContainer::get_terrain () const
returns the terrain which units are placed on
Definition at line 66 of file unit_container.cpp.
{
     if (this->terrain.expired()) {
         throw Error{MSG(err) << "Terrain has expired"};
     }
     return this->terrain.lock();
 }
References openage::log::err(), MSG, and terrain.
Referenced by new_unit().
get_unit()
UnitReference openage::UnitContainer::get_unit (id_t id)
returns a reference to a unit
Definition at line 79 of file unit_container.cpp.
{
     if (this->valid_id(id)) {
         return UnitReference(this, id, this->live_units[id].get());
     }
     else {
         return UnitReference(this, id, nullptr);
     }
 }
References live_units, and valid_id().
new_unit() [1/3]
UnitReference openage::UnitContainer::new_unit ()
creates a new unit without initialising
Definition at line 88 of file unit_container.cpp.
{
     auto id = next_new_id;
     next_new_id += 1;
     this->live_units.emplace(id, std::make_unique<Unit>(this, id));
     return this->live_units[id]->get_ref();
 }
References live_units, and next_new_id.
Referenced by openage::Generator::add_units(), openage::gameio::load_unit(), and openage::ActionMode::on_game_control_set().
new_unit() [2/3]
UnitReference openage::UnitContainer::new_unit (UnitType & type, Player & owner, coord::phys3 position)
adds a new unit to the container and initialises using a unit type
Definition at line 96 of file unit_container.cpp.
{
     auto new_id = next_new_id;
     next_new_id += 1;
     auto newobj = std::make_unique<Unit>(this, new_id);
     // try placing unit at this location
     auto terrain_shared = this->get_terrain();
     auto placed = type.place(newobj.get(), terrain_shared, position);
     if (placed) {
         type.initialise(newobj.get(), owner);
         owner.active_unit_added(newobj.get()); // \todo change, move elsewhere
         auto id = newobj->id;
         this->live_units.emplace(id, std::move(newobj));
         return this->live_units[id]->get_ref();
     }
     return UnitReference(); // is not valid
 }
References get_terrain(), openage::UnitType::initialise(), live_units, openage::move, next_new_id, openage::owner, openage::UnitType::place(), and openage::placed.
new_unit() [3/3]
UnitReference openage::UnitContainer::new_unit (UnitType & type, Player & owner, TerrainObject * other)
adds a new unit to the container and initialises using a unit type places outside an existing object using the player of that object
Definition at line 118 of file unit_container.cpp.
{
     auto new_id = next_new_id;
     next_new_id += 1;
     auto newobj = std::make_unique<Unit>(this, new_id);
     // try placing unit
     TerrainObject *placed = type.place_beside(newobj.get(), other);
     if (placed) {
         type.initialise(newobj.get(), owner);
         owner.active_unit_added(newobj.get()); // \todo change, move elsewhere
         auto id = newobj->id;
         this->live_units.emplace(id, std::move(newobj));
         return this->live_units[id]->get_ref();
     }
     return UnitReference(); // is not valid
 }
References openage::UnitType::initialise(), live_units, openage::move, next_new_id, openage::owner, openage::UnitType::place_beside(), and openage::placed.
reset()
void openage::UnitContainer::reset ()
Definition at line 58 of file unit_container.cpp.
{
     this->live_units.clear();
 }
References live_units.
Referenced by openage::gameio::load().
set_terrain()
void openage::UnitContainer::set_terrain (std::shared_ptr< Terrain > & t)
sets terrain to initialise units on
Definition at line 62 of file unit_container.cpp.
{
     this->terrain = t;
 }
References terrain.
update_all()
bool openage::UnitContainer::update_all (time_nsec_t lastframe_duration)
update dispatched by the game engine on each physics tick.
this will update all game objects.
Definition at line 143 of file unit_container.cpp.
{
     // update everything and find objects with no actions
     std::vector<id_t> to_remove;
     for (auto &obj : this->live_units) {
         obj.second->update(lastframe_duration);
         if (not obj.second->has_action()) {
             to_remove.push_back(obj.first);
         }
     }
     // cleanup and removal of objects
     for (auto &obj : to_remove) {
         // unique pointer triggers cleanup
         this->live_units.erase(obj);
     }
     return true;
 }
References live_units.
Referenced by openage::GameMain::update().
valid_id()
bool openage::UnitContainer::valid_id (id_t id) const
checks the id is valid
Definition at line 74 of file unit_container.cpp.
{
     return (this->live_units.count(id) > 0);
 }
References live_units.
Referenced by get_unit().
Member Data Documentation
live_units
std::unordered_map<id_t, std::unique_ptr<Unit> > openage::UnitContainer::live_units private
mapping unit ids to unit objects
Definition at line 140 of file unit_container.h.
Referenced by all_units(), get_unit(), new_unit(), reset(), update_all(), and valid_id().
next_new_id
id_t openage::UnitContainer::next_new_id private
Definition at line 135 of file unit_container.h.
Referenced by new_unit().
terrain
std::weak_ptr<Terrain> openage::UnitContainer::terrain private
Terrain for initialising new units.
Definition at line 145 of file unit_container.h.
Referenced by get_terrain(), and set_terrain().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/unit_container.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/unit_container.cpp