openage: openage::HealAction Class Reference
openage::HealAction Class Reference
heals another unit
#include <action.h>
Public Member Functions
HealAction (Unit *e, UnitReference tar)
virtual ~HealAction ()
void update_in_range (unsigned int time, Unit *target_unit) override
Control units action when in range of the target.
void on_completion_in_range (int) override
bool completed_in_range (Unit *) const override
std::string name () const override
debug string to identify action types
Public Member Functions inherited from openage::TargetAction
TargetAction (Unit *e, graphic_type gt, UnitReference r, coord::phys_t action_rad)
action_rad is how close a unit must come to another unit to be considered to touch the other, for example in gathering resource and melee attack
TargetAction (Unit *e, graphic_type gt, UnitReference r)
this constructor uses the default action radius formula which will bring the object as near to the target as the pathing grid will allow.
virtual ~TargetAction ()
void update (unsigned int time) override
each action has its own update functionality which gets called when this is the active action
void on_completion () override
action to perform when popped from a units action stack
bool completed () const override
gets called for all actions on stack each update cycle
bool allow_interupt () const override
checks if the action can be interrupted, allowing it to be popped if the user specifies a new action, if false the action must reach a completed state before removal eg dead action must be completed and cannot be discarded
bool allow_control () const override
control whether stack can discard the action automatically and should the stack be modifiable when this action is on top
coord::phys_t distance_to_target ()
Unit * update_distance ()
UnitReference get_target () const
int get_target_type_id () const
void set_target (UnitReference new_target)
changes target, ending action when new target is invalid
Public Member Functions inherited from openage::UnitAction
UnitAction (Unit *u, graphic_type initial_gt)
Require unit to be updated and an initial graphic type.
virtual ~UnitAction ()
graphic_type type () const
type of graphic this action should use
float current_frame () const
frame number to use on the current graphic
virtual const graphic_set & current_graphics () const
determines which graphic should be used for drawing this unit finds the default graphic using the units type, used by most actions
void draw_debug (const Engine &engine)
void face_towards (const coord::phys3 pos)
common functions for actions
bool damage_unit (Unit &target)
Damage a unit, returns true if the unit was killed in the process.
void move_to (Unit &target, bool use_range=true)
Private Member Functions
void heal (Unit &target)
use heal action
Private Attributes
IntervalTimer timer
Additional Inherited Members
Static Public Member Functions inherited from openage::UnitAction
static coord::phys_t adjacent_range (Unit *u)
a small distance to which units are considered touching when within this distance
static coord::phys_t get_attack_range (Unit *u)
looks at an ranged attributes on the unit otherwise returns same as adjacent_range()
static coord::phys_t get_heal_range (Unit *u)
looks at heal attribute on the unit otherwise returns same as adjacent_range()
Static Public Attributes inherited from openage::UnitAction
static bool show_debug = false
produce debug info such as visualising paths
Protected Attributes inherited from openage::UnitAction
Unit * entity
the entity being updated
graphic_type graphic
common graphic controls
float frame
float frame_rate
std::function< void(const Engine &)> debug_draw_action
additional drawing for debug purposes
Detailed Description
heals another unit
Definition at line 590 of file action.h.
Constructor & Destructor Documentation
HealAction()
openage::HealAction::HealAction (Unit * e, UnitReference tar)
Definition at line 1252 of file action.cpp.
     :
     TargetAction{e, graphic_type::heal, tar, get_attack_range(e)},
     timer{this->entity->get_attribute<attr_type::heal>().rate} {
 }
References openage::UnitAction::get_attack_range(), and openage::heal.
~HealAction()
openage::HealAction::~HealAction () virtual
Definition at line 1259 of file action.cpp.
 {}
Member Function Documentation
completed_in_range()
bool openage::HealAction::completed_in_range (Unit * target_ptr) const override virtual
Implements openage::TargetAction.
Definition at line 1270 of file action.cpp.
{
     auto &hp = target_ptr->get_attribute<attr_type::hitpoints>();
     auto &dm = target_ptr->get_attribute<attr_type::damaged>();
     return dm.hp >= hp.hp; // is unit at full hitpoints?
 }
References openage::damaged, openage::Unit::get_attribute(), and openage::hitpoints.
heal()
void openage::HealAction::heal (Unit & target) private
use heal action
Definition at line 1276 of file action.cpp.
{
     auto &heal = this->entity->get_attribute<attr_type::heal>();
     // \todo move to seperate function heal_unit (like damage_unit)?
     // heal object
     if (target.has_attribute(attr_type::hitpoints) && target.has_attribute(attr_type::damaged)) {
         auto &hp = target.get_attribute<attr_type::hitpoints>();
         auto &dm = target.get_attribute<attr_type::damaged>();
         if ((dm.hp + heal.life) < hp.hp) {
             dm.hp += heal.life;
         }
         else {
             dm.hp = hp.hp;
         }
     }
 }
References openage::damaged, openage::UnitAction::entity, openage::Unit::get_attribute(), openage::Unit::has_attribute(), openage::heal, openage::hitpoints, and openage::TargetAction::target.
Referenced by update_in_range().
name()
std::string openage::HealAction::name () const inline override virtual
debug string to identify action types
Implements openage::TargetAction.
Definition at line 598 of file action.h.
 { return "heal"; }
Referenced by openage.util.fslike.path.Path::stem(), openage.util.fslike.path.Path::suffix(), and openage.util.fslike.path.Path::suffixes().
on_completion_in_range()
void openage::HealAction::on_completion_in_range (int) inline override virtual
Implements openage::TargetAction.
Definition at line 596 of file action.h.
 {}
update_in_range()
void openage::HealAction::update_in_range (unsigned int , Unit *) override virtual
Control units action when in range of the target.
Implements openage::TargetAction.
Definition at line 1261 of file action.cpp.
{
     if (this->timer.update(time)) {
         this->heal(*target_ptr);
     }
     // inc frame
     this->frame += time * this->current_graphics().at(graphic)->frame_count * 1.0f / this->timer.get_interval();
 }
References openage::UnitAction::current_graphics(), openage::UnitAction::frame, openage::IntervalTimer::get_interval(), openage::UnitAction::graphic, heal(), timer, and openage::IntervalTimer::update().
Member Data Documentation
timer
IntervalTimer openage::HealAction::timer private
Definition at line 602 of file action.h.
Referenced by update_in_range().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/action.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/unit/action.cpp