openage: openage::util::filelike::Native Class Reference
openage::util::filelike::Native Class Reference
File-like class that uses native stdlib functions to access data.
#include <native.h>
Public Member Functions
Native (const std::string &path, mode_t mode=mode_t::R)
virtual ~Native ()
std::string read (ssize_t max) override
size_t read_to (void *buf, ssize_t max) override
bool readable () override
void write (const std::string &data) override
bool writable () override
void seek (ssize_t offset, seek_t how=seek_t::SET) override
bool seekable () override
size_t tell () override
void close () override
void flush () override
ssize_t get_size () override
std::ostream & repr (std::ostream &) override
string representation of the filelike
Public Member Functions inherited from openage::util::filelike::FileLike
FileLike ()
virtual ~FileLike ()=default
virtual bool is_python_native () const noexcept
Protected Attributes
std::string path
mode_t mode
std::fstream file
Additional Inherited Members
Public Types inherited from openage::util::filelike::FileLike
enum seek_t : int { seek_t::SET = 0, seek_t::CUR = 1, seek_t::END = 2 }
Seek reference point.
enum mode_t : int {
mode_t::R = 0, mode_t::W = 1, mode_t::RW = 2, mode_t::A = 3,
mode_t::AR = 4
}
File access mode.
Detailed Description
File-like class that uses native stdlib functions to access data.
Definition at line 20 of file native.h.
Constructor & Destructor Documentation
Native()
openage::util::filelike::Native::Native (const std::string & path, mode_t mode = mode_t::R)
Definition at line 14 of file native.cpp.
     :
     path{path},
     mode{mode} {
     std::ios_base::openmode open_mode;
     switch (this->mode) {
     case mode_t::R:
         open_mode = std::ios_base::in;
         break;
     case mode_t::W:
         open_mode = std::ios_base::out;
         break;
     case mode_t::RW:
         open_mode = std::ios_base::in | std::ios_base::out;
         break;
     case mode_t::A:
         open_mode = std::ios_base::out | std::ios_base::ate;
         break;
     case mode_t::AR:
         open_mode = std::ios_base::in | std::ios_base::out | std::ios_base::ate;
         break;
     default:
         throw Error{ERR << "unknown open mode"};
     }
     // Open in binary mode to avoid stupid behaviour on Windows
     open_mode |= std::ios_base::binary;
     this->file.open(this->path, open_mode);
     if (not this->file.is_open()) {
         throw Error{ERR << "file not found: " << path};
     }
 }
References path.
~Native()
openage::util::filelike::Native::~Native () virtual
Definition at line 52 of file native.cpp.
 {}
Member Function Documentation
close()
void openage::util::filelike::Native::close () override virtual
Implements openage::util::filelike::FileLike.
Definition at line 139 of file native.cpp.
                    {
     this->file.close();
 }
References file.
Referenced by openage.util.filelike.abstract.FileLikeObject::__exit__(), and openage.convert.slp_converter_pool.SLPConverterPool::__exit__().
flush()
void openage::util::filelike::Native::flush () override virtual
Implements openage::util::filelike::FileLike.
Definition at line 144 of file native.cpp.
                    {
     this->file.flush();
 }
References file.
get_size()
ssize_t openage::util::filelike::Native::get_size () override virtual
Implements openage::util::filelike::FileLike.
Definition at line 149 of file native.cpp.
{
     // remember where we were
     size_t pos = this->file.tellg();
     // go to the end
     this->file.seekg(0, std::ios::end);
     ssize_t size = static_cast<ssize_t>(this->file.tellg());
     // return to position
     this->file.seekg(pos, std::ios::beg);
     return size;
 }
References file.
Referenced by openage.util.filelike.abstract.FileLikeObject::seek_helper().
read()
std::string openage::util::filelike::Native::read (ssize_t max) override virtual
Implements openage::util::filelike::FileLike.
Definition at line 55 of file native.cpp.
{
     // read whole file:
     if (max < 0) {
         std::string ret;
         // get remaining size and prepare the string size
         // to avoid resizing
         size_t pos = this->file.tellg();
         this->file.seekg(0, std::ios::end);
         ret.reserve(static_cast<size_t>(this->file.tellg()) - pos);
         this->file.seekg(pos, std::ios::beg);
         ret.assign(std::istreambuf_iterator<char>(this->file),
                    std::istreambuf_iterator<char>());
         return ret;
     }
     // read `max` bytes
     else {
         // create string with required size
         std::string ret;
         ret.resize(max);
         // and read the data
         this->file.read(&ret[0], max);
         return ret;
     }
 }
References file, and openage::console::tests::max().
Referenced by openage.convert.dataformat.exportable.Exportable::read(), and openage.convert.peresource.StringLiteral::readall().
read_to()
size_t openage::util::filelike::Native::read_to (void * buf, ssize_t max) override virtual
Implements openage::util::filelike::FileLike.
Definition at line 85 of file native.cpp.
{
     this->file.readsome(reinterpret_cast<std::fstream::char_type *>(buf), max);
     return this->file.gcount();
 }
References file, and openage::console::tests::max().
readable()
bool openage::util::filelike::Native::readable () override virtual
Implements openage::util::filelike::FileLike.
Definition at line 91 of file native.cpp.
                       {
     return (this->mode == mode_t::R or
             this->mode == mode_t::RW);
 }
References mode, openage::util::filelike::FileLike::R, and openage::util::filelike::FileLike::RW.
repr()
std::ostream & openage::util::filelike::Native::repr (std::ostream &) override virtual
string representation of the filelike
Implements openage::util::filelike::FileLike.
Definition at line 164 of file native.cpp.
{
     stream << "Native(" << this->path  << ")";
     return stream;
 }
References path.
seek()
void openage::util::filelike::Native::seek (ssize_t offset, seek_t how = seek_t::SET) override virtual
Implements openage::util::filelike::FileLike.
Definition at line 108 of file native.cpp.
{
     std::ios::seekdir where;
     switch (how) {
     case seek_t::SET:
         where = std::ios::beg;
         break;
     case seek_t::CUR:
         where = std::ios::cur;
         break;
     case seek_t::END:
         where = std::ios::end;
         break;
     default:
         throw Error{ERR << "invalid seek mode"};
     }
     this->file.seekg(offset, where);
 }
References openage::util::filelike::FileLike::CUR, openage::util::filelike::FileLike::END, ERR, file, and openage::util::filelike::FileLike::SET.
seekable()
bool openage::util::filelike::Native::seekable () override virtual
Implements openage::util::filelike::FileLike.
Definition at line 129 of file native.cpp.
                       {
     return true;
 }
tell()
size_t openage::util::filelike::Native::tell () override virtual
Implements openage::util::filelike::FileLike.
Definition at line 134 of file native.cpp.
                     {
     return this->file.tellg();
 }
References file.
Referenced by openage.util.filelike.abstract.FileLikeObject::seek_helper().
writable()
bool openage::util::filelike::Native::writable () override virtual
Implements openage::util::filelike::FileLike.
Definition at line 102 of file native.cpp.
                       {
     return (this->mode == mode_t::W or
             this->mode == mode_t::RW);
 }
References mode, openage::util::filelike::FileLike::RW, and openage::util::filelike::FileLike::W.
Referenced by openage.util.fslike.wrapper.Wrapper::resolve_w(), and openage.util.fslike.abstract.FSLikeObject::resolve_w().
write()
void openage::util::filelike::Native::write (const std::string & data) override virtual
Implements openage::util::filelike::FileLike.
Definition at line 97 of file native.cpp.
{
     this->file.write(data.c_str(), data.size());
 }
References file.
Member Data Documentation
file
std::fstream openage::util::filelike::Native::file protected
Definition at line 48 of file native.h.
Referenced by close(), flush(), get_size(), read(), read_to(), seek(), tell(), and write().
mode
mode_t openage::util::filelike::Native::mode protected
Definition at line 46 of file native.h.
Referenced by readable(), and writable().
path
std::string openage::util::filelike::Native::path protected
Definition at line 44 of file native.h.
Referenced by openage.util.fslike.directory.Directory::__repr__(), openage.util.fslike.directory.CaseIgnoringDirectory::__repr__(), openage.util.fslike.directory.CaseIgnoringDirectory::actual_name(), Native(), repr(), openage.util.fslike.directory.Directory::resolve(), openage.util.fslike.directory.CaseIgnoringDirectory::resolve(), and openage.util.fslike.directory.Directory::writable().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/filelike/native.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/util/filelike/native.cpp