openage: openage::cvar::CVarManager Class Reference
openage::cvar::CVarManager Class Reference
#include <cvar.h>
Public Member Functions
CVarManager (const util::Path &path)
bool create (const std::string &name, const std::pair< get_func, set_func > &accessors)
std::string get (const std::string &name) const
void set (const std::string &name, const std::string &value) const
void load_config (const util::Path &path)
void load_all ()
Private Attributes
std::unordered_map< std::string, std::pair< get_func, set_func > > store
util::Path path
Detailed Description
Configuration manager.
Stores key-value pairs of config data. Actually it doesn't store data, instead functions that perform/fetch the configuration at the appropriate place.
pxd:
cppclass CVarManager: string get(string name) except + void set(string name, string value) except + void load_config(Path path) except +
Definition at line 42 of file cvar.h.
Constructor & Destructor Documentation
CVarManager()
openage::cvar::CVarManager::CVarManager (const util::Path & path)
Definition at line 11 of file cvar.cpp.
     :
     path{path} {}
References path.
Member Function Documentation
create()
bool openage::cvar::CVarManager::create (const std::string & name, const std::pair< get_func, set_func > & accessors)
Creates a configuration entry
Returns
if the entry name was successful. It won't be if the name was used before.
Definition at line 16 of file cvar.cpp.
{
     auto it = this->store.find(name);
     if (it == this->store.end()) {
         this->store[name] = accessors;
         return true;
     }
     return false;
 }
References store.
Referenced by openage::input::ActionManager::create().
get()
std::string openage::cvar::CVarManager::get (const std::string & name) const
Gets the value of a config entry. Internally calls the stored get function.
Definition at line 27 of file cvar.cpp.
{
     auto it = this->store.find(name);
     if (it != this->store.end()) {
         return it->second.first();
     }
     return "";
 }
References store.
Referenced by openage::console::Console::interpret().
load_all()
void openage::cvar::CVarManager::load_all ()
Perform the load of the default config files.
Definition at line 49 of file cvar.cpp.
{
     log::log(INFO << "loading configuration files...");
     this->load_config(this->path["keybinds.oac"]);
 }
References INFO, load_config(), openage::log::log(), and path.
load_config()
void openage::cvar::CVarManager::load_config (const util::Path & path)
Performs the loading of a configuration file via the Python implementation.
Definition at line 44 of file cvar.cpp.
{
     pyx_load_config_file.call(this, path);
 }
References path, and openage::cvar::pyx_load_config_file.
Referenced by load_all().
set()
void openage::cvar::CVarManager::set (const std::string & name, const std::string & value) const
Sets the config entry value.
Definition at line 36 of file cvar.cpp.
{
     auto it = store.find(name);
     if (it != store.end()) {
         it->second.second(value);
     }
 }
References store.
Referenced by openage::console::Console::interpret().
Member Data Documentation
path
util::Path openage::cvar::CVarManager::path private
Magic path that stores config files. Auto-redirects to the default and write paths in the home folder. It is set up in openage/cvar/location.py and openage/game/main.py
Definition at line 91 of file cvar.h.
Referenced by openage.util.fslike.directory.Directory::__repr__(), openage.util.fslike.directory.CaseIgnoringDirectory::__repr__(), openage.util.fslike.directory.CaseIgnoringDirectory::actual_name(), CVarManager(), load_all(), load_config(), openage.util.fslike.directory.Directory::resolve(), openage.util.fslike.directory.CaseIgnoringDirectory::resolve(), and openage.util.fslike.directory.Directory::writable().
store
std::unordered_map<std::string, std::pair<get_func, set_func> > openage::cvar::CVarManager::store private
Store the key-value pair of config options. The clue is to store the "what does the config do", not the actual value. That way the system is universal.
Definition at line 84 of file cvar.h.
Referenced by create(), get(), and set().
The documentation for this class was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/cvar/cvar.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/cvar/cvar.cpp