openage: openage::util::constexpr_ Namespace Reference
openage::util::constexpr_ Namespace Reference
Classes
struct truncated_string_literal
Functions
constexpr bool streq (const char *a, const char *b)
constexpr size_t strlen (const char *str)
constexpr truncated_string_literal get_prefix (const char *str, const char *suffix)
constexpr truncated_string_literal create_truncated_string_literal (const char *str)
constexpr bool has_prefix (const char *str, const truncated_string_literal prefix)
constexpr const char * strip_prefix (const char *str, const truncated_string_literal prefix)
constexpr const char * strip_prefix (const char *str, const char *prefix)
Function Documentation
create_truncated_string_literal()
constexpr truncated_string_literal openage::util::constexpr_::create_truncated_string_literal (const char * str)
Creates a truncated_string_literal from a regular string literal.
Definition at line 75 of file constexpr.h.
{
     return truncated_string_literal{str, strlen(str)};
 }
References openage::py::str(), and strlen().
Referenced by strip_prefix().
get_prefix()
constexpr truncated_string_literal openage::util::constexpr_::get_prefix (const char * str, const char * suffix)
Truncates a suffix from a string literal.
Raises 'false' if str doesn't end in the given suffix.
Definition at line 59 of file constexpr.h.
{
     if (strlen(str) < strlen(suffix)) {
         // suffix is longer than str
         throw false;
     } else if (streq(str + (strlen(str) - strlen(suffix)), suffix)) {
         // str ends with suffix
         return truncated_string_literal{str, strlen(str) - strlen(suffix)};
     } else {
         throw false;
     }
 }
References openage::py::str(), streq(), and strlen().
has_prefix()
constexpr bool openage::util::constexpr_::has_prefix (const char * str, const truncated_string_literal prefix)
Tests whether a string literal starts with the given prefix.
Definition at line 82 of file constexpr.h.
{
     for (size_t pos = 0; pos < prefix.length; ++pos) {
         if (str[pos] != prefix.literal[pos]) {
             return false;
         }
     }
     return true;
 }
References openage::util::constexpr_::truncated_string_literal::length, openage::util::constexpr_::truncated_string_literal::literal, and openage::py::str().
Referenced by strip_prefix().
streq()
constexpr bool openage::util::constexpr_::streq (const char * a, const char * b)
Returns true IFF the string literals have equal content.
Definition at line 17 of file constexpr.h.
{
     for (;*a == *b; ++a, ++b) {
         if (*a == '\0') {
             return true;
         }
     }
     return false;
 }
Referenced by get_prefix().
strip_prefix() [1/2]
constexpr const char* openage::util::constexpr_::strip_prefix (const char * str, const truncated_string_literal prefix)
Strips a prefix from a given string literal.
If the string literal doesn't have that prefix, returns the string literal itself.
Definition at line 97 of file constexpr.h.
{
     if (has_prefix(str, prefix)) {
         return str + prefix.length;
     } else {
         return str;
     }
 }
References has_prefix(), openage::util::constexpr_::truncated_string_literal::length, and openage::py::str().
Referenced by strip_prefix().
strip_prefix() [2/2]
constexpr const char* openage::util::constexpr_::strip_prefix (const char * str, const char * prefix)
Strips a prefix, given as const char *, from a given string literal.
If the string literal doesn't have that prefix, returns the string literal itself.
Definition at line 111 of file constexpr.h.
{
     return strip_prefix(str, create_truncated_string_literal(prefix));
 }
References create_truncated_string_literal(), openage::py::str(), and strip_prefix().
strlen()
constexpr size_t openage::util::constexpr_::strlen (const char * str)
Returns the length of the string literal, excluding the terminating NULL byte.
Definition at line 30 of file constexpr.h.
{
     for (size_t len = 0;; ++len) {
         if (str[len] == '\0') {
             return len;
         }
     }
 }
References openage::py::str().
Referenced by openage::util::copy_string(), create_truncated_string_literal(), get_prefix(), openage::util::FD::puts(), openage::util::rstrip(), openage::error::sigsegv_handler(), and openage::util::utf8_last_char_size().