openage: openage.codegen.cpp_testlist Namespace Reference
openage.codegen.cpp_testlist Namespace Reference
Classes
class Namespace
Represents a C++ namespace, which contains other namespaces and functions.
Functions
def generate_testlist (projectdir)
Generates the test/demo method symbol lookup file from tests_cpp.
Function Documentation
generate_testlist()
def openage.codegen.cpp_testlist.generate_testlist (projectdir)
Generates the test/demo method symbol lookup file from tests_cpp.
projectdir is a util.fslike.path.Path.
Definition at line 70 of file cpp_testlist.py.
     from ..testing.list_processor import list_targets_cpp
     for testname, _, _, _ in list_targets_cpp():
         root_namespace.add_functionname(testname.split('::'))
     func_prototypes = list(root_namespace.gen_prototypes())
     method_mappings = [
         "{\"%s\", ::%s}" % (functionname, functionname)
         for functionname in root_namespace.get_functionnames()]
     tmpl_path = projectdir.joinpath("libopenage/testing/testlist.cpp.template")
     with tmpl_path.open() as tmpl:
         content = tmpl.read()
     content = content.replace('FUNCTION_PROTOTYPES', "".join(func_prototypes))
     content = content.replace('METHOD_MAPPINGS', ",\n\t".join(method_mappings))
     gen_path = projectdir.joinpath("libopenage/testing/testlist.gen.cpp")
     with gen_path.open("w") as gen:
         gen.write(content)
References openage::py.list(), and openage.testing.list_processor.list_targets_cpp().
Referenced by openage.codegen.listing.generate_all().