openage: openage.cppinterface.setup Namespace Reference
openage.cppinterface.setup Namespace Reference
Functions
def setup (args)
After a call to setup(), the C++ interface is in a usable state.
Function Documentation
setup()
def openage.cppinterface.setup.setup (args)
After a call to setup(), the C++ interface is in a usable state.
setup() automatically checks whether there are any remaining un-initialized PyFunc objects, and raises an Exception if so.
Must be invoked before any functions from libopenage are invoked. Runs only once; any subsequent invocations are a no-op, so don't hesitate to call this method whenever likely.
Do not invoke from a .pyx extension module that itself provides a setup method (circular imports)!
Definition at line 30 of file setup.py.
     # this is where calls to the setup methods of all other modules belong.
     from .exctranslate import setup as exctranslate_setup
     exctranslate_setup(args)
     from .exctranslate_tests import setup as exctranslate_tests_setup
     exctranslate_tests_setup()
     from .pyobject import setup as pyobject_setup
     pyobject_setup()
     from ..util.filelike.cpp import setup as filelike_setup
     filelike_setup()
     from ..util.fslike.cpp import setup as fslike_setup
     fslike_setup()
     from ..cvar.cvar import setup as cvar_setup
     cvar_setup()
     # verify that everything has been properly initialized.
     from .setup_checker import check
     check()
     enable_log_translation()
     dbg("C++ <-> Python interface has been initialized")
References openage::pyinterface.check(), and openage::log.dbg().
Referenced by openage.convert.main.main(), and openage.testing.main.process_args().