openage: openage::os Namespace Reference
openage::os Namespace Reference
Functions
std::string read_symlink (const char *path)
std::string self_exec_filename ()
int execute_file (const char *path, bool background)
Detailed Description
similar in its goals to Python's os module
Function Documentation
execute_file()
int openage::os::execute_file (const char * path, bool background = true)
tries to xdg-open the file
Definition at line 102 of file os.cpp.
{
 #ifdef _WIN32
     // \todo some sort of shell-open, not yet implemented
     return -1; // failure
 #else
         std::string runner = "";
 #ifdef __APPLE__
             runner = subprocess::which("open");
 #else
             runner = subprocess::which("xdg-open");
             // fallback
             if (runner.size() == 0) {
                 runner = subprocess::which("gnome-open");
             }
 #endif
         if (runner.size() == 0) {
             log::log(MSG(err) << "could not locate file-opener");
             return -1;
         }
         return subprocess::call({runner.c_str(), path, nullptr}, not background);
 #endif
 }
References openage::subprocess::call(), openage::log::err(), openage::log::log(), MSG, and openage::subprocess::which().
Referenced by openage::util::ExternalProfiler::show_results().
read_symlink()
std::string openage::os::read_symlink (const char * path)
reads a symlink
Definition at line 28 of file os.cpp.
{
 #ifdef _WIN32
     // \todo not yet implemented
     return "";
 #else
     size_t bufsize = 1024;
     while (true) {
         bufsize *= 2;
         std::unique_ptr<char[]> buf{new char[bufsize]};
         ssize_t len = readlink(path, buf.get(), bufsize);
         if (len < 0) {
             log::log(MSG(err) << "could not read link " << path);
             return "";
         }
         if ((size_t) len >= bufsize) {
             continue;
         }
         buf[len] = '\0';
         return std::string{buf.get()};
     }
 #endif
 }
References openage::log::err(), openage::log::log(), and MSG.
Referenced by self_exec_filename().
self_exec_filename()
std::string openage::os::self_exec_filename ()
returns openage's executable name
Definition at line 57 of file os.cpp.
{
     // nice overview of crossplatform methods:
     // http://stackoverflow.com/questions/5919996
 #ifdef __linux
     return read_symlink("/proc/self/exe");
 #elif __APPLE__
     uint32_t bufsize = 1024;
     while (true) {
         std::unique_ptr<char[]> buf{new char[bufsize]};
         if (_NSGetExecutablePath(buf.get(), &bufsize) < 0) {
             continue;
         }
         return std::string{buf.get()};
     }
 #elif __FreeBSD__
     size_t bufsize = 1024;
     int mib[4] = {
         CTL_KERN,
         KERN_PROC,
         KERN_PROC_PATHNAME,
         -1
     };
     while (true) {
         std::unique_ptr<char[]> buf{new char[bufsize]};
         if (sysctl(mib, 4, buf.get(), &bufsize, nullptr, 0) < 0) {
             continue;
         }
         return std::string{buf.get()};
     }
 #elif _WIN32
     // \todo not yet implemented
     return std::string("openage.exe"); // FIXME: wild guess though
 #else
     static_assert(false, "subprocess::self_filename is not yet implemented for... whatever platform you're using right now.");
 #endif
 }
References read_symlink().
Referenced by openage::util::ExternalProfiler::show_results().