openage: openage::timing Namespace Reference
openage::timing Namespace Reference
Functions
time_nsec_t get_real_time ()
time_nsec_t get_monotonic_time ()
Function Documentation
get_monotonic_time()
time_nsec_t openage::timing::get_monotonic_time ()
returns a monotonically-increasing time that returns the number of nanoseconds since an unspecified event.
not influenced by system time changes.
Definition at line 20 of file timing.cpp.
{
     std::chrono::steady_clock::time_point t;
     t = std::chrono::steady_clock::now();
     auto ns = std::chrono::duration_cast<std::chrono::nanoseconds>(t.time_since_epoch()).count();
     return static_cast<time_nsec_t>(ns);
 }
Referenced by openage::util::Timer::getandresetval(), openage::util::Timer::getval(), openage::util::Timer::reset(), openage::util::Timer::start(), openage::util::Timer::stop(), and openage::console::draw::to_opengl().
get_real_time()
time_nsec_t openage::timing::get_real_time ()
returns the number of nanoseconds since the UNIX epoch.
Definition at line 13 of file timing.cpp.
{
     std::chrono::system_clock::time_point t;
     t = std::chrono::system_clock::now();
     auto ns = std::chrono::duration_cast<std::chrono::nanoseconds>(t.time_since_epoch()).count();
     return static_cast<time_nsec_t>(ns);
 }
Referenced by openage::log::message::init(), and openage::rng::time_seed().