openage: openage.codegen.listing Namespace Reference
openage.codegen.listing Namespace Reference
Functions
def generate_all (projectdir)
Contains the listing of all code generator invocations.
Function Documentation
generate_all()
def openage.codegen.listing.generate_all (projectdir)
Contains the listing of all code generator invocations.
Generates all source files in targetdir.
Definition at line 13 of file listing.py.
     generate_gamespec_structs(projectdir)
     from .cpp_testlist import generate_testlist
     generate_testlist(projectdir)
     from .coord import generate_coord_basetypes
     generate_coord_basetypes(projectdir)
References openage.codegen.coord.generate_coord_basetypes(), openage.codegen.gamespec_structs.generate_gamespec_structs(), and openage.codegen.cpp_testlist.generate_testlist().
Referenced by openage.codegen.codegen.codegen().