openage: openage::audio Namespace Reference
openage::audio Namespace Reference
Classes
struct audio_chunk_t
class AudioManager
struct chunk_info_t
class DynamicLoader
class DynamicResource
class Error
class InMemoryLoader
class InMemoryResource
struct opus_file_t
class OpusDynamicLoader
class OpusInMemoryLoader
class Resource
struct resource_def
class SDLDeviceLock
class Sound
class SoundImpl
Typedefs
using pcm_data_t = std::vector< int16_t >
using pcm_chunk_t = std::vector< int16_t >
Enumerations
enum category_t { category_t::GAME, category_t::INTERFACE, category_t::MUSIC, category_t::TAUNT }
enum format_t { format_t::OPUS, format_t::WAV, format_t::MP3, format_t::FLAC }
enum loader_policy_t { loader_policy_t::IN_MEMORY, loader_policy_t::DYNAMIC }
Functions
const char * category_t_to_str (category_t val)
std::ostream & operator<< (std::ostream &os, const category_t val)
const char * format_t_to_str (format_t val)
std::ostream & operator<< (std::ostream &os, const format_t val)
const char * loader_policy_t_to_str (loader_policy_t val)
std::ostream & operator<< (std::ostream &os, const loader_policy_t val)
opus_file_t open_opus_file (const util::Path &path)
Variables
static auto opus_deleter
static op_read_func opus_reader
static op_seek_func opus_seeker
static op_tell_func opus_teller
static OpusFileCallbacks opus_access_funcs
Typedef Documentation
pcm_chunk_t
using openage::audio::pcm_chunk_t = typedef std::vector<int16_t>
pcm_chunk_t is a vector consisting of signed 16 bit integer samples. It is used to represent a chunk of a audio resource's buffer with a fixed size.
Definition at line 35 of file types.h.
pcm_data_t
using openage::audio::pcm_data_t = typedef std::vector<int16_t>
pcm_data_t is a vector consisting of signed 16 bit integer samples. It is used to represent one complete audio resource's buffer.
Definition at line 29 of file types.h.
Enumeration Type Documentation
category_t
enum openage::audio::category_t strong
Enumerator
GAME
INTERFACE
MUSIC
TAUNT
Definition at line 11 of file category.h.
                       {
     GAME,
     INTERFACE,
     MUSIC,
     TAUNT
 };
format_t
enum openage::audio::format_t strong
Enumerator
OPUS
WAV
MP3
FLAC
Definition at line 11 of file format.h.
                     {
     OPUS,
     WAV,
     MP3,
     FLAC
 };
loader_policy_t
enum openage::audio::loader_policy_t strong
Enumerator
IN_MEMORY
DYNAMIC
Definition at line 12 of file loader_policy.h.
{
     IN_MEMORY,
     DYNAMIC
 };
Function Documentation
category_t_to_str()
const char * openage::audio::category_t_to_str (category_t val)
Definition at line 13 of file category.cpp.
{
     switch (val) {
     case category_t::GAME:      return "GAME";
     case category_t::INTERFACE: return "INTERFACE";
     case category_t::MUSIC:     return "MUSIC";
     case category_t::TAUNT:     return "TAUNT";
     default:                    return "unknown";
     }
 }
References GAME, INTERFACE, MUSIC, TAUNT, and val.
Referenced by operator<<().
format_t_to_str()
const char * openage::audio::format_t_to_str (format_t val)
Definition at line 11 of file format.cpp.
{
     switch (val) {
     case format_t::OPUS: return "OPUS";
     case format_t::WAV:  return "WAV";
     case format_t::MP3:  return "MP3";
     case format_t::FLAC: return "FLAC";
     default:             return "unknown";
     }
 }
References FLAC, MP3, OPUS, val, and WAV.
Referenced by operator<<().
loader_policy_t_to_str()
const char * openage::audio::loader_policy_t_to_str (loader_policy_t val)
Definition at line 11 of file loader_policy.cpp.
{
     switch (val) {
     case loader_policy_t::IN_MEMORY: return "IN_MEMORY";
     case loader_policy_t::DYNAMIC:   return "DYNAMIC";
     default:                         return "unknown";
     }
 }
References DYNAMIC, IN_MEMORY, and val.
Referenced by operator<<().
open_opus_file()
opus_file_t openage::audio::open_opus_file (const util::Path & path)
Opens a opus file. Its location is specified by the path stored in the DynamicLoader.
Definition at line 57 of file opus_loading.cpp.
{
     if (not path.is_file()) {
         throw audio::Error{
             ERR << "Audio file not found: " << path
         };
     }
     opus_file_t op_file;
     int op_err = 0;
     // check if the file can be opened directly
     auto native_path = path.resolve_native_path();
     if (native_path.size() > 0) {
         op_file.handle = {
             op_open_file(native_path.c_str(), &op_err),
             opus_deleter
         };
     }
     else {
         // open the file and move the handle to the heap
         op_file.file = std::make_unique<util::File>();
         *op_file.file = path.open_r();
         op_file.handle = {
             op_open_callbacks(op_file.file.get(), &opus_access_funcs,
                               nullptr, 0, &op_err),
             opus_deleter
         };
     }
     if (op_err != 0) {
         const char *reason;
         switch (op_err) {
         case OP_EREAD:
             reason = "read/seek/tell failed or data has changed"; break;
         case OP_EFAULT:
             reason = "opus failed to allocate memory "
                      "or something else bad happened internally"; break;
         case OP_EIMPL:
             reason = "Stream used an unsupported feature"; break;
         case OP_EINVAL:
             reason = "seek() worked, but tell() did not, "
                      "or initial_bytes != start seek pos"; break;
         case OP_ENOTFORMAT:
             reason = "Data didn't contain opus stream"; break;
         case OP_EBADHEADER:
             reason = "Header packet was invalid or missing"; break;
         case OP_EVERSION:
             reason = "ID header has unrecognized version"; break;
         case OP_EBADLINK:
             reason = "Data we already saw before seeking not found"; break;
         case OP_EBADTIMESTAMP:
             reason = "Validity check for first/last timestamp failed"; break;
         default:
             reason = "Unknown other error in opusfile"; break;
         }
         throw audio::Error{
             ERR
             << "Could not open opus file: "
             << path << " = '" << native_path << "': "
             << reason
         };
     }
     return op_file;
 }
References ERR, openage::audio::opus_file_t::file, openage::audio::opus_file_t::handle, openage::util::Path::is_file(), openage::util::Path::open_r(), opus_access_funcs, opus_deleter, and openage::util::Path::resolve_native_path().
Referenced by openage::audio::OpusInMemoryLoader::get_resource().
operator<<() [1/3]
std::ostream & openage::audio::operator<< (std::ostream & os, const loader_policy_t val)
Definition at line 20 of file loader_policy.cpp.
{
     os << loader_policy_t_to_str(val);
     return os;
 }
References loader_policy_t_to_str(), and val.
operator<<() [2/3]
std::ostream & openage::audio::operator<< (std::ostream & os, const format_t val)
Definition at line 22 of file format.cpp.
{
     os << format_t_to_str(val);
     return os;
 }
References format_t_to_str(), and val.
operator<<() [3/3]
std::ostream & openage::audio::operator<< (std::ostream & os, const category_t val)
Definition at line 24 of file category.cpp.
{
     os << category_t_to_str(val);
     return os;
 }
References category_t_to_str(), and val.
Variable Documentation
opus_access_funcs
OpusFileCallbacks openage::audio::opus_access_funcs static
Initial value:
{
    opus_reader,
    opus_seeker,
    opus_teller,
    nullptr
}
Definition at line 49 of file opus_loading.cpp.
Referenced by open_opus_file().
opus_deleter
auto openage::audio::opus_deleter static
Initial value:
= [](OggOpusFile *op_file) {
    if (op_file != nullptr) {
        op_free(op_file);
    }
}
Definition at line 13 of file opus_loading.cpp.
Referenced by open_opus_file().
opus_reader
op_read_func openage::audio::opus_reader static
Initial value:
= [](void *stream,
                                     unsigned char *buf,
                                     int count) -> int {
    util::File *file = reinterpret_cast<util::File *>(stream);
    return file->read_to(buf, count);
}
Definition at line 20 of file opus_loading.cpp.
opus_seeker
op_seek_func openage::audio::opus_seeker static
Initial value:
= [](void *stream,
                                     opus_int64 offset,
                                     int whence) -> int {
    util::File *file = reinterpret_cast<util::File *>(stream);
    if (unlikely(not file->seekable())) {
        return -1;
    }
    file->seek(offset, static_cast<util::File::seek_t>(whence));
    return 0;
}
Definition at line 29 of file opus_loading.cpp.
opus_teller
op_tell_func openage::audio::opus_teller static
Initial value:
= [](void *stream) -> opus_int64 {
    util::File *file = reinterpret_cast<util::File *>(stream);
    return file->tell();
}
Definition at line 43 of file opus_loading.cpp.