openage: openage.codegen.codegen Namespace Reference
openage.codegen.codegen Namespace Reference
Classes
class CodegenDirWrapper
Only allows pure-read and pure-write operations;.
class CodegenMode
Modus operandi.
class WriteCatcher
Functions
def codegen (mode, input_dir, output_dir)
def depend_module_blacklist ()
def get_codegen_depends (outputwrapper)
Yields all codegen dependencies.
def get_header_lines ()
Yields the lines for the automatically-added file header.
def postprocess_write (parts, data)
Post-processes a single write operation, as intercepted during codegen.
Function Documentation
codegen()
def openage.codegen.codegen.codegen (mode, input_dir, output_dir)
Definition at line 118 of file codegen.py.
     output_dir = Directory(output_dir).root
     # this wrapper intercepts all writes and logs all reads.
     wrapper = CodegenDirWrapper(input_dir)
     generate_all(wrapper.root)
     # set of all generated filenames
     generated = set()
     for parts, data in wrapper.get_writes():
         # TODO: this assumes output_dir is a fslike.Directory!
         generated.add(output_dir.fsobj.resolve(parts))
         # now, actually perform the generation.
         # first, assemble the path for the current file
         wpath = output_dir[parts]
         try:
             data = postprocess_write(parts, data)
         except ValueError as exc:
             err("code generation issue with output file %s:\n%s",
                 b'/'.join(parts).decode(errors='replace'), exc.args[0])
             sys.exit(1)
         if mode == CodegenMode.codegen:
             # skip writing if the file already has that exact content
             try:
                 with wpath.open('rb') as outfile:
                     if outfile.read() == data:
                         continue
             except FileNotFoundError:
                 pass
             # write new content to file
             wpath.parent.mkdirs()
             with wpath.open('wb') as outfile:
                 print("\x1b[36mcodegen: %s\x1b[0m" % b'/'.join(parts).decode(errors='replace'))
                 outfile.write(data)
         elif mode == CodegenMode.dryrun:
             # no-op
             pass
         elif mode == CodegenMode.clean:
             if wpath.is_file():
                 print(b'/'.join(parts).decode(errors='replace'))
                 wpath.unlink()
         else:
             err("unknown codegen mode: %s", mode)
             sys.exit(1)
     generated = {os.path.realpath(path).decode() for path in generated}
     depends = {os.path.realpath(path) for path in get_codegen_depends(wrapper)}
     return generated, depends
 def depend_module_blacklist():
     """
     Yields all modules whose source files shall explicitly not appear in the
     dependency list, even if they have been imported.
     """
     # openage.config is created only after the first run of cmake,
References openage::log.err(), openage.codegen.listing.generate_all(), openage.codegen.codegen.get_codegen_depends(), and openage.codegen.codegen.postprocess_write().
Referenced by openage.codegen.main.main().
depend_module_blacklist()
def openage.codegen.codegen.depend_module_blacklist ()
Definition at line 181 of file codegen.py.
     # thus, the depends list will change at the second run of codegen,
     # re-triggering cmake.
     try:
         import openage.config
         yield openage.config
     except ImportError:
         pass
     # devmode is imported by config, so the same reason as above applies.
     try:
         import openage.devmode
         yield openage.devmode
     except ImportError:
         pass
 def get_codegen_depends(outputwrapper):
     """
Referenced by openage.codegen.codegen.get_codegen_depends().
get_codegen_depends()
def openage.codegen.codegen.get_codegen_depends (outputwrapper)
Yields all codegen dependencies.
outputwrapper is the CodegenDirWrapper that was passed to generate_all; it's used to determine the files that have been read.
In addition, all imported python modules are yielded.
Definition at line 207 of file codegen.py.
     for parts in outputwrapper.get_reads():
         # TODO: this assumes that the wrap.obj.fsobj is a fslike.Directory
         # this just resolves paths to the output directory
         yield outputwrapper.obj.fsobj.resolve(parts).decode()
     module_blacklist = set(depend_module_blacklist())
     # add all source files that have been loaded as depends
     for module in modules.values():
         if module in module_blacklist:
             continue
         try:
             filename = module.__file__
         except AttributeError:
             # built-in modules don't have __file__, we don't want those as
             # depends.
             continue
         if filename is None:
             # some modules have __file__ == None, we don't want those either.
             continue
         if module.__package__ == '':
             continue
         if not filename.endswith('.py'):
             # This usually means that some .so file is imported as module.
             # This is not a problem as long as it's not "our" .so file.
             # => just handle non-openage non-.py files normally
             if 'openage' in module.__name__:
                 print("codegeneration depends on non-.py module " + filename)
                 sys.exit(1)
         yield filename
 def get_header_lines():
     """
References openage.codegen.codegen.depend_module_blacklist().
Referenced by openage.codegen.codegen.codegen().
get_header_lines()
def openage.codegen.codegen.get_header_lines ()
Yields the lines for the automatically-added file header.
Definition at line 250 of file codegen.py.
     yield (
         "Copyright 2013-{year} the openage authors. "
         "See copying.md for legal info."
     ).format(year=datetime.now().year)
     yield ""
     yield "Warning: this file was auto-generated; manual changes are futile."
     yield "For details, see buildsystem/codegen.cmake and openage/codegen."
     yield ""
 def postprocess_write(parts, data):
     """
Referenced by openage.codegen.codegen.postprocess_write().
postprocess_write()
def openage.codegen.codegen.postprocess_write (parts, data)
Post-processes a single write operation, as intercepted during codegen.
Definition at line 266 of file codegen.py.
     if parts[0] != b"libopenage":
         raise ValueError("Not in libopenage source directory")
     # test whether filename matches the pattern *.gen.*
     name, extension = os.path.splitext(parts[-1].decode())
     if not name.endswith('.gen'):
         raise ValueError("Doesn't match required filename format .gen.SUFFIX")
     # check file extension, and use the appropriate comment prefix
     if extension in {'.h', '.cpp'}:
         comment_prefix = '//'
     else:
         raise ValueError("Extension not in {.h, .cpp}")
     datalines = data.decode('ascii').split('\n')
     if 'Copyright' in datalines[0]:
         datalines = datalines[1:]
     headerlines = []
     for line in get_header_lines():
         if line:
             headerlines.append(comment_prefix + " " + line)
         else:
             headerlines.append("")
     return '\n'.join(chain(headerlines, datalines)).encode('ascii')
References openage.codegen.codegen.get_header_lines(), and openage::util.split().
Referenced by openage.codegen.codegen.codegen().