openage: openage::renderer::vulkan Namespace Reference
openage::renderer::vulkan Namespace Reference
Classes
struct SurfaceSupportDetails
struct vlk_capabilities
class VlkDrawableDisplay
class VlkFramebuffer
class VlkGraphicsDevice
Owns a device capable of graphics operations and surface presentation using WSI.
class VlkLoader
A class for dynamically loading Vulkan extension functions.
class VlkRenderer
A renderer using the Vulkan API.
class VlkShaderProgram
class VlkWindow
Functions
static VkShaderStageFlagBits vk_shader_stage (resources::shader_stage_t stage)
static VKAPI_ATTR VkBool32 VKAPI_CALL vlk_debug_cb (VkDebugReportFlagsEXT, VkDebugReportObjectTypeEXT, uint64_t, size_t, int32_t, const char *layerPrefix, const char *msg, void *)
static vlk_capabilities find_capabilities ()
Queries the Vulkan implementation for available extensions and layers.
Function Documentation
find_capabilities()
static vlk_capabilities openage::renderer::vulkan::find_capabilities () static
Queries the Vulkan implementation for available extensions and layers.
Definition at line 39 of file windowvk.cpp.
{
     vlk_capabilities caps;
     // Find which layers are available.
     auto layers = vk_do_ritual(vkEnumerateInstanceLayerProperties);
     log::log(MSG(dbg) << "Available Vulkan layers:");
     for (auto const& lr : layers) {
         caps.layers.insert(lr.layerName);
         log::log(MSG(dbg) << "\t" << lr.layerName);
     }
     // Find which extensions are available.
     // This is annoying, since an enumeration call without a filter-by-layer parameter
     // won't return all extensions. We thus have to enumerate extensions for each layer
     // and then remove duplicates.
     // First retrieve non-layer extensions.
     auto props = vk_do_ritual(vkEnumerateInstanceExtensionProperties, nullptr);
     for (auto const& p : props) {
         caps.extensions.emplace(p.extensionName);
     }
     // Then retrieve extensions from layers.
     for (auto const& lr : layers) {
         auto lr_props = vk_do_ritual(vkEnumerateInstanceExtensionProperties, lr.layerName);
         for (auto const& p : lr_props) {
             caps.extensions.emplace(p.extensionName);
         }
     }
     log::log(MSG(dbg) << "Available Vulkan extensions:");
     for (const auto& ext : caps.extensions) {
         log::log(MSG(dbg) << "\t" << ext);
     }
     return caps;
 }
References openage::log::dbg(), openage::renderer::vulkan::vlk_capabilities::extensions, openage::renderer::vulkan::vlk_capabilities::layers, openage::log::log(), MSG, and vk_do_ritual().
vk_shader_stage()
static VkShaderStageFlagBits openage::renderer::vulkan::vk_shader_stage (resources::shader_stage_t stage) static
Definition at line 16 of file shader_program.h.
{
     switch (stage) {
     case resources::shader_stage_t::vertex: return VK_SHADER_STAGE_VERTEX_BIT;
     case resources::shader_stage_t::geometry: return VK_SHADER_STAGE_GEOMETRY_BIT;
     case resources::shader_stage_t::tesselation_control: return VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT;
     case resources::shader_stage_t::tesselation_evaluation: return VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT;
     case resources::shader_stage_t::fragment: return VK_SHADER_STAGE_FRAGMENT_BIT;
     default: throw Error(MSG(err) << "Unknown shader stage.");
     }
 }
References openage::log::err(), openage::renderer::resources::fragment, openage::renderer::resources::geometry, MSG, openage::renderer::resources::tesselation_control, openage::renderer::resources::tesselation_evaluation, and openage::renderer::resources::vertex.
Referenced by openage::renderer::vulkan::VlkShaderProgram::VlkShaderProgram().
vlk_debug_cb()
static VKAPI_ATTR VkBool32 VKAPI_CALL openage::renderer::vulkan::vlk_debug_cb (VkDebugReportFlagsEXT , VkDebugReportObjectTypeEXT , uint64_t , size_t , int32_t , const char * layerPrefix, const char * msg, void *) static
Definition at line 22 of file windowvk.cpp.
 {
     log::log(MSG(dbg) << layerPrefix << " " << msg);
     return VK_FALSE;
 }
References openage::log::dbg(), openage::log::log(), and MSG.
Referenced by openage::renderer::vulkan::VlkWindow::VlkWindow().