openage: openage.convert.gamedata.empiresdat Namespace Reference
openage.convert.gamedata.empiresdat Namespace Reference
Classes
class EmpiresDat
class for fighting and beating the compressed empires2*.dat
class EmpiresDatWrapper
Functions
def load_gamespec (fileobj, game_versions, cachefile_name=None, load_cache=False)
Function Documentation
load_gamespec()
def openage.convert.gamedata.empiresdat.load_gamespec (fileobj, game_versions, cachefile_name = None, load_cache = False)
Definition at line 382 of file empiresdat.py.
     if cachefile_name and load_cache:
         try:
             with open(cachefile_name, "rb") as cachefile:
                 # pickle.load() can fail in many ways, we need to catch all.
                 # pylint: disable=broad-except
                 try:
                     gamespec = pickle.load(cachefile)
                     info("using cached gamespec: %s", cachefile_name)
                     return gamespec
                 except Exception:
                     warn("could not use cached gamespec:")
                     import traceback
                     traceback.print_exc()
                     warn("we will just skip the cache, no worries.")
         except FileNotFoundError:
             pass
     # read the file ourselves
     dbg("reading dat file")
     compressed_data = fileobj.read()
     fileobj.close()
     dbg("decompressing dat file")
     # -15: there's no header, window size is 15.
     file_data = decompress(compressed_data, -15)
     del compressed_data
     spam("length of decompressed data: %d", len(file_data))
     gamespec = EmpiresDatWrapper(game_versions=game_versions)
     gamespec.read(file_data, 0)
     if cachefile_name:
         dbg("dumping dat file contents to cache file: %s", cachefile_name)
         with open(cachefile_name, "wb") as cachefile:
             pickle.dump(gamespec, cachefile)
     return gamespec
References openage::log.dbg(), openage::log.info(), openage::log.spam(), and openage::log.warn().
Referenced by openage.convert.driver.get_gamespec().