openage: openage::util Namespace Reference
openage::util Namespace Reference
Namespaces
bytequeue
compress
constexpr_
context
decorators
filelike
files
fslike
fsprinting
iterators
math
profiler
strings
struct
system
tests
threading
Classes
class CachableOSStream
struct col
struct color
struct component_time_data
class ConstInitVector
struct csv_subdata
class CSVCollection
class Enum
class EnumValue
class ExternalOStringStream
class ExternalProfiler
class ExternalStringBuf
class FD
class File
class FixedPoint
struct FloatFixed
class Formatter
class FrameCounter
class FString
class FunctionPtr
struct less
class Matrix
class OnDeInit
class OnInit
class Path
class Profiler
class Quaternion
struct SharedPtrLess
class Siphash
class StringFormatter
class Timer
class utf8_decoder
class Variable
class VariableBase
class Vector
Typedefs
template<typename T = float>
using Matrix2t = Matrix< 2, 2, T >
template<typename T = float>
using Matrix3t = Matrix< 3, 3, T >
template<typename T = float>
using Matrix4t = Matrix< 4, 4, T >
template<size_t M, size_t N>
using Matrixf = Matrix< M, N, float >
template<size_t M, size_t N>
using Matrixd = Matrix< M, N, double >
using Matrix2f = Matrix< 2, 2, float >
using Matrix3f = Matrix< 3, 3, float >
using Matrix4f = Matrix< 4, 4, float >
using Matrix2d = Matrix< 2, 2, double >
using Matrix3d = Matrix< 3, 3, double >
using Matrix4d = Matrix< 4, 4, double >
using Quaternionf = Quaternion< float >
using Quaterniond = Quaternion< double >
using codepoint_t = int32_t
template<typename T = float>
using Vector2t = Vector< 2, T >
template<typename T = float>
using Vector3t = Vector< 3, T >
template<typename T = float>
using Vector4t = Vector< 4, T >
template<size_t N>
using Vectorf = Vector< N, float >
template<size_t N>
using Vectord = Vector< N, double >
using Vector2f = Vector< 2, float >
using Vector3f = Vector< 3, float >
using Vector4f = Vector< 4, float >
using Vector2d = Vector< 2, double >
using Vector3d = Vector< 3, double >
using Vector4d = Vector< 4, double >
Functions
template<class Container , class Function >
Function for_each (Container &&container, Function &&func)
template<class Container , class Function >
void remove_from (Container &container, Function &&func)
std::string demangle (const char *symbol)
std::string addr_to_string (const void *addr)
std::string symbol_name (const void *addr, bool require_exact_addr, bool no_pure_addrs)
bool is_symbol (const void *addr)
template<typename lineformat >
std::vector< lineformat > read_csv_file (const Path &path)
std::ostream & operator<< (std::ostream &stream, const File &file)
template<unsigned int amount, typename T >
static constexpr std::enable_if<(amount+(std::is_signed< T >::value ? 1 :0)< sizeof(T) *CHAR_BIT), T >::type safe_shiftleft (T value)
template<unsigned int amount, typename T >
static constexpr std::enable_if<(amount >=sizeof(T) *CHAR_BIT), T >::type safe_shiftright (T value)
template<unsigned int amount, typename T >
static constexpr std::enable_if<(amount< sizeof(T) *CHAR_BIT), T >::type safe_shiftright (T value)
template<int amount, typename T >
static constexpr std::enable_if<(amount< 0), T >::type safe_shift (T value)
template<int amount, typename T >
static constexpr std::enable_if<(amount >=0), T >::type safe_shift (T value)
template<typename I , unsigned int F>
constexpr FixedPoint< I, F > operator+ (const FixedPoint< I, F > &lhs, const FixedPoint< I, F > &rhs)
template<typename I , unsigned int F>
constexpr FixedPoint< I, F > operator+ (const FixedPoint< I, F > &lhs, const double &rhs)
template<typename I , unsigned int F>
constexpr FixedPoint< I, F > operator - (const FixedPoint< I, F > &lhs, const FixedPoint< I, F > &rhs)
template<typename I , unsigned int F>
constexpr FixedPoint< I, F > operator - (const FixedPoint< I, F > &lhs, const double &rhs)
template<typename I , unsigned F, typename N >
std::enable_if< std::is_arithmetic< N >::value, FixedPoint< I, F > >::type constexpr operator * (const FixedPoint< I, F > lhs, const N &rhs)
template<typename I , unsigned F, typename N >
constexpr FixedPoint< I, F > operator/ (const FixedPoint< I, F > lhs, const N &rhs)
size_t hash_combine (size_t hash1, size_t hash2)
uint64_t hash (const uint64_t key[2], const uint8_t *data, size_t len_data)
template<typename T >
void ignore_result (T)
template<size_t M, size_t N, typename T >
Matrix< M, N, T > operator * (T a, const Matrix< M, N, T > &mat)
template<size_t M, size_t N, typename T >
Matrix< M, N, T > operator * (int64_t a, const Matrix< M, N, T > &mat)
template<typename T >
constexpr T mod (T x, T m)
template<typename T , unsigned int modulo>
constexpr T mod (T x)
template<typename T , int amount>
constexpr T rol (T x)
template<typename T >
constexpr T div (T x, T m)
uint64_t array8_to_uint64 (const uint8_t *start, size_t count, bool big_endian=false)
std::vector< uint8_t > uint64_to_array8 (const uint64_t value, bool big_endian=false)
constexpr size_t array64_size (size_t count)
std::vector< uint64_t > array8_to_array64 (const uint8_t *start, size_t count, bool big_endian=false)
std::vector< uint8_t > array64_to_array8 (const uint64_t *start, size_t count, bool big_endian=false)
template<typename T >
void vector_extend (std::vector< T > &vec, const std::vector< T > &ext)
template<typename T >
void vector_extend (std::vector< T > &vec, std::vector< T > &&ext)
template<typename T >
void vector_remove_swap_end (std::vector< T > &vec, size_t idx)
void gl_check_error ()
void path_normalizer (Path::parts_t &output, const Path::parts_t &input)
std::ostream & operator<< (std::ostream &stream, const Path &path)
std::string filename (const std::string &fullpath)
std::string dirname (const std::string &fullpath)
std::string repr (const std::string &arg)
std::string sformat (const char *fmt,...)
size_t vsformat (const char *fmt, va_list ap, std::string &output)
std::unique_ptr< char[]> copy_string (const char *s)
size_t rstrip (char *s)
bool string_matches_pattern (const char *str, const char *pattern)
std::vector< std::string > split (const std::string &txt, char delimiter)
std::vector< std::string > split_escape (const std::string &txt, char delim, size_t size_hint)
template<unsigned decimals, unsigned w>
std::ostream & operator<< (std::ostream &os, FloatFixed< decimals, w > f)
template<typename ret_t >
void split (const std::string &txt, char delimiter, ret_t result)
size_t get_current_thread_id ()
size_t utf8_decode (const unsigned char *s, size_t len, int32_t *outbuf)
size_t utf8_encode (int cp, char *outbuf)
size_t utf8_last_char_size (char *str)
void utf8_pop_back (std::string &str)
Variables
std::string empty_string
static constexpr size_t uint64_s = 8
constexpr const char * HEX_DIGITS = "0123456789abcdef"
Typedef Documentation
codepoint_t
using openage::util::codepoint_t = typedef int32_t
Definition at line 15 of file unicode.h.
Matrix2d
using openage::util::Matrix2d = typedef Matrix<2, 2, double>
Definition at line 291 of file matrix.h.
Matrix2f
using openage::util::Matrix2f = typedef Matrix<2, 2, float>
Definition at line 287 of file matrix.h.
Matrix2t
template<typename T = float> using openage::util::Matrix2t = typedef Matrix<2, 2, T>
Definition at line 273 of file matrix.h.
Matrix3d
using openage::util::Matrix3d = typedef Matrix<3, 3, double>
Definition at line 292 of file matrix.h.
Matrix3f
using openage::util::Matrix3f = typedef Matrix<3, 3, float>
Definition at line 288 of file matrix.h.
Matrix3t
template<typename T = float> using openage::util::Matrix3t = typedef Matrix<3, 3, T>
Definition at line 276 of file matrix.h.
Matrix4d
using openage::util::Matrix4d = typedef Matrix<4, 4, double>
Definition at line 293 of file matrix.h.
Matrix4f
using openage::util::Matrix4f = typedef Matrix<4, 4, float>
Definition at line 289 of file matrix.h.
Matrix4t
template<typename T = float> using openage::util::Matrix4t = typedef Matrix<4, 4, T>
Definition at line 279 of file matrix.h.
Matrixd
template<size_t M, size_t N> using openage::util::Matrixd = typedef Matrix<M, N, double>
Definition at line 285 of file matrix.h.
Matrixf
template<size_t M, size_t N> using openage::util::Matrixf = typedef Matrix<M, N, float>
Definition at line 282 of file matrix.h.
Quaterniond
using openage::util::Quaterniond = typedef Quaternion<double>
Definition at line 436 of file quaternion.h.
Quaternionf
using openage::util::Quaternionf = typedef Quaternion<float>
Definition at line 435 of file quaternion.h.
Vector2d
using openage::util::Vector2d = typedef Vector<2, double>
Definition at line 225 of file vector.h.
Vector2f
using openage::util::Vector2f = typedef Vector<2, float>
Definition at line 221 of file vector.h.
Vector2t
template<typename T = float> using openage::util::Vector2t = typedef Vector<2, T>
Definition at line 207 of file vector.h.
Vector3d
using openage::util::Vector3d = typedef Vector<3, double>
Definition at line 226 of file vector.h.
Vector3f
using openage::util::Vector3f = typedef Vector<3, float>
Definition at line 222 of file vector.h.
Vector3t
template<typename T = float> using openage::util::Vector3t = typedef Vector<3, T>
Definition at line 210 of file vector.h.
Vector4d
using openage::util::Vector4d = typedef Vector<4, double>
Definition at line 227 of file vector.h.
Vector4f
using openage::util::Vector4f = typedef Vector<4, float>
Definition at line 223 of file vector.h.
Vector4t
template<typename T = float> using openage::util::Vector4t = typedef Vector<4, T>
Definition at line 213 of file vector.h.
Vectord
template<size_t N> using openage::util::Vectord = typedef Vector<N, double>
Definition at line 219 of file vector.h.
Vectorf
template<size_t N> using openage::util::Vectorf = typedef Vector<N, float>
Definition at line 216 of file vector.h.
Function Documentation
addr_to_string()
std::string openage::util::addr_to_string (const void * addr)
Definition at line 46 of file compiler.cpp.
{
     return sformat("[%p]", addr);
 }
References sformat().
Referenced by symbol_name().
array64_size()
constexpr size_t openage::util::array64_size (size_t count) inline
Get the number of uint64-elements that result from converting a count-sized uint8_t array.
Used to determine the size for array8_to_array64()
Returns
ceil(count/8)
Definition at line 170 of file misc.h.
{
     size_t partial = mod<size_t, uint64_s>(count);
     return ((count - partial) / uint64_s) + (partial ? 1 : 0);
 }
References uint64_s.
Referenced by array8_to_array64().
array64_to_array8()
std::vector<uint8_t> openage::util::array64_to_array8 (const uint64_t * start, size_t count, bool big_endian = false) inline
Convert a C-style array of uint64_t to a std::vector of uint8_t. Uses little-endianness as default.
e.g (big-endian): 0x0123456789abcdef -> {0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef} e.g (little-endian): 0x0123456789abcdef -> {0xef, 0xcd, 0xab, 0x89, 0x67, 0x45, 0x23, 0x01}
Parameters
Start of the input data.
count Number of uint64_t to convert.
big_endian Endianness of byte array.
Returns
Input data as a 8 bit number vector.
Definition at line 222 of file misc.h.
{
     std::vector<uint8_t> result;
     result.reserve(count * uint64_s);
     for (size_t i = 0; i < count; i++) {
         std::vector<uint8_t> block = uint64_to_array8(*(start + i), big_endian);
         result.insert(result.end(), block.begin(), block.end());
     }
     return result;
 }
References openage.testing.testing::result(), uint64_s, and uint64_to_array8().
Referenced by openage::util::tests::array_conversion().
array8_to_array64()
std::vector<uint64_t> openage::util::array8_to_array64 (const uint8_t * start, size_t count, bool big_endian = false) inline
Convert a C-style array of uint8_t to a std::vector of uint64_t. Uses little-endianness as default. Fills the remaining bytes of the last uint64_t with zeroes.
e.g (big-endian): {0x01, 0x23, 0x45, 0x67} -> 0x0123456700000000 e.g (little-endian): {0x01, 0x23, 0x45, 0x67} -> 0x0000000067452301
Parameters
start Start of the input data.
count Number of bytes to convert.
big_endian Endianness of byte array.
Returns
Input data as a 64 bit number vector.
Definition at line 190 of file misc.h.
{
     size_t size{array64_size(count)};
     std::vector<uint64_t> result(size, 0);
     size_t rem_bytes;
     for (size_t i = 0; i < size; i++) {
         rem_bytes = count - i * uint64_s;
         result[i] = array8_to_uint64(
             start + (i * uint64_s),
             std::min(rem_bytes, uint64_s),
             big_endian
         );
     }
     return result;
 }
References array64_size(), array8_to_uint64(), std::min(), openage.testing.testing::result(), and uint64_s.
Referenced by openage::util::tests::array_conversion().
array8_to_uint64()
uint64_t openage::util::array8_to_uint64 (const uint8_t * start, size_t count, bool big_endian = false) inline
Convert a C-style array of uint8_t to a uint64_t. Uses little-endianness as default. Fills the remaining bytes with zeroes.
e.g (big-endian): {0x01, 0x23, 0x45, 0x67} -> 0x0123456700000000 e.g (little-endian): {0x01, 0x23, 0x45, 0x67} -> 0x0000000067452301
Parameters
start Pointer to start of the input data.
count Number of bytes to read.
big_endian Endianness of byte array.
Returns
Input data as a 64 bit number.
Definition at line 111 of file misc.h.
{
     if (count > uint64_s) {
         throw Error(MSG(err) << "Tried to copy more than " << uint64_s << " bytes");
     }
     uint64_t result{0};
     if (big_endian) {
         for (size_t i = 0; i < count; i++) {
             result |= static_cast<uint64_t>(*(start + i)) << (7 - i) * 8;
         }
     }
     else {
         for (size_t i = 0; i < count; i++) {
             result |= static_cast<uint64_t>(*(start + i)) << i * 8;
         }
     }
     return result;
 }
References openage::log::err(), MSG, openage.testing.testing::result(), and uint64_s.
Referenced by array8_to_array64(), openage::util::tests::array_conversion(), hash(), and openage::util::Siphash::set_key().
copy_string()
std::unique_ptr< char[]> openage::util::copy_string (const char * s)
Copies the given string to the returned unique_ptr, including 0 byte.
Definition at line 64 of file strings.cpp.
{
     size_t sz = strlen(s) + 1;
     auto ret = std::make_unique<char[]>(sz);
     memcpy(ret.get(), s, sz);
     return ret;
 }
References openage::util::constexpr_::strlen().
Referenced by openage::subprocess::which().
demangle()
std::string openage::util::demangle (const char * symbol)
Demangles a symbol name.
On failure, the mangled symbol name is returned.
Definition at line 25 of file compiler.cpp.
{
 #ifdef _WIN32
     // \todo demangle names for MSVC; Possibly using UnDecorateSymbolName
     // https://msdn.microsoft.com/en-us/library/windows/desktop/ms681400(v=vs.85).aspx
     // Could it be that MSVC's typeid(T).name() already returns a demangled name? It seems that .raw_name() returns the mangled name
     return symbol;
 #else
     int status;
     char *buf = abi::__cxa_demangle(symbol, nullptr, nullptr, &status);
     if (status != 0) {
         return symbol;
     } else {
         std::string result{buf};
         free(buf);
         return result;
     }
 #endif
 }
References openage.testing.testing::result().
Referenced by openage::pyinterface::tests::err_py_to_cpp(), openage::GameSpec::initialize(), openage::error::operator<<(), symbol_name(), openage::error::terminate_handler(), openage::pyinterface::translate_exc_cpp_to_py(), and openage::error::Error::type_name().
dirname()
std::string openage::util::dirname (const std::string & fullpath)
return the head (dirname) part of a path.
Definition at line 374 of file path.cpp.
{
     size_t rsep_pos = fullpath.rfind(fslike::PATHSEP);
     if (rsep_pos == std::string::npos) {
         return "";
     } else {
         return fullpath.substr(0, rsep_pos);
     }
 }
References openage::util::fslike::PATHSEP.
Referenced by openage::util::CSVCollection::read().
div()
template<typename T > constexpr T openage::util::div (T x, T m) inline
implements the 'correct' version of the division operator, which always rounds to -inf
Definition at line 75 of file misc.h.
{
     return (x - mod<T>(x, m)) / m;
 }
Referenced by operator/(), openage::util::FixedPoint< int64_t, 16 >::operator/=(), and openage::coord::tile::to_chunk().
filename()
std::string openage::util::filename (const std::string & fullpath)
get the filename (last part) of a given path
Definition at line 364 of file path.cpp.
{
     size_t rsep_pos = fullpath.rfind(fslike::PATHSEP);
     if (rsep_pos == std::string::npos) {
         return "";
     } else {
         return fullpath.substr(rsep_pos + 1);
     }
 }
References openage::util::fslike::PATHSEP.
Referenced by openage::gui::GameSaver::activate(), openage::ScreenshotManager::encode_png(), openage::log::FileSink::FileSink(), openage::util::CSVCollection::get_data(), openage::gui::GuiGameSpecImageProviderByFilenameImpl::get_texture_handle(), openage::pyinterface::init_exc_message(), openage::subprocess::is_executable(), openage::util::CSVCollection::read(), and openage::subprocess::which().
for_each()
template<class Container , class Function > Function openage::util::for_each (Container && container, Function && func) inline
std::for_each except just on containers.
Definition at line 18 of file algorithm.h.
{
     // why cpp why...
     return std::for_each(std::begin(std::forward<Container>(container)),
                          std::end(std::forward<Container>(container)),
                          std::forward<Function>(func));
 }
References openage::curve::tests::container().
Referenced by openage::EditorMode::announce_category_content(), openage::gui::GuiFilledTextureHandles::fill_all_handles_with_texture(), qtsdl::GuiLiveReloader::init_persistent_items(), and qtsdl::QmlEngineWithSingletonItemsInfo::~QmlEngineWithSingletonItemsInfo().
get_current_thread_id()
size_t openage::util::get_current_thread_id ()
Returns the unique identifier of the current thread.
For compilers with support for thread_local storage, the function also guarantees to return strictly monotonically increasing identifier (no collision).
Definition at line 44 of file thread_id.cpp.
{
     #if HAVE_THREAD_LOCAL_STORAGE
     static thread_local ThreadIdSupplier current_thread_id;
     return current_thread_id.val;
     #else
     return std::hash<std::thread::id>()(std::this_thread::get_id());
     #endif
 }
Referenced by openage::job::JobManager::execute_callbacks(), openage::log::message::init(), and openage::job::TypedJobStateBase< T >::TypedJobStateBase().
gl_check_error()
void openage::util::gl_check_error ()
query the current opengl context for any errors.
raises exceptions on any error.
Definition at line 12 of file opengl.cpp.
                       {
     int glerrorstate = 0;
     glerrorstate = glGetError();
     if (glerrorstate != GL_NO_ERROR) {
         const char *errormsg;
         //generate error message
         switch (glerrorstate) {
         case GL_INVALID_ENUM:
             // An unacceptable value is specified for an enumerated argument.
             // The offending command is ignored
             // and has no other side effect than to set the error flag.
             errormsg = "invalid enum passed to opengl call";
             break;
         case GL_INVALID_VALUE:
             // A numeric argument is out of range.
             // The offending command is ignored
             // and has no other side effect than to set the error flag.
             errormsg = "invalid value passed to opengl call";
             break;
         case GL_INVALID_OPERATION:
             // The specified operation is not allowed in the current state.
             // The offending command is ignored
             // and has no other side effect than to set the error flag.
             errormsg = "invalid operation performed during some state";
             break;
         case GL_INVALID_FRAMEBUFFER_OPERATION:
             // The framebuffer object is not complete. The offending command
             // is ignored and has no other side effect than to set the error flag.
             errormsg = "invalid framebuffer operation";
             break;
         case GL_OUT_OF_MEMORY:
             // There is not enough memory left to execute the command.
             // The state of the GL is undefined,
             // except for the state of the error flags,
             // after this error is recorded.
             errormsg = "out of memory, wtf?";
             break;
         case GL_STACK_UNDERFLOW:
             // An attempt has been made to perform an operation that would
             // cause an internal stack to underflow.
             errormsg = "stack underflow";
             break;
         case GL_STACK_OVERFLOW:
             // An attempt has been made to perform an operation that would
             // cause an internal stack to overflow.
             errormsg = "stack overflow";
             break;
         default:
             // unknown error state
             errormsg = "unknown error";
         }
         throw Error(MSG(err) <<
             "OpenGL error state after running draw method: " << glerrorstate << "\n"
             "\t" << errormsg << "\n"
             << "Run the game with --gl-debug to get more information: './run game --gl-debug'.");
     }
 }
References openage::log::err(), and MSG.
Referenced by openage::Engine::loop().
hash()
uint64_t openage::util::hash (const uint64_t key[2], const uint8_t * data, size_t len_data)
Siphash implementation
https://131002.net/siphash/
Definition at line 36 of file hash.cpp.
{
     static auto sipround = [](uint64_t *v) {
         v[0] += v[1];
         v[1] = rol<uint64_t, 13>(v[1]);
         v[1] ^= v[0];
         v[0] = rol<uint64_t, 32>(v[0]);
         v[2] += v[3];
         v[3] = rol<uint64_t, 16>(v[3]);
         v[3] ^= v[2];
         v[0] += v[3];
         v[3] = rol<uint64_t, 21>(v[3]);
         v[3] ^= v[0];
         v[2] += v[1];
         v[1] = rol<uint64_t, 17>(v[1]);
         v[1] ^= v[2];
         v[2] = rol<uint64_t, 32>(v[2]);
     };
     // (len_data mod 256) ending to append later at the end of the data
     uint64_t ending = static_cast<uint64_t>(len_data & 0xff) << 56;
     // Initialization
     uint64_t v[4];
     // These values were taken from the paper: https://131002.net/siphash/siphash.pdf
     v[0] = key[0] ^ 0x736f6d6570736575ull;
     v[1] = key[1] ^ 0x646f72616e646f6dull;
     v[2] = key[0] ^ 0x6c7967656e657261ull;
     v[3] = key[1] ^ 0x7465646279746573ull;
     // Compression
     {
         size_t rem_bytes{len_data};
         const uint8_t *idx{data}; // Points to the start of the current block being copied
         uint64_t block;
         bool finished{false};
         do {
             if (rem_bytes < 8) {
                 block = array8_to_uint64(idx, rem_bytes, false);
                 block |= ending;
                 finished = true;
             }
             else {
                 block = array8_to_uint64(idx, 8, false);
             }
             v[3] ^= block;
             sipround(v);
             sipround(v);
             v[0] ^= block;
             rem_bytes -= 8;
             idx += 8;
         } while (!finished);
     }
     // Finalization
     v[2] ^= 0xff;
     sipround(v);
     sipround(v);
     sipround(v);
     sipround(v);
     return v[0] ^ v[1] ^ v[2] ^ v[3];
 }
References array8_to_uint64().
Referenced by openage.convert.dataformat.header_snippet.HeaderSnippet::__hash__(), openage.convert.dataformat.struct_snippet.StructSnippet::__hash__(), openage.convert.dataformat.content_snippet.ContentSnippet::__hash__(), openage::util::Siphash::digest(), openage::renderer::GlyphAtlas::get_cache_key(), and std::hash< openage::renderer::font_description >::operator()().
hash_combine()
size_t openage::util::hash_combine (size_t hash1, size_t hash2)
Creates a hash value as a combination of two other hashes. Can be called incrementally to create hash value from several variables.
Definition at line 12 of file hash.cpp.
{
     // Taken from http://www.boost.org/doc/libs/1_55_0/doc/html/hash/reference.html#boost.hash_combine
     return hash1 ^ (hash2 + 0x9e3779b9 + ((hash1 << 6) + (hash1 >> 2)));
 }
Referenced by openage::renderer::GlyphAtlas::get_cache_key(), and std::hash< openage::renderer::font_description >::operator()().
ignore_result()
template<typename T > void openage::util::ignore_result (T) inline
Wrapping a function call with ignore_result makes it more clear to readers, compilers and linters that you are, in fact, ignoring the function's return value on purpose.
Definition at line 38 of file language.h.
 {}
Referenced by openage::error::sigsegv_handler().
is_symbol()
bool openage::util::is_symbol (const void * addr)
Returns true if the address is the (exact) address of a symbol.
Definition at line 136 of file compiler.cpp.
{
 #ifdef _WIN32
     if (!initialized_symbol_handler_successfully) {
         return true;
     } else {
         return symbol_name_win(addr).has_value();
     }
 #else
     Dl_info addr_info;
     if (dladdr(addr, &addr_info) == 0) {
         return false;
     }
     return (addr_info.dli_saddr == addr);
 #endif
 }
Referenced by openage::pyinterface::add_py_if_component().
mod() [1/2]
template<typename T > constexpr T openage::util::mod (T x, T m)
modulo operation that guarantees to return positive values.
Definition at line 32 of file misc.h.
                 {
     T r = x % m;
     if (r < 0) {
         return r + m;
     } else {
         return r;
     }
 }
Referenced by openage::util::Profiler::draw_component_performance(), openage::input::InputManager::get_mod(), openage::coord::tile::get_pos_on_chunk(), openage::input::sdl_key(), openage::input::sdl_mod(), openage::input::sdl_mouse(), openage::input::sdl_mouse_up_down(), openage::input::sdl_wheel(), openage::input::text_to_event(), and openage::renderer::vulkan::VlkShaderProgram::VlkShaderProgram().
mod() [2/2]
template<typename T , unsigned int modulo> constexpr T openage::util::mod (T x)
compiletime defined modulo function.
Definition at line 47 of file misc.h.
            {
     T r = x % modulo;
     if (r < 0) {
         return r + modulo;
     } else {
         return r;
     }
 }
operator *() [1/3]
template<size_t M, size_t N, typename T > Matrix<M, N, T> openage::util::operator * (T a, const Matrix< M, N, T > & mat)
Scalar multiplication with swapped arguments
Definition at line 258 of file matrix.h.
{
     return mat * a;
 }
operator *() [2/3]
template<size_t M, size_t N, typename T > Matrix<M, N, T> openage::util::operator * (int64_t a, const Matrix< M, N, T > & mat)
Scalar multiplication with swapped arguments for int. This was just added because otherwise the above float-multiplication function might not match to the template deduction.
Definition at line 268 of file matrix.h.
{
     return mat * a;
 }
operator *() [3/3]
template<typename I , unsigned F, typename N > std::enable_if<std::is_arithmetic<N>::value, FixedPoint<I, F> >::type constexpr openage::util::operator * (const FixedPoint< I, F > lhs, const N & rhs)
FixedPoint * N
Definition at line 440 of file fixed_point.h.
{
     return FixedPoint<I, F>::from_raw_value(lhs.get_raw_value() * rhs);
 }
References openage::util::FixedPoint< int_type, fractional_bits >::from_raw_value(), and openage::util::FixedPoint< int_type, fractional_bits >::get_raw_value().
operator -() [1/2]
template<typename I , unsigned int F> constexpr FixedPoint<I, F> openage::util::operator - (const FixedPoint< I, F > & lhs, const FixedPoint< I, F > & rhs)
FixedPoint - FixedPoint
Definition at line 422 of file fixed_point.h.
{
     return FixedPoint<I, F>::from_raw_value(lhs.get_raw_value() - rhs.get_raw_value());
 }
References openage::util::FixedPoint< int_type, fractional_bits >::from_raw_value(), and openage::util::FixedPoint< int_type, fractional_bits >::get_raw_value().
operator -() [2/2]
template<typename I , unsigned int F> constexpr FixedPoint<I, F> openage::util::operator - (const FixedPoint< I, F > & lhs, const double & rhs)
FixedPoint - double
Definition at line 430 of file fixed_point.h.
{
     return FixedPoint<I, F>{lhs} - FixedPoint<I, F>::from_double(rhs);
 }
References openage::util::FixedPoint< int_type, fractional_bits >::from_double().
operator+() [1/2]
template<typename I , unsigned int F> constexpr FixedPoint<I, F> openage::util::operator+ (const FixedPoint< I, F > & lhs, const FixedPoint< I, F > & rhs)
FixedPoint + FixedPoint
Definition at line 406 of file fixed_point.h.
{
     return FixedPoint<I, F>::from_raw_value(lhs.get_raw_value() + rhs.get_raw_value());
 }
References openage::util::FixedPoint< int_type, fractional_bits >::from_raw_value(), and openage::util::FixedPoint< int_type, fractional_bits >::get_raw_value().
operator+() [2/2]
template<typename I , unsigned int F> constexpr FixedPoint<I, F> openage::util::operator+ (const FixedPoint< I, F > & lhs, const double & rhs)
FixedPoint + double
Definition at line 414 of file fixed_point.h.
{
     return FixedPoint<I, F>{lhs} + FixedPoint<I, F>::from_double(rhs);
 }
References openage::util::FixedPoint< int_type, fractional_bits >::from_double().
operator/()
template<typename I , unsigned F, typename N > constexpr FixedPoint<I, F> openage::util::operator/ (const FixedPoint< I, F > lhs, const N & rhs)
FixedPoint / N
Definition at line 459 of file fixed_point.h.
{
     return FixedPoint<I, F>::from_raw_value(div(lhs.get_raw_value(), static_cast<I>(rhs)));
 }
References div(), openage::util::FixedPoint< int_type, fractional_bits >::from_raw_value(), and openage::util::FixedPoint< int_type, fractional_bits >::get_raw_value().
operator<<() [1/3]
template<unsigned decimals, unsigned w> std::ostream& openage::util::operator<< (std::ostream & os, FloatFixed< decimals, w > f)
Definition at line 34 of file strings.h.
{
     static_assert(decimals < 50, "Refusing to print float with >= 50 decimals");
     static_assert(w < 70, "Refusing to print float with a width >= 70");
     os.precision(decimals);
     os << std::fixed;
     if (w) {
         os << std::setw(w);
     }
     os << f.value;
     return os;
 }
operator<<() [2/3]
std::ostream& openage::util::operator<< (std::ostream & stream, const File & file)
Definition at line 124 of file file.cpp.
{
     stream << "File(";
     file.filelike->repr(stream);
     stream << ")";
     return stream;
 }
References openage::util::File::filelike.
operator<<() [3/3]
std::ostream& openage::util::operator<< (std::ostream & stream, const Path & path)
Definition at line 349 of file path.cpp.
{
     stream << "Path(";
     path.fsobj->repr(stream);
     stream << ":";
     for (auto &part : path.parts) {
         stream << "/" << part;
     }
     stream << ")";
     return stream;
 }
References openage::util::Path::fsobj, and openage::util::Path::parts.
path_normalizer()
void openage::util::path_normalizer (Path::parts_t & output, const Path::parts_t & input)
Strip out ../ etc
Definition at line 21 of file path.cpp.
{
     output.reserve(input.size());
     // normalize the path parts
     for (auto &part : input) {
         if (part == "." or part == "") {
             continue;
         }
         else if (part == "..") {
             if (likely(output.size() > 0)) {
                 output.pop_back();
             }
         }
         else {
             output.push_back(part);
         }
     }
 }
References likely.
read_csv_file()
template<typename lineformat > std::vector<lineformat> openage::util::read_csv_file (const Path & path)
read a single csv file. call the destination struct .fill() method for actually storing line data
Definition at line 182 of file csv.h.
{
     File csv = path.open();
     std::vector<lineformat> ret;
     size_t line_count = 0;
     for (auto &line : csv.get_lines()) {
         line_count += 1;
         // ignore comments and empty lines
         if (line.empty() || line[0] == '#') {
             continue;
         }
         lineformat current_line_data;
         // use the line copy to fill the current line struct.
         int error_column = current_line_data.fill(line);
         if (error_column != -1) {
             throw Error{
                 ERR
                 << "Failed to read CSV file: "
                 << csv << ":" << line_count << ":" << error_column
                 << ": error parsing " << line
             };
         }
         ret.push_back(current_line_data);
     }
     return ret;
 }
References ERR, openage::util::File::get_lines(), openage::line, and openage::util::Path::open().
remove_from()
template<class Container , class Function > void openage::util::remove_from (Container & container, Function && func) inline
Filters items from a container which satisfy a certain predicate.
Definition at line 29 of file algorithm.h.
{
     container.erase(std::remove_if(std::begin(container),
                                    std::end(container),
                                    std::forward<Function>(func)),
                     std::end(container));
 }
References openage::curve::tests::container().
repr()
std::string openage::util::repr (const std::string & arg)
method that behaves similar to python's "repr". puts the string in quotes and escapes all sorts of stuff inside.
Definition at line 12 of file repr.cpp.
{
     std::string result;
     result.push_back('"');
     for (char c : arg) {
         if (c >= 0x20 && c < 0x7f) {
             // printable
             if (c == '\\' || c == '"') {
                 // but it must be escaped
                 result.push_back('\\');
             }
             result.push_back(c);
         } else {
             // non-printable
             result.push_back('\\');
             result.push_back('x');
             result.push_back(HEX_DIGITS[(c & 0xf0) >> 4]);
             result.push_back(HEX_DIGITS[(c & 0x0f) >> 0]);
         }
     }
     result.push_back('"');
     return result;
 }
References HEX_DIGITS, and openage.testing.testing::result().
Referenced by openage.convert.texture.Texture::__init__(), openage.cabextract.cab.CABFile::__init__(), openage.convert.dataformat.content_snippet.ContentSnippet::__lt__(), openage.util.struct.NamedStructMeta::__new__(), openage.util.struct.FlagsMeta::__new__(), openage.util.fslike.wrapper.Wrapper::__repr__(), openage.util.fslike.path.Path::__repr__(), openage.codegen.codegen.CodegenDirWrapper::__repr__(), openage.convert.dataformat.members.GroupMember::__repr__(), openage.util.fslike.wrapper.WriteBlocker::__repr__(), openage.convert.dataformat.content_snippet.ContentSnippet::__repr__(), openage.convert.dataformat.members.IncludeMembers::__repr__(), openage.util.fslike.wrapper.Synchronizer::__repr__(), openage.util.fslike.wrapper.GuardedFile::__repr__(), openage.util.struct.NamedStruct::__repr__(), openage.util.struct.Flags::__repr__(), openage.util.fslike.union.Union::__str__(), openage.convert.colortable.ColorTable::__str__(), openage.convert.dataformat.struct_snippet.StructSnippet::__str__(), openage.convert.dataformat.content_snippet.ContentSnippet::__str__(), openage.convert.dataformat.struct_definition.StructDefinition::__str__(), openage.convert.dataformat.content_snippet.ContentSnippet::add_required_snippets(), openage.util.bytequeue.ByteQueue::append(), openage.util.bytequeue.ByteBuffer::append(), openage.testing.testing::assert_value(), openage::input::ActionManager::create(), openage.convert.dataformat.generated_file.GeneratedFile::generate(), openage.convert.dataformat.data_definition.DataDefinition::generate_csv(), openage.util.fslike.union.Union::list(), openage.cvar.config_file::load_config_file(), openage.util.strings::lstrip_once(), openage::pyinterface::tests::pyobject(), openage.convert.dataformat.exportable.Exportable::read(), openage.testing.testing::result(), and openage.util.strings::rstrip_once().
rol()
template<typename T , int amount> constexpr T openage::util::rol (T x)
compiletime defined rotate left function
Definition at line 63 of file misc.h.
            {
     static_assert(sizeof(T)*CHAR_BIT > amount && amount > 0, "invalid rotation amount");
     return (x << amount) | (x >> (sizeof(T)*CHAR_BIT - amount));
 }
rstrip()
size_t openage::util::rstrip (char * s)
Returns the number of whitespace characters on the right of the string.
Definition at line 72 of file strings.cpp.
{
     size_t strippedlen = strlen(s);
     while (strippedlen > 0) {
         if (s[strippedlen - 1] == '\n' ||
             s[strippedlen - 1] == ' '  ||
             s[strippedlen - 1] == '\t') {
             strippedlen -= 1;
         } else {
             break;
         }
     }
     s[strippedlen] = '\0';
     return strippedlen;
 }
References openage::util::constexpr_::strlen().
Referenced by openage.convert.pefile.PEFile::__init__().
safe_shift() [1/2]
template<int amount, typename T > static constexpr std::enable_if<(amount < 0), T>::type openage::util::safe_shift (T value) static
Helper function that performs either a safe shift-right (amount > 0), or a safe shift-left (amount < 0).
Definition at line 62 of file fixed_point.h.
                     {
     return safe_shiftright<-amount>(value);
 }
References safe_shiftright().
safe_shift() [2/2]
template<int amount, typename T > static constexpr std::enable_if<(amount >= 0), T>::type openage::util::safe_shift (T value) static
Definition at line 70 of file fixed_point.h.
                     {
     return safe_shiftleft<amount>(value);
 }
safe_shiftleft()
template<unsigned int amount, typename T > static constexpr std::enable_if<(amount + (std::is_signed<T>::value ? 1 : 0) < sizeof(T) * CHAR_BIT), T>::type openage::util::safe_shiftleft (T value) static
Helper function that performs a left shift without causing undefined behavior. regular left-shift is undefined if amount >= bitwidth, or amount >= bitwidth - 1 for signed integers.
Definition at line 28 of file fixed_point.h.
{
     return static_cast<T>(
         static_cast<typename std::make_unsigned<T>::type>(value) << amount
     );
 }
safe_shiftright() [1/2]
template<unsigned int amount, typename T > static constexpr std::enable_if<(amount >= sizeof(T) * CHAR_BIT), T>::type openage::util::safe_shiftright (T value) static
Helper function that performs a right shift without causing undefined behavior. right-shift is usually undefined if amount >= bit size.
Definition at line 43 of file fixed_point.h.
{
     return value < 0 ? -1 : 0;
 }
Referenced by safe_shift().
safe_shiftright() [2/2]
template<unsigned int amount, typename T > static constexpr std::enable_if<(amount < sizeof(T) * CHAR_BIT), T>::type openage::util::safe_shiftright (T value) static
Definition at line 50 of file fixed_point.h.
{
     return value >> amount;
 }
sformat()
std::string openage::util::sformat (const char * fmt, ...)
printf-style to-string formatting.
Definition at line 20 of file strings.cpp.
{
     std::string ret;
     va_list ap;
     va_start(ap, fmt);
     vsformat(fmt, ap, ret);
     va_end(ap);
     return ret;
 }
References vsformat().
Referenced by addr_to_string(), openage::log::tests::demo(), openage::ScreenshotManager::gen_next_filename(), openage::GameSpec::get_texture(), openage::GameSpec::load_terrain(), openage::GameSpec::on_gamedata_loaded(), and symbol_name().
split() [1/2]
template<typename ret_t > void openage::util::split (const std::string & txt, char delimiter, ret_t result)
Split a string at a delimiter, push the result back in an iterator. Why doesn't the fucking standard library have std::string::split(delimiter)?
Definition at line 88 of file strings.h.
{
     std::stringstream splitter;
     splitter.str(txt);
     std::string part;
     while (std::getline(splitter, part, delimiter)) {
         *result = part;
         result++;
     }
 }
split() [2/2]
std::vector< std::string > openage::util::split (const std::string & txt, char delim)
Split a string at a delimiter into a vector. Internally, uses the above iterator splitter.
Definition at line 136 of file strings.cpp.
{
     std::vector<std::string> items;
     // use the back inserter iterator and the templated split function.
     split(txt, delimiter, std::back_inserter(items));
     return items;
 }
Referenced by openage.convert.colortable.ColorTable::fill(), qtsdl::GuiPropertyMap::get_csv(), openage::util::Path::joinpath(), openage::util::fslike::Directory::mkdirs(), openage.codegen.codegen::postprocess_write(), openage.cabextract.cab.CABFile::read_file_headers(), openage.convert.hdlanguagefile::read_hd_language_file(), and openage.util.files::which().
split_escape()
std::vector< std::string > openage::util::split_escape (const std::string & txt, char delim, size_t size_hint = 0)
Split a string at a delimiter into a vector. size_hint is to give a predicted size of the vector already.
tokenizes txt by splitting it up to substrings at the deliminiters. "\n" is evaluated to '
'; all other '\X' escape sequences are evaluated to literal X, including the deliminiter.
Definition at line 144 of file strings.cpp.
{
     // output vector
     std::vector<std::string> items;
     if (likely(size_hint)) {
         items.reserve(size_hint);
     }
 #if HAVE_THREAD_LOCAL_STORAGE
     static thread_local std::vector<char> buf;
 #else
     std::vector<char> buf;
     buf.reserve(256);
 #endif
     // string reading pointer
     const char *r = txt.c_str();
     // copy characters to buf, and a buf is emitted as a token
     // when the delimiter or end is reached.
     while (true) {
         // end of input string
         if (*r == '\0') {
             items.push_back(std::string{std::begin(buf), std::end(buf)});
             buf.clear();
             break;
         }
         // delimiter found
         if (*r == delim) {
             items.push_back(std::string{std::begin(buf), std::end(buf)});
             buf.clear();
             r++;
             continue;
         }
         if (*r == '\\') {
             // an escaped char: increment the read pointer to point
             // at the escape code.
             r++;
             // analyze the escape code
             switch (*r) {
             case '\0':
                 // string ended in the middle of an escape code
                 // error!
                 throw Error{ERR << "string ends after escape"};
             case 'n':
                 // a newline
                 buf.push_back('\n');
                 continue;
             default:
                 // the escape code already represents the literal
                 // character (e.g.: "\\" = '\', "\," = ',').
                 break;
             }
         }
         buf.push_back(*r);
         r++;
     }
     return items;
 }
References ERR, and likely.
Referenced by openage::renderer::resources::Texture2dSubInfo::Texture2dSubInfo().
string_matches_pattern()
bool openage::util::string_matches_pattern (const char * str, const char * pattern)
returns true if str matches the basic globbing pattern in the pattern, '*' matches any number of characters, while all other characters are interpreted as literal.
Definition at line 92 of file strings.cpp.
{
     while (true) {
         if (*pattern == '*') {
             // skip all wildcard chars
             while (*pattern == '*') {
                 pattern++;
             }
             // performance optimization: if the wildcard was the
             // last char of the pattern, it's a sure match.
             if (*pattern == '\0') {
                 return true;
             }
             // search for all places in str that equal *pattern;
             // those are possible places of continuation.
             while (*str != '\0') {
                 if (*str == *pattern) {
                     if (string_matches_pattern(str, pattern)) {
                         return true;
                     }
                 }
             }
             // no match was found
             return false;
         }
         if (*str != *pattern) {
             // chars don't match
             return false;
         }
         if (*pattern == '\0') {
             // comparision done
             return true;
         }
         str += 1;
         pattern += 1;
     }
 }
References openage::py::str().
symbol_name()
OAAPI std::string openage::util::symbol_name (const void * addr, bool require_exact_addr = true, bool no_pure_addrs = false)
Returns the (demangled) symbol name for a given address.
If no exact match can be found, if require_exact_addr == true (default): if no_pure_addrs == false (default): a pure hex address string is returned else: an empty string is returned if require_exact_addr == false: name of closest symbol + offset hex string is returned
pxd: string symbol_name(const void *addr) except +
Definition at line 98 of file compiler.cpp.
{
 #ifdef _WIN32
     auto symbol_name_result = symbol_name_win(addr);
     if (!initialized_symbol_handler_successfully ||
         !symbol_name_result.has_value()) {
         return no_pure_addrs ? "" : addr_to_string(addr);
     }
     return symbol_name_result.value();
 #else
     Dl_info addr_info;
     if (dladdr(addr, &addr_info) == 0) {
         // dladdr has... failed.
         return no_pure_addrs ? "" : addr_to_string(addr);
     } else {
         size_t symbol_offset = (size_t) addr - (size_t) addr_info.dli_saddr;
         if (addr_info.dli_sname == nullptr or (symbol_offset != 0 and require_exact_addr)) {
             return no_pure_addrs ? "" : addr_to_string(addr);
         }
         if (symbol_offset == 0) {
             // this is our symbol name.
             return demangle(addr_info.dli_sname);
         } else {
             return util::sformat("%s+0x%lx",
                                  demangle(addr_info.dli_sname).c_str(),
                                  symbol_offset);
         }
     }
 #endif
 }
References addr_to_string(), demangle(), and sformat().
Referenced by openage::pyinterface::add_py_if_component(), openage::pyinterface::check(), openage::pyinterface::Func< ReturnType, ArgTypes ... >::check_fptr(), and openage::error::StackAnalyzer::get_symbols().
uint64_to_array8()
std::vector<uint8_t> openage::util::uint64_to_array8 (const uint64_t value, bool big_endian = false) inline
Convert a uint64_t to an array of uint8_t. Uses little-endianness as default.
e.g (big-endian): 0x0123456789abcdef -> {0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef} e.g (little-endian): 0x0123456789abcdef -> {0xef, 0xcd, 0xab, 0x89, 0x67, 0x45, 0x23, 0x01}
Parameters
value 64 bit number to convert.
big_endian Endianness of byte array.
Returns
Input data as a 8 bit number array.
Definition at line 145 of file misc.h.
{
     std::vector<uint8_t> result(uint64_s, 0);
     if (big_endian) {
         for (size_t i = 0; i < uint64_s; i++) {
             result[i] = (value >> ((7 - i) * 8)) & 0xff;
         }
     }
     else {
         for (size_t i = 0; i < uint64_s; i++) {
             result[i] = (value >> (i * 8)) & 0xff;
         }
     }
     return result;
 }
References openage.testing.testing::result(), and uint64_s.
Referenced by array64_to_array8(), openage::util::tests::array_conversion(), and openage::util::Siphash::digest().
utf8_decode()
size_t openage::util::utf8_decode (const unsigned char * s, size_t len, codepoint_t * outbuf)
decodes a UTF-8 character string of given length
the results are written to outbuf. no leading 0 is written to outbuf (nor is one expected at s). outbuf MUST be large enough to hold all characters. to ensure that outbuf is large enough, it SHOULD have a size of at least len.
the number of actual unicode characters is returned. it might be anywhere in the range [len/4; len].
in case of decoding errors, the special unicode character 0xfffd is written.
code logic gratefully borrowed from rxvt-unicode.
Definition at line 72 of file unicode.cpp.
{
     size_t advance;
     wchar_t w;
     size_t result = 0;
     while (len > 0) {
         if (s[0] < 0x80) {
             // 1-byte (ASCII) character
             w = *s;
             advance = 1;
         } else if (len >= 2 && s[0] >= 0xc2 && s[0] <= 0xdf && (s[1] & 0xc0) == 0x80) {
             // 2-byte character
             w = ((s[0] & 0x1f) << 6) | (s[1] & 0x3f);
             advance = 2;
         } else if (len >= 3 &&
               ((s[0] == 0xe0  && s[1] >= 0xa0 && s[1] <= 0xbf)
             || (s[0] >= 0xe1 && s[0] <= 0xec && s[1] >= 0x80 && s[1] <= 0xbf)
             || (s[0] == 0xed && s[1] >= 0x80 && s[1] <= 0x9f)
             || (s[0] >= 0xee && s[0] <= 0xef && s[1] >= 0x80 && s[1] <= 0xbf))
             && (s[2] & 0xc0) == 0x80) {
             // 3-byte character
             w = ((s[0] & 0x0f) << 12) | ((s[1] & 0x3f) << 6) | (s[2] & 0x3f);
             advance = 3;
         } else if (len >= 4 &&
               ((s[0] == 0xf0 && s[1] >= 0x90 && s[1] <= 0xbf)
             || (s[0] >= 0xf1 && s[0] <= 0xf3 && s[1] >= 0x80 && s[1] <= 0xbf)
             || (s[0] == 0xf4 && s[1] >= 0x80 && s[1] <= 0x8f))
             && (s[2] & 0xc0) == 0x80
             && (s[3] & 0xc0) == 0x80) {
             // 4-byte character
             w = ((s[0] & 0x07) << 18) | ((s[1] & 0x3f) << 12) | ((s[2] & 0x3f) << 6) | (s[3] & 0x3f);
             advance = 4;
         } else {
             // decoding error; try with next byte
             w = 0xfffd;
             advance = 1;
         }
         len -= advance;
         s += advance;
         *outbuf++ = w;
         result++;
     }
     return result;
 }
References openage.testing.testing::result().
utf8_encode()
size_t openage::util::utf8_encode (int cp, char * outbuf)
encodes one Unicode codepoint to a null-terminated UTF-8 character string. due to the nature of UTF-8, the result string is at most 4 bytes long. on error, the empty string is returned.
cp the codepoint outbuf a output char buffer. outbuf[0] to outbuf[4] MUST be writeable. outbuf[0] will ALWAYS be written to. returns the number of non-NULL bytes that have been written, i.e. strlen(outbuf)
Definition at line 120 of file unicode.cpp.
{
     if (cp < 0) {
         // illegal codepoint (negative)
         outbuf[0] = '\0';
         return 0;
     } else if (cp < 0x80) {
         outbuf[0] = cp;
         outbuf[1] = '\0';
         return 1;
     } else if (cp < 0x800) {
         outbuf[2] = '\0';
         outbuf[1] = 0x80 | (cp & 0x3f); cp >>= 6;
         outbuf[0] = 0xc0 | cp;
         return 2;
     } else if (cp < 0x10000) {
         outbuf[3] = '\0';
         outbuf[2] = 0x80 | (cp & 0x3f); cp >>= 6;
         outbuf[1] = 0x80 | (cp & 0x3f); cp >>= 6;
         outbuf[0] = 0xe0 | cp;
         return 3;
     } else if (cp < 0x200000) {
         outbuf[4] = '\0';
         outbuf[3] = 0x80 | (cp & 0x3f); cp >>= 6;
         outbuf[2] = 0x80 | (cp & 0x3f); cp >>= 6;
         outbuf[1] = 0x80 | (cp & 0x3f); cp >>= 6;
         outbuf[0] = 0xf0 | cp;
         return 4;
     } else {
         // illegal codepoint: unicode is only defined up to 0x1fffff
         outbuf[0] = '\0';
         return 0;
     }
 }
Referenced by openage::util::FD::putcp(), and openage::console::draw::to_opengl().
utf8_last_char_size()
size_t openage::util::utf8_last_char_size (char * str)
computes the length of the last character in a given UTF-8 string.
str the UTF-8 string returns the length of the last character in bytes
Definition at line 154 of file unicode.cpp.
{
     int r = 0;
     int i = strlen(str) - 1;
     while ((i >= 0) && (str[i] & 0x80) && !(str[i] & 0x40)) {
         i--;
         r++;
     }
     if (i >= 0) {
         r++;
     }
     return r;
 }
References openage::py::str(), and openage::util::constexpr_::strlen().
Referenced by utf8_pop_back().
utf8_pop_back()
void openage::util::utf8_pop_back (std::string & str)
pops back (deletes) the last UTF-8 character in a std::string.
Definition at line 167 of file unicode.cpp.
{
     str.erase(str.size() - utf8_last_char_size(&str[0]));
 }
References openage::py::str(), and utf8_last_char_size().
Referenced by openage::console::Console::register_to_engine().
vector_extend() [1/2]
template<typename T > void openage::util::vector_extend (std::vector< T > & vec, const std::vector< T > & ext)
Extend a vector with elements, without destroying source one.
Definition at line 239 of file misc.h.
{
     vec.reserve(vec.size() + ext.size());
     vec.insert(std::end(vec), std::begin(ext), std::end(ext));
 }
Referenced by openage::util::fslike::Directory::mkdirs().
vector_extend() [2/2]
template<typename T > void openage::util::vector_extend (std::vector< T > & vec, std::vector< T > && ext)
Definition at line 249 of file misc.h.
{
     if (vec.empty()) {
         vec = std::move(ext);
     }
     else {
         vec.reserve(vec.size() + ext.size());
         std::move(std::begin(ext), std::end(ext), std::back_inserter(vec));
         ext.clear();
     }
 }
References openage::move.
vector_remove_swap_end()
template<typename T > void openage::util::vector_remove_swap_end (std::vector< T > & vec, size_t idx)
Remove the given element index in the vector. May swap with the end element for efficient removing.
If the element is not in the vector, do nothing.
Definition at line 268 of file misc.h.
{
     // is at the end
     if (idx == vec.size() - 1) {
         vec.pop_back();
     }
     // is in the middle
     else if (idx < vec.size()) {
         std::swap(vec[idx], vec.back());
         vec.pop_back();
     } else {
         return;
     }
 }
Referenced by openage::audio::AudioManager::audio_callback(), and openage::audio::AudioManager::remove_sound().
vsformat()
std::string size_t openage::util::vsformat (const char * fmt, va_list ap, std::string & output)
printf-style valist-to-string formatting; the result is appended to output.
Definition at line 32 of file strings.cpp.
{
 #if HAVE_THREAD_LOCAL_STORAGE
     static thread_local std::vector<char> buf(64);
 #else
     std::vector<char> buf(64);
 #endif
     va_list aq;
     va_copy(aq, ap);
     size_t length = vsnprintf(buf.data(), buf.size(), fmt, aq);
     va_end(aq);
     if (unlikely(length >= buf.size())) {
         size_t target_size = buf.size();
         if (unlikely(target_size < 64)) {
             target_size = 64;
         }
         while (length >= target_size) {
             target_size *= 2;
         }
         buf.resize(target_size);
         vsnprintf(buf.data(), buf.size(), fmt, ap);
     }
     output.append(buf.data(), length);
     return length;
 }
References unlikely.
Referenced by openage::renderer::TextRenderer::draw(), openage::Engine::render_text(), and sformat().
Variable Documentation
empty_string
std::string openage::util::empty_string
global empty string, sometimes needed as return value in some std::string &function() return values.
Definition at line 8 of file misc.cpp.
Referenced by openage::util::Path::get_name().
HEX_DIGITS
constexpr const char* openage::util::HEX_DIGITS = "0123456789abcdef"
Definition at line 9 of file repr.cpp.
Referenced by repr().
uint64_s
constexpr size_t openage::util::uint64_s = 8 static
Definition at line 94 of file misc.h.
Referenced by array64_size(), array64_to_array8(), array8_to_array64(), array8_to_uint64(), and uint64_to_array8().