openage: openage::error Namespace Reference
openage::error Namespace Reference
Classes
class Backtrace
struct backtrace_symbol
class Error
class StackAnalyzer
Functions
std::ostream & operator<< (std::ostream &os, const backtrace_symbol &bt_sym)
std::ostream & operator<< (std::ostream &os, const Backtrace &bt)
void demo ()
std::ostream & operator<< (std::ostream &os, const Error &e)
std::string no_ensuring_message ()
SDL_GLContext create_debug_context (SDL_Window *window)
void terminate_handler () noexcept
void sigsegv_handler (int)
void exit_handler ()
void set_exit_ok (bool value)
Variables
constexpr const char * runtime_error_message = "polymorphic openage Error object; catch by reference!"
static bool enable_break_on_create = false
constexpr uint64_t skip_entry_frames = 1
constexpr uint64_t base_skip_frames = 1
Function Documentation
create_debug_context()
SDL_GLContext openage::error::create_debug_context (SDL_Window * window)
Definition at line 45 of file gl_debug.cpp.
{
     SDL_GL_SetAttribute(SDL_GL_CONTEXT_FLAGS, SDL_GL_CONTEXT_DEBUG_FLAG);
     auto ctx = SDL_GL_CreateContext(window);
     if (ctx != nullptr) {
         GLint flags;
         glGetIntegerv(GL_CONTEXT_FLAGS, &flags);
         if (!(flags & GL_CONTEXT_FLAG_DEBUG_BIT))
             throw Error(MSG(err)<< "Failed creating a debug OpenGL context.");
         glDebugMessageControl(GL_DONT_CARE, GL_DONT_CARE, GL_DONT_CARE, 0, nullptr, GL_FALSE);
         glDebugMessageControl(GL_DONT_CARE, GL_DEBUG_TYPE_ERROR, GL_DONT_CARE, 0, nullptr, GL_TRUE);
         glDebugMessageControl(GL_DONT_CARE, GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR, GL_DONT_CARE, 0, nullptr, GL_TRUE);
         glDebugMessageCallback(callback, nullptr);
         glEnable(GL_DEBUG_OUTPUT_SYNCHRONOUS);
     }
     return ctx;
 }
References openage::log::err(), and MSG.
demo()
void openage::error::demo ()
Definition at line 45 of file demo.cpp.
             {
     try {
         bar(0);
     } catch (Error &exc) {
         if (exc.backtrace) {
             exc.trim_backtrace();
         }
         log::log(MSG(info) <<
             "exception_demo: captured the following exception:" << std::endl <<
             exc << std::endl <<
             "exception_demo: end of exception");
     }
 }
References openage::error::Error::backtrace, openage::log::info(), openage::log::log(), MSG, and openage::error::Error::trim_backtrace().
exit_handler()
void openage::error::exit_handler ()
Definition at line 119 of file handlers.cpp.
                     {
     // This handler is registered to run atexit().
     // It is used to catch calls to exit() that occur somewhere inside
     // the running game (while exit_ok == false).
     // exit() should never be invoked directly while the game is running,
     // but some libraries such as libepoxy might do it anyway.
     // The actual proper way of exiting the running game is via throwing
     // an exception or similar action.
     if (exit_ok) { return; }
     std::cout << "\x1b[31;1mexit() was called in an illegal place\x1b[m\n" << std::endl;
 }
no_ensuring_message()
std::string openage::error::no_ensuring_message () inline
Definition at line 149 of file error.h.
 {
     return std::string{};
 }
operator<<() [1/3]
std::ostream & openage::error::operator<< (std::ostream & os, const backtrace_symbol & bt_sym)
Prints a backtrace_symbol object.
Definition at line 16 of file backtrace.cpp.
{
     // imitate the looks of a Python traceback.
     os << "  File ";
     if (bt_sym.filename.empty()) {
         os << '?';
     } else {
         os << '"' << bt_sym.filename << '"';
     }
     if (bt_sym.lineno) {
         os << ", line " << bt_sym.lineno;
     }
     os << ", in ";
     if (bt_sym.functionname.empty()) {
         os << '?';
     } else {
         os << bt_sym.functionname;
     }
     if (bt_sym.pc != nullptr) {
         os << " [" << bt_sym.pc << "]";
     }
     return os;
 }
References openage::error::backtrace_symbol::filename, openage::error::backtrace_symbol::functionname, openage::error::backtrace_symbol::lineno, and openage::error::backtrace_symbol::pc.
operator<<() [2/3]
std::ostream & openage::error::operator<< (std::ostream & os, const Backtrace & bt)
Prints an entire Backtrace object.
Definition at line 49 of file backtrace.cpp.
{
     // imitate the looks of a Python traceback.
     os << "Traceback (most recent call last):" << std::endl;
     bt.get_symbols([&os](const backtrace_symbol *symbol) {
         os << *symbol << std::endl;
     }, true);
     return os;
 }
References openage::error::Backtrace::get_symbols().
operator<<() [3/3]
std::ostream & openage::error::operator<< (std::ostream & os, const Error & e)
Definition at line 89 of file error.cpp.
{
     // output the exception cause
     bool had_a_cause = true;
     try {
         e.rethrow_cause();
         had_a_cause = false;
     } catch (Error &cause) {
         os << cause << std::endl;
     } catch (std::exception &cause) {
         os << util::demangle(typeid(cause).name()) << ": " << cause.what() << std::endl;
     } catch (...) {
         os << "unknown non std::exception cause!" << std::endl;
     }
     if (had_a_cause) {
         os << std::endl << "The above exception was the direct cause of the following exception:" << std::endl << std::endl;
     }
     // output the exception backtrace
     if (e.backtrace) {
         os << *e.backtrace;
     } else {
         os << "origin:" << std::endl;
     }
     // the exception message metadata also holds some "backtrace-like" info
     os << backtrace_symbol{
         e.msg.filename,
         e.msg.lineno,
         e.msg.functionname,
         nullptr} << std::endl;
     os << e.type_name();
     if (not e.msg.text.empty()) {
         os << ": " << e.msg.text;
     }
     return os;
 }
References openage::error::Error::backtrace, openage::util::demangle(), openage::log::message::filename, openage::log::message::functionname, openage::log::message::lineno, openage::error::Error::msg, openage::error::Error::rethrow_cause(), openage::log::message::text, and openage::error::Error::type_name().
set_exit_ok()
OAAPI void openage::error::set_exit_ok (bool value)
Call this to set or unset the atexit error handler.
In order to capture any stray calls to exit() from any place in the game (including libraries), set this to true on startup, and back to false right before termination.
pxd: void set_exit_ok(cppbool value) except +
Definition at line 134 of file handlers.cpp.
{
     exit_ok = value;
 }
sigsegv_handler()
void openage::error::sigsegv_handler (int)
Definition at line 107 of file handlers.cpp.
{
     // In theory, this handler may only call async-signal-safe functions,
     // such as write().
     const char *message = "\n\x1b[31;1mSIGSEGV\x1b[m\n";
     util::ignore_result(write(1, message, strlen(message)));
     // however, everything is broken anyways. can't hurt to try to print
     // more useful info. fuck the police! wheeee!
     std::terminate();
 }
References openage::util::ignore_result(), and openage::util::constexpr_::strlen().
terminate_handler()
void openage::error::terminate_handler () noexcept
Definition at line 69 of file handlers.cpp.
{
     // immediately unset this handler, to avoid endless recursions if
     // terminate() is accidentially triggered from here.
     std::set_terminate(old_terminate_handler);
     std::cout << "\n\x1b[31;1mFATAL: terminate has been called\x1b[m" << std::endl;
     if (std::exception_ptr e_ptr = std::current_exception()) {
         std::cout << "\n\x1b[33muncaught exception\x1b[m\n" << std::endl;
         try {
             std::rethrow_exception(e_ptr);
         } catch (Error &exc) {
             std::cout << exc << std::endl;
         } catch (std::exception &exc) {
             std::cout <<
                 "std::exception of type " <<
                 util::demangle(typeid(exc).name()) <<
                 ": " << exc.what() << std::endl;
         } catch (...) {
             std::cout << "non-standard exception object" << std::endl;
         }
     }
     std::cout << "\n\x1b[33mcurrent stack:\x1b[m\n" << std::endl;
     StackAnalyzer backtrace;
     backtrace.analyze();
     std::cout << backtrace << std::endl;
     // die again to enable debugger functionality.
     // that maybe print some additional useful info that we forgot about.
     // \todo we maybe want to prevent that for end-users.
     std::cout << "\x1b[33mhanding over to the system...\x1b[m\n" << std::endl;
     std::terminate();
 }
References openage::error::StackAnalyzer::analyze(), and openage::util::demangle().
Variable Documentation
base_skip_frames
constexpr uint64_t openage::error::base_skip_frames = 1
Skip this many stack frames, this drops the stackanalyzer function call itself.
Definition at line 25 of file stackanalyzer.cpp.
Referenced by openage::error::StackAnalyzer::analyze().
enable_break_on_create
bool openage::error::enable_break_on_create = false static
Definition at line 15 of file error.cpp.
Referenced by openage::error::Error::debug_break_on_create().
runtime_error_message
constexpr const char* openage::error::runtime_error_message = "polymorphic openage Error object; catch by reference!"
Definition at line 13 of file error.cpp.
Referenced by openage::error::Error::Error().
skip_entry_frames
constexpr uint64_t openage::error::skip_entry_frames = 1
Skip this many frames at the beginning of the trace. Can trim away various libc calls.
Definition at line 19 of file stackanalyzer.cpp.
Referenced by openage::error::StackAnalyzer::analyze().