openage: openage.convert.changelog Namespace Reference
openage.convert.changelog Namespace Reference
Functions
def changes (asset_version, spec_version)
return all changed components since the passed version number.
def test ()
verify only allowed versions are stored in the changes
Variables
string ASSET_VERSION_FILENAME = "asset_version"
string GAMESPEC_VERSION_FILENAME = "gamespec_version"
dictionary COMPONENTS
tuple CHANGES
int ASSET_VERSION = len(CHANGES) - 1
Function Documentation
changes()
def openage.convert.changelog.changes (asset_version, spec_version)
return all changed components since the passed version number.
Definition at line 52 of file changelog.py.
     if asset_version >= len(CHANGES):
         warn("asset version from the future: %d", asset_version)
         warn("current version is: %d", ASSET_VERSION)
         warn("leaving assets as they are.")
         return set()
     changed_components = set()
     first_new_version = asset_version + 1
     # fetch all changes since the detected version
     for version_changes in CHANGES[first_new_version:]:
         changed_components |= version_changes
     if "metadata" not in changed_components:
         if EmpiresDat.get_hash() != spec_version:
             info("game metadata hash changed, need to reconvert it")
             changed_components.add("metadata")
     return changed_components
 def test():
     """
References openage::log.info(), and openage::log.warn().
Referenced by openage::event::demo::PongPlayer.child_changes(), openage::event::demo::PongBall.child_changes(), openage::curve::ValueContainer< T >.set_insert(), and openage::curve::ValueContainer< T >.set_last().
test()
def openage.convert.changelog.test ()
verify only allowed versions are stored in the changes
Definition at line 79 of file changelog.py.
     for entry in CHANGES:
         if entry > COMPONENTS:
             invalid = entry - COMPONENTS
             raise TestError("'{}': invalid changelog entry".format(invalid))
Variable Documentation
ASSET_VERSION
int openage.convert.changelog.ASSET_VERSION = len(CHANGES) - 1
Definition at line 46 of file changelog.py.
ASSET_VERSION_FILENAME
string openage.convert.changelog.ASSET_VERSION_FILENAME = "asset_version"
Definition at line 19 of file changelog.py.
CHANGES
tuple openage.convert.changelog.CHANGES
Initial value:
 =  (
     {"graphics", "sounds"},
     {"sounds"},
     {"graphics"},
     {"interface"},
     {"interface"},
     {"metadata"},
     {"metadata"},
     {"graphics"},
 )
Definition at line 34 of file changelog.py.
COMPONENTS
dictionary openage.convert.changelog.COMPONENTS
Initial value:
 =  {
     "graphics",
     "sounds",
     "metadata",
     "interface",
 }
Definition at line 25 of file changelog.py.
GAMESPEC_VERSION_FILENAME
string openage.convert.changelog.GAMESPEC_VERSION_FILENAME = "gamespec_version"
Definition at line 22 of file changelog.py.