openage: openage Namespace Reference
openage Namespace Reference
Namespaces
__main__
alphamask_shader
assets
audio
cabextract
codegen
console
convert
coord
cppinterface
curve
cvar
datastructure
default_dirs
devmode
error
event
game
gameio
gui
input
job
log
math
options
os
path
py
pyinterface
renderer
rng
shader
simulation
subprocess
teamcolor_shader
test
testing
texture_shader
texturefont_shader
timing
util
Classes
class ActionMode
class ActionModeSignals
class AssetManager
class AttackAbility
class AttackAction
class Attribute
class Attribute< attr_type::armor >
class Attribute< attr_type::attack >
class Attribute< attr_type::building >
class Attribute< attr_type::damaged >
class Attribute< attr_type::direction >
class Attribute< attr_type::dropsite >
class Attribute< attr_type::formation >
class Attribute< attr_type::garrison >
class Attribute< attr_type::heal >
class Attribute< attr_type::hitpoints >
class Attribute< attr_type::multitype >
class Attribute< attr_type::owner >
class Attribute< attr_type::population >
class Attribute< attr_type::projectile >
class Attribute< attr_type::resource >
class Attribute< attr_type::resource_generator >
class Attribute< attr_type::speed >
class Attribute< attr_type::storage >
class Attribute< attr_type::worker >
class AttributeContainer
class Attributes
class BuildAbility
class BuildAction
class BuildingProducer
struct chunk_neighbors
class Civilisation
class ClassicResources
class Command
class ConvertAbility
class ConvertAction
struct coord_chunk_hash
class CreateMode
class DeadAction
class DecayAction
class DrawHandler
class EditorMode
class EditorModeSignals
class Engine
class EngineSignals
class FoundationAction
class GameControl
class GameControlSignals
class GameMain
class GameMainHandle
class GameMainSignals
class GameRenderer
class GameSpec
class GameSpecHandle
class GameSpecSignals
class GarrisonAbility
class GarrisonAction
class GatherAbility
class GatherAction
class Generator
struct gl_texture_buffer
class HealAbility
class HealAction
class HudHandler
class IdleAction
struct influence
struct influence_group
class InputHandler
class IntervalTimer
class LivingProducer
struct main_arguments
class Market
class MovableProducer
class MoveAbility
class MoveAction
struct neighbor_tile
class NyanResearchType
class NyanType
class ObjectProducer
class OutputMode
class OutputModeSignals
class PatrolAbility
class Player
class PlayerScore
class PopulationTracker
class ProjectileAction
class ProjectileProducer
class RadialObject
struct reference_data
class Region
class RenderOptions
class RepairAbility
class RepairAction
class Research
class ResearchAbility
class ResearchAction
class ResearchType
class ResizeHandler
class Resource
class ResourceBundle
class ResourceCost
class ResourceProducer
class Resources
class Score
class ScreenshotManager
class SetPointAbility
class SharedAttributeContainer
class Sound
class SquareObject
class TargetAction
class Team
class TeamScore
class Terrain
struct terrain_meta
struct terrain_render_data
class TerrainChunk
class TerrainObject
class TerrainSearch
class Texture
class TickHandler
struct tile_data
struct tile_draw_data
struct tile_range
class TileContent
class TrainAbility
class TrainAction
class TypePair
class UngarrisonAbility
class UngarrisonAction
class Unit
class UnitAbility
class UnitAction
class UnitContainer
class UnitReference
class UnitSelection
class UnitTexture
class UnitType
class UnitTypeMeta
class UnsharedAttributeContainer
Typedefs
using index_t = int
using unit_type_list = std::vector< std::shared_ptr< UnitType > >
using unit_meta_list = std::vector< std::shared_ptr< UnitTypeMeta > >
using tileset_t = std::unordered_set< coord::tile >
using terrain_t = int
using ability_set = std::bitset< ability_type_size >
using ability_id_t = unsigned int
using graphic_set = std::map< graphic_type, std::shared_ptr< UnitTexture > >
using typeamount_map = std::unordered_map< int, unsigned int >
using id_t = unsigned long int
using time_nsec_t = uint64_t
Enumerations
enum ActionButtonsType {
ActionButtonsType::None, ActionButtonsType::MilitaryUnits, ActionButtonsType::CivilianUnits, ActionButtonsType::BuildMenu,
ActionButtonsType::MilBuildMenu
}
enum cost_type : int { cost_type::constant, cost_type::workforce }
enum game_resource : int {
game_resource::wood = 0, game_resource::food = 1, game_resource::gold = 2, game_resource::stone = 3,
game_resource::RESOURCE_TYPE_COUNT = 4
}
enum score_category : int {
score_category::military, score_category::economy, score_category::technology, score_category::society,
score_category::SCORE_CATEGORY_COUNT
}
enum member_type { member_type::leader, member_type::member, member_type::recruit, member_type::none }
enum tile_state { tile_state::missing, tile_state::existing, tile_state::creatable, tile_state::invalid }
enum object_state { object_state::removed, object_state::floating, object_state::placed, object_state::placed_no_collision }
enum ability_type {
ability_type::move, ability_type::patrol, ability_type::set_point, ability_type::garrison,
ability_type::ungarrison, ability_type::train, ability_type::build, ability_type::research,
ability_type::gather, ability_type::attack, ability_type::convert, ability_type::repair,
ability_type::heal, ability_type::MAX
}
enum graphic_type {
graphic_type::construct, graphic_type::shadow, graphic_type::decay, graphic_type::dying,
graphic_type::standing, graphic_type::walking, graphic_type::carrying, graphic_type::attack,
graphic_type::heal, graphic_type::work
}
enum attr_type {
attr_type::owner, attr_type::population, attr_type::damaged, attr_type::hitpoints,
attr_type::armor, attr_type::attack, attr_type::formation, attr_type::heal,
attr_type::speed, attr_type::direction, attr_type::projectile, attr_type::building,
attr_type::dropsite, attr_type::resource, attr_type::resource_generator, attr_type::worker,
attr_type::storage, attr_type::multitype, attr_type::garrison
}
enum attack_stance { attack_stance::aggressive, attack_stance::defensive, attack_stance::stand_ground, attack_stance::do_nothing }
enum attack_formation { attack_formation::line, attack_formation::staggered, attack_formation::box, attack_formation::flank }
enum command_flag { command_flag::interrupt, command_flag::use_range, command_flag::attack_res }
enum research_category : int { research_category::unit_upgrade, research_category::age_advance, research_category::generic, research_category::RESEARCH_CATEGORY_COUNT }
enum selection_type_t {
selection_type_t::own_units, selection_type_t::own_buildings, selection_type_t::enemy_unit, selection_type_t::enemy_building,
selection_type_t::nothing
}
Functions
coord::tile random_tile (rng::RNG &rng, tileset_t tiles)
int run_game (const main_arguments &args)
std::vector< coord::tile > tile_list (const tile_range &rng)
tile_range building_center (coord::phys3 west, coord::tile_delta size, const Terrain &terrain)
bool complete_building (Unit &u)
std::shared_ptr< Texture > square_outline (coord::tile_delta foundation_size)
std::shared_ptr< Texture > radial_outline (float radius)
TerrainObject * find_near (const TerrainObject &start, std::function< bool(const TerrainObject &)> found, unsigned int search_limit)
TerrainObject * find_in_radius (const TerrainObject &start, std::function< bool(const TerrainObject &)> found, float radius)
std::unordered_set< terrain_t > allowed_terrains (const gamedata::ground_type &restriction)
ResourceBundle create_resource_cost (game_resource resource, int amount)
std::vector< coord::tile > tiles_in_range (coord::camgame p1, coord::camgame p2, const coord::CoordManager &coord)
bool dispatch_command (id_t, const Command &)
unsigned int dir_group (coord::phys3_delta dir, unsigned int angles)
Variables
constexpr coord::tile_delta const neigh_tiles []
constexpr double MARKET_PRICE_D = 3.0
constexpr double MARKET_PRICE_MIN = 20.0
constexpr double MARKET_PRICE_MAX = 9999.0
constexpr double MARKET_TRANSACTION_AMOUNT = 100.0
constexpr coord::tile_delta const neigh_offsets []
constexpr size_t chunk_size = 16
constexpr coord::tile_delta const neigh_tile []
constexpr int PLAYERCOLORED = 1 << 0
constexpr int ALPHAMASKED = 1 << 1
constexpr int ability_type_size = static_cast<int>(ability_type::MAX)
const ability_set ability_all = ability_set().set()
static std::vector< ability_type > ability_priority
string VERSION = "< unknown version; ./configure incomplete >"
string LONGVERSION = VERSION
Detailed Description
This file contains forward declarations for all the coordinate types, as well as their scalar types.
It was created to escape circular-include hell.
Main openage namespace to store all things that make the have to do with the game.
Game entity management, graphics drawing, gui stuff, input handling etc. So basically everything that makes the game work lies in here...
Todo:
make general transformation from iterator algorithm to container algorithm. so much metaprogramming...
This namespace contains constexpr functions, i.e. C++14 functions that are designed to run at compile-time.
Typedef Documentation
ability_id_t
using openage::ability_id_t = typedef unsigned int
Definition at line 48 of file ability.h.
ability_set
using openage::ability_set = typedef std::bitset<ability_type_size>
Definition at line 47 of file ability.h.
graphic_set
using openage::graphic_set = typedef std::map<graphic_type, std::shared_ptr<UnitTexture> >
Collection of graphics attached to each unit.
Definition at line 54 of file attribute.h.
id_t
using openage::id_t = typedef unsigned long int
Type used to identify each single unit in the game.
Definition at line 28 of file unit_container.h.
index_t
using openage::index_t = typedef int
the key type mapped to data objects
Definition at line 29 of file game_spec.h.
terrain_t
using openage::terrain_t = typedef int
type that for terrain ids. it's signed so that -1 can indicate a missing tile.
Todo:
get rid of the signedness.
Definition at line 32 of file terrain.h.
tileset_t
using openage::tileset_t = typedef std::unordered_set<coord::tile>
the type to store a set of tiles
Definition at line 27 of file generator.h.
time_nsec_t
using openage::time_nsec_t = typedef uint64_t
Type to store time in nanoseconds.
Definition at line 12 of file timing.h.
typeamount_map
using openage::typeamount_map = typedef std::unordered_map<int, unsigned int>
An unordered_map with a int key used as a type id and a unsigned int value used as the amount
Definition at line 143 of file attribute.h.
unit_meta_list
using openage::unit_meta_list = typedef std::vector<std::shared_ptr<UnitTypeMeta> >
Definition at line 36 of file game_spec.h.
unit_type_list
using openage::unit_type_list = typedef std::vector<std::shared_ptr<UnitType> >
could use unique ptr
Definition at line 35 of file game_spec.h.
Enumeration Type Documentation
ability_type
enum openage::ability_type strong
roughly the same as command_ability in game data
Enumerator
move
patrol
set_point
garrison
ungarrison
train
build
research
gather
attack
convert
repair
heal
MAX
Definition at line 26 of file ability.h.
{
     move,
     patrol,
     set_point,
     garrison,
     ungarrison,
     train,
     build,
     research,
     gather,
     attack,
     convert,
     repair,
     heal,
     MAX
 };
ActionButtonsType
enum openage::ActionButtonsType strong
Enumerator
None
MilitaryUnits
CivilianUnits
BuildMenu
MilBuildMenu
Definition at line 130 of file game_control.h.
{
     None,
     MilitaryUnits,
     CivilianUnits,
     BuildMenu,
     MilBuildMenu
 };
attack_formation
enum openage::attack_formation strong
List of unit's formation. Effect applys on a group of units.
Enumerator
line
staggered
box
flank
Definition at line 96 of file attribute.h.
{
     line,
     staggered,
     box,
     flank
 };
attack_stance
enum openage::attack_stance strong
List of unit's attack stance. Can be used for buildings also.
Enumerator
aggressive
defensive
stand_ground
do_nothing
Definition at line 85 of file attribute.h.
{
     aggressive,
     defensive,
     stand_ground,
     do_nothing
 };
attr_type
enum openage::attr_type strong
List of unit's attribute types.
Enumerator
owner
population
damaged
hitpoints
armor
attack
formation
heal
speed
direction
projectile
building
dropsite
resource
resource_generator
worker
storage
multitype
garrison
Definition at line 59 of file attribute.h.
                      {
     owner,
     population,
     damaged,
     hitpoints,
     armor,
     attack,
     formation,
     heal,
     speed,
     direction,
     projectile,
     building,
     dropsite,
     resource,
     resource_generator,
     worker,
     storage,
     multitype,
     garrison
 };
command_flag
enum openage::command_flag strong
additional flags which may affect some abilities
Enumerator
interrupt
use_range
attack_res
Definition at line 15 of file command.h.
{
     interrupt, // the user directly issued this command, stopping other actions
     use_range, // move command account for units range
     attack_res // allow attack on a resource object
 };
cost_type
enum openage::cost_type : int strong
Types of dynamic cost calculation (and one constant).
Used in ResourceCost
Todo:
use in TimeCost
Enumerator
constant
Constant resources.
workforce
Dynamic cost based on the workforce.
Definition at line 18 of file cost.h.
                      : int {
     constant,
     workforce
 };
game_resource
enum openage::game_resource : int strong
Enumerator
wood
food
gold
stone
RESOURCE_TYPE_COUNT
Definition at line 94 of file resource.h.
                          : int {
     wood = 0,
     food = 1,
     gold = 2,
     stone = 3,
     RESOURCE_TYPE_COUNT = 4
 };
graphic_type
enum openage::graphic_type strong
Types of action graphics
Enumerator
construct
shadow
decay
dying
standing
walking
carrying
attack
heal
work
Definition at line 36 of file attribute.h.
{
     construct,
     shadow,
     decay,
     dying,
     standing,
     walking,
     carrying,
     attack,
     heal,
     work
 };
member_type
enum openage::member_type strong
Types of membership
Enumerator
leader
member
recruit
none
Definition at line 20 of file team.h.
{
     leader,
     member,
     recruit,
     none // pseudo type
 };
object_state
enum openage::object_state strong
only placed will enable collision checks
Enumerator
removed
floating
placed
placed_no_collision
Definition at line 22 of file terrain_object.h.
{
     removed,
     floating,
     placed,
     placed_no_collision
 };
research_category
enum openage::research_category : int strong
Enumerator
unit_upgrade
Research which modify unit type data.
age_advance
Research which modify unit type data and also progresses the next age. Separate category for simplification.
generic
Research which modify unit type data and something else. (eg. see enemy line of sight)
RESEARCH_CATEGORY_COUNT
Definition at line 15 of file research.h.
                              : int {
     unit_upgrade,
     age_advance,
     generic,
     RESEARCH_CATEGORY_COUNT
 };
score_category
enum openage::score_category : int strong
The categories of sub-scores that sum to a player's score.
Enumerator
military
20% of units killed cost
economy
20% of alive units cost and 10% of resources
technology
20% of researched technologies and 10 for each 1% of map explored
society
20% of Castles and Wonders cost
SCORE_CATEGORY_COUNT
Definition at line 18 of file score.h.
                           : int {
     military,
     economy,
     technology,
     society,
     SCORE_CATEGORY_COUNT
 };
selection_type_t
enum openage::selection_type_t strong
A selection of units always has a type You can't select units from multiple types at once Earlier types have precedence over later types
So you can select a group of units, or a building (or multiple if append is on) Enemy units, enemy buildings and other objects may only be selected one at a time
Enumerator
own_units
own_buildings
enemy_unit
enemy_building
nothing
Definition at line 27 of file selection.h.
{
     own_units,
     own_buildings,
     enemy_unit,
     enemy_building,
     nothing
 };
tile_state
enum openage::tile_state strong
describes the state of a terrain tile.
Enumerator
missing
tile is not created yet
existing
tile is already existing
creatable
tile does not exist but can be created
invalid
tile does not exist and can not be created
Definition at line 81 of file terrain.h.
                       {
     missing,
     existing,
     creatable,
     invalid,
 };
Function Documentation
allowed_terrains()
std::unordered_set< terrain_t > openage::allowed_terrains (const gamedata::ground_type & restriction)
Definition at line 28 of file producer.cpp.
{
     // returns a terrain whitelist for a given restriction
     // you can also define a blacklist for brevity, it will be converted and returned
     std::unordered_set<terrain_t> whitelist;
     std::unordered_set<terrain_t> blacklist;
     // 1, 14, and 15 are water, 2 is shore
     if (restriction == gamedata::ground_type::WATER ||
         restriction == gamedata::ground_type::WATER_0x0D ||
         restriction == gamedata::ground_type::WATER_SHIP_0x03 ||
         restriction == gamedata::ground_type::WATER_SHIP_0x0F) {
         whitelist.insert(1); // water
         whitelist.insert(2); // shore
         whitelist.insert(4); // shallows
         whitelist.insert(14); // medium water
         whitelist.insert(15); // deep water
     }
     else if (restriction == gamedata::ground_type::SOLID) {
         blacklist.insert(1); // water
         blacklist.insert(4); // shallows
         blacklist.insert(14); // medium water
         blacklist.insert(15); // deep water
     }
     else if (restriction == gamedata::ground_type::FOUNDATION ||
         restriction == gamedata::ground_type::NO_ICE_0x08 ||
         restriction == gamedata::ground_type::FOREST) {
         blacklist.insert(1); // water
         blacklist.insert(4); // shallows
         blacklist.insert(14); // medium water
         blacklist.insert(15); // deep water
         blacklist.insert(18); // ice
     }
     else {
         log::log(MSG(warn) << "undefined terrain restriction, assuming solid");
         blacklist.insert(1); // water
         blacklist.insert(4); // shallows
         blacklist.insert(14); // medium water
         blacklist.insert(15); // deep water
     }
     // if we're using a blacklist, fill out a whitelist with everything not on it
     if (blacklist.size() > 0) {
         // Allow all terrains that are not on blacklist
         for (int i = 0; i < 32; ++i) {
             if (blacklist.count(i) == 0) {
                 whitelist.insert(i);
             }
         }
     }
     return whitelist;
 }
References openage::log::log(), MSG, and openage::log::warn().
Referenced by openage::ObjectProducer::place(), and openage::BuildingProducer::place().
building_center()
tile_range openage::building_center (coord::phys3 west, coord::tile_delta size, const Terrain & terrain)
given the west most point of a building foundation and the tile_delta size of the foundation, this will return the tile range covered by the base, which includes start and end tiles, and phys3 center point (used for drawing)
Definition at line 470 of file terrain_object.cpp.
{
     tile_range result;
     // \todo it should be possible that the building is placed on any position,
     //      not just tile positions.
     result.start = west.to_tile();
     result.end   = result.start + size;
     coord::phys2 draw_pos = result.start.to_phys2();
     draw_pos.ne += coord::phys_t(size.ne / 2.0f);
     draw_pos.se += coord::phys_t(size.se / 2.0f);
     result.draw  = draw_pos.to_phys3(terrain);
     return result;
 }
References openage.testing.testing::result(), openage::coord::phys2::to_phys3(), and openage::coord::phys3::to_tile().
Referenced by openage::SquareObject::get_range(), and openage::ActionMode::render().
complete_building()
bool openage::complete_building (Unit &)
sets a building to a fully completed state
Definition at line 487 of file terrain_object.cpp.
{
     if (u.has_attribute(attr_type::building)) {
         auto &build = u.get_attribute<attr_type::building>();
         build.completed = 1.0f;
         // set ground under a completed building
         auto target_location = u.location.get();
         bool placed_ok = target_location->place(build.completion_state);
         if (placed_ok) {
             target_location->set_ground(build.foundation_terrain, 0);
         }
         return placed_ok;
     }
     return false;
 }
References build, building, openage::Unit::get_attribute(), openage::Unit::has_attribute(), and openage::Unit::location.
Referenced by openage::Generator::add_units(), and openage::gameio::load_unit().
create_resource_cost()
ResourceBundle openage::create_resource_cost (game_resource resource, int amount)
Definition at line 83 of file producer.cpp.
{
     ResourceBundle resources = ResourceBundle();
     resources[resource] = amount;
     return resources;
 }
References resource.
dir_group()
unsigned int openage::dir_group (coord::phys3_delta dir, unsigned int angles = 8)
the set of images to used based on unit direction, usually 8 directions to draw for each unit (3 are mirrored)
Parameters
dir a world space direction,
angles number of angles, usually 8
first_angle offset added to angle, modulo number of angles
Returns
image set index
Definition at line 162 of file unit_texture.cpp.
{
     unsigned int first_angle = 5 * angles / 8;
     // normalise direction vector
     double len = std::hypot(dir.ne, dir.se);
     double dir_ne = static_cast<double>(dir.ne) / len;
     double dir_se = static_cast<double>(dir.se) / len;
     // formula to find the correct angle
     return static_cast<unsigned int>(
         round(angles * atan2(dir_se, dir_ne) * (math::INV_PI / 2))
         + first_angle
     ) % angles;
 }
References std::hypot(), and openage::math::INV_PI.
Referenced by openage::UnitTexture::draw().
dispatch_command()
bool openage::dispatch_command (id_t , const Command &)
Definition at line 139 of file unit_container.cpp.
{
     return true;
 }
find_in_radius()
TerrainObject * openage::find_in_radius (const TerrainObject & start, std::function< bool(const TerrainObject &)> found, float radius)
Definition at line 33 of file terrain_search.cpp.
{
     auto terrain = start.get_terrain();
     coord::tile start_tile = start.pos.draw.to_tile3().to_tile();
     TerrainSearch search(terrain, start_tile, radius);
     // next_tile will first return the starting tile, so we need to run it once. We also
     // shouldn't discard this tile - if it isn't useful, ignore it in found
     coord::tile tile = search.next_tile();
     do {
         for (auto o : terrain->get_data(tile)->obj) {
             if (found(*o)) {
                 return o;
             }
         }
         tile = search.next_tile();
         // coord::tile doesn't have a != operator, so we need to use !(a==b)
     } while (!(tile == start_tile));
     return nullptr;
 }
References openage::tile_range::draw, openage::TerrainObject::get_terrain(), openage::TerrainSearch::next_tile(), openage::TerrainObject::pos, openage::coord::tile3::to_tile(), and openage::coord::phys3::to_tile3().
Referenced by openage::BuildAction::on_completion().
find_near()
TerrainObject * openage::find_near (const TerrainObject & start, std::function< bool(const TerrainObject &)> found, unsigned int search_limit)
Definition at line 11 of file terrain_search.cpp.
{
     auto terrain = start.get_terrain();
     auto tile = start.pos.draw.to_tile3().to_tile();
     TerrainSearch search(terrain, tile);
     for (unsigned int i = 0; i < search_limit; ++i) {
         for (auto o : terrain->get_data(tile)->obj) {
             // invalid pointers are removed when the object is deleted
             if (found(*o)) {
                 return o;
             }
         }
         tile = search.next_tile();
     }
     return nullptr;
 }
References openage::tile_range::draw, openage::TerrainObject::get_terrain(), openage::TerrainSearch::next_tile(), openage::TerrainObject::pos, openage::coord::tile3::to_tile(), and openage::coord::phys3::to_tile3().
Referenced by openage::GatherAction::nearest_dropsite(), and openage::GatherAction::on_completion_in_range().
radial_outline()
std::shared_ptr< Texture > openage::radial_outline (float radius)
Generate a isometric circle outline texture
Definition at line 33 of file terrain_outline.cpp.
{
     // additional pixels around the edge
     int border = 4;
     // image size
     int width = border + radius * 96 * 2;
     int height = border + radius * 48 * 2;
     int half_width = width / 2;
     int half_height = height / 2;
     auto image_data = std::make_unique<uint32_t[]>(width * height);
     for (int i = 0; i < width; ++i) {
         for (int j = 0; j < height; ++j) {
             float w_percent = (float) (border+i-half_width) / (float) (half_width-border);
             float h_percent = (float) (border/2+j-half_height) / (float) (half_height-border/2);
             // line drawn where distance to image center == 1
             // line variable is in range 0.0 to 1.0
             float line = 1.0f - fabs(1.0f - std::hypot(w_percent, h_percent));
             unsigned char inten = 255 * pow(line, 32 * width/96);
             image_data[i + j * width] = (inten << 24) | (inten << 16) | (inten << 8) | inten;
         }
     }
     return std::make_shared<Texture>(width, height, std::move(image_data));
 }
References std::hypot(), line, and move.
random_tile()
coord::tile openage::random_tile (rng::RNG & rng, tileset_t tiles)
picks a random tile from a set
Definition at line 17 of file generator.cpp.
{
     if (tiles.empty()) {
         log::log(MSG(err) << "random tile failed");
         return coord::tile{0, 0};
     }
     uint64_t index = rng.random() % tiles.size();
     auto it = std::begin(tiles);
     std::advance(it, index);
     return *it;
 }
References openage::log::err(), openage::log::log(), MSG, and openage::rng::RNG::random().
Referenced by openage::Region::get_tile(), and openage::Region::subset().
run_game()
OAAPI int openage::run_game (const main_arguments & args)
runs the game.
pxd: int run_game(const main_arguments &args) except +
Definition at line 24 of file main.cpp.
{
     log::log(MSG(info)
              << "launching engine with "
              << args.root_path
              << " and fps limit "
              << args.fps_limit);
     util::Timer timer;
     timer.start();
     Engine engine{args.root_path, args.fps_limit, args.gl_debug, "openage"};
     // read and apply the configuration files
     engine.get_cvar_manager().load_all();
     // initialize terminal colors
     std::vector<gamedata::palette_color> termcolors = util::read_csv_file<gamedata::palette_color>(
         args.root_path["assets/converted/termcolors.docx"]
     );
     // \todo move inside the engine
     // \todo support multiple consoles
     console::Console console{&engine};
     console.load_colors(termcolors);
     console.register_to_engine();
     log::log(MSG(info).fmt("Loading time [engine]: %5.3f s", timer.getval() / 1.0e9));
     timer.start();
     {
         // create components that use the engine.
         GameRenderer renderer{&engine};
         log::log(MSG(info).fmt("Loading time   [game]: %5.3f s", timer.getval() / 1.0e9));
         // run main loop
         engine.run();
     }
     log::log(INFO << "cya!");
     return 0;
 }
References openage::main_arguments::fps_limit, openage::util::Timer::getval(), openage::main_arguments::gl_debug, openage::log::info(), INFO, openage::console::Console::load_colors(), openage::log::log(), MSG, openage::main_arguments::root_path, and openage::util::Timer::start().
Referenced by openage.game.main::main().
square_outline()
std::shared_ptr< Texture > openage::square_outline (coord::tile_delta foundation_size)
Generate a isometric square outline texture
Definition at line 12 of file terrain_outline.cpp.
{
     int width = (foundation_size.ne + foundation_size.se) * 48;
     int height = (foundation_size.ne + foundation_size.se) * 24;
     auto image_data = std::make_unique<uint32_t[]>(width * height);
     for (int i = 0; i < width; ++i) {
         for (int j = 0; j < height; ++j) {
             float w_percent = (float) abs(i - (width / 2)) / (float) (width / 2);
             float h_percent = (float) abs(j - (height / 2)) / (float) (height / 2);
             // draw line where (w_percent + h_percent) == 1
             // line variable is in range 0.0 to 1.0
             float line = 1.0f - fabs(1.0f - fabs(h_percent + w_percent));
             unsigned char inten = 255 * pow(line, 16 * width/96);
             image_data[i + j * width] = (inten << 24) | (inten << 16) | (inten << 8) | inten;
         }
     }
     return std::make_shared<Texture>(width, height, std::move(image_data));
 }
References std::abs(), line, and move.
tile_list()
std::vector< coord::tile > openage::tile_list (const tile_range & rng)
get all tiles in the tile range – useful for iterating returns a flat list of tiles between the rectangle enclosed by the tile_range start and end tiles
Definition at line 445 of file terrain_object.cpp.
{
     std::vector<coord::tile> tiles;
     coord::tile check_pos = rng.start;
     while (check_pos.ne < rng.end.ne) {
         while (check_pos.se < rng.end.se) {
             tiles.push_back(check_pos);
             check_pos.se += 1;
         }
         check_pos.se = rng.start.se;
         check_pos.ne += 1;
     }
     // a case when the objects radius is zero
     if (tiles.empty()) {
         tiles.push_back(rng.start);
     }
     return tiles;
     // a case when the objects radius is zero
     if (tiles.empty()) {
         tiles.push_back(rng.start);
     }
     return tiles;
 }
References openage::tile_range::end, and openage::tile_range::start.
Referenced by openage::SquareObject::contains(), openage::ObjectProducer::place(), openage::BuildingProducer::place(), openage::TerrainObject::place(), openage::ProjectileProducer::place(), openage::UnitType::place_beside(), openage::TerrainObject::place_unchecked(), and openage::TerrainObject::remove().
tiles_in_range()
std::vector< coord::tile > openage::tiles_in_range (coord::camgame p1, coord::camgame p2, const coord::CoordManager & coord)
Definition at line 331 of file selection.cpp.
{
     // the remaining corners
     coord::camgame p3 = coord::camgame{p1.x, p2.y};
     coord::camgame p4 = coord::camgame{p2.x, p1.y};
     coord::camgame pts[4] {p1, p2, p3, p4};
     // find the range of tiles covered
     coord::tile t1 = pts[0].to_tile(coord);
     coord::tile min = t1;
     coord::tile max = t1;
     for (unsigned i = 1; i < 4; ++i) {
         coord::tile t = pts[i].to_tile(coord);
         min.ne = std::min(min.ne, t.ne);
         min.se = std::min(min.se, t.se);
         max.ne = std::max(max.ne, t.ne);
         max.se = std::max(max.se, t.se);
     }
     // find all units in the boxed region
     std::vector<coord::tile> tiles;
     coord::tile check_pos = min;
     while (check_pos.ne <= max.ne) {
         while (check_pos.se <= max.se) {
             tiles.push_back(check_pos);
             check_pos.se += 1;
         }
         check_pos.se = min.se;
         check_pos.ne += 1;
     }
     return tiles;
 }
References openage::coord::tests::coord(), openage::console::tests::max(), std::max(), and std::min().
Referenced by openage::UnitSelection::select_space().
Variable Documentation
ability_all
const ability_set openage::ability_all = ability_set().set()
all bits set to 1
Definition at line 53 of file ability.h.
ability_priority
std::vector<ability_type> openage::ability_priority static
Initial value:
{
    ability_type::gather,
    ability_type::convert,
    ability_type::repair,
    ability_type::heal,
    ability_type::attack,
    ability_type::build,
    ability_type::move,
    ability_type::patrol,
    ability_type::garrison,
    ability_type::ungarrison,
    ability_type::train,
    ability_type::research,
    ability_type::set_point,
}
the order abilities should be used when available
Definition at line 58 of file ability.h.
Referenced by openage::Unit::queue_cmd().
ability_type_size
constexpr int openage::ability_type_size = static_cast<int>(ability_type::MAX)
a container where each ability uses 1 bit
Definition at line 46 of file ability.h.
ALPHAMASKED
constexpr int openage::ALPHAMASKED = 1 << 1
Definition at line 46 of file texture.h.
Referenced by openage::Texture::draw(), and openage::Terrain::draw().
chunk_size
constexpr size_t openage::chunk_size = 16
the number of tiles per direction on a chunk
Definition at line 24 of file terrain_chunk.h.
Referenced by openage::TerrainChunk::get_size(), openage::audio::OpusDynamicLoader::load_chunk(), openage::TerrainChunk::neighbor_id_by_pos(), openage::TerrainChunk::tile_position(), and openage::TerrainChunk::tile_position_neigh().
LONGVERSION
tuple openage.LONGVERSION = VERSION
Definition at line 28 of file __init__.py.
MARKET_PRICE_D
constexpr double openage::MARKET_PRICE_D = 3.0
Definition at line 11 of file market.h.
Referenced by openage::Market::buy(), and openage::Market::sell().
MARKET_PRICE_MAX
constexpr double openage::MARKET_PRICE_MAX = 9999.0
Definition at line 13 of file market.h.
Referenced by openage::Market::buy().
MARKET_PRICE_MIN
constexpr double openage::MARKET_PRICE_MIN = 20.0
Definition at line 12 of file market.h.
Referenced by openage::Market::sell().
MARKET_TRANSACTION_AMOUNT
constexpr double openage::MARKET_TRANSACTION_AMOUNT = 100.0
Definition at line 14 of file market.h.
Referenced by openage::Market::buy(), and openage::Market::sell().
neigh_offsets
constexpr coord::tile_delta const openage::neigh_offsets[]
Initial value:
= {
    { 1, -1},
    { 1,  0},
    { 1,  1},
    { 0,  1},
    {-1,  1},
    {-1,  0},
    {-1, -1},
    { 0, -1}
}
coordinate offsets for getting tile neighbors by their id.
Definition at line 66 of file terrain.h.
Referenced by openage::Terrain::get_chunk_neighbors(), and openage::Terrain::get_neighbors().
neigh_tile
constexpr coord::tile_delta const openage::neigh_tile[]
Initial value:
= {
    {0,  1},
    {0, -1},
    {1,  0},
    {-1, 0}
}
Definition at line 25 of file terrain_search.h.
Referenced by openage::TerrainSearch::next_tile().
neigh_tiles
constexpr coord::tile_delta const openage::neigh_tiles[]
Initial value:
= {
    { 1,  0},
    {-1,  0},
    { 0,  1},
    { 0, -1}
}
the four directions available for 2d tiles
Definition at line 37 of file generator.h.
Referenced by openage::Region::subset().
PLAYERCOLORED
constexpr int openage::PLAYERCOLORED = 1 << 0
Definition at line 45 of file texture.h.
Referenced by openage::UnitTexture::draw(), openage::Texture::draw(), and openage::UnitTexture::sample().
VERSION
string openage.VERSION = "< unknown version; ./configure incomplete >"
Definition at line 27 of file __init__.py.