openage: openage::coord::tests Namespace Reference
openage::coord::tests Namespace Reference
Functions
void coord ()
Function Documentation
coord()
void openage::coord::tests::coord ()
test method for the base CoordXY* classes.
Definition at line 36 of file coord_test.cpp.
              {
     // test comparision
     TESTEQUALS(TestCoordsAbsolute(3, 4) == TestCoordsAbsolute(3, 4), true);
     TESTEQUALS(TestCoordsAbsolute(3, 4) != TestCoordsAbsolute(3, 4), false);
     TESTEQUALS(TestCoordsAbsolute(3, 4) == TestCoordsAbsolute(3, 5), false);
     TESTEQUALS(TestCoordsAbsolute(3, 4) == TestCoordsAbsolute(4, 4), false);
     TESTEQUALS(TestCoordsAbsolute(3, 4) != TestCoordsAbsolute(3, 5), true);
     TESTEQUALS(TestCoordsRelative(3, 4) == TestCoordsRelative(3, 4), true);
     TESTEQUALS(TestCoordsRelative(3, 4) != TestCoordsRelative(3, 4), false);
     TESTEQUALS(TestCoordsRelative(3, 4) == TestCoordsRelative(3, 5), false);
     TESTEQUALS(TestCoordsRelative(3, 4) == TestCoordsRelative(4, 4), false);
     TESTEQUALS(TestCoordsRelative(3, 4) != TestCoordsRelative(3, 5), true);
     // test copy constructor / assignment operator
     TestCoordsAbsolute a0(1, 2);
     TestCoordsRelative r0(3, 4);
     TESTEQUALS(a0, TestCoordsAbsolute(1, 2));
     TESTEQUALS(r0, TestCoordsRelative(3, 4));
     TestCoordsAbsolute a1{a0};
     TestCoordsRelative r1{r0};
     TESTEQUALS(a0, a1);
     TESTEQUALS(r0, r1);
     a1 = a0;
     r1 = r0;
     TESTEQUALS(a0, a1);
     TESTEQUALS(r0, r1);
     // test unary +/-
     TESTEQUALS(-r0, TestCoordsRelative(-3, -4));
     TESTEQUALS(+r0, TestCoordsRelative(3, 4));
     // test addition
     TESTEQUALS(r0 + r0, TestCoordsRelative(6, 8));
     TESTEQUALS(a0 + r0, TestCoordsAbsolute(4, 6));
     TESTEQUALS(r0 + a0, TestCoordsAbsolute(4, 6));
     // test scalar multiplication and division
     TESTEQUALS(r0 * 3, TestCoordsRelative(9, 12));
     TESTEQUALS(r0 / 3, TestCoordsRelative(1, 1));
     // test string representation
     util::FString s;
     s << TestCoordsAbsolute(1, 2);
     TESTEQUALS(std::string(s), "[x: 1, y: 2]");
     s.reset();
     s << TestCoordsRelative(3, 4);
     TESTEQUALS(std::string(s), "(x: 3, y: 4)");
 }
References openage::util::FString::reset(), and TESTEQUALS.
Referenced by openage::UnitTexture::draw(), openage::ActionMode::on_game_control_set(), openage::UnitTexture::sample(), and openage::tiles_in_range().