openage: openage.util.math Namespace Reference
openage.util.math Namespace Reference
Functions
def clamp (val, minval, maxval)
clamps val to be at least minval, and at most maxval.
Variables
INF = float("+inf")
int TAU = 2 * math.pi
int DEGSPERRAD = TAU / 360
Function Documentation
clamp()
def openage.util.math.clamp (val, minval, maxval)
clamps val to be at least minval, and at most maxval.
clamp(9, 3, 7)
7
clamp(1, 3, 7)
3
clamp(5, 3, 7)
5
Definition at line 29 of file math.py.
References openage::console::tests.max(), and std.min().
Referenced by openage.util.filelike.stream.StreamSeekBuffer.read(), openage.util.filelike.stream.StreamFragment.read(), and openage::log.verbosity_to_level().
Variable Documentation
DEGSPERRAD
int openage.util.math.DEGSPERRAD = TAU / 360
Definition at line 16 of file math.py.
Referenced by openage::util::Quaternion< T >.from_deg().
INF
openage.util.math.INF = float("+inf")
Definition at line 12 of file math.py.
TAU
int openage.util.math.TAU = 2 * math.pi
Definition at line 15 of file math.py.