openage: openage::gui Namespace Reference
openage::gui Namespace Reference
Classes
class ActionModeLink
class ActionsListModel
Model used for the Action Buttons to render (e.g.
class AssetManagerLink
class CategoryContentsListModel
Adaptor for the contents of a category of the Civilisation.
class CreateModeLink
class EditorModeLink
class EngineLink
class EngineQMLInfo
This container is attached to the QML engine.
class GameControlLink
class GameCreator
class GameCreatorSignals
class GameMainLink
class GameSaver
class GameSaverSignals
class GameSpecLink
class GeneratorLink
class GUI
Main entry point for the openage Qt-based user interface.
class GuiApplicationWithLogger
Houses gui logic event queue and attaches to game logger.
class GuiFilledTextureHandles
Stores pointers to game texture handlers given to the Qt.
class GuiFilledTextureHandleUser
class GuiGameSpecImageProvider
class GuiGameSpecImageProviderByFilenameImpl
Exposes game textures to the Qt by their file name.
class GuiGameSpecImageProviderByGraphicIdImpl
Exposes game textures to the Qt by their id.
class GuiGameSpecImageProviderByIdImpl
Base for providers that expose textures to the Qt by their id.
class GuiGameSpecImageProviderByTerrainIdImpl
Exposes terrain textures to the Qt by their id.
class GuiGameSpecImageProviderImpl
Exposes game textures to the Qt.
class GuiImageProviderLink
class GuiStandaloneSubtexture
class GuiTexture
class GuiTextureFactory
class MainArgsLink
Used to make arguments of the game available in QML.
class OutputModeLink
class ResourcesListModel
Resource table for the gui.
class SizedTextureHandle
class TextureHandle
Functions
void gui_log (QtMsgType type, const QMessageLogContext &context, const QString &msg)
std::unique_ptr< QSGTexture > make_standalone_subtexture (GLuint id, const QSize &size)
bool isAtlasTexture (const TextureHandle &texture_handle)
QSize textureSize (const SizedTextureHandle &texture_handle)
QSize native_size (const TextureHandle &texture_handle)
QSize aspect_fit_size (const TextureHandle &texture_handle, const QSize &requested_size)
The sourceSize property of the Image QML element ends up here for checking.
Variables
const int reg_path = qRegisterMetaType<util::Path>("util::Path")
Function Documentation
aspect_fit_size()
QSize openage::gui::aspect_fit_size (const TextureHandle & texture_handle, const QSize & requested_size)
The sourceSize property of the Image QML element ends up here for checking.
Parameters
requested_size sourceSize if used in Image QML element.
Returns
if !requested_size.isValid() or requested_size.isNull() then native size, otherwise fit in the requested_size (zero component in requested_size means unbounded).
Definition at line 43 of file gui_texture_handle.cpp.
{
     const QSize size = native_size(texture_handle);
     if (requested_size.isValid()) {
         const QSize bounding_size(requested_size.width() > 0 ? requested_size.width() : size.width(), requested_size.height() > 0 ? requested_size.height() : size.height());
         // If requested_size.isEmpty() then the caller don't care how big one or two dimensions can grow.
         return size.scaled(bounding_size, requested_size.isEmpty() && (requested_size.width() > size.width() || requested_size.height() > size.height()) ? Qt::KeepAspectRatioByExpanding : Qt::KeepAspectRatio);
     } else {
         return size;
     }
 }
References native_size().
Referenced by openage::gui::GuiGameSpecImageProviderImpl::overwrite_texture_handle().
gui_log()
void openage::gui::gui_log (QtMsgType type, const QMessageLogContext & context, const QString & msg)
Definition at line 12 of file gui_log.cpp.
{
     log::level msg_lvl;
     switch (type) {
     case QtDebugMsg:
         msg_lvl = log::level::dbg;
         break;
     case QtInfoMsg:
         msg_lvl = log::level::info;
         break;
     case QtWarningMsg:
         msg_lvl = log::level::warn;
         break;
     case QtCriticalMsg:
         msg_lvl = log::level::err;
         break;
     case QtFatalMsg:
         msg_lvl = log::level::crit;
         break;
     default:
         msg_lvl = log::level::warn;
         break;
     }
     log::MessageBuilder builder{
         context.file != nullptr ? context.file : "<unknown file>",
         static_cast<unsigned>(context.line),
             context.function != nullptr ? context.function : "<unknown function>",
             msg_lvl
     };
     // \todo maybe it's not UTF-8
     // \todo Qt should become a LogSource
     log::log(builder << msg.toUtf8().data());
     if (type == QtFatalMsg)
         abort();
 }
References openage::log::crit(), openage::log::dbg(), openage::log::err(), openage::log::info(), openage::log::log(), and openage::log::warn().
isAtlasTexture()
bool openage::gui::isAtlasTexture (const TextureHandle & texture_handle)
Definition at line 24 of file gui_texture_handle.cpp.
{
     return texture_handle.subid >= 0 && texture_handle.texture->get_subtexture_count() > 1;
 }
References openage::Texture::get_subtexture_count(), openage::gui::TextureHandle::subid, and openage::gui::TextureHandle::texture.
Referenced by openage::gui::GuiTexture::isAtlasTexture(), and native_size().
make_standalone_subtexture()
std::unique_ptr< QSGTexture > openage::gui::make_standalone_subtexture (GLuint id, const QSize & size)
Definition at line 9 of file gui_make_standalone_subtexture.cpp.
{
     return std::make_unique<GuiStandaloneSubtexture>(id, size);
 }
Referenced by openage::gui::GuiTexture::removedFromAtlas().
native_size()
QSize openage::gui::native_size (const TextureHandle & texture_handle)
Definition at line 32 of file gui_texture_handle.cpp.
{
     auto tex = texture_handle.texture;
     if (isAtlasTexture(texture_handle)) {
         auto sub = tex->get_subtexture(texture_handle.subid);
         return QSize(sub->w, sub->h);
     } else {
         return QSize(tex->w, tex->h);
     }
 }
References openage::Texture::get_subtexture(), isAtlasTexture(), openage::gui::TextureHandle::subid, and openage::gui::TextureHandle::texture.
Referenced by aspect_fit_size().
textureSize()
QSize openage::gui::textureSize (const SizedTextureHandle & texture_handle)
Definition at line 28 of file gui_texture_handle.cpp.
{
     return texture_handle.size;
 }
References openage::gui::SizedTextureHandle::size.
Referenced by openage::gui::GuiFilledTextureHandles::fill_all_handles_with_texture(), openage::gui::GuiTextureFactory::textureSize(), and openage::gui::GuiTexture::textureSize().
Variable Documentation
reg_path
const int openage::gui::reg_path = qRegisterMetaType<util::Path>("util::Path")
Definition at line 10 of file registrations.cpp.