openage: openage::pyinterface Namespace Reference
openage::pyinterface Namespace Reference
Namespaces
tests
Classes
class Func
class PyException
class PyExceptionBacktrace
class PyIfFunc
class PyObjectRef
Typedefs
template<typename RT >
using Func0 = Func< RT >
template<typename RT , typename AT0 >
using Func1 = Func< RT, AT0 >
template<typename RT , typename AT0 , typename AT1 >
using Func2 = Func< RT, AT0, AT1 >
template<typename RT , typename AT0 , typename AT1 , typename AT2 >
using Func3 = Func< RT, AT0, AT1, AT2 >
template<typename RT , typename AT0 , typename AT1 , typename AT2 , typename AT3 >
using Func4 = Func< RT, AT0, AT1, AT2, AT3 >
template<typename RT , typename AT0 , typename AT1 , typename AT2 , typename AT3 , typename AT4 >
using Func5 = Func< RT, AT0, AT1, AT2, AT3, AT4 >
using PyObj = PyObjectRef
Functions
void set_exc_translation_funcs (void(*raise_cpp_error_impl)(Error *), void(*raise_cpp_pyexception_impl)(PyException *), bool(*check_for_py_exception_impl)(), void(*describe_py_exception_impl)(PyException *))
void translate_exc_cpp_to_py ()
void translate_exc_py_to_cpp ()
void init_exc_message (log::message *msg, const std::string &filename, unsigned int lineno, const std::string &functionname) noexcept
std::ostream & operator<< (std::ostream &os, const PyObjectRef &ref)
void add_py_if_component (void *thisptr, std::function< bool()> checker)
void destroy_py_if_component (void *thisptr)
void check ()
Variables
void(* raise_cpp_error)(Error *) = nullptr
void(* raise_cpp_pyexception)(PyException *) = nullptr
void(* describe_py_exception)(PyException *) = nullptr
bool(* check_for_py_exception)() = nullptr
PyIfFunc< void, PyObject *, Func< void, const error::backtrace_symbol * > > pyexception_bt_get_symbols
PyIfFunc< void, PyObject * > py_xincref
PyIfFunc< void, PyObject * > py_xdecref
PyIfFunc< std::string, PyObject * > py_str
PyIfFunc< std::string, PyObject * > py_repr
PyIfFunc< std::string, PyObject * > py_bytes
PyIfFunc< int, PyObject * > py_len
PyIfFunc< bool, PyObject * > py_callable
PyIfFunc< void, PyObjectRef *, PyObject * > py_call0
PyIfFunc< void, PyObjectRef *, PyObject *, std::vector< PyObject * > & > py_calln
PyIfFunc< bool, PyObject *, std::string > py_hasattr
PyIfFunc< void, PyObjectRef *, PyObject *, std::string > py_getattr
PyIfFunc< void, PyObject *, std::string, PyObject * > py_setattr
PyIfFunc< bool, PyObject *, PyObject * > py_isinstance
PyIfFunc< bool, PyObject * > py_to_bool
PyIfFunc< int64_t, PyObject * > py_to_int
PyIfFunc< void, PyObject *, Func< void, std::string > > py_dir
PyIfFunc< bool, PyObject *, PyObject * > py_equals
PyIfFunc< void, PyObject *, std::string > py_exec
PyIfFunc< void, PyObject *, PyObjectRef *, std::string > py_eval
PyIfFunc< void, PyObject *, PyObjectRef *, PyObject * > py_get
PyIfFunc< bool, PyObject *, PyObject * > py_in
PyIfFunc< void, PyObject *, PyObjectRef * > py_type
PyIfFunc< std::string, PyObject * > py_modulename
PyIfFunc< std::string, PyObject * > py_classname
PyIfFunc< void, PyObjectRef *, const std::string & > py_builtin
PyIfFunc< void, PyObjectRef *, const std::string & > py_import
PyIfFunc< void, PyObjectRef *, const std::string & > py_createstr
PyIfFunc< void, PyObjectRef *, const std::string & > py_createbytes
PyIfFunc< void, PyObjectRef *, int > py_createint
PyIfFunc< void, PyObjectRef * > py_createdict
PyIfFunc< void, PyObjectRef * > py_createlist
PyObjectRef None
PyObjectRef True
PyObjectRef False
Typedef Documentation
Func0
template<typename RT > using openage::pyinterface::Func0 = typedef Func<RT>
Definition at line 275 of file functional.h.
Func1
template<typename RT , typename AT0 > using openage::pyinterface::Func1 = typedef Func<RT, AT0>
Definition at line 296 of file functional.h.
Func2
template<typename RT , typename AT0 , typename AT1 > using openage::pyinterface::Func2 = typedef Func<RT, AT0, AT1>
Definition at line 318 of file functional.h.
Func3
template<typename RT , typename AT0 , typename AT1 , typename AT2 > using openage::pyinterface::Func3 = typedef Func<RT, AT0, AT1, AT2>
Definition at line 340 of file functional.h.
Func4
template<typename RT , typename AT0 , typename AT1 , typename AT2 , typename AT3 > using openage::pyinterface::Func4 = typedef Func<RT, AT0, AT1, AT2, AT3>
Definition at line 362 of file functional.h.
Func5
template<typename RT , typename AT0 , typename AT1 , typename AT2 , typename AT3 , typename AT4 > using openage::pyinterface::Func5 = typedef Func<RT, AT0, AT1, AT2, AT3, AT4>
Definition at line 385 of file functional.h.
PyObj
using openage::pyinterface::PyObj = typedef PyObjectRef
convenience alias
Definition at line 282 of file pyobject.h.
Function Documentation
add_py_if_component()
void openage::pyinterface::add_py_if_component (void * thisptr, std::function< bool()> checker)
Adds a Python interface component. Usually, you'd call this from a component's constructor.
thisptr is a pointer to the component object.
checker is a function that must have defined behavior until destroy_py_if_component has been called for thisptr. It shall return true if the object has been properly initialized, and shall not throw any exceptions.
Definition at line 44 of file setup.cpp.
{
     state &checkers = state::get();
     std::unique_lock<std::mutex> lock{checkers.lock};
     // enforce that the object has an associated symbol name.
     if (unlikely(not util::is_symbol(thisptr))) {
         throw Error(
             MSG(err) <<
             "Can't instantiate py interface component as non-global object. " <<
             "Attempted instantiation at " <<
             util::symbol_name(thisptr) << ".",
             true);
     }
     checkers.map[thisptr] = checker;
 }
References openage::log::err(), openage::util::is_symbol(), lock, MSG, openage::util::symbol_name(), and unlikely.
Referenced by openage::pyinterface::PyIfFunc< ReturnType, ArgTypes >::PyIfFunc().
check()
OAAPI void openage::pyinterface::check ()
Checks whether all objects that have been registered via add_py_if_component have been properly initialized.
If not, or if components have been destroyed already, raises an exception that contains the component names.
May be called only once.
pxd: void check() except +
Definition at line 73 of file setup.cpp.
              {
     state &checkers = state::get();
     std::unique_lock<std::mutex> lock{checkers.lock};
     if (checkers.check_performed) {
         throw Error(MSG(err) <<
             "py interface initialization check has already been performed. "
             "fix your init code.");
     }
     checkers.check_performed = true;
     bool error_found = false;
     auto msg = MSG(err);
     msg << "Fix your init code: ";
     if (not checkers.destroyed_components.empty()) {
         msg << std::endl <<
             "Py interface components have been de-initialized before "
             "initialization had even been completed:";
         for (void *thisptr : checkers.destroyed_components) {
             msg << std::endl << "\t" << util::symbol_name(thisptr);
         }
         error_found = true;
     }
     checkers.destroyed_components.clear();
     bool first = true;
     for (auto &checker : checkers.map) {
         if (not checker.second()) {
             if (first) {
                 msg << std::endl <<
                     "The following components have not been initialized:";
                 first = false;
                 error_found = true;
             }
             msg << std::endl << "\t" << util::symbol_name(checker.first);
         }
     }
     checkers.map.clear();
     if (error_found) {
         throw Error(msg);
     }
 }
References openage::log::err(), lock, MSG, and openage::util::symbol_name().
Referenced by openage.cppinterface.setup::setup().
destroy_py_if_component()
void openage::pyinterface::destroy_py_if_component (void * thisptr)
Signals that an interface component that has been previously registered via add_py_if_component is no longer valid, e.g. because its destructor has been invoked. Usually, you'd call this from a component's destructor.
Definition at line 63 of file setup.cpp.
{
     state &checkers = state::get();
     std::unique_lock<std::mutex> lock{checkers.lock};
     checkers.destroyed_components.insert(thisptr);
     checkers.map.erase(thisptr);
 }
References lock.
Referenced by openage::pyinterface::PyIfFunc< ReturnType, ArgTypes >::~PyIfFunc().
init_exc_message()
OAAPI void openage::pyinterface::init_exc_message (log::message * msg, const std::string & filename, unsigned int lineno, const std::string & functionname) noexcept
For use by Python, to initialize a message's meta data.
Initializes all values.
pxd: void init_exc_message(message *msg, string filename, unsigned int lineno, string functionname) noexcept
Definition at line 137 of file exctranslate.cpp.
{
     try {
         msg->init_with_metadata_copy(filename, functionname);
     } catch (...) {
         // we cannot afford to raise an exception from this function;
         // this is part of the exception translation code.
         std::cout << "[WTF] failed so init exception message!" << std::endl;
     }
     msg->lvl = log::level::err;
     msg->lineno = lineno;
 }
References openage::log::err(), and openage::util::filename().
operator<<()
std::ostream & openage::pyinterface::operator<< (std::ostream & os, const PyObjectRef & ref)
Stream operator for printing PyObjects
Definition at line 261 of file pyobject.cpp.
{
     if (unlikely(ref.get_ref() == nullptr)) {
         os << "PyObjectRef[null]";
     } else {
         os << "PyObjectRef[" << ref.repr() << "]";
     }
     return os;
 }
References ref, and unlikely.
set_exc_translation_funcs()
OAAPI void openage::pyinterface::set_exc_translation_funcs (void(*)(Error *) raise_cpp_error, void(*)(PyException *) raise_cpp_pyexception, bool(*)() check_for_py_exception, void(*)(PyException *) describe_py_exception)
Installs the basic interface functions that are used for exception translation.
No PyIfFunc wrappers can be used here, because those internally rely on exception translation themselves, which would lead to
infinite loops
immediate back-conversion of raised Python CPPException objects
Thus, we instead offer this setter function, to be called during openage.cppinterface.exctranslate.setup().
Parameters
raise_cpp_error Raises the given C++ Exception object as a Python exception. called by translate_exc_cpp_to_py.
raise_cpp_pyexception Raises the given C++ PyException object as a Python exception. called by translate_exc_cpp_to_py.
The PyException still contains a reference to the original Python object that was translated by describe_py_exception - we just use that.
Invoked by openage::pyinterface::cpp_to_py.
Parameters
check_for_py_exception Used by translate_exc_cpp_to_py to check whether there is a currently-active Python exception.
describe_py_exception Used by translate_exc_cpp_to_py to gather information about the current Python exception.
Calls PyErr_Fetch and stores all sorts of information in the PyException. The current Python exception is cleared in the process.
If the current Python exception had a cause, that cause is set as the new active exception. Call check_exception() afterwards to test whether that has happend.
If there's no currently-active Python Exception, the behavior is undefined; make sure to call check_exception() before.
Afterwards, the PyException is ready for throwing.
pxd:
void set_exc_translation_funcs(void (*)(Error *) except * with gil, void (*)(PyException *) except * with gil, cppbool (*)() with gil, void (*)(PyException *) except * with gil) noexcept
Definition at line 31 of file exctranslate.cpp.
{
     raise_cpp_error = raise_cpp_error_impl;
     raise_cpp_pyexception = raise_cpp_pyexception_impl;
     check_for_py_exception = check_for_py_exception_impl;
     describe_py_exception = describe_py_exception_impl;
 }
References check_for_py_exception, describe_py_exception, raise_cpp_error, and raise_cpp_pyexception.
translate_exc_cpp_to_py()
OAAPI void openage::pyinterface::translate_exc_cpp_to_py ()
Analyzes the current C++ exception, and creates and raises an analogous Python CPPException object.
If there's no current C++ exception, this terminates the program non-gracefully (std::terminate).
Designed to be called by auto-generated Cython code; Do not use in any other way.
Definition at line 47 of file exctranslate.cpp.
{
     try {
         // when we reach this, cython caught an error.
         // and we're now in the handler.
         // to continue, first rethrow the exception so we can analyze it:
         throw;
     } catch (PyException &exc) {
         if (unlikely(raise_cpp_pyexception == nullptr)) {
             throw Error(MSG(err) <<
                 "raise_pyexception_in_py is uninitialized; "
                 "can't translate C++ exception to Python exception.",
                 false, false);
         }
         // handle the python object directly by PyErr_SetObject
         raise_cpp_pyexception(&exc);
     } catch (Error &exc) {
         if (unlikely(raise_cpp_error == nullptr)) {
             throw Error(MSG(err) <<
                 "raise_error_in_py is uninitialized; "
                 "can't translate C++ exception to Python exception.",
                 false, false);
         }
         // translate the exception to python
         // = insert it in pythons backtrace
         raise_cpp_error(&exc);
     }
     // we also need to catch std::exception so that rethrown causes are handled
     // properly. otherwise they just crash everything. not good.
     catch (const std::exception &exc) {
         // the std::exception doesn't contain a stack trace...
         // as we're at a special place we must not generate the current
         // stack trace either. and we _must not_ store the causing
         // exception, as the whole point of this code is to get rid
         // of std::exceptions.
         Error error{
             ERR << "std::exception: "
                 << util::demangle(typeid(exc).name())
                 << ": "
                 << exc.what(),
             false,
             false
         };
         raise_cpp_error(&error);
     }
     /*
      * all other exceptions are more than unexpected;
      * they don't contain any useful stack trace information,
      * so the safest course of action is not to catch them.
      * That way, terminate() is called, where we can analyze the stack
      * trace and debug the issue in gdb.
      */
 }
References openage::util::demangle(), openage::log::err(), ERR, MSG, raise_cpp_error, raise_cpp_pyexception, and unlikely.
translate_exc_py_to_cpp()
OAAPI void openage::pyinterface::translate_exc_py_to_cpp ()
Analyzes the current Python exception, and creates and throws an analogous C++ PyException object.
Works, and is designed to be used in, situations where there is no current Python exception (it's a no-op then).
Definition at line 110 of file exctranslate.cpp.
{
     if (unlikely(describe_py_exception == nullptr)) {
         throw Error(MSG(err) <<
             "describe_py_exception is uninitialized; "
             "can't check for and translate Python exception to C++ exception.");
     }
     if (likely(not check_for_py_exception())) {
         // no exception has occurred.
         return;
     }
     PyException pyex;
     describe_py_exception(&pyex);
     // recurse to throw a possible cause.
     try {
         translate_exc_py_to_cpp();
     } catch (...) {
         pyex.store_cause();
     }
     // throw exception without cause.
     throw pyex;
 }
References check_for_py_exception, describe_py_exception, openage::log::err(), likely, MSG, openage::error::Error::store_cause(), and unlikely.
Referenced by openage::pyinterface::Func< ReturnType, ArgTypes ... >::bind_catchexcept_impl().
Variable Documentation
check_for_py_exception
bool(* openage::pyinterface::check_for_py_exception) () = nullptr
Definition at line 28 of file exctranslate.cpp.
Referenced by set_exc_translation_funcs(), and translate_exc_py_to_cpp().
describe_py_exception
void(* openage::pyinterface::describe_py_exception) (PyException *) = nullptr
Definition at line 27 of file exctranslate.cpp.
Referenced by set_exc_translation_funcs(), and translate_exc_py_to_cpp().
False
OAAPI PyObjectRef openage::pyinterface::False
Definition at line 308 of file pyobject.cpp.
Referenced by openage::pyinterface::tests::pyobject().
None
OAAPI PyObjectRef openage::pyinterface::None
Definition at line 306 of file pyobject.cpp.
py_builtin
OAAPI PyIfFunc< void, PyObjectRef *, const std::string & > openage::pyinterface::py_builtin
Definition at line 298 of file pyobject.cpp.
Referenced by openage::py::builtin().
py_bytes
OAAPI PyIfFunc< std::string, PyObject * > openage::pyinterface::py_bytes
Definition at line 277 of file pyobject.cpp.
Referenced by openage::pyinterface::PyObjectRef::bytes().
py_call0
OAAPI PyIfFunc< void, PyObjectRef *, PyObject * > openage::pyinterface::py_call0
Definition at line 280 of file pyobject.cpp.
Referenced by openage::pyinterface::PyObjectRef::call_impl().
py_callable
OAAPI PyIfFunc< bool, PyObject * > openage::pyinterface::py_callable
Definition at line 279 of file pyobject.cpp.
Referenced by openage::pyinterface::PyObjectRef::callable().
py_calln
OAAPI PyIfFunc< void, PyObjectRef *, PyObject *, std::vector< PyObject * > & > openage::pyinterface::py_calln
Definition at line 281 of file pyobject.cpp.
Referenced by openage::pyinterface::PyObjectRef::call_impl().
py_classname
OAAPI PyIfFunc< std::string, PyObject * > openage::pyinterface::py_classname
Definition at line 296 of file pyobject.cpp.
Referenced by openage::pyinterface::PyObjectRef::classname().
py_createbytes
OAAPI PyIfFunc< void, PyObjectRef *, const std::string & > openage::pyinterface::py_createbytes
Definition at line 301 of file pyobject.cpp.
Referenced by openage::py::bytes().
py_createdict
OAAPI PyIfFunc< void, PyObjectRef * > openage::pyinterface::py_createdict
Definition at line 303 of file pyobject.cpp.
Referenced by openage::py::dict().
py_createint
OAAPI PyIfFunc< void, PyObjectRef *, int > openage::pyinterface::py_createint
Definition at line 302 of file pyobject.cpp.
Referenced by openage::py::integer().
py_createlist
OAAPI PyIfFunc< void, PyObjectRef * > openage::pyinterface::py_createlist
Definition at line 304 of file pyobject.cpp.
Referenced by openage::py::list().
py_createstr
OAAPI PyIfFunc< void, PyObjectRef *, const std::string & > openage::pyinterface::py_createstr
Definition at line 300 of file pyobject.cpp.
Referenced by openage::py::str().
py_dir
OAAPI PyIfFunc< void, PyObject *, Func< void, std::string > > openage::pyinterface::py_dir
Definition at line 288 of file pyobject.cpp.
Referenced by openage::pyinterface::PyObjectRef::dir().
py_equals
OAAPI PyIfFunc< bool, PyObject *, PyObject * > openage::pyinterface::py_equals
Definition at line 289 of file pyobject.cpp.
Referenced by openage::pyinterface::PyObjectRef::equals().
py_eval
OAAPI PyIfFunc< void, PyObject *, PyObjectRef *, std::string > openage::pyinterface::py_eval
Definition at line 291 of file pyobject.cpp.
Referenced by openage::pyinterface::PyObjectRef::eval().
py_exec
OAAPI PyIfFunc< void, PyObject *, std::string > openage::pyinterface::py_exec
Definition at line 290 of file pyobject.cpp.
Referenced by openage::pyinterface::PyObjectRef::exec().
py_get
OAAPI PyIfFunc< void, PyObject *, PyObjectRef *, PyObject * > openage::pyinterface::py_get
Definition at line 292 of file pyobject.cpp.
Referenced by openage::pyinterface::PyObjectRef::get().
py_getattr
OAAPI PyIfFunc< void, PyObjectRef *, PyObject *, std::string > openage::pyinterface::py_getattr
Definition at line 283 of file pyobject.cpp.
Referenced by openage::pyinterface::PyObjectRef::getattr().
py_hasattr
OAAPI PyIfFunc< bool, PyObject *, std::string > openage::pyinterface::py_hasattr
Definition at line 282 of file pyobject.cpp.
Referenced by openage::pyinterface::PyObjectRef::hasattr().
py_import
OAAPI PyIfFunc< void, PyObjectRef *, const std::string & > openage::pyinterface::py_import
Definition at line 299 of file pyobject.cpp.
Referenced by openage::py::import().
py_in
OAAPI PyIfFunc< bool, PyObject *, PyObject * > openage::pyinterface::py_in
Definition at line 293 of file pyobject.cpp.
Referenced by openage::pyinterface::PyObjectRef::in().
py_isinstance
OAAPI PyIfFunc< bool, PyObject *, PyObject * > openage::pyinterface::py_isinstance
Definition at line 285 of file pyobject.cpp.
Referenced by openage::pyinterface::PyObjectRef::isinstance().
py_len
OAAPI PyIfFunc< int, PyObject * > openage::pyinterface::py_len
Definition at line 278 of file pyobject.cpp.
Referenced by openage::pyinterface::PyObjectRef::len().
py_modulename
OAAPI PyIfFunc< std::string, PyObject * > openage::pyinterface::py_modulename
Definition at line 295 of file pyobject.cpp.
Referenced by openage::pyinterface::PyObjectRef::modulename().
py_repr
OAAPI PyIfFunc< std::string, PyObject * > openage::pyinterface::py_repr
Definition at line 276 of file pyobject.cpp.
Referenced by openage::pyinterface::PyObjectRef::repr().
py_setattr
OAAPI PyIfFunc< void, PyObject *, std::string, PyObject * > openage::pyinterface::py_setattr
Definition at line 284 of file pyobject.cpp.
Referenced by openage::pyinterface::PyObjectRef::setattr().
py_str
OAAPI PyIfFunc< std::string, PyObject * > openage::pyinterface::py_str
Definition at line 275 of file pyobject.cpp.
Referenced by openage::pyinterface::PyObjectRef::str().
py_to_bool
OAAPI PyIfFunc< bool, PyObject * > openage::pyinterface::py_to_bool
Definition at line 286 of file pyobject.cpp.
Referenced by openage::pyinterface::PyObjectRef::to_bool().
py_to_int
OAAPI PyIfFunc< int64_t, PyObject * > openage::pyinterface::py_to_int
Definition at line 287 of file pyobject.cpp.
Referenced by openage::pyinterface::PyObjectRef::to_int().
py_type
OAAPI PyIfFunc< void, PyObject *, PyObjectRef * > openage::pyinterface::py_type
Definition at line 294 of file pyobject.cpp.
Referenced by openage::pyinterface::PyObjectRef::type().
py_xdecref
OAAPI PyIfFunc< void, PyObject * > openage::pyinterface::py_xdecref
Definition at line 273 of file pyobject.cpp.
Referenced by openage::pyinterface::PyObjectRef::operator=(), openage::pyinterface::PyObjectRef::set_ref(), openage::pyinterface::PyObjectRef::set_ref_without_incrementing(), and openage::pyinterface::PyObjectRef::~PyObjectRef().
py_xincref
OAAPI PyIfFunc< void, PyObject * > openage::pyinterface::py_xincref
Definition at line 272 of file pyobject.cpp.
Referenced by openage::pyinterface::PyObjectRef::operator=(), and openage::pyinterface::PyObjectRef::set_ref().
pyexception_bt_get_symbols
OAAPI PyIfFunc< void, PyObject *, Func< void, const error::backtrace_symbol * > > openage::pyinterface::pyexception_bt_get_symbols
Definition at line 46 of file pyexception.cpp.
Referenced by openage::pyinterface::PyExceptionBacktrace::get_symbols().
raise_cpp_error
void(* openage::pyinterface::raise_cpp_error) (Error *) = nullptr
Definition at line 24 of file exctranslate.cpp.
Referenced by set_exc_translation_funcs(), and translate_exc_cpp_to_py().
raise_cpp_pyexception
void(* openage::pyinterface::raise_cpp_pyexception) (PyException *) = nullptr
Definition at line 25 of file exctranslate.cpp.
Referenced by set_exc_translation_funcs(), and translate_exc_cpp_to_py().
True
OAAPI PyObjectRef openage::pyinterface::True
Definition at line 307 of file pyobject.cpp.
Referenced by openage::pyinterface::tests::pyobject().