openage: openage::log::tests Namespace Reference
openage::log::tests Namespace Reference
Classes
class TestLogSink
class TestLogSource
Functions
void demo ()
def demo (args)
Demonstrates the Python logging facility.
Function Documentation
demo() [1/2]
def openage.log.tests.demo (args)
Demonstrates the Python logging facility.
Definition at line 15 of file tests.py.
     cli = argparse.ArgumentParser()
     cli.add_argument("--verbose", "-v", action='count', default=ENV_VERBOSITY)
     cli.add_argument("--quiet", "-q", action='count', default=0)
     args = cli.parse_args(args)
     level = verbosity_to_level(args.verbose - args.quiet)
     info("new log level: %s", level)
     old_level = set_loglevel(level)
     info("old level was: %s", old_level)
     info("printing some messages with different log levels")
     spam("rofl")
     dbg("wtf?")
     info("foo")
     warn("WARNING!!!!")
     err("that didn't go so well")
     crit("pretty critical, huh?")
     info("restoring old loglevel")
     set_loglevel(old_level)
     info("old loglevel restored")
     info("running some threaded stuff")
     pool = ThreadPool()
     for i in range(8):
         pool.apply_async(info, ("async message #%s", i))
     pool.close()
     pool.join()
References openage::log.crit(), openage::log.dbg(), demo(), openage::log.err(), openage::log.info(), openage::log.set_loglevel(), openage::log.spam(), openage::log.verbosity_to_level(), and openage::log.warn().
demo() [2/2]
void openage::log::tests::demo ()
Definition at line 41 of file test.cpp.
             {
     TestLogSource logger;
     TestLogSink sink{std::cout};
     logger.log(MSG(err) << 1337 << "lol...");
     logger.log(MSG(crit) << util::sformat("wtf %s %d", "test", 1337));
     std::thread t0([&]() {
         logger.log(MSG(info) << "this msg comes from a thread");
     });
     std::thread t1([&]() {
         logger.log(MSG(dbg) << "this one, too!");
     });
     auto m = MSG(warn);
     for (int i = 0; i < 4; i++) {
         m << i << ", ";
     }
     logger.log(m);
     t0.join();
     t1.join();
 }
References openage::log::crit(), openage::log::dbg(), openage::log::err(), openage::log::info(), openage::log::LogSource::log(), MSG, openage::util::sformat(), and openage::log::warn().
Referenced by demo().