openage: std Namespace Reference
std Namespace Reference
Classes
struct hash< openage::ability_type >
struct hash< openage::command_flag >
struct hash< openage::coord::phys3 >
struct hash< openage::coord::tile >
struct hash< openage::datastructure::tests::heap_elem >
struct hash< openage::game_resource >
struct hash< openage::gamedata::unit_classes >
struct hash< openage::path::Node & >
struct hash< openage::renderer::font_description >
struct hash< openage::score_category >
struct hash< openage::util::FixedPoint< I, F > >
struct hash< QString >
struct hash< std::tuple<::openage::audio::category_t, int > >
struct hash<::openage::audio::category_t >
struct numeric_limits< openage::util::FixedPoint< I, F > >
Functions
string to_string (const openage::game_resource &res)
string to_string (const openage::score_category &cat)
string to_string (const openage::ability_type &at)
template<typename I , unsigned F>
constexpr double sqrt (openage::util::FixedPoint< I, F > n)
template<typename I , unsigned F>
constexpr openage::util::FixedPoint< I, F > min (openage::util::FixedPoint< I, F > x, openage::util::FixedPoint< I, F > y)
template<typename I , unsigned F>
constexpr openage::util::FixedPoint< I, F > max (openage::util::FixedPoint< I, F > x, openage::util::FixedPoint< I, F > y)
template<typename I , unsigned F>
constexpr openage::util::FixedPoint< I, F > abs (openage::util::FixedPoint< I, F > n)
template<typename I , unsigned F>
constexpr double hypot (openage::util::FixedPoint< I, F > x, openage::util::FixedPoint< I, F > y)
Function Documentation
abs()
template<typename I , unsigned F> constexpr openage::util::FixedPoint<I, F> std::abs (openage::util::FixedPoint< I, F > n)
Definition at line 491 of file fixed_point.h.
{
     return openage::util::FixedPoint<I, F>::from_raw_value(
         std::abs(n.get_raw_value())
     );
 }
References openage::util::FixedPoint< int_type, fractional_bits >::from_raw_value(), and openage::util::FixedPoint< int_type, fractional_bits >::get_raw_value().
Referenced by openage::rng::tests::bool_dist(), openage::path::chebyshev_cost(), openage::Terrain::create_draw_advice(), openage::util::Vector< N, T >::equals(), openage::util::Matrix< M, N, T >::equals(), openage::util::Quaternion< T >::equals_rad(), openage::util::tests::fixed_point(), openage::rng::tests::freq_dist(), openage::path::manhattan_cost(), openage::rng::tests::real_dist(), and openage::square_outline().
hypot()
template<typename I , unsigned F> constexpr double std::hypot (openage::util::FixedPoint< I, F > x, openage::util::FixedPoint< I, F > y)
Definition at line 498 of file fixed_point.h.
{
     return x.hypot(y);
 }
References openage::util::FixedPoint< int_type, fractional_bits >::hypot().
Referenced by openage::dir_group(), openage::util::tests::fixed_point(), openage::SquareObject::from_edge(), openage::util::FixedPoint< int64_t, 16 >::hypot(), openage::SquareObject::intersects(), openage::coord::phys2_delta::length(), openage::TerrainSearch::next_tile(), openage::radial_outline(), openage::MoveAction::set_distance(), and openage::MoveAction::update().
max()
template<typename I , unsigned F> constexpr openage::util::FixedPoint<I, F> std::max (openage::util::FixedPoint< I, F > x, openage::util::FixedPoint< I, F > y)
Definition at line 483 of file fixed_point.h.
{
     return openage::util::FixedPoint<I, F>::from_raw_value(
         std::max(x.get_raw_value(),
                  y.get_raw_value())
     );
 }
References openage::util::FixedPoint< int_type, fractional_bits >::from_raw_value(), and openage::util::FixedPoint< int_type, fractional_bits >::get_raw_value().
Referenced by openage::path::chebyshev_cost(), openage::Generator::create_regions(), openage::util::tests::fixed_point(), openage::util::FixedPoint< int64_t, 16 >::fractional_part_bitmask(), openage::SquareObject::from_edge(), openage::RadialObject::from_edge(), openage::SquareObject::intersects(), openage::util::FixedPoint< int64_t, 16 >::max_value(), openage::SquareObject::on_edge(), openage::UnitSelection::select_space(), openage::tiles_in_range(), openage::renderer::GlyphAtlas::update_dirty_area(), and openage::renderer::vulkan::VlkDrawableDisplay::VlkDrawableDisplay().
min()
template<typename I , unsigned F> constexpr openage::util::FixedPoint<I, F> std::min (openage::util::FixedPoint< I, F > x, openage::util::FixedPoint< I, F > y)
Definition at line 475 of file fixed_point.h.
{
     return openage::util::FixedPoint<I, F>::from_raw_value(
         std::min(x.get_raw_value(),
                  y.get_raw_value())
     );
 }
References openage::util::FixedPoint< int_type, fractional_bits >::from_raw_value(), and openage::util::FixedPoint< int_type, fractional_bits >::get_raw_value().
Referenced by openage::util::array8_to_array64(), openage.convert.binpack.BestPacker::best_packer(), openage.util.math::clamp(), openage::event::EventQueue::create_event(), openage::util::compress::LZXDStream::decompress_next_frame(), openage::event::Loop::execute_events(), openage::util::tests::fixed_point(), openage::SquareObject::from_edge(), openage.util.bytequeue.ByteBuffer::get_buffers(), openage::SquareObject::intersects(), openage::curve::KeyframeContainer< T >::KeyframeContainer(), openage.convert.binpack::maxside_heuristic(), openage::SquareObject::min_axis(), openage::util::FixedPoint< int64_t, 16 >::min_value(), openage::SquareObject::on_edge(), openage::UnitSelection::select_space(), openage::log::LogSinkList::set_lowest_loglevel(), openage::tiles_in_range(), openage::event::Loop::update_changes(), and openage::renderer::GlyphAtlas::update_dirty_area().
sqrt()
template<typename I , unsigned F> constexpr double std::sqrt (openage::util::FixedPoint< I, F > n)
Definition at line 470 of file fixed_point.h.
{
     return n.sqrt();
 }
References openage::util::FixedPoint< int_type, fractional_bits >::sqrt().
Referenced by openage::Terrain::calculate_masks(), openage::Terrain::create_tile_advice(), openage::util::tests::fixed_point(), openage::math::hypot3(), openage::util::Vector< N, T >::norm(), openage::util::Quaternion< T >::norm(), openage::util::Quaternion< T >::Quaternion(), and openage::util::FixedPoint< int64_t, 16 >::sqrt().
to_string() [1/3]
std::string std::to_string (const openage::score_category & cat)
Definition at line 94 of file score.cpp.
{
     switch (cat) {
     case openage::score_category::military:
         return "military";
     case openage::score_category::economy:
         return "economy";
     case openage::score_category::technology:
         return "technology";
     case openage::score_category::society:
         return "society";
     default:
         return "unknown";
     }
 }
References openage::economy, openage::military, openage::society, and openage::technology.
to_string() [2/3]
std::string std::to_string (const openage::game_resource & res)
Definition at line 193 of file resource.cpp.
{
     switch (res) {
     case openage::game_resource::wood:
         return "wood";
     case openage::game_resource::food:
         return "food";
     case openage::game_resource::gold:
         return "gold";
     case openage::game_resource::stone:
         return "stone";
     default:
         return "unknown";
     }
 }
References openage::food, openage::gold, openage::stone, and openage::wood.
Referenced by openage::ActionMode::announce(), openage::GameControl::announce_current_player_name(), openage::input::Event::info(), openage::Unit::logsource_name(), openage::input::InputManager::mouse_bind_to_string(), openage::ActionMode::on_game_control_set(), openage::UnitSelection::show_attributes(), and openage::options::OptionValue::str_value().
to_string() [3/3]
std::string std::to_string (const openage::ability_type & at)
Definition at line 415 of file ability.cpp.
{
     switch (at) {
     case openage::ability_type::move:
         return "move";
     case openage::ability_type::garrison:
         return "garrison";
     case openage::ability_type::ungarrison:
         return "ungarrison";
     case openage::ability_type::patrol:
         return "patrol";
     case openage::ability_type::train:
         return "train";
     case openage::ability_type::build:
         return "build";
     case openage::ability_type::research:
         return "research";
     case openage::ability_type::gather:
         return "gather";
     case openage::ability_type::attack:
         return "attack";
     case openage::ability_type::convert:
         return "convert";
     case openage::ability_type::repair:
         return "repair";
     case openage::ability_type::heal:
         return "heal";
     default:
         return "unknown";
     }
 }
References openage::attack, openage::build, openage::convert, openage::garrison, openage::gather, openage::heal, openage::move, openage::patrol, openage::repair, openage::research, openage::train, and openage::ungarrison.