openage: openage::rng Namespace Reference
openage::rng Namespace Reference
Namespaces
tests
Classes
class RNG
Functions
uint64_t global_seed ()
uint64_t random ()
uint64_t random_range (uint64_t lower, uint64_t upper)
double real ()
double real_range (double lower, double upper)
static uint64_t do_rng (uint64_t &s0, uint64_t &s1)
template<class T , class Lambda >
static void act_fill (T *dat, uint64_t *state, size_t len, const Lambda &op)
std::ostream & operator<< (std::ostream &ostream, const RNG &inrng)
std::istream & operator >> (std::istream &instream, RNG &inrng)
static uint64_t try_random_device ()
static uint64_t time_seed (bool randomize)
uint64_t time_seed ()
uint64_t random_seed ()
Variables
static std::mutex rand_mutex
static RNG global_rand_gen (global_seed())
static const std::array< uint8_t, 16 > seed_key
Detailed Description
Contains an easy to use and fast random number generator.
This was never designed or intended as a cryptographic-quality, RNG, so don't use it as one. If you do, I'll tell my mom.
Function Documentation
act_fill()
template<class T , class Lambda > static void openage::rng::act_fill (T * dat, uint64_t * state, size_t len, const Lambda & op) inline static
Definition at line 100 of file rng.cpp.
{
     uint64_t s0 = state[0];
     uint64_t s1 = state[1];
     size_t ev_len = len - (len & 1);
     for (size_t i = 0; i < ev_len; i += 2) {
         op(do_rng(s1, s0), dat, i);
         op(do_rng(s0, s1), dat, i + 1);
     }
     if (len & 1) {
         op(do_rng(s1, s0), dat, len-1);
         std::swap(s1, s0);
     }
     state[0] = s0;
     state[1] = s1;
 }
References do_rng().
Referenced by openage::rng::RNG::fill_real().
do_rng()
static uint64_t openage::rng::do_rng (uint64_t & s0, uint64_t & s1) inline static
Definition at line 82 of file rng.cpp.
{
     s1 ^= s1 << 23;
     s1 = (s1 ^ s0 ^ (s1 >> 17) ^ (s0 >> 26));
     return s1 + s0;
 }
Referenced by act_fill(), and openage::rng::RNG::random().
global_seed()
uint64_t openage::rng::global_seed ()
Returns the value of the global seed.
Definition at line 13 of file global_rng.cpp.
{
     static const uint64_t seed = random_seed();
     return seed;
 }
References random_seed().
operator >>()
std::istream & openage::rng::operator >> (std::istream & instream, RNG & inrng)
Reads the rng from a stream
Exceptions
Error if reading from the stream fails
Definition at line 185 of file rng.cpp.
{
     inrng.from_stream(instream);
     return instream;
 }
References openage::rng::RNG::from_stream().
operator<<()
std::ostream & openage::rng::operator<< (std::ostream & ostream, const RNG & inrng)
Writes the rng state to a stream
Exceptions
Error if writing data fails
Definition at line 179 of file rng.cpp.
{
     inrng.to_stream(ostream);
     return ostream;
 }
References openage::rng::RNG::to_stream().
random()
uint64_t openage::rng::random ()
Returns a random number from the global rng.
Definition at line 18 of file global_rng.cpp.
                   {
     std::lock_guard<std::mutex> rand_lock(rand_mutex);
     return global_rand_gen.random();
 }
References global_rand_gen, rand_mutex, and openage::rng::RNG::random().
Referenced by openage::event::demo::ResetGame::invoke().
random_range()
uint64_t openage::rng::random_range (uint64_t lower, uint64_t upper)
Returns a random number n [lower, upper) from the global rng.
Definition at line 23 of file global_rng.cpp.
{
     std::lock_guard<std::mutex> rand_lock(rand_mutex);
     return global_rand_gen.random_range(lower, upper);
 }
References global_rand_gen, rand_mutex, and openage::rng::RNG::random_range().
Referenced by openage::Sound::play().
random_seed()
uint64_t openage::rng::random_seed ()
Returns a seed based on time since epoch as well as data from std::random_device if available
Definition at line 222 of file rng.cpp.
{
     return time_seed(true);
 }
References time_seed().
Referenced by openage::rng::tests::bool_dist(), openage::rng::tests::fill(), global_seed(), and openage::rng::tests::serialize().
real()
double openage::rng::real ()
Returns a double in [0, 1) from the global rng.
Definition at line 28 of file global_rng.cpp.
               {
     std::lock_guard<std::mutex> rand_lock(rand_mutex);
     return global_rand_gen.real();
 }
References global_rand_gen, rand_mutex, and openage::rng::RNG::real().
real_range()
double openage::rng::real_range (double lower, double upper)
Returns a double in [lower, upper) from the global rng.
Definition at line 33 of file global_rng.cpp.
{
     std::lock_guard<std::mutex> rand_lock(rand_mutex);
     return global_rand_gen.real_range(lower, upper);
 }
References global_rand_gen, rand_mutex, and openage::rng::RNG::real_range().
time_seed() [1/2]
static uint64_t openage::rng::time_seed (bool randomize) static
Definition at line 207 of file rng.cpp.
{
     uint64_t nanos = timing::get_real_time();
     if (randomize) {
         nanos ^= try_random_device();
     }
     return nanos;
 }
References openage::timing::get_real_time(), and try_random_device().
Referenced by openage::rng::tests::fill_real(), openage::rng::tests::freq_dist(), random_seed(), openage::rng::tests::real_dist(), openage::rng::tests::reproduce(), and time_seed().
time_seed() [2/2]
uint64_t openage::rng::time_seed ()
Returns a seed based on time since epoch
Definition at line 217 of file rng.cpp.
                      {
     return time_seed(false);
 }
References time_seed().
try_random_device()
static uint64_t openage::rng::try_random_device () static
Definition at line 191 of file rng.cpp.
{
     uint64_t rand1 = 0;
     // std::random_device constructor may throw if it isn't available
     try {
         std::random_device rnd;
         if (rnd.entropy() > 0) {
             rand1 = rnd() + (uint64_t(rnd()) << 32);
         }
     }
     catch (std::exception &e) {
         throw Error(MSG(err) << "failed using std::random_device: " << e.what());
     }
     return rand1;
 }
References openage::log::err(), and MSG.
Referenced by time_seed().
Variable Documentation
global_rand_gen
RNG openage::rng::global_rand_gen(global_seed()) static
Referenced by random(), random_range(), real(), and real_range().
rand_mutex
std::mutex openage::rng::rand_mutex static
Definition at line 10 of file global_rng.cpp.
Referenced by random(), random_range(), real(), and real_range().
seed_key
const std::array<uint8_t, 16> openage::rng::seed_key static
Initial value:
{{
    0xba, 0xda, 0x55, 0x00, 0x5e, 0xed, 0x00, 0x00,
    0xab, 0xcd, 0xef, 0x12, 0x34, 0x56, 0x78, 0x90
}}
Definition at line 27 of file rng.cpp.
Referenced by openage::rng::RNG::seed().