openage: openage::job::tests Namespace Reference
openage::job::tests Namespace Reference
Functions
void test_simple_job ()
void test_simple_job_with_exception ()
void test_job_manager ()
Function Documentation
test_job_manager()
void openage::job::tests::test_job_manager ()
Definition at line 93 of file tests.cpp.
{
     test_simple_job();
     test_simple_job_with_exception();
 }
References test_simple_job(), and test_simple_job_with_exception().
test_simple_job()
void openage::job::tests::test_simple_job ()
Definition at line 15 of file tests.cpp.
{
     JobManager manager{4};
     manager.start();
     std::atomic<int> finish_count(0);
     int job_count = 1337;
     bool result = false;
     auto job_function = []() -> int {
         return 42;
     };
     auto job_callback = [&](result_function_t<int> get_result) {
         int job_result = get_result();
         if (job_result == 42) {
             result = true;
         }
         finish_count++;
     };
     for (int i = 0; i < job_count; i++) {
         manager.enqueue<int>(job_function, job_callback);
     }
     while (finish_count.load() < job_count) {
         manager.execute_callbacks();
     }
     manager.stop();
     result or TESTFAIL;
 }
References openage.testing.testing::result(), openage::job::JobManager::start(), and TESTFAIL.
Referenced by test_job_manager().
test_simple_job_with_exception()
void openage::job::tests::test_simple_job_with_exception ()
Definition at line 49 of file tests.cpp.
{
     JobManager manager{4};
     manager.start();
     int good_jobs = 5;
     int bad_jobs = 5;
     std::atomic<int> finished(0);
     std::atomic<int> errors(0);
     auto exception_job_function = []() -> int {
         throw "error string";
     };
     auto job_function = []() -> int {
         return 42;
     };
     auto job_callback = [&](result_function_t<int> get_result) {
         try {
             get_result();
         } catch (const char *e) {
             errors++;
         }
         finished++;
     };
     for (int i = 0; i < good_jobs; i++) {
         manager.enqueue<int>(job_function, job_callback);
     }
     for (int i = 0; i < bad_jobs; i++) {
         manager.enqueue<int>(exception_job_function, job_callback);
     }
     while (finished.load() < good_jobs + bad_jobs) {
         manager.execute_callbacks();
     }
     manager.stop();
     errors.load() == bad_jobs or TESTFAIL;
 }
References openage::job::JobManager::start(), and TESTFAIL.
Referenced by test_job_manager().