openage: openage.util.files Namespace Reference
openage.util.files Namespace Reference
Functions
def read_guaranteed (fileobj, size)
def read_nullterminated_string (fileobj, maxlen=255)
Reads bytes until a null terminator is reached.
def which (filename)
Function Documentation
read_guaranteed()
def openage.util.files.read_guaranteed (fileobj, size)
Definition at line 15 of file files.py.
     result = []
     while remaining:
         data = fileobj.read(remaining)
         if not data:
             raise EOFError()
         remaining -= len(data)
         result.append(data)
     return b"".join(result)
 def read_nullterminated_string(fileobj, maxlen=255):
     """
Referenced by openage.cabextract.cab.CABFile.__init__(), openage.util.struct.NamedStruct.read(), openage.cabextract.cab.CABFolderStream.read_block_data(), openage.cabextract.cab.CABFile.read_folder_headers(), and openage.util.files.read_nullterminated_string().
read_nullterminated_string()
def openage.util.files.read_nullterminated_string (fileobj, maxlen = 255)
Reads bytes until a null terminator is reached.
Definition at line 33 of file files.py.
     while True:
         char = ord(read_guaranteed(fileobj, 1))
         if char == 0:
             break
         else:
             result.append(char)
         if len(result) > maxlen:
             raise Exception("Null-terminated string too long.")
     return bytes(result)
 def which(filename):
     """
     Like the which (1) tool to get the full path of a command
     by looking at the PATH environment variable.
     """
References openage::py.bytes(), and openage.util.files.read_guaranteed().
Referenced by openage.cabextract.cab.CABFile.__init__(), and openage.cabextract.cab.CABFile.read_file_headers().
which()
def openage.util.files.which (filename)
Definition at line 54 of file files.py.
     def is_executable(fpath):
         """
         Test if the given file exists and has an executable bit.
         """
         return os.path.isfile(fpath) and os.access(fpath, os.X_OK)
     fpath = os.path.split(filename)[0]
     if fpath:
         if is_executable(filename):
             return filename
     else:
         for path in os.environ["PATH"].split(os.pathsep):
             path = path.strip('"')
             exe_file = os.path.join(path, filename)
             if is_executable(exe_file):
                 return exe_file
     return None
References openage::subprocess.is_executable(), and openage::util.split().