openage: qtsdl Namespace Reference
qtsdl Namespace Reference
Classes
struct can_call
struct can_call_test
class CtxExtractionException
class CtxExtractionMode
class DeferredInitialConstantPropertyValues
class EventHandlingQuickWindow
class GameLogicCaller
struct gl_debug_parameters
class GuiApplication
class GuiApplicationImpl
class GuiCallback
class GuiDedicatedThread
class GuiEngine
class GuiEngineImpl
class GuiEngineImplConnection
class GuiEventQueue
class GuiEventQueueImpl
class GuiImageProvider
class GuiImageProviderImpl
class GuiInput
class GuiInputImpl
class GuiItem
class GuiItemBase
class GuiItemCoreInstantiator
class GuiItemInterface
class GuiItemLink
class GuiItemListModel
class GuiItemMethods
class GuiItemOrigin
class GuiItemQObject
class GuiListModel
class GuiLiveReloader
class GuiLiveReloaderAttachedProperty
class GuiLiveReloaderAttachedPropertyProvider
struct GuiPropertyMap
class GuiPropertyMapImpl
class GuiRenderer
class GuiRendererImpl
class GuiRenderingCtxActivator
class GuiRenderingSetupRoutines
class GuiSeparateRenderingContext
class GuiSingletonItem
class GuiSingletonItemsInfo
class GuiSubtree
class GuiSubtreeImpl
class GuiUniqueRenderingContext
class Inherits
class PersistentCoreHolder
class PersistentCoreHolderBase
class QmlEngineWithSingletonItemsInfo
class RecursiveDirectoryWatcher
class RecursiveDirectoryWatcherWorker
class Shadow
class TemporaryDisableGuiRendererSync
struct Unwrap
struct Unwrap< openage::gui::ActionModeLink >
struct Unwrap< openage::gui::AssetManagerLink >
struct Unwrap< openage::gui::CreateModeLink >
struct Unwrap< openage::gui::EditorModeLink >
struct Unwrap< openage::gui::EngineLink >
struct Unwrap< openage::gui::GameControlLink >
struct Unwrap< openage::gui::GameMainLink >
struct Unwrap< openage::gui::GameSpecLink >
struct Unwrap< openage::gui::GeneratorLink >
struct Unwrap< openage::gui::OutputModeLink >
struct Wrap
struct Wrap< openage::ActionMode >
struct Wrap< openage::AssetManager >
struct Wrap< openage::CreateMode >
struct Wrap< openage::EditorMode >
struct Wrap< openage::Engine >
struct Wrap< openage::GameControl >
struct Wrap< openage::GameMainHandle >
struct Wrap< openage::GameSpecHandle >
struct Wrap< openage::Generator >
struct Wrap< openage::OutputMode >
Functions
QString name_tidier (const char *name)
template<typename T >
Unwrap< T >::Type * unwrap (T *t)
template<typename T >
const Unwrap< T >::Type * unwrap (const T *t)
template<typename U >
const Wrap< U >::Type * wrap (const U *u)
template<typename U >
Wrap< U >::Type * wrap (U *u, typename std::enable_if<!std::is_base_of< GuiSingletonItem, typename Wrap< U >::Type >::value >::type *=nullptr)
template<typename U >
Wrap< U >::Type * wrap (U *u, typename std::enable_if< std::is_base_of< GuiSingletonItem, typename Wrap< U >::Type >::value >::type *=nullptr)
template<typename P >
constexpr P && wrap_if_can (typename std::remove_reference< P >::type &&p) noexcept
template<typename T >
T wrap_if_can (typename Unwrap< typename std::remove_pointer< T >::type >::Type *u)
template<typename P >
P unwrap_if_can (P &p)
template<typename T , typename Unwrap< T >::Type * = nullptr>
Unwrap< T >::Type * unwrap_if_can (T *t)
template<typename F , typename ... Args>
constexpr void static_assert_about_unwrapping ()
template<typename T , typename U >
T checked_static_cast (U *u)
gl_debug_parameters get_current_opengl_debug_parameters (const QOpenGLContext &current_source_context)
void apply_opengl_debug_parameters (gl_debug_parameters params, QOpenGLContext &current_dest_context)
std::tuple< QVariant, WId > extract_native_context (SDL_Window *window)
std::tuple< QVariant, std::function< void()> > extract_native_context_and_switchback_func (SDL_Window *window)
template<>
std::string GuiPropertyMap::getv< std::string > (const char *name) const
template<>
void GuiPropertyMap::setv< const std::string & > (const char *name, const std::string &v)
template<>
std::vector< std::string > GuiPropertyMap::getv< std::vector< std::string > > (const char *name) const
template<>
void GuiPropertyMap::setv< const std::vector< std::string > & > (const char *name, const std::vector< std::string > &v)
Function Documentation
apply_opengl_debug_parameters()
void qtsdl::apply_opengl_debug_parameters (gl_debug_parameters params, QOpenGLContext & current_dest_context)
Create a GL logger in the current GL context
Parameters
params debugging settings
current_dest_context current GL context to which parameters will be applied
Definition at line 30 of file opengl_debug_logger.cpp.
{
     if (params.is_debug && params.callback) {
         if (auto functions = current_dest_context.versionFunctions<QOpenGLFunctions_4_4_Core>()) {
             functions->initializeOpenGLFunctions();
             functions->glDebugMessageControl(GL_DONT_CARE, GL_DONT_CARE, GL_DONT_CARE, 0, nullptr, GL_FALSE);
             functions->glDebugMessageControl(GL_DONT_CARE, GL_DEBUG_TYPE_ERROR, GL_DONT_CARE, 0, nullptr, GL_TRUE);
             functions->glDebugMessageControl(GL_DONT_CARE, GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR, GL_DONT_CARE, 0, nullptr, GL_TRUE);
             functions->glDebugMessageCallback((GLDEBUGPROC)params.callback, nullptr);
             if (params.synchronous)
                 glEnable(GL_DEBUG_OUTPUT_SYNCHRONOUS);
         }
     }
 }
References qtsdl::gl_debug_parameters::callback, qtsdl::gl_debug_parameters::is_debug, and qtsdl::gl_debug_parameters::synchronous.
checked_static_cast()
template<typename T , typename U > T qtsdl::checked_static_cast (U * u)
Definition at line 10 of file qtsdl_checked_static_cast.h.
{
     assert(dynamic_cast<T>(u));
     return static_cast<T>(u);
 }
Referenced by qtsdl::GuiItemCoreInstantiator< GameSpecLink >::do_adopt_core(), and wrap().
extract_native_context()
std::tuple< QVariant, WId > qtsdl::extract_native_context (SDL_Window * window)
Returns
current context (or null) and id of the window
Definition at line 14 of file context_extraction_cocoa.mm.
{
     assert(window);
     NSOpenGLContext *current_context = [NSOpenGLContext currentContext];
     assert(current_context);
     NSView *view = nullptr;
     SDL_SysWMinfo wm_info;
     SDL_VERSION(&wm_info.version);
     if (SDL_GetWindowWMInfo(window, &wm_info)) {
         NSWindow *ns_window = wm_info.info.cocoa.window;
         view = [ns_window contentView];
         assert(view);
     }
     return std::make_tuple(QVariant::fromValue<QCocoaNativeContext>(QCocoaNativeContext(current_context)), reinterpret_cast<WId>(view));
 }
extract_native_context_and_switchback_func()
std::tuple< QVariant, std::function< void()> > qtsdl::extract_native_context_and_switchback_func (SDL_Window * window)
Returns
current context (or null) and function to get it back to the window
Definition at line 35 of file context_extraction_cocoa.mm.
{
     assert(window);
     NSOpenGLContext *current_context = [NSOpenGLContext currentContext];
     assert(current_context);
     NSView *view = nullptr;
     SDL_SysWMinfo wm_info;
     SDL_VERSION(&wm_info.version);
     if (SDL_GetWindowWMInfo(window, &wm_info)) {
         NSWindow *ns_window = wm_info.info.cocoa.window;
         view = [ns_window contentView];
         assert(view);
         return std::make_tuple(QVariant::fromValue<QCocoaNativeContext>(QCocoaNativeContext(current_context)), [current_context] {
             [current_context makeCurrentContext];
         });
     }
     return std::tuple<QVariant, std::function<void()>>{};
 }
get_current_opengl_debug_parameters()
gl_debug_parameters qtsdl::get_current_opengl_debug_parameters (const QOpenGLContext & current_source_context)
Get debugging settings of the current GL context
Parameters
current_source_context current GL context
Returns
debugging settings
Definition at line 18 of file opengl_debug_logger.cpp.
{
     gl_debug_parameters params{};
     if (current_source_context.versionFunctions<QOpenGLFunctions_4_4_Core>())
         if ((params.is_debug = current_source_context.format().options().testFlag(QSurfaceFormat::DebugContext))) {
             glGetPointerv(GL_DEBUG_CALLBACK_FUNCTION, &params.callback);
             params.synchronous = glIsEnabled(GL_DEBUG_OUTPUT_SYNCHRONOUS);
         }
     return params;
 }
GuiPropertyMap::getv< std::string >()
template<> std::string qtsdl::GuiPropertyMap::getv< std::string > (const char * name) const
Definition at line 100 of file gui_property_map.cpp.
{
     return getter<QString>(*this->impl, name).toStdString();
 }
GuiPropertyMap::getv< std::vector< std::string > >()
template<> std::vector<std::string> qtsdl::GuiPropertyMap::getv< std::vector< std::string > > (const char * name) const
Definition at line 115 of file gui_property_map.cpp.
{
     return strings_to_vector(getter<QStringList>(*this->impl, name));
 }
GuiPropertyMap::setv< const std::string & >()
template<> void qtsdl::GuiPropertyMap::setv< const std::string & > (const char * name, const std::string & v)
Definition at line 105 of file gui_property_map.cpp.
{
     setter(*this->impl, name, QString::fromStdString(v));
 }
GuiPropertyMap::setv< const std::vector< std::string > & >()
template<> void qtsdl::GuiPropertyMap::setv< const std::vector< std::string > & > (const char * name, const std::vector< std::string > & v)
Definition at line 120 of file gui_property_map.cpp.
{
     setter(*this->impl, name, vector_to_strings(v));
 }
name_tidier()
QString qtsdl::name_tidier (const char * name)
Cleans a text from unneeded content like "qtsdl".
Definition at line 8 of file gui_item.cpp.
{
     QString cleaner_name = QString::fromLatin1(name);
     cleaner_name.remove(QRegularExpression("qtsdl|PersistentCoreHolder"));
     return cleaner_name;
 }
Referenced by qtsdl::GuiItemCoreInstantiator< GameSpecLink >::do_adopt_core().
static_assert_about_unwrapping()
template<typename F , typename ... Args> constexpr void qtsdl::static_assert_about_unwrapping ()
To print our own error message that warns about possible cause of the argument mismatch.
Unwrapping uses type trait "Unwrap" that is defined in the header with corresponding type. If the header is not included, then compiler considers it as a basic type and tries to pass it wrapped to a function that expects an unwrapped type.
Template Parameters
F callable
A arguments to test against the callable
Definition at line 117 of file gui_item_link.h.
{
     static_assert(can_call<F, Args...>{}, "One of possible causes: if you're passing SomethingLink*, then don't forget to #include \"something_link.h\".");
 }
unwrap() [1/2]
template<typename T > Unwrap<T>::Type* qtsdl::unwrap (T * t)
Definition at line 37 of file gui_item_link.h.
{
     return t ? t->template get<typename Unwrap<T>::Type>() : nullptr;
 }
Referenced by qtsdl::GuiItemMethods< GameSpecLink >::assign_while_catching_constant_properies_inits(), qtsdl::GuiItemListModel< GeneratorLink >::do_initial_to_gui_propagation(), qtsdl::GuiItemListModel< GeneratorLink >::establish_from_gui_propagation(), qtsdl::GuiItemListModel< GeneratorLink >::establish_to_gui_propagation(), qtsdl::GuiItemMethods< GameSpecLink >::i(), openage::gui::OutputModeLink::on_core_adopted(), openage::gui::GameMainLink::on_core_adopted(), openage::gui::GameSpecLink::on_core_adopted(), openage::gui::ActionModeLink::on_core_adopted(), openage::gui::EditorModeLink::on_core_adopted(), openage::gui::GameControlLink::on_core_adopted(), openage::gui::ResourcesListModel::set_action_mode(), openage::gui::GameControlLink::set_modes(), unwrap_if_can(), and openage::gui::EngineLink::~EngineLink().
unwrap() [2/2]
template<typename T > const Unwrap<T>::Type* qtsdl::unwrap (const T * t)
Definition at line 42 of file gui_item_link.h.
{
     return t ? t->template get<typename Unwrap<T>::Type>() : nullptr;
 }
unwrap_if_can() [1/2]
template<typename P > P qtsdl::unwrap_if_can (P & p)
Definition at line 77 of file gui_item_link.h.
                       {
     return p;
 }
Referenced by qtsdl::GuiItemMethods< GameSpecLink >::assign_while_catching_constant_properies_inits(), and qtsdl::GuiItemMethods< GameSpecLink >::i().
unwrap_if_can() [2/2]
template<typename T , typename Unwrap< T >::Type * = nullptr> Unwrap<T>::Type* qtsdl::unwrap_if_can (T * t)
Definition at line 82 of file gui_item_link.h.
{
     return unwrap(t);
 }
References unwrap().
wrap() [1/3]
template<typename U > const Wrap<U>::Type* qtsdl::wrap (const U * u)
Definition at line 47 of file gui_item_link.h.
{
     return checked_static_cast<typename Wrap<U>::Type*>(u->gui_link);
 }
References checked_static_cast().
Referenced by openage::gui::GameControlLink::on_mode_changed(), and wrap_if_can().
wrap() [2/3]
template<typename U > Wrap<U>::Type* qtsdl::wrap (U * u, typename std::enable_if<!std::is_base_of< GuiSingletonItem, typename Wrap< U >::Type >::value >::type * = nullptr)
Definition at line 57 of file gui_item_link.h.
{
     return u ? checked_static_cast<typename Wrap<U>::Type*>(u->gui_link) : nullptr;
 }
References checked_static_cast().
wrap() [3/3]
template<typename U > Wrap<U>::Type* qtsdl::wrap (U * u, typename std::enable_if< std::is_base_of< GuiSingletonItem, typename Wrap< U >::Type >::value >::type * = nullptr)
Definition at line 62 of file gui_item_link.h.
{
     return u ? checked_static_cast<typename Wrap<U>::Type*>(u->gui_link) : nullptr;
 }
References checked_static_cast().
wrap_if_can() [1/2]
template<typename P > constexpr P&& qtsdl::wrap_if_can (typename std::remove_reference< P >::type && p) noexcept
Definition at line 67 of file gui_item_link.h.
{
     return std::forward<P>(p);
 }
wrap_if_can() [2/2]
template<typename T > T qtsdl::wrap_if_can (typename Unwrap< typename std::remove_pointer< T >::type >::Type * u)
Definition at line 72 of file gui_item_link.h.
{
     return wrap(u);
 }
References wrap().