openage: openage.convert.interface.rename Namespace Reference
openage.convert.interface.rename Namespace Reference
Functions
def hud_rename (filepath)
Renaming interface assets and splitting into directories.
def asset_rename (filepath)
Rename a slp asset path by the lookup map above.
Function Documentation
asset_rename()
def openage.convert.interface.rename.asset_rename (filepath)
Rename a slp asset path by the lookup map above.
Definition at line 28 of file rename.py.
         return filepath.parent[ASSETS[filepath.stem] + filepath.suffix]
     except (KeyError, AttributeError):
         return filepath
Referenced by openage.convert.interface.rename.hud_rename().
hud_rename()
def openage.convert.interface.rename.hud_rename (filepath)
Renaming interface assets and splitting into directories.
Definition at line 14 of file rename.py.
         return filepath.parent["hud{}{}".format(
             str(ingame_hud_background_index(int(filepath.stem))).zfill(4),
             filepath.suffix
         )]
     except ValueError:
         return asset_rename(filepath)
 def asset_rename(filepath):
     """
References openage.convert.interface.rename.asset_rename(), openage.convert.interface.hardcoded.ingame_hud_background_index(), and openage::py.str().
Referenced by openage.convert.driver.convert_slp().