openage: openage::py Namespace Reference
openage::py Namespace Reference
Typedefs
using Obj = pyinterface::PyObjectRef
Functions
Obj builtin (const std::string &name)
Obj import (const std::string &name)
Obj str (const std::string &value)
Obj bytes (const std::string &value)
Obj integer (int value)
Obj dict ()
Obj list ()
Detailed Description
Convenience functions and types for the python interface.
Typedef Documentation
Obj
using openage::py::Obj = typedef pyinterface::PyObjectRef
Python object reference.
Definition at line 381 of file pyobject.h.
Function Documentation
builtin()
Obj openage::py::builtin (const std::string & name)
getattr(importlib.import_module("builtins"), name)
Definition at line 317 of file pyobject.cpp.
{
     Obj result;
     py_builtin.call(&result, name);
     return result;
 }
References openage::pyinterface::py_builtin, and openage.testing.testing::result().
Referenced by openage::pyinterface::tests::pyobject().
bytes()
Obj openage::py::bytes (const std::string & value)
bytes(value)
Definition at line 338 of file pyobject.cpp.
{
     Obj result;
     py_createbytes.call(&result, value);
     return result;
 }
References openage::pyinterface::py_createbytes, and openage.testing.testing::result().
Referenced by openage.util.fslike.directory.Directory::__init__(), openage::pyinterface::tests::pyobject(), openage.util.files::read_nullterminated_string(), and openage::util::FD::write().
dict()
Obj openage::py::dict ()
dict()
Definition at line 352 of file pyobject.cpp.
            {
     Obj result;
     py_createdict.call(&result);
     return result;
 }
References openage::pyinterface::py_createdict, and openage.testing.testing::result().
Referenced by openage.util.struct.NamedStructMeta::__new__(), openage.convert.dataformat.exportable.Exportable::dump(), openage.convert.dataformat.data_formatter.DataFormatter::export(), openage.convert.driver::extract_mediafiles_names_map(), openage.convert.dataformat.util::gather_data(), openage.codegen.coord::generate_coord_basetypes(), openage::pyinterface::tests::pyobject(), openage::pyinterface::tests::pyobject_demo(), and openage.convert.dataformat.exportable.Exportable::read().
import()
Obj openage::py::import (const std::string & name)
importlib.import_module(name)
Definition at line 324 of file pyobject.cpp.
{
     Obj result;
     py_import.call(&result, name);
     return result;
 }
References openage::pyinterface::py_import, and openage.testing.testing::result().
Referenced by openage::pyinterface::tests::pyobject().
integer()
Obj openage::py::integer (int value)
int(value)
Definition at line 345 of file pyobject.cpp.
{
     Obj result;
     py_createint.call(&result, value);
     return result;
 }
References openage::pyinterface::py_createint, and openage.testing.testing::result().
Referenced by openage::pyinterface::PyObjectRef::get(), and openage::pyinterface::tests::pyobject().
list()
Obj openage::py::list ()
list()
Definition at line 359 of file pyobject.cpp.
            {
     Obj result;
     py_createlist.call(&result);
     return result;
 }
References openage::pyinterface::py_createlist, and openage.testing.testing::result().
Referenced by openage.convert.driver::change_dir(), openage::GameSpec::create_abilities(), openage.convert.stringresource.StringResource::dump(), openage.convert.dataformat.exportable.Exportable::dump(), openage.convert.colortable.ColorTable::dump(), openage.convert.dataformat.data_formatter.DataFormatter::export(), openage.convert.dataformat.generated_file.GeneratedFile::generate(), openage.convert.dataformat.data_definition.DataDefinition::generate_csv(), openage.convert.dataformat.struct_definition.StructDefinition::generate_struct_implementation(), openage.codegen.cpp_testlist::generate_testlist(), openage.convert.dataformat.members.MultisubtypeMember::get_empty_value(), openage.convert.dataformat.members.EnumMember::get_parsers(), openage.convert.blendomatic.BlendingTile::get_picture_data(), openage.convert.dataformat.content_snippet.ContentSnippet::get_required_snippets(), openage.convert.dataformat.members.EnumMember::get_snippets(), openage.convert.dataformat.members.MultisubtypeMember::get_snippets(), openage.convert.dataformat.members.SubdataMember::get_snippets(), openage.convert.blendomatic.BlendingMode::get_tile_from_data(), openage::GameSpec::load_building(), openage::GameSpec::load_living(), openage::GameSpec::load_missile(), openage::GameSpec::load_object(), openage.convert.dataformat.exportable.Exportable::read(), openage.convert.hdlanguagefile::read_age2_hd_3x_stringresources(), openage.convert.dataformat.exportable.Exportable::structs(), openage.cabextract.test::test(), openage.util.threading::test_concurrent_chain(), and openage.util.fslike.test::test_union().
str()
Obj openage::py::str (const std::string & value)
str(value);
Definition at line 331 of file pyobject.cpp.
{
     Obj result;
     py_createstr.call(&result, value);
     return result;
 }
References openage::pyinterface::py_createstr, and openage.testing.testing::result().
Referenced by openage.util.struct.NamedStruct::__repr__(), openage.convert.dataformat.data_definition.DataDefinition::__str__(), openage.convert.dataformat.content_snippet.ContentSnippet::__str__(), openage.util.struct.NamedStruct::__str__(), openage.convert.blendomatic.Blendomatic::__str__(), openage.convert.driver::convert(), openage::util::constexpr_::create_truncated_string_literal(), openage.convert.dataformat.util::encode_value(), openage.convert.dataformat.members.EnumLookupMember::entry_hook(), openage.convert.dataformat.members.DynLengthMember::format_hash(), openage.util.strings::format_progress(), openage.convert.colortable.ColorTable::gen_image(), openage::pyinterface::PyObjectRef::get(), openage::util::constexpr_::get_prefix(), openage::util::constexpr_::has_prefix(), openage.convert.interface.rename::hud_rename(), openage::event::demo::BallReflectPanel::invoke(), openage::event::demo::ResetGame::invoke(), openage::event::demo::BallReflectWall::predict_invoke_time(), openage::event::demo::BallReflectPanel::predict_invoke_time(), openage.util.fslike.abstract.FSLikeObject::pretty(), openage::util::FD::puts(), openage::pyinterface::tests::pyobject(), openage.util.fslike.abstract.ReadOnlyFSLikeObject::read_only_error(), openage.convert.drs.DRS::read_tables(), openage::util::string_matches_pattern(), openage::util::constexpr_::strip_prefix(), openage::util::constexpr_::strlen(), openage.util.struct.Flags::unknown(), openage::util::utf8_last_char_size(), and openage::util::utf8_pop_back().