openage: openage.convert.texture Namespace Reference
openage.convert.texture Namespace Reference
Classes
class Texture
class TextureImage
represents a image created from a (r,g,b,a) matrix.
Functions
def subtexture_meta (tx, ty, hx, hy, cx, cy)
def merge_frames (frames)
merge all given frames of this slp to a single image file.
Function Documentation
merge_frames()
def openage.convert.texture.merge_frames (frames)
merge all given frames of this slp to a single image file.
frames = [TextureImage, ...]
returns = TextureImage, (width, height), [drawn_frames_meta]
Definition at line 210 of file texture.py.
     packer = BestPacker([BinaryTreePacker(margin=MARGIN, aspect_ratio=1),
                          BinaryTreePacker(margin=MARGIN,
                                           aspect_ratio=TERRAIN_ASPECT_RATIO),
                          RowPacker(margin=MARGIN),
                          ColumnPacker(margin=MARGIN)])
     packer.pack(frames)
     width, height = packer.width(), packer.height()
     assert width <= MAX_TEXTURE_DIMENSION, "Texture width limit exceeded"
     assert height <= MAX_TEXTURE_DIMENSION, "Texture height limit exceeded"
     area = sum(block.width * block.height for block in frames)
     used_area = width * height
     efficiency = area / used_area
     spam("merging %d frames to %dx%d atlas, efficiency %.3f.",
          len(frames), width, height, efficiency)
     atlas_data = numpy.zeros((height, width, 4), dtype=numpy.uint8)
     drawn_frames_meta = []
     for sub_frame in frames:
         sub_w = sub_frame.width
         sub_h = sub_frame.height
         pos_x, pos_y = packer.pos(sub_frame)
         spam("drawing frame %03d on atlas at %d x %d...",
              len(drawn_frames_meta), pos_x, pos_y)
         # draw the subtexture on atlas_data
         atlas_data[pos_y:pos_y + sub_h, pos_x:pos_x + sub_w] = sub_frame.data
         # generate subtexture meta information object
         hotspot_x, hotspot_y = sub_frame.hotspot
         drawn_frames_meta.append(subtexture_meta(pos_x, pos_y,
                                                  sub_w, sub_h,
                                                  hotspot_x, hotspot_y))
     atlas = TextureImage(atlas_data)
     spam("successfully merged %d frames to atlas.", len(frames))
     return atlas, (width, height), drawn_frames_meta
References openage::log.spam(), and openage.convert.texture.subtexture_meta().
Referenced by openage.convert.texture.Texture.__init__().
subtexture_meta()
def openage.convert.texture.subtexture_meta (tx, ty, hx, hy, cx, cy)
Definition at line 33 of file texture.py.
         "y":  ty,
         "w":  hx,
         "h":  hy,
         "cx": cx,
         "cy": cy,
     }
     return ret
 class TextureImage:
     """
     represents a image created from a (r,g,b,a) matrix.
Referenced by openage.convert.texture.merge_frames().