openage: openage.convert.game_versions Namespace Reference
openage.convert.game_versions Namespace Reference
Classes
class GameVersion
class Support
Support state of a game version.
Functions
def get_game_versions (srcdir)
def has_x1_p1 (versions)
Determine whether any of the versions has patch 1, i.e.
Function Documentation
get_game_versions()
def openage.convert.game_versions.get_game_versions (srcdir)
Definition at line 120 of file game_versions.py.
         if all(srcdir.joinpath(path).is_file()
                for path in version.required_files):
             yield version
 def has_x1_p1(versions):
     """
Referenced by openage.convert.main.mount_input().
has_x1_p1()
def openage.convert.game_versions.has_x1_p1 (versions)
Determine whether any of the versions has patch 1, i.e.
the *_x1_p1.* files
Definition at line 130 of file game_versions.py.
         for ver_file in ver.required_files:
             if "x1_p1" in ver_file:
                 return True
     return False
Referenced by openage.convert.driver.get_gamespec(), openage.convert.driver.get_string_resources(), and openage.convert.main.mount_drs_archives().