openage: openage::console::tests Namespace Reference
openage::console::tests Namespace Reference
Functions
int max (int a, int b)
void render ()
void interactive ()
Function Documentation
interactive()
void openage::console::tests::interactive ()
Definition at line 55 of file tests.cpp.
                    {
     #ifndef _WIN32
     console::Buf buf{{80, 25}, 1337, 80};
     struct winsize ws;
     ws.ws_col = buf.dims.x;
     ws.ws_row = buf.dims.y;
     ws.ws_xpixel = buf.dims.x * 8;
     ws.ws_ypixel = buf.dims.y * 13;
     int amaster;
     switch (forkpty(&amaster, nullptr, nullptr, &ws)) {
     case -1:
         throw Error(MSG(err) << "fork() failed: " << strerror(errno));
     case 0: {
         // we are the child, spawn a shell
         const char *shell = getenv("SHELL");
         if (shell == nullptr) {
             shell = "/bin/sh";
         }
         execl(shell, shell, nullptr);
         throw Error(MSG(err) << "execl(\"" << shell << "\", \"" << shell << "\", nullptr) failed: " << strerror(errno));
     }
     default:
         //we are the parent
         break;
     }
     util::FD ptyout{amaster};            // for writing to the slave
     util::FD ptyin{&ptyout, true};       // for reading the slave's output
     util::FD termout{STDOUT_FILENO};     // for writing to the terminal
     util::FD termin{STDIN_FILENO, true}; // for reading the user input
     // hide cursor
     termout.puts("\x1b[?25l");
     // set canon input mode
     termin.setinputmodecanon();
     // set amaster to auto-close
     ptyout.close_on_destroy = true;
     constexpr int rdbuf_size = 4096;
     char rdbuf[rdbuf_size];
     int nfds = max(termin.fd, ptyin.fd) + 1;
     bool loop = true;
     console::draw::to_terminal(&buf, &termout, true);
     while (loop) {
         fd_set rfds;
         struct timeval tv;
         // Watch stdin (fd 0) to see when it has input.
         FD_ZERO(&rfds);
         FD_SET(ptyin.fd, &rfds);
         FD_SET(termin.fd, &rfds);
         tv.tv_sec = 0;
         tv.tv_usec = 1000000 / 60;
         switch (select(nfds, &rfds, NULL, NULL, &tv)) {
         case -1:
             // error
             break;
         case 0:
             // timeout
             break;
         default:
             // success
             if (FD_ISSET(termin.fd, &rfds)) {
                 ssize_t retval = read(termin.fd, rdbuf, rdbuf_size);
                 switch (retval) {
                 case -1:
                     // error... probably EWOULDBLOCK. ignore.
                     break;
                 case 0:
                     // EOF on stdin... huh... well... that was unexpected... TODO
                     break;
                 default:
                     if (ptyout.write(rdbuf, retval) != retval) {
                         // for some reason, we couldn't write all input to
                         // a master.
                         loop = false;
                     }
                     break;
                 }
             }
             if (FD_ISSET(ptyin.fd, &rfds)) {
                 ssize_t retval = read(ptyin.fd, rdbuf, rdbuf_size);
                 switch (retval) {
                 case -1:
                     switch(errno) {
                     case EIO:
                         loop = false;
                         break;
                     default:
                         // probably EWOULDBLOCK. ignore.
                         break;
                     }
                     break;
                 case 0:
                     // EOF on amaster
                     loop = false;
                     break;
                 default:
                     for (int i = 0; i < retval; i++) {
                         buf.write(rdbuf[i]);
                     }
                 }
             }
             break;
         }
         if (tv.tv_usec == 0) {
             console::draw::to_terminal(&buf, &termout, false);
             tv.tv_usec = 1000000 / 60;
         }
     }
     // show cursor
     termout.puts("\x1b[?25h");
     #endif /* _WIN32 */
 }
References openage::console::Buf::dims, openage::log::err(), max(), MSG, openage::util::FD::puts(), and openage::console::draw::to_terminal().
max()
int openage::console::tests::max (int a, int b)
Definition at line 31 of file tests.cpp.
                       {
     return (a > b) ? a : b;
 }
Referenced by openage::curve::UnorderedMap< key_t, val_t >::at(), openage::curve::Queue< T >::begin(), openage::curve::UnorderedMap< key_t, val_t >::begin(), openage.util.math::clamp(), openage::renderer::vulkan::VlkRenderer::do_the_thing(), openage::curve::Queue< T >::end(), openage::curve::UnorderedMap< key_t, val_t >::end(), openage::rng::tests::freq_dist(), openage.util.bytequeue.ByteBuffer::get_buffers(), openage.convert.binpack.Packer::height(), openage::curve::Queue< T >::insert(), openage::curve::UnorderedMap< key_t, val_t >::insert(), interactive(), openage.convert.binpack::maxside_heuristic(), openage::event::demo::BallReflectWall::predict_invoke_time(), openage::event::demo::BallReflectPanel::predict_invoke_time(), openage.testing.main::print_test_list(), openage::util::filelike::Native::read(), openage::util::filelike::Python::read(), openage.util.filelike.stream.StreamSeekBuffer::read(), openage::util::filelike::Native::read_to(), openage::util::filelike::Python::read_to(), openage::util::File::read_to(), openage::UnitSelection::select_space(), openage::tiles_in_range(), openage::renderer::vulkan::VlkDrawableDisplay::VlkDrawableDisplay(), and openage.convert.binpack.Packer::width().
render()
void openage::console::tests::render ()
Definition at line 39 of file tests.cpp.
               {
     console::Buf buf{{80, 25}, 1337, 80};
     buf.write("Hello, brave new console world!\n\n\n\n");
     buf.write("stuff, lol.\n\n");
     buf.write("\x1b[1mbold stuff, lol.\x1b[m\n\n");
     buf.write("\x1b[5;31;1mred bold blinking stuff, lol, ... also, this text seems to be quite long, maybe even wider than the terminal width. i wonder what could \x1b[7mhappen.\x1b[m\n\n");
     for (int i = 0; i < 18; i++) {
         buf.write("rofl\n");
     }
     buf.scroll(100);
     util::FD outfd{STDOUT_FILENO};
     console::draw::to_terminal(&buf, &outfd, true);
 }
References openage::console::draw::to_terminal(), and openage::console::Buf::write().