openage: openage::gameio Namespace Reference
openage::gameio Namespace Reference
Functions
void save_unit (std::ofstream &file, Unit *unit)
void load_unit (std::ifstream &file, GameMain *game)
void save_tile_content (std::ofstream &file, openage::TileContent *content)
TileContent load_tile_content (std::ifstream &file)
void save (openage::GameMain *, std::string fname)
a game save function that sometimes works
void load (openage::GameMain *, std::string fname)
a game load function that sometimes works
Variables
const std::string save_label = "openage-save-file"
const std::string save_version = "v0.1"
Function Documentation
load()
void openage::gameio::load (openage::GameMain * game, std::string fname)
a game load function that sometimes works
Definition at line 102 of file game_save.cpp.
{
     std::ifstream file(fname, std::ifstream::in);
     if (!file.good()) {
         log::log(MSG(dbg) << "could not find " + fname);
         return;
     }
     log::log(MSG(dbg) << "loading " + fname);
     // load metadata
     std::string file_label;
     file >> file_label;
     if (file_label != save_label) {
         log::log(MSG(warn) << fname << " is not a savefile");
         return;
     }
     std::string version;
     file >> version;
     if (version != save_version) {
         log::log(MSG(warn) << "savefile has different version");
     }
     std::string build;
     file >> build;
     // read terrain chunks
     unsigned int num_chunks;
     file >> num_chunks;
     for (unsigned int c = 0; c < num_chunks; ++c) {
         coord::chunk_t ne, se;
         size_t tile_count;
         file >> ne;
         file >> se;
         file >> tile_count;
         openage::TerrainChunk *chunk = game->terrain->get_create_chunk(coord::chunk{ne, se});
         for (size_t p = 0; p < tile_count; ++p) {
             *chunk->get_data(p) = load_tile_content( file );
         }
     }
     game->placed_units.reset();
     unsigned int num_units;
     file >> num_units;
     for (unsigned int u = 0; u < num_units; ++u) {
         load_unit( file, game );
     }
 }
References openage::build, openage::log::dbg(), openage::TerrainChunk::get_data(), load_tile_content(), load_unit(), openage::log::log(), MSG, openage::GameMain::placed_units, openage::UnitContainer::reset(), save_label, save_version, openage::GameMain::terrain, and openage::log::warn().
Referenced by openage::Generator::create().
load_tile_content()
TileContent openage::gameio::load_tile_content (std::ifstream & file)
Definition at line 61 of file game_save.cpp.
{
     openage::TileContent content;
     file >> content.terrain_id;
     unsigned int o_size;
     file >> o_size;
     return content;
 }
References openage::TileContent::terrain_id.
Referenced by load().
load_unit()
void openage::gameio::load_unit (std::ifstream & file, GameMain * game)
Definition at line 33 of file game_save.cpp.
{
     int pr_id;
     int player_no;
     coord::tile_t ne, se;
     file >> pr_id;
     file >> player_no;
     file >> ne;
     file >> se;
     UnitType &saved_type = *game->get_player(player_no)->get_type(pr_id);
     auto ref = game->placed_units.new_unit(saved_type, *game->get_player(player_no), coord::tile{ne, se}.to_phys3(*game->terrain));
     bool has_building_attr;
     file >> has_building_attr;
     if (has_building_attr) {
         float completed;
         file >> completed;
         if (completed >= 1.0f && ref.is_valid()) {
             complete_building(*ref.get());
         }
     }
 }
References openage::complete_building(), openage::GameMain::get_player(), openage::Player::get_type(), openage::UnitContainer::new_unit(), openage::GameMain::placed_units, ref, openage::GameMain::terrain, and openage::coord::tile::to_phys3().
Referenced by load().
save()
void openage::gameio::save (openage::GameMain * game, std::string fname)
a game save function that sometimes works
Definition at line 70 of file game_save.cpp.
{
     std::ofstream file(fname, std::ofstream::out);
     log::log(MSG(dbg) << "saving " + fname);
     // metadata
     file << save_label << std::endl;
     file << save_version << std::endl;
     file << config::version << std::endl;
     // how many chunks
     std::vector<coord::chunk> used = game->terrain->used_chunks();
     file << used.size() << std::endl;
     // save each chunk
     for (coord::chunk &position : used) {
         file << position.ne << " " << position.se << std::endl;
         openage::TerrainChunk *chunk = game->terrain->get_chunk(position);
         file << chunk->tile_count << std::endl;
         for (size_t p = 0; p < chunk->tile_count; ++p) {
             save_tile_content( file, chunk->get_data(p) );
         }
     }
     // save units
     std::vector<openage::Unit *> units = game->placed_units.all_units();
     file << units.size() << std::endl;
     for (Unit *u : units) {
         save_unit(file, u);
     }
 }
References openage::UnitContainer::all_units(), openage::log::dbg(), openage::TerrainChunk::get_data(), openage::log::log(), MSG, openage::GameMain::placed_units, save_label, save_tile_content(), save_unit(), save_version, openage::GameMain::terrain, and openage::TerrainChunk::tile_count.
Referenced by openage::gui::GameSaver::activate(), openage.convert.main::interactive_browser(), and openage.convert.colortable.ColorTable::save_visualization().
save_tile_content()
void openage::gameio::save_tile_content (std::ofstream & file, openage::TileContent * content)
Definition at line 56 of file game_save.cpp.
{
     file << content->terrain_id << std::endl;
     file << content->obj.size() << std::endl;
 }
References openage::TileContent::obj, and openage::TileContent::terrain_id.
Referenced by save().
save_unit()
void openage::gameio::save_unit (std::ofstream & file, Unit * unit)
Definition at line 20 of file game_save.cpp.
{
     file << unit->unit_type->id() << std::endl;
     file << unit->get_attribute<attr_type::owner>().player.player_number << std::endl;
     coord::tile pos = unit->location->pos.start;
     file << pos.ne << " " << pos.se << std::endl;
     bool has_building_attr = unit->has_attribute(attr_type::building);
     file << has_building_attr << std::endl;
     if (has_building_attr) {
         file << unit->get_attribute<attr_type::building>().completed << std::endl;
     }
 }
References openage::building, openage::Unit::get_attribute(), openage::Unit::has_attribute(), openage::UnitType::id(), openage::Unit::location, openage::owner, and openage::Unit::unit_type.
Referenced by save().
Variable Documentation
save_label
const std::string openage::gameio::save_label = "openage-save-file"
Definition at line 14 of file game_save.h.
Referenced by load(), and save().
save_version
const std::string openage::gameio::save_version = "v0.1"
Definition at line 15 of file game_save.h.
Referenced by load(), and save().