openage: openage::renderer::resources Namespace Reference
openage::renderer::resources Namespace Reference
Classes
class MeshData
class ShaderSource
Stores source code for a part of a shader program.
class Texture2dData
class Texture2dInfo
struct Texture2dSubInfo
class VertexInputInfo
Enumerations
enum vertex_input_t { vertex_input_t::F32, vertex_input_t::V2F32, vertex_input_t::V3F32, vertex_input_t::M3F32 }
The type of a single per-vertex input to the shader program.
enum vertex_primitive_t {
vertex_primitive_t::POINTS, vertex_primitive_t::LINES, vertex_primitive_t::LINE_STRIP, vertex_primitive_t::TRIANGLES,
vertex_primitive_t::TRIANGLE_STRIP, vertex_primitive_t::TRIANGLE_FAN
}
The primitive type that the vertices in a mesh combine into.
enum index_t { index_t::U8, index_t::U16, index_t::U32 }
The type of indices used for indexed rendering.
enum vertex_layout_t { vertex_layout_t::AOS, vertex_layout_t::SOA }
enum shader_lang_t { shader_lang_t::glsl, shader_lang_t::spirv }
The source language of a shader.
enum shader_stage_t {
shader_stage_t::vertex, shader_stage_t::geometry, shader_stage_t::tesselation_control, shader_stage_t::tesselation_evaluation,
shader_stage_t::fragment
}
Shader stages present in modern graphics pipelines.
enum pixel_format {
pixel_format::r16ui, pixel_format::r32ui, pixel_format::rgb8, pixel_format::bgr8,
pixel_format::depth24, pixel_format::rgba8, pixel_format::rgba8ui
}
How the pixels are represented in a texture.
Functions
size_t vertex_input_size (vertex_input_t)
Returns the size in bytes of a per-vertex input.
size_t vertex_input_count (vertex_input_t in)
static constexpr size_t guess_row_alignment (size_t width, pixel_format fmt, size_t row_size)
constexpr size_t pixel_size (pixel_format fmt)
Returns the size in bytes of a single pixel of the specified format.
Variables
static constexpr auto vin_size
static constexpr auto vin_count
static constexpr const std::array< float, 16 > QUAD_DATA
Enumeration Type Documentation
index_t
enum openage::renderer::resources::index_t strong
The type of indices used for indexed rendering.
Enumerator
U8
U16
U32
Definition at line 37 of file mesh_data.h.
                    {
     U8,
     U16,
     U32,
 };
pixel_format
enum openage::renderer::resources::pixel_format strong
How the pixels are represented in a texture.
Enumerator
r16ui
16 bits per pixel, unsigned integer, single channel
r32ui
32 bits per pixel, unsigned integer, single channel
rgb8
24 bits per pixel, float, RGB order
bgr8
24 bits per pixel, float, BGR order
depth24
24 bits per pixel, depth texture
rgba8
32 bits per pixel, float, alpha channel, RGBA order
rgba8ui
32 bits per pixel, unsigned integer, alpha channel, RGBA order
Definition at line 18 of file texture_info.h.
{
     r16ui,
     r32ui,
     rgb8,
     bgr8,
     depth24,
     rgba8,
     rgba8ui,
 };
shader_lang_t
enum openage::renderer::resources::shader_lang_t strong
The source language of a shader.
Enumerator
glsl
spirv
Definition at line 15 of file shader_source.h.
{
     glsl,
     spirv,
 };
shader_stage_t
enum openage::renderer::resources::shader_stage_t strong
Shader stages present in modern graphics pipelines.
Enumerator
vertex
geometry
tesselation_control
tesselation_evaluation
fragment
Definition at line 21 of file shader_source.h.
{
     vertex,
     geometry,
     tesselation_control,
     tesselation_evaluation,
     fragment,
 };
vertex_input_t
enum openage::renderer::resources::vertex_input_t strong
The type of a single per-vertex input to the shader program.
Enumerator
F32
V2F32
V3F32
M3F32
Definition at line 19 of file mesh_data.h.
{
     F32,
     V2F32,
     V3F32,
     M3F32,
 };
vertex_layout_t
enum openage::renderer::resources::vertex_layout_t strong
Enumerator
AOS
Array of structs. XYZUV, XYZUV, XYZUV.
SOA
Struct of arrays. XYZXYZXYZ, UVUVUV.
Definition at line 50 of file mesh_data.h.
{
     AOS,
     SOA,
 };
vertex_primitive_t
enum openage::renderer::resources::vertex_primitive_t strong
The primitive type that the vertices in a mesh combine into.
Enumerator
POINTS
LINES
LINE_STRIP
TRIANGLES
TRIANGLE_STRIP
TRIANGLE_FAN
Definition at line 27 of file mesh_data.h.
{
     POINTS,
     LINES,
     LINE_STRIP,
     TRIANGLES,
     TRIANGLE_STRIP,
     TRIANGLE_FAN,
 };
Function Documentation
guess_row_alignment()
static constexpr size_t openage::renderer::resources::guess_row_alignment (size_t width, pixel_format fmt, size_t row_size) static
Tries to guess the alignment of image rows based on image parameters. Kinda black magic and might not actually work.
Parameters
width in pixels of the image
fmt of pixels in the image
row_size the actual size in bytes of an image row, including padding
Definition at line 22 of file texture_data.cpp.
{
     // Use the highest possible alignment for even-width images.
     if (width % 8 == 0) {
         return 8;
     }
     if (width % 4 == 0) {
         return 4;
     }
     if (width % 2 == 0) {
         return 2;
     }
     // The size of meaningful data in each row.
     size_t pix_bytes = width * pixel_size(fmt);
     // The size of padding.
     size_t padding = row_size - pix_bytes;
     if (padding == 0) {
         return 1;
     }
     if (padding <= 1) {
         return 2;
     }
     if (padding <= 3) {
         return 4;
     }
     if (padding <= 7) {
         return 8;
     }
     // Bail with a sane value.
     return 4;
 }
References pixel_size().
Referenced by openage::renderer::resources::Texture2dData::Texture2dData().
pixel_size()
constexpr size_t openage::renderer::resources::pixel_size (pixel_format fmt)
Returns the size in bytes of a single pixel of the specified format.
Definition at line 36 of file texture_info.h.
{
     constexpr auto pix_size = datastructure::create_const_map<pixel_format, size_t>(
         std::make_pair(pixel_format::r16ui, 2),
         std::make_pair(pixel_format::r32ui, 4),
         std::make_pair(pixel_format::rgb8, 3),
         std::make_pair(pixel_format::bgr8, 3),
         std::make_pair(pixel_format::rgba8, 4),
         std::make_pair(pixel_format::rgba8ui, 4),
         std::make_pair(pixel_format::depth24, 3)
   );
     return pix_size.get(fmt);
 }
References bgr8, depth24, r16ui, r32ui, rgb8, rgba8, and rgba8ui.
Referenced by openage::renderer::resources::Texture2dInfo::get_row_size(), guess_row_alignment(), and openage::renderer::resources::Texture2dData::read_pixel().
vertex_input_count()
size_t openage::renderer::resources::vertex_input_count (vertex_input_t)
Returns the number of elements of the underlying type in a given per-vertex input type. For example, V3F32 has 3 float elements, so the value is 3.
Definition at line 35 of file mesh_data.cpp.
{
     return vin_count.get(in);
 }
References vin_count.
vertex_input_size()
size_t openage::renderer::resources::vertex_input_size (vertex_input_t in)
Returns the size in bytes of a per-vertex input.
Definition at line 31 of file mesh_data.cpp.
{
     return vin_size.get(in);
 }
References vin_size.
Referenced by openage::renderer::resources::VertexInputInfo::vert_size().
Variable Documentation
QUAD_DATA
constexpr const std::array<float, 16> openage::renderer::resources::QUAD_DATA static
Initial value:
= { {
        -1.0f, 1.0f, 0.0f, 1.0f,
        -1.0f, -1.0f, 0.0f, 0.0f,
        1.0f, 1.0f, 1.0f, 1.0f,
        1.0f, -1.0f, 1.0f, 0.0f
    } }
Vertices of a quadrilateral filling the whole screen. Format: (pos, tex_coords) = (x, y, u, v)
Definition at line 116 of file mesh_data.cpp.
Referenced by openage::renderer::resources::MeshData::make_quad().
vin_count
constexpr auto openage::renderer::resources::vin_count static
Initial value:
= datastructure::create_const_map<vertex_input_t, size_t>(
    std::make_pair(vertex_input_t::F32, 1),
    std::make_pair(vertex_input_t::V2F32, 2),
    std::make_pair(vertex_input_t::V3F32, 3),
    std::make_pair(vertex_input_t::M3F32, 9)
)
Definition at line 24 of file mesh_data.cpp.
Referenced by vertex_input_count().
vin_size
constexpr auto openage::renderer::resources::vin_size static
Initial value:
= datastructure::create_const_map<vertex_input_t, size_t>(
    std::make_pair(vertex_input_t::F32, 4),
    std::make_pair(vertex_input_t::V2F32, 8),
    std::make_pair(vertex_input_t::V3F32, 12),
    std::make_pair(vertex_input_t::M3F32, 36)
)
Definition at line 17 of file mesh_data.cpp.
Referenced by vertex_input_size().