openage: openage.util.threading Namespace Reference
openage.util.threading Namespace Reference
Classes
class ClosableQueue
For use in concurrent_chain.
class GeneratorEvent
Functions
def concurrent_chain (generators, jobs=None)
def generator_to_queue (generator, queue)
def test_concurrent_chain ()
Tests concurrent_chain.
Function Documentation
concurrent_chain()
def openage.util.threading.concurrent_chain (generators, jobs = None)
Definition at line 24 of file threading.py.
         jobs = os.cpu_count()
     if jobs == 1:
         # we don't need to do all that threading stuff;
         # let's just behave _precisely_ like itertools.chain.
         for generator in generators:
             yield from generator
         return
     queue = ClosableQueue()
     running_generator_count = 0
     with ThreadPoolExecutor(jobs) as pool:
         for generator in generators:
             pool.submit(generator_to_queue, generator, queue)
             running_generator_count += 1
         while running_generator_count > 0:
             event_type, value = queue.get()
             if event_type == GeneratorEvent.VALUE:
                 yield value
             elif event_type == GeneratorEvent.EXCEPTION:
                 queue.close("Exception in different generator")
                 raise value
             elif event_type == GeneratorEvent.STOP_ITERATION:
                 running_generator_count -= 1
 class ClosableQueue(Queue):
     """
Referenced by openage.convert.driver.convert_media(), and openage.util.threading.test_concurrent_chain().
generator_to_queue()
def openage.util.threading.generator_to_queue (generator, queue)
Definition at line 105 of file threading.py.
         queue.raise_if_closed()
         for item in generator:
             queue.put((GeneratorEvent.VALUE, item))
         queue.put((GeneratorEvent.STOP_ITERATION, None))
     except BaseException as exc:
         queue.put((GeneratorEvent.EXCEPTION, exc))
 def test_concurrent_chain():
     """ Tests concurrent_chain """
test_concurrent_chain()
def openage.util.threading.test_concurrent_chain ()
Tests concurrent_chain.
Definition at line 117 of file threading.py.
     def errorgen():
         """ Test generator that raises an exception """
         yield "errorgen"
         raise ValueError()
     assert_value(list(concurrent_chain([], 2)), [])
     assert_value(list(concurrent_chain([range(10)], 2)), list(range(10)))
     assert_value(
         sorted(list(concurrent_chain([range(10), range(20)], 2))),
         sorted(list(itertools.chain(range(10), range(20))))
     )
     chain = concurrent_chain([range(10), range(20), errorgen(), range(30)], 2)
     with assert_raises(ValueError):
         result(list(chain))
References openage.testing.testing.assert_raises(), openage.testing.testing.assert_value(), openage.util.threading.concurrent_chain(), openage::py.list(), and openage.testing.testing.result().