openage: openage::path Namespace Reference
openage::path Namespace Reference
Namespaces
tests
Classes
struct compare_node_cost
Cost comparison for node_pt.
class Node
One navigation waypoint in a path.
class Path
Represents a planned trajectory.
Typedefs
using heuristic_t = cost_t(*)(const coord::phys3 &start, const coord::phys3 &end)
function pointer type for distance estimation functions.
using cost_t = float
The data type for movement cost.
using node_pt = std::shared_ptr< Node >
Type for storing navigation nodes.
using nodemap_t = std::unordered_map< coord::phys3, node_pt >
Type for mapping tiles to nodes.
using heap_t = datastructure::PairingHeap< node_pt, compare_node_cost >
Priority queue node item type.
Functions
Path to_point (coord::phys3 start, coord::phys3 end, std::function< bool(const coord::phys3 &)> passable)
path between two static points
Path to_object (TerrainObject *to_move, TerrainObject *end, coord::phys_t rad)
path between 2 objects, with how close to come to end point
Path find_nearest (coord::phys3 start, std::function< bool(const coord::phys3 &)> valid_end, std::function< bool(const coord::phys3 &)> passable)
path to nearest object with lambda
Path a_star (coord::phys3 start, std::function< bool(const coord::phys3 &)> valid_end, std::function< cost_t(const coord::phys3 &)> heuristic, std::function< bool(const coord::phys3 &)> passable)
finds a path between two endpoints
cost_t manhattan_cost (const coord::phys3 &start, const coord::phys3 &end)
Manhattan distance cost estimation.
cost_t chebyshev_cost (const coord::phys3 &start, const coord::phys3 &end)
Chebyshev distance cost estimation.
cost_t euclidean_cost (const coord::phys3 &start, const coord::phys3 &end)
Euclidean distance cost estimation.
cost_t euclidean_squared_cost (const coord::phys3 &start, const coord::phys3 &end)
Squared euclidean distance cost estimation.
cost_t euclidean_squared_to_euclidean_cost (const cost_t euclidean_squared_value)
Calculate euclidean distance from a already calculated squared euclidean distance.
bool passable_line (node_pt start, node_pt end, std::function< bool(const coord::phys3 &)>passable, float samples=5.0f)
Variables
constexpr coord::phys_t path_grid_size {1.f/8}
Size of phys-coord grid for path nodes.
constexpr coord::phys3_delta const neigh_phys []
Phys3 delta coordinates to select for path neighbors.
Typedef Documentation
cost_t
using openage::path::cost_t = typedef float
The data type for movement cost.
Definition at line 30 of file path.h.
heap_t
using openage::path::heap_t = typedef datastructure::PairingHeap<node_pt, compare_node_cost>
Priority queue node item type.
Definition at line 55 of file path.h.
heuristic_t
using openage::path::heuristic_t = typedef cost_t (*)(const coord::phys3 &start, const coord::phys3 &end)
function pointer type for distance estimation functions.
Definition at line 13 of file heuristics.h.
node_pt
using openage::path::node_pt = typedef std::shared_ptr<Node>
Type for storing navigation nodes.
Definition at line 35 of file path.h.
nodemap_t
using openage::path::nodemap_t = typedef std::unordered_map<coord::phys3, node_pt>
Type for mapping tiles to nodes.
Definition at line 40 of file path.h.
Function Documentation
a_star()
Path openage::path::a_star (coord::phys3 start, std::function< bool(const coord::phys3 &)> valid_end, std::function< cost_t(const coord::phys3 &)> heuristic, std::function< bool(const coord::phys3 &)> passable)
finds a path between two endpoints
Parameters
start the starting tile coords
end the ending tile coords
heuristic the heuristic for evaluating cost
passable lambda to decide which terrain is passable
Returns
path between the given tiles
Definition at line 66 of file a_star.cpp.
{
     // path node storage, always provides cheapest next node.
     heap_t node_candidates;
     // list of known tiles and corresponding node.
     nodemap_t visited_tiles;
     // add starting node
     node_pt start_node = std::make_shared<Node>(start, nullptr, .0f, heuristic(start));
     visited_tiles[start_node->position] = start_node;
     node_candidates.push(start_node);
     start_node->heap_node = node_candidates.push(start_node);
     // track the closest we can get to the end position
     // used when no path is found
     node_pt closest_node = start_node;
     // while there are candidates to visit
     while (not node_candidates.empty()) {
         node_pt best_candidate = node_candidates.pop();
         best_candidate->was_best = true;
         // node to terminate the search was found
         if (valid_end(best_candidate->position)) {
             log::log(MSG(dbg) <<
                 "path cost is " <<
                 util::FloatFixed<3, 8>{closest_node->future_cost});
             return best_candidate->generate_backtrace();
         }
         // closest node for cases when target cannot be reached
         if (best_candidate->heuristic_cost < closest_node->heuristic_cost) {
             closest_node = best_candidate;
         }
         // evaluate all neighbors of the current candidate for further progress
         for (node_pt neighbor : best_candidate->get_neighbors(visited_tiles)) {
             if (neighbor->was_best) {
                 continue;
             }
             if (not passable_line(best_candidate, neighbor, passable)) {
                 continue;
             }
             bool not_visited = (visited_tiles.count(neighbor->position) == 0);
             cost_t new_past_cost = best_candidate->past_cost + best_candidate->cost_to(*neighbor);
             // if new cost is better than the previous path
             if (not_visited or new_past_cost < neighbor->past_cost) {
                 if (not_visited) {
                     // calculate heuristic only once per node
                     neighbor->heuristic_cost = heuristic(neighbor->position);
                 }
                 if (neighbor->heuristic_cost > closest_node->heuristic_cost * 3) {
                     continue; // dont search forever...
                 }
                 // update new cost knowledge
                 neighbor->past_cost        = new_past_cost;
                 neighbor->future_cost      = neighbor->past_cost + neighbor->heuristic_cost;
                 neighbor->path_predecessor = best_candidate;
                 if (not_visited) {
                     neighbor->heap_node = node_candidates.push(neighbor);
                     visited_tiles[neighbor->position] = neighbor;
                 } else {
                     node_candidates.decrease(neighbor->heap_node);
                 }
             }
         }
     }
     log::log(MSG(dbg) <<
         "incomplete path cost is " <<
         util::FloatFixed<3, 8>{closest_node->future_cost});
     return closest_node->generate_backtrace();
 }
References openage::log::dbg(), openage::datastructure::PairingHeap< T, compare, heapnode_t >::decrease(), openage::datastructure::PairingHeap< T, compare, heapnode_t >::empty(), openage::log::log(), MSG, passable_line(), openage::datastructure::PairingHeap< T, compare, heapnode_t >::pop(), and openage::datastructure::PairingHeap< T, compare, heapnode_t >::push().
Referenced by find_nearest(), to_object(), and to_point().
chebyshev_cost()
cost_t openage::path::chebyshev_cost (const coord::phys3 & start, const coord::phys3 & end)
Chebyshev distance cost estimation.
Returns
y or x difference, whichever is higher.
Definition at line 18 of file heuristics.cpp.
{
     cost_t dx = std::abs(start.ne - end.ne).to_float();
     cost_t dy = std::abs(start.se - end.se).to_float();
     return std::max(dx, dy);
 }
References std::abs(), and std::max().
euclidean_cost()
cost_t openage::path::euclidean_cost (const coord::phys3 & start, const coord::phys3 & end)
Euclidean distance cost estimation.
Returns
the hypotenuse length of the rectangular triangle formed.
Definition at line 24 of file heuristics.cpp.
{
     return (end - start).length();
 }
Referenced by to_point().
euclidean_squared_cost()
cost_t openage::path::euclidean_squared_cost (const coord::phys3 & start, const coord::phys3 & end)
Squared euclidean distance cost estimation.
Returns
the square of the hypotenuse length of the rectangular triangle formed.
Definition at line 28 of file heuristics.cpp.
{
     cost_t dx = (start.ne - end.ne).to_float();
     cost_t dy = (start.se - end.se).to_float();
     return dx * dx + dy * dy;
 }
Referenced by to_point().
euclidean_squared_to_euclidean_cost()
cost_t openage::path::euclidean_squared_to_euclidean_cost (const cost_t euclidean_squared_value)
Calculate euclidean distance from a already calculated squared euclidean distance.
find_nearest()
Path openage::path::find_nearest (coord::phys3 start, std::function< bool(const coord::phys3 &)> valid_end, std::function< bool(const coord::phys3 &)> passable)
path to nearest object with lambda
Definition at line 58 of file a_star.cpp.
{
     // Use Dijkstra (hueristic = 0)
     auto zero = [](const coord::phys3 &) -> cost_t { return .0f; };
     return a_star(start, valid_end, zero, passable);
 }
References a_star().
manhattan_cost()
cost_t openage::path::manhattan_cost (const coord::phys3 & start, const coord::phys3 & end)
Manhattan distance cost estimation.
Returns
the sum of the x and y difference.
Definition at line 12 of file heuristics.cpp.
{
     cost_t dx = std::abs(start.ne - end.ne).to_float();
     cost_t dy = std::abs(start.se - end.se).to_float();
     return dx + dy;
 }
References std::abs().
passable_line()
bool openage::path::passable_line (node_pt start, node_pt end, std::function< bool(const coord::phys3 &)> passable, float samples)
Definition at line 100 of file path.cpp.
{
     // interpolate between points and make passablity checks
     // (dont check starting position)
     for (int i = 1; i <= samples; ++i) {
         // \todo needs more fixed-point
         double percent = (double) i / samples;
         coord::phys_t ne = (1.0 - percent) * start->position.ne.to_double() + percent * end->position.ne.to_double();
         coord::phys_t se = (1.0 - percent) * start->position.se.to_double() + percent * end->position.se.to_double();
         coord::phys_t up = (1.0 - percent) * start->position.up.to_double() + percent * end->position.up.to_double();
         if (!passable(coord::phys3{ne, se, up})) {
             return false;
         }
     }
     return true;
 }
References openage::util::FixedPoint< int_type, fractional_bits >::to_double().
Referenced by a_star(), and openage::path::tests::node_passable_line_0().
to_object()
Path openage::path::to_object (openage::TerrainObject * to_move, openage::TerrainObject * end, coord::phys_t rad)
path between 2 objects, with how close to come to end point
Definition at line 44 of file a_star.cpp.
{
     coord::phys3 start = to_move->pos.draw;
     auto valid_end = [&](const coord::phys3 &pos) -> bool {
         return end->from_edge(pos) < rad;
     };
     auto heuristic = [&](const coord::phys3 &pos) -> cost_t {
         return (end->from_edge(pos) - to_move->min_axis() / 2L).to_float();
     };
     return a_star(start, valid_end, heuristic, to_move->passable);
 }
References a_star(), openage::tile_range::draw, openage::TerrainObject::from_edge(), openage::TerrainObject::min_axis(), openage::TerrainObject::passable, and openage::TerrainObject::pos.
Referenced by openage::MoveAction::set_path(), and openage::IdleAction::update().
to_point()
Path openage::path::to_point (coord::phys3 start, coord::phys3 end, std::function< bool(const coord::phys3 &)> passable)
path between two static points
Definition at line 30 of file a_star.cpp.
{
     auto valid_end = [&](const coord::phys3 &point) -> bool {
         return euclidean_squared_cost(point, end) < path_grid_size.to_float();
     };
     auto heuristic = [&](const coord::phys3 &point) -> cost_t {
         return euclidean_cost(point, end);
     };
     return a_star(start, valid_end, heuristic, passable);
 }
References a_star(), euclidean_cost(), euclidean_squared_cost(), path_grid_size, and openage::util::FixedPoint< int_type, fractional_bits >::to_float().
Referenced by openage::MoveAction::set_path().
Variable Documentation
neigh_phys
constexpr coord::phys3_delta const openage::path::neigh_phys[]
Initial value:
= {
    {path_grid_size *  1, path_grid_size * -1, 0},
    {path_grid_size *  1, path_grid_size *  0, 0},
    {path_grid_size *  1, path_grid_size *  1, 0},
    {path_grid_size *  0, path_grid_size *  1, 0},
    {path_grid_size * -1, path_grid_size *  1, 0},
    {path_grid_size * -1, path_grid_size *  0, 0},
    {path_grid_size * -1, path_grid_size * -1, 0},
    {path_grid_size *  0, path_grid_size * -1, 0}
}
Phys3 delta coordinates to select for path neighbors.
Definition at line 65 of file path.h.
Referenced by openage::path::Node::get_neighbors().
path_grid_size
constexpr coord::phys_t openage::path::path_grid_size {1.f/8}
Size of phys-coord grid for path nodes.
Definition at line 60 of file path.h.
Referenced by openage::UnitAction::adjacent_range(), openage::MoveAbility::invoke(), and to_point().