openage: openage.util.strings Namespace Reference
openage.util.strings Namespace Reference
Functions
def decode_until_null (data, encoding='utf-8')
decodes a bytes object, aborting at the first \0 character.
def try_decode (data)
does its best to attempt decoding the given string of unknown encoding.
def binstr (num, bits=None, group=8)
def colorize (string, colorcode)
Colorizes string with the given EMCA-48 SGR code.
def lstrip_once (string, substr)
Removes substr at the start of string, and raises ValueError on failure.
def rstrip_once (string, substr)
Removes substr at the end of string, and raises ValueError on failure.
def format_progress (progress, total)
Formats an "x out of y" string with fixed width.
Function Documentation
binstr()
def openage.util.strings.binstr (num, bits = None, group = 8)
Definition at line 45 of file strings.py.
     if bits is not None:
         result = result.rjust(bits, '0')
     result = result.replace('0', '_')
     if group is not None:
         grouped = [result[i:i + group] for i in range(0, len(result), group)]
         result = ' '.join(grouped)
     return result
 def colorize(string, colorcode):
     """
     Colorizes string with the given EMCA-48 SGR code.
colorize()
def openage.util.strings.colorize (string, colorcode)
Colorizes string with the given EMCA-48 SGR code.
colorize('foo', '31;1')
'\x1b[31;1mfoo\x1b[m'
Definition at line 66 of file strings.py.
             colorcode=colorcode, string=string)
     else:
         colorized = string
     return colorized
 def lstrip_once(string, substr):
     """
     Removes substr at the start of string, and raises ValueError on failure.
Referenced by openage.util.fsprinting.colorize_dirname(), and openage.util.fsprinting.colorize_filename().
decode_until_null()
def openage.util.strings.decode_until_null (data, encoding = 'utf-8')
decodes a bytes object, aborting at the first \0 character.
decode_until_null(b"foo\\0bar")
'foo'
Definition at line 17 of file strings.py.
         data = data[:end]
     return data.decode(encoding)
 def try_decode(data):
     """
     does its best to attempt decoding the given string of unknown encoding.
Referenced by openage.convert.dataformat.exportable.Exportable.read().
format_progress()
def openage.util.strings.format_progress (progress, total)
Formats an "x out of y" string with fixed width.
format_progress(5, 20)
' 5/20'
Definition at line 114 of file strings.py.
                                                 total=total)
References openage::py.str().
Referenced by openage.convert.main.convert_assets(), and openage.testing.main.main().
lstrip_once()
def openage.util.strings.lstrip_once (string, substr)
Removes substr at the start of string, and raises ValueError on failure.
lstrip_once("openage.test", "openage.")
'test'
lstrip_once("libopenage.test", "openage.")
Traceback (most recent call last): ValueError 'libopenage.test' doesn't start with 'openage.'
Definition at line 85 of file strings.py.
             string=repr(string), substr=repr(substr)))
     return string[len(substr):]
 def rstrip_once(string, substr):
     """
     Removes substr at the end of string, and raises ValueError on failure.
References openage::util.repr().
Referenced by openage.testing.list_processor.get_all_targets().
rstrip_once()
def openage.util.strings.rstrip_once (string, substr)
Removes substr at the end of string, and raises ValueError on failure.
rstrip_once("test.cpp", ".cpp")
'test'
Definition at line 99 of file strings.py.
             "{string} doesn't end with {substr}".format(string=repr(string),
                                                         substr=repr(substr)))
     return string[:-len(substr)]
 def format_progress(progress, total):
     """
     Formats an "x out of y" string with fixed width.
References openage::util.repr().
try_decode()
def openage.util.strings.try_decode (data)
does its best to attempt decoding the given string of unknown encoding.
Definition at line 28 of file strings.py.
     except UnicodeDecodeError:
         pass
     return data.decode('iso-8859-1')
 def binstr(num, bits=None, group=8):
     """
     Similar to the built-in bin(), but optionally takes
     the number of bits as an argument, and prints underscores instead of
     zeroes.
     >>> binstr(1337, 16)
     '_____1_1 __111__1'
     """
     result = bin(num)[2:]
Referenced by openage.cabextract.cab.CABFile.__init__().