openage: openage::util::tests Namespace Reference
openage::util::tests Namespace Reference
Classes
struct testenum
pxd:
struct testenum_value
pxd:
Functions
void constinit_vector ()
void enum_ ()
void fixed_point ()
void siphash ()
void init ()
void matrix ()
void array_conversion ()
void quaternion ()
void vector ()
Variables
static constexpr testenum_value undefined {{"UNDEFINED", 0}, "undefined test string"}
static const std::array< uint8_t, 16 > test_key
Function Documentation
array_conversion()
void openage::util::tests::array_conversion ()
Definition at line 13 of file misc_test.cpp.
{
     {
         static const std::vector<uint8_t> test_array8_big{
             0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef
         };
         static const std::vector<uint8_t> test_array8_little{
             0xef, 0xcd, 0xab, 0x89, 0x67, 0x45, 0x23, 0x01
         };
         static const uint64_t test_uint64{0x0123456789abcdef};
         // Big-endian conversions
         array8_to_uint64(test_array8_big.data(), 8, true) == test_uint64 or TESTFAIL;
         uint64_to_array8(test_uint64, true) == test_array8_big or TESTFAIL;
         // Little-endian conversions
         array8_to_uint64(test_array8_little.data(), 8, false) == test_uint64 or TESTFAIL;
         uint64_to_array8(test_uint64, false) == test_array8_little or TESTFAIL;
     }
     {
         static const std::vector<uint8_t> test_array8_big{
             0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef,
             0xf0, 0xf1, 0xf2, 0xf3, 0xf4, 0xf5, 0xf6, 0xf7
         };
         static const std::vector<uint8_t> test_array8_little{
             0xef, 0xcd, 0xab, 0x89, 0x67, 0x45, 0x23, 0x01,
             0xf7, 0xf6, 0xf5, 0xf4, 0xf3, 0xf2, 0xf1, 0xf0
         };
         static const std::vector<uint64_t> test_array64{
             0x0123456789abcdef, 0xf0f1f2f3f4f5f6f7
         };
         // Big-endian conversions
         array8_to_array64(test_array8_big.data(), 16, true) == test_array64 or TESTFAIL;
         array64_to_array8(test_array64.data(), 2, true) == test_array8_big or TESTFAIL;
         // Little-endian conversions
         array8_to_array64(test_array8_little.data(), 16, false) == test_array64 or TESTFAIL;
         array64_to_array8(test_array64.data(), 2, false) == test_array8_little or TESTFAIL;
     }
     // Now I'm converting 14 instead of 16 bytes, when using array8_to_array64 the
     // remaining bytes should be filled with zeroes.
     {
         static const std::vector<uint8_t> test_array8_big{
             0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef,
             0xf0, 0xf1, 0xf2, 0xf3, 0xf4, 0xf5, 0x00, 0x00
         };
         static const std::vector<uint64_t> test_array64_big{
             0x0123456789abcdef, 0xf0f1f2f3f4f50000
         };
         static const std::vector<uint8_t> test_array8_little{
             0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef,
             0xf7, 0xf6, 0xf5, 0xf4, 0xf3, 0xf2, 0x00, 0x00
         };
         static const std::vector<uint64_t> test_array64_little{
             0xefcdab8967452301, 0x0000f2f3f4f5f6f7
         };
         // Big-endian conversions
         array8_to_array64(test_array8_big.data(), 14, true) == test_array64_big or TESTFAIL;
         array64_to_array8(test_array64_big.data(), 2, true) == test_array8_big or TESTFAIL;
         // Little-endian conversions
         array8_to_array64(test_array8_little.data(), 14, false) == test_array64_little or TESTFAIL;
         array64_to_array8(test_array64_little.data(), 2, false) == test_array8_little or TESTFAIL;
     }
 }
References openage::util::array64_to_array8(), openage::util::array8_to_array64(), openage::util::array8_to_uint64(), TESTFAIL, and openage::util::uint64_to_array8().
constinit_vector()
void openage::util::tests::constinit_vector ()
Definition at line 55 of file constinit_vector.cpp.
{
     ConstInitVector<S> sv;
     for (int i = 0; i < 1337; i++) {
         sv.push_back(S{i});
     }
     sv.size() == 1337 or TESTFAIL;
     sv[235].val == 235 or TESTFAIL;
     int refctr = 0;
     { // scope to test whether tv gets correctly de-inited.
     ConstInitVector<T> tv;
     for (int i = 0; i < 1337; i++) {
         tv.push_back(T(&refctr));
     }
     refctr == 1337 or TESTFAIL;
     sv.size() == 1337 or TESTFAIL;
     }
     refctr == 0 or TESTFAIL;
 }
References openage::util::ConstInitVector< T >::push_back(), openage::util::ConstInitVector< T >::size(), and TESTFAIL.
enum_()
void openage::util::tests::enum_ ()
Definition at line 15 of file enum_test.cpp.
              {
     testenum tv0 = testenum::foo;
     tv0 == testenum::foo or TESTFAIL;
     tv0 != testenum::bar or TESTFAIL;
     testenum tv1 = testenum::bar;
     tv0 == tv1 and TESTFAIL;
     tv1 = testenum::foo;
     tv0 == tv1 or TESTFAIL;
     tv0 != tv1 and TESTFAIL;
     TESTEQUALS(tv0->get_stuff(), std::string("foooooooooooooooooo"));
     TESTEQUALS(tv0->stuff, std::string("foooooooooooooooooo"));
     // "default value"
     testenum tv2;
     TESTEQUALS(tv2->stuff, std::string("undefined test string"));
     tv2 != tv0 or TESTFAIL;
     tv2 != tv1 or TESTFAIL;
     tv2 == tv2 or TESTFAIL;
     FString fstr;
     fstr << tv0;
     TESTEQUALS(fstr.buffer, "openage::util::tests::testenum_value::foo");
     fstr.reset();
     fstr << tv2;
     TESTEQUALS(fstr.buffer, "openage::util::tests::testenum_value::UNDEFINED");
 }
References openage::util::tests::testenum::bar, openage::util::FString::buffer, openage::util::tests::testenum::foo, openage::util::FString::reset(), TESTEQUALS, and TESTFAIL.
fixed_point()
void openage::util::tests::fixed_point ()
Definition at line 15 of file fixed_point_test.cpp.
                    {
     // test construction and assignments
     FixedPoint<int8_t, 4> a(4.3);
     TESTEQUALS(a.to_int(), 4);
     TESTEQUALS(a.to_float(), 4.25);
     TESTEQUALS(a.to_double(), 4.25);
     TESTEQUALS(a.get_raw_value(), 68);
     TESTEQUALS(a.get_fractional_part().to_float(), 0.25);
     FixedPoint<int8_t, 4> b(a);
     TESTEQUALS(b.get_raw_value(), 68);
     auto c = FixedPoint<uint16_t, 8>::from_fixedpoint<int8_t, 4>(a);
     TESTEQUALS(c.get_raw_value(), 1088);
     TESTEQUALS(c.to_int(), 4);
     TESTEQUALS(c.to_double(), 4.25);
     a = FixedPoint<int8_t, 4>::from_int(1);
     TESTEQUALS(a.get_raw_value(), 16);
     a = FixedPoint<int8_t, 4>::from_float(1.3);
     TESTEQUALS(a.get_raw_value(), 20);
     a = FixedPoint<int8_t, 4>::from_double(1.4);
     TESTEQUALS(a.get_raw_value(), 22);
     auto d = FixedPoint<uint64_t, 48>::from_double(2016);
     // this raw value was calculated in python: 2016 * 2**48
     TESTEQUALS(d.get_raw_value(), 567453553048682496UL);
     // test arithmetics
     using TestType = FixedPoint<int64_t, 32>;
     TestType e(120.7);
     TestType f(-12.4);
     e += f;
     TESTEQUALS_FLOAT(e.to_double(), 108.3, 1e-7);
     TESTEQUALS_FLOAT((-e).to_double(), -108.3, 1e-7);
     TESTEQUALS_FLOAT((+e).to_double(), 108.3, 1e-7);
     TESTEQUALS_FLOAT((e - f).to_double(), 120.7, 1e-7);
     TESTEQUALS_FLOAT((e + f).to_double(), 95.9, 1e-7);
     TESTEQUALS_FLOAT((e * 1.02).to_double(), 108.3 * 1.02, 1e-7);
     TESTEQUALS_FLOAT((e * 10).to_double(), 108.3 * 10, 1e-7);
     TESTEQUALS_FLOAT((e / 10).to_double(), 108.3 / 10, 1e-7);
     TESTEQUALS_FLOAT(std::sqrt(e), sqrt(108.3), 1e-7);
     TESTEQUALS_FLOAT(std::abs(-e).to_double(), 108.3, 1e-7);
     TESTEQUALS_FLOAT(std::hypot(e, f), hypot(108.3, -12.4), 1e-7);
     TESTEQUALS_FLOAT(std::min(e, f), -12.4, 1e-7);
     TESTEQUALS_FLOAT(std::max(e, f), 108.3, 1e-7);
     TESTEQUALS_FLOAT(TestType::min_value().to_double(), -2147483648.0, 1e-7);
     TESTEQUALS_FLOAT(TestType::max_value().to_double(), 2147483648.0, 1e-7);
     e -= f;
     TESTEQUALS_FLOAT(e.to_double(), 120.7, 1e-7);
     TESTEQUALS(e == f, false);
     TESTEQUALS(e != f, true);
     TESTEQUALS(e == e, true);
     TESTEQUALS(e <= e, true);
     TESTEQUALS(e >= e, true);
     TESTEQUALS(e >= f, true);
     TESTEQUALS(e <= f, false);
     TESTEQUALS(e < e, false);
     TESTEQUALS(e > e, false);
     TESTEQUALS(e < f, false);
     TESTEQUALS(e > f, true);
     // test the string I/O functions
     FString s;
     s << a;
     TESTEQUALS(std::string(s), "1.38");
     s.reset();
     s << c;
     TESTEQUALS(std::string(s), "4.250");
     s.reset();
     s << d;
     TESTEQUALS(std::string(s), "2016.000000000000000");
     std::stringstream sstr("1234.5678");
     sstr >> e;
     TESTEQUALS_FLOAT(e.to_double(), 1234.5678, 1e-7);
 }
References std::abs(), openage::util::FixedPoint< int_type, fractional_bits >::from_double(), openage::util::FixedPoint< int_type, fractional_bits >::from_float(), openage::util::FixedPoint< int_type, fractional_bits >::from_int(), openage::util::FixedPoint< int_type, fractional_bits >::get_fractional_part(), openage::util::FixedPoint< int_type, fractional_bits >::get_raw_value(), std::hypot(), std::max(), std::min(), openage::util::FString::reset(), std::sqrt(), TESTEQUALS, TESTEQUALS_FLOAT, openage::util::FixedPoint< int_type, fractional_bits >::to_double(), openage::util::FixedPoint< int_type, fractional_bits >::to_float(), and openage::util::FixedPoint< int_type, fractional_bits >::to_int().
init()
void openage::util::tests::init ()
Definition at line 20 of file init.cpp.
             {
     TESTEQUALS(testval, 5);
     int i = 6;
     TESTEQUALS(i, 6);
     {
         OnInit init_i([&]() {
             i = 7;
         });
         OnDeInit deinit_i([&]() {
             i = 8;
         });
         TESTEQUALS(i, 7);
     }
     TESTEQUALS(i, 8);
 }
References TESTEQUALS.
Referenced by openage::event::demo::curvepong(), and openage::options::Var< bool >::Var().
matrix()
void openage::util::tests::matrix ()
Definition at line 12 of file matrix_test.cpp.
               {
     { // matrix multiplication
         const Matrix<5, 3, float> a(0.0, 0.5, 1.0,
                                     1.5, 2.0, 2.5,
                                     3.0, 3.5, 4.0,
                                     4.5, 5.0, 5.5,
                                     6.0, 6.5, 7.0);
         const Matrix<3, 4, float> b(1, 0, 0, 0,
                                     0, 1, 0, 0,
                                     0, 0, 1, 0);
         Matrix<5, 4, float> c = a * b;
         TESTEQUALS_FLOAT(c[0][0], 0, 1e-7);
         TESTEQUALS_FLOAT(c[0][1], 0.5, 1e-7);
         TESTEQUALS_FLOAT(c[0][2], 1, 1e-7);
         TESTEQUALS_FLOAT(c[0][3], 0, 1e-7);
         TESTEQUALS_FLOAT(c[1][0], 1.5, 1e-7);
         TESTEQUALS_FLOAT(c[1][1], 2, 1e-7);
         TESTEQUALS_FLOAT(c[1][2], 2.5, 1e-7);
         TESTEQUALS_FLOAT(c[1][3], 0, 1e-7);
         TESTEQUALS_FLOAT(c[2][0], 3, 1e-7);
         TESTEQUALS_FLOAT(c[2][1], 3.5, 1e-7);
         TESTEQUALS_FLOAT(c[2][2], 4, 1e-7);
         TESTEQUALS_FLOAT(c[2][3], 0, 1e-7);
         TESTEQUALS_FLOAT(c[3][0], 4.5, 1e-7);
         TESTEQUALS_FLOAT(c[3][1], 5, 1e-7);
         TESTEQUALS_FLOAT(c[3][2], 5.5, 1e-7);
         TESTEQUALS_FLOAT(c[3][3], 0, 1e-7);
         TESTEQUALS_FLOAT(c[4][0], 6, 1e-7);
         TESTEQUALS_FLOAT(c[4][1], 6.5, 1e-7);
         TESTEQUALS_FLOAT(c[4][2], 7, 1e-7);
         TESTEQUALS_FLOAT(c[4][3], 0, 1e-7);
     }
     { // addition and subtraction
         const Matrix2f a(1, 2, 3, 4);
         const Matrix2f b(5, 6, 7, 8);
         Matrix2f c = a + b;
         TESTEQUALS_FLOAT(c[0][0], 6, 1e-7);
         TESTEQUALS_FLOAT(c[0][1], 8, 1e-7);
         TESTEQUALS_FLOAT(c[1][0], 10, 1e-7);
         TESTEQUALS_FLOAT(c[1][1], 12, 1e-7);
         c = b - a;
         TESTEQUALS_FLOAT(c[0][0], 4, 1e-7);
         TESTEQUALS_FLOAT(c[0][1], 4, 1e-7);
         TESTEQUALS_FLOAT(c[1][0], 4, 1e-7);
         TESTEQUALS_FLOAT(c[1][1], 4, 1e-7);
     }
     { // scalar multiplication and division
         const Matrix2f a(0, 1, 2, 3);
         Matrix2f b = a * 2;
         TESTEQUALS_FLOAT(b[0][0], 0, 1e-7);
         TESTEQUALS_FLOAT(b[0][1], 2, 1e-7);
         TESTEQUALS_FLOAT(b[1][0], 4, 1e-7);
         TESTEQUALS_FLOAT(b[1][1], 6, 1e-7);
         b = 2 * a;
         TESTEQUALS_FLOAT(b[0][0], 0, 1e-7);
         TESTEQUALS_FLOAT(b[0][1], 2, 1e-7);
         TESTEQUALS_FLOAT(b[1][0], 4, 1e-7);
         TESTEQUALS_FLOAT(b[1][1], 6, 1e-7);
         b = a / 0.5;
         TESTEQUALS_FLOAT(b[0][0], 0, 1e-7);
         TESTEQUALS_FLOAT(b[0][1], 2, 1e-7);
         TESTEQUALS_FLOAT(b[1][0], 4, 1e-7);
         TESTEQUALS_FLOAT(b[1][1], 6, 1e-7);
     }
     { // transposition
         const Matrix2f a(1, 2, 3, 4);
         const Matrix2f b = a.transpose();
         TESTEQUALS_FLOAT(b[0][0], 1, 1e-7);
         TESTEQUALS_FLOAT(b[0][1], 3, 1e-7);
         TESTEQUALS_FLOAT(b[1][0], 2, 1e-7);
         TESTEQUALS_FLOAT(b[1][1], 4, 1e-7);
     }
     { // vector interaction
         const Matrix3f a(2, 0, 0,
                          0, 2, 0,
                          0, 0, 2);
         const Vector3f v(1, 2, 3);
         auto u = (a * v).to_vector();
         TESTEQUALS_FLOAT(u[0], 2, 1e-7);
         TESTEQUALS_FLOAT(u[1], 4, 1e-7);
         TESTEQUALS_FLOAT(u[2], 6, 1e-7);
     }
 }
References TESTEQUALS_FLOAT, and openage::util::Matrix< M, N, T >::transpose().
quaternion()
void openage::util::tests::quaternion ()
Definition at line 16 of file quaternion_test.cpp.
                   {
     {
         // Quaternion construction tests
         const Quaternionf id{};
         Quaternionf id_explicit{1.0, 0.0, 0.0, 0.0};
         id.equals(id_explicit) or TESTFAIL;
         id.equals_deg(id_explicit, 1e-5f) or TESTFAIL;
         Quaternionf wrong{0.0, 0.0, 1.0, 0.0};
         not id.equals(wrong) or TESTFAIL;
         Matrix3f id_mat3 = Matrix3f::identity();
         Quaternionf q_id_mat3{id_mat3};
         id.equals(q_id_mat3) or TESTFAIL;
         Matrix4f id_mat4 = Matrix4f::identity();
         Quaternionf q_id_mat4{id_mat4};
         id.equals(q_id_mat4) or TESTFAIL;
         Matrix4f neg_mat4{
             -1, 0, 0, 0,
             0, 1, 0, 0,
             0, 0, -1, 0,
             0, 0, 0, 1,
         };
         Quaternionf q_neg{neg_mat4};
         Quaternionf q_nex_exp{0, 0, 1, 0};
         q_neg.equals(q_nex_exp) or TESTFAIL;
     }
     {
         // member functions
         Quaternionf q0{1, 2, 3, 4};
         Quaternionf q1{5, 6, 7, 8};
         TESTEQUALS_FLOAT(q0.dot(q1), 5 + 12 + 21 + 32, 1e-5f);
         TESTEQUALS_FLOAT(q0.norm(), 5.4772255 /*= sqrt(30) */, 1e-4f);
         Quaternionf q2{2, 8, 4, 16};
         Quaternionf q2_normd = q2.normalized();
         q2_normd.equals(q2) or TESTFAIL;
         Quaternionf q2conj_exp{2, -8, -4, -16};
         q2conj_exp.equals(q2.conjugated()) or TESTFAIL;
         Quaternionf q2inv_exp{
             0.0058823529411764705f,
             -0.023529411764705882f,
             -0.011764705882352941f,
             -0.047058823529411764f
         };
         Quaternionf q2inv = q2.inversed();
         q2inv.normalized().equals(q2inv_exp.normalized()) or TESTFAIL;
         q2.normalize();
         Quaternionf q2norm_exp{
             0.10846522f, 0.433860915f, 0.216930457f, 0.8677218312f
         };
         q2norm_exp.equals(q2) or TESTFAIL;
     }
     {
         // Operator tests.
         Quaternionf id{};
         Quaternionf bla0{13, 37, 42, 235};
         bla0.equals(id * bla0) or TESTFAIL;
         Quaternionf bla1{8, 16, 24, 32};
         Quaternionf bla0_1_exp{21, 45, 50, 243};
         bla0_1_exp.equals(bla0 + bla1) or TESTFAIL;
         Quaternionf bla1_2_exp{2, 8, 12, 16};
         bla1_2_exp.equals(bla1 / 4) or TESTFAIL;
         Quaternionf bla1_3_exp{16, 64, 96, 128};
         bla1_3_exp.equals(bla1 * 8) or TESTFAIL;
         Quaternionf bla1_4_exp{21, 53, 66, 267};
         bla1_4_exp.equals(bla0 + bla1) or TESTFAIL;
         Quaternionf bla1_5_exp{5, 21, 18, 203};
         bla1_5_exp.equals(bla0 - bla1) or TESTFAIL;
         Quaternionf bla2_exp{
             13 * 21 - 37 * 45 - 42 * 50 - 235 * 243,
             13 * 45 + 37 * 21 + 42 * 243 - 235 * 50,
             13 * 50 - 37 * 243 + 42 * 21 + 235 * 45,
             13 * 243 + 37 * 50 - 42 * 45 + 235 * 21
         };
         bla2_exp.equals(bla0 * bla0_1_exp) or TESTFAIL;
         (bla2_exp == bla2_exp) or TESTFAIL;
         (bla2_exp != bla0) or TESTFAIL;
         Quaternionf bla0_neg_exp{-13, -37, -42, -235};
         bla0_neg_exp.equals(-bla0) or TESTFAIL;
     }
     {
         enum class axis {
             x, y, z
         };
         // Rotation tests
         auto rot_mat = [&](axis a, float am, bool deg=true) -> Matrix3f {
             if (deg) {
                 am = (am * math::PI) / 180.0;
             }
             switch (a) {
             case axis::x:
                 return {
                     1, 0, 0,
                     0, std::cos(am), -std::sin(am),
                     0, std::sin(am), std::cos(am)
                 };
             case axis::y:
                 return {
                     std::cos(am), 0, std::sin(am),
                     0, 1, 0,
                     -std::sin(am), 0, std::cos(am)
                 };
             case axis::z:
                 return {
                     std::cos(am), -std::sin(am), 0,
                     std::sin(am), std::cos(am), 0,
                     0, 0, 1,
                 };
             default:
                 throw Error{ERR << "wtf unreachable code reached"};
             }
         };
         // zero rotation = identity.
         Matrix3f rot = rot_mat(axis::x, 0, false);
         rot.equals(Matrix3f::identity()) or TESTFAIL;
         Quaternionf q_rot{rot};
         Quaternionf q_rot_deg = Quaternionf::from_rad(0, {1, 0, 0});
         q_rot.equals_deg(q_rot_deg) or TESTFAIL;
         // 10 rad rotation
         rot = rot_mat(axis::x, 10, false);
         q_rot = Quaternionf{rot};
         q_rot_deg = Quaternionf::from_rad(10, {1, 0, 0});
         q_rot.equals_rad(q_rot_deg) or TESTFAIL;
         // wrong 90-rad-rotation:
         q_rot_deg = Quaternionf::from_rad(90, {1, 0, 0});
         not q_rot.equals_rad(q_rot_deg) or TESTFAIL;
         // 10 deg rotation
         rot = rot_mat(axis::x, 10);
         q_rot = Quaternionf{rot};
         q_rot_deg = Quaternionf::from_deg(10, {1, 0, 0});
         q_rot.equals_deg(q_rot_deg) or TESTFAIL;
         // 90 deg rotation
         rot = rot_mat(axis::x, 90);
         q_rot = Quaternionf{rot};
         q_rot_deg = Quaternionf::from_deg(90, {1, 0, 0});
         q_rot.equals_deg(q_rot_deg) or TESTFAIL;
         rot = rot_mat(axis::y, 90);
         q_rot = Quaternionf{rot};
         q_rot_deg = Quaternionf::from_deg(90, {0, 1, 0});
         q_rot.equals_deg(q_rot_deg) or TESTFAIL;
         rot = rot_mat(axis::z, 90);
         q_rot = Quaternionf{rot};
         q_rot_deg = Quaternionf::from_deg(90, {0, 0, 1});
         q_rot.equals_deg(q_rot_deg) or TESTFAIL;
         // -90 deg rotation
         rot = rot_mat(axis::y, -90);
         q_rot = Quaternionf{rot};
         q_rot_deg = Quaternionf::from_deg(-90, {0, 1, 0});
         q_rot.equals_deg(q_rot_deg) or TESTFAIL;
         // 45 deg rotation
         rot = rot_mat(axis::z, 45);
         q_rot = Quaternionf{rot};
         q_rot_deg = Quaternionf::from_deg(45, {0, 0, 1});
         q_rot.equals_deg(q_rot_deg) or TESTFAIL;
         // rotation combination
         rot = rot_mat(axis::z, 45) * rot_mat(axis::y, 60);
         q_rot = Quaternionf{rot};
         q_rot_deg = (Quaternionf::from_deg(45, {0, 0, 1}) *
                      Quaternionf::from_deg(60, {0, 1, 0}));
         q_rot.equals_deg(q_rot_deg) or TESTFAIL;
         rot = rot_mat(axis::z, 45) *
               rot_mat(axis::y, 60) *
               rot_mat(axis::x, -200);
         q_rot = Quaternionf{rot};
         q_rot_deg = (Quaternionf::from_deg(45, {0, 0, 1}) *
                      Quaternionf::from_deg(60, {0, 1, 0}) *
                      Quaternionf::from_deg(-200, {1, 0, 0}));
         q_rot.equals_deg(q_rot_deg) or TESTFAIL;
         // to_matrix tests
         rot = rot_mat(axis::x, 235);
         q_rot = Quaternionf::from_deg(235, {1, 0, 0});
         rot.equals(q_rot.to_matrix()) or TESTFAIL;
         rot = rot_mat(axis::y, -55);
         q_rot = Quaternionf::from_deg(-55, {0, 1, 0});
         rot.equals(q_rot.to_matrix()) or TESTFAIL;
         rot = rot_mat(axis::z, 64);
         q_rot = Quaternionf::from_deg(64, {0, 0, 1});
         rot.equals(q_rot.to_matrix()) or TESTFAIL;
     }
     {
         Vector3f vec{5, 0, 0};
         Vector3f turned = Quaternionf::from_deg(180, {0, 0, 1}) * vec;
         Vector3f turned_exp{-5, 0, 0};
         turned.equals(turned_exp) or TESTFAIL;
         // intentional fail:
         turned_exp = Vector3f{-42, -42, -42};
         not turned.equals(turned_exp) or TESTFAIL;
         // another turn
         vec = Vector3f{1337, 42, 235};
         turned = Quaternionf::from_deg(90, {1, 0, 0}) * vec;
         turned_exp = Vector3f{1337, -235, 42};
         turned.equals(turned_exp) or TESTFAIL;
     }
 }
References openage::util::Vector< N, T >::equals(), openage::util::Matrix< M, N, T >::equals(), openage::util::Quaternion< T >::equals(), openage::util::Quaternion< T >::equals_deg(), openage::util::Quaternion< T >::equals_rad(), ERR, openage::util::Quaternion< T >::from_deg(), openage::util::Quaternion< T >::from_rad(), openage::util::Matrix< M, N, T >::identity(), openage::util::Quaternion< T >::inversed(), openage::util::Quaternion< T >::normalized(), openage::math::PI, TESTEQUALS_FLOAT, and TESTFAIL.
siphash()
void openage::util::tests::siphash ()
Definition at line 21 of file hash_test.cpp.
                {
     /*
      * Hash results for some Siphash inputs
      *
      * The test key is 0x000102...0d0e0f
      * The inputs are:
      *    - nothing (zero length)
      *    - 0x00
      *    - 0x0001
      *    - 0x000102
      *    - 0x00010203
      *    - ...
      */
     static const std::array<uint64_t, 64> expected_hashes {{
         0x726fdb47dd0e0e31,0x74f839c593dc67fd,0x0d6c8009d9a94f5a,0x85676696d7fb7e2d,
         0xcf2794e0277187b7,0x18765564cd99a68d,0xcbc9466e58fee3ce,0xab0200f58b01d137,
         0x93f5f5799a932462,0x9e0082df0ba9e4b0,0x7a5dbbc594ddb9f3,0xf4b32f46226bada7,
         0x751e8fbc860ee5fb,0x14ea5627c0843d90,0xf723ca908e7af2ee,0xa129ca6149be45e5,
         0x3f2acc7f57c29bdb,0x699ae9f52cbe4794,0x4bc1b3f0968dd39c,0xbb6dc91da77961bd,
         0xbed65cf21aa2ee98,0xd0f2cbb02e3b67c7,0x93536795e3a33e88,0xa80c038ccd5ccec8,
         0xb8ad50c6f649af94,0xbce192de8a85b8ea,0x17d835b85bbb15f3,0x2f2e6163076bcfad,
         0xde4daaaca71dc9a5,0xa6a2506687956571,0xad87a3535c49ef28,0x32d892fad841c342,
         0x7127512f72f27cce,0xa7f32346f95978e3,0x12e0b01abb051238,0x15e034d40fa197ae,
         0x314dffbe0815a3b4,0x027990f029623981,0xcadcd4e59ef40c4d,0x9abfd8766a33735c,
         0x0e3ea96b5304a7d0,0xad0c42d6fc585992,0x187306c89bc215a9,0xd4a60abcf3792b95,
         0xf935451de4f21df2,0xa9538f0419755787,0xdb9acddff56ca510,0xd06c98cd5c0975eb,
         0xe612a3cb9ecba951,0xc766e62cfcadaf96,0xee64435a9752fe72,0xa192d576b245165a,
         0x0a8787bf8ecb74b2,0x81b3e73d20b49b6f,0x7fa8220ba3b2ecea,0x245731c13ca42499,
         0xb78dbfaf3a8d83bd,0xea1ad565322a1a0b,0x60e61c23a3795013,0x6606d7e446282b93,
         0x6ca4ecb15c5f91e1,0x9f626da15c9625f3,0xe51b38608ef25f57,0x958a324ceb064572
     }};
     std::array<uint8_t, 64> data;
     openage::util::Siphash siphash(test_key);
     for (int i = 0; i < 64; i++) {
         TESTEQUALS(siphash.digest(data.data(), i), expected_hashes[i]);
         data.at(i) = i;
     }
     // Now test the 64bit input digest
     const uint8_t data8[8] = {0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef};
     const uint64_t data64 = 0x0123456789abcdef;
     TESTEQUALS(siphash.digest(data8, 8), siphash.digest(data64));
 }
References test_key, and TESTEQUALS.
Referenced by openage::rng::RNG::seed().
vector()
void openage::util::tests::vector ()
Definition at line 11 of file vector_test.cpp.
               {
     {
         // zero-initialization test.
         Vectorf<5> zero_explicit{0, 0, 0, 0, 0};
         Vectorf<5> zero;
         zero.equals(zero_explicit) or TESTFAIL;
     }
     {
         // tests in 2 dimensions.
         // we want to be able to reuse the variable names later.
         const Vectorf<2> a(1.0, 2.0);
         const Vectorf<2> b(3.0, 4.0);
         Vectorf<2> c;
         // test basic operators.
         c = a + b;
         c.equals({4.0, 6.0}) or TESTFAIL;
         c = a - b;
         c.equals({-2.0, -2.0}) or TESTFAIL;
         c = 5 * a;
         c.equals({5.0, 10.0}) or TESTFAIL;
         c = a / 8;
         c.equals({0.125, 0.25}) or TESTFAIL;
         c.equals({13, 37}) and TESTFAIL;
         // test dot product, norm and normalization.
         TESTEQUALS_FLOAT(a.dot(b), 11, 1e-7);
         c = b;
         TESTEQUALS_FLOAT(c.norm(), 5, 1e-7);
         c.normalize();
         TESTEQUALS_FLOAT(c.norm(), 1, 1e-7);
     }
     {
         // test for the cross_product
         const Vectorf<3> a(1.0, 2.0, 3.0);
         const Vectorf<3> b(4.0, 5.0, 6.0);
         Vectorf<3> c = a.cross_product(b);
         c.equals({-3.0, 6.0, -3.0}) or TESTFAIL;
     }
 }
References openage::util::Vector< N, T >::cross_product(), openage::util::Vector< N, T >::dot(), openage::util::Vector< N, T >::equals(), TESTEQUALS_FLOAT, and TESTFAIL.
Variable Documentation
test_key
const std::array<uint8_t, 16> openage::util::tests::test_key static
Initial value:
{{
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
    0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f
}}
Definition at line 15 of file hash_test.cpp.
Referenced by siphash().
undefined
constexpr testenum_value openage::util::tests::undefined {{"UNDEFINED", 0}, "undefined test string"} static
Definition at line 12 of file enum_test.cpp.
Referenced by openage::util::tests::testenum::testenum().