openage: openage::console Namespace Reference
openage::console Namespace Reference
In-game console subsystem.
Namespaces
draw
tests
Classes
class Buf
struct buf_char
a single character in the buffer
struct buf_line
metadata for a single line in the buffer
class Console
class NewBuf
Typedefs
using chrcol_t = uint8_t
the length of the escape sequence buffer, and thus the maximum length of any escape sequence that will be successfully processed.
using chrflags_t = uint16_t
using linetype_t = uint8_t
Functions
void print_cps (FILE *f, std::vector< int > *v)
Variables
constexpr chrflags_t CHR_BOLD = (1 << 0)
constexpr chrflags_t CHR_FAINT = (1 << 1)
constexpr chrflags_t CHR_ITALIC = (1 << 2)
constexpr chrflags_t CHR_BLINKING = (1 << 3)
constexpr chrflags_t CHR_BLINKINGFAST = (1 << 4)
constexpr chrflags_t CHR_UNDERLINED = (1 << 5)
constexpr chrflags_t CHR_STRUCKOUT = (1 << 6)
constexpr chrflags_t CHR_FRAKTUR = (1 << 7)
constexpr chrflags_t CHR_NEGATIVE = (1 << 8)
constexpr chrflags_t CHR_INVISIBLE = (1 << 9)
constexpr chrflags_t CHR_FRAMED = (1 << 10)
constexpr chrflags_t CHR_ENCIRCLED = (1 << 11)
constexpr chrflags_t CHR_OVERLINED = (1 << 12)
constexpr chrflags_t CHR_RIGHTLINED = (1 << 13)
constexpr chrflags_t CHR_LEFTLINED = (1 << 14)
constexpr chrflags_t CHR_STRESS_IDEOGRAM = (1 << 15)
constexpr linetype_t LINE_EMPTY = 0
the line has not been written yet (or cleared in between)
constexpr linetype_t LINE_REGULAR = 1
the line has some contents
constexpr linetype_t LINE_WRAPPED = 2
the line has been written to until it auto-wrapped; its continuation can be found in the next line
constexpr buf_line BUF_LINE_DEFAULT {LINE_EMPTY}
Detailed Description
In-game console subsystem.
Featuring a full terminal emulator.
Typedef Documentation
chrcol_t
using openage::console::chrcol_t = typedef uint8_t
the length of the escape sequence buffer, and thus the maximum length of any escape sequence that will be successfully processed.
longer escape sequences will be ignored.
Definition at line 27 of file buf.h.
chrflags_t
using openage::console::chrflags_t = typedef uint16_t
Definition at line 28 of file buf.h.
linetype_t
using openage::console::linetype_t = typedef uint8_t
Definition at line 94 of file buf.h.
Function Documentation
print_cps()
void openage::console::print_cps (FILE * f, std::vector< int > * v)
Definition at line 599 of file buf.cpp.
{
     for (int i: *v) {
         if (i >= 0x20 and i < 0x7f) {
             fprintf(f, "%c", (char) i);
         } else {
             fprintf(f, "?");
         }
     }
 }
Referenced by openage::console::Buf::escape_sequence_aborted().
Variable Documentation
BUF_LINE_DEFAULT
constexpr buf_line openage::console::BUF_LINE_DEFAULT {LINE_EMPTY}
Definition at line 119 of file buf.h.
Referenced by openage::console::Buf::linedata_clear(), and openage::console::NewBuf::move_ptrs_to_next_line().
CHR_BLINKING
constexpr chrflags_t openage::console::CHR_BLINKING = (1 << 3)
Definition at line 33 of file buf.h.
Referenced by openage::console::Buf::process_sgr_code(), openage::console::draw::to_opengl(), and openage::console::draw::to_terminal().
CHR_BLINKINGFAST
constexpr chrflags_t openage::console::CHR_BLINKINGFAST = (1 << 4)
Definition at line 34 of file buf.h.
Referenced by openage::console::Buf::process_sgr_code(), and openage::console::draw::to_opengl().
CHR_BOLD
constexpr chrflags_t openage::console::CHR_BOLD = (1 << 0)
Definition at line 30 of file buf.h.
Referenced by openage::console::Buf::process_sgr_code(), and openage::console::draw::to_terminal().
CHR_ENCIRCLED
constexpr chrflags_t openage::console::CHR_ENCIRCLED = (1 << 11)
Definition at line 41 of file buf.h.
Referenced by openage::console::Buf::process_sgr_code().
CHR_FAINT
constexpr chrflags_t openage::console::CHR_FAINT = (1 << 1)
Definition at line 31 of file buf.h.
Referenced by openage::console::Buf::process_sgr_code().
CHR_FRAKTUR
constexpr chrflags_t openage::console::CHR_FRAKTUR = (1 << 7)
Definition at line 37 of file buf.h.
Referenced by openage::console::Buf::process_sgr_code().
CHR_FRAMED
constexpr chrflags_t openage::console::CHR_FRAMED = (1 << 10)
Definition at line 40 of file buf.h.
Referenced by openage::console::Buf::process_sgr_code().
CHR_INVISIBLE
constexpr chrflags_t openage::console::CHR_INVISIBLE = (1 << 9)
Definition at line 39 of file buf.h.
Referenced by openage::console::Buf::process_sgr_code(), and openage::console::draw::to_opengl().
CHR_ITALIC
constexpr chrflags_t openage::console::CHR_ITALIC = (1 << 2)
Definition at line 32 of file buf.h.
Referenced by openage::console::Buf::process_sgr_code().
CHR_LEFTLINED
constexpr chrflags_t openage::console::CHR_LEFTLINED = (1 << 14)
Definition at line 44 of file buf.h.
Referenced by openage::console::Buf::process_sgr_code().
CHR_NEGATIVE
constexpr chrflags_t openage::console::CHR_NEGATIVE = (1 << 8)
Definition at line 38 of file buf.h.
Referenced by openage::console::Buf::process_sgr_code(), openage::console::draw::to_opengl(), and openage::console::draw::to_terminal().
CHR_OVERLINED
constexpr chrflags_t openage::console::CHR_OVERLINED = (1 << 12)
Definition at line 42 of file buf.h.
Referenced by openage::console::Buf::process_sgr_code().
CHR_RIGHTLINED
constexpr chrflags_t openage::console::CHR_RIGHTLINED = (1 << 13)
Definition at line 43 of file buf.h.
Referenced by openage::console::Buf::process_sgr_code().
CHR_STRESS_IDEOGRAM
constexpr chrflags_t openage::console::CHR_STRESS_IDEOGRAM = (1 << 15)
Definition at line 45 of file buf.h.
Referenced by openage::console::Buf::process_sgr_code().
CHR_STRUCKOUT
constexpr chrflags_t openage::console::CHR_STRUCKOUT = (1 << 6)
Definition at line 36 of file buf.h.
Referenced by openage::console::Buf::process_sgr_code().
CHR_UNDERLINED
constexpr chrflags_t openage::console::CHR_UNDERLINED = (1 << 5)
Definition at line 35 of file buf.h.
Referenced by openage::console::Buf::process_sgr_code().
LINE_EMPTY
constexpr linetype_t openage::console::LINE_EMPTY = 0
the line has not been written yet (or cleared in between)
Definition at line 99 of file buf.h.
Referenced by openage::console::Buf::pop_last_char(), and openage::console::Buf::print_codepoint().
LINE_REGULAR
constexpr linetype_t openage::console::LINE_REGULAR = 1
the line has some contents
Definition at line 103 of file buf.h.
Referenced by openage::console::NewBuf::new_chr(), openage::console::Buf::pop_last_char(), and openage::console::Buf::print_codepoint().
LINE_WRAPPED
constexpr linetype_t openage::console::LINE_WRAPPED = 2
the line has been written to until it auto-wrapped; its continuation can be found in the next line
this value is required for re-calculating the buffer on resize
Definition at line 110 of file buf.h.
Referenced by openage::console::NewBuf::new_chr(), openage::console::Buf::pop_last_char(), and openage::console::Buf::print_codepoint().