openage: openage::curve::tests Namespace Reference
openage::curve::tests Namespace Reference
Classes
struct map_test_element
Functions
std::ostream & operator<< (std::ostream &o, const map_test_element &e)
template<typename key_t , typename val_t >
void dump (const std::unordered_map< key_t, val_t > &map)
void test_map ()
void test_list ()
void test_queue ()
void container ()
void curve_types ()
Function Documentation
container()
void openage::curve::tests::container ()
Definition at line 205 of file container.cpp.
                  {
     test_map();
     test_list();
     test_queue();
 }
References test_list(), test_map(), and test_queue().
Referenced by openage::curve::Queue< T >::begin(), openage::curve::Queue< T >::between(), openage::curve::Queue< T >::clean(), openage::curve::Queue< T >::clear(), openage::curve::Queue< T >::end(), openage::curve::Queue< T >::erase(), openage::curve::KeyframeContainer< T >::erase(), openage::curve::KeyframeContainer< T >::erase_after(), openage::AttackAction::fire_projectile(), openage::util::for_each(), openage::curve::ValueContainer< T >::frame(), openage::curve::Queue< T >::front(), openage::curve::Continuous< T >::get(), openage::curve::Discrete< T >::get(), openage::curve::Discrete< T >::get_previous(), openage::curve::Discrete< T >::get_time(), openage::curve::Queue< T >::insert(), openage::curve::KeyframeContainer< T >::last(), openage::curve::ValueContainer< T >::next_frame(), openage::EditorMode::paint_entity_at(), openage::ActionMode::place_selection(), openage::util::remove_from(), openage::curve::ValueContainer< T >::set_insert(), openage::curve::ValueContainer< T >::set_last(), and openage::TrainAction::update().
curve_types()
void openage::curve::tests::curve_types ()
Definition at line 14 of file curve_types.cpp.
                    {
     // Check the base container type
     {
         auto loop = std::make_shared<event::Loop>();
         KeyframeContainer<int> c{loop};
         auto p0 = c.insert(0, 0);
         auto p1 = c.insert(1, 1);
         auto p2 = c.insert(10, 2);
         // last function tests without hints
         TESTEQUALS(c.last(0)->value, 0);
         TESTEQUALS(c.last(1)->value, 1); // last shall give >= not only > !
         TESTEQUALS(c.last(5)->value, 1);
         TESTEQUALS(c.last(10)->value, 2);
         TESTEQUALS(c.last(47)->value, 2);
         // last() with hints. Yes this can make a difference. we want to be
         // absolutely sure!
         TESTEQUALS(c.last(0, p0)->value, 0);
         TESTEQUALS(c.last(1, p0)->value, 1); // last shall give >= not only > !
         TESTEQUALS(c.last(5, p0)->value, 1);
         TESTEQUALS(c.last(10, p0)->value, 2);
         TESTEQUALS(c.last(47, p0)->value, 2);
         TESTEQUALS(c.last(0, p1)->value, 0);
         TESTEQUALS(c.last(1, p1)->value, 1); // last shall give >= not only > !
         TESTEQUALS(c.last(5, p1)->value, 1);
         TESTEQUALS(c.last(10, p1)->value, 2);
         TESTEQUALS(c.last(47, p1)->value, 2);
         TESTEQUALS(c.last(0, p2)->value, 0);
         TESTEQUALS(c.last(1, p2)->value, 1); // last shall give >= not only > !
         TESTEQUALS(c.last(5, p2)->value, 1);
         TESTEQUALS(c.last(10, p2)->value, 2);
         TESTEQUALS(c.last(47, p2)->value, 2);
         // Now test the basic erase() function
         // Delete the 1-element, new values should be [0, 2]
         c.erase(c.last(1));
         TESTEQUALS(c.last(1)->value, 0);
         TESTEQUALS(c.last(5)->value, 0);
         TESTEQUALS(c.last(47)->value, 2);
         // should do nothing, since we delete all at > 99,
         // but the last element is at 10.
         c.erase_after(c.last(99));
         TESTEQUALS(c.last(47)->value, 2);
         // now since 5 < 10, element with value 2 has to be gone
         c.erase_after(c.last(5));
         TESTEQUALS(c.last(47)->value, 0);
     }
     // Check the Simple Continuous type
     {
         auto f = std::make_shared<event::Loop>();
         Continuous<float> c(f, 0);
         c.set_insert(0, 0);
         c.set_insert(10, 1);
         TESTEQUALS(c.get(0), 0);
         TESTEQUALS_FLOAT(c.get(1), 0.1, 1e-7);
     }
     {
         auto f = std::make_shared<event::Loop>();
         Continuous<float> c(f, 0);
         log::log(DBG << "Testing Continuous float");
         c.set_insert(0, 0);
         log::log(DBG << "Inserting t:20, v:20");
         c.set_insert(20, 20);
         TESTEQUALS(c.get(0), 0);
         TESTEQUALS(c.get(1), 1);
         TESTEQUALS(c.get(7), 7);
         c.set_last(20, 10);
         log::log(DBG << "Inserting t:20, v:10. This should overwrite the old values!");
         TESTEQUALS(c.get(0), 0);
         TESTEQUALS(c.get(2), 1);
         TESTEQUALS(c.get(8), 4);
     }
     //Check the discrete type
     {
         auto f = std::make_shared<event::Loop>();
         Discrete<int> c(f, 0);
         c.set_insert(0, 0);
         c.set_insert(10, 10);
         TESTEQUALS(c.get(0), 0);
         TESTEQUALS(c.get(1), 0);
         TESTEQUALS(c.get(10), 10);
         Discrete<std::string> complex(f, 0);
         complex.set_insert(0, "Test 0");
         complex.set_insert(10, "Test 10");
         TESTEQUALS(complex.get(0), "Test 0");
         TESTEQUALS(complex.get(1), "Test 0");
         TESTEQUALS(complex.get(10), "Test 10");
     }
     //check set_last
     {
         auto f = std::make_shared<event::Loop>();
         Discrete<int> c(f, 0);
         c.set_insert(0, 0);
         c.set_insert(1, 1);
         c.set_insert(3, 3);
         TESTEQUALS(c.get(3), 3);
         c.set_last(2, 10);
         TESTEQUALS(c.get(2), 10);
     }
     // Encountered Errors
     {
         auto f = std::make_shared<event::Loop>();
         Continuous<int> c(f, 0);
         c.set_insert(1, 1);
         c.set_last(1, -5);
         TESTEQUALS(c.get(1), -5);
     }
 }
References DBG, openage::curve::Continuous< T >::get(), openage::curve::Discrete< T >::get(), openage::curve::KeyframeContainer< T >::insert(), openage::log::log(), openage::curve::ValueContainer< T >::set_insert(), openage::curve::ValueContainer< T >::set_last(), TESTEQUALS, and TESTEQUALS_FLOAT.
dump()
template<typename key_t , typename val_t > void openage::curve::tests::dump (const std::unordered_map< key_t, val_t > & map)
Definition at line 34 of file container.cpp.
{
     for (const auto &i : map) {
         std::cout << i.first << ": " << i.second << std::endl;
     }
 }
References map.
operator<<()
std::ostream& openage::curve::tests::operator<< (std::ostream & o, const map_test_element & e)
Definition at line 28 of file container.cpp.
{
     o << e.value;
     return o;
 }
References openage::curve::tests::map_test_element::value.
test_list()
void openage::curve::tests::test_list ()
Definition at line 134 of file container.cpp.
                  {
 }
Referenced by container().
test_map()
void openage::curve::tests::test_map ()
Definition at line 40 of file container.cpp.
                 {
     static_assert(std::is_copy_constructible<MapFilterIterator<int, int, UnorderedMap<int, int>>>::value,
                   "UnorderedMapIterator not Copy Constructable able");
     static_assert(std::is_copy_assignable<MapFilterIterator<int, int, UnorderedMap<int, int>>>::value,
                   "UnorderedMapIterator not Copy Assignable");
     UnorderedMap<int, int> map;
     map.insert(0, 10, 0, 0);
     map.insert(5, 10, 5, 1);
     map.insert(100, 200, 200, 2);
     // Basic tests test lookup in the middle of the range.
     {
         auto t = map.at(2, 0); //At timestamp 2 element 0
         TESTEQUALS(t.has_value(), true);
         TESTEQUALS(t.value().value(), 0);
         t = map.at(20, 5);
         TESTEQUALS(t.has_value(), false);
     }
     {
         auto t = map.at(7, 5);
         TESTEQUALS(t.has_value(), true);
         TESTEQUALS(t.value().value(), 1);
         t = map.at(20, 5);
         TESTEQUALS(t.has_value(), false);
         t = map.at(2, 5);
         TESTEQUALS(t.has_value(), false);
     }
     {
         auto t = map.at(150, 200);
         TESTEQUALS(t.has_value(), true);
         TESTEQUALS(t.value().value(), 2);
         t = map.at(500, 200);
         TESTEQUALS(t.has_value(), false);
         t = map.at(5, 200);
         TESTEQUALS(t.has_value(), false);
     }
     // test 2.0: test at the boundaries
     {
         auto t = map.at(0, 0);
         TESTEQUALS(t.has_value(), true);
         TESTEQUALS(t.value().value(), 0);
         t = map.at(10, 0);
         TESTEQUALS(t.has_value(), false);
     }
     {
         auto t = map.at(5, 5);
         TESTEQUALS(t.has_value(), true);
         TESTEQUALS(t.value().value(), 1);
         t = map.at(10, 5);
         TESTEQUALS(t.has_value(), false);
     }
     {
         auto t = map.at(100, 200);
         TESTEQUALS(t.has_value(), true);
         TESTEQUALS(t.value().value(), 2);
         t = map.at(200, 200);
         TESTEQUALS(t.has_value(), false);
     }
     // Test 3.0 Iterations
     {
         // Iteration tests
         std::unordered_map<int, int> reference;
         reference[0] = 0;
         reference[5] = 1;
         reference[200] = 2;
         for (auto it = map.begin(0); it != map.end(); ++it) { // Get all
             auto ri = reference.find(it.key());
             if (ri != reference.end()) {
                 reference.erase(ri);
             }
         }
         TESTEQUALS(reference.empty(), true);
         reference[5] = 5;
         for (auto it = map.begin(1); it != map.end(90); ++it) {
             auto ri = reference.find(it.key());
             if (ri != reference.end()) {
                 reference.erase(ri);
             }
         }
         TESTEQUALS(reference.empty(), true);
         reference[5] = 5;
         for (auto it = map.between(1,90); it != map.end(); ++it) {
             auto ri = reference.find(it.key());
             if (ri != reference.end()) {
                 reference.erase(ri);
             }
         }
         TESTEQUALS(reference.empty(), true);
     }
 }
References map, and TESTEQUALS.
Referenced by container().
test_queue()
void openage::curve::tests::test_queue ()
Definition at line 138 of file container.cpp.
                   {
     static_assert(std::is_copy_constructible<QueueFilterIterator<int, Queue<int>>>::value,
                   "QueueIterator not Copy Constructable able");
     static_assert(std::is_copy_assignable<QueueFilterIterator<int, Queue<int>>>::value,
                   "QueueIterator not Copy Assignable");
     Queue<int> q;
     q.insert(0, 1);
     q.insert(2, 2);
     q.insert(4, 3);
     q.insert(10, 4);
     q.insert(100001, 5);
     TESTEQUALS(*q.begin(0), 1);
     TESTEQUALS(*q.begin(1), 2);
     TESTEQUALS(*q.begin(2), 2);
     TESTEQUALS(*q.begin(3), 3);
     TESTEQUALS(*q.begin(4), 3);
     TESTEQUALS(*q.begin(5), 4);
     TESTEQUALS(*q.begin(10), 4);
     TESTEQUALS(*q.begin(12), 5);
     TESTEQUALS(*q.begin(100000), 5);
     {
         std::unordered_set<int> reference = {1,2,3};
         for (auto it = q.between(0,6); it != q.end(); ++it) {
             auto ri = reference.find(it.value());
             if (ri != reference.end()) {
                 reference.erase(ri);
             }
         }
         TESTEQUALS(reference.empty(), true);
     }
     {
         std::unordered_set<int> reference = {2,3,4};
         for (auto it = q.between(1,40); it != q.end(); ++it) {
             auto ri = reference.find(it.value());
             if (ri != reference.end()) {
                 reference.erase(ri);
             }
         }
         TESTEQUALS(reference.empty(), true);
     }
     {
         std::unordered_set<int> reference = {};
         for (auto it = q.between(30,40); it != q.end(); ++it) {
             auto ri = reference.find(it.value());
             if (ri != reference.end()) {
                 reference.erase(ri);
             }
         }
         TESTEQUALS(reference.empty(), true);
     }
     {
         std::unordered_set<int> reference = {1,2,3,4};
         for (auto it = q.between(0,40); it != q.end(); ++it) {
             auto ri = reference.find(it.value());
             if (ri != reference.end()) {
                 reference.erase(ri);
             }
         }
         TESTEQUALS(reference.empty(), true);
     }
 }
References openage::curve::Queue< T >::begin(), openage::curve::Queue< T >::between(), openage::curve::Queue< T >::end(), openage::curve::Queue< T >::insert(), and TESTEQUALS.
Referenced by container().