openage: openage::input Namespace Reference
openage::input Namespace Reference
The openage input layer.
Namespaces
tests
Classes
struct action_arg_t
Contains information about a triggered event.
class ActionManager
The action manager manages all the actions allow creation, access information and equality.
struct class_code_hash
class ClassCode
base event type containing event class and event code
class Event
Input event, as triggered by some input device like mouse, kezb, joystick, tablet, microwave or dildo.
struct event_class_hash
struct event_hash
class InputContext
An input context contains all keybindings and actions active in e.g.
class InputManager
The input manager manages all input layers (hud, game, ...) and triggers the registered actions depending on the active layer.
struct modifier_hash
Typedefs
using action_t = unsigned int
Used to identify actions.
using action_id_t = action_t
using action_func_t = std::function< void(const action_arg_t &)>
Performs the effect of an action.
using action_check_t = std::function< bool(const action_arg_t &)>
For receivers of sets of events a bool is returned to indicate if the event was used.
using code_t = int
types used by events
using modset_t = std::unordered_set< modifier, modifier_hash >
using event_set_t = std::unordered_set< Event, event_hash >
using binding_map_t = std::unordered_map< action_t, Event >
maps actions to events.
Enumerations
enum event_class {
event_class::ANY, event_class::KEYBOARD, event_class::CHAR, event_class::ALPHA,
event_class::DIGIT, event_class::PRINT, event_class::NONPRINT, event_class::OTHER,
event_class::UTF8, event_class::MOUSE, event_class::MOUSE_BUTTON, event_class::MOUSE_BUTTON_UP,
event_class::MOUSE_BUTTON_DOWN, event_class::MOUSE_WHEEL, event_class::MOUSE_MOTION
}
highest level classes of input
enum modifier { modifier::CTRL, modifier::ALT, modifier::SHIFT }
mods set on an event
Functions
bool operator== (ClassCode a, ClassCode b)
modset_t sdl_mod (SDL_Keymod mod)
Event sdl_key (SDL_Keycode code, SDL_Keymod mod)
Event utf8 (const std::string &text)
Event sdl_mouse (int button, SDL_Keymod mod)
Event sdl_mouse_up_down (int button, bool up, SDL_Keymod mod)
Event sdl_wheel (int direction, SDL_Keymod mod)
Event text_to_event (const std::string &event_str)
Convert a string to an event, throw if the string is not a valid event.
Variables
static std::unordered_map< event_class, event_class, event_class_hash > event_base
each event type mapped to parent type
Detailed Description
The openage input layer.
It gets all the events and processes them accordingly.
Typedef Documentation
action_check_t
using openage::input::action_check_t = typedef std::function<bool(const action_arg_t &)>
For receivers of sets of events a bool is returned to indicate if the event was used.
Definition at line 96 of file action.h.
action_func_t
using openage::input::action_func_t = typedef std::function<void(const action_arg_t &)>
Performs the effect of an action.
Definition at line 89 of file action.h.
action_id_t
using openage::input::action_id_t = typedef action_t
Definition at line 65 of file action.h.
action_t
using openage::input::action_t = typedef unsigned int
Used to identify actions.
Definition at line 27 of file action.h.
binding_map_t
using openage::input::binding_map_t = typedef std::unordered_map<action_t, Event>
maps actions to events.
Definition at line 29 of file input_manager.h.
code_t
using openage::input::code_t = typedef int
types used by events
Definition at line 78 of file event.h.
event_set_t
using openage::input::event_set_t = typedef std::unordered_set<Event, event_hash>
Definition at line 148 of file event.h.
modset_t
using openage::input::modset_t = typedef std::unordered_set<modifier, modifier_hash>
Definition at line 79 of file event.h.
Enumeration Type Documentation
event_class
enum openage::input::event_class strong
highest level classes of input
Enumerator
ANY
KEYBOARD
CHAR
ALPHA
DIGIT
PRINT
NONPRINT
OTHER
UTF8
MOUSE
MOUSE_BUTTON
MOUSE_BUTTON_UP
MOUSE_BUTTON_DOWN
MOUSE_WHEEL
MOUSE_MOTION
Definition at line 18 of file event.h.
{
     ANY,
     KEYBOARD,
     CHAR,           // basic keycodes (lower-case, non-modified)
     ALPHA,          // abc
     DIGIT,          // 123
     PRINT,          // remaining printable chars
     NONPRINT,       // tab, return, backspace, delete
     OTHER,          // arrows, home, end
     UTF8,           // events with utf8 encoded data
     MOUSE,
     MOUSE_BUTTON,
     MOUSE_BUTTON_UP,
     MOUSE_BUTTON_DOWN,
     MOUSE_WHEEL,
     MOUSE_MOTION
 };
modifier
enum openage::input::modifier strong
mods set on an event
Enumerator
CTRL
ALT
SHIFT
Definition at line 63 of file event.h.
                     {
     CTRL,
     ALT,
     SHIFT
 };
Function Documentation
operator==()
bool openage::input::operator== (ClassCode a, ClassCode b)
Definition at line 41 of file event.cpp.
{
     return a.eclass == b.eclass && a.code == b.code;
 }
References openage::input::ClassCode::code, and openage::input::ClassCode::eclass.
sdl_key()
Event openage::input::sdl_key (SDL_Keycode code, SDL_Keymod mod)
Definition at line 127 of file event.cpp.
{
     // sdl values for non printable keys
     if (code & (1 << 30)) {
         return Event(event_class::OTHER, code, sdl_mod(mod));
     }
     else {
         event_class ec;
         char c = (code & 0xff);
         if (isdigit(c)) {
             ec = event_class::DIGIT;
         }
         else if (isalpha(c)) {
             ec = event_class::ALPHA;
         }
         else if (isprint(c)) {
             ec = event_class::PRINT;
         }
         else {
             ec = event_class::NONPRINT;
         }
         return Event(ec, code, sdl_mod(mod));
     }
 }
References ALPHA, DIGIT, openage::util::mod(), NONPRINT, OTHER, PRINT, and sdl_mod().
Referenced by openage::input::InputManager::is_down(), and openage::input::InputManager::on_input().
sdl_mod()
modset_t openage::input::sdl_mod (SDL_Keymod mod)
Definition at line 110 of file event.cpp.
{
     // Remove modifiers like num lock and caps lock
     // mod = static_cast<SDL_Keymod>(mod & this->used_keymods);
     modset_t result;
     if (mod & KMOD_CTRL) {
         result.emplace(modifier::CTRL);
     }
     if (mod & KMOD_SHIFT) {
         result.emplace(modifier::SHIFT);
     }
     if (mod & KMOD_ALT) {
         result.emplace(modifier::ALT);
     }
     return result;
 }
References ALT, CTRL, openage::util::mod(), openage.testing.testing::result(), and SHIFT.
Referenced by openage::input::InputManager::get_mod(), openage::input::tests::parse_event_string(), sdl_key(), sdl_mouse(), sdl_mouse_up_down(), and sdl_wheel().
sdl_mouse()
Event openage::input::sdl_mouse (int button, SDL_Keymod mod)
Definition at line 156 of file event.cpp.
{
     return Event(event_class::MOUSE_BUTTON, button, sdl_mod(mod));
 }
References openage::util::mod(), MOUSE_BUTTON, and sdl_mod().
Referenced by openage::input::InputManager::on_input().
sdl_mouse_up_down()
Event openage::input::sdl_mouse_up_down (int button, bool up, SDL_Keymod mod)
Definition at line 160 of file event.cpp.
{
     return Event(up ? event_class::MOUSE_BUTTON_UP : event_class::MOUSE_BUTTON_DOWN, button, sdl_mod(mod));
 }
References openage::util::mod(), MOUSE_BUTTON_DOWN, MOUSE_BUTTON_UP, and sdl_mod().
Referenced by openage::input::InputManager::on_input().
sdl_wheel()
Event openage::input::sdl_wheel (int direction, SDL_Keymod mod)
Definition at line 164 of file event.cpp.
{
     return Event(event_class::MOUSE_WHEEL, direction, sdl_mod(mod));
 }
References openage::direction, openage::util::mod(), MOUSE_WHEEL, and sdl_mod().
Referenced by openage::input::InputManager::on_input().
text_to_event()
Event openage::input::text_to_event (const std::string & event_str)
Convert a string to an event, throw if the string is not a valid event.
First element is the entire match, so search from the second.
Definition at line 76 of file text_to_event.cpp.
{
     check_modifiers_once();
     ENSURE(event_str.find('\n'), "Input event string representation must be one line, got '" << event_str << "'.");
     int mod = 0;
     std::smatch event_elements;
     if (std::regex_match(event_str, event_elements, event_pattern)) {
         auto groups_it = std::begin(event_elements) + 1;
         auto first_non_empty = std::find_if(groups_it, std::end(event_elements), [] (const std::ssub_match &element) {
             return element.length();
         });
         ENSURE(first_non_empty != std::end(event_elements), "Nothing captured from string representation of event '"<< event_str <<"': regex pattern is broken.");
         auto index_first_non_empty = std::distance(groups_it, first_non_empty);
         if (index_first_non_empty < std::distance(std::begin(modifiers), std::end(modifiers)))
             mod = modifiers[index_first_non_empty];
         auto event_type = groups_it[modifiers.size()].str();
         ENSURE(!event_type.empty(), "Empty group where key was expected in string representation of event '"<< event_str <<"': regex pattern is broken.");
         auto param = groups_it[modifiers.size() + 1].str();
         return to_event(event_type, param, mod);
     } else {
         throw Error(MSG(err) << "could not parse keybinding '" << event_str << "'!");
     }
 }
References ENSURE, openage::log::err(), openage::util::mod(), and MSG.
Referenced by openage::input::tests::parse_event_string(), and openage::input::InputManager::set_bind().
utf8()
Event openage::input::utf8 (const std::string & text)
Definition at line 152 of file event.cpp.
{
     return Event(event_class::UTF8, text, modset_t());
 }
References UTF8.
Referenced by openage::input::InputManager::on_input(), and openage::console::Console::register_to_engine().
Variable Documentation
event_base
std::unordered_map<event_class, event_class, event_class_hash> openage::input::event_base static
Initial value:
{
    {event_class::KEYBOARD, event_class::ANY},
    {event_class::CHAR, event_class::KEYBOARD},
    {event_class::ALPHA, event_class::CHAR},
    {event_class::DIGIT, event_class::CHAR},
    {event_class::PRINT, event_class::CHAR},
    {event_class::NONPRINT, event_class::KEYBOARD},
    {event_class::OTHER, event_class::KEYBOARD},
    {event_class::UTF8, event_class::KEYBOARD},
    {event_class::MOUSE, event_class::ANY},
    {event_class::MOUSE_BUTTON, event_class::MOUSE},
    {event_class::MOUSE_WHEEL, event_class::MOUSE},
    {event_class::MOUSE_MOTION, event_class::MOUSE},
}
each event type mapped to parent type
Definition at line 45 of file event.h.
Referenced by openage::input::ClassCode::get_classes().