openage: openage::coord::camgame Struct Reference
openage::coord::camgame Struct Reference
#include <pixel.h>
Public Member Functions
viewport to_viewport (const CoordManager &mgr) const
See the comments for camgame_delta::to_phys3.
camhud to_camhud (const CoordManager &mgr) const
phys3 to_phys3 (const CoordManager &mgr, phys_t up=phys_t::zero()) const
tile to_tile (const CoordManager &mgr, phys_t up=phys_t::zero()) const
Detailed Description
Definition at line 32 of file pixel.h.
Member Function Documentation
to_camhud()
camhud openage::coord::camgame::to_camhud (const CoordManager & mgr) const
Definition at line 56 of file pixel.cpp.
{
     return this->to_viewport(mgr).to_camhud(mgr);
 }
References openage::coord::viewport::to_camhud(), and to_viewport().
to_phys3()
phys3 openage::coord::camgame::to_phys3 (const CoordManager & mgr, phys_t up = phys_t::zero()) const
Definition at line 40 of file pixel.cpp.
{
     return (*this - camgame{0, 0}).to_phys3(mgr, up) + mgr.camgame_phys;
 }
References openage::coord::CoordManager::camgame_phys.
Referenced by openage::UnitSelection::select_point(), openage::coord::viewport::to_phys3(), openage::coord::input::to_phys3(), and to_tile().
to_tile()
tile openage::coord::camgame::to_tile (const CoordManager & mgr, phys_t up = phys_t::zero()) const
Definition at line 82 of file pixel.cpp.
{
     return this->to_phys3(mgr, up).to_tile();
 }
References to_phys3(), and openage::coord::phys3::to_tile().
Referenced by openage::coord::viewport::to_tile().
to_viewport()
viewport openage::coord::camgame::to_viewport (const CoordManager & mgr) const
See the comments for camgame_delta::to_phys3.
Todo:
Once we have terrain elevation, 'up' will not mean the absolute elevation, but instead the returned phys3 coordinate will be the intersection between the camgame line and the 3d terrain + up altitude.
Definition at line 45 of file pixel.cpp.
{
     // reverse of viewport::to_camgame
     return (*this - camgame{0, 0}).to_viewport() + mgr.camgame_viewport;
 }
References openage::coord::CoordManager::camgame_viewport.
Referenced by openage::Texture::draw(), openage::UnitSelection::on_drawhud(), to_camhud(), openage::coord::tile::to_viewport(), and openage::coord::phys3::to_viewport().
The documentation for this struct was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/coord/pixel.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/coord/pixel.cpp