openage: openage::coord::viewport_delta Struct Reference
openage::coord::viewport_delta Struct Reference
#include <pixel.h>
Public Member Functions
constexpr camgame_delta to_camgame () const
phys3_delta to_phys3 (const CoordManager &mgr, phys_t up) const
camhud_delta to_camhud () const
Detailed Description
Definition at line 63 of file pixel.h.
Member Function Documentation
to_camgame()
constexpr camgame_delta openage::coord::viewport_delta::to_camgame () const inline
Definition at line 66 of file pixel.h.
{
         return camgame_delta{this->x, this->y};
     }
Referenced by openage::coord::input_delta::to_camgame(), to_phys3(), and openage::coord::input_delta::to_phys3().
to_camhud()
camhud_delta openage::coord::viewport_delta::to_camhud () const inline
Definition at line 71 of file pixel.h.
{
         return camhud_delta{this->x, this->y};
     }
to_phys3()
phys3_delta openage::coord::viewport_delta::to_phys3 (const CoordManager & mgr, phys_t up) const
Definition at line 66 of file pixel.cpp.
{
     return this->to_camgame().to_phys3(mgr, up);
 }
References to_camgame(), and openage::coord::camgame_delta::to_phys3().
The documentation for this struct was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/coord/pixel.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/coord/pixel.cpp