openage: openage::coord::phys2 Struct Reference
openage::coord::phys2 Struct Reference
#include <phys.h>
Public Member Functions
tile to_tile () const
phys3 to_phys3 (const Terrain &terrain, phys_t altitude=0) const
double distance (phys2 other) const
Detailed Description
Definition at line 32 of file phys.h.
Member Function Documentation
distance()
double openage::coord::phys2::distance (phys2 other) const
Definition at line 46 of file phys.cpp.
{
     return (*this - other).length();
 }
Referenced by openage::RadialObject::contains(), openage::RadialObject::from_edge(), and openage::RadialObject::intersects().
to_phys3()
phys3 openage::coord::phys2::to_phys3 (const Terrain & terrain, phys_t altitude = 0) const
Definition at line 51 of file phys.cpp.
{
     // TODO: once terrain elevations have been implemented,
     //       query the terrain elevation at {ne, se}.
     phys_t elevation = 0;
     return phys3{this->ne, this->se, elevation + altitude};
 }
Referenced by openage::building_center().
to_tile()
tile openage::coord::phys2::to_tile () const
Definition at line 21 of file phys.cpp.
{
     return tile{this->ne.to_int(), this->se.to_int()};
 }
The documentation for this struct was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/coord/phys.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/coord/phys.cpp