openage: openage::coord::viewport Struct Reference
openage::coord::viewport Struct Reference
#include <pixel.h>
Public Member Functions
camgame to_camgame (const CoordManager &mgr) const
phys3 to_phys3 (const CoordManager &mgr, phys_t up=phys_t::zero()) const
tile to_tile (const CoordManager &mgr, phys_t up=phys_t::zero()) const
camhud to_camhud (const CoordManager &mgr) const
Detailed Description
Definition at line 77 of file pixel.h.
Member Function Documentation
to_camgame()
camgame openage::coord::viewport::to_camgame (const CoordManager & mgr) const
Definition at line 71 of file pixel.cpp.
{
     // mgr.camgame_viewport describes the coordinates of camgame{0, 0} in the viewport system.
     return camgame{0, 0} + (*this - mgr.camgame_viewport).to_camgame();
 }
References openage::coord::CoordManager::camgame_viewport.
Referenced by openage::coord::input::to_camgame(), to_phys3(), openage::coord::input::to_phys3(), and to_tile().
to_camhud()
camhud openage::coord::viewport::to_camhud (const CoordManager & mgr) const
Definition at line 87 of file pixel.cpp.
{
     return camhud{0, 0} + (*this - mgr.camhud_viewport).to_camhud();
 }
References openage::coord::CoordManager::camhud_viewport.
Referenced by openage::coord::camgame::to_camhud(), and openage::coord::phys3::to_camhud().
to_phys3()
phys3 openage::coord::viewport::to_phys3 (const CoordManager & mgr, phys_t up = phys_t::zero()) const
Definition at line 51 of file pixel.cpp.
{
     return this->to_camgame(mgr).to_phys3(mgr, up);
 }
References to_camgame(), and openage::coord::camgame::to_phys3().
Referenced by openage::EditorMode::paint_entity_at().
to_tile()
tile openage::coord::viewport::to_tile (const CoordManager & mgr, phys_t up = phys_t::zero()) const
Definition at line 77 of file pixel.cpp.
{
     return this->to_camgame(mgr).to_tile(mgr, up);
 }
References to_camgame(), and openage::coord::camgame::to_tile().
Referenced by openage::Terrain::draw(), and openage::EditorMode::paint_terrain_at().
The documentation for this struct was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/coord/pixel.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/coord/pixel.cpp