openage: openage::coord::phys3 Struct Reference
openage::coord::phys3 Struct Reference
#include <phys.h>
Public Member Functions
tile3 to_tile3 () const
tile to_tile () const
phys2 to_phys2 () const
camgame to_camgame (const CoordManager &mgr) const
viewport to_viewport (const CoordManager &mgr) const
camhud to_camhud (const CoordManager &mgr) const
Detailed Description
Definition at line 56 of file phys.h.
Member Function Documentation
to_camgame()
camgame openage::coord::phys3::to_camgame (const CoordManager & mgr) const
Definition at line 91 of file phys.cpp.
{
     return (*this - mgr.camgame_phys).to_camgame(mgr) + camgame{0, 0};
 }
References openage::coord::CoordManager::camgame_phys.
Referenced by openage::Unit::draw(), openage::coord::tile::to_camgame(), and to_viewport().
to_camhud()
camhud openage::coord::phys3::to_camhud (const CoordManager & mgr) const
Definition at line 101 of file phys.cpp.
{
     return this->to_viewport(mgr).to_camhud(mgr);
 }
References openage::coord::viewport::to_camhud(), and to_viewport().
Referenced by openage::ActionMode::render().
to_phys2()
phys2 openage::coord::phys3::to_phys2 () const
Definition at line 26 of file phys.cpp.
{
     return phys2{this->ne, this->se};
 }
Referenced by openage::RadialObject::contains(), openage::RadialObject::from_edge(), and openage::RadialObject::intersects().
to_tile()
tile openage::coord::phys3::to_tile () const
Definition at line 106 of file phys.cpp.
{
     return this->to_tile3().to_tile();
 }
References openage::coord::tile3::to_tile(), and to_tile3().
Referenced by openage::building_center(), openage::Terrain::obj_at_point(), openage::ActionMode::on_game_control_set(), openage::EditorMode::paint_entity_at(), and openage::coord::camgame::to_tile().
to_tile3()
tile3 openage::coord::phys3::to_tile3 () const
Definition at line 16 of file phys.cpp.
{
     return tile3{this->ne.to_int(), this->se.to_int(), this->up.to_int()};
 }
Referenced by openage::SquareObject::contains(), openage::find_in_radius(), openage::find_near(), openage::RadialObject::get_range(), to_tile(), and openage::ProjectileAction::update().
to_viewport()
viewport openage::coord::phys3::to_viewport (const CoordManager & mgr) const
Definition at line 96 of file phys.cpp.
{
     return this->to_camgame(mgr).to_viewport(mgr);
 }
References to_camgame(), and openage::coord::camgame::to_viewport().
Referenced by openage::Texture::draw(), openage::UnitSelection::on_drawhud(), and to_camhud().
The documentation for this struct was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/coord/phys.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/coord/phys.cpp