openage: openage::coord::phys3_delta Struct Reference
openage::coord::phys3_delta Struct Reference
#include <phys.h>
Public Member Functions
double length () const
phys3_delta normalize (double length=1) const
camgame_delta to_camgame (const CoordManager &mgr) const
phys2_delta to_phys2 () const
Detailed Description
Definition at line 41 of file phys.h.
Member Function Documentation
length()
double openage::coord::phys3_delta::length () const
Definition at line 81 of file phys.cpp.
{
     return math::hypot3(this->ne.to_double(), this->se.to_double(), this->up.to_double());
 }
References openage::math::hypot3().
Referenced by normalize().
normalize()
phys3_delta openage::coord::phys3_delta::normalize (double length = 1) const
Definition at line 86 of file phys.cpp.
{
     return *this * (length / this->length());
 }
References length().
to_camgame()
camgame_delta openage::coord::phys3_delta::to_camgame (const CoordManager & mgr) const
Definition at line 60 of file phys.cpp.
{
     // apply transformation matrix to phys3_delta, to get 'scaled':
     //                   (ne)
     //  (x) = (+1 +1 +0) (se)
     //  (y) = (+1 -1 +1) (up)
     phys_t x = phys_t{this->ne} * (+1) + this->se * (+1) + this->up * (+0);
     phys_t y = phys_t{this->ne} * (+1) + this->se * (-1) + this->up * (+1);
     // add scaling (w/2 for x, h/2 for y)
     return camgame_delta{
         static_cast<camgame_delta::elem_t>((x * (mgr.tile_size.x / 2)).to_int()),
         static_cast<camgame_delta::elem_t>((y * (mgr.tile_size.y / 2)).to_int())
     };
 }
References openage::coord::CoordManager::tile_size.
to_phys2()
phys2_delta openage::coord::phys3_delta::to_phys2 () const
Definition at line 76 of file phys.cpp.
{
     return phys2_delta{this->ne, this->se};
 }
The documentation for this struct was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/coord/phys.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/coord/phys.cpp