openage: openage::coord::input_delta Struct Reference
openage::coord::input_delta Struct Reference
#include <pixel.h>
Public Member Functions
viewport_delta to_viewport (const CoordManager &mgr) const
camgame_delta to_camgame (const CoordManager &mgr) const
phys3_delta to_phys3 (const CoordManager &mgr, phys_t up=phys_t::zero()) const
Detailed Description
Definition at line 87 of file pixel.h.
Member Function Documentation
to_camgame()
camgame_delta openage::coord::input_delta::to_camgame (const CoordManager & mgr) const
Definition at line 113 of file pixel.cpp.
{
     return this->to_viewport(mgr).to_camgame();
 }
References openage::coord::viewport_delta::to_camgame(), and to_viewport().
to_phys3()
phys3_delta openage::coord::input_delta::to_phys3 (const CoordManager & mgr, phys_t up = phys_t::zero()) const
Definition at line 118 of file pixel.cpp.
{
     return this->to_viewport(mgr).to_camgame().to_phys3(mgr, up);
 }
References openage::coord::viewport_delta::to_camgame(), openage::coord::camgame_delta::to_phys3(), and to_viewport().
to_viewport()
viewport_delta openage::coord::input_delta::to_viewport (const CoordManager & mgr) const
Definition at line 103 of file pixel.cpp.
{
     viewport_delta result;
     result.x = this->x;
     result.y = mgr.viewport_size.y - this->y;
     return result;
 }
References openage.testing.testing::result(), and openage::coord::CoordManager::viewport_size.
Referenced by to_camgame(), and to_phys3().
The documentation for this struct was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/coord/pixel.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/coord/pixel.cpp