openage: openage::coord::camgame_delta Struct Reference
openage::coord::camgame_delta Struct Reference
#include <pixel.h>
Public Member Functions
phys3_delta to_phys3 (const CoordManager &mgr, phys_t up=phys_t::zero()) const
viewport_delta to_viewport () const
Detailed Description
Definition at line 18 of file pixel.h.
Member Function Documentation
to_phys3()
phys3_delta openage::coord::camgame_delta::to_phys3 (const CoordManager & mgr, phys_t up = phys_t::zero()) const
There are infinite solutions to this conversion problem because a 2D coordinate is converted into a 3D coordinate.
The user needs to manually give the 'up' value of the phys3 result.
Definition at line 12 of file pixel.cpp.
{
     // apply scaling factor; w/2 for x, h/2 for y
     phys_t x = phys_t::from_int(this->x) / static_cast<int64_t>(mgr.tile_size.x / 2);
     phys_t y = phys_t::from_int(this->y) / static_cast<int64_t>(mgr.tile_size.y / 2);
     // apply transformation matrix to 'scaled',
     // to get the relative phys3 position
     //
     // a camgame position represents a line in the 3D phys space
     // a camgame delta of 0 might actually correlate to an arbitrarily
     // large phys delta.
     // we select one specific point on that line by explicitly specifying the
     // 'up' value of the result.
     //
     // the transformation matrix is:
     //
     //  (ne) = (+0.5 +0.5 +0.5) ( x)
     //  (se) = (+0.5 -0.5 -0.5) ( y)
     //  (up) = (+0.0 +0.0 +1.0) (up)
     phys3_delta result;
     result.ne = (x + y + up)/2L;
     result.se = (x - y - up)/2L;
     result.up = (        up);
     return result;
 }
References openage::util::FixedPoint< int64_t, phys_t_radix_pos >::from_int(), openage.testing.testing::result(), and openage::coord::CoordManager::tile_size.
Referenced by openage::coord::viewport_delta::to_phys3(), and openage::coord::input_delta::to_phys3().
to_viewport()
viewport_delta openage::coord::camgame_delta::to_viewport () const
Definition at line 61 of file pixel.cpp.
{
         return viewport_delta{this->x, this->y};
 }
The documentation for this struct was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/coord/pixel.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/coord/pixel.cpp