openage: openage::coord::tile Struct Reference
openage::coord::tile Struct Reference
#include <tile.h>
Public Member Functions
tile3 to_tile3 (const Terrain &terrain, tile_t altitude=0) const
adds an UP component to the coordinate.
phys2 to_phys2 () const
phys3 to_phys3 (const Terrain &terrain, tile_t altitude=0) const
camgame to_camgame (const CoordManager &mgr, const Terrain &terrain, tile_t altitude=0) const
viewport to_viewport (const CoordManager &mgr, const Terrain &terrain, tile_t altitude=0) const
chunk to_chunk () const
tile_delta get_pos_on_chunk () const
Detailed Description
Definition at line 29 of file tile.h.
Member Function Documentation
get_pos_on_chunk()
tile_delta openage::coord::tile::get_pos_on_chunk () const
Definition at line 70 of file tile.cpp.
{
     return tile_delta{
         util::mod(this->ne, tiles_per_chunk),
         util::mod(this->se, tiles_per_chunk)
     };
 }
References openage::util::mod(), and openage::coord::tiles_per_chunk.
Referenced by openage::TerrainChunk::get_data(), openage::Terrain::get_data(), and openage::TerrainObject::set_ground().
to_camgame()
camgame openage::coord::tile::to_camgame (const CoordManager & mgr, const Terrain & terrain, tile_t altitude = 0) const
Definition at line 47 of file tile.cpp.
{
     return this->to_phys3(terrain, altitude).to_camgame(mgr);
 }
References openage::coord::phys3::to_camgame(), and to_phys3().
Referenced by to_viewport().
to_chunk()
chunk openage::coord::tile::to_chunk () const
Definition at line 62 of file tile.cpp.
{
     return chunk{
         static_cast<chunk::elem_t>(util::div(this->ne, tiles_per_chunk)),
         static_cast<chunk::elem_t>(util::div(this->se, tiles_per_chunk))
     };
 }
References openage::util::div(), and openage::coord::tiles_per_chunk.
Referenced by openage::Terrain::get_chunk(), openage::Terrain::get_create_chunk(), and openage::Terrain::get_data().
to_phys2()
phys2 openage::coord::tile::to_phys2 () const
Definition at line 23 of file tile.cpp.
{
     return phys2{phys3::elem_t::from_int(this->ne), phys3::elem_t::from_int(this->se)};
 }
Referenced by openage::SquareObject::from_edge(), openage::SquareObject::intersects(), openage::SquareObject::on_edge(), and openage::coord::tile3::to_phys2().
to_phys3()
phys3 openage::coord::tile::to_phys3 (const Terrain & terrain, tile_t altitude = 0) const
Definition at line 28 of file tile.cpp.
{
     return this->to_tile3(terrain, altitude).to_phys3();
 }
References openage::coord::tile3::to_phys3(), and to_tile3().
Referenced by openage::Generator::add_units(), openage::gameio::load_unit(), and to_camgame().
to_tile3()
tile3 openage::coord::tile::to_tile3 (const Terrain & terrain, tile_t altitude = 0) const
adds an UP component to the coordinate.
the resulting UP component will be 'altitude' tiles above ground elevation.
Todo:
once terrain elevations have been implemented, query the terrain elevation at {ne, se}.
Definition at line 12 of file tile.cpp.
{
     tile_t elevation = 0;
     return tile3{this->ne, this->se, elevation + altitude};
 }
Referenced by to_phys3().
to_viewport()
viewport openage::coord::tile::to_viewport (const CoordManager & mgr, const Terrain & terrain, tile_t altitude = 0) const
Definition at line 55 of file tile.cpp.
{
     return this->to_camgame(mgr, terrain, altitude).to_viewport(mgr);
 }
References to_camgame(), and openage::coord::camgame::to_viewport().
Referenced by openage::Texture::draw().
The documentation for this struct was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/coord/tile.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/coord/tile.cpp