openage: openage::renderer::resources::Texture2dSubInfo Struct Reference
openage::renderer::resources::Texture2dSubInfo Struct Reference
#include <texture_subinfo.h>
Public Member Functions
Texture2dSubInfo (const std::string &line)
Initializes the info from a CSV line containing its members.
Texture2dSubInfo (uint32_t x, uint32_t y, uint32_t w, uint32_t h, uint32_t cx, uint32_t cy)
Initializes the info from data.
Texture2dSubInfo ()=default
int fill (const std::string &line)
Needed for compatibility reasons, don't use this directly.
Public Attributes
uint32_t x {}
The subtexture position within the atlas.
uint32_t y {}
uint32_t w {}
The subtexture size.
uint32_t h {}
uint32_t cx {}
Position of the subtexture's center within the atlas.
uint32_t cy {}
Detailed Description
Describes a position of a (sub)texture within a larger texture. Used for texture atlases and animations where all frames are within one texture file.
Definition at line 18 of file texture_subinfo.h.
Constructor & Destructor Documentation
Texture2dSubInfo() [1/3]
openage::renderer::resources::Texture2dSubInfo::Texture2dSubInfo (const std::string & line)
Initializes the info from a CSV line containing its members.
Definition at line 10 of file texture_subinfo.cpp.
{
     constexpr size_t member_count = 6;
     std::vector<std::string> buf = openage::util::split_escape(
         line, ',', member_count
     );
     if (buf.size() != member_count) {
         throw Error(
             MSG(err) << "Tokenizing subtexture led to "
             << buf.size() << " columns (expected "
             << member_count << ")!"
         );
     }
     size_t elems_read = 0;
     elems_read += sscanf(buf[0].c_str(), "%u", &this->x);
     elems_read += sscanf(buf[1].c_str(), "%u", &this->y);
     elems_read += sscanf(buf[2].c_str(), "%u", &this->w);
     elems_read += sscanf(buf[3].c_str(), "%u", &this->h);
     elems_read += sscanf(buf[4].c_str(), "%u", &this->cx);
     elems_read += sscanf(buf[5].c_str(), "%u", &this->cy);
     if (elems_read != member_count) {
         throw Error(MSG(err) << "Failed to read subtexture members from CSV line.");
     }
 }
References cx, cy, openage::log::err(), h, openage::line, MSG, openage::util::split_escape(), w, x, and y.
Texture2dSubInfo() [2/3]
openage::renderer::resources::Texture2dSubInfo::Texture2dSubInfo (uint32_t x, uint32_t y, uint32_t w, uint32_t h, uint32_t cx, uint32_t cy)
Initializes the info from data.
Definition at line 38 of file texture_subinfo.cpp.
     : x(x)
     , y(y)
     , w(w)
     , h(h)
     , cx(cx)
     , cy(cy) {}
Texture2dSubInfo() [3/3]
openage::renderer::resources::Texture2dSubInfo::Texture2dSubInfo () default
Referenced by fill().
Member Function Documentation
fill()
int openage::renderer::resources::Texture2dSubInfo::fill (const std::string & line)
Needed for compatibility reasons, don't use this directly.
Definition at line 46 of file texture_subinfo.cpp.
{
     *this = Texture2dSubInfo(line);
     return -1;
 }
References openage::line, and Texture2dSubInfo().
Referenced by openage.convert.colortable.ColorTable::__init__().
Member Data Documentation
cx
uint32_t openage::renderer::resources::Texture2dSubInfo::cx {}
Position of the subtexture's center within the atlas.
Definition at line 26 of file texture_subinfo.h.
Referenced by Texture2dSubInfo().
cy
uint32_t openage::renderer::resources::Texture2dSubInfo::cy {}
Definition at line 26 of file texture_subinfo.h.
Referenced by Texture2dSubInfo().
h
uint32_t openage::renderer::resources::Texture2dSubInfo::h {}
Definition at line 23 of file texture_subinfo.h.
Referenced by Texture2dSubInfo().
w
uint32_t openage::renderer::resources::Texture2dSubInfo::w {}
The subtexture size.
Definition at line 23 of file texture_subinfo.h.
Referenced by Texture2dSubInfo().
x
uint32_t openage::renderer::resources::Texture2dSubInfo::x {}
The subtexture position within the atlas.
Definition at line 20 of file texture_subinfo.h.
Referenced by Texture2dSubInfo().
y
uint32_t openage::renderer::resources::Texture2dSubInfo::y {}
Definition at line 20 of file texture_subinfo.h.
Referenced by Texture2dSubInfo().
The documentation for this struct was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/resources/texture_subinfo.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/resources/texture_subinfo.cpp