openage: openage::coord::tile3 Struct Reference
openage::coord::tile3 Struct Reference
#include <tile.h>
Public Member Functions
constexpr tile to_tile () const
phys2 to_phys2 () const
phys3 to_phys3 () const
Detailed Description
Definition at line 55 of file tile.h.
Member Function Documentation
to_phys2()
phys2 openage::coord::tile3::to_phys2 () const
Definition at line 33 of file tile.cpp.
{
     return this->to_tile().to_phys2();
 }
References openage::coord::tile::to_phys2(), and to_tile().
to_phys3()
phys3 openage::coord::tile3::to_phys3 () const
Definition at line 38 of file tile.cpp.
{
     return phys3{
         phys3::elem_t::from_int(this->ne),
         phys3::elem_t::from_int(this->se),
         phys3::elem_t::from_int(this->up)
     };
 }
Referenced by openage::coord::tile::to_phys3().
to_tile()
constexpr tile openage::coord::tile3::to_tile () const inline
Definition at line 59 of file tile.h.
{
         return tile{this->ne, this->se};
     }
Referenced by openage::SquareObject::contains(), openage::find_in_radius(), openage::find_near(), openage::RadialObject::get_range(), to_phys2(), openage::coord::phys3::to_tile(), and openage::ProjectileAction::update().
The documentation for this struct was generated from the following files:
C:/Users/Jameson/Documents/git-projects/openage/libopenage/coord/tile.h
C:/Users/Jameson/Documents/git-projects/openage/libopenage/coord/tile.cpp