openage: C:/Users/Jameson/Documents/git-projects/openage/libopenage/renderer/vulkan/util.h File Reference
util.h File Reference
#include <vulkan/vulkan.h>
#include "../../error/error.h"
Macros
#define VK_CALL_CHECKED(fun, ...)
Functions
template<typename R , typename R2 >
std::vector< R > vk_do_ritual (R2(*func)(uint32_t *, R *))
template<typename T , typename T2 , typename R , typename R2 >
std::vector< R > vk_do_ritual (R2(*func)(T, uint32_t *, R *), T2 &&a)
template<typename T , typename T2 , typename U , typename U2 , typename R , typename R2 >
std::vector< R > vk_do_ritual (R2(*func)(T, U, uint32_t *, R *), T2 &&a, U2 &&b)
template<typename T , typename T2 , typename U , typename U2 , typename V , typename V2 , typename R , typename R2 >
std::vector< R > vk_do_ritual (R2(*func)(T, U, V, uint32_t *, R *), T2 &&a, U2 &&b, V2 &&c)
Macro Definition Documentation
VK_CALL_CHECKED
#define VK_CALL_CHECKED (fun, ...)
Value:
{ \
        VkResult res = fun(__VA_ARGS__); \
        if (res != VK_SUCCESS) { \
            throw Error(MSG(err) << "Call to Vulkan function " << #fun << " failed with " << res << "."); \
        } \
    }
Definition at line 50 of file util.h.
Function Documentation
vk_do_ritual() [1/4]
template<typename R , typename R2 > std::vector<R> vk_do_ritual (R2(*)(uint32_t *, R *) func)
Definition at line 11 of file util.h.
{
     uint32_t count = 0;
     func(&count, nullptr);
     std::vector<R> ret(count);
     func(&count, ret.data());
     return ret;
 }
Referenced by openage::renderer::vulkan::VlkRenderer::do_the_thing(), openage::renderer::vulkan::find_capabilities(), openage::renderer::vulkan::VlkGraphicsDevice::find_device_surface_support(), openage::renderer::vulkan::VlkDrawableDisplay::VlkDrawableDisplay(), openage::renderer::vulkan::VlkGraphicsDevice::VlkGraphicsDevice(), and openage::renderer::vulkan::VlkWindow::VlkWindow().
vk_do_ritual() [2/4]
template<typename T , typename T2 , typename R , typename R2 > std::vector<R> vk_do_ritual (R2(*)(T, uint32_t *, R *) func, T2 && a)
Definition at line 21 of file util.h.
{
     uint32_t count = 0;
     func(std::forward<T2>(a), &count, nullptr);
     std::vector<R> ret(count);
     func(std::forward<T2>(a), &count, ret.data());
     return ret;
 }
vk_do_ritual() [3/4]
template<typename T , typename T2 , typename U , typename U2 , typename R , typename R2 > std::vector<R> vk_do_ritual (R2(*)(T, U, uint32_t *, R *) func, T2 && a, U2 && b)
Definition at line 31 of file util.h.
{
     uint32_t count = 0;
     func(std::forward<T2>(a), std::forward<U2>(b), &count, nullptr);
     std::vector<R> ret(count);
     func(std::forward<T2>(a), std::forward<U2>(b), &count, ret.data());
     return ret;
 }
vk_do_ritual() [4/4]
template<typename T , typename T2 , typename U , typename U2 , typename V , typename V2 , typename R , typename R2 > std::vector<R> vk_do_ritual (R2(*)(T, U, V, uint32_t *, R *) func, T2 && a, U2 && b, V2 && c)
Definition at line 41 of file util.h.
{
     uint32_t count = 0;
     func(std::forward<T2>(a), std::forward<U2>(b), std::forward<V2>(c), &count, nullptr);
     std::vector<R> ret(count);
     func(std::forward<T2>(a), std::forward<U2>(b), std::forward<V2>(c), &count, ret.data());
     return ret;
 }