#!/bin/bash

cp openage dist-win32/openage.exe

for d in \
        "SDL2.dll" \
        "SDL2_image.dll" \
        "libfontconfig-1.dll" \
        "libftgl-2.dll" \
        "libgcc_s_sjlj-1.dll" \
        "glew32.dll" \
        "libopusfile-0.dll" \
        "libwinpthread-1.dll" \
        "libpython3.4m.dll" \
        "libstdc++-6.dll" \
        "libfreetype-6.dll" \
        "libfontconfig-1.dll" \
        "libfreetype-6.dll" \
        "libftgl-2.dll" \
        "libogg-0.dll" \
        "libopus-0.dll" \
        "libopusfile-0.dll" \
        "libexpat-1.dll" \
        "libbz2-1.dll" \
        "libfreetype-6.dll" \
        "libfontconfig-1.dll" \
        "libbz2-1.dll" \
        "libfreetype-6.dll" \
        "libftgl-2.dll" \
        "libpng16-16.dll" \
        "zlib1.dll" \
; do
    cp "/usr/i686-w64-mingw32/bin/$d" "dist-win32/$d"
done

echo "done. run it!"
