function(print_filename filename)
	file(RELATIVE_PATH relfilename ${CMAKE_SOURCE_DIR} ${filename})
	message("${ARGN}\t${relfilename}")
endfunction()

function(list_contains var value)
	set(${var} FALSE)
	foreach(value2 ${ARGN})
		if(${value} STREQUAL ${value2})
			set(${var} TRUE PARENT_SCOPE)
		endif()
	endforeach()
endfunction()
