// Copyright 2015-2015 the openage authors. See copying.md for legal info.

#ifndef OPENAGE_KEYBINDS_ACTION_H_
#define OPENAGE_KEYBINDS_ACTION_H_

namespace openage {
namespace keybinds {

enum class action_t {
	STOP_GAME,
	TOGGLE_HUD,
	SCREENSHOT,
	TOGGLE_DEBUG_OVERLAY,
	TOGGLE_DEBUG_GRID,
	QUICK_SAVE,
	QUICK_LOAD,
	TOGGLE_BLENDING,
	TOGGLE_PROFILER,
	TOGGLE_CONSTRUCT_MODE,
	TOGGLE_UNIT_DEBUG,
	TRAIN_OBJECT,
	ENABLE_BUILDING_PLACEMENT,
	DISABLE_SET_ABILITY,
	SET_ABILITY_MOVE,
	SET_ABILITY_GATHER,
	TOGGLE_CONSOLE,
	SPAWN_VILLAGER,
	KILL_UNIT,
	BUILDING_1,
	BUILDING_2,
	BUILDING_3,
	BUILDING_4,
	SWITCH_TO_PLAYER_1,
	SWITCH_TO_PLAYER_2,
	SWITCH_TO_PLAYER_3,
	SWITCH_TO_PLAYER_4,
	SWITCH_TO_PLAYER_5,
	SWITCH_TO_PLAYER_6,
	SWITCH_TO_PLAYER_7,
	SWITCH_TO_PLAYER_8
};

struct action_hash {
	int operator()(const action_t& a) const;
};

} //namespace keybinds
} //namespace openage

#endif
