# Copyright 2020-2020 the openage authors. See copying.md for legal info.

"""
nyan object names and filenames for SWGB.
"""

# key: head unit id; value: (nyan object name, filename prefix)
# For unit lines with different graphics per civ only the unit line of
# the first civ (Empire) is stored
UNIT_LINE_LOOKUPS = {
    2: ("FambaShieldGenerator", "famba_shield_generator"),
    4: ("RoyalCrusader", "royal_crusader"),
    6: ("Airspeeder", "airspeeder"),
    8: ("Berserker", "berserker"),
    13: ("UtilityTrawler", "utility_trawler"),
    89: ("SithMaster", "sith_master"),
    118: ("Worker", "worker"),
    125: ("JediMaster", "jedi_master"),
    174: ("DestroyerDroid", "destroyer_droid"),
    180: ("SithKnight", "sith_knight"),
    183: ("JediKnight", "jedi_knight"),
    307: ("Trooper", "trooper"),
    359: ("MountedTrooper", "mounted_trooper"),
    381: ("GrenadeTrooper", "grenade_trooper"),
    438: ("AntiAirTrooper", "anti_air_trooper"),
    469: ("StrikeMech", "strike_mech"),
    481: ("Ackley", "ackeley"),
    485: ("MechDestroyer", "mech_destroyer"),
    500: ("AssaultMech", "assault_mech"),
    550: ("Scout", "scout"),
    625: ("AirCruiser", "air_cruiser"),
    641: ("JediStarfighter", "jedi_starfighter"),
    642: ("GeonosianWarrior", "utility_trawler"),
    691: ("Artillery", "artillery"),
    713: ("Pummel", "pummel"),
    762: ("Bomber", "bomber"),
    773: ("Fighter", "fighter"),
    792: ("AntiAirMobile", "anti_air_mobile"),
    815: ("Cruiser", "cruiser"),
    838: ("TransportShip", "transport_ship"),
    860: ("Nexu", "nexu"),
    868: ("Frigate", "frigate"),
    898: ("Destroyer", "destroyer"),
    918: ("AntiAirDestroyer", "anti_air_destroyer"),
    921: ("Reek", "reek"),
    931: ("CargoHovercraft", "cargo_hovercraft"),
    939: ("Medic", "medic"),
    961: ("BountyHunter", "bounty_hunter"),
    983: ("Cannon", "cannon"),
    993: ("DarkTrooper", "dark_trooper"),
    1009: ("PowerDroid", "power_droid"),
    1034: ("Probot", "probot"),
    1036: ("AirTransport", "air_transport"),
    1582: ("AWing", "a_wing"),
}

# key: head unit id; value: (nyan object name, filename prefix)
BUILDING_LINE_LOOKUPS = {
    12: ("PowerCore", "power_core"),
    45: ("Shipyard", "shipyard"),
    49: ("HeavyWeaponsFactory", "heavy_weapons_factory"),
    50: ("Farm", "farm"),
    68: ("FoodProcCenter", "food_proc_center"),
    70: ("PrefabShelter", "prefab_shelter"),
    72: ("LightWall", "light_wall"),
    79: ("LaserTurret", "laser_turret"),
    82: ("Fortress", "fortress"),
    84: ("Spaceport", "spaceport"),
    87: ("TroopCenter", "troop_center"),
    101: ("MechFactory", "mech_factory"),
    103: ("WarCenter", "war_center"),
    104: ("Temple", "temple"),
    109: ("CommandCenter", "command_center"),
    117: ("Wall", "wall"),
    199: ("FishingTrap", "fishing_trap"),
    209: ("ResearchCenter", "research_center"),
    236: ("AntiAirTurret", "anti_air_turret"),
    276: ("Monument", "monument"),
    317: ("Airbase", "airbase"),
    319: ("AnimalNursery", "animal_nursery"),
    323: ("NovaProcCenter", "nova_proc_center"),
    335: ("ShieldGenerator", "shield_generator"),
    487: ("Gate", "gate"),
    562: ("CarbonProcCenter", "carbon_proc_center"),
    584: ("OreProcCenter", "ore_proc_center"),
    598: ("Outpost", "outpost"),
    1576: ("SensorBuoy", "sensor_buoy"),
}

# key: (head) unit id; value: (nyan object name, filename prefix)
AMBIENT_GROUP_LOOKUPS = {
    59: ("BerryBush", "berry_bush"),
    66: ("NovaMine", "nova_mine"),
    102: ("OreMine", "ore_mine"),
    285: ("Holocron", "holocron"),
    348: ("OakTree", "oak_tree"),
    349: ("PalmTree", "palm_tree"),
    350: ("ScrewedTree", "screwed_tree"),
    351: ("LeaflessTree", "leafless_tree"),
    411: ("TimberTree", "timber_tree"),
    413: ("PineTree", "pine_tree"),
    414: ("JungleTree", "jungle_tree"),
    1341: ("CarbonRock", "carbon_rock"),
}

# key: index; value: (nyan object name, filename prefix, units belonging to group, variant type)
VARIANT_GROUP_LOOKUPS = {
    69: ("Shorefish", "shore_fish", (69,), "misc"),
    96: ("Bird", "bird", (96, 816), "misc"),
    264: ("Cliff", "cliff", (264, 265, 266, 267, 268, 269, 270, 271, 272, 273), "angle"),
    450: ("BigOceanFish", "big_ocean_fish", (450, 451), "random"),
    455: ("OceanFish", "ocean_fish", (455, 456, 457, 458), "random"),
}

# key: head unit id; value: (nyan object name, filename prefix)
TECH_GROUP_LOOKUPS = {
    1: ("TechLevel2", "tech_level_2"),
    2: ("TechLevel3", "tech_level_3"),
    3: ("TechLevel4", "tech_level_4"),
    9: ("AWing", "a_wing"),
    33: ("BasicTraining", "basic_training"),
    61: ("HolonetTranceiver", "holonet_traceiver"),
    62: ("BothanSpynet", "bothan_spynet"),
    63: ("ElevationTracking", "elevation_tracking"),
    64: ("LightPlating", "light_plating"),
    65: ("BasicArmor", "basic_armor"),
    66: ("PrimaryFocusingCoils", "primary_focusing_coils"),
    67: ("HeavyArmor", "heavy_armor"),
    68: ("HeavyPlating", "heavy_plating"),
    69: ("TargetingSensors", "targeting_sensors"),
    70: ("EnlargedBombHold", "enlarged_bomb_hold"),
    71: ("FlightSchool", "flight_school"),
    72: ("EfficientManufactering", "efficient_manufacturing"),
    73: ("ShieldModifications", "shield_modifications"),
    74: ("CoolingSleeves", "cooling_sleeves"),
    75: ("ExternalSensorPod", "external_sensor_pod"),
    76: ("AdvancedFlightSchool", "advanced_flight_school"),
    77: ("ArmoredPlates", "armored_plates"),
    78: ("AdvancedEngines", "advanced_engines"),
    79: ("LightArmor", "light_armor"),
    80: ("MediumPlating", "medium_plating"),
    81: ("AdvancedPowerPack", "advanced_power_pack"),
    82: ("Stimulants", "stimulants"),
    83: ("Genetics", "genetics"),
    126: ("SensorBeacon", "sensor_beacon"),
    127: ("Cloning", "cloning"),
    128: ("UpgradedMotivator", "upgraded_motivator"),
    129: ("OptimizedMotivator", "optimized_motivator"),
    130: ("SensorArray", "sensor_array"),
    132: ("FusionExtractor", "fusion_extractor"),
    133: ("SelfRegeneraration", "self_regeneration"),
    134: ("Irrigation", "irrigation"),
    135: ("HarvestingProgram", "harvesting_program"),
    136: ("AdvancedHarvestingProgram", "advanced_harvesting_program"),
    137: ("BattleArmor", "battle_armor"),
    138: ("Taxation", "taxation"),
    139: ("AttackProgramming", "attack_programming"),
    141: ("Presidium", "presidium"),
    143: ("BerserkerJetPacks", "berserker_jet_packs"),
    144: ("StrengthenedFrame", "strengthened_frame"),
    145: ("CreatureTraining", "creature_training"),
    146: ("ReinforcedFrame", "reinforced_frame"),
    147: ("Mechanics", "mechanics"),
    148: ("ForestVision", "forest_vision"),
    149: ("NovaBeamdrillMining", "beamdrill_mining_nova"),
    150: ("HeavyNovaBeamdrill", "heavy_beamdrill_nova"),
    151: ("ForceAgility", "force_agility"),
    152: ("ForceConcentration", "force_concentration"),
    153: ("ForceRegeneration", "force_regeneration"),
    154: ("ForceStrength", "force_strength"),
    155: ("FaithInTheForce", "faith_in_the_force"),
    156: ("ForceInfluence", "force_influence"),
    157: ("ForceStrong", "force_strong"),
    158: ("ForcePerception", "force_perception"),
    159: ("JediMindTrick", "jedi_mind_trick"),
    160: ("HandheldCarbonExtractor", "handheld_carbon_extractor"),
    161: ("EnhancedCarbonExtractor", "enhanced_carbon_extractor"),
    162: ("HeavyCarbonExtractor", "heavy_carbon_extractor"),
    163: ("UpgradedGenerator", "upgraded_generator"),
    164: ("WalkerResearch", "walker_research"),
    166: ("AdvancedGenerator", "advanced_generator"),
    167: ("GunganCreatureArmor", "gungan_creature_armor"),
    168: ("AdvancedRedesign", "advanced_redesign"),
    169: ("WookieIngenuity", "wookie_ingenuity"),
    170: ("Technicians", "technicians"),
    171: ("OreBeamdrillMining", "beamdrill_mining_ore"),
    172: ("HeavyOreBeamdrill", "heavy_beamdrill_ore"),
    173: ("Durasteel", "durasteel"),
    174: ("IonAccelerator", "ion_accelerator"),
    175: ("PowerCalibrator", "power_calibrator"),
    176: ("RotationBearings", "rotation_bearings"),
    177: ("TrackingComputer", "tracking_computer"),
    178: ("HomingSensors", "homing_sensors"),
    179: ("HeavyWeaponsEngineers", "heavy_weapons_engineers"),
    180: ("PermacitePlating", "permacite_plating"),
    183: ("RedesignedSpecs", "redesigned_specs"),
    184: ("AdvancedPropulsion", "advanced_propulsion"),
    185: ("RedoubledEfforts", "redoubled_efforts"),
    186: ("AdvancedScanning", "advanced_scanning"),
    187: ("FasterGrowthChambers", "faster_growth_chambers"),
    188: ("HuttEndorsement", "hutt_endorsement"),
    189: ("NeimoidianEndorsement", "neimoidian_endorsement"),
    190: ("GalacticBanking", "galactic_banking"),
    192: ("InsiderTrading", "insider_trading"),
    193: ("GalacticTradeComission", "galactic_trade_comission"),
    194: ("AlteredBargains", "altered_bargains"),
    195: ("MarketControl", "market_control"),
    197: ("MacroBinoculars", "macro_binoculars"),
    198: ("LighterArmor", "lighter_armor"),
    199: ("PortableScanner", "portable_scanner"),
    201: ("FarSeeInBinoculars", "far_see_in_binoculars"),
    202: ("IncreasedExplosiveYields", "increased_explosive_yields"),
    203: ("IntegratedRangefinder", "integrated_rangefinder"),
    204: ("TougherArmor", "tougher_armor"),
    205: ("Dexterity", "dexterity"),
    206: ("AutomatedProcesses", "automated_processes"),
    500: ("ForceMeditation", "force_meditation"),
    501: ("BactaTanks", "bacta_tanks"),
    535: ("GrenadierTraining", "grenadier_training"),
    568: ("AntiAirRetrofit", "anti_air_retrofit"),
    569: ("StrenghtenedSuperstructure", "streghtened_superstructure"),
    570: ("SuperconductingShields", "superconducting_shields"),
    571: ("EfficientBuildings", "efficient_buildings"),
    572: ("PowerCoreShielding", "power_core_shielding"),
    573: ("StregthenedAssembly", "strengthened_assembly"),
    574: ("GeonosianDiligence", "geonosian_diligence"),
    575: ("ConfederacyAlliance", "confederacy_alliance"),
    576: ("GeonosianEngineers", "geonosian_engineers"),
    577: ("DroidUpgrades", "droid_upgrades"),
    578: ("UpgradedMedicDroids", "upgraded_medic_droids"),
    579: ("KaminoanCloners", "kaminoan_cloners"),
    580: ("GalacticSenateHub", "galactic_senate_hub"),
    581: ("SightBeyondSight", "sight_beyond_sight"),
    582: ("KaminoanRefit", "kaminoan_refit"),
    583: ("AirCruiserBoost", "air_cruiser_boost"),
}

# key: civ index; value: (nyan object name, filename prefix)
CIV_GROUP_LOOKUPS = {
    0: ("Nature", "nature"),
    1: ("Empire", "empire"),
    2: ("Gungans", "gungans"),
    3: ("Rebels", "rebels"),
    4: ("Naboo", "naboo"),
    5: ("Federation", "federation"),
    6: ("Wookiees", "wokiees"),
    7: ("Republic", "republic"),
    8: ("Confederacy", "confederacy"),
}

# key: civ index; value: (civ ids, nyan object name, filename prefix)
GRAPHICS_SET_LOOKUPS = {
    0: ((0, 1), "Empire", "empire"),
    1: ((2,), "Gungan", "gungan"),
    2: ((3,), "Rebel", "rebel"),
    3: ((4,), "Naboo", "naboo"),
    4: ((5,), "Federation", "federate"),
    5: ((6,), "Wookiee", "wookiee"),
    6: ((7,), "Republican", "reppublican"),
    7: ((8,), "Confederate", "confederate"),
}

# key: terrain index; value: (unit terrain restrictions (manual), nyan object name, filename prefix)
# TODO: Use terrain restrictions from .dat
TERRAIN_GROUP_LOOKUPS = {
}

# key: not relevant; value: (terrain indices, unit terrain restrictions (manual), nyan object name)
# TODO: Use terrain restrictions from .dat
TERRAIN_TYPE_LOOKUPS = {
}


CLASS_ID_LOOKUPS = {
    1: "Bantha",
    2: "Fambaa",
    4: "Animal",
    5: "Monster",
    6: "Wall",
    7: "Farm",
    8: "Gate",
    9: "AntiAirTurret",
    10: "LaserTurret",
    11: "Cruiser",
    13: "Destroyer",
    14: "UtilityTrawler",
    15: "Frigate",
    16: "AntiAirDestroyer",
    17: "TransportShip",
    18: "BuildingMisc",
    19: "Doppelganger",
    20: "DeadOrProjectile",     # do not use this as GameEntityType
    21: "HOLDTHIS",             # something from a scenario
    22: "Cliff",
    23: "OceanFish",
    25: "ShoreFish",
    26: "AmbientFlag",
    27: "BerryBush",
    28: "Holocron",
    29: "Nova",
    30: "Ore",
    31: "CarbonTree",
    32: "Artillery",
    33: "AntiAirMobile",
    34: "MobileCannon",
    35: "Pummel",
    36: "Cannon",
    39: "UnderwaterFrigate",
    40: "AntiAirDestroyer",
    42: "EyeCandy",
    43: "Bomber",
    44: "BountyHunter",
    45: "CargoHovercraft",
    46: "ScenarioUnit",                  # should not be present in final modpack
    47: "Scout",
    48: "Fighter",
    49: "GrenadeTrooper",
    50: "Jedi",
    51: "JediWithHolocron",
    52: "Trooper",
    53: "Mech",
    54: "Medic",
    55: "AntiAirTrooper",
    56: "MountedTrooper",
    57: "FambaaShieldGenerator",
    58: "Worker",
    59: "AirTransport",
    60: "Herdable",
    61: "PowerDroid",
    62: "AirCruiser",
    63: "GeonosianWarrior",
    64: "JediStarfighter",
}

# key: genie unit id; value: Gather ability name
GATHER_TASK_LOOKUPS = {
    13: ("Fish", "fish"),  # fishing ship
    56: ("Fish", "fish"),
    57: ("Fish", "fish"),
    120: ("CollectBerries", "collect_berries"),
    354: ("CollectBerries", "collect_berries"),
    122: ("HarvestGame", "harvest_game"),
    216: ("HarvestGame", "harvest_game"),
    123: ("ExtractCarbon", "extract_carbon"),
    218: ("ExtractCarbon", "extract_carbon"),
    124: ("MineOre", "mine_ore"),
    220: ("MineOre", "mine_ore"),
    214: ("FarmCrops", "farm_crops"),
    259: ("FarmCrops", "farm_crops"),
    579: ("MineNova", "mine_nova"),
    581: ("MineNova", "mine_nova"),
    590: ("HarvestLivestock", "harvest_livestock"),
    592: ("HarvestLivestock", "harvest_livestock"),
}

# key: restock target unit id; value: Gather ability name
RESTOCK_TARGET_LOOKUPS = {
    50: ("ReseedFarm", "reseed_farm"),
}

# key: armor class; value: Gather ability name
ARMOR_CLASS_LOOKUPS = {
    0: "AirCraft",
    1: "HeavyAssaultMech",
    2: "HeavyMech",
    3: "Ranged",
    4: "Melee",
    5: "ForceUnit",
    6: "AssaultMachine",
    7: "Decimator",
    8: "Shielded",
    9: "Ship",
    10: "Submarine",
    11: "Building",
    13: "DefenseBuilding",
    14: "Trooper",
    15: "MountedTrooper",
    16: "Cruiser",
    17: "HeavySiege",
    19: "Worker",
    20: "Destroyer",
    21: "StandardBuilding",
    22: "Wall",
    23: "AirCruiser",
    24: "WildAnimal",
    26: "Fortress",
    30: "TameAnimal",
}

# key: command type; value: Apply*Effect ability name
COMMAND_TYPE_LOOKUPS = {
    7: ("Attack", "attack"),
    101: ("Construct", "construct"),
    104: ("Convert", "convert"),
    105: ("Heal", "heal"),
    106: ("Repair", "repair"),
    110: ("Hunt", "hunt"),
}
