Document: openage
Title: Debian openage Manual
Author: <insert document author here>
Abstract: This manual describes what openage is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openage/openage.sgml.gz

Format: postscript
Files: /usr/share/doc/openage/openage.ps.gz

Format: text
Files: /usr/share/doc/openage/openage.text.gz

Format: HTML
Index: /usr/share/doc/openage/html/index.html
Files: /usr/share/doc/openage/html/*.html
