# Copyright 2014-2023 the openage authors. See copying.md for legal info.

"""
Checks the legal headers of all files.
"""

import re

from .util import findfiles, readfile, has_ext, SHEBANG


# The last-modification year is optional; only the creation year is required.
OPENAGE_AUTHORS = (
    "Copyright (?P<crstart>\\d{4})(-(?P<crend>\\d{4}))? the openage authors\\."
)

NATIVELEGALHEADER = re.compile(
    "^"
    # Allow shebang line, followed by an optional empty line.
    "(" + SHEBANG + ")?"

    # Next line must be the copyright line.
    "(#|//) " + OPENAGE_AUTHORS + " See copying\\.md for legal info\\.\n"
)

THIRDPARTYLEGALHEADER = re.compile(
    "^"
    # 3rd-party copyright/license
    "(#|//) This file (was (taken|adapted)|contains (data|code)) from .*\n"
    "(#|//) Copyright \\d{4}-\\d{4} .*\n"
    "(#|//) .*license.*\n"

    # any number of lines containing further 3rd-party copyright info
    "((#|//) .*\\n)*"

    # the openage copyright
    "(#|//) (Modifications|Other (data|code)|Everything else) " +
    OPENAGE_AUTHORS + "\n"
    "(#|//) See copying\\.md for further legal info\\.\n")

# Empty files (consisting of only comments) don't require a legal header.
EMPTYFILE = re.compile("^(((#|//) .*)?\n)*$")

# cython-generated files
CYTHONGENERATED = re.compile("^[^\\n]*(Generated by Cython |failed Cython compilation.)")


# all those files will be checked.
EXTENSIONS_REQUIRING_LEGAL_HEADERS = {
    '.h', '.cpp', '.py', '.pyx', '.pxi', '.cmake', '.h.in',
    '.cpp.in', '.py.in', '.h.template', '.cpp.template',
    '.py.template', '.qml'
}


def match_legalheader(data):
    """
    Tests whether data matches any of the regular expressions,
    and returns a tuple of (matching header regex, match).
    """
    for hdr in (NATIVELEGALHEADER,
                THIRDPARTYLEGALHEADER,
                EMPTYFILE,
                CYTHONGENERATED):

        match = re.match(hdr, data)
        if match is not None:
            return hdr, match

    raise ValueError("no match found")


def test_headers(paths, third_party_files):
    """ Tests all in-sourcefile legal headers. """

    for filename in findfiles(paths, EXTENSIONS_REQUIRING_LEGAL_HEADERS):
        try:
            headertype, _ = match_legalheader(readfile(filename))
        except ValueError:
            yield (
                "Legal header missing or invalid",
                (filename + "\nSee copying.md for a template"),
                None
            )
            continue

        if headertype is THIRDPARTYLEGALHEADER:
            third_party_files.add(filename)


def find_issues(paths):
    """
    Tests all source files for the required legal headers.
    """

    third_party_files = set()

    yield from test_headers(paths, third_party_files)

    # test whether all third-party files are listed in copying.md
    listed_files = set()
    for line in readfile('copying.md').split('\n'):
        match = re.match("^ - `([^`]+)`.*$", line)
        if not match:
            continue

        filename = match.group(1)
        listed_files.add(filename)

    # file listed, but has no 3rd-party header?
    for filename in sorted(listed_files - third_party_files):
        if has_ext(filename, EXTENSIONS_REQUIRING_LEGAL_HEADERS):
            yield (
                "third-party file listing issue",
                (f"{filename}\n\tlisted in copying.md, but has no "
                 "third-party license header."),
                None
            )

    # file has 3rd-party header, but is not listed?
    for filename in sorted(third_party_files - listed_files):
        yield (
            "third-party file listing issue",
            (f"{filename}\n\thas a third-party license header, but isn't "
             "listed in copying.md"),
            None
        )
