FROM ubuntu:24.04

RUN apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get install -y sudo \
    && sudo apt-get update \
    && sudo DEBIAN_FRONTEND="noninteractive" apt-get install -y \
    apt-utils \
    build-essential \
    cmake \
    cython3 \
    flex \
    gcc \
    g++ \
    git \
    libeigen3-dev \
    libepoxy-dev \
    libfontconfig1-dev \
    libfreetype-dev \
    libharfbuzz-dev \
    libogg-dev \
    libopus-dev \
    libopusfile-dev \
    libpng-dev \
    libtoml11-dev \
    make \
    ninja-build \
    python3-dev \
    python3-mako \
    python3-numpy \
    python3-lz4 \
    python3-pil \
    python3-pip \
    python3-pygments \
    python3-toml \
    qml6-module-qtquick-controls \
    qt6-declarative-dev \
    qt6-multimedia-dev \
    qml6-module-qtquick3d-spatialaudio \
    && sudo apt-get clean \
    && truncate -s 0 ~/.bash_history

# At least cython >= 3.0.10 < 4.0.0 is required to avoid runtime errors
# TODO: Remove this line once cython is upgraded in Ubuntu 24.04.3 (expected around August 2025)
RUN pip install "cython>=3.0.10,<4.0.0" --break-system-packages