FROM ubuntu:26.04

RUN apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get install -y sudo \
    && sudo apt-get update \
    && sudo DEBIAN_FRONTEND="noninteractive" apt-get install -y \
    apt-utils \
    build-essential \
    cmake \
    curl \
    cython3 \
    flex \
    gcc \
    g++ \
    git \
    libeigen3-dev \
    libepoxy-dev \
    libfontconfig1-dev \
    libfreetype-dev \
    libharfbuzz-dev \
    libogg-dev \
    libopus-dev \
    libopusfile-dev \
    libpng-dev \
    libtoml11-dev \
    make \
    ninja-build \
    python3-dev \
    python3-mako \
    python3-numpy \
    python3-lz4 \
    python3-pil \
    python3-pip \
    python3-pygments \
    python3-setuptools \
    python3-tomli-w \
    qml6-module-qtquick-controls \
    qt6-declarative-dev \
    qt6-multimedia-dev \
    qml6-module-qtquick3d-spatialaudio \
    && sudo apt-get clean \
    && truncate -s 0 ~/.bash_history

# snapd is unavailable in containers
RUN curl -LsSf https://astral.sh/uv/install.sh | env UV_INSTALL_DIR=/usr/local/bin UV_NO_MODIFY_PATH=1 sh