FROM ubuntu:23.04

RUN apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get install -y sudo \
    && sudo apt-get update \
    && sudo DEBIAN_FRONTEND="noninteractive" apt-get install -y \
    apt-utils \
    build-essential \
    cmake \
    cython3 \
    flex \
    gcc-11 \
    g++-11 \
    git \
    libeigen3-dev \
    libepoxy-dev \
    libfontconfig1-dev \
    libfreetype-dev \
    libharfbuzz-dev \
    libogg-dev \
    libopus-dev \
    libopusfile-dev \
    libpng-dev \
    libsdl2-dev \
    libsdl2-image-dev \
    libtoml11-dev \
    make \
    ninja-build \
    python3-dev \
    python3-mako \
    python3-numpy \
    python3-lz4 \
    python3-pil \
    python3-pip \
    python3-pygments \
    python3-toml \
    qml6-module-qtquick-controls \
    qt6-declarative-dev \
    && sudo apt-get clean \
    && truncate -s 0 ~/.bash_history
